from typing import Any, ClassVar, overload

class HttpParams:
    def setLongParameter(self, p0: str, p1: int) -> "HttpParams": ...
    def setDoubleParameter(self, p0: str, p1: float) -> "HttpParams": ...
    def removeParameter(self, p0: str) -> bool: ...
    def getLongParameter(self, p0: str, p1: int) -> int: ...
    def getBooleanParameter(self, p0: str, p1: bool) -> bool: ...
    def setBooleanParameter(self, p0: str, p1: bool) -> "HttpParams": ...
    def isParameterTrue(self, p0: str) -> bool: ...
    def isParameterFalse(self, p0: str) -> bool: ...
    def setIntParameter(self, p0: str, p1: int) -> "HttpParams": ...
    def getIntParameter(self, p0: str, p1: int) -> int: ...
    def getDoubleParameter(self, p0: str, p1: float) -> float: ...
    def copy(self) -> "HttpParams": ...
    def setParameter(self, p0: str, p1: Any) -> "HttpParams": ...
    def getParameter(self, p0: str) -> Any: ...
