from typing import Any, ClassVar, overload
from android.content.ComponentName import ComponentName
from android.os.Bundle import Bundle
from android.os.Parcel import Parcel

class CredentialOption:
    CREATOR: ClassVar[Any]
    SUPPORTED_ELEMENT_KEYS: ClassVar[str]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    def getCredentialRetrievalData(self) -> Bundle: ...
    def getCandidateQueryData(self) -> Bundle: ...
    def isSystemProviderRequired(self) -> bool: ...
    def getAllowedProviders(self) -> set: ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
    def toString(self) -> str: ...
    def getType(self) -> str: ...

    class Builder:
        def __init__(self, p0: str, p1: Bundle, p2: Bundle) -> None: ...
        def addAllowedProvider(self, p0: ComponentName) -> Any: ...
        def setAllowedProviders(self, p0: set) -> Any: ...
        def setIsSystemProviderRequired(self, p0: bool) -> Any: ...
        def build(self) -> "CredentialOption": ...
