from typing import Any, ClassVar, overload
from android.credentials.CredentialOption import CredentialOption
from android.os.Bundle import Bundle
from android.os.Parcel import Parcel

class GetCredentialRequest:
    CREATOR: ClassVar[Any]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    def alwaysSendAppInfoToProvider(self) -> bool: ...
    def getCredentialOptions(self) -> list: ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
    def getOrigin(self) -> str: ...
    def getData(self) -> Bundle: ...
    def toString(self) -> str: ...

    class Builder:
        def __init__(self, p0: Bundle) -> None: ...
        def setAlwaysSendAppInfoToProvider(self, p0: bool) -> Any: ...
        def setOrigin(self, p0: str) -> Any: ...
        def addCredentialOption(self, p0: CredentialOption) -> Any: ...
        def setCredentialOptions(self, p0: list) -> Any: ...
        def build(self) -> "GetCredentialRequest": ...
