from typing import Any, ClassVar, overload
from android.credentials.CredentialDescription import CredentialDescription
from android.os.Parcel import Parcel

class RegisterCredentialDescriptionRequest:
    CREATOR: ClassVar[Any]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    @overload
    def __init__(self, p0: CredentialDescription) -> None: ...
    @overload
    def __init__(self, p0: set) -> None: ...
    def getCredentialDescriptions(self) -> set: ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
