from typing import Any, ClassVar, overload
from android.content.res.Configuration import Configuration
from android.os.Parcel import Parcel

class ConfigurationStats:
    CREATOR: ClassVar[Any]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    def __init__(self, p0: "ConfigurationStats") -> None: ...
    def getActivationCount(self) -> int: ...
    def getFirstTimeStamp(self) -> int: ...
    def getLastTimeActive(self) -> int: ...
    def getTotalTimeActive(self) -> int: ...
    def getLastTimeStamp(self) -> int: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
    def describeContents(self) -> int: ...
    def getConfiguration(self) -> Configuration: ...
