from typing import Any, ClassVar, overload
from android.content.res.Configuration import Configuration
from android.os.Parcel import Parcel
from android.os.PersistableBundle import PersistableBundle

class UsageEvents:
    CREATOR: ClassVar[Any]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    def hasNextEvent(self) -> bool: ...
    def getNextEvent(self, p0: Any) -> bool: ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...

    class Event:
        ACTIVITY_PAUSED: ClassVar[int]
        ACTIVITY_RESUMED: ClassVar[int]
        ACTIVITY_STOPPED: ClassVar[int]
        CONFIGURATION_CHANGE: ClassVar[int]
        DEVICE_SHUTDOWN: ClassVar[int]
        DEVICE_STARTUP: ClassVar[int]
        FOREGROUND_SERVICE_START: ClassVar[int]
        FOREGROUND_SERVICE_STOP: ClassVar[int]
        KEYGUARD_HIDDEN: ClassVar[int]
        KEYGUARD_SHOWN: ClassVar[int]
        MOVE_TO_BACKGROUND: ClassVar[int]
        MOVE_TO_FOREGROUND: ClassVar[int]
        NONE: ClassVar[int]
        SCREEN_INTERACTIVE: ClassVar[int]
        SCREEN_NON_INTERACTIVE: ClassVar[int]
        SHORTCUT_INVOCATION: ClassVar[int]
        STANDBY_BUCKET_CHANGED: ClassVar[int]
        USER_INTERACTION: ClassVar[int]
        def __init__(self) -> None: ...
        def getTimeStamp(self) -> int: ...
        def getAppStandbyBucket(self) -> int: ...
        def getShortcutId(self) -> str: ...
        def getConfiguration(self) -> Configuration: ...
        def getEventType(self) -> int: ...
        def getExtras(self) -> PersistableBundle: ...
        def getClassName(self) -> str: ...
        def getPackageName(self) -> str: ...
