from typing import Any, ClassVar, overload
from java.time.DayOfWeek import DayOfWeek
from java.time.temporal.TemporalField import TemporalField
from java.time.temporal.TemporalUnit import TemporalUnit
from java.util.Locale import Locale

class WeekFields:
    ISO: ClassVar["WeekFields"]
    SUNDAY_START: ClassVar["WeekFields"]
    WEEK_BASED_YEARS: ClassVar[TemporalUnit]
    def dayOfWeek(self) -> TemporalField: ...
    def equals(self, p0: Any) -> bool: ...
    def toString(self) -> str: ...
    def hashCode(self) -> int: ...
    @overload
    @staticmethod
    def of(p0: Locale) -> "WeekFields": ...
    @overload
    @staticmethod
    def of(p0: DayOfWeek, p1: int) -> "WeekFields": ...
    def weekOfYear(self) -> TemporalField: ...
    def weekOfMonth(self) -> TemporalField: ...
    def weekBasedYear(self) -> TemporalField: ...
    def weekOfWeekBasedYear(self) -> TemporalField: ...
    def getFirstDayOfWeek(self) -> DayOfWeek: ...
    def getMinimalDaysInFirstWeek(self) -> int: ...
