# cython: language_level=3
# Generated by pyjnius-wrap cython — do not edit by hand.
from jni_core._core cimport JavaObject
from jni_core.jni cimport (
    jobject, jstring,
    jboolean, jbyte, jchar, jshort, jint, jlong, jfloat, jdouble,
)

cdef class QuickAccessWalletService(JavaObject):
    cdef void _onWalletCardsRequested(self, jobject p0, jobject p1) except *
    cdef void _onWalletCardSelected(self, jobject p0) except *
    cdef void _onWalletDismissed(self) except *
    cdef void _sendWalletServiceEvent(self, jobject p0) except *
    cdef jobject _getTargetActivityPendingIntent(self) except? NULL
    cdef jobject _onBind(self, jobject p0) except? NULL
