from typing import Any, ClassVar, overload
from android.graphics.Canvas import Canvas
from android.graphics.Outline import Outline
from android.graphics.Paint import Paint
from android.graphics.RectF import RectF
from android.graphics.drawable.shapes.RectShape import RectShape
from android.graphics.drawable.shapes.Shape import Shape

class RoundRectShape:
    def __init__(self, p0: Any, p1: RectF, p2: Any) -> None: ...
    def equals(self, p0: Any) -> bool: ...
    def hashCode(self) -> int: ...
    @overload
    def clone(self) -> Shape: ...
    @overload
    def clone(self) -> Any: ...
    @overload
    def clone(self) -> "RoundRectShape": ...
    @overload
    def clone(self) -> RectShape: ...
    def draw(self, p0: Canvas, p1: Paint) -> None: ...
    def getOutline(self, p0: Outline) -> None: ...
