from typing import Any, ClassVar, overload
from android.graphics.Canvas import Canvas
from android.graphics.Outline import Outline
from android.graphics.Paint import Paint

class Shape:
    def __init__(self) -> None: ...
    def draw(self, p0: Canvas, p1: Paint) -> None: ...
    def getWidth(self) -> float: ...
    def getHeight(self) -> float: ...
    def getOutline(self, p0: Outline) -> None: ...
    def hasAlpha(self) -> bool: ...
    def resize(self, p0: float, p1: float) -> None: ...
    def equals(self, p0: Any) -> bool: ...
    def hashCode(self) -> int: ...
    @overload
    def clone(self) -> "Shape": ...
    @overload
    def clone(self) -> Any: ...
