from typing import Any, ClassVar, overload
from android.net.MacAddress import MacAddress
from android.os.Parcel import Parcel

class MloLink:
    CREATOR: ClassVar[Any]
    INVALID_MLO_LINK_ID: ClassVar[int]
    MLO_LINK_STATE_ACTIVE: ClassVar[int]
    MLO_LINK_STATE_IDLE: ClassVar[int]
    MLO_LINK_STATE_INVALID: ClassVar[int]
    MLO_LINK_STATE_UNASSOCIATED: ClassVar[int]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    def __init__(self) -> None: ...
    def getBand(self) -> int: ...
    def getStaMacAddress(self) -> MacAddress: ...
    def getLinkId(self) -> int: ...
    def getApMacAddress(self) -> MacAddress: ...
    def equals(self, p0: Any) -> bool: ...
    def toString(self) -> str: ...
    def hashCode(self) -> int: ...
    def getState(self) -> int: ...
    def getRssi(self) -> int: ...
    def getChannel(self) -> int: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
    def describeContents(self) -> int: ...
    def getRxLinkSpeedMbps(self) -> int: ...
    def getTxLinkSpeedMbps(self) -> int: ...
