from typing import Any, ClassVar, overload
from android.graphics.Rect import Rect
from android.os.Parcel import Parcel

class VerifiedDisplayHash:
    CREATOR: ClassVar[Any]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    def __init__(self, p0: int, p1: Rect, p2: str, p3: Any) -> None: ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
    def getBoundsInWindow(self) -> Rect: ...
    def getTimeMillis(self) -> int: ...
    def getImageHash(self) -> Any: ...
    def getHashAlgorithm(self) -> str: ...
    def toString(self) -> str: ...
