from typing import Any, ClassVar, overload
from java.io.OutputStream import OutputStream
from javax.crypto.Cipher import Cipher

class CipherOutputStream:
    def __init__(self, p0: OutputStream, p1: Cipher) -> None: ...
    def flush(self) -> None: ...
    def close(self) -> None: ...
    @overload
    def write(self, p0: Any, p1: int, p2: int) -> None: ...
    @overload
    def write(self, p0: Any) -> None: ...
    @overload
    def write(self, p0: int) -> None: ...
