from typing import Any, ClassVar, overload
from java.security.Provider import Provider
from java.security.SecureRandom import SecureRandom
from java.security.spec.AlgorithmParameterSpec import AlgorithmParameterSpec
from javax.crypto.SecretKey import SecretKey

class KeyGenerator:
    def getProvider(self) -> Provider: ...
    @overload
    @staticmethod
    def getInstance(p0: str) -> "KeyGenerator": ...
    @overload
    @staticmethod
    def getInstance(p0: str, p1: str) -> "KeyGenerator": ...
    @overload
    @staticmethod
    def getInstance(p0: str, p1: Provider) -> "KeyGenerator": ...
    @overload
    def init(self, p0: AlgorithmParameterSpec, p1: SecureRandom) -> None: ...
    @overload
    def init(self, p0: int) -> None: ...
    @overload
    def init(self, p0: int, p1: SecureRandom) -> None: ...
    @overload
    def init(self, p0: AlgorithmParameterSpec) -> None: ...
    @overload
    def init(self, p0: SecureRandom) -> None: ...
    def generateKey(self) -> SecretKey: ...
    def getAlgorithm(self) -> str: ...
