from typing import Any, ClassVar, overload
from android.app.slice.Slice import Slice
from android.content.Intent import Intent
from android.net.Uri import Uri

class SliceManager:
    CATEGORY_SLICE: ClassVar[str]
    SLICE_METADATA_KEY: ClassVar[str]
    @overload
    def bindSlice(self, p0: Uri, p1: set) -> Slice: ...
    @overload
    def bindSlice(self, p0: Intent, p1: set) -> Slice: ...
    def checkSlicePermission(self, p0: Uri, p1: int, p2: int) -> int: ...
    def getPinnedSlices(self) -> list: ...
    def getPinnedSpecs(self, p0: Uri) -> set: ...
    def getSliceDescendants(self, p0: Uri) -> list: ...
    def grantSlicePermission(self, p0: str, p1: Uri) -> None: ...
    def mapIntentToUri(self, p0: Intent) -> Uri: ...
    def pinSlice(self, p0: Uri, p1: set) -> None: ...
    def revokeSlicePermission(self, p0: str, p1: Uri) -> None: ...
    def unpinSlice(self, p0: Uri) -> None: ...
