from typing import Any, ClassVar, overload

class DownloadCompletedOutput:
    def getRetainedKeys(self) -> list: ...
    def equals(self, p0: Any) -> bool: ...
    def hashCode(self) -> int: ...

    class Builder:
        def __init__(self) -> None: ...
        def setRetainedKeys(self, p0: list) -> Any: ...
        def addRetainedKey(self, p0: str) -> Any: ...
        def build(self) -> "DownloadCompletedOutput": ...
