from typing import Any, ClassVar, overload
from android.adservices.ondevicepersonalization.RequestLogRecord import RequestLogRecord
from android.content.ContentValues import ContentValues
from android.os.Parcel import Parcel
from java.time.Instant import Instant

class EventLogRecord:
    CREATOR: ClassVar[Any]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    def getRowIndex(self) -> int: ...
    def getRequestLogRecord(self) -> RequestLogRecord: ...
    def equals(self, p0: Any) -> bool: ...
    def hashCode(self) -> int: ...
    def getType(self) -> int: ...
    def getData(self) -> ContentValues: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
    def describeContents(self) -> int: ...
    def getTime(self) -> Instant: ...

    class Builder:
        def __init__(self) -> None: ...
        def setRowIndex(self, p0: int) -> Any: ...
        def setType(self, p0: int) -> Any: ...
        def setData(self, p0: ContentValues) -> Any: ...
        def build(self) -> "EventLogRecord": ...
        def setRequestLogRecord(self, p0: RequestLogRecord) -> Any: ...
