from typing import Any, ClassVar, overload
from android.adservices.ondevicepersonalization.FederatedComputeInput import FederatedComputeInput
from android.adservices.ondevicepersonalization.TrainingInterval import TrainingInterval

class FederatedComputeScheduler:
    def cancel(self, p0: FederatedComputeInput) -> None: ...
    def schedule(self, p0: Any, p1: FederatedComputeInput) -> None: ...

    class Params:
        def __init__(self, p0: TrainingInterval) -> None: ...
        def getTrainingInterval(self) -> TrainingInterval: ...
