from typing import Any, ClassVar, overload
from android.adservices.ondevicepersonalization.InferenceOutput import InferenceOutput
from android.adservices.ondevicepersonalization.KeyValueStore import KeyValueStore

class InferenceInput:
    def equals(self, p0: Any) -> bool: ...
    def hashCode(self) -> int: ...
    def getBatchSize(self) -> int: ...
    def getExpectedOutputStructure(self) -> InferenceOutput: ...
    def getInputData(self) -> Any: ...
    def getParams(self) -> Any: ...

    class Params:
        DELEGATE_CPU: ClassVar[int]
        MODEL_TYPE_TENSORFLOW_LITE: ClassVar[int]
        def equals(self, p0: Any) -> bool: ...
        def hashCode(self) -> int: ...
        def getModelType(self) -> int: ...
        def getKeyValueStore(self) -> KeyValueStore: ...
        def getDelegateType(self) -> int: ...
        def getRecommendedNumThreads(self) -> int: ...
        def getModelKey(self) -> str: ...

        class Builder:
            def __init__(self, p0: KeyValueStore, p1: str) -> None: ...
            def build(self) -> Any: ...
            def setDelegateType(self, p0: int) -> Any: ...
            def setModelType(self, p0: int) -> Any: ...
            def setModelKey(self, p0: str) -> Any: ...
            def setKeyValueStore(self, p0: KeyValueStore) -> Any: ...
            def setRecommendedNumThreads(self, p0: int) -> Any: ...

    class Builder:
        def __init__(self, p0: Any, p1: Any, p2: InferenceOutput) -> None: ...
        def setParams(self, p0: Any) -> Any: ...
        def setBatchSize(self, p0: int) -> Any: ...
        def setExpectedOutputStructure(self, p0: InferenceOutput) -> Any: ...
        def setInputData(self, p0: Any) -> Any: ...
        def build(self) -> "InferenceInput": ...
