from typing import Any, ClassVar, overload
from android.os.PersistableBundle import PersistableBundle

class RenderOutput:
    def getTemplateParams(self) -> PersistableBundle: ...
    def getTemplateId(self) -> str: ...
    def equals(self, p0: Any) -> bool: ...
    def hashCode(self) -> int: ...
    def getContent(self) -> str: ...

    class Builder:
        def __init__(self) -> None: ...
        def setTemplateParams(self, p0: PersistableBundle) -> Any: ...
        def setTemplateId(self, p0: str) -> Any: ...
        def setContent(self, p0: str) -> Any: ...
        def build(self) -> "RenderOutput": ...
