from typing import Any, ClassVar, overload
from android.os.Bundle import Bundle
from android.os.Parcel import Parcel
from android.view.autofill.AutofillId import AutofillId

class FillEventHistory:
    CREATOR: ClassVar[Any]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    def toString(self) -> str: ...
    def getEvents(self) -> list: ...
    def getClientState(self) -> Bundle: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
    def describeContents(self) -> int: ...
    def getSessionId(self) -> int: ...

    class Event:
        NO_SAVE_UI_REASON_DATASET_MATCH: ClassVar[int]
        NO_SAVE_UI_REASON_FIELD_VALIDATION_FAILED: ClassVar[int]
        NO_SAVE_UI_REASON_HAS_EMPTY_REQUIRED: ClassVar[int]
        NO_SAVE_UI_REASON_NONE: ClassVar[int]
        NO_SAVE_UI_REASON_NO_SAVE_INFO: ClassVar[int]
        NO_SAVE_UI_REASON_NO_VALUE_CHANGED: ClassVar[int]
        NO_SAVE_UI_REASON_USING_CREDMAN: ClassVar[int]
        NO_SAVE_UI_REASON_WITH_DELAY_SAVE_FLAG: ClassVar[int]
        TYPE_AUTHENTICATION_SELECTED: ClassVar[int]
        TYPE_CONTEXT_COMMITTED: ClassVar[int]
        TYPE_DATASETS_SHOWN: ClassVar[int]
        TYPE_DATASET_AUTHENTICATION_SELECTED: ClassVar[int]
        TYPE_DATASET_SELECTED: ClassVar[int]
        TYPE_SAVE_SHOWN: ClassVar[int]
        TYPE_VIEW_REQUESTED_AUTOFILL: ClassVar[int]
        UI_TYPE_CREDENTIAL_MANAGER: ClassVar[int]
        UI_TYPE_DIALOG: ClassVar[int]
        UI_TYPE_INLINE: ClassVar[int]
        UI_TYPE_MENU: ClassVar[int]
        UI_TYPE_UNKNOWN: ClassVar[int]
        def getFocusedId(self) -> AutofillId: ...
        def toString(self) -> str: ...
        def getType(self) -> int: ...
        def getClientState(self) -> Bundle: ...
        def getChangedFields(self) -> dict: ...
        def getDatasetId(self) -> str: ...
        def getFieldsClassification(self) -> dict: ...
        def getIgnoredDatasetIds(self) -> set: ...
        def getManuallyEnteredField(self) -> dict: ...
        def getNoSaveUiReason(self) -> int: ...
        def getSelectedDatasetIds(self) -> set: ...
        def getShownDatasetIds(self) -> set: ...
        def getUiType(self) -> int: ...
