from typing import Any, ClassVar, overload
from android.content.IntentSender import IntentSender
from android.os.Parcel import Parcel
from android.service.autofill.CustomDescription import CustomDescription
from android.service.autofill.Sanitizer import Sanitizer
from android.service.autofill.Validator import Validator
from android.view.autofill.AutofillId import AutofillId

class SaveInfo:
    CREATOR: ClassVar[Any]
    FLAG_DELAY_SAVE: ClassVar[int]
    FLAG_DONT_SAVE_ON_FINISH: ClassVar[int]
    FLAG_SAVE_ON_ALL_VIEWS_INVISIBLE: ClassVar[int]
    NEGATIVE_BUTTON_STYLE_CANCEL: ClassVar[int]
    NEGATIVE_BUTTON_STYLE_NEVER: ClassVar[int]
    NEGATIVE_BUTTON_STYLE_REJECT: ClassVar[int]
    POSITIVE_BUTTON_STYLE_CONTINUE: ClassVar[int]
    POSITIVE_BUTTON_STYLE_SAVE: ClassVar[int]
    SAVE_DATA_TYPE_ADDRESS: ClassVar[int]
    SAVE_DATA_TYPE_CREDIT_CARD: ClassVar[int]
    SAVE_DATA_TYPE_DEBIT_CARD: ClassVar[int]
    SAVE_DATA_TYPE_EMAIL_ADDRESS: ClassVar[int]
    SAVE_DATA_TYPE_GENERIC: ClassVar[int]
    SAVE_DATA_TYPE_GENERIC_CARD: ClassVar[int]
    SAVE_DATA_TYPE_PASSWORD: ClassVar[int]
    SAVE_DATA_TYPE_PAYMENT_CARD: ClassVar[int]
    SAVE_DATA_TYPE_USERNAME: ClassVar[int]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    def toString(self) -> str: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
    def describeContents(self) -> int: ...

    class Builder:
        @overload
        def __init__(self, p0: int, p1: Any) -> None: ...
        @overload
        def __init__(self, p0: int) -> None: ...
        def addSanitizer(self, p0: Sanitizer, p1: Any) -> Any: ...
        def setPositiveAction(self, p0: int) -> Any: ...
        def setNegativeAction(self, p0: int, p1: IntentSender) -> Any: ...
        def setCustomDescription(self, p0: CustomDescription) -> Any: ...
        def setOptionalIds(self, p0: Any) -> Any: ...
        def setTriggerId(self, p0: AutofillId) -> Any: ...
        def build(self) -> "SaveInfo": ...
        def setDescription(self, p0: str) -> Any: ...
        def setFlags(self, p0: int) -> Any: ...
        def setValidator(self, p0: Validator) -> Any: ...
