from typing import Any, ClassVar, overload
from android.os.Bundle import Bundle
from android.os.Parcel import Parcel

class UserData:
    CREATOR: ClassVar[Any]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    @staticmethod
    def getMaxUserDataSize() -> int: ...
    def getFieldClassificationAlgorithm(self) -> str: ...
    def getFieldClassificationAlgorithmForCategory(self, p0: str) -> str: ...
    @staticmethod
    def getMaxFieldClassificationIdsSize() -> int: ...
    @staticmethod
    def getMaxCategoryCount() -> int: ...
    @staticmethod
    def getMinValueLength() -> int: ...
    @staticmethod
    def getMaxValueLength() -> int: ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
    def toString(self) -> str: ...
    def getId(self) -> str: ...

    class Builder:
        def __init__(self, p0: str, p1: str, p2: str) -> None: ...
        def setFieldClassificationAlgorithmForCategory(self, p0: str, p1: str, p2: Bundle) -> Any: ...
        def setFieldClassificationAlgorithm(self, p0: str, p1: Bundle) -> Any: ...
        def build(self) -> "UserData": ...
        def add(self, p0: str, p1: str) -> Any: ...
