from typing import Any, ClassVar, overload
from android.os.Parcel import Parcel
from android.service.autofill.BatchUpdates import BatchUpdates
from android.service.autofill.OnClickAction import OnClickAction
from android.service.autofill.Transformation import Transformation
from android.service.autofill.Validator import Validator
from android.widget.RemoteViews import RemoteViews

class CustomDescription:
    CREATOR: ClassVar[Any]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    def toString(self) -> str: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
    def describeContents(self) -> int: ...

    class Builder:
        def __init__(self, p0: RemoteViews) -> None: ...
        def addChild(self, p0: int, p1: Transformation) -> Any: ...
        def build(self) -> "CustomDescription": ...
        def addOnClickAction(self, p0: int, p1: OnClickAction) -> Any: ...
        def batchUpdate(self, p0: Validator, p1: BatchUpdates) -> Any: ...
