from typing import Any, ClassVar, overload
from android.service.autofill.InlinePresentation import InlinePresentation
from android.widget.RemoteViews import RemoteViews

class Presentations:
    def getInlinePresentation(self) -> InlinePresentation: ...
    def getInlineTooltipPresentation(self) -> InlinePresentation: ...
    def getMenuPresentation(self) -> RemoteViews: ...
    def getDialogPresentation(self) -> RemoteViews: ...

    class Builder:
        def __init__(self) -> None: ...
        def setInlinePresentation(self, p0: InlinePresentation) -> Any: ...
        def setDialogPresentation(self, p0: RemoteViews) -> Any: ...
        def setInlineTooltipPresentation(self, p0: InlinePresentation) -> Any: ...
        def setMenuPresentation(self, p0: RemoteViews) -> Any: ...
        def build(self) -> "Presentations": ...
