from typing import Any, ClassVar, overload
from java.io.InputStream import InputStream
from java.io.OutputStream import OutputStream
from java.nio.Buffer import Buffer
from java.nio.ByteBuffer import ByteBuffer

class ETC1Util:
    def __init__(self) -> None: ...
    @overload
    @staticmethod
    def loadTexture(p0: int, p1: int, p2: int, p3: int, p4: int, p5: Any) -> None: ...
    @overload
    @staticmethod
    def loadTexture(p0: int, p1: int, p2: int, p3: int, p4: int, p5: InputStream) -> None: ...
    @staticmethod
    def isETC1Supported() -> bool: ...
    @staticmethod
    def createTexture(p0: InputStream) -> Any: ...
    @staticmethod
    def compressTexture(p0: Buffer, p1: int, p2: int, p3: int, p4: int) -> Any: ...
    @staticmethod
    def writeTexture(p0: Any, p1: OutputStream) -> None: ...

    class ETC1Texture:
        def __init__(self, p0: int, p1: int, p2: ByteBuffer) -> None: ...
        def getWidth(self) -> int: ...
        def getHeight(self) -> int: ...
        def getData(self) -> ByteBuffer: ...
