from typing import Any, ClassVar, overload
from android.os.Bundle import Bundle
from android.os.Parcel import Parcel

class CreateCredentialRequest:
    CREATOR: ClassVar[Any]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    def getCredentialData(self) -> Bundle: ...
    def alwaysSendAppInfoToProvider(self) -> bool: ...
    def toString(self) -> str: ...
    def getType(self) -> str: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
    def describeContents(self) -> int: ...
    def getOrigin(self) -> str: ...
    def getCandidateQueryData(self) -> Bundle: ...
    def isSystemProviderRequired(self) -> bool: ...

    class Builder:
        def __init__(self, p0: str, p1: Bundle, p2: Bundle) -> None: ...
        def setAlwaysSendAppInfoToProvider(self, p0: bool) -> Any: ...
        def build(self) -> "CreateCredentialRequest": ...
        def setIsSystemProviderRequired(self, p0: bool) -> Any: ...
        def setOrigin(self, p0: str) -> Any: ...
