from typing import Any, ClassVar, overload
from java.nio.channels.spi.SelectorProvider import SelectorProvider

class AbstractSelector:
    def isOpen(self) -> bool: ...
    def close(self) -> None: ...
    def provider(self) -> SelectorProvider: ...
