from typing import Any, ClassVar, overload
from org.w3c.dom.DOMConfiguration import DOMConfiguration
from org.w3c.dom.Document import Document
from org.w3c.dom.Node import Node
from org.w3c.dom.ls.LSInput import LSInput
from org.w3c.dom.ls.LSParserFilter import LSParserFilter

class LSParser:
    ACTION_APPEND_AS_CHILDREN: ClassVar[int]
    ACTION_REPLACE_CHILDREN: ClassVar[int]
    ACTION_INSERT_BEFORE: ClassVar[int]
    ACTION_INSERT_AFTER: ClassVar[int]
    ACTION_REPLACE: ClassVar[int]
    def abort(self) -> None: ...
    def parse(self, p0: LSInput) -> Document: ...
    def setFilter(self, p0: LSParserFilter) -> None: ...
    def getFilter(self) -> LSParserFilter: ...
    def getDomConfig(self) -> DOMConfiguration: ...
    def getAsync(self) -> bool: ...
    def getBusy(self) -> bool: ...
    def parseURI(self, p0: str) -> Document: ...
    def parseWithContext(self, p0: LSInput, p1: Node, p2: int) -> Node: ...
