from typing import Any, ClassVar, overload
from android.health.connect.datatypes.DataOrigin import DataOrigin
from android.os.Parcel import Parcel

class ChangeLogTokenRequest:
    CREATOR: ClassVar[Any]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    def describeContents(self) -> int: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
    def getDataOriginFilters(self) -> set: ...
    def getRecordTypes(self) -> set: ...

    class Builder:
        def __init__(self) -> None: ...
        def addDataOriginFilter(self, p0: DataOrigin) -> Any: ...
        def addRecordType(self, p0: type) -> Any: ...
        def build(self) -> "ChangeLogTokenRequest": ...
