from jnius import JavaClass, MetaJavaClass, JavaMethod, JavaStaticMethod, JavaMultipleMethod, JavaField, JavaStaticField

__all__ = ["SmsMessage"]

class SmsMessage(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "android/telephony/gsm/SmsMessage"
    __javaconstructor__ = [("()V", False)]
    ENCODING_16BIT = JavaStaticField("I")
    ENCODING_7BIT = JavaStaticField("I")
    ENCODING_8BIT = JavaStaticField("I")
    ENCODING_UNKNOWN = JavaStaticField("I")
    MAX_USER_DATA_BYTES = JavaStaticField("I")
    MAX_USER_DATA_SEPTETS = JavaStaticField("I")
    MAX_USER_DATA_SEPTETS_WITH_HEADER = JavaStaticField("I")
    getStatus = JavaMethod("()I")
    createFromPdu = JavaStaticMethod("([B)Landroid/telephony/gsm/SmsMessage;")
    calculateLength = JavaMultipleMethod([("(Ljava/lang/CharSequence;Z)[I", True, False), ("(Ljava/lang/String;Z)[I", True, False)])
    getDisplayMessageBody = JavaMethod("()Ljava/lang/String;")
    getDisplayOriginatingAddress = JavaMethod("()Ljava/lang/String;")
    getEmailBody = JavaMethod("()Ljava/lang/String;")
    getEmailFrom = JavaMethod("()Ljava/lang/String;")
    getIndexOnSim = JavaMethod("()I")
    getMessageBody = JavaMethod("()Ljava/lang/String;")
    getMessageClass = JavaMethod("()Landroid/telephony/gsm/SmsMessage$MessageClass;")
    getOriginatingAddress = JavaMethod("()Ljava/lang/String;")
    getPdu = JavaMethod("()[B")
    getProtocolIdentifier = JavaMethod("()I")
    getPseudoSubject = JavaMethod("()Ljava/lang/String;")
    getServiceCenterAddress = JavaMethod("()Ljava/lang/String;")
    getStatusOnSim = JavaMethod("()I")
    getSubmitPdu = JavaMultipleMethod([("(Ljava/lang/String;Ljava/lang/String;S[BZ)Landroid/telephony/gsm/SmsMessage$SubmitPdu;", True, False), ("(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Z)Landroid/telephony/gsm/SmsMessage$SubmitPdu;", True, False)])
    getTPLayerLengthForPDU = JavaStaticMethod("(Ljava/lang/String;)I")
    getUserData = JavaMethod("()[B")
    isCphsMwiMessage = JavaMethod("()Z")
    isEmail = JavaMethod("()Z")
    isMWIClearMessage = JavaMethod("()Z")
    isMWISetMessage = JavaMethod("()Z")
    isMwiDontStore = JavaMethod("()Z")
    isReplace = JavaMethod("()Z")
    isReplyPathPresent = JavaMethod("()Z")
    isStatusReportMessage = JavaMethod("()Z")
    getTimestampMillis = JavaMethod("()J")

    class SubmitPdu(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "android/telephony/gsm/SmsMessage$SubmitPdu"
        __javaconstructor__ = [("()V", False)]
        encodedMessage = JavaField("[B")
        encodedScAddress = JavaField("[B")
        toString = JavaMethod("()Ljava/lang/String;")

    class MessageClass(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "android/telephony/gsm/SmsMessage$MessageClass"
        CLASS_0 = JavaStaticField("Landroid/telephony/gsm/SmsMessage$MessageClass;")
        CLASS_1 = JavaStaticField("Landroid/telephony/gsm/SmsMessage$MessageClass;")
        CLASS_2 = JavaStaticField("Landroid/telephony/gsm/SmsMessage$MessageClass;")
        CLASS_3 = JavaStaticField("Landroid/telephony/gsm/SmsMessage$MessageClass;")
        UNKNOWN = JavaStaticField("Landroid/telephony/gsm/SmsMessage$MessageClass;")
        values = JavaStaticMethod("()[Landroid/telephony/gsm/SmsMessage$MessageClass;")
        valueOf = JavaStaticMethod("(Ljava/lang/String;)Landroid/telephony/gsm/SmsMessage$MessageClass;")
        CLASS_0 = JavaStaticField("Landroid/telephony/gsm/SmsMessage$MessageClass;")
        CLASS_1 = JavaStaticField("Landroid/telephony/gsm/SmsMessage$MessageClass;")
        CLASS_2 = JavaStaticField("Landroid/telephony/gsm/SmsMessage$MessageClass;")
        CLASS_3 = JavaStaticField("Landroid/telephony/gsm/SmsMessage$MessageClass;")
        UNKNOWN = JavaStaticField("Landroid/telephony/gsm/SmsMessage$MessageClass;")