from typing import Any, ClassVar, overload
from java.sql.Array import Array
from java.sql.Blob import Blob
from java.sql.CallableStatement import CallableStatement
from java.sql.Clob import Clob
from java.sql.DatabaseMetaData import DatabaseMetaData
from java.sql.NClob import NClob
from java.sql.PreparedStatement import PreparedStatement
from java.sql.SQLWarning import SQLWarning
from java.sql.SQLXML import SQLXML
from java.sql.Savepoint import Savepoint
from java.sql.Statement import Statement
from java.sql.Struct import Struct
from java.util.Properties import Properties
from java.util.concurrent.Executor import Executor

# Forward declarations for Java types we do not wrap.
# Bound as empty classes so annotations resolve in the IDE.
class ShardingKey:
    """Forward declaration for ``java.sql.ShardingKey``.

    This Java type is referenced by the wrapper but is not itself
    wrapped by pyjnius-wrap. At runtime pyjnius will hand you a
    live ``autoclass('java.sql.ShardingKey')`` proxy; this empty class exists
    purely so static type checkers and IDEs can resolve the name.

    See: https://docs.oracle.com/javase/8/docs/api/java/sql/ShardingKey.html
    """
    ...

class Connection:
    TRANSACTION_NONE: ClassVar[int]
    TRANSACTION_READ_UNCOMMITTED: ClassVar[int]
    TRANSACTION_READ_COMMITTED: ClassVar[int]
    TRANSACTION_REPEATABLE_READ: ClassVar[int]
    TRANSACTION_SERIALIZABLE: ClassVar[int]
    def getWarnings(self) -> SQLWarning: ...
    def clearWarnings(self) -> None: ...
    def getMetaData(self) -> DatabaseMetaData: ...
    @overload
    def prepareCall(self, p0: str, p1: int, p2: int, p3: int) -> CallableStatement: ...
    @overload
    def prepareCall(self, p0: str, p1: int, p2: int) -> CallableStatement: ...
    @overload
    def prepareCall(self, p0: str) -> CallableStatement: ...
    @overload
    def createStatement(self, p0: int, p1: int) -> Statement: ...
    @overload
    def createStatement(self, p0: int, p1: int, p2: int) -> Statement: ...
    @overload
    def createStatement(self) -> Statement: ...
    @overload
    def prepareStatement(self, p0: str, p1: int, p2: int, p3: int) -> PreparedStatement: ...
    @overload
    def prepareStatement(self, p0: str) -> PreparedStatement: ...
    @overload
    def prepareStatement(self, p0: str, p1: int, p2: int) -> PreparedStatement: ...
    @overload
    def prepareStatement(self, p0: str, p1: Any) -> PreparedStatement: ...
    @overload
    def prepareStatement(self, p0: str, p1: int) -> PreparedStatement: ...
    @overload
    def prepareStatement(self, p0: str, p1: Any) -> PreparedStatement: ...
    def nativeSQL(self, p0: str) -> str: ...
    def setAutoCommit(self, p0: bool) -> None: ...
    def getAutoCommit(self) -> bool: ...
    @overload
    def rollback(self) -> None: ...
    @overload
    def rollback(self, p0: Savepoint) -> None: ...
    def setCatalog(self, p0: str) -> None: ...
    def getCatalog(self) -> str: ...
    def setTransactionIsolation(self, p0: int) -> None: ...
    def getTransactionIsolation(self) -> int: ...
    def getTypeMap(self) -> dict: ...
    def setTypeMap(self, p0: dict) -> None: ...
    def setHoldability(self, p0: int) -> None: ...
    def getHoldability(self) -> int: ...
    @overload
    def setSavepoint(self, p0: str) -> Savepoint: ...
    @overload
    def setSavepoint(self) -> Savepoint: ...
    def releaseSavepoint(self, p0: Savepoint) -> None: ...
    def createClob(self) -> Clob: ...
    def createBlob(self) -> Blob: ...
    def createNClob(self) -> NClob: ...
    def createSQLXML(self) -> SQLXML: ...
    @overload
    def setClientInfo(self, p0: str, p1: str) -> None: ...
    @overload
    def setClientInfo(self, p0: Properties) -> None: ...
    @overload
    def getClientInfo(self) -> Properties: ...
    @overload
    def getClientInfo(self, p0: str) -> str: ...
    def createArrayOf(self, p0: str, p1: Any) -> Array: ...
    def createStruct(self, p0: str, p1: Any) -> Struct: ...
    def setNetworkTimeout(self, p0: Executor, p1: int) -> None: ...
    def getNetworkTimeout(self) -> int: ...
    def beginRequest(self) -> None: ...
    def endRequest(self) -> None: ...
    @overload
    def setShardingKeyIfValid(self, p0: ShardingKey, p1: ShardingKey, p2: int) -> bool: ...
    @overload
    def setShardingKeyIfValid(self, p0: ShardingKey, p1: int) -> bool: ...
    @overload
    def setShardingKey(self, p0: ShardingKey) -> None: ...
    @overload
    def setShardingKey(self, p0: ShardingKey, p1: ShardingKey) -> None: ...
    def abort(self, p0: Executor) -> None: ...
    def setSchema(self, p0: str) -> None: ...
    def getSchema(self) -> str: ...
    def isClosed(self) -> bool: ...
    def isValid(self, p0: int) -> bool: ...
    def isReadOnly(self) -> bool: ...
    def commit(self) -> None: ...
    def setReadOnly(self, p0: bool) -> None: ...
    def close(self) -> None: ...
