from typing import Any, ClassVar, overload

class ResultSetMetaData:
    columnNoNulls: ClassVar[int]
    columnNullable: ClassVar[int]
    columnNullableUnknown: ClassVar[int]
    def getTableName(self, p0: int) -> str: ...
    def isAutoIncrement(self, p0: int) -> bool: ...
    def isCaseSensitive(self, p0: int) -> bool: ...
    def isSearchable(self, p0: int) -> bool: ...
    def isCurrency(self, p0: int) -> bool: ...
    def isNullable(self, p0: int) -> int: ...
    def getColumnDisplaySize(self, p0: int) -> int: ...
    def getColumnLabel(self, p0: int) -> str: ...
    def getCatalogName(self, p0: int) -> str: ...
    def getColumnTypeName(self, p0: int) -> str: ...
    def isDefinitelyWritable(self, p0: int) -> bool: ...
    def getColumnClassName(self, p0: int) -> str: ...
    def getSchemaName(self, p0: int) -> str: ...
    def getColumnType(self, p0: int) -> int: ...
    def isWritable(self, p0: int) -> bool: ...
    def getColumnName(self, p0: int) -> str: ...
    def getColumnCount(self) -> int: ...
    def getScale(self, p0: int) -> int: ...
    def getPrecision(self, p0: int) -> int: ...
    def isSigned(self, p0: int) -> bool: ...
    def isReadOnly(self, p0: int) -> bool: ...
