from typing import Any, ClassVar, overload
from java.util.Comparator import Comparator
from java.util.function.BiFunction import BiFunction
from java.util.function.BinaryOperator import BinaryOperator
from java.util.function.Function import Function
from java.util.function.Predicate import Predicate
from java.util.function.Supplier import Supplier
from java.util.function.ToDoubleFunction import ToDoubleFunction
from java.util.function.ToIntFunction import ToIntFunction
from java.util.function.ToLongFunction import ToLongFunction
from java.util.stream.Collector import Collector

class Collectors:
    @overload
    @staticmethod
    def joining(p0: str) -> Collector: ...
    @overload
    @staticmethod
    def joining() -> Collector: ...
    @overload
    @staticmethod
    def joining(p0: str, p1: str, p2: str) -> Collector: ...
    @staticmethod
    def toList() -> Collector: ...
    @overload
    @staticmethod
    def toMap(p0: Function, p1: Function, p2: BinaryOperator, p3: Supplier) -> Collector: ...
    @overload
    @staticmethod
    def toMap(p0: Function, p1: Function) -> Collector: ...
    @overload
    @staticmethod
    def toMap(p0: Function, p1: Function, p2: BinaryOperator) -> Collector: ...
    @staticmethod
    def toSet() -> Collector: ...
    @overload
    @staticmethod
    def groupingBy(p0: Function) -> Collector: ...
    @overload
    @staticmethod
    def groupingBy(p0: Function, p1: Collector) -> Collector: ...
    @overload
    @staticmethod
    def groupingBy(p0: Function, p1: Supplier, p2: Collector) -> Collector: ...
    @staticmethod
    def mapping(p0: Function, p1: Collector) -> Collector: ...
    @overload
    @staticmethod
    def toUnmodifiableMap(p0: Function, p1: Function) -> Collector: ...
    @overload
    @staticmethod
    def toUnmodifiableMap(p0: Function, p1: Function, p2: BinaryOperator) -> Collector: ...
    @staticmethod
    def summarizingInt(p0: ToIntFunction) -> Collector: ...
    @staticmethod
    def summarizingLong(p0: ToLongFunction) -> Collector: ...
    @staticmethod
    def summarizingDouble(p0: ToDoubleFunction) -> Collector: ...
    @staticmethod
    def teeing(p0: Collector, p1: Collector, p2: BiFunction) -> Collector: ...
    @staticmethod
    def minBy(p0: Comparator) -> Collector: ...
    @staticmethod
    def maxBy(p0: Comparator) -> Collector: ...
    @staticmethod
    def summingLong(p0: ToLongFunction) -> Collector: ...
    @overload
    @staticmethod
    def reducing(p0: BinaryOperator) -> Collector: ...
    @overload
    @staticmethod
    def reducing(p0: Any, p1: BinaryOperator) -> Collector: ...
    @overload
    @staticmethod
    def reducing(p0: Any, p1: Function, p2: BinaryOperator) -> Collector: ...
    @overload
    @staticmethod
    def groupingByConcurrent(p0: Function, p1: Supplier, p2: Collector) -> Collector: ...
    @overload
    @staticmethod
    def groupingByConcurrent(p0: Function, p1: Collector) -> Collector: ...
    @overload
    @staticmethod
    def groupingByConcurrent(p0: Function) -> Collector: ...
    @overload
    @staticmethod
    def partitioningBy(p0: Predicate, p1: Collector) -> Collector: ...
    @overload
    @staticmethod
    def partitioningBy(p0: Predicate) -> Collector: ...
    @staticmethod
    def collectingAndThen(p0: Collector, p1: Function) -> Collector: ...
    @overload
    @staticmethod
    def toConcurrentMap(p0: Function, p1: Function, p2: BinaryOperator) -> Collector: ...
    @overload
    @staticmethod
    def toConcurrentMap(p0: Function, p1: Function) -> Collector: ...
    @overload
    @staticmethod
    def toConcurrentMap(p0: Function, p1: Function, p2: BinaryOperator, p3: Supplier) -> Collector: ...
    @staticmethod
    def toCollection(p0: Supplier) -> Collector: ...
    @staticmethod
    def toUnmodifiableList() -> Collector: ...
    @staticmethod
    def toUnmodifiableSet() -> Collector: ...
    @staticmethod
    def flatMapping(p0: Function, p1: Collector) -> Collector: ...
    @staticmethod
    def filtering(p0: Predicate, p1: Collector) -> Collector: ...
    @staticmethod
    def counting() -> Collector: ...
    @staticmethod
    def summingInt(p0: ToIntFunction) -> Collector: ...
    @staticmethod
    def summingDouble(p0: ToDoubleFunction) -> Collector: ...
    @staticmethod
    def averagingInt(p0: ToIntFunction) -> Collector: ...
    @staticmethod
    def averagingLong(p0: ToLongFunction) -> Collector: ...
    @staticmethod
    def averagingDouble(p0: ToDoubleFunction) -> Collector: ...
