from typing import Any, ClassVar, overload
from android.os.Parcel import Parcel
from android.ranging.raw.RawRangingDevice import RawRangingDevice

class RawInitiatorRangingConfig:
    CREATOR: ClassVar[Any]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    RANGING_SESSION_OOB: ClassVar[int]
    RANGING_SESSION_RAW: ClassVar[int]
    def getRawRangingDevices(self) -> list: ...
    def toString(self) -> str: ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...

    class Builder:
        def __init__(self) -> None: ...
        def addRawRangingDevice(self, p0: RawRangingDevice) -> Any: ...
        def addRawRangingDevices(self, p0: list) -> Any: ...
        def build(self) -> "RawInitiatorRangingConfig": ...

from typing import Any, ClassVar, overload
from android.os.Parcel import Parcel
from android.ranging.RangingDevice import RangingDevice
from android.ranging.ble.cs.BleCsRangingParams import BleCsRangingParams
from android.ranging.ble.rssi.BleRssiRangingParams import BleRssiRangingParams
from android.ranging.uwb.UwbRangingParams import UwbRangingParams
from android.ranging.wifi.rtt.RttRangingParams import RttRangingParams

class RawRangingDevice:
    CREATOR: ClassVar[Any]
    UPDATE_RATE_FREQUENT: ClassVar[int]
    UPDATE_RATE_INFREQUENT: ClassVar[int]
    UPDATE_RATE_NORMAL: ClassVar[int]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    def getBleRssiRangingParams(self) -> BleRssiRangingParams: ...
    def getCsRangingParams(self) -> BleCsRangingParams: ...
    def getRttRangingParams(self) -> RttRangingParams: ...
    def getUwbRangingParams(self) -> UwbRangingParams: ...
    def toString(self) -> str: ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
    def getRangingDevice(self) -> RangingDevice: ...

    class Builder:
        def __init__(self) -> None: ...
        def setBleRssiRangingParams(self, p0: BleRssiRangingParams) -> Any: ...
        def setCsRangingParams(self, p0: BleCsRangingParams) -> Any: ...
        def setRangingDevice(self, p0: RangingDevice) -> Any: ...
        def setRttRangingParams(self, p0: RttRangingParams) -> Any: ...
        def setUwbRangingParams(self, p0: UwbRangingParams) -> Any: ...
        def build(self) -> "RawRangingDevice": ...

from typing import Any, ClassVar, overload
from android.os.Parcel import Parcel
from android.ranging.raw.RawRangingDevice import RawRangingDevice

class RawResponderRangingConfig:
    CREATOR: ClassVar[Any]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    RANGING_SESSION_OOB: ClassVar[int]
    RANGING_SESSION_RAW: ClassVar[int]
    def getRawRangingDevice(self) -> RawRangingDevice: ...
    def toString(self) -> str: ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...

    class Builder:
        def __init__(self) -> None: ...
        def build(self) -> "RawResponderRangingConfig": ...
        def setRawRangingDevice(self, p0: RawRangingDevice) -> Any: ...

