from typing import Any, ClassVar, overload
from android.os.Bundle import Bundle
from android.os.LocaleList import LocaleList
from android.os.Parcel import Parcel
from android.widget.inline.InlinePresentationSpec import InlinePresentationSpec

class InlineSuggestionsRequest:
    CREATOR: ClassVar[Any]
    SUGGESTION_COUNT_UNLIMITED: ClassVar[int]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    def getMaxSuggestionCount(self) -> int: ...
    def getInlinePresentationSpecs(self) -> list: ...
    def getHostPackageName(self) -> str: ...
    def getSupportedLocales(self) -> LocaleList: ...
    def getInlineTooltipPresentationSpec(self) -> InlinePresentationSpec: ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
    def getExtras(self) -> Bundle: ...
    def equals(self, p0: Any) -> bool: ...
    def toString(self) -> str: ...
    def hashCode(self) -> int: ...

    class Builder:
        def __init__(self, p0: list) -> None: ...
        def setExtras(self, p0: Bundle) -> Any: ...
        def setMaxSuggestionCount(self, p0: int) -> Any: ...
        def setInlinePresentationSpecs(self, p0: list) -> Any: ...
        def addInlinePresentationSpecs(self, p0: InlinePresentationSpec) -> Any: ...
        def setSupportedLocales(self, p0: LocaleList) -> Any: ...
        def setInlineTooltipPresentationSpec(self, p0: InlinePresentationSpec) -> Any: ...
        def build(self) -> "InlineSuggestionsRequest": ...
