from typing import Any, ClassVar, overload
from android.graphics.PointF import PointF
from android.os.Parcel import Parcel

class RemoveSpaceGesture:
    CREATOR: ClassVar[Any]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    GRANULARITY_CHARACTER: ClassVar[int]
    GRANULARITY_WORD: ClassVar[int]
    def getStartPoint(self) -> PointF: ...
    def getEndPoint(self) -> PointF: ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
    def equals(self, p0: Any) -> bool: ...
    def hashCode(self) -> int: ...

    class Builder:
        def __init__(self) -> None: ...
        def setFallbackText(self, p0: str) -> Any: ...
        def setPoints(self, p0: PointF, p1: PointF) -> Any: ...
        def build(self) -> "RemoveSpaceGesture": ...
