# cython: language_level=3
# Generated by pyjnius-wrap cython — do not edit by hand.
from jni_core._core cimport JavaObject

cdef class WifiManager(JavaObject):
    pass

cdef class WpsCallback(JavaObject):
    pass

cdef class WifiLock(JavaObject):
    pass

cdef class SuggestionUserApprovalStatusListener(JavaObject):
    pass

cdef class SuggestionConnectionStatusListener(JavaObject):
    pass

cdef class SubsystemRestartTrackingCallback(JavaObject):
    pass

cdef class ScanResultsCallback(JavaObject):
    pass

cdef class MulticastLock(JavaObject):
    pass

cdef class LocalOnlyHotspotReservation(JavaObject):
    pass

cdef class LocalOnlyHotspotCallback(JavaObject):
    pass

cdef class LocalOnlyConnectionFailureListener(JavaObject):
    pass

cdef class InterfaceCreationImpact(JavaObject):
    pass

cdef class AddNetworkResult(JavaObject):
    pass
