from typing import Any, ClassVar, overload
from android.adservices.common.AdSelectionSignals import AdSelectionSignals
from android.adservices.common.AdTechIdentifier import AdTechIdentifier
from android.adservices.customaudience.TrustedBiddingData import TrustedBiddingData
from android.net.Uri import Uri
from android.os.Parcel import Parcel
from java.time.Instant import Instant

class CustomAudience:
    CREATOR: ClassVar[Any]
    FLAG_AUCTION_SERVER_REQUEST_OMIT_ADS: ClassVar[int]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    def getActivationTime(self) -> Instant: ...
    def getExpirationTime(self) -> Instant: ...
    def getUserBiddingSignals(self) -> AdSelectionSignals: ...
    def getBuyer(self) -> AdTechIdentifier: ...
    def getAds(self) -> list: ...
    def getDailyUpdateUri(self) -> Uri: ...
    def getAuctionServerRequestFlags(self) -> int: ...
    def getTrustedBiddingData(self) -> TrustedBiddingData: ...
    def getBiddingLogicUri(self) -> Uri: ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
    def getName(self) -> str: ...
    def equals(self, p0: Any) -> bool: ...
    def toString(self) -> str: ...
    def hashCode(self) -> int: ...

    class Builder:
        def __init__(self) -> None: ...
        def setBuyer(self, p0: AdTechIdentifier) -> Any: ...
        def setActivationTime(self, p0: Instant) -> Any: ...
        def setExpirationTime(self, p0: Instant) -> Any: ...
        def setUserBiddingSignals(self, p0: AdSelectionSignals) -> Any: ...
        def setDailyUpdateUri(self, p0: Uri) -> Any: ...
        def setAds(self, p0: list) -> Any: ...
        def setAuctionServerRequestFlags(self, p0: int) -> Any: ...
        def setTrustedBiddingData(self, p0: TrustedBiddingData) -> Any: ...
        def setBiddingLogicUri(self, p0: Uri) -> Any: ...
        def build(self) -> "CustomAudience": ...
        def setName(self, p0: str) -> Any: ...
