from typing import Any, ClassVar, overload
from android.net.Uri import Uri
from java.time.Duration import Duration

class ScheduleCustomAudienceUpdateRequest:
    def getUpdateUri(self) -> Uri: ...
    def getPartialCustomAudienceList(self) -> list: ...
    def getMinDelay(self) -> Duration: ...
    def equals(self, p0: Any) -> bool: ...
    def toString(self) -> str: ...
    def hashCode(self) -> int: ...

    class Builder:
        def __init__(self, p0: Uri, p1: Duration, p2: list) -> None: ...
        def setUpdateUri(self, p0: Uri) -> Any: ...
        def setMinDelay(self, p0: Duration) -> Any: ...
        def setPartialCustomAudienceList(self, p0: list) -> Any: ...
        def build(self) -> "ScheduleCustomAudienceUpdateRequest": ...
