from typing import Any, ClassVar, overload
from android.net.Uri import Uri
from android.os.Parcel import Parcel

class TrustedBiddingData:
    CREATOR: ClassVar[Any]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    def getTrustedBiddingKeys(self) -> list: ...
    def getTrustedBiddingUri(self) -> Uri: ...
    def equals(self, p0: Any) -> bool: ...
    def hashCode(self) -> int: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
    def describeContents(self) -> int: ...

    class Builder:
        def __init__(self) -> None: ...
        def setTrustedBiddingKeys(self, p0: list) -> Any: ...
        def setTrustedBiddingUri(self, p0: Uri) -> Any: ...
        def build(self) -> "TrustedBiddingData": ...
