from typing import Any, ClassVar, overload
from android.os.Parcel import Parcel

class AdvertisingSetParameters:
    CREATOR: ClassVar[Any]
    INTERVAL_HIGH: ClassVar[int]
    INTERVAL_LOW: ClassVar[int]
    INTERVAL_MAX: ClassVar[int]
    INTERVAL_MEDIUM: ClassVar[int]
    INTERVAL_MIN: ClassVar[int]
    TX_POWER_HIGH: ClassVar[int]
    TX_POWER_LOW: ClassVar[int]
    TX_POWER_MAX: ClassVar[int]
    TX_POWER_MEDIUM: ClassVar[int]
    TX_POWER_MIN: ClassVar[int]
    TX_POWER_ULTRA_LOW: ClassVar[int]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    def getTxPowerLevel(self) -> int: ...
    def isDiscoverable(self) -> bool: ...
    def isScannable(self) -> bool: ...
    def isAnonymous(self) -> bool: ...
    def includeTxPower(self) -> bool: ...
    def isLegacy(self) -> bool: ...
    def isConnectable(self) -> bool: ...
    def getPrimaryPhy(self) -> int: ...
    def getSecondaryPhy(self) -> int: ...
    def getInterval(self) -> int: ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
    def toString(self) -> str: ...

    class Builder:
        def __init__(self) -> None: ...
        def setTxPowerLevel(self, p0: int) -> Any: ...
        def setConnectable(self, p0: bool) -> Any: ...
        def setDiscoverable(self, p0: bool) -> Any: ...
        def setScannable(self, p0: bool) -> Any: ...
        def setLegacyMode(self, p0: bool) -> Any: ...
        def setAnonymous(self, p0: bool) -> Any: ...
        def setIncludeTxPower(self, p0: bool) -> Any: ...
        def setPrimaryPhy(self, p0: int) -> Any: ...
        def setSecondaryPhy(self, p0: int) -> Any: ...
        def setInterval(self, p0: int) -> Any: ...
        def build(self) -> "AdvertisingSetParameters": ...
