from typing import Any, ClassVar, overload
from android.os.Parcel import Parcel

class AdvertiseSettings:
    ADVERTISE_MODE_BALANCED: ClassVar[int]
    ADVERTISE_MODE_LOW_LATENCY: ClassVar[int]
    ADVERTISE_MODE_LOW_POWER: ClassVar[int]
    ADVERTISE_TX_POWER_HIGH: ClassVar[int]
    ADVERTISE_TX_POWER_LOW: ClassVar[int]
    ADVERTISE_TX_POWER_MEDIUM: ClassVar[int]
    ADVERTISE_TX_POWER_ULTRA_LOW: ClassVar[int]
    CREATOR: ClassVar[Any]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    def getTxPowerLevel(self) -> int: ...
    def isDiscoverable(self) -> bool: ...
    def isConnectable(self) -> bool: ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
    def getMode(self) -> int: ...
    def getTimeout(self) -> int: ...
    def toString(self) -> str: ...

    class Builder:
        def __init__(self) -> None: ...
        def setTxPowerLevel(self, p0: int) -> Any: ...
        def setConnectable(self, p0: bool) -> Any: ...
        def setAdvertiseMode(self, p0: int) -> Any: ...
        def setDiscoverable(self, p0: bool) -> Any: ...
        def build(self) -> "AdvertiseSettings": ...
        def setTimeout(self, p0: int) -> Any: ...
