from typing import Any, ClassVar, overload
from android.bluetooth.BluetoothDevice import BluetoothDevice
from android.bluetooth.le.ScanRecord import ScanRecord
from android.os.Parcel import Parcel

class ScanResult:
    CREATOR: ClassVar[Any]
    DATA_COMPLETE: ClassVar[int]
    DATA_TRUNCATED: ClassVar[int]
    PERIODIC_INTERVAL_NOT_PRESENT: ClassVar[int]
    PHY_UNUSED: ClassVar[int]
    SID_NOT_PRESENT: ClassVar[int]
    TX_POWER_NOT_PRESENT: ClassVar[int]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    @overload
    def __init__(self, p0: BluetoothDevice, p1: ScanRecord, p2: int, p3: int) -> None: ...
    @overload
    def __init__(self, p0: BluetoothDevice, p1: int, p2: int, p3: int, p4: int, p5: int, p6: int, p7: int, p8: ScanRecord, p9: int) -> None: ...
    def getScanRecord(self) -> ScanRecord: ...
    def getRssi(self) -> int: ...
    def isLegacy(self) -> bool: ...
    def isConnectable(self) -> bool: ...
    def getDataStatus(self) -> int: ...
    def getPrimaryPhy(self) -> int: ...
    def getSecondaryPhy(self) -> int: ...
    def getAdvertisingSid(self) -> int: ...
    def getTxPower(self) -> int: ...
    def getPeriodicAdvertisingInterval(self) -> int: ...
    def getTimestampNanos(self) -> int: ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
    def getDevice(self) -> BluetoothDevice: ...
    def equals(self, p0: Any) -> bool: ...
    def toString(self) -> str: ...
    def hashCode(self) -> int: ...
