from typing import Any, ClassVar, overload
from java.io.OutputStream import OutputStream
from java.util.logging.Formatter import Formatter
from java.util.logging.LogRecord import LogRecord

class StreamHandler:
    @overload
    def __init__(self, p0: OutputStream, p1: Formatter) -> None: ...
    @overload
    def __init__(self) -> None: ...
    def isLoggable(self, p0: LogRecord) -> bool: ...
    def setEncoding(self, p0: str) -> None: ...
    def publish(self, p0: LogRecord) -> None: ...
    def flush(self) -> None: ...
    def close(self) -> None: ...
