from typing import Any, ClassVar, overload
from android.os.Parcel import Parcel

class GetWalletCardsRequest:
    CREATOR: ClassVar[Any]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    def __init__(self, p0: int, p1: int, p2: int, p3: int) -> None: ...
    def getCardHeightPx(self) -> int: ...
    def getCardWidthPx(self) -> int: ...
    def getIconSizePx(self) -> int: ...
    def getMaxCards(self) -> int: ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
