from typing import Any, ClassVar, overload
from android.nfc.NdefMessage import NdefMessage
from android.nfc.Tag import Tag

class NdefFormatable:
    def connect(self) -> None: ...
    def isConnected(self) -> bool: ...
    @staticmethod
    def get(p0: Tag) -> "NdefFormatable": ...
    def format(self, p0: NdefMessage) -> None: ...
    def close(self) -> None: ...
    def getTag(self) -> Tag: ...
    def formatReadOnly(self, p0: NdefMessage) -> None: ...
