from typing import Any, ClassVar, overload
from org.xml.sax.Locator import Locator

class LocatorImpl:
    @overload
    def __init__(self, p0: Locator) -> None: ...
    @overload
    def __init__(self) -> None: ...
    def getSystemId(self) -> str: ...
    def setSystemId(self, p0: str) -> None: ...
    def getColumnNumber(self) -> int: ...
    def getPublicId(self) -> str: ...
    def setPublicId(self, p0: str) -> None: ...
    def setColumnNumber(self, p0: int) -> None: ...
    def setLineNumber(self, p0: int) -> None: ...
    def getLineNumber(self) -> int: ...
