from typing import Any, ClassVar, overload
from java.util.Enumeration import Enumeration

class NamespaceSupport:
    XMLNS: ClassVar[str]
    NSDECL: ClassVar[str]
    def __init__(self) -> None: ...
    def reset(self) -> None: ...
    def processName(self, p0: str, p1: Any, p2: bool) -> Any: ...
    def getPrefix(self, p0: str) -> str: ...
    def getURI(self, p0: str) -> str: ...
    @overload
    def getPrefixes(self, p0: str) -> Enumeration: ...
    @overload
    def getPrefixes(self) -> Enumeration: ...
    def declarePrefix(self, p0: str, p1: str) -> bool: ...
    def getDeclaredPrefixes(self) -> Enumeration: ...
    def pushContext(self) -> None: ...
    def popContext(self) -> None: ...
    def setNamespaceDeclUris(self, p0: bool) -> None: ...
    def isNamespaceDeclUris(self) -> bool: ...
