from typing import Any, ClassVar, overload
from android.os.Parcel import Parcel

class RttRangingParams:
    CREATOR: ClassVar[Any]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    def getRangingUpdateRate(self) -> int: ...
    def equals(self, p0: Any) -> bool: ...
    def toString(self) -> str: ...
    def hashCode(self) -> int: ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
    def getMatchFilter(self) -> Any: ...
    def getServiceName(self) -> str: ...
    def isPeriodicRangingHwFeatureEnabled(self) -> bool: ...

    class Builder:
        def __init__(self, p0: str) -> None: ...
        def setRangingUpdateRate(self, p0: int) -> Any: ...
        def build(self) -> "RttRangingParams": ...
        def setMatchFilter(self, p0: Any) -> Any: ...
        def setPeriodicRangingHwFeatureEnabled(self, p0: bool) -> Any: ...

from typing import Any, ClassVar, overload
from android.os.Parcel import Parcel

class RttRangingCapabilities:
    CREATOR: ClassVar[Any]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    def toString(self) -> str: ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
    def hasPeriodicRangingHardwareFeature(self) -> bool: ...

