from typing import Any, ClassVar, overload
from java.io.InputStream import InputStream
from java.io.Reader import Reader

class XmlPullParser:
    CDSECT: ClassVar[int]
    COMMENT: ClassVar[int]
    DOCDECL: ClassVar[int]
    END_DOCUMENT: ClassVar[int]
    END_TAG: ClassVar[int]
    ENTITY_REF: ClassVar[int]
    FEATURE_PROCESS_DOCDECL: ClassVar[str]
    FEATURE_PROCESS_NAMESPACES: ClassVar[str]
    FEATURE_REPORT_NAMESPACE_ATTRIBUTES: ClassVar[str]
    FEATURE_VALIDATION: ClassVar[str]
    IGNORABLE_WHITESPACE: ClassVar[int]
    NO_NAMESPACE: ClassVar[str]
    PROCESSING_INSTRUCTION: ClassVar[int]
    START_DOCUMENT: ClassVar[int]
    START_TAG: ClassVar[int]
    TEXT: ClassVar[int]
    TYPES: ClassVar[Any]
    def setFeature(self, p0: str, p1: bool) -> None: ...
    def getFeature(self, p0: str) -> bool: ...
    def getInputEncoding(self) -> str: ...
    def defineEntityReplacementText(self, p0: str, p1: str) -> None: ...
    def getNamespaceCount(self, p0: int) -> int: ...
    def getNamespacePrefix(self, p0: int) -> str: ...
    def getNamespaceUri(self, p0: int) -> str: ...
    @overload
    def getNamespace(self, p0: str) -> str: ...
    @overload
    def getNamespace(self) -> str: ...
    def getDepth(self) -> int: ...
    def getTextCharacters(self, p0: Any) -> Any: ...
    def getPrefix(self) -> str: ...
    def isEmptyElementTag(self) -> bool: ...
    def getAttributePrefix(self, p0: int) -> str: ...
    def getAttributeType(self, p0: int) -> str: ...
    def isAttributeDefault(self, p0: int) -> bool: ...
    def require(self, p0: int, p1: str, p2: str) -> None: ...
    def nextText(self) -> str: ...
    def nextTag(self) -> int: ...
    def getName(self) -> str: ...
    def getProperty(self, p0: str) -> Any: ...
    def isWhitespace(self) -> bool: ...
    def next(self) -> int: ...
    def setProperty(self, p0: str, p1: Any) -> None: ...
    def nextToken(self) -> int: ...
    def getLineNumber(self) -> int: ...
    def getText(self) -> str: ...
    @overload
    def setInput(self, p0: InputStream, p1: str) -> None: ...
    @overload
    def setInput(self, p0: Reader) -> None: ...
    def getAttributeCount(self) -> int: ...
    def getAttributeNamespace(self, p0: int) -> str: ...
    def getAttributeName(self, p0: int) -> str: ...
    @overload
    def getAttributeValue(self, p0: int) -> str: ...
    @overload
    def getAttributeValue(self, p0: str, p1: str) -> str: ...
    def getPositionDescription(self) -> str: ...
    def getColumnNumber(self) -> int: ...
    def getEventType(self) -> int: ...
