from typing import Any, ClassVar, overload
from android.app.appsearch.GenericDocument import GenericDocument
from android.os.Bundle import Bundle
from android.os.Parcel import Parcel

class ExecuteAppFunctionResponse:
    CREATOR: ClassVar[Any]
    PROPERTY_RETURN_VALUE: ClassVar[str]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    @overload
    def __init__(self, p0: GenericDocument) -> None: ...
    @overload
    def __init__(self, p0: GenericDocument, p1: Bundle) -> None: ...
    def getExtras(self) -> Bundle: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
    def describeContents(self) -> int: ...
    def getResultDocument(self) -> GenericDocument: ...
