from typing import Any, ClassVar, overload
from java.util.Properties import Properties
from javax.xml.transform.ErrorListener import ErrorListener
from javax.xml.transform.Result import Result
from javax.xml.transform.Source import Source
from javax.xml.transform.URIResolver import URIResolver

class Transformer:
    def setParameter(self, p0: str, p1: Any) -> None: ...
    def getParameter(self, p0: str) -> Any: ...
    def setURIResolver(self, p0: URIResolver) -> None: ...
    def getURIResolver(self) -> URIResolver: ...
    def setOutputProperties(self, p0: Properties) -> None: ...
    def getOutputProperties(self) -> Properties: ...
    def setOutputProperty(self, p0: str, p1: str) -> None: ...
    def getOutputProperty(self, p0: str) -> str: ...
    def setErrorListener(self, p0: ErrorListener) -> None: ...
    def getErrorListener(self) -> ErrorListener: ...
    def reset(self) -> None: ...
    def transform(self, p0: Source, p1: Result) -> None: ...
    def clearParameters(self) -> None: ...

from typing import Any, ClassVar, overload

class OutputKeys:
    METHOD: ClassVar[str]
    VERSION: ClassVar[str]
    ENCODING: ClassVar[str]
    OMIT_XML_DECLARATION: ClassVar[str]
    STANDALONE: ClassVar[str]
    DOCTYPE_PUBLIC: ClassVar[str]
    DOCTYPE_SYSTEM: ClassVar[str]
    CDATA_SECTION_ELEMENTS: ClassVar[str]
    INDENT: ClassVar[str]
    MEDIA_TYPE: ClassVar[str]

from typing import Any, ClassVar, overload
from java.io.PrintStream import PrintStream
from java.io.PrintWriter import PrintWriter
from java.lang.Throwable import Throwable
from javax.xml.transform.SourceLocator import SourceLocator

class TransformerException:
    @overload
    def __init__(self, p0: str, p1: SourceLocator, p2: Throwable) -> None: ...
    @overload
    def __init__(self, p0: str) -> None: ...
    @overload
    def __init__(self, p0: Throwable) -> None: ...
    @overload
    def __init__(self, p0: str, p1: Throwable) -> None: ...
    @overload
    def __init__(self, p0: str, p1: SourceLocator) -> None: ...
    def getLocationAsString(self) -> str: ...
    def getLocator(self) -> SourceLocator: ...
    def setLocator(self, p0: SourceLocator) -> None: ...
    def getMessageAndLocation(self) -> str: ...
    @overload
    def printStackTrace(self, p0: PrintWriter) -> None: ...
    @overload
    def printStackTrace(self, p0: PrintStream) -> None: ...
    @overload
    def printStackTrace(self) -> None: ...
    def getCause(self) -> Throwable: ...
    def initCause(self, p0: Throwable) -> Throwable: ...
    def getException(self) -> Throwable: ...

from typing import Any, ClassVar, overload

class SourceLocator:
    def getSystemId(self) -> str: ...
    def getPublicId(self) -> str: ...
    def getColumnNumber(self) -> int: ...
    def getLineNumber(self) -> int: ...

from typing import Any, ClassVar, overload
from java.util.Properties import Properties
from javax.xml.transform.Transformer import Transformer

class Templates:
    def getOutputProperties(self) -> Properties: ...
    def newTransformer(self) -> Transformer: ...

from typing import Any, ClassVar, overload
from java.lang.Exception import Exception
from java.lang.Throwable import Throwable

class TransformerFactoryConfigurationError:
    @overload
    def __init__(self, p0: Exception, p1: str) -> None: ...
    @overload
    def __init__(self, p0: Exception) -> None: ...
    @overload
    def __init__(self, p0: str) -> None: ...
    @overload
    def __init__(self) -> None: ...
    def getCause(self) -> Throwable: ...
    def getMessage(self) -> str: ...
    def getException(self) -> Exception: ...

from typing import Any, ClassVar, overload
from java.lang.Throwable import Throwable
from javax.xml.transform.SourceLocator import SourceLocator

class TransformerConfigurationException:
    @overload
    def __init__(self, p0: str, p1: SourceLocator, p2: Throwable) -> None: ...
    @overload
    def __init__(self, p0: str, p1: SourceLocator) -> None: ...
    @overload
    def __init__(self, p0: str, p1: Throwable) -> None: ...
    @overload
    def __init__(self, p0: Throwable) -> None: ...
    @overload
    def __init__(self, p0: str) -> None: ...
    @overload
    def __init__(self) -> None: ...

from typing import Any, ClassVar, overload

class Source:
    def getSystemId(self) -> str: ...
    def setSystemId(self, p0: str) -> None: ...
    def isEmpty(self) -> bool: ...

from typing import Any, ClassVar, overload

class Result:
    PI_DISABLE_OUTPUT_ESCAPING: ClassVar[str]
    PI_ENABLE_OUTPUT_ESCAPING: ClassVar[str]
    def getSystemId(self) -> str: ...
    def setSystemId(self, p0: str) -> None: ...

from typing import Any, ClassVar, overload
from javax.xml.transform.Source import Source

class URIResolver:
    def resolve(self, p0: str, p1: str) -> Source: ...

from typing import Any, ClassVar, overload
from java.lang.ClassLoader import ClassLoader
from javax.xml.transform.ErrorListener import ErrorListener
from javax.xml.transform.Source import Source
from javax.xml.transform.Templates import Templates
from javax.xml.transform.Transformer import Transformer
from javax.xml.transform.URIResolver import URIResolver

class TransformerFactory:
    def setAttribute(self, p0: str, p1: Any) -> None: ...
    def getAttribute(self, p0: str) -> Any: ...
    def setURIResolver(self, p0: URIResolver) -> None: ...
    def getURIResolver(self) -> URIResolver: ...
    def setErrorListener(self, p0: ErrorListener) -> None: ...
    def getErrorListener(self) -> ErrorListener: ...
    @overload
    def newTransformer(self) -> Transformer: ...
    @overload
    def newTransformer(self, p0: Source) -> Transformer: ...
    def newTemplates(self, p0: Source) -> Templates: ...
    def getAssociatedStylesheet(self, p0: Source, p1: str, p2: str, p3: str) -> Source: ...
    @overload
    @staticmethod
    def newInstance() -> "TransformerFactory": ...
    @overload
    @staticmethod
    def newInstance(p0: str, p1: ClassLoader) -> "TransformerFactory": ...
    def getFeature(self, p0: str) -> bool: ...
    def setFeature(self, p0: str, p1: bool) -> None: ...
    @staticmethod
    def newDefaultInstance() -> "TransformerFactory": ...

from typing import Any, ClassVar, overload
from javax.xml.transform.TransformerException import TransformerException

class ErrorListener:
    def warning(self, p0: TransformerException) -> None: ...
    def error(self, p0: TransformerException) -> None: ...
    def fatalError(self, p0: TransformerException) -> None: ...

