from typing import Any, ClassVar, overload
from javax.xml.transform.Result import Result
from javax.xml.transform.Source import Source
from org.w3c.dom.ls.LSResourceResolver import LSResourceResolver
from org.xml.sax.ErrorHandler import ErrorHandler

class Validator:
    def getErrorHandler(self) -> ErrorHandler: ...
    def reset(self) -> None: ...
    def getProperty(self, p0: str) -> Any: ...
    @overload
    def validate(self, p0: Source) -> None: ...
    @overload
    def validate(self, p0: Source, p1: Result) -> None: ...
    def setProperty(self, p0: str, p1: Any) -> None: ...
    def setErrorHandler(self, p0: ErrorHandler) -> None: ...
    def getFeature(self, p0: str) -> bool: ...
    def setFeature(self, p0: str, p1: bool) -> None: ...
    def setResourceResolver(self, p0: LSResourceResolver) -> None: ...
    def getResourceResolver(self) -> LSResourceResolver: ...

from typing import Any, ClassVar, overload
from javax.xml.validation.TypeInfoProvider import TypeInfoProvider
from org.w3c.dom.ls.LSResourceResolver import LSResourceResolver
from org.xml.sax.ContentHandler import ContentHandler
from org.xml.sax.ErrorHandler import ErrorHandler

class ValidatorHandler:
    def getErrorHandler(self) -> ErrorHandler: ...
    def getProperty(self, p0: str) -> Any: ...
    def setProperty(self, p0: str, p1: Any) -> None: ...
    def setErrorHandler(self, p0: ErrorHandler) -> None: ...
    def getFeature(self, p0: str) -> bool: ...
    def setFeature(self, p0: str, p1: bool) -> None: ...
    def setContentHandler(self, p0: ContentHandler) -> None: ...
    def getContentHandler(self) -> ContentHandler: ...
    def setResourceResolver(self, p0: LSResourceResolver) -> None: ...
    def getResourceResolver(self) -> LSResourceResolver: ...
    def getTypeInfoProvider(self) -> TypeInfoProvider: ...

from typing import Any, ClassVar, overload
from java.io.File import File
from java.lang.ClassLoader import ClassLoader
from java.net.URL import URL
from javax.xml.transform.Source import Source
from javax.xml.validation.Schema import Schema
from org.w3c.dom.ls.LSResourceResolver import LSResourceResolver
from org.xml.sax.ErrorHandler import ErrorHandler

class SchemaFactory:
    def getErrorHandler(self) -> ErrorHandler: ...
    def getProperty(self, p0: str) -> Any: ...
    @overload
    @staticmethod
    def newInstance(p0: str, p1: str, p2: ClassLoader) -> "SchemaFactory": ...
    @overload
    @staticmethod
    def newInstance(p0: str) -> "SchemaFactory": ...
    def setProperty(self, p0: str, p1: Any) -> None: ...
    def setErrorHandler(self, p0: ErrorHandler) -> None: ...
    def getFeature(self, p0: str) -> bool: ...
    def setFeature(self, p0: str, p1: bool) -> None: ...
    def setResourceResolver(self, p0: LSResourceResolver) -> None: ...
    def getResourceResolver(self) -> LSResourceResolver: ...
    def isSchemaLanguageSupported(self, p0: str) -> bool: ...
    @overload
    def newSchema(self) -> Schema: ...
    @overload
    def newSchema(self, p0: URL) -> Schema: ...
    @overload
    def newSchema(self, p0: Any) -> Schema: ...
    @overload
    def newSchema(self, p0: Source) -> Schema: ...
    @overload
    def newSchema(self, p0: File) -> Schema: ...
    @staticmethod
    def newDefaultInstance() -> "SchemaFactory": ...

from typing import Any, ClassVar, overload
from org.w3c.dom.TypeInfo import TypeInfo

class TypeInfoProvider:
    def getElementTypeInfo(self) -> TypeInfo: ...
    def getAttributeTypeInfo(self, p0: int) -> TypeInfo: ...
    def isIdAttribute(self, p0: int) -> bool: ...
    def isSpecified(self, p0: int) -> bool: ...

from typing import Any, ClassVar, overload
from javax.xml.validation.SchemaFactory import SchemaFactory

class SchemaFactoryLoader:
    def newFactory(self, p0: str) -> SchemaFactory: ...

from typing import Any, ClassVar, overload
from javax.xml.validation.Validator import Validator
from javax.xml.validation.ValidatorHandler import ValidatorHandler

class Schema:
    def newValidator(self) -> Validator: ...
    def newValidatorHandler(self) -> ValidatorHandler: ...

