from typing import Any, ClassVar, overload
from android.util.Rational import Rational

class ColorSpaceTransform:
    @overload
    def __init__(self, p0: Any) -> None: ...
    @overload
    def __init__(self, p0: Any) -> None: ...
    def getElement(self, p0: int, p1: int) -> Rational: ...
    def equals(self, p0: Any) -> bool: ...
    def toString(self) -> str: ...
    def hashCode(self) -> int: ...
    @overload
    def copyElements(self, p0: Any, p1: int) -> None: ...
    @overload
    def copyElements(self, p0: Any, p1: int) -> None: ...
