from typing import Any, ClassVar, overload

class MultiResolutionStreamConfigurationMap:
    def getOutputFormats(self) -> Any: ...
    def getInputFormats(self) -> Any: ...
    def getOutputInfo(self, p0: int) -> list: ...
    def getInputInfo(self, p0: int) -> list: ...
    def equals(self, p0: Any) -> bool: ...
    def toString(self) -> str: ...
    def hashCode(self) -> int: ...
