from typing import Any, ClassVar, overload
from android.icu.util.ULocale import ULocale
from java.text.CharacterIterator import CharacterIterator
from java.util.Locale import Locale

class BreakIterator:
    DONE: ClassVar[int]
    KIND_CHARACTER: ClassVar[int]
    KIND_LINE: ClassVar[int]
    KIND_SENTENCE: ClassVar[int]
    KIND_TITLE: ClassVar[int]
    KIND_WORD: ClassVar[int]
    WORD_IDEO: ClassVar[int]
    WORD_IDEO_LIMIT: ClassVar[int]
    WORD_KANA: ClassVar[int]
    WORD_KANA_LIMIT: ClassVar[int]
    WORD_LETTER: ClassVar[int]
    WORD_LETTER_LIMIT: ClassVar[int]
    WORD_NONE: ClassVar[int]
    WORD_NONE_LIMIT: ClassVar[int]
    WORD_NUMBER: ClassVar[int]
    WORD_NUMBER_LIMIT: ClassVar[int]
    def getRuleStatusVec(self, p0: Any) -> int: ...
    @overload
    @staticmethod
    def getWordInstance(p0: ULocale) -> "BreakIterator": ...
    @overload
    @staticmethod
    def getWordInstance(p0: Locale) -> "BreakIterator": ...
    @overload
    @staticmethod
    def getWordInstance() -> "BreakIterator": ...
    def getRuleStatus(self) -> int: ...
    @overload
    @staticmethod
    def getLineInstance() -> "BreakIterator": ...
    @overload
    @staticmethod
    def getLineInstance(p0: ULocale) -> "BreakIterator": ...
    @overload
    @staticmethod
    def getLineInstance(p0: Locale) -> "BreakIterator": ...
    @overload
    @staticmethod
    def getCharacterInstance(p0: ULocale) -> "BreakIterator": ...
    @overload
    @staticmethod
    def getCharacterInstance() -> "BreakIterator": ...
    @overload
    @staticmethod
    def getCharacterInstance(p0: Locale) -> "BreakIterator": ...
    @overload
    @staticmethod
    def getSentenceInstance(p0: ULocale) -> "BreakIterator": ...
    @overload
    @staticmethod
    def getSentenceInstance(p0: Locale) -> "BreakIterator": ...
    @overload
    @staticmethod
    def getSentenceInstance() -> "BreakIterator": ...
    @overload
    @staticmethod
    def getTitleInstance() -> "BreakIterator": ...
    @overload
    @staticmethod
    def getTitleInstance(p0: ULocale) -> "BreakIterator": ...
    @overload
    @staticmethod
    def getTitleInstance(p0: Locale) -> "BreakIterator": ...
    def following(self, p0: int) -> int: ...
    def preceding(self, p0: int) -> int: ...
    def isBoundary(self, p0: int) -> bool: ...
    def getText(self) -> CharacterIterator: ...
    @overload
    def setText(self, p0: CharacterIterator) -> None: ...
    @overload
    def setText(self, p0: str) -> None: ...
    @overload
    def setText(self, p0: str) -> None: ...
    @staticmethod
    def getAvailableLocales() -> Any: ...
    def previous(self) -> int: ...
    def clone(self) -> Any: ...
    @overload
    def next(self, p0: int) -> int: ...
    @overload
    def next(self) -> int: ...
    def last(self) -> int: ...
    def first(self) -> int: ...
    def current(self) -> int: ...
