from typing import Any, ClassVar, overload

class CollationKey:
    def __init__(self, p0: str, p1: Any) -> None: ...
    def getBound(self, p0: int, p1: int) -> "CollationKey": ...
    def getSourceString(self) -> str: ...
    def toByteArray(self) -> Any: ...
    @overload
    def equals(self, p0: "CollationKey") -> bool: ...
    @overload
    def equals(self, p0: Any) -> bool: ...
    def hashCode(self) -> int: ...
    @overload
    def compareTo(self, p0: Any) -> int: ...
    @overload
    def compareTo(self, p0: "CollationKey") -> int: ...
    def merge(self, p0: "CollationKey") -> "CollationKey": ...

    class BoundMode:
        LOWER: ClassVar[int]
        UPPER: ClassVar[int]
        UPPER_LONG: ClassVar[int]
