from typing import Any, ClassVar, overload
from android.icu.math.BigDecimal import BigDecimal
from android.icu.math.MathContext import MathContext
from android.icu.text.CurrencyPluralInfo import CurrencyPluralInfo
from android.icu.text.DecimalFormatSymbols import DecimalFormatSymbols
from android.icu.util.Currency import Currency
from android.icu.util.CurrencyAmount import CurrencyAmount
from java.lang.StringBuffer import StringBuffer
from java.math.BigDecimal import BigDecimal
from java.math.BigInteger import BigInteger
from java.math.MathContext import MathContext
from java.text.AttributedCharacterIterator import AttributedCharacterIterator
from java.text.FieldPosition import FieldPosition
from java.text.ParsePosition import ParsePosition

class DecimalFormat:
    MINIMUM_GROUPING_DIGITS_AUTO: ClassVar[int]
    MINIMUM_GROUPING_DIGITS_MIN2: ClassVar[int]
    PAD_AFTER_PREFIX: ClassVar[int]
    PAD_AFTER_SUFFIX: ClassVar[int]
    PAD_BEFORE_PREFIX: ClassVar[int]
    PAD_BEFORE_SUFFIX: ClassVar[int]
    ACCOUNTINGCURRENCYSTYLE: ClassVar[int]
    CASHCURRENCYSTYLE: ClassVar[int]
    CURRENCYSTYLE: ClassVar[int]
    FRACTION_FIELD: ClassVar[int]
    INTEGERSTYLE: ClassVar[int]
    INTEGER_FIELD: ClassVar[int]
    ISOCURRENCYSTYLE: ClassVar[int]
    NUMBERSTYLE: ClassVar[int]
    PERCENTSTYLE: ClassVar[int]
    PLURALCURRENCYSTYLE: ClassVar[int]
    SCIENTIFICSTYLE: ClassVar[int]
    STANDARDCURRENCYSTYLE: ClassVar[int]
    @overload
    def __init__(self, p0: str) -> None: ...
    @overload
    def __init__(self, p0: str, p1: DecimalFormatSymbols, p2: CurrencyPluralInfo, p3: int) -> None: ...
    @overload
    def __init__(self, p0: str, p1: DecimalFormatSymbols) -> None: ...
    @overload
    def __init__(self) -> None: ...
    def parseCurrency(self, p0: str, p1: ParsePosition) -> CurrencyAmount: ...
    def setParseStrict(self, p0: bool) -> None: ...
    def isParseStrict(self) -> bool: ...
    def applyLocalizedPattern(self, p0: str) -> None: ...
    def setDecimalFormatSymbols(self, p0: DecimalFormatSymbols) -> None: ...
    def getPositivePrefix(self) -> str: ...
    def setPositivePrefix(self, p0: str) -> None: ...
    def getNegativePrefix(self) -> str: ...
    def setNegativePrefix(self, p0: str) -> None: ...
    def getPositiveSuffix(self) -> str: ...
    def setPositiveSuffix(self, p0: str) -> None: ...
    def getNegativeSuffix(self) -> str: ...
    def setNegativeSuffix(self, p0: str) -> None: ...
    def isSignAlwaysShown(self) -> bool: ...
    def setSignAlwaysShown(self, p0: bool) -> None: ...
    def getMultiplier(self) -> int: ...
    def setMultiplier(self, p0: int) -> None: ...
    @overload
    def setRoundingIncrement(self, p0: BigDecimal) -> None: ...
    @overload
    def setRoundingIncrement(self, p0: BigDecimal) -> None: ...
    @overload
    def setRoundingIncrement(self, p0: float) -> None: ...
    def getMathContext(self) -> MathContext: ...
    def setMathContext(self, p0: MathContext) -> None: ...
    def getRoundingIncrement(self) -> BigDecimal: ...
    def applyPattern(self, p0: str) -> None: ...
    def toPattern(self) -> str: ...
    def getMathContextICU(self) -> MathContext: ...
    def setMathContextICU(self, p0: MathContext) -> None: ...
    def areSignificantDigitsUsed(self) -> bool: ...
    def setSignificantDigitsUsed(self, p0: bool) -> None: ...
    def getMinimumSignificantDigits(self) -> int: ...
    def setMinimumSignificantDigits(self, p0: int) -> None: ...
    def getMaximumSignificantDigits(self) -> int: ...
    def setMaximumSignificantDigits(self, p0: int) -> None: ...
    def getFormatWidth(self) -> int: ...
    def setFormatWidth(self, p0: int) -> None: ...
    def getPadCharacter(self) -> str: ...
    def setPadCharacter(self, p0: str) -> None: ...
    def getPadPosition(self) -> int: ...
    def setPadPosition(self, p0: int) -> None: ...
    def isScientificNotation(self) -> bool: ...
    def setScientificNotation(self, p0: bool) -> None: ...
    def getMinimumExponentDigits(self) -> int: ...
    def setMinimumExponentDigits(self, p0: int) -> None: ...
    def isExponentSignAlwaysShown(self) -> bool: ...
    def setExponentSignAlwaysShown(self, p0: bool) -> None: ...
    def getGroupingSize(self) -> int: ...
    def setGroupingSize(self, p0: int) -> None: ...
    def getSecondaryGroupingSize(self) -> int: ...
    def setSecondaryGroupingSize(self, p0: int) -> None: ...
    def getMinimumGroupingDigits(self) -> int: ...
    def setMinimumGroupingDigits(self, p0: int) -> None: ...
    def isDecimalSeparatorAlwaysShown(self) -> bool: ...
    def setDecimalSeparatorAlwaysShown(self, p0: bool) -> None: ...
    def getCurrencyUsage(self) -> Any: ...
    def setCurrencyUsage(self, p0: Any) -> None: ...
    def getCurrencyPluralInfo(self) -> CurrencyPluralInfo: ...
    def setCurrencyPluralInfo(self, p0: CurrencyPluralInfo) -> None: ...
    def isParseBigDecimal(self) -> bool: ...
    def setParseBigDecimal(self, p0: bool) -> None: ...
    def getParseMaxDigits(self) -> int: ...
    def setParseMaxDigits(self, p0: int) -> None: ...
    def isDecimalPatternMatchRequired(self) -> bool: ...
    def setDecimalPatternMatchRequired(self, p0: bool) -> None: ...
    def isParseNoExponent(self) -> bool: ...
    def setParseNoExponent(self, p0: bool) -> None: ...
    def isParseCaseSensitive(self) -> bool: ...
    def setParseCaseSensitive(self, p0: bool) -> None: ...
    def toLocalizedPattern(self) -> str: ...
    def formatToCharacterIterator(self, p0: Any) -> AttributedCharacterIterator: ...
    def getDecimalFormatSymbols(self) -> DecimalFormatSymbols: ...
    def isParseIntegerOnly(self) -> bool: ...
    def setParseIntegerOnly(self, p0: bool) -> None: ...
    def isGroupingUsed(self) -> bool: ...
    def setGroupingUsed(self, p0: bool) -> None: ...
    def getMaximumIntegerDigits(self) -> int: ...
    def setMaximumIntegerDigits(self, p0: int) -> None: ...
    def getMinimumIntegerDigits(self) -> int: ...
    def setMinimumIntegerDigits(self, p0: int) -> None: ...
    def getMaximumFractionDigits(self) -> int: ...
    def setMaximumFractionDigits(self, p0: int) -> None: ...
    def getMinimumFractionDigits(self) -> int: ...
    def setMinimumFractionDigits(self, p0: int) -> None: ...
    def getCurrency(self) -> Currency: ...
    def getRoundingMode(self) -> int: ...
    def setRoundingMode(self, p0: int) -> None: ...
    def setCurrency(self, p0: Currency) -> None: ...
    def equals(self, p0: Any) -> bool: ...
    def toString(self) -> str: ...
    def hashCode(self) -> int: ...
    def clone(self) -> Any: ...
    @overload
    def format(self, p0: CurrencyAmount, p1: StringBuffer, p2: FieldPosition) -> StringBuffer: ...
    @overload
    def format(self, p0: BigDecimal, p1: StringBuffer, p2: FieldPosition) -> StringBuffer: ...
    @overload
    def format(self, p0: BigInteger, p1: StringBuffer, p2: FieldPosition) -> StringBuffer: ...
    @overload
    def format(self, p0: int, p1: StringBuffer, p2: FieldPosition) -> StringBuffer: ...
    @overload
    def format(self, p0: float, p1: StringBuffer, p2: FieldPosition) -> StringBuffer: ...
    @overload
    def format(self, p0: BigDecimal, p1: StringBuffer, p2: FieldPosition) -> StringBuffer: ...
    def parse(self, p0: str, p1: ParsePosition) -> float: ...
