from typing import Any, ClassVar, overload
from java.io.InputStream import InputStream
from java.lang.Appendable import Appendable
from java.lang.StringBuilder import StringBuilder

class Normalizer2:
    def isNormalized(self, p0: str) -> bool: ...
    def composePair(self, p0: int, p1: int) -> int: ...
    @staticmethod
    def getNFCInstance() -> "Normalizer2": ...
    @staticmethod
    def getNFKDInstance() -> "Normalizer2": ...
    def hasBoundaryAfter(self, p0: int) -> bool: ...
    @staticmethod
    def getNFKCInstance() -> "Normalizer2": ...
    def getDecomposition(self, p0: int) -> str: ...
    @staticmethod
    def getNFDInstance() -> "Normalizer2": ...
    @staticmethod
    def getNFKCCasefoldInstance() -> "Normalizer2": ...
    @staticmethod
    def getNFKCSimpleCasefoldInstance() -> "Normalizer2": ...
    def getRawDecomposition(self, p0: int) -> str: ...
    def hasBoundaryBefore(self, p0: int) -> bool: ...
    def isInert(self, p0: int) -> bool: ...
    def normalizeSecondAndAppend(self, p0: StringBuilder, p1: str) -> StringBuilder: ...
    def quickCheck(self, p0: str) -> Any: ...
    def spanQuickCheckYes(self, p0: str) -> int: ...
    def append(self, p0: StringBuilder, p1: str) -> StringBuilder: ...
    @staticmethod
    def getInstance(p0: InputStream, p1: str, p2: Any) -> "Normalizer2": ...
    def getCombiningClass(self, p0: int) -> int: ...
    @overload
    def normalize(self, p0: str, p1: StringBuilder) -> StringBuilder: ...
    @overload
    def normalize(self, p0: str) -> str: ...
    @overload
    def normalize(self, p0: str, p1: Appendable) -> Appendable: ...

    class Mode:
        COMPOSE: ClassVar["Mode"]
        COMPOSE_CONTIGUOUS: ClassVar["Mode"]
        DECOMPOSE: ClassVar["Mode"]
        FCD: ClassVar["Mode"]
        COMPOSE: ClassVar[Any]
        COMPOSE_CONTIGUOUS: ClassVar[Any]
        DECOMPOSE: ClassVar[Any]
        FCD: ClassVar[Any]
        @staticmethod
        def values() -> Any: ...
        @staticmethod
        def valueOf(p0: str) -> Any: ...
