from typing import Any, ClassVar, overload
from android.icu.util.ULocale import ULocale
from java.util.Locale import Locale

class NumberingSystem:
    LATIN: ClassVar["NumberingSystem"]
    def __init__(self) -> None: ...
    @staticmethod
    def getAvailableNames() -> Any: ...
    @staticmethod
    def getInstanceByName(p0: str) -> "NumberingSystem": ...
    def getRadix(self) -> int: ...
    def isAlgorithmic(self) -> bool: ...
    @staticmethod
    def isValidDigitString(p0: str) -> bool: ...
    def getName(self) -> str: ...
    @overload
    @staticmethod
    def getInstance(p0: Locale) -> "NumberingSystem": ...
    @overload
    @staticmethod
    def getInstance() -> "NumberingSystem": ...
    @overload
    @staticmethod
    def getInstance(p0: ULocale) -> "NumberingSystem": ...
    @overload
    @staticmethod
    def getInstance(p0: int, p1: bool, p2: str) -> "NumberingSystem": ...
    def getDescription(self) -> str: ...
