from typing import Any, ClassVar, overload
from android.icu.text.Replaceable import Replaceable
from android.icu.text.SymbolTable import SymbolTable
from java.lang.Iterable import Iterable
from java.lang.StringBuffer import StringBuffer
from java.text.ParsePosition import ParsePosition
from java.util.Iterator import Iterator

class UnicodeSet:
    ADD_CASE_MAPPINGS: ClassVar[int]
    ALL_CODE_POINTS: ClassVar["UnicodeSet"]
    CASE: ClassVar[int]
    CASE_INSENSITIVE: ClassVar[int]
    EMPTY: ClassVar["UnicodeSet"]
    IGNORE_SPACE: ClassVar[int]
    MAX_VALUE: ClassVar[int]
    MIN_VALUE: ClassVar[int]
    ETHER: ClassVar[str]
    U_MATCH: ClassVar[int]
    U_MISMATCH: ClassVar[int]
    U_PARTIAL_MATCH: ClassVar[int]
    @overload
    def __init__(self, p0: str) -> None: ...
    @overload
    def __init__(self, p0: str, p1: bool) -> None: ...
    @overload
    def __init__(self, p0: str, p1: int) -> None: ...
    @overload
    def __init__(self, p0: str, p1: ParsePosition, p2: SymbolTable) -> None: ...
    @overload
    def __init__(self, p0: str, p1: ParsePosition, p2: SymbolTable, p3: int) -> None: ...
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, p0: "UnicodeSet") -> None: ...
    @overload
    def __init__(self, p0: int, p1: int) -> None: ...
    @overload
    def __init__(self, p0: Any) -> None: ...
    @overload
    def cloneAsThawed(self) -> Any: ...
    @overload
    def cloneAsThawed(self) -> "UnicodeSet": ...
    @overload
    def applyPattern(self, p0: str) -> "UnicodeSet": ...
    @overload
    def applyPattern(self, p0: str, p1: bool) -> "UnicodeSet": ...
    @overload
    def applyPattern(self, p0: str, p1: int) -> "UnicodeSet": ...
    @overload
    def _generatePattern(self, p0: StringBuffer, p1: bool) -> StringBuffer: ...
    @overload
    def _generatePattern(self, p0: StringBuffer, p1: bool, p2: bool) -> StringBuffer: ...
    def hasStrings(self) -> bool: ...
    @overload
    def complementAll(self, p0: str) -> "UnicodeSet": ...
    @overload
    def complementAll(self, p0: "UnicodeSet") -> "UnicodeSet": ...
    def removeAllStrings(self) -> "UnicodeSet": ...
    @staticmethod
    def fromAll(p0: str) -> "UnicodeSet": ...
    @overload
    def containsNone(self, p0: Iterable) -> bool: ...
    @overload
    def containsNone(self, p0: int, p1: int) -> bool: ...
    @overload
    def containsNone(self, p0: str) -> bool: ...
    @overload
    def containsNone(self, p0: "UnicodeSet") -> bool: ...
    @overload
    def containsSome(self, p0: str) -> bool: ...
    @overload
    def containsSome(self, p0: int, p1: int) -> bool: ...
    @overload
    def containsSome(self, p0: "UnicodeSet") -> bool: ...
    @overload
    def containsSome(self, p0: Iterable) -> bool: ...
    def getRangeCount(self) -> int: ...
    def getRangeStart(self, p0: int) -> int: ...
    def getRangeEnd(self, p0: int) -> int: ...
    def addAllTo(self, p0: list) -> list: ...
    def applyIntPropertyValue(self, p0: int, p1: int) -> "UnicodeSet": ...
    @overload
    def applyPropertyAlias(self, p0: str, p1: str) -> "UnicodeSet": ...
    @overload
    def applyPropertyAlias(self, p0: str, p1: str, p2: SymbolTable) -> "UnicodeSet": ...
    def closeOver(self, p0: int) -> "UnicodeSet": ...
    @overload
    def spanBack(self, p0: str, p1: int, p2: Any) -> int: ...
    @overload
    def spanBack(self, p0: str, p1: Any) -> int: ...
    def toPattern(self, p0: bool) -> str: ...
    def matchesIndexValue(self, p0: int) -> bool: ...
    def addMatchSetTo(self, p0: "UnicodeSet") -> None: ...
    def strings(self) -> list: ...
    @overload
    def span(self, p0: str, p1: Any) -> int: ...
    @overload
    def span(self, p0: str, p1: int, p2: Any) -> int: ...
    def ranges(self) -> Iterable: ...
    @overload
    def retain(self, p0: str) -> "UnicodeSet": ...
    @overload
    def retain(self, p0: int) -> "UnicodeSet": ...
    @overload
    def retain(self, p0: int, p1: int) -> "UnicodeSet": ...
    def isFrozen(self) -> bool: ...
    def compact(self) -> "UnicodeSet": ...
    @overload
    def removeAll(self, p0: "UnicodeSet") -> "UnicodeSet": ...
    @overload
    def removeAll(self, p0: str) -> "UnicodeSet": ...
    @overload
    def removeAll(self, p0: Iterable) -> "UnicodeSet": ...
    @overload
    def retainAll(self, p0: Iterable) -> "UnicodeSet": ...
    @overload
    def retainAll(self, p0: "UnicodeSet") -> "UnicodeSet": ...
    @overload
    def retainAll(self, p0: str) -> "UnicodeSet": ...
    @overload
    def complement(self, p0: int, p1: int) -> "UnicodeSet": ...
    @overload
    def complement(self, p0: int) -> "UnicodeSet": ...
    @overload
    def complement(self) -> "UnicodeSet": ...
    @overload
    def complement(self, p0: str) -> "UnicodeSet": ...
    @overload
    def containsAll(self, p0: "UnicodeSet") -> bool: ...
    @overload
    def containsAll(self, p0: Iterable) -> bool: ...
    @overload
    def containsAll(self, p0: str) -> bool: ...
    @overload
    def freeze(self) -> Any: ...
    @overload
    def freeze(self) -> "UnicodeSet": ...
    @overload
    def remove(self, p0: int) -> "UnicodeSet": ...
    @overload
    def remove(self, p0: int, p1: int) -> "UnicodeSet": ...
    @overload
    def remove(self, p0: str) -> "UnicodeSet": ...
    def size(self) -> int: ...
    def equals(self, p0: Any) -> bool: ...
    def toString(self) -> str: ...
    def hashCode(self) -> int: ...
    def clone(self) -> Any: ...
    @overload
    def compareTo(self, p0: "UnicodeSet") -> int: ...
    @overload
    def compareTo(self, p0: "UnicodeSet", p1: Any) -> int: ...
    @overload
    def compareTo(self, p0: Any) -> int: ...
    @overload
    def compareTo(self, p0: Iterable) -> int: ...
    def indexOf(self, p0: int) -> int: ...
    def clear(self) -> "UnicodeSet": ...
    def charAt(self, p0: int) -> int: ...
    def isEmpty(self) -> bool: ...
    def matches(self, p0: Replaceable, p1: Any, p2: int, p3: bool) -> int: ...
    @overload
    def add(self, p0: int, p1: int) -> "UnicodeSet": ...
    @overload
    def add(self, p0: Iterable) -> "UnicodeSet": ...
    @overload
    def add(self, p0: int) -> "UnicodeSet": ...
    @overload
    def add(self, p0: str) -> "UnicodeSet": ...
    def iterator(self) -> Iterator: ...
    @overload
    def contains(self, p0: int) -> bool: ...
    @overload
    def contains(self, p0: int, p1: int) -> bool: ...
    @overload
    def contains(self, p0: str) -> bool: ...
    @staticmethod
    def from_(p0: str) -> "UnicodeSet": ...
    @overload
    def addAll(self, p0: int, p1: int) -> "UnicodeSet": ...
    @overload
    def addAll(self, p0: str) -> "UnicodeSet": ...
    @overload
    def addAll(self, p0: "UnicodeSet") -> "UnicodeSet": ...
    @overload
    def addAll(self, p0: Iterable) -> "UnicodeSet": ...
    @overload
    def addAll(self, p0: Any) -> "UnicodeSet": ...
    @overload
    def set(self, p0: "UnicodeSet") -> "UnicodeSet": ...
    @overload
    def set(self, p0: int, p1: int) -> "UnicodeSet": ...

    class SpanCondition:
        NOT_CONTAINED: ClassVar["SpanCondition"]
        CONTAINED: ClassVar["SpanCondition"]
        SIMPLE: ClassVar["SpanCondition"]
        CONDITION_COUNT: ClassVar["SpanCondition"]
        NOT_CONTAINED: ClassVar[Any]
        CONTAINED: ClassVar[Any]
        SIMPLE: ClassVar[Any]
        CONDITION_COUNT: ClassVar[Any]
        @staticmethod
        def values() -> Any: ...
        @staticmethod
        def valueOf(p0: str) -> Any: ...

    class EntryRange:
        codepoint: int
        codepointEnd: int
        def toString(self) -> str: ...

    class ComparisonStyle:
        SHORTER_FIRST: ClassVar["ComparisonStyle"]
        LEXICOGRAPHIC: ClassVar["ComparisonStyle"]
        LONGER_FIRST: ClassVar["ComparisonStyle"]
        SHORTER_FIRST: ClassVar[Any]
        LEXICOGRAPHIC: ClassVar[Any]
        LONGER_FIRST: ClassVar[Any]
        @staticmethod
        def values() -> Any: ...
        @staticmethod
        def valueOf(p0: str) -> Any: ...
