from typing import Any, ClassVar, overload
from android.icu.text.UnicodeSet import UnicodeSet

class UnicodeSetSpanner:
    def __init__(self, p0: UnicodeSet) -> None: ...
    def getUnicodeSet(self) -> UnicodeSet: ...
    @overload
    def countIn(self, p0: str, p1: Any, p2: Any) -> int: ...
    @overload
    def countIn(self, p0: str, p1: Any) -> int: ...
    @overload
    def countIn(self, p0: str) -> int: ...
    @overload
    def deleteFrom(self, p0: str, p1: Any) -> str: ...
    @overload
    def deleteFrom(self, p0: str) -> str: ...
    @overload
    def replaceFrom(self, p0: str, p1: str, p2: Any, p3: Any) -> str: ...
    @overload
    def replaceFrom(self, p0: str, p1: str) -> str: ...
    @overload
    def replaceFrom(self, p0: str, p1: str, p2: Any) -> str: ...
    def equals(self, p0: Any) -> bool: ...
    def hashCode(self) -> int: ...
    @overload
    def trim(self, p0: str, p1: Any, p2: Any) -> str: ...
    @overload
    def trim(self, p0: str, p1: Any) -> str: ...
    @overload
    def trim(self, p0: str) -> str: ...

    class TrimOption:
        LEADING: ClassVar["TrimOption"]
        BOTH: ClassVar["TrimOption"]
        TRAILING: ClassVar["TrimOption"]
        LEADING: ClassVar[Any]
        BOTH: ClassVar[Any]
        TRAILING: ClassVar[Any]
        @staticmethod
        def values() -> Any: ...
        @staticmethod
        def valueOf(p0: str) -> Any: ...

    class CountMethod:
        WHOLE_SPAN: ClassVar["CountMethod"]
        MIN_ELEMENTS: ClassVar["CountMethod"]
        WHOLE_SPAN: ClassVar[Any]
        MIN_ELEMENTS: ClassVar[Any]
        @staticmethod
        def values() -> Any: ...
        @staticmethod
        def valueOf(p0: str) -> Any: ...
