from typing import Any, ClassVar, overload
from android.net.http.HeaderBlock import HeaderBlock

class UrlResponseInfo:
    def __init__(self) -> None: ...
    def getHeaders(self) -> HeaderBlock: ...
    def getHttpStatusText(self) -> str: ...
    def getHttpStatusCode(self) -> int: ...
    def wasCached(self) -> bool: ...
    def getUrlChain(self) -> list: ...
    def getNegotiatedProtocol(self) -> str: ...
    def getReceivedByteCount(self) -> int: ...
    def getUrl(self) -> str: ...
