from typing import Any, ClassVar, overload
from android.print.PrintJobId import PrintJobId
from android.print.PrintJobInfo import PrintJobInfo
from android.printservice.PrintDocument import PrintDocument

class PrintJob:
    def isCancelled(self) -> bool: ...
    def isCompleted(self) -> bool: ...
    def getDocument(self) -> PrintDocument: ...
    def isFailed(self) -> bool: ...
    def getAdvancedStringOption(self, p0: str) -> str: ...
    def hasAdvancedOption(self, p0: str) -> bool: ...
    def getAdvancedIntOption(self, p0: str) -> int: ...
    def getInfo(self) -> PrintJobInfo: ...
    @overload
    def setStatus(self, p0: str) -> None: ...
    @overload
    def setStatus(self, p0: int) -> None: ...
    def isBlocked(self) -> bool: ...
    def equals(self, p0: Any) -> bool: ...
    def hashCode(self) -> int: ...
    def start(self) -> bool: ...
    def getId(self) -> PrintJobId: ...
    def cancel(self) -> bool: ...
    def block(self, p0: str) -> bool: ...
    def isQueued(self) -> bool: ...
    def isStarted(self) -> bool: ...
    def fail(self, p0: str) -> bool: ...
    def complete(self) -> bool: ...
    def getTag(self) -> str: ...
    def setTag(self, p0: str) -> bool: ...
    def setProgress(self, p0: float) -> None: ...
