from typing import Any, ClassVar, overload
from java.util.function.IntBinaryOperator import IntBinaryOperator
from java.util.function.IntUnaryOperator import IntUnaryOperator

class AtomicInteger:
    @overload
    def __init__(self, p0: int) -> None: ...
    @overload
    def __init__(self) -> None: ...
    def getOpaque(self) -> int: ...
    def setOpaque(self, p0: int) -> None: ...
    def getAcquire(self) -> int: ...
    def setRelease(self, p0: int) -> None: ...
    def compareAndSet(self, p0: int, p1: int) -> bool: ...
    def compareAndExchange(self, p0: int, p1: int) -> int: ...
    def compareAndExchangeAcquire(self, p0: int, p1: int) -> int: ...
    def compareAndExchangeRelease(self, p0: int, p1: int) -> int: ...
    def weakCompareAndSetPlain(self, p0: int, p1: int) -> bool: ...
    def weakCompareAndSet(self, p0: int, p1: int) -> bool: ...
    def weakCompareAndSetAcquire(self, p0: int, p1: int) -> bool: ...
    def weakCompareAndSetRelease(self, p0: int, p1: int) -> bool: ...
    def getAndSet(self, p0: int) -> int: ...
    def getAndAdd(self, p0: int) -> int: ...
    def lazySet(self, p0: int) -> None: ...
    def incrementAndGet(self) -> int: ...
    def weakCompareAndSetVolatile(self, p0: int, p1: int) -> bool: ...
    def getAndIncrement(self) -> int: ...
    def getAndDecrement(self) -> int: ...
    def decrementAndGet(self) -> int: ...
    def addAndGet(self, p0: int) -> int: ...
    def getAndUpdate(self, p0: IntUnaryOperator) -> int: ...
    def updateAndGet(self, p0: IntUnaryOperator) -> int: ...
    def getAndAccumulate(self, p0: int, p1: IntBinaryOperator) -> int: ...
    def accumulateAndGet(self, p0: int, p1: IntBinaryOperator) -> int: ...
    def getPlain(self) -> int: ...
    def setPlain(self, p0: int) -> None: ...
    def get(self) -> int: ...
    def toString(self) -> str: ...
    def intValue(self) -> int: ...
    def longValue(self) -> int: ...
    def floatValue(self) -> float: ...
    def doubleValue(self) -> float: ...
    def set(self, p0: int) -> None: ...
