from typing import Any, ClassVar, overload

class DoubleUnaryOperator:
    @staticmethod
    def identity() -> "DoubleUnaryOperator": ...
    def applyAsDouble(self, p0: float) -> float: ...
    def compose(self, p0: "DoubleUnaryOperator") -> "DoubleUnaryOperator": ...
    def andThen(self, p0: "DoubleUnaryOperator") -> "DoubleUnaryOperator": ...
