from typing import Any, ClassVar, overload
from android.content.ComponentName import ComponentName
from android.content.pm.PackageManager import PackageManager
from android.content.pm.ServiceInfo import ServiceInfo
from android.graphics.drawable.Drawable import Drawable
from android.os.Parcel import Parcel
from android.view.textservice.SpellCheckerSubtype import SpellCheckerSubtype

class SpellCheckerInfo:
    CREATOR: ClassVar[Any]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    def getSubtypeAt(self, p0: int) -> SpellCheckerSubtype: ...
    def getSubtypeCount(self) -> int: ...
    def getPackageName(self) -> str: ...
    def getId(self) -> str: ...
    def getComponent(self) -> ComponentName: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
    def describeContents(self) -> int: ...
    def loadIcon(self, p0: PackageManager) -> Drawable: ...
    def loadLabel(self, p0: PackageManager) -> str: ...
    def getSettingsActivity(self) -> str: ...
    def getServiceInfo(self) -> ServiceInfo: ...
