from typing import Any, ClassVar, overload
from android.net.wifi.WifiSsid import WifiSsid
from android.os.Parcel import Parcel

class PasnConfig:
    AKM_FILS_EAP_SHA256: ClassVar[int]
    AKM_FILS_EAP_SHA384: ClassVar[int]
    AKM_FT_EAP_SHA256: ClassVar[int]
    AKM_FT_EAP_SHA384: ClassVar[int]
    AKM_FT_PSK_SHA256: ClassVar[int]
    AKM_FT_PSK_SHA384: ClassVar[int]
    AKM_NONE: ClassVar[int]
    AKM_PASN: ClassVar[int]
    AKM_SAE: ClassVar[int]
    CIPHER_CCMP_128: ClassVar[int]
    CIPHER_CCMP_256: ClassVar[int]
    CIPHER_GCMP_128: ClassVar[int]
    CIPHER_GCMP_256: ClassVar[int]
    CIPHER_NONE: ClassVar[int]
    CREATOR: ClassVar[Any]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    def getPassword(self) -> str: ...
    def getWifiSsid(self) -> WifiSsid: ...
    def getBaseAkms(self) -> int: ...
    def getCiphers(self) -> int: ...
    def getPasnComebackCookie(self) -> Any: ...
    def equals(self, p0: Any) -> bool: ...
    def toString(self) -> str: ...
    def hashCode(self) -> int: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
    def describeContents(self) -> int: ...

    class Builder:
        def __init__(self, p0: int, p1: int) -> None: ...
        def setPasnComebackCookie(self, p0: Any) -> Any: ...
        def setPassword(self, p0: str) -> Any: ...
        def build(self) -> "PasnConfig": ...
        def setWifiSsid(self, p0: WifiSsid) -> Any: ...
