from typing import Any, ClassVar, overload
from java.io.BufferedReader import BufferedReader
from java.io.BufferedWriter import BufferedWriter
from java.io.InputStream import InputStream
from java.io.OutputStream import OutputStream
from java.lang.Iterable import Iterable
from java.nio.channels.SeekableByteChannel import SeekableByteChannel
from java.nio.charset.Charset import Charset
from java.nio.file.DirectoryStream import DirectoryStream
from java.nio.file.FileStore import FileStore
from java.nio.file.FileVisitor import FileVisitor
from java.nio.file.Path import Path
from java.nio.file.attribute.BasicFileAttributes import BasicFileAttributes
from java.nio.file.attribute.FileAttributeView import FileAttributeView
from java.nio.file.attribute.FileTime import FileTime
from java.nio.file.attribute.UserPrincipal import UserPrincipal
from java.util.function.BiPredicate import BiPredicate
from java.util.stream.Stream import Stream

class Files:
    @staticmethod
    def setOwner(p0: Path, p1: UserPrincipal) -> Path: ...
    @overload
    @staticmethod
    def createTempDirectory(p0: str, p1: Any) -> Path: ...
    @overload
    @staticmethod
    def createTempDirectory(p0: Path, p1: str, p2: Any) -> Path: ...
    @staticmethod
    def probeContentType(p0: Path) -> str: ...
    @overload
    @staticmethod
    def walkFileTree(p0: Path, p1: FileVisitor) -> Path: ...
    @overload
    @staticmethod
    def walkFileTree(p0: Path, p1: set, p2: int, p3: FileVisitor) -> Path: ...
    @overload
    @staticmethod
    def newBufferedReader(p0: Path) -> BufferedReader: ...
    @overload
    @staticmethod
    def newBufferedReader(p0: Path, p1: Charset) -> BufferedReader: ...
    @overload
    @staticmethod
    def newBufferedWriter(p0: Path, p1: Charset, p2: Any) -> BufferedWriter: ...
    @overload
    @staticmethod
    def newBufferedWriter(p0: Path, p1: Any) -> BufferedWriter: ...
    @overload
    @staticmethod
    def readString(p0: Path, p1: Charset) -> str: ...
    @overload
    @staticmethod
    def readString(p0: Path) -> str: ...
    @overload
    @staticmethod
    def readAllLines(p0: Path, p1: Charset) -> list: ...
    @overload
    @staticmethod
    def readAllLines(p0: Path) -> list: ...
    @overload
    @staticmethod
    def writeString(p0: Path, p1: str, p2: Any) -> Path: ...
    @overload
    @staticmethod
    def writeString(p0: Path, p1: str, p2: Charset, p3: Any) -> Path: ...
    @overload
    @staticmethod
    def newByteChannel(p0: Path, p1: set, p2: Any) -> SeekableByteChannel: ...
    @overload
    @staticmethod
    def newByteChannel(p0: Path, p1: Any) -> SeekableByteChannel: ...
    @staticmethod
    def isReadable(p0: Path) -> bool: ...
    @staticmethod
    def isWritable(p0: Path) -> bool: ...
    @staticmethod
    def isExecutable(p0: Path) -> bool: ...
    @overload
    @staticmethod
    def newDirectoryStream(p0: Path, p1: Any) -> DirectoryStream: ...
    @overload
    @staticmethod
    def newDirectoryStream(p0: Path) -> DirectoryStream: ...
    @overload
    @staticmethod
    def newDirectoryStream(p0: Path, p1: str) -> DirectoryStream: ...
    @staticmethod
    def createSymbolicLink(p0: Path, p1: Path, p2: Any) -> Path: ...
    @staticmethod
    def createLink(p0: Path, p1: Path) -> Path: ...
    @staticmethod
    def readSymbolicLink(p0: Path) -> Path: ...
    @staticmethod
    def setAttribute(p0: Path, p1: str, p2: Any, p3: Any) -> Path: ...
    @staticmethod
    def deleteIfExists(p0: Path) -> bool: ...
    @staticmethod
    def newInputStream(p0: Path, p1: Any) -> InputStream: ...
    @staticmethod
    def newOutputStream(p0: Path, p1: Any) -> OutputStream: ...
    @staticmethod
    def isSymbolicLink(p0: Path) -> bool: ...
    @staticmethod
    def getOwner(p0: Path, p1: Any) -> UserPrincipal: ...
    @staticmethod
    def exists(p0: Path, p1: Any) -> bool: ...
    @staticmethod
    def isDirectory(p0: Path, p1: Any) -> bool: ...
    @staticmethod
    def createFile(p0: Path, p1: Any) -> Path: ...
    @staticmethod
    def createDirectories(p0: Path, p1: Any) -> Path: ...
    @staticmethod
    def getAttribute(p0: Path, p1: str, p2: Any) -> Any: ...
    @staticmethod
    def getPosixFilePermissions(p0: Path, p1: Any) -> set: ...
    @staticmethod
    def setPosixFilePermissions(p0: Path, p1: set) -> Path: ...
    @staticmethod
    def notExists(p0: Path, p1: Any) -> bool: ...
    @overload
    @staticmethod
    def walk(p0: Path, p1: Any) -> Stream: ...
    @overload
    @staticmethod
    def walk(p0: Path, p1: int, p2: Any) -> Stream: ...
    @overload
    @staticmethod
    def readAttributes(p0: Path, p1: type, p2: Any) -> BasicFileAttributes: ...
    @overload
    @staticmethod
    def readAttributes(p0: Path, p1: str, p2: Any) -> dict: ...
    @staticmethod
    def getFileAttributeView(p0: Path, p1: type, p2: Any) -> FileAttributeView: ...
    @staticmethod
    def getFileStore(p0: Path) -> FileStore: ...
    @staticmethod
    def move(p0: Path, p1: Path, p2: Any) -> Path: ...
    @staticmethod
    def isSameFile(p0: Path, p1: Path) -> bool: ...
    @staticmethod
    def getLastModifiedTime(p0: Path, p1: Any) -> FileTime: ...
    @staticmethod
    def createDirectory(p0: Path, p1: Any) -> Path: ...
    @staticmethod
    def setLastModifiedTime(p0: Path, p1: FileTime) -> Path: ...
    @overload
    @staticmethod
    def createTempFile(p0: str, p1: str, p2: Any) -> Path: ...
    @overload
    @staticmethod
    def createTempFile(p0: Path, p1: str, p2: str, p3: Any) -> Path: ...
    @staticmethod
    def isRegularFile(p0: Path, p1: Any) -> bool: ...
    @staticmethod
    def size(p0: Path) -> int: ...
    @staticmethod
    def isHidden(p0: Path) -> bool: ...
    @staticmethod
    def mismatch(p0: Path, p1: Path) -> int: ...
    @overload
    @staticmethod
    def lines(p0: Path, p1: Charset) -> Stream: ...
    @overload
    @staticmethod
    def lines(p0: Path) -> Stream: ...
    @staticmethod
    def list(p0: Path) -> Stream: ...
    @staticmethod
    def find(p0: Path, p1: int, p2: BiPredicate, p3: Any) -> Stream: ...
    @overload
    @staticmethod
    def write(p0: Path, p1: Iterable, p2: Charset, p3: Any) -> Path: ...
    @overload
    @staticmethod
    def write(p0: Path, p1: Any, p2: Any) -> Path: ...
    @overload
    @staticmethod
    def write(p0: Path, p1: Iterable, p2: Any) -> Path: ...
    @staticmethod
    def delete(p0: Path) -> None: ...
    @staticmethod
    def readAllBytes(p0: Path) -> Any: ...
    @overload
    @staticmethod
    def copy(p0: InputStream, p1: Path, p2: Any) -> int: ...
    @overload
    @staticmethod
    def copy(p0: Path, p1: OutputStream) -> int: ...
    @overload
    @staticmethod
    def copy(p0: Path, p1: Path, p2: Any) -> Path: ...
