from typing import Any, ClassVar, overload
from java.io.IOException import IOException
from java.nio.file.FileVisitResult import FileVisitResult
from java.nio.file.attribute.BasicFileAttributes import BasicFileAttributes

class SimpleFileVisitor:
    def visitFile(self, p0: Any, p1: BasicFileAttributes) -> FileVisitResult: ...
    def visitFileFailed(self, p0: Any, p1: IOException) -> FileVisitResult: ...
    def preVisitDirectory(self, p0: Any, p1: BasicFileAttributes) -> FileVisitResult: ...
    def postVisitDirectory(self, p0: Any, p1: IOException) -> FileVisitResult: ...
