from typing import Any, ClassVar, overload
from java.io.InputStream import InputStream
from java.io.OutputStream import OutputStream
from java.util.prefs.NodeChangeListener import NodeChangeListener
from java.util.prefs.PreferenceChangeListener import PreferenceChangeListener

class Preferences:
    MAX_KEY_LENGTH: ClassVar[int]
    MAX_VALUE_LENGTH: ClassVar[int]
    MAX_NAME_LENGTH: ClassVar[int]
    def putByteArray(self, p0: str, p1: Any) -> None: ...
    def getByteArray(self, p0: str, p1: Any) -> Any: ...
    def sync(self) -> None: ...
    def removeNode(self) -> None: ...
    @staticmethod
    def userRoot() -> "Preferences": ...
    @staticmethod
    def systemRoot() -> "Preferences": ...
    @staticmethod
    def importPreferences(p0: InputStream) -> None: ...
    @staticmethod
    def userNodeForPackage(p0: type) -> "Preferences": ...
    @staticmethod
    def systemNodeForPackage(p0: type) -> "Preferences": ...
    def childrenNames(self) -> Any: ...
    def nodeExists(self, p0: str) -> bool: ...
    def absolutePath(self) -> str: ...
    def isUserNode(self) -> bool: ...
    def addPreferenceChangeListener(self, p0: PreferenceChangeListener) -> None: ...
    def removePreferenceChangeListener(self, p0: PreferenceChangeListener) -> None: ...
    def addNodeChangeListener(self, p0: NodeChangeListener) -> None: ...
    def removeNodeChangeListener(self, p0: NodeChangeListener) -> None: ...
    def exportNode(self, p0: OutputStream) -> None: ...
    def exportSubtree(self, p0: OutputStream) -> None: ...
    def node(self, p0: str) -> "Preferences": ...
    def name(self) -> str: ...
    def remove(self, p0: str) -> None: ...
    def parent(self) -> "Preferences": ...
    def get(self, p0: str, p1: str) -> str: ...
    def put(self, p0: str, p1: str) -> None: ...
    def toString(self) -> str: ...
    def getBoolean(self, p0: str, p1: bool) -> bool: ...
    def putBoolean(self, p0: str, p1: bool) -> None: ...
    def getInt(self, p0: str, p1: int) -> int: ...
    def putInt(self, p0: str, p1: int) -> None: ...
    def getLong(self, p0: str, p1: int) -> int: ...
    def putLong(self, p0: str, p1: int) -> None: ...
    def getFloat(self, p0: str, p1: float) -> float: ...
    def putFloat(self, p0: str, p1: float) -> None: ...
    def getDouble(self, p0: str, p1: float) -> float: ...
    def putDouble(self, p0: str, p1: float) -> None: ...
    def clear(self) -> None: ...
    def flush(self) -> None: ...
    def keys(self) -> Any: ...
