from typing import Any, ClassVar, overload
from android.os.Parcel import Parcel
from android.service.autofill.Transformation import Transformation
from android.widget.RemoteViews import RemoteViews

class BatchUpdates:
    CREATOR: ClassVar[Any]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    def toString(self) -> str: ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...

    class Builder:
        def __init__(self) -> None: ...
        def updateTemplate(self, p0: RemoteViews) -> Any: ...
        def transformChild(self, p0: int, p1: Transformation) -> Any: ...
        def build(self) -> "BatchUpdates": ...
