from typing import Any, ClassVar, overload
from android.os.Parcel import Parcel
from org.xmlpull.v1.XmlPullParser import XmlPullParser

class ApplicationMediaCapabilities:
    CREATOR: ClassVar[Any]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    def getSupportedHdrTypes(self) -> list: ...
    def getSupportedVideoMimeTypes(self) -> list: ...
    def getUnsupportedHdrTypes(self) -> list: ...
    def getUnsupportedVideoMimeTypes(self) -> list: ...
    def isFormatSpecified(self, p0: str) -> bool: ...
    def isHdrTypeSupported(self, p0: str) -> bool: ...
    def isVideoMimeTypeSupported(self, p0: str) -> bool: ...
    def toString(self) -> str: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
    def describeContents(self) -> int: ...
    @staticmethod
    def createFromXml(p0: XmlPullParser) -> "ApplicationMediaCapabilities": ...

    class Builder:
        def __init__(self) -> None: ...
        def addUnsupportedVideoMimeType(self, p0: str) -> Any: ...
        def addSupportedVideoMimeType(self, p0: str) -> Any: ...
        def addUnsupportedHdrType(self, p0: str) -> Any: ...
        def addSupportedHdrType(self, p0: str) -> Any: ...
        def build(self) -> "ApplicationMediaCapabilities": ...
