from typing import Any, ClassVar, overload
from android.media.AudioDeviceInfo import AudioDeviceInfo
from android.os.Handler import Handler

class AudioRouting:
    def getRoutedDevice(self) -> AudioDeviceInfo: ...
    def getPreferredDevice(self) -> AudioDeviceInfo: ...
    def addOnRoutingChangedListener(self, p0: Any, p1: Handler) -> None: ...
    def getRoutedDevices(self) -> list: ...
    def removeOnRoutingChangedListener(self, p0: Any) -> None: ...
    def setPreferredDevice(self, p0: AudioDeviceInfo) -> bool: ...

    class OnRoutingChangedListener:
        def onRoutingChanged(self, p0: "AudioRouting") -> None: ...
