from typing import Any, ClassVar, overload
from android.media.AudioMetadataMap import AudioMetadataMap

class AudioMetadataReadMap:
    def size(self) -> int: ...
    def get(self, p0: Any) -> Any: ...
    def containsKey(self, p0: Any) -> bool: ...
    def dup(self) -> AudioMetadataMap: ...
