from typing import Any, ClassVar, overload
from android.os.Parcel import Parcel

class AudioDescriptor:
    CREATOR: ClassVar[Any]
    STANDARD_EDID: ClassVar[int]
    STANDARD_NONE: ClassVar[int]
    STANDARD_SADB: ClassVar[int]
    STANDARD_VSADB: ClassVar[int]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    def getEncapsulationType(self) -> int: ...
    def equals(self, p0: Any) -> bool: ...
    def toString(self) -> str: ...
    def hashCode(self) -> int: ...
    def getDescriptor(self) -> Any: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
    def describeContents(self) -> int: ...
    def getStandard(self) -> int: ...
