# cython: language_level=3
# Generated by pyjnius-wrap cython — do not edit by hand.

from jni_core._core cimport (
    JavaObject, get_env, check_jni_exc,
    find_class_global, get_method_id, get_static_method_id,
    get_field_id, get_static_field_id, j_str, py_str,
)
from jni_core._dispatch cimport (
    jnicore_NewObjectA, jnicore_DeleteLocalRef,
    jnicore_CallVoidMethodA, jnicore_CallObjectMethodA,
    jnicore_CallBooleanMethodA, jnicore_CallByteMethodA,
    jnicore_CallCharMethodA, jnicore_CallShortMethodA,
    jnicore_CallIntMethodA, jnicore_CallLongMethodA,
    jnicore_CallFloatMethodA, jnicore_CallDoubleMethodA,
    jnicore_CallStaticVoidMethodA, jnicore_CallStaticObjectMethodA,
    jnicore_CallStaticBooleanMethodA, jnicore_CallStaticByteMethodA,
    jnicore_CallStaticCharMethodA, jnicore_CallStaticShortMethodA,
    jnicore_CallStaticIntMethodA, jnicore_CallStaticLongMethodA,
    jnicore_CallStaticFloatMethodA, jnicore_CallStaticDoubleMethodA,
    jnicore_GetObjectField, jnicore_SetObjectField,
    jnicore_GetBooleanField, jnicore_SetBooleanField,
    jnicore_GetByteField, jnicore_SetByteField,
    jnicore_GetCharField, jnicore_SetCharField,
    jnicore_GetShortField, jnicore_SetShortField,
    jnicore_GetIntField, jnicore_SetIntField,
    jnicore_GetLongField, jnicore_SetLongField,
    jnicore_GetFloatField, jnicore_SetFloatField,
    jnicore_GetDoubleField, jnicore_SetDoubleField,
    jnicore_GetStaticObjectField, jnicore_SetStaticObjectField,
    jnicore_GetStaticBooleanField, jnicore_SetStaticBooleanField,
    jnicore_GetStaticByteField, jnicore_SetStaticByteField,
    jnicore_GetStaticCharField, jnicore_SetStaticCharField,
    jnicore_GetStaticShortField, jnicore_SetStaticShortField,
    jnicore_GetStaticIntField, jnicore_SetStaticIntField,
    jnicore_GetStaticLongField, jnicore_SetStaticLongField,
    jnicore_GetStaticFloatField, jnicore_SetStaticFloatField,
    jnicore_GetStaticDoubleField, jnicore_SetStaticDoubleField,
)
from jni_core.jni cimport (
    jclass, jobject, jmethodID, jfieldID, jvalue, JNIEnv,
    jboolean, jbyte, jchar, jshort, jint, jlong, jfloat, jdouble, jstring,
)

include "jni_core/conversions.pxi"

__javaclass__ = "android/media/AudioPresentation"  # android.media.AudioPresentation

cdef jclass _cls_AudioPresentation = NULL
cdef jmethodID _m_AudioPresentation_getProgramId_0 = NULL
cdef jmethodID _m_AudioPresentation_getPresentationId_0 = NULL
cdef jmethodID _m_AudioPresentation_getMasteringIndication_0 = NULL
cdef jmethodID _m_AudioPresentation_hasAudioDescription_0 = NULL
cdef jmethodID _m_AudioPresentation_hasSpokenSubtitles_0 = NULL
cdef jmethodID _m_AudioPresentation_hasDialogueEnhancement_0 = NULL
cdef jmethodID _m_AudioPresentation_equals_0 = NULL
cdef jmethodID _m_AudioPresentation_toString_0 = NULL
cdef jmethodID _m_AudioPresentation_hashCode_0 = NULL
cdef jmethodID _m_AudioPresentation_getLocale_0 = NULL
cdef jmethodID _m_AudioPresentation_describeContents_0 = NULL
cdef jmethodID _m_AudioPresentation_writeToParcel_0 = NULL
cdef jmethodID _m_AudioPresentation_getLabels_0 = NULL
cdef jfieldID _sf_AudioPresentation_CONTENT_COMMENTARY = NULL
cdef jfieldID _sf_AudioPresentation_CONTENT_DIALOG = NULL
cdef jfieldID _sf_AudioPresentation_CONTENT_EMERGENCY = NULL
cdef jfieldID _sf_AudioPresentation_CONTENT_HEARING_IMPAIRED = NULL
cdef jfieldID _sf_AudioPresentation_CONTENT_MAIN = NULL
cdef jfieldID _sf_AudioPresentation_CONTENT_MUSIC_AND_EFFECTS = NULL
cdef jfieldID _sf_AudioPresentation_CONTENT_UNKNOWN = NULL
cdef jfieldID _sf_AudioPresentation_CONTENT_VISUALLY_IMPAIRED = NULL
cdef jfieldID _sf_AudioPresentation_CONTENT_VOICEOVER = NULL
cdef jfieldID _sf_AudioPresentation_CREATOR = NULL
cdef jfieldID _sf_AudioPresentation_MASTERED_FOR_3D = NULL
cdef jfieldID _sf_AudioPresentation_MASTERED_FOR_HEADPHONE = NULL
cdef jfieldID _sf_AudioPresentation_MASTERED_FOR_STEREO = NULL
cdef jfieldID _sf_AudioPresentation_MASTERED_FOR_SURROUND = NULL
cdef jfieldID _sf_AudioPresentation_MASTERING_NOT_INDICATED = NULL
cdef jfieldID _sf_AudioPresentation_PRESENTATION_ID_UNKNOWN = NULL
cdef jfieldID _sf_AudioPresentation_PROGRAM_ID_UNKNOWN = NULL
cdef jfieldID _sf_AudioPresentation_CONTENTS_FILE_DESCRIPTOR = NULL
cdef jfieldID _sf_AudioPresentation_PARCELABLE_WRITE_RETURN_VALUE = NULL

cdef int _ensure_ids_AudioPresentation(JNIEnv* env) except -1:
    global _cls_AudioPresentation, _m_AudioPresentation_getProgramId_0, _m_AudioPresentation_getPresentationId_0, _m_AudioPresentation_getMasteringIndication_0, _m_AudioPresentation_hasAudioDescription_0, _m_AudioPresentation_hasSpokenSubtitles_0, _m_AudioPresentation_hasDialogueEnhancement_0, _m_AudioPresentation_equals_0, _m_AudioPresentation_toString_0, _m_AudioPresentation_hashCode_0, _m_AudioPresentation_getLocale_0, _m_AudioPresentation_describeContents_0, _m_AudioPresentation_writeToParcel_0, _m_AudioPresentation_getLabels_0, _sf_AudioPresentation_CONTENT_COMMENTARY, _sf_AudioPresentation_CONTENT_DIALOG, _sf_AudioPresentation_CONTENT_EMERGENCY, _sf_AudioPresentation_CONTENT_HEARING_IMPAIRED, _sf_AudioPresentation_CONTENT_MAIN, _sf_AudioPresentation_CONTENT_MUSIC_AND_EFFECTS, _sf_AudioPresentation_CONTENT_UNKNOWN, _sf_AudioPresentation_CONTENT_VISUALLY_IMPAIRED, _sf_AudioPresentation_CONTENT_VOICEOVER, _sf_AudioPresentation_CREATOR, _sf_AudioPresentation_MASTERED_FOR_3D, _sf_AudioPresentation_MASTERED_FOR_HEADPHONE, _sf_AudioPresentation_MASTERED_FOR_STEREO, _sf_AudioPresentation_MASTERED_FOR_SURROUND, _sf_AudioPresentation_MASTERING_NOT_INDICATED, _sf_AudioPresentation_PRESENTATION_ID_UNKNOWN, _sf_AudioPresentation_PROGRAM_ID_UNKNOWN, _sf_AudioPresentation_CONTENTS_FILE_DESCRIPTOR, _sf_AudioPresentation_PARCELABLE_WRITE_RETURN_VALUE
    if _cls_AudioPresentation != NULL:
        return 0
    _cls_AudioPresentation = find_class_global(env, b"android/media/AudioPresentation")
    _m_AudioPresentation_getProgramId_0 = get_method_id(env, _cls_AudioPresentation, b"getProgramId", b"()I")
    _m_AudioPresentation_getPresentationId_0 = get_method_id(env, _cls_AudioPresentation, b"getPresentationId", b"()I")
    _m_AudioPresentation_getMasteringIndication_0 = get_method_id(env, _cls_AudioPresentation, b"getMasteringIndication", b"()I")
    _m_AudioPresentation_hasAudioDescription_0 = get_method_id(env, _cls_AudioPresentation, b"hasAudioDescription", b"()Z")
    _m_AudioPresentation_hasSpokenSubtitles_0 = get_method_id(env, _cls_AudioPresentation, b"hasSpokenSubtitles", b"()Z")
    _m_AudioPresentation_hasDialogueEnhancement_0 = get_method_id(env, _cls_AudioPresentation, b"hasDialogueEnhancement", b"()Z")
    _m_AudioPresentation_equals_0 = get_method_id(env, _cls_AudioPresentation, b"equals", b"(Ljava/lang/Object;)Z")
    _m_AudioPresentation_toString_0 = get_method_id(env, _cls_AudioPresentation, b"toString", b"()Ljava/lang/String;")
    _m_AudioPresentation_hashCode_0 = get_method_id(env, _cls_AudioPresentation, b"hashCode", b"()I")
    _m_AudioPresentation_getLocale_0 = get_method_id(env, _cls_AudioPresentation, b"getLocale", b"()Ljava/util/Locale;")
    _m_AudioPresentation_describeContents_0 = get_method_id(env, _cls_AudioPresentation, b"describeContents", b"()I")
    _m_AudioPresentation_writeToParcel_0 = get_method_id(env, _cls_AudioPresentation, b"writeToParcel", b"(Landroid/os/Parcel;I)V")
    _m_AudioPresentation_getLabels_0 = get_method_id(env, _cls_AudioPresentation, b"getLabels", b"()Ljava/util/Map;")
    _sf_AudioPresentation_CONTENT_COMMENTARY = get_static_field_id(env, _cls_AudioPresentation, b"CONTENT_COMMENTARY", b"I")
    _sf_AudioPresentation_CONTENT_DIALOG = get_static_field_id(env, _cls_AudioPresentation, b"CONTENT_DIALOG", b"I")
    _sf_AudioPresentation_CONTENT_EMERGENCY = get_static_field_id(env, _cls_AudioPresentation, b"CONTENT_EMERGENCY", b"I")
    _sf_AudioPresentation_CONTENT_HEARING_IMPAIRED = get_static_field_id(env, _cls_AudioPresentation, b"CONTENT_HEARING_IMPAIRED", b"I")
    _sf_AudioPresentation_CONTENT_MAIN = get_static_field_id(env, _cls_AudioPresentation, b"CONTENT_MAIN", b"I")
    _sf_AudioPresentation_CONTENT_MUSIC_AND_EFFECTS = get_static_field_id(env, _cls_AudioPresentation, b"CONTENT_MUSIC_AND_EFFECTS", b"I")
    _sf_AudioPresentation_CONTENT_UNKNOWN = get_static_field_id(env, _cls_AudioPresentation, b"CONTENT_UNKNOWN", b"I")
    _sf_AudioPresentation_CONTENT_VISUALLY_IMPAIRED = get_static_field_id(env, _cls_AudioPresentation, b"CONTENT_VISUALLY_IMPAIRED", b"I")
    _sf_AudioPresentation_CONTENT_VOICEOVER = get_static_field_id(env, _cls_AudioPresentation, b"CONTENT_VOICEOVER", b"I")
    _sf_AudioPresentation_CREATOR = get_static_field_id(env, _cls_AudioPresentation, b"CREATOR", b"Landroid/os/Parcelable$Creator;")
    _sf_AudioPresentation_MASTERED_FOR_3D = get_static_field_id(env, _cls_AudioPresentation, b"MASTERED_FOR_3D", b"I")
    _sf_AudioPresentation_MASTERED_FOR_HEADPHONE = get_static_field_id(env, _cls_AudioPresentation, b"MASTERED_FOR_HEADPHONE", b"I")
    _sf_AudioPresentation_MASTERED_FOR_STEREO = get_static_field_id(env, _cls_AudioPresentation, b"MASTERED_FOR_STEREO", b"I")
    _sf_AudioPresentation_MASTERED_FOR_SURROUND = get_static_field_id(env, _cls_AudioPresentation, b"MASTERED_FOR_SURROUND", b"I")
    _sf_AudioPresentation_MASTERING_NOT_INDICATED = get_static_field_id(env, _cls_AudioPresentation, b"MASTERING_NOT_INDICATED", b"I")
    _sf_AudioPresentation_PRESENTATION_ID_UNKNOWN = get_static_field_id(env, _cls_AudioPresentation, b"PRESENTATION_ID_UNKNOWN", b"I")
    _sf_AudioPresentation_PROGRAM_ID_UNKNOWN = get_static_field_id(env, _cls_AudioPresentation, b"PROGRAM_ID_UNKNOWN", b"I")
    _sf_AudioPresentation_CONTENTS_FILE_DESCRIPTOR = get_static_field_id(env, _cls_AudioPresentation, b"CONTENTS_FILE_DESCRIPTOR", b"I")
    _sf_AudioPresentation_PARCELABLE_WRITE_RETURN_VALUE = get_static_field_id(env, _cls_AudioPresentation, b"PARCELABLE_WRITE_RETURN_VALUE", b"I")
    return 0

cdef class AudioPresentation(JavaObject):
    """android.media.AudioPresentation"""

    def __init__(self, *args, **kwargs):
        raise TypeError("AudioPresentation has no public constructor")

    # Static field AudioPresentation.CONTENT_COMMENTARY
    @staticmethod
    def CONTENT_COMMENTARY() -> int:
        cdef JNIEnv* env = get_env()
        _ensure_ids_AudioPresentation(env)
        cdef jint _ret = jnicore_GetStaticIntField(env, _cls_AudioPresentation, _sf_AudioPresentation_CONTENT_COMMENTARY)
        check_jni_exc(env)
        return <int>_ret

    # Static field AudioPresentation.CONTENT_DIALOG
    @staticmethod
    def CONTENT_DIALOG() -> int:
        cdef JNIEnv* env = get_env()
        _ensure_ids_AudioPresentation(env)
        cdef jint _ret = jnicore_GetStaticIntField(env, _cls_AudioPresentation, _sf_AudioPresentation_CONTENT_DIALOG)
        check_jni_exc(env)
        return <int>_ret

    # Static field AudioPresentation.CONTENT_EMERGENCY
    @staticmethod
    def CONTENT_EMERGENCY() -> int:
        cdef JNIEnv* env = get_env()
        _ensure_ids_AudioPresentation(env)
        cdef jint _ret = jnicore_GetStaticIntField(env, _cls_AudioPresentation, _sf_AudioPresentation_CONTENT_EMERGENCY)
        check_jni_exc(env)
        return <int>_ret

    # Static field AudioPresentation.CONTENT_HEARING_IMPAIRED
    @staticmethod
    def CONTENT_HEARING_IMPAIRED() -> int:
        cdef JNIEnv* env = get_env()
        _ensure_ids_AudioPresentation(env)
        cdef jint _ret = jnicore_GetStaticIntField(env, _cls_AudioPresentation, _sf_AudioPresentation_CONTENT_HEARING_IMPAIRED)
        check_jni_exc(env)
        return <int>_ret

    # Static field AudioPresentation.CONTENT_MAIN
    @staticmethod
    def CONTENT_MAIN() -> int:
        cdef JNIEnv* env = get_env()
        _ensure_ids_AudioPresentation(env)
        cdef jint _ret = jnicore_GetStaticIntField(env, _cls_AudioPresentation, _sf_AudioPresentation_CONTENT_MAIN)
        check_jni_exc(env)
        return <int>_ret

    # Static field AudioPresentation.CONTENT_MUSIC_AND_EFFECTS
    @staticmethod
    def CONTENT_MUSIC_AND_EFFECTS() -> int:
        cdef JNIEnv* env = get_env()
        _ensure_ids_AudioPresentation(env)
        cdef jint _ret = jnicore_GetStaticIntField(env, _cls_AudioPresentation, _sf_AudioPresentation_CONTENT_MUSIC_AND_EFFECTS)
        check_jni_exc(env)
        return <int>_ret

    # Static field AudioPresentation.CONTENT_UNKNOWN
    @staticmethod
    def CONTENT_UNKNOWN() -> int:
        cdef JNIEnv* env = get_env()
        _ensure_ids_AudioPresentation(env)
        cdef jint _ret = jnicore_GetStaticIntField(env, _cls_AudioPresentation, _sf_AudioPresentation_CONTENT_UNKNOWN)
        check_jni_exc(env)
        return <int>_ret

    # Static field AudioPresentation.CONTENT_VISUALLY_IMPAIRED
    @staticmethod
    def CONTENT_VISUALLY_IMPAIRED() -> int:
        cdef JNIEnv* env = get_env()
        _ensure_ids_AudioPresentation(env)
        cdef jint _ret = jnicore_GetStaticIntField(env, _cls_AudioPresentation, _sf_AudioPresentation_CONTENT_VISUALLY_IMPAIRED)
        check_jni_exc(env)
        return <int>_ret

    # Static field AudioPresentation.CONTENT_VOICEOVER
    @staticmethod
    def CONTENT_VOICEOVER() -> int:
        cdef JNIEnv* env = get_env()
        _ensure_ids_AudioPresentation(env)
        cdef jint _ret = jnicore_GetStaticIntField(env, _cls_AudioPresentation, _sf_AudioPresentation_CONTENT_VOICEOVER)
        check_jni_exc(env)
        return <int>_ret

    # Static field AudioPresentation.CREATOR
    @staticmethod
    def CREATOR() -> object:
        cdef JNIEnv* env = get_env()
        _ensure_ids_AudioPresentation(env)
        cdef jobject _ret = jnicore_GetStaticObjectField(env, _cls_AudioPresentation, _sf_AudioPresentation_CREATOR)
        check_jni_exc(env)
        if _ret == NULL:
            return None
        cdef JavaObject _wrapped = JavaObject.__new__(JavaObject)
        _wrapped._adopt_local(env, _ret)
        return _wrapped

    # Static field AudioPresentation.MASTERED_FOR_3D
    @staticmethod
    def MASTERED_FOR_3D() -> int:
        cdef JNIEnv* env = get_env()
        _ensure_ids_AudioPresentation(env)
        cdef jint _ret = jnicore_GetStaticIntField(env, _cls_AudioPresentation, _sf_AudioPresentation_MASTERED_FOR_3D)
        check_jni_exc(env)
        return <int>_ret

    # Static field AudioPresentation.MASTERED_FOR_HEADPHONE
    @staticmethod
    def MASTERED_FOR_HEADPHONE() -> int:
        cdef JNIEnv* env = get_env()
        _ensure_ids_AudioPresentation(env)
        cdef jint _ret = jnicore_GetStaticIntField(env, _cls_AudioPresentation, _sf_AudioPresentation_MASTERED_FOR_HEADPHONE)
        check_jni_exc(env)
        return <int>_ret

    # Static field AudioPresentation.MASTERED_FOR_STEREO
    @staticmethod
    def MASTERED_FOR_STEREO() -> int:
        cdef JNIEnv* env = get_env()
        _ensure_ids_AudioPresentation(env)
        cdef jint _ret = jnicore_GetStaticIntField(env, _cls_AudioPresentation, _sf_AudioPresentation_MASTERED_FOR_STEREO)
        check_jni_exc(env)
        return <int>_ret

    # Static field AudioPresentation.MASTERED_FOR_SURROUND
    @staticmethod
    def MASTERED_FOR_SURROUND() -> int:
        cdef JNIEnv* env = get_env()
        _ensure_ids_AudioPresentation(env)
        cdef jint _ret = jnicore_GetStaticIntField(env, _cls_AudioPresentation, _sf_AudioPresentation_MASTERED_FOR_SURROUND)
        check_jni_exc(env)
        return <int>_ret

    # Static field AudioPresentation.MASTERING_NOT_INDICATED
    @staticmethod
    def MASTERING_NOT_INDICATED() -> int:
        cdef JNIEnv* env = get_env()
        _ensure_ids_AudioPresentation(env)
        cdef jint _ret = jnicore_GetStaticIntField(env, _cls_AudioPresentation, _sf_AudioPresentation_MASTERING_NOT_INDICATED)
        check_jni_exc(env)
        return <int>_ret

    # Static field AudioPresentation.PRESENTATION_ID_UNKNOWN
    @staticmethod
    def PRESENTATION_ID_UNKNOWN() -> int:
        cdef JNIEnv* env = get_env()
        _ensure_ids_AudioPresentation(env)
        cdef jint _ret = jnicore_GetStaticIntField(env, _cls_AudioPresentation, _sf_AudioPresentation_PRESENTATION_ID_UNKNOWN)
        check_jni_exc(env)
        return <int>_ret

    # Static field AudioPresentation.PROGRAM_ID_UNKNOWN
    @staticmethod
    def PROGRAM_ID_UNKNOWN() -> int:
        cdef JNIEnv* env = get_env()
        _ensure_ids_AudioPresentation(env)
        cdef jint _ret = jnicore_GetStaticIntField(env, _cls_AudioPresentation, _sf_AudioPresentation_PROGRAM_ID_UNKNOWN)
        check_jni_exc(env)
        return <int>_ret

    # Static field AudioPresentation.CONTENTS_FILE_DESCRIPTOR
    @staticmethod
    def CONTENTS_FILE_DESCRIPTOR() -> int:
        cdef JNIEnv* env = get_env()
        _ensure_ids_AudioPresentation(env)
        cdef jint _ret = jnicore_GetStaticIntField(env, _cls_AudioPresentation, _sf_AudioPresentation_CONTENTS_FILE_DESCRIPTOR)
        check_jni_exc(env)
        return <int>_ret

    # Static field AudioPresentation.PARCELABLE_WRITE_RETURN_VALUE
    @staticmethod
    def PARCELABLE_WRITE_RETURN_VALUE() -> int:
        cdef JNIEnv* env = get_env()
        _ensure_ids_AudioPresentation(env)
        cdef jint _ret = jnicore_GetStaticIntField(env, _cls_AudioPresentation, _sf_AudioPresentation_PARCELABLE_WRITE_RETURN_VALUE)
        check_jni_exc(env)
        return <int>_ret

    cdef jint _getProgramId(self) except *:
        cdef JNIEnv* env = get_env()
        _ensure_ids_AudioPresentation(env)
        cdef jvalue _args[1]  # zero-arg call; _args ignored by JNI
        cdef jint _ret = jnicore_CallIntMethodA(env, self._handle, _m_AudioPresentation_getProgramId_0, _args)
        check_jni_exc(env)
        return _ret

    def getProgramId(self) -> int:
        cdef JNIEnv* env = get_env()
        cdef jint _ret = 0
        _ret = self._getProgramId()
        return <int>_ret

    cdef jint _getPresentationId(self) except *:
        cdef JNIEnv* env = get_env()
        _ensure_ids_AudioPresentation(env)
        cdef jvalue _args[1]  # zero-arg call; _args ignored by JNI
        cdef jint _ret = jnicore_CallIntMethodA(env, self._handle, _m_AudioPresentation_getPresentationId_0, _args)
        check_jni_exc(env)
        return _ret

    def getPresentationId(self) -> int:
        cdef JNIEnv* env = get_env()
        cdef jint _ret = 0
        _ret = self._getPresentationId()
        return <int>_ret

    cdef jint _getMasteringIndication(self) except *:
        cdef JNIEnv* env = get_env()
        _ensure_ids_AudioPresentation(env)
        cdef jvalue _args[1]  # zero-arg call; _args ignored by JNI
        cdef jint _ret = jnicore_CallIntMethodA(env, self._handle, _m_AudioPresentation_getMasteringIndication_0, _args)
        check_jni_exc(env)
        return _ret

    def getMasteringIndication(self) -> int:
        cdef JNIEnv* env = get_env()
        cdef jint _ret = 0
        _ret = self._getMasteringIndication()
        return <int>_ret

    cdef jboolean _hasAudioDescription(self) except *:
        cdef JNIEnv* env = get_env()
        _ensure_ids_AudioPresentation(env)
        cdef jvalue _args[1]  # zero-arg call; _args ignored by JNI
        cdef jboolean _ret = jnicore_CallBooleanMethodA(env, self._handle, _m_AudioPresentation_hasAudioDescription_0, _args)
        check_jni_exc(env)
        return _ret

    def hasAudioDescription(self) -> bool:
        cdef JNIEnv* env = get_env()
        cdef jboolean _ret = 0
        _ret = self._hasAudioDescription()
        return jboolean_to_py(_ret)

    cdef jboolean _hasSpokenSubtitles(self) except *:
        cdef JNIEnv* env = get_env()
        _ensure_ids_AudioPresentation(env)
        cdef jvalue _args[1]  # zero-arg call; _args ignored by JNI
        cdef jboolean _ret = jnicore_CallBooleanMethodA(env, self._handle, _m_AudioPresentation_hasSpokenSubtitles_0, _args)
        check_jni_exc(env)
        return _ret

    def hasSpokenSubtitles(self) -> bool:
        cdef JNIEnv* env = get_env()
        cdef jboolean _ret = 0
        _ret = self._hasSpokenSubtitles()
        return jboolean_to_py(_ret)

    cdef jboolean _hasDialogueEnhancement(self) except *:
        cdef JNIEnv* env = get_env()
        _ensure_ids_AudioPresentation(env)
        cdef jvalue _args[1]  # zero-arg call; _args ignored by JNI
        cdef jboolean _ret = jnicore_CallBooleanMethodA(env, self._handle, _m_AudioPresentation_hasDialogueEnhancement_0, _args)
        check_jni_exc(env)
        return _ret

    def hasDialogueEnhancement(self) -> bool:
        cdef JNIEnv* env = get_env()
        cdef jboolean _ret = 0
        _ret = self._hasDialogueEnhancement()
        return jboolean_to_py(_ret)

    cdef jboolean _equals(self, jobject p0) except *:
        cdef JNIEnv* env = get_env()
        _ensure_ids_AudioPresentation(env)
        cdef jvalue _args[1]
        _args[0].l = p0
        cdef jboolean _ret = jnicore_CallBooleanMethodA(env, self._handle, _m_AudioPresentation_equals_0, _args)
        check_jni_exc(env)
        return _ret

    def equals(self, p0) -> bool:
        cdef JNIEnv* env = get_env()
        cdef jboolean _ret = 0
        cdef jobject _h0 = (<JavaObject?>p0)._handle if p0 is not None else <jobject>NULL
        _ret = self._equals(_h0)
        return jboolean_to_py(_ret)

    cdef jstring _toString(self) except? NULL:
        cdef JNIEnv* env = get_env()
        _ensure_ids_AudioPresentation(env)
        cdef jvalue _args[1]  # zero-arg call; _args ignored by JNI
        cdef jstring _ret = <jstring>jnicore_CallObjectMethodA(env, self._handle, _m_AudioPresentation_toString_0, _args)
        check_jni_exc(env)
        return <jstring>_ret

    def toString(self) -> str:
        cdef JNIEnv* env = get_env()
        cdef jstring _ret = NULL
        _ret = self._toString()
        return py_str(env, _ret)

    cdef jint _hashCode(self) except *:
        cdef JNIEnv* env = get_env()
        _ensure_ids_AudioPresentation(env)
        cdef jvalue _args[1]  # zero-arg call; _args ignored by JNI
        cdef jint _ret = jnicore_CallIntMethodA(env, self._handle, _m_AudioPresentation_hashCode_0, _args)
        check_jni_exc(env)
        return _ret

    def hashCode(self) -> int:
        cdef JNIEnv* env = get_env()
        cdef jint _ret = 0
        _ret = self._hashCode()
        return <int>_ret

    cdef jobject _getLocale(self) except? NULL:
        cdef JNIEnv* env = get_env()
        _ensure_ids_AudioPresentation(env)
        cdef jvalue _args[1]  # zero-arg call; _args ignored by JNI
        cdef jobject _ret = jnicore_CallObjectMethodA(env, self._handle, _m_AudioPresentation_getLocale_0, _args)
        check_jni_exc(env)
        return _ret

    def getLocale(self) -> object:
        cdef JNIEnv* env = get_env()
        cdef jobject _ret = NULL
        _ret = self._getLocale()
        if _ret == NULL:
            return None
        cdef JavaObject _wrapped = JavaObject.__new__(JavaObject)
        _wrapped._adopt_local(env, _ret)
        return _wrapped

    cdef jint _describeContents(self) except *:
        cdef JNIEnv* env = get_env()
        _ensure_ids_AudioPresentation(env)
        cdef jvalue _args[1]  # zero-arg call; _args ignored by JNI
        cdef jint _ret = jnicore_CallIntMethodA(env, self._handle, _m_AudioPresentation_describeContents_0, _args)
        check_jni_exc(env)
        return _ret

    def describeContents(self) -> int:
        cdef JNIEnv* env = get_env()
        cdef jint _ret = 0
        _ret = self._describeContents()
        return <int>_ret

    cdef void _writeToParcel(self, jobject p0, jint p1) except *:
        cdef JNIEnv* env = get_env()
        _ensure_ids_AudioPresentation(env)
        cdef jvalue _args[2]
        _args[0].l = p0
        _args[1].i = p1
        jnicore_CallVoidMethodA(env, self._handle, _m_AudioPresentation_writeToParcel_0, _args)
        check_jni_exc(env)

    def writeToParcel(self, p0, p1) -> None:
        cdef JNIEnv* env = get_env()
        cdef jobject _h0 = (<JavaObject?>p0)._handle if p0 is not None else <jobject>NULL
        cdef jint _c1 = py_to_jint(p1)
        self._writeToParcel(_h0, _c1)

    cdef jobject _getLabels(self) except? NULL:
        cdef JNIEnv* env = get_env()
        _ensure_ids_AudioPresentation(env)
        cdef jvalue _args[1]  # zero-arg call; _args ignored by JNI
        cdef jobject _ret = jnicore_CallObjectMethodA(env, self._handle, _m_AudioPresentation_getLabels_0, _args)
        check_jni_exc(env)
        return _ret

    def getLabels(self) -> object:
        cdef JNIEnv* env = get_env()
        cdef jobject _ret = NULL
        _ret = self._getLabels()
        if _ret == NULL:
            return None
        cdef JavaObject _wrapped = JavaObject.__new__(JavaObject)
        _wrapped._adopt_local(env, _ret)
        return _wrapped

# Nested class: android.media.AudioPresentation$Builder  (JNI: android/media/AudioPresentation$Builder)
cdef jclass _cls_Builder = NULL
cdef jmethodID _ctor_Builder_0 = NULL
cdef jmethodID _m_Builder_setProgramId_0 = NULL
cdef jmethodID _m_Builder_setMasteringIndication_0 = NULL
cdef jmethodID _m_Builder_setLabels_0 = NULL
cdef jmethodID _m_Builder_setHasAudioDescription_0 = NULL
cdef jmethodID _m_Builder_setHasSpokenSubtitles_0 = NULL
cdef jmethodID _m_Builder_setHasDialogueEnhancement_0 = NULL
cdef jmethodID _m_Builder_build_0 = NULL
cdef jmethodID _m_Builder_setLocale_0 = NULL

cdef int _ensure_ids_Builder(JNIEnv* env) except -1:
    global _cls_Builder, _ctor_Builder_0, _m_Builder_setProgramId_0, _m_Builder_setMasteringIndication_0, _m_Builder_setLabels_0, _m_Builder_setHasAudioDescription_0, _m_Builder_setHasSpokenSubtitles_0, _m_Builder_setHasDialogueEnhancement_0, _m_Builder_build_0, _m_Builder_setLocale_0
    if _cls_Builder != NULL:
        return 0
    _cls_Builder = find_class_global(env, b"android/media/AudioPresentation$Builder")
    _ctor_Builder_0 = get_method_id(env, _cls_Builder, b"<init>", b"(I)V")
    _m_Builder_setProgramId_0 = get_method_id(env, _cls_Builder, b"setProgramId", b"(I)Landroid/media/AudioPresentation$Builder;")
    _m_Builder_setMasteringIndication_0 = get_method_id(env, _cls_Builder, b"setMasteringIndication", b"(I)Landroid/media/AudioPresentation$Builder;")
    _m_Builder_setLabels_0 = get_method_id(env, _cls_Builder, b"setLabels", b"(Ljava/util/Map;)Landroid/media/AudioPresentation$Builder;")
    _m_Builder_setHasAudioDescription_0 = get_method_id(env, _cls_Builder, b"setHasAudioDescription", b"(Z)Landroid/media/AudioPresentation$Builder;")
    _m_Builder_setHasSpokenSubtitles_0 = get_method_id(env, _cls_Builder, b"setHasSpokenSubtitles", b"(Z)Landroid/media/AudioPresentation$Builder;")
    _m_Builder_setHasDialogueEnhancement_0 = get_method_id(env, _cls_Builder, b"setHasDialogueEnhancement", b"(Z)Landroid/media/AudioPresentation$Builder;")
    _m_Builder_build_0 = get_method_id(env, _cls_Builder, b"build", b"()Landroid/media/AudioPresentation;")
    _m_Builder_setLocale_0 = get_method_id(env, _cls_Builder, b"setLocale", b"(Landroid/icu/util/ULocale;)Landroid/media/AudioPresentation$Builder;")
    return 0

cdef class Builder(JavaObject):
    """android.media.AudioPresentation$Builder"""

    def __init__(self, p0):
        cdef JNIEnv* env = get_env()
        _ensure_ids_Builder(env)
        cdef jvalue _args[1]
        _args[0].i = py_to_jint(p0)
        cdef jobject _ret = jnicore_NewObjectA(env, _cls_Builder, _ctor_Builder_0, _args)
        check_jni_exc(env)
        self._adopt_local(env, _ret)

    cdef jobject _setProgramId(self, jint p0) except? NULL:
        cdef JNIEnv* env = get_env()
        _ensure_ids_Builder(env)
        cdef jvalue _args[1]
        _args[0].i = p0
        cdef jobject _ret = jnicore_CallObjectMethodA(env, self._handle, _m_Builder_setProgramId_0, _args)
        check_jni_exc(env)
        return _ret

    def setProgramId(self, p0) -> object:
        cdef JNIEnv* env = get_env()
        cdef jobject _ret = NULL
        cdef jint _c0 = py_to_jint(p0)
        _ret = self._setProgramId(_c0)
        if _ret == NULL:
            return None
        cdef JavaObject _wrapped = JavaObject.__new__(JavaObject)
        _wrapped._adopt_local(env, _ret)
        return _wrapped

    cdef jobject _setMasteringIndication(self, jint p0) except? NULL:
        cdef JNIEnv* env = get_env()
        _ensure_ids_Builder(env)
        cdef jvalue _args[1]
        _args[0].i = p0
        cdef jobject _ret = jnicore_CallObjectMethodA(env, self._handle, _m_Builder_setMasteringIndication_0, _args)
        check_jni_exc(env)
        return _ret

    def setMasteringIndication(self, p0) -> object:
        cdef JNIEnv* env = get_env()
        cdef jobject _ret = NULL
        cdef jint _c0 = py_to_jint(p0)
        _ret = self._setMasteringIndication(_c0)
        if _ret == NULL:
            return None
        cdef JavaObject _wrapped = JavaObject.__new__(JavaObject)
        _wrapped._adopt_local(env, _ret)
        return _wrapped

    cdef jobject _setLabels(self, jobject p0) except? NULL:
        cdef JNIEnv* env = get_env()
        _ensure_ids_Builder(env)
        cdef jvalue _args[1]
        _args[0].l = p0
        cdef jobject _ret = jnicore_CallObjectMethodA(env, self._handle, _m_Builder_setLabels_0, _args)
        check_jni_exc(env)
        return _ret

    def setLabels(self, p0) -> object:
        cdef JNIEnv* env = get_env()
        cdef jobject _ret = NULL
        cdef jobject _h0 = (<JavaObject?>p0)._handle if p0 is not None else <jobject>NULL
        _ret = self._setLabels(_h0)
        if _ret == NULL:
            return None
        cdef JavaObject _wrapped = JavaObject.__new__(JavaObject)
        _wrapped._adopt_local(env, _ret)
        return _wrapped

    cdef jobject _setHasAudioDescription(self, jboolean p0) except? NULL:
        cdef JNIEnv* env = get_env()
        _ensure_ids_Builder(env)
        cdef jvalue _args[1]
        _args[0].z = p0
        cdef jobject _ret = jnicore_CallObjectMethodA(env, self._handle, _m_Builder_setHasAudioDescription_0, _args)
        check_jni_exc(env)
        return _ret

    def setHasAudioDescription(self, p0) -> object:
        cdef JNIEnv* env = get_env()
        cdef jobject _ret = NULL
        cdef jboolean _c0 = py_to_jboolean(p0)
        _ret = self._setHasAudioDescription(_c0)
        if _ret == NULL:
            return None
        cdef JavaObject _wrapped = JavaObject.__new__(JavaObject)
        _wrapped._adopt_local(env, _ret)
        return _wrapped

    cdef jobject _setHasSpokenSubtitles(self, jboolean p0) except? NULL:
        cdef JNIEnv* env = get_env()
        _ensure_ids_Builder(env)
        cdef jvalue _args[1]
        _args[0].z = p0
        cdef jobject _ret = jnicore_CallObjectMethodA(env, self._handle, _m_Builder_setHasSpokenSubtitles_0, _args)
        check_jni_exc(env)
        return _ret

    def setHasSpokenSubtitles(self, p0) -> object:
        cdef JNIEnv* env = get_env()
        cdef jobject _ret = NULL
        cdef jboolean _c0 = py_to_jboolean(p0)
        _ret = self._setHasSpokenSubtitles(_c0)
        if _ret == NULL:
            return None
        cdef JavaObject _wrapped = JavaObject.__new__(JavaObject)
        _wrapped._adopt_local(env, _ret)
        return _wrapped

    cdef jobject _setHasDialogueEnhancement(self, jboolean p0) except? NULL:
        cdef JNIEnv* env = get_env()
        _ensure_ids_Builder(env)
        cdef jvalue _args[1]
        _args[0].z = p0
        cdef jobject _ret = jnicore_CallObjectMethodA(env, self._handle, _m_Builder_setHasDialogueEnhancement_0, _args)
        check_jni_exc(env)
        return _ret

    def setHasDialogueEnhancement(self, p0) -> object:
        cdef JNIEnv* env = get_env()
        cdef jobject _ret = NULL
        cdef jboolean _c0 = py_to_jboolean(p0)
        _ret = self._setHasDialogueEnhancement(_c0)
        if _ret == NULL:
            return None
        cdef JavaObject _wrapped = JavaObject.__new__(JavaObject)
        _wrapped._adopt_local(env, _ret)
        return _wrapped

    cdef jobject _build(self) except? NULL:
        cdef JNIEnv* env = get_env()
        _ensure_ids_Builder(env)
        cdef jvalue _args[1]  # zero-arg call; _args ignored by JNI
        cdef jobject _ret = jnicore_CallObjectMethodA(env, self._handle, _m_Builder_build_0, _args)
        check_jni_exc(env)
        return _ret

    def build(self) -> object:
        cdef JNIEnv* env = get_env()
        cdef jobject _ret = NULL
        _ret = self._build()
        if _ret == NULL:
            return None
        cdef JavaObject _wrapped = JavaObject.__new__(JavaObject)
        _wrapped._adopt_local(env, _ret)
        return _wrapped

    cdef jobject _setLocale(self, jobject p0) except? NULL:
        cdef JNIEnv* env = get_env()
        _ensure_ids_Builder(env)
        cdef jvalue _args[1]
        _args[0].l = p0
        cdef jobject _ret = jnicore_CallObjectMethodA(env, self._handle, _m_Builder_setLocale_0, _args)
        check_jni_exc(env)
        return _ret

    def setLocale(self, p0) -> object:
        cdef JNIEnv* env = get_env()
        cdef jobject _ret = NULL
        cdef jobject _h0 = (<JavaObject?>p0)._handle if p0 is not None else <jobject>NULL
        _ret = self._setLocale(_h0)
        if _ret == NULL:
            return None
        cdef JavaObject _wrapped = JavaObject.__new__(JavaObject)
        _wrapped._adopt_local(env, _ret)
        return _wrapped

