from typing import Any, ClassVar, overload
from android.media.metrics.LogSessionId import LogSessionId
from android.os.Handler import Handler
from android.os.PersistableBundle import PersistableBundle
from java.util.UUID import UUID
from java.util.concurrent.Executor import Executor

class MediaDrm:
    EVENT_KEY_EXPIRED: ClassVar[int]
    EVENT_KEY_REQUIRED: ClassVar[int]
    EVENT_PROVISION_REQUIRED: ClassVar[int]
    EVENT_SESSION_RECLAIMED: ClassVar[int]
    EVENT_VENDOR_DEFINED: ClassVar[int]
    HDCP_LEVEL_UNKNOWN: ClassVar[int]
    HDCP_NONE: ClassVar[int]
    HDCP_NO_DIGITAL_OUTPUT: ClassVar[int]
    HDCP_V1: ClassVar[int]
    HDCP_V2: ClassVar[int]
    HDCP_V2_1: ClassVar[int]
    HDCP_V2_2: ClassVar[int]
    HDCP_V2_3: ClassVar[int]
    KEY_TYPE_OFFLINE: ClassVar[int]
    KEY_TYPE_RELEASE: ClassVar[int]
    KEY_TYPE_STREAMING: ClassVar[int]
    OFFLINE_LICENSE_STATE_RELEASED: ClassVar[int]
    OFFLINE_LICENSE_STATE_UNKNOWN: ClassVar[int]
    OFFLINE_LICENSE_STATE_USABLE: ClassVar[int]
    PROPERTY_ALGORITHMS: ClassVar[str]
    PROPERTY_DESCRIPTION: ClassVar[str]
    PROPERTY_DEVICE_UNIQUE_ID: ClassVar[str]
    PROPERTY_VENDOR: ClassVar[str]
    PROPERTY_VERSION: ClassVar[str]
    SECURITY_LEVEL_HW_SECURE_ALL: ClassVar[int]
    SECURITY_LEVEL_HW_SECURE_CRYPTO: ClassVar[int]
    SECURITY_LEVEL_HW_SECURE_DECODE: ClassVar[int]
    SECURITY_LEVEL_SW_SECURE_CRYPTO: ClassVar[int]
    SECURITY_LEVEL_SW_SECURE_DECODE: ClassVar[int]
    SECURITY_LEVEL_UNKNOWN: ClassVar[int]
    def __init__(self, p0: UUID) -> None: ...
    def setPropertyString(self, p0: str, p1: str) -> None: ...
    def getSecurityLevel(self, p0: Any) -> int: ...
    def getKeyRequest(self, p0: Any, p1: Any, p2: str, p3: int, p4: dict) -> Any: ...
    def provideKeyResponse(self, p0: Any, p1: Any) -> Any: ...
    def restoreKeys(self, p0: Any, p1: Any) -> None: ...
    @overload
    @staticmethod
    def isCryptoSchemeSupported(p0: UUID, p1: str, p2: int) -> bool: ...
    @overload
    @staticmethod
    def isCryptoSchemeSupported(p0: UUID, p1: str) -> bool: ...
    @overload
    @staticmethod
    def isCryptoSchemeSupported(p0: UUID) -> bool: ...
    @staticmethod
    def getSupportedCryptoSchemes() -> list: ...
    @overload
    def setOnExpirationUpdateListener(self, p0: Any, p1: Handler) -> None: ...
    @overload
    def setOnExpirationUpdateListener(self, p0: Executor, p1: Any) -> None: ...
    def clearOnExpirationUpdateListener(self) -> None: ...
    @overload
    def setOnKeyStatusChangeListener(self, p0: Executor, p1: Any) -> None: ...
    @overload
    def setOnKeyStatusChangeListener(self, p0: Any, p1: Handler) -> None: ...
    def clearOnKeyStatusChangeListener(self) -> None: ...
    @overload
    def setOnSessionLostStateListener(self, p0: Any, p1: Handler) -> None: ...
    @overload
    def setOnSessionLostStateListener(self, p0: Executor, p1: Any) -> None: ...
    def clearOnSessionLostStateListener(self) -> None: ...
    def clearOnEventListener(self) -> None: ...
    def closeSession(self, p0: Any) -> None: ...
    def removeKeys(self, p0: Any) -> None: ...
    def queryKeyStatus(self, p0: Any) -> dict: ...
    def getProvisionRequest(self) -> Any: ...
    def provideProvisionResponse(self, p0: Any) -> None: ...
    def getOfflineLicenseKeySetIds(self) -> list: ...
    def removeOfflineLicense(self, p0: Any) -> None: ...
    def getOfflineLicenseState(self, p0: Any) -> int: ...
    def getSecureStops(self) -> list: ...
    def getSecureStopIds(self) -> list: ...
    def getSecureStop(self, p0: Any) -> Any: ...
    def releaseSecureStops(self, p0: Any) -> None: ...
    def removeSecureStop(self, p0: Any) -> None: ...
    def removeAllSecureStops(self) -> None: ...
    def releaseAllSecureStops(self) -> None: ...
    def getConnectedHdcpLevel(self) -> int: ...
    def getMaxHdcpLevel(self) -> int: ...
    def getOpenSessionCount(self) -> int: ...
    def getMaxSessionCount(self) -> int: ...
    @staticmethod
    def getMaxSecurityLevel() -> int: ...
    def getPropertyByteArray(self, p0: str) -> Any: ...
    def setPropertyByteArray(self, p0: str, p1: Any) -> None: ...
    def getCryptoSession(self, p0: Any, p1: str, p2: str) -> Any: ...
    @overload
    def requiresSecureDecoder(self, p0: str, p1: int) -> bool: ...
    @overload
    def requiresSecureDecoder(self, p0: str) -> bool: ...
    def getPlaybackComponent(self, p0: Any) -> Any: ...
    def getLogMessages(self) -> list: ...
    @overload
    def setOnEventListener(self, p0: Executor, p1: Any) -> None: ...
    @overload
    def setOnEventListener(self, p0: Any) -> None: ...
    @overload
    def setOnEventListener(self, p0: Any, p1: Handler) -> None: ...
    def close(self) -> None: ...
    def release(self) -> None: ...
    def getMetrics(self) -> PersistableBundle: ...
    @overload
    def openSession(self, p0: int) -> Any: ...
    @overload
    def openSession(self) -> Any: ...
    def getPropertyString(self, p0: str) -> str: ...

    class SessionException:
        ERROR_RESOURCE_CONTENTION: ClassVar[int]
        ERROR_UNKNOWN: ClassVar[int]
        def __init__(self, p0: int, p1: str) -> None: ...
        def getOemError(self) -> int: ...
        def getVendorError(self) -> int: ...
        def getErrorContext(self) -> int: ...
        def isTransient(self) -> bool: ...
        def getErrorCode(self) -> int: ...

    class ProvisionRequest:
        def getDefaultUrl(self) -> str: ...
        def getData(self) -> Any: ...

    class PlaybackComponent:
        def setLogSessionId(self, p0: LogSessionId) -> None: ...
        def getLogSessionId(self) -> LogSessionId: ...

    class OnSessionLostStateListener:
        def onSessionLostState(self, p0: "MediaDrm", p1: Any) -> None: ...

    class OnKeyStatusChangeListener:
        def onKeyStatusChange(self, p0: "MediaDrm", p1: Any, p2: list, p3: bool) -> None: ...

    class OnExpirationUpdateListener:
        def onExpirationUpdate(self, p0: "MediaDrm", p1: Any, p2: int) -> None: ...

    class OnEventListener:
        def onEvent(self, p0: "MediaDrm", p1: Any, p2: int, p3: int, p4: Any) -> None: ...

    class MetricsConstants:
        CLOSE_SESSION_ERROR_COUNT: ClassVar[str]
        CLOSE_SESSION_ERROR_LIST: ClassVar[str]
        CLOSE_SESSION_OK_COUNT: ClassVar[str]
        EVENT_KEY_EXPIRED_COUNT: ClassVar[str]
        EVENT_KEY_NEEDED_COUNT: ClassVar[str]
        EVENT_PROVISION_REQUIRED_COUNT: ClassVar[str]
        EVENT_SESSION_RECLAIMED_COUNT: ClassVar[str]
        EVENT_VENDOR_DEFINED_COUNT: ClassVar[str]
        GET_DEVICE_UNIQUE_ID_ERROR_COUNT: ClassVar[str]
        GET_DEVICE_UNIQUE_ID_ERROR_LIST: ClassVar[str]
        GET_DEVICE_UNIQUE_ID_OK_COUNT: ClassVar[str]
        GET_KEY_REQUEST_ERROR_COUNT: ClassVar[str]
        GET_KEY_REQUEST_ERROR_LIST: ClassVar[str]
        GET_KEY_REQUEST_OK_COUNT: ClassVar[str]
        GET_KEY_REQUEST_OK_TIME_MICROS: ClassVar[str]
        GET_PROVISION_REQUEST_ERROR_COUNT: ClassVar[str]
        GET_PROVISION_REQUEST_ERROR_LIST: ClassVar[str]
        GET_PROVISION_REQUEST_OK_COUNT: ClassVar[str]
        KEY_STATUS_EXPIRED_COUNT: ClassVar[str]
        KEY_STATUS_INTERNAL_ERROR_COUNT: ClassVar[str]
        KEY_STATUS_OUTPUT_NOT_ALLOWED_COUNT: ClassVar[str]
        KEY_STATUS_PENDING_COUNT: ClassVar[str]
        KEY_STATUS_USABLE_COUNT: ClassVar[str]
        OPEN_SESSION_ERROR_COUNT: ClassVar[str]
        OPEN_SESSION_ERROR_LIST: ClassVar[str]
        OPEN_SESSION_OK_COUNT: ClassVar[str]
        PROVIDE_KEY_RESPONSE_ERROR_COUNT: ClassVar[str]
        PROVIDE_KEY_RESPONSE_ERROR_LIST: ClassVar[str]
        PROVIDE_KEY_RESPONSE_OK_COUNT: ClassVar[str]
        PROVIDE_KEY_RESPONSE_OK_TIME_MICROS: ClassVar[str]
        PROVIDE_PROVISION_RESPONSE_ERROR_COUNT: ClassVar[str]
        PROVIDE_PROVISION_RESPONSE_ERROR_LIST: ClassVar[str]
        PROVIDE_PROVISION_RESPONSE_OK_COUNT: ClassVar[str]
        SESSION_END_TIMES_MS: ClassVar[str]
        SESSION_START_TIMES_MS: ClassVar[str]

    class MediaDrmStateException:
        def getDiagnosticInfo(self) -> str: ...
        def getOemError(self) -> int: ...
        def getVendorError(self) -> int: ...
        def getErrorContext(self) -> int: ...
        def isTransient(self) -> bool: ...
        def getErrorCode(self) -> int: ...

    class LogMessage:
        def toString(self) -> str: ...
        def getMessage(self) -> str: ...
        def getPriority(self) -> int: ...
        def getTimestampMillis(self) -> int: ...

    class KeyStatus:
        STATUS_EXPIRED: ClassVar[int]
        STATUS_INTERNAL_ERROR: ClassVar[int]
        STATUS_OUTPUT_NOT_ALLOWED: ClassVar[int]
        STATUS_PENDING: ClassVar[int]
        STATUS_USABLE: ClassVar[int]
        STATUS_USABLE_IN_FUTURE: ClassVar[int]
        def getKeyId(self) -> Any: ...
        def getStatusCode(self) -> int: ...

    class KeyRequest:
        REQUEST_TYPE_INITIAL: ClassVar[int]
        REQUEST_TYPE_NONE: ClassVar[int]
        REQUEST_TYPE_RELEASE: ClassVar[int]
        REQUEST_TYPE_RENEWAL: ClassVar[int]
        REQUEST_TYPE_UPDATE: ClassVar[int]
        def getDefaultUrl(self) -> str: ...
        def getRequestType(self) -> int: ...
        def getData(self) -> Any: ...

    class ErrorCodes:
        ERROR_CERTIFICATE_MALFORMED: ClassVar[int]
        ERROR_CERTIFICATE_MISSING: ClassVar[int]
        ERROR_CRYPTO_LIBRARY: ClassVar[int]
        ERROR_FRAME_TOO_LARGE: ClassVar[int]
        ERROR_GENERIC_OEM: ClassVar[int]
        ERROR_GENERIC_PLUGIN: ClassVar[int]
        ERROR_INIT_DATA: ClassVar[int]
        ERROR_INSUFFICIENT_OUTPUT_PROTECTION: ClassVar[int]
        ERROR_INSUFFICIENT_SECURITY: ClassVar[int]
        ERROR_KEY_EXPIRED: ClassVar[int]
        ERROR_KEY_NOT_LOADED: ClassVar[int]
        ERROR_LICENSE_PARSE: ClassVar[int]
        ERROR_LICENSE_POLICY: ClassVar[int]
        ERROR_LICENSE_RELEASE: ClassVar[int]
        ERROR_LICENSE_REQUEST_REJECTED: ClassVar[int]
        ERROR_LICENSE_RESTORE: ClassVar[int]
        ERROR_LICENSE_STATE: ClassVar[int]
        ERROR_LOST_STATE: ClassVar[int]
        ERROR_MEDIA_FRAMEWORK: ClassVar[int]
        ERROR_NO_KEY: ClassVar[int]
        ERROR_PROVISIONING_CERTIFICATE: ClassVar[int]
        ERROR_PROVISIONING_CONFIG: ClassVar[int]
        ERROR_PROVISIONING_PARSE: ClassVar[int]
        ERROR_PROVISIONING_REQUEST_REJECTED: ClassVar[int]
        ERROR_PROVISIONING_RETRY: ClassVar[int]
        ERROR_RESOURCE_BUSY: ClassVar[int]
        ERROR_RESOURCE_CONTENTION: ClassVar[int]
        ERROR_SECURE_STOP_RELEASE: ClassVar[int]
        ERROR_SESSION_NOT_OPENED: ClassVar[int]
        ERROR_STORAGE_READ: ClassVar[int]
        ERROR_STORAGE_WRITE: ClassVar[int]
        ERROR_UNKNOWN: ClassVar[int]
        ERROR_UNSUPPORTED_OPERATION: ClassVar[int]
        ERROR_ZERO_SUBSAMPLES: ClassVar[int]

    class CryptoSession:
        def decrypt(self, p0: Any, p1: Any, p2: Any) -> Any: ...
        def encrypt(self, p0: Any, p1: Any, p2: Any) -> Any: ...
        def sign(self, p0: Any, p1: Any) -> Any: ...
        def verify(self, p0: Any, p1: Any, p2: Any) -> bool: ...
