from typing import Any, ClassVar, overload
from android.content.Context import Context
from android.content.res.AssetFileDescriptor import AssetFileDescriptor
from android.media.AudioAttributes import AudioAttributes
from android.media.AudioDeviceInfo import AudioDeviceInfo
from android.media.MediaDataSource import MediaDataSource
from android.media.MediaFormat import MediaFormat
from android.media.MediaTimestamp import MediaTimestamp
from android.media.PlaybackParams import PlaybackParams
from android.media.SubtitleData import SubtitleData
from android.media.SyncParams import SyncParams
from android.media.TimedMetaData import TimedMetaData
from android.media.TimedText import TimedText
from android.media.VolumeShaper import VolumeShaper
from android.net.Uri import Uri
from android.os.Handler import Handler
from android.os.Parcel import Parcel
from android.os.PersistableBundle import PersistableBundle
from android.view.Surface import Surface
from android.view.SurfaceHolder import SurfaceHolder
from java.io.FileDescriptor import FileDescriptor
from java.util.UUID import UUID

class MediaPlayer:
    MEDIA_ERROR_IO: ClassVar[int]
    MEDIA_ERROR_MALFORMED: ClassVar[int]
    MEDIA_ERROR_NOT_VALID_FOR_PROGRESSIVE_PLAYBACK: ClassVar[int]
    MEDIA_ERROR_SERVER_DIED: ClassVar[int]
    MEDIA_ERROR_TIMED_OUT: ClassVar[int]
    MEDIA_ERROR_UNKNOWN: ClassVar[int]
    MEDIA_ERROR_UNSUPPORTED: ClassVar[int]
    MEDIA_INFO_AUDIO_NOT_PLAYING: ClassVar[int]
    MEDIA_INFO_BAD_INTERLEAVING: ClassVar[int]
    MEDIA_INFO_BUFFERING_END: ClassVar[int]
    MEDIA_INFO_BUFFERING_START: ClassVar[int]
    MEDIA_INFO_METADATA_UPDATE: ClassVar[int]
    MEDIA_INFO_NOT_SEEKABLE: ClassVar[int]
    MEDIA_INFO_STARTED_AS_NEXT: ClassVar[int]
    MEDIA_INFO_SUBTITLE_TIMED_OUT: ClassVar[int]
    MEDIA_INFO_UNKNOWN: ClassVar[int]
    MEDIA_INFO_UNSUPPORTED_SUBTITLE: ClassVar[int]
    MEDIA_INFO_VIDEO_NOT_PLAYING: ClassVar[int]
    MEDIA_INFO_VIDEO_RENDERING_START: ClassVar[int]
    MEDIA_INFO_VIDEO_TRACK_LAGGING: ClassVar[int]
    MEDIA_MIMETYPE_TEXT_SUBRIP: ClassVar[str]
    PREPARE_DRM_STATUS_PREPARATION_ERROR: ClassVar[int]
    PREPARE_DRM_STATUS_PROVISIONING_NETWORK_ERROR: ClassVar[int]
    PREPARE_DRM_STATUS_PROVISIONING_SERVER_ERROR: ClassVar[int]
    PREPARE_DRM_STATUS_SUCCESS: ClassVar[int]
    SEEK_CLOSEST: ClassVar[int]
    SEEK_CLOSEST_SYNC: ClassVar[int]
    SEEK_NEXT_SYNC: ClassVar[int]
    SEEK_PREVIOUS_SYNC: ClassVar[int]
    VIDEO_SCALING_MODE_SCALE_TO_FIT: ClassVar[int]
    VIDEO_SCALING_MODE_SCALE_TO_FIT_WITH_CROPPING: ClassVar[int]
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, p0: Context) -> None: ...
    def setLooping(self, p0: bool) -> None: ...
    def isLooping(self) -> bool: ...
    def setVolume(self, p0: float, p1: float) -> None: ...
    def setDisplay(self, p0: SurfaceHolder) -> None: ...
    def setVideoScalingMode(self, p0: int) -> None: ...
    @overload
    def setDataSource(self, p0: Context, p1: Uri) -> None: ...
    @overload
    def setDataSource(self, p0: Context, p1: Uri, p2: dict, p3: list) -> None: ...
    @overload
    def setDataSource(self, p0: Context, p1: Uri, p2: dict) -> None: ...
    @overload
    def setDataSource(self, p0: str) -> None: ...
    @overload
    def setDataSource(self, p0: AssetFileDescriptor) -> None: ...
    @overload
    def setDataSource(self, p0: MediaDataSource) -> None: ...
    @overload
    def setDataSource(self, p0: FileDescriptor) -> None: ...
    @overload
    def setDataSource(self, p0: FileDescriptor, p1: int, p2: int) -> None: ...
    def prepareAsync(self) -> None: ...
    def createVolumeShaper(self, p0: Any) -> VolumeShaper: ...
    def setPreferredDevice(self, p0: AudioDeviceInfo) -> bool: ...
    def getPreferredDevice(self) -> AudioDeviceInfo: ...
    def getRoutedDevice(self) -> AudioDeviceInfo: ...
    def addOnRoutingChangedListener(self, p0: Any, p1: Handler) -> None: ...
    def removeOnRoutingChangedListener(self, p0: Any) -> None: ...
    def setWakeMode(self, p0: Context, p1: int) -> None: ...
    def setScreenOnWhilePlaying(self, p0: bool) -> None: ...
    def getVideoWidth(self) -> int: ...
    def getVideoHeight(self) -> int: ...
    def setPlaybackParams(self, p0: PlaybackParams) -> None: ...
    def getPlaybackParams(self) -> PlaybackParams: ...
    def setSyncParams(self, p0: SyncParams) -> None: ...
    def getSyncParams(self) -> SyncParams: ...
    def setNextMediaPlayer(self, p0: "MediaPlayer") -> None: ...
    def setAudioStreamType(self, p0: int) -> None: ...
    def setAudioSessionId(self, p0: int) -> None: ...
    def attachAuxEffect(self, p0: int) -> None: ...
    def setAuxEffectSendLevel(self, p0: float) -> None: ...
    def getTrackInfo(self) -> Any: ...
    @overload
    def addTimedTextSource(self, p0: Context, p1: Uri, p2: str) -> None: ...
    @overload
    def addTimedTextSource(self, p0: FileDescriptor, p1: str) -> None: ...
    @overload
    def addTimedTextSource(self, p0: FileDescriptor, p1: int, p2: int, p3: str) -> None: ...
    @overload
    def addTimedTextSource(self, p0: str, p1: str) -> None: ...
    def getSelectedTrack(self, p0: int) -> int: ...
    def selectTrack(self, p0: int) -> None: ...
    def deselectTrack(self, p0: int) -> None: ...
    def setOnBufferingUpdateListener(self, p0: Any) -> None: ...
    def setOnSeekCompleteListener(self, p0: Any) -> None: ...
    def setOnVideoSizeChangedListener(self, p0: Any) -> None: ...
    def setOnTimedTextListener(self, p0: Any) -> None: ...
    @overload
    def setOnSubtitleDataListener(self, p0: Any, p1: Handler) -> None: ...
    @overload
    def setOnSubtitleDataListener(self, p0: Any) -> None: ...
    def clearOnSubtitleDataListener(self) -> None: ...
    @overload
    def setOnMediaTimeDiscontinuityListener(self, p0: Any) -> None: ...
    @overload
    def setOnMediaTimeDiscontinuityListener(self, p0: Any, p1: Handler) -> None: ...
    def clearOnMediaTimeDiscontinuityListener(self) -> None: ...
    def setOnTimedMetaDataAvailableListener(self, p0: Any) -> None: ...
    def setOnDrmConfigHelper(self, p0: Any) -> None: ...
    @overload
    def setOnDrmInfoListener(self, p0: Any) -> None: ...
    @overload
    def setOnDrmInfoListener(self, p0: Any, p1: Handler) -> None: ...
    @overload
    def setOnDrmPreparedListener(self, p0: Any, p1: Handler) -> None: ...
    @overload
    def setOnDrmPreparedListener(self, p0: Any) -> None: ...
    def getDrmInfo(self) -> Any: ...
    def prepareDrm(self, p0: UUID) -> None: ...
    def releaseDrm(self) -> None: ...
    def getKeyRequest(self, p0: Any, p1: Any, p2: str, p3: int, p4: dict) -> Any: ...
    def provideKeyResponse(self, p0: Any, p1: Any) -> Any: ...
    def restoreKeys(self, p0: Any) -> None: ...
    def getDrmPropertyString(self, p0: str) -> str: ...
    def setDrmPropertyString(self, p0: str, p1: str) -> None: ...
    def setSurface(self, p0: Surface) -> None: ...
    def reset(self) -> None: ...
    def start(self) -> None: ...
    def stop(self) -> None: ...
    @overload
    @staticmethod
    def create(p0: Context, p1: Uri, p2: SurfaceHolder, p3: AudioAttributes, p4: int) -> "MediaPlayer": ...
    @overload
    @staticmethod
    def create(p0: Context, p1: int) -> "MediaPlayer": ...
    @overload
    @staticmethod
    def create(p0: Context, p1: int, p2: AudioAttributes, p3: int) -> "MediaPlayer": ...
    @overload
    @staticmethod
    def create(p0: Context, p1: Uri, p2: SurfaceHolder) -> "MediaPlayer": ...
    @overload
    @staticmethod
    def create(p0: Context, p1: Uri) -> "MediaPlayer": ...
    def prepare(self) -> None: ...
    def setAudioAttributes(self, p0: AudioAttributes) -> None: ...
    @overload
    def seekTo(self, p0: int, p1: int) -> None: ...
    @overload
    def seekTo(self, p0: int) -> None: ...
    def pause(self) -> None: ...
    def setOnPreparedListener(self, p0: Any) -> None: ...
    def setOnCompletionListener(self, p0: Any) -> None: ...
    def setOnErrorListener(self, p0: Any) -> None: ...
    def setOnInfoListener(self, p0: Any) -> None: ...
    def getDuration(self) -> int: ...
    def getCurrentPosition(self) -> int: ...
    def isPlaying(self) -> bool: ...
    def getAudioSessionId(self) -> int: ...
    def release(self) -> None: ...
    def getTimestamp(self) -> MediaTimestamp: ...
    def getMetrics(self) -> PersistableBundle: ...

    class TrackInfo:
        MEDIA_TRACK_TYPE_AUDIO: ClassVar[int]
        MEDIA_TRACK_TYPE_METADATA: ClassVar[int]
        MEDIA_TRACK_TYPE_SUBTITLE: ClassVar[int]
        MEDIA_TRACK_TYPE_TIMEDTEXT: ClassVar[int]
        MEDIA_TRACK_TYPE_UNKNOWN: ClassVar[int]
        MEDIA_TRACK_TYPE_VIDEO: ClassVar[int]
        CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
        PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
        def getTrackType(self) -> int: ...
        def toString(self) -> str: ...
        def getLanguage(self) -> str: ...
        def describeContents(self) -> int: ...
        def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
        def getFormat(self) -> MediaFormat: ...

    class ProvisioningServerErrorException:
        def __init__(self, p0: str) -> None: ...

    class ProvisioningNetworkErrorException:
        def __init__(self, p0: str) -> None: ...

    class OnVideoSizeChangedListener:
        def onVideoSizeChanged(self, p0: "MediaPlayer", p1: int, p2: int) -> None: ...

    class OnTimedTextListener:
        def onTimedText(self, p0: "MediaPlayer", p1: TimedText) -> None: ...

    class OnTimedMetaDataAvailableListener:
        def onTimedMetaDataAvailable(self, p0: "MediaPlayer", p1: TimedMetaData) -> None: ...

    class OnSubtitleDataListener:
        def onSubtitleData(self, p0: "MediaPlayer", p1: SubtitleData) -> None: ...

    class OnSeekCompleteListener:
        def onSeekComplete(self, p0: "MediaPlayer") -> None: ...

    class OnPreparedListener:
        def onPrepared(self, p0: "MediaPlayer") -> None: ...

    class OnMediaTimeDiscontinuityListener:
        def onMediaTimeDiscontinuity(self, p0: "MediaPlayer", p1: MediaTimestamp) -> None: ...

    class OnInfoListener:
        def onInfo(self, p0: "MediaPlayer", p1: int, p2: int) -> bool: ...

    class OnErrorListener:
        def onError(self, p0: "MediaPlayer", p1: int, p2: int) -> bool: ...

    class OnDrmPreparedListener:
        def onDrmPrepared(self, p0: "MediaPlayer", p1: int) -> None: ...

    class OnDrmInfoListener:
        def onDrmInfo(self, p0: "MediaPlayer", p1: Any) -> None: ...

    class OnDrmConfigHelper:
        def onDrmConfig(self, p0: "MediaPlayer") -> None: ...

    class OnCompletionListener:
        def onCompletion(self, p0: "MediaPlayer") -> None: ...

    class OnBufferingUpdateListener:
        def onBufferingUpdate(self, p0: "MediaPlayer", p1: int) -> None: ...

    class NoDrmSchemeException:
        def __init__(self, p0: str) -> None: ...

    class MetricsConstants:
        CODEC_AUDIO: ClassVar[str]
        CODEC_VIDEO: ClassVar[str]
        DURATION: ClassVar[str]
        ERRORS: ClassVar[str]
        ERROR_CODE: ClassVar[str]
        FRAMES: ClassVar[str]
        FRAMES_DROPPED: ClassVar[str]
        HEIGHT: ClassVar[str]
        MIME_TYPE_AUDIO: ClassVar[str]
        MIME_TYPE_VIDEO: ClassVar[str]
        PLAYING: ClassVar[str]
        WIDTH: ClassVar[str]

    class DrmInfo:
        def getPssh(self) -> dict: ...
        def getSupportedSchemes(self) -> Any: ...
