from typing import Any, ClassVar, overload
from android.app.Activity import Activity
from android.content.Context import Context
from android.content.res.AssetFileDescriptor import AssetFileDescriptor
from android.database.Cursor import Cursor
from android.media.Ringtone import Ringtone
from android.net.Uri import Uri

class RingtoneManager:
    ACTION_RINGTONE_PICKER: ClassVar[str]
    EXTRA_RINGTONE_DEFAULT_URI: ClassVar[str]
    EXTRA_RINGTONE_EXISTING_URI: ClassVar[str]
    EXTRA_RINGTONE_INCLUDE_DRM: ClassVar[str]
    EXTRA_RINGTONE_PICKED_URI: ClassVar[str]
    EXTRA_RINGTONE_SHOW_DEFAULT: ClassVar[str]
    EXTRA_RINGTONE_SHOW_SILENT: ClassVar[str]
    EXTRA_RINGTONE_TITLE: ClassVar[str]
    EXTRA_RINGTONE_TYPE: ClassVar[str]
    ID_COLUMN_INDEX: ClassVar[int]
    TITLE_COLUMN_INDEX: ClassVar[int]
    TYPE_ALARM: ClassVar[int]
    TYPE_ALL: ClassVar[int]
    TYPE_NOTIFICATION: ClassVar[int]
    TYPE_RINGTONE: ClassVar[int]
    URI_COLUMN_INDEX: ClassVar[int]
    @overload
    def __init__(self, p0: Context) -> None: ...
    @overload
    def __init__(self, p0: Activity) -> None: ...
    def inferStreamType(self) -> int: ...
    def setStopPreviousRingtone(self, p0: bool) -> None: ...
    def stopPreviousRingtone(self) -> None: ...
    def getStopPreviousRingtone(self) -> bool: ...
    def getIncludeDrm(self) -> bool: ...
    def setIncludeDrm(self, p0: bool) -> None: ...
    @overload
    def getRingtone(self, p0: int) -> Ringtone: ...
    @overload
    @staticmethod
    def getRingtone(p0: Context, p1: Uri) -> Ringtone: ...
    def getRingtoneUri(self, p0: int) -> Uri: ...
    def getRingtonePosition(self, p0: Uri) -> int: ...
    @staticmethod
    def getValidRingtoneUri(p0: Context) -> Uri: ...
    @staticmethod
    def getActualDefaultRingtoneUri(p0: Context, p1: int) -> Uri: ...
    @staticmethod
    def setActualDefaultRingtoneUri(p0: Context, p1: int, p2: Uri) -> None: ...
    @staticmethod
    def getDefaultType(p0: Uri) -> int: ...
    @staticmethod
    def getDefaultUri(p0: int) -> Uri: ...
    @staticmethod
    def openDefaultRingtoneUri(p0: Context, p1: Uri) -> AssetFileDescriptor: ...
    @overload
    @staticmethod
    def hasHapticChannels(p0: Uri) -> bool: ...
    @overload
    def hasHapticChannels(self, p0: int) -> bool: ...
    @overload
    @staticmethod
    def hasHapticChannels(p0: Context, p1: Uri) -> bool: ...
    @staticmethod
    def isDefault(p0: Uri) -> bool: ...
    def setType(self, p0: int) -> None: ...
    def getCursor(self) -> Cursor: ...
