from typing import Any, ClassVar, overload
from android.content.Context import Context
from android.media.AudioAttributes import AudioAttributes

class Ringtone:
    def getAudioAttributes(self) -> AudioAttributes: ...
    def play(self) -> None: ...
    def getStreamType(self) -> int: ...
    def setStreamType(self, p0: int) -> None: ...
    def isLooping(self) -> bool: ...
    def isHapticGeneratorEnabled(self) -> bool: ...
    def setHapticGeneratorEnabled(self, p0: bool) -> bool: ...
    def setLooping(self, p0: bool) -> None: ...
    def setVolume(self, p0: float) -> None: ...
    def isPlaying(self) -> bool: ...
    def setAudioAttributes(self, p0: AudioAttributes) -> None: ...
    def stop(self) -> None: ...
    def getVolume(self) -> float: ...
    def getTitle(self, p0: Context) -> str: ...
