from typing import Any, ClassVar, overload
from android.content.ComponentName import ComponentName
from android.os.Parcel import Parcel

class RouteListingPreference:
    ACTION_TRANSFER_MEDIA: ClassVar[str]
    CREATOR: ClassVar[Any]
    EXTRA_ROUTE_ID: ClassVar[str]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    def getUseSystemOrdering(self) -> bool: ...
    def getLinkedItemComponentName(self) -> ComponentName: ...
    def getItems(self) -> list: ...
    def equals(self, p0: Any) -> bool: ...
    def hashCode(self) -> int: ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...

    class Item:
        CREATOR: ClassVar[Any]
        FLAG_ONGOING_SESSION: ClassVar[int]
        FLAG_ONGOING_SESSION_MANAGED: ClassVar[int]
        FLAG_SUGGESTED: ClassVar[int]
        SELECTION_BEHAVIOR_GO_TO_APP: ClassVar[int]
        SELECTION_BEHAVIOR_NONE: ClassVar[int]
        SELECTION_BEHAVIOR_TRANSFER: ClassVar[int]
        SUBTEXT_AD_ROUTING_DISALLOWED: ClassVar[int]
        SUBTEXT_CUSTOM: ClassVar[int]
        SUBTEXT_DEVICE_LOW_POWER: ClassVar[int]
        SUBTEXT_DOWNLOADED_CONTENT_ROUTING_DISALLOWED: ClassVar[int]
        SUBTEXT_ERROR_UNKNOWN: ClassVar[int]
        SUBTEXT_NONE: ClassVar[int]
        SUBTEXT_SUBSCRIPTION_REQUIRED: ClassVar[int]
        SUBTEXT_TRACK_UNSUPPORTED: ClassVar[int]
        SUBTEXT_UNAUTHORIZED: ClassVar[int]
        CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
        PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
        def getRouteId(self) -> str: ...
        def getSelectionBehavior(self) -> int: ...
        def getSubText(self) -> int: ...
        def getCustomSubtextMessage(self) -> str: ...
        def equals(self, p0: Any) -> bool: ...
        def hashCode(self) -> int: ...
        def getFlags(self) -> int: ...
        def describeContents(self) -> int: ...
        def writeToParcel(self, p0: Parcel, p1: int) -> None: ...

        class Builder:
            def __init__(self, p0: str) -> None: ...
            def setSelectionBehavior(self, p0: int) -> Any: ...
            def setCustomSubtextMessage(self, p0: str) -> Any: ...
            def build(self) -> Any: ...
            def setFlags(self, p0: int) -> Any: ...
            def setSubText(self, p0: int) -> Any: ...

    class Builder:
        def __init__(self) -> None: ...
        def setItems(self, p0: list) -> Any: ...
        def setLinkedItemComponentName(self, p0: ComponentName) -> Any: ...
        def setUseSystemOrdering(self, p0: bool) -> Any: ...
        def build(self) -> "RouteListingPreference": ...
