from typing import Any, ClassVar, overload
from android.os.Parcel import Parcel
from android.print.PrintAttributes import PrintAttributes
from android.print.PrintJobId import PrintJobId
from android.print.PrinterId import PrinterId

class PrintJobInfo:
    CREATOR: ClassVar[Any]
    STATE_BLOCKED: ClassVar[int]
    STATE_CANCELED: ClassVar[int]
    STATE_COMPLETED: ClassVar[int]
    STATE_CREATED: ClassVar[int]
    STATE_FAILED: ClassVar[int]
    STATE_QUEUED: ClassVar[int]
    STATE_STARTED: ClassVar[int]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    def getPages(self) -> Any: ...
    def getPrinterId(self) -> PrinterId: ...
    def getCopies(self) -> int: ...
    def getAdvancedStringOption(self, p0: str) -> str: ...
    def hasAdvancedOption(self, p0: str) -> bool: ...
    def getAdvancedIntOption(self, p0: str) -> int: ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
    def getLabel(self) -> str: ...
    def getAttributes(self) -> PrintAttributes: ...
    def getCreationTime(self) -> int: ...
    def toString(self) -> str: ...
    def getId(self) -> PrintJobId: ...
    def getState(self) -> int: ...

    class Builder:
        def __init__(self, p0: "PrintJobInfo") -> None: ...
        def setPages(self, p0: Any) -> None: ...
        @overload
        def putAdvancedOption(self, p0: str, p1: int) -> None: ...
        @overload
        def putAdvancedOption(self, p0: str, p1: str) -> None: ...
        def setCopies(self, p0: int) -> None: ...
        def setAttributes(self, p0: PrintAttributes) -> None: ...
        def build(self) -> "PrintJobInfo": ...
