from typing import Any, ClassVar, overload
from android.content.Context import Context
from android.security.ConfirmationCallback import ConfirmationCallback
from java.util.concurrent.Executor import Executor

class ConfirmationPrompt:
    def cancelPrompt(self) -> None: ...
    def presentPrompt(self, p0: Executor, p1: ConfirmationCallback) -> None: ...
    @staticmethod
    def isSupported(p0: Context) -> bool: ...

    class Builder:
        def __init__(self, p0: Context) -> None: ...
        def setExtraData(self, p0: Any) -> Any: ...
        def setPromptText(self, p0: str) -> Any: ...
        def build(self) -> "ConfirmationPrompt": ...
