from typing import Any, ClassVar, overload
from android.app.PendingIntent import PendingIntent
from android.graphics.drawable.Icon import Icon
from android.os.Parcel import Parcel

class Tile:
    CREATOR: ClassVar[Any]
    STATE_ACTIVE: ClassVar[int]
    STATE_INACTIVE: ClassVar[int]
    STATE_UNAVAILABLE: ClassVar[int]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    def updateTile(self) -> None: ...
    def getActivityLaunchForClick(self) -> PendingIntent: ...
    def setActivityLaunchForClick(self, p0: PendingIntent) -> None: ...
    def getState(self) -> int: ...
    def setState(self, p0: int) -> None: ...
    def getIcon(self) -> Icon: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
    def describeContents(self) -> int: ...
    def getLabel(self) -> str: ...
    def setIcon(self, p0: Icon) -> None: ...
    def getContentDescription(self) -> str: ...
    def getStateDescription(self) -> str: ...
    def setContentDescription(self, p0: str) -> None: ...
    def setStateDescription(self, p0: str) -> None: ...
    def getSubtitle(self) -> str: ...
    def setSubtitle(self, p0: str) -> None: ...
    def setLabel(self, p0: str) -> None: ...
