from typing import Any, ClassVar, overload
from android.os.Parcel import Parcel

class HomeSp:
    CREATOR: ClassVar[Any]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    @overload
    def __init__(self, p0: "HomeSp") -> None: ...
    @overload
    def __init__(self) -> None: ...
    def getFqdn(self) -> str: ...
    def getFriendlyName(self) -> str: ...
    def getOtherHomePartnersList(self) -> list: ...
    def getMatchAllOis(self) -> Any: ...
    def getMatchAnyOis(self) -> Any: ...
    def getRoamingConsortiumOis(self) -> Any: ...
    def setFqdn(self, p0: str) -> None: ...
    def setFriendlyName(self, p0: str) -> None: ...
    def setMatchAllOis(self, p0: Any) -> None: ...
    def setMatchAnyOis(self, p0: Any) -> None: ...
    def setOtherHomePartnersList(self, p0: list) -> None: ...
    def setRoamingConsortiumOis(self, p0: Any) -> None: ...
    def equals(self, p0: Any) -> bool: ...
    def toString(self) -> str: ...
    def hashCode(self) -> int: ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...

from typing import Any, ClassVar, overload
from android.os.Parcel import Parcel
from java.security.PrivateKey import PrivateKey
from java.security.cert.X509Certificate import X509Certificate

class Credential:
    CREATOR: ClassVar[Any]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    @overload
    def __init__(self, p0: "Credential") -> None: ...
    @overload
    def __init__(self) -> None: ...
    def setRealm(self, p0: str) -> None: ...
    def getCertCredential(self) -> Any: ...
    def getSimCredential(self) -> Any: ...
    def getUserCredential(self) -> Any: ...
    def setClientCertificateChain(self, p0: Any) -> None: ...
    def setCertCredential(self, p0: Any) -> None: ...
    def setClientPrivateKey(self, p0: PrivateKey) -> None: ...
    def setSimCredential(self, p0: Any) -> None: ...
    def setUserCredential(self, p0: Any) -> None: ...
    def equals(self, p0: Any) -> bool: ...
    def toString(self) -> str: ...
    def hashCode(self) -> int: ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
    def getCaCertificate(self) -> X509Certificate: ...
    def getClientCertificateChain(self) -> Any: ...
    def getClientPrivateKey(self) -> PrivateKey: ...
    def getMinimumTlsVersion(self) -> int: ...
    def getRealm(self) -> str: ...
    def setCaCertificate(self, p0: X509Certificate) -> None: ...
    def setMinimumTlsVersion(self, p0: int) -> None: ...

    class UserCredential:
        CREATOR: ClassVar[Any]
        CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
        PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
        @overload
        def __init__(self) -> None: ...
        @overload
        def __init__(self, p0: Any) -> None: ...
        def setUsername(self, p0: str) -> None: ...
        def getPassword(self) -> str: ...
        def getEapType(self) -> int: ...
        def setEapType(self, p0: int) -> None: ...
        def getNonEapInnerMethod(self) -> str: ...
        def setNonEapInnerMethod(self, p0: str) -> None: ...
        def getUsername(self) -> str: ...
        def equals(self, p0: Any) -> bool: ...
        def toString(self) -> str: ...
        def hashCode(self) -> int: ...
        def describeContents(self) -> int: ...
        def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
        def setPassword(self, p0: str) -> None: ...

    class SimCredential:
        CREATOR: ClassVar[Any]
        CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
        PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
        @overload
        def __init__(self) -> None: ...
        @overload
        def __init__(self, p0: Any) -> None: ...
        def getImsi(self) -> str: ...
        def getEapType(self) -> int: ...
        def setEapType(self, p0: int) -> None: ...
        def setImsi(self, p0: str) -> None: ...
        def equals(self, p0: Any) -> bool: ...
        def toString(self) -> str: ...
        def hashCode(self) -> int: ...
        def describeContents(self) -> int: ...
        def writeToParcel(self, p0: Parcel, p1: int) -> None: ...

    class CertificateCredential:
        CREATOR: ClassVar[Any]
        CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
        PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
        @overload
        def __init__(self) -> None: ...
        @overload
        def __init__(self, p0: Any) -> None: ...
        def getCertType(self) -> str: ...
        def setCertType(self, p0: str) -> None: ...
        def getCertSha256Fingerprint(self) -> Any: ...
        def setCertSha256Fingerprint(self, p0: Any) -> None: ...
        def equals(self, p0: Any) -> bool: ...
        def toString(self) -> str: ...
        def hashCode(self) -> int: ...
        def describeContents(self) -> int: ...
        def writeToParcel(self, p0: Parcel, p1: int) -> None: ...

