from typing import Any, ClassVar, overload
from java.lang.Throwable import Throwable

class BackendBusyException:
    @overload
    def __init__(self, p0: int) -> None: ...
    @overload
    def __init__(self, p0: int, p1: str, p2: Throwable) -> None: ...
    @overload
    def __init__(self, p0: int, p1: str) -> None: ...
    def getBackOffHintMillis(self) -> int: ...
