from typing import Any, ClassVar, overload
from java.util.Date import Date

class KeyProtection:
    def getDigests(self) -> Any: ...
    def getEncryptionPaddings(self) -> Any: ...
    def getBlockModes(self) -> Any: ...
    def getKeyValidityForConsumptionEnd(self) -> Date: ...
    def getKeyValidityForOriginationEnd(self) -> Date: ...
    def getKeyValidityStart(self) -> Date: ...
    def getMaxUsageCount(self) -> int: ...
    def getMgf1Digests(self) -> set: ...
    def getPurposes(self) -> int: ...
    def getSignaturePaddings(self) -> Any: ...
    def getUserAuthenticationType(self) -> int: ...
    def getUserAuthenticationValidityDurationSeconds(self) -> int: ...
    def isDigestsSpecified(self) -> bool: ...
    def isInvalidatedByBiometricEnrollment(self) -> bool: ...
    def isMgf1DigestsSpecified(self) -> bool: ...
    def isRandomizedEncryptionRequired(self) -> bool: ...
    def isUnlockedDeviceRequired(self) -> bool: ...
    def isUserAuthenticationRequired(self) -> bool: ...
    def isUserAuthenticationValidWhileOnBody(self) -> bool: ...
    def isUserConfirmationRequired(self) -> bool: ...
    def isUserPresenceRequired(self) -> bool: ...

    class Builder:
        def __init__(self, p0: int) -> None: ...
        def setBlockModes(self, p0: Any) -> Any: ...
        def setDigests(self, p0: Any) -> Any: ...
        def setKeyValidityEnd(self, p0: Date) -> Any: ...
        def setEncryptionPaddings(self, p0: Any) -> Any: ...
        def setInvalidatedByBiometricEnrollment(self, p0: bool) -> Any: ...
        def setIsStrongBoxBacked(self, p0: bool) -> Any: ...
        def setKeyValidityForConsumptionEnd(self, p0: Date) -> Any: ...
        def setKeyValidityForOriginationEnd(self, p0: Date) -> Any: ...
        def setKeyValidityStart(self, p0: Date) -> Any: ...
        def setRandomizedEncryptionRequired(self, p0: bool) -> Any: ...
        def setSignaturePaddings(self, p0: Any) -> Any: ...
        def setUnlockedDeviceRequired(self, p0: bool) -> Any: ...
        def setUserAuthenticationParameters(self, p0: int, p1: int) -> Any: ...
        def setUserAuthenticationRequired(self, p0: bool) -> Any: ...
        def setUserAuthenticationValidWhileOnBody(self, p0: bool) -> Any: ...
        def setUserAuthenticationValidityDurationSeconds(self, p0: int) -> Any: ...
        def setUserConfirmationRequired(self, p0: bool) -> Any: ...
        def setUserPresenceRequired(self, p0: bool) -> Any: ...
        def setMgf1Digests(self, p0: Any) -> Any: ...
        def setMaxUsageCount(self, p0: int) -> Any: ...
        def build(self) -> "KeyProtection": ...
