from typing import Any, ClassVar, overload
from android.os.Parcel import Parcel

class NetworkEvent:
    CREATOR: ClassVar[Any]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    def getPackageName(self) -> str: ...
    def getId(self) -> int: ...
    def getTimestamp(self) -> int: ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
