from typing import Any, ClassVar, overload
from android.os.Parcel import Parcel

class PreferentialNetworkServiceConfig:
    CREATOR: ClassVar[Any]
    PREFERENTIAL_NETWORK_ID_1: ClassVar[int]
    PREFERENTIAL_NETWORK_ID_2: ClassVar[int]
    PREFERENTIAL_NETWORK_ID_3: ClassVar[int]
    PREFERENTIAL_NETWORK_ID_4: ClassVar[int]
    PREFERENTIAL_NETWORK_ID_5: ClassVar[int]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    def getNetworkId(self) -> int: ...
    def getIncludedUids(self) -> Any: ...
    def isFallbackToDefaultConnectionAllowed(self) -> bool: ...
    def shouldBlockNonMatchingNetworks(self) -> bool: ...
    def getExcludedUids(self) -> Any: ...
    def equals(self, p0: Any) -> bool: ...
    def toString(self) -> str: ...
    def hashCode(self) -> int: ...
    def isEnabled(self) -> bool: ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...

    class Builder:
        def __init__(self) -> None: ...
        def setExcludedUids(self, p0: Any) -> Any: ...
        def setNetworkId(self, p0: int) -> Any: ...
        def setFallbackToDefaultConnectionAllowed(self, p0: bool) -> Any: ...
        def setIncludedUids(self, p0: Any) -> Any: ...
        def setShouldBlockNonMatchingNetworks(self, p0: bool) -> Any: ...
        def build(self) -> "PreferentialNetworkServiceConfig": ...
        def setEnabled(self, p0: bool) -> Any: ...
