from typing import Any, ClassVar, overload
from android.os.Parcel import Parcel

class NetworkSliceInfo:
    CREATOR: ClassVar[Any]
    SLICE_DIFFERENTIATOR_NO_SLICE: ClassVar[int]
    SLICE_SERVICE_TYPE_EMBB: ClassVar[int]
    SLICE_SERVICE_TYPE_MIOT: ClassVar[int]
    SLICE_SERVICE_TYPE_NONE: ClassVar[int]
    SLICE_SERVICE_TYPE_URLLC: ClassVar[int]
    SLICE_STATUS_ALLOWED: ClassVar[int]
    SLICE_STATUS_CONFIGURED: ClassVar[int]
    SLICE_STATUS_DEFAULT_CONFIGURED: ClassVar[int]
    SLICE_STATUS_REJECTED_NOT_AVAILABLE_IN_PLMN: ClassVar[int]
    SLICE_STATUS_REJECTED_NOT_AVAILABLE_IN_REGISTERED_AREA: ClassVar[int]
    SLICE_STATUS_UNKNOWN: ClassVar[int]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    def getStatus(self) -> int: ...
    def getSliceDifferentiator(self) -> int: ...
    def getMappedHplmnSliceDifferentiator(self) -> int: ...
    def getMappedHplmnSliceServiceType(self) -> int: ...
    def getSliceServiceType(self) -> int: ...
    def equals(self, p0: Any) -> bool: ...
    def toString(self) -> str: ...
    def hashCode(self) -> int: ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...

    class Builder:
        def __init__(self) -> None: ...
        def setStatus(self, p0: int) -> Any: ...
        def setSliceDifferentiator(self, p0: int) -> Any: ...
        def setMappedHplmnSliceServiceType(self, p0: int) -> Any: ...
        def setSliceServiceType(self, p0: int) -> Any: ...
        def setMappedHplmnSliceDifferentiator(self, p0: int) -> Any: ...
        def build(self) -> "NetworkSliceInfo": ...

from typing import Any, ClassVar, overload
from android.os.Parcel import Parcel

class UrspRule:
    CREATOR: ClassVar[Any]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    def getPrecedence(self) -> int: ...
    def getTrafficDescriptors(self) -> list: ...
    def getRouteSelectionDescriptor(self) -> list: ...
    def equals(self, p0: Any) -> bool: ...
    def toString(self) -> str: ...
    def hashCode(self) -> int: ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...

from typing import Any, ClassVar, overload
from android.net.Uri import Uri
from android.os.Parcel import Parcel
from java.net.InetAddress import InetAddress

class ApnSetting:
    AUTH_TYPE_CHAP: ClassVar[int]
    AUTH_TYPE_NONE: ClassVar[int]
    AUTH_TYPE_PAP: ClassVar[int]
    AUTH_TYPE_PAP_OR_CHAP: ClassVar[int]
    CREATOR: ClassVar[Any]
    MVNO_TYPE_GID: ClassVar[int]
    MVNO_TYPE_ICCID: ClassVar[int]
    MVNO_TYPE_IMSI: ClassVar[int]
    MVNO_TYPE_SPN: ClassVar[int]
    PROTOCOL_IP: ClassVar[int]
    PROTOCOL_IPV4V6: ClassVar[int]
    PROTOCOL_IPV6: ClassVar[int]
    PROTOCOL_NON_IP: ClassVar[int]
    PROTOCOL_PPP: ClassVar[int]
    PROTOCOL_UNSTRUCTURED: ClassVar[int]
    TYPE_BIP: ClassVar[int]
    TYPE_CBS: ClassVar[int]
    TYPE_DEFAULT: ClassVar[int]
    TYPE_DUN: ClassVar[int]
    TYPE_EMERGENCY: ClassVar[int]
    TYPE_ENTERPRISE: ClassVar[int]
    TYPE_FOTA: ClassVar[int]
    TYPE_HIPRI: ClassVar[int]
    TYPE_IA: ClassVar[int]
    TYPE_IMS: ClassVar[int]
    TYPE_MCX: ClassVar[int]
    TYPE_MMS: ClassVar[int]
    TYPE_OEM_PAID: ClassVar[int]
    TYPE_OEM_PRIVATE: ClassVar[int]
    TYPE_RCS: ClassVar[int]
    TYPE_SUPL: ClassVar[int]
    TYPE_VSIM: ClassVar[int]
    TYPE_XCAP: ClassVar[int]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    def getCarrierId(self) -> int: ...
    def getPassword(self) -> str: ...
    def getMmsProxyAddressAsString(self) -> str: ...
    def getApnName(self) -> str: ...
    def getApnTypeBitmask(self) -> int: ...
    def getAuthType(self) -> int: ...
    def getMmsProxyAddress(self) -> InetAddress: ...
    def getMmsProxyPort(self) -> int: ...
    def getMmsc(self) -> Uri: ...
    def getMtuV4(self) -> int: ...
    def getMtuV6(self) -> int: ...
    def getMvnoType(self) -> int: ...
    def getNetworkTypeBitmask(self) -> int: ...
    def getOperatorNumeric(self) -> str: ...
    def getProfileId(self) -> int: ...
    def getProxyAddress(self) -> InetAddress: ...
    def getProxyAddressAsString(self) -> str: ...
    def getProxyPort(self) -> int: ...
    def getRoamingProtocol(self) -> int: ...
    def isAlwaysOn(self) -> bool: ...
    def isPersistent(self) -> bool: ...
    def getEntryName(self) -> str: ...
    def equals(self, p0: Any) -> bool: ...
    def toString(self) -> str: ...
    def hashCode(self) -> int: ...
    def isEnabled(self) -> bool: ...
    def getId(self) -> int: ...
    def getUser(self) -> str: ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
    def getProtocol(self) -> int: ...

    class Builder:
        def __init__(self) -> None: ...
        def setProtocol(self, p0: int) -> Any: ...
        @overload
        def setMmsProxyAddress(self, p0: InetAddress) -> Any: ...
        @overload
        def setMmsProxyAddress(self, p0: str) -> Any: ...
        def setMmsProxyPort(self, p0: int) -> Any: ...
        def setMmsc(self, p0: Uri) -> Any: ...
        def setMtuV4(self, p0: int) -> Any: ...
        def setMtuV6(self, p0: int) -> Any: ...
        def setMvnoType(self, p0: int) -> Any: ...
        def setNetworkTypeBitmask(self, p0: int) -> Any: ...
        def setOperatorNumeric(self, p0: str) -> Any: ...
        def setPersistent(self, p0: bool) -> Any: ...
        def setProfileId(self, p0: int) -> Any: ...
        @overload
        def setProxyAddress(self, p0: InetAddress) -> Any: ...
        @overload
        def setProxyAddress(self, p0: str) -> Any: ...
        def setProxyPort(self, p0: int) -> Any: ...
        def setRoamingProtocol(self, p0: int) -> Any: ...
        def setUser(self, p0: str) -> Any: ...
        def setApnName(self, p0: str) -> Any: ...
        def setAlwaysOn(self, p0: bool) -> Any: ...
        def setApnTypeBitmask(self, p0: int) -> Any: ...
        def setAuthType(self, p0: int) -> Any: ...
        def setCarrierEnabled(self, p0: bool) -> Any: ...
        def setCarrierId(self, p0: int) -> Any: ...
        def setEntryName(self, p0: str) -> Any: ...
        def build(self) -> "ApnSetting": ...
        def setPassword(self, p0: str) -> Any: ...

from typing import Any, ClassVar, overload
from android.os.Parcel import Parcel

class NetworkSlicingConfig:
    CREATOR: ClassVar[Any]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    def __init__(self) -> None: ...
    def getUrspRules(self) -> list: ...
    def getSliceInfo(self) -> list: ...
    def equals(self, p0: Any) -> bool: ...
    def toString(self) -> str: ...
    def hashCode(self) -> int: ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...

from typing import Any, ClassVar, overload
from android.os.Parcel import Parcel

class TrafficDescriptor:
    CREATOR: ClassVar[Any]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    def getDataNetworkName(self) -> str: ...
    def getOsAppId(self) -> Any: ...
    def equals(self, p0: Any) -> bool: ...
    def toString(self) -> str: ...
    def hashCode(self) -> int: ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...

    class Builder:
        def __init__(self) -> None: ...
        def setOsAppId(self, p0: Any) -> Any: ...
        def setDataNetworkName(self, p0: str) -> Any: ...
        def build(self) -> "TrafficDescriptor": ...

from typing import Any, ClassVar, overload
from android.os.Parcel import Parcel

class RouteSelectionDescriptor:
    CREATOR: ClassVar[Any]
    ROUTE_SSC_MODE_1: ClassVar[int]
    ROUTE_SSC_MODE_2: ClassVar[int]
    ROUTE_SSC_MODE_3: ClassVar[int]
    SESSION_TYPE_IPV4: ClassVar[int]
    SESSION_TYPE_IPV4V6: ClassVar[int]
    SESSION_TYPE_IPV6: ClassVar[int]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    def getPrecedence(self) -> int: ...
    def getSliceInfo(self) -> list: ...
    def getDataNetworkName(self) -> list: ...
    def getSscMode(self) -> int: ...
    def equals(self, p0: Any) -> bool: ...
    def toString(self) -> str: ...
    def hashCode(self) -> int: ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
    def getSessionType(self) -> int: ...

