from typing import Any, ClassVar, overload
from android.net.LinkProperties import LinkProperties
from android.os.Parcel import Parcel
from android.telephony.data.ApnSetting import ApnSetting

class PreciseDataConnectionState:
    CREATOR: ClassVar[Any]
    NETWORK_VALIDATION_FAILURE: ClassVar[int]
    NETWORK_VALIDATION_IN_PROGRESS: ClassVar[int]
    NETWORK_VALIDATION_NOT_REQUESTED: ClassVar[int]
    NETWORK_VALIDATION_SUCCESS: ClassVar[int]
    NETWORK_VALIDATION_UNSUPPORTED: ClassVar[int]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    def getNetworkType(self) -> int: ...
    def getApnSetting(self) -> ApnSetting: ...
    def getLinkProperties(self) -> LinkProperties: ...
    def getNetworkValidationStatus(self) -> int: ...
    def getTransportType(self) -> int: ...
    def getLastCauseCode(self) -> int: ...
    def equals(self, p0: Any) -> bool: ...
    def toString(self) -> str: ...
    def hashCode(self) -> int: ...
    def getId(self) -> int: ...
    def getState(self) -> int: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
    def describeContents(self) -> int: ...
