from typing import Any, ClassVar, overload

class SmsMessage:
    ENCODING_16BIT: ClassVar[int]
    ENCODING_7BIT: ClassVar[int]
    ENCODING_8BIT: ClassVar[int]
    ENCODING_KSC5601: ClassVar[int]
    ENCODING_UNKNOWN: ClassVar[int]
    FORMAT_3GPP: ClassVar[str]
    FORMAT_3GPP2: ClassVar[str]
    MAX_USER_DATA_BYTES: ClassVar[int]
    MAX_USER_DATA_BYTES_WITH_HEADER: ClassVar[int]
    MAX_USER_DATA_SEPTETS: ClassVar[int]
    MAX_USER_DATA_SEPTETS_WITH_HEADER: ClassVar[int]
    def getStatus(self) -> int: ...
    @overload
    @staticmethod
    def createFromPdu(p0: Any, p1: str) -> "SmsMessage": ...
    @overload
    @staticmethod
    def createFromPdu(p0: Any) -> "SmsMessage": ...
    @overload
    @staticmethod
    def calculateLength(p0: str, p1: bool) -> Any: ...
    @overload
    @staticmethod
    def calculateLength(p0: str, p1: bool) -> Any: ...
    def getDisplayMessageBody(self) -> str: ...
    def getDisplayOriginatingAddress(self) -> str: ...
    def getEmailBody(self) -> str: ...
    def getEmailFrom(self) -> str: ...
    def getIndexOnIcc(self) -> int: ...
    def getIndexOnSim(self) -> int: ...
    def getMessageBody(self) -> str: ...
    def getMessageClass(self) -> Any: ...
    def getOriginatingAddress(self) -> str: ...
    def getPdu(self) -> Any: ...
    def getProtocolIdentifier(self) -> int: ...
    def getPseudoSubject(self) -> str: ...
    def getRecipientAddress(self) -> str: ...
    def getServiceCenterAddress(self) -> str: ...
    def getStatusOnIcc(self) -> int: ...
    def getStatusOnSim(self) -> int: ...
    @overload
    @staticmethod
    def getSubmitPdu(p0: str, p1: str, p2: int, p3: Any, p4: bool) -> Any: ...
    @overload
    @staticmethod
    def getSubmitPdu(p0: str, p1: str, p2: str, p3: bool) -> Any: ...
    @staticmethod
    def getTPLayerLengthForPDU(p0: str) -> int: ...
    def getUserData(self) -> Any: ...
    def isCphsMwiMessage(self) -> bool: ...
    def isEmail(self) -> bool: ...
    def isMWIClearMessage(self) -> bool: ...
    def isMWISetMessage(self) -> bool: ...
    def isMwiDontStore(self) -> bool: ...
    def isReplace(self) -> bool: ...
    def isReplyPathPresent(self) -> bool: ...
    def isStatusReportMessage(self) -> bool: ...
    def getTimestampMillis(self) -> int: ...

    class SubmitPdu:
        encodedMessage: Any
        encodedScAddress: Any
        def toString(self) -> str: ...

    class MessageClass:
        CLASS_0: ClassVar["MessageClass"]
        CLASS_1: ClassVar["MessageClass"]
        CLASS_2: ClassVar["MessageClass"]
        CLASS_3: ClassVar["MessageClass"]
        UNKNOWN: ClassVar["MessageClass"]
        CLASS_0: ClassVar[Any]
        CLASS_1: ClassVar[Any]
        CLASS_2: ClassVar[Any]
        CLASS_3: ClassVar[Any]
        UNKNOWN: ClassVar[Any]
        @staticmethod
        def values() -> Any: ...
        @staticmethod
        def valueOf(p0: str) -> Any: ...
