from typing import Any, ClassVar, overload
from android.app.PendingIntent import PendingIntent
from android.content.Context import Context
from android.os.ParcelUuid import ParcelUuid
from android.telephony.SubscriptionInfo import SubscriptionInfo
from java.util.concurrent.Executor import Executor

class SubscriptionManager:
    ACTION_DEFAULT_SMS_SUBSCRIPTION_CHANGED: ClassVar[str]
    ACTION_DEFAULT_SUBSCRIPTION_CHANGED: ClassVar[str]
    ACTION_MANAGE_SUBSCRIPTION_PLANS: ClassVar[str]
    ACTION_REFRESH_SUBSCRIPTION_PLANS: ClassVar[str]
    D2D_SHARING_ALL: ClassVar[int]
    D2D_SHARING_ALL_CONTACTS: ClassVar[int]
    D2D_SHARING_DISABLED: ClassVar[int]
    D2D_SHARING_SELECTED_CONTACTS: ClassVar[int]
    D2D_STATUS_SHARING: ClassVar[str]
    D2D_STATUS_SHARING_SELECTED_CONTACTS: ClassVar[str]
    DATA_ROAMING_DISABLE: ClassVar[int]
    DATA_ROAMING_ENABLE: ClassVar[int]
    DEFAULT_SUBSCRIPTION_ID: ClassVar[int]
    EXTRA_SLOT_INDEX: ClassVar[str]
    EXTRA_SUBSCRIPTION_INDEX: ClassVar[str]
    INVALID_SIM_SLOT_INDEX: ClassVar[int]
    INVALID_SUBSCRIPTION_ID: ClassVar[int]
    PHONE_NUMBER_SOURCE_CARRIER: ClassVar[int]
    PHONE_NUMBER_SOURCE_IMS: ClassVar[int]
    PHONE_NUMBER_SOURCE_UICC: ClassVar[int]
    SERVICE_CAPABILITY_DATA: ClassVar[int]
    SERVICE_CAPABILITY_SMS: ClassVar[int]
    SERVICE_CAPABILITY_VOICE: ClassVar[int]
    SUBSCRIPTION_TYPE_LOCAL_SIM: ClassVar[int]
    SUBSCRIPTION_TYPE_REMOTE_SIM: ClassVar[int]
    USAGE_SETTING_DATA_CENTRIC: ClassVar[int]
    USAGE_SETTING_DEFAULT: ClassVar[int]
    USAGE_SETTING_UNKNOWN: ClassVar[int]
    USAGE_SETTING_VOICE_CENTRIC: ClassVar[int]
    def getSubscriptionIds(self, p0: int) -> Any: ...
    @overload
    def getPhoneNumber(self, p0: int) -> str: ...
    @overload
    def getPhoneNumber(self, p0: int, p1: int) -> str: ...
    @staticmethod
    def getSubscriptionId(p0: int) -> int: ...
    def addOnOpportunisticSubscriptionsChangedListener(self, p0: Executor, p1: Any) -> None: ...
    @staticmethod
    def from_(p0: Context) -> "SubscriptionManager": ...
    def isNetworkRoaming(self, p0: int) -> bool: ...
    @staticmethod
    def getSlotIndex(p0: int) -> int: ...
    @staticmethod
    def getDefaultVoiceSubscriptionId() -> int: ...
    def getDeviceToDeviceStatusSharingContacts(self, p0: int) -> list: ...
    def getDeviceToDeviceStatusSharingPreference(self, p0: int) -> int: ...
    def getOpportunisticSubscriptions(self) -> list: ...
    def getSubscriptionPlans(self, p0: int) -> list: ...
    def getSubscriptionsInGroup(self, p0: ParcelUuid) -> list: ...
    def isActiveSubscriptionId(self, p0: int) -> bool: ...
    @staticmethod
    def isUsableSubscriptionId(p0: int) -> bool: ...
    @staticmethod
    def isValidSubscriptionId(p0: int) -> bool: ...
    def removeOnOpportunisticSubscriptionsChangedListener(self, p0: Any) -> None: ...
    def removeOnSubscriptionsChangedListener(self, p0: Any) -> None: ...
    def removeSubscriptionsFromGroup(self, p0: list, p1: ParcelUuid) -> None: ...
    def setCarrierPhoneNumber(self, p0: int, p1: str) -> None: ...
    def setDeviceToDeviceStatusSharingContacts(self, p0: int, p1: list) -> None: ...
    def setDeviceToDeviceStatusSharingPreference(self, p0: int, p1: int) -> None: ...
    def setOpportunistic(self, p0: bool, p1: int) -> bool: ...
    @overload
    def setSubscriptionOverrideCongested(self, p0: int, p1: bool, p2: int) -> None: ...
    @overload
    def setSubscriptionOverrideCongested(self, p0: int, p1: bool, p2: Any, p3: int) -> None: ...
    @overload
    def setSubscriptionOverrideUnmetered(self, p0: int, p1: bool, p2: int) -> None: ...
    @overload
    def setSubscriptionOverrideUnmetered(self, p0: int, p1: bool, p2: Any, p3: int) -> None: ...
    @overload
    def setSubscriptionPlans(self, p0: int, p1: list, p2: int) -> None: ...
    @overload
    def setSubscriptionPlans(self, p0: int, p1: list) -> None: ...
    def switchToSubscription(self, p0: int, p1: PendingIntent) -> None: ...
    @overload
    def addOnSubscriptionsChangedListener(self, p0: Any) -> None: ...
    @overload
    def addOnSubscriptionsChangedListener(self, p0: Executor, p1: Any) -> None: ...
    def addSubscriptionsIntoGroup(self, p0: list, p1: ParcelUuid) -> None: ...
    def canManageSubscription(self, p0: SubscriptionInfo) -> bool: ...
    def createSubscriptionGroup(self, p0: list) -> ParcelUuid: ...
    def getAccessibleSubscriptionInfoList(self) -> list: ...
    @staticmethod
    def getActiveDataSubscriptionId() -> int: ...
    def getActiveSubscriptionInfo(self, p0: int) -> SubscriptionInfo: ...
    def getActiveSubscriptionInfoCount(self) -> int: ...
    def getActiveSubscriptionInfoCountMax(self) -> int: ...
    def getActiveSubscriptionInfoForSimSlotIndex(self, p0: int) -> SubscriptionInfo: ...
    def getActiveSubscriptionInfoList(self) -> list: ...
    def getAllSubscriptionInfoList(self) -> list: ...
    def getCompleteActiveSubscriptionInfoList(self) -> list: ...
    @staticmethod
    def getDefaultDataSubscriptionId() -> int: ...
    @staticmethod
    def getDefaultSmsSubscriptionId() -> int: ...
    @staticmethod
    def getDefaultSubscriptionId() -> int: ...

    class OnSubscriptionsChangedListener:
        def __init__(self) -> None: ...
        def onSubscriptionsChanged(self) -> None: ...

    class OnOpportunisticSubscriptionsChangedListener:
        def __init__(self) -> None: ...
        def onOpportunisticSubscriptionsChanged(self) -> None: ...
