from typing import Any, ClassVar, overload
from android.icu.number.Precision import Precision

class FractionPrecision:
    def withSignificantDigits(self, p0: int, p1: int, p2: Any) -> Precision: ...
    def withMinDigits(self, p0: int) -> Precision: ...
    def withMaxDigits(self, p0: int) -> Precision: ...
