from typing import Any, ClassVar, overload
from android.icu.number.UnlocalizedNumberFormatter import UnlocalizedNumberFormatter

class NumberRangeFormatterSettings:
    def numberFormatterBoth(self, p0: UnlocalizedNumberFormatter) -> "NumberRangeFormatterSettings": ...
    def numberFormatterFirst(self, p0: UnlocalizedNumberFormatter) -> "NumberRangeFormatterSettings": ...
    def numberFormatterSecond(self, p0: UnlocalizedNumberFormatter) -> "NumberRangeFormatterSettings": ...
    def collapse(self, p0: Any) -> "NumberRangeFormatterSettings": ...
    def identityFallback(self, p0: Any) -> "NumberRangeFormatterSettings": ...
    def equals(self, p0: Any) -> bool: ...
    def hashCode(self) -> int: ...
