from typing import Any, ClassVar, overload
from android.icu.number.IntegerWidth import IntegerWidth
from android.icu.number.Notation import Notation
from android.icu.number.Precision import Precision
from android.icu.number.Scale import Scale
from android.icu.text.DecimalFormatSymbols import DecimalFormatSymbols
from android.icu.text.DisplayOptions import DisplayOptions
from android.icu.text.NumberingSystem import NumberingSystem
from android.icu.util.MeasureUnit import MeasureUnit
from java.math.RoundingMode import RoundingMode

class NumberFormatterSettings:
    def displayOptions(self, p0: DisplayOptions) -> "NumberFormatterSettings": ...
    def perUnit(self, p0: MeasureUnit) -> "NumberFormatterSettings": ...
    def notation(self, p0: Notation) -> "NumberFormatterSettings": ...
    def grouping(self, p0: Any) -> "NumberFormatterSettings": ...
    def integerWidth(self, p0: IntegerWidth) -> "NumberFormatterSettings": ...
    def unitWidth(self, p0: Any) -> "NumberFormatterSettings": ...
    def decimal(self, p0: Any) -> "NumberFormatterSettings": ...
    def equals(self, p0: Any) -> bool: ...
    def hashCode(self) -> int: ...
    def scale(self, p0: Scale) -> "NumberFormatterSettings": ...
    def sign(self, p0: Any) -> "NumberFormatterSettings": ...
    def unit(self, p0: MeasureUnit) -> "NumberFormatterSettings": ...
    @overload
    def symbols(self, p0: NumberingSystem) -> "NumberFormatterSettings": ...
    @overload
    def symbols(self, p0: DecimalFormatSymbols) -> "NumberFormatterSettings": ...
    def roundingMode(self, p0: RoundingMode) -> "NumberFormatterSettings": ...
    def usage(self, p0: str) -> "NumberFormatterSettings": ...
    def precision(self, p0: Precision) -> "NumberFormatterSettings": ...
