from typing import Any, ClassVar, overload
from android.health.connect.datatypes.AggregationType import AggregationType
from android.health.connect.datatypes.Metadata import Metadata
from android.health.connect.datatypes.units.Power import Power
from java.time.Instant import Instant
from java.time.ZoneOffset import ZoneOffset

class BasalMetabolicRateRecord:
    BASAL_CALORIES_TOTAL: ClassVar[AggregationType]
    def getBasalMetabolicRate(self) -> Power: ...
    def equals(self, p0: Any) -> bool: ...
    def hashCode(self) -> int: ...

    class Builder:
        def __init__(self, p0: Metadata, p1: Instant, p2: Power) -> None: ...
        def clearZoneOffset(self) -> Any: ...
        def setZoneOffset(self, p0: ZoneOffset) -> Any: ...
        def build(self) -> "BasalMetabolicRateRecord": ...
