from typing import Any, ClassVar, overload
from android.health.connect.datatypes.AggregationType import AggregationType
from android.health.connect.datatypes.Metadata import Metadata
from android.health.connect.datatypes.units.Length import Length
from java.time.Instant import Instant
from java.time.ZoneOffset import ZoneOffset

class DistanceRecord:
    DISTANCE_TOTAL: ClassVar[AggregationType]
    def equals(self, p0: Any) -> bool: ...
    def hashCode(self) -> int: ...
    def getDistance(self) -> Length: ...

    class Builder:
        def __init__(self, p0: Metadata, p1: Instant, p2: Instant, p3: Length) -> None: ...
        def build(self) -> "DistanceRecord": ...
        def clearEndZoneOffset(self) -> Any: ...
        def clearStartZoneOffset(self) -> Any: ...
        def setEndZoneOffset(self, p0: ZoneOffset) -> Any: ...
        def setStartZoneOffset(self, p0: ZoneOffset) -> Any: ...
