from typing import Any, ClassVar, overload
from android.os.Parcel import Parcel

class FhirResource:
    CREATOR: ClassVar[Any]
    FHIR_RESOURCE_TYPE_ALLERGY_INTOLERANCE: ClassVar[int]
    FHIR_RESOURCE_TYPE_CONDITION: ClassVar[int]
    FHIR_RESOURCE_TYPE_ENCOUNTER: ClassVar[int]
    FHIR_RESOURCE_TYPE_IMMUNIZATION: ClassVar[int]
    FHIR_RESOURCE_TYPE_LOCATION: ClassVar[int]
    FHIR_RESOURCE_TYPE_MEDICATION: ClassVar[int]
    FHIR_RESOURCE_TYPE_MEDICATION_REQUEST: ClassVar[int]
    FHIR_RESOURCE_TYPE_MEDICATION_STATEMENT: ClassVar[int]
    FHIR_RESOURCE_TYPE_OBSERVATION: ClassVar[int]
    FHIR_RESOURCE_TYPE_ORGANIZATION: ClassVar[int]
    FHIR_RESOURCE_TYPE_PATIENT: ClassVar[int]
    FHIR_RESOURCE_TYPE_PRACTITIONER: ClassVar[int]
    FHIR_RESOURCE_TYPE_PRACTITIONER_ROLE: ClassVar[int]
    FHIR_RESOURCE_TYPE_PROCEDURE: ClassVar[int]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    def equals(self, p0: Any) -> bool: ...
    def toString(self) -> str: ...
    def hashCode(self) -> int: ...
    def getId(self) -> str: ...
    def getType(self) -> int: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
    def describeContents(self) -> int: ...
    def getData(self) -> str: ...

    class Builder:
        @overload
        def __init__(self, p0: int, p1: str, p2: str) -> None: ...
        @overload
        def __init__(self, p0: Any) -> None: ...
        @overload
        def __init__(self, p0: "FhirResource") -> None: ...
        def build(self) -> "FhirResource": ...
        def setType(self, p0: int) -> Any: ...
        def setData(self, p0: str) -> Any: ...
        def setId(self, p0: str) -> Any: ...
