from typing import Any, ClassVar, overload
from java.time.Instant import Instant
from java.time.ZoneOffset import ZoneOffset

class InstantRecord:
    def equals(self, p0: Any) -> bool: ...
    def hashCode(self) -> int: ...
    def getZoneOffset(self) -> ZoneOffset: ...
    def getTime(self) -> Instant: ...
