from typing import Any, ClassVar, overload
from android.health.connect.MedicalResourceId import MedicalResourceId
from android.health.connect.datatypes.FhirResource import FhirResource
from android.health.connect.datatypes.FhirVersion import FhirVersion
from android.os.Parcel import Parcel

class MedicalResource:
    CREATOR: ClassVar[Any]
    MEDICAL_RESOURCE_TYPE_ALLERGIES_INTOLERANCES: ClassVar[int]
    MEDICAL_RESOURCE_TYPE_CONDITIONS: ClassVar[int]
    MEDICAL_RESOURCE_TYPE_LABORATORY_RESULTS: ClassVar[int]
    MEDICAL_RESOURCE_TYPE_MEDICATIONS: ClassVar[int]
    MEDICAL_RESOURCE_TYPE_PERSONAL_DETAILS: ClassVar[int]
    MEDICAL_RESOURCE_TYPE_PRACTITIONER_DETAILS: ClassVar[int]
    MEDICAL_RESOURCE_TYPE_PREGNANCY: ClassVar[int]
    MEDICAL_RESOURCE_TYPE_PROCEDURES: ClassVar[int]
    MEDICAL_RESOURCE_TYPE_SOCIAL_HISTORY: ClassVar[int]
    MEDICAL_RESOURCE_TYPE_VACCINES: ClassVar[int]
    MEDICAL_RESOURCE_TYPE_VISITS: ClassVar[int]
    MEDICAL_RESOURCE_TYPE_VITAL_SIGNS: ClassVar[int]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    def equals(self, p0: Any) -> bool: ...
    def toString(self) -> str: ...
    def hashCode(self) -> int: ...
    def getId(self) -> MedicalResourceId: ...
    def getType(self) -> int: ...
    def getFhirResource(self) -> FhirResource: ...
    def getDataSourceId(self) -> str: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
    def describeContents(self) -> int: ...
    def getFhirVersion(self) -> FhirVersion: ...

    class Builder:
        @overload
        def __init__(self, p0: int, p1: str, p2: FhirVersion, p3: FhirResource) -> None: ...
        @overload
        def __init__(self, p0: Any) -> None: ...
        @overload
        def __init__(self, p0: "MedicalResource") -> None: ...
        def setDataSourceId(self, p0: str) -> Any: ...
        def setFhirResource(self, p0: FhirResource) -> Any: ...
        def build(self) -> "MedicalResource": ...
        def setType(self, p0: int) -> Any: ...
        def setFhirVersion(self, p0: FhirVersion) -> Any: ...
