from typing import Any, ClassVar, overload
from android.health.connect.datatypes.Metadata import Metadata
from java.time.Instant import Instant
from java.time.ZoneOffset import ZoneOffset

class MenstruationFlowRecord:
    def getFlow(self) -> int: ...
    def equals(self, p0: Any) -> bool: ...
    def hashCode(self) -> int: ...

    class MenstruationFlowType:
        FLOW_HEAVY: ClassVar[int]
        FLOW_LIGHT: ClassVar[int]
        FLOW_MEDIUM: ClassVar[int]
        FLOW_UNKNOWN: ClassVar[int]

    class Builder:
        def __init__(self, p0: Metadata, p1: Instant, p2: int) -> None: ...
        def clearZoneOffset(self) -> Any: ...
        def setZoneOffset(self, p0: ZoneOffset) -> Any: ...
        def build(self) -> "MenstruationFlowRecord": ...
