from typing import Any, ClassVar, overload
from android.health.connect.datatypes.Metadata import Metadata
from android.health.connect.datatypes.PlannedExerciseBlock import PlannedExerciseBlock
from java.time.Duration import Duration
from java.time.Instant import Instant
from java.time.LocalDate import LocalDate
from java.time.ZoneOffset import ZoneOffset

class PlannedExerciseSessionRecord:
    def equals(self, p0: Any) -> bool: ...
    def hashCode(self) -> int: ...
    def getDuration(self) -> Duration: ...
    def hasExplicitTime(self) -> bool: ...
    def getBlocks(self) -> list: ...
    def getStartDate(self) -> LocalDate: ...
    def getExerciseType(self) -> int: ...
    def getNotes(self) -> str: ...
    def getCompletedExerciseSessionId(self) -> str: ...
    def getTitle(self) -> str: ...

    class Builder:
        @overload
        def __init__(self, p0: Metadata, p1: int, p2: Instant, p3: Instant) -> None: ...
        @overload
        def __init__(self, p0: Metadata, p1: int, p2: LocalDate, p3: Duration) -> None: ...
        def build(self) -> "PlannedExerciseSessionRecord": ...
        def setStartTime(self, p0: Instant) -> Any: ...
        def addBlock(self, p0: PlannedExerciseBlock) -> Any: ...
        def clearBlocks(self) -> Any: ...
        def clearEndZoneOffset(self) -> Any: ...
        def clearStartZoneOffset(self) -> Any: ...
        def setBlocks(self, p0: list) -> Any: ...
        def setEndTime(self, p0: Instant) -> Any: ...
        def setEndZoneOffset(self, p0: ZoneOffset) -> Any: ...
        def setExerciseType(self, p0: int) -> Any: ...
        def setMetadata(self, p0: Metadata) -> Any: ...
        def setNotes(self, p0: str) -> Any: ...
        def setStartZoneOffset(self, p0: ZoneOffset) -> Any: ...
        def setTitle(self, p0: str) -> Any: ...
