from typing import Any, ClassVar, overload
from android.health.connect.datatypes.AggregationType import AggregationType
from android.health.connect.datatypes.Metadata import Metadata
from java.time.Instant import Instant
from java.time.ZoneOffset import ZoneOffset

class SleepSessionRecord:
    SLEEP_DURATION_TOTAL: ClassVar[AggregationType]
    def getNotes(self) -> str: ...
    def getStages(self) -> list: ...
    def getTitle(self) -> str: ...
    def equals(self, p0: Any) -> bool: ...
    def hashCode(self) -> int: ...

    class StageType:
        STAGE_TYPE_AWAKE: ClassVar[int]
        STAGE_TYPE_AWAKE_IN_BED: ClassVar[int]
        STAGE_TYPE_AWAKE_OUT_OF_BED: ClassVar[int]
        STAGE_TYPE_SLEEPING: ClassVar[int]
        STAGE_TYPE_SLEEPING_DEEP: ClassVar[int]
        STAGE_TYPE_SLEEPING_LIGHT: ClassVar[int]
        STAGE_TYPE_SLEEPING_REM: ClassVar[int]
        STAGE_TYPE_UNKNOWN: ClassVar[int]

    class Stage:
        def __init__(self, p0: Instant, p1: Instant, p2: int) -> None: ...
        def getStartTime(self) -> Instant: ...
        def getEndTime(self) -> Instant: ...
        def equals(self, p0: Any) -> bool: ...
        def hashCode(self) -> int: ...
        def getType(self) -> int: ...

    class Builder:
        def __init__(self, p0: Metadata, p1: Instant, p2: Instant) -> None: ...
        def setTitle(self, p0: str) -> Any: ...
        def setStages(self, p0: list) -> Any: ...
        def setStartZoneOffset(self, p0: ZoneOffset) -> Any: ...
        def setEndZoneOffset(self, p0: ZoneOffset) -> Any: ...
        def clearStartZoneOffset(self) -> Any: ...
        def clearEndZoneOffset(self) -> Any: ...
        def setNotes(self, p0: str) -> Any: ...
        def build(self) -> "SleepSessionRecord": ...
