from typing import Any, ClassVar, overload
from android.health.connect.datatypes.AggregationType import AggregationType
from android.health.connect.datatypes.Metadata import Metadata
from java.time.Instant import Instant
from java.time.ZoneOffset import ZoneOffset

class StepsCadenceRecord:
    STEPS_CADENCE_RATE_AVG: ClassVar[AggregationType]
    STEPS_CADENCE_RATE_MAX: ClassVar[AggregationType]
    STEPS_CADENCE_RATE_MIN: ClassVar[AggregationType]
    def getSamples(self) -> list: ...
    def equals(self, p0: Any) -> bool: ...
    def hashCode(self) -> int: ...

    class StepsCadenceRecordSample:
        def __init__(self, p0: float, p1: Instant) -> None: ...
        def getRate(self) -> float: ...
        def getTime(self) -> Instant: ...
        def equals(self, p0: Any) -> bool: ...
        def hashCode(self) -> int: ...

    class Builder:
        def __init__(self, p0: Metadata, p1: Instant, p2: Instant, p3: list) -> None: ...
        def setStartZoneOffset(self, p0: ZoneOffset) -> Any: ...
        def setEndZoneOffset(self, p0: ZoneOffset) -> Any: ...
        def clearStartZoneOffset(self) -> Any: ...
        def clearEndZoneOffset(self) -> Any: ...
        def build(self) -> "StepsCadenceRecord": ...
