from typing import Any, ClassVar, overload
from android.app.Dialog import Dialog
from android.app.FragmentManager import FragmentManager
from android.app.FragmentTransaction import FragmentTransaction
from android.content.Context import Context
from android.content.DialogInterface import DialogInterface
from android.os.Bundle import Bundle
from android.view.LayoutInflater import LayoutInflater
from java.io.FileDescriptor import FileDescriptor
from java.io.PrintWriter import PrintWriter

class DialogFragment:
    STYLE_NORMAL: ClassVar[int]
    STYLE_NO_FRAME: ClassVar[int]
    STYLE_NO_INPUT: ClassVar[int]
    STYLE_NO_TITLE: ClassVar[int]
    TRIM_MEMORY_BACKGROUND: ClassVar[int]
    TRIM_MEMORY_COMPLETE: ClassVar[int]
    TRIM_MEMORY_MODERATE: ClassVar[int]
    TRIM_MEMORY_RUNNING_CRITICAL: ClassVar[int]
    TRIM_MEMORY_RUNNING_LOW: ClassVar[int]
    TRIM_MEMORY_RUNNING_MODERATE: ClassVar[int]
    TRIM_MEMORY_UI_HIDDEN: ClassVar[int]
    def __init__(self) -> None: ...
    def dismissAllowingStateLoss(self) -> None: ...
    def getDialog(self) -> Dialog: ...
    def isCancelable(self) -> bool: ...
    def setShowsDialog(self, p0: bool) -> None: ...
    def getShowsDialog(self) -> bool: ...
    def setCancelable(self, p0: bool) -> None: ...
    def setStyle(self, p0: int, p1: int) -> None: ...
    def onCancel(self, p0: DialogInterface) -> None: ...
    def onSaveInstanceState(self, p0: Bundle) -> None: ...
    def dismiss(self) -> None: ...
    def onStop(self) -> None: ...
    def onCreate(self, p0: Bundle) -> None: ...
    @overload
    def show(self, p0: FragmentManager, p1: str) -> None: ...
    @overload
    def show(self, p0: FragmentTransaction, p1: str) -> int: ...
    def onCreateDialog(self, p0: Bundle) -> Dialog: ...
    def onDestroyView(self) -> None: ...
    def onDismiss(self, p0: DialogInterface) -> None: ...
    def getTheme(self) -> int: ...
    def onGetLayoutInflater(self, p0: Bundle) -> LayoutInflater: ...
    def onAttach(self, p0: Context) -> None: ...
    def onActivityCreated(self, p0: Bundle) -> None: ...
    def onDetach(self) -> None: ...
    def dump(self, p0: str, p1: FileDescriptor, p2: PrintWriter, p3: Any) -> None: ...
    def onStart(self) -> None: ...
