from typing import Any, ClassVar, overload
from android.content.LocusId import LocusId
from android.os.Bundle import Bundle
from android.os.Parcel import Parcel

class DirectAction:
    CREATOR: ClassVar[Any]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    def equals(self, p0: Any) -> bool: ...
    def hashCode(self) -> int: ...
    def getId(self) -> str: ...
    def getExtras(self) -> Bundle: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
    def describeContents(self) -> int: ...
    def getLocusId(self) -> LocusId: ...

    class Builder:
        def __init__(self, p0: str) -> None: ...
        def build(self) -> "DirectAction": ...
        def setExtras(self, p0: Bundle) -> Any: ...
        def setLocusId(self, p0: LocusId) -> Any: ...
