from typing import Any, ClassVar, overload
from android.content.Context import Context
from android.database.Cursor import Cursor
from android.net.Uri import Uri
from android.os.ParcelFileDescriptor import ParcelFileDescriptor

class DownloadManager:
    ACTION_DOWNLOAD_COMPLETE: ClassVar[str]
    ACTION_NOTIFICATION_CLICKED: ClassVar[str]
    ACTION_VIEW_DOWNLOADS: ClassVar[str]
    COLUMN_BYTES_DOWNLOADED_SO_FAR: ClassVar[str]
    COLUMN_DESCRIPTION: ClassVar[str]
    COLUMN_ID: ClassVar[str]
    COLUMN_LAST_MODIFIED_TIMESTAMP: ClassVar[str]
    COLUMN_LOCAL_FILENAME: ClassVar[str]
    COLUMN_LOCAL_URI: ClassVar[str]
    COLUMN_MEDIAPROVIDER_URI: ClassVar[str]
    COLUMN_MEDIA_TYPE: ClassVar[str]
    COLUMN_REASON: ClassVar[str]
    COLUMN_STATUS: ClassVar[str]
    COLUMN_TITLE: ClassVar[str]
    COLUMN_TOTAL_SIZE_BYTES: ClassVar[str]
    COLUMN_URI: ClassVar[str]
    ERROR_CANNOT_RESUME: ClassVar[int]
    ERROR_DEVICE_NOT_FOUND: ClassVar[int]
    ERROR_FILE_ALREADY_EXISTS: ClassVar[int]
    ERROR_FILE_ERROR: ClassVar[int]
    ERROR_HTTP_DATA_ERROR: ClassVar[int]
    ERROR_INSUFFICIENT_SPACE: ClassVar[int]
    ERROR_TOO_MANY_REDIRECTS: ClassVar[int]
    ERROR_UNHANDLED_HTTP_CODE: ClassVar[int]
    ERROR_UNKNOWN: ClassVar[int]
    EXTRA_DOWNLOAD_ID: ClassVar[str]
    EXTRA_NOTIFICATION_CLICK_DOWNLOAD_IDS: ClassVar[str]
    INTENT_EXTRAS_SORT_BY_SIZE: ClassVar[str]
    PAUSED_QUEUED_FOR_WIFI: ClassVar[int]
    PAUSED_UNKNOWN: ClassVar[int]
    PAUSED_WAITING_FOR_NETWORK: ClassVar[int]
    PAUSED_WAITING_TO_RETRY: ClassVar[int]
    STATUS_FAILED: ClassVar[int]
    STATUS_PAUSED: ClassVar[int]
    STATUS_PENDING: ClassVar[int]
    STATUS_RUNNING: ClassVar[int]
    STATUS_SUCCESSFUL: ClassVar[int]
    @overload
    def addCompletedDownload(self, p0: str, p1: str, p2: bool, p3: str, p4: str, p5: int, p6: bool, p7: Uri, p8: Uri) -> int: ...
    @overload
    def addCompletedDownload(self, p0: str, p1: str, p2: bool, p3: str, p4: str, p5: int, p6: bool) -> int: ...
    @staticmethod
    def getMaxBytesOverMobile(p0: Context) -> int: ...
    def getMimeTypeForDownloadedFile(self, p0: int) -> str: ...
    @staticmethod
    def getRecommendedMaxBytesOverMobile(p0: Context) -> int: ...
    def getUriForDownloadedFile(self, p0: int) -> Uri: ...
    def openDownloadedFile(self, p0: int) -> ParcelFileDescriptor: ...
    def remove(self, p0: Any) -> int: ...
    def enqueue(self, p0: Any) -> int: ...
    def query(self, p0: Any) -> Cursor: ...

    class Request:
        NETWORK_MOBILE: ClassVar[int]
        NETWORK_WIFI: ClassVar[int]
        VISIBILITY_HIDDEN: ClassVar[int]
        VISIBILITY_VISIBLE: ClassVar[int]
        VISIBILITY_VISIBLE_NOTIFY_COMPLETED: ClassVar[int]
        VISIBILITY_VISIBLE_NOTIFY_ONLY_COMPLETION: ClassVar[int]
        def __init__(self, p0: Uri) -> None: ...
        def setMimeType(self, p0: str) -> Any: ...
        def setRequiresDeviceIdle(self, p0: bool) -> Any: ...
        def addRequestHeader(self, p0: str, p1: str) -> Any: ...
        def allowScanningByMediaScanner(self) -> None: ...
        def setAllowedNetworkTypes(self, p0: int) -> Any: ...
        def setAllowedOverMetered(self, p0: bool) -> Any: ...
        def setAllowedOverRoaming(self, p0: bool) -> Any: ...
        def setDestinationInExternalFilesDir(self, p0: Context, p1: str, p2: str) -> Any: ...
        def setDestinationInExternalPublicDir(self, p0: str, p1: str) -> Any: ...
        def setDestinationUri(self, p0: Uri) -> Any: ...
        def setNotificationVisibility(self, p0: int) -> Any: ...
        def setShowRunningNotification(self, p0: bool) -> Any: ...
        def setVisibleInDownloadsUi(self, p0: bool) -> Any: ...
        def setDescription(self, p0: str) -> Any: ...
        def setRequiresCharging(self, p0: bool) -> Any: ...
        def setTitle(self, p0: str) -> Any: ...

    class Query:
        def __init__(self) -> None: ...
        def setFilterById(self, p0: Any) -> Any: ...
        def setFilterByStatus(self, p0: int) -> Any: ...
