from typing import Any, ClassVar, overload
from android.content.Loader import Loader
from android.os.Bundle import Bundle
from java.io.FileDescriptor import FileDescriptor
from java.io.PrintWriter import PrintWriter

class LoaderManager:
    def __init__(self) -> None: ...
    def initLoader(self, p0: int, p1: Bundle, p2: Any) -> Loader: ...
    def restartLoader(self, p0: int, p1: Bundle, p2: Any) -> Loader: ...
    def destroyLoader(self, p0: int) -> None: ...
    @staticmethod
    def enableDebugLogging(p0: bool) -> None: ...
    def getLoader(self, p0: int) -> Loader: ...
    def dump(self, p0: str, p1: FileDescriptor, p2: PrintWriter, p3: Any) -> None: ...

    class LoaderCallbacks:
        def onCreateLoader(self, p0: int, p1: Bundle) -> Loader: ...
        def onLoadFinished(self, p0: Loader, p1: Any) -> None: ...
        def onLoaderReset(self, p0: Loader) -> None: ...
