from typing import Any, ClassVar, overload
from android.graphics.drawable.Icon import Icon
from android.os.Parcel import Parcel

class Person:
    CREATOR: ClassVar[Any]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    def toBuilder(self) -> Any: ...
    def isImportant(self) -> bool: ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
    def isBot(self) -> bool: ...
    def getIcon(self) -> Icon: ...
    def getUri(self) -> str: ...
    def getName(self) -> str: ...
    def equals(self, p0: Any) -> bool: ...
    def hashCode(self) -> int: ...
    def getKey(self) -> str: ...

    class Builder:
        def __init__(self) -> None: ...
        def setImportant(self, p0: bool) -> Any: ...
        def setBot(self, p0: bool) -> Any: ...
        def setKey(self, p0: str) -> Any: ...
        def setUri(self, p0: str) -> Any: ...
        def setIcon(self, p0: Icon) -> Any: ...
        def build(self) -> "Person": ...
        def setName(self, p0: str) -> Any: ...
