from typing import Any, ClassVar, overload
from android.app.PendingIntent import PendingIntent
from android.graphics.drawable.Icon import Icon
from android.os.Parcel import Parcel
from java.io.PrintWriter import PrintWriter

class RemoteAction:
    CREATOR: ClassVar[Any]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    def __init__(self, p0: Icon, p1: str, p2: str, p3: PendingIntent) -> None: ...
    def setShouldShowIcon(self, p0: bool) -> None: ...
    def shouldShowIcon(self) -> bool: ...
    def getActionIntent(self) -> PendingIntent: ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
    def getIcon(self) -> Icon: ...
    def getContentDescription(self) -> str: ...
    def setEnabled(self, p0: bool) -> None: ...
    def getTitle(self) -> str: ...
    def dump(self, p0: str, p1: PrintWriter) -> None: ...
    def equals(self, p0: Any) -> bool: ...
    def hashCode(self) -> int: ...
    @overload
    def clone(self) -> Any: ...
    @overload
    def clone(self) -> "RemoteAction": ...
    def isEnabled(self) -> bool: ...
