from typing import Any, ClassVar, overload
from android.content.Context import Context
from android.graphics.Matrix import Matrix
from android.graphics.RectF import RectF
from android.os.Parcelable import Parcelable
from android.view.View import View

class SharedElementCallback:
    def __init__(self) -> None: ...
    def onCreateSnapshotView(self, p0: Context, p1: Parcelable) -> View: ...
    def onCaptureSharedElementSnapshot(self, p0: View, p1: Matrix, p2: RectF) -> Parcelable: ...
    def onMapSharedElements(self, p0: list, p1: dict) -> None: ...
    def onRejectSharedElements(self, p0: list) -> None: ...
    def onSharedElementEnd(self, p0: list, p1: list, p2: list) -> None: ...
    def onSharedElementStart(self, p0: list, p1: list, p2: list) -> None: ...
    def onSharedElementsArrived(self, p0: list, p1: list, p2: Any) -> None: ...

    class OnSharedElementsReadyListener:
        def onSharedElementsReady(self) -> None: ...
