from typing import Any, ClassVar, overload
from java.util.Iterator import Iterator
from org.json.JSONArray import JSONArray
from org.json.JSONTokener import JSONTokener

class JSONObject:
    NULL: ClassVar[Any]
    @overload
    def __init__(self, p0: "JSONObject", p1: Any) -> None: ...
    @overload
    def __init__(self, p0: str) -> None: ...
    @overload
    def __init__(self, p0: JSONTokener) -> None: ...
    @overload
    def __init__(self, p0: dict) -> None: ...
    @overload
    def __init__(self) -> None: ...
    def putOpt(self, p0: str, p1: Any) -> "JSONObject": ...
    @overload
    def optInt(self, p0: str) -> int: ...
    @overload
    def optInt(self, p0: str, p1: int) -> int: ...
    @overload
    def optDouble(self, p0: str, p1: float) -> float: ...
    @overload
    def optDouble(self, p0: str) -> float: ...
    @overload
    def optBoolean(self, p0: str) -> bool: ...
    @overload
    def optBoolean(self, p0: str, p1: bool) -> bool: ...
    @overload
    def optLong(self, p0: str) -> int: ...
    @overload
    def optLong(self, p0: str, p1: int) -> int: ...
    @overload
    def optString(self, p0: str) -> str: ...
    @overload
    def optString(self, p0: str, p1: str) -> str: ...
    def getJSONArray(self, p0: str) -> JSONArray: ...
    def optJSONArray(self, p0: str) -> JSONArray: ...
    def getJSONObject(self, p0: str) -> "JSONObject": ...
    def optJSONObject(self, p0: str) -> "JSONObject": ...
    def toJSONArray(self, p0: JSONArray) -> JSONArray: ...
    @staticmethod
    def numberToString(p0: float) -> str: ...
    def opt(self, p0: str) -> Any: ...
    def getString(self, p0: str) -> str: ...
    def isNull(self, p0: str) -> bool: ...
    def names(self) -> JSONArray: ...
    def accumulate(self, p0: str, p1: Any) -> "JSONObject": ...
    def has(self, p0: str) -> bool: ...
    @staticmethod
    def quote(p0: str) -> str: ...
    def remove(self, p0: str) -> Any: ...
    def get(self, p0: str) -> Any: ...
    @overload
    def put(self, p0: str, p1: int) -> "JSONObject": ...
    @overload
    def put(self, p0: str, p1: bool) -> "JSONObject": ...
    @overload
    def put(self, p0: str, p1: float) -> "JSONObject": ...
    @overload
    def put(self, p0: str, p1: int) -> "JSONObject": ...
    @overload
    def put(self, p0: str, p1: Any) -> "JSONObject": ...
    def length(self) -> int: ...
    @overload
    def toString(self, p0: int) -> str: ...
    @overload
    def toString(self) -> str: ...
    def append(self, p0: str, p1: Any) -> "JSONObject": ...
    def getBoolean(self, p0: str) -> bool: ...
    def getInt(self, p0: str) -> int: ...
    def getLong(self, p0: str) -> int: ...
    def getDouble(self, p0: str) -> float: ...
    @staticmethod
    def wrap(p0: Any) -> Any: ...
    def keys(self) -> Iterator: ...
