from typing import Any, ClassVar, overload
from android.graphics.Point import Point
from android.os.Parcel import Parcel

class SelectionBoundary:
    CREATOR: ClassVar[Any]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    @overload
    def __init__(self, p0: Point) -> None: ...
    @overload
    def __init__(self, p0: int) -> None: ...
    def getIsRtl(self) -> bool: ...
    def getPoint(self) -> Point: ...
    def getIndex(self) -> int: ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...

from typing import Any, ClassVar, overload
from android.graphics.pdf.models.selection.SelectionBoundary import SelectionBoundary
from android.os.Parcel import Parcel

class PageSelection:
    CREATOR: ClassVar[Any]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    def __init__(self, p0: int, p1: SelectionBoundary, p2: SelectionBoundary, p3: list) -> None: ...
    def getStart(self) -> SelectionBoundary: ...
    def getSelectedTextContents(self) -> list: ...
    def getPage(self) -> int: ...
    def getStop(self) -> SelectionBoundary: ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...

