from typing import Any, ClassVar, overload
from java.io.InputStream import InputStream
from java.io.Reader import Reader
from java.math.BigDecimal import BigDecimal
from java.net.URL import URL
from java.sql.Array import Array
from java.sql.Blob import Blob
from java.sql.Clob import Clob
from java.sql.Date import Date
from java.sql.NClob import NClob
from java.sql.Ref import Ref
from java.sql.RowId import RowId
from java.sql.SQLXML import SQLXML
from java.sql.Time import Time
from java.sql.Timestamp import Timestamp

class SQLInput:
    def readBigDecimal(self) -> BigDecimal: ...
    def readDate(self) -> Date: ...
    def readTime(self) -> Time: ...
    def readTimestamp(self) -> Timestamp: ...
    def readCharacterStream(self) -> Reader: ...
    def readAsciiStream(self) -> InputStream: ...
    def readBinaryStream(self) -> InputStream: ...
    def readRef(self) -> Ref: ...
    def readClob(self) -> Clob: ...
    def wasNull(self) -> bool: ...
    def readURL(self) -> URL: ...
    def readNClob(self) -> NClob: ...
    def readNString(self) -> str: ...
    def readSQLXML(self) -> SQLXML: ...
    def readRowId(self) -> RowId: ...
    @overload
    def readObject(self) -> Any: ...
    @overload
    def readObject(self, p0: type) -> Any: ...
    def readInt(self) -> int: ...
    def readBytes(self) -> Any: ...
    def readFloat(self) -> float: ...
    def readBlob(self) -> Blob: ...
    def readArray(self) -> Array: ...
    def readLong(self) -> int: ...
    def readByte(self) -> int: ...
    def readShort(self) -> int: ...
    def readString(self) -> str: ...
    def readBoolean(self) -> bool: ...
    def readDouble(self) -> float: ...
