from typing import Any, ClassVar, overload

class GroupCallCallback:
    SIGNAL_STRENGTH_UNAVAILABLE: ClassVar[int]
    def onGroupCallStateChanged(self, p0: int, p1: int) -> None: ...
    def onBroadcastSignalStrengthUpdated(self, p0: int) -> None: ...
    def onError(self, p0: int, p1: str) -> None: ...
