from typing import Any, ClassVar, overload

class Output:
    value: Any
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, p0: Any) -> None: ...
    def toString(self) -> str: ...
