from typing import Any, ClassVar, overload

class ValueIterator:
    def setRange(self, p0: int, p1: int) -> None: ...
    def reset(self) -> None: ...
    def next(self, p0: Any) -> bool: ...

    class Element:
        integer: int
        value: Any
        def __init__(self) -> None: ...
