from typing import Any, ClassVar, overload
from android.icu.util.ULocale import ULocale
from java.util.Date import Date
from java.util.Locale import Locale

class TimeZone:
    GENERIC_LOCATION: ClassVar[int]
    GMT_ZONE: ClassVar["TimeZone"]
    LONG: ClassVar[int]
    LONG_GENERIC: ClassVar[int]
    LONG_GMT: ClassVar[int]
    SHORT: ClassVar[int]
    SHORT_COMMONLY_USED: ClassVar[int]
    SHORT_GENERIC: ClassVar[int]
    SHORT_GMT: ClassVar[int]
    TIMEZONE_ICU: ClassVar[int]
    TIMEZONE_JDK: ClassVar[int]
    UNKNOWN_ZONE: ClassVar["TimeZone"]
    UNKNOWN_ZONE_ID: ClassVar[str]
    def __init__(self) -> None: ...
    @overload
    def cloneAsThawed(self) -> "TimeZone": ...
    @overload
    def cloneAsThawed(self) -> Any: ...
    @staticmethod
    def getFrozenTimeZone(p0: str) -> "TimeZone": ...
    @staticmethod
    def countEquivalentIDs(p0: str) -> int: ...
    @staticmethod
    def getEquivalentID(p0: str, p1: int) -> str: ...
    @staticmethod
    def getTZDataVersion() -> str: ...
    @overload
    @staticmethod
    def getCanonicalID(p0: str) -> str: ...
    @overload
    @staticmethod
    def getCanonicalID(p0: str, p1: Any) -> str: ...
    @staticmethod
    def getWindowsID(p0: str) -> str: ...
    @staticmethod
    def getIDForWindowsID(p0: str, p1: str) -> str: ...
    def equals(self, p0: Any) -> bool: ...
    def hashCode(self) -> int: ...
    def clone(self) -> Any: ...
    @staticmethod
    def getDefault() -> "TimeZone": ...
    @overload
    def freeze(self) -> "TimeZone": ...
    @overload
    def freeze(self) -> Any: ...
    @overload
    def getOffset(self, p0: int, p1: int, p2: int, p3: int, p4: int, p5: int) -> int: ...
    @overload
    def getOffset(self, p0: int) -> int: ...
    @overload
    def getOffset(self, p0: int, p1: bool, p2: Any) -> None: ...
    def isFrozen(self) -> bool: ...
    @staticmethod
    def getRegion(p0: str) -> str: ...
    def getID(self) -> str: ...
    @overload
    def getDisplayName(self, p0: bool, p1: int) -> str: ...
    @overload
    def getDisplayName(self, p0: bool, p1: int, p2: Locale) -> str: ...
    @overload
    def getDisplayName(self, p0: bool, p1: int, p2: ULocale) -> str: ...
    @overload
    def getDisplayName(self, p0: ULocale) -> str: ...
    @overload
    def getDisplayName(self, p0: Locale) -> str: ...
    @overload
    def getDisplayName(self) -> str: ...
    @overload
    @staticmethod
    def getTimeZone(p0: str) -> "TimeZone": ...
    @overload
    @staticmethod
    def getTimeZone(p0: str, p1: int) -> "TimeZone": ...
    def inDaylightTime(self, p0: Date) -> bool: ...
    def getRawOffset(self) -> int: ...
    def getDSTSavings(self) -> int: ...
    def useDaylightTime(self) -> bool: ...
    @overload
    @staticmethod
    def getAvailableIDs(p0: Any, p1: str, p2: int) -> set: ...
    @overload
    @staticmethod
    def getAvailableIDs() -> Any: ...
    @overload
    @staticmethod
    def getAvailableIDs(p0: int) -> Any: ...
    @overload
    @staticmethod
    def getAvailableIDs(p0: str) -> Any: ...
    def setID(self, p0: str) -> None: ...
    def setRawOffset(self, p0: int) -> None: ...
    def observesDaylightTime(self) -> bool: ...
    def hasSameRules(self, p0: "TimeZone") -> bool: ...

    class SystemTimeZoneType:
        ANY: ClassVar["SystemTimeZoneType"]
        CANONICAL: ClassVar["SystemTimeZoneType"]
        CANONICAL_LOCATION: ClassVar["SystemTimeZoneType"]
        ANY: ClassVar[Any]
        CANONICAL: ClassVar[Any]
        CANONICAL_LOCATION: ClassVar[Any]
        @staticmethod
        def values() -> Any: ...
        @staticmethod
        def valueOf(p0: str) -> Any: ...
