from typing import Any, ClassVar, overload
from android.os.Parcel import Parcel

class AutofillValue:
    CREATOR: ClassVar[Any]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    def equals(self, p0: Any) -> bool: ...
    def toString(self) -> str: ...
    def hashCode(self) -> int: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
    def describeContents(self) -> int: ...
    @staticmethod
    def forList(p0: int) -> "AutofillValue": ...
    @staticmethod
    def forText(p0: str) -> "AutofillValue": ...
    @staticmethod
    def forDate(p0: int) -> "AutofillValue": ...
    @staticmethod
    def forToggle(p0: bool) -> "AutofillValue": ...
    def getDateValue(self) -> int: ...
    def getListValue(self) -> int: ...
    def getTextValue(self) -> str: ...
    def getToggleValue(self) -> bool: ...
    def isDate(self) -> bool: ...
    def isList(self) -> bool: ...
    def isText(self) -> bool: ...
    def isToggle(self) -> bool: ...
