from typing import Any, ClassVar, overload

class VirtualViewFillInfo:
    def getAutofillHints(self) -> Any: ...

    class Builder:
        def __init__(self) -> None: ...
        def build(self) -> "VirtualViewFillInfo": ...
        def setAutofillHints(self, p0: Any) -> Any: ...
