from typing import Any, ClassVar, overload
from android.media.AudioDeviceInfo import AudioDeviceInfo
from android.media.AudioFormat import AudioFormat
from android.os.Parcel import Parcel

class AudioRecordingConfiguration:
    CREATOR: ClassVar[Any]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    def getAudioDevice(self) -> AudioDeviceInfo: ...
    def getClientFormat(self) -> AudioFormat: ...
    def getClientAudioSessionId(self) -> int: ...
    def getEffects(self) -> list: ...
    def isClientSilenced(self) -> bool: ...
    def getClientAudioSource(self) -> int: ...
    def getClientEffects(self) -> list: ...
    def getAudioSource(self) -> int: ...
    def equals(self, p0: Any) -> bool: ...
    def hashCode(self) -> int: ...
    def getFormat(self) -> AudioFormat: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
    def describeContents(self) -> int: ...
