from typing import Any, ClassVar, overload
from android.media.AudioAttributes import AudioAttributes
from android.media.AudioDeviceInfo import AudioDeviceInfo
from android.os.Parcel import Parcel

class AudioPlaybackConfiguration:
    CREATOR: ClassVar[Any]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    def getAudioDeviceInfo(self) -> AudioDeviceInfo: ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
    def getAudioAttributes(self) -> AudioAttributes: ...
    def equals(self, p0: Any) -> bool: ...
    def toString(self) -> str: ...
    def hashCode(self) -> int: ...
