from typing import Any, ClassVar, overload
from android.media.projection.MediaProjection import MediaProjection

class AudioPlaybackCaptureConfiguration:
    def getMatchingUids(self) -> Any: ...
    def getExcludeUids(self) -> Any: ...
    def getExcludeUsages(self) -> Any: ...
    def getMatchingUsages(self) -> Any: ...
    def getMediaProjection(self) -> MediaProjection: ...

    class Builder:
        def __init__(self, p0: MediaProjection) -> None: ...
        def addMatchingUid(self, p0: int) -> Any: ...
        def addMatchingUsage(self, p0: int) -> Any: ...
        def excludeUid(self, p0: int) -> Any: ...
        def excludeUsage(self, p0: int) -> Any: ...
        def build(self) -> "AudioPlaybackCaptureConfiguration": ...
