from typing import Any, ClassVar, overload

class EncoderProfiles:
    def getVideoProfiles(self) -> list: ...
    def getDefaultDurationSeconds(self) -> int: ...
    def getRecommendedFileFormat(self) -> int: ...
    def getAudioProfiles(self) -> list: ...

    class VideoProfile:
        HDR_DOLBY_VISION: ClassVar[int]
        HDR_HDR10: ClassVar[int]
        HDR_HDR10PLUS: ClassVar[int]
        HDR_HLG: ClassVar[int]
        HDR_NONE: ClassVar[int]
        YUV_420: ClassVar[int]
        YUV_422: ClassVar[int]
        YUV_444: ClassVar[int]
        def getCodec(self) -> int: ...
        def getFrameRate(self) -> int: ...
        def getBitrate(self) -> int: ...
        def getMediaType(self) -> str: ...
        def getBitDepth(self) -> int: ...
        def getChromaSubsampling(self) -> int: ...
        def getHdrFormat(self) -> int: ...
        def getWidth(self) -> int: ...
        def getHeight(self) -> int: ...
        def getProfile(self) -> int: ...

    class AudioProfile:
        def getCodec(self) -> int: ...
        def getBitrate(self) -> int: ...
        def getMediaType(self) -> str: ...
        def getSampleRate(self) -> int: ...
        def getChannels(self) -> int: ...
        def getProfile(self) -> int: ...
