from typing import Any, ClassVar, overload
from android.media.MediaCodec import MediaCodec
from android.os.Bundle import Bundle
from java.util.concurrent.Executor import Executor

class LoudnessCodecController:
    def addMediaCodec(self, p0: MediaCodec) -> bool: ...
    def removeMediaCodec(self, p0: MediaCodec) -> None: ...
    def getLoudnessCodecParams(self, p0: MediaCodec) -> Bundle: ...
    @overload
    @staticmethod
    def create(p0: int) -> "LoudnessCodecController": ...
    @overload
    @staticmethod
    def create(p0: int, p1: Executor, p2: Any) -> "LoudnessCodecController": ...
    def close(self) -> None: ...

    class OnLoudnessCodecUpdateListener:
        def onLoudnessCodecUpdate(self, p0: MediaCodec, p1: Bundle) -> Bundle: ...
