from typing import Any, ClassVar, overload

class MediaDrmException:
    def __init__(self, p0: str) -> None: ...
    def getErrorContext(self) -> int: ...
    def getVendorError(self) -> int: ...
    def getOemError(self) -> int: ...
