from typing import Any, ClassVar, overload
from android.os.Parcel import Parcel
from android.util.Size import Size

class MediaItemInfo:
    CREATOR: ClassVar[Any]
    DATA_TYPE_AUDIO: ClassVar[int]
    DATA_TYPE_DEPTH: ClassVar[int]
    DATA_TYPE_GAIN_MAP: ClassVar[int]
    DATA_TYPE_GAPLESS: ClassVar[int]
    DATA_TYPE_HIGH_DYNAMIC_RANGE_VIDEO: ClassVar[int]
    DATA_TYPE_HIGH_FRAME_RATE: ClassVar[int]
    DATA_TYPE_IMAGE: ClassVar[int]
    DATA_TYPE_METADATA: ClassVar[int]
    DATA_TYPE_SPATIAL_AUDIO: ClassVar[int]
    DATA_TYPE_SPEED_SETTING_CUE_POINTS: ClassVar[int]
    DATA_TYPE_VIDEO: ClassVar[int]
    SOURCE_TYPE_CAMERA: ClassVar[int]
    SOURCE_TYPE_EDITING_SESSION: ClassVar[int]
    SOURCE_TYPE_GALLERY: ClassVar[int]
    SOURCE_TYPE_GENERATED: ClassVar[int]
    SOURCE_TYPE_LOCAL_FILE: ClassVar[int]
    SOURCE_TYPE_REMOTE_FILE: ClassVar[int]
    SOURCE_TYPE_REMOTE_LIVE_STREAM: ClassVar[int]
    SOURCE_TYPE_UNSPECIFIED: ClassVar[int]
    VALUE_UNSPECIFIED: ClassVar[int]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    def getDurationMillis(self) -> int: ...
    def getCodecNames(self) -> list: ...
    def getDataTypes(self) -> int: ...
    def getAudioChannelCount(self) -> int: ...
    def getAudioSampleCount(self) -> int: ...
    def getAudioSampleRateHz(self) -> int: ...
    def getClipDurationMillis(self) -> int: ...
    def getContainerMimeType(self) -> str: ...
    def getSampleMimeTypes(self) -> list: ...
    def getSourceType(self) -> int: ...
    def getVideoDataSpace(self) -> int: ...
    def getVideoFrameRate(self) -> float: ...
    def getVideoSampleCount(self) -> int: ...
    def getVideoSize(self) -> Size: ...
    def equals(self, p0: Any) -> bool: ...
    def toString(self) -> str: ...
    def hashCode(self) -> int: ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...

    class Builder:
        def __init__(self) -> None: ...
        def setDurationMillis(self, p0: int) -> Any: ...
        def addCodecName(self, p0: str) -> Any: ...
        def addSampleMimeType(self, p0: str) -> Any: ...
        def setAudioChannelCount(self, p0: int) -> Any: ...
        def setAudioSampleCount(self, p0: int) -> Any: ...
        def setAudioSampleRateHz(self, p0: int) -> Any: ...
        def setClipDurationMillis(self, p0: int) -> Any: ...
        def setContainerMimeType(self, p0: str) -> Any: ...
        def setSourceType(self, p0: int) -> Any: ...
        def setVideoDataSpace(self, p0: int) -> Any: ...
        def setVideoFrameRate(self, p0: float) -> Any: ...
        def setVideoSampleCount(self, p0: int) -> Any: ...
        def setVideoSize(self, p0: Size) -> Any: ...
        def build(self) -> "MediaItemInfo": ...
        def addDataType(self, p0: int) -> Any: ...

from typing import Any, ClassVar, overload
from android.os.Bundle import Bundle
from android.os.Parcel import Parcel
from java.lang.Exception import Exception

class PlaybackErrorEvent:
    CREATOR: ClassVar[Any]
    ERROR_AUDIO_TRACK_INIT_FAILED: ClassVar[int]
    ERROR_AUDIO_TRACK_OTHER: ClassVar[int]
    ERROR_AUDIO_TRACK_WRITE_FAILED: ClassVar[int]
    ERROR_DECODER_INIT_FAILED: ClassVar[int]
    ERROR_DECODING_FAILED: ClassVar[int]
    ERROR_DECODING_FORMAT_EXCEEDS_CAPABILITIES: ClassVar[int]
    ERROR_DECODING_FORMAT_UNSUPPORTED: ClassVar[int]
    ERROR_DECODING_OTHER: ClassVar[int]
    ERROR_DRM_CONTENT_ERROR: ClassVar[int]
    ERROR_DRM_DEVICE_REVOKED: ClassVar[int]
    ERROR_DRM_DISALLOWED_OPERATION: ClassVar[int]
    ERROR_DRM_LICENSE_ACQUISITION_FAILED: ClassVar[int]
    ERROR_DRM_OTHER: ClassVar[int]
    ERROR_DRM_PROVISIONING_FAILED: ClassVar[int]
    ERROR_DRM_SCHEME_UNSUPPORTED: ClassVar[int]
    ERROR_DRM_SYSTEM_ERROR: ClassVar[int]
    ERROR_IO_BAD_HTTP_STATUS: ClassVar[int]
    ERROR_IO_CONNECTION_CLOSED: ClassVar[int]
    ERROR_IO_CONNECTION_TIMEOUT: ClassVar[int]
    ERROR_IO_DNS_FAILED: ClassVar[int]
    ERROR_IO_FILE_NOT_FOUND: ClassVar[int]
    ERROR_IO_NETWORK_CONNECTION_FAILED: ClassVar[int]
    ERROR_IO_NETWORK_UNAVAILABLE: ClassVar[int]
    ERROR_IO_NO_PERMISSION: ClassVar[int]
    ERROR_IO_OTHER: ClassVar[int]
    ERROR_OTHER: ClassVar[int]
    ERROR_PARSING_CONTAINER_MALFORMED: ClassVar[int]
    ERROR_PARSING_CONTAINER_UNSUPPORTED: ClassVar[int]
    ERROR_PARSING_MANIFEST_MALFORMED: ClassVar[int]
    ERROR_PARSING_MANIFEST_UNSUPPORTED: ClassVar[int]
    ERROR_PARSING_OTHER: ClassVar[int]
    ERROR_PLAYER_BEHIND_LIVE_WINDOW: ClassVar[int]
    ERROR_PLAYER_OTHER: ClassVar[int]
    ERROR_PLAYER_REMOTE: ClassVar[int]
    ERROR_RUNTIME: ClassVar[int]
    ERROR_UNKNOWN: ClassVar[int]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    def getMetricsBundle(self) -> Bundle: ...
    def getSubErrorCode(self) -> int: ...
    def getTimeSinceCreatedMillis(self) -> int: ...
    def getErrorCode(self) -> int: ...
    def equals(self, p0: Any) -> bool: ...
    def toString(self) -> str: ...
    def hashCode(self) -> int: ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...

    class Builder:
        def __init__(self) -> None: ...
        def setErrorCode(self, p0: int) -> Any: ...
        def setException(self, p0: Exception) -> Any: ...
        def setMetricsBundle(self, p0: Bundle) -> Any: ...
        def setSubErrorCode(self, p0: int) -> Any: ...
        def setTimeSinceCreatedMillis(self, p0: int) -> Any: ...
        def build(self) -> "PlaybackErrorEvent": ...

from typing import Any, ClassVar, overload
from android.media.metrics.LogSessionId import LogSessionId

class TranscodingSession:
    def getSessionId(self) -> LogSessionId: ...
    def equals(self, p0: Any) -> bool: ...
    def hashCode(self) -> int: ...
    def close(self) -> None: ...

from typing import Any, ClassVar, overload
from android.media.metrics.LogSessionId import LogSessionId

class RecordingSession:
    def getSessionId(self) -> LogSessionId: ...
    def equals(self, p0: Any) -> bool: ...
    def hashCode(self) -> int: ...
    def close(self) -> None: ...

from typing import Any, ClassVar, overload
from android.os.Bundle import Bundle

class Event:
    def getMetricsBundle(self) -> Bundle: ...
    def getTimeSinceCreatedMillis(self) -> int: ...

from typing import Any, ClassVar, overload
from android.media.metrics.LogSessionId import LogSessionId
from android.media.metrics.NetworkEvent import NetworkEvent
from android.media.metrics.PlaybackErrorEvent import PlaybackErrorEvent
from android.media.metrics.PlaybackMetrics import PlaybackMetrics
from android.media.metrics.PlaybackStateEvent import PlaybackStateEvent
from android.media.metrics.TrackChangeEvent import TrackChangeEvent

class PlaybackSession:
    def reportNetworkEvent(self, p0: NetworkEvent) -> None: ...
    def reportPlaybackErrorEvent(self, p0: PlaybackErrorEvent) -> None: ...
    def reportPlaybackMetrics(self, p0: PlaybackMetrics) -> None: ...
    def reportPlaybackStateEvent(self, p0: PlaybackStateEvent) -> None: ...
    def reportTrackChangeEvent(self, p0: TrackChangeEvent) -> None: ...
    def getSessionId(self) -> LogSessionId: ...
    def equals(self, p0: Any) -> bool: ...
    def hashCode(self) -> int: ...
    def close(self) -> None: ...

from typing import Any, ClassVar, overload
from android.os.Bundle import Bundle
from android.os.Parcel import Parcel

class TrackChangeEvent:
    CREATOR: ClassVar[Any]
    TRACK_CHANGE_REASON_ADAPTIVE: ClassVar[int]
    TRACK_CHANGE_REASON_INITIAL: ClassVar[int]
    TRACK_CHANGE_REASON_MANUAL: ClassVar[int]
    TRACK_CHANGE_REASON_OTHER: ClassVar[int]
    TRACK_CHANGE_REASON_UNKNOWN: ClassVar[int]
    TRACK_STATE_OFF: ClassVar[int]
    TRACK_STATE_ON: ClassVar[int]
    TRACK_TYPE_AUDIO: ClassVar[int]
    TRACK_TYPE_TEXT: ClassVar[int]
    TRACK_TYPE_VIDEO: ClassVar[int]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    def getChannelCount(self) -> int: ...
    def getCodecName(self) -> str: ...
    def getAudioSampleRate(self) -> int: ...
    def getBitrate(self) -> int: ...
    def getLanguageRegion(self) -> str: ...
    def getSampleMimeType(self) -> str: ...
    def getTrackChangeReason(self) -> int: ...
    def getTrackState(self) -> int: ...
    def getTrackType(self) -> int: ...
    def getContainerMimeType(self) -> str: ...
    def getVideoFrameRate(self) -> float: ...
    def getMetricsBundle(self) -> Bundle: ...
    def getTimeSinceCreatedMillis(self) -> int: ...
    def equals(self, p0: Any) -> bool: ...
    def toString(self) -> str: ...
    def hashCode(self) -> int: ...
    def getLanguage(self) -> str: ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
    def getHeight(self) -> int: ...
    def getWidth(self) -> int: ...

    class Builder:
        def __init__(self, p0: int) -> None: ...
        def setChannelCount(self, p0: int) -> Any: ...
        def setMetricsBundle(self, p0: Bundle) -> Any: ...
        def setTimeSinceCreatedMillis(self, p0: int) -> Any: ...
        def setAudioSampleRate(self, p0: int) -> Any: ...
        def setBitrate(self, p0: int) -> Any: ...
        def setCodecName(self, p0: str) -> Any: ...
        def setLanguageRegion(self, p0: str) -> Any: ...
        def setSampleMimeType(self, p0: str) -> Any: ...
        def setTrackChangeReason(self, p0: int) -> Any: ...
        def setTrackState(self, p0: int) -> Any: ...
        def setContainerMimeType(self, p0: str) -> Any: ...
        def setVideoFrameRate(self, p0: float) -> Any: ...
        def build(self) -> "TrackChangeEvent": ...
        def setLanguage(self, p0: str) -> Any: ...
        def setHeight(self, p0: int) -> Any: ...
        def setWidth(self, p0: int) -> Any: ...

from typing import Any, ClassVar, overload
from android.media.metrics.BundleSession import BundleSession
from android.media.metrics.EditingSession import EditingSession
from android.media.metrics.PlaybackSession import PlaybackSession
from android.media.metrics.RecordingSession import RecordingSession
from android.media.metrics.TranscodingSession import TranscodingSession

class MediaMetricsManager:
    INVALID_TIMESTAMP: ClassVar[int]
    def createTranscodingSession(self) -> TranscodingSession: ...
    def createBundleSession(self) -> BundleSession: ...
    def createEditingSession(self) -> EditingSession: ...
    def createPlaybackSession(self) -> PlaybackSession: ...
    def createRecordingSession(self) -> RecordingSession: ...
    def releaseSessionId(self, p0: str) -> None: ...

from typing import Any, ClassVar, overload
from android.media.metrics.MediaItemInfo import MediaItemInfo
from android.os.Bundle import Bundle
from android.os.Parcel import Parcel

class EditingEndedEvent:
    CREATOR: ClassVar[Any]
    ERROR_CODE_AUDIO_PROCESSING_FAILED: ClassVar[int]
    ERROR_CODE_DECODER_INIT_FAILED: ClassVar[int]
    ERROR_CODE_DECODING_FAILED: ClassVar[int]
    ERROR_CODE_DECODING_FORMAT_UNSUPPORTED: ClassVar[int]
    ERROR_CODE_ENCODER_INIT_FAILED: ClassVar[int]
    ERROR_CODE_ENCODING_FAILED: ClassVar[int]
    ERROR_CODE_ENCODING_FORMAT_UNSUPPORTED: ClassVar[int]
    ERROR_CODE_FAILED_RUNTIME_CHECK: ClassVar[int]
    ERROR_CODE_IO_BAD_HTTP_STATUS: ClassVar[int]
    ERROR_CODE_IO_CLEARTEXT_NOT_PERMITTED: ClassVar[int]
    ERROR_CODE_IO_FILE_NOT_FOUND: ClassVar[int]
    ERROR_CODE_IO_NETWORK_CONNECTION_FAILED: ClassVar[int]
    ERROR_CODE_IO_NETWORK_CONNECTION_TIMEOUT: ClassVar[int]
    ERROR_CODE_IO_NO_PERMISSION: ClassVar[int]
    ERROR_CODE_IO_READ_POSITION_OUT_OF_RANGE: ClassVar[int]
    ERROR_CODE_IO_UNSPECIFIED: ClassVar[int]
    ERROR_CODE_MUXING_FAILED: ClassVar[int]
    ERROR_CODE_NONE: ClassVar[int]
    ERROR_CODE_VIDEO_FRAME_PROCESSING_FAILED: ClassVar[int]
    FINAL_STATE_CANCELED: ClassVar[int]
    FINAL_STATE_ERROR: ClassVar[int]
    FINAL_STATE_SUCCEEDED: ClassVar[int]
    OPERATION_TYPE_AUDIO_EDIT: ClassVar[int]
    OPERATION_TYPE_AUDIO_TRANSCODE: ClassVar[int]
    OPERATION_TYPE_AUDIO_TRANSMUX: ClassVar[int]
    OPERATION_TYPE_PAUSED: ClassVar[int]
    OPERATION_TYPE_RESUMED: ClassVar[int]
    OPERATION_TYPE_VIDEO_EDIT: ClassVar[int]
    OPERATION_TYPE_VIDEO_TRANSCODE: ClassVar[int]
    OPERATION_TYPE_VIDEO_TRANSMUX: ClassVar[int]
    PROGRESS_PERCENT_UNKNOWN: ClassVar[int]
    TIME_SINCE_CREATED_UNKNOWN: ClassVar[int]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    def getExporterName(self) -> str: ...
    def getFinalProgressPercent(self) -> float: ...
    def getFinalState(self) -> int: ...
    def getInputMediaItemInfos(self) -> list: ...
    def getMuxerName(self) -> str: ...
    def getOperationTypes(self) -> int: ...
    def getOutputMediaItemInfo(self) -> MediaItemInfo: ...
    def getMetricsBundle(self) -> Bundle: ...
    def getTimeSinceCreatedMillis(self) -> int: ...
    def getErrorCode(self) -> int: ...
    def equals(self, p0: Any) -> bool: ...
    def toString(self) -> str: ...
    def hashCode(self) -> int: ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...

    class Builder:
        def __init__(self, p0: int) -> None: ...
        def setErrorCode(self, p0: int) -> Any: ...
        def setMetricsBundle(self, p0: Bundle) -> Any: ...
        def setTimeSinceCreatedMillis(self, p0: int) -> Any: ...
        def setFinalProgressPercent(self, p0: float) -> Any: ...
        def addInputMediaItemInfo(self, p0: MediaItemInfo) -> Any: ...
        def addOperationType(self, p0: int) -> Any: ...
        def setExporterName(self, p0: str) -> Any: ...
        def setMuxerName(self, p0: str) -> Any: ...
        def setOutputMediaItemInfo(self, p0: MediaItemInfo) -> Any: ...
        def build(self) -> "EditingEndedEvent": ...

from typing import Any, ClassVar, overload
from android.os.Bundle import Bundle
from android.os.Parcel import Parcel

class PlaybackMetrics:
    CONTENT_TYPE_AD: ClassVar[int]
    CONTENT_TYPE_MAIN: ClassVar[int]
    CONTENT_TYPE_OTHER: ClassVar[int]
    CONTENT_TYPE_UNKNOWN: ClassVar[int]
    CREATOR: ClassVar[Any]
    DRM_TYPE_CLEARKEY: ClassVar[int]
    DRM_TYPE_NONE: ClassVar[int]
    DRM_TYPE_OTHER: ClassVar[int]
    DRM_TYPE_PLAY_READY: ClassVar[int]
    DRM_TYPE_WIDEVINE_L1: ClassVar[int]
    DRM_TYPE_WIDEVINE_L3: ClassVar[int]
    DRM_TYPE_WV_L3_FALLBACK: ClassVar[int]
    PLAYBACK_TYPE_LIVE: ClassVar[int]
    PLAYBACK_TYPE_OTHER: ClassVar[int]
    PLAYBACK_TYPE_UNKNOWN: ClassVar[int]
    PLAYBACK_TYPE_VOD: ClassVar[int]
    STREAM_SOURCE_DEVICE: ClassVar[int]
    STREAM_SOURCE_MIXED: ClassVar[int]
    STREAM_SOURCE_NETWORK: ClassVar[int]
    STREAM_SOURCE_UNKNOWN: ClassVar[int]
    STREAM_TYPE_DASH: ClassVar[int]
    STREAM_TYPE_HLS: ClassVar[int]
    STREAM_TYPE_OTHER: ClassVar[int]
    STREAM_TYPE_PROGRESSIVE: ClassVar[int]
    STREAM_TYPE_SS: ClassVar[int]
    STREAM_TYPE_UNKNOWN: ClassVar[int]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    def getNetworkTransferDurationMillis(self) -> int: ...
    def getAudioUnderrunCount(self) -> int: ...
    def getDrmSessionId(self) -> Any: ...
    def getDrmType(self) -> int: ...
    def getExperimentIds(self) -> Any: ...
    def getLocalBytesRead(self) -> int: ...
    def getMediaDurationMillis(self) -> int: ...
    def getNetworkBytesRead(self) -> int: ...
    def getPlaybackType(self) -> int: ...
    def getPlayerName(self) -> str: ...
    def getPlayerVersion(self) -> str: ...
    def getStreamSource(self) -> int: ...
    def getStreamType(self) -> int: ...
    def getVideoFramesDropped(self) -> int: ...
    def getVideoFramesPlayed(self) -> int: ...
    def getMetricsBundle(self) -> Bundle: ...
    def equals(self, p0: Any) -> bool: ...
    def toString(self) -> str: ...
    def hashCode(self) -> int: ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
    def getContentType(self) -> int: ...

    class Builder:
        def __init__(self) -> None: ...
        def setMetricsBundle(self, p0: Bundle) -> Any: ...
        def addExperimentId(self, p0: int) -> Any: ...
        def setMediaDurationMillis(self, p0: int) -> Any: ...
        def setNetworkBytesRead(self, p0: int) -> Any: ...
        def setNetworkTransferDurationMillis(self, p0: int) -> Any: ...
        def setPlaybackType(self, p0: int) -> Any: ...
        def setPlayerName(self, p0: str) -> Any: ...
        def setPlayerVersion(self, p0: str) -> Any: ...
        def setAudioUnderrunCount(self, p0: int) -> Any: ...
        def setDrmSessionId(self, p0: Any) -> Any: ...
        def setDrmType(self, p0: int) -> Any: ...
        def setLocalBytesRead(self, p0: int) -> Any: ...
        def setStreamSource(self, p0: int) -> Any: ...
        def setStreamType(self, p0: int) -> Any: ...
        def setVideoFramesDropped(self, p0: int) -> Any: ...
        def setVideoFramesPlayed(self, p0: int) -> Any: ...
        def build(self) -> "PlaybackMetrics": ...
        def setContentType(self, p0: int) -> Any: ...

from typing import Any, ClassVar, overload

class LogSessionId:
    LOG_SESSION_ID_NONE: ClassVar["LogSessionId"]
    def getStringId(self) -> str: ...
    def equals(self, p0: Any) -> bool: ...
    def toString(self) -> str: ...
    def hashCode(self) -> int: ...

from typing import Any, ClassVar, overload
from android.os.Bundle import Bundle
from android.os.Parcel import Parcel

class PlaybackStateEvent:
    CREATOR: ClassVar[Any]
    STATE_ABANDONED: ClassVar[int]
    STATE_BUFFERING: ClassVar[int]
    STATE_ENDED: ClassVar[int]
    STATE_FAILED: ClassVar[int]
    STATE_INTERRUPTED_BY_AD: ClassVar[int]
    STATE_JOINING_BACKGROUND: ClassVar[int]
    STATE_JOINING_FOREGROUND: ClassVar[int]
    STATE_NOT_STARTED: ClassVar[int]
    STATE_PAUSED: ClassVar[int]
    STATE_PAUSED_BUFFERING: ClassVar[int]
    STATE_PLAYING: ClassVar[int]
    STATE_SEEKING: ClassVar[int]
    STATE_STOPPED: ClassVar[int]
    STATE_SUPPRESSED: ClassVar[int]
    STATE_SUPPRESSED_BUFFERING: ClassVar[int]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    def getMetricsBundle(self) -> Bundle: ...
    def getTimeSinceCreatedMillis(self) -> int: ...
    def equals(self, p0: Any) -> bool: ...
    def hashCode(self) -> int: ...
    def getState(self) -> int: ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...

    class Builder:
        def __init__(self) -> None: ...
        def setMetricsBundle(self, p0: Bundle) -> Any: ...
        def setTimeSinceCreatedMillis(self, p0: int) -> Any: ...
        def build(self) -> "PlaybackStateEvent": ...
        def setState(self, p0: int) -> Any: ...

from typing import Any, ClassVar, overload
from android.media.metrics.LogSessionId import LogSessionId
from android.os.PersistableBundle import PersistableBundle

class BundleSession:
    KEY_STATSD_ATOM: ClassVar[str]
    def reportBundleMetrics(self, p0: PersistableBundle) -> None: ...
    def getSessionId(self) -> LogSessionId: ...
    def equals(self, p0: Any) -> bool: ...
    def hashCode(self) -> int: ...
    def close(self) -> None: ...

from typing import Any, ClassVar, overload
from android.os.Bundle import Bundle
from android.os.Parcel import Parcel

class NetworkEvent:
    CREATOR: ClassVar[Any]
    NETWORK_TYPE_2G: ClassVar[int]
    NETWORK_TYPE_3G: ClassVar[int]
    NETWORK_TYPE_4G: ClassVar[int]
    NETWORK_TYPE_5G_NSA: ClassVar[int]
    NETWORK_TYPE_5G_SA: ClassVar[int]
    NETWORK_TYPE_ETHERNET: ClassVar[int]
    NETWORK_TYPE_OFFLINE: ClassVar[int]
    NETWORK_TYPE_OTHER: ClassVar[int]
    NETWORK_TYPE_UNKNOWN: ClassVar[int]
    NETWORK_TYPE_WIFI: ClassVar[int]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    def getNetworkType(self) -> int: ...
    def getMetricsBundle(self) -> Bundle: ...
    def getTimeSinceCreatedMillis(self) -> int: ...
    def equals(self, p0: Any) -> bool: ...
    def toString(self) -> str: ...
    def hashCode(self) -> int: ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...

    class Builder:
        def __init__(self) -> None: ...
        def setMetricsBundle(self, p0: Bundle) -> Any: ...
        def setTimeSinceCreatedMillis(self, p0: int) -> Any: ...
        def setNetworkType(self, p0: int) -> Any: ...
        def build(self) -> "NetworkEvent": ...

from typing import Any, ClassVar, overload
from android.media.metrics.EditingEndedEvent import EditingEndedEvent
from android.media.metrics.LogSessionId import LogSessionId

class EditingSession:
    def reportEditingEndedEvent(self, p0: EditingEndedEvent) -> None: ...
    def getSessionId(self) -> LogSessionId: ...
    def equals(self, p0: Any) -> bool: ...
    def hashCode(self) -> int: ...
    def close(self) -> None: ...

