from typing import Any, ClassVar, overload
from android.app.PendingIntent import PendingIntent
from android.graphics.Bitmap import Bitmap
from android.media.MediaMetadataEditor import MediaMetadataEditor
from android.media.session.MediaSession import MediaSession
from android.os.Looper import Looper

class RemoteControlClient:
    FLAG_KEY_MEDIA_FAST_FORWARD: ClassVar[int]
    FLAG_KEY_MEDIA_NEXT: ClassVar[int]
    FLAG_KEY_MEDIA_PAUSE: ClassVar[int]
    FLAG_KEY_MEDIA_PLAY: ClassVar[int]
    FLAG_KEY_MEDIA_PLAY_PAUSE: ClassVar[int]
    FLAG_KEY_MEDIA_POSITION_UPDATE: ClassVar[int]
    FLAG_KEY_MEDIA_PREVIOUS: ClassVar[int]
    FLAG_KEY_MEDIA_RATING: ClassVar[int]
    FLAG_KEY_MEDIA_REWIND: ClassVar[int]
    FLAG_KEY_MEDIA_STOP: ClassVar[int]
    PLAYSTATE_BUFFERING: ClassVar[int]
    PLAYSTATE_ERROR: ClassVar[int]
    PLAYSTATE_FAST_FORWARDING: ClassVar[int]
    PLAYSTATE_PAUSED: ClassVar[int]
    PLAYSTATE_PLAYING: ClassVar[int]
    PLAYSTATE_REWINDING: ClassVar[int]
    PLAYSTATE_SKIPPING_BACKWARDS: ClassVar[int]
    PLAYSTATE_SKIPPING_FORWARDS: ClassVar[int]
    PLAYSTATE_STOPPED: ClassVar[int]
    @overload
    def __init__(self, p0: PendingIntent) -> None: ...
    @overload
    def __init__(self, p0: PendingIntent, p1: Looper) -> None: ...
    def getMediaSession(self) -> MediaSession: ...
    def setMetadataUpdateListener(self, p0: Any) -> None: ...
    def setOnGetPlaybackPositionListener(self, p0: Any) -> None: ...
    def setPlaybackPositionUpdateListener(self, p0: Any) -> None: ...
    def setTransportControlFlags(self, p0: int) -> None: ...
    @overload
    def setPlaybackState(self, p0: int, p1: int, p2: float) -> None: ...
    @overload
    def setPlaybackState(self, p0: int) -> None: ...
    def editMetadata(self, p0: bool) -> Any: ...

    class OnPlaybackPositionUpdateListener:
        def onPlaybackPositionUpdate(self, p0: int) -> None: ...

    class OnMetadataUpdateListener:
        def onMetadataUpdate(self, p0: int, p1: Any) -> None: ...

    class OnGetPlaybackPositionListener:
        def onGetPlaybackPosition(self) -> int: ...

    class MetadataEditor:
        BITMAP_KEY_ARTWORK: ClassVar[int]
        BITMAP_KEY_ARTWORK: ClassVar[int]
        RATING_KEY_BY_OTHERS: ClassVar[int]
        RATING_KEY_BY_USER: ClassVar[int]
        @overload
        def putBitmap(self, p0: int, p1: Bitmap) -> Any: ...
        @overload
        def putBitmap(self, p0: int, p1: Bitmap) -> MediaMetadataEditor: ...
        @overload
        def putObject(self, p0: int, p1: Any) -> MediaMetadataEditor: ...
        @overload
        def putObject(self, p0: int, p1: Any) -> Any: ...
        def clone(self) -> Any: ...
        @overload
        def putLong(self, p0: int, p1: int) -> Any: ...
        @overload
        def putLong(self, p0: int, p1: int) -> MediaMetadataEditor: ...
        def clear(self) -> None: ...
        def apply(self) -> None: ...
        @overload
        def putString(self, p0: int, p1: str) -> Any: ...
        @overload
        def putString(self, p0: int, p1: str) -> MediaMetadataEditor: ...
