from typing import Any, ClassVar, overload
from android.media.Session2Command import Session2Command
from android.os.Parcel import Parcel

class Session2CommandGroup:
    CREATOR: ClassVar[Any]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    def getCommands(self) -> set: ...
    @overload
    def hasCommand(self, p0: Session2Command) -> bool: ...
    @overload
    def hasCommand(self, p0: int) -> bool: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
    def describeContents(self) -> int: ...

    class Builder:
        @overload
        def __init__(self, p0: "Session2CommandGroup") -> None: ...
        @overload
        def __init__(self) -> None: ...
        def addCommand(self, p0: Session2Command) -> Any: ...
        def removeCommand(self, p0: Session2Command) -> Any: ...
        def build(self) -> "Session2CommandGroup": ...
