from typing import Any, ClassVar, overload
from android.os.Bundle import Bundle
from android.os.Parcel import Parcel

class Session2Command:
    COMMAND_CODE_CUSTOM: ClassVar[int]
    CREATOR: ClassVar[Any]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    @overload
    def __init__(self, p0: int) -> None: ...
    @overload
    def __init__(self, p0: str, p1: Bundle) -> None: ...
    def getCustomAction(self) -> str: ...
    def getCommandCode(self) -> int: ...
    def getCustomExtras(self) -> Bundle: ...
    def equals(self, p0: Any) -> bool: ...
    def hashCode(self) -> int: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
    def describeContents(self) -> int: ...

    class Result:
        RESULT_ERROR_UNKNOWN_ERROR: ClassVar[int]
        RESULT_INFO_SKIPPED: ClassVar[int]
        RESULT_SUCCESS: ClassVar[int]
        def __init__(self, p0: int, p1: Bundle) -> None: ...
        def getResultData(self) -> Bundle: ...
        def getResultCode(self) -> int: ...
