from typing import Any, ClassVar, overload

class JSONStringer:
    def __init__(self) -> None: ...
    def endArray(self) -> "JSONStringer": ...
    def endObject(self) -> "JSONStringer": ...
    @overload
    def value(self, p0: Any) -> "JSONStringer": ...
    @overload
    def value(self, p0: float) -> "JSONStringer": ...
    @overload
    def value(self, p0: bool) -> "JSONStringer": ...
    @overload
    def value(self, p0: int) -> "JSONStringer": ...
    def toString(self) -> str: ...
    def array(self) -> "JSONStringer": ...
    def key(self, p0: str) -> "JSONStringer": ...
    def object(self) -> "JSONStringer": ...
