from typing import Any, ClassVar, overload
from org.json.JSONException import JSONException

class JSONTokener:
    def __init__(self, p0: str) -> None: ...
    def nextString(self, p0: str) -> str: ...
    @staticmethod
    def dehexchar(p0: str) -> int: ...
    def nextClean(self) -> str: ...
    @overload
    def nextTo(self, p0: str) -> str: ...
    @overload
    def nextTo(self, p0: str) -> str: ...
    def skipPast(self, p0: str) -> None: ...
    def skipTo(self, p0: str) -> str: ...
    def syntaxError(self, p0: str) -> JSONException: ...
    def toString(self) -> str: ...
    @overload
    def next(self, p0: int) -> str: ...
    @overload
    def next(self) -> str: ...
    @overload
    def next(self, p0: str) -> str: ...
    def nextValue(self) -> Any: ...
    def back(self) -> None: ...
    def more(self) -> bool: ...
