from typing import Any, ClassVar, overload
from java.security.Permission import Permission
from java.security.PermissionCollection import PermissionCollection

class BasicPermission:
    @overload
    def __init__(self, p0: str, p1: str) -> None: ...
    @overload
    def __init__(self, p0: str) -> None: ...
    def newPermissionCollection(self) -> PermissionCollection: ...
    def equals(self, p0: Any) -> bool: ...
    def hashCode(self) -> int: ...
    def implies(self, p0: Permission) -> bool: ...
    def getActions(self) -> str: ...
