from typing import Any, ClassVar, overload
from java.io.InputStream import InputStream
from java.util.Enumeration import Enumeration
from java.util.function.BiConsumer import BiConsumer
from java.util.function.BiFunction import BiFunction
from java.util.function.Function import Function

class Provider:
    def getInfo(self) -> str: ...
    def getService(self, p0: str, p1: str) -> Any: ...
    def isConfigured(self) -> bool: ...
    def getVersionStr(self) -> str: ...
    def getVersion(self) -> float: ...
    def configure(self, p0: str) -> "Provider": ...
    def getServices(self) -> set: ...
    def getName(self) -> str: ...
    @overload
    def remove(self, p0: Any) -> Any: ...
    @overload
    def remove(self, p0: Any, p1: Any) -> bool: ...
    def get(self, p0: Any) -> Any: ...
    def put(self, p0: Any, p1: Any) -> Any: ...
    def getProperty(self, p0: str) -> str: ...
    def toString(self) -> str: ...
    def values(self) -> list: ...
    def load(self, p0: InputStream) -> None: ...
    def clear(self) -> None: ...
    @overload
    def replace(self, p0: Any, p1: Any, p2: Any) -> bool: ...
    @overload
    def replace(self, p0: Any, p1: Any) -> Any: ...
    def replaceAll(self, p0: BiFunction) -> None: ...
    def elements(self) -> Enumeration: ...
    def merge(self, p0: Any, p1: Any, p2: BiFunction) -> Any: ...
    def entrySet(self) -> set: ...
    def putAll(self, p0: dict) -> None: ...
    def putIfAbsent(self, p0: Any, p1: Any) -> Any: ...
    def compute(self, p0: Any, p1: BiFunction) -> Any: ...
    def forEach(self, p0: BiConsumer) -> None: ...
    def computeIfAbsent(self, p0: Any, p1: Function) -> Any: ...
    def keys(self) -> Enumeration: ...
    def keySet(self) -> set: ...
    def getOrDefault(self, p0: Any, p1: Any) -> Any: ...
    def computeIfPresent(self, p0: Any, p1: BiFunction) -> Any: ...

    class Service:
        def __init__(self, p0: "Provider", p1: str, p2: str, p3: str, p4: list, p5: dict) -> None: ...
        def getClassName(self) -> str: ...
        def getAttribute(self, p0: str) -> str: ...
        def getAlgorithm(self) -> str: ...
        def getProvider(self) -> "Provider": ...
        def supportsParameter(self, p0: Any) -> bool: ...
        def toString(self) -> str: ...
        def newInstance(self, p0: Any) -> Any: ...
        def getType(self) -> str: ...
