from typing import Any, ClassVar, overload
from java.security.Provider import Provider

class Security:
    @staticmethod
    def getProvider(p0: str) -> Provider: ...
    @staticmethod
    def getProperty(p0: str) -> str: ...
    @staticmethod
    def setProperty(p0: str, p1: str) -> None: ...
    @staticmethod
    def addProvider(p0: Provider) -> int: ...
    @staticmethod
    def removeProvider(p0: str) -> None: ...
    @overload
    @staticmethod
    def getProviders(p0: dict) -> Any: ...
    @overload
    @staticmethod
    def getProviders(p0: str) -> Any: ...
    @overload
    @staticmethod
    def getProviders() -> Any: ...
    @staticmethod
    def insertProviderAt(p0: Provider, p1: int) -> int: ...
    @staticmethod
    def getAlgorithmProperty(p0: str, p1: str) -> str: ...
    @staticmethod
    def getAlgorithms(p0: str) -> set: ...
