from typing import Any, ClassVar, overload
from java.io.InputStream import InputStream
from java.util.zip.Inflater import Inflater

class InflaterInputStream:
    @overload
    def __init__(self, p0: InputStream) -> None: ...
    @overload
    def __init__(self, p0: InputStream, p1: Inflater, p2: int) -> None: ...
    @overload
    def __init__(self, p0: InputStream, p1: Inflater) -> None: ...
    def mark(self, p0: int) -> None: ...
    def skip(self, p0: int) -> int: ...
    def available(self) -> int: ...
    def markSupported(self) -> bool: ...
    def reset(self) -> None: ...
    @overload
    def read(self) -> int: ...
    @overload
    def read(self, p0: Any, p1: int, p2: int) -> int: ...
    def close(self) -> None: ...
