from typing import Any, ClassVar, overload
from java.nio.ByteBuffer import ByteBuffer

class Inflater:
    @overload
    def __init__(self, p0: bool) -> None: ...
    @overload
    def __init__(self) -> None: ...
    @overload
    def setDictionary(self, p0: Any, p1: int, p2: int) -> None: ...
    @overload
    def setDictionary(self, p0: Any) -> None: ...
    @overload
    def setDictionary(self, p0: ByteBuffer) -> None: ...
    def getAdler(self) -> int: ...
    def getBytesRead(self) -> int: ...
    def getRemaining(self) -> int: ...
    def getTotalIn(self) -> int: ...
    def getTotalOut(self) -> int: ...
    @overload
    def setInput(self, p0: Any, p1: int, p2: int) -> None: ...
    @overload
    def setInput(self, p0: ByteBuffer) -> None: ...
    @overload
    def setInput(self, p0: Any) -> None: ...
    def getBytesWritten(self) -> int: ...
    def finished(self) -> bool: ...
    def needsDictionary(self) -> bool: ...
    def needsInput(self) -> bool: ...
    def reset(self) -> None: ...
    @overload
    def inflate(self, p0: Any, p1: int, p2: int) -> int: ...
    @overload
    def inflate(self, p0: Any) -> int: ...
    @overload
    def inflate(self, p0: ByteBuffer) -> int: ...
    def end(self) -> None: ...
