from typing import Any, ClassVar, overload
from android.os.health.TimerStat import TimerStat

class HealthStats:
    def hasTimer(self, p0: int) -> bool: ...
    def hasMeasurement(self, p0: int) -> bool: ...
    def getMeasurement(self, p0: int) -> int: ...
    def getMeasurementKeyCount(self) -> int: ...
    def getMeasurementKeyAt(self, p0: int) -> int: ...
    def hasStats(self, p0: int) -> bool: ...
    def getStats(self, p0: int) -> dict: ...
    def getStatsKeyCount(self) -> int: ...
    def getStatsKeyAt(self, p0: int) -> int: ...
    def hasTimers(self, p0: int) -> bool: ...
    def getMeasurementsKeyCount(self) -> int: ...
    def getTimer(self, p0: int) -> TimerStat: ...
    def getTimerCount(self, p0: int) -> int: ...
    def getTimerTime(self, p0: int) -> int: ...
    def getTimerKeyCount(self) -> int: ...
    def getTimerKeyAt(self, p0: int) -> int: ...
    def getTimers(self, p0: int) -> dict: ...
    def getTimersKeyCount(self) -> int: ...
    def getTimersKeyAt(self, p0: int) -> int: ...
    def getMeasurementsKeyAt(self, p0: int) -> int: ...
    def hasMeasurements(self, p0: int) -> bool: ...
    def getMeasurements(self, p0: int) -> dict: ...
    def getDataType(self) -> str: ...
