from typing import Any, ClassVar, overload
from android.os.Parcel import Parcel

class TimerStat:
    CREATOR: ClassVar[Any]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, p0: int, p1: int) -> None: ...
    @overload
    def __init__(self, p0: Parcel) -> None: ...
    def setCount(self, p0: int) -> None: ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
    def setTime(self, p0: int) -> None: ...
    def getTime(self) -> int: ...
    def getCount(self) -> int: ...
