from typing import Any, ClassVar, overload
from android.content.res.AssetFileDescriptor import AssetFileDescriptor
from android.content.res.XmlResourceParser import XmlResourceParser
from java.io.InputStream import InputStream

class AssetManager:
    ACCESS_BUFFER: ClassVar[int]
    ACCESS_RANDOM: ClassVar[int]
    ACCESS_STREAMING: ClassVar[int]
    ACCESS_UNKNOWN: ClassVar[int]
    @overload
    def openNonAssetFd(self, p0: str) -> AssetFileDescriptor: ...
    @overload
    def openNonAssetFd(self, p0: int, p1: str) -> AssetFileDescriptor: ...
    @overload
    def openXmlResourceParser(self, p0: str) -> XmlResourceParser: ...
    @overload
    def openXmlResourceParser(self, p0: int, p1: str) -> XmlResourceParser: ...
    def list(self, p0: str) -> Any: ...
    def close(self) -> None: ...
    @overload
    def open(self, p0: str) -> InputStream: ...
    @overload
    def open(self, p0: str, p1: int) -> InputStream: ...
    def getLocales(self) -> Any: ...
    def openFd(self, p0: str) -> AssetFileDescriptor: ...

    class AssetInputStream:
        def reset(self) -> None: ...
        @overload
        def read(self, p0: Any) -> int: ...
        @overload
        def read(self) -> int: ...
        @overload
        def read(self, p0: Any, p1: int, p2: int) -> int: ...
        def close(self) -> None: ...
        def mark(self, p0: int) -> None: ...
        def skip(self, p0: int) -> int: ...
        def available(self) -> int: ...
        def markSupported(self) -> bool: ...
