from typing import Any, ClassVar, overload
from android.content.Context import Context
from android.content.Intent import Intent
from android.content.SharedPreferences import SharedPreferences
from android.graphics.drawable.Drawable import Drawable
from android.os.Bundle import Bundle
from android.os.Parcel import Parcel
from android.os.Parcelable import Parcelable
from android.preference.PreferenceDataStore import PreferenceDataStore
from android.preference.PreferenceGroup import PreferenceGroup
from android.preference.PreferenceManager import PreferenceManager
from android.util.AttributeSet import AttributeSet
from android.view.AbsSavedState import AbsSavedState
from android.view.View import View
from android.view.ViewGroup import ViewGroup

class Preference:
    DEFAULT_ORDER: ClassVar[int]
    @overload
    def __init__(self, p0: Context) -> None: ...
    @overload
    def __init__(self, p0: Context, p1: AttributeSet) -> None: ...
    @overload
    def __init__(self, p0: Context, p1: AttributeSet, p2: int) -> None: ...
    @overload
    def __init__(self, p0: Context, p1: AttributeSet, p2: int, p3: int) -> None: ...
    def setPersistent(self, p0: bool) -> None: ...
    @overload
    def setSummary(self, p0: str) -> None: ...
    @overload
    def setSummary(self, p0: int) -> None: ...
    def getPreferenceDataStore(self) -> PreferenceDataStore: ...
    def setPreferenceDataStore(self, p0: PreferenceDataStore) -> None: ...
    def isPersistent(self) -> bool: ...
    def getSummary(self) -> str: ...
    def notifyDependencyChange(self, p0: bool) -> None: ...
    def getPreferenceManager(self) -> PreferenceManager: ...
    def hasKey(self) -> bool: ...
    def setWidgetLayoutResource(self, p0: int) -> None: ...
    def setFragment(self, p0: str) -> None: ...
    def peekExtras(self) -> Bundle: ...
    def getTitleRes(self) -> int: ...
    def setSelectable(self, p0: bool) -> None: ...
    def setShouldDisableView(self, p0: bool) -> None: ...
    def getShouldDisableView(self) -> bool: ...
    def setRecycleEnabled(self, p0: bool) -> None: ...
    def isRecycleEnabled(self) -> bool: ...
    def setSingleLineTitle(self, p0: bool) -> None: ...
    def isSingleLineTitle(self) -> bool: ...
    def setIconSpaceReserved(self, p0: bool) -> None: ...
    def getWidgetLayoutResource(self) -> int: ...
    def isIconSpaceReserved(self) -> bool: ...
    def setOnPreferenceChangeListener(self, p0: Any) -> None: ...
    def getOnPreferenceChangeListener(self) -> Any: ...
    def setOnPreferenceClickListener(self, p0: Any) -> None: ...
    def getOnPreferenceClickListener(self) -> Any: ...
    def getEditor(self) -> Any: ...
    def shouldCommit(self) -> bool: ...
    def onDependencyChanged(self, p0: "Preference", p1: bool) -> None: ...
    def onParentChanged(self, p0: "Preference", p1: bool) -> None: ...
    def shouldDisableDependents(self) -> bool: ...
    def setDependency(self, p0: str) -> None: ...
    def getDependency(self) -> str: ...
    def setDefaultValue(self, p0: Any) -> None: ...
    def persistStringSet(self, p0: set) -> bool: ...
    def getPersistedStringSet(self, p0: set) -> set: ...
    def setOrder(self, p0: int) -> None: ...
    def getLayoutResource(self) -> int: ...
    def setLayoutResource(self, p0: int) -> None: ...
    def setKey(self, p0: str) -> None: ...
    def getFragment(self) -> str: ...
    def setIntent(self, p0: Intent) -> None: ...
    @overload
    def setIcon(self, p0: Drawable) -> None: ...
    @overload
    def setIcon(self, p0: int) -> None: ...
    def getOrder(self) -> int: ...
    def getIcon(self) -> Drawable: ...
    def saveHierarchyState(self, p0: Bundle) -> None: ...
    def restoreHierarchyState(self, p0: Bundle) -> None: ...
    def getView(self, p0: View, p1: ViewGroup) -> View: ...
    def setEnabled(self, p0: bool) -> None: ...
    def getTitle(self) -> str: ...
    @overload
    def setTitle(self, p0: int) -> None: ...
    @overload
    def setTitle(self, p0: str) -> None: ...
    def isSelectable(self) -> bool: ...
    def getSharedPreferences(self) -> SharedPreferences: ...
    def getIntent(self) -> Intent: ...
    def getExtras(self) -> Bundle: ...
    def toString(self) -> str: ...
    @overload
    def compareTo(self, p0: Any) -> int: ...
    @overload
    def compareTo(self, p0: "Preference") -> int: ...
    def isEnabled(self) -> bool: ...
    def getKey(self) -> str: ...
    def getParent(self) -> PreferenceGroup: ...
    def getContext(self) -> Context: ...

    class OnPreferenceClickListener:
        def onPreferenceClick(self, p0: "Preference") -> bool: ...

    class OnPreferenceChangeListener:
        def onPreferenceChange(self, p0: "Preference", p1: Any) -> bool: ...

    class BaseSavedState:
        CREATOR: ClassVar[Any]
        CREATOR: ClassVar[Any]
        EMPTY_STATE: ClassVar[AbsSavedState]
        CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
        PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
        @overload
        def __init__(self, p0: Parcel) -> None: ...
        @overload
        def __init__(self, p0: Parcelable) -> None: ...
