from typing import Any, ClassVar, overload

class LightingColorFilter:
    def __init__(self, p0: int, p1: int) -> None: ...
    def getColorMultiply(self) -> int: ...
    def getColorAdd(self) -> int: ...
