from typing import Any, ClassVar, overload
from android.graphics.Matrix import Matrix

class Matrix44:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, p0: Matrix) -> None: ...
    def rotate(self, p0: float, p1: float, p2: float, p3: float) -> "Matrix44": ...
    def invert(self) -> bool: ...
    def getValues(self, p0: Any) -> None: ...
    def setValues(self, p0: Any) -> None: ...
    def translate(self, p0: float, p1: float, p2: float) -> "Matrix44": ...
    def isIdentity(self) -> bool: ...
    def reset(self) -> None: ...
    def get(self, p0: int, p1: int) -> float: ...
    def equals(self, p0: Any) -> bool: ...
    def toString(self) -> str: ...
    def hashCode(self) -> int: ...
    def scale(self, p0: float, p1: float, p2: float) -> "Matrix44": ...
    @overload
    def map(self, p0: float, p1: float, p2: float, p3: float) -> Any: ...
    @overload
    def map(self, p0: float, p1: float, p2: float, p3: float, p4: Any) -> None: ...
    def concat(self, p0: "Matrix44") -> "Matrix44": ...
    def set(self, p0: int, p1: int, p2: float) -> None: ...
