from typing import Any, ClassVar, overload

class LoadParams:
    def getPassword(self) -> str: ...

    class Builder:
        def __init__(self) -> None: ...
        def build(self) -> "LoadParams": ...
        def setPassword(self, p0: str) -> Any: ...

from typing import Any, ClassVar, overload
from android.graphics.Bitmap import Bitmap
from android.graphics.Matrix import Matrix
from android.graphics.Rect import Rect
from android.graphics.pdf.LoadParams import LoadParams
from android.graphics.pdf.RenderParams import RenderParams
from android.graphics.pdf.models.FormEditRecord import FormEditRecord
from android.graphics.pdf.models.FormWidgetInfo import FormWidgetInfo
from android.graphics.pdf.models.selection.PageSelection import PageSelection
from android.graphics.pdf.models.selection.SelectionBoundary import SelectionBoundary
from android.os.ParcelFileDescriptor import ParcelFileDescriptor

class PdfRendererPreV:
    DOCUMENT_LINEARIZED_TYPE_LINEARIZED: ClassVar[int]
    DOCUMENT_LINEARIZED_TYPE_NON_LINEARIZED: ClassVar[int]
    PDF_FORM_TYPE_ACRO_FORM: ClassVar[int]
    PDF_FORM_TYPE_NONE: ClassVar[int]
    PDF_FORM_TYPE_XFA_FOREGROUND: ClassVar[int]
    PDF_FORM_TYPE_XFA_FULL: ClassVar[int]
    @overload
    def __init__(self, p0: ParcelFileDescriptor) -> None: ...
    @overload
    def __init__(self, p0: ParcelFileDescriptor, p1: LoadParams) -> None: ...
    def write(self, p0: ParcelFileDescriptor, p1: bool) -> None: ...
    def close(self) -> None: ...
    def getDocumentLinearizationType(self) -> int: ...
    def getPageCount(self) -> int: ...
    def getPdfFormType(self) -> int: ...
    def openPage(self, p0: int) -> Any: ...

    class Page:
        def applyEdit(self, p0: FormEditRecord) -> list: ...
        def getFormWidgetInfoAtIndex(self, p0: int) -> FormWidgetInfo: ...
        def getFormWidgetInfoAtPosition(self, p0: int, p1: int) -> FormWidgetInfo: ...
        def render(self, p0: Bitmap, p1: Rect, p2: Matrix, p3: RenderParams) -> None: ...
        @overload
        def getFormWidgetInfos(self, p0: Any) -> list: ...
        @overload
        def getFormWidgetInfos(self) -> list: ...
        def getGotoLinks(self) -> list: ...
        def getImageContents(self) -> list: ...
        def getLinkContents(self) -> list: ...
        def getTextContents(self) -> list: ...
        def selectContent(self, p0: SelectionBoundary, p1: SelectionBoundary) -> PageSelection: ...
        def searchText(self, p0: str) -> list: ...
        def close(self) -> None: ...
        def getIndex(self) -> int: ...
        def getHeight(self) -> int: ...
        def getWidth(self) -> int: ...

from typing import Any, ClassVar, overload

class RenderParams:
    FLAG_RENDER_HIGHLIGHT_ANNOTATIONS: ClassVar[int]
    FLAG_RENDER_TEXT_ANNOTATIONS: ClassVar[int]
    RENDER_MODE_FOR_DISPLAY: ClassVar[int]
    RENDER_MODE_FOR_PRINT: ClassVar[int]
    def getRenderFlags(self) -> int: ...
    def getRenderMode(self) -> int: ...

    class Builder:
        def __init__(self, p0: int) -> None: ...
        @overload
        def setRenderFlags(self, p0: int, p1: int) -> Any: ...
        @overload
        def setRenderFlags(self, p0: int) -> Any: ...
        def build(self) -> "RenderParams": ...

from typing import Any, ClassVar, overload
from android.graphics.Canvas import Canvas
from android.graphics.Rect import Rect
from java.io.OutputStream import OutputStream

class PdfDocument:
    def __init__(self) -> None: ...
    def finishPage(self, p0: Any) -> None: ...
    def getPages(self) -> list: ...
    def startPage(self, p0: Any) -> Any: ...
    def close(self) -> None: ...
    def writeTo(self, p0: OutputStream) -> None: ...

    class PageInfo:
        def getPageNumber(self) -> int: ...
        def getContentRect(self) -> Rect: ...
        def getPageHeight(self) -> int: ...
        def getPageWidth(self) -> int: ...

        class Builder:
            def __init__(self, p0: int, p1: int, p2: int) -> None: ...
            def setContentRect(self, p0: Rect) -> Any: ...
            def create(self) -> Any: ...

    class Page:
        def getInfo(self) -> Any: ...
        def getCanvas(self) -> Canvas: ...

from typing import Any, ClassVar, overload
from android.graphics.Bitmap import Bitmap
from android.graphics.Matrix import Matrix
from android.graphics.Rect import Rect
from android.graphics.pdf.LoadParams import LoadParams
from android.graphics.pdf.RenderParams import RenderParams
from android.graphics.pdf.models.FormEditRecord import FormEditRecord
from android.graphics.pdf.models.FormWidgetInfo import FormWidgetInfo
from android.graphics.pdf.models.selection.PageSelection import PageSelection
from android.graphics.pdf.models.selection.SelectionBoundary import SelectionBoundary
from android.os.ParcelFileDescriptor import ParcelFileDescriptor

class PdfRenderer:
    DOCUMENT_LINEARIZED_TYPE_LINEARIZED: ClassVar[int]
    DOCUMENT_LINEARIZED_TYPE_NON_LINEARIZED: ClassVar[int]
    PDF_FORM_TYPE_ACRO_FORM: ClassVar[int]
    PDF_FORM_TYPE_NONE: ClassVar[int]
    PDF_FORM_TYPE_XFA_FOREGROUND: ClassVar[int]
    PDF_FORM_TYPE_XFA_FULL: ClassVar[int]
    @overload
    def __init__(self, p0: ParcelFileDescriptor) -> None: ...
    @overload
    def __init__(self, p0: ParcelFileDescriptor, p1: LoadParams) -> None: ...
    def shouldScaleForPrinting(self) -> bool: ...
    def write(self, p0: ParcelFileDescriptor, p1: bool) -> None: ...
    def close(self) -> None: ...
    def getDocumentLinearizationType(self) -> int: ...
    def getPageCount(self) -> int: ...
    def getPdfFormType(self) -> int: ...
    def openPage(self, p0: int) -> Any: ...

    class Page:
        RENDER_MODE_FOR_DISPLAY: ClassVar[int]
        RENDER_MODE_FOR_PRINT: ClassVar[int]
        def applyEdit(self, p0: FormEditRecord) -> list: ...
        def getFormWidgetInfoAtIndex(self, p0: int) -> FormWidgetInfo: ...
        def getFormWidgetInfoAtPosition(self, p0: int, p1: int) -> FormWidgetInfo: ...
        @overload
        def render(self, p0: Bitmap, p1: Rect, p2: Matrix, p3: RenderParams) -> None: ...
        @overload
        def render(self, p0: Bitmap, p1: Rect, p2: Matrix, p3: int) -> None: ...
        @overload
        def getFormWidgetInfos(self, p0: Any) -> list: ...
        @overload
        def getFormWidgetInfos(self) -> list: ...
        def getGotoLinks(self) -> list: ...
        def getImageContents(self) -> list: ...
        def getLinkContents(self) -> list: ...
        def getTextContents(self) -> list: ...
        def selectContent(self, p0: SelectionBoundary, p1: SelectionBoundary) -> PageSelection: ...
        def searchText(self, p0: str) -> list: ...
        def close(self) -> None: ...
        def getIndex(self) -> int: ...
        def getHeight(self) -> int: ...
        def getWidth(self) -> int: ...

