from typing import Any, ClassVar, overload
from android.os.Handler import Handler

class SurfaceTexture:
    @overload
    def __init__(self, p0: int, p1: bool) -> None: ...
    @overload
    def __init__(self, p0: bool) -> None: ...
    @overload
    def __init__(self, p0: int) -> None: ...
    @overload
    def setOnFrameAvailableListener(self, p0: Any) -> None: ...
    @overload
    def setOnFrameAvailableListener(self, p0: Any, p1: Handler) -> None: ...
    def setDefaultBufferSize(self, p0: int, p1: int) -> None: ...
    def updateTexImage(self) -> None: ...
    def releaseTexImage(self) -> None: ...
    def detachFromGLContext(self) -> None: ...
    def attachToGLContext(self, p0: int) -> None: ...
    def getTransformMatrix(self, p0: Any) -> None: ...
    def getDataSpace(self) -> int: ...
    def isReleased(self) -> bool: ...
    def release(self) -> None: ...
    def getTimestamp(self) -> int: ...

    class OutOfResourcesException:
        @overload
        def __init__(self) -> None: ...
        @overload
        def __init__(self, p0: str) -> None: ...

    class OnFrameAvailableListener:
        def onFrameAvailable(self, p0: "SurfaceTexture") -> None: ...
