# cython: language_level=3
# Generated by pyjnius-wrap cython — do not edit by hand.

from jni_core._core cimport (
    JavaObject, get_env, check_jni_exc,
    find_class_global, get_method_id, get_static_method_id,
    get_field_id, get_static_field_id, j_str, py_str,
)
from jni_core._dispatch cimport (
    jnicore_NewObjectA, jnicore_DeleteLocalRef,
    jnicore_CallVoidMethodA, jnicore_CallObjectMethodA,
    jnicore_CallBooleanMethodA, jnicore_CallByteMethodA,
    jnicore_CallCharMethodA, jnicore_CallShortMethodA,
    jnicore_CallIntMethodA, jnicore_CallLongMethodA,
    jnicore_CallFloatMethodA, jnicore_CallDoubleMethodA,
    jnicore_CallStaticVoidMethodA, jnicore_CallStaticObjectMethodA,
    jnicore_CallStaticBooleanMethodA, jnicore_CallStaticByteMethodA,
    jnicore_CallStaticCharMethodA, jnicore_CallStaticShortMethodA,
    jnicore_CallStaticIntMethodA, jnicore_CallStaticLongMethodA,
    jnicore_CallStaticFloatMethodA, jnicore_CallStaticDoubleMethodA,
    jnicore_GetObjectField, jnicore_SetObjectField,
    jnicore_GetBooleanField, jnicore_SetBooleanField,
    jnicore_GetByteField, jnicore_SetByteField,
    jnicore_GetCharField, jnicore_SetCharField,
    jnicore_GetShortField, jnicore_SetShortField,
    jnicore_GetIntField, jnicore_SetIntField,
    jnicore_GetLongField, jnicore_SetLongField,
    jnicore_GetFloatField, jnicore_SetFloatField,
    jnicore_GetDoubleField, jnicore_SetDoubleField,
    jnicore_GetStaticObjectField, jnicore_SetStaticObjectField,
    jnicore_GetStaticBooleanField, jnicore_SetStaticBooleanField,
    jnicore_GetStaticByteField, jnicore_SetStaticByteField,
    jnicore_GetStaticCharField, jnicore_SetStaticCharField,
    jnicore_GetStaticShortField, jnicore_SetStaticShortField,
    jnicore_GetStaticIntField, jnicore_SetStaticIntField,
    jnicore_GetStaticLongField, jnicore_SetStaticLongField,
    jnicore_GetStaticFloatField, jnicore_SetStaticFloatField,
    jnicore_GetStaticDoubleField, jnicore_SetStaticDoubleField,
)
from jni_core.jni cimport (
    jclass, jobject, jmethodID, jfieldID, jvalue, JNIEnv,
    jboolean, jbyte, jchar, jshort, jint, jlong, jfloat, jdouble, jstring,
)

include "jni_core/conversions.pxi"

__javaclass__ = "android/graphics/SurfaceTexture"  # android.graphics.SurfaceTexture

cdef jclass _cls_SurfaceTexture = NULL
cdef jmethodID _ctor_0 = NULL
cdef jmethodID _ctor_1 = NULL
cdef jmethodID _ctor_2 = NULL
cdef jmethodID _m_setOnFrameAvailableListener_0 = NULL
cdef jmethodID _m_setOnFrameAvailableListener_1 = NULL
cdef jmethodID _m_setDefaultBufferSize_0 = NULL
cdef jmethodID _m_updateTexImage_0 = NULL
cdef jmethodID _m_releaseTexImage_0 = NULL
cdef jmethodID _m_detachFromGLContext_0 = NULL
cdef jmethodID _m_attachToGLContext_0 = NULL
cdef jmethodID _m_getTransformMatrix_0 = NULL
cdef jmethodID _m_getDataSpace_0 = NULL
cdef jmethodID _m_isReleased_0 = NULL
cdef jmethodID _m_release_0 = NULL
cdef jmethodID _m_getTimestamp_0 = NULL

cdef int _ensure_ids_SurfaceTexture(JNIEnv* env) except -1:
    global _cls_SurfaceTexture, _ctor_0, _ctor_1, _ctor_2, _m_setOnFrameAvailableListener_0, _m_setOnFrameAvailableListener_1, _m_setDefaultBufferSize_0, _m_updateTexImage_0, _m_releaseTexImage_0, _m_detachFromGLContext_0, _m_attachToGLContext_0, _m_getTransformMatrix_0, _m_getDataSpace_0, _m_isReleased_0, _m_release_0, _m_getTimestamp_0
    if _cls_SurfaceTexture != NULL:
        return 0
    _cls_SurfaceTexture = find_class_global(env, b"android/graphics/SurfaceTexture")
    _ctor_0 = get_method_id(env, _cls_SurfaceTexture, b"<init>", b"(IZ)V")
    _ctor_1 = get_method_id(env, _cls_SurfaceTexture, b"<init>", b"(Z)V")
    _ctor_2 = get_method_id(env, _cls_SurfaceTexture, b"<init>", b"(I)V")
    _m_setOnFrameAvailableListener_0 = get_method_id(env, _cls_SurfaceTexture, b"setOnFrameAvailableListener", b"(Landroid/graphics/SurfaceTexture$OnFrameAvailableListener;)V")
    _m_setOnFrameAvailableListener_1 = get_method_id(env, _cls_SurfaceTexture, b"setOnFrameAvailableListener", b"(Landroid/graphics/SurfaceTexture$OnFrameAvailableListener;Landroid/os/Handler;)V")
    _m_setDefaultBufferSize_0 = get_method_id(env, _cls_SurfaceTexture, b"setDefaultBufferSize", b"(II)V")
    _m_updateTexImage_0 = get_method_id(env, _cls_SurfaceTexture, b"updateTexImage", b"()V")
    _m_releaseTexImage_0 = get_method_id(env, _cls_SurfaceTexture, b"releaseTexImage", b"()V")
    _m_detachFromGLContext_0 = get_method_id(env, _cls_SurfaceTexture, b"detachFromGLContext", b"()V")
    _m_attachToGLContext_0 = get_method_id(env, _cls_SurfaceTexture, b"attachToGLContext", b"(I)V")
    _m_getTransformMatrix_0 = get_method_id(env, _cls_SurfaceTexture, b"getTransformMatrix", b"([F)V")
    _m_getDataSpace_0 = get_method_id(env, _cls_SurfaceTexture, b"getDataSpace", b"()I")
    _m_isReleased_0 = get_method_id(env, _cls_SurfaceTexture, b"isReleased", b"()Z")
    _m_release_0 = get_method_id(env, _cls_SurfaceTexture, b"release", b"()V")
    _m_getTimestamp_0 = get_method_id(env, _cls_SurfaceTexture, b"getTimestamp", b"()J")
    return 0

cdef class SurfaceTexture(JavaObject):
    """android.graphics.SurfaceTexture"""

    # TODO: 3 constructor overloads; only the first is wired.
    #   overload[0] = (IZ)V
    #   overload[1] = (Z)V
    #   overload[2] = (I)V
    def __init__(self, p0, p1):
        cdef JNIEnv* env = get_env()
        _ensure_ids_SurfaceTexture(env)
        cdef jvalue _args[2]
        _args[0].i = py_to_jint(p0)
        _args[1].z = py_to_jboolean(p1)
        cdef jobject _ret = jnicore_NewObjectA(env, _cls_SurfaceTexture, _ctor_0, _args)
        check_jni_exc(env)
        self._adopt_local(env, _ret)

    # TODO: 2 overloads of setOnFrameAvailableListener; only the first is wired.
    #   overload[0] = (Landroid/graphics/SurfaceTexture$OnFrameAvailableListener;)V
    #   overload[1] = (Landroid/graphics/SurfaceTexture$OnFrameAvailableListener;Landroid/os/Handler;)V
    def setOnFrameAvailableListener(self, p0) -> None:
        cdef JNIEnv* env = get_env()
        _ensure_ids_SurfaceTexture(env)
        cdef jvalue _args[1]
        _args[0].l = (<JavaObject?>p0)._handle if p0 is not None else <jobject>NULL
        jnicore_CallVoidMethodA(env, self._handle, _m_setOnFrameAvailableListener_0, _args)
        check_jni_exc(env)

    def setDefaultBufferSize(self, p0, p1) -> None:
        cdef JNIEnv* env = get_env()
        _ensure_ids_SurfaceTexture(env)
        cdef jvalue _args[2]
        _args[0].i = py_to_jint(p0)
        _args[1].i = py_to_jint(p1)
        jnicore_CallVoidMethodA(env, self._handle, _m_setDefaultBufferSize_0, _args)
        check_jni_exc(env)

    def updateTexImage(self) -> None:
        cdef JNIEnv* env = get_env()
        _ensure_ids_SurfaceTexture(env)
        cdef jvalue _args[1]  # unused; arrayless calls disallowed in Cython
        jnicore_CallVoidMethodA(env, self._handle, _m_updateTexImage_0, _args)
        check_jni_exc(env)

    def releaseTexImage(self) -> None:
        cdef JNIEnv* env = get_env()
        _ensure_ids_SurfaceTexture(env)
        cdef jvalue _args[1]  # unused; arrayless calls disallowed in Cython
        jnicore_CallVoidMethodA(env, self._handle, _m_releaseTexImage_0, _args)
        check_jni_exc(env)

    def detachFromGLContext(self) -> None:
        cdef JNIEnv* env = get_env()
        _ensure_ids_SurfaceTexture(env)
        cdef jvalue _args[1]  # unused; arrayless calls disallowed in Cython
        jnicore_CallVoidMethodA(env, self._handle, _m_detachFromGLContext_0, _args)
        check_jni_exc(env)

    def attachToGLContext(self, p0) -> None:
        cdef JNIEnv* env = get_env()
        _ensure_ids_SurfaceTexture(env)
        cdef jvalue _args[1]
        _args[0].i = py_to_jint(p0)
        jnicore_CallVoidMethodA(env, self._handle, _m_attachToGLContext_0, _args)
        check_jni_exc(env)

    def getTransformMatrix(self, p0) -> None:
        cdef JNIEnv* env = get_env()
        _ensure_ids_SurfaceTexture(env)
        cdef jvalue _args[1]
        _args[0].l = (<JavaObject?>p0)._handle if p0 is not None else <jobject>NULL
        jnicore_CallVoidMethodA(env, self._handle, _m_getTransformMatrix_0, _args)
        check_jni_exc(env)

    def getDataSpace(self) -> int:
        cdef JNIEnv* env = get_env()
        _ensure_ids_SurfaceTexture(env)
        cdef jvalue _args[1]  # unused; arrayless calls disallowed in Cython
        cdef jint _ret = jnicore_CallIntMethodA(env, self._handle, _m_getDataSpace_0, _args)
        check_jni_exc(env)
        return <int>_ret

    def isReleased(self) -> bool:
        cdef JNIEnv* env = get_env()
        _ensure_ids_SurfaceTexture(env)
        cdef jvalue _args[1]  # unused; arrayless calls disallowed in Cython
        cdef jboolean _ret = jnicore_CallBooleanMethodA(env, self._handle, _m_isReleased_0, _args)
        check_jni_exc(env)
        return jboolean_to_py(_ret)

    def release(self) -> None:
        cdef JNIEnv* env = get_env()
        _ensure_ids_SurfaceTexture(env)
        cdef jvalue _args[1]  # unused; arrayless calls disallowed in Cython
        jnicore_CallVoidMethodA(env, self._handle, _m_release_0, _args)
        check_jni_exc(env)

    def getTimestamp(self) -> int:
        cdef JNIEnv* env = get_env()
        _ensure_ids_SurfaceTexture(env)
        cdef jvalue _args[1]  # unused; arrayless calls disallowed in Cython
        cdef jlong _ret = jnicore_CallLongMethodA(env, self._handle, _m_getTimestamp_0, _args)
        check_jni_exc(env)
        return <long long>_ret

__javaclass__ = "android/graphics/SurfaceTexture$OutOfResourcesException"  # android.graphics.SurfaceTexture$OutOfResourcesException

cdef jclass _cls_OutOfResourcesException = NULL
cdef jmethodID _ctor_0 = NULL
cdef jmethodID _ctor_1 = NULL

cdef int _ensure_ids_OutOfResourcesException(JNIEnv* env) except -1:
    global _cls_OutOfResourcesException, _ctor_0, _ctor_1
    if _cls_OutOfResourcesException != NULL:
        return 0
    _cls_OutOfResourcesException = find_class_global(env, b"android/graphics/SurfaceTexture$OutOfResourcesException")
    _ctor_0 = get_method_id(env, _cls_OutOfResourcesException, b"<init>", b"()V")
    _ctor_1 = get_method_id(env, _cls_OutOfResourcesException, b"<init>", b"(Ljava/lang/String;)V")
    return 0

cdef class OutOfResourcesException(JavaObject):
    """android.graphics.SurfaceTexture$OutOfResourcesException"""

    # TODO: 2 constructor overloads; only the first is wired.
    #   overload[0] = ()V
    #   overload[1] = (Ljava/lang/String;)V
    def __init__(self, ):
        cdef JNIEnv* env = get_env()
        _ensure_ids_OutOfResourcesException(env)
        cdef jvalue _args[1]  # unused; arrayless calls disallowed in Cython
        cdef jobject _ret = jnicore_NewObjectA(env, _cls_OutOfResourcesException, _ctor_0, _args)
        check_jni_exc(env)
        self._adopt_local(env, _ret)

__javaclass__ = "android/graphics/SurfaceTexture$OnFrameAvailableListener"  # android.graphics.SurfaceTexture$OnFrameAvailableListener

cdef jclass _cls_OnFrameAvailableListener = NULL
cdef jmethodID _m_onFrameAvailable_0 = NULL

cdef int _ensure_ids_OnFrameAvailableListener(JNIEnv* env) except -1:
    global _cls_OnFrameAvailableListener, _m_onFrameAvailable_0
    if _cls_OnFrameAvailableListener != NULL:
        return 0
    _cls_OnFrameAvailableListener = find_class_global(env, b"android/graphics/SurfaceTexture$OnFrameAvailableListener")
    _m_onFrameAvailable_0 = get_method_id(env, _cls_OnFrameAvailableListener, b"onFrameAvailable", b"(Landroid/graphics/SurfaceTexture;)V")
    return 0

# NOTE: OnFrameAvailableListener is a Java interface. Cython subclassing of
# Java interfaces (PythonJavaClass equivalent) is not yet implemented.
# This class is provided to access the interface's static members only.
cdef class OnFrameAvailableListener(JavaObject):
    """android.graphics.SurfaceTexture$OnFrameAvailableListener"""

    def onFrameAvailable(self, p0) -> None:
        cdef JNIEnv* env = get_env()
        _ensure_ids_OnFrameAvailableListener(env)
        cdef jvalue _args[1]
        _args[0].l = (<JavaObject?>p0)._handle if p0 is not None else <jobject>NULL
        jnicore_CallVoidMethodA(env, self._handle, _m_onFrameAvailable_0, _args)
        check_jni_exc(env)

