from typing import Any, ClassVar, overload
from android.graphics.ColorSpace import ColorSpace
from android.graphics.Rect import Rect
from java.io.OutputStream import OutputStream

class YuvImage:
    @overload
    def __init__(self, p0: Any, p1: int, p2: int, p3: int, p4: Any, p5: ColorSpace) -> None: ...
    @overload
    def __init__(self, p0: Any, p1: int, p2: int, p3: int, p4: Any) -> None: ...
    def compressToJpeg(self, p0: Rect, p1: int, p2: OutputStream) -> bool: ...
    def compressToJpegR(self, p0: "YuvImage", p1: int, p2: OutputStream) -> bool: ...
    def getYuvData(self) -> Any: ...
    def getYuvFormat(self) -> int: ...
    def getStrides(self) -> Any: ...
    def getWidth(self) -> int: ...
    def getHeight(self) -> int: ...
    def getColorSpace(self) -> ColorSpace: ...
