from typing import Any, ClassVar, overload
from android.graphics.MaskFilter import MaskFilter
from android.text.TextPaint import TextPaint

class MaskFilterSpan:
    def __init__(self, p0: MaskFilter) -> None: ...
    def toString(self) -> str: ...
    def getMaskFilter(self) -> MaskFilter: ...
    def updateDrawState(self, p0: TextPaint) -> None: ...
