from typing import Any, ClassVar, overload
from java.time.Clock import Clock
from java.time.LocalTime import LocalTime
from java.time.ZoneId import ZoneId
from java.time.chrono.ChronoLocalDate import ChronoLocalDate
from java.time.chrono.ChronoLocalDateTime import ChronoLocalDateTime
from java.time.chrono.ChronoPeriod import ChronoPeriod
from java.time.chrono.Chronology import Chronology
from java.time.chrono.Era import Era
from java.time.chrono.MinguoChronology import MinguoChronology
from java.time.chrono.MinguoEra import MinguoEra
from java.time.temporal.Temporal import Temporal
from java.time.temporal.TemporalAccessor import TemporalAccessor
from java.time.temporal.TemporalAdjuster import TemporalAdjuster
from java.time.temporal.TemporalAmount import TemporalAmount
from java.time.temporal.TemporalField import TemporalField
from java.time.temporal.TemporalUnit import TemporalUnit
from java.time.temporal.ValueRange import ValueRange

class MinguoDate:
    def equals(self, p0: Any) -> bool: ...
    def toString(self) -> str: ...
    def hashCode(self) -> int: ...
    def getLong(self, p0: TemporalField) -> int: ...
    @staticmethod
    def of(p0: int, p1: int, p2: int) -> "MinguoDate": ...
    @staticmethod
    def from_(p0: TemporalAccessor) -> "MinguoDate": ...
    @overload
    def with_(self, p0: TemporalAdjuster) -> "MinguoDate": ...
    @overload
    def with_(self, p0: TemporalField, p1: int) -> "MinguoDate": ...
    @overload
    def with_(self, p0: TemporalField, p1: int) -> Temporal: ...
    @overload
    def with_(self, p0: TemporalAdjuster) -> ChronoLocalDate: ...
    @overload
    def with_(self, p0: TemporalField, p1: int) -> ChronoLocalDate: ...
    @overload
    def with_(self, p0: TemporalAdjuster) -> Temporal: ...
    def lengthOfMonth(self) -> int: ...
    def toEpochDay(self) -> int: ...
    def atTime(self, p0: LocalTime) -> ChronoLocalDateTime: ...
    @overload
    def getEra(self) -> MinguoEra: ...
    @overload
    def getEra(self) -> Era: ...
    @overload
    @staticmethod
    def now(p0: Clock) -> "MinguoDate": ...
    @overload
    @staticmethod
    def now() -> "MinguoDate": ...
    @overload
    @staticmethod
    def now(p0: ZoneId) -> "MinguoDate": ...
    @overload
    def plus(self, p0: int, p1: TemporalUnit) -> Temporal: ...
    @overload
    def plus(self, p0: int, p1: TemporalUnit) -> ChronoLocalDate: ...
    @overload
    def plus(self, p0: int, p1: TemporalUnit) -> "MinguoDate": ...
    @overload
    def plus(self, p0: TemporalAmount) -> ChronoLocalDate: ...
    @overload
    def plus(self, p0: TemporalAmount) -> Temporal: ...
    @overload
    def plus(self, p0: TemporalAmount) -> "MinguoDate": ...
    @overload
    def until(self, p0: ChronoLocalDate) -> ChronoPeriod: ...
    @overload
    def until(self, p0: Temporal, p1: TemporalUnit) -> int: ...
    @overload
    def minus(self, p0: TemporalAmount) -> ChronoLocalDate: ...
    @overload
    def minus(self, p0: int, p1: TemporalUnit) -> ChronoLocalDate: ...
    @overload
    def minus(self, p0: TemporalAmount) -> "MinguoDate": ...
    @overload
    def minus(self, p0: TemporalAmount) -> Temporal: ...
    @overload
    def minus(self, p0: int, p1: TemporalUnit) -> Temporal: ...
    @overload
    def minus(self, p0: int, p1: TemporalUnit) -> "MinguoDate": ...
    @overload
    def getChronology(self) -> MinguoChronology: ...
    @overload
    def getChronology(self) -> Chronology: ...
    def range(self, p0: TemporalField) -> ValueRange: ...

from typing import Any, ClassVar, overload
from java.time.Clock import Clock
from java.time.LocalTime import LocalTime
from java.time.ZoneId import ZoneId
from java.time.chrono.ChronoLocalDate import ChronoLocalDate
from java.time.chrono.ChronoLocalDateTime import ChronoLocalDateTime
from java.time.chrono.ChronoPeriod import ChronoPeriod
from java.time.chrono.Chronology import Chronology
from java.time.chrono.Era import Era
from java.time.chrono.JapaneseChronology import JapaneseChronology
from java.time.chrono.JapaneseEra import JapaneseEra
from java.time.temporal.Temporal import Temporal
from java.time.temporal.TemporalAccessor import TemporalAccessor
from java.time.temporal.TemporalAdjuster import TemporalAdjuster
from java.time.temporal.TemporalAmount import TemporalAmount
from java.time.temporal.TemporalField import TemporalField
from java.time.temporal.TemporalUnit import TemporalUnit
from java.time.temporal.ValueRange import ValueRange

class JapaneseDate:
    def equals(self, p0: Any) -> bool: ...
    def toString(self) -> str: ...
    def hashCode(self) -> int: ...
    def getLong(self, p0: TemporalField) -> int: ...
    @overload
    @staticmethod
    def of(p0: int, p1: int, p2: int) -> "JapaneseDate": ...
    @overload
    @staticmethod
    def of(p0: JapaneseEra, p1: int, p2: int, p3: int) -> "JapaneseDate": ...
    @staticmethod
    def from_(p0: TemporalAccessor) -> "JapaneseDate": ...
    def isSupported(self, p0: TemporalField) -> bool: ...
    @overload
    def with_(self, p0: TemporalAdjuster) -> "JapaneseDate": ...
    @overload
    def with_(self, p0: TemporalField, p1: int) -> "JapaneseDate": ...
    @overload
    def with_(self, p0: TemporalField, p1: int) -> ChronoLocalDate: ...
    @overload
    def with_(self, p0: TemporalAdjuster) -> ChronoLocalDate: ...
    @overload
    def with_(self, p0: TemporalAdjuster) -> Temporal: ...
    @overload
    def with_(self, p0: TemporalField, p1: int) -> Temporal: ...
    def lengthOfMonth(self) -> int: ...
    def lengthOfYear(self) -> int: ...
    def toEpochDay(self) -> int: ...
    def atTime(self, p0: LocalTime) -> ChronoLocalDateTime: ...
    @overload
    def getEra(self) -> JapaneseEra: ...
    @overload
    def getEra(self) -> Era: ...
    @overload
    @staticmethod
    def now(p0: ZoneId) -> "JapaneseDate": ...
    @overload
    @staticmethod
    def now() -> "JapaneseDate": ...
    @overload
    @staticmethod
    def now(p0: Clock) -> "JapaneseDate": ...
    @overload
    def plus(self, p0: TemporalAmount) -> "JapaneseDate": ...
    @overload
    def plus(self, p0: int, p1: TemporalUnit) -> "JapaneseDate": ...
    @overload
    def plus(self, p0: int, p1: TemporalUnit) -> Temporal: ...
    @overload
    def plus(self, p0: int, p1: TemporalUnit) -> ChronoLocalDate: ...
    @overload
    def plus(self, p0: TemporalAmount) -> ChronoLocalDate: ...
    @overload
    def plus(self, p0: TemporalAmount) -> Temporal: ...
    @overload
    def until(self, p0: ChronoLocalDate) -> ChronoPeriod: ...
    @overload
    def until(self, p0: Temporal, p1: TemporalUnit) -> int: ...
    @overload
    def minus(self, p0: TemporalAmount) -> "JapaneseDate": ...
    @overload
    def minus(self, p0: int, p1: TemporalUnit) -> ChronoLocalDate: ...
    @overload
    def minus(self, p0: int, p1: TemporalUnit) -> Temporal: ...
    @overload
    def minus(self, p0: TemporalAmount) -> ChronoLocalDate: ...
    @overload
    def minus(self, p0: TemporalAmount) -> Temporal: ...
    @overload
    def minus(self, p0: int, p1: TemporalUnit) -> "JapaneseDate": ...
    @overload
    def getChronology(self) -> JapaneseChronology: ...
    @overload
    def getChronology(self) -> Chronology: ...
    def range(self, p0: TemporalField) -> ValueRange: ...

from typing import Any, ClassVar, overload
from java.time.Instant import Instant
from java.time.LocalTime import LocalTime
from java.time.ZoneId import ZoneId
from java.time.ZoneOffset import ZoneOffset
from java.time.chrono.ChronoLocalDate import ChronoLocalDate
from java.time.chrono.ChronoZonedDateTime import ChronoZonedDateTime
from java.time.chrono.Chronology import Chronology
from java.time.format.DateTimeFormatter import DateTimeFormatter
from java.time.temporal.Temporal import Temporal
from java.time.temporal.TemporalAccessor import TemporalAccessor
from java.time.temporal.TemporalAdjuster import TemporalAdjuster
from java.time.temporal.TemporalAmount import TemporalAmount
from java.time.temporal.TemporalField import TemporalField
from java.time.temporal.TemporalQuery import TemporalQuery
from java.time.temporal.TemporalUnit import TemporalUnit
from java.util.Comparator import Comparator

class ChronoLocalDateTime:
    def equals(self, p0: Any) -> bool: ...
    def toString(self) -> str: ...
    def hashCode(self) -> int: ...
    @overload
    def compareTo(self, p0: "ChronoLocalDateTime") -> int: ...
    @overload
    def compareTo(self, p0: Any) -> int: ...
    def format(self, p0: DateTimeFormatter) -> str: ...
    @staticmethod
    def from_(p0: TemporalAccessor) -> "ChronoLocalDateTime": ...
    @overload
    def isSupported(self, p0: TemporalField) -> bool: ...
    @overload
    def isSupported(self, p0: TemporalUnit) -> bool: ...
    @overload
    def with_(self, p0: TemporalAdjuster) -> Temporal: ...
    @overload
    def with_(self, p0: TemporalField, p1: int) -> Temporal: ...
    @overload
    def with_(self, p0: TemporalField, p1: int) -> "ChronoLocalDateTime": ...
    @overload
    def with_(self, p0: TemporalAdjuster) -> "ChronoLocalDateTime": ...
    def adjustInto(self, p0: Temporal) -> Temporal: ...
    def toLocalTime(self) -> LocalTime: ...
    def isAfter(self, p0: "ChronoLocalDateTime") -> bool: ...
    def isBefore(self, p0: "ChronoLocalDateTime") -> bool: ...
    @staticmethod
    def timeLineOrder() -> Comparator: ...
    def atZone(self, p0: ZoneId) -> ChronoZonedDateTime: ...
    def toLocalDate(self) -> ChronoLocalDate: ...
    def toEpochSecond(self, p0: ZoneOffset) -> int: ...
    def toInstant(self, p0: ZoneOffset) -> Instant: ...
    def query(self, p0: TemporalQuery) -> Any: ...
    def isEqual(self, p0: "ChronoLocalDateTime") -> bool: ...
    @overload
    def plus(self, p0: TemporalAmount) -> Temporal: ...
    @overload
    def plus(self, p0: int, p1: TemporalUnit) -> "ChronoLocalDateTime": ...
    @overload
    def plus(self, p0: TemporalAmount) -> "ChronoLocalDateTime": ...
    @overload
    def plus(self, p0: int, p1: TemporalUnit) -> Temporal: ...
    @overload
    def minus(self, p0: int, p1: TemporalUnit) -> "ChronoLocalDateTime": ...
    @overload
    def minus(self, p0: int, p1: TemporalUnit) -> Temporal: ...
    @overload
    def minus(self, p0: TemporalAmount) -> Temporal: ...
    @overload
    def minus(self, p0: TemporalAmount) -> "ChronoLocalDateTime": ...
    def getChronology(self) -> Chronology: ...

from typing import Any, ClassVar, overload
from java.time.format.TextStyle import TextStyle
from java.util.Locale import Locale

class MinguoEra:
    BEFORE_ROC: ClassVar["MinguoEra"]
    ROC: ClassVar["MinguoEra"]
    BEFORE_ROC: ClassVar["MinguoEra"]
    ROC: ClassVar["MinguoEra"]
    @staticmethod
    def values() -> Any: ...
    @staticmethod
    def valueOf(p0: str) -> "MinguoEra": ...
    def getValue(self) -> int: ...
    @staticmethod
    def of(p0: int) -> "MinguoEra": ...
    def getDisplayName(self, p0: TextStyle, p1: Locale) -> str: ...

from typing import Any, ClassVar, overload
from java.time.Clock import Clock
from java.time.Instant import Instant
from java.time.ZoneId import ZoneId
from java.time.chrono.ChronoLocalDate import ChronoLocalDate
from java.time.chrono.ChronoLocalDateTime import ChronoLocalDateTime
from java.time.chrono.ChronoZonedDateTime import ChronoZonedDateTime
from java.time.chrono.Era import Era
from java.time.chrono.ThaiBuddhistDate import ThaiBuddhistDate
from java.time.chrono.ThaiBuddhistEra import ThaiBuddhistEra
from java.time.format.ResolverStyle import ResolverStyle
from java.time.temporal.ChronoField import ChronoField
from java.time.temporal.TemporalAccessor import TemporalAccessor
from java.time.temporal.ValueRange import ValueRange

class ThaiBuddhistChronology:
    INSTANCE: ClassVar["ThaiBuddhistChronology"]
    def getId(self) -> str: ...
    def isLeapYear(self, p0: int) -> bool: ...
    @overload
    def eraOf(self, p0: int) -> ThaiBuddhistEra: ...
    @overload
    def eraOf(self, p0: int) -> Era: ...
    def localDateTime(self, p0: TemporalAccessor) -> ChronoLocalDateTime: ...
    @overload
    def date(self, p0: Era, p1: int, p2: int, p3: int) -> ChronoLocalDate: ...
    @overload
    def date(self, p0: int, p1: int, p2: int) -> ChronoLocalDate: ...
    @overload
    def date(self, p0: TemporalAccessor) -> ThaiBuddhistDate: ...
    @overload
    def date(self, p0: int, p1: int, p2: int) -> ThaiBuddhistDate: ...
    @overload
    def date(self, p0: Era, p1: int, p2: int, p3: int) -> ThaiBuddhistDate: ...
    @overload
    def date(self, p0: TemporalAccessor) -> ChronoLocalDate: ...
    def eras(self) -> list: ...
    def prolepticYear(self, p0: Era, p1: int) -> int: ...
    @overload
    def dateYearDay(self, p0: int, p1: int) -> ChronoLocalDate: ...
    @overload
    def dateYearDay(self, p0: int, p1: int) -> ThaiBuddhistDate: ...
    @overload
    def dateYearDay(self, p0: Era, p1: int, p2: int) -> ThaiBuddhistDate: ...
    @overload
    def dateYearDay(self, p0: Era, p1: int, p2: int) -> ChronoLocalDate: ...
    @overload
    def dateNow(self) -> ChronoLocalDate: ...
    @overload
    def dateNow(self, p0: ZoneId) -> ThaiBuddhistDate: ...
    @overload
    def dateNow(self, p0: Clock) -> ChronoLocalDate: ...
    @overload
    def dateNow(self, p0: ZoneId) -> ChronoLocalDate: ...
    @overload
    def dateNow(self, p0: Clock) -> ThaiBuddhistDate: ...
    @overload
    def dateNow(self) -> ThaiBuddhistDate: ...
    @overload
    def dateEpochDay(self, p0: int) -> ThaiBuddhistDate: ...
    @overload
    def dateEpochDay(self, p0: int) -> ChronoLocalDate: ...
    @overload
    def resolveDate(self, p0: dict, p1: ResolverStyle) -> ChronoLocalDate: ...
    @overload
    def resolveDate(self, p0: dict, p1: ResolverStyle) -> ThaiBuddhistDate: ...
    def isIsoBased(self) -> bool: ...
    def getCalendarType(self) -> str: ...
    def range(self, p0: ChronoField) -> ValueRange: ...
    @overload
    def zonedDateTime(self, p0: Instant, p1: ZoneId) -> ChronoZonedDateTime: ...
    @overload
    def zonedDateTime(self, p0: TemporalAccessor) -> ChronoZonedDateTime: ...

from typing import Any, ClassVar, overload
from java.time.Instant import Instant
from java.time.LocalTime import LocalTime
from java.time.ZoneId import ZoneId
from java.time.ZoneOffset import ZoneOffset
from java.time.chrono.ChronoLocalDate import ChronoLocalDate
from java.time.chrono.ChronoLocalDateTime import ChronoLocalDateTime
from java.time.chrono.Chronology import Chronology
from java.time.format.DateTimeFormatter import DateTimeFormatter
from java.time.temporal.Temporal import Temporal
from java.time.temporal.TemporalAccessor import TemporalAccessor
from java.time.temporal.TemporalAdjuster import TemporalAdjuster
from java.time.temporal.TemporalAmount import TemporalAmount
from java.time.temporal.TemporalField import TemporalField
from java.time.temporal.TemporalQuery import TemporalQuery
from java.time.temporal.TemporalUnit import TemporalUnit
from java.time.temporal.ValueRange import ValueRange
from java.util.Comparator import Comparator

class ChronoZonedDateTime:
    def get(self, p0: TemporalField) -> int: ...
    def equals(self, p0: Any) -> bool: ...
    def toString(self) -> str: ...
    def hashCode(self) -> int: ...
    @overload
    def compareTo(self, p0: Any) -> int: ...
    @overload
    def compareTo(self, p0: "ChronoZonedDateTime") -> int: ...
    def getLong(self, p0: TemporalField) -> int: ...
    def format(self, p0: DateTimeFormatter) -> str: ...
    @staticmethod
    def from_(p0: TemporalAccessor) -> "ChronoZonedDateTime": ...
    @overload
    def isSupported(self, p0: TemporalUnit) -> bool: ...
    @overload
    def isSupported(self, p0: TemporalField) -> bool: ...
    @overload
    def with_(self, p0: TemporalAdjuster) -> "ChronoZonedDateTime": ...
    @overload
    def with_(self, p0: TemporalField, p1: int) -> "ChronoZonedDateTime": ...
    @overload
    def with_(self, p0: TemporalAdjuster) -> Temporal: ...
    @overload
    def with_(self, p0: TemporalField, p1: int) -> Temporal: ...
    def getOffset(self) -> ZoneOffset: ...
    def getZone(self) -> ZoneId: ...
    def toLocalTime(self) -> LocalTime: ...
    def isAfter(self, p0: "ChronoZonedDateTime") -> bool: ...
    def isBefore(self, p0: "ChronoZonedDateTime") -> bool: ...
    @staticmethod
    def timeLineOrder() -> Comparator: ...
    def toLocalDateTime(self) -> ChronoLocalDateTime: ...
    def toLocalDate(self) -> ChronoLocalDate: ...
    def toEpochSecond(self) -> int: ...
    def toInstant(self) -> Instant: ...
    def query(self, p0: TemporalQuery) -> Any: ...
    def isEqual(self, p0: "ChronoZonedDateTime") -> bool: ...
    @overload
    def plus(self, p0: int, p1: TemporalUnit) -> Temporal: ...
    @overload
    def plus(self, p0: TemporalAmount) -> Temporal: ...
    @overload
    def plus(self, p0: TemporalAmount) -> "ChronoZonedDateTime": ...
    @overload
    def plus(self, p0: int, p1: TemporalUnit) -> "ChronoZonedDateTime": ...
    @overload
    def minus(self, p0: TemporalAmount) -> Temporal: ...
    @overload
    def minus(self, p0: int, p1: TemporalUnit) -> Temporal: ...
    @overload
    def minus(self, p0: int, p1: TemporalUnit) -> "ChronoZonedDateTime": ...
    @overload
    def minus(self, p0: TemporalAmount) -> "ChronoZonedDateTime": ...
    def getChronology(self) -> Chronology: ...
    def range(self, p0: TemporalField) -> ValueRange: ...
    def withZoneSameInstant(self, p0: ZoneId) -> "ChronoZonedDateTime": ...
    def withZoneSameLocal(self, p0: ZoneId) -> "ChronoZonedDateTime": ...
    def withLaterOffsetAtOverlap(self) -> "ChronoZonedDateTime": ...
    def withEarlierOffsetAtOverlap(self) -> "ChronoZonedDateTime": ...

from typing import Any, ClassVar, overload
from java.time.Clock import Clock
from java.time.Instant import Instant
from java.time.ZoneId import ZoneId
from java.time.ZoneOffset import ZoneOffset
from java.time.chrono.ChronoLocalDate import ChronoLocalDate
from java.time.chrono.ChronoLocalDateTime import ChronoLocalDateTime
from java.time.chrono.ChronoPeriod import ChronoPeriod
from java.time.chrono.ChronoZonedDateTime import ChronoZonedDateTime
from java.time.chrono.Era import Era
from java.time.format.ResolverStyle import ResolverStyle
from java.time.format.TextStyle import TextStyle
from java.time.temporal.ChronoField import ChronoField
from java.time.temporal.TemporalAccessor import TemporalAccessor
from java.time.temporal.ValueRange import ValueRange
from java.util.Locale import Locale

class Chronology:
    def equals(self, p0: Any) -> bool: ...
    def toString(self) -> str: ...
    def hashCode(self) -> int: ...
    @overload
    def compareTo(self, p0: "Chronology") -> int: ...
    @overload
    def compareTo(self, p0: Any) -> int: ...
    @staticmethod
    def of(p0: str) -> "Chronology": ...
    @staticmethod
    def from_(p0: TemporalAccessor) -> "Chronology": ...
    def getId(self) -> str: ...
    def getDisplayName(self, p0: TextStyle, p1: Locale) -> str: ...
    def isLeapYear(self, p0: int) -> bool: ...
    def eraOf(self, p0: int) -> Era: ...
    @overload
    def epochSecond(self, p0: Era, p1: int, p2: int, p3: int, p4: int, p5: int, p6: int, p7: ZoneOffset) -> int: ...
    @overload
    def epochSecond(self, p0: int, p1: int, p2: int, p3: int, p4: int, p5: int, p6: ZoneOffset) -> int: ...
    def localDateTime(self, p0: TemporalAccessor) -> ChronoLocalDateTime: ...
    @overload
    def date(self, p0: int, p1: int, p2: int) -> ChronoLocalDate: ...
    @overload
    def date(self, p0: Era, p1: int, p2: int, p3: int) -> ChronoLocalDate: ...
    @overload
    def date(self, p0: TemporalAccessor) -> ChronoLocalDate: ...
    def period(self, p0: int, p1: int, p2: int) -> ChronoPeriod: ...
    def eras(self) -> list: ...
    @staticmethod
    def ofLocale(p0: Locale) -> "Chronology": ...
    @staticmethod
    def getAvailableChronologies() -> set: ...
    def prolepticYear(self, p0: Era, p1: int) -> int: ...
    @overload
    def dateYearDay(self, p0: Era, p1: int, p2: int) -> ChronoLocalDate: ...
    @overload
    def dateYearDay(self, p0: int, p1: int) -> ChronoLocalDate: ...
    @overload
    def dateNow(self, p0: ZoneId) -> ChronoLocalDate: ...
    @overload
    def dateNow(self, p0: Clock) -> ChronoLocalDate: ...
    @overload
    def dateNow(self) -> ChronoLocalDate: ...
    def dateEpochDay(self, p0: int) -> ChronoLocalDate: ...
    def resolveDate(self, p0: dict, p1: ResolverStyle) -> ChronoLocalDate: ...
    def isIsoBased(self) -> bool: ...
    def getCalendarType(self) -> str: ...
    def range(self, p0: ChronoField) -> ValueRange: ...
    @overload
    def zonedDateTime(self, p0: Instant, p1: ZoneId) -> ChronoZonedDateTime: ...
    @overload
    def zonedDateTime(self, p0: TemporalAccessor) -> ChronoZonedDateTime: ...

from typing import Any, ClassVar, overload

class IsoEra:
    BCE: ClassVar["IsoEra"]
    CE: ClassVar["IsoEra"]
    BCE: ClassVar["IsoEra"]
    CE: ClassVar["IsoEra"]
    @staticmethod
    def values() -> Any: ...
    @staticmethod
    def valueOf(p0: str) -> "IsoEra": ...
    def getValue(self) -> int: ...
    @staticmethod
    def of(p0: int) -> "IsoEra": ...

from typing import Any, ClassVar, overload
from java.time.chrono.ChronoLocalDate import ChronoLocalDate
from java.time.chrono.Chronology import Chronology
from java.time.temporal.Temporal import Temporal
from java.time.temporal.TemporalAmount import TemporalAmount
from java.time.temporal.TemporalUnit import TemporalUnit

class ChronoPeriod:
    def get(self, p0: TemporalUnit) -> int: ...
    def equals(self, p0: Any) -> bool: ...
    def toString(self) -> str: ...
    def hashCode(self) -> int: ...
    @staticmethod
    def between(p0: ChronoLocalDate, p1: ChronoLocalDate) -> "ChronoPeriod": ...
    def plus(self, p0: TemporalAmount) -> "ChronoPeriod": ...
    def getUnits(self) -> list: ...
    def negated(self) -> "ChronoPeriod": ...
    def multipliedBy(self, p0: int) -> "ChronoPeriod": ...
    def isNegative(self) -> bool: ...
    def minus(self, p0: TemporalAmount) -> "ChronoPeriod": ...
    def isZero(self) -> bool: ...
    def addTo(self, p0: Temporal) -> Temporal: ...
    def subtractFrom(self, p0: Temporal) -> Temporal: ...
    def getChronology(self) -> Chronology: ...
    def normalized(self) -> "ChronoPeriod": ...

from typing import Any, ClassVar, overload
from java.time.LocalTime import LocalTime
from java.time.chrono.ChronoLocalDateTime import ChronoLocalDateTime
from java.time.chrono.ChronoPeriod import ChronoPeriod
from java.time.chrono.Chronology import Chronology
from java.time.chrono.Era import Era
from java.time.format.DateTimeFormatter import DateTimeFormatter
from java.time.temporal.Temporal import Temporal
from java.time.temporal.TemporalAccessor import TemporalAccessor
from java.time.temporal.TemporalAdjuster import TemporalAdjuster
from java.time.temporal.TemporalAmount import TemporalAmount
from java.time.temporal.TemporalField import TemporalField
from java.time.temporal.TemporalQuery import TemporalQuery
from java.time.temporal.TemporalUnit import TemporalUnit
from java.util.Comparator import Comparator

class ChronoLocalDate:
    def equals(self, p0: Any) -> bool: ...
    def toString(self) -> str: ...
    def hashCode(self) -> int: ...
    @overload
    def compareTo(self, p0: "ChronoLocalDate") -> int: ...
    @overload
    def compareTo(self, p0: Any) -> int: ...
    def format(self, p0: DateTimeFormatter) -> str: ...
    @staticmethod
    def from_(p0: TemporalAccessor) -> "ChronoLocalDate": ...
    @overload
    def isSupported(self, p0: TemporalUnit) -> bool: ...
    @overload
    def isSupported(self, p0: TemporalField) -> bool: ...
    @overload
    def with_(self, p0: TemporalField, p1: int) -> Temporal: ...
    @overload
    def with_(self, p0: TemporalAdjuster) -> Temporal: ...
    @overload
    def with_(self, p0: TemporalAdjuster) -> "ChronoLocalDate": ...
    @overload
    def with_(self, p0: TemporalField, p1: int) -> "ChronoLocalDate": ...
    def isLeapYear(self) -> bool: ...
    def lengthOfMonth(self) -> int: ...
    def lengthOfYear(self) -> int: ...
    def toEpochDay(self) -> int: ...
    def adjustInto(self, p0: Temporal) -> Temporal: ...
    def atTime(self, p0: LocalTime) -> ChronoLocalDateTime: ...
    def isAfter(self, p0: "ChronoLocalDate") -> bool: ...
    def isBefore(self, p0: "ChronoLocalDate") -> bool: ...
    def getEra(self) -> Era: ...
    @staticmethod
    def timeLineOrder() -> Comparator: ...
    def query(self, p0: TemporalQuery) -> Any: ...
    def isEqual(self, p0: "ChronoLocalDate") -> bool: ...
    @overload
    def plus(self, p0: int, p1: TemporalUnit) -> Temporal: ...
    @overload
    def plus(self, p0: TemporalAmount) -> Temporal: ...
    @overload
    def plus(self, p0: int, p1: TemporalUnit) -> "ChronoLocalDate": ...
    @overload
    def plus(self, p0: TemporalAmount) -> "ChronoLocalDate": ...
    @overload
    def until(self, p0: Temporal, p1: TemporalUnit) -> int: ...
    @overload
    def until(self, p0: "ChronoLocalDate") -> ChronoPeriod: ...
    @overload
    def minus(self, p0: TemporalAmount) -> Temporal: ...
    @overload
    def minus(self, p0: int, p1: TemporalUnit) -> "ChronoLocalDate": ...
    @overload
    def minus(self, p0: TemporalAmount) -> "ChronoLocalDate": ...
    @overload
    def minus(self, p0: int, p1: TemporalUnit) -> Temporal: ...
    def getChronology(self) -> Chronology: ...

from typing import Any, ClassVar, overload
from java.time.Clock import Clock
from java.time.Instant import Instant
from java.time.ZoneId import ZoneId
from java.time.chrono.ChronoLocalDate import ChronoLocalDate
from java.time.chrono.ChronoLocalDateTime import ChronoLocalDateTime
from java.time.chrono.ChronoZonedDateTime import ChronoZonedDateTime
from java.time.chrono.Era import Era
from java.time.chrono.MinguoDate import MinguoDate
from java.time.chrono.MinguoEra import MinguoEra
from java.time.format.ResolverStyle import ResolverStyle
from java.time.temporal.ChronoField import ChronoField
from java.time.temporal.TemporalAccessor import TemporalAccessor
from java.time.temporal.ValueRange import ValueRange

class MinguoChronology:
    INSTANCE: ClassVar["MinguoChronology"]
    def getId(self) -> str: ...
    def isLeapYear(self, p0: int) -> bool: ...
    @overload
    def eraOf(self, p0: int) -> MinguoEra: ...
    @overload
    def eraOf(self, p0: int) -> Era: ...
    def localDateTime(self, p0: TemporalAccessor) -> ChronoLocalDateTime: ...
    @overload
    def date(self, p0: Era, p1: int, p2: int, p3: int) -> ChronoLocalDate: ...
    @overload
    def date(self, p0: int, p1: int, p2: int) -> ChronoLocalDate: ...
    @overload
    def date(self, p0: TemporalAccessor) -> MinguoDate: ...
    @overload
    def date(self, p0: int, p1: int, p2: int) -> MinguoDate: ...
    @overload
    def date(self, p0: Era, p1: int, p2: int, p3: int) -> MinguoDate: ...
    @overload
    def date(self, p0: TemporalAccessor) -> ChronoLocalDate: ...
    def eras(self) -> list: ...
    def prolepticYear(self, p0: Era, p1: int) -> int: ...
    @overload
    def dateYearDay(self, p0: int, p1: int) -> ChronoLocalDate: ...
    @overload
    def dateYearDay(self, p0: int, p1: int) -> MinguoDate: ...
    @overload
    def dateYearDay(self, p0: Era, p1: int, p2: int) -> MinguoDate: ...
    @overload
    def dateYearDay(self, p0: Era, p1: int, p2: int) -> ChronoLocalDate: ...
    @overload
    def dateNow(self) -> ChronoLocalDate: ...
    @overload
    def dateNow(self, p0: ZoneId) -> MinguoDate: ...
    @overload
    def dateNow(self, p0: Clock) -> ChronoLocalDate: ...
    @overload
    def dateNow(self, p0: ZoneId) -> ChronoLocalDate: ...
    @overload
    def dateNow(self, p0: Clock) -> MinguoDate: ...
    @overload
    def dateNow(self) -> MinguoDate: ...
    @overload
    def dateEpochDay(self, p0: int) -> MinguoDate: ...
    @overload
    def dateEpochDay(self, p0: int) -> ChronoLocalDate: ...
    @overload
    def resolveDate(self, p0: dict, p1: ResolverStyle) -> ChronoLocalDate: ...
    @overload
    def resolveDate(self, p0: dict, p1: ResolverStyle) -> MinguoDate: ...
    def isIsoBased(self) -> bool: ...
    def getCalendarType(self) -> str: ...
    def range(self, p0: ChronoField) -> ValueRange: ...
    @overload
    def zonedDateTime(self, p0: Instant, p1: ZoneId) -> ChronoZonedDateTime: ...
    @overload
    def zonedDateTime(self, p0: TemporalAccessor) -> ChronoZonedDateTime: ...

from typing import Any, ClassVar, overload
from java.time.Clock import Clock
from java.time.LocalTime import LocalTime
from java.time.ZoneId import ZoneId
from java.time.chrono.ChronoLocalDate import ChronoLocalDate
from java.time.chrono.ChronoLocalDateTime import ChronoLocalDateTime
from java.time.chrono.ChronoPeriod import ChronoPeriod
from java.time.chrono.Chronology import Chronology
from java.time.chrono.Era import Era
from java.time.chrono.ThaiBuddhistChronology import ThaiBuddhistChronology
from java.time.chrono.ThaiBuddhistEra import ThaiBuddhistEra
from java.time.temporal.Temporal import Temporal
from java.time.temporal.TemporalAccessor import TemporalAccessor
from java.time.temporal.TemporalAdjuster import TemporalAdjuster
from java.time.temporal.TemporalAmount import TemporalAmount
from java.time.temporal.TemporalField import TemporalField
from java.time.temporal.TemporalUnit import TemporalUnit
from java.time.temporal.ValueRange import ValueRange

class ThaiBuddhistDate:
    def equals(self, p0: Any) -> bool: ...
    def toString(self) -> str: ...
    def hashCode(self) -> int: ...
    def getLong(self, p0: TemporalField) -> int: ...
    @staticmethod
    def of(p0: int, p1: int, p2: int) -> "ThaiBuddhistDate": ...
    @staticmethod
    def from_(p0: TemporalAccessor) -> "ThaiBuddhistDate": ...
    @overload
    def with_(self, p0: TemporalAdjuster) -> "ThaiBuddhistDate": ...
    @overload
    def with_(self, p0: TemporalField, p1: int) -> "ThaiBuddhistDate": ...
    @overload
    def with_(self, p0: TemporalField, p1: int) -> Temporal: ...
    @overload
    def with_(self, p0: TemporalAdjuster) -> ChronoLocalDate: ...
    @overload
    def with_(self, p0: TemporalField, p1: int) -> ChronoLocalDate: ...
    @overload
    def with_(self, p0: TemporalAdjuster) -> Temporal: ...
    def lengthOfMonth(self) -> int: ...
    def toEpochDay(self) -> int: ...
    def atTime(self, p0: LocalTime) -> ChronoLocalDateTime: ...
    @overload
    def getEra(self) -> ThaiBuddhistEra: ...
    @overload
    def getEra(self) -> Era: ...
    @overload
    @staticmethod
    def now(p0: Clock) -> "ThaiBuddhistDate": ...
    @overload
    @staticmethod
    def now() -> "ThaiBuddhistDate": ...
    @overload
    @staticmethod
    def now(p0: ZoneId) -> "ThaiBuddhistDate": ...
    @overload
    def plus(self, p0: int, p1: TemporalUnit) -> Temporal: ...
    @overload
    def plus(self, p0: int, p1: TemporalUnit) -> ChronoLocalDate: ...
    @overload
    def plus(self, p0: int, p1: TemporalUnit) -> "ThaiBuddhistDate": ...
    @overload
    def plus(self, p0: TemporalAmount) -> ChronoLocalDate: ...
    @overload
    def plus(self, p0: TemporalAmount) -> Temporal: ...
    @overload
    def plus(self, p0: TemporalAmount) -> "ThaiBuddhistDate": ...
    @overload
    def until(self, p0: ChronoLocalDate) -> ChronoPeriod: ...
    @overload
    def until(self, p0: Temporal, p1: TemporalUnit) -> int: ...
    @overload
    def minus(self, p0: TemporalAmount) -> ChronoLocalDate: ...
    @overload
    def minus(self, p0: int, p1: TemporalUnit) -> ChronoLocalDate: ...
    @overload
    def minus(self, p0: TemporalAmount) -> "ThaiBuddhistDate": ...
    @overload
    def minus(self, p0: TemporalAmount) -> Temporal: ...
    @overload
    def minus(self, p0: int, p1: TemporalUnit) -> Temporal: ...
    @overload
    def minus(self, p0: int, p1: TemporalUnit) -> "ThaiBuddhistDate": ...
    @overload
    def getChronology(self) -> ThaiBuddhistChronology: ...
    @overload
    def getChronology(self) -> Chronology: ...
    def range(self, p0: TemporalField) -> ValueRange: ...

from typing import Any, ClassVar, overload
from java.time.format.TextStyle import TextStyle
from java.time.temporal.TemporalField import TemporalField
from java.time.temporal.ValueRange import ValueRange
from java.util.Locale import Locale

class JapaneseEra:
    MEIJI: ClassVar["JapaneseEra"]
    TAISHO: ClassVar["JapaneseEra"]
    SHOWA: ClassVar["JapaneseEra"]
    HEISEI: ClassVar["JapaneseEra"]
    REIWA: ClassVar["JapaneseEra"]
    def toString(self) -> str: ...
    @staticmethod
    def values() -> Any: ...
    @staticmethod
    def valueOf(p0: str) -> "JapaneseEra": ...
    def getValue(self) -> int: ...
    @staticmethod
    def of(p0: int) -> "JapaneseEra": ...
    def getDisplayName(self, p0: TextStyle, p1: Locale) -> str: ...
    def range(self, p0: TemporalField) -> ValueRange: ...

from typing import Any, ClassVar, overload
from java.time.chrono.ChronoLocalDate import ChronoLocalDate
from java.time.chrono.Chronology import Chronology
from java.time.format.ResolverStyle import ResolverStyle

class AbstractChronology:
    def equals(self, p0: Any) -> bool: ...
    def toString(self) -> str: ...
    def hashCode(self) -> int: ...
    @overload
    def compareTo(self, p0: Any) -> int: ...
    @overload
    def compareTo(self, p0: Chronology) -> int: ...
    def resolveDate(self, p0: dict, p1: ResolverStyle) -> ChronoLocalDate: ...

from typing import Any, ClassVar, overload
from java.time.Clock import Clock
from java.time.Instant import Instant
from java.time.ZoneId import ZoneId
from java.time.chrono.ChronoLocalDate import ChronoLocalDate
from java.time.chrono.ChronoLocalDateTime import ChronoLocalDateTime
from java.time.chrono.ChronoZonedDateTime import ChronoZonedDateTime
from java.time.chrono.Era import Era
from java.time.chrono.HijrahDate import HijrahDate
from java.time.chrono.HijrahEra import HijrahEra
from java.time.format.ResolverStyle import ResolverStyle
from java.time.temporal.ChronoField import ChronoField
from java.time.temporal.TemporalAccessor import TemporalAccessor
from java.time.temporal.ValueRange import ValueRange

class HijrahChronology:
    INSTANCE: ClassVar["HijrahChronology"]
    def getId(self) -> str: ...
    def isLeapYear(self, p0: int) -> bool: ...
    @overload
    def eraOf(self, p0: int) -> Era: ...
    @overload
    def eraOf(self, p0: int) -> HijrahEra: ...
    def localDateTime(self, p0: TemporalAccessor) -> ChronoLocalDateTime: ...
    @overload
    def date(self, p0: Era, p1: int, p2: int, p3: int) -> HijrahDate: ...
    @overload
    def date(self, p0: Era, p1: int, p2: int, p3: int) -> ChronoLocalDate: ...
    @overload
    def date(self, p0: TemporalAccessor) -> ChronoLocalDate: ...
    @overload
    def date(self, p0: int, p1: int, p2: int) -> HijrahDate: ...
    @overload
    def date(self, p0: int, p1: int, p2: int) -> ChronoLocalDate: ...
    @overload
    def date(self, p0: TemporalAccessor) -> HijrahDate: ...
    def eras(self) -> list: ...
    def prolepticYear(self, p0: Era, p1: int) -> int: ...
    @overload
    def dateYearDay(self, p0: Era, p1: int, p2: int) -> ChronoLocalDate: ...
    @overload
    def dateYearDay(self, p0: int, p1: int) -> ChronoLocalDate: ...
    @overload
    def dateYearDay(self, p0: Era, p1: int, p2: int) -> HijrahDate: ...
    @overload
    def dateYearDay(self, p0: int, p1: int) -> HijrahDate: ...
    @overload
    def dateNow(self) -> HijrahDate: ...
    @overload
    def dateNow(self, p0: ZoneId) -> HijrahDate: ...
    @overload
    def dateNow(self, p0: Clock) -> ChronoLocalDate: ...
    @overload
    def dateNow(self, p0: ZoneId) -> ChronoLocalDate: ...
    @overload
    def dateNow(self) -> ChronoLocalDate: ...
    @overload
    def dateNow(self, p0: Clock) -> HijrahDate: ...
    @overload
    def dateEpochDay(self, p0: int) -> ChronoLocalDate: ...
    @overload
    def dateEpochDay(self, p0: int) -> HijrahDate: ...
    @overload
    def resolveDate(self, p0: dict, p1: ResolverStyle) -> HijrahDate: ...
    @overload
    def resolveDate(self, p0: dict, p1: ResolverStyle) -> ChronoLocalDate: ...
    def getCalendarType(self) -> str: ...
    def range(self, p0: ChronoField) -> ValueRange: ...
    @overload
    def zonedDateTime(self, p0: Instant, p1: ZoneId) -> ChronoZonedDateTime: ...
    @overload
    def zonedDateTime(self, p0: TemporalAccessor) -> ChronoZonedDateTime: ...

from typing import Any, ClassVar, overload
from java.time.Clock import Clock
from java.time.Instant import Instant
from java.time.ZoneId import ZoneId
from java.time.chrono.ChronoLocalDate import ChronoLocalDate
from java.time.chrono.ChronoLocalDateTime import ChronoLocalDateTime
from java.time.chrono.ChronoZonedDateTime import ChronoZonedDateTime
from java.time.chrono.Era import Era
from java.time.chrono.JapaneseDate import JapaneseDate
from java.time.chrono.JapaneseEra import JapaneseEra
from java.time.format.ResolverStyle import ResolverStyle
from java.time.temporal.ChronoField import ChronoField
from java.time.temporal.TemporalAccessor import TemporalAccessor
from java.time.temporal.ValueRange import ValueRange

class JapaneseChronology:
    INSTANCE: ClassVar["JapaneseChronology"]
    def getId(self) -> str: ...
    def isLeapYear(self, p0: int) -> bool: ...
    @overload
    def eraOf(self, p0: int) -> Era: ...
    @overload
    def eraOf(self, p0: int) -> JapaneseEra: ...
    def localDateTime(self, p0: TemporalAccessor) -> ChronoLocalDateTime: ...
    @overload
    def date(self, p0: int, p1: int, p2: int) -> ChronoLocalDate: ...
    @overload
    def date(self, p0: Era, p1: int, p2: int, p3: int) -> JapaneseDate: ...
    @overload
    def date(self, p0: TemporalAccessor) -> ChronoLocalDate: ...
    @overload
    def date(self, p0: int, p1: int, p2: int) -> JapaneseDate: ...
    @overload
    def date(self, p0: TemporalAccessor) -> JapaneseDate: ...
    @overload
    def date(self, p0: Era, p1: int, p2: int, p3: int) -> ChronoLocalDate: ...
    def eras(self) -> list: ...
    def prolepticYear(self, p0: Era, p1: int) -> int: ...
    @overload
    def dateYearDay(self, p0: int, p1: int) -> ChronoLocalDate: ...
    @overload
    def dateYearDay(self, p0: Era, p1: int, p2: int) -> JapaneseDate: ...
    @overload
    def dateYearDay(self, p0: Era, p1: int, p2: int) -> ChronoLocalDate: ...
    @overload
    def dateYearDay(self, p0: int, p1: int) -> JapaneseDate: ...
    @overload
    def dateNow(self, p0: Clock) -> ChronoLocalDate: ...
    @overload
    def dateNow(self, p0: ZoneId) -> ChronoLocalDate: ...
    @overload
    def dateNow(self) -> ChronoLocalDate: ...
    @overload
    def dateNow(self, p0: ZoneId) -> JapaneseDate: ...
    @overload
    def dateNow(self, p0: Clock) -> JapaneseDate: ...
    @overload
    def dateNow(self) -> JapaneseDate: ...
    @overload
    def dateEpochDay(self, p0: int) -> ChronoLocalDate: ...
    @overload
    def dateEpochDay(self, p0: int) -> JapaneseDate: ...
    @overload
    def resolveDate(self, p0: dict, p1: ResolverStyle) -> ChronoLocalDate: ...
    @overload
    def resolveDate(self, p0: dict, p1: ResolverStyle) -> JapaneseDate: ...
    def isIsoBased(self) -> bool: ...
    def getCalendarType(self) -> str: ...
    def range(self, p0: ChronoField) -> ValueRange: ...
    @overload
    def zonedDateTime(self, p0: TemporalAccessor) -> ChronoZonedDateTime: ...
    @overload
    def zonedDateTime(self, p0: Instant, p1: ZoneId) -> ChronoZonedDateTime: ...

from typing import Any, ClassVar, overload
from java.time.Clock import Clock
from java.time.LocalTime import LocalTime
from java.time.ZoneId import ZoneId
from java.time.chrono.ChronoLocalDate import ChronoLocalDate
from java.time.chrono.ChronoLocalDateTime import ChronoLocalDateTime
from java.time.chrono.ChronoPeriod import ChronoPeriod
from java.time.chrono.Chronology import Chronology
from java.time.chrono.Era import Era
from java.time.chrono.HijrahChronology import HijrahChronology
from java.time.chrono.HijrahEra import HijrahEra
from java.time.temporal.Temporal import Temporal
from java.time.temporal.TemporalAccessor import TemporalAccessor
from java.time.temporal.TemporalAdjuster import TemporalAdjuster
from java.time.temporal.TemporalAmount import TemporalAmount
from java.time.temporal.TemporalField import TemporalField
from java.time.temporal.TemporalUnit import TemporalUnit
from java.time.temporal.ValueRange import ValueRange

class HijrahDate:
    def equals(self, p0: Any) -> bool: ...
    def toString(self) -> str: ...
    def hashCode(self) -> int: ...
    def getLong(self, p0: TemporalField) -> int: ...
    @staticmethod
    def of(p0: int, p1: int, p2: int) -> "HijrahDate": ...
    @staticmethod
    def from_(p0: TemporalAccessor) -> "HijrahDate": ...
    @overload
    def with_(self, p0: TemporalAdjuster) -> "HijrahDate": ...
    @overload
    def with_(self, p0: TemporalField, p1: int) -> Temporal: ...
    @overload
    def with_(self, p0: TemporalField, p1: int) -> "HijrahDate": ...
    @overload
    def with_(self, p0: TemporalAdjuster) -> Temporal: ...
    @overload
    def with_(self, p0: TemporalAdjuster) -> ChronoLocalDate: ...
    @overload
    def with_(self, p0: TemporalField, p1: int) -> ChronoLocalDate: ...
    def isLeapYear(self) -> bool: ...
    def lengthOfMonth(self) -> int: ...
    def lengthOfYear(self) -> int: ...
    def toEpochDay(self) -> int: ...
    def atTime(self, p0: LocalTime) -> ChronoLocalDateTime: ...
    @overload
    def getEra(self) -> HijrahEra: ...
    @overload
    def getEra(self) -> Era: ...
    def withVariant(self, p0: HijrahChronology) -> "HijrahDate": ...
    @overload
    @staticmethod
    def now() -> "HijrahDate": ...
    @overload
    @staticmethod
    def now(p0: ZoneId) -> "HijrahDate": ...
    @overload
    @staticmethod
    def now(p0: Clock) -> "HijrahDate": ...
    @overload
    def plus(self, p0: int, p1: TemporalUnit) -> ChronoLocalDate: ...
    @overload
    def plus(self, p0: int, p1: TemporalUnit) -> Temporal: ...
    @overload
    def plus(self, p0: TemporalAmount) -> ChronoLocalDate: ...
    @overload
    def plus(self, p0: TemporalAmount) -> "HijrahDate": ...
    @overload
    def plus(self, p0: TemporalAmount) -> Temporal: ...
    @overload
    def plus(self, p0: int, p1: TemporalUnit) -> "HijrahDate": ...
    @overload
    def until(self, p0: Temporal, p1: TemporalUnit) -> int: ...
    @overload
    def until(self, p0: ChronoLocalDate) -> ChronoPeriod: ...
    @overload
    def minus(self, p0: TemporalAmount) -> Temporal: ...
    @overload
    def minus(self, p0: int, p1: TemporalUnit) -> Temporal: ...
    @overload
    def minus(self, p0: TemporalAmount) -> ChronoLocalDate: ...
    @overload
    def minus(self, p0: int, p1: TemporalUnit) -> ChronoLocalDate: ...
    @overload
    def minus(self, p0: int, p1: TemporalUnit) -> "HijrahDate": ...
    @overload
    def minus(self, p0: TemporalAmount) -> "HijrahDate": ...
    @overload
    def getChronology(self) -> Chronology: ...
    @overload
    def getChronology(self) -> HijrahChronology: ...
    def range(self, p0: TemporalField) -> ValueRange: ...

from typing import Any, ClassVar, overload
from java.time.format.TextStyle import TextStyle
from java.time.temporal.TemporalField import TemporalField
from java.time.temporal.ValueRange import ValueRange
from java.util.Locale import Locale

class HijrahEra:
    AH: ClassVar["HijrahEra"]
    AH: ClassVar["HijrahEra"]
    @staticmethod
    def values() -> Any: ...
    @staticmethod
    def valueOf(p0: str) -> "HijrahEra": ...
    def getValue(self) -> int: ...
    @staticmethod
    def of(p0: int) -> "HijrahEra": ...
    def getDisplayName(self, p0: TextStyle, p1: Locale) -> str: ...
    def range(self, p0: TemporalField) -> ValueRange: ...

from typing import Any, ClassVar, overload
from java.time.format.TextStyle import TextStyle
from java.util.Locale import Locale

class ThaiBuddhistEra:
    BEFORE_BE: ClassVar["ThaiBuddhistEra"]
    BE: ClassVar["ThaiBuddhistEra"]
    BEFORE_BE: ClassVar["ThaiBuddhistEra"]
    BE: ClassVar["ThaiBuddhistEra"]
    @staticmethod
    def values() -> Any: ...
    @staticmethod
    def valueOf(p0: str) -> "ThaiBuddhistEra": ...
    def getValue(self) -> int: ...
    @staticmethod
    def of(p0: int) -> "ThaiBuddhistEra": ...
    def getDisplayName(self, p0: TextStyle, p1: Locale) -> str: ...

from typing import Any, ClassVar, overload
from java.time.format.TextStyle import TextStyle
from java.time.temporal.Temporal import Temporal
from java.time.temporal.TemporalField import TemporalField
from java.time.temporal.TemporalQuery import TemporalQuery
from java.time.temporal.ValueRange import ValueRange
from java.util.Locale import Locale

class Era:
    def get(self, p0: TemporalField) -> int: ...
    def getLong(self, p0: TemporalField) -> int: ...
    def getValue(self) -> int: ...
    def isSupported(self, p0: TemporalField) -> bool: ...
    def getDisplayName(self, p0: TextStyle, p1: Locale) -> str: ...
    def adjustInto(self, p0: Temporal) -> Temporal: ...
    def query(self, p0: TemporalQuery) -> Any: ...
    def range(self, p0: TemporalField) -> ValueRange: ...

from typing import Any, ClassVar, overload
from java.time.Clock import Clock
from java.time.Instant import Instant
from java.time.LocalDate import LocalDate
from java.time.LocalDateTime import LocalDateTime
from java.time.Period import Period
from java.time.ZoneId import ZoneId
from java.time.ZoneOffset import ZoneOffset
from java.time.ZonedDateTime import ZonedDateTime
from java.time.chrono.ChronoLocalDate import ChronoLocalDate
from java.time.chrono.ChronoLocalDateTime import ChronoLocalDateTime
from java.time.chrono.ChronoPeriod import ChronoPeriod
from java.time.chrono.ChronoZonedDateTime import ChronoZonedDateTime
from java.time.chrono.Era import Era
from java.time.chrono.IsoEra import IsoEra
from java.time.format.ResolverStyle import ResolverStyle
from java.time.temporal.ChronoField import ChronoField
from java.time.temporal.TemporalAccessor import TemporalAccessor
from java.time.temporal.ValueRange import ValueRange

class IsoChronology:
    INSTANCE: ClassVar["IsoChronology"]
    def getId(self) -> str: ...
    def isLeapYear(self, p0: int) -> bool: ...
    @overload
    def eraOf(self, p0: int) -> IsoEra: ...
    @overload
    def eraOf(self, p0: int) -> Era: ...
    def epochSecond(self, p0: int, p1: int, p2: int, p3: int, p4: int, p5: int, p6: ZoneOffset) -> int: ...
    @overload
    def localDateTime(self, p0: TemporalAccessor) -> ChronoLocalDateTime: ...
    @overload
    def localDateTime(self, p0: TemporalAccessor) -> LocalDateTime: ...
    @overload
    def date(self, p0: Era, p1: int, p2: int, p3: int) -> LocalDate: ...
    @overload
    def date(self, p0: int, p1: int, p2: int) -> ChronoLocalDate: ...
    @overload
    def date(self, p0: int, p1: int, p2: int) -> LocalDate: ...
    @overload
    def date(self, p0: TemporalAccessor) -> ChronoLocalDate: ...
    @overload
    def date(self, p0: Era, p1: int, p2: int, p3: int) -> ChronoLocalDate: ...
    @overload
    def date(self, p0: TemporalAccessor) -> LocalDate: ...
    @overload
    def period(self, p0: int, p1: int, p2: int) -> Period: ...
    @overload
    def period(self, p0: int, p1: int, p2: int) -> ChronoPeriod: ...
    def eras(self) -> list: ...
    def prolepticYear(self, p0: Era, p1: int) -> int: ...
    @overload
    def dateYearDay(self, p0: Era, p1: int, p2: int) -> ChronoLocalDate: ...
    @overload
    def dateYearDay(self, p0: int, p1: int) -> ChronoLocalDate: ...
    @overload
    def dateYearDay(self, p0: Era, p1: int, p2: int) -> LocalDate: ...
    @overload
    def dateYearDay(self, p0: int, p1: int) -> LocalDate: ...
    @overload
    def dateNow(self) -> ChronoLocalDate: ...
    @overload
    def dateNow(self, p0: Clock) -> LocalDate: ...
    @overload
    def dateNow(self, p0: ZoneId) -> LocalDate: ...
    @overload
    def dateNow(self) -> LocalDate: ...
    @overload
    def dateNow(self, p0: ZoneId) -> ChronoLocalDate: ...
    @overload
    def dateNow(self, p0: Clock) -> ChronoLocalDate: ...
    @overload
    def dateEpochDay(self, p0: int) -> LocalDate: ...
    @overload
    def dateEpochDay(self, p0: int) -> ChronoLocalDate: ...
    @overload
    def resolveDate(self, p0: dict, p1: ResolverStyle) -> LocalDate: ...
    @overload
    def resolveDate(self, p0: dict, p1: ResolverStyle) -> ChronoLocalDate: ...
    def isIsoBased(self) -> bool: ...
    def getCalendarType(self) -> str: ...
    def range(self, p0: ChronoField) -> ValueRange: ...
    @overload
    def zonedDateTime(self, p0: TemporalAccessor) -> ChronoZonedDateTime: ...
    @overload
    def zonedDateTime(self, p0: TemporalAccessor) -> ZonedDateTime: ...
    @overload
    def zonedDateTime(self, p0: Instant, p1: ZoneId) -> ZonedDateTime: ...
    @overload
    def zonedDateTime(self, p0: Instant, p1: ZoneId) -> ChronoZonedDateTime: ...

