from typing import Any, ClassVar, overload
from java.time.format.TextStyle import TextStyle
from java.time.temporal.Temporal import Temporal
from java.time.temporal.TemporalAccessor import TemporalAccessor
from java.time.temporal.TemporalField import TemporalField
from java.time.temporal.TemporalQuery import TemporalQuery
from java.time.temporal.ValueRange import ValueRange
from java.util.Locale import Locale

class Month:
    JANUARY: ClassVar["Month"]
    FEBRUARY: ClassVar["Month"]
    MARCH: ClassVar["Month"]
    APRIL: ClassVar["Month"]
    MAY: ClassVar["Month"]
    JUNE: ClassVar["Month"]
    JULY: ClassVar["Month"]
    AUGUST: ClassVar["Month"]
    SEPTEMBER: ClassVar["Month"]
    OCTOBER: ClassVar["Month"]
    NOVEMBER: ClassVar["Month"]
    DECEMBER: ClassVar["Month"]
    JANUARY: ClassVar["Month"]
    FEBRUARY: ClassVar["Month"]
    MARCH: ClassVar["Month"]
    APRIL: ClassVar["Month"]
    MAY: ClassVar["Month"]
    JUNE: ClassVar["Month"]
    JULY: ClassVar["Month"]
    AUGUST: ClassVar["Month"]
    SEPTEMBER: ClassVar["Month"]
    OCTOBER: ClassVar["Month"]
    NOVEMBER: ClassVar["Month"]
    DECEMBER: ClassVar["Month"]
    def length(self, p0: bool) -> int: ...
    @staticmethod
    def values() -> Any: ...
    def getLong(self, p0: TemporalField) -> int: ...
    @staticmethod
    def valueOf(p0: str) -> "Month": ...
    @staticmethod
    def of(p0: int) -> "Month": ...
    def getValue(self) -> int: ...
    def get(self, p0: TemporalField) -> int: ...
    @staticmethod
    def from_(p0: TemporalAccessor) -> "Month": ...
    def isSupported(self, p0: TemporalField) -> bool: ...
    def query(self, p0: TemporalQuery) -> Any: ...
    def minLength(self) -> int: ...
    def plus(self, p0: int) -> "Month": ...
    def minus(self, p0: int) -> "Month": ...
    def firstDayOfYear(self, p0: bool) -> int: ...
    def adjustInto(self, p0: Temporal) -> Temporal: ...
    def range(self, p0: TemporalField) -> ValueRange: ...
    def getDisplayName(self, p0: TextStyle, p1: Locale) -> str: ...
    def firstMonthOfQuarter(self) -> "Month": ...
    def maxLength(self) -> int: ...
