from typing import Any, ClassVar, overload
from android.os.Parcel import Parcel

class MagnificationConfig:
    CREATOR: ClassVar[Any]
    MAGNIFICATION_MODE_DEFAULT: ClassVar[int]
    MAGNIFICATION_MODE_FULLSCREEN: ClassVar[int]
    MAGNIFICATION_MODE_WINDOW: ClassVar[int]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    def getCenterY(self) -> float: ...
    def getCenterX(self) -> float: ...
    def toString(self) -> str: ...
    def getMode(self) -> int: ...
    def isActivated(self) -> bool: ...
    def getScale(self) -> float: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
    def describeContents(self) -> int: ...

    class Builder:
        def __init__(self) -> None: ...
        def setCenterX(self, p0: float) -> Any: ...
        def setCenterY(self, p0: float) -> Any: ...
        def setMode(self, p0: int) -> Any: ...
        def setActivated(self, p0: bool) -> Any: ...
        def setScale(self, p0: float) -> Any: ...
        def build(self) -> "MagnificationConfig": ...
