from typing import Any, ClassVar, overload
from android.net.Uri import Uri
from android.os.Parcel import Parcel

class PdfPageLinkContent:
    CREATOR: ClassVar[Any]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    def __init__(self, p0: list, p1: Uri) -> None: ...
    def getBounds(self) -> list: ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
    def getUri(self) -> Uri: ...
