from typing import Any, ClassVar, overload

class UtteranceProgressListener:
    def __init__(self) -> None: ...
    def onDone(self, p0: str) -> None: ...
    @overload
    def onError(self, p0: str) -> None: ...
    @overload
    def onError(self, p0: str, p1: int) -> None: ...
    def onBeginSynthesis(self, p0: str, p1: int, p2: int, p3: int) -> None: ...
    def onAudioAvailable(self, p0: str, p1: Any) -> None: ...
    def onRangeStart(self, p0: str, p1: int, p2: int, p3: int) -> None: ...
    def onStop(self, p0: str, p1: bool) -> None: ...
    def onStart(self, p0: str) -> None: ...
