from typing import Any, ClassVar, overload

class RC5ParameterSpec:
    @overload
    def __init__(self, p0: int, p1: int, p2: int) -> None: ...
    @overload
    def __init__(self, p0: int, p1: int, p2: int, p3: Any, p4: int) -> None: ...
    @overload
    def __init__(self, p0: int, p1: int, p2: int, p3: Any) -> None: ...
    def getIV(self) -> Any: ...
    def getVersion(self) -> int: ...
    def getRounds(self) -> int: ...
    def getWordSize(self) -> int: ...
    def equals(self, p0: Any) -> bool: ...
    def hashCode(self) -> int: ...
