from typing import Any, ClassVar, overload

class Visualizer:
    ALREADY_EXISTS: ClassVar[int]
    ERROR: ClassVar[int]
    ERROR_BAD_VALUE: ClassVar[int]
    ERROR_DEAD_OBJECT: ClassVar[int]
    ERROR_INVALID_OPERATION: ClassVar[int]
    ERROR_NO_INIT: ClassVar[int]
    ERROR_NO_MEMORY: ClassVar[int]
    MEASUREMENT_MODE_NONE: ClassVar[int]
    MEASUREMENT_MODE_PEAK_RMS: ClassVar[int]
    SCALING_MODE_AS_PLAYED: ClassVar[int]
    SCALING_MODE_NORMALIZED: ClassVar[int]
    STATE_ENABLED: ClassVar[int]
    STATE_INITIALIZED: ClassVar[int]
    STATE_UNINITIALIZED: ClassVar[int]
    SUCCESS: ClassVar[int]
    def __init__(self, p0: int) -> None: ...
    def getEnabled(self) -> bool: ...
    def getFft(self, p0: Any) -> int: ...
    @staticmethod
    def getCaptureSizeRange() -> Any: ...
    @staticmethod
    def getMaxCaptureRate() -> int: ...
    def setCaptureSize(self, p0: int) -> int: ...
    def getCaptureSize(self) -> int: ...
    def setScalingMode(self, p0: int) -> int: ...
    def getScalingMode(self) -> int: ...
    def setMeasurementMode(self, p0: int) -> int: ...
    def getMeasurementMode(self) -> int: ...
    def getSamplingRate(self) -> int: ...
    def getWaveForm(self, p0: Any) -> int: ...
    def getMeasurementPeakRms(self, p0: Any) -> int: ...
    def setDataCaptureListener(self, p0: Any, p1: int, p2: bool, p3: bool) -> int: ...
    def release(self) -> None: ...
    def setEnabled(self, p0: bool) -> int: ...

    class OnDataCaptureListener:
        def onWaveFormDataCapture(self, p0: "Visualizer", p1: Any, p2: int) -> None: ...
        def onFftDataCapture(self, p0: "Visualizer", p1: Any, p2: int) -> None: ...

    class MeasurementPeakRms:
        mPeak: int
        mRms: int
        def __init__(self) -> None: ...
