from typing import Any, ClassVar, overload
from java.util.DoubleSummaryStatistics import DoubleSummaryStatistics
from java.util.Iterator import Iterator
from java.util.OptionalDouble import OptionalDouble
from java.util.Spliterator import Spliterator
from java.util.function.BiConsumer import BiConsumer
from java.util.function.DoubleBinaryOperator import DoubleBinaryOperator
from java.util.function.DoubleConsumer import DoubleConsumer
from java.util.function.DoubleFunction import DoubleFunction
from java.util.function.DoublePredicate import DoublePredicate
from java.util.function.DoubleSupplier import DoubleSupplier
from java.util.function.DoubleToIntFunction import DoubleToIntFunction
from java.util.function.DoubleToLongFunction import DoubleToLongFunction
from java.util.function.DoubleUnaryOperator import DoubleUnaryOperator
from java.util.function.ObjDoubleConsumer import ObjDoubleConsumer
from java.util.function.Supplier import Supplier
from java.util.stream.BaseStream import BaseStream
from java.util.stream.IntStream import IntStream
from java.util.stream.LongStream import LongStream
from java.util.stream.Stream import Stream

class DoubleStream:
    def min(self) -> OptionalDouble: ...
    def max(self) -> OptionalDouble: ...
    @overload
    @staticmethod
    def of(p0: float) -> "DoubleStream": ...
    @overload
    @staticmethod
    def of(p0: Any) -> "DoubleStream": ...
    def toArray(self) -> Any: ...
    @overload
    def iterator(self) -> Iterator: ...
    @overload
    def iterator(self) -> Any: ...
    def map(self, p0: DoubleUnaryOperator) -> "DoubleStream": ...
    def collect(self, p0: Supplier, p1: ObjDoubleConsumer, p2: BiConsumer) -> Any: ...
    def count(self) -> int: ...
    @staticmethod
    def builder() -> Any: ...
    @staticmethod
    def concat(p0: "DoubleStream", p1: "DoubleStream") -> "DoubleStream": ...
    def limit(self, p0: int) -> "DoubleStream": ...
    @overload
    def spliterator(self) -> Spliterator: ...
    @overload
    def spliterator(self) -> Any: ...
    def filter(self, p0: DoublePredicate) -> "DoubleStream": ...
    @staticmethod
    def empty() -> "DoubleStream": ...
    def anyMatch(self, p0: DoublePredicate) -> bool: ...
    def forEach(self, p0: DoubleConsumer) -> None: ...
    def findAny(self) -> OptionalDouble: ...
    def skip(self, p0: int) -> "DoubleStream": ...
    def peek(self, p0: DoubleConsumer) -> "DoubleStream": ...
    @overload
    @staticmethod
    def iterate(p0: float, p1: DoubleUnaryOperator) -> "DoubleStream": ...
    @overload
    @staticmethod
    def iterate(p0: float, p1: DoublePredicate, p2: DoubleUnaryOperator) -> "DoubleStream": ...
    def flatMap(self, p0: DoubleFunction) -> "DoubleStream": ...
    def allMatch(self, p0: DoublePredicate) -> bool: ...
    def dropWhile(self, p0: DoublePredicate) -> "DoubleStream": ...
    @overload
    def parallel(self) -> BaseStream: ...
    @overload
    def parallel(self) -> "DoubleStream": ...
    def mapToInt(self, p0: DoubleToIntFunction) -> IntStream: ...
    def mapToLong(self, p0: DoubleToLongFunction) -> LongStream: ...
    def mapMulti(self, p0: Any) -> "DoubleStream": ...
    def takeWhile(self, p0: DoublePredicate) -> "DoubleStream": ...
    def forEachOrdered(self, p0: DoubleConsumer) -> None: ...
    @overload
    def sequential(self) -> "DoubleStream": ...
    @overload
    def sequential(self) -> BaseStream: ...
    def average(self) -> OptionalDouble: ...
    def summaryStatistics(self) -> DoubleSummaryStatistics: ...
    def boxed(self) -> Stream: ...
    def distinct(self) -> "DoubleStream": ...
    def findFirst(self) -> OptionalDouble: ...
    def noneMatch(self, p0: DoublePredicate) -> bool: ...
    def sum(self) -> float: ...
    @overload
    def reduce(self, p0: DoubleBinaryOperator) -> OptionalDouble: ...
    @overload
    def reduce(self, p0: float, p1: DoubleBinaryOperator) -> float: ...
    def mapToObj(self, p0: DoubleFunction) -> Stream: ...
    def sorted(self) -> "DoubleStream": ...
    @staticmethod
    def generate(p0: DoubleSupplier) -> "DoubleStream": ...

    class DoubleMapMultiConsumer:
        def accept(self, p0: float, p1: DoubleConsumer) -> None: ...

    class Builder:
        def add(self, p0: float) -> Any: ...
        def accept(self, p0: float) -> None: ...
        def build(self) -> "DoubleStream": ...
