from typing import Any, ClassVar, overload
from javax.security.auth.Subject import Subject
from javax.security.auth.callback.CallbackHandler import CallbackHandler

class AuthProvider:
    def logout(self) -> None: ...
    def setCallbackHandler(self, p0: CallbackHandler) -> None: ...
    def login(self, p0: Subject, p1: CallbackHandler) -> None: ...
