from typing import Any, ClassVar, overload
from java.security.KeyPair import KeyPair
from java.security.SecureRandom import SecureRandom
from java.security.spec.AlgorithmParameterSpec import AlgorithmParameterSpec

class KeyPairGeneratorSpi:
    def __init__(self) -> None: ...
    def generateKeyPair(self) -> KeyPair: ...
    @overload
    def initialize(self, p0: int, p1: SecureRandom) -> None: ...
    @overload
    def initialize(self, p0: AlgorithmParameterSpec, p1: SecureRandom) -> None: ...
