from typing import Any, ClassVar, overload
from java.security.PrivateKey import PrivateKey
from java.security.PublicKey import PublicKey

class KeyPair:
    def __init__(self, p0: PublicKey, p1: PrivateKey) -> None: ...
    def getPublic(self) -> PublicKey: ...
    def getPrivate(self) -> PrivateKey: ...
