from typing import Any, ClassVar, overload
from java.security.Permission import Permission
from java.util.Enumeration import Enumeration
from java.util.stream.Stream import Stream

class PermissionCollection:
    def __init__(self) -> None: ...
    def toString(self) -> str: ...
    def add(self, p0: Permission) -> None: ...
    def elements(self) -> Enumeration: ...
    def setReadOnly(self) -> None: ...
    def implies(self, p0: Permission) -> bool: ...
    def isReadOnly(self) -> bool: ...
    def elementsAsStream(self) -> Stream: ...
