from typing import Any, ClassVar, overload
from java.net.URI import URI

class CookieHandler:
    def __init__(self) -> None: ...
    def put(self, p0: URI, p1: dict) -> None: ...
    def get(self, p0: URI, p1: dict) -> dict: ...
    @staticmethod
    def getDefault() -> "CookieHandler": ...
    @staticmethod
    def setDefault(p0: "CookieHandler") -> None: ...
