from typing import Any, ClassVar, overload

class HttpRetryException:
    @overload
    def __init__(self, p0: str, p1: int) -> None: ...
    @overload
    def __init__(self, p0: str, p1: int, p2: str) -> None: ...
    def getLocation(self) -> str: ...
    def responseCode(self) -> int: ...
    def getReason(self) -> str: ...
