from typing import Any, ClassVar, overload
from java.net.NetworkInterface import NetworkInterface

class InetAddress:
    @staticmethod
    def getAllByName(p0: str) -> Any: ...
    def equals(self, p0: Any) -> bool: ...
    def toString(self) -> str: ...
    def hashCode(self) -> int: ...
    def getAddress(self) -> Any: ...
    @staticmethod
    def getByName(p0: str) -> "InetAddress": ...
    def getHostAddress(self) -> str: ...
    def getHostName(self) -> str: ...
    @overload
    def isReachable(self, p0: NetworkInterface, p1: int, p2: int) -> bool: ...
    @overload
    def isReachable(self, p0: int) -> bool: ...
    @staticmethod
    def ofLiteral(p0: str) -> "InetAddress": ...
    @overload
    @staticmethod
    def getByAddress(p0: str, p1: Any) -> "InetAddress": ...
    @overload
    @staticmethod
    def getByAddress(p0: Any) -> "InetAddress": ...
    def isMulticastAddress(self) -> bool: ...
    def isAnyLocalAddress(self) -> bool: ...
    def isLoopbackAddress(self) -> bool: ...
    def isSiteLocalAddress(self) -> bool: ...
    def isMCGlobal(self) -> bool: ...
    def isMCNodeLocal(self) -> bool: ...
    def isMCLinkLocal(self) -> bool: ...
    def isMCSiteLocal(self) -> bool: ...
    def isMCOrgLocal(self) -> bool: ...
    def getCanonicalHostName(self) -> str: ...
    @staticmethod
    def getLoopbackAddress() -> "InetAddress": ...
    @staticmethod
    def getLocalHost() -> "InetAddress": ...
    def isLinkLocalAddress(self) -> bool: ...
