from typing import Any, ClassVar, overload
from java.net.URL import URL
from java.util.jar.Attributes import Attributes
from java.util.jar.JarEntry import JarEntry
from java.util.jar.JarFile import JarFile
from java.util.jar.Manifest import Manifest

class JarURLConnection:
    def getCertificates(self) -> Any: ...
    def getMainAttributes(self) -> Attributes: ...
    def getAttributes(self) -> Attributes: ...
    def getManifest(self) -> Manifest: ...
    def getJarFileURL(self) -> URL: ...
    def getJarEntry(self) -> JarEntry: ...
    def getEntryName(self) -> str: ...
    def getJarFile(self) -> JarFile: ...
