from typing import Any, ClassVar, overload
from java.net.InetAddress import InetAddress
from java.net.NetworkInterface import NetworkInterface
from java.net.SocketAddress import SocketAddress

class MulticastSocket:
    @overload
    def __init__(self, p0: SocketAddress) -> None: ...
    @overload
    def __init__(self, p0: int) -> None: ...
    @overload
    def __init__(self) -> None: ...
    def setInterface(self, p0: InetAddress) -> None: ...
    def setTimeToLive(self, p0: int) -> None: ...
    def getInterface(self) -> InetAddress: ...
    def setNetworkInterface(self, p0: NetworkInterface) -> None: ...
    def getNetworkInterface(self) -> NetworkInterface: ...
    def setLoopbackMode(self, p0: bool) -> None: ...
    def getLoopbackMode(self) -> bool: ...
    def getTimeToLive(self) -> int: ...
    @overload
    def joinGroup(self, p0: SocketAddress, p1: NetworkInterface) -> None: ...
    @overload
    def joinGroup(self, p0: InetAddress) -> None: ...
    @overload
    def leaveGroup(self, p0: InetAddress) -> None: ...
    @overload
    def leaveGroup(self, p0: SocketAddress, p1: NetworkInterface) -> None: ...
