from typing import Any, ClassVar, overload
from java.io.InputStream import InputStream
from java.lang.ClassLoader import ClassLoader
from java.net.URL import URL
from java.net.URLStreamHandlerFactory import URLStreamHandlerFactory
from java.util.Enumeration import Enumeration

class URLClassLoader:
    @overload
    def __init__(self, p0: str, p1: Any, p2: ClassLoader, p3: URLStreamHandlerFactory) -> None: ...
    @overload
    def __init__(self, p0: str, p1: Any, p2: ClassLoader) -> None: ...
    @overload
    def __init__(self, p0: Any, p1: ClassLoader, p2: URLStreamHandlerFactory) -> None: ...
    @overload
    def __init__(self, p0: Any) -> None: ...
    @overload
    def __init__(self, p0: Any, p1: ClassLoader) -> None: ...
    @overload
    @staticmethod
    def newInstance(p0: Any, p1: ClassLoader) -> "URLClassLoader": ...
    @overload
    @staticmethod
    def newInstance(p0: Any) -> "URLClassLoader": ...
    def findResource(self, p0: str) -> URL: ...
    def getResourceAsStream(self, p0: str) -> InputStream: ...
    def close(self) -> None: ...
    def findResources(self, p0: str) -> Enumeration: ...
    def getURLs(self) -> Any: ...
