from typing import Any, ClassVar, overload
from android.graphics.text.MeasuredText import MeasuredText

class LineBreaker:
    BREAK_STRATEGY_BALANCED: ClassVar[int]
    BREAK_STRATEGY_HIGH_QUALITY: ClassVar[int]
    BREAK_STRATEGY_SIMPLE: ClassVar[int]
    HYPHENATION_FREQUENCY_FULL: ClassVar[int]
    HYPHENATION_FREQUENCY_NONE: ClassVar[int]
    HYPHENATION_FREQUENCY_NORMAL: ClassVar[int]
    JUSTIFICATION_MODE_INTER_CHARACTER: ClassVar[int]
    JUSTIFICATION_MODE_INTER_WORD: ClassVar[int]
    JUSTIFICATION_MODE_NONE: ClassVar[int]
    def computeLineBreaks(self, p0: MeasuredText, p1: Any, p2: int) -> Any: ...

    class Result:
        def getEndLineHyphenEdit(self, p0: int) -> int: ...
        def getLineBreakOffset(self, p0: int) -> int: ...
        def getStartLineHyphenEdit(self, p0: int) -> int: ...
        def hasLineTab(self, p0: int) -> bool: ...
        def getLineCount(self) -> int: ...
        def getLineAscent(self, p0: int) -> float: ...
        def getLineDescent(self, p0: int) -> float: ...
        def getLineWidth(self, p0: int) -> float: ...

    class ParagraphConstraints:
        def __init__(self) -> None: ...
        def getFirstWidth(self) -> float: ...
        def getTabStops(self) -> Any: ...
        def getFirstWidthLineCount(self) -> int: ...
        def setTabStops(self, p0: Any, p1: float) -> None: ...
        def getDefaultTabStop(self) -> float: ...
        def getWidth(self) -> float: ...
        def setIndent(self, p0: float, p1: int) -> None: ...
        def setWidth(self, p0: float) -> None: ...

    class Builder:
        def __init__(self) -> None: ...
        def setIndents(self, p0: Any) -> Any: ...
        def build(self) -> "LineBreaker": ...
        def setBreakStrategy(self, p0: int) -> Any: ...
        def setHyphenationFrequency(self, p0: int) -> Any: ...
        def setJustificationMode(self, p0: int) -> Any: ...
        def setUseBoundsForWidth(self, p0: bool) -> Any: ...
