from typing import Any, ClassVar, overload
from android.graphics.pdf.models.selection.SelectionBoundary import SelectionBoundary
from android.os.Parcel import Parcel

class PageSelection:
    CREATOR: ClassVar[Any]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    def __init__(self, p0: int, p1: SelectionBoundary, p2: SelectionBoundary, p3: list) -> None: ...
    def getPage(self) -> int: ...
    def getSelectedTextContents(self) -> list: ...
    def getStop(self) -> SelectionBoundary: ...
    def getStart(self) -> SelectionBoundary: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
    def describeContents(self) -> int: ...
