from typing import Any, ClassVar, overload
from android.os.Parcel import Parcel

class DownloadableSubscription:
    CREATOR: ClassVar[Any]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    def getEncodedActivationCode(self) -> str: ...
    def getConfirmationCode(self) -> str: ...
    @staticmethod
    def forActivationCode(p0: str) -> "DownloadableSubscription": ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...

    class Builder:
        @overload
        def __init__(self, p0: str) -> None: ...
        @overload
        def __init__(self, p0: "DownloadableSubscription") -> None: ...
        def setConfirmationCode(self, p0: str) -> Any: ...
        def setEncodedActivationCode(self, p0: str) -> Any: ...
        def build(self) -> "DownloadableSubscription": ...
