from typing import Any, ClassVar, overload

class RecordIdFilter:
    @staticmethod
    def fromId(p0: type, p1: str) -> "RecordIdFilter": ...
    @staticmethod
    def fromClientRecordId(p0: type, p1: str) -> "RecordIdFilter": ...
    def getRecordType(self) -> type: ...
    def getClientRecordId(self) -> str: ...
    def getId(self) -> str: ...
