from typing import Any, ClassVar, overload
from android.health.connect.datatypes.FhirVersion import FhirVersion
from android.os.Parcel import Parcel

class UpsertMedicalResourceRequest:
    CREATOR: ClassVar[Any]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    def equals(self, p0: Any) -> bool: ...
    def toString(self) -> str: ...
    def hashCode(self) -> int: ...
    def getDataSourceId(self) -> str: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
    def describeContents(self) -> int: ...
    def getFhirVersion(self) -> FhirVersion: ...
    def getData(self) -> str: ...

    class Builder:
        @overload
        def __init__(self, p0: str, p1: FhirVersion, p2: str) -> None: ...
        @overload
        def __init__(self, p0: Any) -> None: ...
        @overload
        def __init__(self, p0: "UpsertMedicalResourceRequest") -> None: ...
        def setDataSourceId(self, p0: str) -> Any: ...
        def build(self) -> "UpsertMedicalResourceRequest": ...
        def setData(self, p0: str) -> Any: ...
        def setFhirVersion(self, p0: FhirVersion) -> Any: ...
