# cython: language_level=3
# Generated by pyjnius-wrap cython — do not edit by hand.

from jni_core._core cimport (
    JavaObject, get_env, check_jni_exc,
    find_class_global, get_method_id, get_static_method_id,
    get_field_id, get_static_field_id, j_str, py_str,
)
from jni_core._dispatch cimport (
    jnicore_NewObjectA, jnicore_DeleteLocalRef,
    jnicore_CallVoidMethodA, jnicore_CallObjectMethodA,
    jnicore_CallBooleanMethodA, jnicore_CallByteMethodA,
    jnicore_CallCharMethodA, jnicore_CallShortMethodA,
    jnicore_CallIntMethodA, jnicore_CallLongMethodA,
    jnicore_CallFloatMethodA, jnicore_CallDoubleMethodA,
    jnicore_CallStaticVoidMethodA, jnicore_CallStaticObjectMethodA,
    jnicore_CallStaticBooleanMethodA, jnicore_CallStaticByteMethodA,
    jnicore_CallStaticCharMethodA, jnicore_CallStaticShortMethodA,
    jnicore_CallStaticIntMethodA, jnicore_CallStaticLongMethodA,
    jnicore_CallStaticFloatMethodA, jnicore_CallStaticDoubleMethodA,
    jnicore_GetObjectField, jnicore_SetObjectField,
    jnicore_GetBooleanField, jnicore_SetBooleanField,
    jnicore_GetByteField, jnicore_SetByteField,
    jnicore_GetCharField, jnicore_SetCharField,
    jnicore_GetShortField, jnicore_SetShortField,
    jnicore_GetIntField, jnicore_SetIntField,
    jnicore_GetLongField, jnicore_SetLongField,
    jnicore_GetFloatField, jnicore_SetFloatField,
    jnicore_GetDoubleField, jnicore_SetDoubleField,
    jnicore_GetStaticObjectField, jnicore_SetStaticObjectField,
    jnicore_GetStaticBooleanField, jnicore_SetStaticBooleanField,
    jnicore_GetStaticByteField, jnicore_SetStaticByteField,
    jnicore_GetStaticCharField, jnicore_SetStaticCharField,
    jnicore_GetStaticShortField, jnicore_SetStaticShortField,
    jnicore_GetStaticIntField, jnicore_SetStaticIntField,
    jnicore_GetStaticLongField, jnicore_SetStaticLongField,
    jnicore_GetStaticFloatField, jnicore_SetStaticFloatField,
    jnicore_GetStaticDoubleField, jnicore_SetStaticDoubleField,
)
from jni_core.jni cimport (
    jclass, jobject, jmethodID, jfieldID, jvalue, JNIEnv,
    jboolean, jbyte, jchar, jshort, jint, jlong, jfloat, jdouble, jstring,
)

include "jni_core/conversions.pxi"

__javaclass__ = "android/telephony/emergency/EmergencyNumber"  # android.telephony.emergency.EmergencyNumber

cdef jclass _cls_EmergencyNumber = NULL
cdef jmethodID _m_getCountryIso_0 = NULL
cdef jmethodID _m_getEmergencyUrns_0 = NULL
cdef jmethodID _m_isFromSources_0 = NULL
cdef jmethodID _m_getEmergencyServiceCategories_0 = NULL
cdef jmethodID _m_isInEmergencyServiceCategories_0 = NULL
cdef jmethodID _m_getEmergencyNumberSources_0 = NULL
cdef jmethodID _m_getEmergencyCallRouting_0 = NULL
cdef jmethodID _m_getMnc_0 = NULL
cdef jmethodID _m_describeContents_0 = NULL
cdef jmethodID _m_writeToParcel_0 = NULL
cdef jmethodID _m_getNumber_0 = NULL
cdef jmethodID _m_equals_0 = NULL
cdef jmethodID _m_toString_0 = NULL
cdef jmethodID _m_hashCode_0 = NULL
cdef jmethodID _m_compareTo_0 = NULL
cdef jmethodID _m_compareTo_1 = NULL
cdef jfieldID _sf_CREATOR = NULL
cdef jfieldID _sf_EMERGENCY_CALL_ROUTING_EMERGENCY = NULL
cdef jfieldID _sf_EMERGENCY_CALL_ROUTING_NORMAL = NULL
cdef jfieldID _sf_EMERGENCY_CALL_ROUTING_UNKNOWN = NULL
cdef jfieldID _sf_EMERGENCY_NUMBER_SOURCE_DATABASE = NULL
cdef jfieldID _sf_EMERGENCY_NUMBER_SOURCE_DEFAULT = NULL
cdef jfieldID _sf_EMERGENCY_NUMBER_SOURCE_MODEM_CONFIG = NULL
cdef jfieldID _sf_EMERGENCY_NUMBER_SOURCE_NETWORK_SIGNALING = NULL
cdef jfieldID _sf_EMERGENCY_NUMBER_SOURCE_SIM = NULL
cdef jfieldID _sf_EMERGENCY_SERVICE_CATEGORY_AIEC = NULL
cdef jfieldID _sf_EMERGENCY_SERVICE_CATEGORY_AMBULANCE = NULL
cdef jfieldID _sf_EMERGENCY_SERVICE_CATEGORY_FIRE_BRIGADE = NULL
cdef jfieldID _sf_EMERGENCY_SERVICE_CATEGORY_MARINE_GUARD = NULL
cdef jfieldID _sf_EMERGENCY_SERVICE_CATEGORY_MIEC = NULL
cdef jfieldID _sf_EMERGENCY_SERVICE_CATEGORY_MOUNTAIN_RESCUE = NULL
cdef jfieldID _sf_EMERGENCY_SERVICE_CATEGORY_POLICE = NULL
cdef jfieldID _sf_EMERGENCY_SERVICE_CATEGORY_UNSPECIFIED = NULL
cdef jfieldID _sf_CONTENTS_FILE_DESCRIPTOR = NULL
cdef jfieldID _sf_PARCELABLE_WRITE_RETURN_VALUE = NULL

cdef int _ensure_ids_EmergencyNumber(JNIEnv* env) except -1:
    global _cls_EmergencyNumber, _m_getCountryIso_0, _m_getEmergencyUrns_0, _m_isFromSources_0, _m_getEmergencyServiceCategories_0, _m_isInEmergencyServiceCategories_0, _m_getEmergencyNumberSources_0, _m_getEmergencyCallRouting_0, _m_getMnc_0, _m_describeContents_0, _m_writeToParcel_0, _m_getNumber_0, _m_equals_0, _m_toString_0, _m_hashCode_0, _m_compareTo_0, _m_compareTo_1, _sf_CREATOR, _sf_EMERGENCY_CALL_ROUTING_EMERGENCY, _sf_EMERGENCY_CALL_ROUTING_NORMAL, _sf_EMERGENCY_CALL_ROUTING_UNKNOWN, _sf_EMERGENCY_NUMBER_SOURCE_DATABASE, _sf_EMERGENCY_NUMBER_SOURCE_DEFAULT, _sf_EMERGENCY_NUMBER_SOURCE_MODEM_CONFIG, _sf_EMERGENCY_NUMBER_SOURCE_NETWORK_SIGNALING, _sf_EMERGENCY_NUMBER_SOURCE_SIM, _sf_EMERGENCY_SERVICE_CATEGORY_AIEC, _sf_EMERGENCY_SERVICE_CATEGORY_AMBULANCE, _sf_EMERGENCY_SERVICE_CATEGORY_FIRE_BRIGADE, _sf_EMERGENCY_SERVICE_CATEGORY_MARINE_GUARD, _sf_EMERGENCY_SERVICE_CATEGORY_MIEC, _sf_EMERGENCY_SERVICE_CATEGORY_MOUNTAIN_RESCUE, _sf_EMERGENCY_SERVICE_CATEGORY_POLICE, _sf_EMERGENCY_SERVICE_CATEGORY_UNSPECIFIED, _sf_CONTENTS_FILE_DESCRIPTOR, _sf_PARCELABLE_WRITE_RETURN_VALUE
    if _cls_EmergencyNumber != NULL:
        return 0
    _cls_EmergencyNumber = find_class_global(env, b"android/telephony/emergency/EmergencyNumber")
    _m_getCountryIso_0 = get_method_id(env, _cls_EmergencyNumber, b"getCountryIso", b"()Ljava/lang/String;")
    _m_getEmergencyUrns_0 = get_method_id(env, _cls_EmergencyNumber, b"getEmergencyUrns", b"()Ljava/util/List;")
    _m_isFromSources_0 = get_method_id(env, _cls_EmergencyNumber, b"isFromSources", b"(I)Z")
    _m_getEmergencyServiceCategories_0 = get_method_id(env, _cls_EmergencyNumber, b"getEmergencyServiceCategories", b"()Ljava/util/List;")
    _m_isInEmergencyServiceCategories_0 = get_method_id(env, _cls_EmergencyNumber, b"isInEmergencyServiceCategories", b"(I)Z")
    _m_getEmergencyNumberSources_0 = get_method_id(env, _cls_EmergencyNumber, b"getEmergencyNumberSources", b"()Ljava/util/List;")
    _m_getEmergencyCallRouting_0 = get_method_id(env, _cls_EmergencyNumber, b"getEmergencyCallRouting", b"()I")
    _m_getMnc_0 = get_method_id(env, _cls_EmergencyNumber, b"getMnc", b"()Ljava/lang/String;")
    _m_describeContents_0 = get_method_id(env, _cls_EmergencyNumber, b"describeContents", b"()I")
    _m_writeToParcel_0 = get_method_id(env, _cls_EmergencyNumber, b"writeToParcel", b"(Landroid/os/Parcel;I)V")
    _m_getNumber_0 = get_method_id(env, _cls_EmergencyNumber, b"getNumber", b"()Ljava/lang/String;")
    _m_equals_0 = get_method_id(env, _cls_EmergencyNumber, b"equals", b"(Ljava/lang/Object;)Z")
    _m_toString_0 = get_method_id(env, _cls_EmergencyNumber, b"toString", b"()Ljava/lang/String;")
    _m_hashCode_0 = get_method_id(env, _cls_EmergencyNumber, b"hashCode", b"()I")
    _m_compareTo_0 = get_method_id(env, _cls_EmergencyNumber, b"compareTo", b"(Ljava/lang/Object;)I")
    _m_compareTo_1 = get_method_id(env, _cls_EmergencyNumber, b"compareTo", b"(Landroid/telephony/emergency/EmergencyNumber;)I")
    _sf_CREATOR = get_static_field_id(env, _cls_EmergencyNumber, b"CREATOR", b"Landroid/os/Parcelable$Creator;")
    _sf_EMERGENCY_CALL_ROUTING_EMERGENCY = get_static_field_id(env, _cls_EmergencyNumber, b"EMERGENCY_CALL_ROUTING_EMERGENCY", b"I")
    _sf_EMERGENCY_CALL_ROUTING_NORMAL = get_static_field_id(env, _cls_EmergencyNumber, b"EMERGENCY_CALL_ROUTING_NORMAL", b"I")
    _sf_EMERGENCY_CALL_ROUTING_UNKNOWN = get_static_field_id(env, _cls_EmergencyNumber, b"EMERGENCY_CALL_ROUTING_UNKNOWN", b"I")
    _sf_EMERGENCY_NUMBER_SOURCE_DATABASE = get_static_field_id(env, _cls_EmergencyNumber, b"EMERGENCY_NUMBER_SOURCE_DATABASE", b"I")
    _sf_EMERGENCY_NUMBER_SOURCE_DEFAULT = get_static_field_id(env, _cls_EmergencyNumber, b"EMERGENCY_NUMBER_SOURCE_DEFAULT", b"I")
    _sf_EMERGENCY_NUMBER_SOURCE_MODEM_CONFIG = get_static_field_id(env, _cls_EmergencyNumber, b"EMERGENCY_NUMBER_SOURCE_MODEM_CONFIG", b"I")
    _sf_EMERGENCY_NUMBER_SOURCE_NETWORK_SIGNALING = get_static_field_id(env, _cls_EmergencyNumber, b"EMERGENCY_NUMBER_SOURCE_NETWORK_SIGNALING", b"I")
    _sf_EMERGENCY_NUMBER_SOURCE_SIM = get_static_field_id(env, _cls_EmergencyNumber, b"EMERGENCY_NUMBER_SOURCE_SIM", b"I")
    _sf_EMERGENCY_SERVICE_CATEGORY_AIEC = get_static_field_id(env, _cls_EmergencyNumber, b"EMERGENCY_SERVICE_CATEGORY_AIEC", b"I")
    _sf_EMERGENCY_SERVICE_CATEGORY_AMBULANCE = get_static_field_id(env, _cls_EmergencyNumber, b"EMERGENCY_SERVICE_CATEGORY_AMBULANCE", b"I")
    _sf_EMERGENCY_SERVICE_CATEGORY_FIRE_BRIGADE = get_static_field_id(env, _cls_EmergencyNumber, b"EMERGENCY_SERVICE_CATEGORY_FIRE_BRIGADE", b"I")
    _sf_EMERGENCY_SERVICE_CATEGORY_MARINE_GUARD = get_static_field_id(env, _cls_EmergencyNumber, b"EMERGENCY_SERVICE_CATEGORY_MARINE_GUARD", b"I")
    _sf_EMERGENCY_SERVICE_CATEGORY_MIEC = get_static_field_id(env, _cls_EmergencyNumber, b"EMERGENCY_SERVICE_CATEGORY_MIEC", b"I")
    _sf_EMERGENCY_SERVICE_CATEGORY_MOUNTAIN_RESCUE = get_static_field_id(env, _cls_EmergencyNumber, b"EMERGENCY_SERVICE_CATEGORY_MOUNTAIN_RESCUE", b"I")
    _sf_EMERGENCY_SERVICE_CATEGORY_POLICE = get_static_field_id(env, _cls_EmergencyNumber, b"EMERGENCY_SERVICE_CATEGORY_POLICE", b"I")
    _sf_EMERGENCY_SERVICE_CATEGORY_UNSPECIFIED = get_static_field_id(env, _cls_EmergencyNumber, b"EMERGENCY_SERVICE_CATEGORY_UNSPECIFIED", b"I")
    _sf_CONTENTS_FILE_DESCRIPTOR = get_static_field_id(env, _cls_EmergencyNumber, b"CONTENTS_FILE_DESCRIPTOR", b"I")
    _sf_PARCELABLE_WRITE_RETURN_VALUE = get_static_field_id(env, _cls_EmergencyNumber, b"PARCELABLE_WRITE_RETURN_VALUE", b"I")
    return 0

cdef class EmergencyNumber(JavaObject):
    """android.telephony.emergency.EmergencyNumber"""

    def __init__(self, *args, **kwargs):
        raise TypeError("EmergencyNumber has no public constructor")

    # Static field EmergencyNumber.CREATOR
    @staticmethod
    def CREATOR() -> object:
        cdef JNIEnv* env = get_env()
        _ensure_ids_EmergencyNumber(env)
        cdef jobject _ret = jnicore_GetStaticObjectField(env, _cls_EmergencyNumber, _sf_CREATOR)
        check_jni_exc(env)
        if _ret == NULL:
            return None
        cdef JavaObject _wrapped = JavaObject.__new__(JavaObject)
        _wrapped._adopt_local(env, _ret)
        return _wrapped

    # Static field EmergencyNumber.EMERGENCY_CALL_ROUTING_EMERGENCY
    @staticmethod
    def EMERGENCY_CALL_ROUTING_EMERGENCY() -> int:
        cdef JNIEnv* env = get_env()
        _ensure_ids_EmergencyNumber(env)
        cdef jint _ret = jnicore_GetStaticIntField(env, _cls_EmergencyNumber, _sf_EMERGENCY_CALL_ROUTING_EMERGENCY)
        check_jni_exc(env)
        return <int>_ret

    # Static field EmergencyNumber.EMERGENCY_CALL_ROUTING_NORMAL
    @staticmethod
    def EMERGENCY_CALL_ROUTING_NORMAL() -> int:
        cdef JNIEnv* env = get_env()
        _ensure_ids_EmergencyNumber(env)
        cdef jint _ret = jnicore_GetStaticIntField(env, _cls_EmergencyNumber, _sf_EMERGENCY_CALL_ROUTING_NORMAL)
        check_jni_exc(env)
        return <int>_ret

    # Static field EmergencyNumber.EMERGENCY_CALL_ROUTING_UNKNOWN
    @staticmethod
    def EMERGENCY_CALL_ROUTING_UNKNOWN() -> int:
        cdef JNIEnv* env = get_env()
        _ensure_ids_EmergencyNumber(env)
        cdef jint _ret = jnicore_GetStaticIntField(env, _cls_EmergencyNumber, _sf_EMERGENCY_CALL_ROUTING_UNKNOWN)
        check_jni_exc(env)
        return <int>_ret

    # Static field EmergencyNumber.EMERGENCY_NUMBER_SOURCE_DATABASE
    @staticmethod
    def EMERGENCY_NUMBER_SOURCE_DATABASE() -> int:
        cdef JNIEnv* env = get_env()
        _ensure_ids_EmergencyNumber(env)
        cdef jint _ret = jnicore_GetStaticIntField(env, _cls_EmergencyNumber, _sf_EMERGENCY_NUMBER_SOURCE_DATABASE)
        check_jni_exc(env)
        return <int>_ret

    # Static field EmergencyNumber.EMERGENCY_NUMBER_SOURCE_DEFAULT
    @staticmethod
    def EMERGENCY_NUMBER_SOURCE_DEFAULT() -> int:
        cdef JNIEnv* env = get_env()
        _ensure_ids_EmergencyNumber(env)
        cdef jint _ret = jnicore_GetStaticIntField(env, _cls_EmergencyNumber, _sf_EMERGENCY_NUMBER_SOURCE_DEFAULT)
        check_jni_exc(env)
        return <int>_ret

    # Static field EmergencyNumber.EMERGENCY_NUMBER_SOURCE_MODEM_CONFIG
    @staticmethod
    def EMERGENCY_NUMBER_SOURCE_MODEM_CONFIG() -> int:
        cdef JNIEnv* env = get_env()
        _ensure_ids_EmergencyNumber(env)
        cdef jint _ret = jnicore_GetStaticIntField(env, _cls_EmergencyNumber, _sf_EMERGENCY_NUMBER_SOURCE_MODEM_CONFIG)
        check_jni_exc(env)
        return <int>_ret

    # Static field EmergencyNumber.EMERGENCY_NUMBER_SOURCE_NETWORK_SIGNALING
    @staticmethod
    def EMERGENCY_NUMBER_SOURCE_NETWORK_SIGNALING() -> int:
        cdef JNIEnv* env = get_env()
        _ensure_ids_EmergencyNumber(env)
        cdef jint _ret = jnicore_GetStaticIntField(env, _cls_EmergencyNumber, _sf_EMERGENCY_NUMBER_SOURCE_NETWORK_SIGNALING)
        check_jni_exc(env)
        return <int>_ret

    # Static field EmergencyNumber.EMERGENCY_NUMBER_SOURCE_SIM
    @staticmethod
    def EMERGENCY_NUMBER_SOURCE_SIM() -> int:
        cdef JNIEnv* env = get_env()
        _ensure_ids_EmergencyNumber(env)
        cdef jint _ret = jnicore_GetStaticIntField(env, _cls_EmergencyNumber, _sf_EMERGENCY_NUMBER_SOURCE_SIM)
        check_jni_exc(env)
        return <int>_ret

    # Static field EmergencyNumber.EMERGENCY_SERVICE_CATEGORY_AIEC
    @staticmethod
    def EMERGENCY_SERVICE_CATEGORY_AIEC() -> int:
        cdef JNIEnv* env = get_env()
        _ensure_ids_EmergencyNumber(env)
        cdef jint _ret = jnicore_GetStaticIntField(env, _cls_EmergencyNumber, _sf_EMERGENCY_SERVICE_CATEGORY_AIEC)
        check_jni_exc(env)
        return <int>_ret

    # Static field EmergencyNumber.EMERGENCY_SERVICE_CATEGORY_AMBULANCE
    @staticmethod
    def EMERGENCY_SERVICE_CATEGORY_AMBULANCE() -> int:
        cdef JNIEnv* env = get_env()
        _ensure_ids_EmergencyNumber(env)
        cdef jint _ret = jnicore_GetStaticIntField(env, _cls_EmergencyNumber, _sf_EMERGENCY_SERVICE_CATEGORY_AMBULANCE)
        check_jni_exc(env)
        return <int>_ret

    # Static field EmergencyNumber.EMERGENCY_SERVICE_CATEGORY_FIRE_BRIGADE
    @staticmethod
    def EMERGENCY_SERVICE_CATEGORY_FIRE_BRIGADE() -> int:
        cdef JNIEnv* env = get_env()
        _ensure_ids_EmergencyNumber(env)
        cdef jint _ret = jnicore_GetStaticIntField(env, _cls_EmergencyNumber, _sf_EMERGENCY_SERVICE_CATEGORY_FIRE_BRIGADE)
        check_jni_exc(env)
        return <int>_ret

    # Static field EmergencyNumber.EMERGENCY_SERVICE_CATEGORY_MARINE_GUARD
    @staticmethod
    def EMERGENCY_SERVICE_CATEGORY_MARINE_GUARD() -> int:
        cdef JNIEnv* env = get_env()
        _ensure_ids_EmergencyNumber(env)
        cdef jint _ret = jnicore_GetStaticIntField(env, _cls_EmergencyNumber, _sf_EMERGENCY_SERVICE_CATEGORY_MARINE_GUARD)
        check_jni_exc(env)
        return <int>_ret

    # Static field EmergencyNumber.EMERGENCY_SERVICE_CATEGORY_MIEC
    @staticmethod
    def EMERGENCY_SERVICE_CATEGORY_MIEC() -> int:
        cdef JNIEnv* env = get_env()
        _ensure_ids_EmergencyNumber(env)
        cdef jint _ret = jnicore_GetStaticIntField(env, _cls_EmergencyNumber, _sf_EMERGENCY_SERVICE_CATEGORY_MIEC)
        check_jni_exc(env)
        return <int>_ret

    # Static field EmergencyNumber.EMERGENCY_SERVICE_CATEGORY_MOUNTAIN_RESCUE
    @staticmethod
    def EMERGENCY_SERVICE_CATEGORY_MOUNTAIN_RESCUE() -> int:
        cdef JNIEnv* env = get_env()
        _ensure_ids_EmergencyNumber(env)
        cdef jint _ret = jnicore_GetStaticIntField(env, _cls_EmergencyNumber, _sf_EMERGENCY_SERVICE_CATEGORY_MOUNTAIN_RESCUE)
        check_jni_exc(env)
        return <int>_ret

    # Static field EmergencyNumber.EMERGENCY_SERVICE_CATEGORY_POLICE
    @staticmethod
    def EMERGENCY_SERVICE_CATEGORY_POLICE() -> int:
        cdef JNIEnv* env = get_env()
        _ensure_ids_EmergencyNumber(env)
        cdef jint _ret = jnicore_GetStaticIntField(env, _cls_EmergencyNumber, _sf_EMERGENCY_SERVICE_CATEGORY_POLICE)
        check_jni_exc(env)
        return <int>_ret

    # Static field EmergencyNumber.EMERGENCY_SERVICE_CATEGORY_UNSPECIFIED
    @staticmethod
    def EMERGENCY_SERVICE_CATEGORY_UNSPECIFIED() -> int:
        cdef JNIEnv* env = get_env()
        _ensure_ids_EmergencyNumber(env)
        cdef jint _ret = jnicore_GetStaticIntField(env, _cls_EmergencyNumber, _sf_EMERGENCY_SERVICE_CATEGORY_UNSPECIFIED)
        check_jni_exc(env)
        return <int>_ret

    # Static field EmergencyNumber.CONTENTS_FILE_DESCRIPTOR
    @staticmethod
    def CONTENTS_FILE_DESCRIPTOR() -> int:
        cdef JNIEnv* env = get_env()
        _ensure_ids_EmergencyNumber(env)
        cdef jint _ret = jnicore_GetStaticIntField(env, _cls_EmergencyNumber, _sf_CONTENTS_FILE_DESCRIPTOR)
        check_jni_exc(env)
        return <int>_ret

    # Static field EmergencyNumber.PARCELABLE_WRITE_RETURN_VALUE
    @staticmethod
    def PARCELABLE_WRITE_RETURN_VALUE() -> int:
        cdef JNIEnv* env = get_env()
        _ensure_ids_EmergencyNumber(env)
        cdef jint _ret = jnicore_GetStaticIntField(env, _cls_EmergencyNumber, _sf_PARCELABLE_WRITE_RETURN_VALUE)
        check_jni_exc(env)
        return <int>_ret

    def getCountryIso(self) -> str:
        cdef JNIEnv* env = get_env()
        _ensure_ids_EmergencyNumber(env)
        cdef jvalue _args[1]  # unused; arrayless calls disallowed in Cython
        cdef jstring _ret = <jstring>jnicore_CallObjectMethodA(env, self._handle, _m_getCountryIso_0, _args)
        check_jni_exc(env)
        return py_str(env, _ret)

    def getEmergencyUrns(self) -> object:
        cdef JNIEnv* env = get_env()
        _ensure_ids_EmergencyNumber(env)
        cdef jvalue _args[1]  # unused; arrayless calls disallowed in Cython
        cdef jobject _ret = jnicore_CallObjectMethodA(env, self._handle, _m_getEmergencyUrns_0, _args)
        check_jni_exc(env)
        if _ret == NULL:
            return None
        cdef JavaObject _wrapped = JavaObject.__new__(JavaObject)
        _wrapped._adopt_local(env, _ret)
        return _wrapped

    def isFromSources(self, p0) -> bool:
        cdef JNIEnv* env = get_env()
        _ensure_ids_EmergencyNumber(env)
        cdef jvalue _args[1]
        _args[0].i = py_to_jint(p0)
        cdef jboolean _ret = jnicore_CallBooleanMethodA(env, self._handle, _m_isFromSources_0, _args)
        check_jni_exc(env)
        return jboolean_to_py(_ret)

    def getEmergencyServiceCategories(self) -> object:
        cdef JNIEnv* env = get_env()
        _ensure_ids_EmergencyNumber(env)
        cdef jvalue _args[1]  # unused; arrayless calls disallowed in Cython
        cdef jobject _ret = jnicore_CallObjectMethodA(env, self._handle, _m_getEmergencyServiceCategories_0, _args)
        check_jni_exc(env)
        if _ret == NULL:
            return None
        cdef JavaObject _wrapped = JavaObject.__new__(JavaObject)
        _wrapped._adopt_local(env, _ret)
        return _wrapped

    def isInEmergencyServiceCategories(self, p0) -> bool:
        cdef JNIEnv* env = get_env()
        _ensure_ids_EmergencyNumber(env)
        cdef jvalue _args[1]
        _args[0].i = py_to_jint(p0)
        cdef jboolean _ret = jnicore_CallBooleanMethodA(env, self._handle, _m_isInEmergencyServiceCategories_0, _args)
        check_jni_exc(env)
        return jboolean_to_py(_ret)

    def getEmergencyNumberSources(self) -> object:
        cdef JNIEnv* env = get_env()
        _ensure_ids_EmergencyNumber(env)
        cdef jvalue _args[1]  # unused; arrayless calls disallowed in Cython
        cdef jobject _ret = jnicore_CallObjectMethodA(env, self._handle, _m_getEmergencyNumberSources_0, _args)
        check_jni_exc(env)
        if _ret == NULL:
            return None
        cdef JavaObject _wrapped = JavaObject.__new__(JavaObject)
        _wrapped._adopt_local(env, _ret)
        return _wrapped

    def getEmergencyCallRouting(self) -> int:
        cdef JNIEnv* env = get_env()
        _ensure_ids_EmergencyNumber(env)
        cdef jvalue _args[1]  # unused; arrayless calls disallowed in Cython
        cdef jint _ret = jnicore_CallIntMethodA(env, self._handle, _m_getEmergencyCallRouting_0, _args)
        check_jni_exc(env)
        return <int>_ret

    def getMnc(self) -> str:
        cdef JNIEnv* env = get_env()
        _ensure_ids_EmergencyNumber(env)
        cdef jvalue _args[1]  # unused; arrayless calls disallowed in Cython
        cdef jstring _ret = <jstring>jnicore_CallObjectMethodA(env, self._handle, _m_getMnc_0, _args)
        check_jni_exc(env)
        return py_str(env, _ret)

    def describeContents(self) -> int:
        cdef JNIEnv* env = get_env()
        _ensure_ids_EmergencyNumber(env)
        cdef jvalue _args[1]  # unused; arrayless calls disallowed in Cython
        cdef jint _ret = jnicore_CallIntMethodA(env, self._handle, _m_describeContents_0, _args)
        check_jni_exc(env)
        return <int>_ret

    def writeToParcel(self, p0, p1) -> None:
        cdef JNIEnv* env = get_env()
        _ensure_ids_EmergencyNumber(env)
        cdef jvalue _args[2]
        _args[0].l = (<JavaObject?>p0)._handle if p0 is not None else <jobject>NULL
        _args[1].i = py_to_jint(p1)
        jnicore_CallVoidMethodA(env, self._handle, _m_writeToParcel_0, _args)
        check_jni_exc(env)

    def getNumber(self) -> str:
        cdef JNIEnv* env = get_env()
        _ensure_ids_EmergencyNumber(env)
        cdef jvalue _args[1]  # unused; arrayless calls disallowed in Cython
        cdef jstring _ret = <jstring>jnicore_CallObjectMethodA(env, self._handle, _m_getNumber_0, _args)
        check_jni_exc(env)
        return py_str(env, _ret)

    def equals(self, p0) -> bool:
        cdef JNIEnv* env = get_env()
        _ensure_ids_EmergencyNumber(env)
        cdef jvalue _args[1]
        _args[0].l = (<JavaObject?>p0)._handle if p0 is not None else <jobject>NULL
        cdef jboolean _ret = jnicore_CallBooleanMethodA(env, self._handle, _m_equals_0, _args)
        check_jni_exc(env)
        return jboolean_to_py(_ret)

    def toString(self) -> str:
        cdef JNIEnv* env = get_env()
        _ensure_ids_EmergencyNumber(env)
        cdef jvalue _args[1]  # unused; arrayless calls disallowed in Cython
        cdef jstring _ret = <jstring>jnicore_CallObjectMethodA(env, self._handle, _m_toString_0, _args)
        check_jni_exc(env)
        return py_str(env, _ret)

    def hashCode(self) -> int:
        cdef JNIEnv* env = get_env()
        _ensure_ids_EmergencyNumber(env)
        cdef jvalue _args[1]  # unused; arrayless calls disallowed in Cython
        cdef jint _ret = jnicore_CallIntMethodA(env, self._handle, _m_hashCode_0, _args)
        check_jni_exc(env)
        return <int>_ret

    # TODO: 2 overloads of compareTo; only the first is wired.
    #   overload[0] = (Ljava/lang/Object;)I
    #   overload[1] = (Landroid/telephony/emergency/EmergencyNumber;)I
    def compareTo(self, p0) -> int:
        cdef JNIEnv* env = get_env()
        _ensure_ids_EmergencyNumber(env)
        cdef jvalue _args[1]
        _args[0].l = (<JavaObject?>p0)._handle if p0 is not None else <jobject>NULL
        cdef jint _ret = jnicore_CallIntMethodA(env, self._handle, _m_compareTo_0, _args)
        check_jni_exc(env)
        return <int>_ret

