from typing import Any, ClassVar, overload
from android.os.Parcel import Parcel

class EmbeddedPhotoPickerFeatureInfo:
    CREATOR: ClassVar[Any]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    def toString(self) -> str: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
    def describeContents(self) -> int: ...
    def getAccentColor(self) -> int: ...
    def getPreSelectedUris(self) -> list: ...
    def getMimeTypes(self) -> list: ...
    def isOrderedSelection(self) -> bool: ...
    def getThemeNightMode(self) -> int: ...
    def getMaxSelectionLimit(self) -> int: ...

    class Builder:
        def __init__(self) -> None: ...
        def build(self) -> "EmbeddedPhotoPickerFeatureInfo": ...
        def setAccentColor(self, p0: int) -> Any: ...
        def setMaxSelectionLimit(self, p0: int) -> Any: ...
        def setOrderedSelection(self, p0: bool) -> Any: ...
        def setMimeTypes(self, p0: list) -> Any: ...
        def setThemeNightMode(self, p0: int) -> Any: ...
        def setPreSelectedUris(self, p0: list) -> Any: ...
