from typing import Any, ClassVar, overload
from android.content.res.Configuration import Configuration

class EmbeddedPhotoPickerSession:
    def close(self) -> None: ...
    def getSurfacePackage(self) -> Any: ...
    def notifyPhotoPickerExpanded(self, p0: bool) -> None: ...
    def notifyResized(self, p0: int, p1: int) -> None: ...
    def notifyConfigurationChanged(self, p0: Configuration) -> None: ...
    def notifyVisibilityChanged(self, p0: bool) -> None: ...
    def requestRevokeUriPermission(self, p0: list) -> None: ...
