from typing import Any, ClassVar, overload

class BackupDataInput:
    def skipEntityData(self) -> None: ...
    def readNextHeader(self) -> bool: ...
    def readEntityData(self, p0: Any, p1: int, p2: int) -> int: ...
    def getDataSize(self) -> int: ...
    def getKey(self) -> str: ...
