from typing import Any, ClassVar, overload
from android.os.Parcel import Parcel

class RecognitionSupport:
    CREATOR: ClassVar[Any]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    def equals(self, p0: Any) -> bool: ...
    def toString(self) -> str: ...
    def hashCode(self) -> int: ...
    def getOnlineLanguages(self) -> list: ...
    def getPendingOnDeviceLanguages(self) -> list: ...
    def getInstalledOnDeviceLanguages(self) -> list: ...
    def getSupportedOnDeviceLanguages(self) -> list: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
    def describeContents(self) -> int: ...

    class Builder:
        def __init__(self) -> None: ...
        def setOnlineLanguages(self, p0: list) -> Any: ...
        def addOnlineLanguage(self, p0: str) -> Any: ...
        def addInstalledOnDeviceLanguage(self, p0: str) -> Any: ...
        def addPendingOnDeviceLanguage(self, p0: str) -> Any: ...
        def addSupportedOnDeviceLanguage(self, p0: str) -> Any: ...
        def setInstalledOnDeviceLanguages(self, p0: list) -> Any: ...
        def setPendingOnDeviceLanguages(self, p0: list) -> Any: ...
        def setSupportedOnDeviceLanguages(self, p0: list) -> Any: ...
        def build(self) -> "RecognitionSupport": ...
