from typing import Any, ClassVar, overload
from android.content.Context import Context
from android.graphics.Path import Path
from android.util.AttributeSet import AttributeSet

class PatternPathMotion:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, p0: Path) -> None: ...
    @overload
    def __init__(self, p0: Context, p1: AttributeSet) -> None: ...
    def getPatternPath(self) -> Path: ...
    def setPatternPath(self, p0: Path) -> None: ...
    def getPath(self, p0: float, p1: float, p2: float, p3: float) -> Path: ...
