from typing import Any, ClassVar, overload
from android.animation.Animator import Animator
from android.animation.TimeInterpolator import TimeInterpolator
from android.content.Context import Context
from android.graphics.Rect import Rect
from android.transition.PathMotion import PathMotion
from android.transition.TransitionPropagation import TransitionPropagation
from android.transition.TransitionValues import TransitionValues
from android.util.AttributeSet import AttributeSet
from android.view.View import View
from android.view.ViewGroup import ViewGroup

class Transition:
    MATCH_ID: ClassVar[int]
    MATCH_INSTANCE: ClassVar[int]
    MATCH_ITEM_ID: ClassVar[int]
    MATCH_NAME: ClassVar[int]
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, p0: Context, p1: AttributeSet) -> None: ...
    def getName(self) -> str: ...
    def toString(self) -> str: ...
    @overload
    def clone(self) -> Any: ...
    @overload
    def clone(self) -> "Transition": ...
    def getDuration(self) -> int: ...
    def setDuration(self, p0: int) -> "Transition": ...
    def setStartDelay(self, p0: int) -> "Transition": ...
    def getStartDelay(self) -> int: ...
    def setInterpolator(self, p0: TimeInterpolator) -> "Transition": ...
    def getInterpolator(self) -> TimeInterpolator: ...
    def getTransitionProperties(self) -> Any: ...
    def createAnimator(self, p0: ViewGroup, p1: TransitionValues, p2: TransitionValues) -> Animator: ...
    def setMatchOrder(self, p0: Any) -> None: ...
    def captureStartValues(self, p0: TransitionValues) -> None: ...
    def captureEndValues(self, p0: TransitionValues) -> None: ...
    @overload
    def addTarget(self, p0: str) -> "Transition": ...
    @overload
    def addTarget(self, p0: View) -> "Transition": ...
    @overload
    def addTarget(self, p0: type) -> "Transition": ...
    @overload
    def addTarget(self, p0: int) -> "Transition": ...
    @overload
    def removeTarget(self, p0: View) -> "Transition": ...
    @overload
    def removeTarget(self, p0: type) -> "Transition": ...
    @overload
    def removeTarget(self, p0: str) -> "Transition": ...
    @overload
    def removeTarget(self, p0: int) -> "Transition": ...
    @overload
    def excludeTarget(self, p0: str, p1: bool) -> "Transition": ...
    @overload
    def excludeTarget(self, p0: int, p1: bool) -> "Transition": ...
    @overload
    def excludeTarget(self, p0: type, p1: bool) -> "Transition": ...
    @overload
    def excludeTarget(self, p0: View, p1: bool) -> "Transition": ...
    @overload
    def excludeChildren(self, p0: type, p1: bool) -> "Transition": ...
    @overload
    def excludeChildren(self, p0: int, p1: bool) -> "Transition": ...
    @overload
    def excludeChildren(self, p0: View, p1: bool) -> "Transition": ...
    def getTargetIds(self) -> list: ...
    def getTargets(self) -> list: ...
    def getTargetNames(self) -> list: ...
    def getTargetTypes(self) -> list: ...
    def getTransitionValues(self, p0: View, p1: bool) -> TransitionValues: ...
    def isTransitionRequired(self, p0: TransitionValues, p1: TransitionValues) -> bool: ...
    def addListener(self, p0: Any) -> "Transition": ...
    def removeListener(self, p0: Any) -> "Transition": ...
    def setEpicenterCallback(self, p0: Any) -> None: ...
    def getEpicenterCallback(self) -> Any: ...
    def getEpicenter(self) -> Rect: ...
    def setPathMotion(self, p0: PathMotion) -> None: ...
    def getPathMotion(self) -> PathMotion: ...
    def setPropagation(self, p0: TransitionPropagation) -> None: ...
    def getPropagation(self) -> TransitionPropagation: ...
    def canRemoveViews(self) -> bool: ...

    class TransitionListener:
        def onTransitionEnd(self, p0: "Transition") -> None: ...
        def onTransitionCancel(self, p0: "Transition") -> None: ...
        def onTransitionStart(self, p0: "Transition") -> None: ...
        def onTransitionPause(self, p0: "Transition") -> None: ...
        def onTransitionResume(self, p0: "Transition") -> None: ...

    class EpicenterCallback:
        def __init__(self) -> None: ...
        def onGetEpicenter(self, p0: "Transition") -> Rect: ...
