from typing import Any, ClassVar, overload
from android.os.Parcel import Parcel
from android.service.credentials.CreateEntry import CreateEntry
from android.service.credentials.RemoteEntry import RemoteEntry

class BeginCreateCredentialResponse:
    CREATOR: ClassVar[Any]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    def __init__(self) -> None: ...
    def getCreateEntries(self) -> list: ...
    def getRemoteCreateEntry(self) -> RemoteEntry: ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...

    class Builder:
        def __init__(self) -> None: ...
        def setCreateEntries(self, p0: list) -> Any: ...
        def addCreateEntry(self, p0: CreateEntry) -> Any: ...
        def setRemoteCreateEntry(self, p0: RemoteEntry) -> Any: ...
        def build(self) -> "BeginCreateCredentialResponse": ...
