from typing import Any, ClassVar, overload
from android.os.Bundle import Bundle
from android.os.Parcel import Parcel
from android.service.credentials.CallingAppInfo import CallingAppInfo

class CreateCredentialRequest:
    CREATOR: ClassVar[Any]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    def __init__(self, p0: CallingAppInfo, p1: str, p2: Bundle) -> None: ...
    def getCallingAppInfo(self) -> CallingAppInfo: ...
    def getType(self) -> str: ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
    def getData(self) -> Bundle: ...
