from typing import Any, ClassVar, overload
from java.nio.Buffer import Buffer
from java.nio.FloatBuffer import FloatBuffer
from java.nio.IntBuffer import IntBuffer

class GL11ExtensionPack:
    GL_BLEND_DST_ALPHA: ClassVar[int]
    GL_BLEND_DST_RGB: ClassVar[int]
    GL_BLEND_EQUATION: ClassVar[int]
    GL_BLEND_EQUATION_ALPHA: ClassVar[int]
    GL_BLEND_EQUATION_RGB: ClassVar[int]
    GL_BLEND_SRC_ALPHA: ClassVar[int]
    GL_BLEND_SRC_RGB: ClassVar[int]
    GL_COLOR_ATTACHMENT0_OES: ClassVar[int]
    GL_COLOR_ATTACHMENT10_OES: ClassVar[int]
    GL_COLOR_ATTACHMENT11_OES: ClassVar[int]
    GL_COLOR_ATTACHMENT12_OES: ClassVar[int]
    GL_COLOR_ATTACHMENT13_OES: ClassVar[int]
    GL_COLOR_ATTACHMENT14_OES: ClassVar[int]
    GL_COLOR_ATTACHMENT15_OES: ClassVar[int]
    GL_COLOR_ATTACHMENT1_OES: ClassVar[int]
    GL_COLOR_ATTACHMENT2_OES: ClassVar[int]
    GL_COLOR_ATTACHMENT3_OES: ClassVar[int]
    GL_COLOR_ATTACHMENT4_OES: ClassVar[int]
    GL_COLOR_ATTACHMENT5_OES: ClassVar[int]
    GL_COLOR_ATTACHMENT6_OES: ClassVar[int]
    GL_COLOR_ATTACHMENT7_OES: ClassVar[int]
    GL_COLOR_ATTACHMENT8_OES: ClassVar[int]
    GL_COLOR_ATTACHMENT9_OES: ClassVar[int]
    GL_DECR_WRAP: ClassVar[int]
    GL_DEPTH_ATTACHMENT_OES: ClassVar[int]
    GL_DEPTH_COMPONENT: ClassVar[int]
    GL_DEPTH_COMPONENT16: ClassVar[int]
    GL_DEPTH_COMPONENT24: ClassVar[int]
    GL_DEPTH_COMPONENT32: ClassVar[int]
    GL_FRAMEBUFFER_ATTACHMENT_OBJECT_NAME_OES: ClassVar[int]
    GL_FRAMEBUFFER_ATTACHMENT_OBJECT_TYPE_OES: ClassVar[int]
    GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_CUBE_MAP_FACE_OES: ClassVar[int]
    GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_LEVEL_OES: ClassVar[int]
    GL_FRAMEBUFFER_BINDING_OES: ClassVar[int]
    GL_FRAMEBUFFER_COMPLETE_OES: ClassVar[int]
    GL_FRAMEBUFFER_INCOMPLETE_ATTACHMENT_OES: ClassVar[int]
    GL_FRAMEBUFFER_INCOMPLETE_DIMENSIONS_OES: ClassVar[int]
    GL_FRAMEBUFFER_INCOMPLETE_DRAW_BUFFER_OES: ClassVar[int]
    GL_FRAMEBUFFER_INCOMPLETE_FORMATS_OES: ClassVar[int]
    GL_FRAMEBUFFER_INCOMPLETE_MISSING_ATTACHMENT_OES: ClassVar[int]
    GL_FRAMEBUFFER_INCOMPLETE_READ_BUFFER_OES: ClassVar[int]
    GL_FRAMEBUFFER_OES: ClassVar[int]
    GL_FRAMEBUFFER_UNSUPPORTED_OES: ClassVar[int]
    GL_FUNC_ADD: ClassVar[int]
    GL_FUNC_REVERSE_SUBTRACT: ClassVar[int]
    GL_FUNC_SUBTRACT: ClassVar[int]
    GL_INCR_WRAP: ClassVar[int]
    GL_INVALID_FRAMEBUFFER_OPERATION_OES: ClassVar[int]
    GL_MAX_COLOR_ATTACHMENTS_OES: ClassVar[int]
    GL_MAX_CUBE_MAP_TEXTURE_SIZE: ClassVar[int]
    GL_MAX_RENDERBUFFER_SIZE_OES: ClassVar[int]
    GL_MIRRORED_REPEAT: ClassVar[int]
    GL_NORMAL_MAP: ClassVar[int]
    GL_REFLECTION_MAP: ClassVar[int]
    GL_RENDERBUFFER_ALPHA_SIZE_OES: ClassVar[int]
    GL_RENDERBUFFER_BINDING_OES: ClassVar[int]
    GL_RENDERBUFFER_BLUE_SIZE_OES: ClassVar[int]
    GL_RENDERBUFFER_DEPTH_SIZE_OES: ClassVar[int]
    GL_RENDERBUFFER_GREEN_SIZE_OES: ClassVar[int]
    GL_RENDERBUFFER_HEIGHT_OES: ClassVar[int]
    GL_RENDERBUFFER_INTERNAL_FORMAT_OES: ClassVar[int]
    GL_RENDERBUFFER_OES: ClassVar[int]
    GL_RENDERBUFFER_RED_SIZE_OES: ClassVar[int]
    GL_RENDERBUFFER_STENCIL_SIZE_OES: ClassVar[int]
    GL_RENDERBUFFER_WIDTH_OES: ClassVar[int]
    GL_RGB565_OES: ClassVar[int]
    GL_RGB5_A1: ClassVar[int]
    GL_RGB8: ClassVar[int]
    GL_RGBA4: ClassVar[int]
    GL_RGBA8: ClassVar[int]
    GL_STENCIL_ATTACHMENT_OES: ClassVar[int]
    GL_STENCIL_INDEX: ClassVar[int]
    GL_STENCIL_INDEX1_OES: ClassVar[int]
    GL_STENCIL_INDEX4_OES: ClassVar[int]
    GL_STENCIL_INDEX8_OES: ClassVar[int]
    GL_STR: ClassVar[int]
    GL_TEXTURE_BINDING_CUBE_MAP: ClassVar[int]
    GL_TEXTURE_CUBE_MAP: ClassVar[int]
    GL_TEXTURE_CUBE_MAP_NEGATIVE_X: ClassVar[int]
    GL_TEXTURE_CUBE_MAP_NEGATIVE_Y: ClassVar[int]
    GL_TEXTURE_CUBE_MAP_NEGATIVE_Z: ClassVar[int]
    GL_TEXTURE_CUBE_MAP_POSITIVE_X: ClassVar[int]
    GL_TEXTURE_CUBE_MAP_POSITIVE_Y: ClassVar[int]
    GL_TEXTURE_CUBE_MAP_POSITIVE_Z: ClassVar[int]
    GL_TEXTURE_GEN_MODE: ClassVar[int]
    GL_TEXTURE_GEN_STR: ClassVar[int]
    def glBlendEquation(self, p0: int) -> None: ...
    def glBlendEquationSeparate(self, p0: int, p1: int) -> None: ...
    def glBlendFuncSeparate(self, p0: int, p1: int, p2: int, p3: int) -> None: ...
    def glBindFramebufferOES(self, p0: int, p1: int) -> None: ...
    def glBindRenderbufferOES(self, p0: int, p1: int) -> None: ...
    def glCheckFramebufferStatusOES(self, p0: int) -> int: ...
    @overload
    def glDeleteFramebuffersOES(self, p0: int, p1: Any, p2: int) -> None: ...
    @overload
    def glDeleteFramebuffersOES(self, p0: int, p1: IntBuffer) -> None: ...
    @overload
    def glDeleteRenderbuffersOES(self, p0: int, p1: IntBuffer) -> None: ...
    @overload
    def glDeleteRenderbuffersOES(self, p0: int, p1: Any, p2: int) -> None: ...
    def glFramebufferRenderbufferOES(self, p0: int, p1: int, p2: int, p3: int) -> None: ...
    def glFramebufferTexture2DOES(self, p0: int, p1: int, p2: int, p3: int, p4: int) -> None: ...
    @overload
    def glGenFramebuffersOES(self, p0: int, p1: Any, p2: int) -> None: ...
    @overload
    def glGenFramebuffersOES(self, p0: int, p1: IntBuffer) -> None: ...
    @overload
    def glGenRenderbuffersOES(self, p0: int, p1: IntBuffer) -> None: ...
    @overload
    def glGenRenderbuffersOES(self, p0: int, p1: Any, p2: int) -> None: ...
    def glGenerateMipmapOES(self, p0: int) -> None: ...
    @overload
    def glGetFramebufferAttachmentParameterivOES(self, p0: int, p1: int, p2: int, p3: IntBuffer) -> None: ...
    @overload
    def glGetFramebufferAttachmentParameterivOES(self, p0: int, p1: int, p2: int, p3: Any, p4: int) -> None: ...
    @overload
    def glGetRenderbufferParameterivOES(self, p0: int, p1: int, p2: Any, p3: int) -> None: ...
    @overload
    def glGetRenderbufferParameterivOES(self, p0: int, p1: int, p2: IntBuffer) -> None: ...
    def glIsFramebufferOES(self, p0: int) -> bool: ...
    def glIsRenderbufferOES(self, p0: int) -> bool: ...
    def glRenderbufferStorageOES(self, p0: int, p1: int, p2: int, p3: int) -> None: ...
    def glBindTexture(self, p0: int, p1: int) -> None: ...
    def glCompressedTexImage2D(self, p0: int, p1: int, p2: int, p3: int, p4: int, p5: int, p6: int, p7: Buffer) -> None: ...
    def glCopyTexImage2D(self, p0: int, p1: int, p2: int, p3: int, p4: int, p5: int, p6: int, p7: int) -> None: ...
    def glEnable(self, p0: int) -> None: ...
    @overload
    def glGetIntegerv(self, p0: int, p1: IntBuffer) -> None: ...
    @overload
    def glGetIntegerv(self, p0: int, p1: Any, p2: int) -> None: ...
    def glStencilOp(self, p0: int, p1: int, p2: int) -> None: ...
    def glTexEnvf(self, p0: int, p1: int, p2: float) -> None: ...
    @overload
    def glTexEnvfv(self, p0: int, p1: int, p2: Any, p3: int) -> None: ...
    @overload
    def glTexEnvfv(self, p0: int, p1: int, p2: FloatBuffer) -> None: ...
    def glTexEnvx(self, p0: int, p1: int, p2: int) -> None: ...
    @overload
    def glTexEnvxv(self, p0: int, p1: int, p2: Any, p3: int) -> None: ...
    @overload
    def glTexEnvxv(self, p0: int, p1: int, p2: IntBuffer) -> None: ...
    def glTexParameterf(self, p0: int, p1: int, p2: float) -> None: ...
    def glTexGeni(self, p0: int, p1: int, p2: int) -> None: ...
    @overload
    def glTexGenfv(self, p0: int, p1: int, p2: Any, p3: int) -> None: ...
    @overload
    def glTexGenfv(self, p0: int, p1: int, p2: FloatBuffer) -> None: ...
    @overload
    def glTexGeniv(self, p0: int, p1: int, p2: Any, p3: int) -> None: ...
    @overload
    def glTexGeniv(self, p0: int, p1: int, p2: IntBuffer) -> None: ...
    def glTexGenx(self, p0: int, p1: int, p2: int) -> None: ...
    @overload
    def glGetTexGenxv(self, p0: int, p1: int, p2: IntBuffer) -> None: ...
    @overload
    def glGetTexGenxv(self, p0: int, p1: int, p2: Any, p3: int) -> None: ...
    def glTexGenf(self, p0: int, p1: int, p2: float) -> None: ...
    @overload
    def glGetTexGeniv(self, p0: int, p1: int, p2: Any, p3: int) -> None: ...
    @overload
    def glGetTexGeniv(self, p0: int, p1: int, p2: IntBuffer) -> None: ...
    @overload
    def glGetTexGenfv(self, p0: int, p1: int, p2: Any, p3: int) -> None: ...
    @overload
    def glGetTexGenfv(self, p0: int, p1: int, p2: FloatBuffer) -> None: ...
    @overload
    def glTexGenxv(self, p0: int, p1: int, p2: IntBuffer) -> None: ...
    @overload
    def glTexGenxv(self, p0: int, p1: int, p2: Any, p3: int) -> None: ...
