from typing import Any, ClassVar, overload
from android.os.Parcel import Parcel

class Annotation:
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    @overload
    def __init__(self, p0: Parcel) -> None: ...
    @overload
    def __init__(self, p0: str, p1: str) -> None: ...
    def getValue(self) -> str: ...
    def getKey(self) -> str: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
    def describeContents(self) -> int: ...
    def getSpanTypeId(self) -> int: ...
