from jnius import JavaClass, MetaJavaClass, JavaMethod, JavaStaticMethod, JavaMultipleMethod, JavaField, JavaStaticField

__all__ = ["BoringLayout"]

class BoringLayout(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "android/text/BoringLayout"
    __javaconstructor__ = [("(Ljava/lang/CharSequence;Landroid/text/TextPaint;ILandroid/text/Layout$Alignment;FFLandroid/text/BoringLayout$Metrics;Z)V", False), ("(Ljava/lang/CharSequence;Landroid/text/TextPaint;ILandroid/text/Layout$Alignment;FFLandroid/text/BoringLayout$Metrics;ZLandroid/text/TextUtils$TruncateAt;IZ)V", False), ("(Ljava/lang/CharSequence;Landroid/text/TextPaint;ILandroid/text/Layout$Alignment;FFLandroid/text/BoringLayout$Metrics;ZLandroid/text/TextUtils$TruncateAt;I)V", False)]
    BREAK_STRATEGY_BALANCED = JavaStaticField("I")
    BREAK_STRATEGY_HIGH_QUALITY = JavaStaticField("I")
    BREAK_STRATEGY_SIMPLE = JavaStaticField("I")
    DEFAULT_LINESPACING_ADDITION = JavaStaticField("F")
    DEFAULT_LINESPACING_MULTIPLIER = JavaStaticField("F")
    DIR_LEFT_TO_RIGHT = JavaStaticField("I")
    DIR_RIGHT_TO_LEFT = JavaStaticField("I")
    HYPHENATION_FREQUENCY_FULL = JavaStaticField("I")
    HYPHENATION_FREQUENCY_FULL_FAST = JavaStaticField("I")
    HYPHENATION_FREQUENCY_NONE = JavaStaticField("I")
    HYPHENATION_FREQUENCY_NORMAL = JavaStaticField("I")
    HYPHENATION_FREQUENCY_NORMAL_FAST = JavaStaticField("I")
    INCLUSION_STRATEGY_ANY_OVERLAP = JavaStaticField("Landroid/text/Layout$TextInclusionStrategy;")
    INCLUSION_STRATEGY_CONTAINS_ALL = JavaStaticField("Landroid/text/Layout$TextInclusionStrategy;")
    INCLUSION_STRATEGY_CONTAINS_CENTER = JavaStaticField("Landroid/text/Layout$TextInclusionStrategy;")
    JUSTIFICATION_MODE_INTER_CHARACTER = JavaStaticField("I")
    JUSTIFICATION_MODE_INTER_WORD = JavaStaticField("I")
    JUSTIFICATION_MODE_NONE = JavaStaticField("I")
    ellipsized = JavaMethod("(II)V")
    isBoring = JavaMultipleMethod([("(Ljava/lang/CharSequence;Landroid/text/TextPaint;Landroid/text/TextDirectionHeuristic;ZLandroid/text/BoringLayout$Metrics;)Landroid/text/BoringLayout$Metrics;", True, False), ("(Ljava/lang/CharSequence;Landroid/text/TextPaint;Landroid/text/BoringLayout$Metrics;)Landroid/text/BoringLayout$Metrics;", True, False), ("(Ljava/lang/CharSequence;Landroid/text/TextPaint;)Landroid/text/BoringLayout$Metrics;", True, False)])
    replaceOrMake = JavaMultipleMethod([("(Ljava/lang/CharSequence;Landroid/text/TextPaint;ILandroid/text/Layout$Alignment;FFLandroid/text/BoringLayout$Metrics;ZLandroid/text/TextUtils$TruncateAt;I)Landroid/text/BoringLayout;", False, False), ("(Ljava/lang/CharSequence;Landroid/text/TextPaint;ILandroid/text/Layout$Alignment;Landroid/text/BoringLayout$Metrics;ZLandroid/text/TextUtils$TruncateAt;IZ)Landroid/text/BoringLayout;", False, False), ("(Ljava/lang/CharSequence;Landroid/text/TextPaint;ILandroid/text/Layout$Alignment;FFLandroid/text/BoringLayout$Metrics;Z)Landroid/text/BoringLayout;", False, False)])
    make = JavaMultipleMethod([("(Ljava/lang/CharSequence;Landroid/text/TextPaint;ILandroid/text/Layout$Alignment;FFLandroid/text/BoringLayout$Metrics;Z)Landroid/text/BoringLayout;", True, False), ("(Ljava/lang/CharSequence;Landroid/text/TextPaint;ILandroid/text/Layout$Alignment;FFLandroid/text/BoringLayout$Metrics;ZLandroid/text/TextUtils$TruncateAt;I)Landroid/text/BoringLayout;", True, False), ("(Ljava/lang/CharSequence;Landroid/text/TextPaint;ILandroid/text/Layout$Alignment;Landroid/text/BoringLayout$Metrics;ZLandroid/text/TextUtils$TruncateAt;IZ)Landroid/text/BoringLayout;", True, False)])
    draw = JavaMethod("(Landroid/graphics/Canvas;Landroid/graphics/Path;Landroid/graphics/Paint;I)V")
    getHeight = JavaMethod("()I")
    getLineCount = JavaMethod("()I")
    getBottomPadding = JavaMethod("()I")
    computeDrawingBoundingBox = JavaMethod("()Landroid/graphics/RectF;")
    getEllipsisCount = JavaMethod("(I)I")
    getEllipsisStart = JavaMethod("(I)I")
    getEllipsizedWidth = JavaMethod("()I")
    getLineContainsTab = JavaMethod("(I)Z")
    getLineDescent = JavaMethod("(I)I")
    getLineDirections = JavaMethod("(I)Landroid/text/Layout$Directions;")
    getLineMax = JavaMethod("(I)F")
    getLineStart = JavaMethod("(I)I")
    getLineTop = JavaMethod("(I)I")
    getLineWidth = JavaMethod("(I)F")
    getParagraphDirection = JavaMethod("(I)I")
    getTopPadding = JavaMethod("()I")
    isFallbackLineSpacingEnabled = JavaMethod("()Z")

    class Metrics(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "android/text/BoringLayout$Metrics"
        __javaconstructor__ = [("()V", False)]
        width = JavaField("I")
        ascent = JavaField("I")
        bottom = JavaField("I")
        descent = JavaField("I")
        leading = JavaField("I")
        top = JavaField("I")
        getDrawingBoundingBox = JavaMethod("()Landroid/graphics/RectF;")
        toString = JavaMethod("()Ljava/lang/String;")