from typing import Any, ClassVar, overload
from android.text.TextPaint import TextPaint

class GraphemeClusterSegmentFinder:
    DONE: ClassVar[int]
    def __init__(self, p0: str, p1: TextPaint) -> None: ...
    def nextEndBoundary(self, p0: int) -> int: ...
    def nextStartBoundary(self, p0: int) -> int: ...
    def previousEndBoundary(self, p0: int) -> int: ...
    def previousStartBoundary(self, p0: int) -> int: ...
