from typing import Any, ClassVar, overload
from android.text.Spannable import Spannable
from android.view.KeyEvent import KeyEvent
from android.view.MotionEvent import MotionEvent
from android.widget.TextView import TextView

class BaseMovementMethod:
    def __init__(self) -> None: ...
    def nextParagraph(self, p0: TextView, p1: Spannable) -> bool: ...
    def previousParagraph(self, p0: TextView, p1: Spannable) -> bool: ...
    def initialize(self, p0: TextView, p1: Spannable) -> None: ...
    def canSelectArbitrarily(self) -> bool: ...
    def onKeyOther(self, p0: TextView, p1: Spannable, p2: KeyEvent) -> bool: ...
    def onTakeFocus(self, p0: TextView, p1: Spannable, p2: int) -> None: ...
    def onGenericMotionEvent(self, p0: TextView, p1: Spannable, p2: MotionEvent) -> bool: ...
    def onKeyDown(self, p0: TextView, p1: Spannable, p2: int, p3: KeyEvent) -> bool: ...
    def onTrackballEvent(self, p0: TextView, p1: Spannable, p2: MotionEvent) -> bool: ...
    def onKeyUp(self, p0: TextView, p1: Spannable, p2: int, p3: KeyEvent) -> bool: ...
    def onTouchEvent(self, p0: TextView, p1: Spannable, p2: MotionEvent) -> bool: ...

from typing import Any, ClassVar, overload
from android.content.Context import Context
from android.text.Editable import Editable
from android.view.View import View
from android.widget.AdapterView import AdapterView

class CharacterPickerDialog:
    BUTTON1: ClassVar[int]
    BUTTON2: ClassVar[int]
    BUTTON3: ClassVar[int]
    BUTTON_NEGATIVE: ClassVar[int]
    BUTTON_NEUTRAL: ClassVar[int]
    BUTTON_POSITIVE: ClassVar[int]
    def __init__(self, p0: Context, p1: View, p2: Editable, p3: str, p4: bool) -> None: ...
    def onClick(self, p0: View) -> None: ...
    def onItemClick(self, p0: AdapterView, p1: View, p2: int, p3: int) -> None: ...

from typing import Any, ClassVar, overload
from android.text.Editable import Editable
from android.text.Spannable import Spannable
from android.view.KeyEvent import KeyEvent
from android.view.View import View

class QwertyKeyListener:
    META_ALT_LOCKED: ClassVar[int]
    META_ALT_ON: ClassVar[int]
    META_CAP_LOCKED: ClassVar[int]
    META_SHIFT_ON: ClassVar[int]
    META_SYM_LOCKED: ClassVar[int]
    META_SYM_ON: ClassVar[int]
    def __init__(self, p0: Any, p1: bool) -> None: ...
    @staticmethod
    def getInstanceForFullKeyboard() -> "QwertyKeyListener": ...
    @staticmethod
    def markAsReplaced(p0: Spannable, p1: int, p2: int, p3: str) -> None: ...
    @staticmethod
    def getInstance(p0: bool, p1: Any) -> "QwertyKeyListener": ...
    def onKeyDown(self, p0: View, p1: Editable, p2: int, p3: KeyEvent) -> bool: ...
    def getInputType(self) -> int: ...

from typing import Any, ClassVar, overload
from android.text.Spannable import Spannable
from android.view.KeyEvent import KeyEvent
from android.view.MotionEvent import MotionEvent
from android.widget.TextView import TextView

class MovementMethod:
    def initialize(self, p0: TextView, p1: Spannable) -> None: ...
    def canSelectArbitrarily(self) -> bool: ...
    def onKeyOther(self, p0: TextView, p1: Spannable, p2: KeyEvent) -> bool: ...
    def onTakeFocus(self, p0: TextView, p1: Spannable, p2: int) -> None: ...
    def onGenericMotionEvent(self, p0: TextView, p1: Spannable, p2: MotionEvent) -> bool: ...
    def onKeyDown(self, p0: TextView, p1: Spannable, p2: int, p3: KeyEvent) -> bool: ...
    def onTrackballEvent(self, p0: TextView, p1: Spannable, p2: MotionEvent) -> bool: ...
    def onKeyUp(self, p0: TextView, p1: Spannable, p2: int, p3: KeyEvent) -> bool: ...
    def onTouchEvent(self, p0: TextView, p1: Spannable, p2: MotionEvent) -> bool: ...

from typing import Any, ClassVar, overload
from android.text.Layout import Layout
from android.text.Spannable import Spannable
from android.view.MotionEvent import MotionEvent
from android.widget.TextView import TextView

class Touch:
    @staticmethod
    def getInitialScrollX(p0: TextView, p1: Spannable) -> int: ...
    @staticmethod
    def getInitialScrollY(p0: TextView, p1: Spannable) -> int: ...
    @staticmethod
    def scrollTo(p0: TextView, p1: Layout, p2: int, p3: int) -> None: ...
    @staticmethod
    def onTouchEvent(p0: TextView, p1: Spannable, p2: MotionEvent) -> bool: ...

from typing import Any, ClassVar, overload
from android.text.Editable import Editable
from android.view.KeyEvent import KeyEvent
from android.view.View import View

class KeyListener:
    def onKeyOther(self, p0: View, p1: Editable, p2: KeyEvent) -> bool: ...
    def onKeyDown(self, p0: View, p1: Editable, p2: int, p3: KeyEvent) -> bool: ...
    def clearMetaKeyState(self, p0: View, p1: Editable, p2: int) -> None: ...
    def onKeyUp(self, p0: View, p1: Editable, p2: int, p3: KeyEvent) -> bool: ...
    def getInputType(self) -> int: ...

from typing import Any, ClassVar, overload
from android.text.Editable import Editable
from android.text.Spanned import Spanned
from android.view.KeyEvent import KeyEvent
from android.view.View import View

class NumberKeyListener:
    META_ALT_LOCKED: ClassVar[int]
    META_ALT_ON: ClassVar[int]
    META_CAP_LOCKED: ClassVar[int]
    META_SHIFT_ON: ClassVar[int]
    META_SYM_LOCKED: ClassVar[int]
    META_SYM_ON: ClassVar[int]
    def __init__(self) -> None: ...
    def filter(self, p0: str, p1: int, p2: int, p3: Spanned, p4: int, p5: int) -> str: ...
    def onKeyDown(self, p0: View, p1: Editable, p2: int, p3: KeyEvent) -> bool: ...

from typing import Any, ClassVar, overload
from android.text.Spannable import Spannable
from android.text.method.MovementMethod import MovementMethod
from android.view.MotionEvent import MotionEvent
from android.widget.TextView import TextView

class ScrollingMovementMethod:
    def __init__(self) -> None: ...
    @staticmethod
    def getInstance() -> MovementMethod: ...
    def onTakeFocus(self, p0: TextView, p1: Spannable, p2: int) -> None: ...
    def onTouchEvent(self, p0: TextView, p1: Spannable, p2: MotionEvent) -> bool: ...

from typing import Any, ClassVar, overload
from android.graphics.Rect import Rect
from android.view.View import View

class TransformationMethod:
    def getTransformation(self, p0: str, p1: View) -> str: ...
    def onFocusChanged(self, p0: View, p1: str, p2: bool, p3: int, p4: Rect) -> None: ...

from typing import Any, ClassVar, overload

class DialerKeyListener:
    CHARACTERS: ClassVar[Any]
    META_ALT_LOCKED: ClassVar[int]
    META_ALT_ON: ClassVar[int]
    META_CAP_LOCKED: ClassVar[int]
    META_SHIFT_ON: ClassVar[int]
    META_SYM_LOCKED: ClassVar[int]
    META_SYM_ON: ClassVar[int]
    def __init__(self) -> None: ...
    @staticmethod
    def getInstance() -> "DialerKeyListener": ...
    def getInputType(self) -> int: ...

from typing import Any, ClassVar, overload

class HideReturnsTransformationMethod:
    def __init__(self) -> None: ...
    @staticmethod
    def getInstance() -> "HideReturnsTransformationMethod": ...

from typing import Any, ClassVar, overload
from android.text.Spannable import Spannable
from android.text.method.MovementMethod import MovementMethod
from android.view.MotionEvent import MotionEvent
from android.widget.TextView import TextView

class ArrowKeyMovementMethod:
    def __init__(self) -> None: ...
    def nextParagraph(self, p0: TextView, p1: Spannable) -> bool: ...
    def previousParagraph(self, p0: TextView, p1: Spannable) -> bool: ...
    @staticmethod
    def getInstance() -> MovementMethod: ...
    def initialize(self, p0: TextView, p1: Spannable) -> None: ...
    def canSelectArbitrarily(self) -> bool: ...
    def onTakeFocus(self, p0: TextView, p1: Spannable, p2: int) -> None: ...
    def onTouchEvent(self, p0: TextView, p1: Spannable, p2: MotionEvent) -> bool: ...

from typing import Any, ClassVar, overload
from android.graphics.Rect import Rect
from android.view.View import View

class ReplacementTransformationMethod:
    def __init__(self) -> None: ...
    def getTransformation(self, p0: str, p1: View) -> str: ...
    def onFocusChanged(self, p0: View, p1: str, p2: bool, p3: int, p4: Rect) -> None: ...

from typing import Any, ClassVar, overload
from android.text.Editable import Editable
from android.text.Spannable import Spannable
from android.view.KeyEvent import KeyEvent
from android.view.View import View

class MultiTapKeyListener:
    META_ALT_LOCKED: ClassVar[int]
    META_ALT_ON: ClassVar[int]
    META_CAP_LOCKED: ClassVar[int]
    META_SHIFT_ON: ClassVar[int]
    META_SYM_LOCKED: ClassVar[int]
    META_SYM_ON: ClassVar[int]
    def __init__(self, p0: Any, p1: bool) -> None: ...
    def onSpanAdded(self, p0: Spannable, p1: Any, p2: int, p3: int) -> None: ...
    def onSpanRemoved(self, p0: Spannable, p1: Any, p2: int, p3: int) -> None: ...
    def onSpanChanged(self, p0: Spannable, p1: Any, p2: int, p3: int, p4: int, p5: int) -> None: ...
    @staticmethod
    def getInstance(p0: bool, p1: Any) -> "MultiTapKeyListener": ...
    def onKeyDown(self, p0: View, p1: Editable, p2: int, p3: KeyEvent) -> bool: ...
    def getInputType(self) -> int: ...

from typing import Any, ClassVar, overload
from android.text.Editable import Editable
from android.view.KeyEvent import KeyEvent
from android.view.View import View

class BaseKeyListener:
    META_ALT_LOCKED: ClassVar[int]
    META_ALT_ON: ClassVar[int]
    META_CAP_LOCKED: ClassVar[int]
    META_SHIFT_ON: ClassVar[int]
    META_SYM_LOCKED: ClassVar[int]
    META_SYM_ON: ClassVar[int]
    def __init__(self) -> None: ...
    def backspace(self, p0: View, p1: Editable, p2: int, p3: KeyEvent) -> bool: ...
    def forwardDelete(self, p0: View, p1: Editable, p2: int, p3: KeyEvent) -> bool: ...
    def onKeyOther(self, p0: View, p1: Editable, p2: KeyEvent) -> bool: ...
    def onKeyDown(self, p0: View, p1: Editable, p2: int, p3: KeyEvent) -> bool: ...

from typing import Any, ClassVar, overload
from android.text.Spannable import Spannable
from android.text.method.MovementMethod import MovementMethod
from android.view.MotionEvent import MotionEvent
from android.widget.TextView import TextView

class LinkMovementMethod:
    def __init__(self) -> None: ...
    @staticmethod
    def getInstance() -> MovementMethod: ...
    def initialize(self, p0: TextView, p1: Spannable) -> None: ...
    def canSelectArbitrarily(self) -> bool: ...
    def onTakeFocus(self, p0: TextView, p1: Spannable, p2: int) -> None: ...
    def onTouchEvent(self, p0: TextView, p1: Spannable, p2: MotionEvent) -> bool: ...

from typing import Any, ClassVar, overload
from java.util.Locale import Locale

class TimeKeyListener:
    CHARACTERS: ClassVar[Any]
    META_ALT_LOCKED: ClassVar[int]
    META_ALT_ON: ClassVar[int]
    META_CAP_LOCKED: ClassVar[int]
    META_SHIFT_ON: ClassVar[int]
    META_SYM_LOCKED: ClassVar[int]
    META_SYM_ON: ClassVar[int]
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, p0: Locale) -> None: ...
    @overload
    @staticmethod
    def getInstance() -> "TimeKeyListener": ...
    @overload
    @staticmethod
    def getInstance(p0: Locale) -> "TimeKeyListener": ...
    def getInputType(self) -> int: ...

from typing import Any, ClassVar, overload
from android.text.Spanned import Spanned
from java.util.Locale import Locale

class DigitsKeyListener:
    META_ALT_LOCKED: ClassVar[int]
    META_ALT_ON: ClassVar[int]
    META_CAP_LOCKED: ClassVar[int]
    META_SHIFT_ON: ClassVar[int]
    META_SYM_LOCKED: ClassVar[int]
    META_SYM_ON: ClassVar[int]
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, p0: Locale, p1: bool, p2: bool) -> None: ...
    @overload
    def __init__(self, p0: Locale) -> None: ...
    @overload
    def __init__(self, p0: bool, p1: bool) -> None: ...
    def filter(self, p0: str, p1: int, p2: int, p3: Spanned, p4: int, p5: int) -> str: ...
    @overload
    @staticmethod
    def getInstance(p0: bool, p1: bool) -> "DigitsKeyListener": ...
    @overload
    @staticmethod
    def getInstance(p0: str) -> "DigitsKeyListener": ...
    @overload
    @staticmethod
    def getInstance(p0: Locale) -> "DigitsKeyListener": ...
    @overload
    @staticmethod
    def getInstance() -> "DigitsKeyListener": ...
    @overload
    @staticmethod
    def getInstance(p0: Locale, p1: bool, p2: bool) -> "DigitsKeyListener": ...
    def getInputType(self) -> int: ...

from typing import Any, ClassVar, overload
from android.text.Editable import Editable
from android.text.Spannable import Spannable
from android.view.KeyEvent import KeyEvent
from android.view.View import View

class MetaKeyKeyListener:
    META_ALT_LOCKED: ClassVar[int]
    META_ALT_ON: ClassVar[int]
    META_CAP_LOCKED: ClassVar[int]
    META_SHIFT_ON: ClassVar[int]
    META_SYM_LOCKED: ClassVar[int]
    META_SYM_ON: ClassVar[int]
    def __init__(self) -> None: ...
    @overload
    @staticmethod
    def adjustMetaAfterKeypress(p0: int) -> int: ...
    @overload
    @staticmethod
    def adjustMetaAfterKeypress(p0: Spannable) -> None: ...
    @staticmethod
    def handleKeyDown(p0: int, p1: int, p2: KeyEvent) -> int: ...
    @staticmethod
    def handleKeyUp(p0: int, p1: int, p2: KeyEvent) -> int: ...
    @staticmethod
    def isMetaTracker(p0: str, p1: Any) -> bool: ...
    @staticmethod
    def isSelectingMetaTracker(p0: str, p1: Any) -> bool: ...
    @staticmethod
    def resetLockedMeta(p0: int) -> int: ...
    @staticmethod
    def resetMetaState(p0: Spannable) -> None: ...
    def onKeyDown(self, p0: View, p1: Editable, p2: int, p3: KeyEvent) -> bool: ...
    @overload
    @staticmethod
    def getMetaState(p0: str, p1: KeyEvent) -> int: ...
    @overload
    @staticmethod
    def getMetaState(p0: str) -> int: ...
    @overload
    @staticmethod
    def getMetaState(p0: int) -> int: ...
    @overload
    @staticmethod
    def getMetaState(p0: str, p1: int, p2: KeyEvent) -> int: ...
    @overload
    @staticmethod
    def getMetaState(p0: int, p1: int) -> int: ...
    @overload
    @staticmethod
    def getMetaState(p0: str, p1: int) -> int: ...
    @overload
    @staticmethod
    def clearMetaKeyState(p0: Editable, p1: int) -> None: ...
    @overload
    def clearMetaKeyState(self, p0: View, p1: Editable, p2: int) -> None: ...
    @overload
    def clearMetaKeyState(self, p0: int, p1: int) -> int: ...
    def onKeyUp(self, p0: View, p1: Editable, p2: int, p3: KeyEvent) -> bool: ...

from typing import Any, ClassVar, overload

class SingleLineTransformationMethod:
    def __init__(self) -> None: ...
    @staticmethod
    def getInstance() -> "SingleLineTransformationMethod": ...

from typing import Any, ClassVar, overload
from java.util.Locale import Locale

class DateKeyListener:
    CHARACTERS: ClassVar[Any]
    META_ALT_LOCKED: ClassVar[int]
    META_ALT_ON: ClassVar[int]
    META_CAP_LOCKED: ClassVar[int]
    META_SHIFT_ON: ClassVar[int]
    META_SYM_LOCKED: ClassVar[int]
    META_SYM_ON: ClassVar[int]
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, p0: Locale) -> None: ...
    @overload
    @staticmethod
    def getInstance() -> "DateKeyListener": ...
    @overload
    @staticmethod
    def getInstance(p0: Locale) -> "DateKeyListener": ...
    def getInputType(self) -> int: ...

from typing import Any, ClassVar, overload
from android.text.Editable import Editable
from android.text.Spannable import Spannable
from android.view.KeyEvent import KeyEvent
from android.view.View import View

class TextKeyListener:
    META_ALT_LOCKED: ClassVar[int]
    META_ALT_ON: ClassVar[int]
    META_CAP_LOCKED: ClassVar[int]
    META_SHIFT_ON: ClassVar[int]
    META_SYM_LOCKED: ClassVar[int]
    META_SYM_ON: ClassVar[int]
    def __init__(self, p0: Any, p1: bool) -> None: ...
    def onSpanAdded(self, p0: Spannable, p1: Any, p2: int, p3: int) -> None: ...
    def onSpanRemoved(self, p0: Spannable, p1: Any, p2: int, p3: int) -> None: ...
    def onSpanChanged(self, p0: Spannable, p1: Any, p2: int, p3: int, p4: int, p5: int) -> None: ...
    @staticmethod
    def shouldCap(p0: Any, p1: str, p2: int) -> bool: ...
    @staticmethod
    def clear(p0: Editable) -> None: ...
    @overload
    @staticmethod
    def getInstance(p0: bool, p1: Any) -> "TextKeyListener": ...
    @overload
    @staticmethod
    def getInstance() -> "TextKeyListener": ...
    def onKeyOther(self, p0: View, p1: Editable, p2: KeyEvent) -> bool: ...
    def onKeyDown(self, p0: View, p1: Editable, p2: int, p3: KeyEvent) -> bool: ...
    def onKeyUp(self, p0: View, p1: Editable, p2: int, p3: KeyEvent) -> bool: ...
    def getInputType(self) -> int: ...
    def release(self) -> None: ...

    class Capitalize:
        CHARACTERS: ClassVar["Capitalize"]
        NONE: ClassVar["Capitalize"]
        SENTENCES: ClassVar["Capitalize"]
        WORDS: ClassVar["Capitalize"]
        CHARACTERS: ClassVar[Any]
        NONE: ClassVar[Any]
        SENTENCES: ClassVar[Any]
        WORDS: ClassVar[Any]
        @staticmethod
        def values() -> Any: ...
        @staticmethod
        def valueOf(p0: str) -> Any: ...

from typing import Any, ClassVar, overload
from java.util.Locale import Locale

class DateTimeKeyListener:
    CHARACTERS: ClassVar[Any]
    META_ALT_LOCKED: ClassVar[int]
    META_ALT_ON: ClassVar[int]
    META_CAP_LOCKED: ClassVar[int]
    META_SHIFT_ON: ClassVar[int]
    META_SYM_LOCKED: ClassVar[int]
    META_SYM_ON: ClassVar[int]
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, p0: Locale) -> None: ...
    @overload
    @staticmethod
    def getInstance() -> "DateTimeKeyListener": ...
    @overload
    @staticmethod
    def getInstance(p0: Locale) -> "DateTimeKeyListener": ...
    def getInputType(self) -> int: ...

from typing import Any, ClassVar, overload
from android.graphics.Rect import Rect
from android.text.Editable import Editable
from android.view.View import View

class PasswordTransformationMethod:
    def __init__(self) -> None: ...
    @staticmethod
    def getInstance() -> "PasswordTransformationMethod": ...
    def getTransformation(self, p0: str, p1: View) -> str: ...
    def onFocusChanged(self, p0: View, p1: str, p2: bool, p3: int, p4: Rect) -> None: ...
    def afterTextChanged(self, p0: Editable) -> None: ...
    def beforeTextChanged(self, p0: str, p1: int, p2: int, p3: int) -> None: ...
    def onTextChanged(self, p0: str, p1: int, p2: int, p3: int) -> None: ...

