from jnius import JavaClass, JavaInterface, MetaJavaClass, JavaMethod, JavaStaticMethod, JavaMultipleMethod, JavaField, JavaStaticField

class BaseMovementMethod(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "android/text/method/BaseMovementMethod"
    __javaconstructor__ = [("()V", False)]
    nextParagraph = JavaMethod("(Landroid/widget/TextView;Landroid/text/Spannable;)Z")
    previousParagraph = JavaMethod("(Landroid/widget/TextView;Landroid/text/Spannable;)Z")
    initialize = JavaMethod("(Landroid/widget/TextView;Landroid/text/Spannable;)V")
    canSelectArbitrarily = JavaMethod("()Z")
    onKeyOther = JavaMethod("(Landroid/widget/TextView;Landroid/text/Spannable;Landroid/view/KeyEvent;)Z")
    onTakeFocus = JavaMethod("(Landroid/widget/TextView;Landroid/text/Spannable;I)V")
    onGenericMotionEvent = JavaMethod("(Landroid/widget/TextView;Landroid/text/Spannable;Landroid/view/MotionEvent;)Z")
    onKeyDown = JavaMethod("(Landroid/widget/TextView;Landroid/text/Spannable;ILandroid/view/KeyEvent;)Z")
    onTrackballEvent = JavaMethod("(Landroid/widget/TextView;Landroid/text/Spannable;Landroid/view/MotionEvent;)Z")
    onKeyUp = JavaMethod("(Landroid/widget/TextView;Landroid/text/Spannable;ILandroid/view/KeyEvent;)Z")
    onTouchEvent = JavaMethod("(Landroid/widget/TextView;Landroid/text/Spannable;Landroid/view/MotionEvent;)Z")

class CharacterPickerDialog(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "android/text/method/CharacterPickerDialog"
    __javaconstructor__ = [("(Landroid/content/Context;Landroid/view/View;Landroid/text/Editable;Ljava/lang/String;Z)V", False)]
    BUTTON1 = JavaStaticField("I")
    BUTTON2 = JavaStaticField("I")
    BUTTON3 = JavaStaticField("I")
    BUTTON_NEGATIVE = JavaStaticField("I")
    BUTTON_NEUTRAL = JavaStaticField("I")
    BUTTON_POSITIVE = JavaStaticField("I")
    onClick = JavaMethod("(Landroid/view/View;)V")
    onItemClick = JavaMethod("(Landroid/widget/AdapterView;Landroid/view/View;IJ)V")

class QwertyKeyListener(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "android/text/method/QwertyKeyListener"
    __javaconstructor__ = [("(Landroid/text/method/TextKeyListener$Capitalize;Z)V", False)]
    META_ALT_LOCKED = JavaStaticField("I")
    META_ALT_ON = JavaStaticField("I")
    META_CAP_LOCKED = JavaStaticField("I")
    META_SHIFT_ON = JavaStaticField("I")
    META_SYM_LOCKED = JavaStaticField("I")
    META_SYM_ON = JavaStaticField("I")
    getInstanceForFullKeyboard = JavaStaticMethod("()Landroid/text/method/QwertyKeyListener;")
    markAsReplaced = JavaStaticMethod("(Landroid/text/Spannable;IILjava/lang/String;)V")
    getInstance = JavaStaticMethod("(ZLandroid/text/method/TextKeyListener$Capitalize;)Landroid/text/method/QwertyKeyListener;")
    onKeyDown = JavaMethod("(Landroid/view/View;Landroid/text/Editable;ILandroid/view/KeyEvent;)Z")
    getInputType = JavaMethod("()I")

class MovementMethod(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "android/text/method/MovementMethod"
    initialize = JavaMethod("(Landroid/widget/TextView;Landroid/text/Spannable;)V")
    canSelectArbitrarily = JavaMethod("()Z")
    onKeyOther = JavaMethod("(Landroid/widget/TextView;Landroid/text/Spannable;Landroid/view/KeyEvent;)Z")
    onTakeFocus = JavaMethod("(Landroid/widget/TextView;Landroid/text/Spannable;I)V")
    onGenericMotionEvent = JavaMethod("(Landroid/widget/TextView;Landroid/text/Spannable;Landroid/view/MotionEvent;)Z")
    onKeyDown = JavaMethod("(Landroid/widget/TextView;Landroid/text/Spannable;ILandroid/view/KeyEvent;)Z")
    onTrackballEvent = JavaMethod("(Landroid/widget/TextView;Landroid/text/Spannable;Landroid/view/MotionEvent;)Z")
    onKeyUp = JavaMethod("(Landroid/widget/TextView;Landroid/text/Spannable;ILandroid/view/KeyEvent;)Z")
    onTouchEvent = JavaMethod("(Landroid/widget/TextView;Landroid/text/Spannable;Landroid/view/MotionEvent;)Z")

class Touch(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "android/text/method/Touch"
    getInitialScrollX = JavaStaticMethod("(Landroid/widget/TextView;Landroid/text/Spannable;)I")
    getInitialScrollY = JavaStaticMethod("(Landroid/widget/TextView;Landroid/text/Spannable;)I")
    scrollTo = JavaStaticMethod("(Landroid/widget/TextView;Landroid/text/Layout;II)V")
    onTouchEvent = JavaStaticMethod("(Landroid/widget/TextView;Landroid/text/Spannable;Landroid/view/MotionEvent;)Z")

class KeyListener(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "android/text/method/KeyListener"
    onKeyOther = JavaMethod("(Landroid/view/View;Landroid/text/Editable;Landroid/view/KeyEvent;)Z")
    onKeyDown = JavaMethod("(Landroid/view/View;Landroid/text/Editable;ILandroid/view/KeyEvent;)Z")
    clearMetaKeyState = JavaMethod("(Landroid/view/View;Landroid/text/Editable;I)V")
    onKeyUp = JavaMethod("(Landroid/view/View;Landroid/text/Editable;ILandroid/view/KeyEvent;)Z")
    getInputType = JavaMethod("()I")

class NumberKeyListener(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "android/text/method/NumberKeyListener"
    __javaconstructor__ = [("()V", False)]
    META_ALT_LOCKED = JavaStaticField("I")
    META_ALT_ON = JavaStaticField("I")
    META_CAP_LOCKED = JavaStaticField("I")
    META_SHIFT_ON = JavaStaticField("I")
    META_SYM_LOCKED = JavaStaticField("I")
    META_SYM_ON = JavaStaticField("I")
    filter = JavaMethod("(Ljava/lang/CharSequence;IILandroid/text/Spanned;II)Ljava/lang/CharSequence;")
    onKeyDown = JavaMethod("(Landroid/view/View;Landroid/text/Editable;ILandroid/view/KeyEvent;)Z")

class ScrollingMovementMethod(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "android/text/method/ScrollingMovementMethod"
    __javaconstructor__ = [("()V", False)]
    getInstance = JavaStaticMethod("()Landroid/text/method/MovementMethod;")
    onTakeFocus = JavaMethod("(Landroid/widget/TextView;Landroid/text/Spannable;I)V")
    onTouchEvent = JavaMethod("(Landroid/widget/TextView;Landroid/text/Spannable;Landroid/view/MotionEvent;)Z")

class TransformationMethod(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "android/text/method/TransformationMethod"
    getTransformation = JavaMethod("(Ljava/lang/CharSequence;Landroid/view/View;)Ljava/lang/CharSequence;")
    onFocusChanged = JavaMethod("(Landroid/view/View;Ljava/lang/CharSequence;ZILandroid/graphics/Rect;)V")

class DialerKeyListener(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "android/text/method/DialerKeyListener"
    __javaconstructor__ = [("()V", False)]
    CHARACTERS = JavaStaticField("[C")
    META_ALT_LOCKED = JavaStaticField("I")
    META_ALT_ON = JavaStaticField("I")
    META_CAP_LOCKED = JavaStaticField("I")
    META_SHIFT_ON = JavaStaticField("I")
    META_SYM_LOCKED = JavaStaticField("I")
    META_SYM_ON = JavaStaticField("I")
    getInstance = JavaStaticMethod("()Landroid/text/method/DialerKeyListener;")
    getInputType = JavaMethod("()I")

class HideReturnsTransformationMethod(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "android/text/method/HideReturnsTransformationMethod"
    __javaconstructor__ = [("()V", False)]
    getInstance = JavaStaticMethod("()Landroid/text/method/HideReturnsTransformationMethod;")

class ArrowKeyMovementMethod(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "android/text/method/ArrowKeyMovementMethod"
    __javaconstructor__ = [("()V", False)]
    nextParagraph = JavaMethod("(Landroid/widget/TextView;Landroid/text/Spannable;)Z")
    previousParagraph = JavaMethod("(Landroid/widget/TextView;Landroid/text/Spannable;)Z")
    getInstance = JavaStaticMethod("()Landroid/text/method/MovementMethod;")
    initialize = JavaMethod("(Landroid/widget/TextView;Landroid/text/Spannable;)V")
    canSelectArbitrarily = JavaMethod("()Z")
    onTakeFocus = JavaMethod("(Landroid/widget/TextView;Landroid/text/Spannable;I)V")
    onTouchEvent = JavaMethod("(Landroid/widget/TextView;Landroid/text/Spannable;Landroid/view/MotionEvent;)Z")

class ReplacementTransformationMethod(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "android/text/method/ReplacementTransformationMethod"
    __javaconstructor__ = [("()V", False)]
    getTransformation = JavaMethod("(Ljava/lang/CharSequence;Landroid/view/View;)Ljava/lang/CharSequence;")
    onFocusChanged = JavaMethod("(Landroid/view/View;Ljava/lang/CharSequence;ZILandroid/graphics/Rect;)V")

class MultiTapKeyListener(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "android/text/method/MultiTapKeyListener"
    __javaconstructor__ = [("(Landroid/text/method/TextKeyListener$Capitalize;Z)V", False)]
    META_ALT_LOCKED = JavaStaticField("I")
    META_ALT_ON = JavaStaticField("I")
    META_CAP_LOCKED = JavaStaticField("I")
    META_SHIFT_ON = JavaStaticField("I")
    META_SYM_LOCKED = JavaStaticField("I")
    META_SYM_ON = JavaStaticField("I")
    onSpanAdded = JavaMethod("(Landroid/text/Spannable;Ljava/lang/Object;II)V")
    onSpanRemoved = JavaMethod("(Landroid/text/Spannable;Ljava/lang/Object;II)V")
    onSpanChanged = JavaMethod("(Landroid/text/Spannable;Ljava/lang/Object;IIII)V")
    getInstance = JavaStaticMethod("(ZLandroid/text/method/TextKeyListener$Capitalize;)Landroid/text/method/MultiTapKeyListener;")
    onKeyDown = JavaMethod("(Landroid/view/View;Landroid/text/Editable;ILandroid/view/KeyEvent;)Z")
    getInputType = JavaMethod("()I")

class BaseKeyListener(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "android/text/method/BaseKeyListener"
    __javaconstructor__ = [("()V", False)]
    META_ALT_LOCKED = JavaStaticField("I")
    META_ALT_ON = JavaStaticField("I")
    META_CAP_LOCKED = JavaStaticField("I")
    META_SHIFT_ON = JavaStaticField("I")
    META_SYM_LOCKED = JavaStaticField("I")
    META_SYM_ON = JavaStaticField("I")
    backspace = JavaMethod("(Landroid/view/View;Landroid/text/Editable;ILandroid/view/KeyEvent;)Z")
    forwardDelete = JavaMethod("(Landroid/view/View;Landroid/text/Editable;ILandroid/view/KeyEvent;)Z")
    onKeyOther = JavaMethod("(Landroid/view/View;Landroid/text/Editable;Landroid/view/KeyEvent;)Z")
    onKeyDown = JavaMethod("(Landroid/view/View;Landroid/text/Editable;ILandroid/view/KeyEvent;)Z")

class LinkMovementMethod(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "android/text/method/LinkMovementMethod"
    __javaconstructor__ = [("()V", False)]
    getInstance = JavaStaticMethod("()Landroid/text/method/MovementMethod;")
    initialize = JavaMethod("(Landroid/widget/TextView;Landroid/text/Spannable;)V")
    canSelectArbitrarily = JavaMethod("()Z")
    onTakeFocus = JavaMethod("(Landroid/widget/TextView;Landroid/text/Spannable;I)V")
    onTouchEvent = JavaMethod("(Landroid/widget/TextView;Landroid/text/Spannable;Landroid/view/MotionEvent;)Z")

class TimeKeyListener(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "android/text/method/TimeKeyListener"
    __javaconstructor__ = [("()V", False), ("(Ljava/util/Locale;)V", False)]
    CHARACTERS = JavaStaticField("[C")
    META_ALT_LOCKED = JavaStaticField("I")
    META_ALT_ON = JavaStaticField("I")
    META_CAP_LOCKED = JavaStaticField("I")
    META_SHIFT_ON = JavaStaticField("I")
    META_SYM_LOCKED = JavaStaticField("I")
    META_SYM_ON = JavaStaticField("I")
    getInstance = JavaMultipleMethod([("()Landroid/text/method/TimeKeyListener;", True, False), ("(Ljava/util/Locale;)Landroid/text/method/TimeKeyListener;", True, False)])
    getInputType = JavaMethod("()I")

class DigitsKeyListener(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "android/text/method/DigitsKeyListener"
    __javaconstructor__ = [("()V", False), ("(Ljava/util/Locale;ZZ)V", False), ("(Ljava/util/Locale;)V", False), ("(ZZ)V", False)]
    META_ALT_LOCKED = JavaStaticField("I")
    META_ALT_ON = JavaStaticField("I")
    META_CAP_LOCKED = JavaStaticField("I")
    META_SHIFT_ON = JavaStaticField("I")
    META_SYM_LOCKED = JavaStaticField("I")
    META_SYM_ON = JavaStaticField("I")
    filter = JavaMethod("(Ljava/lang/CharSequence;IILandroid/text/Spanned;II)Ljava/lang/CharSequence;")
    getInstance = JavaMultipleMethod([("(ZZ)Landroid/text/method/DigitsKeyListener;", True, False), ("(Ljava/lang/String;)Landroid/text/method/DigitsKeyListener;", True, False), ("(Ljava/util/Locale;)Landroid/text/method/DigitsKeyListener;", True, False), ("()Landroid/text/method/DigitsKeyListener;", True, False), ("(Ljava/util/Locale;ZZ)Landroid/text/method/DigitsKeyListener;", True, False)])
    getInputType = JavaMethod("()I")

class MetaKeyKeyListener(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "android/text/method/MetaKeyKeyListener"
    __javaconstructor__ = [("()V", False)]
    META_ALT_LOCKED = JavaStaticField("I")
    META_ALT_ON = JavaStaticField("I")
    META_CAP_LOCKED = JavaStaticField("I")
    META_SHIFT_ON = JavaStaticField("I")
    META_SYM_LOCKED = JavaStaticField("I")
    META_SYM_ON = JavaStaticField("I")
    adjustMetaAfterKeypress = JavaMultipleMethod([("(J)J", True, False), ("(Landroid/text/Spannable;)V", True, False)])
    handleKeyDown = JavaStaticMethod("(JILandroid/view/KeyEvent;)J")
    handleKeyUp = JavaStaticMethod("(JILandroid/view/KeyEvent;)J")
    isMetaTracker = JavaStaticMethod("(Ljava/lang/CharSequence;Ljava/lang/Object;)Z")
    isSelectingMetaTracker = JavaStaticMethod("(Ljava/lang/CharSequence;Ljava/lang/Object;)Z")
    resetLockedMeta = JavaStaticMethod("(J)J")
    resetMetaState = JavaStaticMethod("(Landroid/text/Spannable;)V")
    onKeyDown = JavaMethod("(Landroid/view/View;Landroid/text/Editable;ILandroid/view/KeyEvent;)Z")
    getMetaState = JavaMultipleMethod([("(Ljava/lang/CharSequence;Landroid/view/KeyEvent;)I", True, False), ("(Ljava/lang/CharSequence;)I", True, False), ("(J)I", True, False), ("(Ljava/lang/CharSequence;ILandroid/view/KeyEvent;)I", True, False), ("(JI)I", True, False), ("(Ljava/lang/CharSequence;I)I", True, False)])
    clearMetaKeyState = JavaMultipleMethod([("(Landroid/text/Editable;I)V", True, False), ("(Landroid/view/View;Landroid/text/Editable;I)V", False, False), ("(JI)J", False, False)])
    onKeyUp = JavaMethod("(Landroid/view/View;Landroid/text/Editable;ILandroid/view/KeyEvent;)Z")

class SingleLineTransformationMethod(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "android/text/method/SingleLineTransformationMethod"
    __javaconstructor__ = [("()V", False)]
    getInstance = JavaStaticMethod("()Landroid/text/method/SingleLineTransformationMethod;")

class DateKeyListener(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "android/text/method/DateKeyListener"
    __javaconstructor__ = [("()V", False), ("(Ljava/util/Locale;)V", False)]
    CHARACTERS = JavaStaticField("[C")
    META_ALT_LOCKED = JavaStaticField("I")
    META_ALT_ON = JavaStaticField("I")
    META_CAP_LOCKED = JavaStaticField("I")
    META_SHIFT_ON = JavaStaticField("I")
    META_SYM_LOCKED = JavaStaticField("I")
    META_SYM_ON = JavaStaticField("I")
    getInstance = JavaMultipleMethod([("()Landroid/text/method/DateKeyListener;", True, False), ("(Ljava/util/Locale;)Landroid/text/method/DateKeyListener;", True, False)])
    getInputType = JavaMethod("()I")

class TextKeyListener(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "android/text/method/TextKeyListener"
    __javaconstructor__ = [("(Landroid/text/method/TextKeyListener$Capitalize;Z)V", False)]
    META_ALT_LOCKED = JavaStaticField("I")
    META_ALT_ON = JavaStaticField("I")
    META_CAP_LOCKED = JavaStaticField("I")
    META_SHIFT_ON = JavaStaticField("I")
    META_SYM_LOCKED = JavaStaticField("I")
    META_SYM_ON = JavaStaticField("I")
    onSpanAdded = JavaMethod("(Landroid/text/Spannable;Ljava/lang/Object;II)V")
    onSpanRemoved = JavaMethod("(Landroid/text/Spannable;Ljava/lang/Object;II)V")
    onSpanChanged = JavaMethod("(Landroid/text/Spannable;Ljava/lang/Object;IIII)V")
    shouldCap = JavaStaticMethod("(Landroid/text/method/TextKeyListener$Capitalize;Ljava/lang/CharSequence;I)Z")
    clear = JavaStaticMethod("(Landroid/text/Editable;)V")
    getInstance = JavaMultipleMethod([("(ZLandroid/text/method/TextKeyListener$Capitalize;)Landroid/text/method/TextKeyListener;", True, False), ("()Landroid/text/method/TextKeyListener;", True, False)])
    onKeyOther = JavaMethod("(Landroid/view/View;Landroid/text/Editable;Landroid/view/KeyEvent;)Z")
    onKeyDown = JavaMethod("(Landroid/view/View;Landroid/text/Editable;ILandroid/view/KeyEvent;)Z")
    onKeyUp = JavaMethod("(Landroid/view/View;Landroid/text/Editable;ILandroid/view/KeyEvent;)Z")
    getInputType = JavaMethod("()I")
    release = JavaMethod("()V")

    class Capitalize(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "android/text/method/TextKeyListener$Capitalize"
        CHARACTERS = JavaStaticField("Landroid/text/method/TextKeyListener$Capitalize;")
        NONE = JavaStaticField("Landroid/text/method/TextKeyListener$Capitalize;")
        SENTENCES = JavaStaticField("Landroid/text/method/TextKeyListener$Capitalize;")
        WORDS = JavaStaticField("Landroid/text/method/TextKeyListener$Capitalize;")
        values = JavaStaticMethod("()[Landroid/text/method/TextKeyListener$Capitalize;")
        valueOf = JavaStaticMethod("(Ljava/lang/String;)Landroid/text/method/TextKeyListener$Capitalize;")
        CHARACTERS = JavaStaticField("Landroid/text/method/TextKeyListener$Capitalize;")
        NONE = JavaStaticField("Landroid/text/method/TextKeyListener$Capitalize;")
        SENTENCES = JavaStaticField("Landroid/text/method/TextKeyListener$Capitalize;")
        WORDS = JavaStaticField("Landroid/text/method/TextKeyListener$Capitalize;")

class DateTimeKeyListener(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "android/text/method/DateTimeKeyListener"
    __javaconstructor__ = [("()V", False), ("(Ljava/util/Locale;)V", False)]
    CHARACTERS = JavaStaticField("[C")
    META_ALT_LOCKED = JavaStaticField("I")
    META_ALT_ON = JavaStaticField("I")
    META_CAP_LOCKED = JavaStaticField("I")
    META_SHIFT_ON = JavaStaticField("I")
    META_SYM_LOCKED = JavaStaticField("I")
    META_SYM_ON = JavaStaticField("I")
    getInstance = JavaMultipleMethod([("()Landroid/text/method/DateTimeKeyListener;", True, False), ("(Ljava/util/Locale;)Landroid/text/method/DateTimeKeyListener;", True, False)])
    getInputType = JavaMethod("()I")

class PasswordTransformationMethod(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "android/text/method/PasswordTransformationMethod"
    __javaconstructor__ = [("()V", False)]
    getInstance = JavaStaticMethod("()Landroid/text/method/PasswordTransformationMethod;")
    getTransformation = JavaMethod("(Ljava/lang/CharSequence;Landroid/view/View;)Ljava/lang/CharSequence;")
    onFocusChanged = JavaMethod("(Landroid/view/View;Ljava/lang/CharSequence;ZILandroid/graphics/Rect;)V")
    afterTextChanged = JavaMethod("(Landroid/text/Editable;)V")
    beforeTextChanged = JavaMethod("(Ljava/lang/CharSequence;III)V")
    onTextChanged = JavaMethod("(Ljava/lang/CharSequence;III)V")