from typing import Any, ClassVar, overload
from java.net.SocketAddress import SocketAddress
from java.net.SocketOption import SocketOption

class NetworkChannel:
    def getLocalAddress(self) -> SocketAddress: ...
    def setOption(self, p0: SocketOption, p1: Any) -> "NetworkChannel": ...
    def getOption(self, p0: SocketOption) -> Any: ...
    def supportedOptions(self) -> set: ...
    def bind(self, p0: SocketAddress) -> "NetworkChannel": ...
