from typing import Any, ClassVar, overload
from java.math.BigInteger import BigInteger
from java.security.spec.ECField import ECField

class EllipticCurve:
    @overload
    def __init__(self, p0: ECField, p1: BigInteger, p2: BigInteger) -> None: ...
    @overload
    def __init__(self, p0: ECField, p1: BigInteger, p2: BigInteger, p3: Any) -> None: ...
    def getA(self) -> BigInteger: ...
    def getB(self) -> BigInteger: ...
    def equals(self, p0: Any) -> bool: ...
    def hashCode(self) -> int: ...
    def getField(self) -> ECField: ...
    def getSeed(self) -> Any: ...
