from typing import Any, ClassVar, overload
from java.math.BigInteger import BigInteger
from java.security.spec.AlgorithmParameterSpec import AlgorithmParameterSpec

class RSAPrivateKeySpec:
    @overload
    def __init__(self, p0: BigInteger, p1: BigInteger) -> None: ...
    @overload
    def __init__(self, p0: BigInteger, p1: BigInteger, p2: AlgorithmParameterSpec) -> None: ...
    def getParams(self) -> AlgorithmParameterSpec: ...
    def getModulus(self) -> BigInteger: ...
    def getPrivateExponent(self) -> BigInteger: ...
