from typing import Any, ClassVar, overload
from java.math.BigInteger import BigInteger
from java.security.spec.AlgorithmParameterSpec import AlgorithmParameterSpec

class XECPublicKeySpec:
    def __init__(self, p0: AlgorithmParameterSpec, p1: BigInteger) -> None: ...
    def getParams(self) -> AlgorithmParameterSpec: ...
    def getU(self) -> BigInteger: ...
