from typing import Any, ClassVar, overload
from android.accessibilityservice.AccessibilityService import AccessibilityService
from android.view.KeyEvent import KeyEvent
from android.view.inputmethod.EditorInfo import EditorInfo
from android.view.inputmethod.SurroundingText import SurroundingText
from android.view.inputmethod.TextAttribute import TextAttribute

class InputMethod:
    def __init__(self, p0: AccessibilityService) -> None: ...
    def getCurrentInputConnection(self) -> Any: ...
    def getCurrentInputStarted(self) -> bool: ...
    def getCurrentInputEditorInfo(self) -> EditorInfo: ...
    def onStartInput(self, p0: EditorInfo, p1: bool) -> None: ...
    def onFinishInput(self) -> None: ...
    def onUpdateSelection(self, p0: int, p1: int, p2: int, p3: int, p4: int, p5: int) -> None: ...

    class AccessibilityInputConnection:
        def setSelection(self, p0: int, p1: int) -> None: ...
        def getSurroundingText(self, p0: int, p1: int, p2: int) -> SurroundingText: ...
        def getCursorCapsMode(self, p0: int) -> int: ...
        def deleteSurroundingText(self, p0: int, p1: int) -> None: ...
        def commitText(self, p0: str, p1: int, p2: TextAttribute) -> None: ...
        def performEditorAction(self, p0: int) -> None: ...
        def performContextMenuAction(self, p0: int) -> None: ...
        def sendKeyEvent(self, p0: KeyEvent) -> None: ...
        def clearMetaKeyStates(self, p0: int) -> None: ...
