from typing import Any, ClassVar, overload

class FloatEvaluator:
    def __init__(self) -> None: ...
    @overload
    def evaluate(self, p0: float, p1: float, p2: float) -> float: ...
    @overload
    def evaluate(self, p0: float, p1: Any, p2: Any) -> Any: ...
