from typing import Any, ClassVar, overload

class IntEvaluator:
    def __init__(self) -> None: ...
    @overload
    def evaluate(self, p0: float, p1: int, p2: int) -> int: ...
    @overload
    def evaluate(self, p0: float, p1: Any, p2: Any) -> Any: ...
