from typing import Any, ClassVar, overload
from android.animation.TypeConverter import TypeConverter
from android.animation.TypeEvaluator import TypeEvaluator
from android.graphics.Path import Path
from android.util.Property import Property

class PropertyValuesHolder:
    @overload
    @staticmethod
    def ofKeyframe(p0: Property, p1: Any) -> "PropertyValuesHolder": ...
    @overload
    @staticmethod
    def ofKeyframe(p0: str, p1: Any) -> "PropertyValuesHolder": ...
    def setConverter(self, p0: TypeConverter) -> None: ...
    def setKeyframes(self, p0: Any) -> None: ...
    def toString(self) -> str: ...
    @overload
    def clone(self) -> Any: ...
    @overload
    def clone(self) -> "PropertyValuesHolder": ...
    def setProperty(self, p0: Property) -> None: ...
    @overload
    @staticmethod
    def ofMultiFloat(p0: str, p1: Path) -> "PropertyValuesHolder": ...
    @overload
    @staticmethod
    def ofMultiFloat(p0: str, p1: Any) -> "PropertyValuesHolder": ...
    @overload
    @staticmethod
    def ofMultiFloat(p0: str, p1: TypeConverter, p2: TypeEvaluator, p3: Any) -> "PropertyValuesHolder": ...
    @overload
    @staticmethod
    def ofMultiFloat(p0: str, p1: TypeConverter, p2: TypeEvaluator, p3: Any) -> "PropertyValuesHolder": ...
    def setPropertyName(self, p0: str) -> None: ...
    @overload
    @staticmethod
    def ofInt(p0: str, p1: Any) -> "PropertyValuesHolder": ...
    @overload
    @staticmethod
    def ofInt(p0: Property, p1: Any) -> "PropertyValuesHolder": ...
    @overload
    @staticmethod
    def ofObject(p0: str, p1: TypeConverter, p2: Path) -> "PropertyValuesHolder": ...
    @overload
    @staticmethod
    def ofObject(p0: Property, p1: TypeConverter, p2: TypeEvaluator, p3: Any) -> "PropertyValuesHolder": ...
    @overload
    @staticmethod
    def ofObject(p0: str, p1: TypeEvaluator, p2: Any) -> "PropertyValuesHolder": ...
    @overload
    @staticmethod
    def ofObject(p0: Property, p1: TypeConverter, p2: Path) -> "PropertyValuesHolder": ...
    @overload
    @staticmethod
    def ofObject(p0: Property, p1: TypeEvaluator, p2: Any) -> "PropertyValuesHolder": ...
    @overload
    @staticmethod
    def ofMultiInt(p0: str, p1: Path) -> "PropertyValuesHolder": ...
    @overload
    @staticmethod
    def ofMultiInt(p0: str, p1: Any) -> "PropertyValuesHolder": ...
    @overload
    @staticmethod
    def ofMultiInt(p0: str, p1: TypeConverter, p2: TypeEvaluator, p3: Any) -> "PropertyValuesHolder": ...
    @overload
    @staticmethod
    def ofMultiInt(p0: str, p1: TypeConverter, p2: TypeEvaluator, p3: Any) -> "PropertyValuesHolder": ...
    def setObjectValues(self, p0: Any) -> None: ...
    def setIntValues(self, p0: Any) -> None: ...
    def setFloatValues(self, p0: Any) -> None: ...
    @overload
    @staticmethod
    def ofFloat(p0: str, p1: Any) -> "PropertyValuesHolder": ...
    @overload
    @staticmethod
    def ofFloat(p0: Property, p1: Any) -> "PropertyValuesHolder": ...
    def getPropertyName(self) -> str: ...
    def setEvaluator(self, p0: TypeEvaluator) -> None: ...
