from typing import Any, ClassVar, overload
from android.renderscript.RenderScript import RenderScript

class Element:
    def isComplex(self) -> bool: ...
    @staticmethod
    def A_8(p0: RenderScript) -> "Element": ...
    @staticmethod
    def RGBA_4444(p0: RenderScript) -> "Element": ...
    @staticmethod
    def RGBA_5551(p0: RenderScript) -> "Element": ...
    @staticmethod
    def F16_3(p0: RenderScript) -> "Element": ...
    @staticmethod
    def F16_2(p0: RenderScript) -> "Element": ...
    @staticmethod
    def F32_2(p0: RenderScript) -> "Element": ...
    @staticmethod
    def F64_2(p0: RenderScript) -> "Element": ...
    @staticmethod
    def F32_4(p0: RenderScript) -> "Element": ...
    @staticmethod
    def F64_3(p0: RenderScript) -> "Element": ...
    @staticmethod
    def F32(p0: RenderScript) -> "Element": ...
    @staticmethod
    def F64(p0: RenderScript) -> "Element": ...
    @staticmethod
    def FONT(p0: RenderScript) -> "Element": ...
    @staticmethod
    def I16_2(p0: RenderScript) -> "Element": ...
    @staticmethod
    def F16_4(p0: RenderScript) -> "Element": ...
    @staticmethod
    def F16(p0: RenderScript) -> "Element": ...
    @staticmethod
    def I16(p0: RenderScript) -> "Element": ...
    @staticmethod
    def ALLOCATION(p0: RenderScript) -> "Element": ...
    @staticmethod
    def F64_4(p0: RenderScript) -> "Element": ...
    @staticmethod
    def I8_2(p0: RenderScript) -> "Element": ...
    @staticmethod
    def I8_3(p0: RenderScript) -> "Element": ...
    @staticmethod
    def I8_4(p0: RenderScript) -> "Element": ...
    @staticmethod
    def MATRIX4X4(p0: RenderScript) -> "Element": ...
    @staticmethod
    def MATRIX_2X2(p0: RenderScript) -> "Element": ...
    @staticmethod
    def MATRIX_3X3(p0: RenderScript) -> "Element": ...
    @staticmethod
    def MATRIX_4X4(p0: RenderScript) -> "Element": ...
    @staticmethod
    def MESH(p0: RenderScript) -> "Element": ...
    @staticmethod
    def PROGRAM_FRAGMENT(p0: RenderScript) -> "Element": ...
    @staticmethod
    def PROGRAM_RASTER(p0: RenderScript) -> "Element": ...
    @staticmethod
    def I16_4(p0: RenderScript) -> "Element": ...
    @staticmethod
    def I32(p0: RenderScript) -> "Element": ...
    @staticmethod
    def F32_3(p0: RenderScript) -> "Element": ...
    @staticmethod
    def ELEMENT(p0: RenderScript) -> "Element": ...
    @staticmethod
    def I16_3(p0: RenderScript) -> "Element": ...
    @staticmethod
    def U8(p0: RenderScript) -> "Element": ...
    @staticmethod
    def I32_2(p0: RenderScript) -> "Element": ...
    @staticmethod
    def I32_3(p0: RenderScript) -> "Element": ...
    @staticmethod
    def I8(p0: RenderScript) -> "Element": ...
    @staticmethod
    def I32_4(p0: RenderScript) -> "Element": ...
    @staticmethod
    def I64(p0: RenderScript) -> "Element": ...
    @staticmethod
    def I64_2(p0: RenderScript) -> "Element": ...
    @staticmethod
    def I64_3(p0: RenderScript) -> "Element": ...
    @staticmethod
    def I64_4(p0: RenderScript) -> "Element": ...
    @staticmethod
    def PROGRAM_STORE(p0: RenderScript) -> "Element": ...
    @staticmethod
    def PROGRAM_VERTEX(p0: RenderScript) -> "Element": ...
    @staticmethod
    def SAMPLER(p0: RenderScript) -> "Element": ...
    @staticmethod
    def SCRIPT(p0: RenderScript) -> "Element": ...
    @staticmethod
    def U16(p0: RenderScript) -> "Element": ...
    @staticmethod
    def U16_2(p0: RenderScript) -> "Element": ...
    @staticmethod
    def U16_3(p0: RenderScript) -> "Element": ...
    @staticmethod
    def U16_4(p0: RenderScript) -> "Element": ...
    @staticmethod
    def U32(p0: RenderScript) -> "Element": ...
    @staticmethod
    def U32_2(p0: RenderScript) -> "Element": ...
    @staticmethod
    def U32_3(p0: RenderScript) -> "Element": ...
    @staticmethod
    def U32_4(p0: RenderScript) -> "Element": ...
    @staticmethod
    def U64(p0: RenderScript) -> "Element": ...
    @staticmethod
    def U64_2(p0: RenderScript) -> "Element": ...
    @staticmethod
    def U64_3(p0: RenderScript) -> "Element": ...
    @staticmethod
    def U64_4(p0: RenderScript) -> "Element": ...
    @staticmethod
    def U8_2(p0: RenderScript) -> "Element": ...
    @staticmethod
    def U8_3(p0: RenderScript) -> "Element": ...
    @staticmethod
    def U8_4(p0: RenderScript) -> "Element": ...
    @staticmethod
    def YUV(p0: RenderScript) -> "Element": ...
    @staticmethod
    def createPixel(p0: RenderScript, p1: Any, p2: Any) -> "Element": ...
    @staticmethod
    def createVector(p0: RenderScript, p1: Any, p2: int) -> "Element": ...
    def getDataKind(self) -> Any: ...
    def getSubElement(self, p0: int) -> "Element": ...
    def getSubElementArraySize(self, p0: int) -> int: ...
    def getSubElementCount(self) -> int: ...
    def getSubElementName(self, p0: int) -> str: ...
    def getSubElementOffsetBytes(self, p0: int) -> int: ...
    def getVectorSize(self) -> int: ...
    def isCompatible(self, p0: "Element") -> bool: ...
    def getBytesSize(self) -> int: ...
    @staticmethod
    def TYPE(p0: RenderScript) -> "Element": ...
    @staticmethod
    def BOOLEAN(p0: RenderScript) -> "Element": ...
    @staticmethod
    def RGBA_8888(p0: RenderScript) -> "Element": ...
    @staticmethod
    def RGB_565(p0: RenderScript) -> "Element": ...
    @staticmethod
    def RGB_888(p0: RenderScript) -> "Element": ...
    def getDataType(self) -> Any: ...

    class DataType:
        BOOLEAN: ClassVar["DataType"]
        FLOAT_16: ClassVar["DataType"]
        FLOAT_32: ClassVar["DataType"]
        FLOAT_64: ClassVar["DataType"]
        MATRIX_2X2: ClassVar["DataType"]
        MATRIX_3X3: ClassVar["DataType"]
        MATRIX_4X4: ClassVar["DataType"]
        NONE: ClassVar["DataType"]
        RS_ALLOCATION: ClassVar["DataType"]
        RS_ELEMENT: ClassVar["DataType"]
        RS_FONT: ClassVar["DataType"]
        RS_MESH: ClassVar["DataType"]
        RS_PROGRAM_FRAGMENT: ClassVar["DataType"]
        RS_PROGRAM_RASTER: ClassVar["DataType"]
        RS_PROGRAM_STORE: ClassVar["DataType"]
        RS_PROGRAM_VERTEX: ClassVar["DataType"]
        RS_SAMPLER: ClassVar["DataType"]
        RS_SCRIPT: ClassVar["DataType"]
        RS_TYPE: ClassVar["DataType"]
        SIGNED_16: ClassVar["DataType"]
        SIGNED_32: ClassVar["DataType"]
        SIGNED_64: ClassVar["DataType"]
        SIGNED_8: ClassVar["DataType"]
        UNSIGNED_16: ClassVar["DataType"]
        UNSIGNED_32: ClassVar["DataType"]
        UNSIGNED_4_4_4_4: ClassVar["DataType"]
        UNSIGNED_5_5_5_1: ClassVar["DataType"]
        UNSIGNED_5_6_5: ClassVar["DataType"]
        UNSIGNED_64: ClassVar["DataType"]
        UNSIGNED_8: ClassVar["DataType"]
        BOOLEAN: ClassVar[Any]
        FLOAT_16: ClassVar[Any]
        FLOAT_32: ClassVar[Any]
        FLOAT_64: ClassVar[Any]
        MATRIX_2X2: ClassVar[Any]
        MATRIX_3X3: ClassVar[Any]
        MATRIX_4X4: ClassVar[Any]
        NONE: ClassVar[Any]
        RS_ALLOCATION: ClassVar[Any]
        RS_ELEMENT: ClassVar[Any]
        RS_FONT: ClassVar[Any]
        RS_MESH: ClassVar[Any]
        RS_PROGRAM_FRAGMENT: ClassVar[Any]
        RS_PROGRAM_RASTER: ClassVar[Any]
        RS_PROGRAM_STORE: ClassVar[Any]
        RS_PROGRAM_VERTEX: ClassVar[Any]
        RS_SAMPLER: ClassVar[Any]
        RS_SCRIPT: ClassVar[Any]
        RS_TYPE: ClassVar[Any]
        SIGNED_16: ClassVar[Any]
        SIGNED_32: ClassVar[Any]
        SIGNED_64: ClassVar[Any]
        SIGNED_8: ClassVar[Any]
        UNSIGNED_16: ClassVar[Any]
        UNSIGNED_32: ClassVar[Any]
        UNSIGNED_4_4_4_4: ClassVar[Any]
        UNSIGNED_5_5_5_1: ClassVar[Any]
        UNSIGNED_5_6_5: ClassVar[Any]
        UNSIGNED_64: ClassVar[Any]
        UNSIGNED_8: ClassVar[Any]
        @staticmethod
        def values() -> Any: ...
        @staticmethod
        def valueOf(p0: str) -> Any: ...

    class DataKind:
        PIXEL_A: ClassVar["DataKind"]
        PIXEL_DEPTH: ClassVar["DataKind"]
        PIXEL_L: ClassVar["DataKind"]
        PIXEL_LA: ClassVar["DataKind"]
        PIXEL_RGB: ClassVar["DataKind"]
        PIXEL_RGBA: ClassVar["DataKind"]
        PIXEL_YUV: ClassVar["DataKind"]
        USER: ClassVar["DataKind"]
        PIXEL_A: ClassVar[Any]
        PIXEL_DEPTH: ClassVar[Any]
        PIXEL_L: ClassVar[Any]
        PIXEL_LA: ClassVar[Any]
        PIXEL_RGB: ClassVar[Any]
        PIXEL_RGBA: ClassVar[Any]
        PIXEL_YUV: ClassVar[Any]
        USER: ClassVar[Any]
        @staticmethod
        def values() -> Any: ...
        @staticmethod
        def valueOf(p0: str) -> Any: ...

    class Builder:
        def __init__(self, p0: RenderScript) -> None: ...
        @overload
        def add(self, p0: "Element", p1: str, p2: int) -> Any: ...
        @overload
        def add(self, p0: "Element", p1: str) -> Any: ...
        def create(self) -> "Element": ...
