# cython: language_level=3
# Generated by jni-wrap cython — do not edit by hand.

from jni_core._core cimport (
    JavaObject, get_env, check_jni_exc,
    find_class_global, get_method_id, get_static_method_id,
    get_field_id, get_static_field_id, j_str, py_str,
)
from jni_core._dispatch cimport (
    jnicore_NewObjectA, jnicore_DeleteLocalRef, jnicore_NewGlobalRef,
    jnicore_CallVoidMethodA, jnicore_CallObjectMethodA,
    jnicore_CallBooleanMethodA, jnicore_CallByteMethodA,
    jnicore_CallCharMethodA, jnicore_CallShortMethodA,
    jnicore_CallIntMethodA, jnicore_CallLongMethodA,
    jnicore_CallFloatMethodA, jnicore_CallDoubleMethodA,
    jnicore_CallStaticVoidMethodA, jnicore_CallStaticObjectMethodA,
    jnicore_CallStaticBooleanMethodA, jnicore_CallStaticByteMethodA,
    jnicore_CallStaticCharMethodA, jnicore_CallStaticShortMethodA,
    jnicore_CallStaticIntMethodA, jnicore_CallStaticLongMethodA,
    jnicore_CallStaticFloatMethodA, jnicore_CallStaticDoubleMethodA,
    jnicore_GetObjectField, jnicore_SetObjectField,
    jnicore_GetBooleanField, jnicore_SetBooleanField,
    jnicore_GetByteField, jnicore_SetByteField,
    jnicore_GetCharField, jnicore_SetCharField,
    jnicore_GetShortField, jnicore_SetShortField,
    jnicore_GetIntField, jnicore_SetIntField,
    jnicore_GetLongField, jnicore_SetLongField,
    jnicore_GetFloatField, jnicore_SetFloatField,
    jnicore_GetDoubleField, jnicore_SetDoubleField,
    jnicore_GetStaticObjectField, jnicore_SetStaticObjectField,
    jnicore_GetStaticBooleanField, jnicore_SetStaticBooleanField,
    jnicore_GetStaticByteField, jnicore_SetStaticByteField,
    jnicore_GetStaticCharField, jnicore_SetStaticCharField,
    jnicore_GetStaticShortField, jnicore_SetStaticShortField,
    jnicore_GetStaticIntField, jnicore_SetStaticIntField,
    jnicore_GetStaticLongField, jnicore_SetStaticLongField,
    jnicore_GetStaticFloatField, jnicore_SetStaticFloatField,
    jnicore_GetStaticDoubleField, jnicore_SetStaticDoubleField,
)
from jni_core.jni cimport (
    jclass, jobject, jmethodID, jfieldID, jvalue, JNIEnv,
    jboolean, jbyte, jchar, jshort, jint, jlong, jfloat, jdouble, jstring,
)

include "jni_core/conversions.pxi"

__javaclass__ = "android/renderscript/Int4"  # android.renderscript.Int4

cdef jclass _cls_Int4 = NULL
cdef jmethodID _ctor_Int4_0 = NULL
cdef jmethodID _ctor_Int4_1 = NULL
cdef jfieldID _f_Int4_w = NULL
cdef jfieldID _f_Int4_x = NULL
cdef jfieldID _f_Int4_y = NULL
cdef jfieldID _f_Int4_z = NULL

cdef int _ensure_ids_Int4(JNIEnv* env) except -1:
    global _cls_Int4, _ctor_Int4_0, _ctor_Int4_1, _f_Int4_w, _f_Int4_x, _f_Int4_y, _f_Int4_z
    if _cls_Int4 != NULL:
        return 0
    _cls_Int4 = find_class_global(env, b"android/renderscript/Int4")
    _ctor_Int4_0 = get_method_id(env, _cls_Int4, b"<init>", b"()V")
    _ctor_Int4_1 = get_method_id(env, _cls_Int4, b"<init>", b"(IIII)V")
    _f_Int4_w = get_field_id(env, _cls_Int4, b"w", b"I")
    _f_Int4_x = get_field_id(env, _cls_Int4, b"x", b"I")
    _f_Int4_y = get_field_id(env, _cls_Int4, b"y", b"I")
    _f_Int4_z = get_field_id(env, _cls_Int4, b"z", b"I")
    return 0

cdef class Int4(JavaObject):
    """android.renderscript.Int4"""

    # TODO: 2 constructor overloads; only the first is wired.
    #   overload[0] = ()V
    #   overload[1] = (IIII)V
    def __init__(self, ):
        cdef JNIEnv* env = get_env()
        _ensure_ids_Int4(env)
        cdef jvalue _args[1]  # unused; arrayless calls disallowed in Cython
        cdef jobject _ret = jnicore_NewObjectA(env, _cls_Int4, _ctor_Int4_0, _args)
        check_jni_exc(env)
        self._adopt_local(env, _ret)

    @property
    def w(self) -> int:
        cdef JNIEnv* env = get_env()
        _ensure_ids_Int4(env)
        cdef jint _ret = jnicore_GetIntField(env, self._handle, _f_Int4_w)
        check_jni_exc(env)
        return <int>_ret

    @w.setter
    def w(self, value) -> None:
        cdef JNIEnv* env = get_env()
        _ensure_ids_Int4(env)
        jnicore_SetIntField(env, self._handle, _f_Int4_w, py_to_jint(value))
        check_jni_exc(env)

    @property
    def x(self) -> int:
        cdef JNIEnv* env = get_env()
        _ensure_ids_Int4(env)
        cdef jint _ret = jnicore_GetIntField(env, self._handle, _f_Int4_x)
        check_jni_exc(env)
        return <int>_ret

    @x.setter
    def x(self, value) -> None:
        cdef JNIEnv* env = get_env()
        _ensure_ids_Int4(env)
        jnicore_SetIntField(env, self._handle, _f_Int4_x, py_to_jint(value))
        check_jni_exc(env)

    @property
    def y(self) -> int:
        cdef JNIEnv* env = get_env()
        _ensure_ids_Int4(env)
        cdef jint _ret = jnicore_GetIntField(env, self._handle, _f_Int4_y)
        check_jni_exc(env)
        return <int>_ret

    @y.setter
    def y(self, value) -> None:
        cdef JNIEnv* env = get_env()
        _ensure_ids_Int4(env)
        jnicore_SetIntField(env, self._handle, _f_Int4_y, py_to_jint(value))
        check_jni_exc(env)

    @property
    def z(self) -> int:
        cdef JNIEnv* env = get_env()
        _ensure_ids_Int4(env)
        cdef jint _ret = jnicore_GetIntField(env, self._handle, _f_Int4_z)
        check_jni_exc(env)
        return <int>_ret

    @z.setter
    def z(self, value) -> None:
        cdef JNIEnv* env = get_env()
        _ensure_ids_Int4(env)
        jnicore_SetIntField(env, self._handle, _f_Int4_z, py_to_jint(value))
        check_jni_exc(env)

    @staticmethod
    def from_java_object(obj) -> object:
        """Wrap a plain JavaObject as Int4 (no JNI type check)."""
        cdef JNIEnv* env = get_env()
        cdef Int4 inst = Int4.__new__(Int4)
        cdef jobject global_ref = jnicore_NewGlobalRef(env, (<JavaObject?>obj)._handle)
        inst._adopt_global(env, global_ref)
        return inst

