from typing import Any, ClassVar, overload
from android.renderscript.Allocation import Allocation
from android.renderscript.Element import Element
from android.renderscript.RenderScript import RenderScript

class ScriptIntrinsicBlend:
    @overload
    def forEachDstOver(self, p0: Allocation, p1: Allocation) -> None: ...
    @overload
    def forEachDstOver(self, p0: Allocation, p1: Allocation, p2: Any) -> None: ...
    @overload
    def forEachDstIn(self, p0: Allocation, p1: Allocation, p2: Any) -> None: ...
    @overload
    def forEachDstIn(self, p0: Allocation, p1: Allocation) -> None: ...
    @overload
    def forEachDstAtop(self, p0: Allocation, p1: Allocation) -> None: ...
    @overload
    def forEachDstAtop(self, p0: Allocation, p1: Allocation, p2: Any) -> None: ...
    @overload
    def forEachAdd(self, p0: Allocation, p1: Allocation, p2: Any) -> None: ...
    @overload
    def forEachAdd(self, p0: Allocation, p1: Allocation) -> None: ...
    @overload
    def forEachClear(self, p0: Allocation, p1: Allocation, p2: Any) -> None: ...
    @overload
    def forEachClear(self, p0: Allocation, p1: Allocation) -> None: ...
    @overload
    def forEachSrcIn(self, p0: Allocation, p1: Allocation) -> None: ...
    @overload
    def forEachSrcIn(self, p0: Allocation, p1: Allocation, p2: Any) -> None: ...
    @overload
    def forEachDst(self, p0: Allocation, p1: Allocation) -> None: ...
    @overload
    def forEachDst(self, p0: Allocation, p1: Allocation, p2: Any) -> None: ...
    def getKernelIDSrcAtop(self) -> Any: ...
    def getKernelIDSrcIn(self) -> Any: ...
    def getKernelIDSrcOut(self) -> Any: ...
    def getKernelIDSrcOver(self) -> Any: ...
    def getKernelIDSubtract(self) -> Any: ...
    def getKernelIDXor(self) -> Any: ...
    @overload
    def forEachMultiply(self, p0: Allocation, p1: Allocation, p2: Any) -> None: ...
    @overload
    def forEachMultiply(self, p0: Allocation, p1: Allocation) -> None: ...
    @overload
    def forEachSrcAtop(self, p0: Allocation, p1: Allocation) -> None: ...
    @overload
    def forEachSrcAtop(self, p0: Allocation, p1: Allocation, p2: Any) -> None: ...
    @overload
    def forEachSrc(self, p0: Allocation, p1: Allocation, p2: Any) -> None: ...
    @overload
    def forEachSrc(self, p0: Allocation, p1: Allocation) -> None: ...
    @overload
    def forEachSrcOver(self, p0: Allocation, p1: Allocation, p2: Any) -> None: ...
    @overload
    def forEachSrcOver(self, p0: Allocation, p1: Allocation) -> None: ...
    @overload
    def forEachSubtract(self, p0: Allocation, p1: Allocation) -> None: ...
    @overload
    def forEachSubtract(self, p0: Allocation, p1: Allocation, p2: Any) -> None: ...
    @overload
    def forEachXor(self, p0: Allocation, p1: Allocation) -> None: ...
    @overload
    def forEachXor(self, p0: Allocation, p1: Allocation, p2: Any) -> None: ...
    @overload
    def forEachSrcOut(self, p0: Allocation, p1: Allocation, p2: Any) -> None: ...
    @overload
    def forEachSrcOut(self, p0: Allocation, p1: Allocation) -> None: ...
    @overload
    def forEachDstOut(self, p0: Allocation, p1: Allocation, p2: Any) -> None: ...
    @overload
    def forEachDstOut(self, p0: Allocation, p1: Allocation) -> None: ...
    def getKernelIDAdd(self) -> Any: ...
    def getKernelIDClear(self) -> Any: ...
    def getKernelIDDst(self) -> Any: ...
    def getKernelIDDstAtop(self) -> Any: ...
    def getKernelIDDstIn(self) -> Any: ...
    def getKernelIDDstOut(self) -> Any: ...
    def getKernelIDDstOver(self) -> Any: ...
    def getKernelIDMultiply(self) -> Any: ...
    def getKernelIDSrc(self) -> Any: ...
    @staticmethod
    def create(p0: RenderScript, p1: Element) -> "ScriptIntrinsicBlend": ...
