from typing import Any, ClassVar, overload
from android.renderscript.Allocation import Allocation
from android.renderscript.Element import Element
from android.renderscript.RenderScript import RenderScript

class ScriptIntrinsicConvolve3x3:
    def getKernelID(self) -> Any: ...
    def setCoefficients(self, p0: Any) -> None: ...
    def getFieldID_Input(self) -> Any: ...
    @overload
    def forEach(self, p0: Allocation) -> None: ...
    @overload
    def forEach(self, p0: Allocation, p1: Any) -> None: ...
    @staticmethod
    def create(p0: RenderScript, p1: Element) -> "ScriptIntrinsicConvolve3x3": ...
    def setInput(self, p0: Allocation) -> None: ...
