from typing import Any, ClassVar, overload
from android.renderscript.Allocation import Allocation
from android.renderscript.BaseObj import BaseObj
from android.renderscript.Element import Element
from android.renderscript.FieldPacker import FieldPacker
from android.renderscript.Type import Type

class Script:
    def getVarB(self, p0: int) -> bool: ...
    def getVarD(self, p0: int) -> float: ...
    def bindAllocation(self, p0: Allocation, p1: int) -> None: ...
    def getVarF(self, p0: int) -> float: ...
    def getVarI(self, p0: int) -> int: ...
    def getVarJ(self, p0: int) -> int: ...
    def getVarV(self, p0: int, p1: FieldPacker) -> None: ...
    @overload
    def setVar(self, p0: int, p1: float) -> None: ...
    @overload
    def setVar(self, p0: int, p1: float) -> None: ...
    @overload
    def setVar(self, p0: int, p1: bool) -> None: ...
    @overload
    def setVar(self, p0: int, p1: int) -> None: ...
    @overload
    def setVar(self, p0: int, p1: int) -> None: ...
    @overload
    def setVar(self, p0: int, p1: BaseObj) -> None: ...
    @overload
    def setVar(self, p0: int, p1: FieldPacker) -> None: ...
    @overload
    def setVar(self, p0: int, p1: FieldPacker, p2: Element, p3: Any) -> None: ...
    def setTimeZone(self, p0: str) -> None: ...

    class LaunchOptions:
        def __init__(self) -> None: ...
        def getXEnd(self) -> int: ...
        def getXStart(self) -> int: ...
        def getYEnd(self) -> int: ...
        def getYStart(self) -> int: ...
        def getZEnd(self) -> int: ...
        def getZStart(self) -> int: ...
        def setX(self, p0: int, p1: int) -> Any: ...
        def setY(self, p0: int, p1: int) -> Any: ...
        def setZ(self, p0: int, p1: int) -> Any: ...

    class KernelID:
        ...

    class InvokeID:
        ...

    class FieldID:
        ...

    class FieldBase:
        def getElement(self) -> Element: ...
        def getAllocation(self) -> Allocation: ...
        def updateAllocation(self) -> None: ...
        def getType(self) -> Type: ...

    class Builder:
        ...
