from typing import Any, ClassVar, overload
from org.w3c.dom.Document import Document
from org.w3c.dom.DocumentType import DocumentType

class DOMImplementation:
    def createDocument(self, p0: str, p1: str, p2: DocumentType) -> Document: ...
    def getFeature(self, p0: str, p1: str) -> Any: ...
    def hasFeature(self, p0: str, p1: str) -> bool: ...
    def createDocumentType(self, p0: str, p1: str, p2: str) -> DocumentType: ...
