from typing import Any, ClassVar, overload
from android.graphics.Rect import Rect
from android.os.Parcel import Parcel

class FormWidgetInfo:
    CREATOR: ClassVar[Any]
    WIDGET_TYPE_CHECKBOX: ClassVar[int]
    WIDGET_TYPE_COMBOBOX: ClassVar[int]
    WIDGET_TYPE_LISTBOX: ClassVar[int]
    WIDGET_TYPE_PUSHBUTTON: ClassVar[int]
    WIDGET_TYPE_RADIOBUTTON: ClassVar[int]
    WIDGET_TYPE_SIGNATURE: ClassVar[int]
    WIDGET_TYPE_TEXTFIELD: ClassVar[int]
    WIDGET_TYPE_UNKNOWN: ClassVar[int]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    def getWidgetType(self) -> int: ...
    def getWidgetIndex(self) -> int: ...
    def getWidgetRect(self) -> Rect: ...
    def getAccessibilityLabel(self) -> str: ...
    def isEditableText(self) -> bool: ...
    def isMultiSelect(self) -> bool: ...
    def isMultiLineText(self) -> bool: ...
    def getMaxLength(self) -> int: ...
    def getFontSize(self) -> float: ...
    def equals(self, p0: Any) -> bool: ...
    def toString(self) -> str: ...
    def hashCode(self) -> int: ...
    def isReadOnly(self) -> bool: ...
    def getListItems(self) -> list: ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
    def getTextValue(self) -> str: ...

    class Builder:
        def __init__(self, p0: int, p1: int, p2: Rect, p3: str, p4: str) -> None: ...
        def setEditableText(self, p0: bool) -> Any: ...
        def setMultiSelect(self, p0: bool) -> Any: ...
        def setMultiLineText(self, p0: bool) -> Any: ...
        def setMaxLength(self, p0: int) -> Any: ...
        def setFontSize(self, p0: float) -> Any: ...
        def setListItems(self, p0: list) -> Any: ...
        def setReadOnly(self, p0: bool) -> Any: ...
        def build(self) -> "FormWidgetInfo": ...
