from typing import Any, ClassVar, overload
from android.graphics.Point import Point
from android.os.Parcel import Parcel

class FormEditRecord:
    CREATOR: ClassVar[Any]
    EDIT_TYPE_CLICK: ClassVar[int]
    EDIT_TYPE_SET_INDICES: ClassVar[int]
    EDIT_TYPE_SET_TEXT: ClassVar[int]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    def getPageNumber(self) -> int: ...
    def getWidgetIndex(self) -> int: ...
    def getClickPoint(self) -> Point: ...
    def getSelectedIndices(self) -> Any: ...
    def equals(self, p0: Any) -> bool: ...
    def hashCode(self) -> int: ...
    def getType(self) -> int: ...
    def getText(self) -> str: ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...

    class Builder:
        def __init__(self, p0: int, p1: int, p2: int) -> None: ...
        def setClickPoint(self, p0: Point) -> Any: ...
        def setSelectedIndices(self, p0: Any) -> Any: ...
        def build(self) -> "FormEditRecord": ...
        def setText(self, p0: str) -> Any: ...
