from jnius import JavaClass, MetaJavaClass, JavaMethod, JavaStaticMethod, JavaMultipleMethod, JavaField, JavaStaticField

__all__ = ["Collator"]

class Collator(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "android/icu/text/Collator"
    CANONICAL_DECOMPOSITION = JavaStaticField("I")
    FULL_DECOMPOSITION = JavaStaticField("I")
    IDENTICAL = JavaStaticField("I")
    NO_DECOMPOSITION = JavaStaticField("I")
    PRIMARY = JavaStaticField("I")
    QUATERNARY = JavaStaticField("I")
    SECONDARY = JavaStaticField("I")
    TERTIARY = JavaStaticField("I")
    cloneAsThawed = JavaMultipleMethod([("()Ljava/lang/Object;", False, False), ("()Landroid/icu/text/Collator;", False, False)])
    getAvailableULocales = JavaStaticMethod("()[Landroid/icu/util/ULocale;")
    getEquivalentReorderCodes = JavaStaticMethod("(I)[I")
    getFunctionalEquivalent = JavaMultipleMethod([("(Ljava/lang/String;Landroid/icu/util/ULocale;[Z)Landroid/icu/util/ULocale;", True, False), ("(Ljava/lang/String;Landroid/icu/util/ULocale;)Landroid/icu/util/ULocale;", True, False)])
    getKeywordValues = JavaStaticMethod("(Ljava/lang/String;)[Ljava/lang/String;")
    getMaxVariable = JavaMethod("()I")
    getReorderCodes = JavaMethod("()[I")
    getStrength = JavaMethod("()I")
    getTailoredSet = JavaMethod("()Landroid/icu/text/UnicodeSet;")
    getUCAVersion = JavaMethod("()Landroid/icu/util/VersionInfo;")
    getVariableTop = JavaMethod("()I")
    setDecomposition = JavaMethod("(I)V")
    setMaxVariable = JavaMethod("(I)Landroid/icu/text/Collator;")
    setReorderCodes = JavaMethod("([I)V", varargs=True)
    setStrength = JavaMethod("(I)V")
    getKeywordValuesForLocale = JavaStaticMethod("(Ljava/lang/String;Landroid/icu/util/ULocale;Z)[Ljava/lang/String;")
    equals = JavaMultipleMethod([("(Ljava/lang/Object;)Z", False, False), ("(Ljava/lang/String;Ljava/lang/String;)Z", False, False)])
    hashCode = JavaMethod("()I")
    clone = JavaMethod("()Ljava/lang/Object;")
    compare = JavaMultipleMethod([("(Ljava/lang/String;Ljava/lang/String;)I", False, False), ("(Ljava/lang/Object;Ljava/lang/Object;)I", False, False)])
    getInstance = JavaMultipleMethod([("(Landroid/icu/util/ULocale;)Landroid/icu/text/Collator;", True, False), ("(Ljava/util/Locale;)Landroid/icu/text/Collator;", True, False), ("()Landroid/icu/text/Collator;", True, False)])
    isFrozen = JavaMethod("()Z")
    getKeywords = JavaStaticMethod("()[Ljava/lang/String;")
    getDisplayName = JavaMultipleMethod([("(Ljava/util/Locale;)Ljava/lang/String;", True, False), ("(Landroid/icu/util/ULocale;Landroid/icu/util/ULocale;)Ljava/lang/String;", True, False), ("(Ljava/util/Locale;Ljava/util/Locale;)Ljava/lang/String;", True, False), ("(Landroid/icu/util/ULocale;)Ljava/lang/String;", True, False)])
    getAvailableLocales = JavaStaticMethod("()[Ljava/util/Locale;")
    getDecomposition = JavaMethod("()I")
    getCollationKey = JavaMethod("(Ljava/lang/String;)Landroid/icu/text/CollationKey;")
    getVersion = JavaMethod("()Landroid/icu/util/VersionInfo;")
    freeze = JavaMultipleMethod([("()Ljava/lang/Object;", False, False), ("()Landroid/icu/text/Collator;", False, False)])

    class ReorderCodes(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "android/icu/text/Collator$ReorderCodes"
        CURRENCY = JavaStaticField("I")
        DEFAULT = JavaStaticField("I")
        DIGIT = JavaStaticField("I")
        FIRST = JavaStaticField("I")
        NONE = JavaStaticField("I")
        OTHERS = JavaStaticField("I")
        PUNCTUATION = JavaStaticField("I")
        SPACE = JavaStaticField("I")
        SYMBOL = JavaStaticField("I")