from jnius import JavaClass, MetaJavaClass, JavaMethod, JavaStaticMethod, JavaMultipleMethod, JavaField, JavaStaticField

__all__ = ["DateTimePatternGenerator"]

class DateTimePatternGenerator(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "android/icu/text/DateTimePatternGenerator"
    DAY = JavaStaticField("I")
    DAYPERIOD = JavaStaticField("I")
    DAY_OF_WEEK_IN_MONTH = JavaStaticField("I")
    DAY_OF_YEAR = JavaStaticField("I")
    ERA = JavaStaticField("I")
    FRACTIONAL_SECOND = JavaStaticField("I")
    HOUR = JavaStaticField("I")
    MATCH_ALL_FIELDS_LENGTH = JavaStaticField("I")
    MATCH_HOUR_FIELD_LENGTH = JavaStaticField("I")
    MATCH_NO_OPTIONS = JavaStaticField("I")
    MINUTE = JavaStaticField("I")
    MONTH = JavaStaticField("I")
    QUARTER = JavaStaticField("I")
    SECOND = JavaStaticField("I")
    WEEKDAY = JavaStaticField("I")
    WEEK_OF_MONTH = JavaStaticField("I")
    WEEK_OF_YEAR = JavaStaticField("I")
    YEAR = JavaStaticField("I")
    ZONE = JavaStaticField("I")
    cloneAsThawed = JavaMultipleMethod([("()Ljava/lang/Object;", False, False), ("()Landroid/icu/text/DateTimePatternGenerator;", False, False)])
    addPattern = JavaMethod("(Ljava/lang/String;ZLandroid/icu/text/DateTimePatternGenerator$PatternInfo;)Landroid/icu/text/DateTimePatternGenerator;")
    getAppendItemFormat = JavaMethod("(I)Ljava/lang/String;")
    getAppendItemName = JavaMethod("(I)Ljava/lang/String;")
    getBaseSkeleton = JavaMethod("(Ljava/lang/String;)Ljava/lang/String;")
    getBaseSkeletons = JavaMethod("(Ljava/util/Set;)Ljava/util/Set;")
    getBestPattern = JavaMultipleMethod([("(Ljava/lang/String;)Ljava/lang/String;", False, False), ("(Ljava/lang/String;I)Ljava/lang/String;", False, False)])
    getDecimal = JavaMethod("()Ljava/lang/String;")
    getDefaultHourCycle = JavaMethod("()Landroid/icu/text/DateFormat$HourCycle;")
    getEmptyInstance = JavaStaticMethod("()Landroid/icu/text/DateTimePatternGenerator;")
    getFieldDisplayName = JavaMethod("(ILandroid/icu/text/DateTimePatternGenerator$DisplayWidth;)Ljava/lang/String;")
    getSkeleton = JavaMethod("(Ljava/lang/String;)Ljava/lang/String;")
    getSkeletons = JavaMethod("(Ljava/util/Map;)Ljava/util/Map;")
    replaceFieldTypes = JavaMultipleMethod([("(Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;", False, False), ("(Ljava/lang/String;Ljava/lang/String;I)Ljava/lang/String;", False, False)])
    setAppendItemFormat = JavaMethod("(ILjava/lang/String;)V")
    setAppendItemName = JavaMethod("(ILjava/lang/String;)V")
    setDateTimeFormat = JavaMultipleMethod([("(ILjava/lang/String;)V", False, False), ("(Ljava/lang/String;)V", False, False)])
    setDecimal = JavaMethod("(Ljava/lang/String;)V")
    getDateTimeFormat = JavaMultipleMethod([("()Ljava/lang/String;", False, False), ("(I)Ljava/lang/String;", False, False)])
    clone = JavaMethod("()Ljava/lang/Object;")
    getInstance = JavaMultipleMethod([("(Ljava/util/Locale;)Landroid/icu/text/DateTimePatternGenerator;", True, False), ("()Landroid/icu/text/DateTimePatternGenerator;", True, False), ("(Landroid/icu/util/ULocale;)Landroid/icu/text/DateTimePatternGenerator;", True, False)])
    isFrozen = JavaMethod("()Z")
    freeze = JavaMultipleMethod([("()Ljava/lang/Object;", False, False), ("()Landroid/icu/text/DateTimePatternGenerator;", False, False)])

    class PatternInfo(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "android/icu/text/DateTimePatternGenerator$PatternInfo"
        __javaconstructor__ = [("()V", False)]
        BASE_CONFLICT = JavaStaticField("I")
        CONFLICT = JavaStaticField("I")
        OK = JavaStaticField("I")
        conflictingPattern = JavaField("Ljava/lang/String;")
        status = JavaField("I")

    class DisplayWidth(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "android/icu/text/DateTimePatternGenerator$DisplayWidth"
        ABBREVIATED = JavaStaticField("Landroid/icu/text/DateTimePatternGenerator$DisplayWidth;")
        NARROW = JavaStaticField("Landroid/icu/text/DateTimePatternGenerator$DisplayWidth;")
        WIDE = JavaStaticField("Landroid/icu/text/DateTimePatternGenerator$DisplayWidth;")
        values = JavaStaticMethod("()[Landroid/icu/text/DateTimePatternGenerator$DisplayWidth;")
        valueOf = JavaStaticMethod("(Ljava/lang/String;)Landroid/icu/text/DateTimePatternGenerator$DisplayWidth;")
        ABBREVIATED = JavaStaticField("Landroid/icu/text/DateTimePatternGenerator$DisplayWidth;")
        NARROW = JavaStaticField("Landroid/icu/text/DateTimePatternGenerator$DisplayWidth;")
        WIDE = JavaStaticField("Landroid/icu/text/DateTimePatternGenerator$DisplayWidth;")