from typing import Any, ClassVar, overload

class Replaceable:
    def char32At(self, p0: int) -> int: ...
    def hasMetaData(self) -> bool: ...
    def length(self) -> int: ...
    def getChars(self, p0: int, p1: int, p2: Any, p3: int) -> None: ...
    def charAt(self, p0: int) -> str: ...
    def copy(self, p0: int, p1: int, p2: int) -> None: ...
    @overload
    def replace(self, p0: int, p1: int, p2: Any, p3: int, p4: int) -> None: ...
    @overload
    def replace(self, p0: int, p1: int, p2: str) -> None: ...
