from typing import Any, ClassVar, overload
from android.icu.text.BreakIterator import BreakIterator
from java.text.CharacterIterator import CharacterIterator

class SearchIterator:
    DONE: ClassVar[int]
    def getElementComparisonType(self) -> Any: ...
    def getMatchedText(self) -> str: ...
    def isOverlapping(self) -> bool: ...
    def preceding(self, p0: int) -> int: ...
    def setBreakIterator(self, p0: BreakIterator) -> None: ...
    def setElementComparisonType(self, p0: Any) -> None: ...
    def setOverlapping(self, p0: bool) -> None: ...
    def getBreakIterator(self) -> BreakIterator: ...
    def getMatchLength(self) -> int: ...
    def getMatchStart(self) -> int: ...
    def following(self, p0: int) -> int: ...
    def reset(self) -> None: ...
    def next(self) -> int: ...
    def last(self) -> int: ...
    def first(self) -> int: ...
    def getTarget(self) -> CharacterIterator: ...
    def setTarget(self, p0: CharacterIterator) -> None: ...
    def setIndex(self, p0: int) -> None: ...
    def getIndex(self) -> int: ...
    def previous(self) -> int: ...

    class ElementComparisonType:
        ANY_BASE_WEIGHT_IS_WILDCARD: ClassVar["ElementComparisonType"]
        PATTERN_BASE_WEIGHT_IS_WILDCARD: ClassVar["ElementComparisonType"]
        STANDARD_ELEMENT_COMPARISON: ClassVar["ElementComparisonType"]
        ANY_BASE_WEIGHT_IS_WILDCARD: ClassVar[Any]
        PATTERN_BASE_WEIGHT_IS_WILDCARD: ClassVar[Any]
        STANDARD_ELEMENT_COMPARISON: ClassVar[Any]
        @staticmethod
        def values() -> Any: ...
        @staticmethod
        def valueOf(p0: str) -> Any: ...
