from typing import Any, ClassVar, overload
from android.health.connect.datatypes.AggregationType import AggregationType
from java.time.LocalDateTime import LocalDateTime
from java.time.ZoneOffset import ZoneOffset

class AggregateRecordsGroupedByPeriodResponse:
    def get(self, p0: AggregationType) -> Any: ...
    def getEndTime(self) -> LocalDateTime: ...
    def getStartTime(self) -> LocalDateTime: ...
    def getZoneOffset(self, p0: AggregationType) -> ZoneOffset: ...
    def getDataOrigins(self, p0: AggregationType) -> set: ...
