from typing import Any, ClassVar, overload
from android.health.connect.TimeRangeFilter import TimeRangeFilter
from android.health.connect.datatypes.DataOrigin import DataOrigin

class ReadRecordsRequestUsingFilters:
    def getDataOrigins(self) -> set: ...
    def getPageSize(self) -> int: ...
    def getPageToken(self) -> int: ...
    def isAscending(self) -> bool: ...
    def getTimeRangeFilter(self) -> TimeRangeFilter: ...

    class Builder:
        def __init__(self, p0: type) -> None: ...
        def build(self) -> "ReadRecordsRequestUsingFilters": ...
        def setPageToken(self, p0: int) -> Any: ...
        def addDataOrigins(self, p0: DataOrigin) -> Any: ...
        def setTimeRangeFilter(self, p0: TimeRangeFilter) -> Any: ...
        def setAscending(self, p0: bool) -> Any: ...
        def setPageSize(self, p0: int) -> Any: ...
