from typing import Any, ClassVar, overload
from android.net.MacAddress import MacAddress
from android.net.wifi.ScanResult import ScanResult
from android.net.wifi.aware.PeerHandle import PeerHandle
from android.net.wifi.rtt.ResponderConfig import ResponderConfig
from android.os.Parcel import Parcel

class RangingRequest:
    CREATOR: ClassVar[Any]
    SECURITY_MODE_OPEN: ClassVar[int]
    SECURITY_MODE_OPPORTUNISTIC: ClassVar[int]
    SECURITY_MODE_SECURE_AUTH: ClassVar[int]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    def getSecurityMode(self) -> int: ...
    @staticmethod
    def getMaxPeers() -> int: ...
    @staticmethod
    def getMinRttBurstSize() -> int: ...
    @staticmethod
    def getMaxRttBurstSize() -> int: ...
    def getRttBurstSize(self) -> int: ...
    @staticmethod
    def getDefaultRttBurstSize() -> int: ...
    def equals(self, p0: Any) -> bool: ...
    def toString(self) -> str: ...
    def hashCode(self) -> int: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
    def describeContents(self) -> int: ...

    class Builder:
        def __init__(self) -> None: ...
        def addAccessPoint(self, p0: ScanResult) -> Any: ...
        def addAccessPoints(self, p0: list) -> Any: ...
        def addNon80211mcCapableAccessPoint(self, p0: ScanResult) -> Any: ...
        def addNon80211mcCapableAccessPoints(self, p0: list) -> Any: ...
        def addResponder(self, p0: ResponderConfig) -> Any: ...
        def addResponders(self, p0: list) -> Any: ...
        @overload
        def addWifiAwarePeer(self, p0: PeerHandle) -> Any: ...
        @overload
        def addWifiAwarePeer(self, p0: MacAddress) -> Any: ...
        def setRttBurstSize(self, p0: int) -> Any: ...
        def setSecurityMode(self, p0: int) -> Any: ...
        def build(self) -> "RangingRequest": ...
