from typing import Any, ClassVar, overload

class ConsumerIrManager:
    def getCarrierFrequencies(self) -> Any: ...
    def hasIrEmitter(self) -> bool: ...
    def transmit(self, p0: int, p1: Any) -> None: ...

    class CarrierFrequencyRange:
        def __init__(self, p0: "ConsumerIrManager", p1: int, p2: int) -> None: ...
        def getMinFrequency(self) -> int: ...
        def getMaxFrequency(self) -> int: ...
