from typing import Any, ClassVar, overload
from android.view.Display import Display
from android.view.Surface import Surface

class VirtualDisplay:
    def setSurface(self, p0: Surface) -> None: ...
    def getSurface(self) -> Surface: ...
    def release(self) -> None: ...
    def toString(self) -> str: ...
    def resize(self, p0: int, p1: int, p2: int) -> None: ...
    def setRotation(self, p0: int) -> None: ...
    def getDisplay(self) -> Display: ...

    class Callback:
        def __init__(self) -> None: ...
        def onStopped(self) -> None: ...
        def onResumed(self) -> None: ...
        def onPaused(self) -> None: ...

from typing import Any, ClassVar, overload
from android.os.Parcel import Parcel

class HdrConversionMode:
    CREATOR: ClassVar[Any]
    HDR_CONVERSION_FORCE: ClassVar[int]
    HDR_CONVERSION_PASSTHROUGH: ClassVar[int]
    HDR_CONVERSION_SYSTEM: ClassVar[int]
    HDR_CONVERSION_UNSUPPORTED: ClassVar[int]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    @overload
    def __init__(self, p0: int) -> None: ...
    @overload
    def __init__(self, p0: int, p1: int) -> None: ...
    def equals(self, p0: Any) -> bool: ...
    def toString(self) -> str: ...
    def hashCode(self) -> int: ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
    def getConversionMode(self) -> int: ...
    def getPreferredHdrOutputType(self) -> int: ...

from typing import Any, ClassVar, overload
from android.os.Parcel import Parcel
from android.view.Surface import Surface
from java.util.concurrent.Executor import Executor

class VirtualDisplayConfig:
    CREATOR: ClassVar[Any]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    def getSurface(self) -> Surface: ...
    def getName(self) -> str: ...
    def equals(self, p0: Any) -> bool: ...
    def toString(self) -> str: ...
    def hashCode(self) -> int: ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
    def getHeight(self) -> int: ...
    def getWidth(self) -> int: ...
    def getFlags(self) -> int: ...
    def getRequestedRefreshRate(self) -> float: ...
    def getDefaultBrightness(self) -> float: ...
    def getDensityDpi(self) -> int: ...
    def getDimBrightness(self) -> float: ...
    def getDisplayCategories(self) -> set: ...

    class Builder:
        def __init__(self, p0: str, p1: int, p2: int, p3: int) -> None: ...
        def setSurface(self, p0: Surface) -> Any: ...
        def build(self) -> "VirtualDisplayConfig": ...
        def setFlags(self, p0: int) -> Any: ...
        def addDisplayCategory(self, p0: str) -> Any: ...
        def setBrightnessListener(self, p0: Executor, p1: Any) -> Any: ...
        def setDefaultBrightness(self, p0: float) -> Any: ...
        def setRequestedRefreshRate(self, p0: float) -> Any: ...
        def setDimBrightness(self, p0: float) -> Any: ...
        def setDisplayCategories(self, p0: set) -> Any: ...

    class BrightnessListener:
        def onBrightnessChanged(self, p0: float) -> None: ...

from typing import Any, ClassVar, overload
from android.hardware.display.HdrConversionMode import HdrConversionMode
from android.hardware.display.VirtualDisplay import VirtualDisplay
from android.hardware.display.VirtualDisplayConfig import VirtualDisplayConfig
from android.os.Handler import Handler
from android.view.Display import Display
from android.view.Surface import Surface
from java.util.concurrent.Executor import Executor

class DisplayManager:
    DISPLAY_CATEGORY_PRESENTATION: ClassVar[str]
    EVENT_TYPE_DISPLAY_ADDED: ClassVar[int]
    EVENT_TYPE_DISPLAY_CHANGED: ClassVar[int]
    EVENT_TYPE_DISPLAY_REFRESH_RATE: ClassVar[int]
    EVENT_TYPE_DISPLAY_REMOVED: ClassVar[int]
    EVENT_TYPE_DISPLAY_STATE: ClassVar[int]
    MATCH_CONTENT_FRAMERATE_ALWAYS: ClassVar[int]
    MATCH_CONTENT_FRAMERATE_NEVER: ClassVar[int]
    MATCH_CONTENT_FRAMERATE_SEAMLESSS_ONLY: ClassVar[int]
    MATCH_CONTENT_FRAMERATE_UNKNOWN: ClassVar[int]
    VIRTUAL_DISPLAY_FLAG_AUTO_MIRROR: ClassVar[int]
    VIRTUAL_DISPLAY_FLAG_OWN_CONTENT_ONLY: ClassVar[int]
    VIRTUAL_DISPLAY_FLAG_PRESENTATION: ClassVar[int]
    VIRTUAL_DISPLAY_FLAG_PUBLIC: ClassVar[int]
    VIRTUAL_DISPLAY_FLAG_SECURE: ClassVar[int]
    @overload
    def getDisplays(self, p0: str) -> Any: ...
    @overload
    def getDisplays(self) -> Any: ...
    @overload
    def createVirtualDisplay(self, p0: str, p1: int, p2: int, p3: int, p4: Surface, p5: int, p6: Any, p7: Handler) -> VirtualDisplay: ...
    @overload
    def createVirtualDisplay(self, p0: str, p1: int, p2: int, p3: int, p4: Surface, p5: int) -> VirtualDisplay: ...
    @overload
    def createVirtualDisplay(self, p0: VirtualDisplayConfig, p1: Handler, p2: Any) -> VirtualDisplay: ...
    @overload
    def createVirtualDisplay(self, p0: VirtualDisplayConfig) -> VirtualDisplay: ...
    def getHdrConversionMode(self) -> HdrConversionMode: ...
    def getMatchContentFrameRateUserPreference(self) -> int: ...
    @overload
    def registerDisplayListener(self, p0: Any, p1: Handler) -> None: ...
    @overload
    def registerDisplayListener(self, p0: Executor, p1: int, p2: Any) -> None: ...
    def unregisterDisplayListener(self, p0: Any) -> None: ...
    def getDisplay(self, p0: int) -> Display: ...

    class DisplayListener:
        def onDisplayAdded(self, p0: int) -> None: ...
        def onDisplayChanged(self, p0: int) -> None: ...
        def onDisplayRemoved(self, p0: int) -> None: ...

from typing import Any, ClassVar, overload
from android.os.Parcel import Parcel

class DeviceProductInfo:
    CONNECTION_TO_SINK_BUILT_IN: ClassVar[int]
    CONNECTION_TO_SINK_DIRECT: ClassVar[int]
    CONNECTION_TO_SINK_TRANSITIVE: ClassVar[int]
    CONNECTION_TO_SINK_UNKNOWN: ClassVar[int]
    CREATOR: ClassVar[Any]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    def __init__(self, p0: str, p1: str, p2: str, p3: int, p4: int) -> None: ...
    def getProductId(self) -> str: ...
    def getConnectionToSinkType(self) -> int: ...
    def getManufactureWeek(self) -> int: ...
    def getManufactureYear(self) -> int: ...
    def getManufacturerPnpId(self) -> str: ...
    def getModelYear(self) -> int: ...
    def getName(self) -> str: ...
    def equals(self, p0: Any) -> bool: ...
    def toString(self) -> str: ...
    def hashCode(self) -> int: ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...

