from typing import Any, ClassVar, overload
from android.graphics.Rect import Rect
from android.graphics.Region import Region
from android.view.SurfaceControl import SurfaceControl
from android.window.InputTransferToken import InputTransferToken
from java.util.concurrent.Executor import Executor

class AttachedSurfaceControl:
    def setTouchableRegion(self, p0: Region) -> None: ...
    def addOnBufferTransformHintChangedListener(self, p0: Any) -> None: ...
    def applyTransactionOnDraw(self, p0: Any) -> bool: ...
    def buildReparentTransaction(self, p0: SurfaceControl) -> Any: ...
    def getBufferTransformHint(self) -> int: ...
    def registerOnJankDataListener(self, p0: Executor, p1: Any) -> Any: ...
    def removeOnBufferTransformHintChangedListener(self, p0: Any) -> None: ...
    def setChildBoundingInsets(self, p0: Rect) -> None: ...
    def getInputTransferToken(self) -> InputTransferToken: ...

    class OnBufferTransformHintChangedListener:
        def onBufferTransformHintChanged(self, p0: int) -> None: ...
