from typing import Any, ClassVar, overload
from android.content.ClipData import ClipData
from android.net.Uri import Uri
from android.os.Bundle import Bundle
from android.os.Parcel import Parcel

class ContentInfo:
    CREATOR: ClassVar[Any]
    FLAG_CONVERT_TO_PLAIN_TEXT: ClassVar[int]
    SOURCE_APP: ClassVar[int]
    SOURCE_AUTOFILL: ClassVar[int]
    SOURCE_CLIPBOARD: ClassVar[int]
    SOURCE_DRAG_AND_DROP: ClassVar[int]
    SOURCE_INPUT_METHOD: ClassVar[int]
    SOURCE_PROCESS_TEXT: ClassVar[int]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    def toString(self) -> str: ...
    def getClip(self) -> ClipData: ...
    def getFlags(self) -> int: ...
    def getExtras(self) -> Bundle: ...
    def getLinkUri(self) -> Uri: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
    def describeContents(self) -> int: ...
    def getSource(self) -> int: ...

    class Builder:
        @overload
        def __init__(self, p0: ClipData, p1: int) -> None: ...
        @overload
        def __init__(self, p0: "ContentInfo") -> None: ...
        def setLinkUri(self, p0: Uri) -> Any: ...
        def setClip(self, p0: ClipData) -> Any: ...
        def setExtras(self, p0: Bundle) -> Any: ...
        def setSource(self, p0: int) -> Any: ...
        def setFlags(self, p0: int) -> Any: ...
        def build(self) -> "ContentInfo": ...
