from typing import Any, ClassVar, overload
from android.hardware.BatteryState import BatteryState
from android.hardware.SensorManager import SensorManager
from android.hardware.lights.LightsManager import LightsManager
from android.os.Parcel import Parcel
from android.os.Vibrator import Vibrator
from android.os.VibratorManager import VibratorManager
from android.view.KeyCharacterMap import KeyCharacterMap

class InputDevice:
    CREATOR: ClassVar[Any]
    KEYBOARD_TYPE_ALPHABETIC: ClassVar[int]
    KEYBOARD_TYPE_NONE: ClassVar[int]
    KEYBOARD_TYPE_NON_ALPHABETIC: ClassVar[int]
    MOTION_RANGE_ORIENTATION: ClassVar[int]
    MOTION_RANGE_PRESSURE: ClassVar[int]
    MOTION_RANGE_SIZE: ClassVar[int]
    MOTION_RANGE_TOOL_MAJOR: ClassVar[int]
    MOTION_RANGE_TOOL_MINOR: ClassVar[int]
    MOTION_RANGE_TOUCH_MAJOR: ClassVar[int]
    MOTION_RANGE_TOUCH_MINOR: ClassVar[int]
    MOTION_RANGE_X: ClassVar[int]
    MOTION_RANGE_Y: ClassVar[int]
    SOURCE_ANY: ClassVar[int]
    SOURCE_BLUETOOTH_STYLUS: ClassVar[int]
    SOURCE_CLASS_BUTTON: ClassVar[int]
    SOURCE_CLASS_JOYSTICK: ClassVar[int]
    SOURCE_CLASS_MASK: ClassVar[int]
    SOURCE_CLASS_NONE: ClassVar[int]
    SOURCE_CLASS_POINTER: ClassVar[int]
    SOURCE_CLASS_POSITION: ClassVar[int]
    SOURCE_CLASS_TRACKBALL: ClassVar[int]
    SOURCE_DPAD: ClassVar[int]
    SOURCE_GAMEPAD: ClassVar[int]
    SOURCE_HDMI: ClassVar[int]
    SOURCE_JOYSTICK: ClassVar[int]
    SOURCE_KEYBOARD: ClassVar[int]
    SOURCE_MOUSE: ClassVar[int]
    SOURCE_MOUSE_RELATIVE: ClassVar[int]
    SOURCE_ROTARY_ENCODER: ClassVar[int]
    SOURCE_SENSOR: ClassVar[int]
    SOURCE_STYLUS: ClassVar[int]
    SOURCE_TOUCHPAD: ClassVar[int]
    SOURCE_TOUCHSCREEN: ClassVar[int]
    SOURCE_TOUCH_NAVIGATION: ClassVar[int]
    SOURCE_TRACKBALL: ClassVar[int]
    SOURCE_UNKNOWN: ClassVar[int]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    def getBatteryState(self) -> BatteryState: ...
    def getControllerNumber(self) -> int: ...
    @staticmethod
    def getDeviceIds() -> Any: ...
    def getKeyCodeForKeyLocation(self, p0: int) -> int: ...
    def getKeyboardType(self) -> int: ...
    def getLightsManager(self) -> LightsManager: ...
    @overload
    def getMotionRange(self, p0: int) -> Any: ...
    @overload
    def getMotionRange(self, p0: int, p1: int) -> Any: ...
    def getMotionRanges(self) -> list: ...
    def getSensorManager(self) -> SensorManager: ...
    def getSources(self) -> int: ...
    def getVibrator(self) -> Vibrator: ...
    def getVibratorManager(self) -> VibratorManager: ...
    def hasKeys(self, p0: Any) -> Any: ...
    def hasMicrophone(self) -> bool: ...
    def isExternal(self) -> bool: ...
    def supportsSource(self, p0: int) -> bool: ...
    def getName(self) -> str: ...
    def toString(self) -> str: ...
    def getDescriptor(self) -> str: ...
    def isEnabled(self) -> bool: ...
    def isVirtual(self) -> bool: ...
    def getId(self) -> int: ...
    def getVendorId(self) -> int: ...
    def getProductId(self) -> int: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
    def describeContents(self) -> int: ...
    def getKeyCharacterMap(self) -> KeyCharacterMap: ...
    @staticmethod
    def getDevice(p0: int) -> "InputDevice": ...

    class ViewBehavior:
        def shouldSmoothScroll(self, p0: int, p1: int) -> bool: ...

    class MotionRange:
        def getFuzz(self) -> float: ...
        def getFlat(self) -> float: ...
        def getAxis(self) -> int: ...
        def getRange(self) -> float: ...
        def getMax(self) -> float: ...
        def getMin(self) -> float: ...
        def getResolution(self) -> float: ...
        def getSource(self) -> int: ...
        def isFromSource(self, p0: int) -> bool: ...
