from typing import Any, ClassVar, overload
from android.content.Context import Context

class OrientationListener:
    ORIENTATION_UNKNOWN: ClassVar[int]
    @overload
    def __init__(self, p0: Context, p1: int) -> None: ...
    @overload
    def __init__(self, p0: Context) -> None: ...
    def onOrientationChanged(self, p0: int) -> None: ...
    def disable(self) -> None: ...
    def enable(self) -> None: ...
    def onSensorChanged(self, p0: int, p1: Any) -> None: ...
    def onAccuracyChanged(self, p0: int, p1: int) -> None: ...
