from typing import Any, ClassVar, overload
from android.os.Parcel import Parcel

class VerifiedMotionEvent:
    CREATOR: ClassVar[Any]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    CREATOR: ClassVar[Any]
    def getDownTimeNanos(self) -> int: ...
    def getFlag(self, p0: int) -> bool: ...
    def equals(self, p0: Any) -> bool: ...
    def hashCode(self) -> int: ...
    def getActionMasked(self) -> int: ...
    def getButtonState(self) -> int: ...
    def getRawX(self) -> float: ...
    def getRawY(self) -> float: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
    def describeContents(self) -> int: ...
    def getMetaState(self) -> int: ...
