from typing import Any, ClassVar, overload
from android.view.View import View
from java.lang.Runnable import Runnable
from java.util.function.Consumer import Consumer

class ViewTreeObserver:
    def addOnGlobalFocusChangeListener(self, p0: Any) -> None: ...
    def addOnGlobalLayoutListener(self, p0: Any) -> None: ...
    def addOnPreDrawListener(self, p0: Any) -> None: ...
    def addOnScrollChangedListener(self, p0: Any) -> None: ...
    def addOnSystemGestureExclusionRectsChangedListener(self, p0: Consumer) -> None: ...
    def addOnDrawListener(self, p0: Any) -> None: ...
    def addOnTouchModeChangeListener(self, p0: Any) -> None: ...
    def addOnWindowAttachListener(self, p0: Any) -> None: ...
    def addOnWindowFocusChangeListener(self, p0: Any) -> None: ...
    def addOnWindowVisibilityChangeListener(self, p0: Any) -> None: ...
    def dispatchOnDraw(self) -> None: ...
    def dispatchOnGlobalLayout(self) -> None: ...
    def dispatchOnPreDraw(self) -> bool: ...
    def registerFrameCommitCallback(self, p0: Runnable) -> None: ...
    def removeGlobalOnLayoutListener(self, p0: Any) -> None: ...
    def removeOnDrawListener(self, p0: Any) -> None: ...
    def removeOnGlobalFocusChangeListener(self, p0: Any) -> None: ...
    def removeOnGlobalLayoutListener(self, p0: Any) -> None: ...
    def removeOnPreDrawListener(self, p0: Any) -> None: ...
    def removeOnScrollChangedListener(self, p0: Any) -> None: ...
    def removeOnSystemGestureExclusionRectsChangedListener(self, p0: Consumer) -> None: ...
    def removeOnTouchModeChangeListener(self, p0: Any) -> None: ...
    def removeOnWindowAttachListener(self, p0: Any) -> None: ...
    def removeOnWindowFocusChangeListener(self, p0: Any) -> None: ...
    def removeOnWindowVisibilityChangeListener(self, p0: Any) -> None: ...
    def unregisterFrameCommitCallback(self, p0: Runnable) -> bool: ...
    def isAlive(self) -> bool: ...

    class OnWindowVisibilityChangeListener:
        def onWindowVisibilityChanged(self, p0: int) -> None: ...

    class OnWindowFocusChangeListener:
        def onWindowFocusChanged(self, p0: bool) -> None: ...

    class OnWindowAttachListener:
        def onWindowDetached(self) -> None: ...
        def onWindowAttached(self) -> None: ...

    class OnTouchModeChangeListener:
        def onTouchModeChanged(self, p0: bool) -> None: ...

    class OnScrollChangedListener:
        def onScrollChanged(self) -> None: ...

    class OnPreDrawListener:
        def onPreDraw(self) -> bool: ...

    class OnGlobalLayoutListener:
        def onGlobalLayout(self) -> None: ...

    class OnGlobalFocusChangeListener:
        def onGlobalFocusChanged(self, p0: View, p1: View) -> None: ...

    class OnDrawListener:
        def onDraw(self) -> None: ...
