from typing import Any, ClassVar, overload
from android.content.Context import Context
from android.content.res.Configuration import Configuration
from android.content.res.TypedArray import TypedArray
from android.graphics.Rect import Rect
from android.graphics.drawable.Drawable import Drawable
from android.media.session.MediaController import MediaController
from android.net.Uri import Uri
from android.os.Bundle import Bundle
from android.os.Handler import Handler
from android.os.IBinder import IBinder
from android.transition.Scene import Scene
from android.transition.Transition import Transition
from android.transition.TransitionManager import TransitionManager
from android.view.ActionMode import ActionMode
from android.view.AttachedSurfaceControl import AttachedSurfaceControl
from android.view.FrameMetrics import FrameMetrics
from android.view.InputEvent import InputEvent
from android.view.KeyEvent import KeyEvent
from android.view.LayoutInflater import LayoutInflater
from android.view.Menu import Menu
from android.view.MenuItem import MenuItem
from android.view.MotionEvent import MotionEvent
from android.view.ScrollCaptureCallback import ScrollCaptureCallback
from android.view.SearchEvent import SearchEvent
from android.view.View import View
from android.view.WindowInsetsController import WindowInsetsController
from android.view.WindowManager import WindowManager
from android.view.accessibility.AccessibilityEvent import AccessibilityEvent
from android.window.OnBackInvokedDispatcher import OnBackInvokedDispatcher

class Window:
    DECOR_CAPTION_SHADE_AUTO: ClassVar[int]
    DECOR_CAPTION_SHADE_DARK: ClassVar[int]
    DECOR_CAPTION_SHADE_LIGHT: ClassVar[int]
    FEATURE_ACTION_BAR: ClassVar[int]
    FEATURE_ACTION_BAR_OVERLAY: ClassVar[int]
    FEATURE_ACTION_MODE_OVERLAY: ClassVar[int]
    FEATURE_ACTIVITY_TRANSITIONS: ClassVar[int]
    FEATURE_CONTENT_TRANSITIONS: ClassVar[int]
    FEATURE_CONTEXT_MENU: ClassVar[int]
    FEATURE_CUSTOM_TITLE: ClassVar[int]
    FEATURE_INDETERMINATE_PROGRESS: ClassVar[int]
    FEATURE_LEFT_ICON: ClassVar[int]
    FEATURE_NO_TITLE: ClassVar[int]
    FEATURE_OPTIONS_PANEL: ClassVar[int]
    FEATURE_PROGRESS: ClassVar[int]
    FEATURE_RIGHT_ICON: ClassVar[int]
    FEATURE_SWIPE_TO_DISMISS: ClassVar[int]
    ID_ANDROID_CONTENT: ClassVar[int]
    NAVIGATION_BAR_BACKGROUND_TRANSITION_NAME: ClassVar[str]
    PROGRESS_END: ClassVar[int]
    PROGRESS_INDETERMINATE_OFF: ClassVar[int]
    PROGRESS_INDETERMINATE_ON: ClassVar[int]
    PROGRESS_SECONDARY_END: ClassVar[int]
    PROGRESS_SECONDARY_START: ClassVar[int]
    PROGRESS_START: ClassVar[int]
    PROGRESS_VISIBILITY_OFF: ClassVar[int]
    PROGRESS_VISIBILITY_ON: ClassVar[int]
    STATUS_BAR_BACKGROUND_TRANSITION_NAME: ClassVar[str]
    def __init__(self, p0: Context) -> None: ...
    def getAllowReturnTransitionOverlap(self) -> bool: ...
    def getReenterTransition(self) -> Transition: ...
    def getReturnTransition(self) -> Transition: ...
    def getSharedElementEnterTransition(self) -> Transition: ...
    def getSharedElementReturnTransition(self) -> Transition: ...
    def setAllowEnterTransitionOverlap(self, p0: bool) -> None: ...
    def setAllowReturnTransitionOverlap(self, p0: bool) -> None: ...
    def setReenterTransition(self, p0: Transition) -> None: ...
    def setReturnTransition(self, p0: Transition) -> None: ...
    def setSharedElementEnterTransition(self, p0: Transition) -> None: ...
    def setSharedElementReturnTransition(self, p0: Transition) -> None: ...
    def isWideColorGamut(self) -> bool: ...
    def getColorMode(self) -> int: ...
    def getDesiredHdrHeadroom(self) -> float: ...
    def getFrameRateBoostOnTouchEnabled(self) -> bool: ...
    def isFrameRatePowerSavingsBalanced(self) -> bool: ...
    def setColorMode(self, p0: int) -> None: ...
    def setFrameRateBoostOnTouchEnabled(self, p0: bool) -> None: ...
    def setFrameRatePowerSavingsBalanced(self, p0: bool) -> None: ...
    def addOnFrameMetricsAvailableListener(self, p0: Any, p1: Handler) -> None: ...
    def clearFlags(self, p0: int) -> None: ...
    def closeAllPanels(self) -> None: ...
    def closePanel(self, p0: int) -> None: ...
    def getDecorView(self) -> View: ...
    @staticmethod
    def getDefaultFeatures(p0: Context) -> int: ...
    def getInsetsController(self) -> WindowInsetsController: ...
    def getNavigationBarColor(self) -> int: ...
    def getNavigationBarDividerColor(self) -> int: ...
    def getSharedElementExitTransition(self) -> Transition: ...
    def getSharedElementReenterTransition(self) -> Transition: ...
    def getSharedElementsUseOverlay(self) -> bool: ...
    def getStatusBarColor(self) -> int: ...
    def getTransitionBackgroundFadeDuration(self) -> int: ...
    def getTransitionManager(self) -> TransitionManager: ...
    def getWindowStyle(self) -> TypedArray: ...
    def getAttributes(self) -> Any: ...
    def addContentView(self, p0: View, p1: Any) -> None: ...
    def getContentScene(self) -> Scene: ...
    def getCurrentFocus(self) -> View: ...
    def getLayoutInflater(self) -> LayoutInflater: ...
    def getMediaController(self) -> MediaController: ...
    def getOnBackInvokedDispatcher(self) -> OnBackInvokedDispatcher: ...
    def getWindowManager(self) -> WindowManager: ...
    def findViewById(self, p0: int) -> View: ...
    def getContext(self) -> Context: ...
    def getRootSurfaceControl(self) -> AttachedSurfaceControl: ...
    def getSystemGestureExclusionRects(self) -> list: ...
    def requireViewById(self, p0: int) -> View: ...
    def restoreHierarchyState(self, p0: Bundle) -> None: ...
    def saveHierarchyState(self) -> Bundle: ...
    def setBackgroundDrawable(self, p0: Drawable) -> None: ...
    def setClipToOutline(self, p0: bool) -> None: ...
    def setElevation(self, p0: float) -> None: ...
    def setSystemGestureExclusionRects(self, p0: list) -> None: ...
    def setIcon(self, p0: int) -> None: ...
    def setFeatureDrawable(self, p0: int, p1: Drawable) -> None: ...
    def setFeatureDrawableAlpha(self, p0: int, p1: int) -> None: ...
    def setFeatureDrawableResource(self, p0: int, p1: int) -> None: ...
    def setFeatureDrawableUri(self, p0: int, p1: Uri) -> None: ...
    def setTitleColor(self, p0: int) -> None: ...
    def setVolumeControlStream(self, p0: int) -> None: ...
    def takeKeyEvents(self, p0: bool) -> None: ...
    def setLogo(self, p0: int) -> None: ...
    def setTitle(self, p0: str) -> None: ...
    def getVolumeControlStream(self) -> int: ...
    def setType(self, p0: int) -> None: ...
    def setFlags(self, p0: int, p1: int) -> None: ...
    def addFlags(self, p0: int) -> None: ...
    def getAllowEnterTransitionOverlap(self) -> bool: ...
    def setGravity(self, p0: int) -> None: ...
    def setMediaController(self, p0: MediaController) -> None: ...
    def isShortcutKey(self, p0: int, p1: KeyEvent) -> bool: ...
    def onConfigurationChanged(self, p0: Configuration) -> None: ...
    def hasFeature(self, p0: int) -> bool: ...
    def hasChildren(self) -> bool: ...
    def registerScrollCaptureCallback(self, p0: ScrollCaptureCallback) -> None: ...
    def removeOnFrameMetricsAvailableListener(self, p0: Any) -> None: ...
    def setBackgroundBlurRadius(self, p0: int) -> None: ...
    def injectInputEvent(self, p0: InputEvent) -> None: ...
    def openPanel(self, p0: int, p1: KeyEvent) -> None: ...
    def performContextMenuIdentifierAction(self, p0: int, p1: int) -> bool: ...
    def performPanelIdentifierAction(self, p0: int, p1: int, p2: int) -> bool: ...
    def performPanelShortcut(self, p0: int, p1: int, p2: KeyEvent, p3: int) -> bool: ...
    def requestFeature(self, p0: int) -> bool: ...
    def isStatusBarContrastEnforced(self) -> bool: ...
    def peekDecorView(self) -> View: ...
    def setAttributes(self, p0: Any) -> None: ...
    def invalidatePanelMenu(self, p0: int) -> None: ...
    def isNavigationBarContrastEnforced(self) -> bool: ...
    def makeActive(self) -> None: ...
    def setBackgroundDrawableResource(self, p0: int) -> None: ...
    def setChildDrawable(self, p0: int, p1: Drawable) -> None: ...
    def setChildInt(self, p0: int, p1: int) -> None: ...
    def setContainer(self, p0: "Window") -> None: ...
    def setDecorCaptionShade(self, p0: int) -> None: ...
    def setDecorFitsSystemWindows(self, p0: bool) -> None: ...
    def setDimAmount(self, p0: float) -> None: ...
    def setFeatureInt(self, p0: int, p1: int) -> None: ...
    def setHideOverlayWindows(self, p0: bool) -> None: ...
    def setLayout(self, p0: int, p1: int) -> None: ...
    def setLocalFocus(self, p0: bool, p1: bool) -> None: ...
    def setNavigationBarColor(self, p0: int) -> None: ...
    def setNavigationBarContrastEnforced(self, p0: bool) -> None: ...
    def setNavigationBarDividerColor(self, p0: int) -> None: ...
    def setPreferMinimalPostProcessing(self, p0: bool) -> None: ...
    def setResizingCaptionDrawable(self, p0: Drawable) -> None: ...
    def setRestrictedCaptionAreaListener(self, p0: Any) -> None: ...
    def setStatusBarColor(self, p0: int) -> None: ...
    def setSharedElementExitTransition(self, p0: Transition) -> None: ...
    def setSharedElementReenterTransition(self, p0: Transition) -> None: ...
    def setSharedElementsUseOverlay(self, p0: bool) -> None: ...
    def setStatusBarContrastEnforced(self, p0: bool) -> None: ...
    def setSustainedPerformanceMode(self, p0: bool) -> None: ...
    def setTransitionBackgroundFadeDuration(self, p0: int) -> None: ...
    def setTransitionManager(self, p0: TransitionManager) -> None: ...
    @overload
    def setUiOptions(self, p0: int, p1: int) -> None: ...
    @overload
    def setUiOptions(self, p0: int) -> None: ...
    def setWindowAnimations(self, p0: int) -> None: ...
    @overload
    def setWindowManager(self, p0: WindowManager, p1: IBinder, p2: str, p3: bool) -> None: ...
    @overload
    def setWindowManager(self, p0: WindowManager, p1: IBinder, p2: str) -> None: ...
    def superDispatchGenericMotionEvent(self, p0: MotionEvent) -> bool: ...
    def superDispatchKeyEvent(self, p0: KeyEvent) -> bool: ...
    def superDispatchKeyShortcutEvent(self, p0: KeyEvent) -> bool: ...
    def superDispatchTouchEvent(self, p0: MotionEvent) -> bool: ...
    def superDispatchTrackballEvent(self, p0: MotionEvent) -> bool: ...
    def takeInputQueue(self, p0: Any) -> None: ...
    def takeSurface(self, p0: Any) -> None: ...
    def togglePanel(self, p0: int, p1: KeyEvent) -> None: ...
    def unregisterScrollCaptureCallback(self, p0: ScrollCaptureCallback) -> None: ...
    def setDesiredHdrHeadroom(self, p0: float) -> None: ...
    def getEnterTransition(self) -> Transition: ...
    def getExitTransition(self) -> Transition: ...
    @overload
    def setContentView(self, p0: View, p1: Any) -> None: ...
    @overload
    def setContentView(self, p0: int) -> None: ...
    @overload
    def setContentView(self, p0: View) -> None: ...
    def setEnterTransition(self, p0: Transition) -> None: ...
    def setSoftInputMode(self, p0: int) -> None: ...
    def setExitTransition(self, p0: Transition) -> None: ...
    def getCallback(self) -> Any: ...
    def setCallback(self, p0: Any) -> None: ...
    def setFormat(self, p0: int) -> None: ...
    def getContainer(self) -> "Window": ...
    def isFloating(self) -> bool: ...
    def isActive(self) -> bool: ...

    class OnRestrictedCaptionAreaChangedListener:
        def onRestrictedCaptionAreaChanged(self, p0: Rect) -> None: ...

    class OnFrameMetricsAvailableListener:
        def onFrameMetricsAvailable(self, p0: "Window", p1: FrameMetrics, p2: int) -> None: ...

    class Callback:
        def onPointerCaptureChanged(self, p0: bool) -> None: ...
        def onActionModeFinished(self, p0: ActionMode) -> None: ...
        def onActionModeStarted(self, p0: ActionMode) -> None: ...
        def onAttachedToWindow(self) -> None: ...
        def onDetachedFromWindow(self) -> None: ...
        def dispatchGenericMotionEvent(self, p0: MotionEvent) -> bool: ...
        def dispatchKeyEvent(self, p0: KeyEvent) -> bool: ...
        def dispatchKeyShortcutEvent(self, p0: KeyEvent) -> bool: ...
        def dispatchPopulateAccessibilityEvent(self, p0: AccessibilityEvent) -> bool: ...
        def dispatchTouchEvent(self, p0: MotionEvent) -> bool: ...
        def dispatchTrackballEvent(self, p0: MotionEvent) -> bool: ...
        def onWindowFocusChanged(self, p0: bool) -> None: ...
        def onCreatePanelMenu(self, p0: int, p1: Menu) -> bool: ...
        def onCreatePanelView(self, p0: int) -> View: ...
        def onMenuItemSelected(self, p0: int, p1: MenuItem) -> bool: ...
        def onMenuOpened(self, p0: int, p1: Menu) -> bool: ...
        def onPanelClosed(self, p0: int, p1: Menu) -> None: ...
        def onPreparePanel(self, p0: int, p1: View, p2: Menu) -> bool: ...
        def onProvideKeyboardShortcuts(self, p0: list, p1: Menu, p2: int) -> None: ...
        @overload
        def onSearchRequested(self, p0: SearchEvent) -> bool: ...
        @overload
        def onSearchRequested(self) -> bool: ...
        def onWindowAttributesChanged(self, p0: Any) -> None: ...
        @overload
        def onWindowStartingActionMode(self, p0: Any) -> ActionMode: ...
        @overload
        def onWindowStartingActionMode(self, p0: Any, p1: int) -> ActionMode: ...
        def onContentChanged(self) -> None: ...
