from typing import Any, ClassVar, overload
from android.graphics.Insets import Insets
from android.graphics.Rect import Rect
from android.util.Size import Size
from android.view.DisplayCutout import DisplayCutout
from android.view.DisplayShape import DisplayShape
from android.view.RoundedCorner import RoundedCorner

class WindowInsets:
    CONSUMED: ClassVar["WindowInsets"]
    def __init__(self, p0: "WindowInsets") -> None: ...
    def getRoundedCorner(self, p0: int) -> RoundedCorner: ...
    def equals(self, p0: Any) -> bool: ...
    def toString(self) -> str: ...
    def hashCode(self) -> int: ...
    def isVisible(self, p0: int) -> bool: ...
    def getDisplayCutout(self) -> DisplayCutout: ...
    def getBoundingRects(self, p0: int) -> list: ...
    def consumeDisplayCutout(self) -> "WindowInsets": ...
    def consumeStableInsets(self) -> "WindowInsets": ...
    def consumeSystemWindowInsets(self) -> "WindowInsets": ...
    def getBoundingRectsIgnoringVisibility(self, p0: int) -> list: ...
    def getDisplayShape(self) -> DisplayShape: ...
    def getFrame(self) -> Size: ...
    def getInsets(self, p0: int) -> Insets: ...
    def getInsetsIgnoringVisibility(self, p0: int) -> Insets: ...
    def getMandatorySystemGestureInsets(self) -> Insets: ...
    def getPrivacyIndicatorBounds(self) -> Rect: ...
    def getStableInsetBottom(self) -> int: ...
    def getStableInsetLeft(self) -> int: ...
    def getStableInsetRight(self) -> int: ...
    def getStableInsetTop(self) -> int: ...
    def getStableInsets(self) -> Insets: ...
    def getSystemGestureInsets(self) -> Insets: ...
    def getSystemWindowInsetBottom(self) -> int: ...
    def getSystemWindowInsetLeft(self) -> int: ...
    def getSystemWindowInsetRight(self) -> int: ...
    def getSystemWindowInsetTop(self) -> int: ...
    def getSystemWindowInsets(self) -> Insets: ...
    def getTappableElementInsets(self) -> Insets: ...
    def hasInsets(self) -> bool: ...
    def hasStableInsets(self) -> bool: ...
    def hasSystemWindowInsets(self) -> bool: ...
    def isConsumed(self) -> bool: ...
    def isRound(self) -> bool: ...
    @overload
    def replaceSystemWindowInsets(self, p0: int, p1: int, p2: int, p3: int) -> "WindowInsets": ...
    @overload
    def replaceSystemWindowInsets(self, p0: Rect) -> "WindowInsets": ...
    @overload
    def inset(self, p0: Insets) -> "WindowInsets": ...
    @overload
    def inset(self, p0: int, p1: int, p2: int, p3: int) -> "WindowInsets": ...

    class Type:
        @staticmethod
        def tappableElement() -> int: ...
        @staticmethod
        def navigationBars() -> int: ...
        @staticmethod
        def systemGestures() -> int: ...
        @staticmethod
        def displayCutout() -> int: ...
        @staticmethod
        def statusBars() -> int: ...
        @staticmethod
        def ime() -> int: ...
        @staticmethod
        def systemBars() -> int: ...
        @staticmethod
        def systemOverlays() -> int: ...
        @staticmethod
        def captionBar() -> int: ...
        @staticmethod
        def mandatorySystemGestures() -> int: ...

    class Side:
        BOTTOM: ClassVar[int]
        LEFT: ClassVar[int]
        RIGHT: ClassVar[int]
        TOP: ClassVar[int]
        @staticmethod
        def all() -> int: ...

    class Builder:
        @overload
        def __init__(self) -> None: ...
        @overload
        def __init__(self, p0: "WindowInsets") -> None: ...
        def setBoundingRects(self, p0: int, p1: list) -> Any: ...
        def setInsets(self, p0: int, p1: Insets) -> Any: ...
        def setDisplayShape(self, p0: DisplayShape) -> Any: ...
        def setDisplayCutout(self, p0: DisplayCutout) -> Any: ...
        def setBoundingRectsIgnoringVisibility(self, p0: int, p1: list) -> Any: ...
        def setMandatorySystemGestureInsets(self, p0: Insets) -> Any: ...
        def setPrivacyIndicatorBounds(self, p0: Rect) -> Any: ...
        def setRoundedCorner(self, p0: int, p1: RoundedCorner) -> Any: ...
        def setStableInsets(self, p0: Insets) -> Any: ...
        def setSystemGestureInsets(self, p0: Insets) -> Any: ...
        def setSystemWindowInsets(self, p0: Insets) -> Any: ...
        def setTappableElementInsets(self, p0: Insets) -> Any: ...
        def setFrame(self, p0: int, p1: int) -> Any: ...
        def setInsetsIgnoringVisibility(self, p0: int, p1: Insets) -> Any: ...
        def build(self) -> "WindowInsets": ...
        def setVisible(self, p0: int, p1: bool) -> Any: ...
