from typing import Any, ClassVar, overload
from android.view.WindowInsetsAnimationController import WindowInsetsAnimationController

class WindowInsetsAnimationControlListener:
    def onReady(self, p0: WindowInsetsAnimationController, p1: int) -> None: ...
    def onFinished(self, p0: WindowInsetsAnimationController) -> None: ...
    def onCancelled(self, p0: WindowInsetsAnimationController) -> None: ...
