from typing import Any, ClassVar, overload
from java.util.Iterator import Iterator

class DrmInfoRequest:
    ACCOUNT_ID: ClassVar[str]
    SUBSCRIPTION_ID: ClassVar[str]
    TYPE_REGISTRATION_INFO: ClassVar[int]
    TYPE_RIGHTS_ACQUISITION_INFO: ClassVar[int]
    TYPE_RIGHTS_ACQUISITION_PROGRESS_INFO: ClassVar[int]
    TYPE_UNREGISTRATION_INFO: ClassVar[int]
    def __init__(self, p0: int, p1: str) -> None: ...
    def getMimeType(self) -> str: ...
    def getInfoType(self) -> int: ...
    def keyIterator(self) -> Iterator: ...
    def put(self, p0: str, p1: Any) -> None: ...
    def get(self, p0: str) -> Any: ...
    def iterator(self) -> Iterator: ...
