from typing import Any, ClassVar, overload
from android.content.ContentValues import ContentValues
from android.content.Context import Context
from android.drm.DrmConvertedStatus import DrmConvertedStatus
from android.drm.DrmErrorEvent import DrmErrorEvent
from android.drm.DrmEvent import DrmEvent
from android.drm.DrmInfo import DrmInfo
from android.drm.DrmInfoEvent import DrmInfoEvent
from android.drm.DrmInfoRequest import DrmInfoRequest
from android.drm.DrmRights import DrmRights
from android.net.Uri import Uri

class DrmManagerClient:
    ERROR_NONE: ClassVar[int]
    ERROR_UNKNOWN: ClassVar[int]
    def __init__(self, p0: Context) -> None: ...
    def setOnEventListener(self, p0: Any) -> None: ...
    @overload
    def getConstraints(self, p0: str, p1: int) -> ContentValues: ...
    @overload
    def getConstraints(self, p0: Uri, p1: int) -> ContentValues: ...
    def getAvailableDrmEngines(self) -> Any: ...
    def getAvailableDrmSupportInfo(self) -> list: ...
    def saveRights(self, p0: DrmRights, p1: str, p2: str) -> int: ...
    @overload
    def canHandle(self, p0: Uri, p1: str) -> bool: ...
    @overload
    def canHandle(self, p0: str, p1: str) -> bool: ...
    def processDrmInfo(self, p0: DrmInfo) -> int: ...
    def acquireDrmInfo(self, p0: DrmInfoRequest) -> DrmInfo: ...
    def acquireRights(self, p0: DrmInfoRequest) -> int: ...
    @overload
    def getDrmObjectType(self, p0: Uri, p1: str) -> int: ...
    @overload
    def getDrmObjectType(self, p0: str, p1: str) -> int: ...
    @overload
    def getOriginalMimeType(self, p0: Uri) -> str: ...
    @overload
    def getOriginalMimeType(self, p0: str) -> str: ...
    @overload
    def checkRightsStatus(self, p0: str) -> int: ...
    @overload
    def checkRightsStatus(self, p0: Uri) -> int: ...
    @overload
    def checkRightsStatus(self, p0: str, p1: int) -> int: ...
    @overload
    def checkRightsStatus(self, p0: Uri, p1: int) -> int: ...
    @overload
    def removeRights(self, p0: Uri) -> int: ...
    @overload
    def removeRights(self, p0: str) -> int: ...
    def removeAllRights(self) -> int: ...
    def openConvertSession(self, p0: str) -> int: ...
    def convertData(self, p0: int, p1: Any) -> DrmConvertedStatus: ...
    def closeConvertSession(self, p0: int) -> DrmConvertedStatus: ...
    def close(self) -> None: ...
    def setOnErrorListener(self, p0: Any) -> None: ...
    def setOnInfoListener(self, p0: Any) -> None: ...
    def release(self) -> None: ...
    @overload
    def getMetadata(self, p0: Uri) -> ContentValues: ...
    @overload
    def getMetadata(self, p0: str) -> ContentValues: ...

    class OnInfoListener:
        def onInfo(self, p0: "DrmManagerClient", p1: DrmInfoEvent) -> None: ...

    class OnEventListener:
        def onEvent(self, p0: "DrmManagerClient", p1: DrmEvent) -> None: ...

    class OnErrorListener:
        def onError(self, p0: "DrmManagerClient", p1: DrmErrorEvent) -> None: ...
