from typing import Any, ClassVar, overload
from android.net.wifi.hotspot2.pps.Credential import Credential
from android.net.wifi.hotspot2.pps.HomeSp import HomeSp
from android.os.Parcel import Parcel

class PasspointConfiguration:
    CREATOR: ClassVar[Any]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, p0: "PasspointConfiguration") -> None: ...
    def setHomeSp(self, p0: HomeSp) -> None: ...
    def getHomeSp(self) -> HomeSp: ...
    def setCredential(self, p0: Credential) -> None: ...
    def isOsuProvisioned(self) -> bool: ...
    def getSubscriptionExpirationTimeMillis(self) -> int: ...
    def setSubscriptionExpirationTimeInMillis(self, p0: int) -> None: ...
    def getDecoratedIdentityPrefix(self) -> str: ...
    def setDecoratedIdentityPrefix(self, p0: str) -> None: ...
    def equals(self, p0: Any) -> bool: ...
    def toString(self) -> str: ...
    def hashCode(self) -> int: ...
    def getUniqueId(self) -> str: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
    def describeContents(self) -> int: ...
    def getCredential(self) -> Credential: ...
