from typing import Any, ClassVar, overload
from android.os.Parcel import Parcel

class CorrectionInfo:
    CREATOR: ClassVar[Any]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    def __init__(self, p0: int, p1: str, p2: str) -> None: ...
    def toString(self) -> str: ...
    def getOldText(self) -> str: ...
    def getNewText(self) -> str: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
    def describeContents(self) -> int: ...
    def getOffset(self) -> int: ...
