from typing import Any, ClassVar, overload
from android.graphics.RectF import RectF
from android.os.Parcel import Parcel

class DeleteGesture:
    CREATOR: ClassVar[Any]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    GRANULARITY_CHARACTER: ClassVar[int]
    GRANULARITY_WORD: ClassVar[int]
    def getGranularity(self) -> int: ...
    def getDeletionArea(self) -> RectF: ...
    def equals(self, p0: Any) -> bool: ...
    def hashCode(self) -> int: ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...

    class Builder:
        def __init__(self) -> None: ...
        def setGranularity(self, p0: int) -> Any: ...
        def setFallbackText(self, p0: str) -> Any: ...
        def setDeletionArea(self, p0: RectF) -> Any: ...
        def build(self) -> "DeleteGesture": ...
