# cython: language_level=3
# Generated by pyjnius-wrap cython — do not edit by hand.
from jni_core._core cimport JavaObject
from jni_core.jni cimport (
    jobject, jstring,
    jboolean, jbyte, jchar, jshort, jint, jlong, jfloat, jdouble,
)

cdef class SelectGesture(JavaObject):
    cdef jint _getGranularity(self) except *
    cdef jobject _getSelectionArea(self) except? NULL
    cdef jboolean _equals(self, jobject p0) except *
    cdef jint _hashCode(self) except *
    cdef jint _describeContents(self) except *
    cdef void _writeToParcel(self, jobject p0, jint p1) except *

cdef class Builder(JavaObject):
    cdef jobject _setSelectionArea(self, jobject p0) except? NULL
    cdef jobject _setGranularity(self, jint p0) except? NULL
    cdef jobject _setFallbackText(self, jstring p0) except? NULL
    cdef jobject _build(self) except? NULL
