from typing import Any, ClassVar, overload
from android.window.SplashScreenView import SplashScreenView

class SplashScreen:
    SPLASH_SCREEN_STYLE_ICON: ClassVar[int]
    SPLASH_SCREEN_STYLE_SOLID_COLOR: ClassVar[int]
    def setSplashScreenTheme(self, p0: int) -> None: ...
    def setOnExitAnimationListener(self, p0: Any) -> None: ...
    def clearOnExitAnimationListener(self) -> None: ...

    class OnExitAnimationListener:
        def onSplashScreenExit(self, p0: SplashScreenView) -> None: ...
