from typing import Any, ClassVar, overload

class DataInput:
    def readLine(self) -> str: ...
    def readInt(self) -> int: ...
    def readUTF(self) -> str: ...
    def readLong(self) -> int: ...
    def readByte(self) -> int: ...
    def readShort(self) -> int: ...
    def readUnsignedByte(self) -> int: ...
    def skipBytes(self, p0: int) -> int: ...
    def readBoolean(self) -> bool: ...
    def readDouble(self) -> float: ...
    def readUnsignedShort(self) -> int: ...
    def readChar(self) -> str: ...
    def readFloat(self) -> float: ...
    @overload
    def readFully(self, p0: Any, p1: int, p2: int) -> None: ...
    @overload
    def readFully(self, p0: Any) -> None: ...
