from typing import Any, ClassVar, overload
from java.io.File import File
from java.io.FileDescriptor import FileDescriptor
from java.nio.charset.Charset import Charset

class FileWriter:
    @overload
    def __init__(self, p0: FileDescriptor) -> None: ...
    @overload
    def __init__(self, p0: str, p1: Charset) -> None: ...
    @overload
    def __init__(self, p0: str, p1: Charset, p2: bool) -> None: ...
    @overload
    def __init__(self, p0: File, p1: Charset) -> None: ...
    @overload
    def __init__(self, p0: File, p1: Charset, p2: bool) -> None: ...
    @overload
    def __init__(self, p0: str) -> None: ...
    @overload
    def __init__(self, p0: str, p1: bool) -> None: ...
    @overload
    def __init__(self, p0: File) -> None: ...
    @overload
    def __init__(self, p0: File, p1: bool) -> None: ...
