from typing import Any, ClassVar, overload
from java.io.InputStream import InputStream
from java.nio.CharBuffer import CharBuffer
from java.nio.charset.Charset import Charset
from java.nio.charset.CharsetDecoder import CharsetDecoder

class InputStreamReader:
    @overload
    def __init__(self, p0: InputStream, p1: Charset) -> None: ...
    @overload
    def __init__(self, p0: InputStream, p1: str) -> None: ...
    @overload
    def __init__(self, p0: InputStream) -> None: ...
    @overload
    def __init__(self, p0: InputStream, p1: CharsetDecoder) -> None: ...
    @overload
    def read(self, p0: Any, p1: int, p2: int) -> int: ...
    @overload
    def read(self, p0: CharBuffer) -> int: ...
    @overload
    def read(self) -> int: ...
    def close(self) -> None: ...
    def getEncoding(self) -> str: ...
    def ready(self) -> bool: ...
