from typing import Any, ClassVar, overload

class ObjectInput:
    def readObject(self) -> Any: ...
    @overload
    def read(self, p0: Any, p1: int, p2: int) -> int: ...
    @overload
    def read(self, p0: Any) -> int: ...
    @overload
    def read(self) -> int: ...
    def close(self) -> None: ...
    def skip(self, p0: int) -> int: ...
    def available(self) -> int: ...
