from typing import Any, ClassVar, overload
from java.io.PipedOutputStream import PipedOutputStream

class PipedInputStream:
    @overload
    def __init__(self, p0: PipedOutputStream) -> None: ...
    @overload
    def __init__(self, p0: int) -> None: ...
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, p0: PipedOutputStream, p1: int) -> None: ...
    def connect(self, p0: PipedOutputStream) -> None: ...
    def close(self) -> None: ...
    @overload
    def read(self, p0: Any, p1: int, p2: int) -> int: ...
    @overload
    def read(self) -> int: ...
    def available(self) -> int: ...
