from typing import Any, ClassVar, overload
from java.io.PipedInputStream import PipedInputStream

class PipedOutputStream:
    @overload
    def __init__(self, p0: PipedInputStream) -> None: ...
    @overload
    def __init__(self) -> None: ...
    def flush(self) -> None: ...
    @overload
    def write(self, p0: Any, p1: int, p2: int) -> None: ...
    @overload
    def write(self, p0: int) -> None: ...
    def connect(self, p0: PipedInputStream) -> None: ...
    def close(self) -> None: ...
