from typing import Any, ClassVar, overload
from android.os.ParcelFileDescriptor import ParcelFileDescriptor

class SQLiteStatement:
    def simpleQueryForLong(self) -> int: ...
    def executeInsert(self) -> int: ...
    def executeUpdateDelete(self) -> int: ...
    def simpleQueryForBlobFileDescriptor(self) -> ParcelFileDescriptor: ...
    def simpleQueryForString(self) -> str: ...
    def toString(self) -> str: ...
    def execute(self) -> None: ...
