from typing import Any, ClassVar, overload
from java.nio.file.attribute.BasicFileAttributes import BasicFileAttributes
from java.nio.file.attribute.FileTime import FileTime

class BasicFileAttributeView:
    def name(self) -> str: ...
    def readAttributes(self) -> BasicFileAttributes: ...
    def setTimes(self, p0: FileTime, p1: FileTime, p2: FileTime) -> None: ...
