from typing import Any, ClassVar, overload
from java.util.Random import Random

class BigInteger:
    ZERO: ClassVar["BigInteger"]
    ONE: ClassVar["BigInteger"]
    TWO: ClassVar["BigInteger"]
    TEN: ClassVar["BigInteger"]
    @overload
    def __init__(self, p0: int, p1: Any) -> None: ...
    @overload
    def __init__(self, p0: int, p1: Any, p2: int, p3: int) -> None: ...
    @overload
    def __init__(self, p0: Any) -> None: ...
    @overload
    def __init__(self, p0: Any, p1: int, p2: int) -> None: ...
    @overload
    def __init__(self, p0: int, p1: int, p2: Random) -> None: ...
    @overload
    def __init__(self, p0: int, p1: Random) -> None: ...
    @overload
    def __init__(self, p0: str) -> None: ...
    @overload
    def __init__(self, p0: str, p1: int) -> None: ...
    def subtract(self, p0: "BigInteger") -> "BigInteger": ...
    def multiply(self, p0: "BigInteger") -> "BigInteger": ...
    def divide(self, p0: "BigInteger") -> "BigInteger": ...
    def longValueExact(self) -> int: ...
    def divideAndRemainder(self, p0: "BigInteger") -> Any: ...
    def bitLength(self) -> int: ...
    def bitCount(self) -> int: ...
    def equals(self, p0: Any) -> bool: ...
    @overload
    def toString(self) -> str: ...
    @overload
    def toString(self, p0: int) -> str: ...
    def hashCode(self) -> int: ...
    def abs(self) -> "BigInteger": ...
    def sqrt(self) -> "BigInteger": ...
    def pow(self, p0: int) -> "BigInteger": ...
    def min(self, p0: "BigInteger") -> "BigInteger": ...
    def max(self, p0: "BigInteger") -> "BigInteger": ...
    def signum(self) -> int: ...
    @overload
    def compareTo(self, p0: "BigInteger") -> int: ...
    @overload
    def compareTo(self, p0: Any) -> int: ...
    def intValue(self) -> int: ...
    def longValue(self) -> int: ...
    def floatValue(self) -> float: ...
    def doubleValue(self) -> float: ...
    @staticmethod
    def valueOf(p0: int) -> "BigInteger": ...
    def add(self, p0: "BigInteger") -> "BigInteger": ...
    def mod(self, p0: "BigInteger") -> "BigInteger": ...
    def negate(self) -> "BigInteger": ...
    def shiftLeft(self, p0: int) -> "BigInteger": ...
    def remainder(self, p0: "BigInteger") -> "BigInteger": ...
    def setBit(self, p0: int) -> "BigInteger": ...
    def and_(self, p0: "BigInteger") -> "BigInteger": ...
    def not_(self) -> "BigInteger": ...
    def toByteArray(self) -> Any: ...
    def testBit(self, p0: int) -> bool: ...
    def shiftRight(self, p0: int) -> "BigInteger": ...
    def getLowestSetBit(self) -> int: ...
    def modPow(self, p0: "BigInteger", p1: "BigInteger") -> "BigInteger": ...
    def modInverse(self, p0: "BigInteger") -> "BigInteger": ...
    @staticmethod
    def probablePrime(p0: int, p1: Random) -> "BigInteger": ...
    def nextProbablePrime(self) -> "BigInteger": ...
    def parallelMultiply(self, p0: "BigInteger") -> "BigInteger": ...
    def sqrtAndRemainder(self) -> Any: ...
    def gcd(self, p0: "BigInteger") -> "BigInteger": ...
    def xor(self, p0: "BigInteger") -> "BigInteger": ...
    def andNot(self, p0: "BigInteger") -> "BigInteger": ...
    def clearBit(self, p0: int) -> "BigInteger": ...
    def flipBit(self, p0: int) -> "BigInteger": ...
    def isProbablePrime(self, p0: int) -> bool: ...
    def intValueExact(self) -> int: ...
    def shortValueExact(self) -> int: ...
    def byteValueExact(self) -> int: ...
    def or_(self, p0: "BigInteger") -> "BigInteger": ...

from typing import Any, ClassVar, overload
from java.math.RoundingMode import RoundingMode

class MathContext:
    UNLIMITED: ClassVar["MathContext"]
    DECIMAL32: ClassVar["MathContext"]
    DECIMAL64: ClassVar["MathContext"]
    DECIMAL128: ClassVar["MathContext"]
    @overload
    def __init__(self, p0: str) -> None: ...
    @overload
    def __init__(self, p0: int, p1: RoundingMode) -> None: ...
    @overload
    def __init__(self, p0: int) -> None: ...
    def getPrecision(self) -> int: ...
    def equals(self, p0: Any) -> bool: ...
    def toString(self) -> str: ...
    def hashCode(self) -> int: ...
    def getRoundingMode(self) -> RoundingMode: ...

from typing import Any, ClassVar, overload
from java.math.BigInteger import BigInteger
from java.math.MathContext import MathContext
from java.math.RoundingMode import RoundingMode

class BigDecimal:
    ZERO: ClassVar["BigDecimal"]
    ONE: ClassVar["BigDecimal"]
    TWO: ClassVar["BigDecimal"]
    TEN: ClassVar["BigDecimal"]
    ROUND_UP: ClassVar[int]
    ROUND_DOWN: ClassVar[int]
    ROUND_CEILING: ClassVar[int]
    ROUND_FLOOR: ClassVar[int]
    ROUND_HALF_UP: ClassVar[int]
    ROUND_HALF_DOWN: ClassVar[int]
    ROUND_HALF_EVEN: ClassVar[int]
    ROUND_UNNECESSARY: ClassVar[int]
    @overload
    def __init__(self, p0: Any, p1: int, p2: int) -> None: ...
    @overload
    def __init__(self, p0: BigInteger, p1: int, p2: MathContext) -> None: ...
    @overload
    def __init__(self, p0: BigInteger, p1: int) -> None: ...
    @overload
    def __init__(self, p0: BigInteger, p1: MathContext) -> None: ...
    @overload
    def __init__(self, p0: BigInteger) -> None: ...
    @overload
    def __init__(self, p0: int, p1: MathContext) -> None: ...
    @overload
    def __init__(self, p0: int) -> None: ...
    @overload
    def __init__(self, p0: int, p1: MathContext) -> None: ...
    @overload
    def __init__(self, p0: int) -> None: ...
    @overload
    def __init__(self, p0: str) -> None: ...
    @overload
    def __init__(self, p0: Any, p1: MathContext) -> None: ...
    @overload
    def __init__(self, p0: Any) -> None: ...
    @overload
    def __init__(self, p0: Any, p1: int, p2: int, p3: MathContext) -> None: ...
    @overload
    def __init__(self, p0: str, p1: MathContext) -> None: ...
    @overload
    def __init__(self, p0: float) -> None: ...
    @overload
    def __init__(self, p0: float, p1: MathContext) -> None: ...
    @overload
    def subtract(self, p0: "BigDecimal", p1: MathContext) -> "BigDecimal": ...
    @overload
    def subtract(self, p0: "BigDecimal") -> "BigDecimal": ...
    def movePointLeft(self, p0: int) -> "BigDecimal": ...
    def unscaledValue(self) -> BigInteger: ...
    @overload
    def multiply(self, p0: "BigDecimal") -> "BigDecimal": ...
    @overload
    def multiply(self, p0: "BigDecimal", p1: MathContext) -> "BigDecimal": ...
    def ulp(self) -> "BigDecimal": ...
    @overload
    def plus(self, p0: MathContext) -> "BigDecimal": ...
    @overload
    def plus(self) -> "BigDecimal": ...
    @overload
    def divide(self, p0: "BigDecimal") -> "BigDecimal": ...
    @overload
    def divide(self, p0: "BigDecimal", p1: MathContext) -> "BigDecimal": ...
    @overload
    def divide(self, p0: "BigDecimal", p1: int, p2: int) -> "BigDecimal": ...
    @overload
    def divide(self, p0: "BigDecimal", p1: int, p2: RoundingMode) -> "BigDecimal": ...
    @overload
    def divide(self, p0: "BigDecimal", p1: int) -> "BigDecimal": ...
    @overload
    def divide(self, p0: "BigDecimal", p1: RoundingMode) -> "BigDecimal": ...
    @overload
    def divideToIntegralValue(self, p0: "BigDecimal", p1: MathContext) -> "BigDecimal": ...
    @overload
    def divideToIntegralValue(self, p0: "BigDecimal") -> "BigDecimal": ...
    def longValueExact(self) -> int: ...
    def movePointRight(self, p0: int) -> "BigDecimal": ...
    def toBigIntegerExact(self) -> BigInteger: ...
    @overload
    def divideAndRemainder(self, p0: "BigDecimal") -> Any: ...
    @overload
    def divideAndRemainder(self, p0: "BigDecimal", p1: MathContext) -> Any: ...
    def toEngineeringString(self) -> str: ...
    def toPlainString(self) -> str: ...
    def stripTrailingZeros(self) -> "BigDecimal": ...
    def scaleByPowerOfTen(self, p0: int) -> "BigDecimal": ...
    def equals(self, p0: Any) -> bool: ...
    def toString(self) -> str: ...
    def hashCode(self) -> int: ...
    @overload
    def abs(self, p0: MathContext) -> "BigDecimal": ...
    @overload
    def abs(self) -> "BigDecimal": ...
    def sqrt(self, p0: MathContext) -> "BigDecimal": ...
    @overload
    def pow(self, p0: int) -> "BigDecimal": ...
    @overload
    def pow(self, p0: int, p1: MathContext) -> "BigDecimal": ...
    def min(self, p0: "BigDecimal") -> "BigDecimal": ...
    def max(self, p0: "BigDecimal") -> "BigDecimal": ...
    def round(self, p0: MathContext) -> "BigDecimal": ...
    def signum(self) -> int: ...
    @overload
    def compareTo(self, p0: "BigDecimal") -> int: ...
    @overload
    def compareTo(self, p0: Any) -> int: ...
    def intValue(self) -> int: ...
    def longValue(self) -> int: ...
    def floatValue(self) -> float: ...
    def doubleValue(self) -> float: ...
    @overload
    @staticmethod
    def valueOf(p0: float) -> "BigDecimal": ...
    @overload
    @staticmethod
    def valueOf(p0: int) -> "BigDecimal": ...
    @overload
    @staticmethod
    def valueOf(p0: int, p1: int) -> "BigDecimal": ...
    def scale(self) -> int: ...
    @overload
    def add(self, p0: "BigDecimal", p1: MathContext) -> "BigDecimal": ...
    @overload
    def add(self, p0: "BigDecimal") -> "BigDecimal": ...
    @overload
    def negate(self) -> "BigDecimal": ...
    @overload
    def negate(self, p0: MathContext) -> "BigDecimal": ...
    def precision(self) -> int: ...
    @overload
    def remainder(self, p0: "BigDecimal", p1: MathContext) -> "BigDecimal": ...
    @overload
    def remainder(self, p0: "BigDecimal") -> "BigDecimal": ...
    @overload
    def setScale(self, p0: int, p1: int) -> "BigDecimal": ...
    @overload
    def setScale(self, p0: int, p1: RoundingMode) -> "BigDecimal": ...
    @overload
    def setScale(self, p0: int) -> "BigDecimal": ...
    def toBigInteger(self) -> BigInteger: ...
    def intValueExact(self) -> int: ...
    def shortValueExact(self) -> int: ...
    def byteValueExact(self) -> int: ...

from typing import Any, ClassVar, overload

class RoundingMode:
    UP: ClassVar["RoundingMode"]
    DOWN: ClassVar["RoundingMode"]
    CEILING: ClassVar["RoundingMode"]
    FLOOR: ClassVar["RoundingMode"]
    HALF_UP: ClassVar["RoundingMode"]
    HALF_DOWN: ClassVar["RoundingMode"]
    HALF_EVEN: ClassVar["RoundingMode"]
    UNNECESSARY: ClassVar["RoundingMode"]
    UP: ClassVar["RoundingMode"]
    DOWN: ClassVar["RoundingMode"]
    CEILING: ClassVar["RoundingMode"]
    FLOOR: ClassVar["RoundingMode"]
    HALF_UP: ClassVar["RoundingMode"]
    HALF_DOWN: ClassVar["RoundingMode"]
    HALF_EVEN: ClassVar["RoundingMode"]
    UNNECESSARY: ClassVar["RoundingMode"]
    @staticmethod
    def values() -> Any: ...
    @overload
    @staticmethod
    def valueOf(p0: str) -> "RoundingMode": ...
    @overload
    @staticmethod
    def valueOf(p0: int) -> "RoundingMode": ...

