from typing import Any, ClassVar, overload
from android.bluetooth.BluetoothSocket import BluetoothSocket

class BluetoothServerSocket:
    def getPsm(self) -> int: ...
    def toString(self) -> str: ...
    @overload
    def accept(self, p0: int) -> BluetoothSocket: ...
    @overload
    def accept(self) -> BluetoothSocket: ...
    def close(self) -> None: ...
