from typing import Any, ClassVar, overload
from android.bluetooth.BluetoothDevice import BluetoothDevice
from android.bluetooth.BluetoothGattCharacteristic import BluetoothGattCharacteristic
from android.bluetooth.BluetoothGattService import BluetoothGattService
from java.util.UUID import UUID

class BluetoothGattServer:
    A2DP: ClassVar[int]
    CSIP_SET_COORDINATOR: ClassVar[int]
    EXTRA_PREVIOUS_STATE: ClassVar[str]
    EXTRA_STATE: ClassVar[str]
    GATT: ClassVar[int]
    GATT_SERVER: ClassVar[int]
    HAP_CLIENT: ClassVar[int]
    HEADSET: ClassVar[int]
    HEALTH: ClassVar[int]
    HEARING_AID: ClassVar[int]
    HID_DEVICE: ClassVar[int]
    LE_AUDIO: ClassVar[int]
    SAP: ClassVar[int]
    STATE_CONNECTED: ClassVar[int]
    STATE_CONNECTING: ClassVar[int]
    STATE_DISCONNECTED: ClassVar[int]
    STATE_DISCONNECTING: ClassVar[int]
    def getConnectionState(self, p0: BluetoothDevice) -> int: ...
    def getConnectedDevices(self) -> list: ...
    def getDevicesMatchingConnectionStates(self, p0: Any) -> list: ...
    def setPreferredPhy(self, p0: BluetoothDevice, p1: int, p2: int, p3: int) -> None: ...
    def cancelConnection(self, p0: BluetoothDevice) -> None: ...
    def readPhy(self, p0: BluetoothDevice) -> None: ...
    def sendResponse(self, p0: BluetoothDevice, p1: int, p2: int, p3: int, p4: Any) -> bool: ...
    @overload
    def notifyCharacteristicChanged(self, p0: BluetoothDevice, p1: BluetoothGattCharacteristic, p2: bool, p3: Any) -> int: ...
    @overload
    def notifyCharacteristicChanged(self, p0: BluetoothDevice, p1: BluetoothGattCharacteristic, p2: bool) -> bool: ...
    def addService(self, p0: BluetoothGattService) -> bool: ...
    def removeService(self, p0: BluetoothGattService) -> bool: ...
    def clearServices(self) -> None: ...
    def getService(self, p0: UUID) -> BluetoothGattService: ...
    def getServices(self) -> list: ...
    def connect(self, p0: BluetoothDevice, p1: bool) -> bool: ...
    def close(self) -> None: ...
