from typing import Any, ClassVar, overload
from java.lang.Throwable import Throwable

class Violation:
    def fillInStackTrace(self) -> Throwable: ...
    def initCause(self, p0: Throwable) -> Throwable: ...
    def hashCode(self) -> int: ...
    def setStackTrace(self, p0: Any) -> None: ...
