from typing import Any, ClassVar, overload
from android.adservices.common.AdServicesOutcomeReceiver import AdServicesOutcomeReceiver
from android.content.Context import Context
from android.os.OutcomeReceiver import OutcomeReceiver
from java.util.concurrent.Executor import Executor

class AdIdManager:
    @overload
    def getAdId(self, p0: Executor, p1: OutcomeReceiver) -> None: ...
    @overload
    def getAdId(self, p0: Executor, p1: AdServicesOutcomeReceiver) -> None: ...
    @staticmethod
    def get(p0: Context) -> "AdIdManager": ...

from typing import Any, ClassVar, overload

class AdId:
    ZERO_OUT: ClassVar[str]
    def __init__(self, p0: str, p1: bool) -> None: ...
    def getAdId(self) -> str: ...
    def isLimitAdTrackingEnabled(self) -> bool: ...
    def equals(self, p0: Any) -> bool: ...
    def toString(self) -> str: ...
    def hashCode(self) -> int: ...

