from typing import Any, ClassVar, overload
from android.content.Context import Context
from android.os.OutcomeReceiver import OutcomeReceiver
from java.util.concurrent.Executor import Executor

class AppSetIdManager:
    def getAppSetId(self, p0: Executor, p1: OutcomeReceiver) -> None: ...
    @staticmethod
    def get(p0: Context) -> "AppSetIdManager": ...

from typing import Any, ClassVar, overload

class AppSetId:
    SCOPE_APP: ClassVar[int]
    SCOPE_DEVELOPER: ClassVar[int]
    def __init__(self, p0: str, p1: int) -> None: ...
    def equals(self, p0: Any) -> bool: ...
    def hashCode(self) -> int: ...
    def getId(self) -> str: ...
    def getScope(self) -> int: ...

