from typing import Any, ClassVar, overload
from android.content.res.ColorStateList import ColorStateList
from android.content.res.Resources import Resources
from android.graphics.BlendMode import BlendMode
from android.graphics.Canvas import Canvas
from android.graphics.ColorFilter import ColorFilter
from android.graphics.Outline import Outline
from android.graphics.drawable.Drawable import Drawable
from android.util.AttributeSet import AttributeSet
from org.xmlpull.v1.XmlPullParser import XmlPullParser

class ColorDrawable:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, p0: int) -> None: ...
    def inflate(self, p0: Resources, p1: XmlPullParser, p2: AttributeSet, p3: Any) -> None: ...
    def getColorFilter(self) -> ColorFilter: ...
    def setAlpha(self, p0: int) -> None: ...
    def setColorFilter(self, p0: ColorFilter) -> None: ...
    def getChangingConfigurations(self) -> int: ...
    def setColor(self, p0: int) -> None: ...
    def draw(self, p0: Canvas) -> None: ...
    def getAlpha(self) -> int: ...
    def applyTheme(self, p0: Any) -> None: ...
    def canApplyTheme(self) -> bool: ...
    def getConstantState(self) -> Any: ...
    def getOpacity(self) -> int: ...
    def getOutline(self, p0: Outline) -> None: ...
    def hasFocusStateSpecified(self) -> bool: ...
    def isStateful(self) -> bool: ...
    def mutate(self) -> Drawable: ...
    def setTintBlendMode(self, p0: BlendMode) -> None: ...
    def setTintList(self, p0: ColorStateList) -> None: ...
    def getColor(self) -> int: ...
