from typing import Any, ClassVar, overload
from android.content.res.Resources import Resources
from android.graphics.Insets import Insets
from android.graphics.Outline import Outline
from android.graphics.Rect import Rect
from android.graphics.drawable.Drawable import Drawable
from android.util.AttributeSet import AttributeSet
from org.xmlpull.v1.XmlPullParser import XmlPullParser

class InsetDrawable:
    @overload
    def __init__(self, p0: Drawable, p1: float, p2: float, p3: float, p4: float) -> None: ...
    @overload
    def __init__(self, p0: Drawable, p1: int, p2: int, p3: int, p4: int) -> None: ...
    @overload
    def __init__(self, p0: Drawable, p1: float) -> None: ...
    @overload
    def __init__(self, p0: Drawable, p1: int) -> None: ...
    def inflate(self, p0: Resources, p1: XmlPullParser, p2: AttributeSet, p3: Any) -> None: ...
    def applyTheme(self, p0: Any) -> None: ...
    def getOpacity(self) -> int: ...
    def getIntrinsicWidth(self) -> int: ...
    def getIntrinsicHeight(self) -> int: ...
    def getPadding(self, p0: Rect) -> bool: ...
    def getOpticalInsets(self) -> Insets: ...
    def getOutline(self, p0: Outline) -> None: ...
