from typing import Any, ClassVar, overload
from android.content.res.ColorStateList import ColorStateList
from android.content.res.Resources import Resources
from android.graphics.Bitmap import Bitmap
from android.graphics.BlendMode import BlendMode
from android.graphics.Canvas import Canvas
from android.graphics.ColorFilter import ColorFilter
from android.graphics.Insets import Insets
from android.graphics.NinePatch import NinePatch
from android.graphics.Outline import Outline
from android.graphics.Paint import Paint
from android.graphics.Rect import Rect
from android.graphics.Region import Region
from android.graphics.drawable.Drawable import Drawable
from android.util.AttributeSet import AttributeSet
from android.util.DisplayMetrics import DisplayMetrics
from org.xmlpull.v1.XmlPullParser import XmlPullParser

class NinePatchDrawable:
    @overload
    def __init__(self, p0: Bitmap, p1: Any, p2: Rect, p3: str) -> None: ...
    @overload
    def __init__(self, p0: Resources, p1: Bitmap, p2: Any, p3: Rect, p4: str) -> None: ...
    @overload
    def __init__(self, p0: NinePatch) -> None: ...
    @overload
    def __init__(self, p0: Resources, p1: NinePatch) -> None: ...
    @overload
    def setTargetDensity(self, p0: DisplayMetrics) -> None: ...
    @overload
    def setTargetDensity(self, p0: int) -> None: ...
    @overload
    def setTargetDensity(self, p0: Canvas) -> None: ...
    def inflate(self, p0: Resources, p1: XmlPullParser, p2: AttributeSet, p3: Any) -> None: ...
    def getChangingConfigurations(self) -> int: ...
    def setColorFilter(self, p0: ColorFilter) -> None: ...
    def setAlpha(self, p0: int) -> None: ...
    def getAlpha(self) -> int: ...
    def draw(self, p0: Canvas) -> None: ...
    def setFilterBitmap(self, p0: bool) -> None: ...
    def setDither(self, p0: bool) -> None: ...
    def isFilterBitmap(self) -> bool: ...
    def setTintList(self, p0: ColorStateList) -> None: ...
    def setTintBlendMode(self, p0: BlendMode) -> None: ...
    def isStateful(self) -> bool: ...
    def hasFocusStateSpecified(self) -> bool: ...
    def setAutoMirrored(self, p0: bool) -> None: ...
    def isAutoMirrored(self) -> bool: ...
    def applyTheme(self, p0: Any) -> None: ...
    def canApplyTheme(self) -> bool: ...
    def getOpacity(self) -> int: ...
    def getTransparentRegion(self) -> Region: ...
    def getIntrinsicWidth(self) -> int: ...
    def getIntrinsicHeight(self) -> int: ...
    def getPadding(self, p0: Rect) -> bool: ...
    def getOpticalInsets(self) -> Insets: ...
    def getOutline(self, p0: Outline) -> None: ...
    def mutate(self) -> Drawable: ...
    def getConstantState(self) -> Any: ...
    def getPaint(self) -> Paint: ...
