from typing import Any, ClassVar, overload
from android.content.res.Resources import Resources
from android.graphics.drawable.Drawable import Drawable
from android.util.AttributeSet import AttributeSet
from org.xmlpull.v1.XmlPullParser import XmlPullParser

class StateListDrawable:
    def __init__(self) -> None: ...
    def addState(self, p0: Any, p1: Drawable) -> None: ...
    def getStateDrawable(self, p0: int) -> Drawable: ...
    def getStateCount(self) -> int: ...
    def getStateSet(self, p0: int) -> Any: ...
    def findStateDrawableIndex(self, p0: Any) -> int: ...
    def inflate(self, p0: Resources, p1: XmlPullParser, p2: AttributeSet, p3: Any) -> None: ...
    def applyTheme(self, p0: Any) -> None: ...
    def hasFocusStateSpecified(self) -> bool: ...
    def isStateful(self) -> bool: ...
    def mutate(self) -> Drawable: ...
