from typing import Any, ClassVar, overload
from android.app.Person import Person
from android.os.Bundle import Bundle
from android.os.Parcel import Parcel
from java.time.ZonedDateTime import ZonedDateTime

class ConversationActions:
    CREATOR: ClassVar[Any]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    def __init__(self, p0: list, p1: str) -> None: ...
    def getConversationActions(self) -> list: ...
    def getId(self) -> str: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
    def describeContents(self) -> int: ...

    class Request:
        CREATOR: ClassVar[Any]
        HINT_FOR_IN_APP: ClassVar[str]
        HINT_FOR_NOTIFICATION: ClassVar[str]
        CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
        PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
        def getCallingPackageName(self) -> str: ...
        def getHints(self) -> list: ...
        def getConversation(self) -> list: ...
        def getMaxSuggestions(self) -> int: ...
        def getTypeConfig(self) -> Any: ...
        def getExtras(self) -> Bundle: ...
        def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
        def describeContents(self) -> int: ...

        class Builder:
            def __init__(self, p0: list) -> None: ...
            def setTypeConfig(self, p0: Any) -> Any: ...
            def setHints(self, p0: list) -> Any: ...
            def build(self) -> Any: ...
            def setExtras(self, p0: Bundle) -> Any: ...
            def setMaxSuggestions(self, p0: int) -> Any: ...

    class Message:
        CREATOR: ClassVar[Any]
        PERSON_USER_OTHERS: ClassVar[Person]
        PERSON_USER_SELF: ClassVar[Person]
        CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
        PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
        def getReferenceTime(self) -> ZonedDateTime: ...
        def getAuthor(self) -> Person: ...
        def getExtras(self) -> Bundle: ...
        def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
        def describeContents(self) -> int: ...
        def getText(self) -> str: ...

        class Builder:
            def __init__(self, p0: Person) -> None: ...
            def setReferenceTime(self, p0: ZonedDateTime) -> Any: ...
            def build(self) -> Any: ...
            def setExtras(self, p0: Bundle) -> Any: ...
            def setText(self, p0: str) -> Any: ...
