from typing import Any, ClassVar, overload
from android.app.RemoteAction import RemoteAction
from android.content.Intent import Intent
from android.graphics.drawable.Drawable import Drawable
from android.os.Bundle import Bundle
from android.os.LocaleList import LocaleList
from android.os.Parcel import Parcel
from java.time.ZonedDateTime import ZonedDateTime

class TextClassification:
    CREATOR: ClassVar[Any]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    def getOnClickListener(self) -> Any: ...
    def getEntityCount(self) -> int: ...
    def getEntity(self, p0: int) -> str: ...
    def toString(self) -> str: ...
    def getActions(self) -> list: ...
    def getId(self) -> str: ...
    def getText(self) -> str: ...
    def getLabel(self) -> str: ...
    def getIntent(self) -> Intent: ...
    def getExtras(self) -> Bundle: ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
    def getIcon(self) -> Drawable: ...
    def getConfidenceScore(self, p0: str) -> float: ...

    class Request:
        CREATOR: ClassVar[Any]
        CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
        PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
        def getStartIndex(self) -> int: ...
        def getEndIndex(self) -> int: ...
        def getDefaultLocales(self) -> LocaleList: ...
        def getReferenceTime(self) -> ZonedDateTime: ...
        def getCallingPackageName(self) -> str: ...
        def getText(self) -> str: ...
        def getExtras(self) -> Bundle: ...
        def describeContents(self) -> int: ...
        def writeToParcel(self, p0: Parcel, p1: int) -> None: ...

        class Builder:
            def __init__(self, p0: str, p1: int, p2: int) -> None: ...
            def setDefaultLocales(self, p0: LocaleList) -> Any: ...
            def setReferenceTime(self, p0: ZonedDateTime) -> Any: ...
            def build(self) -> Any: ...
            def setExtras(self, p0: Bundle) -> Any: ...

    class Builder:
        def __init__(self) -> None: ...
        def setEntityType(self, p0: str, p1: float) -> Any: ...
        def build(self) -> "TextClassification": ...
        def addAction(self, p0: RemoteAction) -> Any: ...
        def setOnClickListener(self, p0: Any) -> Any: ...
        def setId(self, p0: str) -> Any: ...
        def setText(self, p0: str) -> Any: ...
        def setIntent(self, p0: Intent) -> Any: ...
        def setIcon(self, p0: Drawable) -> Any: ...
        def setExtras(self, p0: Bundle) -> Any: ...
        def setLabel(self, p0: str) -> Any: ...
