from typing import Any, ClassVar, overload
from android.os.LocaleList import LocaleList
from android.os.Parcel import Parcel
from android.view.textclassifier.ConversationActions import ConversationActions
from android.view.textclassifier.SelectionEvent import SelectionEvent
from android.view.textclassifier.TextClassification import TextClassification
from android.view.textclassifier.TextClassifierEvent import TextClassifierEvent
from android.view.textclassifier.TextLanguage import TextLanguage
from android.view.textclassifier.TextLinks import TextLinks
from android.view.textclassifier.TextSelection import TextSelection

class TextClassifier:
    EXTRA_FROM_TEXT_CLASSIFIER: ClassVar[str]
    HINT_TEXT_IS_EDITABLE: ClassVar[str]
    HINT_TEXT_IS_NOT_EDITABLE: ClassVar[str]
    NO_OP: ClassVar["TextClassifier"]
    TYPE_ADDRESS: ClassVar[str]
    TYPE_DATE: ClassVar[str]
    TYPE_DATE_TIME: ClassVar[str]
    TYPE_EMAIL: ClassVar[str]
    TYPE_FLIGHT_NUMBER: ClassVar[str]
    TYPE_OTHER: ClassVar[str]
    TYPE_PHONE: ClassVar[str]
    TYPE_UNKNOWN: ClassVar[str]
    TYPE_URL: ClassVar[str]
    WIDGET_TYPE_CLIPBOARD: ClassVar[str]
    WIDGET_TYPE_CUSTOM_EDITTEXT: ClassVar[str]
    WIDGET_TYPE_CUSTOM_TEXTVIEW: ClassVar[str]
    WIDGET_TYPE_CUSTOM_UNSELECTABLE_TEXTVIEW: ClassVar[str]
    WIDGET_TYPE_EDITTEXT: ClassVar[str]
    WIDGET_TYPE_EDIT_WEBVIEW: ClassVar[str]
    WIDGET_TYPE_NOTIFICATION: ClassVar[str]
    WIDGET_TYPE_TEXTVIEW: ClassVar[str]
    WIDGET_TYPE_UNKNOWN: ClassVar[str]
    WIDGET_TYPE_UNSELECTABLE_TEXTVIEW: ClassVar[str]
    WIDGET_TYPE_WEBVIEW: ClassVar[str]
    def isDestroyed(self) -> bool: ...
    def destroy(self) -> None: ...
    @overload
    def suggestSelection(self, p0: Any) -> TextSelection: ...
    @overload
    def suggestSelection(self, p0: str, p1: int, p2: int, p3: LocaleList) -> TextSelection: ...
    @overload
    def classifyText(self, p0: Any) -> TextClassification: ...
    @overload
    def classifyText(self, p0: str, p1: int, p2: int, p3: LocaleList) -> TextClassification: ...
    def generateLinks(self, p0: Any) -> TextLinks: ...
    def getMaxGenerateLinksTextLength(self) -> int: ...
    def detectLanguage(self, p0: Any) -> TextLanguage: ...
    def suggestConversationActions(self, p0: Any) -> ConversationActions: ...
    def onSelectionEvent(self, p0: SelectionEvent) -> None: ...
    def onTextClassifierEvent(self, p0: TextClassifierEvent) -> None: ...

    class EntityConfig:
        CREATOR: ClassVar[Any]
        CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
        PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
        def getHints(self) -> list: ...
        def shouldIncludeTypesFromTextClassifier(self) -> bool: ...
        @staticmethod
        def createWithHints(p0: list) -> Any: ...
        @staticmethod
        def createWithExplicitEntityList(p0: list) -> Any: ...
        def resolveEntityListModifications(self, p0: list) -> list: ...
        @staticmethod
        def create(p0: list, p1: list, p2: list) -> Any: ...
        def describeContents(self) -> int: ...
        def writeToParcel(self, p0: Parcel, p1: int) -> None: ...

        class Builder:
            def __init__(self) -> None: ...
            def setExcludedTypes(self, p0: list) -> Any: ...
            def setIncludedTypes(self, p0: list) -> Any: ...
            def includeTypesFromTextClassifier(self, p0: bool) -> Any: ...
            def setHints(self, p0: list) -> Any: ...
            def build(self) -> Any: ...
