from typing import Any, ClassVar, overload
from java.util.Iterator import Iterator

class DrmSupportInfo:
    def __init__(self) -> None: ...
    def getDescriprition(self) -> str: ...
    def addFileSuffix(self, p0: str) -> None: ...
    def addMimeType(self, p0: str) -> None: ...
    def getFileSuffixIterator(self) -> Iterator: ...
    def getMimeTypeIterator(self) -> Iterator: ...
    def equals(self, p0: Any) -> bool: ...
    def hashCode(self) -> int: ...
    def setDescription(self, p0: str) -> None: ...
    def getDescription(self) -> str: ...
