from typing import Any, ClassVar, overload
from java.util.Iterator import Iterator

class DrmUtils:
    def __init__(self) -> None: ...
    @staticmethod
    def getExtendedMetadataParser(p0: Any) -> Any: ...

    class ExtendedMetadataParser:
        def keyIterator(self) -> Iterator: ...
        def get(self, p0: str) -> str: ...
        def iterator(self) -> Iterator: ...
