from typing import Any, ClassVar, overload
from android.view.MotionEvent import MotionEvent
from java.util.concurrent.Executor import Executor

class TouchInteractionController:
    STATE_CLEAR: ClassVar[int]
    STATE_DELEGATING: ClassVar[int]
    STATE_DRAGGING: ClassVar[int]
    STATE_TOUCH_EXPLORING: ClassVar[int]
    STATE_TOUCH_INTERACTING: ClassVar[int]
    def unregisterAllCallbacks(self) -> None: ...
    def requestTouchExploration(self) -> None: ...
    def requestDragging(self, p0: int) -> None: ...
    def requestDelegating(self) -> None: ...
    def performLongClickAndStartDrag(self) -> None: ...
    def getMaxPointerCount(self) -> int: ...
    @staticmethod
    def stateToString(p0: int) -> str: ...
    def getState(self) -> int: ...
    def performClick(self) -> None: ...
    def getDisplayId(self) -> int: ...
    def registerCallback(self, p0: Executor, p1: Any) -> None: ...
    def unregisterCallback(self, p0: Any) -> bool: ...

    class Callback:
        def onStateChanged(self, p0: int) -> None: ...
        def onMotionEvent(self, p0: MotionEvent) -> None: ...
