from typing import Any, ClassVar, overload

class AtomicStampedReference:
    def __init__(self, p0: Any, p1: int) -> None: ...
    def getStamp(self) -> int: ...
    def getReference(self) -> Any: ...
    def get(self, p0: Any) -> Any: ...
    def set(self, p0: Any, p1: int) -> None: ...
    def compareAndSet(self, p0: Any, p1: Any, p2: int, p3: int) -> bool: ...
    def weakCompareAndSet(self, p0: Any, p1: Any, p2: int, p3: int) -> bool: ...
    def attemptStamp(self, p0: Any, p1: int) -> bool: ...
