from typing import Any, ClassVar, overload
from java.util.function.LongBinaryOperator import LongBinaryOperator
from java.util.function.LongUnaryOperator import LongUnaryOperator

class AtomicLongFieldUpdater:
    @staticmethod
    def newUpdater(p0: type, p1: str) -> "AtomicLongFieldUpdater": ...
    def get(self, p0: Any) -> int: ...
    def set(self, p0: Any, p1: int) -> None: ...
    def compareAndSet(self, p0: Any, p1: int, p2: int) -> bool: ...
    def weakCompareAndSet(self, p0: Any, p1: int, p2: int) -> bool: ...
    def getAndSet(self, p0: Any, p1: int) -> int: ...
    def getAndAdd(self, p0: Any, p1: int) -> int: ...
    def incrementAndGet(self, p0: Any) -> int: ...
    def lazySet(self, p0: Any, p1: int) -> None: ...
    def getAndIncrement(self, p0: Any) -> int: ...
    def getAndDecrement(self, p0: Any) -> int: ...
    def decrementAndGet(self, p0: Any) -> int: ...
    def addAndGet(self, p0: Any, p1: int) -> int: ...
    def getAndUpdate(self, p0: Any, p1: LongUnaryOperator) -> int: ...
    def updateAndGet(self, p0: Any, p1: LongUnaryOperator) -> int: ...
    def getAndAccumulate(self, p0: Any, p1: int, p2: LongBinaryOperator) -> int: ...
    def accumulateAndGet(self, p0: Any, p1: int, p2: LongBinaryOperator) -> int: ...
