from typing import Any, ClassVar, overload

class TvContentRating:
    UNRATED: ClassVar["TvContentRating"]
    def getDomain(self) -> str: ...
    @staticmethod
    def createRating(p0: str, p1: str, p2: str, p3: Any) -> "TvContentRating": ...
    def getRatingSystem(self) -> str: ...
    def getMainRating(self) -> str: ...
    def getSubRatings(self) -> list: ...
    def equals(self, p0: Any) -> bool: ...
    def hashCode(self) -> int: ...
    def contains(self, p0: "TvContentRating") -> bool: ...
    def flattenToString(self) -> str: ...
    @staticmethod
    def unflattenFromString(p0: str) -> "TvContentRating": ...
