from typing import Any, ClassVar, overload
from java.time.Instant import Instant
from java.time.LocalTime import LocalTime
from java.time.ZoneId import ZoneId
from java.time.ZoneOffset import ZoneOffset
from java.time.chrono.ChronoLocalDate import ChronoLocalDate
from java.time.chrono.ChronoLocalDateTime import ChronoLocalDateTime
from java.time.chrono.Chronology import Chronology
from java.time.format.DateTimeFormatter import DateTimeFormatter
from java.time.temporal.Temporal import Temporal
from java.time.temporal.TemporalAccessor import TemporalAccessor
from java.time.temporal.TemporalAdjuster import TemporalAdjuster
from java.time.temporal.TemporalAmount import TemporalAmount
from java.time.temporal.TemporalField import TemporalField
from java.time.temporal.TemporalQuery import TemporalQuery
from java.time.temporal.TemporalUnit import TemporalUnit
from java.time.temporal.ValueRange import ValueRange
from java.util.Comparator import Comparator

class ChronoZonedDateTime:
    def equals(self, p0: Any) -> bool: ...
    def toString(self) -> str: ...
    def hashCode(self) -> int: ...
    @overload
    def compareTo(self, p0: Any) -> int: ...
    @overload
    def compareTo(self, p0: "ChronoZonedDateTime") -> int: ...
    def getLong(self, p0: TemporalField) -> int: ...
    def get(self, p0: TemporalField) -> int: ...
    def format(self, p0: DateTimeFormatter) -> str: ...
    @staticmethod
    def from_(p0: TemporalAccessor) -> "ChronoZonedDateTime": ...
    @overload
    def isSupported(self, p0: TemporalUnit) -> bool: ...
    @overload
    def isSupported(self, p0: TemporalField) -> bool: ...
    @overload
    def with_(self, p0: TemporalAdjuster) -> Temporal: ...
    @overload
    def with_(self, p0: TemporalAdjuster) -> "ChronoZonedDateTime": ...
    @overload
    def with_(self, p0: TemporalField, p1: int) -> Temporal: ...
    @overload
    def with_(self, p0: TemporalField, p1: int) -> "ChronoZonedDateTime": ...
    def query(self, p0: TemporalQuery) -> Any: ...
    def getOffset(self) -> ZoneOffset: ...
    def isEqual(self, p0: "ChronoZonedDateTime") -> bool: ...
    def range(self, p0: TemporalField) -> ValueRange: ...
    def toLocalDateTime(self) -> ChronoLocalDateTime: ...
    def toLocalDate(self) -> ChronoLocalDate: ...
    def withZoneSameInstant(self, p0: ZoneId) -> "ChronoZonedDateTime": ...
    def withZoneSameLocal(self, p0: ZoneId) -> "ChronoZonedDateTime": ...
    def withLaterOffsetAtOverlap(self) -> "ChronoZonedDateTime": ...
    def withEarlierOffsetAtOverlap(self) -> "ChronoZonedDateTime": ...
    @overload
    def plus(self, p0: TemporalAmount) -> Temporal: ...
    @overload
    def plus(self, p0: int, p1: TemporalUnit) -> "ChronoZonedDateTime": ...
    @overload
    def plus(self, p0: TemporalAmount) -> "ChronoZonedDateTime": ...
    @overload
    def plus(self, p0: int, p1: TemporalUnit) -> Temporal: ...
    @overload
    def minus(self, p0: int, p1: TemporalUnit) -> Temporal: ...
    @overload
    def minus(self, p0: TemporalAmount) -> Temporal: ...
    @overload
    def minus(self, p0: TemporalAmount) -> "ChronoZonedDateTime": ...
    @overload
    def minus(self, p0: int, p1: TemporalUnit) -> "ChronoZonedDateTime": ...
    def getChronology(self) -> Chronology: ...
    def getZone(self) -> ZoneId: ...
    def toLocalTime(self) -> LocalTime: ...
    def isAfter(self, p0: "ChronoZonedDateTime") -> bool: ...
    def isBefore(self, p0: "ChronoZonedDateTime") -> bool: ...
    @staticmethod
    def timeLineOrder() -> Comparator: ...
    def toEpochSecond(self) -> int: ...
    def toInstant(self) -> Instant: ...
