from typing import Any, ClassVar, overload
from java.lang.ClassLoader import ClassLoader
from javax.xml.parsers.SAXParser import SAXParser
from javax.xml.validation.Schema import Schema

class SAXParserFactory:
    def setSchema(self, p0: Schema) -> None: ...
    @overload
    @staticmethod
    def newInstance() -> "SAXParserFactory": ...
    @overload
    @staticmethod
    def newInstance(p0: str, p1: ClassLoader) -> "SAXParserFactory": ...
    @staticmethod
    def newDefaultInstance() -> "SAXParserFactory": ...
    def getFeature(self, p0: str) -> bool: ...
    def setFeature(self, p0: str, p1: bool) -> None: ...
    def getSchema(self) -> Schema: ...
    def setNamespaceAware(self, p0: bool) -> None: ...
    @staticmethod
    def newDefaultNSInstance() -> "SAXParserFactory": ...
    @overload
    @staticmethod
    def newNSInstance() -> "SAXParserFactory": ...
    @overload
    @staticmethod
    def newNSInstance(p0: str, p1: ClassLoader) -> "SAXParserFactory": ...
    def newSAXParser(self) -> SAXParser: ...
    def setValidating(self, p0: bool) -> None: ...
    def isNamespaceAware(self) -> bool: ...
    def isValidating(self) -> bool: ...
    def setXIncludeAware(self, p0: bool) -> None: ...
    def isXIncludeAware(self) -> bool: ...
