from typing import Any, ClassVar, overload
from javax.security.auth.Subject import Subject

class SubjectDomainCombiner:
    def __init__(self, p0: Subject) -> None: ...
    def getSubject(self) -> Subject: ...
    def combine(self, p0: Any, p1: Any) -> Any: ...

from typing import Any, ClassVar, overload
from java.security.Permission import Permission
from java.security.PermissionCollection import PermissionCollection

class PrivateCredentialPermission:
    def __init__(self, p0: str, p1: str) -> None: ...
    def newPermissionCollection(self) -> PermissionCollection: ...
    def getCredentialClass(self) -> str: ...
    def equals(self, p0: Any) -> bool: ...
    def hashCode(self) -> int: ...
    def implies(self, p0: Permission) -> bool: ...
    def getActions(self) -> str: ...
    def getPrincipals(self) -> Any: ...

from typing import Any, ClassVar, overload
from java.security.AccessControlContext import AccessControlContext
from java.security.PrivilegedAction import PrivilegedAction
from java.security.PrivilegedExceptionAction import PrivilegedExceptionAction
from java.util.concurrent.Callable import Callable

class Subject:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, p0: bool, p1: set, p2: set, p3: set) -> None: ...
    @staticmethod
    def getSubject(p0: AccessControlContext) -> "Subject": ...
    @overload
    @staticmethod
    def doAs(p0: "Subject", p1: PrivilegedExceptionAction) -> Any: ...
    @overload
    @staticmethod
    def doAs(p0: "Subject", p1: PrivilegedAction) -> Any: ...
    @staticmethod
    def callAs(p0: "Subject", p1: Callable) -> Any: ...
    @overload
    @staticmethod
    def doAsPrivileged(p0: "Subject", p1: PrivilegedExceptionAction, p2: AccessControlContext) -> Any: ...
    @overload
    @staticmethod
    def doAsPrivileged(p0: "Subject", p1: PrivilegedAction, p2: AccessControlContext) -> Any: ...
    @overload
    def getPublicCredentials(self, p0: type) -> set: ...
    @overload
    def getPublicCredentials(self) -> set: ...
    @overload
    def getPrivateCredentials(self, p0: type) -> set: ...
    @overload
    def getPrivateCredentials(self) -> set: ...
    def equals(self, p0: Any) -> bool: ...
    def toString(self) -> str: ...
    def hashCode(self) -> int: ...
    def setReadOnly(self) -> None: ...
    @overload
    def getPrincipals(self) -> set: ...
    @overload
    def getPrincipals(self, p0: type) -> set: ...
    @staticmethod
    def current() -> "Subject": ...
    def isReadOnly(self) -> bool: ...

from typing import Any, ClassVar, overload

class Destroyable:
    def isDestroyed(self) -> bool: ...
    def destroy(self) -> None: ...

from typing import Any, ClassVar, overload

class AuthPermission:
    @overload
    def __init__(self, p0: str) -> None: ...
    @overload
    def __init__(self, p0: str, p1: str) -> None: ...

from typing import Any, ClassVar, overload

class DestroyFailedException:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, p0: str) -> None: ...

