from typing import Any, ClassVar, overload
from java.time.ZoneId import ZoneId
from java.time.temporal.Temporal import Temporal
from java.time.temporal.TemporalAccessor import TemporalAccessor
from java.time.temporal.TemporalField import TemporalField
from java.time.temporal.TemporalQuery import TemporalQuery
from java.time.temporal.ValueRange import ValueRange
from java.time.zone.ZoneRules import ZoneRules

class ZoneOffset:
    UTC: ClassVar["ZoneOffset"]
    MIN: ClassVar["ZoneOffset"]
    MAX: ClassVar["ZoneOffset"]
    SHORT_IDS: ClassVar[dict]
    def equals(self, p0: Any) -> bool: ...
    def toString(self) -> str: ...
    def hashCode(self) -> int: ...
    @overload
    def compareTo(self, p0: "ZoneOffset") -> int: ...
    @overload
    def compareTo(self, p0: Any) -> int: ...
    def getLong(self, p0: TemporalField) -> int: ...
    @staticmethod
    def of(p0: str) -> "ZoneOffset": ...
    def get(self, p0: TemporalField) -> int: ...
    @staticmethod
    def from_(p0: TemporalAccessor) -> "ZoneOffset": ...
    def isSupported(self, p0: TemporalField) -> bool: ...
    def getId(self) -> str: ...
    def query(self, p0: TemporalQuery) -> Any: ...
    def range(self, p0: TemporalField) -> ValueRange: ...
    def normalized(self) -> ZoneId: ...
    @staticmethod
    def ofHoursMinutesSeconds(p0: int, p1: int, p2: int) -> "ZoneOffset": ...
    @staticmethod
    def ofTotalSeconds(p0: int) -> "ZoneOffset": ...
    @staticmethod
    def ofHoursMinutes(p0: int, p1: int) -> "ZoneOffset": ...
    @staticmethod
    def ofHours(p0: int) -> "ZoneOffset": ...
    def getTotalSeconds(self) -> int: ...
    def adjustInto(self, p0: Temporal) -> Temporal: ...
    def getRules(self) -> ZoneRules: ...
