from typing import Any, ClassVar, overload

class HttpParams:
    def getBooleanParameter(self, p0: str, p1: bool) -> bool: ...
    def getDoubleParameter(self, p0: str, p1: float) -> float: ...
    def getIntParameter(self, p0: str, p1: int) -> int: ...
    def getLongParameter(self, p0: str, p1: int) -> int: ...
    def isParameterFalse(self, p0: str) -> bool: ...
    def isParameterTrue(self, p0: str) -> bool: ...
    def removeParameter(self, p0: str) -> bool: ...
    def setBooleanParameter(self, p0: str, p1: bool) -> "HttpParams": ...
    def setDoubleParameter(self, p0: str, p1: float) -> "HttpParams": ...
    def setIntParameter(self, p0: str, p1: int) -> "HttpParams": ...
    def setLongParameter(self, p0: str, p1: int) -> "HttpParams": ...
    def setParameter(self, p0: str, p1: Any) -> "HttpParams": ...
    def getParameter(self, p0: str) -> Any: ...
    def copy(self) -> "HttpParams": ...

from typing import Any, ClassVar, overload
from org.apache.http.params.HttpParams import HttpParams

class HttpConnectionParams:
    CONNECTION_TIMEOUT: ClassVar[str]
    MAX_HEADER_COUNT: ClassVar[str]
    MAX_LINE_LENGTH: ClassVar[str]
    SOCKET_BUFFER_SIZE: ClassVar[str]
    SO_LINGER: ClassVar[str]
    SO_TIMEOUT: ClassVar[str]
    STALE_CONNECTION_CHECK: ClassVar[str]
    TCP_NODELAY: ClassVar[str]
    @staticmethod
    def getSocketBufferSize(p0: HttpParams) -> int: ...
    @staticmethod
    def isStaleCheckingEnabled(p0: HttpParams) -> bool: ...
    @staticmethod
    def setConnectionTimeout(p0: HttpParams, p1: int) -> None: ...
    @staticmethod
    def getConnectionTimeout(p0: HttpParams) -> int: ...
    @staticmethod
    def getLinger(p0: HttpParams) -> int: ...
    @staticmethod
    def setLinger(p0: HttpParams, p1: int) -> None: ...
    @staticmethod
    def setSocketBufferSize(p0: HttpParams, p1: int) -> None: ...
    @staticmethod
    def setStaleCheckingEnabled(p0: HttpParams, p1: bool) -> None: ...
    @staticmethod
    def setSoTimeout(p0: HttpParams, p1: int) -> None: ...
    @staticmethod
    def getSoTimeout(p0: HttpParams) -> int: ...
    @staticmethod
    def setTcpNoDelay(p0: HttpParams, p1: bool) -> None: ...
    @staticmethod
    def getTcpNoDelay(p0: HttpParams) -> bool: ...

from typing import Any, ClassVar, overload

class CoreConnectionPNames:
    CONNECTION_TIMEOUT: ClassVar[str]
    MAX_HEADER_COUNT: ClassVar[str]
    MAX_LINE_LENGTH: ClassVar[str]
    SOCKET_BUFFER_SIZE: ClassVar[str]
    SO_LINGER: ClassVar[str]
    SO_TIMEOUT: ClassVar[str]
    STALE_CONNECTION_CHECK: ClassVar[str]
    TCP_NODELAY: ClassVar[str]

