from typing import Any, ClassVar, overload
from java.util.Enumeration import Enumeration
from javax.net.ssl.SSLSession import SSLSession

class SSLSessionContext:
    def getSession(self, p0: Any) -> SSLSession: ...
    def getIds(self) -> Enumeration: ...
    def setSessionTimeout(self, p0: int) -> None: ...
    def getSessionTimeout(self) -> int: ...
    def setSessionCacheSize(self, p0: int) -> None: ...
    def getSessionCacheSize(self) -> int: ...
