from typing import Any, ClassVar, overload

class X509TrustManager:
    def checkServerTrusted(self, p0: Any, p1: str) -> None: ...
    def checkClientTrusted(self, p0: Any, p1: str) -> None: ...
    def getAcceptedIssuers(self) -> Any: ...
