from typing import Any, ClassVar, overload
from android.adservices.common.AdData import AdData
from android.os.Parcel import Parcel

class AdWithBid:
    CREATOR: ClassVar[Any]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    def __init__(self, p0: AdData, p1: float) -> None: ...
    def equals(self, p0: Any) -> bool: ...
    def hashCode(self) -> int: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
    def describeContents(self) -> int: ...
    def getAdData(self) -> AdData: ...
    def getBid(self) -> float: ...
