from typing import Any, ClassVar, overload
from android.net.Network import Network
from android.net.NetworkRequest import NetworkRequest
from android.net.nsd.DiscoveryRequest import DiscoveryRequest
from android.net.nsd.NsdServiceInfo import NsdServiceInfo
from java.util.concurrent.Executor import Executor

class NsdManager:
    ACTION_NSD_STATE_CHANGED: ClassVar[str]
    EXTRA_NSD_STATE: ClassVar[str]
    FAILURE_ALREADY_ACTIVE: ClassVar[int]
    FAILURE_BAD_PARAMETERS: ClassVar[int]
    FAILURE_INTERNAL_ERROR: ClassVar[int]
    FAILURE_MAX_LIMIT: ClassVar[int]
    FAILURE_OPERATION_NOT_RUNNING: ClassVar[int]
    NSD_STATE_DISABLED: ClassVar[int]
    NSD_STATE_ENABLED: ClassVar[int]
    PROTOCOL_DNS_SD: ClassVar[int]
    @overload
    def registerService(self, p0: NsdServiceInfo, p1: int, p2: Executor, p3: Any) -> None: ...
    @overload
    def registerService(self, p0: NsdServiceInfo, p1: int, p2: Any) -> None: ...
    def unregisterService(self, p0: Any) -> None: ...
    def stopServiceDiscovery(self, p0: Any) -> None: ...
    def stopServiceResolution(self, p0: Any) -> None: ...
    def registerServiceInfoCallback(self, p0: NsdServiceInfo, p1: Executor, p2: Any) -> None: ...
    def unregisterServiceInfoCallback(self, p0: Any) -> None: ...
    @overload
    def discoverServices(self, p0: str, p1: int, p2: NetworkRequest, p3: Executor, p4: Any) -> None: ...
    @overload
    def discoverServices(self, p0: str, p1: int, p2: Any) -> None: ...
    @overload
    def discoverServices(self, p0: str, p1: int, p2: Network, p3: Executor, p4: Any) -> None: ...
    @overload
    def discoverServices(self, p0: DiscoveryRequest, p1: Executor, p2: Any) -> None: ...
    @overload
    def resolveService(self, p0: NsdServiceInfo, p1: Executor, p2: Any) -> None: ...
    @overload
    def resolveService(self, p0: NsdServiceInfo, p1: Any) -> None: ...

    class ServiceInfoCallback:
        def onServiceLost(self) -> None: ...
        def onServiceInfoCallbackRegistrationFailed(self, p0: int) -> None: ...
        def onServiceUpdated(self, p0: NsdServiceInfo) -> None: ...
        def onServiceInfoCallbackUnregistered(self) -> None: ...

    class ResolveListener:
        def onResolveFailed(self, p0: NsdServiceInfo, p1: int) -> None: ...
        def onServiceResolved(self, p0: NsdServiceInfo) -> None: ...
        def onResolutionStopped(self, p0: NsdServiceInfo) -> None: ...
        def onStopResolutionFailed(self, p0: NsdServiceInfo, p1: int) -> None: ...

    class RegistrationListener:
        def onUnregistrationFailed(self, p0: NsdServiceInfo, p1: int) -> None: ...
        def onServiceRegistered(self, p0: NsdServiceInfo) -> None: ...
        def onServiceUnregistered(self, p0: NsdServiceInfo) -> None: ...
        def onRegistrationFailed(self, p0: NsdServiceInfo, p1: int) -> None: ...

    class DiscoveryListener:
        def onServiceLost(self, p0: NsdServiceInfo) -> None: ...
        def onStartDiscoveryFailed(self, p0: str, p1: int) -> None: ...
        def onStopDiscoveryFailed(self, p0: str, p1: int) -> None: ...
        def onDiscoveryStarted(self, p0: str) -> None: ...
        def onDiscoveryStopped(self, p0: str) -> None: ...
        def onServiceFound(self, p0: NsdServiceInfo) -> None: ...
