from typing import Any, ClassVar, overload
from java.io.InputStream import InputStream
from java.io.OutputStream import OutputStream
from java.net.URI import URI
from java.nio.channels.AsynchronousFileChannel import AsynchronousFileChannel
from java.nio.channels.FileChannel import FileChannel
from java.nio.channels.SeekableByteChannel import SeekableByteChannel
from java.nio.file.DirectoryStream import DirectoryStream
from java.nio.file.FileStore import FileStore
from java.nio.file.FileSystem import FileSystem
from java.nio.file.Path import Path
from java.nio.file.attribute.BasicFileAttributes import BasicFileAttributes
from java.nio.file.attribute.FileAttributeView import FileAttributeView
from java.util.concurrent.ExecutorService import ExecutorService

class FileSystemProvider:
    def newByteChannel(self, p0: Path, p1: set, p2: Any) -> SeekableByteChannel: ...
    def newDirectoryStream(self, p0: Path, p1: Any) -> DirectoryStream: ...
    def createSymbolicLink(self, p0: Path, p1: Path, p2: Any) -> None: ...
    def createLink(self, p0: Path, p1: Path) -> None: ...
    def readSymbolicLink(self, p0: Path) -> Path: ...
    def setAttribute(self, p0: Path, p1: str, p2: Any, p3: Any) -> None: ...
    def deleteIfExists(self, p0: Path) -> bool: ...
    @staticmethod
    def installedProviders() -> list: ...
    def newInputStream(self, p0: Path, p1: Any) -> InputStream: ...
    def newOutputStream(self, p0: Path, p1: Any) -> OutputStream: ...
    def isHidden(self, p0: Path) -> bool: ...
    def delete(self, p0: Path) -> None: ...
    def checkAccess(self, p0: Path, p1: Any) -> None: ...
    def copy(self, p0: Path, p1: Path, p2: Any) -> None: ...
    def exists(self, p0: Path, p1: Any) -> bool: ...
    def createDirectory(self, p0: Path, p1: Any) -> None: ...
    def getFileSystem(self, p0: URI) -> FileSystem: ...
    @overload
    def readAttributes(self, p0: Path, p1: str, p2: Any) -> dict: ...
    @overload
    def readAttributes(self, p0: Path, p1: type, p2: Any) -> BasicFileAttributes: ...
    @overload
    def newFileSystem(self, p0: URI, p1: dict) -> FileSystem: ...
    @overload
    def newFileSystem(self, p0: Path, p1: dict) -> FileSystem: ...
    def getFileAttributeView(self, p0: Path, p1: type, p2: Any) -> FileAttributeView: ...
    def getFileStore(self, p0: Path) -> FileStore: ...
    def readAttributesIfExists(self, p0: Path, p1: type, p2: Any) -> BasicFileAttributes: ...
    def newFileChannel(self, p0: Path, p1: set, p2: Any) -> FileChannel: ...
    def newAsynchronousFileChannel(self, p0: Path, p1: set, p2: ExecutorService, p3: Any) -> AsynchronousFileChannel: ...
    def move(self, p0: Path, p1: Path, p2: Any) -> None: ...
    def isSameFile(self, p0: Path, p1: Path) -> bool: ...
    def getPath(self, p0: URI) -> Path: ...
    def getScheme(self) -> str: ...

from typing import Any, ClassVar, overload
from java.nio.file.Path import Path

class FileTypeDetector:
    def probeContentType(self, p0: Path) -> str: ...

