from typing import Any, ClassVar, overload
from java.nio.file.Watchable import Watchable

class WatchKey:
    def reset(self) -> bool: ...
    def cancel(self) -> None: ...
    def isValid(self) -> bool: ...
    def pollEvents(self) -> list: ...
    def watchable(self) -> Watchable: ...
