from typing import Any, ClassVar, overload

class Matrix3f:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, p0: Any) -> None: ...
    def loadMultiply(self, p0: "Matrix3f", p1: "Matrix3f") -> None: ...
    @overload
    def loadRotate(self, p0: float) -> None: ...
    @overload
    def loadRotate(self, p0: float, p1: float, p2: float, p3: float) -> None: ...
    @overload
    def loadScale(self, p0: float, p1: float, p2: float) -> None: ...
    @overload
    def loadScale(self, p0: float, p1: float) -> None: ...
    def loadIdentity(self) -> None: ...
    def loadTranslate(self, p0: float, p1: float) -> None: ...
    def transpose(self) -> None: ...
    def load(self, p0: "Matrix3f") -> None: ...
    @overload
    def scale(self, p0: float, p1: float) -> None: ...
    @overload
    def scale(self, p0: float, p1: float, p2: float) -> None: ...
    def get(self, p0: int, p1: int) -> float: ...
    def set(self, p0: int, p1: int, p2: float) -> None: ...
    def translate(self, p0: float, p1: float) -> None: ...
    def getArray(self) -> Any: ...
    def multiply(self, p0: "Matrix3f") -> None: ...
    @overload
    def rotate(self, p0: float) -> None: ...
    @overload
    def rotate(self, p0: float, p1: float, p2: float, p3: float) -> None: ...
