from typing import Any, ClassVar, overload
from android.content.Context import Context

class RenderScript:
    CREATE_FLAG_LOW_LATENCY: ClassVar[int]
    CREATE_FLAG_LOW_POWER: ClassVar[int]
    CREATE_FLAG_NONE: ClassVar[int]
    @staticmethod
    def getMinorVersion() -> int: ...
    def getErrorHandler(self) -> Any: ...
    def setErrorHandler(self, p0: Any) -> None: ...
    def contextDump(self) -> None: ...
    @staticmethod
    def createMultiContext(p0: Context, p1: Any, p2: int, p3: int) -> "RenderScript": ...
    def getMessageHandler(self) -> Any: ...
    @staticmethod
    def releaseAllContexts() -> None: ...
    def setMessageHandler(self, p0: Any) -> None: ...
    def setPriority(self, p0: Any) -> None: ...
    def destroy(self) -> None: ...
    def finish(self) -> None: ...
    @overload
    @staticmethod
    def create(p0: Context, p1: Any) -> "RenderScript": ...
    @overload
    @staticmethod
    def create(p0: Context) -> "RenderScript": ...
    @overload
    @staticmethod
    def create(p0: Context, p1: Any, p2: int) -> "RenderScript": ...
    def sendMessage(self, p0: int, p1: Any) -> None: ...
    def getApplicationContext(self) -> Context: ...

    class RSMessageHandler:
        def __init__(self) -> None: ...
        def run(self) -> None: ...

    class RSErrorHandler:
        def __init__(self) -> None: ...
        def run(self) -> None: ...

    class Priority:
        LOW: ClassVar["Priority"]
        NORMAL: ClassVar["Priority"]
        LOW: ClassVar[Any]
        NORMAL: ClassVar[Any]
        @staticmethod
        def values() -> Any: ...
        @staticmethod
        def valueOf(p0: str) -> Any: ...

    class ContextType:
        DEBUG: ClassVar["ContextType"]
        NORMAL: ClassVar["ContextType"]
        PROFILE: ClassVar["ContextType"]
        DEBUG: ClassVar[Any]
        NORMAL: ClassVar[Any]
        PROFILE: ClassVar[Any]
        @staticmethod
        def values() -> Any: ...
        @staticmethod
        def valueOf(p0: str) -> Any: ...
