from typing import Any, ClassVar, overload
from android.os.Parcel import Parcel

class GnssCapabilities:
    CAPABILITY_SUPPORTED: ClassVar[int]
    CAPABILITY_UNKNOWN: ClassVar[int]
    CAPABILITY_UNSUPPORTED: ClassVar[int]
    CREATOR: ClassVar[Any]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    def hasMsb(self) -> bool: ...
    def hasMsa(self) -> bool: ...
    def hasMeasurements(self) -> bool: ...
    def hasNavigationMessages(self) -> bool: ...
    def hasLowPowerMode(self) -> bool: ...
    def hasSatelliteBlocklist(self) -> bool: ...
    def hasSatellitePvt(self) -> bool: ...
    def hasMeasurementCorrections(self) -> bool: ...
    def hasGnssAntennaInfo(self) -> bool: ...
    def hasAntennaInfo(self) -> bool: ...
    def hasMeasurementCorrelationVectors(self) -> bool: ...
    def hasMeasurementCorrectionsForDriving(self) -> bool: ...
    def hasAccumulatedDeltaRange(self) -> int: ...
    def hasMeasurementCorrectionsLosSats(self) -> bool: ...
    def hasMeasurementCorrectionsExcessPathLength(self) -> bool: ...
    def hasMeasurementCorrectionsReflectingPlane(self) -> bool: ...
    def hasPowerTotal(self) -> bool: ...
    def hasPowerSinglebandTracking(self) -> bool: ...
    def hasPowerMultibandTracking(self) -> bool: ...
    def hasPowerSinglebandAcquisition(self) -> bool: ...
    def hasPowerMultibandAcquisition(self) -> bool: ...
    def hasPowerOtherModes(self) -> bool: ...
    def getGnssSignalTypes(self) -> list: ...
    def hasScheduling(self) -> bool: ...
    def hasSingleShotFix(self) -> bool: ...
    def hasOnDemandTime(self) -> bool: ...
    def hasGeofencing(self) -> bool: ...
    def equals(self, p0: Any) -> bool: ...
    def toString(self) -> str: ...
    def hashCode(self) -> int: ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...

    class Builder:
        @overload
        def __init__(self) -> None: ...
        @overload
        def __init__(self, p0: "GnssCapabilities") -> None: ...
        def setHasScheduling(self, p0: bool) -> Any: ...
        def setHasSingleShotFix(self, p0: bool) -> Any: ...
        def setHasMeasurementCorrections(self, p0: bool) -> Any: ...
        def setHasMeasurementCorrelationVectors(self, p0: bool) -> Any: ...
        def setHasMeasurementCorrectionsForDriving(self, p0: bool) -> Any: ...
        def setHasAccumulatedDeltaRange(self, p0: int) -> Any: ...
        def setHasPowerTotal(self, p0: bool) -> Any: ...
        def setHasMeasurementCorrectionsLosSats(self, p0: bool) -> Any: ...
        def setHasMeasurementCorrectionsExcessPathLength(self, p0: bool) -> Any: ...
        def setHasMeasurementCorrectionsReflectingPlane(self, p0: bool) -> Any: ...
        def setHasPowerSinglebandTracking(self, p0: bool) -> Any: ...
        def setHasPowerMultibandTracking(self, p0: bool) -> Any: ...
        def setHasPowerSinglebandAcquisition(self, p0: bool) -> Any: ...
        def setHasPowerMultibandAcquisition(self, p0: bool) -> Any: ...
        def setHasPowerOtherModes(self, p0: bool) -> Any: ...
        def setGnssSignalTypes(self, p0: list) -> Any: ...
        def setHasMsa(self, p0: bool) -> Any: ...
        def setHasNavigationMessages(self, p0: bool) -> Any: ...
        def setHasMsb(self, p0: bool) -> Any: ...
        def setHasOnDemandTime(self, p0: bool) -> Any: ...
        def setHasGeofencing(self, p0: bool) -> Any: ...
        def setHasMeasurements(self, p0: bool) -> Any: ...
        def setHasLowPowerMode(self, p0: bool) -> Any: ...
        def setHasSatelliteBlocklist(self, p0: bool) -> Any: ...
        def setHasSatellitePvt(self, p0: bool) -> Any: ...
        def setHasAntennaInfo(self, p0: bool) -> Any: ...
        def build(self) -> "GnssCapabilities": ...
