from typing import Any, ClassVar, overload
from android.os.Parcel import Parcel

class GnssMeasurement:
    ADR_STATE_CYCLE_SLIP: ClassVar[int]
    ADR_STATE_HALF_CYCLE_REPORTED: ClassVar[int]
    ADR_STATE_HALF_CYCLE_RESOLVED: ClassVar[int]
    ADR_STATE_RESET: ClassVar[int]
    ADR_STATE_UNKNOWN: ClassVar[int]
    ADR_STATE_VALID: ClassVar[int]
    CREATOR: ClassVar[Any]
    MULTIPATH_INDICATOR_DETECTED: ClassVar[int]
    MULTIPATH_INDICATOR_NOT_DETECTED: ClassVar[int]
    MULTIPATH_INDICATOR_UNKNOWN: ClassVar[int]
    STATE_2ND_CODE_LOCK: ClassVar[int]
    STATE_BDS_D2_BIT_SYNC: ClassVar[int]
    STATE_BDS_D2_SUBFRAME_SYNC: ClassVar[int]
    STATE_BIT_SYNC: ClassVar[int]
    STATE_CODE_LOCK: ClassVar[int]
    STATE_GAL_E1BC_CODE_LOCK: ClassVar[int]
    STATE_GAL_E1B_PAGE_SYNC: ClassVar[int]
    STATE_GAL_E1C_2ND_CODE_LOCK: ClassVar[int]
    STATE_GLO_STRING_SYNC: ClassVar[int]
    STATE_GLO_TOD_DECODED: ClassVar[int]
    STATE_GLO_TOD_KNOWN: ClassVar[int]
    STATE_MSEC_AMBIGUOUS: ClassVar[int]
    STATE_SBAS_SYNC: ClassVar[int]
    STATE_SUBFRAME_SYNC: ClassVar[int]
    STATE_SYMBOL_SYNC: ClassVar[int]
    STATE_TOW_DECODED: ClassVar[int]
    STATE_TOW_KNOWN: ClassVar[int]
    STATE_UNKNOWN: ClassVar[int]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    def getCodeType(self) -> str: ...
    def getConstellationType(self) -> int: ...
    def getCarrierFrequencyHz(self) -> float: ...
    def getAccumulatedDeltaRangeMeters(self) -> float: ...
    def getAccumulatedDeltaRangeState(self) -> int: ...
    def getAccumulatedDeltaRangeUncertaintyMeters(self) -> float: ...
    def getAutomaticGainControlLevelDb(self) -> float: ...
    def getCarrierCycles(self) -> int: ...
    def getCarrierPhase(self) -> float: ...
    def getCarrierPhaseUncertainty(self) -> float: ...
    def getFullInterSignalBiasNanos(self) -> float: ...
    def getFullInterSignalBiasUncertaintyNanos(self) -> float: ...
    def getMultipathIndicator(self) -> int: ...
    def getPseudorangeRateMetersPerSecond(self) -> float: ...
    def getPseudorangeRateUncertaintyMetersPerSecond(self) -> float: ...
    def getReceivedSvTimeNanos(self) -> int: ...
    def getReceivedSvTimeUncertaintyNanos(self) -> int: ...
    def getSatelliteInterSignalBiasNanos(self) -> float: ...
    def getSatelliteInterSignalBiasUncertaintyNanos(self) -> float: ...
    def getSnrInDb(self) -> float: ...
    def getTimeOffsetNanos(self) -> float: ...
    def hasAutomaticGainControlLevelDb(self) -> bool: ...
    def hasCarrierCycles(self) -> bool: ...
    def hasCarrierPhase(self) -> bool: ...
    def hasCarrierPhaseUncertainty(self) -> bool: ...
    def hasCodeType(self) -> bool: ...
    def hasFullInterSignalBiasNanos(self) -> bool: ...
    def hasFullInterSignalBiasUncertaintyNanos(self) -> bool: ...
    def hasSatelliteInterSignalBiasNanos(self) -> bool: ...
    def hasSatelliteInterSignalBiasUncertaintyNanos(self) -> bool: ...
    def hasSnrInDb(self) -> bool: ...
    def getBasebandCn0DbHz(self) -> float: ...
    def getCn0DbHz(self) -> float: ...
    def getSvid(self) -> int: ...
    def hasBasebandCn0DbHz(self) -> bool: ...
    def hasCarrierFrequencyHz(self) -> bool: ...
    def toString(self) -> str: ...
    def getState(self) -> int: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
    def describeContents(self) -> int: ...
