from typing import Any, ClassVar, overload
from android.os.Parcel import Parcel

class GnssAutomaticGainControl:
    CREATOR: ClassVar[Any]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    def getLevelDb(self) -> float: ...
    def getConstellationType(self) -> int: ...
    def getCarrierFrequencyHz(self) -> int: ...
    def equals(self, p0: Any) -> bool: ...
    def toString(self) -> str: ...
    def hashCode(self) -> int: ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...

    class Builder:
        @overload
        def __init__(self) -> None: ...
        @overload
        def __init__(self, p0: "GnssAutomaticGainControl") -> None: ...
        def setLevelDb(self, p0: float) -> Any: ...
        def setCarrierFrequencyHz(self, p0: int) -> Any: ...
        def setConstellationType(self, p0: int) -> Any: ...
        def build(self) -> "GnssAutomaticGainControl": ...
