from typing import Any, ClassVar, overload
from android.os.Parcel import Parcel

class GnssAntennaInfo:
    CREATOR: ClassVar[Any]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    def getSignalGainCorrections(self) -> Any: ...
    def getCarrierFrequencyMHz(self) -> float: ...
    def getPhaseCenterOffset(self) -> Any: ...
    def getPhaseCenterVariationCorrections(self) -> Any: ...
    def equals(self, p0: Any) -> bool: ...
    def toString(self) -> str: ...
    def hashCode(self) -> int: ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...

    class SphericalCorrections:
        CREATOR: ClassVar[Any]
        CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
        PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
        def __init__(self, p0: Any, p1: Any) -> None: ...
        def getCorrectionsArray(self) -> Any: ...
        def getCorrectionUncertaintiesArray(self) -> Any: ...
        def getDeltaTheta(self) -> float: ...
        def getDeltaPhi(self) -> float: ...
        def equals(self, p0: Any) -> bool: ...
        def toString(self) -> str: ...
        def hashCode(self) -> int: ...
        def describeContents(self) -> int: ...
        def writeToParcel(self, p0: Parcel, p1: int) -> None: ...

    class PhaseCenterOffset:
        CREATOR: ClassVar[Any]
        CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
        PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
        def __init__(self, p0: float, p1: float, p2: float, p3: float, p4: float, p5: float) -> None: ...
        def getXOffsetUncertaintyMm(self) -> float: ...
        def getXOffsetMm(self) -> float: ...
        def getYOffsetMm(self) -> float: ...
        def getYOffsetUncertaintyMm(self) -> float: ...
        def getZOffsetMm(self) -> float: ...
        def getZOffsetUncertaintyMm(self) -> float: ...
        def equals(self, p0: Any) -> bool: ...
        def toString(self) -> str: ...
        def hashCode(self) -> int: ...
        def describeContents(self) -> int: ...
        def writeToParcel(self, p0: Parcel, p1: int) -> None: ...

    class Listener:
        def onGnssAntennaInfoReceived(self, p0: list) -> None: ...

    class Builder:
        @overload
        def __init__(self) -> None: ...
        @overload
        def __init__(self, p0: "GnssAntennaInfo") -> None: ...
        @overload
        def __init__(self, p0: float, p1: Any) -> None: ...
        def setSignalGainCorrections(self, p0: Any) -> Any: ...
        def setCarrierFrequencyMHz(self, p0: float) -> Any: ...
        def setPhaseCenterOffset(self, p0: Any) -> Any: ...
        def setPhaseCenterVariationCorrections(self, p0: Any) -> Any: ...
        def build(self) -> "GnssAntennaInfo": ...
