from typing import Any, ClassVar, overload
from android.os.Bundle import Bundle
from android.os.Parcel import Parcel
from android.util.Printer import Printer

class Location:
    CREATOR: ClassVar[Any]
    FORMAT_DEGREES: ClassVar[int]
    FORMAT_MINUTES: ClassVar[int]
    FORMAT_SECONDS: ClassVar[int]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    @overload
    def __init__(self, p0: "Location") -> None: ...
    @overload
    def __init__(self, p0: str) -> None: ...
    def setLongitude(self, p0: float) -> None: ...
    def setMock(self, p0: bool) -> None: ...
    def setLatitude(self, p0: float) -> None: ...
    def setBearingAccuracyDegrees(self, p0: float) -> None: ...
    def setElapsedRealtimeNanos(self, p0: int) -> None: ...
    def setElapsedRealtimeUncertaintyNanos(self, p0: float) -> None: ...
    def setMslAltitudeAccuracyMeters(self, p0: float) -> None: ...
    def setMslAltitudeMeters(self, p0: float) -> None: ...
    def setProvider(self, p0: str) -> None: ...
    def setSpeed(self, p0: float) -> None: ...
    def setSpeedAccuracyMetersPerSecond(self, p0: float) -> None: ...
    def setVerticalAccuracyMeters(self, p0: float) -> None: ...
    def getProvider(self) -> str: ...
    def reset(self) -> None: ...
    def equals(self, p0: Any) -> bool: ...
    def toString(self) -> str: ...
    def hashCode(self) -> int: ...
    @overload
    @staticmethod
    def convert(p0: str) -> float: ...
    @overload
    @staticmethod
    def convert(p0: float, p1: int) -> str: ...
    def set(self, p0: "Location") -> None: ...
    def dump(self, p0: Printer, p1: str) -> None: ...
    def hasSpeedAccuracy(self) -> bool: ...
    def removeAltitude(self) -> None: ...
    def hasSpeed(self) -> bool: ...
    def hasAccuracy(self) -> bool: ...
    def removeBearing(self) -> None: ...
    def removeAccuracy(self) -> None: ...
    def isMock(self) -> bool: ...
    def isComplete(self) -> bool: ...
    def isFromMockProvider(self) -> bool: ...
    def hasBearingAccuracy(self) -> bool: ...
    def hasBearing(self) -> bool: ...
    def hasMslAltitude(self) -> bool: ...
    def getElapsedRealtimeUncertaintyNanos(self) -> float: ...
    def hasAltitude(self) -> bool: ...
    def getMslAltitudeAccuracyMeters(self) -> float: ...
    def getMslAltitudeMeters(self) -> float: ...
    def getSpeedAccuracyMetersPerSecond(self) -> float: ...
    def getVerticalAccuracyMeters(self) -> float: ...
    def hasElapsedRealtimeUncertaintyNanos(self) -> bool: ...
    def hasMslAltitudeAccuracy(self) -> bool: ...
    def hasVerticalAccuracy(self) -> bool: ...
    def removeBearingAccuracy(self) -> None: ...
    def removeMslAltitude(self) -> None: ...
    def removeElapsedRealtimeUncertaintyNanos(self) -> None: ...
    def removeMslAltitudeAccuracy(self) -> None: ...
    def removeSpeed(self) -> None: ...
    def removeSpeedAccuracy(self) -> None: ...
    def removeVerticalAccuracy(self) -> None: ...
    def setAccuracy(self, p0: float) -> None: ...
    def setBearing(self, p0: float) -> None: ...
    def setExtras(self, p0: Bundle) -> None: ...
    def getExtras(self) -> Bundle: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
    def describeContents(self) -> int: ...
    def setAltitude(self, p0: float) -> None: ...
    def getSpeed(self) -> float: ...
    def getLatitude(self) -> float: ...
    def getLongitude(self) -> float: ...
    def getAltitude(self) -> float: ...
    def bearingTo(self, p0: "Location") -> float: ...
    @staticmethod
    def distanceBetween(p0: float, p1: float, p2: float, p3: float, p4: Any) -> None: ...
    def distanceTo(self, p0: "Location") -> float: ...
    def getAccuracy(self) -> float: ...
    def getBearing(self) -> float: ...
    def getBearingAccuracyDegrees(self) -> float: ...
    @overload
    def getElapsedRealtimeAgeMillis(self, p0: int) -> int: ...
    @overload
    def getElapsedRealtimeAgeMillis(self) -> int: ...
    def getElapsedRealtimeMillis(self) -> int: ...
    def getElapsedRealtimeNanos(self) -> int: ...
    def getTime(self) -> int: ...
    def setTime(self, p0: int) -> None: ...
