from typing import Any, ClassVar, overload
from android.os.Parcel import Parcel

class LocationRequest:
    CREATOR: ClassVar[Any]
    PASSIVE_INTERVAL: ClassVar[int]
    QUALITY_BALANCED_POWER_ACCURACY: ClassVar[int]
    QUALITY_HIGH_ACCURACY: ClassVar[int]
    QUALITY_LOW_POWER: ClassVar[int]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    def getDurationMillis(self) -> int: ...
    def getIntervalMillis(self) -> int: ...
    def getMaxUpdateDelayMillis(self) -> int: ...
    def getMaxUpdates(self) -> int: ...
    def getMinUpdateDistanceMeters(self) -> float: ...
    def getMinUpdateIntervalMillis(self) -> int: ...
    def equals(self, p0: Any) -> bool: ...
    def toString(self) -> str: ...
    def hashCode(self) -> int: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
    def describeContents(self) -> int: ...
    def getQuality(self) -> int: ...

    class Builder:
        @overload
        def __init__(self, p0: int) -> None: ...
        @overload
        def __init__(self, p0: "LocationRequest") -> None: ...
        def setQuality(self, p0: int) -> Any: ...
        def setDurationMillis(self, p0: int) -> Any: ...
        def setMaxUpdates(self, p0: int) -> Any: ...
        def clearMinUpdateIntervalMillis(self) -> Any: ...
        def setMaxUpdateDelayMillis(self, p0: int) -> Any: ...
        def setMinUpdateDistanceMeters(self, p0: float) -> Any: ...
        def setMinUpdateIntervalMillis(self, p0: int) -> Any: ...
        def build(self) -> "LocationRequest": ...
        def setIntervalMillis(self, p0: int) -> Any: ...
