from typing import Any, ClassVar, overload

class BackupDataOutput:
    def getQuota(self) -> int: ...
    def getTransportFlags(self) -> int: ...
    def writeEntityData(self, p0: Any, p1: int) -> int: ...
    def writeEntityHeader(self, p0: str, p1: int) -> int: ...
