from typing import Any, ClassVar, overload
from android.adservices.common.AppInstallFilters import AppInstallFilters
from android.adservices.common.FrequencyCapFilters import FrequencyCapFilters
from android.os.Parcel import Parcel

class AdFilters:
    CREATOR: ClassVar[Any]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    def getAppInstallFilters(self) -> AppInstallFilters: ...
    def getFrequencyCapFilters(self) -> FrequencyCapFilters: ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
    def equals(self, p0: Any) -> bool: ...
    def toString(self) -> str: ...
    def hashCode(self) -> int: ...

    class Builder:
        def __init__(self) -> None: ...
        def setFrequencyCapFilters(self, p0: FrequencyCapFilters) -> Any: ...
        def setAppInstallFilters(self, p0: AppInstallFilters) -> Any: ...
        def build(self) -> "AdFilters": ...
