from typing import Any, ClassVar, overload
from android.companion.AssociatedDevice import AssociatedDevice
from android.companion.DeviceId import DeviceId
from android.net.MacAddress import MacAddress
from android.os.Parcel import Parcel

class AssociationInfo:
    CREATOR: ClassVar[Any]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    def isSelfManaged(self) -> bool: ...
    def getDeviceProfile(self) -> str: ...
    def getAssociatedDevice(self) -> AssociatedDevice: ...
    def getDeviceMacAddress(self) -> MacAddress: ...
    def getSystemDataSyncFlags(self) -> int: ...
    def equals(self, p0: Any) -> bool: ...
    def toString(self) -> str: ...
    def hashCode(self) -> int: ...
    def getId(self) -> int: ...
    def getDeviceId(self) -> DeviceId: ...
    def getDisplayName(self) -> str: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
    def describeContents(self) -> int: ...
