from typing import Any, ClassVar, overload
from android.os.Parcel import Parcel
from android.os.ParcelUuid import ParcelUuid
from java.util.regex.Pattern import Pattern

class BluetoothDeviceFilter:
    CREATOR: ClassVar[Any]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    def equals(self, p0: Any) -> bool: ...
    def toString(self) -> str: ...
    def hashCode(self) -> int: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
    def describeContents(self) -> int: ...

    class Builder:
        def __init__(self) -> None: ...
        def setNamePattern(self, p0: Pattern) -> Any: ...
        def setAddress(self, p0: str) -> Any: ...
        def addServiceUuid(self, p0: ParcelUuid, p1: ParcelUuid) -> Any: ...
        def build(self) -> "BluetoothDeviceFilter": ...
