from typing import Any, ClassVar, overload
from android.os.Parcel import Parcel
from android.print.PrintAttributes import PrintAttributes
from android.print.PrinterId import PrinterId

class PrinterCapabilitiesInfo:
    CREATOR: ClassVar[Any]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    def getMinMargins(self) -> Any: ...
    def getMediaSizes(self) -> list: ...
    def getDuplexModes(self) -> int: ...
    def getDefaults(self) -> PrintAttributes: ...
    def getResolutions(self) -> list: ...
    def getColorModes(self) -> int: ...
    def equals(self, p0: Any) -> bool: ...
    def toString(self) -> str: ...
    def hashCode(self) -> int: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
    def describeContents(self) -> int: ...

    class Builder:
        def __init__(self, p0: PrinterId) -> None: ...
        def addResolution(self, p0: Any, p1: bool) -> Any: ...
        def setColorModes(self, p0: int, p1: int) -> Any: ...
        def setDuplexModes(self, p0: int, p1: int) -> Any: ...
        def addMediaSize(self, p0: Any, p1: bool) -> Any: ...
        def setMinMargins(self, p0: Any) -> Any: ...
        def build(self) -> "PrinterCapabilitiesInfo": ...
