# cython: language_level=3
# Generated by pyjnius-wrap cython — do not edit by hand.

from jni_core._core cimport (
    JavaObject, get_env, check_jni_exc,
    find_class_global, get_method_id, get_static_method_id,
    get_field_id, get_static_field_id, j_str, py_str,
)
from jni_core._dispatch cimport (
    jnicore_NewObjectA, jnicore_DeleteLocalRef,
    jnicore_CallVoidMethodA, jnicore_CallObjectMethodA,
    jnicore_CallBooleanMethodA, jnicore_CallByteMethodA,
    jnicore_CallCharMethodA, jnicore_CallShortMethodA,
    jnicore_CallIntMethodA, jnicore_CallLongMethodA,
    jnicore_CallFloatMethodA, jnicore_CallDoubleMethodA,
    jnicore_CallStaticVoidMethodA, jnicore_CallStaticObjectMethodA,
    jnicore_CallStaticBooleanMethodA, jnicore_CallStaticByteMethodA,
    jnicore_CallStaticCharMethodA, jnicore_CallStaticShortMethodA,
    jnicore_CallStaticIntMethodA, jnicore_CallStaticLongMethodA,
    jnicore_CallStaticFloatMethodA, jnicore_CallStaticDoubleMethodA,
    jnicore_GetObjectField, jnicore_SetObjectField,
    jnicore_GetBooleanField, jnicore_SetBooleanField,
    jnicore_GetByteField, jnicore_SetByteField,
    jnicore_GetCharField, jnicore_SetCharField,
    jnicore_GetShortField, jnicore_SetShortField,
    jnicore_GetIntField, jnicore_SetIntField,
    jnicore_GetLongField, jnicore_SetLongField,
    jnicore_GetFloatField, jnicore_SetFloatField,
    jnicore_GetDoubleField, jnicore_SetDoubleField,
    jnicore_GetStaticObjectField, jnicore_SetStaticObjectField,
    jnicore_GetStaticBooleanField, jnicore_SetStaticBooleanField,
    jnicore_GetStaticByteField, jnicore_SetStaticByteField,
    jnicore_GetStaticCharField, jnicore_SetStaticCharField,
    jnicore_GetStaticShortField, jnicore_SetStaticShortField,
    jnicore_GetStaticIntField, jnicore_SetStaticIntField,
    jnicore_GetStaticLongField, jnicore_SetStaticLongField,
    jnicore_GetStaticFloatField, jnicore_SetStaticFloatField,
    jnicore_GetStaticDoubleField, jnicore_SetStaticDoubleField,
)
from jni_core.jni cimport (
    jclass, jobject, jmethodID, jfieldID, jvalue, JNIEnv,
    jboolean, jbyte, jchar, jshort, jint, jlong, jfloat, jdouble, jstring,
)

include "jni_core/conversions.pxi"

__javaclass__ = "javax/net/ssl/SSLContext"  # javax.net.ssl.SSLContext

cdef jclass _cls_SSLContext = NULL
cdef jmethodID _m_SSLContext_getSocketFactory_0 = NULL
cdef jmethodID _m_SSLContext_getDefault_0 = NULL
cdef jmethodID _m_SSLContext_getInstance_0 = NULL
cdef jmethodID _m_SSLContext_getInstance_1 = NULL
cdef jmethodID _m_SSLContext_getInstance_2 = NULL
cdef jmethodID _m_SSLContext_init_0 = NULL
cdef jmethodID _m_SSLContext_getProtocol_0 = NULL
cdef jmethodID _m_SSLContext_setDefault_0 = NULL
cdef jmethodID _m_SSLContext_getProvider_0 = NULL
cdef jmethodID _m_SSLContext_createSSLEngine_0 = NULL
cdef jmethodID _m_SSLContext_createSSLEngine_1 = NULL
cdef jmethodID _m_SSLContext_getServerSessionContext_0 = NULL
cdef jmethodID _m_SSLContext_getClientSessionContext_0 = NULL
cdef jmethodID _m_SSLContext_getDefaultSSLParameters_0 = NULL
cdef jmethodID _m_SSLContext_getSupportedSSLParameters_0 = NULL
cdef jmethodID _m_SSLContext_getServerSocketFactory_0 = NULL

cdef int _ensure_ids_SSLContext(JNIEnv* env) except -1:
    global _cls_SSLContext, _m_SSLContext_getSocketFactory_0, _m_SSLContext_getDefault_0, _m_SSLContext_getInstance_0, _m_SSLContext_getInstance_1, _m_SSLContext_getInstance_2, _m_SSLContext_init_0, _m_SSLContext_getProtocol_0, _m_SSLContext_setDefault_0, _m_SSLContext_getProvider_0, _m_SSLContext_createSSLEngine_0, _m_SSLContext_createSSLEngine_1, _m_SSLContext_getServerSessionContext_0, _m_SSLContext_getClientSessionContext_0, _m_SSLContext_getDefaultSSLParameters_0, _m_SSLContext_getSupportedSSLParameters_0, _m_SSLContext_getServerSocketFactory_0
    if _cls_SSLContext != NULL:
        return 0
    _cls_SSLContext = find_class_global(env, b"javax/net/ssl/SSLContext")
    _m_SSLContext_getSocketFactory_0 = get_method_id(env, _cls_SSLContext, b"getSocketFactory", b"()Ljavax/net/ssl/SSLSocketFactory;")
    _m_SSLContext_getDefault_0 = get_static_method_id(env, _cls_SSLContext, b"getDefault", b"()Ljavax/net/ssl/SSLContext;")
    _m_SSLContext_getInstance_0 = get_static_method_id(env, _cls_SSLContext, b"getInstance", b"(Ljava/lang/String;)Ljavax/net/ssl/SSLContext;")
    _m_SSLContext_getInstance_1 = get_static_method_id(env, _cls_SSLContext, b"getInstance", b"(Ljava/lang/String;Ljava/security/Provider;)Ljavax/net/ssl/SSLContext;")
    _m_SSLContext_getInstance_2 = get_static_method_id(env, _cls_SSLContext, b"getInstance", b"(Ljava/lang/String;Ljava/lang/String;)Ljavax/net/ssl/SSLContext;")
    _m_SSLContext_init_0 = get_method_id(env, _cls_SSLContext, b"init", b"([Ljavax/net/ssl/KeyManager;[Ljavax/net/ssl/TrustManager;Ljava/security/SecureRandom;)V")
    _m_SSLContext_getProtocol_0 = get_method_id(env, _cls_SSLContext, b"getProtocol", b"()Ljava/lang/String;")
    _m_SSLContext_setDefault_0 = get_static_method_id(env, _cls_SSLContext, b"setDefault", b"(Ljavax/net/ssl/SSLContext;)V")
    _m_SSLContext_getProvider_0 = get_method_id(env, _cls_SSLContext, b"getProvider", b"()Ljava/security/Provider;")
    _m_SSLContext_createSSLEngine_0 = get_method_id(env, _cls_SSLContext, b"createSSLEngine", b"(Ljava/lang/String;I)Ljavax/net/ssl/SSLEngine;")
    _m_SSLContext_createSSLEngine_1 = get_method_id(env, _cls_SSLContext, b"createSSLEngine", b"()Ljavax/net/ssl/SSLEngine;")
    _m_SSLContext_getServerSessionContext_0 = get_method_id(env, _cls_SSLContext, b"getServerSessionContext", b"()Ljavax/net/ssl/SSLSessionContext;")
    _m_SSLContext_getClientSessionContext_0 = get_method_id(env, _cls_SSLContext, b"getClientSessionContext", b"()Ljavax/net/ssl/SSLSessionContext;")
    _m_SSLContext_getDefaultSSLParameters_0 = get_method_id(env, _cls_SSLContext, b"getDefaultSSLParameters", b"()Ljavax/net/ssl/SSLParameters;")
    _m_SSLContext_getSupportedSSLParameters_0 = get_method_id(env, _cls_SSLContext, b"getSupportedSSLParameters", b"()Ljavax/net/ssl/SSLParameters;")
    _m_SSLContext_getServerSocketFactory_0 = get_method_id(env, _cls_SSLContext, b"getServerSocketFactory", b"()Ljavax/net/ssl/SSLServerSocketFactory;")
    return 0

cdef class SSLContext(JavaObject):
    """javax.net.ssl.SSLContext"""

    def __init__(self, *args, **kwargs):
        raise TypeError("SSLContext has no public constructor")

    cdef jobject _getSocketFactory(self) except? NULL:
        cdef JNIEnv* env = get_env()
        _ensure_ids_SSLContext(env)
        cdef jvalue _args[1]  # zero-arg call; _args ignored by JNI
        cdef jobject _ret = jnicore_CallObjectMethodA(env, self._handle, _m_SSLContext_getSocketFactory_0, _args)
        check_jni_exc(env)
        return _ret

    def getSocketFactory(self) -> object:
        cdef JNIEnv* env = get_env()
        cdef jobject _ret = NULL
        _ret = self._getSocketFactory()
        if _ret == NULL:
            return None
        cdef JavaObject _wrapped = JavaObject.__new__(JavaObject)
        _wrapped._adopt_local(env, _ret)
        return _wrapped

    @staticmethod
    cdef jobject _getDefault() except? NULL:
        cdef JNIEnv* env = get_env()
        _ensure_ids_SSLContext(env)
        cdef jvalue _args[1]  # zero-arg call; _args ignored by JNI
        cdef jobject _ret = jnicore_CallStaticObjectMethodA(env, _cls_SSLContext, _m_SSLContext_getDefault_0, _args)
        check_jni_exc(env)
        return _ret

    @staticmethod
    def getDefault() -> object:
        cdef JNIEnv* env = get_env()
        cdef jobject _ret = NULL
        _ret = SSLContext._getDefault()
        if _ret == NULL:
            return None
        cdef JavaObject _wrapped = JavaObject.__new__(JavaObject)
        _wrapped._adopt_local(env, _ret)
        return _wrapped

    # TODO: 3 overloads of getInstance; only the first is wired.
    #   overload[0] = (Ljava/lang/String;)Ljavax/net/ssl/SSLContext;
    #   overload[1] = (Ljava/lang/String;Ljava/security/Provider;)Ljavax/net/ssl/SSLContext;
    #   overload[2] = (Ljava/lang/String;Ljava/lang/String;)Ljavax/net/ssl/SSLContext;
    @staticmethod
    cdef jobject _getInstance(jstring p0) except? NULL:
        cdef JNIEnv* env = get_env()
        _ensure_ids_SSLContext(env)
        cdef jvalue _args[1]
        _args[0].l = <jobject>p0
        cdef jobject _ret = jnicore_CallStaticObjectMethodA(env, _cls_SSLContext, _m_SSLContext_getInstance_0, _args)
        check_jni_exc(env)
        return _ret

    @staticmethod
    def getInstance(p0) -> object:
        cdef JNIEnv* env = get_env()
        cdef jobject _ret = NULL
        cdef jstring _arg0_s = NULL
        _arg0_s = j_str(env, p0) if p0 is not None else <jstring>NULL
        try:
            _ret = SSLContext._getInstance(_arg0_s)
        finally:
            if _arg0_s != NULL:
                jnicore_DeleteLocalRef(env, <jobject>_arg0_s)
        if _ret == NULL:
            return None
        cdef JavaObject _wrapped = JavaObject.__new__(JavaObject)
        _wrapped._adopt_local(env, _ret)
        return _wrapped

    cdef void _init(self, jobject p0, jobject p1, jobject p2) except *:
        cdef JNIEnv* env = get_env()
        _ensure_ids_SSLContext(env)
        cdef jvalue _args[3]
        _args[0].l = p0
        _args[1].l = p1
        _args[2].l = p2
        jnicore_CallVoidMethodA(env, self._handle, _m_SSLContext_init_0, _args)
        check_jni_exc(env)

    def init(self, p0, p1, p2) -> None:
        cdef JNIEnv* env = get_env()
        cdef jobject _h0 = (<JavaObject?>p0)._handle if p0 is not None else <jobject>NULL
        cdef jobject _h1 = (<JavaObject?>p1)._handle if p1 is not None else <jobject>NULL
        cdef jobject _h2 = (<JavaObject?>p2)._handle if p2 is not None else <jobject>NULL
        self._init(_h0, _h1, _h2)

    cdef jstring _getProtocol(self) except? NULL:
        cdef JNIEnv* env = get_env()
        _ensure_ids_SSLContext(env)
        cdef jvalue _args[1]  # zero-arg call; _args ignored by JNI
        cdef jstring _ret = <jstring>jnicore_CallObjectMethodA(env, self._handle, _m_SSLContext_getProtocol_0, _args)
        check_jni_exc(env)
        return <jstring>_ret

    def getProtocol(self) -> str:
        cdef JNIEnv* env = get_env()
        cdef jstring _ret = NULL
        _ret = self._getProtocol()
        return py_str(env, _ret)

    @staticmethod
    cdef void _setDefault(jobject p0) except *:
        cdef JNIEnv* env = get_env()
        _ensure_ids_SSLContext(env)
        cdef jvalue _args[1]
        _args[0].l = p0
        jnicore_CallStaticVoidMethodA(env, _cls_SSLContext, _m_SSLContext_setDefault_0, _args)
        check_jni_exc(env)

    @staticmethod
    def setDefault(p0) -> None:
        cdef JNIEnv* env = get_env()
        cdef jobject _h0 = (<JavaObject?>p0)._handle if p0 is not None else <jobject>NULL
        SSLContext._setDefault(_h0)

    cdef jobject _getProvider(self) except? NULL:
        cdef JNIEnv* env = get_env()
        _ensure_ids_SSLContext(env)
        cdef jvalue _args[1]  # zero-arg call; _args ignored by JNI
        cdef jobject _ret = jnicore_CallObjectMethodA(env, self._handle, _m_SSLContext_getProvider_0, _args)
        check_jni_exc(env)
        return _ret

    def getProvider(self) -> object:
        cdef JNIEnv* env = get_env()
        cdef jobject _ret = NULL
        _ret = self._getProvider()
        if _ret == NULL:
            return None
        cdef JavaObject _wrapped = JavaObject.__new__(JavaObject)
        _wrapped._adopt_local(env, _ret)
        return _wrapped

    # TODO: 2 overloads of createSSLEngine; only the first is wired.
    #   overload[0] = (Ljava/lang/String;I)Ljavax/net/ssl/SSLEngine;
    #   overload[1] = ()Ljavax/net/ssl/SSLEngine;
    cdef jobject _createSSLEngine(self, jstring p0, jint p1) except? NULL:
        cdef JNIEnv* env = get_env()
        _ensure_ids_SSLContext(env)
        cdef jvalue _args[2]
        _args[0].l = <jobject>p0
        _args[1].i = p1
        cdef jobject _ret = jnicore_CallObjectMethodA(env, self._handle, _m_SSLContext_createSSLEngine_0, _args)
        check_jni_exc(env)
        return _ret

    def createSSLEngine(self, p0, p1) -> object:
        cdef JNIEnv* env = get_env()
        cdef jobject _ret = NULL
        cdef jstring _arg0_s = NULL
        _arg0_s = j_str(env, p0) if p0 is not None else <jstring>NULL
        cdef jint _c1 = py_to_jint(p1)
        try:
            _ret = self._createSSLEngine(_arg0_s, _c1)
        finally:
            if _arg0_s != NULL:
                jnicore_DeleteLocalRef(env, <jobject>_arg0_s)
        if _ret == NULL:
            return None
        cdef JavaObject _wrapped = JavaObject.__new__(JavaObject)
        _wrapped._adopt_local(env, _ret)
        return _wrapped

    cdef jobject _getServerSessionContext(self) except? NULL:
        cdef JNIEnv* env = get_env()
        _ensure_ids_SSLContext(env)
        cdef jvalue _args[1]  # zero-arg call; _args ignored by JNI
        cdef jobject _ret = jnicore_CallObjectMethodA(env, self._handle, _m_SSLContext_getServerSessionContext_0, _args)
        check_jni_exc(env)
        return _ret

    def getServerSessionContext(self) -> object:
        cdef JNIEnv* env = get_env()
        cdef jobject _ret = NULL
        _ret = self._getServerSessionContext()
        if _ret == NULL:
            return None
        cdef JavaObject _wrapped = JavaObject.__new__(JavaObject)
        _wrapped._adopt_local(env, _ret)
        return _wrapped

    cdef jobject _getClientSessionContext(self) except? NULL:
        cdef JNIEnv* env = get_env()
        _ensure_ids_SSLContext(env)
        cdef jvalue _args[1]  # zero-arg call; _args ignored by JNI
        cdef jobject _ret = jnicore_CallObjectMethodA(env, self._handle, _m_SSLContext_getClientSessionContext_0, _args)
        check_jni_exc(env)
        return _ret

    def getClientSessionContext(self) -> object:
        cdef JNIEnv* env = get_env()
        cdef jobject _ret = NULL
        _ret = self._getClientSessionContext()
        if _ret == NULL:
            return None
        cdef JavaObject _wrapped = JavaObject.__new__(JavaObject)
        _wrapped._adopt_local(env, _ret)
        return _wrapped

    cdef jobject _getDefaultSSLParameters(self) except? NULL:
        cdef JNIEnv* env = get_env()
        _ensure_ids_SSLContext(env)
        cdef jvalue _args[1]  # zero-arg call; _args ignored by JNI
        cdef jobject _ret = jnicore_CallObjectMethodA(env, self._handle, _m_SSLContext_getDefaultSSLParameters_0, _args)
        check_jni_exc(env)
        return _ret

    def getDefaultSSLParameters(self) -> object:
        cdef JNIEnv* env = get_env()
        cdef jobject _ret = NULL
        _ret = self._getDefaultSSLParameters()
        if _ret == NULL:
            return None
        cdef JavaObject _wrapped = JavaObject.__new__(JavaObject)
        _wrapped._adopt_local(env, _ret)
        return _wrapped

    cdef jobject _getSupportedSSLParameters(self) except? NULL:
        cdef JNIEnv* env = get_env()
        _ensure_ids_SSLContext(env)
        cdef jvalue _args[1]  # zero-arg call; _args ignored by JNI
        cdef jobject _ret = jnicore_CallObjectMethodA(env, self._handle, _m_SSLContext_getSupportedSSLParameters_0, _args)
        check_jni_exc(env)
        return _ret

    def getSupportedSSLParameters(self) -> object:
        cdef JNIEnv* env = get_env()
        cdef jobject _ret = NULL
        _ret = self._getSupportedSSLParameters()
        if _ret == NULL:
            return None
        cdef JavaObject _wrapped = JavaObject.__new__(JavaObject)
        _wrapped._adopt_local(env, _ret)
        return _wrapped

    cdef jobject _getServerSocketFactory(self) except? NULL:
        cdef JNIEnv* env = get_env()
        _ensure_ids_SSLContext(env)
        cdef jvalue _args[1]  # zero-arg call; _args ignored by JNI
        cdef jobject _ret = jnicore_CallObjectMethodA(env, self._handle, _m_SSLContext_getServerSocketFactory_0, _args)
        check_jni_exc(env)
        return _ret

    def getServerSocketFactory(self) -> object:
        cdef JNIEnv* env = get_env()
        cdef jobject _ret = NULL
        _ret = self._getServerSocketFactory()
        if _ret == NULL:
            return None
        cdef JavaObject _wrapped = JavaObject.__new__(JavaObject)
        _wrapped._adopt_local(env, _ret)
        return _wrapped

