from typing import Any, ClassVar, overload
from java.io.InputStream import InputStream
from java.net.Socket import Socket
from javax.net.SocketFactory import SocketFactory

class SSLSocketFactory:
    def __init__(self) -> None: ...
    def getSupportedCipherSuites(self) -> Any: ...
    @overload
    def createSocket(self, p0: Socket, p1: str, p2: int, p3: bool) -> Socket: ...
    @overload
    def createSocket(self, p0: Socket, p1: InputStream, p2: bool) -> Socket: ...
    def getDefaultCipherSuites(self) -> Any: ...
    @staticmethod
    def getDefault() -> SocketFactory: ...
