from typing import Any, ClassVar, overload
from java.security.Principal import Principal
from javax.net.ssl.SSLSessionContext import SSLSessionContext

class SSLSession:
    def getCipherSuite(self) -> str: ...
    def getValue(self, p0: str) -> Any: ...
    def getId(self) -> Any: ...
    def getProtocol(self) -> str: ...
    def invalidate(self) -> None: ...
    def getSessionContext(self) -> SSLSessionContext: ...
    def getLastAccessedTime(self) -> int: ...
    def removeValue(self, p0: str) -> None: ...
    def getValueNames(self) -> Any: ...
    def getPeerCertificates(self) -> Any: ...
    def getLocalCertificates(self) -> Any: ...
    def getPeerCertificateChain(self) -> Any: ...
    def getPacketBufferSize(self) -> int: ...
    def getApplicationBufferSize(self) -> int: ...
    def getPeerPrincipal(self) -> Principal: ...
    def getLocalPrincipal(self) -> Principal: ...
    def isValid(self) -> bool: ...
    def putValue(self, p0: str, p1: Any) -> None: ...
    def getCreationTime(self) -> int: ...
    def getPeerHost(self) -> str: ...
    def getPeerPort(self) -> int: ...
