from typing import Any, ClassVar, overload
from java.net.Socket import Socket
from javax.net.ssl.SSLEngine import SSLEngine

class X509ExtendedTrustManager:
    def __init__(self) -> None: ...
    @overload
    def checkServerTrusted(self, p0: Any, p1: str, p2: SSLEngine) -> None: ...
    @overload
    def checkServerTrusted(self, p0: Any, p1: str, p2: Socket) -> None: ...
    @overload
    def checkClientTrusted(self, p0: Any, p1: str, p2: Socket) -> None: ...
    @overload
    def checkClientTrusted(self, p0: Any, p1: str, p2: SSLEngine) -> None: ...
