from typing import Any, ClassVar, overload
from java.math.BigInteger import BigInteger
from java.math.MathContext import MathContext
from java.math.RoundingMode import RoundingMode

class BigDecimal:
    ZERO: ClassVar["BigDecimal"]
    ONE: ClassVar["BigDecimal"]
    TWO: ClassVar["BigDecimal"]
    TEN: ClassVar["BigDecimal"]
    ROUND_UP: ClassVar[int]
    ROUND_DOWN: ClassVar[int]
    ROUND_CEILING: ClassVar[int]
    ROUND_FLOOR: ClassVar[int]
    ROUND_HALF_UP: ClassVar[int]
    ROUND_HALF_DOWN: ClassVar[int]
    ROUND_HALF_EVEN: ClassVar[int]
    ROUND_UNNECESSARY: ClassVar[int]
    @overload
    def __init__(self, p0: int) -> None: ...
    @overload
    def __init__(self, p0: BigInteger, p1: int, p2: MathContext) -> None: ...
    @overload
    def __init__(self, p0: BigInteger, p1: int) -> None: ...
    @overload
    def __init__(self, p0: BigInteger, p1: MathContext) -> None: ...
    @overload
    def __init__(self, p0: int, p1: MathContext) -> None: ...
    @overload
    def __init__(self, p0: int) -> None: ...
    @overload
    def __init__(self, p0: int, p1: MathContext) -> None: ...
    @overload
    def __init__(self, p0: str) -> None: ...
    @overload
    def __init__(self, p0: Any, p1: MathContext) -> None: ...
    @overload
    def __init__(self, p0: Any) -> None: ...
    @overload
    def __init__(self, p0: Any, p1: int, p2: int, p3: MathContext) -> None: ...
    @overload
    def __init__(self, p0: Any, p1: int, p2: int) -> None: ...
    @overload
    def __init__(self, p0: float, p1: MathContext) -> None: ...
    @overload
    def __init__(self, p0: BigInteger) -> None: ...
    @overload
    def __init__(self, p0: float) -> None: ...
    @overload
    def __init__(self, p0: str, p1: MathContext) -> None: ...
    @overload
    def subtract(self, p0: "BigDecimal") -> "BigDecimal": ...
    @overload
    def subtract(self, p0: "BigDecimal", p1: MathContext) -> "BigDecimal": ...
    def movePointLeft(self, p0: int) -> "BigDecimal": ...
    def unscaledValue(self) -> BigInteger: ...
    def equals(self, p0: Any) -> bool: ...
    def toString(self) -> str: ...
    def hashCode(self) -> int: ...
    @overload
    def abs(self, p0: MathContext) -> "BigDecimal": ...
    @overload
    def abs(self) -> "BigDecimal": ...
    def sqrt(self, p0: MathContext) -> "BigDecimal": ...
    @overload
    def pow(self, p0: int, p1: MathContext) -> "BigDecimal": ...
    @overload
    def pow(self, p0: int) -> "BigDecimal": ...
    def min(self, p0: "BigDecimal") -> "BigDecimal": ...
    def max(self, p0: "BigDecimal") -> "BigDecimal": ...
    def round(self, p0: MathContext) -> "BigDecimal": ...
    def signum(self) -> int: ...
    @overload
    def compareTo(self, p0: Any) -> int: ...
    @overload
    def compareTo(self, p0: "BigDecimal") -> int: ...
    def intValue(self) -> int: ...
    def longValue(self) -> int: ...
    def floatValue(self) -> float: ...
    def doubleValue(self) -> float: ...
    @overload
    @staticmethod
    def valueOf(p0: int, p1: int) -> "BigDecimal": ...
    @overload
    @staticmethod
    def valueOf(p0: int) -> "BigDecimal": ...
    @overload
    @staticmethod
    def valueOf(p0: float) -> "BigDecimal": ...
    def scale(self) -> int: ...
    @overload
    def add(self, p0: "BigDecimal") -> "BigDecimal": ...
    @overload
    def add(self, p0: "BigDecimal", p1: MathContext) -> "BigDecimal": ...
    @overload
    def setScale(self, p0: int, p1: int) -> "BigDecimal": ...
    @overload
    def setScale(self, p0: int, p1: RoundingMode) -> "BigDecimal": ...
    @overload
    def setScale(self, p0: int) -> "BigDecimal": ...
    @overload
    def multiply(self, p0: "BigDecimal") -> "BigDecimal": ...
    @overload
    def multiply(self, p0: "BigDecimal", p1: MathContext) -> "BigDecimal": ...
    def ulp(self) -> "BigDecimal": ...
    @overload
    def plus(self, p0: MathContext) -> "BigDecimal": ...
    @overload
    def plus(self) -> "BigDecimal": ...
    @overload
    def divide(self, p0: "BigDecimal") -> "BigDecimal": ...
    @overload
    def divide(self, p0: "BigDecimal", p1: RoundingMode) -> "BigDecimal": ...
    @overload
    def divide(self, p0: "BigDecimal", p1: int, p2: RoundingMode) -> "BigDecimal": ...
    @overload
    def divide(self, p0: "BigDecimal", p1: MathContext) -> "BigDecimal": ...
    @overload
    def divide(self, p0: "BigDecimal", p1: int, p2: int) -> "BigDecimal": ...
    @overload
    def divide(self, p0: "BigDecimal", p1: int) -> "BigDecimal": ...
    @overload
    def divideToIntegralValue(self, p0: "BigDecimal", p1: MathContext) -> "BigDecimal": ...
    @overload
    def divideToIntegralValue(self, p0: "BigDecimal") -> "BigDecimal": ...
    def longValueExact(self) -> int: ...
    def movePointRight(self, p0: int) -> "BigDecimal": ...
    def toBigIntegerExact(self) -> BigInteger: ...
    @overload
    def divideAndRemainder(self, p0: "BigDecimal") -> Any: ...
    @overload
    def divideAndRemainder(self, p0: "BigDecimal", p1: MathContext) -> Any: ...
    def precision(self) -> int: ...
    @overload
    def negate(self, p0: MathContext) -> "BigDecimal": ...
    @overload
    def negate(self) -> "BigDecimal": ...
    @overload
    def remainder(self, p0: "BigDecimal") -> "BigDecimal": ...
    @overload
    def remainder(self, p0: "BigDecimal", p1: MathContext) -> "BigDecimal": ...
    def toBigInteger(self) -> BigInteger: ...
    def intValueExact(self) -> int: ...
    def shortValueExact(self) -> int: ...
    def byteValueExact(self) -> int: ...
    def stripTrailingZeros(self) -> "BigDecimal": ...
    def scaleByPowerOfTen(self, p0: int) -> "BigDecimal": ...
    def toEngineeringString(self) -> str: ...
    def toPlainString(self) -> str: ...
