from typing import Any, ClassVar, overload

class FileSystemException:
    @overload
    def __init__(self, p0: str) -> None: ...
    @overload
    def __init__(self, p0: str, p1: str, p2: str) -> None: ...
    def getMessage(self) -> str: ...
    def getFile(self) -> str: ...
    def getOtherFile(self) -> str: ...
    def getReason(self) -> str: ...
