from typing import Any, ClassVar, overload
from android.net.Uri import Uri

class UpdateSignalsRequest:
    def getUpdateUri(self) -> Uri: ...
    def equals(self, p0: Any) -> bool: ...
    def toString(self) -> str: ...
    def hashCode(self) -> int: ...

    class Builder:
        def __init__(self, p0: Uri) -> None: ...
        def setUpdateUri(self, p0: Uri) -> Any: ...
        def build(self) -> "UpdateSignalsRequest": ...

from typing import Any, ClassVar, overload
from android.adservices.signals.UpdateSignalsRequest import UpdateSignalsRequest
from android.content.Context import Context
from android.os.OutcomeReceiver import OutcomeReceiver
from java.util.concurrent.Executor import Executor

class ProtectedSignalsManager:
    def updateSignals(self, p0: UpdateSignalsRequest, p1: Executor, p2: OutcomeReceiver) -> None: ...
    @staticmethod
    def get(p0: Context) -> "ProtectedSignalsManager": ...

