from typing import Any, ClassVar, overload
from android.content.Context import Context
from java.io.FileDescriptor import FileDescriptor
from java.io.PrintWriter import PrintWriter

class AsyncTaskLoader:
    def __init__(self, p0: Context) -> None: ...
    def onCanceled(self, p0: Any) -> None: ...
    def setUpdateThrottle(self, p0: int) -> None: ...
    def cancelLoadInBackground(self) -> None: ...
    def isLoadInBackgroundCanceled(self) -> bool: ...
    def loadInBackground(self) -> Any: ...
    def dump(self, p0: str, p1: FileDescriptor, p2: PrintWriter, p3: Any) -> None: ...
