from typing import Any, ClassVar, overload
from android.content.Context import Context
from android.content.Intent import Intent
from android.os.Bundle import Bundle
from android.os.IBinder import IBinder

class BroadcastReceiver:
    def __init__(self) -> None: ...
    def isInitialStickyBroadcast(self) -> bool: ...
    def onReceive(self, p0: Context, p1: Intent) -> None: ...
    def goAsync(self) -> Any: ...
    def peekService(self, p0: Context, p1: Intent) -> IBinder: ...
    def setResultCode(self, p0: int) -> None: ...
    def getResultCode(self) -> int: ...
    def setResultData(self, p0: str) -> None: ...
    def getResultData(self) -> str: ...
    def setResultExtras(self, p0: Bundle) -> None: ...
    def getResultExtras(self, p0: bool) -> Bundle: ...
    def getAbortBroadcast(self) -> bool: ...
    def abortBroadcast(self) -> None: ...
    def clearAbortBroadcast(self) -> None: ...
    def isOrderedBroadcast(self) -> bool: ...
    def setOrderedHint(self, p0: bool) -> None: ...
    def getSentFromUid(self) -> int: ...
    def getSentFromPackage(self) -> str: ...
    def setDebugUnregister(self, p0: bool) -> None: ...
    def getDebugUnregister(self) -> bool: ...
    def setResult(self, p0: int, p1: str, p2: Bundle) -> None: ...

    class PendingResult:
        def setResultCode(self, p0: int) -> None: ...
        def getResultCode(self) -> int: ...
        def setResultData(self, p0: str) -> None: ...
        def getResultData(self) -> str: ...
        def setResultExtras(self, p0: Bundle) -> None: ...
        def getResultExtras(self, p0: bool) -> Bundle: ...
        def getAbortBroadcast(self) -> bool: ...
        def abortBroadcast(self) -> None: ...
        def clearAbortBroadcast(self) -> None: ...
        def setResult(self, p0: int, p1: str, p2: Bundle) -> None: ...
        def finish(self) -> None: ...
