from typing import Any, ClassVar, overload
from android.content.AttributionSource import AttributionSource

class ContextParams:
    def getNextAttributionSource(self) -> AttributionSource: ...
    def shouldRegisterAttributionSource(self) -> bool: ...
    def getAttributionTag(self) -> str: ...

    class Builder:
        @overload
        def __init__(self, p0: "ContextParams") -> None: ...
        @overload
        def __init__(self) -> None: ...
        def setAttributionTag(self, p0: str) -> Any: ...
        def setNextAttributionSource(self, p0: AttributionSource) -> Any: ...
        def setShouldRegisterAttributionSource(self, p0: bool) -> Any: ...
        def build(self) -> "ContextParams": ...
