from typing import Any, ClassVar, overload
from android.content.Context import Context
from android.database.Cursor import Cursor
from android.net.Uri import Uri
from java.io.FileDescriptor import FileDescriptor
from java.io.PrintWriter import PrintWriter

class CursorLoader:
    @overload
    def __init__(self, p0: Context) -> None: ...
    @overload
    def __init__(self, p0: Context, p1: Uri, p2: Any, p3: str, p4: Any, p5: str) -> None: ...
    @overload
    def onCanceled(self, p0: Cursor) -> None: ...
    @overload
    def onCanceled(self, p0: Any) -> None: ...
    @overload
    def loadInBackground(self) -> Any: ...
    @overload
    def loadInBackground(self) -> Cursor: ...
    def cancelLoadInBackground(self) -> None: ...
    @overload
    def deliverResult(self, p0: Any) -> None: ...
    @overload
    def deliverResult(self, p0: Cursor) -> None: ...
    def setUri(self, p0: Uri) -> None: ...
    def getUri(self) -> Uri: ...
    def setSelection(self, p0: str) -> None: ...
    def getProjection(self) -> Any: ...
    def setProjection(self, p0: Any) -> None: ...
    def getSelection(self) -> str: ...
    def getSelectionArgs(self) -> Any: ...
    def setSelectionArgs(self, p0: Any) -> None: ...
    def getSortOrder(self) -> str: ...
    def setSortOrder(self, p0: str) -> None: ...
    def dump(self, p0: str, p1: FileDescriptor, p2: PrintWriter, p3: Any) -> None: ...
