from typing import Any, ClassVar, overload
from android.net.Uri import Uri
from android.os.Parcel import Parcel

class UriPermission:
    CREATOR: ClassVar[Any]
    INVALID_TIME: ClassVar[int]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    def isWritePermission(self) -> bool: ...
    def getPersistedTime(self) -> int: ...
    def isReadPermission(self) -> bool: ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
    def getUri(self) -> Uri: ...
    def toString(self) -> str: ...
