from typing import Any, ClassVar, overload

class Interpolator:
    @overload
    def __init__(self, p0: int) -> None: ...
    @overload
    def __init__(self, p0: int, p1: int) -> None: ...
    def getKeyFrameCount(self) -> int: ...
    @overload
    def timeToValues(self, p0: int, p1: Any) -> Any: ...
    @overload
    def timeToValues(self, p0: Any) -> Any: ...
    def setRepeatMirror(self, p0: float, p1: bool) -> None: ...
    def getValueCount(self) -> int: ...
    @overload
    def setKeyFrame(self, p0: int, p1: int, p2: Any, p3: Any) -> None: ...
    @overload
    def setKeyFrame(self, p0: int, p1: int, p2: Any) -> None: ...
    @overload
    def reset(self, p0: int) -> None: ...
    @overload
    def reset(self, p0: int, p1: int) -> None: ...

    class Result:
        FREEZE_END: ClassVar["Result"]
        FREEZE_START: ClassVar["Result"]
        NORMAL: ClassVar["Result"]
        FREEZE_END: ClassVar[Any]
        FREEZE_START: ClassVar[Any]
        NORMAL: ClassVar[Any]
        @staticmethod
        def values() -> Any: ...
        @staticmethod
        def valueOf(p0: str) -> Any: ...
