from typing import Any, ClassVar, overload
from android.os.Bundle import Bundle
from android.os.Parcel import Parcel
from java.util.Locale import Locale

class Address:
    CREATOR: ClassVar[Any]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    def __init__(self, p0: Locale) -> None: ...
    def clearLatitude(self) -> None: ...
    def clearLongitude(self) -> None: ...
    def getAddressLine(self, p0: int) -> str: ...
    def getAdminArea(self) -> str: ...
    def getCountryCode(self) -> str: ...
    def getCountryName(self) -> str: ...
    def getFeatureName(self) -> str: ...
    def getLocality(self) -> str: ...
    def getMaxAddressLineIndex(self) -> int: ...
    def getPhone(self) -> str: ...
    def getPostalCode(self) -> str: ...
    def getPremises(self) -> str: ...
    def getSubAdminArea(self) -> str: ...
    def getSubLocality(self) -> str: ...
    def getSubThoroughfare(self) -> str: ...
    def getThoroughfare(self) -> str: ...
    def hasLatitude(self) -> bool: ...
    def hasLongitude(self) -> bool: ...
    def setAddressLine(self, p0: int, p1: str) -> None: ...
    def setAdminArea(self, p0: str) -> None: ...
    def setCountryCode(self, p0: str) -> None: ...
    def setCountryName(self, p0: str) -> None: ...
    def setFeatureName(self, p0: str) -> None: ...
    def setLocality(self, p0: str) -> None: ...
    def setPhone(self, p0: str) -> None: ...
    def setPostalCode(self, p0: str) -> None: ...
    def setPremises(self, p0: str) -> None: ...
    def setSubAdminArea(self, p0: str) -> None: ...
    def setSubLocality(self, p0: str) -> None: ...
    def setSubThoroughfare(self, p0: str) -> None: ...
    def setThoroughfare(self, p0: str) -> None: ...
    def setUrl(self, p0: str) -> None: ...
    def toString(self) -> str: ...
    def setExtras(self, p0: Bundle) -> None: ...
    def setLatitude(self, p0: float) -> None: ...
    def setLongitude(self, p0: float) -> None: ...
    def getLocale(self) -> Locale: ...
    def getLatitude(self) -> float: ...
    def getLongitude(self) -> float: ...
    def getUrl(self) -> str: ...
    def getExtras(self) -> Bundle: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
    def describeContents(self) -> int: ...
