from typing import Any, ClassVar, overload
from android.os.Parcel import Parcel

class GnssClock:
    CREATOR: ClassVar[Any]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    def getTimeNanos(self) -> int: ...
    def getFullBiasNanos(self) -> int: ...
    def getBiasNanos(self) -> float: ...
    def getBiasUncertaintyNanos(self) -> float: ...
    def getDriftNanosPerSecond(self) -> float: ...
    def getDriftUncertaintyNanosPerSecond(self) -> float: ...
    def getHardwareClockDiscontinuityCount(self) -> int: ...
    def getLeapSecond(self) -> int: ...
    def getReferenceCarrierFrequencyHzForIsb(self) -> float: ...
    def getReferenceCodeTypeForIsb(self) -> str: ...
    def getReferenceConstellationTypeForIsb(self) -> int: ...
    def getTimeUncertaintyNanos(self) -> float: ...
    def hasBiasNanos(self) -> bool: ...
    def hasBiasUncertaintyNanos(self) -> bool: ...
    def hasDriftNanosPerSecond(self) -> bool: ...
    def hasDriftUncertaintyNanosPerSecond(self) -> bool: ...
    def hasElapsedRealtimeNanos(self) -> bool: ...
    def hasFullBiasNanos(self) -> bool: ...
    def hasLeapSecond(self) -> bool: ...
    def hasReferenceCarrierFrequencyHzForIsb(self) -> bool: ...
    def hasReferenceCodeTypeForIsb(self) -> bool: ...
    def hasReferenceConstellationTypeForIsb(self) -> bool: ...
    def hasTimeUncertaintyNanos(self) -> bool: ...
    def toString(self) -> str: ...
    def getElapsedRealtimeNanos(self) -> int: ...
    def getElapsedRealtimeUncertaintyNanos(self) -> float: ...
    def hasElapsedRealtimeUncertaintyNanos(self) -> bool: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
    def describeContents(self) -> int: ...
