from typing import Any, ClassVar, overload

class GpsSatellite:
    def hasEphemeris(self) -> bool: ...
    def hasAlmanac(self) -> bool: ...
    def getSnr(self) -> float: ...
    def usedInFix(self) -> bool: ...
    def getElevation(self) -> float: ...
    def getAzimuth(self) -> float: ...
    def getPrn(self) -> int: ...
