from typing import Any, ClassVar, overload
from android.app.usage.UsageEvents import UsageEvents
from android.app.usage.UsageEventsQuery import UsageEventsQuery

class UsageStatsManager:
    EXTRA_EVENT_ACTION: ClassVar[str]
    EXTRA_EVENT_CATEGORY: ClassVar[str]
    INTERVAL_BEST: ClassVar[int]
    INTERVAL_DAILY: ClassVar[int]
    INTERVAL_MONTHLY: ClassVar[int]
    INTERVAL_WEEKLY: ClassVar[int]
    INTERVAL_YEARLY: ClassVar[int]
    STANDBY_BUCKET_ACTIVE: ClassVar[int]
    STANDBY_BUCKET_FREQUENT: ClassVar[int]
    STANDBY_BUCKET_RARE: ClassVar[int]
    STANDBY_BUCKET_RESTRICTED: ClassVar[int]
    STANDBY_BUCKET_WORKING_SET: ClassVar[int]
    def isAppInactive(self, p0: str) -> bool: ...
    def queryEventsForSelf(self, p0: int, p1: int) -> UsageEvents: ...
    @overload
    def queryEvents(self, p0: UsageEventsQuery) -> UsageEvents: ...
    @overload
    def queryEvents(self, p0: int, p1: int) -> UsageEvents: ...
    def queryEventStats(self, p0: int, p1: int, p2: int) -> list: ...
    def queryUsageStats(self, p0: int, p1: int, p2: int) -> list: ...
    def queryAndAggregateUsageStats(self, p0: int, p1: int) -> dict: ...
    def queryConfigurations(self, p0: int, p1: int, p2: int) -> list: ...
    def getAppStandbyBucket(self) -> int: ...
