from typing import Any, ClassVar, overload
from android.os.Parcel import Parcel

class LightState:
    CREATOR: ClassVar[Any]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    def toString(self) -> str: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
    def describeContents(self) -> int: ...
    def getPlayerId(self) -> int: ...
    def getColor(self) -> int: ...

    class Builder:
        def __init__(self) -> None: ...
        def setPlayerId(self, p0: int) -> Any: ...
        def build(self) -> "LightState": ...
        def setColor(self, p0: int) -> Any: ...
