from typing import Any, ClassVar, overload
from android.text.Spannable import Spannable
from android.view.KeyEvent import KeyEvent
from android.view.MotionEvent import MotionEvent
from android.widget.TextView import TextView

class BaseMovementMethod:
    def __init__(self) -> None: ...
    def previousParagraph(self, p0: TextView, p1: Spannable) -> bool: ...
    def nextParagraph(self, p0: TextView, p1: Spannable) -> bool: ...
    def onKeyOther(self, p0: TextView, p1: Spannable, p2: KeyEvent) -> bool: ...
    def canSelectArbitrarily(self) -> bool: ...
    def onTakeFocus(self, p0: TextView, p1: Spannable, p2: int) -> None: ...
    def onKeyDown(self, p0: TextView, p1: Spannable, p2: int, p3: KeyEvent) -> bool: ...
    def onTrackballEvent(self, p0: TextView, p1: Spannable, p2: MotionEvent) -> bool: ...
    def onGenericMotionEvent(self, p0: TextView, p1: Spannable, p2: MotionEvent) -> bool: ...
    def onTouchEvent(self, p0: TextView, p1: Spannable, p2: MotionEvent) -> bool: ...
    def onKeyUp(self, p0: TextView, p1: Spannable, p2: int, p3: KeyEvent) -> bool: ...
    def initialize(self, p0: TextView, p1: Spannable) -> None: ...
