from typing import Any, ClassVar, overload

class MtpStorageInfo:
    def getStorageId(self) -> int: ...
    def getMaxCapacity(self) -> int: ...
    def getVolumeIdentifier(self) -> str: ...
    def getDescription(self) -> str: ...
    def getFreeSpace(self) -> int: ...
