from typing import Any, ClassVar, overload
from android.webkit.ServiceWorkerClient import ServiceWorkerClient
from android.webkit.ServiceWorkerWebSettings import ServiceWorkerWebSettings

class ServiceWorkerController:
    def __init__(self) -> None: ...
    def getServiceWorkerWebSettings(self) -> ServiceWorkerWebSettings: ...
    def setServiceWorkerClient(self, p0: ServiceWorkerClient) -> None: ...
    @staticmethod
    def getInstance() -> "ServiceWorkerController": ...
