from typing import Any, ClassVar, overload
from android.content.ClipData import ClipData
from android.content.ClipDescription import ClipDescription
from android.os.Parcel import Parcel

class DragEvent:
    ACTION_DRAG_ENDED: ClassVar[int]
    ACTION_DRAG_ENTERED: ClassVar[int]
    ACTION_DRAG_EXITED: ClassVar[int]
    ACTION_DRAG_LOCATION: ClassVar[int]
    ACTION_DRAG_STARTED: ClassVar[int]
    ACTION_DROP: ClassVar[int]
    CREATOR: ClassVar[Any]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    def toString(self) -> str: ...
    def getAction(self) -> int: ...
    def getClipData(self) -> ClipData: ...
    def getX(self) -> float: ...
    def getY(self) -> float: ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
    def getClipDescription(self) -> ClipDescription: ...
    def getLocalState(self) -> Any: ...
    def getResult(self) -> bool: ...
