from typing import Any, ClassVar, overload
from android.graphics.Point import Point
from android.os.Parcel import Parcel

class RoundedCorner:
    CREATOR: ClassVar[Any]
    POSITION_BOTTOM_LEFT: ClassVar[int]
    POSITION_BOTTOM_RIGHT: ClassVar[int]
    POSITION_TOP_LEFT: ClassVar[int]
    POSITION_TOP_RIGHT: ClassVar[int]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    def __init__(self, p0: int, p1: int, p2: int, p3: int) -> None: ...
    def equals(self, p0: Any) -> bool: ...
    def toString(self) -> str: ...
    def hashCode(self) -> int: ...
    def getCenter(self) -> Point: ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
    def getPosition(self) -> int: ...
    def getRadius(self) -> int: ...
