from typing import Any, ClassVar, overload
from android.graphics.Canvas import Canvas
from android.graphics.Rect import Rect
from android.view.Surface import Surface
from java.lang.Runnable import Runnable

class SurfaceHolder:
    SURFACE_TYPE_GPU: ClassVar[int]
    SURFACE_TYPE_HARDWARE: ClassVar[int]
    SURFACE_TYPE_NORMAL: ClassVar[int]
    SURFACE_TYPE_PUSH_BUFFERS: ClassVar[int]
    def getSurfaceFrame(self) -> Rect: ...
    def isCreating(self) -> bool: ...
    def setFixedSize(self, p0: int, p1: int) -> None: ...
    def setSizeFromLayout(self) -> None: ...
    def getSurface(self) -> Surface: ...
    @overload
    def lockCanvas(self, p0: Rect) -> Canvas: ...
    @overload
    def lockCanvas(self) -> Canvas: ...
    def lockHardwareCanvas(self) -> Canvas: ...
    def unlockCanvasAndPost(self, p0: Canvas) -> None: ...
    def setFormat(self, p0: int) -> None: ...
    def setType(self, p0: int) -> None: ...
    def addCallback(self, p0: Any) -> None: ...
    def removeCallback(self, p0: Any) -> None: ...
    def setKeepScreenOn(self, p0: bool) -> None: ...

    class Callback2:
        def surfaceRedrawNeeded(self, p0: "SurfaceHolder") -> None: ...
        def surfaceRedrawNeededAsync(self, p0: "SurfaceHolder", p1: Runnable) -> None: ...

    class Callback:
        def surfaceChanged(self, p0: "SurfaceHolder", p1: int, p2: int, p3: int) -> None: ...
        def surfaceCreated(self, p0: "SurfaceHolder") -> None: ...
        def surfaceDestroyed(self, p0: "SurfaceHolder") -> None: ...

    class BadSurfaceTypeException:
        @overload
        def __init__(self) -> None: ...
        @overload
        def __init__(self, p0: str) -> None: ...
