from typing import Any, ClassVar, overload
from android.graphics.Rect import Rect
from android.view.WindowInsets import WindowInsets

class WindowMetrics:
    @overload
    def __init__(self, p0: Rect, p1: WindowInsets) -> None: ...
    @overload
    def __init__(self, p0: Rect, p1: WindowInsets, p2: float) -> None: ...
    def getWindowInsets(self) -> WindowInsets: ...
    def toString(self) -> str: ...
    def getBounds(self) -> Rect: ...
    def getDensity(self) -> float: ...
