from typing import Any, ClassVar, overload

class AdId:
    ZERO_OUT: ClassVar[str]
    def __init__(self, p0: str, p1: bool) -> None: ...
    def getAdId(self) -> str: ...
    def isLimitAdTrackingEnabled(self) -> bool: ...
    def equals(self, p0: Any) -> bool: ...
    def toString(self) -> str: ...
    def hashCode(self) -> int: ...
