from typing import Any, ClassVar, overload
from android.app.PendingIntent import PendingIntent
from android.net.LinkProperties import LinkProperties
from android.net.Network import Network
from android.net.NetworkCapabilities import NetworkCapabilities
from android.net.NetworkInfo import NetworkInfo
from android.net.NetworkRequest import NetworkRequest
from android.net.ProxyInfo import ProxyInfo
from android.net.SocketKeepalive import SocketKeepalive
from android.os.Handler import Handler
from java.net.InetAddress import InetAddress
from java.net.InetSocketAddress import InetSocketAddress
from java.util.concurrent.Executor import Executor

class ConnectivityManager:
    ACTION_BACKGROUND_DATA_SETTING_CHANGED: ClassVar[str]
    ACTION_CAPTIVE_PORTAL_SIGN_IN: ClassVar[str]
    ACTION_RESTRICT_BACKGROUND_CHANGED: ClassVar[str]
    CONNECTIVITY_ACTION: ClassVar[str]
    DEFAULT_NETWORK_PREFERENCE: ClassVar[int]
    EXTRA_CAPTIVE_PORTAL: ClassVar[str]
    EXTRA_CAPTIVE_PORTAL_URL: ClassVar[str]
    EXTRA_EXTRA_INFO: ClassVar[str]
    EXTRA_IS_FAILOVER: ClassVar[str]
    EXTRA_NETWORK: ClassVar[str]
    EXTRA_NETWORK_INFO: ClassVar[str]
    EXTRA_NETWORK_REQUEST: ClassVar[str]
    EXTRA_NETWORK_TYPE: ClassVar[str]
    EXTRA_NO_CONNECTIVITY: ClassVar[str]
    EXTRA_OTHER_NETWORK_INFO: ClassVar[str]
    EXTRA_REASON: ClassVar[str]
    MULTIPATH_PREFERENCE_HANDOVER: ClassVar[int]
    MULTIPATH_PREFERENCE_PERFORMANCE: ClassVar[int]
    MULTIPATH_PREFERENCE_RELIABILITY: ClassVar[int]
    RESTRICT_BACKGROUND_STATUS_DISABLED: ClassVar[int]
    RESTRICT_BACKGROUND_STATUS_ENABLED: ClassVar[int]
    RESTRICT_BACKGROUND_STATUS_WHITELISTED: ClassVar[int]
    TYPE_BLUETOOTH: ClassVar[int]
    TYPE_DUMMY: ClassVar[int]
    TYPE_ETHERNET: ClassVar[int]
    TYPE_MOBILE: ClassVar[int]
    TYPE_MOBILE_DUN: ClassVar[int]
    TYPE_MOBILE_HIPRI: ClassVar[int]
    TYPE_MOBILE_MMS: ClassVar[int]
    TYPE_MOBILE_SUPL: ClassVar[int]
    TYPE_VPN: ClassVar[int]
    TYPE_WIFI: ClassVar[int]
    TYPE_WIMAX: ClassVar[int]
    def getNetworkCapabilities(self, p0: Network) -> NetworkCapabilities: ...
    def getLinkProperties(self, p0: Network) -> LinkProperties: ...
    def addDefaultNetworkActiveListener(self, p0: Any) -> None: ...
    def bindProcessToNetwork(self, p0: Network) -> bool: ...
    def createSocketKeepalive(self, p0: Network, p1: Any, p2: InetAddress, p3: InetAddress, p4: Executor, p5: Any) -> SocketKeepalive: ...
    def getActiveNetwork(self) -> Network: ...
    def getActiveNetworkInfo(self) -> NetworkInfo: ...
    def getAllNetworkInfo(self) -> Any: ...
    def getAllNetworks(self) -> Any: ...
    def getBackgroundDataSetting(self) -> bool: ...
    def getBoundNetworkForProcess(self) -> Network: ...
    def getConnectionOwnerUid(self, p0: int, p1: InetSocketAddress, p2: InetSocketAddress) -> int: ...
    def getDefaultProxy(self) -> ProxyInfo: ...
    def getMultipathPreference(self, p0: Network) -> int: ...
    @overload
    def getNetworkInfo(self, p0: Network) -> NetworkInfo: ...
    @overload
    def getNetworkInfo(self, p0: int) -> NetworkInfo: ...
    def getNetworkPreference(self) -> int: ...
    def getNetworkWatchlistConfigHash(self) -> Any: ...
    @staticmethod
    def getProcessDefaultNetwork() -> Network: ...
    def getRestrictBackgroundStatus(self) -> int: ...
    def isActiveNetworkMetered(self) -> bool: ...
    def isDefaultNetworkActive(self) -> bool: ...
    @staticmethod
    def isNetworkTypeValid(p0: int) -> bool: ...
    def registerBestMatchingNetworkCallback(self, p0: NetworkRequest, p1: Any, p2: Handler) -> None: ...
    @overload
    def registerDefaultNetworkCallback(self, p0: Any) -> None: ...
    @overload
    def registerDefaultNetworkCallback(self, p0: Any, p1: Handler) -> None: ...
    @overload
    def registerNetworkCallback(self, p0: NetworkRequest, p1: Any, p2: Handler) -> None: ...
    @overload
    def registerNetworkCallback(self, p0: NetworkRequest, p1: Any) -> None: ...
    @overload
    def registerNetworkCallback(self, p0: NetworkRequest, p1: PendingIntent) -> None: ...
    def releaseNetworkRequest(self, p0: PendingIntent) -> None: ...
    def removeDefaultNetworkActiveListener(self, p0: Any) -> None: ...
    def reportBadNetwork(self, p0: Network) -> None: ...
    def reportNetworkConnectivity(self, p0: Network, p1: bool) -> None: ...
    def requestBandwidthUpdate(self, p0: Network) -> bool: ...
    @overload
    def requestNetwork(self, p0: NetworkRequest, p1: Any, p2: Handler) -> None: ...
    @overload
    def requestNetwork(self, p0: NetworkRequest, p1: Any, p2: int) -> None: ...
    @overload
    def requestNetwork(self, p0: NetworkRequest, p1: Any, p2: Handler, p3: int) -> None: ...
    @overload
    def requestNetwork(self, p0: NetworkRequest, p1: PendingIntent) -> None: ...
    @overload
    def requestNetwork(self, p0: NetworkRequest, p1: Any) -> None: ...
    def reserveNetwork(self, p0: NetworkRequest, p1: Handler, p2: Any) -> None: ...
    def setNetworkPreference(self, p0: int) -> None: ...
    @staticmethod
    def setProcessDefaultNetwork(p0: Network) -> bool: ...
    @overload
    def unregisterNetworkCallback(self, p0: PendingIntent) -> None: ...
    @overload
    def unregisterNetworkCallback(self, p0: Any) -> None: ...

    class OnNetworkActiveListener:
        def onNetworkActive(self) -> None: ...

    class NetworkCallback:
        FLAG_INCLUDE_LOCATION_INFO: ClassVar[int]
        @overload
        def __init__(self, p0: int) -> None: ...
        @overload
        def __init__(self) -> None: ...
        def onAvailable(self, p0: Network) -> None: ...
        def onUnavailable(self) -> None: ...
        def onLosing(self, p0: Network, p1: int) -> None: ...
        def onLost(self, p0: Network) -> None: ...
        def onCapabilitiesChanged(self, p0: Network, p1: NetworkCapabilities) -> None: ...
        def onBlockedStatusChanged(self, p0: Network, p1: bool) -> None: ...
        def onReserved(self, p0: NetworkCapabilities) -> None: ...
        def onLinkPropertiesChanged(self, p0: Network, p1: LinkProperties) -> None: ...
