from typing import Any, ClassVar, overload
from android.net.ProxyInfo import ProxyInfo
from android.net.StaticIpConfiguration import StaticIpConfiguration
from android.os.Parcel import Parcel

class IpConfiguration:
    CREATOR: ClassVar[Any]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    def getHttpProxy(self) -> ProxyInfo: ...
    def getStaticIpConfiguration(self) -> StaticIpConfiguration: ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
    def equals(self, p0: Any) -> bool: ...
    def toString(self) -> str: ...
    def hashCode(self) -> int: ...

    class Builder:
        def __init__(self) -> None: ...
        def setHttpProxy(self, p0: ProxyInfo) -> Any: ...
        def setStaticIpConfiguration(self, p0: StaticIpConfiguration) -> Any: ...
        def build(self) -> "IpConfiguration": ...
