from typing import Any, ClassVar, overload
from android.net.Credentials import Credentials
from android.net.LocalSocketAddress import LocalSocketAddress
from java.io.FileDescriptor import FileDescriptor
from java.io.InputStream import InputStream
from java.io.OutputStream import OutputStream

class LocalSocket:
    SOCKET_DGRAM: ClassVar[int]
    SOCKET_SEQPACKET: ClassVar[int]
    SOCKET_STREAM: ClassVar[int]
    @overload
    def __init__(self, p0: int) -> None: ...
    @overload
    def __init__(self) -> None: ...
    def setFileDescriptorsForSend(self, p0: Any) -> None: ...
    def getAncillaryFileDescriptors(self) -> Any: ...
    def getPeerCredentials(self) -> Credentials: ...
    def isConnected(self) -> bool: ...
    def isBound(self) -> bool: ...
    def getRemoteSocketAddress(self) -> LocalSocketAddress: ...
    def getLocalSocketAddress(self) -> LocalSocketAddress: ...
    def setSoTimeout(self, p0: int) -> None: ...
    def getSoTimeout(self) -> int: ...
    def setSendBufferSize(self, p0: int) -> None: ...
    def getSendBufferSize(self) -> int: ...
    def setReceiveBufferSize(self, p0: int) -> None: ...
    def getReceiveBufferSize(self) -> int: ...
    def isInputShutdown(self) -> bool: ...
    def isOutputShutdown(self) -> bool: ...
    def shutdownInput(self) -> None: ...
    def shutdownOutput(self) -> None: ...
    def isClosed(self) -> bool: ...
    def getOutputStream(self) -> OutputStream: ...
    def getFileDescriptor(self) -> FileDescriptor: ...
    def getInputStream(self) -> InputStream: ...
    def bind(self, p0: LocalSocketAddress) -> None: ...
    def toString(self) -> str: ...
    @overload
    def connect(self, p0: LocalSocketAddress, p1: int) -> None: ...
    @overload
    def connect(self, p0: LocalSocketAddress) -> None: ...
    def close(self) -> None: ...
