from typing import Any, ClassVar, overload
from android.os.Parcel import Parcel
from java.net.Inet6Address import Inet6Address

class MacAddress:
    BROADCAST_ADDRESS: ClassVar["MacAddress"]
    CREATOR: ClassVar[Any]
    TYPE_BROADCAST: ClassVar[int]
    TYPE_MULTICAST: ClassVar[int]
    TYPE_UNICAST: ClassVar[int]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    def isLocallyAssigned(self) -> bool: ...
    def toOuiString(self) -> str: ...
    def getAddressType(self) -> int: ...
    def getLinkLocalIpv6FromEui48Mac(self) -> Inet6Address: ...
    def equals(self, p0: Any) -> bool: ...
    def toString(self) -> str: ...
    def hashCode(self) -> int: ...
    def matches(self, p0: "MacAddress", p1: "MacAddress") -> bool: ...
    @staticmethod
    def fromBytes(p0: Any) -> "MacAddress": ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
    def describeContents(self) -> int: ...
    def toByteArray(self) -> Any: ...
    @staticmethod
    def fromString(p0: str) -> "MacAddress": ...
