from typing import Any, ClassVar, overload
from android.net.LinkAddress import LinkAddress
from android.os.Parcel import Parcel
from java.lang.Iterable import Iterable
from java.net.InetAddress import InetAddress

class StaticIpConfiguration:
    CREATOR: ClassVar[Any]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    def getDnsServers(self) -> list: ...
    def getDomains(self) -> str: ...
    def getGateway(self) -> InetAddress: ...
    def equals(self, p0: Any) -> bool: ...
    def toString(self) -> str: ...
    def hashCode(self) -> int: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
    def describeContents(self) -> int: ...
    def getIpAddress(self) -> LinkAddress: ...

    class Builder:
        def __init__(self) -> None: ...
        def setDnsServers(self, p0: Iterable) -> Any: ...
        def setDomains(self, p0: str) -> Any: ...
        def setGateway(self, p0: InetAddress) -> Any: ...
        def setIpAddress(self, p0: LinkAddress) -> Any: ...
        def build(self) -> "StaticIpConfiguration": ...
