from typing import Any, ClassVar, overload
from android.net.eap.EapInfo import EapInfo
from android.net.ipsec.ike.IkeSessionConnectionInfo import IkeSessionConnectionInfo

class IkeSessionConfiguration:
    EXTENSION_TYPE_FRAGMENTATION: ClassVar[int]
    EXTENSION_TYPE_MOBIKE: ClassVar[int]
    def getEapInfo(self) -> EapInfo: ...
    def getRemoteVendorIds(self) -> list: ...
    def getIkeSessionConnectionInfo(self) -> IkeSessionConnectionInfo: ...
    def getRemoteApplicationVersion(self) -> str: ...
    def isIkeExtensionEnabled(self, p0: int) -> bool: ...

    class Builder:
        def __init__(self, p0: IkeSessionConnectionInfo) -> None: ...
        def clearRemoteApplicationVersion(self) -> Any: ...
        def addIkeExtension(self, p0: int) -> Any: ...
        def addRemoteVendorId(self, p0: Any) -> Any: ...
        def clearIkeExtensions(self) -> Any: ...
        def clearRemoteVendorIds(self) -> Any: ...
        def setEapInfo(self, p0: EapInfo) -> Any: ...
        def setRemoteApplicationVersion(self, p0: str) -> Any: ...
        def build(self) -> "IkeSessionConfiguration": ...

from typing import Any, ClassVar, overload
from android.net.ipsec.ike.ChildSaProposal import ChildSaProposal
from android.net.ipsec.ike.IkeTrafficSelector import IkeTrafficSelector
from java.net.Inet4Address import Inet4Address
from java.net.Inet6Address import Inet6Address

class TunnelModeChildSessionParams:
    def getConfigurationRequests(self) -> list: ...
    def equals(self, p0: Any) -> bool: ...
    def hashCode(self) -> int: ...

    class TunnelModeChildConfigRequest:
        ...

    class ConfigRequestIpv6DnsServer:
        ...

    class ConfigRequestIpv6Address:
        def getAddress(self) -> Inet6Address: ...
        def getPrefixLength(self) -> int: ...

    class ConfigRequestIpv4Netmask:
        ...

    class ConfigRequestIpv4DnsServer:
        ...

    class ConfigRequestIpv4DhcpServer:
        ...

    class ConfigRequestIpv4Address:
        def getAddress(self) -> Inet4Address: ...

    class Builder:
        @overload
        def __init__(self, p0: "TunnelModeChildSessionParams") -> None: ...
        @overload
        def __init__(self) -> None: ...
        def addInboundTrafficSelectors(self, p0: IkeTrafficSelector) -> Any: ...
        @overload
        def addInternalAddressRequest(self, p0: int) -> Any: ...
        @overload
        def addInternalAddressRequest(self, p0: Inet4Address) -> Any: ...
        @overload
        def addInternalAddressRequest(self, p0: Inet6Address, p1: int) -> Any: ...
        def addChildSaProposal(self, p0: ChildSaProposal) -> Any: ...
        def addInternalDhcpServerRequest(self, p0: int) -> Any: ...
        def addInternalDnsServerRequest(self, p0: int) -> Any: ...
        def addOutboundTrafficSelectors(self, p0: IkeTrafficSelector) -> Any: ...
        def setLifetimeSeconds(self, p0: int, p1: int) -> Any: ...
        def build(self) -> "TunnelModeChildSessionParams": ...

from typing import Any, ClassVar, overload

class ChildSessionConfiguration:
    def getInboundTrafficSelectors(self) -> list: ...
    def getOutboundTrafficSelectors(self) -> list: ...

    class Builder:
        def __init__(self, p0: list, p1: list) -> None: ...
        def build(self) -> "ChildSessionConfiguration": ...

from typing import Any, ClassVar, overload
from android.net.ipsec.ike.ChildSaProposal import ChildSaProposal
from android.net.ipsec.ike.IkeTrafficSelector import IkeTrafficSelector

class TransportModeChildSessionParams:

    class Builder:
        @overload
        def __init__(self, p0: "TransportModeChildSessionParams") -> None: ...
        @overload
        def __init__(self) -> None: ...
        def addInboundTrafficSelectors(self, p0: IkeTrafficSelector) -> Any: ...
        def addChildSaProposal(self, p0: ChildSaProposal) -> Any: ...
        def addOutboundTrafficSelectors(self, p0: IkeTrafficSelector) -> Any: ...
        def setLifetimeSeconds(self, p0: int, p1: int) -> Any: ...
        def build(self) -> "TransportModeChildSessionParams": ...

from typing import Any, ClassVar, overload
from android.net.IpSecTransform import IpSecTransform
from android.net.ipsec.ike.ChildSessionConfiguration import ChildSessionConfiguration
from android.net.ipsec.ike.exceptions.IkeException import IkeException

class ChildSessionCallback:
    def onClosedWithException(self, p0: IkeException) -> None: ...
    def onIpSecTransformCreated(self, p0: IpSecTransform, p1: int) -> None: ...
    def onIpSecTransformDeleted(self, p0: IpSecTransform, p1: int) -> None: ...
    def onClosed(self) -> None: ...
    def onOpened(self, p0: ChildSessionConfiguration) -> None: ...

from typing import Any, ClassVar, overload
from java.net.InetAddress import InetAddress

class IkeTrafficSelector:
    endPort: int
    endingAddress: InetAddress
    startPort: int
    startingAddress: InetAddress
    def __init__(self, p0: int, p1: int, p2: InetAddress, p3: InetAddress) -> None: ...
    def equals(self, p0: Any) -> bool: ...
    def hashCode(self) -> int: ...

from typing import Any, ClassVar, overload

class IkeFqdnIdentification:
    fqdn: str
    def __init__(self, p0: str) -> None: ...
    def equals(self, p0: Any) -> bool: ...
    def hashCode(self) -> int: ...

from typing import Any, ClassVar, overload
from android.net.Network import Network
from java.net.InetAddress import InetAddress

class IkeSessionConnectionInfo:
    def __init__(self, p0: InetAddress, p1: InetAddress, p2: Network) -> None: ...
    def getRemoteAddress(self) -> InetAddress: ...
    def getNetwork(self) -> Network: ...
    def getLocalAddress(self) -> InetAddress: ...

from typing import Any, ClassVar, overload

class IkeIdentification:
    ...

from typing import Any, ClassVar, overload
from android.net.ipsec.ike.IkeSessionConfiguration import IkeSessionConfiguration
from android.net.ipsec.ike.exceptions.IkeException import IkeException

class IkeSessionCallback:
    def onClosedWithException(self, p0: IkeException) -> None: ...
    def onClosed(self) -> None: ...
    def onOpened(self, p0: IkeSessionConfiguration) -> None: ...
    def onError(self, p0: IkeException) -> None: ...

from typing import Any, ClassVar, overload

class IkeKeyIdIdentification:
    keyId: Any
    def __init__(self, p0: Any) -> None: ...
    def equals(self, p0: Any) -> bool: ...
    def hashCode(self) -> int: ...

from typing import Any, ClassVar, overload
from android.content.Context import Context
from android.net.ipsec.ike.ChildSessionCallback import ChildSessionCallback
from android.net.ipsec.ike.ChildSessionParams import ChildSessionParams
from android.net.ipsec.ike.IkeSessionCallback import IkeSessionCallback
from android.net.ipsec.ike.IkeSessionParams import IkeSessionParams
from java.io.PrintWriter import PrintWriter
from java.util.concurrent.Executor import Executor

class IkeSession:
    def __init__(self, p0: Context, p1: IkeSessionParams, p2: ChildSessionParams, p3: Executor, p4: IkeSessionCallback, p5: ChildSessionCallback) -> None: ...
    def closeChildSession(self, p0: ChildSessionCallback) -> None: ...
    def kill(self) -> None: ...
    def openChildSession(self, p0: ChildSessionParams, p1: ChildSessionCallback) -> None: ...
    def finalize(self) -> None: ...
    def close(self) -> None: ...
    def dump(self, p0: PrintWriter) -> None: ...

from typing import Any, ClassVar, overload

class IkeRfc822AddrIdentification:
    rfc822Name: str
    def __init__(self, p0: str) -> None: ...
    def equals(self, p0: Any) -> bool: ...
    def hashCode(self) -> int: ...

from typing import Any, ClassVar, overload
from java.net.Inet4Address import Inet4Address

class IkeIpv4AddrIdentification:
    ipv4Address: Inet4Address
    def __init__(self, p0: Inet4Address) -> None: ...
    def equals(self, p0: Any) -> bool: ...
    def hashCode(self) -> int: ...

from typing import Any, ClassVar, overload

class ChildSessionParams:
    def getChildSaProposals(self) -> list: ...
    def getHardLifetimeSeconds(self) -> int: ...
    def getInboundTrafficSelectors(self) -> list: ...
    def getOutboundTrafficSelectors(self) -> list: ...
    def getSoftLifetimeSeconds(self) -> int: ...
    def equals(self, p0: Any) -> bool: ...
    def hashCode(self) -> int: ...

from typing import Any, ClassVar, overload

class SaProposal:
    DH_GROUP_1024_BIT_MODP: ClassVar[int]
    DH_GROUP_1536_BIT_MODP: ClassVar[int]
    DH_GROUP_2048_BIT_MODP: ClassVar[int]
    DH_GROUP_3072_BIT_MODP: ClassVar[int]
    DH_GROUP_4096_BIT_MODP: ClassVar[int]
    DH_GROUP_CURVE_25519: ClassVar[int]
    DH_GROUP_NONE: ClassVar[int]
    ENCRYPTION_ALGORITHM_3DES: ClassVar[int]
    ENCRYPTION_ALGORITHM_AES_CBC: ClassVar[int]
    ENCRYPTION_ALGORITHM_AES_CTR: ClassVar[int]
    ENCRYPTION_ALGORITHM_AES_GCM_12: ClassVar[int]
    ENCRYPTION_ALGORITHM_AES_GCM_16: ClassVar[int]
    ENCRYPTION_ALGORITHM_AES_GCM_8: ClassVar[int]
    ENCRYPTION_ALGORITHM_CHACHA20_POLY1305: ClassVar[int]
    INTEGRITY_ALGORITHM_AES_CMAC_96: ClassVar[int]
    INTEGRITY_ALGORITHM_AES_XCBC_96: ClassVar[int]
    INTEGRITY_ALGORITHM_HMAC_SHA1_96: ClassVar[int]
    INTEGRITY_ALGORITHM_HMAC_SHA2_256_128: ClassVar[int]
    INTEGRITY_ALGORITHM_HMAC_SHA2_384_192: ClassVar[int]
    INTEGRITY_ALGORITHM_HMAC_SHA2_512_256: ClassVar[int]
    INTEGRITY_ALGORITHM_NONE: ClassVar[int]
    KEY_LEN_AES_128: ClassVar[int]
    KEY_LEN_AES_192: ClassVar[int]
    KEY_LEN_AES_256: ClassVar[int]
    KEY_LEN_UNUSED: ClassVar[int]
    PSEUDORANDOM_FUNCTION_AES128_CMAC: ClassVar[int]
    PSEUDORANDOM_FUNCTION_AES128_XCBC: ClassVar[int]
    PSEUDORANDOM_FUNCTION_HMAC_SHA1: ClassVar[int]
    PSEUDORANDOM_FUNCTION_SHA2_256: ClassVar[int]
    PSEUDORANDOM_FUNCTION_SHA2_384: ClassVar[int]
    PSEUDORANDOM_FUNCTION_SHA2_512: ClassVar[int]
    def getDhGroups(self) -> list: ...
    def getEncryptionAlgorithms(self) -> list: ...
    def getIntegrityAlgorithms(self) -> list: ...
    @staticmethod
    def getSupportedDhGroups() -> set: ...
    def equals(self, p0: Any) -> bool: ...
    def toString(self) -> str: ...
    def hashCode(self) -> int: ...

from typing import Any, ClassVar, overload
from javax.security.auth.x500.X500Principal import X500Principal

class IkeDerAsn1DnIdentification:
    derAsn1Dn: X500Principal
    def __init__(self, p0: X500Principal) -> None: ...
    def equals(self, p0: Any) -> bool: ...
    def hashCode(self) -> int: ...

from typing import Any, ClassVar, overload
from android.net.ipsec.ike.IkeSessionParams import IkeSessionParams
from android.net.ipsec.ike.TunnelModeChildSessionParams import TunnelModeChildSessionParams

class IkeTunnelConnectionParams:
    def __init__(self, p0: IkeSessionParams, p1: TunnelModeChildSessionParams) -> None: ...
    def getTunnelModeChildSessionParams(self) -> TunnelModeChildSessionParams: ...
    def getIkeSessionParams(self) -> IkeSessionParams: ...
    def equals(self, p0: Any) -> bool: ...
    def hashCode(self) -> int: ...

from typing import Any, ClassVar, overload

class IkeSaProposal:
    DH_GROUP_1024_BIT_MODP: ClassVar[int]
    DH_GROUP_1536_BIT_MODP: ClassVar[int]
    DH_GROUP_2048_BIT_MODP: ClassVar[int]
    DH_GROUP_3072_BIT_MODP: ClassVar[int]
    DH_GROUP_4096_BIT_MODP: ClassVar[int]
    DH_GROUP_CURVE_25519: ClassVar[int]
    DH_GROUP_NONE: ClassVar[int]
    ENCRYPTION_ALGORITHM_3DES: ClassVar[int]
    ENCRYPTION_ALGORITHM_AES_CBC: ClassVar[int]
    ENCRYPTION_ALGORITHM_AES_CTR: ClassVar[int]
    ENCRYPTION_ALGORITHM_AES_GCM_12: ClassVar[int]
    ENCRYPTION_ALGORITHM_AES_GCM_16: ClassVar[int]
    ENCRYPTION_ALGORITHM_AES_GCM_8: ClassVar[int]
    ENCRYPTION_ALGORITHM_CHACHA20_POLY1305: ClassVar[int]
    INTEGRITY_ALGORITHM_AES_CMAC_96: ClassVar[int]
    INTEGRITY_ALGORITHM_AES_XCBC_96: ClassVar[int]
    INTEGRITY_ALGORITHM_HMAC_SHA1_96: ClassVar[int]
    INTEGRITY_ALGORITHM_HMAC_SHA2_256_128: ClassVar[int]
    INTEGRITY_ALGORITHM_HMAC_SHA2_384_192: ClassVar[int]
    INTEGRITY_ALGORITHM_HMAC_SHA2_512_256: ClassVar[int]
    INTEGRITY_ALGORITHM_NONE: ClassVar[int]
    KEY_LEN_AES_128: ClassVar[int]
    KEY_LEN_AES_192: ClassVar[int]
    KEY_LEN_AES_256: ClassVar[int]
    KEY_LEN_UNUSED: ClassVar[int]
    PSEUDORANDOM_FUNCTION_AES128_CMAC: ClassVar[int]
    PSEUDORANDOM_FUNCTION_AES128_XCBC: ClassVar[int]
    PSEUDORANDOM_FUNCTION_HMAC_SHA1: ClassVar[int]
    PSEUDORANDOM_FUNCTION_SHA2_256: ClassVar[int]
    PSEUDORANDOM_FUNCTION_SHA2_384: ClassVar[int]
    PSEUDORANDOM_FUNCTION_SHA2_512: ClassVar[int]
    @staticmethod
    def getSupportedEncryptionAlgorithms() -> set: ...
    @staticmethod
    def getSupportedIntegrityAlgorithms() -> set: ...
    def getPseudorandomFunctions(self) -> list: ...
    @staticmethod
    def getSupportedPseudorandomFunctions() -> set: ...
    def equals(self, p0: Any) -> bool: ...
    def hashCode(self) -> int: ...

    class Builder:
        def __init__(self) -> None: ...
        def addEncryptionAlgorithm(self, p0: int, p1: int) -> Any: ...
        def addDhGroup(self, p0: int) -> Any: ...
        def addIntegrityAlgorithm(self, p0: int) -> Any: ...
        def addPseudorandomFunction(self, p0: int) -> Any: ...
        def build(self) -> "IkeSaProposal": ...

from typing import Any, ClassVar, overload

class ChildSaProposal:
    DH_GROUP_1024_BIT_MODP: ClassVar[int]
    DH_GROUP_1536_BIT_MODP: ClassVar[int]
    DH_GROUP_2048_BIT_MODP: ClassVar[int]
    DH_GROUP_3072_BIT_MODP: ClassVar[int]
    DH_GROUP_4096_BIT_MODP: ClassVar[int]
    DH_GROUP_CURVE_25519: ClassVar[int]
    DH_GROUP_NONE: ClassVar[int]
    ENCRYPTION_ALGORITHM_3DES: ClassVar[int]
    ENCRYPTION_ALGORITHM_AES_CBC: ClassVar[int]
    ENCRYPTION_ALGORITHM_AES_CTR: ClassVar[int]
    ENCRYPTION_ALGORITHM_AES_GCM_12: ClassVar[int]
    ENCRYPTION_ALGORITHM_AES_GCM_16: ClassVar[int]
    ENCRYPTION_ALGORITHM_AES_GCM_8: ClassVar[int]
    ENCRYPTION_ALGORITHM_CHACHA20_POLY1305: ClassVar[int]
    INTEGRITY_ALGORITHM_AES_CMAC_96: ClassVar[int]
    INTEGRITY_ALGORITHM_AES_XCBC_96: ClassVar[int]
    INTEGRITY_ALGORITHM_HMAC_SHA1_96: ClassVar[int]
    INTEGRITY_ALGORITHM_HMAC_SHA2_256_128: ClassVar[int]
    INTEGRITY_ALGORITHM_HMAC_SHA2_384_192: ClassVar[int]
    INTEGRITY_ALGORITHM_HMAC_SHA2_512_256: ClassVar[int]
    INTEGRITY_ALGORITHM_NONE: ClassVar[int]
    KEY_LEN_AES_128: ClassVar[int]
    KEY_LEN_AES_192: ClassVar[int]
    KEY_LEN_AES_256: ClassVar[int]
    KEY_LEN_UNUSED: ClassVar[int]
    PSEUDORANDOM_FUNCTION_AES128_CMAC: ClassVar[int]
    PSEUDORANDOM_FUNCTION_AES128_XCBC: ClassVar[int]
    PSEUDORANDOM_FUNCTION_HMAC_SHA1: ClassVar[int]
    PSEUDORANDOM_FUNCTION_SHA2_256: ClassVar[int]
    PSEUDORANDOM_FUNCTION_SHA2_384: ClassVar[int]
    PSEUDORANDOM_FUNCTION_SHA2_512: ClassVar[int]
    @staticmethod
    def getSupportedEncryptionAlgorithms() -> set: ...
    @staticmethod
    def getSupportedIntegrityAlgorithms() -> set: ...
    def equals(self, p0: Any) -> bool: ...
    def hashCode(self) -> int: ...

    class Builder:
        def __init__(self) -> None: ...
        def addEncryptionAlgorithm(self, p0: int, p1: int) -> Any: ...
        def addDhGroup(self, p0: int) -> Any: ...
        def addIntegrityAlgorithm(self, p0: int) -> Any: ...
        def build(self) -> "ChildSaProposal": ...

from typing import Any, ClassVar, overload
from java.net.Inet6Address import Inet6Address

class IkeIpv6AddrIdentification:
    ipv6Address: Inet6Address
    def __init__(self, p0: Inet6Address) -> None: ...
    def equals(self, p0: Any) -> bool: ...
    def hashCode(self) -> int: ...

from typing import Any, ClassVar, overload
from android.net.Network import Network
from android.net.eap.EapSessionConfig import EapSessionConfig
from android.net.ipsec.ike.IkeIdentification import IkeIdentification
from android.net.ipsec.ike.IkeSaProposal import IkeSaProposal
from java.security.PrivateKey import PrivateKey
from java.security.cert.X509Certificate import X509Certificate

class IkeSessionParams:
    IKE_DPD_DELAY_SEC_DISABLED: ClassVar[int]
    IKE_OPTION_ACCEPT_ANY_REMOTE_ID: ClassVar[int]
    IKE_OPTION_EAP_ONLY_AUTH: ClassVar[int]
    IKE_OPTION_FORCE_PORT_4500: ClassVar[int]
    IKE_OPTION_INITIAL_CONTACT: ClassVar[int]
    IKE_OPTION_MOBIKE: ClassVar[int]
    def getHardLifetimeSeconds(self) -> int: ...
    def getSoftLifetimeSeconds(self) -> int: ...
    def getDpdDelaySeconds(self) -> int: ...
    def getIkeOptions(self) -> set: ...
    def getIkeSaProposals(self) -> list: ...
    def getLocalAuthConfig(self) -> Any: ...
    def getLocalIdentification(self) -> IkeIdentification: ...
    def getNattKeepAliveDelaySeconds(self) -> int: ...
    def getRemoteAuthConfig(self) -> Any: ...
    def getRemoteIdentification(self) -> IkeIdentification: ...
    def getRetransmissionTimeoutsMillis(self) -> Any: ...
    def getServerHostname(self) -> str: ...
    def hasIkeOption(self, p0: int) -> bool: ...
    def equals(self, p0: Any) -> bool: ...
    def hashCode(self) -> int: ...
    def getNetwork(self) -> Network: ...

    class IkeAuthPskConfig:
        def getPsk(self) -> Any: ...
        def equals(self, p0: Any) -> bool: ...
        def hashCode(self) -> int: ...

    class IkeAuthEapConfig:
        def getEapConfig(self) -> EapSessionConfig: ...
        def equals(self, p0: Any) -> bool: ...
        def hashCode(self) -> int: ...

    class IkeAuthDigitalSignRemoteConfig:
        def getRemoteCaCert(self) -> X509Certificate: ...
        def equals(self, p0: Any) -> bool: ...
        def hashCode(self) -> int: ...

    class IkeAuthDigitalSignLocalConfig:
        def getClientEndCertificate(self) -> X509Certificate: ...
        def getIntermediateCertificates(self) -> list: ...
        def equals(self, p0: Any) -> bool: ...
        def hashCode(self) -> int: ...
        def getPrivateKey(self) -> PrivateKey: ...

    class IkeAuthConfig:
        def equals(self, p0: Any) -> bool: ...
        def hashCode(self) -> int: ...

    class Builder:
        @overload
        def __init__(self, p0: "IkeSessionParams") -> None: ...
        @overload
        def __init__(self) -> None: ...
        @overload
        def setAuthDigitalSignature(self, p0: X509Certificate, p1: X509Certificate, p2: PrivateKey) -> Any: ...
        @overload
        def setAuthDigitalSignature(self, p0: X509Certificate, p1: X509Certificate, p2: list, p3: PrivateKey) -> Any: ...
        def setAuthPsk(self, p0: Any) -> Any: ...
        def addIkeOption(self, p0: int) -> Any: ...
        def addIkeSaProposal(self, p0: IkeSaProposal) -> Any: ...
        def removeIkeOption(self, p0: int) -> Any: ...
        def setAuthEap(self, p0: X509Certificate, p1: EapSessionConfig) -> Any: ...
        def setDpdDelaySeconds(self, p0: int) -> Any: ...
        def setLocalIdentification(self, p0: IkeIdentification) -> Any: ...
        def setNattKeepAliveDelaySeconds(self, p0: int) -> Any: ...
        def setRemoteIdentification(self, p0: IkeIdentification) -> Any: ...
        def setRetransmissionTimeoutsMillis(self, p0: Any) -> Any: ...
        def setServerHostname(self, p0: str) -> Any: ...
        def setLifetimeSeconds(self, p0: int, p1: int) -> Any: ...
        def build(self) -> "IkeSessionParams": ...
        def setNetwork(self, p0: Network) -> Any: ...

