from typing import Any, ClassVar, overload
from java.security.Provider import Provider
from java.security.SecureRandom import SecureRandom
from javax.net.ssl.SSLEngine import SSLEngine
from javax.net.ssl.SSLParameters import SSLParameters
from javax.net.ssl.SSLServerSocketFactory import SSLServerSocketFactory
from javax.net.ssl.SSLSessionContext import SSLSessionContext
from javax.net.ssl.SSLSocketFactory import SSLSocketFactory

class SSLContext:
    def getSocketFactory(self) -> SSLSocketFactory: ...
    @overload
    def createSSLEngine(self, p0: str, p1: int) -> SSLEngine: ...
    @overload
    def createSSLEngine(self) -> SSLEngine: ...
    def getServerSessionContext(self) -> SSLSessionContext: ...
    def getClientSessionContext(self) -> SSLSessionContext: ...
    def getDefaultSSLParameters(self) -> SSLParameters: ...
    def getSupportedSSLParameters(self) -> SSLParameters: ...
    def getProtocol(self) -> str: ...
    @staticmethod
    def setDefault(p0: "SSLContext") -> None: ...
    def getServerSocketFactory(self) -> SSLServerSocketFactory: ...
    def getProvider(self) -> Provider: ...
    @staticmethod
    def getDefault() -> "SSLContext": ...
    @overload
    @staticmethod
    def getInstance(p0: str, p1: str) -> "SSLContext": ...
    @overload
    @staticmethod
    def getInstance(p0: str) -> "SSLContext": ...
    @overload
    @staticmethod
    def getInstance(p0: str, p1: Provider) -> "SSLContext": ...
    def init(self, p0: Any, p1: Any, p2: SecureRandom) -> None: ...
