from typing import Any, ClassVar, overload
from java.security.Provider import Provider
from java.security.PublicKey import PublicKey

class Certificate:
    def equals(self, p0: Any) -> bool: ...
    def toString(self) -> str: ...
    def hashCode(self) -> int: ...
    def getType(self) -> str: ...
    def getEncoded(self) -> Any: ...
    @overload
    def verify(self, p0: PublicKey) -> None: ...
    @overload
    def verify(self, p0: PublicKey, p1: str) -> None: ...
    @overload
    def verify(self, p0: PublicKey, p1: Provider) -> None: ...
    def getPublicKey(self) -> PublicKey: ...
