from typing import Any, ClassVar, overload
from java.security.Provider import Provider
from java.security.cert.CRLSelector import CRLSelector
from java.security.cert.CertSelector import CertSelector
from java.security.cert.CertStoreParameters import CertStoreParameters

class CertStore:
    @staticmethod
    def getDefaultType() -> str: ...
    def getProvider(self) -> Provider: ...
    @overload
    @staticmethod
    def getInstance(p0: str, p1: CertStoreParameters, p2: str) -> "CertStore": ...
    @overload
    @staticmethod
    def getInstance(p0: str, p1: CertStoreParameters, p2: Provider) -> "CertStore": ...
    @overload
    @staticmethod
    def getInstance(p0: str, p1: CertStoreParameters) -> "CertStore": ...
    def getCertificates(self, p0: CertSelector) -> list: ...
    def getType(self) -> str: ...
    def getCRLs(self, p0: CRLSelector) -> list: ...
    def getCertStoreParameters(self) -> CertStoreParameters: ...
