from typing import Any, ClassVar, overload
from android.net.MacAddress import MacAddress
from android.net.wifi.WpsInfo import WpsInfo
from android.os.Parcel import Parcel

class WifiP2pConfig:
    CREATOR: ClassVar[Any]
    GROUP_CLIENT_IP_PROVISIONING_MODE_IPV4_DHCP: ClassVar[int]
    GROUP_CLIENT_IP_PROVISIONING_MODE_IPV6_LINK_LOCAL: ClassVar[int]
    GROUP_OWNER_BAND_2GHZ: ClassVar[int]
    GROUP_OWNER_BAND_5GHZ: ClassVar[int]
    GROUP_OWNER_BAND_AUTO: ClassVar[int]
    GROUP_OWNER_INTENT_AUTO: ClassVar[int]
    GROUP_OWNER_INTENT_MAX: ClassVar[int]
    GROUP_OWNER_INTENT_MIN: ClassVar[int]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    deviceAddress: str
    groupOwnerIntent: int
    wps: WpsInfo
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, p0: "WifiP2pConfig") -> None: ...
    def getNetworkId(self) -> int: ...
    def getPassphrase(self) -> str: ...
    def getGroupOwnerBand(self) -> int: ...
    def getGroupClientIpProvisioningMode(self) -> int: ...
    def getNetworkName(self) -> str: ...
    def toString(self) -> str: ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...

    class Builder:
        def __init__(self) -> None: ...
        def setDeviceAddress(self, p0: MacAddress) -> Any: ...
        def setGroupOperatingFrequency(self, p0: int) -> Any: ...
        def setNetworkName(self, p0: str) -> Any: ...
        def setPassphrase(self, p0: str) -> Any: ...
        def setGroupOperatingBand(self, p0: int) -> Any: ...
        def enablePersistentMode(self, p0: bool) -> Any: ...
        def setGroupClientIpProvisioningMode(self, p0: int) -> Any: ...
        def build(self) -> "WifiP2pConfig": ...
