from typing import Any, ClassVar, overload
from android.os.Parcel import Parcel

class WifiP2pWfdInfo:
    CREATOR: ClassVar[Any]
    DEVICE_INFO_AUDIO_ONLY_SUPPORT_AT_SOURCE: ClassVar[int]
    DEVICE_INFO_AUDIO_UNSUPPORTED_AT_PRIMARY_SINK: ClassVar[int]
    DEVICE_INFO_CONTENT_PROTECTION_SUPPORT: ClassVar[int]
    DEVICE_INFO_COUPLED_SINK_SUPPORT_AT_SINK: ClassVar[int]
    DEVICE_INFO_COUPLED_SINK_SUPPORT_AT_SOURCE: ClassVar[int]
    DEVICE_INFO_DEVICE_TYPE_MASK: ClassVar[int]
    DEVICE_INFO_PREFERRED_CONNECTIVITY_MASK: ClassVar[int]
    DEVICE_INFO_SESSION_AVAILABLE_MASK: ClassVar[int]
    DEVICE_INFO_TDLS_PERSISTENT_GROUP: ClassVar[int]
    DEVICE_INFO_TDLS_PERSISTENT_GROUP_REINVOKE: ClassVar[int]
    DEVICE_INFO_TIME_SYNCHRONIZATION_SUPPORT: ClassVar[int]
    DEVICE_INFO_WFD_SERVICE_DISCOVERY_SUPPORT: ClassVar[int]
    DEVICE_TYPE_PRIMARY_SINK: ClassVar[int]
    DEVICE_TYPE_SECONDARY_SINK: ClassVar[int]
    DEVICE_TYPE_SOURCE_OR_PRIMARY_SINK: ClassVar[int]
    DEVICE_TYPE_WFD_SOURCE: ClassVar[int]
    PREFERRED_CONNECTIVITY_P2P: ClassVar[int]
    PREFERRED_CONNECTIVITY_TDLS: ClassVar[int]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    @overload
    def __init__(self, p0: "WifiP2pWfdInfo") -> None: ...
    @overload
    def __init__(self) -> None: ...
    def setDeviceType(self, p0: int) -> bool: ...
    def getDeviceType(self) -> int: ...
    def getDeviceInfo(self) -> int: ...
    def getR2DeviceInfo(self) -> int: ...
    def getControlPort(self) -> int: ...
    def getR2DeviceType(self) -> int: ...
    def setR2DeviceType(self, p0: int) -> bool: ...
    def getMaxThroughput(self) -> int: ...
    def isSessionAvailable(self) -> bool: ...
    def setControlPort(self, p0: int) -> None: ...
    def isR2Supported(self) -> bool: ...
    def setMaxThroughput(self, p0: int) -> None: ...
    def isContentProtectionSupported(self) -> bool: ...
    def isCoupledSinkSupportedAtSink(self) -> bool: ...
    def isCoupledSinkSupportedAtSource(self) -> bool: ...
    def setContentProtectionSupported(self, p0: bool) -> None: ...
    def setCoupledSinkSupportAtSink(self, p0: bool) -> None: ...
    def setCoupledSinkSupportAtSource(self, p0: bool) -> None: ...
    def setSessionAvailable(self, p0: bool) -> None: ...
    def toString(self) -> str: ...
    def isEnabled(self) -> bool: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
    def describeContents(self) -> int: ...
    def setEnabled(self, p0: bool) -> None: ...
