from typing import Any, ClassVar, overload
from java.lang.ClassLoader import ClassLoader
from java.net.URL import URL
from java.util.Enumeration import Enumeration

class DelegateLastClassLoader:
    @overload
    def __init__(self, p0: str, p1: str, p2: ClassLoader, p3: bool) -> None: ...
    @overload
    def __init__(self, p0: str, p1: str, p2: ClassLoader) -> None: ...
    @overload
    def __init__(self, p0: str, p1: ClassLoader) -> None: ...
    def getResource(self, p0: str) -> URL: ...
    def getResources(self, p0: str) -> Enumeration: ...
