from typing import Any, ClassVar, overload

class CloseGuard:
    def __init__(self) -> None: ...
    def warnIfOpen(self) -> None: ...
    def close(self) -> None: ...
    def open(self, p0: str) -> None: ...
