from typing import Any, ClassVar, overload
from java.io.InputStream import InputStream

class WebResourceResponse:
    @overload
    def __init__(self, p0: str, p1: str, p2: int, p3: str, p4: dict, p5: InputStream) -> None: ...
    @overload
    def __init__(self, p0: str, p1: str, p2: InputStream) -> None: ...
    def setStatusCodeAndReasonPhrase(self, p0: int, p1: str) -> None: ...
    def getReasonPhrase(self) -> str: ...
    def getResponseHeaders(self) -> dict: ...
    def getStatusCode(self) -> int: ...
    def setEncoding(self, p0: str) -> None: ...
    def setMimeType(self, p0: str) -> None: ...
    def setResponseHeaders(self, p0: dict) -> None: ...
    def getEncoding(self) -> str: ...
    def getData(self) -> InputStream: ...
    def getMimeType(self) -> str: ...
    def setData(self, p0: InputStream) -> None: ...

from typing import Any, ClassVar, overload
from android.os.Handler import Handler
from android.webkit.WebMessage import WebMessage

class WebMessagePort:
    def postMessage(self, p0: WebMessage) -> None: ...
    @overload
    def setWebMessageCallback(self, p0: Any) -> None: ...
    @overload
    def setWebMessageCallback(self, p0: Any, p1: Handler) -> None: ...
    def close(self) -> None: ...

    class WebMessageCallback:
        def __init__(self) -> None: ...
        def onMessage(self, p0: "WebMessagePort", p1: WebMessage) -> None: ...

from typing import Any, ClassVar, overload
from android.content.Context import Context
from android.view.View import View

class PluginStub:
    def getEmbeddedView(self, p0: int, p1: Context) -> View: ...
    def getFullScreenView(self, p0: int, p1: Context) -> View: ...

from typing import Any, ClassVar, overload
from android.webkit.WebView import WebView
from android.webkit.WebViewRenderProcess import WebViewRenderProcess

class WebViewRenderProcessClient:
    def __init__(self) -> None: ...
    def onRenderProcessResponsive(self, p0: WebView, p1: WebViewRenderProcess) -> None: ...
    def onRenderProcessUnresponsive(self, p0: WebView, p1: WebViewRenderProcess) -> None: ...

from typing import Any, ClassVar, overload

class SafeBrowsingResponse:
    def __init__(self) -> None: ...
    def backToSafety(self, p0: bool) -> None: ...
    def proceed(self, p0: bool) -> None: ...
    def showInterstitial(self, p0: bool) -> None: ...

from typing import Any, ClassVar, overload
from android.net.Uri import Uri

class PermissionRequest:
    RESOURCE_AUDIO_CAPTURE: ClassVar[str]
    RESOURCE_MIDI_SYSEX: ClassVar[str]
    RESOURCE_PROTECTED_MEDIA_ID: ClassVar[str]
    RESOURCE_VIDEO_CAPTURE: ClassVar[str]
    def __init__(self) -> None: ...
    def grant(self, p0: Any) -> None: ...
    def deny(self) -> None: ...
    def getOrigin(self) -> Uri: ...
    def getResources(self) -> Any: ...

from typing import Any, ClassVar, overload

class ValueCallback:
    def onReceiveValue(self, p0: Any) -> None: ...

from typing import Any, ClassVar, overload
from android.net.Uri import Uri

class WebResourceRequest:
    def hasGesture(self) -> bool: ...
    def isForMainFrame(self) -> bool: ...
    def isRedirect(self) -> bool: ...
    def getRequestHeaders(self) -> dict: ...
    def getMethod(self) -> str: ...
    def getUrl(self) -> Uri: ...

from typing import Any, ClassVar, overload
from android.graphics.Bitmap import Bitmap

class WebIconDatabase:
    def __init__(self) -> None: ...
    def releaseIconForPageUrl(self, p0: str) -> None: ...
    def removeAllIcons(self) -> None: ...
    def requestIconForPageUrl(self, p0: str, p1: Any) -> None: ...
    def retainIconForPageUrl(self, p0: str) -> None: ...
    @staticmethod
    def getInstance() -> "WebIconDatabase": ...
    def close(self) -> None: ...
    def open(self, p0: str) -> None: ...

    class IconListener:
        def onReceivedIcon(self, p0: str, p1: Bitmap) -> None: ...

from typing import Any, ClassVar, overload
from android.webkit.ValueCallback import ValueCallback
from android.webkit.WebView import WebView

class CookieManager:
    def __init__(self) -> None: ...
    def flush(self) -> None: ...
    @staticmethod
    def getInstance() -> "CookieManager": ...
    def acceptCookie(self) -> bool: ...
    def acceptThirdPartyCookies(self, p0: WebView) -> bool: ...
    @staticmethod
    def allowFileSchemeCookies() -> bool: ...
    def getCookie(self, p0: str) -> str: ...
    def hasCookies(self) -> bool: ...
    def removeAllCookie(self) -> None: ...
    def removeAllCookies(self, p0: ValueCallback) -> None: ...
    def removeExpiredCookie(self) -> None: ...
    def removeSessionCookie(self) -> None: ...
    def removeSessionCookies(self, p0: ValueCallback) -> None: ...
    def setAcceptCookie(self, p0: bool) -> None: ...
    @staticmethod
    def setAcceptFileSchemeCookies(p0: bool) -> None: ...
    def setAcceptThirdPartyCookies(self, p0: WebView, p1: bool) -> None: ...
    @overload
    def setCookie(self, p0: str, p1: str, p2: ValueCallback) -> None: ...
    @overload
    def setCookie(self, p0: str, p1: str) -> None: ...

from typing import Any, ClassVar, overload
from java.security.PrivateKey import PrivateKey

class ClientCertRequest:
    def __init__(self) -> None: ...
    def proceed(self, p0: PrivateKey, p1: Any) -> None: ...
    def ignore(self) -> None: ...
    def getPrincipals(self) -> Any: ...
    def cancel(self) -> None: ...
    def getKeyTypes(self) -> Any: ...
    def getHost(self) -> str: ...
    def getPort(self) -> int: ...

from typing import Any, ClassVar, overload

class RenderProcessGoneDetail:
    def __init__(self) -> None: ...
    def rendererPriorityAtExit(self) -> int: ...
    def didCrash(self) -> bool: ...

from typing import Any, ClassVar, overload
from android.content.Context import Context

class DateSorter:
    DAY_COUNT: ClassVar[int]
    def __init__(self, p0: Context) -> None: ...
    def getIndex(self, p0: int) -> int: ...
    def getLabel(self, p0: int) -> str: ...
    def getBoundary(self, p0: int) -> int: ...

from typing import Any, ClassVar, overload
from android.content.Context import Context
from android.content.pm.PackageInfo import PackageInfo
from android.graphics.Bitmap import Bitmap
from android.graphics.Paint import Paint
from android.graphics.Picture import Picture
from android.graphics.Rect import Rect
from android.net.Uri import Uri
from android.net.http.SslCertificate import SslCertificate
from android.os.Bundle import Bundle
from android.os.Handler import Handler
from android.os.Looper import Looper
from android.os.Message import Message
from android.print.PrintDocumentAdapter import PrintDocumentAdapter
from android.util.AttributeSet import AttributeSet
from android.util.LongSparseArray import LongSparseArray
from android.util.Property import Property
from android.util.SparseArray import SparseArray
from android.view.DragEvent import DragEvent
from android.view.KeyEvent import KeyEvent
from android.view.MotionEvent import MotionEvent
from android.view.PointerIcon import PointerIcon
from android.view.View import View
from android.view.ViewStructure import ViewStructure
from android.view.WindowInsets import WindowInsets
from android.view.accessibility.AccessibilityNodeProvider import AccessibilityNodeProvider
from android.view.inputmethod.EditorInfo import EditorInfo
from android.view.inputmethod.InputConnection import InputConnection
from android.view.textclassifier.TextClassifier import TextClassifier
from android.view.translation.TranslationCapability import TranslationCapability
from android.webkit.DownloadListener import DownloadListener
from android.webkit.ValueCallback import ValueCallback
from android.webkit.WebBackForwardList import WebBackForwardList
from android.webkit.WebChromeClient import WebChromeClient
from android.webkit.WebMessage import WebMessage
from android.webkit.WebSettings import WebSettings
from android.webkit.WebViewClient import WebViewClient
from android.webkit.WebViewRenderProcess import WebViewRenderProcess
from android.webkit.WebViewRenderProcessClient import WebViewRenderProcessClient
from java.lang.ClassLoader import ClassLoader
from java.lang.Runnable import Runnable
from java.util.concurrent.Executor import Executor
from java.util.function.Consumer import Consumer

class WebView:
    RENDERER_PRIORITY_BOUND: ClassVar[int]
    RENDERER_PRIORITY_IMPORTANT: ClassVar[int]
    RENDERER_PRIORITY_WAIVED: ClassVar[int]
    SCHEME_GEO: ClassVar[str]
    SCHEME_MAILTO: ClassVar[str]
    SCHEME_TEL: ClassVar[str]
    FOCUS_AFTER_DESCENDANTS: ClassVar[int]
    FOCUS_BEFORE_DESCENDANTS: ClassVar[int]
    FOCUS_BLOCK_DESCENDANTS: ClassVar[int]
    LAYOUT_MODE_CLIP_BOUNDS: ClassVar[int]
    LAYOUT_MODE_OPTICAL_BOUNDS: ClassVar[int]
    PERSISTENT_ALL_CACHES: ClassVar[int]
    PERSISTENT_ANIMATION_CACHE: ClassVar[int]
    PERSISTENT_NO_CACHE: ClassVar[int]
    PERSISTENT_SCROLLING_CACHE: ClassVar[int]
    ACCESSIBILITY_DATA_SENSITIVE_AUTO: ClassVar[int]
    ACCESSIBILITY_DATA_SENSITIVE_NO: ClassVar[int]
    ACCESSIBILITY_DATA_SENSITIVE_YES: ClassVar[int]
    ACCESSIBILITY_LIVE_REGION_ASSERTIVE: ClassVar[int]
    ACCESSIBILITY_LIVE_REGION_NONE: ClassVar[int]
    ACCESSIBILITY_LIVE_REGION_POLITE: ClassVar[int]
    ALPHA: ClassVar[Property]
    AUTOFILL_FLAG_INCLUDE_NOT_IMPORTANT_VIEWS: ClassVar[int]
    AUTOFILL_HINT_CREDIT_CARD_EXPIRATION_DATE: ClassVar[str]
    AUTOFILL_HINT_CREDIT_CARD_EXPIRATION_DAY: ClassVar[str]
    AUTOFILL_HINT_CREDIT_CARD_EXPIRATION_MONTH: ClassVar[str]
    AUTOFILL_HINT_CREDIT_CARD_EXPIRATION_YEAR: ClassVar[str]
    AUTOFILL_HINT_CREDIT_CARD_NUMBER: ClassVar[str]
    AUTOFILL_HINT_CREDIT_CARD_SECURITY_CODE: ClassVar[str]
    AUTOFILL_HINT_EMAIL_ADDRESS: ClassVar[str]
    AUTOFILL_HINT_NAME: ClassVar[str]
    AUTOFILL_HINT_PASSWORD: ClassVar[str]
    AUTOFILL_HINT_PHONE: ClassVar[str]
    AUTOFILL_HINT_POSTAL_ADDRESS: ClassVar[str]
    AUTOFILL_HINT_POSTAL_CODE: ClassVar[str]
    AUTOFILL_HINT_USERNAME: ClassVar[str]
    AUTOFILL_TYPE_DATE: ClassVar[int]
    AUTOFILL_TYPE_LIST: ClassVar[int]
    AUTOFILL_TYPE_NONE: ClassVar[int]
    AUTOFILL_TYPE_TEXT: ClassVar[int]
    AUTOFILL_TYPE_TOGGLE: ClassVar[int]
    CONTENT_SENSITIVITY_AUTO: ClassVar[int]
    CONTENT_SENSITIVITY_NOT_SENSITIVE: ClassVar[int]
    CONTENT_SENSITIVITY_SENSITIVE: ClassVar[int]
    DRAG_FLAG_ACCESSIBILITY_ACTION: ClassVar[int]
    DRAG_FLAG_GLOBAL: ClassVar[int]
    DRAG_FLAG_GLOBAL_PERSISTABLE_URI_PERMISSION: ClassVar[int]
    DRAG_FLAG_GLOBAL_PREFIX_URI_PERMISSION: ClassVar[int]
    DRAG_FLAG_GLOBAL_SAME_APPLICATION: ClassVar[int]
    DRAG_FLAG_GLOBAL_URI_READ: ClassVar[int]
    DRAG_FLAG_GLOBAL_URI_WRITE: ClassVar[int]
    DRAG_FLAG_HIDE_CALLING_TASK_ON_DRAG_START: ClassVar[int]
    DRAG_FLAG_OPAQUE: ClassVar[int]
    DRAG_FLAG_START_INTENT_SENDER_ON_UNHANDLED_DRAG: ClassVar[int]
    DRAWING_CACHE_QUALITY_AUTO: ClassVar[int]
    DRAWING_CACHE_QUALITY_HIGH: ClassVar[int]
    DRAWING_CACHE_QUALITY_LOW: ClassVar[int]
    FIND_VIEWS_WITH_CONTENT_DESCRIPTION: ClassVar[int]
    FIND_VIEWS_WITH_TEXT: ClassVar[int]
    FOCUSABLE: ClassVar[int]
    FOCUSABLES_ALL: ClassVar[int]
    FOCUSABLES_TOUCH_MODE: ClassVar[int]
    FOCUSABLE_AUTO: ClassVar[int]
    FOCUS_BACKWARD: ClassVar[int]
    FOCUS_DOWN: ClassVar[int]
    FOCUS_FORWARD: ClassVar[int]
    FOCUS_LEFT: ClassVar[int]
    FOCUS_RIGHT: ClassVar[int]
    FOCUS_UP: ClassVar[int]
    GONE: ClassVar[int]
    HAPTIC_FEEDBACK_ENABLED: ClassVar[int]
    IMPORTANT_FOR_ACCESSIBILITY_AUTO: ClassVar[int]
    IMPORTANT_FOR_ACCESSIBILITY_NO: ClassVar[int]
    IMPORTANT_FOR_ACCESSIBILITY_NO_HIDE_DESCENDANTS: ClassVar[int]
    IMPORTANT_FOR_ACCESSIBILITY_YES: ClassVar[int]
    IMPORTANT_FOR_AUTOFILL_AUTO: ClassVar[int]
    IMPORTANT_FOR_AUTOFILL_NO: ClassVar[int]
    IMPORTANT_FOR_AUTOFILL_NO_EXCLUDE_DESCENDANTS: ClassVar[int]
    IMPORTANT_FOR_AUTOFILL_YES: ClassVar[int]
    IMPORTANT_FOR_AUTOFILL_YES_EXCLUDE_DESCENDANTS: ClassVar[int]
    IMPORTANT_FOR_CONTENT_CAPTURE_AUTO: ClassVar[int]
    IMPORTANT_FOR_CONTENT_CAPTURE_NO: ClassVar[int]
    IMPORTANT_FOR_CONTENT_CAPTURE_NO_EXCLUDE_DESCENDANTS: ClassVar[int]
    IMPORTANT_FOR_CONTENT_CAPTURE_YES: ClassVar[int]
    IMPORTANT_FOR_CONTENT_CAPTURE_YES_EXCLUDE_DESCENDANTS: ClassVar[int]
    INVISIBLE: ClassVar[int]
    KEEP_SCREEN_ON: ClassVar[int]
    LAYER_TYPE_HARDWARE: ClassVar[int]
    LAYER_TYPE_NONE: ClassVar[int]
    LAYER_TYPE_SOFTWARE: ClassVar[int]
    LAYOUT_DIRECTION_INHERIT: ClassVar[int]
    LAYOUT_DIRECTION_LOCALE: ClassVar[int]
    LAYOUT_DIRECTION_LTR: ClassVar[int]
    LAYOUT_DIRECTION_RTL: ClassVar[int]
    MEASURED_HEIGHT_STATE_SHIFT: ClassVar[int]
    MEASURED_SIZE_MASK: ClassVar[int]
    MEASURED_STATE_MASK: ClassVar[int]
    MEASURED_STATE_TOO_SMALL: ClassVar[int]
    NOT_FOCUSABLE: ClassVar[int]
    NO_ID: ClassVar[int]
    OVER_SCROLL_ALWAYS: ClassVar[int]
    OVER_SCROLL_IF_CONTENT_SCROLLS: ClassVar[int]
    OVER_SCROLL_NEVER: ClassVar[int]
    REQUESTED_FRAME_RATE_CATEGORY_DEFAULT: ClassVar[float]
    REQUESTED_FRAME_RATE_CATEGORY_HIGH: ClassVar[float]
    REQUESTED_FRAME_RATE_CATEGORY_LOW: ClassVar[float]
    REQUESTED_FRAME_RATE_CATEGORY_NORMAL: ClassVar[float]
    REQUESTED_FRAME_RATE_CATEGORY_NO_PREFERENCE: ClassVar[float]
    ROTATION: ClassVar[Property]
    ROTATION_X: ClassVar[Property]
    ROTATION_Y: ClassVar[Property]
    SCALE_X: ClassVar[Property]
    SCALE_Y: ClassVar[Property]
    SCREEN_STATE_OFF: ClassVar[int]
    SCREEN_STATE_ON: ClassVar[int]
    SCROLLBARS_INSIDE_INSET: ClassVar[int]
    SCROLLBARS_INSIDE_OVERLAY: ClassVar[int]
    SCROLLBARS_OUTSIDE_INSET: ClassVar[int]
    SCROLLBARS_OUTSIDE_OVERLAY: ClassVar[int]
    SCROLLBAR_POSITION_DEFAULT: ClassVar[int]
    SCROLLBAR_POSITION_LEFT: ClassVar[int]
    SCROLLBAR_POSITION_RIGHT: ClassVar[int]
    SCROLL_AXIS_HORIZONTAL: ClassVar[int]
    SCROLL_AXIS_NONE: ClassVar[int]
    SCROLL_AXIS_VERTICAL: ClassVar[int]
    SCROLL_CAPTURE_HINT_AUTO: ClassVar[int]
    SCROLL_CAPTURE_HINT_EXCLUDE: ClassVar[int]
    SCROLL_CAPTURE_HINT_EXCLUDE_DESCENDANTS: ClassVar[int]
    SCROLL_CAPTURE_HINT_INCLUDE: ClassVar[int]
    SCROLL_INDICATOR_BOTTOM: ClassVar[int]
    SCROLL_INDICATOR_END: ClassVar[int]
    SCROLL_INDICATOR_LEFT: ClassVar[int]
    SCROLL_INDICATOR_RIGHT: ClassVar[int]
    SCROLL_INDICATOR_START: ClassVar[int]
    SCROLL_INDICATOR_TOP: ClassVar[int]
    SOUND_EFFECTS_ENABLED: ClassVar[int]
    STATUS_BAR_HIDDEN: ClassVar[int]
    STATUS_BAR_VISIBLE: ClassVar[int]
    SYSTEM_UI_FLAG_FULLSCREEN: ClassVar[int]
    SYSTEM_UI_FLAG_HIDE_NAVIGATION: ClassVar[int]
    SYSTEM_UI_FLAG_IMMERSIVE: ClassVar[int]
    SYSTEM_UI_FLAG_IMMERSIVE_STICKY: ClassVar[int]
    SYSTEM_UI_FLAG_LAYOUT_FULLSCREEN: ClassVar[int]
    SYSTEM_UI_FLAG_LAYOUT_HIDE_NAVIGATION: ClassVar[int]
    SYSTEM_UI_FLAG_LAYOUT_STABLE: ClassVar[int]
    SYSTEM_UI_FLAG_LIGHT_NAVIGATION_BAR: ClassVar[int]
    SYSTEM_UI_FLAG_LIGHT_STATUS_BAR: ClassVar[int]
    SYSTEM_UI_FLAG_LOW_PROFILE: ClassVar[int]
    SYSTEM_UI_FLAG_VISIBLE: ClassVar[int]
    SYSTEM_UI_LAYOUT_FLAGS: ClassVar[int]
    TEXT_ALIGNMENT_CENTER: ClassVar[int]
    TEXT_ALIGNMENT_GRAVITY: ClassVar[int]
    TEXT_ALIGNMENT_INHERIT: ClassVar[int]
    TEXT_ALIGNMENT_TEXT_END: ClassVar[int]
    TEXT_ALIGNMENT_TEXT_START: ClassVar[int]
    TEXT_ALIGNMENT_VIEW_END: ClassVar[int]
    TEXT_ALIGNMENT_VIEW_START: ClassVar[int]
    TEXT_DIRECTION_ANY_RTL: ClassVar[int]
    TEXT_DIRECTION_FIRST_STRONG: ClassVar[int]
    TEXT_DIRECTION_FIRST_STRONG_LTR: ClassVar[int]
    TEXT_DIRECTION_FIRST_STRONG_RTL: ClassVar[int]
    TEXT_DIRECTION_INHERIT: ClassVar[int]
    TEXT_DIRECTION_LOCALE: ClassVar[int]
    TEXT_DIRECTION_LTR: ClassVar[int]
    TEXT_DIRECTION_RTL: ClassVar[int]
    TRANSLATION_X: ClassVar[Property]
    TRANSLATION_Y: ClassVar[Property]
    TRANSLATION_Z: ClassVar[Property]
    VISIBLE: ClassVar[int]
    X: ClassVar[Property]
    Y: ClassVar[Property]
    Z: ClassVar[Property]
    @overload
    def __init__(self, p0: Context, p1: AttributeSet, p2: int, p3: int) -> None: ...
    @overload
    def __init__(self, p0: Context, p1: AttributeSet, p2: int, p3: bool) -> None: ...
    @overload
    def __init__(self, p0: Context, p1: AttributeSet, p2: int) -> None: ...
    @overload
    def __init__(self, p0: Context, p1: AttributeSet) -> None: ...
    @overload
    def __init__(self, p0: Context) -> None: ...
    def destroy(self) -> None: ...
    def findAll(self, p0: str) -> int: ...
    def getTextClassifier(self) -> TextClassifier: ...
    def setTextClassifier(self, p0: TextClassifier) -> None: ...
    def getTitle(self) -> str: ...
    def requestChildRectangleOnScreen(self, p0: View, p1: Rect, p2: bool) -> bool: ...
    def shouldDelayChildPressedState(self) -> bool: ...
    def getProgress(self) -> int: ...
    def onPause(self) -> None: ...
    def onResume(self) -> None: ...
    @staticmethod
    def getCurrentWebViewPackage() -> PackageInfo: ...
    def getFavicon(self) -> Bitmap: ...
    def getHitTestResult(self) -> Any: ...
    def getHttpAuthUsernamePassword(self, p0: str, p1: str) -> Any: ...
    def getOriginalUrl(self) -> str: ...
    def getRendererPriorityWaivedWhenNotVisible(self) -> bool: ...
    def getRendererRequestedPriority(self) -> int: ...
    @staticmethod
    def getSafeBrowsingPrivacyPolicyUrl() -> Uri: ...
    def getScale(self) -> float: ...
    def getSettings(self) -> WebSettings: ...
    def getWebChromeClient(self) -> WebChromeClient: ...
    @staticmethod
    def getWebViewClassLoader() -> ClassLoader: ...
    def getWebViewClient(self) -> WebViewClient: ...
    def getWebViewLooper(self) -> Looper: ...
    def getWebViewRenderProcess(self) -> WebViewRenderProcess: ...
    def goBack(self) -> None: ...
    def addJavascriptInterface(self, p0: Any, p1: str) -> None: ...
    def canGoBack(self) -> bool: ...
    def canGoBackOrForward(self, p0: int) -> bool: ...
    def canGoForward(self) -> bool: ...
    def canZoomIn(self) -> bool: ...
    def canZoomOut(self) -> bool: ...
    def capturePicture(self) -> Picture: ...
    def clearCache(self, p0: bool) -> None: ...
    @staticmethod
    def clearClientCertPreferences(p0: Runnable) -> None: ...
    def clearFormData(self) -> None: ...
    def clearHistory(self) -> None: ...
    def clearMatches(self) -> None: ...
    def clearSslPreferences(self) -> None: ...
    def clearView(self) -> None: ...
    def copyBackForwardList(self) -> WebBackForwardList: ...
    @overload
    def createPrintDocumentAdapter(self) -> PrintDocumentAdapter: ...
    @overload
    def createPrintDocumentAdapter(self, p0: str) -> PrintDocumentAdapter: ...
    def createWebMessageChannel(self) -> Any: ...
    @staticmethod
    def disableWebView() -> None: ...
    def documentHasImages(self, p0: Message) -> None: ...
    @staticmethod
    def enableSlowWholeDocumentDraw() -> None: ...
    def evaluateJavascript(self, p0: str, p1: ValueCallback) -> None: ...
    @staticmethod
    def findAddress(p0: str) -> str: ...
    def findAllAsync(self, p0: str) -> None: ...
    def findNext(self, p0: bool) -> None: ...
    def flingScroll(self, p0: int, p1: int) -> None: ...
    def getCertificate(self) -> SslCertificate: ...
    def getContentHeight(self) -> int: ...
    def getUrl(self) -> str: ...
    def getWebViewRenderProcessClient(self) -> WebViewRenderProcessClient: ...
    def goBackOrForward(self, p0: int) -> None: ...
    def goForward(self) -> None: ...
    def invokeZoomPicker(self) -> None: ...
    def isPrivateBrowsingEnabled(self) -> bool: ...
    def loadData(self, p0: str, p1: str, p2: str) -> None: ...
    def loadDataWithBaseURL(self, p0: str, p1: str, p2: str, p3: str, p4: str) -> None: ...
    @overload
    def loadUrl(self, p0: str) -> None: ...
    @overload
    def loadUrl(self, p0: str, p1: dict) -> None: ...
    def onGlobalFocusChanged(self, p0: View, p1: View) -> None: ...
    def overlayHorizontalScrollbar(self) -> bool: ...
    def overlayVerticalScrollbar(self) -> bool: ...
    def pageDown(self, p0: bool) -> bool: ...
    def pageUp(self, p0: bool) -> bool: ...
    def pauseTimers(self) -> None: ...
    def postUrl(self, p0: str, p1: Any) -> None: ...
    def postVisualStateCallback(self, p0: int, p1: Any) -> None: ...
    def postWebMessage(self, p0: WebMessage, p1: Uri) -> None: ...
    def reload(self) -> None: ...
    def removeJavascriptInterface(self, p0: str) -> None: ...
    def requestFocusNodeHref(self, p0: Message) -> None: ...
    def requestImageRef(self, p0: Message) -> None: ...
    def restoreState(self, p0: Bundle) -> WebBackForwardList: ...
    def resumeTimers(self) -> None: ...
    def savePassword(self, p0: str, p1: str, p2: str) -> None: ...
    def saveState(self, p0: Bundle) -> WebBackForwardList: ...
    @overload
    def saveWebArchive(self, p0: str) -> None: ...
    @overload
    def saveWebArchive(self, p0: str, p1: bool, p2: ValueCallback) -> None: ...
    def setCertificate(self, p0: SslCertificate) -> None: ...
    @staticmethod
    def setDataDirectorySuffix(p0: str) -> None: ...
    def setDownloadListener(self, p0: DownloadListener) -> None: ...
    def setFindListener(self, p0: Any) -> None: ...
    def setHorizontalScrollbarOverlay(self, p0: bool) -> None: ...
    def setHttpAuthUsernamePassword(self, p0: str, p1: str, p2: str, p3: str) -> None: ...
    def setInitialScale(self, p0: int) -> None: ...
    def setMapTrackballToArrowKeys(self, p0: bool) -> None: ...
    def setNetworkAvailable(self, p0: bool) -> None: ...
    def setPictureListener(self, p0: Any) -> None: ...
    def setRendererPriorityPolicy(self, p0: int, p1: bool) -> None: ...
    @staticmethod
    def setSafeBrowsingWhitelist(p0: list, p1: ValueCallback) -> None: ...
    def setVerticalScrollbarOverlay(self, p0: bool) -> None: ...
    def setWebChromeClient(self, p0: WebChromeClient) -> None: ...
    @staticmethod
    def setWebContentsDebuggingEnabled(p0: bool) -> None: ...
    def setWebViewClient(self, p0: WebViewClient) -> None: ...
    @overload
    def setWebViewRenderProcessClient(self, p0: WebViewRenderProcessClient) -> None: ...
    @overload
    def setWebViewRenderProcessClient(self, p0: Executor, p1: WebViewRenderProcessClient) -> None: ...
    def showFindDialog(self, p0: str, p1: bool) -> bool: ...
    @staticmethod
    def startSafeBrowsing(p0: Context, p1: ValueCallback) -> None: ...
    def zoomBy(self, p0: float) -> None: ...
    def zoomIn(self) -> bool: ...
    def zoomOut(self) -> bool: ...
    def getAccessibilityClassName(self) -> str: ...
    def onKeyUp(self, p0: int, p1: KeyEvent) -> bool: ...
    def onTouchEvent(self, p0: MotionEvent) -> bool: ...
    def isVisibleToUserForAutofill(self, p0: int) -> bool: ...
    def onApplyWindowInsets(self, p0: WindowInsets) -> WindowInsets: ...
    def onCheckIsTextEditor(self) -> bool: ...
    def onCreateInputConnection(self, p0: EditorInfo) -> InputConnection: ...
    def onCreateVirtualViewTranslationRequests(self, p0: Any, p1: Any, p2: Consumer) -> None: ...
    def onDragEvent(self, p0: DragEvent) -> bool: ...
    def onFinishTemporaryDetach(self) -> None: ...
    def onGenericMotionEvent(self, p0: MotionEvent) -> bool: ...
    def onHoverEvent(self, p0: MotionEvent) -> bool: ...
    def onKeyDown(self, p0: int, p1: KeyEvent) -> bool: ...
    def onKeyMultiple(self, p0: int, p1: int, p2: KeyEvent) -> bool: ...
    def onProvideAutofillVirtualStructure(self, p0: ViewStructure, p1: int) -> None: ...
    def onProvideContentCaptureStructure(self, p0: ViewStructure, p1: int) -> None: ...
    def onProvideVirtualStructure(self, p0: ViewStructure) -> None: ...
    def onStartTemporaryDetach(self) -> None: ...
    def onTrackballEvent(self, p0: MotionEvent) -> bool: ...
    def onVirtualViewTranslationResponses(self, p0: LongSparseArray) -> None: ...
    def onWindowFocusChanged(self, p0: bool) -> None: ...
    def performLongClick(self) -> bool: ...
    def requestFocus(self, p0: int, p1: Rect) -> bool: ...
    def setBackgroundColor(self, p0: int) -> None: ...
    def setLayerType(self, p0: int, p1: Paint) -> None: ...
    def setLayoutParams(self, p0: Any) -> None: ...
    def setOverScrollMode(self, p0: int) -> None: ...
    def setScrollBarStyle(self, p0: int) -> None: ...
    def onResolvePointerIcon(self, p0: MotionEvent, p1: int) -> PointerIcon: ...
    def onChildViewAdded(self, p0: View, p1: View) -> None: ...
    def onChildViewRemoved(self, p0: View, p1: View) -> None: ...
    def stopLoading(self) -> None: ...
    def autofill(self, p0: SparseArray) -> None: ...
    def computeScroll(self) -> None: ...
    def dispatchCreateViewTranslationRequest(self, p0: dict, p1: Any, p2: TranslationCapability, p3: list) -> None: ...
    def dispatchKeyEvent(self, p0: KeyEvent) -> bool: ...
    def findFocus(self) -> View: ...
    def getAccessibilityNodeProvider(self) -> AccessibilityNodeProvider: ...
    def freeMemory(self) -> None: ...
    def getHandler(self) -> Handler: ...

    class WebViewTransport:
        def __init__(self, p0: "WebView") -> None: ...
        def getWebView(self) -> "WebView": ...
        def setWebView(self, p0: "WebView") -> None: ...

    class VisualStateCallback:
        def __init__(self) -> None: ...
        def onComplete(self, p0: int) -> None: ...

    class PictureListener:
        def onNewPicture(self, p0: "WebView", p1: Picture) -> None: ...

    class HitTestResult:
        ANCHOR_TYPE: ClassVar[int]
        EDIT_TEXT_TYPE: ClassVar[int]
        EMAIL_TYPE: ClassVar[int]
        GEO_TYPE: ClassVar[int]
        IMAGE_ANCHOR_TYPE: ClassVar[int]
        IMAGE_TYPE: ClassVar[int]
        PHONE_TYPE: ClassVar[int]
        SRC_ANCHOR_TYPE: ClassVar[int]
        SRC_IMAGE_ANCHOR_TYPE: ClassVar[int]
        UNKNOWN_TYPE: ClassVar[int]
        def getType(self) -> int: ...
        def getExtra(self) -> str: ...

    class FindListener:
        def onFindResultReceived(self, p0: int, p1: int, p2: bool) -> None: ...

from typing import Any, ClassVar, overload

class ServiceWorkerWebSettings:
    def __init__(self) -> None: ...
    def getAllowContentAccess(self) -> bool: ...
    def getAllowFileAccess(self) -> bool: ...
    def getBlockNetworkLoads(self) -> bool: ...
    def getCacheMode(self) -> int: ...
    def setAllowContentAccess(self, p0: bool) -> None: ...
    def setAllowFileAccess(self, p0: bool) -> None: ...
    def setBlockNetworkLoads(self, p0: bool) -> None: ...
    def setCacheMode(self, p0: int) -> None: ...

from typing import Any, ClassVar, overload

class WebViewRenderProcess:
    def __init__(self) -> None: ...
    def terminate(self) -> bool: ...

from typing import Any, ClassVar, overload
from android.graphics.Bitmap import Bitmap

class WebHistoryItem:
    def __init__(self) -> None: ...
    def getTitle(self) -> str: ...
    def getFavicon(self) -> Bitmap: ...
    def getOriginalUrl(self) -> str: ...
    def getUrl(self) -> str: ...

from typing import Any, ClassVar, overload
from android.content.Context import Context

class CookieSyncManager:
    def run(self) -> None: ...
    @staticmethod
    def getInstance() -> "CookieSyncManager": ...
    def sync(self) -> None: ...
    @staticmethod
    def createInstance(p0: Context) -> "CookieSyncManager": ...
    def resetSync(self) -> None: ...
    def stopSync(self) -> None: ...
    def startSync(self) -> None: ...

from typing import Any, ClassVar, overload

class WebMessage:
    @overload
    def __init__(self, p0: str) -> None: ...
    @overload
    def __init__(self, p0: str, p1: Any) -> None: ...
    def getData(self) -> str: ...
    def getPorts(self) -> Any: ...

from typing import Any, ClassVar, overload
from android.webkit.ServiceWorkerClient import ServiceWorkerClient
from android.webkit.ServiceWorkerWebSettings import ServiceWorkerWebSettings

class ServiceWorkerController:
    def __init__(self) -> None: ...
    def setServiceWorkerClient(self, p0: ServiceWorkerClient) -> None: ...
    def getServiceWorkerWebSettings(self) -> ServiceWorkerWebSettings: ...
    @staticmethod
    def getInstance() -> "ServiceWorkerController": ...

from typing import Any, ClassVar, overload

class SslErrorHandler:
    def proceed(self) -> None: ...
    def cancel(self) -> None: ...

from typing import Any, ClassVar, overload

class JavascriptInterface:
    ...

from typing import Any, ClassVar, overload
from android.webkit.WebResourceRequest import WebResourceRequest
from android.webkit.WebResourceResponse import WebResourceResponse

class ServiceWorkerClient:
    def __init__(self) -> None: ...
    def shouldInterceptRequest(self, p0: WebResourceRequest) -> WebResourceResponse: ...

from typing import Any, ClassVar, overload
from android.webkit.WebHistoryItem import WebHistoryItem

class WebBackForwardList:
    def __init__(self) -> None: ...
    def getCurrentIndex(self) -> int: ...
    def getCurrentItem(self) -> WebHistoryItem: ...
    def getItemAtIndex(self, p0: int) -> WebHistoryItem: ...
    def getSize(self) -> int: ...

from typing import Any, ClassVar, overload

class MimeTypeMap:
    def getExtensionFromMimeType(self, p0: str) -> str: ...
    @staticmethod
    def getFileExtensionFromUrl(p0: str) -> str: ...
    def getMimeTypeFromExtension(self, p0: str) -> str: ...
    @staticmethod
    def getSingleton() -> "MimeTypeMap": ...
    def hasExtension(self, p0: str) -> bool: ...
    def hasMimeType(self, p0: str) -> bool: ...

from typing import Any, ClassVar, overload

class URLUtil:
    def __init__(self) -> None: ...
    @staticmethod
    def composeSearchUrl(p0: str, p1: str, p2: str) -> str: ...
    @staticmethod
    def guessFileName(p0: str, p1: str, p2: str) -> str: ...
    @staticmethod
    def guessUrl(p0: str) -> str: ...
    @staticmethod
    def isAboutUrl(p0: str) -> bool: ...
    @staticmethod
    def isAssetUrl(p0: str) -> bool: ...
    @staticmethod
    def isContentUrl(p0: str) -> bool: ...
    @staticmethod
    def isCookielessProxyUrl(p0: str) -> bool: ...
    @staticmethod
    def isDataUrl(p0: str) -> bool: ...
    @staticmethod
    def isFileUrl(p0: str) -> bool: ...
    @staticmethod
    def isHttpUrl(p0: str) -> bool: ...
    @staticmethod
    def isHttpsUrl(p0: str) -> bool: ...
    @staticmethod
    def isJavaScriptUrl(p0: str) -> bool: ...
    @staticmethod
    def isNetworkUrl(p0: str) -> bool: ...
    @staticmethod
    def isValidUrl(p0: str) -> bool: ...
    @staticmethod
    def stripAnchor(p0: str) -> str: ...
    @staticmethod
    def decode(p0: Any) -> Any: ...

from typing import Any, ClassVar, overload
from android.os.Bundle import Bundle
from android.view.LayoutInflater import LayoutInflater
from android.view.View import View
from android.view.ViewGroup import ViewGroup
from android.webkit.WebView import WebView

class WebViewFragment:
    TRIM_MEMORY_BACKGROUND: ClassVar[int]
    TRIM_MEMORY_COMPLETE: ClassVar[int]
    TRIM_MEMORY_MODERATE: ClassVar[int]
    TRIM_MEMORY_RUNNING_CRITICAL: ClassVar[int]
    TRIM_MEMORY_RUNNING_LOW: ClassVar[int]
    TRIM_MEMORY_RUNNING_MODERATE: ClassVar[int]
    TRIM_MEMORY_UI_HIDDEN: ClassVar[int]
    def __init__(self) -> None: ...
    def onDestroyView(self) -> None: ...
    def onDestroy(self) -> None: ...
    def onCreateView(self, p0: LayoutInflater, p1: ViewGroup, p2: Bundle) -> View: ...
    def onPause(self) -> None: ...
    def onResume(self) -> None: ...
    def getWebView(self) -> WebView: ...

from typing import Any, ClassVar, overload
from android.graphics.Bitmap import Bitmap
from android.net.http.SslError import SslError
from android.os.Message import Message
from android.view.KeyEvent import KeyEvent
from android.webkit.ClientCertRequest import ClientCertRequest
from android.webkit.HttpAuthHandler import HttpAuthHandler
from android.webkit.RenderProcessGoneDetail import RenderProcessGoneDetail
from android.webkit.SafeBrowsingResponse import SafeBrowsingResponse
from android.webkit.SslErrorHandler import SslErrorHandler
from android.webkit.WebResourceError import WebResourceError
from android.webkit.WebResourceRequest import WebResourceRequest
from android.webkit.WebResourceResponse import WebResourceResponse
from android.webkit.WebView import WebView

class WebViewClient:
    ERROR_AUTHENTICATION: ClassVar[int]
    ERROR_BAD_URL: ClassVar[int]
    ERROR_CONNECT: ClassVar[int]
    ERROR_FAILED_SSL_HANDSHAKE: ClassVar[int]
    ERROR_FILE: ClassVar[int]
    ERROR_FILE_NOT_FOUND: ClassVar[int]
    ERROR_HOST_LOOKUP: ClassVar[int]
    ERROR_IO: ClassVar[int]
    ERROR_PROXY_AUTHENTICATION: ClassVar[int]
    ERROR_REDIRECT_LOOP: ClassVar[int]
    ERROR_TIMEOUT: ClassVar[int]
    ERROR_TOO_MANY_REQUESTS: ClassVar[int]
    ERROR_UNKNOWN: ClassVar[int]
    ERROR_UNSAFE_RESOURCE: ClassVar[int]
    ERROR_UNSUPPORTED_AUTH_SCHEME: ClassVar[int]
    ERROR_UNSUPPORTED_SCHEME: ClassVar[int]
    SAFE_BROWSING_THREAT_BILLING: ClassVar[int]
    SAFE_BROWSING_THREAT_MALWARE: ClassVar[int]
    SAFE_BROWSING_THREAT_PHISHING: ClassVar[int]
    SAFE_BROWSING_THREAT_UNKNOWN: ClassVar[int]
    SAFE_BROWSING_THREAT_UNWANTED_SOFTWARE: ClassVar[int]
    def __init__(self) -> None: ...
    def doUpdateVisitedHistory(self, p0: WebView, p1: str, p2: bool) -> None: ...
    def onFormResubmission(self, p0: WebView, p1: Message, p2: Message) -> None: ...
    def onLoadResource(self, p0: WebView, p1: str) -> None: ...
    def onPageCommitVisible(self, p0: WebView, p1: str) -> None: ...
    def onPageFinished(self, p0: WebView, p1: str) -> None: ...
    def onPageStarted(self, p0: WebView, p1: str, p2: Bitmap) -> None: ...
    def onReceivedClientCertRequest(self, p0: WebView, p1: ClientCertRequest) -> None: ...
    @overload
    def onReceivedError(self, p0: WebView, p1: int, p2: str, p3: str) -> None: ...
    @overload
    def onReceivedError(self, p0: WebView, p1: WebResourceRequest, p2: WebResourceError) -> None: ...
    def onReceivedHttpAuthRequest(self, p0: WebView, p1: HttpAuthHandler, p2: str, p3: str) -> None: ...
    def onReceivedHttpError(self, p0: WebView, p1: WebResourceRequest, p2: WebResourceResponse) -> None: ...
    def onReceivedLoginRequest(self, p0: WebView, p1: str, p2: str, p3: str) -> None: ...
    def onReceivedSslError(self, p0: WebView, p1: SslErrorHandler, p2: SslError) -> None: ...
    def onRenderProcessGone(self, p0: WebView, p1: RenderProcessGoneDetail) -> bool: ...
    def onSafeBrowsingHit(self, p0: WebView, p1: WebResourceRequest, p2: int, p3: SafeBrowsingResponse) -> None: ...
    def onScaleChanged(self, p0: WebView, p1: float, p2: float) -> None: ...
    def onTooManyRedirects(self, p0: WebView, p1: Message, p2: Message) -> None: ...
    def onUnhandledKeyEvent(self, p0: WebView, p1: KeyEvent) -> None: ...
    @overload
    def shouldInterceptRequest(self, p0: WebView, p1: WebResourceRequest) -> WebResourceResponse: ...
    @overload
    def shouldInterceptRequest(self, p0: WebView, p1: str) -> WebResourceResponse: ...
    def shouldOverrideKeyEvent(self, p0: WebView, p1: KeyEvent) -> bool: ...
    @overload
    def shouldOverrideUrlLoading(self, p0: WebView, p1: WebResourceRequest) -> bool: ...
    @overload
    def shouldOverrideUrlLoading(self, p0: WebView, p1: str) -> bool: ...

from typing import Any, ClassVar, overload

class DownloadListener:
    def onDownloadStart(self, p0: str, p1: str, p2: str, p3: str, p4: int) -> None: ...

from typing import Any, ClassVar, overload
from android.webkit.TracingConfig import TracingConfig
from java.io.OutputStream import OutputStream
from java.util.concurrent.Executor import Executor

class TracingController:
    def __init__(self) -> None: ...
    def isTracing(self) -> bool: ...
    @staticmethod
    def getInstance() -> "TracingController": ...
    def start(self, p0: TracingConfig) -> None: ...
    def stop(self, p0: OutputStream, p1: Executor) -> bool: ...

from typing import Any, ClassVar, overload
from android.content.Context import Context

class WebViewDatabase:
    def __init__(self) -> None: ...
    def clearUsernamePassword(self) -> None: ...
    def clearHttpAuthUsernamePassword(self) -> None: ...
    def hasFormData(self) -> bool: ...
    def hasHttpAuthUsernamePassword(self) -> bool: ...
    def hasUsernamePassword(self) -> bool: ...
    @staticmethod
    def getInstance(p0: Context) -> "WebViewDatabase": ...
    def getHttpAuthUsernamePassword(self, p0: str, p1: str) -> Any: ...
    def clearFormData(self) -> None: ...
    def setHttpAuthUsernamePassword(self, p0: str, p1: str, p2: str, p3: str) -> None: ...

from typing import Any, ClassVar, overload

class TracingConfig:
    CATEGORIES_ALL: ClassVar[int]
    CATEGORIES_ANDROID_WEBVIEW: ClassVar[int]
    CATEGORIES_FRAME_VIEWER: ClassVar[int]
    CATEGORIES_INPUT_LATENCY: ClassVar[int]
    CATEGORIES_JAVASCRIPT_AND_RENDERING: ClassVar[int]
    CATEGORIES_NONE: ClassVar[int]
    CATEGORIES_RENDERING: ClassVar[int]
    CATEGORIES_WEB_DEVELOPER: ClassVar[int]
    RECORD_CONTINUOUSLY: ClassVar[int]
    RECORD_UNTIL_FULL: ClassVar[int]
    def getTracingMode(self) -> int: ...
    def getCustomIncludedCategories(self) -> list: ...
    def getPredefinedCategories(self) -> int: ...

    class Builder:
        def __init__(self) -> None: ...
        @overload
        def addCategories(self, p0: Any) -> Any: ...
        @overload
        def addCategories(self, p0: Any) -> Any: ...
        @overload
        def addCategories(self, p0: list) -> Any: ...
        def setTracingMode(self, p0: int) -> Any: ...
        def build(self) -> "TracingConfig": ...

from typing import Any, ClassVar, overload
from android.content.Context import Context

class WebSettings:
    FORCE_DARK_AUTO: ClassVar[int]
    FORCE_DARK_OFF: ClassVar[int]
    FORCE_DARK_ON: ClassVar[int]
    LOAD_CACHE_ELSE_NETWORK: ClassVar[int]
    LOAD_CACHE_ONLY: ClassVar[int]
    LOAD_DEFAULT: ClassVar[int]
    LOAD_NORMAL: ClassVar[int]
    LOAD_NO_CACHE: ClassVar[int]
    MENU_ITEM_NONE: ClassVar[int]
    MENU_ITEM_PROCESS_TEXT: ClassVar[int]
    MENU_ITEM_SHARE: ClassVar[int]
    MENU_ITEM_WEB_SEARCH: ClassVar[int]
    MIXED_CONTENT_ALWAYS_ALLOW: ClassVar[int]
    MIXED_CONTENT_COMPATIBILITY_MODE: ClassVar[int]
    MIXED_CONTENT_NEVER_ALLOW: ClassVar[int]
    def __init__(self) -> None: ...
    def getTextSize(self) -> Any: ...
    def setTextSize(self, p0: Any) -> None: ...
    def enableSmoothTransition(self) -> bool: ...
    def getAllowContentAccess(self) -> bool: ...
    def getAllowFileAccess(self) -> bool: ...
    def getAllowFileAccessFromFileURLs(self) -> bool: ...
    def getAllowUniversalAccessFromFileURLs(self) -> bool: ...
    def getBlockNetworkImage(self) -> bool: ...
    def getBlockNetworkLoads(self) -> bool: ...
    def getBuiltInZoomControls(self) -> bool: ...
    def getCacheMode(self) -> int: ...
    def getCursiveFontFamily(self) -> str: ...
    def getDatabaseEnabled(self) -> bool: ...
    def getDefaultFixedFontSize(self) -> int: ...
    def getDefaultFontSize(self) -> int: ...
    def getDefaultTextEncodingName(self) -> str: ...
    @staticmethod
    def getDefaultUserAgent(p0: Context) -> str: ...
    def getDefaultZoom(self) -> Any: ...
    def getDisabledActionModeMenuItems(self) -> int: ...
    def getDisplayZoomControls(self) -> bool: ...
    def getDomStorageEnabled(self) -> bool: ...
    def getFantasyFontFamily(self) -> str: ...
    def getFixedFontFamily(self) -> str: ...
    def getForceDark(self) -> int: ...
    def getJavaScriptCanOpenWindowsAutomatically(self) -> bool: ...
    def getJavaScriptEnabled(self) -> bool: ...
    def getLayoutAlgorithm(self) -> Any: ...
    def getLightTouchEnabled(self) -> bool: ...
    def getLoadWithOverviewMode(self) -> bool: ...
    def getLoadsImagesAutomatically(self) -> bool: ...
    def getMediaPlaybackRequiresUserGesture(self) -> bool: ...
    def getMinimumFontSize(self) -> int: ...
    def getMinimumLogicalFontSize(self) -> int: ...
    def getMixedContentMode(self) -> int: ...
    def getOffscreenPreRaster(self) -> bool: ...
    def getPluginState(self) -> Any: ...
    def getSafeBrowsingEnabled(self) -> bool: ...
    def getSansSerifFontFamily(self) -> str: ...
    def getSaveFormData(self) -> bool: ...
    def getSavePassword(self) -> bool: ...
    def getSerifFontFamily(self) -> str: ...
    def getStandardFontFamily(self) -> str: ...
    def getTextZoom(self) -> int: ...
    def getUseWideViewPort(self) -> bool: ...
    def getUserAgentString(self) -> str: ...
    def isAlgorithmicDarkeningAllowed(self) -> bool: ...
    def setAlgorithmicDarkeningAllowed(self, p0: bool) -> None: ...
    def setAllowContentAccess(self, p0: bool) -> None: ...
    def setAllowFileAccess(self, p0: bool) -> None: ...
    def setAllowFileAccessFromFileURLs(self, p0: bool) -> None: ...
    def setAllowUniversalAccessFromFileURLs(self, p0: bool) -> None: ...
    def setBlockNetworkImage(self, p0: bool) -> None: ...
    def setBlockNetworkLoads(self, p0: bool) -> None: ...
    def setBuiltInZoomControls(self, p0: bool) -> None: ...
    def setCacheMode(self, p0: int) -> None: ...
    def setCursiveFontFamily(self, p0: str) -> None: ...
    def setDatabaseEnabled(self, p0: bool) -> None: ...
    def setDatabasePath(self, p0: str) -> None: ...
    def setDefaultFixedFontSize(self, p0: int) -> None: ...
    def setDefaultFontSize(self, p0: int) -> None: ...
    def setDefaultTextEncodingName(self, p0: str) -> None: ...
    def setDefaultZoom(self, p0: Any) -> None: ...
    def setDisabledActionModeMenuItems(self, p0: int) -> None: ...
    def setDisplayZoomControls(self, p0: bool) -> None: ...
    def setDomStorageEnabled(self, p0: bool) -> None: ...
    def setEnableSmoothTransition(self, p0: bool) -> None: ...
    def setFantasyFontFamily(self, p0: str) -> None: ...
    def setFixedFontFamily(self, p0: str) -> None: ...
    def setForceDark(self, p0: int) -> None: ...
    def setGeolocationDatabasePath(self, p0: str) -> None: ...
    def setGeolocationEnabled(self, p0: bool) -> None: ...
    def setJavaScriptCanOpenWindowsAutomatically(self, p0: bool) -> None: ...
    def setJavaScriptEnabled(self, p0: bool) -> None: ...
    def setLayoutAlgorithm(self, p0: Any) -> None: ...
    def setLightTouchEnabled(self, p0: bool) -> None: ...
    def setLoadWithOverviewMode(self, p0: bool) -> None: ...
    def setLoadsImagesAutomatically(self, p0: bool) -> None: ...
    def setMediaPlaybackRequiresUserGesture(self, p0: bool) -> None: ...
    def setMinimumFontSize(self, p0: int) -> None: ...
    def setMinimumLogicalFontSize(self, p0: int) -> None: ...
    def setMixedContentMode(self, p0: int) -> None: ...
    def setNeedInitialFocus(self, p0: bool) -> None: ...
    def setOffscreenPreRaster(self, p0: bool) -> None: ...
    def setPluginState(self, p0: Any) -> None: ...
    def setRenderPriority(self, p0: Any) -> None: ...
    def setSafeBrowsingEnabled(self, p0: bool) -> None: ...
    def setSansSerifFontFamily(self, p0: str) -> None: ...
    def setSaveFormData(self, p0: bool) -> None: ...
    def setSavePassword(self, p0: bool) -> None: ...
    def setSerifFontFamily(self, p0: str) -> None: ...
    def setStandardFontFamily(self, p0: str) -> None: ...
    def setSupportMultipleWindows(self, p0: bool) -> None: ...
    def setSupportZoom(self, p0: bool) -> None: ...
    def setTextZoom(self, p0: int) -> None: ...
    def setUseWideViewPort(self, p0: bool) -> None: ...
    def setUserAgentString(self, p0: str) -> None: ...
    def supportMultipleWindows(self) -> bool: ...
    def supportZoom(self) -> bool: ...
    def getDatabasePath(self) -> str: ...

    class ZoomDensity:
        CLOSE: ClassVar["ZoomDensity"]
        FAR: ClassVar["ZoomDensity"]
        MEDIUM: ClassVar["ZoomDensity"]
        CLOSE: ClassVar[Any]
        FAR: ClassVar[Any]
        MEDIUM: ClassVar[Any]
        @staticmethod
        def values() -> Any: ...
        @staticmethod
        def valueOf(p0: str) -> Any: ...

    class TextSize:
        LARGER: ClassVar["TextSize"]
        LARGEST: ClassVar["TextSize"]
        NORMAL: ClassVar["TextSize"]
        SMALLER: ClassVar["TextSize"]
        SMALLEST: ClassVar["TextSize"]
        LARGER: ClassVar[Any]
        LARGEST: ClassVar[Any]
        NORMAL: ClassVar[Any]
        SMALLER: ClassVar[Any]
        SMALLEST: ClassVar[Any]
        @staticmethod
        def values() -> Any: ...
        @staticmethod
        def valueOf(p0: str) -> Any: ...

    class RenderPriority:
        HIGH: ClassVar["RenderPriority"]
        LOW: ClassVar["RenderPriority"]
        NORMAL: ClassVar["RenderPriority"]
        HIGH: ClassVar[Any]
        LOW: ClassVar[Any]
        NORMAL: ClassVar[Any]
        @staticmethod
        def values() -> Any: ...
        @staticmethod
        def valueOf(p0: str) -> Any: ...

    class PluginState:
        OFF: ClassVar["PluginState"]
        ON: ClassVar["PluginState"]
        ON_DEMAND: ClassVar["PluginState"]
        OFF: ClassVar[Any]
        ON: ClassVar[Any]
        ON_DEMAND: ClassVar[Any]
        @staticmethod
        def values() -> Any: ...
        @staticmethod
        def valueOf(p0: str) -> Any: ...

    class LayoutAlgorithm:
        NARROW_COLUMNS: ClassVar["LayoutAlgorithm"]
        NORMAL: ClassVar["LayoutAlgorithm"]
        SINGLE_COLUMN: ClassVar["LayoutAlgorithm"]
        TEXT_AUTOSIZING: ClassVar["LayoutAlgorithm"]
        NARROW_COLUMNS: ClassVar[Any]
        NORMAL: ClassVar[Any]
        SINGLE_COLUMN: ClassVar[Any]
        TEXT_AUTOSIZING: ClassVar[Any]
        @staticmethod
        def values() -> Any: ...
        @staticmethod
        def valueOf(p0: str) -> Any: ...

from typing import Any, ClassVar, overload
from android.content.Intent import Intent
from android.graphics.Bitmap import Bitmap
from android.os.Message import Message
from android.view.View import View
from android.webkit.ConsoleMessage import ConsoleMessage
from android.webkit.JsPromptResult import JsPromptResult
from android.webkit.JsResult import JsResult
from android.webkit.PermissionRequest import PermissionRequest
from android.webkit.ValueCallback import ValueCallback
from android.webkit.WebView import WebView

class WebChromeClient:
    def __init__(self) -> None: ...
    def onReceivedIcon(self, p0: WebView, p1: Bitmap) -> None: ...
    def onProgressChanged(self, p0: WebView, p1: int) -> None: ...
    def getVideoLoadingProgressView(self) -> View: ...
    def getDefaultVideoPoster(self) -> Bitmap: ...
    def getVisitedHistory(self, p0: ValueCallback) -> None: ...
    def onCloseWindow(self, p0: WebView) -> None: ...
    @overload
    def onConsoleMessage(self, p0: str, p1: int, p2: str) -> None: ...
    @overload
    def onConsoleMessage(self, p0: ConsoleMessage) -> bool: ...
    def onCreateWindow(self, p0: WebView, p1: bool, p2: bool, p3: Message) -> bool: ...
    def onExceededDatabaseQuota(self, p0: str, p1: str, p2: int, p3: int, p4: int, p5: Any) -> None: ...
    def onGeolocationPermissionsHidePrompt(self) -> None: ...
    def onGeolocationPermissionsShowPrompt(self, p0: str, p1: Any) -> None: ...
    def onHideCustomView(self) -> None: ...
    def onJsAlert(self, p0: WebView, p1: str, p2: str, p3: JsResult) -> bool: ...
    def onJsBeforeUnload(self, p0: WebView, p1: str, p2: str, p3: JsResult) -> bool: ...
    def onJsConfirm(self, p0: WebView, p1: str, p2: str, p3: JsResult) -> bool: ...
    def onJsPrompt(self, p0: WebView, p1: str, p2: str, p3: str, p4: JsPromptResult) -> bool: ...
    def onJsTimeout(self) -> bool: ...
    def onPermissionRequest(self, p0: PermissionRequest) -> None: ...
    def onPermissionRequestCanceled(self, p0: PermissionRequest) -> None: ...
    def onReceivedTitle(self, p0: WebView, p1: str) -> None: ...
    def onReceivedTouchIconUrl(self, p0: WebView, p1: str, p2: bool) -> None: ...
    def onRequestFocus(self, p0: WebView) -> None: ...
    @overload
    def onShowCustomView(self, p0: View, p1: int, p2: Any) -> None: ...
    @overload
    def onShowCustomView(self, p0: View, p1: Any) -> None: ...
    def onShowFileChooser(self, p0: WebView, p1: ValueCallback, p2: Any) -> bool: ...

    class FileChooserParams:
        MODE_OPEN: ClassVar[int]
        MODE_OPEN_MULTIPLE: ClassVar[int]
        MODE_SAVE: ClassVar[int]
        def __init__(self) -> None: ...
        def createIntent(self) -> Intent: ...
        def getAcceptTypes(self) -> Any: ...
        def getFilenameHint(self) -> str: ...
        def isCaptureEnabled(self) -> bool: ...
        @staticmethod
        def parseResult(p0: int, p1: Intent) -> Any: ...
        def getTitle(self) -> str: ...
        def getMode(self) -> int: ...

    class CustomViewCallback:
        def onCustomViewHidden(self) -> None: ...

from typing import Any, ClassVar, overload

class HttpAuthHandler:
    def proceed(self, p0: str, p1: str) -> None: ...
    def useHttpAuthUsernamePassword(self) -> bool: ...
    def cancel(self) -> None: ...

from typing import Any, ClassVar, overload

class WebResourceError:
    def getErrorCode(self) -> int: ...
    def getDescription(self) -> str: ...

from typing import Any, ClassVar, overload

class JsPromptResult:
    def confirm(self, p0: str) -> None: ...

from typing import Any, ClassVar, overload

class JsResult:
    def confirm(self) -> None: ...
    def cancel(self) -> None: ...

from typing import Any, ClassVar, overload
from android.webkit.ValueCallback import ValueCallback

class GeolocationPermissions:
    def clearAll(self) -> None: ...
    def getAllowed(self, p0: str, p1: ValueCallback) -> None: ...
    def getOrigins(self, p0: ValueCallback) -> None: ...
    def clear(self, p0: str) -> None: ...
    @staticmethod
    def getInstance() -> "GeolocationPermissions": ...
    def allow(self, p0: str) -> None: ...

    class Callback:
        def invoke(self, p0: str, p1: bool, p2: bool) -> None: ...

from typing import Any, ClassVar, overload

class ConsoleMessage:
    def __init__(self, p0: str, p1: str, p2: int, p3: Any) -> None: ...
    def messageLevel(self) -> Any: ...
    def sourceId(self) -> str: ...
    def lineNumber(self) -> int: ...
    def message(self) -> str: ...

    class MessageLevel:
        DEBUG: ClassVar["MessageLevel"]
        ERROR: ClassVar["MessageLevel"]
        LOG: ClassVar["MessageLevel"]
        TIP: ClassVar["MessageLevel"]
        WARNING: ClassVar["MessageLevel"]
        DEBUG: ClassVar[Any]
        ERROR: ClassVar[Any]
        LOG: ClassVar[Any]
        TIP: ClassVar[Any]
        WARNING: ClassVar[Any]
        @staticmethod
        def values() -> Any: ...
        @staticmethod
        def valueOf(p0: str) -> Any: ...

from typing import Any, ClassVar, overload
from android.webkit.ValueCallback import ValueCallback

class WebStorage:
    def getOrigins(self, p0: ValueCallback) -> None: ...
    def deleteAllData(self) -> None: ...
    def deleteOrigin(self, p0: str) -> None: ...
    def getQuotaForOrigin(self, p0: str, p1: ValueCallback) -> None: ...
    def getUsageForOrigin(self, p0: str, p1: ValueCallback) -> None: ...
    def setQuotaForOrigin(self, p0: str, p1: int) -> None: ...
    @staticmethod
    def getInstance() -> "WebStorage": ...

    class QuotaUpdater:
        def updateQuota(self, p0: int) -> None: ...

    class Origin:
        def getOrigin(self) -> str: ...
        def getQuota(self) -> int: ...
        def getUsage(self) -> int: ...

