from typing import Any, ClassVar, overload
from android.os.Parcel import Parcel

class WifiP2pServiceRequest:
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    def equals(self, p0: Any) -> bool: ...
    def hashCode(self) -> int: ...
    @overload
    @staticmethod
    def newInstance(p0: int) -> "WifiP2pServiceRequest": ...
    @overload
    @staticmethod
    def newInstance(p0: int, p1: str) -> "WifiP2pServiceRequest": ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
