from typing import Any, ClassVar, overload
from android.os.Parcel import Parcel

class WifiP2pUsdBasedServiceResponse:
    CREATOR: ClassVar[Any]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    def getServiceSpecificInfo(self) -> Any: ...
    def toString(self) -> str: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
    def describeContents(self) -> int: ...
    def getServiceProtocolType(self) -> int: ...
