from typing import Any, ClassVar, overload
from java.lang.Thread import Thread
from java.util.Date import Date
from java.util.concurrent.TimeUnit import TimeUnit

class AbstractQueuedLongSynchronizer:
    def __init__(self) -> None: ...
    def toString(self) -> str: ...
    def release(self, p0: int) -> bool: ...
    def hasQueuedThreads(self) -> bool: ...
    def isQueued(self, p0: Thread) -> bool: ...
    def getQueueLength(self) -> int: ...
    def getQueuedThreads(self) -> list: ...
    def hasWaiters(self, p0: Any) -> bool: ...
    def getWaitQueueLength(self, p0: Any) -> int: ...
    def getWaitingThreads(self, p0: Any) -> list: ...
    def acquire(self, p0: int) -> None: ...
    def acquireInterruptibly(self, p0: int) -> None: ...
    def tryAcquireNanos(self, p0: int, p1: int) -> bool: ...
    def getFirstQueuedThread(self) -> Thread: ...
    def owns(self, p0: Any) -> bool: ...
    def acquireShared(self, p0: int) -> None: ...
    def acquireSharedInterruptibly(self, p0: int) -> None: ...
    def tryAcquireSharedNanos(self, p0: int, p1: int) -> bool: ...
    def releaseShared(self, p0: int) -> bool: ...
    def hasContended(self) -> bool: ...
    def hasQueuedPredecessors(self) -> bool: ...
    def getExclusiveQueuedThreads(self) -> list: ...
    def getSharedQueuedThreads(self) -> list: ...

    class ConditionObject:
        def __init__(self, p0: "AbstractQueuedLongSynchronizer") -> None: ...
        def awaitUninterruptibly(self) -> None: ...
        def awaitUntil(self, p0: Date) -> bool: ...
        @overload
        def await_(self, p0: int, p1: TimeUnit) -> bool: ...
        @overload
        def await_(self) -> None: ...
        def signal(self) -> None: ...
        def signalAll(self) -> None: ...
        def awaitNanos(self, p0: int) -> int: ...
