from typing import Any, ClassVar, overload
from android.content.ClipDescription import ClipDescription
from android.net.Uri import Uri
from android.os.Parcel import Parcel

class InputContentInfo:
    CREATOR: ClassVar[Any]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    @overload
    def __init__(self, p0: Uri, p1: ClipDescription) -> None: ...
    @overload
    def __init__(self, p0: Uri, p1: ClipDescription, p2: Uri) -> None: ...
    def getContentUri(self) -> Uri: ...
    def releasePermission(self) -> None: ...
    def requestPermission(self) -> None: ...
    def getLinkUri(self) -> Uri: ...
    def getDescription(self) -> ClipDescription: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
    def describeContents(self) -> int: ...
