from jnius import JavaClass, MetaJavaClass, JavaMethod, JavaStaticMethod, JavaMultipleMethod, JavaField, JavaStaticField

__all__ = ["TvTrackInfo"]

class TvTrackInfo(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "android/media/tv/TvTrackInfo"
    CREATOR = JavaStaticField("Landroid/os/Parcelable$Creator;")
    TYPE_AUDIO = JavaStaticField("I")
    TYPE_SUBTITLE = JavaStaticField("I")
    TYPE_VIDEO = JavaStaticField("I")
    CONTENTS_FILE_DESCRIPTOR = JavaStaticField("I")
    PARCELABLE_WRITE_RETURN_VALUE = JavaStaticField("I")
    isEncrypted = JavaMethod("()Z")
    getVideoFrameRate = JavaMethod("()F")
    getAudioChannelCount = JavaMethod("()I")
    getAudioSampleRate = JavaMethod("()I")
    getVideoPixelAspectRatio = JavaMethod("()F")
    isAudioDescription = JavaMethod("()Z")
    isHardOfHearing = JavaMethod("()Z")
    isSpokenSubtitle = JavaMethod("()Z")
    getVideoActiveFormatDescription = JavaMethod("()B")
    getVideoHeight = JavaMethod("()I")
    getVideoWidth = JavaMethod("()I")
    equals = JavaMethod("(Ljava/lang/Object;)Z")
    hashCode = JavaMethod("()I")
    getId = JavaMethod("()Ljava/lang/String;")
    getType = JavaMethod("()I")
    getDescription = JavaMethod("()Ljava/lang/CharSequence;")
    getEncoding = JavaMethod("()Ljava/lang/String;")
    getLanguage = JavaMethod("()Ljava/lang/String;")
    writeToParcel = JavaMethod("(Landroid/os/Parcel;I)V")
    describeContents = JavaMethod("()I")
    getExtra = JavaMethod("()Landroid/os/Bundle;")

    class Builder(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "android/media/tv/TvTrackInfo$Builder"
        __javaconstructor__ = [("(ILjava/lang/String;)V", False)]
        setAudioChannelCount = JavaMethod("(I)Landroid/media/tv/TvTrackInfo$Builder;")
        setVideoFrameRate = JavaMethod("(F)Landroid/media/tv/TvTrackInfo$Builder;")
        setAudioDescription = JavaMethod("(Z)Landroid/media/tv/TvTrackInfo$Builder;")
        setEncrypted = JavaMethod("(Z)Landroid/media/tv/TvTrackInfo$Builder;")
        setHardOfHearing = JavaMethod("(Z)Landroid/media/tv/TvTrackInfo$Builder;")
        setSpokenSubtitle = JavaMethod("(Z)Landroid/media/tv/TvTrackInfo$Builder;")
        setVideoActiveFormatDescription = JavaMethod("(B)Landroid/media/tv/TvTrackInfo$Builder;")
        setVideoHeight = JavaMethod("(I)Landroid/media/tv/TvTrackInfo$Builder;")
        setVideoWidth = JavaMethod("(I)Landroid/media/tv/TvTrackInfo$Builder;")
        setVideoPixelAspectRatio = JavaMethod("(F)Landroid/media/tv/TvTrackInfo$Builder;")
        setAudioSampleRate = JavaMethod("(I)Landroid/media/tv/TvTrackInfo$Builder;")
        setEncoding = JavaMethod("(Ljava/lang/String;)Landroid/media/tv/TvTrackInfo$Builder;")
        setDescription = JavaMethod("(Ljava/lang/CharSequence;)Landroid/media/tv/TvTrackInfo$Builder;")
        build = JavaMethod("()Landroid/media/tv/TvTrackInfo;")
        setLanguage = JavaMethod("(Ljava/lang/String;)Landroid/media/tv/TvTrackInfo$Builder;")
        setExtra = JavaMethod("(Landroid/os/Bundle;)Landroid/media/tv/TvTrackInfo$Builder;")