from typing import Any, ClassVar, overload

class DosFileAttributes:
    def isSystem(self) -> bool: ...
    def isArchive(self) -> bool: ...
    def isReadOnly(self) -> bool: ...
    def isHidden(self) -> bool: ...
