from typing import Any, ClassVar, overload
from java.lang.Throwable import Throwable
from org.xmlpull.v1.XmlPullParser import XmlPullParser

class XmlPullParserException:
    @overload
    def __init__(self, p0: str) -> None: ...
    @overload
    def __init__(self, p0: str, p1: XmlPullParser, p2: Throwable) -> None: ...
    def printStackTrace(self) -> None: ...
    def getLineNumber(self) -> int: ...
    def getColumnNumber(self) -> int: ...
    def getDetail(self) -> Throwable: ...

from typing import Any, ClassVar, overload
from java.io.OutputStream import OutputStream
from java.io.Writer import Writer

class XmlSerializer:
    def endTag(self, p0: str, p1: str) -> "XmlSerializer": ...
    def cdsect(self, p0: str) -> None: ...
    def entityRef(self, p0: str) -> None: ...
    def docdecl(self, p0: str) -> None: ...
    def ignorableWhitespace(self, p0: str) -> None: ...
    def endDocument(self) -> None: ...
    def processingInstruction(self, p0: str) -> None: ...
    @overload
    def setOutput(self, p0: OutputStream, p1: str) -> None: ...
    @overload
    def setOutput(self, p0: Writer) -> None: ...
    def setPrefix(self, p0: str, p1: str) -> None: ...
    def startDocument(self, p0: str, p1: bool) -> None: ...
    def startTag(self, p0: str, p1: str) -> "XmlSerializer": ...
    def getName(self) -> str: ...
    def getProperty(self, p0: str) -> Any: ...
    def flush(self) -> None: ...
    def setProperty(self, p0: str, p1: Any) -> None: ...
    def comment(self, p0: str) -> None: ...
    def attribute(self, p0: str, p1: str, p2: str) -> "XmlSerializer": ...
    @overload
    def text(self, p0: Any, p1: int, p2: int) -> "XmlSerializer": ...
    @overload
    def text(self, p0: str) -> "XmlSerializer": ...
    def getDepth(self) -> int: ...
    def getFeature(self, p0: str) -> bool: ...
    def getNamespace(self) -> str: ...
    def getPrefix(self, p0: str, p1: bool) -> str: ...
    def setFeature(self, p0: str, p1: bool) -> None: ...

from typing import Any, ClassVar, overload
from org.xmlpull.v1.XmlPullParser import XmlPullParser
from org.xmlpull.v1.XmlSerializer import XmlSerializer

class XmlPullParserFactory:
    PROPERTY_NAME: ClassVar[str]
    @overload
    @staticmethod
    def newInstance(p0: str, p1: type) -> "XmlPullParserFactory": ...
    @overload
    @staticmethod
    def newInstance() -> "XmlPullParserFactory": ...
    def getFeature(self, p0: str) -> bool: ...
    def setFeature(self, p0: str, p1: bool) -> None: ...
    def newPullParser(self) -> XmlPullParser: ...
    def newSerializer(self) -> XmlSerializer: ...
    def setNamespaceAware(self, p0: bool) -> None: ...
    def setValidating(self, p0: bool) -> None: ...
    def isNamespaceAware(self) -> bool: ...
    def isValidating(self) -> bool: ...

from typing import Any, ClassVar, overload
from java.io.InputStream import InputStream
from java.io.Reader import Reader

class XmlPullParser:
    CDSECT: ClassVar[int]
    COMMENT: ClassVar[int]
    DOCDECL: ClassVar[int]
    END_DOCUMENT: ClassVar[int]
    END_TAG: ClassVar[int]
    ENTITY_REF: ClassVar[int]
    FEATURE_PROCESS_DOCDECL: ClassVar[str]
    FEATURE_PROCESS_NAMESPACES: ClassVar[str]
    FEATURE_REPORT_NAMESPACE_ATTRIBUTES: ClassVar[str]
    FEATURE_VALIDATION: ClassVar[str]
    IGNORABLE_WHITESPACE: ClassVar[int]
    NO_NAMESPACE: ClassVar[str]
    PROCESSING_INSTRUCTION: ClassVar[int]
    START_DOCUMENT: ClassVar[int]
    START_TAG: ClassVar[int]
    TEXT: ClassVar[int]
    TYPES: ClassVar[Any]
    def getName(self) -> str: ...
    def getProperty(self, p0: str) -> Any: ...
    def isWhitespace(self) -> bool: ...
    def next(self) -> int: ...
    def setProperty(self, p0: str, p1: Any) -> None: ...
    def nextToken(self) -> int: ...
    def getLineNumber(self) -> int: ...
    @overload
    def setInput(self, p0: InputStream, p1: str) -> None: ...
    @overload
    def setInput(self, p0: Reader) -> None: ...
    def getColumnNumber(self) -> int: ...
    def getEventType(self) -> int: ...
    def getText(self) -> str: ...
    def getAttributeCount(self) -> int: ...
    def getAttributeName(self, p0: int) -> str: ...
    def getAttributeNamespace(self, p0: int) -> str: ...
    @overload
    def getAttributeValue(self, p0: str, p1: str) -> str: ...
    @overload
    def getAttributeValue(self, p0: int) -> str: ...
    def getPositionDescription(self) -> str: ...
    def defineEntityReplacementText(self, p0: str, p1: str) -> None: ...
    def getAttributePrefix(self, p0: int) -> str: ...
    def getAttributeType(self, p0: int) -> str: ...
    def getDepth(self) -> int: ...
    def getFeature(self, p0: str) -> bool: ...
    def getInputEncoding(self) -> str: ...
    @overload
    def getNamespace(self) -> str: ...
    @overload
    def getNamespace(self, p0: str) -> str: ...
    def getNamespaceCount(self, p0: int) -> int: ...
    def getNamespacePrefix(self, p0: int) -> str: ...
    def getNamespaceUri(self, p0: int) -> str: ...
    def getPrefix(self) -> str: ...
    def getTextCharacters(self, p0: Any) -> Any: ...
    def isAttributeDefault(self, p0: int) -> bool: ...
    def isEmptyElementTag(self) -> bool: ...
    def nextTag(self) -> int: ...
    def nextText(self) -> str: ...
    def require(self, p0: int, p1: str, p2: str) -> None: ...
    def setFeature(self, p0: str, p1: bool) -> None: ...

