from typing import Any, ClassVar, overload
from java.security.spec.AlgorithmParameterSpec import AlgorithmParameterSpec

class WrappedKeyEntry:
    def __init__(self, p0: Any, p1: str, p2: str, p3: AlgorithmParameterSpec) -> None: ...
    def getTransformation(self) -> str: ...
    def getAlgorithmParameterSpec(self) -> AlgorithmParameterSpec: ...
    def getWrappedKeyBytes(self) -> Any: ...
    def getWrappingKeyAlias(self) -> str: ...
