from typing import Any, ClassVar, overload
from android.health.connect.datatypes.AggregationType import AggregationType
from java.time.ZoneOffset import ZoneOffset

class AggregateRecordsResponse:
    def get(self, p0: AggregationType) -> Any: ...
    def getDataOrigins(self, p0: AggregationType) -> set: ...
    def getZoneOffset(self, p0: AggregationType) -> ZoneOffset: ...
