from typing import Any, ClassVar, overload
from android.os.Parcel import Parcel

class ChangeLogsRequest:
    CREATOR: ClassVar[Any]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    def describeContents(self) -> int: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
    def getPageSize(self) -> int: ...
    def getToken(self) -> str: ...

    class Builder:
        def __init__(self, p0: str) -> None: ...
        def setPageSize(self, p0: int) -> Any: ...
        def build(self) -> "ChangeLogsRequest": ...

from typing import Any, ClassVar, overload
from android.os.Parcel import Parcel
from java.time.Instant import Instant

class ChangeLogsResponse:
    CREATOR: ClassVar[Any]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    def describeContents(self) -> int: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
    def getDeletedLogs(self) -> list: ...
    def getUpsertedRecords(self) -> list: ...
    def getNextChangesToken(self) -> str: ...
    def hasMorePages(self) -> bool: ...

    class DeletedLog:
        def __init__(self, p0: str, p1: int) -> None: ...
        def getDeletedTime(self) -> Instant: ...
        def getDeletedRecordId(self) -> str: ...

from typing import Any, ClassVar, overload
from android.health.connect.datatypes.DataOrigin import DataOrigin
from android.os.Parcel import Parcel

class ChangeLogTokenRequest:
    CREATOR: ClassVar[Any]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    def describeContents(self) -> int: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
    def getRecordTypes(self) -> set: ...
    def getDataOriginFilters(self) -> set: ...

    class Builder:
        def __init__(self) -> None: ...
        def addDataOriginFilter(self, p0: DataOrigin) -> Any: ...
        def addRecordType(self, p0: type) -> Any: ...
        def build(self) -> "ChangeLogTokenRequest": ...

from typing import Any, ClassVar, overload
from android.os.Parcel import Parcel

class ChangeLogTokenResponse:
    CREATOR: ClassVar[Any]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    def describeContents(self) -> int: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
    def getToken(self) -> str: ...

