from typing import Any, ClassVar, overload
from android.os.Parcel import Parcel

class GetMedicalDataSourcesRequest:
    CREATOR: ClassVar[Any]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    def equals(self, p0: Any) -> bool: ...
    def toString(self) -> str: ...
    def hashCode(self) -> int: ...
    def getPackageNames(self) -> set: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
    def describeContents(self) -> int: ...

    class Builder:
        @overload
        def __init__(self, p0: Any) -> None: ...
        @overload
        def __init__(self, p0: "GetMedicalDataSourcesRequest") -> None: ...
        @overload
        def __init__(self) -> None: ...
        def clearPackageNames(self) -> Any: ...
        def addPackageName(self, p0: str) -> Any: ...
        def build(self) -> "GetMedicalDataSourcesRequest": ...
