from typing import Any, ClassVar, overload
from android.health.connect.AggregateRecordsRequest import AggregateRecordsRequest
from android.health.connect.CreateMedicalDataSourceRequest import CreateMedicalDataSourceRequest
from android.health.connect.DeleteMedicalResourcesRequest import DeleteMedicalResourcesRequest
from android.health.connect.GetMedicalDataSourcesRequest import GetMedicalDataSourcesRequest
from android.health.connect.ReadMedicalResourcesRequest import ReadMedicalResourcesRequest
from android.health.connect.ReadRecordsRequest import ReadRecordsRequest
from android.health.connect.TimeRangeFilter import TimeRangeFilter
from android.health.connect.changelog.ChangeLogTokenRequest import ChangeLogTokenRequest
from android.health.connect.changelog.ChangeLogsRequest import ChangeLogsRequest
from android.os.OutcomeReceiver import OutcomeReceiver
from java.time.Duration import Duration
from java.time.Period import Period
from java.util.concurrent.Executor import Executor

class HealthConnectManager:
    ACTION_MANAGE_HEALTH_PERMISSIONS: ClassVar[str]
    ACTION_REQUEST_EXERCISE_ROUTE: ClassVar[str]
    CATEGORY_HEALTH_PERMISSIONS: ClassVar[str]
    EXTRA_EXERCISE_ROUTE: ClassVar[str]
    EXTRA_SESSION_ID: ClassVar[str]
    def getChangeLogToken(self, p0: ChangeLogTokenRequest, p1: Executor, p2: OutcomeReceiver) -> None: ...
    def getChangeLogs(self, p0: ChangeLogsRequest, p1: Executor, p2: OutcomeReceiver) -> None: ...
    def aggregate(self, p0: AggregateRecordsRequest, p1: Executor, p2: OutcomeReceiver) -> None: ...
    def readRecords(self, p0: ReadRecordsRequest, p1: Executor, p2: OutcomeReceiver) -> None: ...
    @overload
    def deleteRecords(self, p0: type, p1: TimeRangeFilter, p2: Executor, p3: OutcomeReceiver) -> None: ...
    @overload
    def deleteRecords(self, p0: list, p1: Executor, p2: OutcomeReceiver) -> None: ...
    def insertRecords(self, p0: list, p1: Executor, p2: OutcomeReceiver) -> None: ...
    def updateRecords(self, p0: list, p1: Executor, p2: OutcomeReceiver) -> None: ...
    def aggregateGroupByDuration(self, p0: AggregateRecordsRequest, p1: Duration, p2: Executor, p3: OutcomeReceiver) -> None: ...
    def aggregateGroupByPeriod(self, p0: AggregateRecordsRequest, p1: Period, p2: Executor, p3: OutcomeReceiver) -> None: ...
    def createMedicalDataSource(self, p0: CreateMedicalDataSourceRequest, p1: Executor, p2: OutcomeReceiver) -> None: ...
    def deleteMedicalDataSourceWithData(self, p0: str, p1: Executor, p2: OutcomeReceiver) -> None: ...
    @overload
    def deleteMedicalResources(self, p0: list, p1: Executor, p2: OutcomeReceiver) -> None: ...
    @overload
    def deleteMedicalResources(self, p0: DeleteMedicalResourcesRequest, p1: Executor, p2: OutcomeReceiver) -> None: ...
    @overload
    def getMedicalDataSources(self, p0: GetMedicalDataSourcesRequest, p1: Executor, p2: OutcomeReceiver) -> None: ...
    @overload
    def getMedicalDataSources(self, p0: list, p1: Executor, p2: OutcomeReceiver) -> None: ...
    @overload
    def readMedicalResources(self, p0: list, p1: Executor, p2: OutcomeReceiver) -> None: ...
    @overload
    def readMedicalResources(self, p0: ReadMedicalResourcesRequest, p1: Executor, p2: OutcomeReceiver) -> None: ...
    def upsertMedicalResources(self, p0: list, p1: Executor, p2: OutcomeReceiver) -> None: ...
