from typing import Any, ClassVar, overload

class ReadMedicalResourcesInitialRequest:
    def equals(self, p0: Any) -> bool: ...
    def toString(self) -> str: ...
    def hashCode(self) -> int: ...
    def getDataSourceIds(self) -> set: ...
    def getMedicalResourceType(self) -> int: ...

    class Builder:
        @overload
        def __init__(self, p0: int) -> None: ...
        @overload
        def __init__(self, p0: Any) -> None: ...
        @overload
        def __init__(self, p0: "ReadMedicalResourcesInitialRequest") -> None: ...
        def addDataSourceId(self, p0: str) -> Any: ...
        def clearDataSourceIds(self) -> Any: ...
        def addDataSourceIds(self, p0: set) -> Any: ...
        def setMedicalResourceType(self, p0: int) -> Any: ...
        def setPageSize(self, p0: int) -> Any: ...
        def build(self) -> "ReadMedicalResourcesInitialRequest": ...
