# cython: language_level=3
# Generated by jni-wrap cython — do not edit by hand.
from jni_core._core cimport JavaObject
from jni_core.jni cimport (
    JNIEnv, jobject, jstring,
    jboolean, jbyte, jchar, jshort, jint, jlong, jfloat, jdouble,
)

cdef class ClientCertRequest(JavaObject):
    cdef jobject _getPrincipals(self, JNIEnv* env) except? NULL
    cdef jobject _getPrincipals_0(self, JNIEnv* env) except? NULL
    cdef void _cancel(self, JNIEnv* env) except *
    cdef void _cancel_0(self, JNIEnv* env) except *
    cdef void _ignore(self, JNIEnv* env) except *
    cdef void _ignore_0(self, JNIEnv* env) except *
    cdef jstring _getHost(self, JNIEnv* env) except? NULL
    cdef jstring _getHost_0(self, JNIEnv* env) except? NULL
    cdef jint _getPort(self, JNIEnv* env) except *
    cdef jint _getPort_0(self, JNIEnv* env) except *
    cdef void _proceed(self, JNIEnv* env, jobject p0, jobject p1) except *
    cdef void _proceed_0(self, JNIEnv* env, jobject p0, jobject p1) except *
    cdef jobject _getKeyTypes(self, JNIEnv* env) except? NULL
    cdef jobject _getKeyTypes_0(self, JNIEnv* env) except? NULL
