from typing import Any, ClassVar, overload
from android.webkit.WebHistoryItem import WebHistoryItem

class WebBackForwardList:
    def __init__(self) -> None: ...
    def getItemAtIndex(self, p0: int) -> WebHistoryItem: ...
    def getCurrentIndex(self) -> int: ...
    def getCurrentItem(self) -> WebHistoryItem: ...
    def getSize(self) -> int: ...
