from typing import Any, ClassVar, overload
from android.graphics.Bitmap import Bitmap

class WebHistoryItem:
    def __init__(self) -> None: ...
    def getFavicon(self) -> Bitmap: ...
    def getOriginalUrl(self) -> str: ...
    def getUrl(self) -> str: ...
    def getTitle(self) -> str: ...
