from typing import Any, ClassVar, overload
from android.app.Notification import Notification
from android.os.Parcel import Parcel
from android.os.UserHandle import UserHandle

class StatusBarNotification:
    CREATOR: ClassVar[Any]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    @overload
    def __init__(self, p0: str, p1: str, p2: int, p3: str, p4: int, p5: int, p6: int, p7: Notification, p8: UserHandle, p9: int) -> None: ...
    @overload
    def __init__(self, p0: Parcel) -> None: ...
    def getOverrideGroupKey(self) -> str: ...
    def getGroupKey(self) -> str: ...
    def getPostTime(self) -> int: ...
    def getUserId(self) -> int: ...
    def getNotification(self) -> Notification: ...
    def isAppGroup(self) -> bool: ...
    def isClearable(self) -> bool: ...
    def getOpPkg(self) -> str: ...
    def isGroup(self) -> bool: ...
    def isOngoing(self) -> bool: ...
    def setOverrideGroupKey(self, p0: str) -> None: ...
    def toString(self) -> str: ...
    @overload
    def clone(self) -> "StatusBarNotification": ...
    @overload
    def clone(self) -> Any: ...
    def getPackageName(self) -> str: ...
    def getKey(self) -> str: ...
    def getId(self) -> int: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
    def describeContents(self) -> int: ...
    def getUser(self) -> UserHandle: ...
    def getUid(self) -> int: ...
    def getTag(self) -> str: ...
