from typing import Any, ClassVar, overload
from java.lang.Thread import Thread

class LockSupport:
    @overload
    @staticmethod
    def park() -> None: ...
    @overload
    @staticmethod
    def park(p0: Any) -> None: ...
    @staticmethod
    def unpark(p0: Thread) -> None: ...
    @overload
    @staticmethod
    def parkNanos(p0: int) -> None: ...
    @overload
    @staticmethod
    def parkNanos(p0: Any, p1: int) -> None: ...
    @overload
    @staticmethod
    def parkUntil(p0: int) -> None: ...
    @overload
    @staticmethod
    def parkUntil(p0: Any, p1: int) -> None: ...
    @staticmethod
    def setCurrentBlocker(p0: Any) -> None: ...
    @staticmethod
    def getBlocker(p0: Thread) -> Any: ...

from typing import Any, ClassVar, overload

class AbstractOwnableSynchronizer:
    ...

from typing import Any, ClassVar, overload
from java.util.concurrent.TimeUnit import TimeUnit
from java.util.concurrent.locks.Lock import Lock
from java.util.concurrent.locks.ReadWriteLock import ReadWriteLock

class StampedLock:
    def __init__(self) -> None: ...
    def toString(self) -> str: ...
    def validate(self, p0: int) -> bool: ...
    def unlock(self, p0: int) -> None: ...
    def unlockWrite(self, p0: int) -> None: ...
    def unlockRead(self, p0: int) -> None: ...
    def getReadLockCount(self) -> int: ...
    def writeLock(self) -> int: ...
    @overload
    def tryWriteLock(self) -> int: ...
    @overload
    def tryWriteLock(self, p0: int, p1: TimeUnit) -> int: ...
    def writeLockInterruptibly(self) -> int: ...
    def readLock(self) -> int: ...
    @overload
    def tryReadLock(self, p0: int, p1: TimeUnit) -> int: ...
    @overload
    def tryReadLock(self) -> int: ...
    def readLockInterruptibly(self) -> int: ...
    def tryOptimisticRead(self) -> int: ...
    def tryConvertToWriteLock(self, p0: int) -> int: ...
    def tryConvertToReadLock(self, p0: int) -> int: ...
    def tryConvertToOptimisticRead(self, p0: int) -> int: ...
    def tryUnlockWrite(self) -> bool: ...
    def tryUnlockRead(self) -> bool: ...
    def isWriteLocked(self) -> bool: ...
    def isReadLocked(self) -> bool: ...
    @staticmethod
    def isWriteLockStamp(p0: int) -> bool: ...
    @staticmethod
    def isReadLockStamp(p0: int) -> bool: ...
    @staticmethod
    def isLockStamp(p0: int) -> bool: ...
    @staticmethod
    def isOptimisticReadStamp(p0: int) -> bool: ...
    def asReadLock(self) -> Lock: ...
    def asWriteLock(self) -> Lock: ...
    def asReadWriteLock(self) -> ReadWriteLock: ...

from typing import Any, ClassVar, overload
from java.lang.Thread import Thread
from java.util.Date import Date
from java.util.concurrent.TimeUnit import TimeUnit

class AbstractQueuedSynchronizer:
    def toString(self) -> str: ...
    def hasQueuedThreads(self) -> bool: ...
    def isQueued(self, p0: Thread) -> bool: ...
    def getQueueLength(self) -> int: ...
    def getQueuedThreads(self) -> list: ...
    def hasWaiters(self, p0: Any) -> bool: ...
    def getWaitQueueLength(self, p0: Any) -> int: ...
    def getWaitingThreads(self, p0: Any) -> list: ...
    def acquire(self, p0: int) -> None: ...
    def acquireInterruptibly(self, p0: int) -> None: ...
    def tryAcquireNanos(self, p0: int, p1: int) -> bool: ...
    def getFirstQueuedThread(self) -> Thread: ...
    def owns(self, p0: Any) -> bool: ...
    def acquireShared(self, p0: int) -> None: ...
    def acquireSharedInterruptibly(self, p0: int) -> None: ...
    def tryAcquireSharedNanos(self, p0: int, p1: int) -> bool: ...
    def releaseShared(self, p0: int) -> bool: ...
    def hasContended(self) -> bool: ...
    def hasQueuedPredecessors(self) -> bool: ...
    def getExclusiveQueuedThreads(self) -> list: ...
    def getSharedQueuedThreads(self) -> list: ...
    def release(self, p0: int) -> bool: ...

    class ConditionObject:
        def __init__(self, p0: "AbstractQueuedSynchronizer") -> None: ...
        def signal(self) -> None: ...
        def signalAll(self) -> None: ...
        @overload
        def await_(self) -> None: ...
        @overload
        def await_(self, p0: int, p1: TimeUnit) -> bool: ...
        def awaitUninterruptibly(self) -> None: ...
        def awaitNanos(self, p0: int) -> int: ...
        def awaitUntil(self, p0: Date) -> bool: ...

from typing import Any, ClassVar, overload
from java.util.concurrent.TimeUnit import TimeUnit
from java.util.concurrent.locks.Condition import Condition

class Lock:
    def newCondition(self) -> Condition: ...
    def lock(self) -> None: ...
    def unlock(self) -> None: ...
    def lockInterruptibly(self) -> None: ...
    @overload
    def tryLock(self, p0: int, p1: TimeUnit) -> bool: ...
    @overload
    def tryLock(self) -> bool: ...

from typing import Any, ClassVar, overload
from java.lang.Thread import Thread
from java.util.concurrent.TimeUnit import TimeUnit
from java.util.concurrent.locks.Condition import Condition
from java.util.concurrent.locks.Lock import Lock

class ReentrantReadWriteLock:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, p0: bool) -> None: ...
    def getWriteHoldCount(self) -> int: ...
    def getReadHoldCount(self) -> int: ...
    def isWriteLockedByCurrentThread(self) -> bool: ...
    def toString(self) -> str: ...
    def hasQueuedThreads(self) -> bool: ...
    def getQueueLength(self) -> int: ...
    def hasWaiters(self, p0: Condition) -> bool: ...
    def getWaitQueueLength(self, p0: Condition) -> int: ...
    def isFair(self) -> bool: ...
    def hasQueuedThread(self, p0: Thread) -> bool: ...
    def getReadLockCount(self) -> int: ...
    @overload
    def writeLock(self) -> Lock: ...
    @overload
    def writeLock(self) -> Any: ...
    @overload
    def readLock(self) -> Lock: ...
    @overload
    def readLock(self) -> Any: ...
    def isWriteLocked(self) -> bool: ...

    class ReadLock:
        def newCondition(self) -> Condition: ...
        def lock(self) -> None: ...
        def toString(self) -> str: ...
        def unlock(self) -> None: ...
        def lockInterruptibly(self) -> None: ...
        @overload
        def tryLock(self, p0: int, p1: TimeUnit) -> bool: ...
        @overload
        def tryLock(self) -> bool: ...

    class WriteLock:
        def newCondition(self) -> Condition: ...
        def lock(self) -> None: ...
        def toString(self) -> str: ...
        def unlock(self) -> None: ...
        def lockInterruptibly(self) -> None: ...
        @overload
        def tryLock(self, p0: int, p1: TimeUnit) -> bool: ...
        @overload
        def tryLock(self) -> bool: ...
        def getHoldCount(self) -> int: ...
        def isHeldByCurrentThread(self) -> bool: ...

from typing import Any, ClassVar, overload
from java.util.concurrent.locks.Lock import Lock

class ReadWriteLock:
    def writeLock(self) -> Lock: ...
    def readLock(self) -> Lock: ...

from typing import Any, ClassVar, overload
from java.lang.Thread import Thread
from java.util.concurrent.TimeUnit import TimeUnit
from java.util.concurrent.locks.Condition import Condition

class ReentrantLock:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, p0: bool) -> None: ...
    def newCondition(self) -> Condition: ...
    def lock(self) -> None: ...
    def toString(self) -> str: ...
    def unlock(self) -> None: ...
    def lockInterruptibly(self) -> None: ...
    @overload
    def tryLock(self, p0: int, p1: TimeUnit) -> bool: ...
    @overload
    def tryLock(self) -> bool: ...
    def getHoldCount(self) -> int: ...
    def isLocked(self) -> bool: ...
    def hasQueuedThreads(self) -> bool: ...
    def getQueueLength(self) -> int: ...
    def hasWaiters(self, p0: Condition) -> bool: ...
    def getWaitQueueLength(self, p0: Condition) -> int: ...
    def isHeldByCurrentThread(self) -> bool: ...
    def isFair(self) -> bool: ...
    def hasQueuedThread(self, p0: Thread) -> bool: ...

from typing import Any, ClassVar, overload
from java.util.Date import Date
from java.util.concurrent.TimeUnit import TimeUnit

class Condition:
    def signal(self) -> None: ...
    def signalAll(self) -> None: ...
    @overload
    def await_(self) -> None: ...
    @overload
    def await_(self, p0: int, p1: TimeUnit) -> bool: ...
    def awaitUninterruptibly(self) -> None: ...
    def awaitNanos(self, p0: int) -> int: ...
    def awaitUntil(self, p0: Date) -> bool: ...

from typing import Any, ClassVar, overload
from java.lang.Thread import Thread
from java.util.Date import Date
from java.util.concurrent.TimeUnit import TimeUnit

class AbstractQueuedLongSynchronizer:
    def __init__(self) -> None: ...
    def toString(self) -> str: ...
    def hasQueuedThreads(self) -> bool: ...
    def isQueued(self, p0: Thread) -> bool: ...
    def getQueueLength(self) -> int: ...
    def getQueuedThreads(self) -> list: ...
    def hasWaiters(self, p0: Any) -> bool: ...
    def getWaitQueueLength(self, p0: Any) -> int: ...
    def getWaitingThreads(self, p0: Any) -> list: ...
    def acquire(self, p0: int) -> None: ...
    def acquireInterruptibly(self, p0: int) -> None: ...
    def tryAcquireNanos(self, p0: int, p1: int) -> bool: ...
    def getFirstQueuedThread(self) -> Thread: ...
    def owns(self, p0: Any) -> bool: ...
    def acquireShared(self, p0: int) -> None: ...
    def acquireSharedInterruptibly(self, p0: int) -> None: ...
    def tryAcquireSharedNanos(self, p0: int, p1: int) -> bool: ...
    def releaseShared(self, p0: int) -> bool: ...
    def hasContended(self) -> bool: ...
    def hasQueuedPredecessors(self) -> bool: ...
    def getExclusiveQueuedThreads(self) -> list: ...
    def getSharedQueuedThreads(self) -> list: ...
    def release(self, p0: int) -> bool: ...

    class ConditionObject:
        def __init__(self, p0: "AbstractQueuedLongSynchronizer") -> None: ...
        def signal(self) -> None: ...
        def signalAll(self) -> None: ...
        @overload
        def await_(self) -> None: ...
        @overload
        def await_(self, p0: int, p1: TimeUnit) -> bool: ...
        def awaitUninterruptibly(self) -> None: ...
        def awaitNanos(self, p0: int) -> int: ...
        def awaitUntil(self, p0: Date) -> bool: ...

