from typing import Any, ClassVar, overload
from java.time.Clock import Clock
from java.time.LocalTime import LocalTime
from java.time.ZoneId import ZoneId
from java.time.chrono.ChronoLocalDate import ChronoLocalDate
from java.time.chrono.ChronoLocalDateTime import ChronoLocalDateTime
from java.time.chrono.ChronoPeriod import ChronoPeriod
from java.time.chrono.Chronology import Chronology
from java.time.chrono.Era import Era
from java.time.chrono.HijrahChronology import HijrahChronology
from java.time.chrono.HijrahEra import HijrahEra
from java.time.temporal.Temporal import Temporal
from java.time.temporal.TemporalAccessor import TemporalAccessor
from java.time.temporal.TemporalAdjuster import TemporalAdjuster
from java.time.temporal.TemporalAmount import TemporalAmount
from java.time.temporal.TemporalField import TemporalField
from java.time.temporal.TemporalUnit import TemporalUnit
from java.time.temporal.ValueRange import ValueRange

class HijrahDate:
    def equals(self, p0: Any) -> bool: ...
    def toString(self) -> str: ...
    def hashCode(self) -> int: ...
    def getLong(self, p0: TemporalField) -> int: ...
    @staticmethod
    def of(p0: int, p1: int, p2: int) -> "HijrahDate": ...
    @staticmethod
    def from_(p0: TemporalAccessor) -> "HijrahDate": ...
    @overload
    def with_(self, p0: TemporalAdjuster) -> "HijrahDate": ...
    @overload
    def with_(self, p0: TemporalField, p1: int) -> Temporal: ...
    @overload
    def with_(self, p0: TemporalField, p1: int) -> "HijrahDate": ...
    @overload
    def with_(self, p0: TemporalAdjuster) -> Temporal: ...
    @overload
    def with_(self, p0: TemporalAdjuster) -> ChronoLocalDate: ...
    @overload
    def with_(self, p0: TemporalField, p1: int) -> ChronoLocalDate: ...
    def range(self, p0: TemporalField) -> ValueRange: ...
    @overload
    @staticmethod
    def now(p0: Clock) -> "HijrahDate": ...
    @overload
    @staticmethod
    def now() -> "HijrahDate": ...
    @overload
    @staticmethod
    def now(p0: ZoneId) -> "HijrahDate": ...
    @overload
    def plus(self, p0: TemporalAmount) -> ChronoLocalDate: ...
    @overload
    def plus(self, p0: int, p1: TemporalUnit) -> "HijrahDate": ...
    @overload
    def plus(self, p0: int, p1: TemporalUnit) -> ChronoLocalDate: ...
    @overload
    def plus(self, p0: int, p1: TemporalUnit) -> Temporal: ...
    @overload
    def plus(self, p0: TemporalAmount) -> "HijrahDate": ...
    @overload
    def plus(self, p0: TemporalAmount) -> Temporal: ...
    @overload
    def until(self, p0: ChronoLocalDate) -> ChronoPeriod: ...
    @overload
    def until(self, p0: Temporal, p1: TemporalUnit) -> int: ...
    @overload
    def minus(self, p0: int, p1: TemporalUnit) -> ChronoLocalDate: ...
    @overload
    def minus(self, p0: TemporalAmount) -> ChronoLocalDate: ...
    @overload
    def minus(self, p0: int, p1: TemporalUnit) -> Temporal: ...
    @overload
    def minus(self, p0: TemporalAmount) -> "HijrahDate": ...
    @overload
    def minus(self, p0: int, p1: TemporalUnit) -> "HijrahDate": ...
    @overload
    def minus(self, p0: TemporalAmount) -> Temporal: ...
    @overload
    def getChronology(self) -> Chronology: ...
    @overload
    def getChronology(self) -> HijrahChronology: ...
    def isLeapYear(self) -> bool: ...
    def lengthOfMonth(self) -> int: ...
    def lengthOfYear(self) -> int: ...
    def toEpochDay(self) -> int: ...
    def atTime(self, p0: LocalTime) -> ChronoLocalDateTime: ...
    @overload
    def getEra(self) -> Era: ...
    @overload
    def getEra(self) -> HijrahEra: ...
    def withVariant(self, p0: HijrahChronology) -> "HijrahDate": ...
