from typing import Any, ClassVar, overload
from android.graphics.Insets import Insets
from android.view.View import View
from android.view.ViewStructure import ViewStructure
from android.view.autofill.AutofillId import AutofillId
from android.view.contentcapture.ContentCaptureContext import ContentCaptureContext
from android.view.contentcapture.ContentCaptureSessionId import ContentCaptureSessionId

class ContentCaptureSession:
    def newAutofillId(self, p0: AutofillId, p1: int) -> AutofillId: ...
    def newViewStructure(self, p0: View) -> ViewStructure: ...
    def notifyViewAppeared(self, p0: ViewStructure) -> None: ...
    def getContentCaptureSessionId(self) -> ContentCaptureSessionId: ...
    def createContentCaptureSession(self, p0: ContentCaptureContext) -> "ContentCaptureSession": ...
    def getContentCaptureContext(self) -> ContentCaptureContext: ...
    def newVirtualViewStructure(self, p0: AutofillId, p1: int) -> ViewStructure: ...
    def notifySessionPaused(self) -> None: ...
    def notifySessionResumed(self) -> None: ...
    def notifyViewDisappeared(self, p0: AutofillId) -> None: ...
    def notifyViewInsetsChanged(self, p0: Insets) -> None: ...
    def notifyViewTextChanged(self, p0: AutofillId, p1: str) -> None: ...
    def notifyViewsAppeared(self, p0: list) -> None: ...
    def notifyViewsDisappeared(self, p0: AutofillId, p1: Any) -> None: ...
    def setContentCaptureContext(self, p0: ContentCaptureContext) -> None: ...
    def toString(self) -> str: ...
    def flush(self) -> None: ...
    def close(self) -> None: ...
    def destroy(self) -> None: ...
