from typing import Any, ClassVar, overload

class EapAkaInfo:
    def getReauthId(self) -> Any: ...

    class Builder:
        def __init__(self) -> None: ...
        def setReauthId(self, p0: Any) -> Any: ...
        def build(self) -> "EapAkaInfo": ...
