from typing import Any, ClassVar, overload

class StreamingServiceCallback:
    SIGNAL_STRENGTH_UNAVAILABLE: ClassVar[int]
    def __init__(self) -> None: ...
    def onMediaDescriptionUpdated(self) -> None: ...
    def onStreamStateUpdated(self, p0: int, p1: int) -> None: ...
    def onStreamMethodUpdated(self, p0: int) -> None: ...
    def onBroadcastSignalStrengthUpdated(self, p0: int) -> None: ...
    def onError(self, p0: int, p1: str) -> None: ...
