from typing import Any, ClassVar, overload
from android.content.pm.SigningInfo import SigningInfo
from android.os.Parcel import Parcel

class CallingAppInfo:
    CREATOR: ClassVar[Any]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    @overload
    def __init__(self, p0: str, p1: SigningInfo) -> None: ...
    @overload
    def __init__(self, p0: str, p1: SigningInfo, p2: str) -> None: ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
    def getOrigin(self) -> str: ...
    def getSigningInfo(self) -> SigningInfo: ...
    def toString(self) -> str: ...
    def getPackageName(self) -> str: ...
