from typing import Any, ClassVar, overload
from android.app.slice.Slice import Slice
from android.os.Parcel import Parcel

class CreateEntry:
    CREATOR: ClassVar[Any]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    def __init__(self, p0: Slice) -> None: ...
    def getSlice(self) -> Slice: ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
