from typing import Any, ClassVar, overload
from java.util.Iterator import Iterator

class CertPath:
    def getEncodings(self) -> Iterator: ...
    @overload
    def getEncoded(self, p0: str) -> Any: ...
    @overload
    def getEncoded(self) -> Any: ...
    def equals(self, p0: Any) -> bool: ...
    def toString(self) -> str: ...
    def hashCode(self) -> int: ...
    def getCertificates(self) -> list: ...
    def getType(self) -> str: ...
