from typing import Any, ClassVar, overload
from java.io.InputStream import InputStream
from java.security.Provider import Provider
from java.security.cert.CRL import CRL
from java.security.cert.CertPath import CertPath
from java.security.cert.Certificate import Certificate
from java.util.Iterator import Iterator

class CertificateFactory:
    def generateCertificate(self, p0: InputStream) -> Certificate: ...
    @overload
    def generateCertPath(self, p0: list) -> CertPath: ...
    @overload
    def generateCertPath(self, p0: InputStream) -> CertPath: ...
    @overload
    def generateCertPath(self, p0: InputStream, p1: str) -> CertPath: ...
    def getCertPathEncodings(self) -> Iterator: ...
    def generateCertificates(self, p0: InputStream) -> list: ...
    def generateCRL(self, p0: InputStream) -> CRL: ...
    def generateCRLs(self, p0: InputStream) -> list: ...
    def getProvider(self) -> Provider: ...
    @overload
    @staticmethod
    def getInstance(p0: str, p1: str) -> "CertificateFactory": ...
    @overload
    @staticmethod
    def getInstance(p0: str) -> "CertificateFactory": ...
    @overload
    @staticmethod
    def getInstance(p0: str, p1: Provider) -> "CertificateFactory": ...
    def getType(self) -> str: ...
