from typing import Any, ClassVar, overload
from java.io.OutputStream import OutputStream

class Extension:
    def isCritical(self) -> bool: ...
    def encode(self, p0: OutputStream) -> None: ...
    def getValue(self) -> Any: ...
    def getId(self) -> str: ...
