from typing import Any, ClassVar, overload
from java.security.cert.Certificate import Certificate

class PKIXCertPathChecker:
    def getSupportedExtensions(self) -> set: ...
    @overload
    def check(self, p0: Certificate, p1: list) -> None: ...
    @overload
    def check(self, p0: Certificate) -> None: ...
    def isForwardCheckingSupported(self) -> bool: ...
    def clone(self) -> Any: ...
    def init(self, p0: bool) -> None: ...
