from typing import Any, ClassVar, overload
from java.security.PublicKey import PublicKey
from java.security.cert.X509Certificate import X509Certificate
from javax.security.auth.x500.X500Principal import X500Principal

class TrustAnchor:
    @overload
    def __init__(self, p0: X509Certificate, p1: Any) -> None: ...
    @overload
    def __init__(self, p0: str, p1: PublicKey, p2: Any) -> None: ...
    @overload
    def __init__(self, p0: X500Principal, p1: PublicKey, p2: Any) -> None: ...
    def getTrustedCert(self) -> X509Certificate: ...
    def getCA(self) -> X500Principal: ...
    def getCAName(self) -> str: ...
    def getCAPublicKey(self) -> PublicKey: ...
    def getNameConstraints(self) -> Any: ...
    def toString(self) -> str: ...
