from typing import Any, ClassVar, overload
from java.net.CookiePolicy import CookiePolicy
from java.net.CookieStore import CookieStore
from java.net.URI import URI

class CookieManager:
    @overload
    def __init__(self, p0: CookieStore, p1: CookiePolicy) -> None: ...
    @overload
    def __init__(self) -> None: ...
    def setCookiePolicy(self, p0: CookiePolicy) -> None: ...
    def getCookieStore(self) -> CookieStore: ...
    def put(self, p0: URI, p1: dict) -> None: ...
    def get(self, p0: URI, p1: dict) -> dict: ...
