from typing import Any, ClassVar, overload
from java.net.CacheRequest import CacheRequest
from java.net.CacheResponse import CacheResponse
from java.net.URI import URI
from java.net.URLConnection import URLConnection

class ResponseCache:
    def __init__(self) -> None: ...
    def get(self, p0: URI, p1: str, p2: dict) -> CacheResponse: ...
    def put(self, p0: URI, p1: URLConnection) -> CacheRequest: ...
    @staticmethod
    def getDefault() -> "ResponseCache": ...
    @staticmethod
    def setDefault(p0: "ResponseCache") -> None: ...
