from typing import Any, ClassVar, overload
from java.security.spec.NamedParameterSpec import NamedParameterSpec

class EdECPrivateKeySpec:
    def __init__(self, p0: NamedParameterSpec, p1: Any) -> None: ...
    def getBytes(self) -> Any: ...
    def getParams(self) -> NamedParameterSpec: ...
