from typing import Any, ClassVar, overload
from android.hardware.input.HostUsiVersion import HostUsiVersion
from android.os.Handler import Handler
from android.view.Display import Display
from android.view.InputDevice import InputDevice
from android.view.InputEvent import InputEvent
from android.view.VerifiedInputEvent import VerifiedInputEvent

class InputManager:
    ACTION_QUERY_KEYBOARD_LAYOUTS: ClassVar[str]
    META_DATA_KEYBOARD_LAYOUTS: ClassVar[str]
    def getInputDeviceIds(self) -> Any: ...
    def getInputDevice(self, p0: int) -> InputDevice: ...
    def getInputDeviceViewBehavior(self, p0: int) -> Any: ...
    def registerInputDeviceListener(self, p0: Any, p1: Handler) -> None: ...
    def unregisterInputDeviceListener(self, p0: Any) -> None: ...
    def getMaximumObscuringOpacityForTouch(self) -> float: ...
    def verifyInputEvent(self, p0: InputEvent) -> VerifiedInputEvent: ...
    def isStylusPointerIconEnabled(self) -> bool: ...
    def getHostUsiVersion(self, p0: Display) -> HostUsiVersion: ...

    class InputDeviceListener:
        def onInputDeviceAdded(self, p0: int) -> None: ...
        def onInputDeviceRemoved(self, p0: int) -> None: ...
        def onInputDeviceChanged(self, p0: int) -> None: ...
