from typing import Any, ClassVar, overload
from android.content.res.Resources import Resources
from android.graphics.drawable.Drawable import Drawable
from android.util.AttributeSet import AttributeSet
from org.xmlpull.v1.XmlPullParser import XmlPullParser

class LevelListDrawable:
    def __init__(self) -> None: ...
    def addLevel(self, p0: int, p1: int, p2: Drawable) -> None: ...
    def mutate(self) -> Drawable: ...
    def inflate(self, p0: Resources, p1: XmlPullParser, p2: AttributeSet, p3: Any) -> None: ...
