from typing import Any, ClassVar, overload
from java.text.CharacterIterator import CharacterIterator
from java.util.Locale import Locale

class BreakIterator:
    DONE: ClassVar[int]
    @overload
    @staticmethod
    def getWordInstance() -> "BreakIterator": ...
    @overload
    @staticmethod
    def getWordInstance(p0: Locale) -> "BreakIterator": ...
    @overload
    @staticmethod
    def getLineInstance() -> "BreakIterator": ...
    @overload
    @staticmethod
    def getLineInstance(p0: Locale) -> "BreakIterator": ...
    @overload
    @staticmethod
    def getCharacterInstance(p0: Locale) -> "BreakIterator": ...
    @overload
    @staticmethod
    def getCharacterInstance() -> "BreakIterator": ...
    @overload
    @staticmethod
    def getSentenceInstance() -> "BreakIterator": ...
    @overload
    @staticmethod
    def getSentenceInstance(p0: Locale) -> "BreakIterator": ...
    def following(self, p0: int) -> int: ...
    def preceding(self, p0: int) -> int: ...
    def isBoundary(self, p0: int) -> bool: ...
    def getText(self) -> CharacterIterator: ...
    @overload
    def setText(self, p0: CharacterIterator) -> None: ...
    @overload
    def setText(self, p0: str) -> None: ...
    @staticmethod
    def getAvailableLocales() -> Any: ...
    def previous(self) -> int: ...
    def clone(self) -> Any: ...
    @overload
    def next(self) -> int: ...
    @overload
    def next(self, p0: int) -> int: ...
    def last(self) -> int: ...
    def first(self) -> int: ...
    def current(self) -> int: ...
