from typing import Any, ClassVar, overload

class CollationKey:
    def getSourceString(self) -> str: ...
    def toByteArray(self) -> Any: ...
    @overload
    def compareTo(self, p0: Any) -> int: ...
    @overload
    def compareTo(self, p0: "CollationKey") -> int: ...
