from typing import Any, ClassVar, overload
from java.lang.StringBuffer import StringBuffer
from java.math.RoundingMode import RoundingMode
from java.text.AttributedCharacterIterator import AttributedCharacterIterator
from java.text.DecimalFormatSymbols import DecimalFormatSymbols
from java.text.FieldPosition import FieldPosition
from java.text.ParsePosition import ParsePosition
from java.util.Currency import Currency

class DecimalFormat:
    INTEGER_FIELD: ClassVar[int]
    FRACTION_FIELD: ClassVar[int]
    @overload
    def __init__(self, p0: str) -> None: ...
    @overload
    def __init__(self, p0: str, p1: DecimalFormatSymbols) -> None: ...
    @overload
    def __init__(self) -> None: ...
    def applyLocalizedPattern(self, p0: str) -> None: ...
    def setDecimalFormatSymbols(self, p0: DecimalFormatSymbols) -> None: ...
    def getPositivePrefix(self) -> str: ...
    def setPositivePrefix(self, p0: str) -> None: ...
    def getNegativePrefix(self) -> str: ...
    def setNegativePrefix(self, p0: str) -> None: ...
    def getPositiveSuffix(self) -> str: ...
    def setPositiveSuffix(self, p0: str) -> None: ...
    def getNegativeSuffix(self) -> str: ...
    def setNegativeSuffix(self, p0: str) -> None: ...
    def getMultiplier(self) -> int: ...
    def setMultiplier(self, p0: int) -> None: ...
    def applyPattern(self, p0: str) -> None: ...
    def toPattern(self) -> str: ...
    def getGroupingSize(self) -> int: ...
    def setGroupingSize(self, p0: int) -> None: ...
    def isDecimalSeparatorAlwaysShown(self) -> bool: ...
    def setDecimalSeparatorAlwaysShown(self, p0: bool) -> None: ...
    def isParseBigDecimal(self) -> bool: ...
    def setParseBigDecimal(self, p0: bool) -> None: ...
    def toLocalizedPattern(self) -> str: ...
    def formatToCharacterIterator(self, p0: Any) -> AttributedCharacterIterator: ...
    def getDecimalFormatSymbols(self) -> DecimalFormatSymbols: ...
    def setGroupingUsed(self, p0: bool) -> None: ...
    def getMaximumIntegerDigits(self) -> int: ...
    def setMaximumIntegerDigits(self, p0: int) -> None: ...
    def getMinimumIntegerDigits(self) -> int: ...
    def setMinimumIntegerDigits(self, p0: int) -> None: ...
    def getMaximumFractionDigits(self) -> int: ...
    def setMaximumFractionDigits(self, p0: int) -> None: ...
    def getMinimumFractionDigits(self) -> int: ...
    def setMinimumFractionDigits(self, p0: int) -> None: ...
    def getCurrency(self) -> Currency: ...
    def getRoundingMode(self) -> RoundingMode: ...
    def setRoundingMode(self, p0: RoundingMode) -> None: ...
    def setCurrency(self, p0: Currency) -> None: ...
    def equals(self, p0: Any) -> bool: ...
    def hashCode(self) -> int: ...
    def clone(self) -> Any: ...
    @overload
    def format(self, p0: float, p1: StringBuffer, p2: FieldPosition) -> StringBuffer: ...
    @overload
    def format(self, p0: Any, p1: StringBuffer, p2: FieldPosition) -> StringBuffer: ...
    @overload
    def format(self, p0: int, p1: StringBuffer, p2: FieldPosition) -> StringBuffer: ...
    def parse(self, p0: str, p1: ParsePosition) -> float: ...
