from typing import Any, ClassVar, overload
from java.lang.StringBuffer import StringBuffer
from java.text.AttributedCharacterIterator import AttributedCharacterIterator
from java.text.FieldPosition import FieldPosition
from java.text.Format import Format
from java.text.ParsePosition import ParsePosition
from java.util.Locale import Locale

class MessageFormat:
    @overload
    def __init__(self, p0: str) -> None: ...
    @overload
    def __init__(self, p0: str, p1: Locale) -> None: ...
    def setFormatsByArgumentIndex(self, p0: Any) -> None: ...
    def setFormats(self, p0: Any) -> None: ...
    def setFormatByArgumentIndex(self, p0: int, p1: Format) -> None: ...
    def getFormatsByArgumentIndex(self) -> Any: ...
    def getFormats(self) -> Any: ...
    def applyPattern(self, p0: str) -> None: ...
    def toPattern(self) -> str: ...
    def parseObject(self, p0: str, p1: ParsePosition) -> Any: ...
    def formatToCharacterIterator(self, p0: Any) -> AttributedCharacterIterator: ...
    def getLocale(self) -> Locale: ...
    def setLocale(self, p0: Locale) -> None: ...
    def setFormat(self, p0: int, p1: Format) -> None: ...
    def equals(self, p0: Any) -> bool: ...
    def hashCode(self) -> int: ...
    def clone(self) -> Any: ...
    @overload
    @staticmethod
    def format(p0: str, p1: Any) -> str: ...
    @overload
    def format(self, p0: Any, p1: StringBuffer, p2: FieldPosition) -> StringBuffer: ...
    @overload
    def format(self, p0: Any, p1: StringBuffer, p2: FieldPosition) -> StringBuffer: ...
    @overload
    def parse(self, p0: str) -> Any: ...
    @overload
    def parse(self, p0: str, p1: ParsePosition) -> Any: ...

    class Field:
        ARGUMENT: ClassVar[Any]
        LANGUAGE: ClassVar[Any]
        READING: ClassVar[Any]
        INPUT_METHOD_SEGMENT: ClassVar[Any]
