# cython: language_level=3
# Generated by jni-wrap cython — do not edit by hand.
from jni_core._core cimport JavaObject
from jni_core.jni cimport (
    JNIEnv, jobject, jstring,
    jboolean, jbyte, jchar, jshort, jint, jlong, jfloat, jdouble,
)

cdef class VirtualViewFillInfo(JavaObject):
    cdef jobject _getAutofillHints(self, JNIEnv* env) except? NULL
    cdef jobject _getAutofillHints_0(self, JNIEnv* env) except? NULL

cdef class Builder(JavaObject):
    cdef jobject _build(self, JNIEnv* env) except? NULL
    cdef jobject _build_0(self, JNIEnv* env) except? NULL
    cdef jobject _setAutofillHints(self, JNIEnv* env, jobject p0) except? NULL
    cdef jobject _setAutofillHints_0(self, JNIEnv* env, jobject p0) except? NULL
