from typing import Any, ClassVar, overload
from android.content.om.OverlayManagerTransaction import OverlayManagerTransaction

class OverlayManager:
    def getOverlayInfosForTarget(self, p0: str) -> list: ...
    def commit(self, p0: OverlayManagerTransaction) -> None: ...

from typing import Any, ClassVar, overload
from android.content.om.OverlayIdentifier import OverlayIdentifier
from android.os.Parcel import Parcel

class OverlayInfo:
    CREATOR: ClassVar[Any]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    def getTargetOverlayableName(self) -> str: ...
    def getTargetPackageName(self) -> str: ...
    def getOverlayIdentifier(self) -> OverlayIdentifier: ...
    def getOverlayName(self) -> str: ...
    def equals(self, p0: Any) -> bool: ...
    def toString(self) -> str: ...
    def hashCode(self) -> int: ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...

from typing import Any, ClassVar, overload
from android.content.om.OverlayIdentifier import OverlayIdentifier
from android.content.res.AssetFileDescriptor import AssetFileDescriptor
from android.os.ParcelFileDescriptor import ParcelFileDescriptor

class FabricatedOverlay:
    def __init__(self, p0: str, p1: str) -> None: ...
    @overload
    def setResourceValue(self, p0: str, p1: AssetFileDescriptor, p2: str) -> None: ...
    @overload
    def setResourceValue(self, p0: str, p1: int, p2: int, p3: str) -> None: ...
    @overload
    def setResourceValue(self, p0: str, p1: int, p2: str, p3: str) -> None: ...
    @overload
    def setResourceValue(self, p0: str, p1: ParcelFileDescriptor, p2: str) -> None: ...
    def setNinePatchResourceValue(self, p0: str, p1: ParcelFileDescriptor, p2: str) -> None: ...
    def setTargetOverlayable(self, p0: str) -> None: ...
    def getIdentifier(self) -> OverlayIdentifier: ...

from typing import Any, ClassVar, overload
from android.content.om.FabricatedOverlay import FabricatedOverlay
from android.content.om.OverlayIdentifier import OverlayIdentifier
from android.os.Parcel import Parcel

class OverlayManagerTransaction:
    CREATOR: ClassVar[Any]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    def registerFabricatedOverlay(self, p0: FabricatedOverlay) -> None: ...
    def unregisterFabricatedOverlay(self, p0: OverlayIdentifier) -> None: ...
    def toString(self) -> str: ...
    @staticmethod
    def newInstance() -> "OverlayManagerTransaction": ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...

from typing import Any, ClassVar, overload
from android.os.Parcel import Parcel

class OverlayIdentifier:
    CREATOR: ClassVar[Any]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    def equals(self, p0: Any) -> bool: ...
    def toString(self) -> str: ...
    def hashCode(self) -> int: ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...

