from typing import Any, ClassVar, overload
from android.content.Context import Context
from android.os.Parcel import Parcel

class RestrictionEntry:
    CREATOR: ClassVar[Any]
    TYPE_BOOLEAN: ClassVar[int]
    TYPE_BUNDLE: ClassVar[int]
    TYPE_BUNDLE_ARRAY: ClassVar[int]
    TYPE_CHOICE: ClassVar[int]
    TYPE_INTEGER: ClassVar[int]
    TYPE_MULTI_SELECT: ClassVar[int]
    TYPE_NULL: ClassVar[int]
    TYPE_STRING: ClassVar[int]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    @overload
    def __init__(self, p0: str, p1: Any) -> None: ...
    @overload
    def __init__(self, p0: str, p1: str) -> None: ...
    @overload
    def __init__(self, p0: str, p1: int) -> None: ...
    @overload
    def __init__(self, p0: Parcel) -> None: ...
    @overload
    def __init__(self, p0: int, p1: str) -> None: ...
    @overload
    def __init__(self, p0: str, p1: bool) -> None: ...
    def equals(self, p0: Any) -> bool: ...
    def toString(self) -> str: ...
    def hashCode(self) -> int: ...
    def getKey(self) -> str: ...
    def getType(self) -> int: ...
    def getTitle(self) -> str: ...
    def setTitle(self, p0: str) -> None: ...
    def setDescription(self, p0: str) -> None: ...
    @staticmethod
    def createBundleEntry(p0: str, p1: Any) -> "RestrictionEntry": ...
    def getAllSelectedStrings(self) -> Any: ...
    def getChoiceEntries(self) -> Any: ...
    def getChoiceValues(self) -> Any: ...
    def getIntValue(self) -> int: ...
    def getRestrictions(self) -> Any: ...
    def getSelectedState(self) -> bool: ...
    @staticmethod
    def createBundleArrayEntry(p0: str, p1: Any) -> "RestrictionEntry": ...
    def setIntValue(self, p0: int) -> None: ...
    def setRestrictions(self, p0: Any) -> None: ...
    def setSelectedState(self, p0: bool) -> None: ...
    def setSelectedString(self, p0: str) -> None: ...
    def getSelectedString(self) -> str: ...
    def setAllSelectedStrings(self, p0: Any) -> None: ...
    @overload
    def setChoiceEntries(self, p0: Context, p1: int) -> None: ...
    @overload
    def setChoiceEntries(self, p0: Any) -> None: ...
    @overload
    def setChoiceValues(self, p0: Any) -> None: ...
    @overload
    def setChoiceValues(self, p0: Context, p1: int) -> None: ...
    def setType(self, p0: int) -> None: ...
    def getDescription(self) -> str: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
    def describeContents(self) -> int: ...
