from typing import Any, ClassVar, overload
from android.os.Parcel import Parcel

class SyncAdapterType:
    CREATOR: ClassVar[Any]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    accountType: str
    authority: str
    isKey: bool
    @overload
    def __init__(self, p0: Parcel) -> None: ...
    @overload
    def __init__(self, p0: str, p1: str, p2: bool, p3: bool) -> None: ...
    def equals(self, p0: Any) -> bool: ...
    def toString(self) -> str: ...
    def hashCode(self) -> int: ...
    def allowParallelSyncs(self) -> bool: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
    def describeContents(self) -> int: ...
    def supportsUploading(self) -> bool: ...
    def isAlwaysSyncable(self) -> bool: ...
    def getSettingsActivity(self) -> str: ...
    def isUserVisible(self) -> bool: ...
    @staticmethod
    def newKey(p0: str, p1: str) -> "SyncAdapterType": ...
