# cython: language_level=3
# Generated by pyjnius-wrap cython — do not edit by hand.

from jni_core._core cimport (
    JavaObject, get_env, check_jni_exc,
    find_class_global, get_method_id, get_static_method_id,
    get_field_id, get_static_field_id, j_str, py_str,
)
from jni_core._dispatch cimport (
    jnicore_NewObjectA, jnicore_DeleteLocalRef,
    jnicore_CallVoidMethodA, jnicore_CallObjectMethodA,
    jnicore_CallBooleanMethodA, jnicore_CallByteMethodA,
    jnicore_CallCharMethodA, jnicore_CallShortMethodA,
    jnicore_CallIntMethodA, jnicore_CallLongMethodA,
    jnicore_CallFloatMethodA, jnicore_CallDoubleMethodA,
    jnicore_CallStaticVoidMethodA, jnicore_CallStaticObjectMethodA,
    jnicore_CallStaticBooleanMethodA, jnicore_CallStaticByteMethodA,
    jnicore_CallStaticCharMethodA, jnicore_CallStaticShortMethodA,
    jnicore_CallStaticIntMethodA, jnicore_CallStaticLongMethodA,
    jnicore_CallStaticFloatMethodA, jnicore_CallStaticDoubleMethodA,
    jnicore_GetObjectField, jnicore_SetObjectField,
    jnicore_GetBooleanField, jnicore_SetBooleanField,
    jnicore_GetByteField, jnicore_SetByteField,
    jnicore_GetCharField, jnicore_SetCharField,
    jnicore_GetShortField, jnicore_SetShortField,
    jnicore_GetIntField, jnicore_SetIntField,
    jnicore_GetLongField, jnicore_SetLongField,
    jnicore_GetFloatField, jnicore_SetFloatField,
    jnicore_GetDoubleField, jnicore_SetDoubleField,
    jnicore_GetStaticObjectField, jnicore_SetStaticObjectField,
    jnicore_GetStaticBooleanField, jnicore_SetStaticBooleanField,
    jnicore_GetStaticByteField, jnicore_SetStaticByteField,
    jnicore_GetStaticCharField, jnicore_SetStaticCharField,
    jnicore_GetStaticShortField, jnicore_SetStaticShortField,
    jnicore_GetStaticIntField, jnicore_SetStaticIntField,
    jnicore_GetStaticLongField, jnicore_SetStaticLongField,
    jnicore_GetStaticFloatField, jnicore_SetStaticFloatField,
    jnicore_GetStaticDoubleField, jnicore_SetStaticDoubleField,
)
from jni_core.jni cimport (
    jclass, jobject, jmethodID, jfieldID, jvalue, JNIEnv,
    jboolean, jbyte, jchar, jshort, jint, jlong, jfloat, jdouble, jstring,
)

include "jni_core/conversions.pxi"

__javaclass__ = "android/adservices/customaudience/PartialCustomAudience"  # android.adservices.customaudience.PartialCustomAudience

cdef jclass _cls_PartialCustomAudience = NULL
cdef jmethodID _m_PartialCustomAudience_getActivationTime_0 = NULL
cdef jmethodID _m_PartialCustomAudience_getExpirationTime_0 = NULL
cdef jmethodID _m_PartialCustomAudience_getUserBiddingSignals_0 = NULL
cdef jmethodID _m_PartialCustomAudience_getName_0 = NULL
cdef jmethodID _m_PartialCustomAudience_equals_0 = NULL
cdef jmethodID _m_PartialCustomAudience_toString_0 = NULL
cdef jmethodID _m_PartialCustomAudience_hashCode_0 = NULL
cdef jmethodID _m_PartialCustomAudience_describeContents_0 = NULL
cdef jmethodID _m_PartialCustomAudience_writeToParcel_0 = NULL
cdef jfieldID _sf_PartialCustomAudience_CREATOR = NULL
cdef jfieldID _sf_PartialCustomAudience_CONTENTS_FILE_DESCRIPTOR = NULL
cdef jfieldID _sf_PartialCustomAudience_PARCELABLE_WRITE_RETURN_VALUE = NULL

cdef int _ensure_ids_PartialCustomAudience(JNIEnv* env) except -1:
    global _cls_PartialCustomAudience, _m_PartialCustomAudience_getActivationTime_0, _m_PartialCustomAudience_getExpirationTime_0, _m_PartialCustomAudience_getUserBiddingSignals_0, _m_PartialCustomAudience_getName_0, _m_PartialCustomAudience_equals_0, _m_PartialCustomAudience_toString_0, _m_PartialCustomAudience_hashCode_0, _m_PartialCustomAudience_describeContents_0, _m_PartialCustomAudience_writeToParcel_0, _sf_PartialCustomAudience_CREATOR, _sf_PartialCustomAudience_CONTENTS_FILE_DESCRIPTOR, _sf_PartialCustomAudience_PARCELABLE_WRITE_RETURN_VALUE
    if _cls_PartialCustomAudience != NULL:
        return 0
    _cls_PartialCustomAudience = find_class_global(env, b"android/adservices/customaudience/PartialCustomAudience")
    _m_PartialCustomAudience_getActivationTime_0 = get_method_id(env, _cls_PartialCustomAudience, b"getActivationTime", b"()Ljava/time/Instant;")
    _m_PartialCustomAudience_getExpirationTime_0 = get_method_id(env, _cls_PartialCustomAudience, b"getExpirationTime", b"()Ljava/time/Instant;")
    _m_PartialCustomAudience_getUserBiddingSignals_0 = get_method_id(env, _cls_PartialCustomAudience, b"getUserBiddingSignals", b"()Landroid/adservices/common/AdSelectionSignals;")
    _m_PartialCustomAudience_getName_0 = get_method_id(env, _cls_PartialCustomAudience, b"getName", b"()Ljava/lang/String;")
    _m_PartialCustomAudience_equals_0 = get_method_id(env, _cls_PartialCustomAudience, b"equals", b"(Ljava/lang/Object;)Z")
    _m_PartialCustomAudience_toString_0 = get_method_id(env, _cls_PartialCustomAudience, b"toString", b"()Ljava/lang/String;")
    _m_PartialCustomAudience_hashCode_0 = get_method_id(env, _cls_PartialCustomAudience, b"hashCode", b"()I")
    _m_PartialCustomAudience_describeContents_0 = get_method_id(env, _cls_PartialCustomAudience, b"describeContents", b"()I")
    _m_PartialCustomAudience_writeToParcel_0 = get_method_id(env, _cls_PartialCustomAudience, b"writeToParcel", b"(Landroid/os/Parcel;I)V")
    _sf_PartialCustomAudience_CREATOR = get_static_field_id(env, _cls_PartialCustomAudience, b"CREATOR", b"Landroid/os/Parcelable$Creator;")
    _sf_PartialCustomAudience_CONTENTS_FILE_DESCRIPTOR = get_static_field_id(env, _cls_PartialCustomAudience, b"CONTENTS_FILE_DESCRIPTOR", b"I")
    _sf_PartialCustomAudience_PARCELABLE_WRITE_RETURN_VALUE = get_static_field_id(env, _cls_PartialCustomAudience, b"PARCELABLE_WRITE_RETURN_VALUE", b"I")
    return 0

cdef class PartialCustomAudience(JavaObject):
    """android.adservices.customaudience.PartialCustomAudience"""

    def __init__(self, *args, **kwargs):
        raise TypeError("PartialCustomAudience has no public constructor")

    # Static field PartialCustomAudience.CREATOR
    @staticmethod
    def CREATOR() -> object:
        cdef JNIEnv* env = get_env()
        _ensure_ids_PartialCustomAudience(env)
        cdef jobject _ret = jnicore_GetStaticObjectField(env, _cls_PartialCustomAudience, _sf_PartialCustomAudience_CREATOR)
        check_jni_exc(env)
        if _ret == NULL:
            return None
        cdef JavaObject _wrapped = JavaObject.__new__(JavaObject)
        _wrapped._adopt_local(env, _ret)
        return _wrapped

    # Static field PartialCustomAudience.CONTENTS_FILE_DESCRIPTOR
    @staticmethod
    def CONTENTS_FILE_DESCRIPTOR() -> int:
        cdef JNIEnv* env = get_env()
        _ensure_ids_PartialCustomAudience(env)
        cdef jint _ret = jnicore_GetStaticIntField(env, _cls_PartialCustomAudience, _sf_PartialCustomAudience_CONTENTS_FILE_DESCRIPTOR)
        check_jni_exc(env)
        return <int>_ret

    # Static field PartialCustomAudience.PARCELABLE_WRITE_RETURN_VALUE
    @staticmethod
    def PARCELABLE_WRITE_RETURN_VALUE() -> int:
        cdef JNIEnv* env = get_env()
        _ensure_ids_PartialCustomAudience(env)
        cdef jint _ret = jnicore_GetStaticIntField(env, _cls_PartialCustomAudience, _sf_PartialCustomAudience_PARCELABLE_WRITE_RETURN_VALUE)
        check_jni_exc(env)
        return <int>_ret

    cdef jobject _getActivationTime(self) except? NULL:
        cdef JNIEnv* env = get_env()
        _ensure_ids_PartialCustomAudience(env)
        cdef jvalue _args[1]  # zero-arg call; _args ignored by JNI
        cdef jobject _ret = jnicore_CallObjectMethodA(env, self._handle, _m_PartialCustomAudience_getActivationTime_0, _args)
        check_jni_exc(env)
        return _ret

    def getActivationTime(self) -> object:
        cdef JNIEnv* env = get_env()
        cdef jobject _ret = NULL
        _ret = self._getActivationTime()
        if _ret == NULL:
            return None
        cdef JavaObject _wrapped = JavaObject.__new__(JavaObject)
        _wrapped._adopt_local(env, _ret)
        return _wrapped

    cdef jobject _getExpirationTime(self) except? NULL:
        cdef JNIEnv* env = get_env()
        _ensure_ids_PartialCustomAudience(env)
        cdef jvalue _args[1]  # zero-arg call; _args ignored by JNI
        cdef jobject _ret = jnicore_CallObjectMethodA(env, self._handle, _m_PartialCustomAudience_getExpirationTime_0, _args)
        check_jni_exc(env)
        return _ret

    def getExpirationTime(self) -> object:
        cdef JNIEnv* env = get_env()
        cdef jobject _ret = NULL
        _ret = self._getExpirationTime()
        if _ret == NULL:
            return None
        cdef JavaObject _wrapped = JavaObject.__new__(JavaObject)
        _wrapped._adopt_local(env, _ret)
        return _wrapped

    cdef jobject _getUserBiddingSignals(self) except? NULL:
        cdef JNIEnv* env = get_env()
        _ensure_ids_PartialCustomAudience(env)
        cdef jvalue _args[1]  # zero-arg call; _args ignored by JNI
        cdef jobject _ret = jnicore_CallObjectMethodA(env, self._handle, _m_PartialCustomAudience_getUserBiddingSignals_0, _args)
        check_jni_exc(env)
        return _ret

    def getUserBiddingSignals(self) -> object:
        cdef JNIEnv* env = get_env()
        cdef jobject _ret = NULL
        _ret = self._getUserBiddingSignals()
        if _ret == NULL:
            return None
        cdef JavaObject _wrapped = JavaObject.__new__(JavaObject)
        _wrapped._adopt_local(env, _ret)
        return _wrapped

    cdef jstring _getName(self) except? NULL:
        cdef JNIEnv* env = get_env()
        _ensure_ids_PartialCustomAudience(env)
        cdef jvalue _args[1]  # zero-arg call; _args ignored by JNI
        cdef jstring _ret = <jstring>jnicore_CallObjectMethodA(env, self._handle, _m_PartialCustomAudience_getName_0, _args)
        check_jni_exc(env)
        return <jstring>_ret

    def getName(self) -> str:
        cdef JNIEnv* env = get_env()
        cdef jstring _ret = NULL
        _ret = self._getName()
        return py_str(env, _ret)

    cdef jboolean _equals(self, jobject p0) except *:
        cdef JNIEnv* env = get_env()
        _ensure_ids_PartialCustomAudience(env)
        cdef jvalue _args[1]
        _args[0].l = p0
        cdef jboolean _ret = jnicore_CallBooleanMethodA(env, self._handle, _m_PartialCustomAudience_equals_0, _args)
        check_jni_exc(env)
        return _ret

    def equals(self, p0) -> bool:
        cdef JNIEnv* env = get_env()
        cdef jboolean _ret = 0
        cdef jobject _h0 = (<JavaObject?>p0)._handle if p0 is not None else <jobject>NULL
        _ret = self._equals(_h0)
        return jboolean_to_py(_ret)

    cdef jstring _toString(self) except? NULL:
        cdef JNIEnv* env = get_env()
        _ensure_ids_PartialCustomAudience(env)
        cdef jvalue _args[1]  # zero-arg call; _args ignored by JNI
        cdef jstring _ret = <jstring>jnicore_CallObjectMethodA(env, self._handle, _m_PartialCustomAudience_toString_0, _args)
        check_jni_exc(env)
        return <jstring>_ret

    def toString(self) -> str:
        cdef JNIEnv* env = get_env()
        cdef jstring _ret = NULL
        _ret = self._toString()
        return py_str(env, _ret)

    cdef jint _hashCode(self) except *:
        cdef JNIEnv* env = get_env()
        _ensure_ids_PartialCustomAudience(env)
        cdef jvalue _args[1]  # zero-arg call; _args ignored by JNI
        cdef jint _ret = jnicore_CallIntMethodA(env, self._handle, _m_PartialCustomAudience_hashCode_0, _args)
        check_jni_exc(env)
        return _ret

    def hashCode(self) -> int:
        cdef JNIEnv* env = get_env()
        cdef jint _ret = 0
        _ret = self._hashCode()
        return <int>_ret

    cdef jint _describeContents(self) except *:
        cdef JNIEnv* env = get_env()
        _ensure_ids_PartialCustomAudience(env)
        cdef jvalue _args[1]  # zero-arg call; _args ignored by JNI
        cdef jint _ret = jnicore_CallIntMethodA(env, self._handle, _m_PartialCustomAudience_describeContents_0, _args)
        check_jni_exc(env)
        return _ret

    def describeContents(self) -> int:
        cdef JNIEnv* env = get_env()
        cdef jint _ret = 0
        _ret = self._describeContents()
        return <int>_ret

    cdef void _writeToParcel(self, jobject p0, jint p1) except *:
        cdef JNIEnv* env = get_env()
        _ensure_ids_PartialCustomAudience(env)
        cdef jvalue _args[2]
        _args[0].l = p0
        _args[1].i = p1
        jnicore_CallVoidMethodA(env, self._handle, _m_PartialCustomAudience_writeToParcel_0, _args)
        check_jni_exc(env)

    def writeToParcel(self, p0, p1) -> None:
        cdef JNIEnv* env = get_env()
        cdef jobject _h0 = (<JavaObject?>p0)._handle if p0 is not None else <jobject>NULL
        cdef jint _c1 = py_to_jint(p1)
        self._writeToParcel(_h0, _c1)

# Nested class: android.adservices.customaudience.PartialCustomAudience$Builder  (JNI: android/adservices/customaudience/PartialCustomAudience$Builder)
cdef jclass _cls_Builder = NULL
cdef jmethodID _ctor_Builder_0 = NULL
cdef jmethodID _m_Builder_setActivationTime_0 = NULL
cdef jmethodID _m_Builder_setUserBiddingSignals_0 = NULL
cdef jmethodID _m_Builder_setExpirationTime_0 = NULL
cdef jmethodID _m_Builder_build_0 = NULL

cdef int _ensure_ids_Builder(JNIEnv* env) except -1:
    global _cls_Builder, _ctor_Builder_0, _m_Builder_setActivationTime_0, _m_Builder_setUserBiddingSignals_0, _m_Builder_setExpirationTime_0, _m_Builder_build_0
    if _cls_Builder != NULL:
        return 0
    _cls_Builder = find_class_global(env, b"android/adservices/customaudience/PartialCustomAudience$Builder")
    _ctor_Builder_0 = get_method_id(env, _cls_Builder, b"<init>", b"(Ljava/lang/String;)V")
    _m_Builder_setActivationTime_0 = get_method_id(env, _cls_Builder, b"setActivationTime", b"(Ljava/time/Instant;)Landroid/adservices/customaudience/PartialCustomAudience$Builder;")
    _m_Builder_setUserBiddingSignals_0 = get_method_id(env, _cls_Builder, b"setUserBiddingSignals", b"(Landroid/adservices/common/AdSelectionSignals;)Landroid/adservices/customaudience/PartialCustomAudience$Builder;")
    _m_Builder_setExpirationTime_0 = get_method_id(env, _cls_Builder, b"setExpirationTime", b"(Ljava/time/Instant;)Landroid/adservices/customaudience/PartialCustomAudience$Builder;")
    _m_Builder_build_0 = get_method_id(env, _cls_Builder, b"build", b"()Landroid/adservices/customaudience/PartialCustomAudience;")
    return 0

cdef class Builder(JavaObject):
    """android.adservices.customaudience.PartialCustomAudience$Builder"""

    def __init__(self, p0):
        cdef JNIEnv* env = get_env()
        _ensure_ids_Builder(env)
        cdef jvalue _args[1]
        cdef jstring _arg0_s = NULL
        _arg0_s = j_str(env, p0) if p0 is not None else <jstring>NULL
        _args[0].l = <jobject>_arg0_s
        cdef jobject _ret = jnicore_NewObjectA(env, _cls_Builder, _ctor_Builder_0, _args)
        if _arg0_s != NULL:
            jnicore_DeleteLocalRef(env, <jobject>_arg0_s)
        check_jni_exc(env)
        self._adopt_local(env, _ret)

    cdef jobject _setActivationTime(self, jobject p0) except? NULL:
        cdef JNIEnv* env = get_env()
        _ensure_ids_Builder(env)
        cdef jvalue _args[1]
        _args[0].l = p0
        cdef jobject _ret = jnicore_CallObjectMethodA(env, self._handle, _m_Builder_setActivationTime_0, _args)
        check_jni_exc(env)
        return _ret

    def setActivationTime(self, p0) -> object:
        cdef JNIEnv* env = get_env()
        cdef jobject _ret = NULL
        cdef jobject _h0 = (<JavaObject?>p0)._handle if p0 is not None else <jobject>NULL
        _ret = self._setActivationTime(_h0)
        if _ret == NULL:
            return None
        cdef JavaObject _wrapped = JavaObject.__new__(JavaObject)
        _wrapped._adopt_local(env, _ret)
        return _wrapped

    cdef jobject _setUserBiddingSignals(self, jobject p0) except? NULL:
        cdef JNIEnv* env = get_env()
        _ensure_ids_Builder(env)
        cdef jvalue _args[1]
        _args[0].l = p0
        cdef jobject _ret = jnicore_CallObjectMethodA(env, self._handle, _m_Builder_setUserBiddingSignals_0, _args)
        check_jni_exc(env)
        return _ret

    def setUserBiddingSignals(self, p0) -> object:
        cdef JNIEnv* env = get_env()
        cdef jobject _ret = NULL
        cdef jobject _h0 = (<JavaObject?>p0)._handle if p0 is not None else <jobject>NULL
        _ret = self._setUserBiddingSignals(_h0)
        if _ret == NULL:
            return None
        cdef JavaObject _wrapped = JavaObject.__new__(JavaObject)
        _wrapped._adopt_local(env, _ret)
        return _wrapped

    cdef jobject _setExpirationTime(self, jobject p0) except? NULL:
        cdef JNIEnv* env = get_env()
        _ensure_ids_Builder(env)
        cdef jvalue _args[1]
        _args[0].l = p0
        cdef jobject _ret = jnicore_CallObjectMethodA(env, self._handle, _m_Builder_setExpirationTime_0, _args)
        check_jni_exc(env)
        return _ret

    def setExpirationTime(self, p0) -> object:
        cdef JNIEnv* env = get_env()
        cdef jobject _ret = NULL
        cdef jobject _h0 = (<JavaObject?>p0)._handle if p0 is not None else <jobject>NULL
        _ret = self._setExpirationTime(_h0)
        if _ret == NULL:
            return None
        cdef JavaObject _wrapped = JavaObject.__new__(JavaObject)
        _wrapped._adopt_local(env, _ret)
        return _wrapped

    cdef jobject _build(self) except? NULL:
        cdef JNIEnv* env = get_env()
        _ensure_ids_Builder(env)
        cdef jvalue _args[1]  # zero-arg call; _args ignored by JNI
        cdef jobject _ret = jnicore_CallObjectMethodA(env, self._handle, _m_Builder_build_0, _args)
        check_jni_exc(env)
        return _ret

    def build(self) -> object:
        cdef JNIEnv* env = get_env()
        cdef jobject _ret = NULL
        _ret = self._build()
        if _ret == NULL:
            return None
        cdef JavaObject _wrapped = JavaObject.__new__(JavaObject)
        _wrapped._adopt_local(env, _ret)
        return _wrapped

