from typing import Any, ClassVar, overload
from android.os.Parcel import Parcel

class Capability:
    CREATOR: ClassVar[Any]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    def getName(self) -> str: ...
    def equals(self, p0: Any) -> bool: ...
    def hashCode(self) -> int: ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...

    class Builder:
        def __init__(self, p0: str) -> None: ...
        def build(self) -> "Capability": ...
