from typing import Any, ClassVar, overload
from android.app.Person import Person
from android.app.appsearch.GenericDocument import GenericDocument
from android.content.ComponentName import ComponentName
from android.content.Context import Context
from android.content.Intent import Intent
from android.content.LocusId import LocusId
from android.content.pm.Capability import Capability
from android.content.pm.CapabilityParams import CapabilityParams
from android.graphics.drawable.Icon import Icon
from android.os.Parcel import Parcel
from android.os.PersistableBundle import PersistableBundle
from android.os.UserHandle import UserHandle

class ShortcutInfo:
    CREATOR: ClassVar[Any]
    DISABLED_REASON_APP_CHANGED: ClassVar[int]
    DISABLED_REASON_BACKUP_NOT_SUPPORTED: ClassVar[int]
    DISABLED_REASON_BY_APP: ClassVar[int]
    DISABLED_REASON_NOT_DISABLED: ClassVar[int]
    DISABLED_REASON_OTHER_RESTORE_ISSUE: ClassVar[int]
    DISABLED_REASON_SIGNATURE_MISMATCH: ClassVar[int]
    DISABLED_REASON_UNKNOWN: ClassVar[int]
    DISABLED_REASON_VERSION_LOWER: ClassVar[int]
    SHORTCUT_CATEGORY_CONVERSATION: ClassVar[str]
    SURFACE_LAUNCHER: ClassVar[int]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    def toString(self) -> str: ...
    def isEnabled(self) -> bool: ...
    def getPackage(self) -> str: ...
    def getId(self) -> str: ...
    def isPinned(self) -> bool: ...
    def getIntent(self) -> Intent: ...
    def getCategories(self) -> set: ...
    def getExtras(self) -> PersistableBundle: ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
    def isImmutable(self) -> bool: ...
    def getActivity(self) -> ComponentName: ...
    @staticmethod
    def createFromGenericDocument(p0: Context, p1: GenericDocument) -> "ShortcutInfo": ...
    def getLocusId(self) -> LocusId: ...
    def getShortLabel(self) -> str: ...
    def getLongLabel(self) -> str: ...
    def getDisabledMessage(self) -> str: ...
    def getDisabledReason(self) -> int: ...
    def getIntents(self) -> Any: ...
    def getRank(self) -> int: ...
    def getUserHandle(self) -> UserHandle: ...
    def getLastChangedTimestamp(self) -> int: ...
    def isCached(self) -> bool: ...
    def isDynamic(self) -> bool: ...
    def isDeclaredInManifest(self) -> bool: ...
    def hasKeyFieldsOnly(self) -> bool: ...
    def isExcludedFromSurfaces(self, p0: int) -> bool: ...
    def getExcludedFromSurfaces(self) -> int: ...
    def getCapabilities(self) -> list: ...
    def getCapabilityParams(self, p0: Capability) -> list: ...

    class Builder:
        def __init__(self, p0: Context, p1: str) -> None: ...
        def build(self) -> "ShortcutInfo": ...
        def setIntent(self, p0: Intent) -> Any: ...
        def setIcon(self, p0: Icon) -> Any: ...
        def setExtras(self, p0: PersistableBundle) -> Any: ...
        def setActivity(self, p0: ComponentName) -> Any: ...
        def setStartingTheme(self, p0: int) -> Any: ...
        def setShortLabel(self, p0: str) -> Any: ...
        def setLongLabel(self, p0: str) -> Any: ...
        def setDisabledMessage(self, p0: str) -> Any: ...
        def setCategories(self, p0: set) -> Any: ...
        def setIntents(self, p0: Any) -> Any: ...
        def setPerson(self, p0: Person) -> Any: ...
        def setPersons(self, p0: Any) -> Any: ...
        def setLongLived(self, p0: bool) -> Any: ...
        def setRank(self, p0: int) -> Any: ...
        def addCapabilityBinding(self, p0: Capability, p1: CapabilityParams) -> Any: ...
        def setLocusId(self, p0: LocusId) -> Any: ...
        def setExcludedFromSurfaces(self, p0: int) -> Any: ...
