from typing import Any, ClassVar, overload
from android.os.Parcel import Parcel

class Signature:
    CREATOR: ClassVar[Any]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    @overload
    def __init__(self, p0: Any) -> None: ...
    @overload
    def __init__(self, p0: str) -> None: ...
    def equals(self, p0: Any) -> bool: ...
    def hashCode(self) -> int: ...
    @overload
    def toChars(self, p0: Any, p1: Any) -> Any: ...
    @overload
    def toChars(self) -> Any: ...
    def toByteArray(self) -> Any: ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
    def toCharsString(self) -> str: ...
