from typing import Any, ClassVar, overload
from android.graphics.Bitmap import Bitmap
from android.net.Uri import Uri
from android.os.Bundle import Bundle
from android.os.Parcel import Parcel

class MediaDescription:
    BT_FOLDER_TYPE_ALBUMS: ClassVar[int]
    BT_FOLDER_TYPE_ARTISTS: ClassVar[int]
    BT_FOLDER_TYPE_GENRES: ClassVar[int]
    BT_FOLDER_TYPE_MIXED: ClassVar[int]
    BT_FOLDER_TYPE_PLAYLISTS: ClassVar[int]
    BT_FOLDER_TYPE_TITLES: ClassVar[int]
    BT_FOLDER_TYPE_YEARS: ClassVar[int]
    CREATOR: ClassVar[Any]
    EXTRA_BT_FOLDER_TYPE: ClassVar[str]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    def getIconUri(self) -> Uri: ...
    def getIconBitmap(self) -> Bitmap: ...
    def getMediaId(self) -> str: ...
    def equals(self, p0: Any) -> bool: ...
    def toString(self) -> str: ...
    def getMediaUri(self) -> Uri: ...
    def getSubtitle(self) -> str: ...
    def getTitle(self) -> str: ...
    def getExtras(self) -> Bundle: ...
    def getDescription(self) -> str: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
    def describeContents(self) -> int: ...

    class Builder:
        def __init__(self) -> None: ...
        def setMediaUri(self, p0: Uri) -> Any: ...
        def setMediaId(self, p0: str) -> Any: ...
        def setIconBitmap(self, p0: Bitmap) -> Any: ...
        def setIconUri(self, p0: Uri) -> Any: ...
        def setExtras(self, p0: Bundle) -> Any: ...
        def setSubtitle(self, p0: str) -> Any: ...
        def setTitle(self, p0: str) -> Any: ...
        def setDescription(self, p0: str) -> Any: ...
        def build(self) -> "MediaDescription": ...
