from typing import Any, ClassVar, overload

class MediaTimestamp:
    TIMESTAMP_UNKNOWN: ClassVar["MediaTimestamp"]
    def __init__(self, p0: int, p1: int, p2: float) -> None: ...
    def getAnchorMediaTimeUs(self) -> int: ...
    def getAnchorSystemNanoTime(self) -> int: ...
    def getAnchorSytemNanoTime(self) -> int: ...
    def getMediaClockRate(self) -> float: ...
    def equals(self, p0: Any) -> bool: ...
    def toString(self) -> str: ...
