from jnius import JavaClass, JavaInterface, MetaJavaClass, JavaMethod, JavaStaticMethod, JavaMultipleMethod, JavaField, JavaStaticField

class AmbientBacklightSettings(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "android/media/quality/AmbientBacklightSettings"
    __javaconstructor__ = [("(IIIIIZI)V", False)]
    CREATOR = JavaStaticField("Landroid/os/Parcelable$Creator;")
    SOURCE_AUDIO = JavaStaticField("I")
    SOURCE_AUDIO_VIDEO = JavaStaticField("I")
    SOURCE_NONE = JavaStaticField("I")
    SOURCE_VIDEO = JavaStaticField("I")
    CONTENTS_FILE_DESCRIPTOR = JavaStaticField("I")
    PARCELABLE_WRITE_RETURN_VALUE = JavaStaticField("I")
    isLetterboxOmitted = JavaMethod("()Z")
    getColorFormat = JavaMethod("()I")
    getMaxFps = JavaMethod("()I")
    getVerticalZonesCount = JavaMethod("()I")
    getHorizontalZonesCount = JavaMethod("()I")
    toString = JavaMethod("()Ljava/lang/String;")
    getThreshold = JavaMethod("()I")
    getSource = JavaMethod("()I")
    describeContents = JavaMethod("()I")
    writeToParcel = JavaMethod("(Landroid/os/Parcel;I)V")

class AmbientBacklightMetadata(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "android/media/quality/AmbientBacklightMetadata"
    __javaconstructor__ = [("(Ljava/lang/String;IIIII[I)V", False)]
    ALGORITHM_NONE = JavaStaticField("I")
    ALGORITHM_RLE = JavaStaticField("I")
    CREATOR = JavaStaticField("Landroid/os/Parcelable$Creator;")
    CONTENTS_FILE_DESCRIPTOR = JavaStaticField("I")
    PARCELABLE_WRITE_RETURN_VALUE = JavaStaticField("I")
    getColorFormat = JavaMethod("()I")
    getVerticalZonesCount = JavaMethod("()I")
    getHorizontalZonesCount = JavaMethod("()I")
    toString = JavaMethod("()Ljava/lang/String;")
    getPackageName = JavaMethod("()Ljava/lang/String;")
    getSource = JavaMethod("()I")
    describeContents = JavaMethod("()I")
    writeToParcel = JavaMethod("(Landroid/os/Parcel;I)V")
    getCompressionAlgorithm = JavaMethod("()I")
    getZoneColors = JavaMethod("()[I")

class PictureProfile(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "android/media/quality/PictureProfile"
    CREATOR = JavaStaticField("Landroid/os/Parcelable$Creator;")
    ERROR_DUPLICATE = JavaStaticField("I")
    ERROR_INVALID_ARGUMENT = JavaStaticField("I")
    ERROR_NOT_ALLOWLISTED = JavaStaticField("I")
    ERROR_NO_PERMISSION = JavaStaticField("I")
    ERROR_UNKNOWN = JavaStaticField("I")
    TYPE_APPLICATION = JavaStaticField("I")
    TYPE_SYSTEM = JavaStaticField("I")
    CONTENTS_FILE_DESCRIPTOR = JavaStaticField("I")
    PARCELABLE_WRITE_RETURN_VALUE = JavaStaticField("I")
    getProfileId = JavaMethod("()Ljava/lang/String;")
    getName = JavaMethod("()Ljava/lang/String;")
    getPackageName = JavaMethod("()Ljava/lang/String;")
    describeContents = JavaMethod("()I")
    writeToParcel = JavaMethod("(Landroid/os/Parcel;I)V")
    getParameters = JavaMethod("()Landroid/os/PersistableBundle;")
    getInputId = JavaMethod("()Ljava/lang/String;")
    getProfileType = JavaMethod("()I")

    class Builder(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "android/media/quality/PictureProfile$Builder"
        __javaconstructor__ = [("(Landroid/media/quality/PictureProfile;)V", False), ("(Ljava/lang/String;)V", False)]
        setParameters = JavaMethod("(Landroid/os/PersistableBundle;)Landroid/media/quality/PictureProfile$Builder;")
        build = JavaMethod("()Landroid/media/quality/PictureProfile;")

class MediaQualityContract(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "android/media/quality/MediaQualityContract"
    LEVEL_HIGH = JavaStaticField("Ljava/lang/String;")
    LEVEL_LOW = JavaStaticField("Ljava/lang/String;")
    LEVEL_MEDIUM = JavaStaticField("Ljava/lang/String;")
    LEVEL_OFF = JavaStaticField("Ljava/lang/String;")

    class SoundQuality(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "android/media/quality/MediaQualityContract$SoundQuality"
        PARAMETER_AUTO_VOLUME_CONTROL = JavaStaticField("Ljava/lang/String;")
        PARAMETER_BALANCE = JavaStaticField("Ljava/lang/String;")
        PARAMETER_BASS = JavaStaticField("Ljava/lang/String;")
        PARAMETER_DIALOGUE_ENHANCER = JavaStaticField("Ljava/lang/String;")
        PARAMETER_DIGITAL_OUTPUT_DELAY_MILLIS = JavaStaticField("Ljava/lang/String;")
        PARAMETER_DIGITAL_OUTPUT_MODE = JavaStaticField("Ljava/lang/String;")
        PARAMETER_DOLBY_AUDIO_PROCESSING_DOLBY_ATMOS = JavaStaticField("Ljava/lang/String;")
        PARAMETER_DOLBY_AUDIO_PROCESSING_SOUND_MODE = JavaStaticField("Ljava/lang/String;")
        PARAMETER_DOLBY_AUDIO_PROCESSING_SURROUND_VIRTUALIZER = JavaStaticField("Ljava/lang/String;")
        PARAMETER_DOLBY_AUDIO_PROCESSING_VOLUME_LEVELER = JavaStaticField("Ljava/lang/String;")
        PARAMETER_DOWN_MIX_MODE = JavaStaticField("Ljava/lang/String;")
        PARAMETER_DTS_DRC = JavaStaticField("Ljava/lang/String;")
        PARAMETER_DTS_VIRTUAL_X_DEFINITION = JavaStaticField("Ljava/lang/String;")
        PARAMETER_DTS_VIRTUAL_X_DIALOG_CLARITY = JavaStaticField("Ljava/lang/String;")
        PARAMETER_DTS_VIRTUAL_X_HEIGHT = JavaStaticField("Ljava/lang/String;")
        PARAMETER_DTS_VIRTUAL_X_LIMITER = JavaStaticField("Ljava/lang/String;")
        PARAMETER_DTS_VIRTUAL_X_TBHDX = JavaStaticField("Ljava/lang/String;")
        PARAMETER_DTS_VIRTUAL_X_TRU_SURROUND_X = JavaStaticField("Ljava/lang/String;")
        PARAMETER_DTS_VIRTUAL_X_TRU_VOLUME_HD = JavaStaticField("Ljava/lang/String;")
        PARAMETER_EARC = JavaStaticField("Ljava/lang/String;")
        PARAMETER_SPEAKERS = JavaStaticField("Ljava/lang/String;")
        PARAMETER_SPEAKERS_DELAY_MILLIS = JavaStaticField("Ljava/lang/String;")
        PARAMETER_SURROUND_SOUND = JavaStaticField("Ljava/lang/String;")
        PARAMETER_TREBLE = JavaStaticField("Ljava/lang/String;")

    class PictureQuality(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "android/media/quality/MediaQualityContract$PictureQuality"
        PARAMETER_AUTO_PICTURE_QUALITY_ENABLED = JavaStaticField("Ljava/lang/String;")
        PARAMETER_AUTO_SUPER_RESOLUTION_ENABLED = JavaStaticField("Ljava/lang/String;")
        PARAMETER_BLUE_STRETCH = JavaStaticField("Ljava/lang/String;")
        PARAMETER_BRIGHTNESS = JavaStaticField("Ljava/lang/String;")
        PARAMETER_COLOR_TEMPERATURE = JavaStaticField("Ljava/lang/String;")
        PARAMETER_COLOR_TUNE = JavaStaticField("Ljava/lang/String;")
        PARAMETER_COLOR_TUNER_BLUE_GAIN = JavaStaticField("Ljava/lang/String;")
        PARAMETER_COLOR_TUNER_BLUE_OFFSET = JavaStaticField("Ljava/lang/String;")
        PARAMETER_COLOR_TUNER_BRIGHTNESS = JavaStaticField("Ljava/lang/String;")
        PARAMETER_COLOR_TUNER_GREEN_GAIN = JavaStaticField("Ljava/lang/String;")
        PARAMETER_COLOR_TUNER_GREEN_OFFSET = JavaStaticField("Ljava/lang/String;")
        PARAMETER_COLOR_TUNER_HUE = JavaStaticField("Ljava/lang/String;")
        PARAMETER_COLOR_TUNER_RED_GAIN = JavaStaticField("Ljava/lang/String;")
        PARAMETER_COLOR_TUNER_RED_OFFSET = JavaStaticField("Ljava/lang/String;")
        PARAMETER_COLOR_TUNER_SATURATION = JavaStaticField("Ljava/lang/String;")
        PARAMETER_CONTRAST = JavaStaticField("Ljava/lang/String;")
        PARAMETER_DECONTOUR = JavaStaticField("Ljava/lang/String;")
        PARAMETER_DYNAMIC_LUMA_CONTROL = JavaStaticField("Ljava/lang/String;")
        PARAMETER_FILM_MODE = JavaStaticField("Ljava/lang/String;")
        PARAMETER_FLESH_TONE = JavaStaticField("Ljava/lang/String;")
        PARAMETER_GLOBAL_DIMMING = JavaStaticField("Ljava/lang/String;")
        PARAMETER_HUE = JavaStaticField("Ljava/lang/String;")
        PARAMETER_MPEG_NOISE_REDUCTION = JavaStaticField("Ljava/lang/String;")
        PARAMETER_NOISE_REDUCTION = JavaStaticField("Ljava/lang/String;")
        PARAMETER_SATURATION = JavaStaticField("Ljava/lang/String;")
        PARAMETER_SHARPNESS = JavaStaticField("Ljava/lang/String;")

class SoundProfile(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "android/media/quality/SoundProfile"
    CREATOR = JavaStaticField("Landroid/os/Parcelable$Creator;")
    ERROR_DUPLICATE = JavaStaticField("I")
    ERROR_INVALID_ARGUMENT = JavaStaticField("I")
    ERROR_NOT_ALLOWLISTED = JavaStaticField("I")
    ERROR_NO_PERMISSION = JavaStaticField("I")
    ERROR_UNKNOWN = JavaStaticField("I")
    TYPE_APPLICATION = JavaStaticField("I")
    TYPE_SYSTEM = JavaStaticField("I")
    CONTENTS_FILE_DESCRIPTOR = JavaStaticField("I")
    PARCELABLE_WRITE_RETURN_VALUE = JavaStaticField("I")
    getProfileId = JavaMethod("()Ljava/lang/String;")
    getName = JavaMethod("()Ljava/lang/String;")
    getPackageName = JavaMethod("()Ljava/lang/String;")
    describeContents = JavaMethod("()I")
    writeToParcel = JavaMethod("(Landroid/os/Parcel;I)V")
    getParameters = JavaMethod("()Landroid/os/PersistableBundle;")
    getInputId = JavaMethod("()Ljava/lang/String;")
    getProfileType = JavaMethod("()I")

    class Builder(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "android/media/quality/SoundProfile$Builder"
        __javaconstructor__ = [("(Landroid/media/quality/SoundProfile;)V", False), ("(Ljava/lang/String;)V", False)]
        setParameters = JavaMethod("(Landroid/os/PersistableBundle;)Landroid/media/quality/SoundProfile$Builder;")
        build = JavaMethod("()Landroid/media/quality/SoundProfile;")

class ActiveProcessingPicture(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "android/media/quality/ActiveProcessingPicture"
    __javaconstructor__ = [("(ILjava/lang/String;)V", False)]
    CREATOR = JavaStaticField("Landroid/os/Parcelable$Creator;")
    CONTENTS_FILE_DESCRIPTOR = JavaStaticField("I")
    PARCELABLE_WRITE_RETURN_VALUE = JavaStaticField("I")
    getProfileId = JavaMethod("()Ljava/lang/String;")
    getId = JavaMethod("()I")
    describeContents = JavaMethod("()I")
    writeToParcel = JavaMethod("(Landroid/os/Parcel;I)V")

class AmbientBacklightEvent(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "android/media/quality/AmbientBacklightEvent"
    __javaconstructor__ = [("(ILandroid/media/quality/AmbientBacklightMetadata;)V", False)]
    AMBIENT_BACKLIGHT_EVENT_DISABLED = JavaStaticField("I")
    AMBIENT_BACKLIGHT_EVENT_ENABLED = JavaStaticField("I")
    AMBIENT_BACKLIGHT_EVENT_INTERRUPTED = JavaStaticField("I")
    AMBIENT_BACKLIGHT_EVENT_METADATA_AVAILABLE = JavaStaticField("I")
    CREATOR = JavaStaticField("Landroid/os/Parcelable$Creator;")
    CONTENTS_FILE_DESCRIPTOR = JavaStaticField("I")
    PARCELABLE_WRITE_RETURN_VALUE = JavaStaticField("I")
    equals = JavaMethod("(Ljava/lang/Object;)Z")
    toString = JavaMethod("()Ljava/lang/String;")
    hashCode = JavaMethod("()I")
    getEventType = JavaMethod("()I")
    describeContents = JavaMethod("()I")
    writeToParcel = JavaMethod("(Landroid/os/Parcel;I)V")
    getMetadata = JavaMethod("()Landroid/media/quality/AmbientBacklightMetadata;")

class MediaQualityManager(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "android/media/quality/MediaQualityManager"
    createPictureProfile = JavaMethod("(Landroid/media/quality/PictureProfile;)V")
    getAvailablePictureProfiles = JavaMethod("(Landroid/media/quality/MediaQualityManager$ProfileQueryParams;)Ljava/util/List;")
    addActiveProcessingPictureListener = JavaMethod("(Ljava/util/concurrent/Executor;Ljava/util/function/Consumer;)V")
    createSoundProfile = JavaMethod("(Landroid/media/quality/SoundProfile;)V")
    getAvailableSoundProfiles = JavaMethod("(Landroid/media/quality/MediaQualityManager$ProfileQueryParams;)Ljava/util/List;")
    getParameterCapabilities = JavaMethod("(Ljava/util/List;)Ljava/util/List;")
    getPictureProfile = JavaMethod("(ILjava/lang/String;Landroid/media/quality/MediaQualityManager$ProfileQueryParams;)Landroid/media/quality/PictureProfile;")
    getSoundProfile = JavaMethod("(ILjava/lang/String;Landroid/media/quality/MediaQualityManager$ProfileQueryParams;)Landroid/media/quality/SoundProfile;")
    isAmbientBacklightEnabled = JavaMethod("()Z")
    isAutoPictureQualityEnabled = JavaMethod("()Z")
    isAutoSoundQualityEnabled = JavaMethod("()Z")
    isSuperResolutionEnabled = JavaMethod("()Z")
    registerAmbientBacklightCallback = JavaMethod("(Ljava/util/concurrent/Executor;Landroid/media/quality/MediaQualityManager$AmbientBacklightCallback;)V")
    registerPictureProfileCallback = JavaMethod("(Ljava/util/concurrent/Executor;Landroid/media/quality/MediaQualityManager$PictureProfileCallback;)V")
    registerSoundProfileCallback = JavaMethod("(Ljava/util/concurrent/Executor;Landroid/media/quality/MediaQualityManager$SoundProfileCallback;)V")
    removeActiveProcessingPictureListener = JavaMethod("(Ljava/util/function/Consumer;)V")
    removePictureProfile = JavaMethod("(Ljava/lang/String;)V")
    removeSoundProfile = JavaMethod("(Ljava/lang/String;)V")
    setAmbientBacklightEnabled = JavaMethod("(Z)V")
    setAmbientBacklightSettings = JavaMethod("(Landroid/media/quality/AmbientBacklightSettings;)V")
    unregisterAmbientBacklightCallback = JavaMethod("(Landroid/media/quality/MediaQualityManager$AmbientBacklightCallback;)V")
    unregisterPictureProfileCallback = JavaMethod("(Landroid/media/quality/MediaQualityManager$PictureProfileCallback;)V")
    unregisterSoundProfileCallback = JavaMethod("(Landroid/media/quality/MediaQualityManager$SoundProfileCallback;)V")
    updatePictureProfile = JavaMethod("(Ljava/lang/String;Landroid/media/quality/PictureProfile;)V")
    updateSoundProfile = JavaMethod("(Ljava/lang/String;Landroid/media/quality/SoundProfile;)V")

    class SoundProfileCallback(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "android/media/quality/MediaQualityManager$SoundProfileCallback"
        __javaconstructor__ = [("()V", False)]
        onParameterCapabilitiesChanged = JavaMethod("(Ljava/lang/String;Ljava/util/List;)V")
        onSoundProfileAdded = JavaMethod("(Ljava/lang/String;Landroid/media/quality/SoundProfile;)V")
        onSoundProfileRemoved = JavaMethod("(Ljava/lang/String;Landroid/media/quality/SoundProfile;)V")
        onSoundProfileUpdated = JavaMethod("(Ljava/lang/String;Landroid/media/quality/SoundProfile;)V")
        onError = JavaMethod("(Ljava/lang/String;I)V")

    class ProfileQueryParams(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "android/media/quality/MediaQualityManager$ProfileQueryParams"
        CREATOR = JavaStaticField("Landroid/os/Parcelable$Creator;")
        CONTENTS_FILE_DESCRIPTOR = JavaStaticField("I")
        PARCELABLE_WRITE_RETURN_VALUE = JavaStaticField("I")
        areParametersIncluded = JavaMethod("()Z")
        describeContents = JavaMethod("()I")
        writeToParcel = JavaMethod("(Landroid/os/Parcel;I)V")

        class Builder(JavaClass, metaclass=MetaJavaClass):
            __javaclass__ = "android/media/quality/MediaQualityManager$ProfileQueryParams$Builder"
            __javaconstructor__ = [("()V", False)]
            setParametersIncluded = JavaMethod("(Z)Landroid/media/quality/MediaQualityManager$ProfileQueryParams$Builder;")
            build = JavaMethod("()Landroid/media/quality/MediaQualityManager$ProfileQueryParams;")

    class PictureProfileCallback(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "android/media/quality/MediaQualityManager$PictureProfileCallback"
        __javaconstructor__ = [("()V", False)]
        onParameterCapabilitiesChanged = JavaMethod("(Ljava/lang/String;Ljava/util/List;)V")
        onPictureProfileAdded = JavaMethod("(Ljava/lang/String;Landroid/media/quality/PictureProfile;)V")
        onPictureProfileRemoved = JavaMethod("(Ljava/lang/String;Landroid/media/quality/PictureProfile;)V")
        onPictureProfileUpdated = JavaMethod("(Ljava/lang/String;Landroid/media/quality/PictureProfile;)V")
        onError = JavaMethod("(Ljava/lang/String;I)V")

    class AmbientBacklightCallback(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "android/media/quality/MediaQualityManager$AmbientBacklightCallback"
        onAmbientBacklightEvent = JavaMethod("(Landroid/media/quality/AmbientBacklightEvent;)V")

class ParameterCapability(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "android/media/quality/ParameterCapability"
    CAPABILITY_DEFAULT = JavaStaticField("Ljava/lang/String;")
    CAPABILITY_ENUM = JavaStaticField("Ljava/lang/String;")
    CAPABILITY_MAX = JavaStaticField("Ljava/lang/String;")
    CAPABILITY_MIN = JavaStaticField("Ljava/lang/String;")
    CREATOR = JavaStaticField("Landroid/os/Parcelable$Creator;")
    TYPE_DOUBLE = JavaStaticField("I")
    TYPE_INT = JavaStaticField("I")
    TYPE_LONG = JavaStaticField("I")
    TYPE_NONE = JavaStaticField("I")
    TYPE_STRING = JavaStaticField("I")
    CONTENTS_FILE_DESCRIPTOR = JavaStaticField("I")
    PARCELABLE_WRITE_RETURN_VALUE = JavaStaticField("I")
    getCapabilities = JavaMethod("()Landroid/os/Bundle;")
    getParameterName = JavaMethod("()Ljava/lang/String;")
    getParameterType = JavaMethod("()I")
    isSupported = JavaMethod("()Z")
    describeContents = JavaMethod("()I")
    writeToParcel = JavaMethod("(Landroid/os/Parcel;I)V")