from typing import Any, ClassVar, overload
from android.os.Bundle import Bundle
from android.os.Parcel import Parcel
from android.os.UserHandle import UserHandle

class RoutingSessionInfo:
    CREATOR: ClassVar[Any]
    TRANSFER_REASON_APP: ClassVar[int]
    TRANSFER_REASON_FALLBACK: ClassVar[int]
    TRANSFER_REASON_SYSTEM_REQUEST: ClassVar[int]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    def getTransferReason(self) -> int: ...
    def getClientPackageName(self) -> str: ...
    def getControlHints(self) -> Bundle: ...
    def getDeselectableRoutes(self) -> list: ...
    def getSelectableRoutes(self) -> list: ...
    def getSelectedRoutes(self) -> list: ...
    def getTransferableRoutes(self) -> list: ...
    def getVolumeHandling(self) -> int: ...
    def getVolumeMax(self) -> int: ...
    def getName(self) -> str: ...
    def equals(self, p0: Any) -> bool: ...
    def toString(self) -> str: ...
    def hashCode(self) -> int: ...
    def getId(self) -> str: ...
    def getVolume(self) -> int: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
    def describeContents(self) -> int: ...

    class Builder:
        @overload
        def __init__(self, p0: "RoutingSessionInfo") -> None: ...
        @overload
        def __init__(self, p0: str, p1: str) -> None: ...
        def setVolumeHandling(self, p0: int) -> Any: ...
        def setVolume(self, p0: int) -> Any: ...
        def addSelectedRoute(self, p0: str) -> Any: ...
        def setTransferReason(self, p0: int) -> Any: ...
        def addSelectableRoute(self, p0: str) -> Any: ...
        def clearTransferableRoutes(self) -> Any: ...
        def removeDeselectableRoute(self, p0: str) -> Any: ...
        def removeSelectableRoute(self, p0: str) -> Any: ...
        def removeSelectedRoute(self, p0: str) -> Any: ...
        def removeTransferableRoute(self, p0: str) -> Any: ...
        def setTransferInitiator(self, p0: UserHandle, p1: str) -> Any: ...
        def clearSelectableRoutes(self) -> Any: ...
        def clearSelectedRoutes(self) -> Any: ...
        def addTransferableRoute(self, p0: str) -> Any: ...
        def clearDeselectableRoutes(self) -> Any: ...
        def setControlHints(self, p0: Bundle) -> Any: ...
        def addDeselectableRoute(self, p0: str) -> Any: ...
        def setVolumeMax(self, p0: int) -> Any: ...
        def setName(self, p0: str) -> Any: ...
        def build(self) -> "RoutingSessionInfo": ...
