from typing import Any, ClassVar, overload

class SyncParams:
    AUDIO_ADJUST_MODE_DEFAULT: ClassVar[int]
    AUDIO_ADJUST_MODE_RESAMPLE: ClassVar[int]
    AUDIO_ADJUST_MODE_STRETCH: ClassVar[int]
    SYNC_SOURCE_AUDIO: ClassVar[int]
    SYNC_SOURCE_DEFAULT: ClassVar[int]
    SYNC_SOURCE_SYSTEM_CLOCK: ClassVar[int]
    SYNC_SOURCE_VSYNC: ClassVar[int]
    def __init__(self) -> None: ...
    def getFrameRate(self) -> float: ...
    def getAudioAdjustMode(self) -> int: ...
    def getSyncSource(self) -> int: ...
    def getTolerance(self) -> float: ...
    def setAudioAdjustMode(self, p0: int) -> "SyncParams": ...
    def setSyncSource(self, p0: int) -> "SyncParams": ...
    def setTolerance(self, p0: float) -> "SyncParams": ...
    def allowDefaults(self) -> "SyncParams": ...
    def setFrameRate(self, p0: float) -> "SyncParams": ...
