from typing import Any, ClassVar, overload
from android.app.Activity import Activity
from android.appwidget.AppWidgetHostView import AppWidgetHostView
from android.appwidget.AppWidgetProviderInfo import AppWidgetProviderInfo
from android.content.Context import Context
from android.os.Bundle import Bundle

class AppWidgetHost:
    def __init__(self, p0: Context, p1: int) -> None: ...
    def createView(self, p0: Context, p1: int, p2: AppWidgetProviderInfo) -> AppWidgetHostView: ...
    def startAppWidgetConfigureActivityForResult(self, p0: Activity, p1: int, p2: int, p3: int, p4: Bundle) -> None: ...
    def allocateAppWidgetId(self) -> int: ...
    @staticmethod
    def deleteAllHosts() -> None: ...
    def deleteAppWidgetId(self, p0: int) -> None: ...
    def deleteHost(self) -> None: ...
    def getAppWidgetIds(self) -> Any: ...
    def onAppWidgetRemoved(self, p0: int) -> None: ...
    def stopListening(self) -> None: ...
    def startListening(self) -> None: ...
