from typing import Any, ClassVar, overload
from android.os.Parcel import Parcel

class WifiP2pUsdBasedServiceDiscoveryConfig:
    CREATOR: ClassVar[Any]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    def getFrequenciesMhz(self) -> Any: ...
    def getBand(self) -> int: ...
    def toString(self) -> str: ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...

    class Builder:
        def __init__(self) -> None: ...
        def setBand(self, p0: int) -> Any: ...
        def setFrequenciesMhz(self, p0: Any) -> Any: ...
        def build(self) -> "WifiP2pUsdBasedServiceDiscoveryConfig": ...

from typing import Any, ClassVar, overload
from android.os.Parcel import Parcel
from java.net.InetAddress import InetAddress

class WifiP2pInfo:
    CREATOR: ClassVar[Any]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    groupFormed: bool
    groupOwnerAddress: InetAddress
    isGroupOwner: bool
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, p0: "WifiP2pInfo") -> None: ...
    def toString(self) -> str: ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...

from typing import Any, ClassVar, overload
from android.os.Parcel import Parcel

class WifiP2pWfdInfo:
    CREATOR: ClassVar[Any]
    DEVICE_INFO_AUDIO_ONLY_SUPPORT_AT_SOURCE: ClassVar[int]
    DEVICE_INFO_AUDIO_UNSUPPORTED_AT_PRIMARY_SINK: ClassVar[int]
    DEVICE_INFO_CONTENT_PROTECTION_SUPPORT: ClassVar[int]
    DEVICE_INFO_COUPLED_SINK_SUPPORT_AT_SINK: ClassVar[int]
    DEVICE_INFO_COUPLED_SINK_SUPPORT_AT_SOURCE: ClassVar[int]
    DEVICE_INFO_DEVICE_TYPE_MASK: ClassVar[int]
    DEVICE_INFO_PREFERRED_CONNECTIVITY_MASK: ClassVar[int]
    DEVICE_INFO_SESSION_AVAILABLE_MASK: ClassVar[int]
    DEVICE_INFO_TDLS_PERSISTENT_GROUP: ClassVar[int]
    DEVICE_INFO_TDLS_PERSISTENT_GROUP_REINVOKE: ClassVar[int]
    DEVICE_INFO_TIME_SYNCHRONIZATION_SUPPORT: ClassVar[int]
    DEVICE_INFO_WFD_SERVICE_DISCOVERY_SUPPORT: ClassVar[int]
    DEVICE_TYPE_PRIMARY_SINK: ClassVar[int]
    DEVICE_TYPE_SECONDARY_SINK: ClassVar[int]
    DEVICE_TYPE_SOURCE_OR_PRIMARY_SINK: ClassVar[int]
    DEVICE_TYPE_WFD_SOURCE: ClassVar[int]
    PREFERRED_CONNECTIVITY_P2P: ClassVar[int]
    PREFERRED_CONNECTIVITY_TDLS: ClassVar[int]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, p0: "WifiP2pWfdInfo") -> None: ...
    def getDeviceType(self) -> int: ...
    def setDeviceType(self, p0: int) -> bool: ...
    def getDeviceInfo(self) -> int: ...
    def toString(self) -> str: ...
    def isEnabled(self) -> bool: ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
    def setEnabled(self, p0: bool) -> None: ...
    def getControlPort(self) -> int: ...
    def getMaxThroughput(self) -> int: ...
    def isR2Supported(self) -> bool: ...
    def getR2DeviceInfo(self) -> int: ...
    def getR2DeviceType(self) -> int: ...
    def isContentProtectionSupported(self) -> bool: ...
    def isCoupledSinkSupportedAtSink(self) -> bool: ...
    def isCoupledSinkSupportedAtSource(self) -> bool: ...
    def isSessionAvailable(self) -> bool: ...
    def setContentProtectionSupported(self, p0: bool) -> None: ...
    def setControlPort(self, p0: int) -> None: ...
    def setCoupledSinkSupportAtSink(self, p0: bool) -> None: ...
    def setCoupledSinkSupportAtSource(self, p0: bool) -> None: ...
    def setMaxThroughput(self, p0: int) -> None: ...
    def setR2DeviceType(self, p0: int) -> bool: ...
    def setSessionAvailable(self, p0: bool) -> None: ...

from typing import Any, ClassVar, overload
from android.content.Context import Context
from android.net.MacAddress import MacAddress
from android.net.NetworkInfo import NetworkInfo
from android.net.wifi.p2p.WifiP2pConfig import WifiP2pConfig
from android.net.wifi.p2p.WifiP2pDevice import WifiP2pDevice
from android.net.wifi.p2p.WifiP2pDeviceList import WifiP2pDeviceList
from android.net.wifi.p2p.WifiP2pDirInfo import WifiP2pDirInfo
from android.net.wifi.p2p.WifiP2pDiscoveryConfig import WifiP2pDiscoveryConfig
from android.net.wifi.p2p.WifiP2pGroup import WifiP2pGroup
from android.net.wifi.p2p.WifiP2pInfo import WifiP2pInfo
from android.net.wifi.p2p.WifiP2pUsdBasedLocalServiceAdvertisementConfig import WifiP2pUsdBasedLocalServiceAdvertisementConfig
from android.net.wifi.p2p.WifiP2pUsdBasedServiceDiscoveryConfig import WifiP2pUsdBasedServiceDiscoveryConfig
from android.net.wifi.p2p.WifiP2pWfdInfo import WifiP2pWfdInfo
from android.net.wifi.p2p.nsd.WifiP2pServiceInfo import WifiP2pServiceInfo
from android.net.wifi.p2p.nsd.WifiP2pServiceRequest import WifiP2pServiceRequest
from android.net.wifi.p2p.nsd.WifiP2pUsdBasedServiceResponse import WifiP2pUsdBasedServiceResponse
from android.os.Looper import Looper
from android.os.OutcomeReceiver import OutcomeReceiver
from java.util.concurrent.Executor import Executor
from java.util.function.Consumer import Consumer

class WifiP2pManager:
    ACTION_WIFI_P2P_LISTEN_STATE_CHANGED: ClassVar[str]
    ACTION_WIFI_P2P_REQUEST_RESPONSE_CHANGED: ClassVar[str]
    BUSY: ClassVar[int]
    CONNECTION_REQUEST_ACCEPT: ClassVar[int]
    CONNECTION_REQUEST_DEFER_SHOW_PIN_TO_SERVICE: ClassVar[int]
    CONNECTION_REQUEST_DEFER_TO_SERVICE: ClassVar[int]
    CONNECTION_REQUEST_REJECT: ClassVar[int]
    ERROR: ClassVar[int]
    EXTRA_DISCOVERY_STATE: ClassVar[str]
    EXTRA_LISTEN_STATE: ClassVar[str]
    EXTRA_NETWORK_INFO: ClassVar[str]
    EXTRA_P2P_DEVICE_LIST: ClassVar[str]
    EXTRA_REQUEST_CONFIG: ClassVar[str]
    EXTRA_REQUEST_RESPONSE: ClassVar[str]
    EXTRA_WIFI_P2P_DEVICE: ClassVar[str]
    EXTRA_WIFI_P2P_GROUP: ClassVar[str]
    EXTRA_WIFI_P2P_INFO: ClassVar[str]
    EXTRA_WIFI_STATE: ClassVar[str]
    GROUP_CREATION_FAILURE_REASON_CONNECTION_CANCELLED: ClassVar[int]
    GROUP_CREATION_FAILURE_REASON_GROUP_REMOVED: ClassVar[int]
    GROUP_CREATION_FAILURE_REASON_INVITATION_FAILED: ClassVar[int]
    GROUP_CREATION_FAILURE_REASON_PROVISION_DISCOVERY_FAILED: ClassVar[int]
    GROUP_CREATION_FAILURE_REASON_TIMED_OUT: ClassVar[int]
    GROUP_CREATION_FAILURE_REASON_USER_REJECTED: ClassVar[int]
    NO_PERMISSION: ClassVar[int]
    NO_SERVICE_REQUESTS: ClassVar[int]
    P2P_UNSUPPORTED: ClassVar[int]
    WIFI_P2P_CONNECTION_CHANGED_ACTION: ClassVar[str]
    WIFI_P2P_DISCOVERY_CHANGED_ACTION: ClassVar[str]
    WIFI_P2P_DISCOVERY_STARTED: ClassVar[int]
    WIFI_P2P_DISCOVERY_STOPPED: ClassVar[int]
    WIFI_P2P_LISTEN_STARTED: ClassVar[int]
    WIFI_P2P_LISTEN_STOPPED: ClassVar[int]
    WIFI_P2P_PEERS_CHANGED_ACTION: ClassVar[str]
    WIFI_P2P_SCAN_FULL: ClassVar[int]
    WIFI_P2P_SCAN_SINGLE_FREQ: ClassVar[int]
    WIFI_P2P_SCAN_SOCIAL: ClassVar[int]
    WIFI_P2P_STATE_CHANGED_ACTION: ClassVar[str]
    WIFI_P2P_STATE_DISABLED: ClassVar[int]
    WIFI_P2P_STATE_ENABLED: ClassVar[int]
    WIFI_P2P_THIS_DEVICE_CHANGED_ACTION: ClassVar[str]
    def discoverServices(self, p0: Any, p1: Any) -> None: ...
    def addExternalApprover(self, p0: Any, p1: MacAddress, p2: Any) -> None: ...
    def addLocalService(self, p0: Any, p1: WifiP2pServiceInfo, p2: Any) -> None: ...
    def addServiceRequest(self, p0: Any, p1: WifiP2pServiceRequest, p2: Any) -> None: ...
    def cancelConnect(self, p0: Any, p1: Any) -> None: ...
    def clearLocalServices(self, p0: Any, p1: Any) -> None: ...
    def clearServiceRequests(self, p0: Any, p1: Any) -> None: ...
    def discoverPeers(self, p0: Any, p1: Any) -> None: ...
    def discoverPeersOnSocialChannels(self, p0: Any, p1: Any) -> None: ...
    def discoverPeersOnSpecificFrequency(self, p0: Any, p1: int, p2: Any) -> None: ...
    def discoverUsdBasedServices(self, p0: Any, p1: WifiP2pUsdBasedServiceDiscoveryConfig, p2: Any) -> None: ...
    def getListenState(self, p0: Any, p1: Executor, p2: Consumer) -> None: ...
    @staticmethod
    def getP2pMaxAllowedVendorElementsLengthBytes() -> int: ...
    def isChannelConstrainedDiscoverySupported(self) -> bool: ...
    def isGroupClientRemovalSupported(self) -> bool: ...
    def isGroupOwnerIPv6LinkLocalAddressProvided(self) -> bool: ...
    def isPccModeSupported(self) -> bool: ...
    def isSetVendorElementsSupported(self) -> bool: ...
    def isWiFiDirectR2Supported(self) -> bool: ...
    def registerWifiP2pListener(self, p0: Executor, p1: Any) -> None: ...
    def removeClient(self, p0: Any, p1: MacAddress, p2: Any) -> None: ...
    def removeExternalApprover(self, p0: Any, p1: MacAddress, p2: Any) -> None: ...
    def removeLocalService(self, p0: Any, p1: WifiP2pServiceInfo, p2: Any) -> None: ...
    def removeServiceRequest(self, p0: Any, p1: WifiP2pServiceRequest, p2: Any) -> None: ...
    def requestConnectionInfo(self, p0: Any, p1: Any) -> None: ...
    def requestDeviceInfo(self, p0: Any, p1: Any) -> None: ...
    def requestDirInfo(self, p0: Any, p1: Executor, p2: OutcomeReceiver) -> None: ...
    def requestDiscoveryState(self, p0: Any, p1: Any) -> None: ...
    def requestGroupInfo(self, p0: Any, p1: Any) -> None: ...
    def requestNetworkInfo(self, p0: Any, p1: Any) -> None: ...
    def requestP2pState(self, p0: Any, p1: Any) -> None: ...
    def requestPeers(self, p0: Any, p1: Any) -> None: ...
    @overload
    def setConnectionRequestResult(self, p0: Any, p1: MacAddress, p2: int, p3: Any) -> None: ...
    @overload
    def setConnectionRequestResult(self, p0: Any, p1: MacAddress, p2: int, p3: str, p4: Any) -> None: ...
    def setDnsSdResponseListeners(self, p0: Any, p1: Any, p2: Any) -> None: ...
    def setServiceResponseListener(self, p0: Any, p1: Any) -> None: ...
    def setUpnpServiceResponseListener(self, p0: Any, p1: Any) -> None: ...
    def setVendorElements(self, p0: Any, p1: list, p2: Any) -> None: ...
    def setWfdInfo(self, p0: Any, p1: WifiP2pWfdInfo, p2: Any) -> None: ...
    def startPeerDiscovery(self, p0: Any, p1: WifiP2pDiscoveryConfig, p2: Any) -> None: ...
    def startUsdBasedLocalServiceAdvertisement(self, p0: Any, p1: WifiP2pServiceInfo, p2: WifiP2pUsdBasedLocalServiceAdvertisementConfig, p3: Any) -> None: ...
    def stopPeerDiscovery(self, p0: Any, p1: Any) -> None: ...
    def unregisterWifiP2pListener(self, p0: Any) -> None: ...
    def validateDirInfo(self, p0: Any, p1: WifiP2pDirInfo, p2: Executor, p3: OutcomeReceiver) -> None: ...
    @overload
    def createGroup(self, p0: Any, p1: WifiP2pConfig, p2: Any) -> None: ...
    @overload
    def createGroup(self, p0: Any, p1: Any) -> None: ...
    def initialize(self, p0: Context, p1: Looper, p2: Any) -> Any: ...
    def connect(self, p0: Any, p1: WifiP2pConfig, p2: Any) -> None: ...
    def removeGroup(self, p0: Any, p1: Any) -> None: ...
    def startListening(self, p0: Any, p1: Any) -> None: ...
    def stopListening(self, p0: Any, p1: Any) -> None: ...

    class WifiP2pListener:
        def onDeviceConfigurationChanged(self, p0: WifiP2pDevice) -> None: ...
        def onDiscoveryStateChanged(self, p0: int) -> None: ...
        def onFrequencyChanged(self, p0: WifiP2pInfo, p1: WifiP2pGroup) -> None: ...
        def onGroupCreated(self, p0: WifiP2pInfo, p1: WifiP2pGroup) -> None: ...
        def onGroupCreating(self) -> None: ...
        def onGroupCreationFailed(self, p0: int) -> None: ...
        def onGroupNegotiationRejectedByUser(self) -> None: ...
        def onGroupRemoved(self) -> None: ...
        def onListenStateChanged(self, p0: int) -> None: ...
        def onP2pStateChanged(self, p0: int) -> None: ...
        def onPeerClientDisconnected(self, p0: WifiP2pInfo, p1: WifiP2pGroup) -> None: ...
        def onPeerClientJoined(self, p0: WifiP2pInfo, p1: WifiP2pGroup) -> None: ...
        def onPeerListChanged(self, p0: WifiP2pDeviceList) -> None: ...

    class UpnpServiceResponseListener:
        def onUpnpServiceAvailable(self, p0: list, p1: WifiP2pDevice) -> None: ...

    class ServiceResponseListener:
        def onUsdBasedServiceAvailable(self, p0: WifiP2pDevice, p1: WifiP2pUsdBasedServiceResponse) -> None: ...
        def onServiceAvailable(self, p0: int, p1: Any, p2: WifiP2pDevice) -> None: ...

    class PeerListListener:
        def onPeersAvailable(self, p0: WifiP2pDeviceList) -> None: ...

    class P2pStateListener:
        def onP2pStateAvailable(self, p0: int) -> None: ...

    class NetworkInfoListener:
        def onNetworkInfoAvailable(self, p0: NetworkInfo) -> None: ...

    class GroupInfoListener:
        def onGroupInfoAvailable(self, p0: WifiP2pGroup) -> None: ...

    class ExternalApproverRequestListener:
        APPROVER_DETACH_REASON_CLOSE: ClassVar[int]
        APPROVER_DETACH_REASON_FAILURE: ClassVar[int]
        APPROVER_DETACH_REASON_REMOVE: ClassVar[int]
        APPROVER_DETACH_REASON_REPLACE: ClassVar[int]
        REQUEST_TYPE_INVITATION: ClassVar[int]
        REQUEST_TYPE_JOIN: ClassVar[int]
        REQUEST_TYPE_NEGOTIATION: ClassVar[int]
        def onAttached(self, p0: MacAddress) -> None: ...
        def onDetached(self, p0: MacAddress, p1: int) -> None: ...
        def onConnectionRequested(self, p0: int, p1: WifiP2pConfig, p2: WifiP2pDevice) -> None: ...
        def onPinGenerated(self, p0: MacAddress, p1: str) -> None: ...

    class DnsSdTxtRecordListener:
        def onDnsSdTxtRecordAvailable(self, p0: str, p1: dict, p2: WifiP2pDevice) -> None: ...

    class DnsSdServiceResponseListener:
        def onDnsSdServiceAvailable(self, p0: str, p1: str, p2: WifiP2pDevice) -> None: ...

    class DiscoveryStateListener:
        def onDiscoveryStateAvailable(self, p0: int) -> None: ...

    class DeviceInfoListener:
        def onDeviceInfoAvailable(self, p0: WifiP2pDevice) -> None: ...

    class ConnectionInfoListener:
        def onConnectionInfoAvailable(self, p0: WifiP2pInfo) -> None: ...

    class ChannelListener:
        def onChannelDisconnected(self) -> None: ...

    class Channel:
        def close(self) -> None: ...

    class ActionListener:
        def onSuccess(self) -> None: ...
        def onFailure(self, p0: int) -> None: ...

from typing import Any, ClassVar, overload
from android.os.Parcel import Parcel

class WifiP2pUsdBasedLocalServiceAdvertisementConfig:
    CREATOR: ClassVar[Any]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    def getFrequencyMhz(self) -> int: ...
    def toString(self) -> str: ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...

    class Builder:
        def __init__(self) -> None: ...
        def setFrequencyMhz(self, p0: int) -> Any: ...
        def build(self) -> "WifiP2pUsdBasedLocalServiceAdvertisementConfig": ...

from typing import Any, ClassVar, overload
from android.net.wifi.p2p.WifiP2pWfdInfo import WifiP2pWfdInfo
from android.os.Parcel import Parcel
from java.net.InetAddress import InetAddress

class WifiP2pDevice:
    AVAILABLE: ClassVar[int]
    CONNECTED: ClassVar[int]
    CREATOR: ClassVar[Any]
    FAILED: ClassVar[int]
    INVITED: ClassVar[int]
    UNAVAILABLE: ClassVar[int]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    deviceAddress: str
    deviceName: str
    primaryDeviceType: str
    secondaryDeviceType: str
    status: int
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, p0: "WifiP2pDevice") -> None: ...
    def getIpAddress(self) -> InetAddress: ...
    def isServiceDiscoveryCapable(self) -> bool: ...
    def getVendorElements(self) -> list: ...
    def getWfdInfo(self) -> WifiP2pWfdInfo: ...
    def isOpportunisticBootstrappingMethodSupported(self) -> bool: ...
    def isPassphraseDisplayBootstrappingMethodSupported(self) -> bool: ...
    def isPassphraseKeypadBootstrappingMethodSupported(self) -> bool: ...
    def isPinCodeDisplayBootstrappingMethodSupported(self) -> bool: ...
    def isPinCodeKeypadBootstrappingMethodSupported(self) -> bool: ...
    def wpsDisplaySupported(self) -> bool: ...
    def wpsKeypadSupported(self) -> bool: ...
    def wpsPbcSupported(self) -> bool: ...
    def isGroupOwner(self) -> bool: ...
    def equals(self, p0: Any) -> bool: ...
    def toString(self) -> str: ...
    def hashCode(self) -> int: ...
    def update(self, p0: "WifiP2pDevice") -> None: ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...

from typing import Any, ClassVar, overload
from android.net.MacAddress import MacAddress
from android.os.Parcel import Parcel

class WifiP2pDirInfo:
    CREATOR: ClassVar[Any]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    def __init__(self, p0: MacAddress, p1: Any, p2: Any) -> None: ...
    def getMacAddress(self) -> MacAddress: ...
    def toString(self) -> str: ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
    def getNonce(self) -> Any: ...
    def getDirTag(self) -> Any: ...

from typing import Any, ClassVar, overload
from android.os.Parcel import Parcel

class WifiP2pDiscoveryConfig:
    CREATOR: ClassVar[Any]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    def getFrequencyMhz(self) -> int: ...
    def getScanType(self) -> int: ...
    def toString(self) -> str: ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...

    class Builder:
        def __init__(self, p0: int) -> None: ...
        def setFrequencyMhz(self, p0: int) -> Any: ...
        def build(self) -> "WifiP2pDiscoveryConfig": ...

from typing import Any, ClassVar, overload
from android.net.MacAddress import MacAddress
from android.net.wifi.p2p.WifiP2pDevice import WifiP2pDevice
from android.os.Parcel import Parcel

class WifiP2pGroup:
    CREATOR: ClassVar[Any]
    NETWORK_ID_PERSISTENT: ClassVar[int]
    NETWORK_ID_TEMPORARY: ClassVar[int]
    SECURITY_TYPE_UNKNOWN: ClassVar[int]
    SECURITY_TYPE_WPA2_PSK: ClassVar[int]
    SECURITY_TYPE_WPA3_COMPATIBILITY: ClassVar[int]
    SECURITY_TYPE_WPA3_SAE: ClassVar[int]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, p0: "WifiP2pGroup") -> None: ...
    def getPassphrase(self) -> str: ...
    def getSecurityType(self) -> int: ...
    def getClientList(self) -> list: ...
    def getFrequency(self) -> int: ...
    def getGroupOwnerBssid(self) -> MacAddress: ...
    def isGroupOwner(self) -> bool: ...
    def getNetworkName(self) -> str: ...
    def getInterface(self) -> str: ...
    def toString(self) -> str: ...
    def getOwner(self) -> WifiP2pDevice: ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
    def getNetworkId(self) -> int: ...

from typing import Any, ClassVar, overload
from android.net.MacAddress import MacAddress
from android.net.wifi.WpsInfo import WpsInfo
from android.net.wifi.p2p.WifiP2pPairingBootstrappingConfig import WifiP2pPairingBootstrappingConfig
from android.os.Parcel import Parcel

class WifiP2pConfig:
    CREATOR: ClassVar[Any]
    GROUP_CLIENT_IP_PROVISIONING_MODE_IPV4_DHCP: ClassVar[int]
    GROUP_CLIENT_IP_PROVISIONING_MODE_IPV6_LINK_LOCAL: ClassVar[int]
    GROUP_OWNER_BAND_2GHZ: ClassVar[int]
    GROUP_OWNER_BAND_5GHZ: ClassVar[int]
    GROUP_OWNER_BAND_6GHZ: ClassVar[int]
    GROUP_OWNER_BAND_AUTO: ClassVar[int]
    GROUP_OWNER_INTENT_AUTO: ClassVar[int]
    GROUP_OWNER_INTENT_MAX: ClassVar[int]
    GROUP_OWNER_INTENT_MIN: ClassVar[int]
    P2P_VERSION_1: ClassVar[int]
    P2P_VERSION_2: ClassVar[int]
    PCC_MODE_CONNECTION_TYPE_LEGACY_ONLY: ClassVar[int]
    PCC_MODE_CONNECTION_TYPE_LEGACY_OR_R2: ClassVar[int]
    PCC_MODE_CONNECTION_TYPE_R2_ONLY: ClassVar[int]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    deviceAddress: str
    groupOwnerIntent: int
    wps: WpsInfo
    @overload
    def __init__(self, p0: "WifiP2pConfig") -> None: ...
    @overload
    def __init__(self) -> None: ...
    def getPassphrase(self) -> str: ...
    def getNetworkName(self) -> str: ...
    def toString(self) -> str: ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
    def getGroupClientIpProvisioningMode(self) -> int: ...
    def getGroupOwnerBand(self) -> int: ...
    def getGroupOwnerVersion(self) -> int: ...
    def getPairingBootstrappingConfig(self) -> WifiP2pPairingBootstrappingConfig: ...
    def getPccModeConnectionType(self) -> int: ...
    def isAuthorizeConnectionFromPeerEnabled(self) -> bool: ...
    def setGroupOwnerVersion(self, p0: int) -> None: ...
    def getNetworkId(self) -> int: ...

    class Builder:
        def __init__(self) -> None: ...
        def setDeviceAddress(self, p0: MacAddress) -> Any: ...
        def enablePersistentMode(self, p0: bool) -> Any: ...
        def setAuthorizeConnectionFromPeerEnabled(self, p0: bool) -> Any: ...
        def setGroupClientIpProvisioningMode(self, p0: int) -> Any: ...
        def setGroupOperatingBand(self, p0: int) -> Any: ...
        def setGroupOperatingFrequency(self, p0: int) -> Any: ...
        def setNetworkName(self, p0: str) -> Any: ...
        def setPairingBootstrappingConfig(self, p0: WifiP2pPairingBootstrappingConfig) -> Any: ...
        def setPassphrase(self, p0: str) -> Any: ...
        def setPccModeConnectionType(self, p0: int) -> Any: ...
        def build(self) -> "WifiP2pConfig": ...

from typing import Any, ClassVar, overload
from android.os.Parcel import Parcel

class WifiP2pPairingBootstrappingConfig:
    CREATOR: ClassVar[Any]
    PAIRING_BOOTSTRAPPING_METHOD_DISPLAY_PASSPHRASE: ClassVar[int]
    PAIRING_BOOTSTRAPPING_METHOD_DISPLAY_PINCODE: ClassVar[int]
    PAIRING_BOOTSTRAPPING_METHOD_KEYPAD_PASSPHRASE: ClassVar[int]
    PAIRING_BOOTSTRAPPING_METHOD_KEYPAD_PINCODE: ClassVar[int]
    PAIRING_BOOTSTRAPPING_METHOD_OPPORTUNISTIC: ClassVar[int]
    PAIRING_BOOTSTRAPPING_METHOD_OUT_OF_BAND: ClassVar[int]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    def __init__(self, p0: int, p1: str) -> None: ...
    def toString(self) -> str: ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...

from typing import Any, ClassVar, overload
from android.net.wifi.p2p.WifiP2pDevice import WifiP2pDevice
from android.os.Parcel import Parcel

class WifiP2pDeviceList:
    CREATOR: ClassVar[Any]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, p0: "WifiP2pDeviceList") -> None: ...
    def getDeviceList(self) -> list: ...
    def get(self, p0: str) -> WifiP2pDevice: ...
    def toString(self) -> str: ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...

