from typing import Any, ClassVar, overload
from java.sql.ResultSet import ResultSet

class Array:
    @overload
    def getResultSet(self, p0: dict) -> ResultSet: ...
    @overload
    def getResultSet(self) -> ResultSet: ...
    @overload
    def getResultSet(self, p0: int, p1: int, p2: dict) -> ResultSet: ...
    @overload
    def getResultSet(self, p0: int, p1: int) -> ResultSet: ...
    def getBaseTypeName(self) -> str: ...
    def getBaseType(self) -> int: ...
    def free(self) -> None: ...
    @overload
    def getArray(self, p0: int, p1: int, p2: dict) -> Any: ...
    @overload
    def getArray(self) -> Any: ...
    @overload
    def getArray(self, p0: dict) -> Any: ...
    @overload
    def getArray(self, p0: int, p1: int) -> Any: ...
