from typing import Any, ClassVar, overload
from android.content.Context import Context
from android.net.sip.SipProfile import SipProfile
from android.net.sip.SipSession import SipSession
from android.os.Message import Message

class SipAudioCall:
    def __init__(self, p0: Context, p1: SipProfile) -> None: ...
    def isInCall(self) -> bool: ...
    def endCall(self) -> None: ...
    def isMuted(self) -> bool: ...
    def isOnHold(self) -> bool: ...
    def getLocalProfile(self) -> SipProfile: ...
    def getPeerProfile(self) -> SipProfile: ...
    def attachCall(self, p0: SipSession, p1: str) -> None: ...
    def makeCall(self, p0: SipProfile, p1: SipSession, p2: int) -> None: ...
    def holdCall(self, p0: int) -> None: ...
    def answerCall(self, p0: int) -> None: ...
    def continueCall(self, p0: int) -> None: ...
    def toggleMute(self) -> None: ...
    def setSpeakerMode(self, p0: bool) -> None: ...
    def startAudio(self) -> None: ...
    @overload
    def sendDtmf(self, p0: int) -> None: ...
    @overload
    def sendDtmf(self, p0: int, p1: Message) -> None: ...
    @overload
    def setListener(self, p0: Any) -> None: ...
    @overload
    def setListener(self, p0: Any, p1: bool) -> None: ...
    def getState(self) -> int: ...
    def close(self) -> None: ...

    class Listener:
        def __init__(self) -> None: ...
        def onReadyToCall(self, p0: "SipAudioCall") -> None: ...
        def onCalling(self, p0: "SipAudioCall") -> None: ...
        def onRinging(self, p0: "SipAudioCall", p1: SipProfile) -> None: ...
        def onRingingBack(self, p0: "SipAudioCall") -> None: ...
        def onCallEstablished(self, p0: "SipAudioCall") -> None: ...
        def onCallEnded(self, p0: "SipAudioCall") -> None: ...
        def onCallBusy(self, p0: "SipAudioCall") -> None: ...
        def onCallHeld(self, p0: "SipAudioCall") -> None: ...
        def onError(self, p0: "SipAudioCall", p1: int, p2: str) -> None: ...
        def onChanged(self, p0: "SipAudioCall") -> None: ...
