from typing import Any, ClassVar, overload
from android.app.RemoteAction import RemoteAction
from android.content.Intent import Intent
from android.graphics.drawable.Drawable import Drawable
from android.os.Bundle import Bundle
from android.os.LocaleList import LocaleList
from android.os.Parcel import Parcel
from java.time.ZonedDateTime import ZonedDateTime

class TextClassification:
    CREATOR: ClassVar[Any]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    def getConfidenceScore(self, p0: str) -> float: ...
    def getEntityCount(self) -> int: ...
    def getEntity(self, p0: int) -> str: ...
    def getOnClickListener(self) -> Any: ...
    def toString(self) -> str: ...
    def getId(self) -> str: ...
    def getIcon(self) -> Drawable: ...
    def getActions(self) -> list: ...
    def getExtras(self) -> Bundle: ...
    def getIntent(self) -> Intent: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
    def describeContents(self) -> int: ...
    def getText(self) -> str: ...
    def getLabel(self) -> str: ...

    class Request:
        CREATOR: ClassVar[Any]
        CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
        PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
        def getReferenceTime(self) -> ZonedDateTime: ...
        def getDefaultLocales(self) -> LocaleList: ...
        def getCallingPackageName(self) -> str: ...
        def getEndIndex(self) -> int: ...
        def getStartIndex(self) -> int: ...
        def getExtras(self) -> Bundle: ...
        def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
        def describeContents(self) -> int: ...
        def getText(self) -> str: ...

        class Builder:
            def __init__(self, p0: str, p1: int, p2: int) -> None: ...
            def setReferenceTime(self, p0: ZonedDateTime) -> Any: ...
            def setDefaultLocales(self, p0: LocaleList) -> Any: ...
            def build(self) -> Any: ...
            def setExtras(self, p0: Bundle) -> Any: ...

    class Builder:
        def __init__(self) -> None: ...
        def setEntityType(self, p0: str, p1: float) -> Any: ...
        def build(self) -> "TextClassification": ...
        def addAction(self, p0: RemoteAction) -> Any: ...
        def setExtras(self, p0: Bundle) -> Any: ...
        def setText(self, p0: str) -> Any: ...
        def setIcon(self, p0: Drawable) -> Any: ...
        def setIntent(self, p0: Intent) -> Any: ...
        def setId(self, p0: str) -> Any: ...
        def setOnClickListener(self, p0: Any) -> Any: ...
        def setLabel(self, p0: str) -> Any: ...
