from typing import Any, ClassVar, overload
from android.icu.util.ULocale import ULocale
from android.os.Bundle import Bundle
from android.os.Parcel import Parcel

class TextLanguage:
    CREATOR: ClassVar[Any]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    def getConfidenceScore(self, p0: ULocale) -> float: ...
    def getLocaleHypothesisCount(self) -> int: ...
    def toString(self) -> str: ...
    def getId(self) -> str: ...
    def getExtras(self) -> Bundle: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
    def describeContents(self) -> int: ...
    def getLocale(self, p0: int) -> ULocale: ...

    class Request:
        CREATOR: ClassVar[Any]
        CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
        PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
        def getCallingPackageName(self) -> str: ...
        def getExtras(self) -> Bundle: ...
        def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
        def describeContents(self) -> int: ...
        def getText(self) -> str: ...

        class Builder:
            def __init__(self, p0: str) -> None: ...
            def build(self) -> Any: ...
            def setExtras(self, p0: Bundle) -> Any: ...

    class Builder:
        def __init__(self) -> None: ...
        def putLocale(self, p0: ULocale, p1: float) -> Any: ...
        def build(self) -> "TextLanguage": ...
        def setExtras(self, p0: Bundle) -> Any: ...
        def setId(self, p0: str) -> Any: ...
