from typing import Any, ClassVar, overload
from android.graphics.Bitmap import Bitmap
from android.hardware.camera2.CameraCharacteristics import CameraCharacteristics
from android.hardware.camera2.CaptureResult import CaptureResult
from android.location.Location import Location
from android.media.Image import Image
from android.util.Size import Size
from java.io.InputStream import InputStream
from java.io.OutputStream import OutputStream
from java.nio.ByteBuffer import ByteBuffer

class DngCreator:
    MAX_THUMBNAIL_DIMENSION: ClassVar[int]
    def __init__(self, p0: CameraCharacteristics, p1: CaptureResult) -> None: ...
    def setDescription(self, p0: str) -> "DngCreator": ...
    def setLocation(self, p0: Location) -> "DngCreator": ...
    def setOrientation(self, p0: int) -> "DngCreator": ...
    @overload
    def setThumbnail(self, p0: Bitmap) -> "DngCreator": ...
    @overload
    def setThumbnail(self, p0: Image) -> "DngCreator": ...
    def writeInputStream(self, p0: OutputStream, p1: Size, p2: InputStream, p3: int) -> None: ...
    def writeByteBuffer(self, p0: OutputStream, p1: Size, p2: ByteBuffer, p3: int) -> None: ...
    def writeImage(self, p0: OutputStream, p1: Image) -> None: ...
    def close(self) -> None: ...
