from typing import Any, ClassVar, overload
from android.app.Fragment import Fragment
from android.app.FragmentTransaction import FragmentTransaction
from android.content.Context import Context
from android.os.Bundle import Bundle
from android.view.View import View
from java.io.FileDescriptor import FileDescriptor
from java.io.PrintWriter import PrintWriter

class FragmentManager:
    POP_BACK_STACK_INCLUSIVE: ClassVar[int]
    def __init__(self) -> None: ...
    @staticmethod
    def enableDebugLogging(p0: bool) -> None: ...
    def executePendingTransactions(self) -> bool: ...
    def findFragmentById(self, p0: int) -> Fragment: ...
    def findFragmentByTag(self, p0: str) -> Fragment: ...
    @overload
    def popBackStack(self, p0: str, p1: int) -> None: ...
    @overload
    def popBackStack(self) -> None: ...
    @overload
    def popBackStack(self, p0: int, p1: int) -> None: ...
    @overload
    def popBackStackImmediate(self, p0: int, p1: int) -> bool: ...
    @overload
    def popBackStackImmediate(self, p0: str, p1: int) -> bool: ...
    @overload
    def popBackStackImmediate(self) -> bool: ...
    def getBackStackEntryCount(self) -> int: ...
    def getBackStackEntryAt(self, p0: int) -> Any: ...
    def addOnBackStackChangedListener(self, p0: Any) -> None: ...
    def removeOnBackStackChangedListener(self, p0: Any) -> None: ...
    def putFragment(self, p0: Bundle, p1: str, p2: Fragment) -> None: ...
    def getFragments(self) -> list: ...
    def saveFragmentInstanceState(self, p0: Fragment) -> Any: ...
    def unregisterFragmentLifecycleCallbacks(self, p0: Any) -> None: ...
    def getPrimaryNavigationFragment(self) -> Fragment: ...
    def isStateSaved(self) -> bool: ...
    def isDestroyed(self) -> bool: ...
    def dump(self, p0: str, p1: FileDescriptor, p2: PrintWriter, p3: Any) -> None: ...
    def getFragment(self, p0: Bundle, p1: str) -> Fragment: ...
    def registerFragmentLifecycleCallbacks(self, p0: Any, p1: bool) -> None: ...
    def invalidateOptionsMenu(self) -> None: ...
    def beginTransaction(self) -> FragmentTransaction: ...

    class OnBackStackChangedListener:
        def onBackStackChanged(self) -> None: ...

    class FragmentLifecycleCallbacks:
        def __init__(self) -> None: ...
        def onFragmentPreAttached(self, p0: "FragmentManager", p1: Fragment, p2: Context) -> None: ...
        def onFragmentActivityCreated(self, p0: "FragmentManager", p1: Fragment, p2: Bundle) -> None: ...
        def onFragmentAttached(self, p0: "FragmentManager", p1: Fragment, p2: Context) -> None: ...
        def onFragmentPreCreated(self, p0: "FragmentManager", p1: Fragment, p2: Bundle) -> None: ...
        def onFragmentCreated(self, p0: "FragmentManager", p1: Fragment, p2: Bundle) -> None: ...
        def onFragmentViewCreated(self, p0: "FragmentManager", p1: Fragment, p2: View, p3: Bundle) -> None: ...
        def onFragmentStarted(self, p0: "FragmentManager", p1: Fragment) -> None: ...
        def onFragmentResumed(self, p0: "FragmentManager", p1: Fragment) -> None: ...
        def onFragmentPaused(self, p0: "FragmentManager", p1: Fragment) -> None: ...
        def onFragmentStopped(self, p0: "FragmentManager", p1: Fragment) -> None: ...
        def onFragmentSaveInstanceState(self, p0: "FragmentManager", p1: Fragment, p2: Bundle) -> None: ...
        def onFragmentViewDestroyed(self, p0: "FragmentManager", p1: Fragment) -> None: ...
        def onFragmentDestroyed(self, p0: "FragmentManager", p1: Fragment) -> None: ...
        def onFragmentDetached(self, p0: "FragmentManager", p1: Fragment) -> None: ...

    class BackStackEntry:
        def getBreadCrumbTitle(self) -> str: ...
        def getBreadCrumbTitleRes(self) -> int: ...
        def getBreadCrumbShortTitle(self) -> str: ...
        def getBreadCrumbShortTitleRes(self) -> int: ...
        def getName(self) -> str: ...
        def getId(self) -> int: ...
