from typing import Any, ClassVar, overload
from android.content.Context import Context
from android.view.MenuItem import MenuItem
from android.view.View import View

class MediaRouteActionProvider:
    def __init__(self, p0: Context) -> None: ...
    def setRouteTypes(self, p0: int) -> None: ...
    def setExtendedSettingsClickListener(self, p0: Any) -> None: ...
    def isVisible(self) -> bool: ...
    @overload
    def onCreateActionView(self, p0: MenuItem) -> View: ...
    @overload
    def onCreateActionView(self) -> View: ...
    def overridesItemVisibility(self) -> bool: ...
    def onPerformDefaultAction(self) -> bool: ...
