from typing import Any, ClassVar, overload
from android.app.RemoteAction import RemoteAction
from android.graphics.Rect import Rect
from android.os.Parcel import Parcel
from android.util.Rational import Rational

class PictureInPictureParams:
    CREATOR: ClassVar[Any]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    def getAspectRatio(self) -> Rational: ...
    def getCloseAction(self) -> RemoteAction: ...
    def getExpandedAspectRatio(self) -> Rational: ...
    def getSourceRectHint(self) -> Rect: ...
    def isAutoEnterEnabled(self) -> bool: ...
    def isSeamlessResizeEnabled(self) -> bool: ...
    def equals(self, p0: Any) -> bool: ...
    def toString(self) -> str: ...
    def hashCode(self) -> int: ...
    def getActions(self) -> list: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
    def describeContents(self) -> int: ...
    def getSubtitle(self) -> str: ...
    def getTitle(self) -> str: ...

    class Builder:
        @overload
        def __init__(self, p0: "PictureInPictureParams") -> None: ...
        @overload
        def __init__(self) -> None: ...
        def setActions(self, p0: list) -> Any: ...
        def setAspectRatio(self, p0: Rational) -> Any: ...
        def setAutoEnterEnabled(self, p0: bool) -> Any: ...
        def setCloseAction(self, p0: RemoteAction) -> Any: ...
        def setSourceRectHint(self, p0: Rect) -> Any: ...
        def setExpandedAspectRatio(self, p0: Rational) -> Any: ...
        def setSeamlessResizeEnabled(self, p0: bool) -> Any: ...
        def build(self) -> "PictureInPictureParams": ...
        def setSubtitle(self, p0: str) -> Any: ...
        def setTitle(self, p0: str) -> Any: ...
