from typing import Any, ClassVar, overload
from android.content.Context import Context
from android.content.res.Resources import Resources
from android.view.Display import Display

class Presentation:
    BUTTON1: ClassVar[int]
    BUTTON2: ClassVar[int]
    BUTTON3: ClassVar[int]
    BUTTON_NEGATIVE: ClassVar[int]
    BUTTON_NEUTRAL: ClassVar[int]
    BUTTON_POSITIVE: ClassVar[int]
    @overload
    def __init__(self, p0: Context, p1: Display) -> None: ...
    @overload
    def __init__(self, p0: Context, p1: Display, p2: int) -> None: ...
    def onDisplayRemoved(self) -> None: ...
    def onDisplayChanged(self) -> None: ...
    def getResources(self) -> Resources: ...
    def show(self) -> None: ...
    def getDisplay(self) -> Display: ...
