from typing import Any, ClassVar, overload
from android.os.Parcel import Parcel
from android.telephony.ClosedSubscriberGroupInfo import ClosedSubscriberGroupInfo

class CellIdentityWcdma:
    CREATOR: ClassVar[Any]
    CREATOR: ClassVar[Any]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    def getMcc(self) -> int: ...
    def getMnc(self) -> int: ...
    def getMccString(self) -> str: ...
    def getCid(self) -> int: ...
    def getAdditionalPlmns(self) -> set: ...
    def getPsc(self) -> int: ...
    def getMncString(self) -> str: ...
    def getUarfcn(self) -> int: ...
    def getLac(self) -> int: ...
    def getClosedSubscriberGroupInfo(self) -> ClosedSubscriberGroupInfo: ...
    def getMobileNetworkOperator(self) -> str: ...
    def equals(self, p0: Any) -> bool: ...
    def toString(self) -> str: ...
    def hashCode(self) -> int: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
