from typing import Any, ClassVar, overload
from android.os.Parcel import Parcel

class NeighboringCellInfo:
    CREATOR: ClassVar[Any]
    UNKNOWN_CID: ClassVar[int]
    UNKNOWN_RSSI: ClassVar[int]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, p0: int, p1: int) -> None: ...
    @overload
    def __init__(self, p0: int, p1: str, p2: int) -> None: ...
    @overload
    def __init__(self, p0: Parcel) -> None: ...
    def getLac(self) -> int: ...
    def getPsc(self) -> int: ...
    def getCid(self) -> int: ...
    def getNetworkType(self) -> int: ...
    def setCid(self, p0: int) -> None: ...
    def setRssi(self, p0: int) -> None: ...
    def getRssi(self) -> int: ...
    def toString(self) -> str: ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
