# cython: language_level=3
# Generated by jni-wrap cython — do not edit by hand.
from jni_core._core cimport JavaObject
from jni_core.jni cimport (
    JNIEnv, jobject, jstring,
    jboolean, jbyte, jchar, jshort, jint, jlong, jfloat, jdouble,
)

cdef class NetworkRegistrationInfo(JavaObject):
    cdef jobject _getCellIdentity(self, JNIEnv* env) except? NULL
    cdef jobject _getCellIdentity_0(self, JNIEnv* env) except? NULL
    cdef jint _getTransportType(self, JNIEnv* env) except *
    cdef jint _getTransportType_0(self, JNIEnv* env) except *
    cdef jboolean _isRoaming(self, JNIEnv* env) except *
    cdef jboolean _isRoaming_0(self, JNIEnv* env) except *
    cdef jint _getAccessNetworkTechnology(self, JNIEnv* env) except *
    cdef jint _getAccessNetworkTechnology_0(self, JNIEnv* env) except *
    cdef jobject _getAvailableServices(self, JNIEnv* env) except? NULL
    cdef jobject _getAvailableServices_0(self, JNIEnv* env) except? NULL
    cdef jint _getDomain(self, JNIEnv* env) except *
    cdef jint _getDomain_0(self, JNIEnv* env) except *
    cdef jstring _getRegisteredPlmn(self, JNIEnv* env) except? NULL
    cdef jstring _getRegisteredPlmn_0(self, JNIEnv* env) except? NULL
    cdef jint _getRejectCause(self, JNIEnv* env) except *
    cdef jint _getRejectCause_0(self, JNIEnv* env) except *
    cdef jboolean _isNetworkRegistered(self, JNIEnv* env) except *
    cdef jboolean _isNetworkRegistered_0(self, JNIEnv* env) except *
    cdef jboolean _isNetworkSearching(self, JNIEnv* env) except *
    cdef jboolean _isNetworkSearching_0(self, JNIEnv* env) except *
    cdef jboolean _isNonTerrestrialNetwork(self, JNIEnv* env) except *
    cdef jboolean _isNonTerrestrialNetwork_0(self, JNIEnv* env) except *
    cdef jboolean _isNetworkRoaming(self, JNIEnv* env) except *
    cdef jboolean _isNetworkRoaming_0(self, JNIEnv* env) except *
    cdef jboolean _equals(self, JNIEnv* env, jobject p0) except *
    cdef jboolean _equals_0(self, JNIEnv* env, jobject p0) except *
    cdef jstring _toString(self, JNIEnv* env) except? NULL
    cdef jstring _toString_0(self, JNIEnv* env) except? NULL
    cdef jint _hashCode(self, JNIEnv* env) except *
    cdef jint _hashCode_0(self, JNIEnv* env) except *
    cdef jboolean _isRegistered(self, JNIEnv* env) except *
    cdef jboolean _isRegistered_0(self, JNIEnv* env) except *
    cdef void _writeToParcel(self, JNIEnv* env, jobject p0, jint p1) except *
    cdef void _writeToParcel_0(self, JNIEnv* env, jobject p0, jint p1) except *
    cdef jint _describeContents(self, JNIEnv* env) except *
    cdef jint _describeContents_0(self, JNIEnv* env) except *
    cdef jboolean _isSearching(self, JNIEnv* env) except *
    cdef jboolean _isSearching_0(self, JNIEnv* env) except *
