from typing import Any, ClassVar, overload
from android.os.Parcel import Parcel

class SignalThresholdInfo:
    CREATOR: ClassVar[Any]
    SIGNAL_MEASUREMENT_TYPE_ECNO: ClassVar[int]
    SIGNAL_MEASUREMENT_TYPE_RSCP: ClassVar[int]
    SIGNAL_MEASUREMENT_TYPE_RSRP: ClassVar[int]
    SIGNAL_MEASUREMENT_TYPE_RSRQ: ClassVar[int]
    SIGNAL_MEASUREMENT_TYPE_RSSI: ClassVar[int]
    SIGNAL_MEASUREMENT_TYPE_RSSNR: ClassVar[int]
    SIGNAL_MEASUREMENT_TYPE_SSRSRP: ClassVar[int]
    SIGNAL_MEASUREMENT_TYPE_SSRSRQ: ClassVar[int]
    SIGNAL_MEASUREMENT_TYPE_SSSINR: ClassVar[int]
    SIGNAL_MEASUREMENT_TYPE_UNKNOWN: ClassVar[int]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    def getThresholds(self) -> Any: ...
    def getHysteresisDb(self) -> int: ...
    def getRadioAccessNetworkType(self) -> int: ...
    def getSignalMeasurementType(self) -> int: ...
    @staticmethod
    def getMinimumNumberOfThresholdsAllowed() -> int: ...
    @staticmethod
    def getMaximumNumberOfThresholdsAllowed() -> int: ...
    def equals(self, p0: Any) -> bool: ...
    def toString(self) -> str: ...
    def hashCode(self) -> int: ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...

    class Builder:
        def __init__(self) -> None: ...
        def setRadioAccessNetworkType(self, p0: int) -> Any: ...
        def setSignalMeasurementType(self, p0: int) -> Any: ...
        def setHysteresisDb(self, p0: int) -> Any: ...
        def setThresholds(self, p0: Any) -> Any: ...
        def build(self) -> "SignalThresholdInfo": ...
