from typing import Any, ClassVar, overload
from android.os.Parcel import Parcel
from java.time.Period import Period
from java.time.ZonedDateTime import ZonedDateTime
from java.util.Iterator import Iterator

class SubscriptionPlan:
    BYTES_UNKNOWN: ClassVar[int]
    BYTES_UNLIMITED: ClassVar[int]
    CREATOR: ClassVar[Any]
    LIMIT_BEHAVIOR_BILLED: ClassVar[int]
    LIMIT_BEHAVIOR_DISABLED: ClassVar[int]
    LIMIT_BEHAVIOR_THROTTLED: ClassVar[int]
    LIMIT_BEHAVIOR_UNKNOWN: ClassVar[int]
    TIME_UNKNOWN: ClassVar[int]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    def getSummary(self) -> str: ...
    def getDataLimitBytes(self) -> int: ...
    def getDataLimitBehavior(self) -> int: ...
    def getDataUsageBytes(self) -> int: ...
    def getDataUsageTime(self) -> int: ...
    def getNetworkTypes(self) -> Any: ...
    def cycleIterator(self) -> Iterator: ...
    def equals(self, p0: Any) -> bool: ...
    def toString(self) -> str: ...
    def hashCode(self) -> int: ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
    def getTitle(self) -> str: ...

    class Builder:
        @staticmethod
        def createNonrecurring(p0: ZonedDateTime, p1: ZonedDateTime) -> Any: ...
        @staticmethod
        def createRecurring(p0: ZonedDateTime, p1: Period) -> Any: ...
        def setSummary(self, p0: str) -> Any: ...
        def setDataLimit(self, p0: int, p1: int) -> Any: ...
        def setDataUsage(self, p0: int, p1: int) -> Any: ...
        def setNetworkTypes(self, p0: Any) -> Any: ...
        def resetNetworkTypes(self) -> Any: ...
        def build(self) -> "SubscriptionPlan": ...
        def setTitle(self, p0: str) -> Any: ...
