from typing import Any, ClassVar, overload
from java.util.concurrent.TimeUnit import TimeUnit
from java.util.concurrent.locks.Lock import Lock
from java.util.concurrent.locks.ReadWriteLock import ReadWriteLock

class StampedLock:
    def __init__(self) -> None: ...
    def toString(self) -> str: ...
    def validate(self, p0: int) -> bool: ...
    def unlock(self, p0: int) -> None: ...
    def unlockWrite(self, p0: int) -> None: ...
    def unlockRead(self, p0: int) -> None: ...
    def getReadLockCount(self) -> int: ...
    def writeLock(self) -> int: ...
    @overload
    def tryWriteLock(self) -> int: ...
    @overload
    def tryWriteLock(self, p0: int, p1: TimeUnit) -> int: ...
    def writeLockInterruptibly(self) -> int: ...
    def readLock(self) -> int: ...
    @overload
    def tryReadLock(self, p0: int, p1: TimeUnit) -> int: ...
    @overload
    def tryReadLock(self) -> int: ...
    def readLockInterruptibly(self) -> int: ...
    def tryOptimisticRead(self) -> int: ...
    def tryConvertToWriteLock(self, p0: int) -> int: ...
    def tryConvertToReadLock(self, p0: int) -> int: ...
    def tryConvertToOptimisticRead(self, p0: int) -> int: ...
    def tryUnlockWrite(self) -> bool: ...
    def tryUnlockRead(self) -> bool: ...
    def isWriteLocked(self) -> bool: ...
    def isReadLocked(self) -> bool: ...
    @staticmethod
    def isWriteLockStamp(p0: int) -> bool: ...
    @staticmethod
    def isReadLockStamp(p0: int) -> bool: ...
    @staticmethod
    def isLockStamp(p0: int) -> bool: ...
    @staticmethod
    def isOptimisticReadStamp(p0: int) -> bool: ...
    def asReadLock(self) -> Lock: ...
    def asWriteLock(self) -> Lock: ...
    def asReadWriteLock(self) -> ReadWriteLock: ...
