from typing import Any, ClassVar, overload
from java.time.LocalDate import LocalDate
from java.time.chrono.ChronoPeriod import ChronoPeriod
from java.time.chrono.Chronology import Chronology
from java.time.chrono.IsoChronology import IsoChronology
from java.time.temporal.Temporal import Temporal
from java.time.temporal.TemporalAmount import TemporalAmount
from java.time.temporal.TemporalUnit import TemporalUnit

class Period:
    ZERO: ClassVar["Period"]
    def get(self, p0: TemporalUnit) -> int: ...
    def equals(self, p0: Any) -> bool: ...
    def toString(self) -> str: ...
    def hashCode(self) -> int: ...
    @staticmethod
    def of(p0: int, p1: int, p2: int) -> "Period": ...
    @staticmethod
    def from_(p0: TemporalAmount) -> "Period": ...
    @staticmethod
    def parse(p0: str) -> "Period": ...
    @staticmethod
    def between(p0: LocalDate, p1: LocalDate) -> "Period": ...
    @overload
    def plus(self, p0: TemporalAmount) -> ChronoPeriod: ...
    @overload
    def plus(self, p0: TemporalAmount) -> "Period": ...
    def getUnits(self) -> list: ...
    @overload
    def negated(self) -> "Period": ...
    @overload
    def negated(self) -> ChronoPeriod: ...
    @overload
    def multipliedBy(self, p0: int) -> ChronoPeriod: ...
    @overload
    def multipliedBy(self, p0: int) -> "Period": ...
    def plusDays(self, p0: int) -> "Period": ...
    def isNegative(self) -> bool: ...
    @overload
    def minus(self, p0: TemporalAmount) -> "Period": ...
    @overload
    def minus(self, p0: TemporalAmount) -> ChronoPeriod: ...
    @staticmethod
    def ofDays(p0: int) -> "Period": ...
    def isZero(self) -> bool: ...
    def minusDays(self, p0: int) -> "Period": ...
    def addTo(self, p0: Temporal) -> Temporal: ...
    def subtractFrom(self, p0: Temporal) -> Temporal: ...
    @overload
    def getChronology(self) -> Chronology: ...
    @overload
    def getChronology(self) -> IsoChronology: ...
    def getYears(self) -> int: ...
    def getMonths(self) -> int: ...
    def getDays(self) -> int: ...
    def plusYears(self, p0: int) -> "Period": ...
    def plusMonths(self, p0: int) -> "Period": ...
    def toTotalMonths(self) -> int: ...
    @staticmethod
    def ofYears(p0: int) -> "Period": ...
    @staticmethod
    def ofMonths(p0: int) -> "Period": ...
    @staticmethod
    def ofWeeks(p0: int) -> "Period": ...
    def withYears(self, p0: int) -> "Period": ...
    def withMonths(self, p0: int) -> "Period": ...
    def withDays(self, p0: int) -> "Period": ...
    def minusYears(self, p0: int) -> "Period": ...
    def minusMonths(self, p0: int) -> "Period": ...
    @overload
    def normalized(self) -> "Period": ...
    @overload
    def normalized(self) -> ChronoPeriod: ...

from typing import Any, ClassVar, overload
from java.time.Clock import Clock
from java.time.LocalDate import LocalDate
from java.time.Month import Month
from java.time.MonthDay import MonthDay
from java.time.YearMonth import YearMonth
from java.time.ZoneId import ZoneId
from java.time.format.DateTimeFormatter import DateTimeFormatter
from java.time.temporal.Temporal import Temporal
from java.time.temporal.TemporalAccessor import TemporalAccessor
from java.time.temporal.TemporalAdjuster import TemporalAdjuster
from java.time.temporal.TemporalAmount import TemporalAmount
from java.time.temporal.TemporalField import TemporalField
from java.time.temporal.TemporalQuery import TemporalQuery
from java.time.temporal.TemporalUnit import TemporalUnit
from java.time.temporal.ValueRange import ValueRange

class Year:
    MIN_VALUE: ClassVar[int]
    MAX_VALUE: ClassVar[int]
    def get(self, p0: TemporalField) -> int: ...
    def equals(self, p0: Any) -> bool: ...
    def length(self) -> int: ...
    def toString(self) -> str: ...
    def hashCode(self) -> int: ...
    @overload
    def compareTo(self, p0: "Year") -> int: ...
    @overload
    def compareTo(self, p0: Any) -> int: ...
    def getLong(self, p0: TemporalField) -> int: ...
    def getValue(self) -> int: ...
    def format(self, p0: DateTimeFormatter) -> str: ...
    @staticmethod
    def of(p0: int) -> "Year": ...
    @staticmethod
    def from_(p0: TemporalAccessor) -> "Year": ...
    @overload
    def isSupported(self, p0: TemporalField) -> bool: ...
    @overload
    def isSupported(self, p0: TemporalUnit) -> bool: ...
    @overload
    @staticmethod
    def parse(p0: str) -> "Year": ...
    @overload
    @staticmethod
    def parse(p0: str, p1: DateTimeFormatter) -> "Year": ...
    @overload
    def with_(self, p0: TemporalAdjuster) -> Temporal: ...
    @overload
    def with_(self, p0: TemporalField, p1: int) -> "Year": ...
    @overload
    def with_(self, p0: TemporalAdjuster) -> "Year": ...
    @overload
    def with_(self, p0: TemporalField, p1: int) -> Temporal: ...
    def adjustInto(self, p0: Temporal) -> Temporal: ...
    def isAfter(self, p0: "Year") -> bool: ...
    def isBefore(self, p0: "Year") -> bool: ...
    def query(self, p0: TemporalQuery) -> Any: ...
    def isValidMonthDay(self, p0: MonthDay) -> bool: ...
    def atDay(self, p0: int) -> LocalDate: ...
    @overload
    def atMonth(self, p0: Month) -> YearMonth: ...
    @overload
    def atMonth(self, p0: int) -> YearMonth: ...
    def atMonthDay(self, p0: MonthDay) -> LocalDate: ...
    @overload
    @staticmethod
    def now(p0: Clock) -> "Year": ...
    @overload
    @staticmethod
    def now(p0: ZoneId) -> "Year": ...
    @overload
    @staticmethod
    def now() -> "Year": ...
    @overload
    def plus(self, p0: TemporalAmount) -> "Year": ...
    @overload
    def plus(self, p0: int, p1: TemporalUnit) -> Temporal: ...
    @overload
    def plus(self, p0: TemporalAmount) -> Temporal: ...
    @overload
    def plus(self, p0: int, p1: TemporalUnit) -> "Year": ...
    def until(self, p0: Temporal, p1: TemporalUnit) -> int: ...
    @overload
    def minus(self, p0: TemporalAmount) -> Temporal: ...
    @overload
    def minus(self, p0: int, p1: TemporalUnit) -> Temporal: ...
    @overload
    def minus(self, p0: TemporalAmount) -> "Year": ...
    @overload
    def minus(self, p0: int, p1: TemporalUnit) -> "Year": ...
    def plusYears(self, p0: int) -> "Year": ...
    def minusYears(self, p0: int) -> "Year": ...
    @overload
    def isLeap(self) -> bool: ...
    @overload
    @staticmethod
    def isLeap(p0: int) -> bool: ...
    def range(self, p0: TemporalField) -> ValueRange: ...

from typing import Any, ClassVar, overload
from java.time.ZoneOffset import ZoneOffset
from java.time.format.TextStyle import TextStyle
from java.time.temporal.TemporalAccessor import TemporalAccessor
from java.time.zone.ZoneRules import ZoneRules
from java.util.Locale import Locale

class ZoneId:
    SHORT_IDS: ClassVar[dict]
    def equals(self, p0: Any) -> bool: ...
    def toString(self) -> str: ...
    def hashCode(self) -> int: ...
    @overload
    @staticmethod
    def of(p0: str, p1: dict) -> "ZoneId": ...
    @overload
    @staticmethod
    def of(p0: str) -> "ZoneId": ...
    @staticmethod
    def from_(p0: TemporalAccessor) -> "ZoneId": ...
    def getId(self) -> str: ...
    def getDisplayName(self, p0: TextStyle, p1: Locale) -> str: ...
    @staticmethod
    def getAvailableZoneIds() -> set: ...
    @staticmethod
    def ofOffset(p0: str, p1: ZoneOffset) -> "ZoneId": ...
    @staticmethod
    def systemDefault() -> "ZoneId": ...
    def getRules(self) -> ZoneRules: ...
    def normalized(self) -> "ZoneId": ...

from typing import Any, ClassVar, overload
from java.time.Clock import Clock
from java.time.DayOfWeek import DayOfWeek
from java.time.Instant import Instant
from java.time.LocalDateTime import LocalDateTime
from java.time.LocalTime import LocalTime
from java.time.Month import Month
from java.time.OffsetDateTime import OffsetDateTime
from java.time.OffsetTime import OffsetTime
from java.time.Period import Period
from java.time.ZoneId import ZoneId
from java.time.ZoneOffset import ZoneOffset
from java.time.ZonedDateTime import ZonedDateTime
from java.time.chrono.ChronoLocalDate import ChronoLocalDate
from java.time.chrono.ChronoLocalDateTime import ChronoLocalDateTime
from java.time.chrono.ChronoPeriod import ChronoPeriod
from java.time.chrono.Chronology import Chronology
from java.time.chrono.Era import Era
from java.time.chrono.IsoChronology import IsoChronology
from java.time.chrono.IsoEra import IsoEra
from java.time.format.DateTimeFormatter import DateTimeFormatter
from java.time.temporal.Temporal import Temporal
from java.time.temporal.TemporalAccessor import TemporalAccessor
from java.time.temporal.TemporalAdjuster import TemporalAdjuster
from java.time.temporal.TemporalAmount import TemporalAmount
from java.time.temporal.TemporalField import TemporalField
from java.time.temporal.TemporalQuery import TemporalQuery
from java.time.temporal.TemporalUnit import TemporalUnit
from java.time.temporal.ValueRange import ValueRange
from java.util.stream.Stream import Stream

class LocalDate:
    MIN: ClassVar["LocalDate"]
    MAX: ClassVar["LocalDate"]
    EPOCH: ClassVar["LocalDate"]
    def get(self, p0: TemporalField) -> int: ...
    def equals(self, p0: Any) -> bool: ...
    def toString(self) -> str: ...
    def hashCode(self) -> int: ...
    @overload
    def compareTo(self, p0: Any) -> int: ...
    @overload
    def compareTo(self, p0: ChronoLocalDate) -> int: ...
    def getLong(self, p0: TemporalField) -> int: ...
    def format(self, p0: DateTimeFormatter) -> str: ...
    @overload
    @staticmethod
    def of(p0: int, p1: int, p2: int) -> "LocalDate": ...
    @overload
    @staticmethod
    def of(p0: int, p1: Month, p2: int) -> "LocalDate": ...
    @staticmethod
    def from_(p0: TemporalAccessor) -> "LocalDate": ...
    @overload
    def isSupported(self, p0: TemporalUnit) -> bool: ...
    @overload
    def isSupported(self, p0: TemporalField) -> bool: ...
    @overload
    @staticmethod
    def parse(p0: str) -> "LocalDate": ...
    @overload
    @staticmethod
    def parse(p0: str, p1: DateTimeFormatter) -> "LocalDate": ...
    @overload
    def with_(self, p0: TemporalField, p1: int) -> "LocalDate": ...
    @overload
    def with_(self, p0: TemporalAdjuster) -> "LocalDate": ...
    @overload
    def with_(self, p0: TemporalAdjuster) -> ChronoLocalDate: ...
    @overload
    def with_(self, p0: TemporalField, p1: int) -> ChronoLocalDate: ...
    @overload
    def with_(self, p0: TemporalAdjuster) -> Temporal: ...
    @overload
    def with_(self, p0: TemporalField, p1: int) -> Temporal: ...
    def isLeapYear(self) -> bool: ...
    @staticmethod
    def ofEpochDay(p0: int) -> "LocalDate": ...
    def lengthOfMonth(self) -> int: ...
    def lengthOfYear(self) -> int: ...
    def toEpochDay(self) -> int: ...
    def getDayOfWeek(self) -> DayOfWeek: ...
    def getDayOfYear(self) -> int: ...
    def adjustInto(self, p0: Temporal) -> Temporal: ...
    def withDayOfMonth(self, p0: int) -> "LocalDate": ...
    def withDayOfYear(self, p0: int) -> "LocalDate": ...
    def plusWeeks(self, p0: int) -> "LocalDate": ...
    def withMonth(self, p0: int) -> "LocalDate": ...
    def withYear(self, p0: int) -> "LocalDate": ...
    @staticmethod
    def ofYearDay(p0: int, p1: int) -> "LocalDate": ...
    @overload
    def atTime(self, p0: int, p1: int, p2: int) -> LocalDateTime: ...
    @overload
    def atTime(self, p0: LocalTime) -> ChronoLocalDateTime: ...
    @overload
    def atTime(self, p0: LocalTime) -> LocalDateTime: ...
    @overload
    def atTime(self, p0: int, p1: int) -> LocalDateTime: ...
    @overload
    def atTime(self, p0: OffsetTime) -> OffsetDateTime: ...
    @overload
    def atTime(self, p0: int, p1: int, p2: int, p3: int) -> LocalDateTime: ...
    def isAfter(self, p0: ChronoLocalDate) -> bool: ...
    def isBefore(self, p0: ChronoLocalDate) -> bool: ...
    @overload
    def getEra(self) -> Era: ...
    @overload
    def getEra(self) -> IsoEra: ...
    def minusWeeks(self, p0: int) -> "LocalDate": ...
    @overload
    def datesUntil(self, p0: "LocalDate", p1: Period) -> Stream: ...
    @overload
    def datesUntil(self, p0: "LocalDate") -> Stream: ...
    @overload
    def atStartOfDay(self, p0: ZoneId) -> ZonedDateTime: ...
    @overload
    def atStartOfDay(self) -> LocalDateTime: ...
    def toEpochSecond(self, p0: LocalTime, p1: ZoneOffset) -> int: ...
    def getYear(self) -> int: ...
    def getMonthValue(self) -> int: ...
    def getDayOfMonth(self) -> int: ...
    @staticmethod
    def ofInstant(p0: Instant, p1: ZoneId) -> "LocalDate": ...
    def getMonth(self) -> Month: ...
    def query(self, p0: TemporalQuery) -> Any: ...
    def isEqual(self, p0: ChronoLocalDate) -> bool: ...
    @overload
    @staticmethod
    def now(p0: Clock) -> "LocalDate": ...
    @overload
    @staticmethod
    def now(p0: ZoneId) -> "LocalDate": ...
    @overload
    @staticmethod
    def now() -> "LocalDate": ...
    @overload
    def plus(self, p0: TemporalAmount) -> Temporal: ...
    @overload
    def plus(self, p0: int, p1: TemporalUnit) -> ChronoLocalDate: ...
    @overload
    def plus(self, p0: int, p1: TemporalUnit) -> Temporal: ...
    @overload
    def plus(self, p0: int, p1: TemporalUnit) -> "LocalDate": ...
    @overload
    def plus(self, p0: TemporalAmount) -> "LocalDate": ...
    @overload
    def plus(self, p0: TemporalAmount) -> ChronoLocalDate: ...
    @overload
    def until(self, p0: ChronoLocalDate) -> ChronoPeriod: ...
    @overload
    def until(self, p0: ChronoLocalDate) -> Period: ...
    @overload
    def until(self, p0: Temporal, p1: TemporalUnit) -> int: ...
    def plusDays(self, p0: int) -> "LocalDate": ...
    @overload
    def minus(self, p0: int, p1: TemporalUnit) -> ChronoLocalDate: ...
    @overload
    def minus(self, p0: TemporalAmount) -> ChronoLocalDate: ...
    @overload
    def minus(self, p0: TemporalAmount) -> "LocalDate": ...
    @overload
    def minus(self, p0: int, p1: TemporalUnit) -> "LocalDate": ...
    @overload
    def minus(self, p0: TemporalAmount) -> Temporal: ...
    @overload
    def minus(self, p0: int, p1: TemporalUnit) -> Temporal: ...
    def minusDays(self, p0: int) -> "LocalDate": ...
    @overload
    def getChronology(self) -> IsoChronology: ...
    @overload
    def getChronology(self) -> Chronology: ...
    def plusYears(self, p0: int) -> "LocalDate": ...
    def plusMonths(self, p0: int) -> "LocalDate": ...
    def minusYears(self, p0: int) -> "LocalDate": ...
    def minusMonths(self, p0: int) -> "LocalDate": ...
    def range(self, p0: TemporalField) -> ValueRange: ...

from typing import Any, ClassVar, overload
from java.time.temporal.Temporal import Temporal
from java.time.temporal.TemporalAmount import TemporalAmount
from java.time.temporal.TemporalUnit import TemporalUnit

class Duration:
    ZERO: ClassVar["Duration"]
    def get(self, p0: TemporalUnit) -> int: ...
    def equals(self, p0: Any) -> bool: ...
    def toString(self) -> str: ...
    def hashCode(self) -> int: ...
    def abs(self) -> "Duration": ...
    @overload
    def compareTo(self, p0: Any) -> int: ...
    @overload
    def compareTo(self, p0: "Duration") -> int: ...
    @staticmethod
    def of(p0: int, p1: TemporalUnit) -> "Duration": ...
    @staticmethod
    def from_(p0: TemporalAmount) -> "Duration": ...
    def toNanos(self) -> int: ...
    def toMillis(self) -> int: ...
    @staticmethod
    def parse(p0: str) -> "Duration": ...
    @staticmethod
    def between(p0: Temporal, p1: Temporal) -> "Duration": ...
    @overload
    def plus(self, p0: "Duration") -> "Duration": ...
    @overload
    def plus(self, p0: int, p1: TemporalUnit) -> "Duration": ...
    def getUnits(self) -> list: ...
    @overload
    @staticmethod
    def ofSeconds(p0: int, p1: int) -> "Duration": ...
    @overload
    @staticmethod
    def ofSeconds(p0: int) -> "Duration": ...
    def negated(self) -> "Duration": ...
    @staticmethod
    def ofNanos(p0: int) -> "Duration": ...
    def plusNanos(self, p0: int) -> "Duration": ...
    def plusSeconds(self, p0: int) -> "Duration": ...
    def plusMillis(self, p0: int) -> "Duration": ...
    def multipliedBy(self, p0: int) -> "Duration": ...
    def plusDays(self, p0: int) -> "Duration": ...
    def plusHours(self, p0: int) -> "Duration": ...
    def plusMinutes(self, p0: int) -> "Duration": ...
    def isNegative(self) -> bool: ...
    @overload
    def minus(self, p0: "Duration") -> "Duration": ...
    @overload
    def minus(self, p0: int, p1: TemporalUnit) -> "Duration": ...
    @staticmethod
    def ofDays(p0: int) -> "Duration": ...
    @staticmethod
    def ofHours(p0: int) -> "Duration": ...
    @staticmethod
    def ofMinutes(p0: int) -> "Duration": ...
    @staticmethod
    def ofMillis(p0: int) -> "Duration": ...
    def isPositive(self) -> bool: ...
    def isZero(self) -> bool: ...
    def withSeconds(self, p0: int) -> "Duration": ...
    def withNanos(self, p0: int) -> "Duration": ...
    def minusDays(self, p0: int) -> "Duration": ...
    def minusHours(self, p0: int) -> "Duration": ...
    def minusMinutes(self, p0: int) -> "Duration": ...
    def minusSeconds(self, p0: int) -> "Duration": ...
    def minusMillis(self, p0: int) -> "Duration": ...
    def minusNanos(self, p0: int) -> "Duration": ...
    @overload
    def dividedBy(self, p0: int) -> "Duration": ...
    @overload
    def dividedBy(self, p0: "Duration") -> int: ...
    def addTo(self, p0: Temporal) -> Temporal: ...
    def subtractFrom(self, p0: Temporal) -> Temporal: ...
    def toDaysPart(self) -> int: ...
    def toHoursPart(self) -> int: ...
    def toMinutesPart(self) -> int: ...
    def toSecondsPart(self) -> int: ...
    def toMillisPart(self) -> int: ...
    def toNanosPart(self) -> int: ...
    def truncatedTo(self, p0: TemporalUnit) -> "Duration": ...
    def toSeconds(self) -> int: ...
    def getSeconds(self) -> int: ...
    def getNano(self) -> int: ...
    def toMinutes(self) -> int: ...
    def toHours(self) -> int: ...
    def toDays(self) -> int: ...

from typing import Any, ClassVar, overload
from java.time.Clock import Clock
from java.time.LocalDate import LocalDate
from java.time.Month import Month
from java.time.ZoneId import ZoneId
from java.time.format.DateTimeFormatter import DateTimeFormatter
from java.time.temporal.Temporal import Temporal
from java.time.temporal.TemporalAccessor import TemporalAccessor
from java.time.temporal.TemporalField import TemporalField
from java.time.temporal.TemporalQuery import TemporalQuery
from java.time.temporal.ValueRange import ValueRange

class MonthDay:
    def get(self, p0: TemporalField) -> int: ...
    def equals(self, p0: Any) -> bool: ...
    def toString(self) -> str: ...
    def hashCode(self) -> int: ...
    @overload
    def compareTo(self, p0: "MonthDay") -> int: ...
    @overload
    def compareTo(self, p0: Any) -> int: ...
    def getLong(self, p0: TemporalField) -> int: ...
    def format(self, p0: DateTimeFormatter) -> str: ...
    @overload
    @staticmethod
    def of(p0: Month, p1: int) -> "MonthDay": ...
    @overload
    @staticmethod
    def of(p0: int, p1: int) -> "MonthDay": ...
    @staticmethod
    def from_(p0: TemporalAccessor) -> "MonthDay": ...
    def isSupported(self, p0: TemporalField) -> bool: ...
    @overload
    @staticmethod
    def parse(p0: str) -> "MonthDay": ...
    @overload
    @staticmethod
    def parse(p0: str, p1: DateTimeFormatter) -> "MonthDay": ...
    def with_(self, p0: Month) -> "MonthDay": ...
    def adjustInto(self, p0: Temporal) -> Temporal: ...
    def withDayOfMonth(self, p0: int) -> "MonthDay": ...
    def withMonth(self, p0: int) -> "MonthDay": ...
    def isAfter(self, p0: "MonthDay") -> bool: ...
    def isBefore(self, p0: "MonthDay") -> bool: ...
    def getMonthValue(self) -> int: ...
    def getDayOfMonth(self) -> int: ...
    def getMonth(self) -> Month: ...
    def query(self, p0: TemporalQuery) -> Any: ...
    @overload
    @staticmethod
    def now() -> "MonthDay": ...
    @overload
    @staticmethod
    def now(p0: ZoneId) -> "MonthDay": ...
    @overload
    @staticmethod
    def now(p0: Clock) -> "MonthDay": ...
    def isValidYear(self, p0: int) -> bool: ...
    def atYear(self, p0: int) -> LocalDate: ...
    def range(self, p0: TemporalField) -> ValueRange: ...

from typing import Any, ClassVar, overload
from java.time.Clock import Clock
from java.time.Instant import Instant
from java.time.LocalDate import LocalDate
from java.time.LocalTime import LocalTime
from java.time.OffsetDateTime import OffsetDateTime
from java.time.ZoneId import ZoneId
from java.time.ZoneOffset import ZoneOffset
from java.time.format.DateTimeFormatter import DateTimeFormatter
from java.time.temporal.Temporal import Temporal
from java.time.temporal.TemporalAccessor import TemporalAccessor
from java.time.temporal.TemporalAdjuster import TemporalAdjuster
from java.time.temporal.TemporalAmount import TemporalAmount
from java.time.temporal.TemporalField import TemporalField
from java.time.temporal.TemporalQuery import TemporalQuery
from java.time.temporal.TemporalUnit import TemporalUnit
from java.time.temporal.ValueRange import ValueRange

class OffsetTime:
    MIN: ClassVar["OffsetTime"]
    MAX: ClassVar["OffsetTime"]
    def get(self, p0: TemporalField) -> int: ...
    def equals(self, p0: Any) -> bool: ...
    def toString(self) -> str: ...
    def hashCode(self) -> int: ...
    @overload
    def compareTo(self, p0: Any) -> int: ...
    @overload
    def compareTo(self, p0: "OffsetTime") -> int: ...
    def getLong(self, p0: TemporalField) -> int: ...
    def format(self, p0: DateTimeFormatter) -> str: ...
    @overload
    @staticmethod
    def of(p0: LocalTime, p1: ZoneOffset) -> "OffsetTime": ...
    @overload
    @staticmethod
    def of(p0: int, p1: int, p2: int, p3: int, p4: ZoneOffset) -> "OffsetTime": ...
    @staticmethod
    def from_(p0: TemporalAccessor) -> "OffsetTime": ...
    @overload
    def isSupported(self, p0: TemporalUnit) -> bool: ...
    @overload
    def isSupported(self, p0: TemporalField) -> bool: ...
    @overload
    @staticmethod
    def parse(p0: str) -> "OffsetTime": ...
    @overload
    @staticmethod
    def parse(p0: str, p1: DateTimeFormatter) -> "OffsetTime": ...
    @overload
    def with_(self, p0: TemporalField, p1: int) -> Temporal: ...
    @overload
    def with_(self, p0: TemporalAdjuster) -> Temporal: ...
    @overload
    def with_(self, p0: TemporalField, p1: int) -> "OffsetTime": ...
    @overload
    def with_(self, p0: TemporalAdjuster) -> "OffsetTime": ...
    def getOffset(self) -> ZoneOffset: ...
    def adjustInto(self, p0: Temporal) -> Temporal: ...
    def toLocalTime(self) -> LocalTime: ...
    def isAfter(self, p0: "OffsetTime") -> bool: ...
    def isBefore(self, p0: "OffsetTime") -> bool: ...
    def withHour(self, p0: int) -> "OffsetTime": ...
    def withMinute(self, p0: int) -> "OffsetTime": ...
    def withSecond(self, p0: int) -> "OffsetTime": ...
    def withNano(self, p0: int) -> "OffsetTime": ...
    def toEpochSecond(self, p0: LocalDate) -> int: ...
    def getHour(self) -> int: ...
    def getMinute(self) -> int: ...
    def getSecond(self) -> int: ...
    @staticmethod
    def ofInstant(p0: Instant, p1: ZoneId) -> "OffsetTime": ...
    def query(self, p0: TemporalQuery) -> Any: ...
    def atDate(self, p0: LocalDate) -> OffsetDateTime: ...
    def withOffsetSameLocal(self, p0: ZoneOffset) -> "OffsetTime": ...
    def withOffsetSameInstant(self, p0: ZoneOffset) -> "OffsetTime": ...
    def isEqual(self, p0: "OffsetTime") -> bool: ...
    @overload
    @staticmethod
    def now(p0: Clock) -> "OffsetTime": ...
    @overload
    @staticmethod
    def now(p0: ZoneId) -> "OffsetTime": ...
    @overload
    @staticmethod
    def now() -> "OffsetTime": ...
    @overload
    def plus(self, p0: int, p1: TemporalUnit) -> "OffsetTime": ...
    @overload
    def plus(self, p0: int, p1: TemporalUnit) -> Temporal: ...
    @overload
    def plus(self, p0: TemporalAmount) -> "OffsetTime": ...
    @overload
    def plus(self, p0: TemporalAmount) -> Temporal: ...
    def until(self, p0: Temporal, p1: TemporalUnit) -> int: ...
    def plusNanos(self, p0: int) -> "OffsetTime": ...
    def plusSeconds(self, p0: int) -> "OffsetTime": ...
    def plusHours(self, p0: int) -> "OffsetTime": ...
    def plusMinutes(self, p0: int) -> "OffsetTime": ...
    @overload
    def minus(self, p0: int, p1: TemporalUnit) -> "OffsetTime": ...
    @overload
    def minus(self, p0: TemporalAmount) -> Temporal: ...
    @overload
    def minus(self, p0: int, p1: TemporalUnit) -> Temporal: ...
    @overload
    def minus(self, p0: TemporalAmount) -> "OffsetTime": ...
    def minusHours(self, p0: int) -> "OffsetTime": ...
    def minusMinutes(self, p0: int) -> "OffsetTime": ...
    def minusSeconds(self, p0: int) -> "OffsetTime": ...
    def minusNanos(self, p0: int) -> "OffsetTime": ...
    def truncatedTo(self, p0: TemporalUnit) -> "OffsetTime": ...
    def range(self, p0: TemporalField) -> ValueRange: ...
    def getNano(self) -> int: ...

from typing import Any, ClassVar, overload
from java.time.format.TextStyle import TextStyle
from java.time.temporal.Temporal import Temporal
from java.time.temporal.TemporalAccessor import TemporalAccessor
from java.time.temporal.TemporalField import TemporalField
from java.time.temporal.TemporalQuery import TemporalQuery
from java.time.temporal.ValueRange import ValueRange
from java.util.Locale import Locale

class Month:
    JANUARY: ClassVar["Month"]
    FEBRUARY: ClassVar["Month"]
    MARCH: ClassVar["Month"]
    APRIL: ClassVar["Month"]
    MAY: ClassVar["Month"]
    JUNE: ClassVar["Month"]
    JULY: ClassVar["Month"]
    AUGUST: ClassVar["Month"]
    SEPTEMBER: ClassVar["Month"]
    OCTOBER: ClassVar["Month"]
    NOVEMBER: ClassVar["Month"]
    DECEMBER: ClassVar["Month"]
    JANUARY: ClassVar["Month"]
    FEBRUARY: ClassVar["Month"]
    MARCH: ClassVar["Month"]
    APRIL: ClassVar["Month"]
    MAY: ClassVar["Month"]
    JUNE: ClassVar["Month"]
    JULY: ClassVar["Month"]
    AUGUST: ClassVar["Month"]
    SEPTEMBER: ClassVar["Month"]
    OCTOBER: ClassVar["Month"]
    NOVEMBER: ClassVar["Month"]
    DECEMBER: ClassVar["Month"]
    def minLength(self) -> int: ...
    def get(self, p0: TemporalField) -> int: ...
    def length(self, p0: bool) -> int: ...
    @staticmethod
    def values() -> Any: ...
    def getLong(self, p0: TemporalField) -> int: ...
    @staticmethod
    def valueOf(p0: str) -> "Month": ...
    def getValue(self) -> int: ...
    @staticmethod
    def of(p0: int) -> "Month": ...
    @staticmethod
    def from_(p0: TemporalAccessor) -> "Month": ...
    def isSupported(self, p0: TemporalField) -> bool: ...
    def getDisplayName(self, p0: TextStyle, p1: Locale) -> str: ...
    def firstDayOfYear(self, p0: bool) -> int: ...
    def adjustInto(self, p0: Temporal) -> Temporal: ...
    def maxLength(self) -> int: ...
    def query(self, p0: TemporalQuery) -> Any: ...
    def firstMonthOfQuarter(self) -> "Month": ...
    def plus(self, p0: int) -> "Month": ...
    def minus(self, p0: int) -> "Month": ...
    def range(self, p0: TemporalField) -> ValueRange: ...

from typing import Any, ClassVar, overload
from java.time.Clock import Clock
from java.time.Instant import Instant
from java.time.LocalDate import LocalDate
from java.time.LocalDateTime import LocalDateTime
from java.time.OffsetTime import OffsetTime
from java.time.ZoneId import ZoneId
from java.time.ZoneOffset import ZoneOffset
from java.time.format.DateTimeFormatter import DateTimeFormatter
from java.time.temporal.Temporal import Temporal
from java.time.temporal.TemporalAccessor import TemporalAccessor
from java.time.temporal.TemporalAdjuster import TemporalAdjuster
from java.time.temporal.TemporalAmount import TemporalAmount
from java.time.temporal.TemporalField import TemporalField
from java.time.temporal.TemporalQuery import TemporalQuery
from java.time.temporal.TemporalUnit import TemporalUnit
from java.time.temporal.ValueRange import ValueRange

class LocalTime:
    MIN: ClassVar["LocalTime"]
    MAX: ClassVar["LocalTime"]
    MIDNIGHT: ClassVar["LocalTime"]
    NOON: ClassVar["LocalTime"]
    def get(self, p0: TemporalField) -> int: ...
    def equals(self, p0: Any) -> bool: ...
    def toString(self) -> str: ...
    def hashCode(self) -> int: ...
    @overload
    def compareTo(self, p0: Any) -> int: ...
    @overload
    def compareTo(self, p0: "LocalTime") -> int: ...
    def getLong(self, p0: TemporalField) -> int: ...
    def format(self, p0: DateTimeFormatter) -> str: ...
    @overload
    @staticmethod
    def of(p0: int, p1: int, p2: int) -> "LocalTime": ...
    @overload
    @staticmethod
    def of(p0: int, p1: int, p2: int, p3: int) -> "LocalTime": ...
    @overload
    @staticmethod
    def of(p0: int, p1: int) -> "LocalTime": ...
    @staticmethod
    def from_(p0: TemporalAccessor) -> "LocalTime": ...
    @overload
    def isSupported(self, p0: TemporalUnit) -> bool: ...
    @overload
    def isSupported(self, p0: TemporalField) -> bool: ...
    @overload
    @staticmethod
    def parse(p0: str) -> "LocalTime": ...
    @overload
    @staticmethod
    def parse(p0: str, p1: DateTimeFormatter) -> "LocalTime": ...
    @overload
    def with_(self, p0: TemporalField, p1: int) -> "LocalTime": ...
    @overload
    def with_(self, p0: TemporalAdjuster) -> "LocalTime": ...
    @overload
    def with_(self, p0: TemporalAdjuster) -> Temporal: ...
    @overload
    def with_(self, p0: TemporalField, p1: int) -> Temporal: ...
    def adjustInto(self, p0: Temporal) -> Temporal: ...
    def toSecondOfDay(self) -> int: ...
    def isAfter(self, p0: "LocalTime") -> bool: ...
    def isBefore(self, p0: "LocalTime") -> bool: ...
    def atOffset(self, p0: ZoneOffset) -> OffsetTime: ...
    @staticmethod
    def ofNanoOfDay(p0: int) -> "LocalTime": ...
    def withHour(self, p0: int) -> "LocalTime": ...
    def withMinute(self, p0: int) -> "LocalTime": ...
    def withSecond(self, p0: int) -> "LocalTime": ...
    def withNano(self, p0: int) -> "LocalTime": ...
    def toNanoOfDay(self) -> int: ...
    def toEpochSecond(self, p0: LocalDate, p1: ZoneOffset) -> int: ...
    def getHour(self) -> int: ...
    def getMinute(self) -> int: ...
    def getSecond(self) -> int: ...
    @staticmethod
    def ofInstant(p0: Instant, p1: ZoneId) -> "LocalTime": ...
    def query(self, p0: TemporalQuery) -> Any: ...
    @staticmethod
    def ofSecondOfDay(p0: int) -> "LocalTime": ...
    def atDate(self, p0: LocalDate) -> LocalDateTime: ...
    @overload
    @staticmethod
    def now(p0: Clock) -> "LocalTime": ...
    @overload
    @staticmethod
    def now(p0: ZoneId) -> "LocalTime": ...
    @overload
    @staticmethod
    def now() -> "LocalTime": ...
    @overload
    def plus(self, p0: TemporalAmount) -> "LocalTime": ...
    @overload
    def plus(self, p0: int, p1: TemporalUnit) -> "LocalTime": ...
    @overload
    def plus(self, p0: int, p1: TemporalUnit) -> Temporal: ...
    @overload
    def plus(self, p0: TemporalAmount) -> Temporal: ...
    def until(self, p0: Temporal, p1: TemporalUnit) -> int: ...
    def plusNanos(self, p0: int) -> "LocalTime": ...
    def plusSeconds(self, p0: int) -> "LocalTime": ...
    def plusHours(self, p0: int) -> "LocalTime": ...
    def plusMinutes(self, p0: int) -> "LocalTime": ...
    @overload
    def minus(self, p0: TemporalAmount) -> Temporal: ...
    @overload
    def minus(self, p0: int, p1: TemporalUnit) -> Temporal: ...
    @overload
    def minus(self, p0: TemporalAmount) -> "LocalTime": ...
    @overload
    def minus(self, p0: int, p1: TemporalUnit) -> "LocalTime": ...
    def minusHours(self, p0: int) -> "LocalTime": ...
    def minusMinutes(self, p0: int) -> "LocalTime": ...
    def minusSeconds(self, p0: int) -> "LocalTime": ...
    def minusNanos(self, p0: int) -> "LocalTime": ...
    def truncatedTo(self, p0: TemporalUnit) -> "LocalTime": ...
    def range(self, p0: TemporalField) -> ValueRange: ...
    def getNano(self) -> int: ...

from typing import Any, ClassVar, overload
from java.time.ZoneId import ZoneId
from java.time.temporal.Temporal import Temporal
from java.time.temporal.TemporalAccessor import TemporalAccessor
from java.time.temporal.TemporalField import TemporalField
from java.time.temporal.TemporalQuery import TemporalQuery
from java.time.temporal.ValueRange import ValueRange
from java.time.zone.ZoneRules import ZoneRules

class ZoneOffset:
    UTC: ClassVar["ZoneOffset"]
    MIN: ClassVar["ZoneOffset"]
    MAX: ClassVar["ZoneOffset"]
    SHORT_IDS: ClassVar[dict]
    def get(self, p0: TemporalField) -> int: ...
    def equals(self, p0: Any) -> bool: ...
    def toString(self) -> str: ...
    def hashCode(self) -> int: ...
    @overload
    def compareTo(self, p0: "ZoneOffset") -> int: ...
    @overload
    def compareTo(self, p0: Any) -> int: ...
    def getLong(self, p0: TemporalField) -> int: ...
    @staticmethod
    def of(p0: str) -> "ZoneOffset": ...
    @staticmethod
    def from_(p0: TemporalAccessor) -> "ZoneOffset": ...
    def isSupported(self, p0: TemporalField) -> bool: ...
    def getId(self) -> str: ...
    def getTotalSeconds(self) -> int: ...
    def adjustInto(self, p0: Temporal) -> Temporal: ...
    @staticmethod
    def ofHoursMinutesSeconds(p0: int, p1: int, p2: int) -> "ZoneOffset": ...
    @staticmethod
    def ofTotalSeconds(p0: int) -> "ZoneOffset": ...
    @staticmethod
    def ofHoursMinutes(p0: int, p1: int) -> "ZoneOffset": ...
    def getRules(self) -> ZoneRules: ...
    def query(self, p0: TemporalQuery) -> Any: ...
    @staticmethod
    def ofHours(p0: int) -> "ZoneOffset": ...
    def range(self, p0: TemporalField) -> ValueRange: ...
    def normalized(self) -> ZoneId: ...

from typing import Any, ClassVar, overload
from java.time.Clock import Clock
from java.time.Duration import Duration
from java.time.Instant import Instant
from java.time.ZoneId import ZoneId

class InstantSource:
    @staticmethod
    def fixed(p0: Instant) -> "InstantSource": ...
    @staticmethod
    def offset(p0: "InstantSource", p1: Duration) -> "InstantSource": ...
    def millis(self) -> int: ...
    @staticmethod
    def system() -> "InstantSource": ...
    def instant(self) -> Instant: ...
    @staticmethod
    def tick(p0: "InstantSource", p1: Duration) -> "InstantSource": ...
    def withZone(self, p0: ZoneId) -> Clock: ...

from typing import Any, ClassVar, overload
from java.time.Clock import Clock
from java.time.DayOfWeek import DayOfWeek
from java.time.Instant import Instant
from java.time.LocalDate import LocalDate
from java.time.LocalDateTime import LocalDateTime
from java.time.LocalTime import LocalTime
from java.time.Month import Month
from java.time.OffsetDateTime import OffsetDateTime
from java.time.ZoneId import ZoneId
from java.time.ZoneOffset import ZoneOffset
from java.time.chrono.ChronoLocalDate import ChronoLocalDate
from java.time.chrono.ChronoLocalDateTime import ChronoLocalDateTime
from java.time.chrono.ChronoZonedDateTime import ChronoZonedDateTime
from java.time.format.DateTimeFormatter import DateTimeFormatter
from java.time.temporal.Temporal import Temporal
from java.time.temporal.TemporalAccessor import TemporalAccessor
from java.time.temporal.TemporalAdjuster import TemporalAdjuster
from java.time.temporal.TemporalAmount import TemporalAmount
from java.time.temporal.TemporalField import TemporalField
from java.time.temporal.TemporalQuery import TemporalQuery
from java.time.temporal.TemporalUnit import TemporalUnit
from java.time.temporal.ValueRange import ValueRange

class ZonedDateTime:
    @staticmethod
    def ofLocal(p0: LocalDateTime, p1: ZoneId, p2: ZoneOffset) -> "ZonedDateTime": ...
    def get(self, p0: TemporalField) -> int: ...
    def equals(self, p0: Any) -> bool: ...
    def toString(self) -> str: ...
    def hashCode(self) -> int: ...
    def getLong(self, p0: TemporalField) -> int: ...
    def format(self, p0: DateTimeFormatter) -> str: ...
    @overload
    @staticmethod
    def of(p0: LocalDate, p1: LocalTime, p2: ZoneId) -> "ZonedDateTime": ...
    @overload
    @staticmethod
    def of(p0: LocalDateTime, p1: ZoneId) -> "ZonedDateTime": ...
    @overload
    @staticmethod
    def of(p0: int, p1: int, p2: int, p3: int, p4: int, p5: int, p6: int, p7: ZoneId) -> "ZonedDateTime": ...
    @staticmethod
    def from_(p0: TemporalAccessor) -> "ZonedDateTime": ...
    @overload
    def isSupported(self, p0: TemporalUnit) -> bool: ...
    @overload
    def isSupported(self, p0: TemporalField) -> bool: ...
    @overload
    @staticmethod
    def parse(p0: str) -> "ZonedDateTime": ...
    @overload
    @staticmethod
    def parse(p0: str, p1: DateTimeFormatter) -> "ZonedDateTime": ...
    @overload
    def with_(self, p0: TemporalAdjuster) -> "ZonedDateTime": ...
    @overload
    def with_(self, p0: TemporalField, p1: int) -> "ZonedDateTime": ...
    @overload
    def with_(self, p0: TemporalAdjuster) -> ChronoZonedDateTime: ...
    @overload
    def with_(self, p0: TemporalField, p1: int) -> ChronoZonedDateTime: ...
    @overload
    def with_(self, p0: TemporalField, p1: int) -> Temporal: ...
    @overload
    def with_(self, p0: TemporalAdjuster) -> Temporal: ...
    def getOffset(self) -> ZoneOffset: ...
    def getZone(self) -> ZoneId: ...
    def getDayOfWeek(self) -> DayOfWeek: ...
    def getDayOfYear(self) -> int: ...
    def withDayOfMonth(self, p0: int) -> "ZonedDateTime": ...
    def withDayOfYear(self, p0: int) -> "ZonedDateTime": ...
    def plusWeeks(self, p0: int) -> "ZonedDateTime": ...
    def withMonth(self, p0: int) -> "ZonedDateTime": ...
    def withYear(self, p0: int) -> "ZonedDateTime": ...
    def toLocalTime(self) -> LocalTime: ...
    def minusWeeks(self, p0: int) -> "ZonedDateTime": ...
    @overload
    def toLocalDateTime(self) -> ChronoLocalDateTime: ...
    @overload
    def toLocalDateTime(self) -> LocalDateTime: ...
    def withHour(self, p0: int) -> "ZonedDateTime": ...
    def withMinute(self, p0: int) -> "ZonedDateTime": ...
    def withSecond(self, p0: int) -> "ZonedDateTime": ...
    def withNano(self, p0: int) -> "ZonedDateTime": ...
    @overload
    def toLocalDate(self) -> ChronoLocalDate: ...
    @overload
    def toLocalDate(self) -> LocalDate: ...
    def getYear(self) -> int: ...
    def getMonthValue(self) -> int: ...
    def getDayOfMonth(self) -> int: ...
    def getHour(self) -> int: ...
    def getMinute(self) -> int: ...
    def getSecond(self) -> int: ...
    @overload
    @staticmethod
    def ofInstant(p0: LocalDateTime, p1: ZoneOffset, p2: ZoneId) -> "ZonedDateTime": ...
    @overload
    @staticmethod
    def ofInstant(p0: Instant, p1: ZoneId) -> "ZonedDateTime": ...
    def getMonth(self) -> Month: ...
    def query(self, p0: TemporalQuery) -> Any: ...
    @overload
    @staticmethod
    def now() -> "ZonedDateTime": ...
    @overload
    @staticmethod
    def now(p0: ZoneId) -> "ZonedDateTime": ...
    @overload
    @staticmethod
    def now(p0: Clock) -> "ZonedDateTime": ...
    @overload
    def plus(self, p0: int, p1: TemporalUnit) -> Temporal: ...
    @overload
    def plus(self, p0: TemporalAmount) -> "ZonedDateTime": ...
    @overload
    def plus(self, p0: TemporalAmount) -> Temporal: ...
    @overload
    def plus(self, p0: int, p1: TemporalUnit) -> ChronoZonedDateTime: ...
    @overload
    def plus(self, p0: TemporalAmount) -> ChronoZonedDateTime: ...
    @overload
    def plus(self, p0: int, p1: TemporalUnit) -> "ZonedDateTime": ...
    def until(self, p0: Temporal, p1: TemporalUnit) -> int: ...
    def plusNanos(self, p0: int) -> "ZonedDateTime": ...
    def plusSeconds(self, p0: int) -> "ZonedDateTime": ...
    def plusDays(self, p0: int) -> "ZonedDateTime": ...
    def plusHours(self, p0: int) -> "ZonedDateTime": ...
    def plusMinutes(self, p0: int) -> "ZonedDateTime": ...
    @overload
    def minus(self, p0: TemporalAmount) -> Temporal: ...
    @overload
    def minus(self, p0: int, p1: TemporalUnit) -> Temporal: ...
    @overload
    def minus(self, p0: TemporalAmount) -> "ZonedDateTime": ...
    @overload
    def minus(self, p0: TemporalAmount) -> ChronoZonedDateTime: ...
    @overload
    def minus(self, p0: int, p1: TemporalUnit) -> ChronoZonedDateTime: ...
    @overload
    def minus(self, p0: int, p1: TemporalUnit) -> "ZonedDateTime": ...
    def minusDays(self, p0: int) -> "ZonedDateTime": ...
    def minusHours(self, p0: int) -> "ZonedDateTime": ...
    def minusMinutes(self, p0: int) -> "ZonedDateTime": ...
    def minusSeconds(self, p0: int) -> "ZonedDateTime": ...
    def minusNanos(self, p0: int) -> "ZonedDateTime": ...
    def truncatedTo(self, p0: TemporalUnit) -> "ZonedDateTime": ...
    def plusYears(self, p0: int) -> "ZonedDateTime": ...
    def plusMonths(self, p0: int) -> "ZonedDateTime": ...
    def minusYears(self, p0: int) -> "ZonedDateTime": ...
    def minusMonths(self, p0: int) -> "ZonedDateTime": ...
    def range(self, p0: TemporalField) -> ValueRange: ...
    def getNano(self) -> int: ...
    @overload
    def withZoneSameInstant(self, p0: ZoneId) -> ChronoZonedDateTime: ...
    @overload
    def withZoneSameInstant(self, p0: ZoneId) -> "ZonedDateTime": ...
    def toOffsetDateTime(self) -> OffsetDateTime: ...
    @overload
    def withZoneSameLocal(self, p0: ZoneId) -> ChronoZonedDateTime: ...
    @overload
    def withZoneSameLocal(self, p0: ZoneId) -> "ZonedDateTime": ...
    @overload
    def withLaterOffsetAtOverlap(self) -> ChronoZonedDateTime: ...
    @overload
    def withLaterOffsetAtOverlap(self) -> "ZonedDateTime": ...
    @overload
    def withEarlierOffsetAtOverlap(self) -> "ZonedDateTime": ...
    @overload
    def withEarlierOffsetAtOverlap(self) -> ChronoZonedDateTime: ...
    @staticmethod
    def ofStrict(p0: LocalDateTime, p1: ZoneOffset, p2: ZoneId) -> "ZonedDateTime": ...
    def withFixedOffsetZone(self) -> "ZonedDateTime": ...

from typing import Any, ClassVar, overload
from java.time.Clock import Clock
from java.time.DayOfWeek import DayOfWeek
from java.time.Instant import Instant
from java.time.LocalDate import LocalDate
from java.time.LocalDateTime import LocalDateTime
from java.time.LocalTime import LocalTime
from java.time.Month import Month
from java.time.OffsetTime import OffsetTime
from java.time.ZoneId import ZoneId
from java.time.ZoneOffset import ZoneOffset
from java.time.ZonedDateTime import ZonedDateTime
from java.time.format.DateTimeFormatter import DateTimeFormatter
from java.time.temporal.Temporal import Temporal
from java.time.temporal.TemporalAccessor import TemporalAccessor
from java.time.temporal.TemporalAdjuster import TemporalAdjuster
from java.time.temporal.TemporalAmount import TemporalAmount
from java.time.temporal.TemporalField import TemporalField
from java.time.temporal.TemporalQuery import TemporalQuery
from java.time.temporal.TemporalUnit import TemporalUnit
from java.time.temporal.ValueRange import ValueRange
from java.util.Comparator import Comparator

class OffsetDateTime:
    MIN: ClassVar["OffsetDateTime"]
    MAX: ClassVar["OffsetDateTime"]
    def toZonedDateTime(self) -> ZonedDateTime: ...
    def get(self, p0: TemporalField) -> int: ...
    def equals(self, p0: Any) -> bool: ...
    def toString(self) -> str: ...
    def hashCode(self) -> int: ...
    @overload
    def compareTo(self, p0: Any) -> int: ...
    @overload
    def compareTo(self, p0: "OffsetDateTime") -> int: ...
    def getLong(self, p0: TemporalField) -> int: ...
    def format(self, p0: DateTimeFormatter) -> str: ...
    @overload
    @staticmethod
    def of(p0: LocalDate, p1: LocalTime, p2: ZoneOffset) -> "OffsetDateTime": ...
    @overload
    @staticmethod
    def of(p0: LocalDateTime, p1: ZoneOffset) -> "OffsetDateTime": ...
    @overload
    @staticmethod
    def of(p0: int, p1: int, p2: int, p3: int, p4: int, p5: int, p6: int, p7: ZoneOffset) -> "OffsetDateTime": ...
    @staticmethod
    def from_(p0: TemporalAccessor) -> "OffsetDateTime": ...
    @overload
    def isSupported(self, p0: TemporalUnit) -> bool: ...
    @overload
    def isSupported(self, p0: TemporalField) -> bool: ...
    @overload
    @staticmethod
    def parse(p0: str) -> "OffsetDateTime": ...
    @overload
    @staticmethod
    def parse(p0: str, p1: DateTimeFormatter) -> "OffsetDateTime": ...
    @overload
    def with_(self, p0: TemporalAdjuster) -> Temporal: ...
    @overload
    def with_(self, p0: TemporalAdjuster) -> "OffsetDateTime": ...
    @overload
    def with_(self, p0: TemporalField, p1: int) -> "OffsetDateTime": ...
    @overload
    def with_(self, p0: TemporalField, p1: int) -> Temporal: ...
    def getOffset(self) -> ZoneOffset: ...
    def getDayOfWeek(self) -> DayOfWeek: ...
    def getDayOfYear(self) -> int: ...
    def adjustInto(self, p0: Temporal) -> Temporal: ...
    def withDayOfMonth(self, p0: int) -> "OffsetDateTime": ...
    def withDayOfYear(self, p0: int) -> "OffsetDateTime": ...
    def plusWeeks(self, p0: int) -> "OffsetDateTime": ...
    def withMonth(self, p0: int) -> "OffsetDateTime": ...
    def withYear(self, p0: int) -> "OffsetDateTime": ...
    def toLocalTime(self) -> LocalTime: ...
    def isAfter(self, p0: "OffsetDateTime") -> bool: ...
    def isBefore(self, p0: "OffsetDateTime") -> bool: ...
    def minusWeeks(self, p0: int) -> "OffsetDateTime": ...
    @staticmethod
    def timeLineOrder() -> Comparator: ...
    def toLocalDateTime(self) -> LocalDateTime: ...
    def withHour(self, p0: int) -> "OffsetDateTime": ...
    def withMinute(self, p0: int) -> "OffsetDateTime": ...
    def withSecond(self, p0: int) -> "OffsetDateTime": ...
    def withNano(self, p0: int) -> "OffsetDateTime": ...
    def toLocalDate(self) -> LocalDate: ...
    def toEpochSecond(self) -> int: ...
    def getYear(self) -> int: ...
    def getMonthValue(self) -> int: ...
    def getDayOfMonth(self) -> int: ...
    def getHour(self) -> int: ...
    def getMinute(self) -> int: ...
    def getSecond(self) -> int: ...
    @staticmethod
    def ofInstant(p0: Instant, p1: ZoneId) -> "OffsetDateTime": ...
    def toInstant(self) -> Instant: ...
    def getMonth(self) -> Month: ...
    def query(self, p0: TemporalQuery) -> Any: ...
    def withOffsetSameLocal(self, p0: ZoneOffset) -> "OffsetDateTime": ...
    def withOffsetSameInstant(self, p0: ZoneOffset) -> "OffsetDateTime": ...
    def atZoneSameInstant(self, p0: ZoneId) -> ZonedDateTime: ...
    def atZoneSimilarLocal(self, p0: ZoneId) -> ZonedDateTime: ...
    def toOffsetTime(self) -> OffsetTime: ...
    def isEqual(self, p0: "OffsetDateTime") -> bool: ...
    @overload
    @staticmethod
    def now(p0: Clock) -> "OffsetDateTime": ...
    @overload
    @staticmethod
    def now() -> "OffsetDateTime": ...
    @overload
    @staticmethod
    def now(p0: ZoneId) -> "OffsetDateTime": ...
    @overload
    def plus(self, p0: int, p1: TemporalUnit) -> Temporal: ...
    @overload
    def plus(self, p0: TemporalAmount) -> Temporal: ...
    @overload
    def plus(self, p0: TemporalAmount) -> "OffsetDateTime": ...
    @overload
    def plus(self, p0: int, p1: TemporalUnit) -> "OffsetDateTime": ...
    def until(self, p0: Temporal, p1: TemporalUnit) -> int: ...
    def plusNanos(self, p0: int) -> "OffsetDateTime": ...
    def plusSeconds(self, p0: int) -> "OffsetDateTime": ...
    def plusDays(self, p0: int) -> "OffsetDateTime": ...
    def plusHours(self, p0: int) -> "OffsetDateTime": ...
    def plusMinutes(self, p0: int) -> "OffsetDateTime": ...
    @overload
    def minus(self, p0: int, p1: TemporalUnit) -> "OffsetDateTime": ...
    @overload
    def minus(self, p0: int, p1: TemporalUnit) -> Temporal: ...
    @overload
    def minus(self, p0: TemporalAmount) -> "OffsetDateTime": ...
    @overload
    def minus(self, p0: TemporalAmount) -> Temporal: ...
    def minusDays(self, p0: int) -> "OffsetDateTime": ...
    def minusHours(self, p0: int) -> "OffsetDateTime": ...
    def minusMinutes(self, p0: int) -> "OffsetDateTime": ...
    def minusSeconds(self, p0: int) -> "OffsetDateTime": ...
    def minusNanos(self, p0: int) -> "OffsetDateTime": ...
    def truncatedTo(self, p0: TemporalUnit) -> "OffsetDateTime": ...
    def plusYears(self, p0: int) -> "OffsetDateTime": ...
    def plusMonths(self, p0: int) -> "OffsetDateTime": ...
    def minusYears(self, p0: int) -> "OffsetDateTime": ...
    def minusMonths(self, p0: int) -> "OffsetDateTime": ...
    def range(self, p0: TemporalField) -> ValueRange: ...
    def getNano(self) -> int: ...

from typing import Any, ClassVar, overload
from java.time.Duration import Duration
from java.time.Instant import Instant
from java.time.ZoneId import ZoneId

class Clock:
    @staticmethod
    def fixed(p0: Instant, p1: ZoneId) -> "Clock": ...
    def equals(self, p0: Any) -> bool: ...
    def hashCode(self) -> int: ...
    @staticmethod
    def offset(p0: "Clock", p1: Duration) -> "Clock": ...
    def millis(self) -> int: ...
    @staticmethod
    def system(p0: ZoneId) -> "Clock": ...
    @staticmethod
    def systemDefaultZone() -> "Clock": ...
    def getZone(self) -> ZoneId: ...
    def instant(self) -> Instant: ...
    @staticmethod
    def systemUTC() -> "Clock": ...
    @staticmethod
    def tickMillis(p0: ZoneId) -> "Clock": ...
    @staticmethod
    def tickSeconds(p0: ZoneId) -> "Clock": ...
    @staticmethod
    def tickMinutes(p0: ZoneId) -> "Clock": ...
    @staticmethod
    def tick(p0: "Clock", p1: Duration) -> "Clock": ...
    def withZone(self, p0: ZoneId) -> "Clock": ...

from typing import Any, ClassVar, overload
from java.time.Clock import Clock
from java.time.OffsetDateTime import OffsetDateTime
from java.time.ZoneId import ZoneId
from java.time.ZoneOffset import ZoneOffset
from java.time.ZonedDateTime import ZonedDateTime
from java.time.temporal.Temporal import Temporal
from java.time.temporal.TemporalAccessor import TemporalAccessor
from java.time.temporal.TemporalAdjuster import TemporalAdjuster
from java.time.temporal.TemporalAmount import TemporalAmount
from java.time.temporal.TemporalField import TemporalField
from java.time.temporal.TemporalQuery import TemporalQuery
from java.time.temporal.TemporalUnit import TemporalUnit
from java.time.temporal.ValueRange import ValueRange

class Instant:
    EPOCH: ClassVar["Instant"]
    MIN: ClassVar["Instant"]
    MAX: ClassVar["Instant"]
    def get(self, p0: TemporalField) -> int: ...
    def equals(self, p0: Any) -> bool: ...
    def toString(self) -> str: ...
    def hashCode(self) -> int: ...
    @overload
    def compareTo(self, p0: Any) -> int: ...
    @overload
    def compareTo(self, p0: "Instant") -> int: ...
    def getLong(self, p0: TemporalField) -> int: ...
    @staticmethod
    def from_(p0: TemporalAccessor) -> "Instant": ...
    @overload
    def isSupported(self, p0: TemporalUnit) -> bool: ...
    @overload
    def isSupported(self, p0: TemporalField) -> bool: ...
    @staticmethod
    def parse(p0: str) -> "Instant": ...
    @overload
    def with_(self, p0: TemporalField, p1: int) -> "Instant": ...
    @overload
    def with_(self, p0: TemporalAdjuster) -> "Instant": ...
    @overload
    def with_(self, p0: TemporalField, p1: int) -> Temporal: ...
    @overload
    def with_(self, p0: TemporalAdjuster) -> Temporal: ...
    def adjustInto(self, p0: Temporal) -> Temporal: ...
    def isAfter(self, p0: "Instant") -> bool: ...
    def isBefore(self, p0: "Instant") -> bool: ...
    def atOffset(self, p0: ZoneOffset) -> OffsetDateTime: ...
    def atZone(self, p0: ZoneId) -> ZonedDateTime: ...
    def toEpochMilli(self) -> int: ...
    @staticmethod
    def ofEpochMilli(p0: int) -> "Instant": ...
    def getEpochSecond(self) -> int: ...
    @overload
    @staticmethod
    def ofEpochSecond(p0: int) -> "Instant": ...
    @overload
    @staticmethod
    def ofEpochSecond(p0: int, p1: int) -> "Instant": ...
    def query(self, p0: TemporalQuery) -> Any: ...
    @overload
    @staticmethod
    def now(p0: Clock) -> "Instant": ...
    @overload
    @staticmethod
    def now() -> "Instant": ...
    @overload
    def plus(self, p0: int, p1: TemporalUnit) -> Temporal: ...
    @overload
    def plus(self, p0: int, p1: TemporalUnit) -> "Instant": ...
    @overload
    def plus(self, p0: TemporalAmount) -> Temporal: ...
    @overload
    def plus(self, p0: TemporalAmount) -> "Instant": ...
    def until(self, p0: Temporal, p1: TemporalUnit) -> int: ...
    def plusNanos(self, p0: int) -> "Instant": ...
    def plusSeconds(self, p0: int) -> "Instant": ...
    def plusMillis(self, p0: int) -> "Instant": ...
    @overload
    def minus(self, p0: int, p1: TemporalUnit) -> Temporal: ...
    @overload
    def minus(self, p0: TemporalAmount) -> Temporal: ...
    @overload
    def minus(self, p0: int, p1: TemporalUnit) -> "Instant": ...
    @overload
    def minus(self, p0: TemporalAmount) -> "Instant": ...
    def minusSeconds(self, p0: int) -> "Instant": ...
    def minusMillis(self, p0: int) -> "Instant": ...
    def minusNanos(self, p0: int) -> "Instant": ...
    def truncatedTo(self, p0: TemporalUnit) -> "Instant": ...
    def range(self, p0: TemporalField) -> ValueRange: ...
    def getNano(self) -> int: ...

from typing import Any, ClassVar, overload
from java.time.Clock import Clock
from java.time.LocalDate import LocalDate
from java.time.Month import Month
from java.time.ZoneId import ZoneId
from java.time.format.DateTimeFormatter import DateTimeFormatter
from java.time.temporal.Temporal import Temporal
from java.time.temporal.TemporalAccessor import TemporalAccessor
from java.time.temporal.TemporalAdjuster import TemporalAdjuster
from java.time.temporal.TemporalAmount import TemporalAmount
from java.time.temporal.TemporalField import TemporalField
from java.time.temporal.TemporalQuery import TemporalQuery
from java.time.temporal.TemporalUnit import TemporalUnit
from java.time.temporal.ValueRange import ValueRange

class YearMonth:
    def get(self, p0: TemporalField) -> int: ...
    def equals(self, p0: Any) -> bool: ...
    def toString(self) -> str: ...
    def hashCode(self) -> int: ...
    @overload
    def compareTo(self, p0: "YearMonth") -> int: ...
    @overload
    def compareTo(self, p0: Any) -> int: ...
    def getLong(self, p0: TemporalField) -> int: ...
    def format(self, p0: DateTimeFormatter) -> str: ...
    @overload
    @staticmethod
    def of(p0: int, p1: Month) -> "YearMonth": ...
    @overload
    @staticmethod
    def of(p0: int, p1: int) -> "YearMonth": ...
    @staticmethod
    def from_(p0: TemporalAccessor) -> "YearMonth": ...
    @overload
    def isSupported(self, p0: TemporalField) -> bool: ...
    @overload
    def isSupported(self, p0: TemporalUnit) -> bool: ...
    @overload
    @staticmethod
    def parse(p0: str, p1: DateTimeFormatter) -> "YearMonth": ...
    @overload
    @staticmethod
    def parse(p0: str) -> "YearMonth": ...
    @overload
    def with_(self, p0: TemporalField, p1: int) -> Temporal: ...
    @overload
    def with_(self, p0: TemporalField, p1: int) -> "YearMonth": ...
    @overload
    def with_(self, p0: TemporalAdjuster) -> "YearMonth": ...
    @overload
    def with_(self, p0: TemporalAdjuster) -> Temporal: ...
    def isLeapYear(self) -> bool: ...
    def lengthOfMonth(self) -> int: ...
    def lengthOfYear(self) -> int: ...
    def adjustInto(self, p0: Temporal) -> Temporal: ...
    def withMonth(self, p0: int) -> "YearMonth": ...
    def withYear(self, p0: int) -> "YearMonth": ...
    def isAfter(self, p0: "YearMonth") -> bool: ...
    def isBefore(self, p0: "YearMonth") -> bool: ...
    def getYear(self) -> int: ...
    def getMonthValue(self) -> int: ...
    def getMonth(self) -> Month: ...
    def query(self, p0: TemporalQuery) -> Any: ...
    def atDay(self, p0: int) -> LocalDate: ...
    def isValidDay(self, p0: int) -> bool: ...
    def atEndOfMonth(self) -> LocalDate: ...
    @overload
    @staticmethod
    def now(p0: Clock) -> "YearMonth": ...
    @overload
    @staticmethod
    def now(p0: ZoneId) -> "YearMonth": ...
    @overload
    @staticmethod
    def now() -> "YearMonth": ...
    @overload
    def plus(self, p0: int, p1: TemporalUnit) -> "YearMonth": ...
    @overload
    def plus(self, p0: TemporalAmount) -> Temporal: ...
    @overload
    def plus(self, p0: TemporalAmount) -> "YearMonth": ...
    @overload
    def plus(self, p0: int, p1: TemporalUnit) -> Temporal: ...
    def until(self, p0: Temporal, p1: TemporalUnit) -> int: ...
    @overload
    def minus(self, p0: int, p1: TemporalUnit) -> Temporal: ...
    @overload
    def minus(self, p0: TemporalAmount) -> Temporal: ...
    @overload
    def minus(self, p0: int, p1: TemporalUnit) -> "YearMonth": ...
    @overload
    def minus(self, p0: TemporalAmount) -> "YearMonth": ...
    def plusYears(self, p0: int) -> "YearMonth": ...
    def plusMonths(self, p0: int) -> "YearMonth": ...
    def minusYears(self, p0: int) -> "YearMonth": ...
    def minusMonths(self, p0: int) -> "YearMonth": ...
    def range(self, p0: TemporalField) -> ValueRange: ...

from typing import Any, ClassVar, overload
from java.time.format.TextStyle import TextStyle
from java.time.temporal.Temporal import Temporal
from java.time.temporal.TemporalAccessor import TemporalAccessor
from java.time.temporal.TemporalField import TemporalField
from java.time.temporal.TemporalQuery import TemporalQuery
from java.time.temporal.ValueRange import ValueRange
from java.util.Locale import Locale

class DayOfWeek:
    MONDAY: ClassVar["DayOfWeek"]
    TUESDAY: ClassVar["DayOfWeek"]
    WEDNESDAY: ClassVar["DayOfWeek"]
    THURSDAY: ClassVar["DayOfWeek"]
    FRIDAY: ClassVar["DayOfWeek"]
    SATURDAY: ClassVar["DayOfWeek"]
    SUNDAY: ClassVar["DayOfWeek"]
    MONDAY: ClassVar["DayOfWeek"]
    TUESDAY: ClassVar["DayOfWeek"]
    WEDNESDAY: ClassVar["DayOfWeek"]
    THURSDAY: ClassVar["DayOfWeek"]
    FRIDAY: ClassVar["DayOfWeek"]
    SATURDAY: ClassVar["DayOfWeek"]
    SUNDAY: ClassVar["DayOfWeek"]
    def get(self, p0: TemporalField) -> int: ...
    @staticmethod
    def values() -> Any: ...
    def getLong(self, p0: TemporalField) -> int: ...
    @staticmethod
    def valueOf(p0: str) -> "DayOfWeek": ...
    def getValue(self) -> int: ...
    @staticmethod
    def of(p0: int) -> "DayOfWeek": ...
    @staticmethod
    def from_(p0: TemporalAccessor) -> "DayOfWeek": ...
    def isSupported(self, p0: TemporalField) -> bool: ...
    def getDisplayName(self, p0: TextStyle, p1: Locale) -> str: ...
    def adjustInto(self, p0: Temporal) -> Temporal: ...
    def query(self, p0: TemporalQuery) -> Any: ...
    def plus(self, p0: int) -> "DayOfWeek": ...
    def minus(self, p0: int) -> "DayOfWeek": ...
    def range(self, p0: TemporalField) -> ValueRange: ...

from typing import Any, ClassVar, overload
from java.lang.Throwable import Throwable

class DateTimeException:
    @overload
    def __init__(self, p0: str) -> None: ...
    @overload
    def __init__(self, p0: str, p1: Throwable) -> None: ...

from typing import Any, ClassVar, overload
from java.time.Clock import Clock
from java.time.DayOfWeek import DayOfWeek
from java.time.Instant import Instant
from java.time.LocalDate import LocalDate
from java.time.LocalTime import LocalTime
from java.time.Month import Month
from java.time.OffsetDateTime import OffsetDateTime
from java.time.ZoneId import ZoneId
from java.time.ZoneOffset import ZoneOffset
from java.time.ZonedDateTime import ZonedDateTime
from java.time.chrono.ChronoLocalDate import ChronoLocalDate
from java.time.chrono.ChronoLocalDateTime import ChronoLocalDateTime
from java.time.chrono.ChronoZonedDateTime import ChronoZonedDateTime
from java.time.format.DateTimeFormatter import DateTimeFormatter
from java.time.temporal.Temporal import Temporal
from java.time.temporal.TemporalAccessor import TemporalAccessor
from java.time.temporal.TemporalAdjuster import TemporalAdjuster
from java.time.temporal.TemporalAmount import TemporalAmount
from java.time.temporal.TemporalField import TemporalField
from java.time.temporal.TemporalQuery import TemporalQuery
from java.time.temporal.TemporalUnit import TemporalUnit
from java.time.temporal.ValueRange import ValueRange

class LocalDateTime:
    MIN: ClassVar["LocalDateTime"]
    MAX: ClassVar["LocalDateTime"]
    def get(self, p0: TemporalField) -> int: ...
    def equals(self, p0: Any) -> bool: ...
    def toString(self) -> str: ...
    def hashCode(self) -> int: ...
    @overload
    def compareTo(self, p0: ChronoLocalDateTime) -> int: ...
    @overload
    def compareTo(self, p0: Any) -> int: ...
    def getLong(self, p0: TemporalField) -> int: ...
    def format(self, p0: DateTimeFormatter) -> str: ...
    @overload
    @staticmethod
    def of(p0: int, p1: int, p2: int, p3: int, p4: int) -> "LocalDateTime": ...
    @overload
    @staticmethod
    def of(p0: int, p1: Month, p2: int, p3: int, p4: int, p5: int, p6: int) -> "LocalDateTime": ...
    @overload
    @staticmethod
    def of(p0: int, p1: Month, p2: int, p3: int, p4: int, p5: int) -> "LocalDateTime": ...
    @overload
    @staticmethod
    def of(p0: int, p1: Month, p2: int, p3: int, p4: int) -> "LocalDateTime": ...
    @overload
    @staticmethod
    def of(p0: LocalDate, p1: LocalTime) -> "LocalDateTime": ...
    @overload
    @staticmethod
    def of(p0: int, p1: int, p2: int, p3: int, p4: int, p5: int, p6: int) -> "LocalDateTime": ...
    @overload
    @staticmethod
    def of(p0: int, p1: int, p2: int, p3: int, p4: int, p5: int) -> "LocalDateTime": ...
    @staticmethod
    def from_(p0: TemporalAccessor) -> "LocalDateTime": ...
    @overload
    def isSupported(self, p0: TemporalUnit) -> bool: ...
    @overload
    def isSupported(self, p0: TemporalField) -> bool: ...
    @overload
    @staticmethod
    def parse(p0: str, p1: DateTimeFormatter) -> "LocalDateTime": ...
    @overload
    @staticmethod
    def parse(p0: str) -> "LocalDateTime": ...
    @overload
    def with_(self, p0: TemporalAdjuster) -> "LocalDateTime": ...
    @overload
    def with_(self, p0: TemporalField, p1: int) -> "LocalDateTime": ...
    @overload
    def with_(self, p0: TemporalField, p1: int) -> ChronoLocalDateTime: ...
    @overload
    def with_(self, p0: TemporalAdjuster) -> ChronoLocalDateTime: ...
    @overload
    def with_(self, p0: TemporalAdjuster) -> Temporal: ...
    @overload
    def with_(self, p0: TemporalField, p1: int) -> Temporal: ...
    def getDayOfWeek(self) -> DayOfWeek: ...
    def getDayOfYear(self) -> int: ...
    def adjustInto(self, p0: Temporal) -> Temporal: ...
    def withDayOfMonth(self, p0: int) -> "LocalDateTime": ...
    def withDayOfYear(self, p0: int) -> "LocalDateTime": ...
    def plusWeeks(self, p0: int) -> "LocalDateTime": ...
    def withMonth(self, p0: int) -> "LocalDateTime": ...
    def withYear(self, p0: int) -> "LocalDateTime": ...
    def toLocalTime(self) -> LocalTime: ...
    def isAfter(self, p0: ChronoLocalDateTime) -> bool: ...
    def isBefore(self, p0: ChronoLocalDateTime) -> bool: ...
    def minusWeeks(self, p0: int) -> "LocalDateTime": ...
    def atOffset(self, p0: ZoneOffset) -> OffsetDateTime: ...
    @overload
    def atZone(self, p0: ZoneId) -> ZonedDateTime: ...
    @overload
    def atZone(self, p0: ZoneId) -> ChronoZonedDateTime: ...
    def withHour(self, p0: int) -> "LocalDateTime": ...
    def withMinute(self, p0: int) -> "LocalDateTime": ...
    def withSecond(self, p0: int) -> "LocalDateTime": ...
    def withNano(self, p0: int) -> "LocalDateTime": ...
    @overload
    def toLocalDate(self) -> ChronoLocalDate: ...
    @overload
    def toLocalDate(self) -> LocalDate: ...
    def getYear(self) -> int: ...
    def getMonthValue(self) -> int: ...
    def getDayOfMonth(self) -> int: ...
    def getHour(self) -> int: ...
    def getMinute(self) -> int: ...
    def getSecond(self) -> int: ...
    @staticmethod
    def ofInstant(p0: Instant, p1: ZoneId) -> "LocalDateTime": ...
    @staticmethod
    def ofEpochSecond(p0: int, p1: int, p2: ZoneOffset) -> "LocalDateTime": ...
    def getMonth(self) -> Month: ...
    def query(self, p0: TemporalQuery) -> Any: ...
    def isEqual(self, p0: ChronoLocalDateTime) -> bool: ...
    @overload
    @staticmethod
    def now(p0: Clock) -> "LocalDateTime": ...
    @overload
    @staticmethod
    def now() -> "LocalDateTime": ...
    @overload
    @staticmethod
    def now(p0: ZoneId) -> "LocalDateTime": ...
    @overload
    def plus(self, p0: int, p1: TemporalUnit) -> ChronoLocalDateTime: ...
    @overload
    def plus(self, p0: TemporalAmount) -> "LocalDateTime": ...
    @overload
    def plus(self, p0: TemporalAmount) -> ChronoLocalDateTime: ...
    @overload
    def plus(self, p0: int, p1: TemporalUnit) -> "LocalDateTime": ...
    @overload
    def plus(self, p0: TemporalAmount) -> Temporal: ...
    @overload
    def plus(self, p0: int, p1: TemporalUnit) -> Temporal: ...
    def until(self, p0: Temporal, p1: TemporalUnit) -> int: ...
    def plusNanos(self, p0: int) -> "LocalDateTime": ...
    def plusSeconds(self, p0: int) -> "LocalDateTime": ...
    def plusDays(self, p0: int) -> "LocalDateTime": ...
    def plusHours(self, p0: int) -> "LocalDateTime": ...
    def plusMinutes(self, p0: int) -> "LocalDateTime": ...
    @overload
    def minus(self, p0: int, p1: TemporalUnit) -> ChronoLocalDateTime: ...
    @overload
    def minus(self, p0: TemporalAmount) -> "LocalDateTime": ...
    @overload
    def minus(self, p0: TemporalAmount) -> Temporal: ...
    @overload
    def minus(self, p0: int, p1: TemporalUnit) -> Temporal: ...
    @overload
    def minus(self, p0: int, p1: TemporalUnit) -> "LocalDateTime": ...
    @overload
    def minus(self, p0: TemporalAmount) -> ChronoLocalDateTime: ...
    def minusDays(self, p0: int) -> "LocalDateTime": ...
    def minusHours(self, p0: int) -> "LocalDateTime": ...
    def minusMinutes(self, p0: int) -> "LocalDateTime": ...
    def minusSeconds(self, p0: int) -> "LocalDateTime": ...
    def minusNanos(self, p0: int) -> "LocalDateTime": ...
    def truncatedTo(self, p0: TemporalUnit) -> "LocalDateTime": ...
    def plusYears(self, p0: int) -> "LocalDateTime": ...
    def plusMonths(self, p0: int) -> "LocalDateTime": ...
    def minusYears(self, p0: int) -> "LocalDateTime": ...
    def minusMonths(self, p0: int) -> "LocalDateTime": ...
    def range(self, p0: TemporalField) -> ValueRange: ...
    def getNano(self) -> int: ...

