from typing import Any, ClassVar, overload
from android.telephony.ims.ImsStateCallback import ImsStateCallback
from android.telephony.ims.RcsUceAdapter import RcsUceAdapter
from java.util.concurrent.Executor import Executor
from java.util.function.Consumer import Consumer

class ImsRcsManager:
    ACTION_SHOW_CAPABILITY_DISCOVERY_OPT_IN: ClassVar[str]
    CAPABILITY_TYPE_NONE: ClassVar[int]
    CAPABILITY_TYPE_OPTIONS_UCE: ClassVar[int]
    CAPABILITY_TYPE_PRESENCE_UCE: ClassVar[int]
    def getUceAdapter(self) -> RcsUceAdapter: ...
    def getRegistrationState(self, p0: Executor, p1: Consumer) -> None: ...
    def getRegistrationTransportType(self, p0: Executor, p1: Consumer) -> None: ...
    def registerImsRegistrationCallback(self, p0: Executor, p1: Any) -> None: ...
    def registerImsStateCallback(self, p0: Executor, p1: ImsStateCallback) -> None: ...
    def unregisterImsRegistrationCallback(self, p0: Any) -> None: ...
    def unregisterImsStateCallback(self, p0: ImsStateCallback) -> None: ...
