from typing import Any, ClassVar, overload
from android.nfc.Tag import Tag

class IsoDep:
    def getMaxTransceiveLength(self) -> int: ...
    def isConnected(self) -> bool: ...
    def transceive(self, p0: Any) -> Any: ...
    def getTimeout(self) -> int: ...
    def setTimeout(self, p0: int) -> None: ...
    def connect(self) -> None: ...
    def getHiLayerResponse(self) -> Any: ...
    def isExtendedLengthApduSupported(self) -> bool: ...
    def getHistoricalBytes(self) -> Any: ...
    @staticmethod
    def get(p0: Tag) -> "IsoDep": ...
    def close(self) -> None: ...
    def getTag(self) -> Tag: ...
