from typing import Any, ClassVar, overload
from android.nfc.Tag import Tag

class NfcB:
    def getMaxTransceiveLength(self) -> int: ...
    def getProtocolInfo(self) -> Any: ...
    def isConnected(self) -> bool: ...
    def transceive(self, p0: Any) -> Any: ...
    def getApplicationData(self) -> Any: ...
    def connect(self) -> None: ...
    @staticmethod
    def get(p0: Tag) -> "NfcB": ...
    def close(self) -> None: ...
    def getTag(self) -> Tag: ...
