from typing import Any, ClassVar, overload
from android.nfc.Tag import Tag

class NfcBarcode:
    TYPE_KOVIO: ClassVar[int]
    TYPE_UNKNOWN: ClassVar[int]
    def getBarcode(self) -> Any: ...
    def isConnected(self) -> bool: ...
    def getTag(self) -> Tag: ...
    @staticmethod
    def get(p0: Tag) -> "NfcBarcode": ...
    def connect(self) -> None: ...
    def close(self) -> None: ...
    def getType(self) -> int: ...
