from typing import Any, ClassVar, overload
from android.app.PendingIntent import PendingIntent
from android.content.Context import Context
from android.media.AudioAttributes import AudioAttributes
from android.media.MediaMetadata import MediaMetadata
from android.media.Rating import Rating
from android.media.session.PlaybackState import PlaybackState
from android.net.Uri import Uri
from android.os.Bundle import Bundle
from android.os.Handler import Handler
from android.os.Parcel import Parcel
from android.os.ResultReceiver import ResultReceiver
from android.view.KeyEvent import KeyEvent

class MediaController:
    def __init__(self, p0: Context, p1: Any) -> None: ...
    def getSessionToken(self) -> Any: ...
    def getTransportControls(self) -> Any: ...
    def getQueueTitle(self) -> str: ...
    def getRatingType(self) -> int: ...
    def getPlaybackInfo(self) -> Any: ...
    def getSessionActivity(self) -> PendingIntent: ...
    def setVolumeTo(self, p0: int, p1: int) -> None: ...
    def adjustVolume(self, p0: int, p1: int) -> None: ...
    def sendCommand(self, p0: str, p1: Bundle, p2: ResultReceiver) -> None: ...
    def dispatchMediaButtonEvent(self, p0: KeyEvent) -> bool: ...
    def getPlaybackState(self) -> PlaybackState: ...
    def getTag(self) -> str: ...
    def getMetadata(self) -> MediaMetadata: ...
    @overload
    def registerCallback(self, p0: Any) -> None: ...
    @overload
    def registerCallback(self, p0: Any, p1: Handler) -> None: ...
    def unregisterCallback(self, p0: Any) -> None: ...
    def getExtras(self) -> Bundle: ...
    def getFlags(self) -> int: ...
    def getSessionInfo(self) -> Bundle: ...
    def getPackageName(self) -> str: ...
    def getQueue(self) -> list: ...

    class TransportControls:
        def prepareFromSearch(self, p0: str, p1: Bundle) -> None: ...
        def prepareFromUri(self, p0: Uri, p1: Bundle) -> None: ...
        def playFromMediaId(self, p0: str, p1: Bundle) -> None: ...
        def playFromSearch(self, p0: str, p1: Bundle) -> None: ...
        def prepareFromMediaId(self, p0: str, p1: Bundle) -> None: ...
        def playFromUri(self, p0: Uri, p1: Bundle) -> None: ...
        def skipToQueueItem(self, p0: int) -> None: ...
        def fastForward(self) -> None: ...
        def skipToNext(self) -> None: ...
        def skipToPrevious(self) -> None: ...
        def setPlaybackSpeed(self, p0: float) -> None: ...
        @overload
        def sendCustomAction(self, p0: Any, p1: Bundle) -> None: ...
        @overload
        def sendCustomAction(self, p0: str, p1: Bundle) -> None: ...
        def play(self) -> None: ...
        def seekTo(self, p0: int) -> None: ...
        def pause(self) -> None: ...
        def setRating(self, p0: Rating) -> None: ...
        def prepare(self) -> None: ...
        def rewind(self) -> None: ...
        def stop(self) -> None: ...

    class PlaybackInfo:
        CREATOR: ClassVar[Any]
        PLAYBACK_TYPE_LOCAL: ClassVar[int]
        PLAYBACK_TYPE_REMOTE: ClassVar[int]
        CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
        PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
        def getPlaybackType(self) -> int: ...
        def describeContents(self) -> int: ...
        def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
        def getAudioAttributes(self) -> AudioAttributes: ...
        def getVolumeControl(self) -> int: ...
        def getMaxVolume(self) -> int: ...
        def getCurrentVolume(self) -> int: ...
        def getVolumeControlId(self) -> str: ...
        def toString(self) -> str: ...

    class Callback:
        def __init__(self) -> None: ...
        def onSessionDestroyed(self) -> None: ...
        def onPlaybackStateChanged(self, p0: PlaybackState) -> None: ...
        def onMetadataChanged(self, p0: MediaMetadata) -> None: ...
        def onQueueChanged(self, p0: list) -> None: ...
        def onQueueTitleChanged(self, p0: str) -> None: ...
        def onAudioInfoChanged(self, p0: Any) -> None: ...
        def onSessionEvent(self, p0: str, p1: Bundle) -> None: ...
        def onExtrasChanged(self, p0: Bundle) -> None: ...
