from typing import Any, ClassVar, overload
from android.graphics.Point import Point
from android.graphics.Rect import Rect
from android.util.Size import Size

class MeteringRectangle:
    METERING_WEIGHT_DONT_CARE: ClassVar[int]
    METERING_WEIGHT_MAX: ClassVar[int]
    METERING_WEIGHT_MIN: ClassVar[int]
    @overload
    def __init__(self, p0: Point, p1: Size, p2: int) -> None: ...
    @overload
    def __init__(self, p0: int, p1: int, p2: int, p3: int, p4: int) -> None: ...
    @overload
    def __init__(self, p0: Rect, p1: int) -> None: ...
    def getUpperLeftPoint(self) -> Point: ...
    def getMeteringWeight(self) -> int: ...
    @overload
    def equals(self, p0: Any) -> bool: ...
    @overload
    def equals(self, p0: "MeteringRectangle") -> bool: ...
    def toString(self) -> str: ...
    def hashCode(self) -> int: ...
    def getSize(self) -> Size: ...
    def getHeight(self) -> int: ...
    def getWidth(self) -> int: ...
    def getX(self) -> int: ...
    def getY(self) -> int: ...
    def getRect(self) -> Rect: ...
