from typing import Any, ClassVar, overload
from android.util.Range import Range
from android.util.Size import Size
from android.view.Surface import Surface

class RecommendedStreamConfigurationMap:
    USECASE_10BIT_OUTPUT: ClassVar[int]
    USECASE_LOW_LATENCY_SNAPSHOT: ClassVar[int]
    USECASE_PREVIEW: ClassVar[int]
    USECASE_RAW: ClassVar[int]
    USECASE_RECORD: ClassVar[int]
    USECASE_SNAPSHOT: ClassVar[int]
    USECASE_VIDEO_SNAPSHOT: ClassVar[int]
    USECASE_ZSL: ClassVar[int]
    def getHighSpeedVideoSizesFor(self, p0: Range) -> set: ...
    def getInputFormats(self) -> set: ...
    def getInputSizes(self, p0: int) -> set: ...
    def getOutputFormats(self) -> set: ...
    @overload
    def getOutputMinFrameDuration(self, p0: type, p1: Size) -> int: ...
    @overload
    def getOutputMinFrameDuration(self, p0: int, p1: Size) -> int: ...
    @overload
    def getOutputSizes(self, p0: int) -> set: ...
    @overload
    def getOutputSizes(self, p0: type) -> set: ...
    @overload
    def getOutputStallDuration(self, p0: int, p1: Size) -> int: ...
    @overload
    def getOutputStallDuration(self, p0: type, p1: Size) -> int: ...
    def getRecommendedUseCase(self) -> int: ...
    def getValidOutputFormatsForInput(self, p0: int) -> set: ...
    def getHighResolutionOutputSizes(self, p0: int) -> set: ...
    def getHighSpeedVideoFpsRanges(self) -> set: ...
    def getHighSpeedVideoFpsRangesFor(self, p0: Size) -> set: ...
    def getHighSpeedVideoSizes(self) -> set: ...
    @overload
    def isOutputSupportedFor(self, p0: Surface) -> bool: ...
    @overload
    def isOutputSupportedFor(self, p0: int) -> bool: ...
