from typing import Any, ClassVar, overload
from java.lang.Runnable import Runnable
from java.util.concurrent.Executor import Executor
from java.util.concurrent.TimeUnit import TimeUnit

class AsyncTask:
    SERIAL_EXECUTOR: ClassVar[Executor]
    THREAD_POOL_EXECUTOR: ClassVar[Executor]
    def __init__(self) -> None: ...
    def executeOnExecutor(self, p0: Executor, p1: Any) -> "AsyncTask": ...
    def isCancelled(self) -> bool: ...
    def getStatus(self) -> Any: ...
    @overload
    def get(self) -> Any: ...
    @overload
    def get(self, p0: int, p1: TimeUnit) -> Any: ...
    @overload
    def execute(self, p0: Any) -> "AsyncTask": ...
    @overload
    @staticmethod
    def execute(p0: Runnable) -> None: ...
    def cancel(self, p0: bool) -> bool: ...

    class Status:
        PENDING: ClassVar["Status"]
        RUNNING: ClassVar["Status"]
        FINISHED: ClassVar["Status"]
        PENDING: ClassVar[Any]
        RUNNING: ClassVar[Any]
        FINISHED: ClassVar[Any]
        @staticmethod
        def values() -> Any: ...
        @staticmethod
        def valueOf(p0: str) -> Any: ...
