from typing import Any, ClassVar, overload
from android.os.Parcel import Parcel
from java.io.FileDescriptor import FileDescriptor
from java.lang.ClassLoader import ClassLoader

class Debug:
    SHOW_CLASSLOADER: ClassVar[int]
    SHOW_FULL_DETAIL: ClassVar[int]
    SHOW_INITIALIZED: ClassVar[int]
    TRACE_COUNT_ALLOCS: ClassVar[int]
    @staticmethod
    def getMemoryInfo(p0: Any) -> None: ...
    @staticmethod
    def startAllocCounting() -> None: ...
    @staticmethod
    def stopAllocCounting() -> None: ...
    @staticmethod
    def getRss() -> int: ...
    @staticmethod
    def getPss() -> int: ...
    @staticmethod
    def attachJvmtiAgent(p0: str, p1: str, p2: ClassLoader) -> None: ...
    @staticmethod
    def enableEmulatorTraceOutput() -> None: ...
    @staticmethod
    def getBinderDeathObjectCount() -> int: ...
    @staticmethod
    def getBinderLocalObjectCount() -> int: ...
    @staticmethod
    def getBinderProxyObjectCount() -> int: ...
    @staticmethod
    def getBinderReceivedTransactions() -> int: ...
    @staticmethod
    def getBinderSentTransactions() -> int: ...
    @staticmethod
    def getGlobalAllocCount() -> int: ...
    @staticmethod
    def changeDebugPort(p0: int) -> None: ...
    @staticmethod
    def dumpHprofData(p0: str) -> None: ...
    @staticmethod
    def dumpService(p0: str, p1: FileDescriptor, p2: Any) -> bool: ...
    @staticmethod
    def getGlobalAllocSize() -> int: ...
    @staticmethod
    def getGlobalClassInitCount() -> int: ...
    @staticmethod
    def getGlobalClassInitTime() -> int: ...
    @staticmethod
    def getGlobalExternalAllocCount() -> int: ...
    @staticmethod
    def getGlobalExternalAllocSize() -> int: ...
    @staticmethod
    def getGlobalExternalFreedCount() -> int: ...
    @staticmethod
    def getGlobalExternalFreedSize() -> int: ...
    @staticmethod
    def getGlobalFreedCount() -> int: ...
    @staticmethod
    def getGlobalFreedSize() -> int: ...
    @staticmethod
    def getGlobalGcInvocationCount() -> int: ...
    @staticmethod
    def getLoadedClassCount() -> int: ...
    @staticmethod
    def getNativeHeapAllocatedSize() -> int: ...
    @staticmethod
    def getNativeHeapFreeSize() -> int: ...
    @staticmethod
    def getNativeHeapSize() -> int: ...
    @staticmethod
    def getRuntimeStat(p0: str) -> str: ...
    @staticmethod
    def getRuntimeStats() -> dict: ...
    @staticmethod
    def getThreadAllocCount() -> int: ...
    @staticmethod
    def getThreadAllocSize() -> int: ...
    @staticmethod
    def getThreadExternalAllocCount() -> int: ...
    @staticmethod
    def getThreadExternalAllocSize() -> int: ...
    @staticmethod
    def getThreadGcInvocationCount() -> int: ...
    @staticmethod
    def isDebuggerConnected() -> bool: ...
    @staticmethod
    def printLoadedClasses(p0: int) -> None: ...
    @staticmethod
    def resetAllCounts() -> None: ...
    @staticmethod
    def resetGlobalAllocCount() -> None: ...
    @staticmethod
    def resetGlobalAllocSize() -> None: ...
    @staticmethod
    def resetGlobalClassInitCount() -> None: ...
    @staticmethod
    def resetGlobalClassInitTime() -> None: ...
    @staticmethod
    def resetGlobalExternalAllocCount() -> None: ...
    @staticmethod
    def resetGlobalExternalAllocSize() -> None: ...
    @staticmethod
    def resetGlobalExternalFreedCount() -> None: ...
    @staticmethod
    def resetGlobalExternalFreedSize() -> None: ...
    @staticmethod
    def resetGlobalFreedCount() -> None: ...
    @staticmethod
    def resetGlobalFreedSize() -> None: ...
    @staticmethod
    def resetGlobalGcInvocationCount() -> None: ...
    @staticmethod
    def resetThreadAllocCount() -> None: ...
    @staticmethod
    def resetThreadAllocSize() -> None: ...
    @staticmethod
    def resetThreadExternalAllocCount() -> None: ...
    @staticmethod
    def resetThreadExternalAllocSize() -> None: ...
    @staticmethod
    def resetThreadGcInvocationCount() -> None: ...
    @staticmethod
    def setAllocationLimit(p0: int) -> int: ...
    @staticmethod
    def setGlobalAllocationLimit(p0: int) -> int: ...
    @overload
    @staticmethod
    def startMethodTracing(p0: str, p1: int, p2: int) -> None: ...
    @overload
    @staticmethod
    def startMethodTracing(p0: str, p1: int) -> None: ...
    @overload
    @staticmethod
    def startMethodTracing(p0: str) -> None: ...
    @overload
    @staticmethod
    def startMethodTracing() -> None: ...
    @staticmethod
    def startMethodTracingSampling(p0: str, p1: int, p2: int) -> None: ...
    @staticmethod
    def startNativeTracing() -> None: ...
    @staticmethod
    def stopMethodTracing() -> None: ...
    @staticmethod
    def stopNativeTracing() -> None: ...
    @staticmethod
    def threadCpuTimeNanos() -> int: ...
    @staticmethod
    def waitForDebugger() -> None: ...
    @staticmethod
    def waitingForDebugger() -> bool: ...

    class MemoryInfo:
        CREATOR: ClassVar[Any]
        CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
        PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
        dalvikPrivateDirty: int
        dalvikPss: int
        dalvikSharedDirty: int
        nativePrivateDirty: int
        nativePss: int
        nativeSharedDirty: int
        otherPrivateDirty: int
        otherPss: int
        otherSharedDirty: int
        def __init__(self) -> None: ...
        def getMemoryStat(self, p0: str) -> str: ...
        def getMemoryStats(self) -> dict: ...
        def getTotalPrivateClean(self) -> int: ...
        def getTotalPrivateDirty(self) -> int: ...
        def getTotalPss(self) -> int: ...
        def getTotalSharedClean(self) -> int: ...
        def getTotalSharedDirty(self) -> int: ...
        def getTotalSwappablePss(self) -> int: ...
        def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
        def readFromParcel(self, p0: Parcel) -> None: ...
        def describeContents(self) -> int: ...

    class InstructionCount:
        def __init__(self) -> None: ...
        def collect(self) -> bool: ...
        def globalTotal(self) -> int: ...
        def resetAndStart(self) -> bool: ...
        def globalMethodInvocations(self) -> int: ...
