from typing import Any, ClassVar, overload
from android.os.Looper import Looper

class HandlerThread:
    MIN_PRIORITY: ClassVar[int]
    NORM_PRIORITY: ClassVar[int]
    MAX_PRIORITY: ClassVar[int]
    @overload
    def __init__(self, p0: str, p1: int) -> None: ...
    @overload
    def __init__(self, p0: str) -> None: ...
    def quit(self) -> bool: ...
    def quitSafely(self) -> bool: ...
    def getLooper(self) -> Looper: ...
    def getThreadId(self) -> int: ...
    def run(self) -> None: ...
