from typing import Any, ClassVar, overload
from android.os.Handler import Handler
from android.os.Parcel import Parcel
from java.io.File import File
from java.io.FileDescriptor import FileDescriptor
from java.io.IOException import IOException
from java.net.DatagramSocket import DatagramSocket
from java.net.Socket import Socket

class ParcelFileDescriptor:
    CREATOR: ClassVar[Any]
    MODE_APPEND: ClassVar[int]
    MODE_CREATE: ClassVar[int]
    MODE_READ_ONLY: ClassVar[int]
    MODE_READ_WRITE: ClassVar[int]
    MODE_TRUNCATE: ClassVar[int]
    MODE_WORLD_READABLE: ClassVar[int]
    MODE_WORLD_WRITEABLE: ClassVar[int]
    MODE_WRITE_ONLY: ClassVar[int]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    def __init__(self, p0: "ParcelFileDescriptor") -> None: ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
    def getFd(self) -> int: ...
    @staticmethod
    def fromFd(p0: int) -> "ParcelFileDescriptor": ...
    @staticmethod
    def adoptFd(p0: int) -> "ParcelFileDescriptor": ...
    @staticmethod
    def fromSocket(p0: Socket) -> "ParcelFileDescriptor": ...
    @staticmethod
    def fromDatagramSocket(p0: DatagramSocket) -> "ParcelFileDescriptor": ...
    @staticmethod
    def createPipe() -> Any: ...
    @staticmethod
    def createReliablePipe() -> Any: ...
    @staticmethod
    def createSocketPair() -> Any: ...
    @staticmethod
    def createReliableSocketPair() -> Any: ...
    @staticmethod
    def parseMode(p0: str) -> int: ...
    def getFileDescriptor(self) -> FileDescriptor: ...
    def getStatSize(self) -> int: ...
    def detachFd(self) -> int: ...
    def closeWithError(self, p0: str) -> None: ...
    def canDetectErrors(self) -> bool: ...
    def checkError(self) -> None: ...
    @overload
    @staticmethod
    def dup(p0: FileDescriptor) -> "ParcelFileDescriptor": ...
    @overload
    def dup(self) -> "ParcelFileDescriptor": ...
    def toString(self) -> str: ...
    @staticmethod
    def wrap(p0: "ParcelFileDescriptor", p1: Handler, p2: Any) -> "ParcelFileDescriptor": ...
    def close(self) -> None: ...
    @overload
    @staticmethod
    def open(p0: File, p1: int) -> "ParcelFileDescriptor": ...
    @overload
    @staticmethod
    def open(p0: File, p1: int, p2: Handler, p3: Any) -> "ParcelFileDescriptor": ...

    class OnCloseListener:
        def onClose(self, p0: IOException) -> None: ...

    class FileDescriptorDetachedException:
        def __init__(self) -> None: ...

    class AutoCloseOutputStream:
        def __init__(self, p0: "ParcelFileDescriptor") -> None: ...
        def close(self) -> None: ...

    class AutoCloseInputStream:
        def __init__(self, p0: "ParcelFileDescriptor") -> None: ...
        @overload
        def read(self, p0: Any, p1: int, p2: int) -> int: ...
        @overload
        def read(self, p0: Any) -> int: ...
        @overload
        def read(self) -> int: ...
        def close(self) -> None: ...
