from typing import Any, ClassVar, overload
from android.os.WorkSource import WorkSource
from java.time.Duration import Duration
from java.util.concurrent.Executor import Executor

class PowerManager:
    ACQUIRE_CAUSES_WAKEUP: ClassVar[int]
    ACTION_DEVICE_IDLE_MODE_CHANGED: ClassVar[str]
    ACTION_DEVICE_LIGHT_IDLE_MODE_CHANGED: ClassVar[str]
    ACTION_LOW_POWER_STANDBY_ENABLED_CHANGED: ClassVar[str]
    ACTION_LOW_POWER_STANDBY_POLICY_CHANGED: ClassVar[str]
    ACTION_POWER_SAVE_MODE_CHANGED: ClassVar[str]
    FEATURE_WAKE_ON_LAN_IN_LOW_POWER_STANDBY: ClassVar[str]
    FULL_WAKE_LOCK: ClassVar[int]
    LOCATION_MODE_ALL_DISABLED_WHEN_SCREEN_OFF: ClassVar[int]
    LOCATION_MODE_FOREGROUND_ONLY: ClassVar[int]
    LOCATION_MODE_GPS_DISABLED_WHEN_SCREEN_OFF: ClassVar[int]
    LOCATION_MODE_NO_CHANGE: ClassVar[int]
    LOCATION_MODE_THROTTLE_REQUESTS_WHEN_SCREEN_OFF: ClassVar[int]
    LOW_POWER_STANDBY_ALLOWED_REASON_ONGOING_CALL: ClassVar[int]
    LOW_POWER_STANDBY_ALLOWED_REASON_TEMP_POWER_SAVE_ALLOWLIST: ClassVar[int]
    LOW_POWER_STANDBY_ALLOWED_REASON_VOICE_INTERACTION: ClassVar[int]
    ON_AFTER_RELEASE: ClassVar[int]
    PARTIAL_WAKE_LOCK: ClassVar[int]
    PROXIMITY_SCREEN_OFF_WAKE_LOCK: ClassVar[int]
    RELEASE_FLAG_WAIT_FOR_NO_PROXIMITY: ClassVar[int]
    SCREEN_BRIGHT_WAKE_LOCK: ClassVar[int]
    SCREEN_DIM_WAKE_LOCK: ClassVar[int]
    THERMAL_STATUS_CRITICAL: ClassVar[int]
    THERMAL_STATUS_EMERGENCY: ClassVar[int]
    THERMAL_STATUS_LIGHT: ClassVar[int]
    THERMAL_STATUS_MODERATE: ClassVar[int]
    THERMAL_STATUS_NONE: ClassVar[int]
    THERMAL_STATUS_SEVERE: ClassVar[int]
    THERMAL_STATUS_SHUTDOWN: ClassVar[int]
    def isInteractive(self) -> bool: ...
    def reboot(self, p0: str) -> None: ...
    def getThermalHeadroom(self, p0: int) -> float: ...
    def isScreenOn(self) -> bool: ...
    def isDeviceIdleMode(self) -> bool: ...
    def newWakeLock(self, p0: int, p1: str) -> Any: ...
    def isPowerSaveMode(self) -> bool: ...
    @overload
    def addThermalHeadroomListener(self, p0: Executor, p1: Any) -> None: ...
    @overload
    def addThermalHeadroomListener(self, p0: Any) -> None: ...
    @overload
    def addThermalStatusListener(self, p0: Any) -> None: ...
    @overload
    def addThermalStatusListener(self, p0: Executor, p1: Any) -> None: ...
    def getBatteryDischargePrediction(self) -> Duration: ...
    def getCurrentThermalStatus(self) -> int: ...
    def getLocationPowerSaveMode(self) -> int: ...
    def getThermalHeadroomThresholds(self) -> dict: ...
    @overload
    def isAllowedInLowPowerStandby(self, p0: str) -> bool: ...
    @overload
    def isAllowedInLowPowerStandby(self, p0: int) -> bool: ...
    def isBatteryDischargePredictionPersonalized(self) -> bool: ...
    def isDeviceLightIdleMode(self) -> bool: ...
    def isExemptFromLowPowerStandby(self) -> bool: ...
    def isIgnoringBatteryOptimizations(self, p0: str) -> bool: ...
    def isLowPowerStandbyEnabled(self) -> bool: ...
    def isRebootingUserspaceSupported(self) -> bool: ...
    def isSustainedPerformanceModeSupported(self) -> bool: ...
    def isWakeLockLevelSupported(self, p0: int) -> bool: ...
    def removeThermalHeadroomListener(self, p0: Any) -> None: ...
    def removeThermalStatusListener(self, p0: Any) -> None: ...

    class WakeLockStateListener:
        def onStateChanged(self, p0: bool) -> None: ...

    class WakeLock:
        def isHeld(self) -> bool: ...
        def setReferenceCounted(self, p0: bool) -> None: ...
        def setWorkSource(self, p0: WorkSource) -> None: ...
        def setStateListener(self, p0: Executor, p1: Any) -> None: ...
        def toString(self) -> str: ...
        @overload
        def release(self) -> None: ...
        @overload
        def release(self, p0: int) -> None: ...
        @overload
        def acquire(self) -> None: ...
        @overload
        def acquire(self, p0: int) -> None: ...

    class OnThermalStatusChangedListener:
        def onThermalStatusChanged(self, p0: int) -> None: ...

    class OnThermalHeadroomChangedListener:
        def onThermalHeadroomChanged(self, p0: float, p1: float, p2: int, p3: dict) -> None: ...
