from typing import Any, ClassVar, overload

class ProxyFileDescriptorCallback:
    def __init__(self) -> None: ...
    def onWrite(self, p0: int, p1: int, p2: Any) -> int: ...
    def onRelease(self) -> None: ...
    def onRead(self, p0: int, p1: int, p2: Any) -> int: ...
    def onGetSize(self) -> int: ...
    def onFsync(self) -> None: ...
