from typing import Any, ClassVar, overload
from android.media.AudioAttributes import AudioAttributes
from android.os.VibrationAttributes import VibrationAttributes
from android.os.VibrationEffect import VibrationEffect

class Vibrator:
    VIBRATION_EFFECT_SUPPORT_NO: ClassVar[int]
    VIBRATION_EFFECT_SUPPORT_UNKNOWN: ClassVar[int]
    VIBRATION_EFFECT_SUPPORT_YES: ClassVar[int]
    @overload
    def vibrate(self, p0: int) -> None: ...
    @overload
    def vibrate(self, p0: int, p1: AudioAttributes) -> None: ...
    @overload
    def vibrate(self, p0: Any, p1: int) -> None: ...
    @overload
    def vibrate(self, p0: VibrationEffect) -> None: ...
    @overload
    def vibrate(self, p0: VibrationEffect, p1: AudioAttributes) -> None: ...
    @overload
    def vibrate(self, p0: VibrationEffect, p1: VibrationAttributes) -> None: ...
    @overload
    def vibrate(self, p0: Any, p1: int, p2: AudioAttributes) -> None: ...
    def hasVibrator(self) -> bool: ...
    def hasAmplitudeControl(self) -> bool: ...
    def getResonantFrequency(self) -> float: ...
    def getQFactor(self) -> float: ...
    def areEffectsSupported(self, p0: Any) -> Any: ...
    def areAllEffectsSupported(self, p0: Any) -> int: ...
    def arePrimitivesSupported(self, p0: Any) -> Any: ...
    def areAllPrimitivesSupported(self, p0: Any) -> bool: ...
    def getPrimitiveDurations(self, p0: Any) -> Any: ...
    def getId(self) -> int: ...
    def cancel(self) -> None: ...
