from typing import Any, ClassVar, overload
from java.util.Iterator import Iterator

class AbstractCollection:
    def remove(self, p0: Any) -> bool: ...
    def size(self) -> int: ...
    def toString(self) -> str: ...
    def clear(self) -> None: ...
    def isEmpty(self) -> bool: ...
    def add(self, p0: Any) -> bool: ...
    @overload
    def toArray(self, p0: Any) -> Any: ...
    @overload
    def toArray(self) -> Any: ...
    def iterator(self) -> Iterator: ...
    def contains(self, p0: Any) -> bool: ...
    def addAll(self, p0: list) -> bool: ...
    def removeAll(self, p0: list) -> bool: ...
    def retainAll(self, p0: list) -> bool: ...
    def containsAll(self, p0: list) -> bool: ...
