from typing import Any, ClassVar, overload
from java.util.Locale import Locale
from java.util.stream.Stream import Stream

class Currency:
    def toString(self) -> str: ...
    @overload
    @staticmethod
    def getInstance(p0: str) -> "Currency": ...
    @overload
    @staticmethod
    def getInstance(p0: Locale) -> "Currency": ...
    @overload
    def getDisplayName(self, p0: Locale) -> str: ...
    @overload
    def getDisplayName(self) -> str: ...
    @overload
    def getSymbol(self, p0: Locale) -> str: ...
    @overload
    def getSymbol(self) -> str: ...
    @staticmethod
    def getAvailableCurrencies() -> set: ...
    @staticmethod
    def availableCurrencies() -> Stream: ...
    def getCurrencyCode(self) -> str: ...
    def getDefaultFractionDigits(self) -> int: ...
    def getNumericCode(self) -> int: ...
    def getNumericCodeAsString(self) -> str: ...
