from jnius import JavaClass, JavaInterface, MetaJavaClass, JavaMethod, JavaStaticMethod, JavaMultipleMethod, JavaField, JavaStaticField

class BackingStoreException(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "java/util/prefs/BackingStoreException"
    __javaconstructor__ = [("(Ljava/lang/String;)V", False), ("(Ljava/lang/Throwable;)V", False)]

class NodeChangeEvent(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "java/util/prefs/NodeChangeEvent"
    __javaconstructor__ = [("(Ljava/util/prefs/Preferences;Ljava/util/prefs/Preferences;)V", False)]
    getParent = JavaMethod("()Ljava/util/prefs/Preferences;")
    getChild = JavaMethod("()Ljava/util/prefs/Preferences;")

class AbstractPreferences(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "java/util/prefs/AbstractPreferences"
    MAX_KEY_LENGTH = JavaStaticField("I")
    MAX_VALUE_LENGTH = JavaStaticField("I")
    MAX_NAME_LENGTH = JavaStaticField("I")
    childrenNames = JavaMethod("()[Ljava/lang/String;")
    nodeExists = JavaMethod("(Ljava/lang/String;)Z")
    absolutePath = JavaMethod("()Ljava/lang/String;")
    isUserNode = JavaMethod("()Z")
    addPreferenceChangeListener = JavaMethod("(Ljava/util/prefs/PreferenceChangeListener;)V")
    removePreferenceChangeListener = JavaMethod("(Ljava/util/prefs/PreferenceChangeListener;)V")
    addNodeChangeListener = JavaMethod("(Ljava/util/prefs/NodeChangeListener;)V")
    removeNodeChangeListener = JavaMethod("(Ljava/util/prefs/NodeChangeListener;)V")
    exportNode = JavaMethod("(Ljava/io/OutputStream;)V")
    exportSubtree = JavaMethod("(Ljava/io/OutputStream;)V")
    name = JavaMethod("()Ljava/lang/String;")
    remove = JavaMethod("(Ljava/lang/String;)V")
    parent = JavaMethod("()Ljava/util/prefs/Preferences;")
    get = JavaMethod("(Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;")
    put = JavaMethod("(Ljava/lang/String;Ljava/lang/String;)V")
    toString = JavaMethod("()Ljava/lang/String;")
    getBoolean = JavaMethod("(Ljava/lang/String;Z)Z")
    putBoolean = JavaMethod("(Ljava/lang/String;Z)V")
    getInt = JavaMethod("(Ljava/lang/String;I)I")
    putInt = JavaMethod("(Ljava/lang/String;I)V")
    getLong = JavaMethod("(Ljava/lang/String;J)J")
    putLong = JavaMethod("(Ljava/lang/String;J)V")
    getFloat = JavaMethod("(Ljava/lang/String;F)F")
    putFloat = JavaMethod("(Ljava/lang/String;F)V")
    getDouble = JavaMethod("(Ljava/lang/String;D)D")
    putDouble = JavaMethod("(Ljava/lang/String;D)V")
    clear = JavaMethod("()V")
    flush = JavaMethod("()V")
    keys = JavaMethod("()[Ljava/lang/String;")
    sync = JavaMethod("()V")
    getByteArray = JavaMethod("(Ljava/lang/String;[B)[B")
    putByteArray = JavaMethod("(Ljava/lang/String;[B)V")
    removeNode = JavaMethod("()V")
    node = JavaMethod("(Ljava/lang/String;)Ljava/util/prefs/Preferences;")

class PreferenceChangeListener(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "java/util/prefs/PreferenceChangeListener"
    preferenceChange = JavaMethod("(Ljava/util/prefs/PreferenceChangeEvent;)V")

class Preferences(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "java/util/prefs/Preferences"
    MAX_KEY_LENGTH = JavaStaticField("I")
    MAX_VALUE_LENGTH = JavaStaticField("I")
    MAX_NAME_LENGTH = JavaStaticField("I")
    userRoot = JavaStaticMethod("()Ljava/util/prefs/Preferences;")
    systemRoot = JavaStaticMethod("()Ljava/util/prefs/Preferences;")
    importPreferences = JavaStaticMethod("(Ljava/io/InputStream;)V")
    userNodeForPackage = JavaStaticMethod("(Ljava/lang/Class;)Ljava/util/prefs/Preferences;")
    systemNodeForPackage = JavaStaticMethod("(Ljava/lang/Class;)Ljava/util/prefs/Preferences;")
    childrenNames = JavaMethod("()[Ljava/lang/String;")
    nodeExists = JavaMethod("(Ljava/lang/String;)Z")
    absolutePath = JavaMethod("()Ljava/lang/String;")
    isUserNode = JavaMethod("()Z")
    addPreferenceChangeListener = JavaMethod("(Ljava/util/prefs/PreferenceChangeListener;)V")
    removePreferenceChangeListener = JavaMethod("(Ljava/util/prefs/PreferenceChangeListener;)V")
    addNodeChangeListener = JavaMethod("(Ljava/util/prefs/NodeChangeListener;)V")
    removeNodeChangeListener = JavaMethod("(Ljava/util/prefs/NodeChangeListener;)V")
    exportNode = JavaMethod("(Ljava/io/OutputStream;)V")
    exportSubtree = JavaMethod("(Ljava/io/OutputStream;)V")
    name = JavaMethod("()Ljava/lang/String;")
    remove = JavaMethod("(Ljava/lang/String;)V")
    parent = JavaMethod("()Ljava/util/prefs/Preferences;")
    get = JavaMethod("(Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;")
    put = JavaMethod("(Ljava/lang/String;Ljava/lang/String;)V")
    toString = JavaMethod("()Ljava/lang/String;")
    getBoolean = JavaMethod("(Ljava/lang/String;Z)Z")
    putBoolean = JavaMethod("(Ljava/lang/String;Z)V")
    getInt = JavaMethod("(Ljava/lang/String;I)I")
    putInt = JavaMethod("(Ljava/lang/String;I)V")
    getLong = JavaMethod("(Ljava/lang/String;J)J")
    putLong = JavaMethod("(Ljava/lang/String;J)V")
    getFloat = JavaMethod("(Ljava/lang/String;F)F")
    putFloat = JavaMethod("(Ljava/lang/String;F)V")
    getDouble = JavaMethod("(Ljava/lang/String;D)D")
    putDouble = JavaMethod("(Ljava/lang/String;D)V")
    clear = JavaMethod("()V")
    flush = JavaMethod("()V")
    keys = JavaMethod("()[Ljava/lang/String;")
    sync = JavaMethod("()V")
    getByteArray = JavaMethod("(Ljava/lang/String;[B)[B")
    putByteArray = JavaMethod("(Ljava/lang/String;[B)V")
    removeNode = JavaMethod("()V")
    node = JavaMethod("(Ljava/lang/String;)Ljava/util/prefs/Preferences;")

class InvalidPreferencesFormatException(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "java/util/prefs/InvalidPreferencesFormatException"
    __javaconstructor__ = [("(Ljava/lang/Throwable;)V", False), ("(Ljava/lang/String;)V", False), ("(Ljava/lang/String;Ljava/lang/Throwable;)V", False)]

class PreferenceChangeEvent(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "java/util/prefs/PreferenceChangeEvent"
    __javaconstructor__ = [("(Ljava/util/prefs/Preferences;Ljava/lang/String;Ljava/lang/String;)V", False)]
    getNewValue = JavaMethod("()Ljava/lang/String;")
    getKey = JavaMethod("()Ljava/lang/String;")
    getNode = JavaMethod("()Ljava/util/prefs/Preferences;")

class NodeChangeListener(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "java/util/prefs/NodeChangeListener"
    childAdded = JavaMethod("(Ljava/util/prefs/NodeChangeEvent;)V")
    childRemoved = JavaMethod("(Ljava/util/prefs/NodeChangeEvent;)V")

class PreferencesFactory(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "java/util/prefs/PreferencesFactory"
    userRoot = JavaMethod("()Ljava/util/prefs/Preferences;")
    systemRoot = JavaMethod("()Ljava/util/prefs/Preferences;")