from typing import Any, ClassVar, overload

class UnknownFormatConversionException:
    def __init__(self, p0: str) -> None: ...
    def getMessage(self) -> str: ...
    def getConversion(self) -> str: ...
