from typing import Any, ClassVar, overload
from java.time.Duration import Duration
from java.time.Instant import Instant
from java.time.LocalDateTime import LocalDateTime
from java.time.ZoneOffset import ZoneOffset
from java.time.zone.ZoneOffsetTransition import ZoneOffsetTransition

class ZoneRules:
    def equals(self, p0: Any) -> bool: ...
    def toString(self) -> str: ...
    def hashCode(self) -> int: ...
    @overload
    @staticmethod
    def of(p0: ZoneOffset, p1: ZoneOffset, p2: list, p3: list, p4: list) -> "ZoneRules": ...
    @overload
    @staticmethod
    def of(p0: ZoneOffset) -> "ZoneRules": ...
    @overload
    def getOffset(self, p0: LocalDateTime) -> ZoneOffset: ...
    @overload
    def getOffset(self, p0: Instant) -> ZoneOffset: ...
    def isDaylightSavings(self, p0: Instant) -> bool: ...
    def getStandardOffset(self, p0: Instant) -> ZoneOffset: ...
    def getDaylightSavings(self, p0: Instant) -> Duration: ...
    def nextTransition(self, p0: Instant) -> ZoneOffsetTransition: ...
    def previousTransition(self, p0: Instant) -> ZoneOffsetTransition: ...
    def getTransitions(self) -> list: ...
    def getTransitionRules(self) -> list: ...
    def getValidOffsets(self, p0: LocalDateTime) -> list: ...
    def isValidOffset(self, p0: LocalDateTime, p1: ZoneOffset) -> bool: ...
    def getTransition(self, p0: LocalDateTime) -> ZoneOffsetTransition: ...
    def isFixedOffset(self) -> bool: ...
