from typing import Any, ClassVar, overload
from android.hardware.biometrics.PromptContentItem import PromptContentItem
from android.os.Parcel import Parcel

class PromptVerticalListContentView:
    CREATOR: ClassVar[Any]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    @staticmethod
    def getMaxItemCount() -> int: ...
    @staticmethod
    def getMaxEachItemCharacterNumber() -> int: ...
    def getListItems(self) -> list: ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
    def getDescription(self) -> str: ...

    class Builder:
        def __init__(self) -> None: ...
        @overload
        def addListItem(self, p0: PromptContentItem) -> Any: ...
        @overload
        def addListItem(self, p0: PromptContentItem, p1: int) -> Any: ...
        def setDescription(self, p0: str) -> Any: ...
        def build(self) -> "PromptVerticalListContentView": ...
