from typing import Any, ClassVar, overload
from android.app.PendingIntent import PendingIntent
from android.app.RemoteInput import RemoteInput
from android.app.slice.Slice import Slice
from android.graphics.drawable.Icon import Icon
from android.os.Bundle import Bundle
from android.os.Parcel import Parcel

class SliceItem:
    CREATOR: ClassVar[Any]
    FORMAT_ACTION: ClassVar[str]
    FORMAT_BUNDLE: ClassVar[str]
    FORMAT_IMAGE: ClassVar[str]
    FORMAT_INT: ClassVar[str]
    FORMAT_LONG: ClassVar[str]
    FORMAT_REMOTE_INPUT: ClassVar[str]
    FORMAT_SLICE: ClassVar[str]
    FORMAT_TEXT: ClassVar[str]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    def getHints(self) -> list: ...
    def getRemoteInput(self) -> RemoteInput: ...
    def getSubType(self) -> str: ...
    def hasHint(self, p0: str) -> bool: ...
    def getInt(self) -> int: ...
    def getLong(self) -> int: ...
    def getFormat(self) -> str: ...
    def getIcon(self) -> Icon: ...
    def getAction(self) -> PendingIntent: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
    def getBundle(self) -> Bundle: ...
    def describeContents(self) -> int: ...
    def getText(self) -> str: ...
    def getSlice(self) -> Slice: ...
