from typing import Any, ClassVar, overload
from android.view.Display import Display
from android.view.Surface import Surface

class VirtualDisplay:
    def getSurface(self) -> Surface: ...
    def setSurface(self, p0: Surface) -> None: ...
    def toString(self) -> str: ...
    def release(self) -> None: ...
    def getDisplay(self) -> Display: ...
    def setRotation(self, p0: int) -> None: ...
    def resize(self, p0: int, p1: int, p2: int) -> None: ...

    class Callback:
        def __init__(self) -> None: ...
        def onPaused(self) -> None: ...
        def onResumed(self) -> None: ...
        def onStopped(self) -> None: ...
