from typing import Any, ClassVar, overload

class DESedeKeySpec:
    DES_EDE_KEY_LEN: ClassVar[int]
    @overload
    def __init__(self, p0: Any) -> None: ...
    @overload
    def __init__(self, p0: Any, p1: int) -> None: ...
    def getKey(self) -> Any: ...
    @staticmethod
    def isParityAdjusted(p0: Any, p1: int) -> bool: ...
