from typing import Any, ClassVar, overload

class DHGenParameterSpec:
    def __init__(self, p0: int, p1: int) -> None: ...
    def getPrimeSize(self) -> int: ...
    def getExponentSize(self) -> int: ...
