from typing import Any, ClassVar, overload

class GCMParameterSpec:
    @overload
    def __init__(self, p0: int, p1: Any) -> None: ...
    @overload
    def __init__(self, p0: int, p1: Any, p2: int, p3: int) -> None: ...
    def getIV(self) -> Any: ...
    def getTLen(self) -> int: ...
