from typing import Any, ClassVar, overload
from java.security.spec.AlgorithmParameterSpec import AlgorithmParameterSpec
from javax.crypto.spec.PSource import PSource

class OAEPParameterSpec:
    DEFAULT: ClassVar["OAEPParameterSpec"]
    def __init__(self, p0: str, p1: str, p2: AlgorithmParameterSpec, p3: PSource) -> None: ...
    def getPSource(self) -> PSource: ...
    def getDigestAlgorithm(self) -> str: ...
    def getMGFAlgorithm(self) -> str: ...
    def getMGFParameters(self) -> AlgorithmParameterSpec: ...
