from typing import Any, ClassVar, overload
from android.os.Parcel import Parcel

class BarringInfo:
    BARRING_SERVICE_TYPE_CS_FALLBACK: ClassVar[int]
    BARRING_SERVICE_TYPE_CS_SERVICE: ClassVar[int]
    BARRING_SERVICE_TYPE_CS_VOICE: ClassVar[int]
    BARRING_SERVICE_TYPE_EMERGENCY: ClassVar[int]
    BARRING_SERVICE_TYPE_MMTEL_VIDEO: ClassVar[int]
    BARRING_SERVICE_TYPE_MMTEL_VOICE: ClassVar[int]
    BARRING_SERVICE_TYPE_MO_DATA: ClassVar[int]
    BARRING_SERVICE_TYPE_MO_SIGNALLING: ClassVar[int]
    BARRING_SERVICE_TYPE_PS_SERVICE: ClassVar[int]
    BARRING_SERVICE_TYPE_SMS: ClassVar[int]
    CREATOR: ClassVar[Any]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    def getBarringServiceInfo(self, p0: int) -> Any: ...
    def equals(self, p0: Any) -> bool: ...
    def toString(self) -> str: ...
    def hashCode(self) -> int: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
    def describeContents(self) -> int: ...

    class BarringServiceInfo:
        BARRING_TYPE_CONDITIONAL: ClassVar[int]
        BARRING_TYPE_NONE: ClassVar[int]
        BARRING_TYPE_UNCONDITIONAL: ClassVar[int]
        BARRING_TYPE_UNKNOWN: ClassVar[int]
        CREATOR: ClassVar[Any]
        CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
        PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
        def getConditionalBarringFactor(self) -> int: ...
        def getConditionalBarringTimeSeconds(self) -> int: ...
        def isConditionallyBarred(self) -> bool: ...
        def isBarred(self) -> bool: ...
        def getBarringType(self) -> int: ...
        def equals(self, p0: Any) -> bool: ...
        def toString(self) -> str: ...
        def hashCode(self) -> int: ...
        def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
        def describeContents(self) -> int: ...
