from typing import Any, ClassVar, overload
from android.os.Parcel import Parcel

class CellSignalStrengthLte:
    CREATOR: ClassVar[Any]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    SIGNAL_STRENGTH_GOOD: ClassVar[int]
    SIGNAL_STRENGTH_GREAT: ClassVar[int]
    SIGNAL_STRENGTH_MODERATE: ClassVar[int]
    SIGNAL_STRENGTH_NONE_OR_UNKNOWN: ClassVar[int]
    SIGNAL_STRENGTH_POOR: ClassVar[int]
    def getAsuLevel(self) -> int: ...
    def getDbm(self) -> int: ...
    def getCqiTableIndex(self) -> int: ...
    def getRsrp(self) -> int: ...
    def getRssnr(self) -> int: ...
    def getRsrq(self) -> int: ...
    def getCqi(self) -> int: ...
    def getTimingAdvance(self) -> int: ...
    def equals(self, p0: Any) -> bool: ...
    def toString(self) -> str: ...
    def hashCode(self) -> int: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
    def describeContents(self) -> int: ...
    def getRssi(self) -> int: ...
    def getLevel(self) -> int: ...
