from typing import Any, ClassVar, overload
from android.os.Parcel import Parcel

class SignalStrengthUpdateRequest:
    CREATOR: ClassVar[Any]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    def isReportingRequestedWhileIdle(self) -> bool: ...
    def getSignalThresholdInfos(self) -> list: ...
    def equals(self, p0: Any) -> bool: ...
    def toString(self) -> str: ...
    def hashCode(self) -> int: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
    def describeContents(self) -> int: ...

    class Builder:
        def __init__(self) -> None: ...
        def setSignalThresholdInfos(self, p0: list) -> Any: ...
        def setReportingRequestedWhileIdle(self, p0: bool) -> Any: ...
        def build(self) -> "SignalStrengthUpdateRequest": ...
