from typing import Any, ClassVar, overload
from android.content.Context import Context
from android.graphics.Bitmap import Bitmap
from android.os.Parcel import Parcel
from android.os.ParcelUuid import ParcelUuid

class SubscriptionInfo:
    CREATOR: ClassVar[Any]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    def createIconBitmap(self, p0: Context) -> Bitmap: ...
    def getIccId(self) -> str: ...
    def getCarrierName(self) -> str: ...
    def getIconTint(self) -> int: ...
    def getDataRoaming(self) -> int: ...
    def getCountryIso(self) -> str: ...
    def isEmbedded(self) -> bool: ...
    def isOpportunistic(self) -> bool: ...
    def getGroupUuid(self) -> ParcelUuid: ...
    def getSubscriptionType(self) -> int: ...
    def getPortIndex(self) -> int: ...
    def getUsageSetting(self) -> int: ...
    def isOnlyNonTerrestrialNetwork(self) -> bool: ...
    def getServiceCapabilities(self) -> set: ...
    def getSubscriptionId(self) -> int: ...
    def getMccString(self) -> str: ...
    def getMncString(self) -> str: ...
    def getSimSlotIndex(self) -> int: ...
    def getMcc(self) -> int: ...
    def getCarrierId(self) -> int: ...
    def getMnc(self) -> int: ...
    def getCardId(self) -> int: ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
    def getNumber(self) -> str: ...
    def getDisplayName(self) -> str: ...
    def equals(self, p0: Any) -> bool: ...
    def toString(self) -> str: ...
    def hashCode(self) -> int: ...
