from typing import Any, ClassVar, overload
from android.net.MacAddress import MacAddress
from android.os.Parcel import Parcel

class WifiP2pDirInfo:
    CREATOR: ClassVar[Any]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    def __init__(self, p0: MacAddress, p1: Any, p2: Any) -> None: ...
    def getMacAddress(self) -> MacAddress: ...
    def toString(self) -> str: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
    def describeContents(self) -> int: ...
    def getDirTag(self) -> Any: ...
    def getNonce(self) -> Any: ...
