from typing import Any, ClassVar, overload
from android.os.Parcel import Parcel
from android.text.TextPaint import TextPaint

class SuggestionRangeSpan:
    CREATOR: ClassVar[Any]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    def __init__(self) -> None: ...
    def setBackgroundColor(self, p0: int) -> None: ...
    def getBackgroundColor(self) -> int: ...
    def updateDrawState(self, p0: TextPaint) -> None: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
    def describeContents(self) -> int: ...
    def getSpanTypeId(self) -> int: ...
