from typing import Any, ClassVar, overload
from android.os.Parcel import Parcel
from android.view.View import View

class URLSpan:
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    @overload
    def __init__(self, p0: Parcel) -> None: ...
    @overload
    def __init__(self, p0: str) -> None: ...
    def toString(self) -> str: ...
    def onClick(self, p0: View) -> None: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
    def describeContents(self) -> int: ...
    def getSpanTypeId(self) -> int: ...
    def getURL(self) -> str: ...
