from jnius import JavaClass, MetaJavaClass, JavaMethod, JavaStaticMethod, JavaMultipleMethod, JavaField, JavaStaticField

__all__ = ["DynamicsProcessing"]

class DynamicsProcessing(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "android/media/audiofx/DynamicsProcessing"
    __javaconstructor__ = [("(IILandroid/media/audiofx/DynamicsProcessing$Config;)V", False), ("(I)V", False)]
    VARIANT_FAVOR_FREQUENCY_RESOLUTION = JavaStaticField("I")
    VARIANT_FAVOR_TIME_RESOLUTION = JavaStaticField("I")
    ACTION_CLOSE_AUDIO_EFFECT_CONTROL_SESSION = JavaStaticField("Ljava/lang/String;")
    ACTION_DISPLAY_AUDIO_EFFECT_CONTROL_PANEL = JavaStaticField("Ljava/lang/String;")
    ACTION_OPEN_AUDIO_EFFECT_CONTROL_SESSION = JavaStaticField("Ljava/lang/String;")
    ALREADY_EXISTS = JavaStaticField("I")
    CONTENT_TYPE_GAME = JavaStaticField("I")
    CONTENT_TYPE_MOVIE = JavaStaticField("I")
    CONTENT_TYPE_MUSIC = JavaStaticField("I")
    CONTENT_TYPE_VOICE = JavaStaticField("I")
    EFFECT_AUXILIARY = JavaStaticField("Ljava/lang/String;")
    EFFECT_INSERT = JavaStaticField("Ljava/lang/String;")
    EFFECT_POST_PROCESSING = JavaStaticField("Ljava/lang/String;")
    EFFECT_PRE_PROCESSING = JavaStaticField("Ljava/lang/String;")
    EFFECT_TYPE_AEC = JavaStaticField("Ljava/util/UUID;")
    EFFECT_TYPE_AGC = JavaStaticField("Ljava/util/UUID;")
    EFFECT_TYPE_BASS_BOOST = JavaStaticField("Ljava/util/UUID;")
    EFFECT_TYPE_DYNAMICS_PROCESSING = JavaStaticField("Ljava/util/UUID;")
    EFFECT_TYPE_ENV_REVERB = JavaStaticField("Ljava/util/UUID;")
    EFFECT_TYPE_EQUALIZER = JavaStaticField("Ljava/util/UUID;")
    EFFECT_TYPE_HAPTIC_GENERATOR = JavaStaticField("Ljava/util/UUID;")
    EFFECT_TYPE_LOUDNESS_ENHANCER = JavaStaticField("Ljava/util/UUID;")
    EFFECT_TYPE_NS = JavaStaticField("Ljava/util/UUID;")
    EFFECT_TYPE_PRESET_REVERB = JavaStaticField("Ljava/util/UUID;")
    EFFECT_TYPE_VIRTUALIZER = JavaStaticField("Ljava/util/UUID;")
    ERROR = JavaStaticField("I")
    ERROR_BAD_VALUE = JavaStaticField("I")
    ERROR_DEAD_OBJECT = JavaStaticField("I")
    ERROR_INVALID_OPERATION = JavaStaticField("I")
    ERROR_NO_INIT = JavaStaticField("I")
    ERROR_NO_MEMORY = JavaStaticField("I")
    EXTRA_AUDIO_SESSION = JavaStaticField("Ljava/lang/String;")
    EXTRA_CONTENT_TYPE = JavaStaticField("Ljava/lang/String;")
    EXTRA_PACKAGE_NAME = JavaStaticField("Ljava/lang/String;")
    SUCCESS = JavaStaticField("I")
    setChannelTo = JavaMethod("(ILandroid/media/audiofx/DynamicsProcessing$Channel;)V")
    setAllChannelsTo = JavaMethod("(Landroid/media/audiofx/DynamicsProcessing$Channel;)V")
    getChannelByChannelIndex = JavaMethod("(I)Landroid/media/audiofx/DynamicsProcessing$Channel;")
    getInputGainByChannelIndex = JavaMethod("(I)F")
    getLimiterByChannelIndex = JavaMethod("(I)Landroid/media/audiofx/DynamicsProcessing$Limiter;")
    getMbcBandByChannelIndex = JavaMethod("(II)Landroid/media/audiofx/DynamicsProcessing$MbcBand;")
    getMbcByChannelIndex = JavaMethod("(I)Landroid/media/audiofx/DynamicsProcessing$Mbc;")
    getPostEqBandByChannelIndex = JavaMethod("(II)Landroid/media/audiofx/DynamicsProcessing$EqBand;")
    getPostEqByChannelIndex = JavaMethod("(I)Landroid/media/audiofx/DynamicsProcessing$Eq;")
    getPreEqBandByChannelIndex = JavaMethod("(II)Landroid/media/audiofx/DynamicsProcessing$EqBand;")
    getPreEqByChannelIndex = JavaMethod("(I)Landroid/media/audiofx/DynamicsProcessing$Eq;")
    setInputGainAllChannelsTo = JavaMethod("(F)V")
    setInputGainbyChannel = JavaMethod("(IF)V")
    setLimiterAllChannelsTo = JavaMethod("(Landroid/media/audiofx/DynamicsProcessing$Limiter;)V")
    setLimiterByChannelIndex = JavaMethod("(ILandroid/media/audiofx/DynamicsProcessing$Limiter;)V")
    setMbcAllChannelsTo = JavaMethod("(Landroid/media/audiofx/DynamicsProcessing$Mbc;)V")
    setMbcBandAllChannelsTo = JavaMethod("(ILandroid/media/audiofx/DynamicsProcessing$MbcBand;)V")
    setMbcBandByChannelIndex = JavaMethod("(IILandroid/media/audiofx/DynamicsProcessing$MbcBand;)V")
    setMbcByChannelIndex = JavaMethod("(ILandroid/media/audiofx/DynamicsProcessing$Mbc;)V")
    setPostEqAllChannelsTo = JavaMethod("(Landroid/media/audiofx/DynamicsProcessing$Eq;)V")
    setPostEqBandAllChannelsTo = JavaMethod("(ILandroid/media/audiofx/DynamicsProcessing$EqBand;)V")
    setPostEqBandByChannelIndex = JavaMethod("(IILandroid/media/audiofx/DynamicsProcessing$EqBand;)V")
    setPostEqByChannelIndex = JavaMethod("(ILandroid/media/audiofx/DynamicsProcessing$Eq;)V")
    setPreEqAllChannelsTo = JavaMethod("(Landroid/media/audiofx/DynamicsProcessing$Eq;)V")
    setPreEqBandAllChannelsTo = JavaMethod("(ILandroid/media/audiofx/DynamicsProcessing$EqBand;)V")
    setPreEqBandByChannelIndex = JavaMethod("(IILandroid/media/audiofx/DynamicsProcessing$EqBand;)V")
    setPreEqByChannelIndex = JavaMethod("(ILandroid/media/audiofx/DynamicsProcessing$Eq;)V")
    getChannelCount = JavaMethod("()I")
    getConfig = JavaMethod("()Landroid/media/audiofx/DynamicsProcessing$Config;")

    class Stage(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "android/media/audiofx/DynamicsProcessing$Stage"
        __javaconstructor__ = [("(ZZ)V", False)]
        isInUse = JavaMethod("()Z")
        toString = JavaMethod("()Ljava/lang/String;")
        isEnabled = JavaMethod("()Z")
        setEnabled = JavaMethod("(Z)V")

    class MbcBand(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "android/media/audiofx/DynamicsProcessing$MbcBand"
        __javaconstructor__ = [("(Landroid/media/audiofx/DynamicsProcessing$MbcBand;)V", False), ("(ZFFFFFFFFFF)V", False)]
        getRatio = JavaMethod("()F")
        getReleaseTime = JavaMethod("()F")
        setAttackTime = JavaMethod("(F)V")
        setPostGain = JavaMethod("(F)V")
        setRatio = JavaMethod("(F)V")
        setReleaseTime = JavaMethod("(F)V")
        getAttackTime = JavaMethod("()F")
        getPostGain = JavaMethod("()F")
        setKneeWidth = JavaMethod("(F)V")
        setNoiseGateThreshold = JavaMethod("(F)V")
        setPreGain = JavaMethod("(F)V")
        getExpanderRatio = JavaMethod("()F")
        getKneeWidth = JavaMethod("()F")
        getNoiseGateThreshold = JavaMethod("()F")
        getPreGain = JavaMethod("()F")
        setExpanderRatio = JavaMethod("(F)V")
        toString = JavaMethod("()Ljava/lang/String;")
        getThreshold = JavaMethod("()F")
        setThreshold = JavaMethod("(F)V")

    class Mbc(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "android/media/audiofx/DynamicsProcessing$Mbc"
        __javaconstructor__ = [("(Landroid/media/audiofx/DynamicsProcessing$Mbc;)V", False), ("(ZZI)V", False)]
        getBand = JavaMethod("(I)Landroid/media/audiofx/DynamicsProcessing$MbcBand;")
        setBand = JavaMethod("(ILandroid/media/audiofx/DynamicsProcessing$MbcBand;)V")
        toString = JavaMethod("()Ljava/lang/String;")

    class Limiter(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "android/media/audiofx/DynamicsProcessing$Limiter"
        __javaconstructor__ = [("(ZZIFFFFF)V", False), ("(Landroid/media/audiofx/DynamicsProcessing$Limiter;)V", False)]
        getRatio = JavaMethod("()F")
        getReleaseTime = JavaMethod("()F")
        setAttackTime = JavaMethod("(F)V")
        setLinkGroup = JavaMethod("(I)V")
        setPostGain = JavaMethod("(F)V")
        setRatio = JavaMethod("(F)V")
        setReleaseTime = JavaMethod("(F)V")
        getAttackTime = JavaMethod("()F")
        getLinkGroup = JavaMethod("()I")
        getPostGain = JavaMethod("()F")
        toString = JavaMethod("()Ljava/lang/String;")
        getThreshold = JavaMethod("()F")
        setThreshold = JavaMethod("(F)V")

    class EqBand(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "android/media/audiofx/DynamicsProcessing$EqBand"
        __javaconstructor__ = [("(Landroid/media/audiofx/DynamicsProcessing$EqBand;)V", False), ("(ZFF)V", False)]
        getGain = JavaMethod("()F")
        setGain = JavaMethod("(F)V")
        toString = JavaMethod("()Ljava/lang/String;")

    class Eq(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "android/media/audiofx/DynamicsProcessing$Eq"
        __javaconstructor__ = [("(Landroid/media/audiofx/DynamicsProcessing$Eq;)V", False), ("(ZZI)V", False)]
        getBand = JavaMethod("(I)Landroid/media/audiofx/DynamicsProcessing$EqBand;")
        setBand = JavaMethod("(ILandroid/media/audiofx/DynamicsProcessing$EqBand;)V")
        toString = JavaMethod("()Ljava/lang/String;")

    class Config(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "android/media/audiofx/DynamicsProcessing$Config"
        setInputGainByChannelIndex = JavaMethod("(IF)V")
        setChannelTo = JavaMethod("(ILandroid/media/audiofx/DynamicsProcessing$Channel;)V")
        setAllChannelsTo = JavaMethod("(Landroid/media/audiofx/DynamicsProcessing$Channel;)V")
        getChannelByChannelIndex = JavaMethod("(I)Landroid/media/audiofx/DynamicsProcessing$Channel;")
        getInputGainByChannelIndex = JavaMethod("(I)F")
        getLimiterByChannelIndex = JavaMethod("(I)Landroid/media/audiofx/DynamicsProcessing$Limiter;")
        getMbcBandByChannelIndex = JavaMethod("(II)Landroid/media/audiofx/DynamicsProcessing$MbcBand;")
        getMbcByChannelIndex = JavaMethod("(I)Landroid/media/audiofx/DynamicsProcessing$Mbc;")
        getPostEqBandByChannelIndex = JavaMethod("(II)Landroid/media/audiofx/DynamicsProcessing$EqBand;")
        getPostEqByChannelIndex = JavaMethod("(I)Landroid/media/audiofx/DynamicsProcessing$Eq;")
        getPreEqBandByChannelIndex = JavaMethod("(II)Landroid/media/audiofx/DynamicsProcessing$EqBand;")
        getPreEqByChannelIndex = JavaMethod("(I)Landroid/media/audiofx/DynamicsProcessing$Eq;")
        setInputGainAllChannelsTo = JavaMethod("(F)V")
        setLimiterAllChannelsTo = JavaMethod("(Landroid/media/audiofx/DynamicsProcessing$Limiter;)V")
        setLimiterByChannelIndex = JavaMethod("(ILandroid/media/audiofx/DynamicsProcessing$Limiter;)V")
        setMbcAllChannelsTo = JavaMethod("(Landroid/media/audiofx/DynamicsProcessing$Mbc;)V")
        setMbcBandAllChannelsTo = JavaMethod("(ILandroid/media/audiofx/DynamicsProcessing$MbcBand;)V")
        setMbcBandByChannelIndex = JavaMethod("(IILandroid/media/audiofx/DynamicsProcessing$MbcBand;)V")
        setMbcByChannelIndex = JavaMethod("(ILandroid/media/audiofx/DynamicsProcessing$Mbc;)V")
        setPostEqAllChannelsTo = JavaMethod("(Landroid/media/audiofx/DynamicsProcessing$Eq;)V")
        setPostEqBandAllChannelsTo = JavaMethod("(ILandroid/media/audiofx/DynamicsProcessing$EqBand;)V")
        setPostEqBandByChannelIndex = JavaMethod("(IILandroid/media/audiofx/DynamicsProcessing$EqBand;)V")
        setPostEqByChannelIndex = JavaMethod("(ILandroid/media/audiofx/DynamicsProcessing$Eq;)V")
        setPreEqAllChannelsTo = JavaMethod("(Landroid/media/audiofx/DynamicsProcessing$Eq;)V")
        setPreEqBandAllChannelsTo = JavaMethod("(ILandroid/media/audiofx/DynamicsProcessing$EqBand;)V")
        setPreEqBandByChannelIndex = JavaMethod("(IILandroid/media/audiofx/DynamicsProcessing$EqBand;)V")
        setPreEqByChannelIndex = JavaMethod("(ILandroid/media/audiofx/DynamicsProcessing$Eq;)V")
        toString = JavaMethod("()Ljava/lang/String;")
        isPostEqInUse = JavaMethod("()Z")
        isLimiterInUse = JavaMethod("()Z")
        getPostEqBandCount = JavaMethod("()I")
        getMbcBandCount = JavaMethod("()I")
        getPreEqBandCount = JavaMethod("()I")
        isMbcInUse = JavaMethod("()Z")
        getPreferredFrameDuration = JavaMethod("()F")
        isPreEqInUse = JavaMethod("()Z")
        getVariant = JavaMethod("()I")

        class Builder(JavaClass, metaclass=MetaJavaClass):
            __javaclass__ = "android/media/audiofx/DynamicsProcessing$Config$Builder"
            __javaconstructor__ = [("(IIZIZIZIZ)V", False)]
            setInputGainByChannelIndex = JavaMethod("(IF)Landroid/media/audiofx/DynamicsProcessing$Config$Builder;")
            setPreferredFrameDuration = JavaMethod("(F)Landroid/media/audiofx/DynamicsProcessing$Config$Builder;")
            setChannelTo = JavaMethod("(ILandroid/media/audiofx/DynamicsProcessing$Channel;)Landroid/media/audiofx/DynamicsProcessing$Config$Builder;")
            setAllChannelsTo = JavaMethod("(Landroid/media/audiofx/DynamicsProcessing$Channel;)Landroid/media/audiofx/DynamicsProcessing$Config$Builder;")
            setInputGainAllChannelsTo = JavaMethod("(F)Landroid/media/audiofx/DynamicsProcessing$Config$Builder;")
            setLimiterAllChannelsTo = JavaMethod("(Landroid/media/audiofx/DynamicsProcessing$Limiter;)Landroid/media/audiofx/DynamicsProcessing$Config$Builder;")
            setLimiterByChannelIndex = JavaMethod("(ILandroid/media/audiofx/DynamicsProcessing$Limiter;)Landroid/media/audiofx/DynamicsProcessing$Config$Builder;")
            setMbcAllChannelsTo = JavaMethod("(Landroid/media/audiofx/DynamicsProcessing$Mbc;)Landroid/media/audiofx/DynamicsProcessing$Config$Builder;")
            setMbcByChannelIndex = JavaMethod("(ILandroid/media/audiofx/DynamicsProcessing$Mbc;)Landroid/media/audiofx/DynamicsProcessing$Config$Builder;")
            setPostEqAllChannelsTo = JavaMethod("(Landroid/media/audiofx/DynamicsProcessing$Eq;)Landroid/media/audiofx/DynamicsProcessing$Config$Builder;")
            setPostEqByChannelIndex = JavaMethod("(ILandroid/media/audiofx/DynamicsProcessing$Eq;)Landroid/media/audiofx/DynamicsProcessing$Config$Builder;")
            setPreEqAllChannelsTo = JavaMethod("(Landroid/media/audiofx/DynamicsProcessing$Eq;)Landroid/media/audiofx/DynamicsProcessing$Config$Builder;")
            setPreEqByChannelIndex = JavaMethod("(ILandroid/media/audiofx/DynamicsProcessing$Eq;)Landroid/media/audiofx/DynamicsProcessing$Config$Builder;")
            build = JavaMethod("()Landroid/media/audiofx/DynamicsProcessing$Config;")

    class Channel(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "android/media/audiofx/DynamicsProcessing$Channel"
        __javaconstructor__ = [("(Landroid/media/audiofx/DynamicsProcessing$Channel;)V", False), ("(FZIZIZIZ)V", False)]
        getPostEqBand = JavaMethod("(I)Landroid/media/audiofx/DynamicsProcessing$EqBand;")
        getPreEqBand = JavaMethod("(I)Landroid/media/audiofx/DynamicsProcessing$EqBand;")
        setInputGain = JavaMethod("(F)V")
        setLimiter = JavaMethod("(Landroid/media/audiofx/DynamicsProcessing$Limiter;)V")
        setMbc = JavaMethod("(Landroid/media/audiofx/DynamicsProcessing$Mbc;)V")
        setMbcBand = JavaMethod("(ILandroid/media/audiofx/DynamicsProcessing$MbcBand;)V")
        setPostEq = JavaMethod("(Landroid/media/audiofx/DynamicsProcessing$Eq;)V")
        getPreEq = JavaMethod("()Landroid/media/audiofx/DynamicsProcessing$Eq;")
        setPostEqBand = JavaMethod("(ILandroid/media/audiofx/DynamicsProcessing$EqBand;)V")
        setPreEq = JavaMethod("(Landroid/media/audiofx/DynamicsProcessing$Eq;)V")
        setPreEqBand = JavaMethod("(ILandroid/media/audiofx/DynamicsProcessing$EqBand;)V")
        toString = JavaMethod("()Ljava/lang/String;")
        getMbcBand = JavaMethod("(I)Landroid/media/audiofx/DynamicsProcessing$MbcBand;")
        getLimiter = JavaMethod("()Landroid/media/audiofx/DynamicsProcessing$Limiter;")
        getInputGain = JavaMethod("()F")
        getMbc = JavaMethod("()Landroid/media/audiofx/DynamicsProcessing$Mbc;")
        getPostEq = JavaMethod("()Landroid/media/audiofx/DynamicsProcessing$Eq;")

    class BandStage(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "android/media/audiofx/DynamicsProcessing$BandStage"
        __javaconstructor__ = [("(ZZI)V", False)]
        getBandCount = JavaMethod("()I")
        toString = JavaMethod("()Ljava/lang/String;")

    class BandBase(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "android/media/audiofx/DynamicsProcessing$BandBase"
        __javaconstructor__ = [("(ZF)V", False)]
        getCutoffFrequency = JavaMethod("()F")
        setCutoffFrequency = JavaMethod("(F)V")
        toString = JavaMethod("()Ljava/lang/String;")
        isEnabled = JavaMethod("()Z")
        setEnabled = JavaMethod("(Z)V")