from typing import Any, ClassVar, overload
from android.graphics.drawable.Icon import Icon
from android.os.Parcel import Parcel

class GetWalletCardsError:
    CREATOR: ClassVar[Any]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    def __init__(self, p0: Icon, p1: str) -> None: ...
    def getMessage(self) -> str: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
    def describeContents(self) -> int: ...
    def getIcon(self) -> Icon: ...
