from typing import Any, ClassVar, overload
from android.os.Parcel import Parcel

class VirtualDevice:
    CREATOR: ClassVar[Any]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    def getDisplayIds(self) -> Any: ...
    def getPersistentDeviceId(self) -> str: ...
    def hasCustomSensorSupport(self) -> bool: ...
    def getName(self) -> str: ...
    def toString(self) -> str: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
    def describeContents(self) -> int: ...
    def getDeviceId(self) -> int: ...
    def getDisplayName(self) -> str: ...
