from typing import Any, ClassVar, overload
from android.content.Context import Context
from android.content.Intent import Intent
from android.content.SharedPreferences import SharedPreferences
from android.preference.Preference import Preference
from android.preference.PreferenceDataStore import PreferenceDataStore
from android.preference.PreferenceScreen import PreferenceScreen

class PreferenceManager:
    KEY_HAS_SET_DEFAULT_VALUES: ClassVar[str]
    METADATA_KEY_PREFERENCES: ClassVar[str]
    @overload
    @staticmethod
    def setDefaultValues(p0: Context, p1: int, p2: bool) -> None: ...
    @overload
    @staticmethod
    def setDefaultValues(p0: Context, p1: str, p2: int, p3: int, p4: bool) -> None: ...
    def isStorageDefault(self) -> bool: ...
    def findPreference(self, p0: str) -> Preference: ...
    def createPreferenceScreen(self, p0: Context) -> PreferenceScreen: ...
    @staticmethod
    def getDefaultSharedPreferences(p0: Context) -> SharedPreferences: ...
    @staticmethod
    def getDefaultSharedPreferencesName(p0: Context) -> str: ...
    def getPreferenceDataStore(self) -> PreferenceDataStore: ...
    def getSharedPreferencesMode(self) -> int: ...
    def getSharedPreferencesName(self) -> str: ...
    def isStorageDeviceProtected(self) -> bool: ...
    def setPreferenceDataStore(self, p0: PreferenceDataStore) -> None: ...
    def setSharedPreferencesMode(self, p0: int) -> None: ...
    def setSharedPreferencesName(self, p0: str) -> None: ...
    def setStorageDefault(self) -> None: ...
    def setStorageDeviceProtected(self) -> None: ...
    def getSharedPreferences(self) -> SharedPreferences: ...

    class OnActivityStopListener:
        def onActivityStop(self) -> None: ...

    class OnActivityResultListener:
        def onActivityResult(self, p0: int, p1: int, p2: Intent) -> bool: ...

    class OnActivityDestroyListener:
        def onActivityDestroy(self) -> None: ...
