from typing import Any, ClassVar, overload
from android.os.Bundle import Bundle

class GsmCellLocation:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, p0: Bundle) -> None: ...
    def fillInNotifierBundle(self, p0: Bundle) -> None: ...
    def setLacAndCid(self, p0: int, p1: int) -> None: ...
    def setStateInvalid(self) -> None: ...
    def getCid(self) -> int: ...
    def getPsc(self) -> int: ...
    def getLac(self) -> int: ...
    def equals(self, p0: Any) -> bool: ...
    def toString(self) -> str: ...
    def hashCode(self) -> int: ...
