from typing import Any, ClassVar, overload
from android.os.Parcel import Parcel

class StorageStats:
    APP_DATA_TYPE_FILE_TYPE_APK: ClassVar[int]
    APP_DATA_TYPE_FILE_TYPE_CURRENT_PROFILE: ClassVar[int]
    APP_DATA_TYPE_FILE_TYPE_DEXOPT_ARTIFACT: ClassVar[int]
    APP_DATA_TYPE_FILE_TYPE_DM: ClassVar[int]
    APP_DATA_TYPE_FILE_TYPE_REFERENCE_PROFILE: ClassVar[int]
    APP_DATA_TYPE_LIB: ClassVar[int]
    CREATOR: ClassVar[Any]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    def getAppBytes(self) -> int: ...
    def getAppBytesByDataType(self, p0: int) -> int: ...
    def getDataBytes(self) -> int: ...
    def getCacheBytes(self) -> int: ...
    def getExternalCacheBytes(self) -> int: ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
