from typing import Any, ClassVar, overload
from android.os.Parcel import Parcel

class UsageEventsQuery:
    CREATOR: ClassVar[Any]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    def getEndTimeMillis(self) -> int: ...
    def getBeginTimeMillis(self) -> int: ...
    def getEventTypes(self) -> Any: ...
    def getPackageNames(self) -> set: ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...

    class Builder:
        def __init__(self, p0: int, p1: int) -> None: ...
        def setEventTypes(self, p0: Any) -> Any: ...
        def setPackageNames(self, p0: Any) -> Any: ...
        def build(self) -> "UsageEventsQuery": ...
