# cython: language_level=3
# Generated by pyjnius-wrap cython — do not edit by hand.
from jni_core._core cimport JavaObject
from jni_core.jni cimport (
    jobject, jstring,
    jboolean, jbyte, jchar, jshort, jint, jlong, jfloat, jdouble,
)

cdef class UsageEvents(JavaObject):
    cdef jint _describeContents(self) except *
    cdef void _writeToParcel(self, jobject p0, jint p1) except *
    cdef jboolean _hasNextEvent(self) except *
    cdef jboolean _getNextEvent(self, jobject p0) except *

cdef class Event(JavaObject):
    cdef jlong _getTimeStamp(self) except *
    cdef jint _getAppStandbyBucket(self) except *
    cdef jstring _getShortcutId(self) except? NULL
    cdef jobject _getConfiguration(self) except? NULL
    cdef jstring _getPackageName(self) except? NULL
    cdef jstring _getClassName(self) except? NULL
    cdef jobject _getExtras(self) except? NULL
    cdef jint _getEventType(self) except *
