from typing import Any, ClassVar, overload
from java.net.DatagramPacket import DatagramPacket
from java.net.DatagramSocketImplFactory import DatagramSocketImplFactory
from java.net.InetAddress import InetAddress
from java.net.NetworkInterface import NetworkInterface
from java.net.SocketAddress import SocketAddress
from java.net.SocketOption import SocketOption
from java.nio.channels.DatagramChannel import DatagramChannel

class DatagramSocket:
    @overload
    def __init__(self, p0: int, p1: InetAddress) -> None: ...
    @overload
    def __init__(self, p0: SocketAddress) -> None: ...
    @overload
    def __init__(self, p0: int) -> None: ...
    @overload
    def __init__(self) -> None: ...
    def getInetAddress(self) -> InetAddress: ...
    def disconnect(self) -> None: ...
    def isConnected(self) -> bool: ...
    def send(self, p0: DatagramPacket) -> None: ...
    def getBroadcast(self) -> bool: ...
    def isBound(self) -> bool: ...
    def getRemoteSocketAddress(self) -> SocketAddress: ...
    def getLocalSocketAddress(self) -> SocketAddress: ...
    def receive(self, p0: DatagramPacket) -> None: ...
    def getLocalAddress(self) -> InetAddress: ...
    def getLocalPort(self) -> int: ...
    def setSoTimeout(self, p0: int) -> None: ...
    def getSoTimeout(self) -> int: ...
    def setSendBufferSize(self, p0: int) -> None: ...
    def getSendBufferSize(self) -> int: ...
    def setReceiveBufferSize(self, p0: int) -> None: ...
    def getReceiveBufferSize(self) -> int: ...
    def setReuseAddress(self, p0: bool) -> None: ...
    def getReuseAddress(self) -> bool: ...
    def setBroadcast(self, p0: bool) -> None: ...
    def setTrafficClass(self, p0: int) -> None: ...
    def getTrafficClass(self) -> int: ...
    def setOption(self, p0: SocketOption, p1: Any) -> "DatagramSocket": ...
    def getOption(self, p0: SocketOption) -> Any: ...
    def supportedOptions(self) -> set: ...
    def joinGroup(self, p0: SocketAddress, p1: NetworkInterface) -> None: ...
    def leaveGroup(self, p0: SocketAddress, p1: NetworkInterface) -> None: ...
    @staticmethod
    def setDatagramSocketImplFactory(p0: DatagramSocketImplFactory) -> None: ...
    def isClosed(self) -> bool: ...
    def getPort(self) -> int: ...
    def getChannel(self) -> DatagramChannel: ...
    def bind(self, p0: SocketAddress) -> None: ...
    @overload
    def connect(self, p0: SocketAddress) -> None: ...
    @overload
    def connect(self, p0: InetAddress, p1: int) -> None: ...
    def close(self) -> None: ...
