from typing import Any, ClassVar, overload
from java.net.NetworkInterface import NetworkInterface

class Inet6Address:
    def isIPv4CompatibleAddress(self) -> bool: ...
    def getScopedInterface(self) -> NetworkInterface: ...
    def getAddress(self) -> Any: ...
    def isLinkLocalAddress(self) -> bool: ...
    def getScopeId(self) -> int: ...
    @overload
    @staticmethod
    def getByAddress(p0: str, p1: Any, p2: int) -> "Inet6Address": ...
    @overload
    @staticmethod
    def getByAddress(p0: str, p1: Any, p2: NetworkInterface) -> "Inet6Address": ...
    def isMulticastAddress(self) -> bool: ...
    def isAnyLocalAddress(self) -> bool: ...
    def isLoopbackAddress(self) -> bool: ...
    def isSiteLocalAddress(self) -> bool: ...
    def isMCGlobal(self) -> bool: ...
    def isMCNodeLocal(self) -> bool: ...
    def isMCLinkLocal(self) -> bool: ...
    def isMCSiteLocal(self) -> bool: ...
    def isMCOrgLocal(self) -> bool: ...
    def equals(self, p0: Any) -> bool: ...
    def hashCode(self) -> int: ...
    def getHostAddress(self) -> str: ...
