from typing import Any, ClassVar, overload

class PasswordAuthentication:
    def __init__(self, p0: str, p1: Any) -> None: ...
    def getUserName(self) -> str: ...
    def getPassword(self) -> Any: ...
