from typing import Any, ClassVar, overload
from android.content.Context import Context
from android.util.AttributeSet import AttributeSet
from android.view.animation.Interpolator import Interpolator
from android.view.animation.Transformation import Transformation

class Animation:
    ABSOLUTE: ClassVar[int]
    INFINITE: ClassVar[int]
    RELATIVE_TO_PARENT: ClassVar[int]
    RELATIVE_TO_SELF: ClassVar[int]
    RESTART: ClassVar[int]
    REVERSE: ClassVar[int]
    START_ON_FIRST_FRAME: ClassVar[int]
    ZORDER_BOTTOM: ClassVar[int]
    ZORDER_NORMAL: ClassVar[int]
    ZORDER_TOP: ClassVar[int]
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, p0: Context, p1: AttributeSet) -> None: ...
    def reset(self) -> None: ...
    def initialize(self, p0: int, p1: int, p2: int, p3: int) -> None: ...
    def start(self) -> None: ...
    def cancel(self) -> None: ...
    def getRepeatCount(self) -> int: ...
    def isInitialized(self) -> bool: ...
    def getInterpolator(self) -> Interpolator: ...
    def setDuration(self, p0: int) -> None: ...
    @overload
    def setInterpolator(self, p0: Interpolator) -> None: ...
    @overload
    def setInterpolator(self, p0: Context, p1: int) -> None: ...
    def getBackgroundColor(self) -> int: ...
    def getDetachWallpaper(self) -> bool: ...
    def getFillAfter(self) -> bool: ...
    def getFillBefore(self) -> bool: ...
    def getBackdropColor(self) -> int: ...
    def computeDurationHint(self) -> int: ...
    def getRepeatMode(self) -> int: ...
    def getShowBackdrop(self) -> bool: ...
    def getStartOffset(self) -> int: ...
    def getStartTime(self) -> int: ...
    @overload
    def getTransformation(self, p0: int, p1: Transformation) -> bool: ...
    @overload
    def getTransformation(self, p0: int, p1: Transformation, p2: float) -> bool: ...
    def getZAdjustment(self) -> int: ...
    def hasEnded(self) -> bool: ...
    def isFillEnabled(self) -> bool: ...
    def restrictDuration(self, p0: int) -> None: ...
    def scaleCurrentDuration(self, p0: float) -> None: ...
    def setAnimationListener(self, p0: Any) -> None: ...
    def setBackdropColor(self, p0: int) -> None: ...
    def setDetachWallpaper(self, p0: bool) -> None: ...
    def setFillAfter(self, p0: bool) -> None: ...
    def setFillBefore(self, p0: bool) -> None: ...
    def setFillEnabled(self, p0: bool) -> None: ...
    def setRepeatCount(self, p0: int) -> None: ...
    def setRepeatMode(self, p0: int) -> None: ...
    def setShowBackdrop(self, p0: bool) -> None: ...
    def setStartOffset(self, p0: int) -> None: ...
    def setStartTime(self, p0: int) -> None: ...
    def setZAdjustment(self, p0: int) -> None: ...
    def startNow(self) -> None: ...
    def willChangeBounds(self) -> bool: ...
    def willChangeTransformationMatrix(self) -> bool: ...
    def getDuration(self) -> int: ...
    def hasStarted(self) -> bool: ...
    def setBackgroundColor(self, p0: int) -> None: ...

    class AnimationListener:
        def onAnimationRepeat(self, p0: "Animation") -> None: ...
        def onAnimationEnd(self, p0: "Animation") -> None: ...
        def onAnimationStart(self, p0: "Animation") -> None: ...
