from typing import Any, ClassVar, overload
from android.content.Context import Context
from android.util.AttributeSet import AttributeSet
from android.view.animation.Animation import Animation

class GridLayoutAnimationController:
    DIRECTION_BOTTOM_TO_TOP: ClassVar[int]
    DIRECTION_HORIZONTAL_MASK: ClassVar[int]
    DIRECTION_LEFT_TO_RIGHT: ClassVar[int]
    DIRECTION_RIGHT_TO_LEFT: ClassVar[int]
    DIRECTION_TOP_TO_BOTTOM: ClassVar[int]
    DIRECTION_VERTICAL_MASK: ClassVar[int]
    PRIORITY_COLUMN: ClassVar[int]
    PRIORITY_NONE: ClassVar[int]
    PRIORITY_ROW: ClassVar[int]
    ORDER_NORMAL: ClassVar[int]
    ORDER_RANDOM: ClassVar[int]
    ORDER_REVERSE: ClassVar[int]
    @overload
    def __init__(self, p0: Context, p1: AttributeSet) -> None: ...
    @overload
    def __init__(self, p0: Animation) -> None: ...
    @overload
    def __init__(self, p0: Animation, p1: float, p2: float) -> None: ...
    def setDirection(self, p0: int) -> None: ...
    def getDirection(self) -> int: ...
    def setRowDelay(self, p0: float) -> None: ...
    def setColumnDelay(self, p0: float) -> None: ...
    def setDirectionPriority(self, p0: int) -> None: ...
    def getRowDelay(self) -> float: ...
    def getColumnDelay(self) -> float: ...
    def getDirectionPriority(self) -> int: ...
    def willOverlap(self) -> bool: ...

    class AnimationParameters:
        column: int
        columnsCount: int
        row: int
        rowsCount: int
        count: int
        index: int
        def __init__(self) -> None: ...
