from typing import Any, ClassVar, overload
from java.math.BigDecimal import BigDecimal
from java.util.Calendar import Calendar
from java.util.Date import Date
from javax.xml.namespace.QName import QName

class Duration:
    def __init__(self) -> None: ...
    def getSign(self) -> int: ...
    def subtract(self, p0: "Duration") -> "Duration": ...
    def equals(self, p0: Any) -> bool: ...
    def toString(self) -> str: ...
    def hashCode(self) -> int: ...
    def compare(self, p0: "Duration") -> int: ...
    def add(self, p0: "Duration") -> "Duration": ...
    def getField(self, p0: Any) -> float: ...
    def isSet(self, p0: Any) -> bool: ...
    @overload
    def multiply(self, p0: int) -> "Duration": ...
    @overload
    def multiply(self, p0: BigDecimal) -> "Duration": ...
    @overload
    def getTimeInMillis(self, p0: Calendar) -> int: ...
    @overload
    def getTimeInMillis(self, p0: Date) -> int: ...
    def getHours(self) -> int: ...
    def getMinutes(self) -> int: ...
    def negate(self) -> "Duration": ...
    def getSeconds(self) -> int: ...
    @overload
    def addTo(self, p0: Calendar) -> None: ...
    @overload
    def addTo(self, p0: Date) -> None: ...
    def getYears(self) -> int: ...
    def getMonths(self) -> int: ...
    def getDays(self) -> int: ...
    def getXMLSchemaType(self) -> QName: ...
    def normalizeWith(self, p0: Calendar) -> "Duration": ...
    def isLongerThan(self, p0: "Duration") -> bool: ...
    def isShorterThan(self, p0: "Duration") -> bool: ...
