from typing import Any, ClassVar, overload
from android.content.Context import Context
from android.content.pm.ApplicationInfo import ApplicationInfo
from android.os.Parcel import Parcel

class SpellCheckerSubtype:
    CREATOR: ClassVar[Any]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    def __init__(self, p0: int, p1: str, p2: str) -> None: ...
    def getNameResId(self) -> int: ...
    def getLanguageTag(self) -> str: ...
    def getExtraValue(self) -> str: ...
    def containsExtraValueKey(self, p0: str) -> bool: ...
    def getExtraValueOf(self, p0: str) -> str: ...
    def equals(self, p0: Any) -> bool: ...
    def hashCode(self) -> int: ...
    def getDisplayName(self, p0: Context, p1: str, p2: ApplicationInfo) -> str: ...
    def getLocale(self) -> str: ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
