from typing import Any, ClassVar, overload
from android.content.Context import Context
from java.math.BigInteger import BigInteger
from java.security.spec.AlgorithmParameterSpec import AlgorithmParameterSpec
from java.util.Date import Date
from javax.security.auth.x500.X500Principal import X500Principal

class KeyPairGeneratorSpec:
    def getKeySize(self) -> int: ...
    def getKeystoreAlias(self) -> str: ...
    def getKeyType(self) -> str: ...
    def isEncryptionRequired(self) -> bool: ...
    def getEndDate(self) -> Date: ...
    def getStartDate(self) -> Date: ...
    def getAlgorithmParameterSpec(self) -> AlgorithmParameterSpec: ...
    def getSerialNumber(self) -> BigInteger: ...
    def getSubjectDN(self) -> X500Principal: ...
    def getContext(self) -> Context: ...

    class Builder:
        def __init__(self, p0: Context) -> None: ...
        def setAlias(self, p0: str) -> Any: ...
        def setEndDate(self, p0: Date) -> Any: ...
        def setKeyType(self, p0: str) -> Any: ...
        def setStartDate(self, p0: Date) -> Any: ...
        def setKeySize(self, p0: int) -> Any: ...
        def setAlgorithmParameterSpec(self, p0: AlgorithmParameterSpec) -> Any: ...
        def setEncryptionRequired(self) -> Any: ...
        def setSerialNumber(self, p0: BigInteger) -> Any: ...
        def setSubject(self, p0: X500Principal) -> Any: ...
        def build(self) -> "KeyPairGeneratorSpec": ...
