from typing import Any, ClassVar, overload
from java.security.cert.Certificate import Certificate

class CRL:
    def isRevoked(self, p0: Certificate) -> bool: ...
    def toString(self) -> str: ...
    def getType(self) -> str: ...
