from typing import Any, ClassVar, overload
from android.os.Parcel import Parcel

class MediaProjectionConfig:
    CREATOR: ClassVar[Any]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    @staticmethod
    def createConfigForUserChoice() -> "MediaProjectionConfig": ...
    @staticmethod
    def createConfigForDefaultDisplay() -> "MediaProjectionConfig": ...
    def equals(self, p0: Any) -> bool: ...
    def toString(self) -> str: ...
    def hashCode(self) -> int: ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
