from typing import Any, ClassVar, overload
from java.net.InetAddress import InetAddress

class RtpStream:
    MODE_NORMAL: ClassVar[int]
    MODE_RECEIVE_ONLY: ClassVar[int]
    MODE_SEND_ONLY: ClassVar[int]
    def getRemoteAddress(self) -> InetAddress: ...
    def getRemotePort(self) -> int: ...
    def isBusy(self) -> bool: ...
    def associate(self, p0: InetAddress, p1: int) -> None: ...
    def getLocalAddress(self) -> InetAddress: ...
    def getLocalPort(self) -> int: ...
    def getMode(self) -> int: ...
    def setMode(self, p0: int) -> None: ...
    def release(self) -> None: ...
