from typing import Any, ClassVar, overload
from android.os.Parcel import Parcel

class BluetoothHealthAppConfiguration:
    CREATOR: ClassVar[Any]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    def getRole(self) -> int: ...
    def getName(self) -> str: ...
    def getDataType(self) -> int: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
    def describeContents(self) -> int: ...
