from typing import Any, ClassVar, overload
from java.util.UUID import UUID

class BluetoothSocketSettings:
    def isEncryptionRequired(self) -> bool: ...
    def toString(self) -> str: ...
    def isAuthenticationRequired(self) -> bool: ...
    def getSocketType(self) -> int: ...
    def getRfcommUuid(self) -> UUID: ...
    def getL2capPsm(self) -> int: ...
    def getRfcommServiceName(self) -> str: ...

    class Builder:
        def __init__(self) -> None: ...
        def setL2capPsm(self, p0: int) -> Any: ...
        def setRfcommUuid(self, p0: UUID) -> Any: ...
        def setSocketType(self, p0: int) -> Any: ...
        def setRfcommServiceName(self, p0: str) -> Any: ...
        def setAuthenticationRequired(self, p0: bool) -> Any: ...
        def setEncryptionRequired(self, p0: bool) -> Any: ...
        def build(self) -> "BluetoothSocketSettings": ...
