from typing import Any, ClassVar, overload
from java.net.ProtocolFamily import ProtocolFamily
from java.nio.channels.Channel import Channel
from java.nio.channels.DatagramChannel import DatagramChannel
from java.nio.channels.Pipe import Pipe
from java.nio.channels.ServerSocketChannel import ServerSocketChannel
from java.nio.channels.SocketChannel import SocketChannel
from java.nio.channels.spi.AbstractSelector import AbstractSelector

class SelectorProvider:
    @staticmethod
    def provider() -> "SelectorProvider": ...
    def inheritedChannel(self) -> Channel: ...
    @overload
    def openDatagramChannel(self, p0: ProtocolFamily) -> DatagramChannel: ...
    @overload
    def openDatagramChannel(self) -> DatagramChannel: ...
    @overload
    def openSocketChannel(self, p0: ProtocolFamily) -> SocketChannel: ...
    @overload
    def openSocketChannel(self) -> SocketChannel: ...
    @overload
    def openServerSocketChannel(self) -> ServerSocketChannel: ...
    @overload
    def openServerSocketChannel(self, p0: ProtocolFamily) -> ServerSocketChannel: ...
    def openSelector(self) -> AbstractSelector: ...
    def openPipe(self) -> Pipe: ...
