from typing import Any, ClassVar, overload
from java.lang.Appendable import Appendable

class Editable:
    SPAN_COMPOSING: ClassVar[int]
    SPAN_EXCLUSIVE_EXCLUSIVE: ClassVar[int]
    SPAN_EXCLUSIVE_INCLUSIVE: ClassVar[int]
    SPAN_INCLUSIVE_EXCLUSIVE: ClassVar[int]
    SPAN_INCLUSIVE_INCLUSIVE: ClassVar[int]
    SPAN_INTERMEDIATE: ClassVar[int]
    SPAN_MARK_MARK: ClassVar[int]
    SPAN_MARK_POINT: ClassVar[int]
    SPAN_PARAGRAPH: ClassVar[int]
    SPAN_POINT_MARK: ClassVar[int]
    SPAN_POINT_MARK_MASK: ClassVar[int]
    SPAN_POINT_POINT: ClassVar[int]
    SPAN_PRIORITY: ClassVar[int]
    SPAN_PRIORITY_SHIFT: ClassVar[int]
    SPAN_USER: ClassVar[int]
    SPAN_USER_SHIFT: ClassVar[int]
    def clearSpans(self) -> None: ...
    def setFilters(self, p0: Any) -> None: ...
    def getFilters(self) -> Any: ...
    @overload
    def append(self, p0: str) -> Appendable: ...
    @overload
    def append(self, p0: str, p1: int, p2: int) -> "Editable": ...
    @overload
    def append(self, p0: str, p1: int, p2: int) -> Appendable: ...
    @overload
    def append(self, p0: str) -> Appendable: ...
    @overload
    def append(self, p0: str) -> "Editable": ...
    @overload
    def append(self, p0: str) -> "Editable": ...
    @overload
    def insert(self, p0: int, p1: str) -> "Editable": ...
    @overload
    def insert(self, p0: int, p1: str, p2: int, p3: int) -> "Editable": ...
    def clear(self) -> None: ...
    @overload
    def replace(self, p0: int, p1: int, p2: str, p3: int, p4: int) -> "Editable": ...
    @overload
    def replace(self, p0: int, p1: int, p2: str) -> "Editable": ...
    def delete(self, p0: int, p1: int) -> "Editable": ...

    class Factory:
        def __init__(self) -> None: ...
        def newEditable(self, p0: str) -> "Editable": ...
        @staticmethod
        def getInstance() -> Any: ...
