from typing import Any, ClassVar, overload

class FontScaleConverter:
    def convertDpToSp(self, p0: float) -> float: ...
    def convertSpToDp(self, p0: float) -> float: ...
    @staticmethod
    def forScale(p0: float) -> "FontScaleConverter": ...
    @staticmethod
    def isNonLinearFontScalingActive(p0: float) -> bool: ...
