from typing import Any, ClassVar, overload
from java.io.DataInput import DataInput
from java.io.InputStream import InputStream

class DataInputStream:
    def __init__(self, p0: InputStream) -> None: ...
    @overload
    def readUTF(self) -> str: ...
    @overload
    @staticmethod
    def readUTF(p0: DataInput) -> str: ...
    def readUnsignedByte(self) -> int: ...
    def readUnsignedShort(self) -> int: ...
    def skipBytes(self, p0: int) -> int: ...
    def readBoolean(self) -> bool: ...
    def readByte(self) -> int: ...
    def readShort(self) -> int: ...
    def readLong(self) -> int: ...
    def readDouble(self) -> float: ...
    @overload
    def readFully(self, p0: Any, p1: int, p2: int) -> None: ...
    @overload
    def readFully(self, p0: Any) -> None: ...
    def readChar(self) -> str: ...
    def readFloat(self) -> float: ...
    @overload
    def read(self, p0: Any, p1: int, p2: int) -> int: ...
    @overload
    def read(self, p0: Any) -> int: ...
    def readLine(self) -> str: ...
    def readInt(self) -> int: ...
