from typing import Any, ClassVar, overload
from java.io.File import File
from java.io.FileDescriptor import FileDescriptor
from java.io.OutputStream import OutputStream
from java.nio.channels.FileChannel import FileChannel

class FileInputStream:
    @overload
    def __init__(self, p0: str) -> None: ...
    @overload
    def __init__(self, p0: File) -> None: ...
    @overload
    def __init__(self, p0: FileDescriptor) -> None: ...
    def readNBytes(self, p0: int) -> Any: ...
    def transferTo(self, p0: OutputStream) -> int: ...
    def skip(self, p0: int) -> int: ...
    def available(self) -> int: ...
    def getChannel(self) -> FileChannel: ...
    def getFD(self) -> FileDescriptor: ...
    @overload
    def read(self) -> int: ...
    @overload
    def read(self, p0: Any) -> int: ...
    @overload
    def read(self, p0: Any, p1: int, p2: int) -> int: ...
    def close(self) -> None: ...
    def readAllBytes(self) -> Any: ...
