from typing import Any, ClassVar, overload
from java.io.FileFilter import FileFilter
from java.io.FilenameFilter import FilenameFilter
from java.net.URI import URI
from java.net.URL import URL
from java.nio.file.Path import Path

class File:
    separatorChar: ClassVar[str]
    separator: ClassVar[str]
    pathSeparatorChar: ClassVar[str]
    pathSeparator: ClassVar[str]
    @overload
    def __init__(self, p0: URI) -> None: ...
    @overload
    def __init__(self, p0: str) -> None: ...
    @overload
    def __init__(self, p0: str, p1: str) -> None: ...
    @overload
    def __init__(self, p0: "File", p1: str) -> None: ...
    def getPath(self) -> str: ...
    def toURI(self) -> URI: ...
    def toURL(self) -> URL: ...
    def getAbsolutePath(self) -> str: ...
    def exists(self) -> bool: ...
    def createNewFile(self) -> bool: ...
    def renameTo(self, p0: "File") -> bool: ...
    def isDirectory(self) -> bool: ...
    def getCanonicalPath(self) -> str: ...
    def getAbsoluteFile(self) -> "File": ...
    def mkdir(self) -> bool: ...
    def getCanonicalFile(self) -> "File": ...
    def getParentFile(self) -> "File": ...
    def mkdirs(self) -> bool: ...
    @overload
    def setWritable(self, p0: bool, p1: bool) -> bool: ...
    @overload
    def setWritable(self, p0: bool) -> bool: ...
    @overload
    def setReadable(self, p0: bool) -> bool: ...
    @overload
    def setReadable(self, p0: bool, p1: bool) -> bool: ...
    @overload
    def setExecutable(self, p0: bool) -> bool: ...
    @overload
    def setExecutable(self, p0: bool, p1: bool) -> bool: ...
    @staticmethod
    def listRoots() -> Any: ...
    @overload
    @staticmethod
    def createTempFile(p0: str, p1: str) -> "File": ...
    @overload
    @staticmethod
    def createTempFile(p0: str, p1: str, p2: "File") -> "File": ...
    def canWrite(self) -> bool: ...
    def isFile(self) -> bool: ...
    def lastModified(self) -> int: ...
    def deleteOnExit(self) -> None: ...
    @overload
    def listFiles(self, p0: FilenameFilter) -> Any: ...
    @overload
    def listFiles(self) -> Any: ...
    @overload
    def listFiles(self, p0: FileFilter) -> Any: ...
    def setLastModified(self, p0: int) -> bool: ...
    def canExecute(self) -> bool: ...
    def getTotalSpace(self) -> int: ...
    def getFreeSpace(self) -> int: ...
    def getUsableSpace(self) -> int: ...
    def toPath(self) -> Path: ...
    def getName(self) -> str: ...
    def equals(self, p0: Any) -> bool: ...
    def length(self) -> int: ...
    def toString(self) -> str: ...
    def hashCode(self) -> int: ...
    def isHidden(self) -> bool: ...
    @overload
    def compareTo(self, p0: "File") -> int: ...
    @overload
    def compareTo(self, p0: Any) -> int: ...
    @overload
    def list(self, p0: FilenameFilter) -> Any: ...
    @overload
    def list(self) -> Any: ...
    def isAbsolute(self) -> bool: ...
    def getParent(self) -> str: ...
    def delete(self) -> bool: ...
    def setReadOnly(self) -> bool: ...
    def canRead(self) -> bool: ...
