from typing import Any, ClassVar, overload
from java.io.File import File
from java.io.OutputStream import OutputStream
from java.io.Writer import Writer
from java.lang.Appendable import Appendable
from java.nio.charset.Charset import Charset
from java.util.Locale import Locale

class PrintWriter:
    @overload
    def __init__(self, p0: str, p1: str) -> None: ...
    @overload
    def __init__(self, p0: str) -> None: ...
    @overload
    def __init__(self, p0: str, p1: Charset) -> None: ...
    @overload
    def __init__(self, p0: File) -> None: ...
    @overload
    def __init__(self, p0: File, p1: Charset) -> None: ...
    @overload
    def __init__(self, p0: File, p1: str) -> None: ...
    @overload
    def __init__(self, p0: Writer) -> None: ...
    @overload
    def __init__(self, p0: Writer, p1: bool) -> None: ...
    @overload
    def __init__(self, p0: OutputStream, p1: bool, p2: Charset) -> None: ...
    @overload
    def __init__(self, p0: OutputStream, p1: bool) -> None: ...
    @overload
    def __init__(self, p0: OutputStream) -> None: ...
    @overload
    def println(self, p0: float) -> None: ...
    @overload
    def println(self, p0: float) -> None: ...
    @overload
    def println(self, p0: int) -> None: ...
    @overload
    def println(self, p0: Any) -> None: ...
    @overload
    def println(self, p0: str) -> None: ...
    @overload
    def println(self, p0: Any) -> None: ...
    @overload
    def println(self) -> None: ...
    @overload
    def println(self, p0: bool) -> None: ...
    @overload
    def println(self, p0: str) -> None: ...
    @overload
    def println(self, p0: int) -> None: ...
    @overload
    def append(self, p0: str) -> Appendable: ...
    @overload
    def append(self, p0: str) -> "PrintWriter": ...
    @overload
    def append(self, p0: str) -> Writer: ...
    @overload
    def append(self, p0: str, p1: int, p2: int) -> Appendable: ...
    @overload
    def append(self, p0: str) -> Writer: ...
    @overload
    def append(self, p0: str) -> Appendable: ...
    @overload
    def append(self, p0: str, p1: int, p2: int) -> Writer: ...
    @overload
    def append(self, p0: str) -> "PrintWriter": ...
    @overload
    def append(self, p0: str, p1: int, p2: int) -> "PrintWriter": ...
    def flush(self) -> None: ...
    @overload
    def format(self, p0: Locale, p1: str, p2: Any) -> "PrintWriter": ...
    @overload
    def format(self, p0: str, p1: Any) -> "PrintWriter": ...
    def close(self) -> None: ...
    @overload
    def print(self, p0: float) -> None: ...
    @overload
    def print(self, p0: int) -> None: ...
    @overload
    def print(self, p0: int) -> None: ...
    @overload
    def print(self, p0: str) -> None: ...
    @overload
    def print(self, p0: bool) -> None: ...
    @overload
    def print(self, p0: Any) -> None: ...
    @overload
    def print(self, p0: str) -> None: ...
    @overload
    def print(self, p0: Any) -> None: ...
    @overload
    def print(self, p0: float) -> None: ...
    @overload
    def write(self, p0: str) -> None: ...
    @overload
    def write(self, p0: Any) -> None: ...
    @overload
    def write(self, p0: str, p1: int, p2: int) -> None: ...
    @overload
    def write(self, p0: Any, p1: int, p2: int) -> None: ...
    @overload
    def write(self, p0: int) -> None: ...
    @overload
    def printf(self, p0: str, p1: Any) -> "PrintWriter": ...
    @overload
    def printf(self, p0: Locale, p1: str, p2: Any) -> "PrintWriter": ...
    def checkError(self) -> bool: ...
