from typing import Any, ClassVar, overload

class StringBufferInputStream:
    def __init__(self, p0: str) -> None: ...
    def skip(self, p0: int) -> int: ...
    def available(self) -> int: ...
    def reset(self) -> None: ...
    @overload
    def read(self) -> int: ...
    @overload
    def read(self, p0: Any, p1: int, p2: int) -> int: ...
