from typing import Any, ClassVar, overload
from java.lang.Appendable import Appendable

class Writer:
    @staticmethod
    def nullWriter() -> "Writer": ...
    @overload
    def append(self, p0: str) -> "Writer": ...
    @overload
    def append(self, p0: str, p1: int, p2: int) -> "Writer": ...
    @overload
    def append(self, p0: str) -> Appendable: ...
    @overload
    def append(self, p0: str) -> "Writer": ...
    @overload
    def append(self, p0: str, p1: int, p2: int) -> Appendable: ...
    @overload
    def append(self, p0: str) -> Appendable: ...
    def flush(self) -> None: ...
    @overload
    def write(self, p0: str, p1: int, p2: int) -> None: ...
    @overload
    def write(self, p0: Any) -> None: ...
    @overload
    def write(self, p0: int) -> None: ...
    @overload
    def write(self, p0: Any, p1: int, p2: int) -> None: ...
    @overload
    def write(self, p0: str) -> None: ...
    def close(self) -> None: ...
