from typing import Any, ClassVar, overload

class DisplayLuts:
    def __init__(self) -> None: ...
    def toString(self) -> str: ...
    @overload
    def set(self, p0: Any) -> None: ...
    @overload
    def set(self, p0: Any, p1: Any) -> None: ...

    class Entry:
        def __init__(self, p0: Any, p1: int, p2: int) -> None: ...
        def getSamplingKey(self) -> int: ...
        def getBuffer(self) -> Any: ...
        def toString(self) -> str: ...
        def getDimension(self) -> int: ...
