from typing import Any, ClassVar, overload
from android.hardware.input.HostUsiVersion import HostUsiVersion
from android.os.Handler import Handler
from android.view.Display import Display
from android.view.InputDevice import InputDevice
from android.view.InputEvent import InputEvent
from android.view.VerifiedInputEvent import VerifiedInputEvent

class InputManager:
    ACTION_QUERY_KEYBOARD_LAYOUTS: ClassVar[str]
    META_DATA_KEYBOARD_LAYOUTS: ClassVar[str]
    def getHostUsiVersion(self, p0: Display) -> HostUsiVersion: ...
    def getInputDevice(self, p0: int) -> InputDevice: ...
    def getInputDeviceIds(self) -> Any: ...
    def getInputDeviceViewBehavior(self, p0: int) -> Any: ...
    def getMaximumObscuringOpacityForTouch(self) -> float: ...
    def isStylusPointerIconEnabled(self) -> bool: ...
    def registerInputDeviceListener(self, p0: Any, p1: Handler) -> None: ...
    def unregisterInputDeviceListener(self, p0: Any) -> None: ...
    def verifyInputEvent(self, p0: InputEvent) -> VerifiedInputEvent: ...

    class InputDeviceListener:
        def onInputDeviceAdded(self, p0: int) -> None: ...
        def onInputDeviceChanged(self, p0: int) -> None: ...
        def onInputDeviceRemoved(self, p0: int) -> None: ...

from typing import Any, ClassVar, overload
from android.os.Parcel import Parcel

class HostUsiVersion:
    CREATOR: ClassVar[Any]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    def equals(self, p0: Any) -> bool: ...
    def toString(self) -> str: ...
    def hashCode(self) -> int: ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
    def getMinorVersion(self) -> int: ...
    def getMajorVersion(self) -> int: ...

