from typing import Any, ClassVar, overload
from android.os.Parcel import Parcel

class SupplicantState:
    ASSOCIATED: ClassVar["SupplicantState"]
    ASSOCIATING: ClassVar["SupplicantState"]
    AUTHENTICATING: ClassVar["SupplicantState"]
    COMPLETED: ClassVar["SupplicantState"]
    DISCONNECTED: ClassVar["SupplicantState"]
    DORMANT: ClassVar["SupplicantState"]
    FOUR_WAY_HANDSHAKE: ClassVar["SupplicantState"]
    GROUP_HANDSHAKE: ClassVar["SupplicantState"]
    INACTIVE: ClassVar["SupplicantState"]
    INTERFACE_DISABLED: ClassVar["SupplicantState"]
    INVALID: ClassVar["SupplicantState"]
    SCANNING: ClassVar["SupplicantState"]
    UNINITIALIZED: ClassVar["SupplicantState"]
    ASSOCIATED: ClassVar["SupplicantState"]
    ASSOCIATING: ClassVar["SupplicantState"]
    AUTHENTICATING: ClassVar["SupplicantState"]
    COMPLETED: ClassVar["SupplicantState"]
    DISCONNECTED: ClassVar["SupplicantState"]
    DORMANT: ClassVar["SupplicantState"]
    FOUR_WAY_HANDSHAKE: ClassVar["SupplicantState"]
    GROUP_HANDSHAKE: ClassVar["SupplicantState"]
    INACTIVE: ClassVar["SupplicantState"]
    INTERFACE_DISABLED: ClassVar["SupplicantState"]
    INVALID: ClassVar["SupplicantState"]
    SCANNING: ClassVar["SupplicantState"]
    UNINITIALIZED: ClassVar["SupplicantState"]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    @staticmethod
    def isValidState(p0: "SupplicantState") -> bool: ...
    @staticmethod
    def values() -> Any: ...
    @staticmethod
    def valueOf(p0: str) -> "SupplicantState": ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...

from typing import Any, ClassVar, overload
from android.net.IpConfiguration import IpConfiguration
from android.net.MacAddress import MacAddress
from android.net.ProxyInfo import ProxyInfo
from android.net.wifi.WifiEnterpriseConfig import WifiEnterpriseConfig
from android.os.Parcel import Parcel
from java.util.BitSet import BitSet

class WifiConfiguration:
    RANDOMIZATION_AUTO: ClassVar[int]
    RANDOMIZATION_NONE: ClassVar[int]
    RANDOMIZATION_NON_PERSISTENT: ClassVar[int]
    RANDOMIZATION_PERSISTENT: ClassVar[int]
    SECURITY_TYPE_DPP: ClassVar[int]
    SECURITY_TYPE_EAP: ClassVar[int]
    SECURITY_TYPE_EAP_SUITE_B: ClassVar[int]
    SECURITY_TYPE_EAP_WPA3_ENTERPRISE: ClassVar[int]
    SECURITY_TYPE_EAP_WPA3_ENTERPRISE_192_BIT: ClassVar[int]
    SECURITY_TYPE_OPEN: ClassVar[int]
    SECURITY_TYPE_OWE: ClassVar[int]
    SECURITY_TYPE_PSK: ClassVar[int]
    SECURITY_TYPE_SAE: ClassVar[int]
    SECURITY_TYPE_WAPI_CERT: ClassVar[int]
    SECURITY_TYPE_WAPI_PSK: ClassVar[int]
    SECURITY_TYPE_WEP: ClassVar[int]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    BSSID: str
    FQDN: str
    SSID: str
    allowedAuthAlgorithms: BitSet
    allowedGroupCiphers: BitSet
    allowedGroupManagementCiphers: BitSet
    allowedKeyManagement: BitSet
    allowedPairwiseCiphers: BitSet
    allowedProtocols: BitSet
    allowedSuiteBCiphers: BitSet
    enterpriseConfig: WifiEnterpriseConfig
    hiddenSSID: bool
    isHomeProviderNetwork: bool
    networkId: int
    preSharedKey: str
    priority: int
    providerFriendlyName: str
    roamingConsortiumIds: Any
    status: int
    wepKeys: Any
    wepTxKeyIndex: int
    @overload
    def __init__(self, p0: "WifiConfiguration") -> None: ...
    @overload
    def __init__(self) -> None: ...
    def getHttpProxy(self) -> ProxyInfo: ...
    def setHttpProxy(self, p0: ProxyInfo) -> None: ...
    def getMacRandomizationSetting(self) -> int: ...
    def getRandomizedMacAddress(self) -> MacAddress: ...
    def isDppConfigurator(self) -> bool: ...
    def isPasspoint(self) -> bool: ...
    def setIpConfiguration(self, p0: IpConfiguration) -> None: ...
    def setMacRandomizationSetting(self, p0: int) -> None: ...
    def setSecurityParams(self, p0: int) -> None: ...
    def toString(self) -> str: ...
    def getKey(self) -> str: ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...

    class Status:
        CURRENT: ClassVar[int]
        DISABLED: ClassVar[int]
        ENABLED: ClassVar[int]
        strings: ClassVar[Any]

    class Protocol:
        RSN: ClassVar[int]
        WAPI: ClassVar[int]
        WPA: ClassVar[int]
        strings: ClassVar[Any]
        varName: ClassVar[str]

    class PairwiseCipher:
        CCMP: ClassVar[int]
        GCMP_128: ClassVar[int]
        GCMP_256: ClassVar[int]
        NONE: ClassVar[int]
        SMS4: ClassVar[int]
        TKIP: ClassVar[int]
        strings: ClassVar[Any]
        varName: ClassVar[str]

    class KeyMgmt:
        DPP: ClassVar[int]
        FILS_SHA256: ClassVar[int]
        FILS_SHA384: ClassVar[int]
        FT_EAP: ClassVar[int]
        FT_PSK: ClassVar[int]
        IEEE8021X: ClassVar[int]
        NONE: ClassVar[int]
        OSEN: ClassVar[int]
        OWE: ClassVar[int]
        SAE: ClassVar[int]
        SUITE_B_192: ClassVar[int]
        WAPI_CERT: ClassVar[int]
        WAPI_PSK: ClassVar[int]
        WPA2_PSK: ClassVar[int]
        WPA_EAP: ClassVar[int]
        WPA_EAP_SHA256: ClassVar[int]
        WPA_PSK: ClassVar[int]
        WPA_PSK_SHA256: ClassVar[int]
        strings: ClassVar[Any]
        varName: ClassVar[str]

    class GroupMgmtCipher:
        BIP_CMAC_256: ClassVar[int]
        BIP_GMAC_128: ClassVar[int]
        BIP_GMAC_256: ClassVar[int]

    class GroupCipher:
        CCMP: ClassVar[int]
        GCMP_128: ClassVar[int]
        GCMP_256: ClassVar[int]
        SMS4: ClassVar[int]
        TKIP: ClassVar[int]
        WEP104: ClassVar[int]
        WEP40: ClassVar[int]
        strings: ClassVar[Any]
        varName: ClassVar[str]

    class AuthAlgorithm:
        LEAP: ClassVar[int]
        OPEN: ClassVar[int]
        SAE: ClassVar[int]
        SHARED: ClassVar[int]
        strings: ClassVar[Any]
        varName: ClassVar[str]

from typing import Any, ClassVar, overload
from android.net.MacAddress import MacAddress
from android.net.wifi.WifiEnterpriseConfig import WifiEnterpriseConfig
from android.net.wifi.WifiSsid import WifiSsid
from android.net.wifi.hotspot2.PasspointConfiguration import PasspointConfiguration
from android.os.Parcel import Parcel
from android.os.ParcelUuid import ParcelUuid

class WifiNetworkSuggestion:
    CREATOR: ClassVar[Any]
    RANDOMIZATION_NON_PERSISTENT: ClassVar[int]
    RANDOMIZATION_PERSISTENT: ClassVar[int]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    def getSubscriptionId(self) -> int: ...
    def getWifiSsid(self) -> WifiSsid: ...
    def getBssid(self) -> MacAddress: ...
    def getPassphrase(self) -> str: ...
    def getSsid(self) -> str: ...
    def isHiddenSsid(self) -> bool: ...
    def isUntrusted(self) -> bool: ...
    def isWifi7Enabled(self) -> bool: ...
    def getEnterpriseConfig(self) -> WifiEnterpriseConfig: ...
    def getPasspointConfig(self) -> PasspointConfiguration: ...
    def getPriorityGroup(self) -> int: ...
    def isEnhancedOpen(self) -> bool: ...
    def getSubscriptionGroup(self) -> ParcelUuid: ...
    def isAppInteractionRequired(self) -> bool: ...
    def isCarrierMerged(self) -> bool: ...
    def isCredentialSharedWithUser(self) -> bool: ...
    def isInitialAutojoinEnabled(self) -> bool: ...
    def isUserInteractionRequired(self) -> bool: ...
    def getMacRandomizationSetting(self) -> int: ...
    def isMetered(self) -> bool: ...
    def equals(self, p0: Any) -> bool: ...
    def toString(self) -> str: ...
    def hashCode(self) -> int: ...
    def getPriority(self) -> int: ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
    def isRestricted(self) -> bool: ...

    class Builder:
        def __init__(self) -> None: ...
        def setRestricted(self, p0: bool) -> Any: ...
        def setBssid(self, p0: MacAddress) -> Any: ...
        def setSubscriptionId(self, p0: int) -> Any: ...
        def setMacRandomizationSetting(self, p0: int) -> Any: ...
        def setCarrierMerged(self, p0: bool) -> Any: ...
        def setCredentialSharedWithUser(self, p0: bool) -> Any: ...
        def setIsAppInteractionRequired(self, p0: bool) -> Any: ...
        def setIsEnhancedOpen(self, p0: bool) -> Any: ...
        def setIsHiddenSsid(self, p0: bool) -> Any: ...
        def setIsInitialAutojoinEnabled(self, p0: bool) -> Any: ...
        def setIsMetered(self, p0: bool) -> Any: ...
        def setIsUserInteractionRequired(self, p0: bool) -> Any: ...
        def setIsWpa3SaeH2eOnlyModeEnabled(self, p0: bool) -> Any: ...
        def setPasspointConfig(self, p0: PasspointConfiguration) -> Any: ...
        def setPriorityGroup(self, p0: int) -> Any: ...
        def setSsid(self, p0: str) -> Any: ...
        def setSubscriptionGroup(self, p0: ParcelUuid) -> Any: ...
        def setUntrusted(self, p0: bool) -> Any: ...
        def setWapiEnterpriseConfig(self, p0: WifiEnterpriseConfig) -> Any: ...
        def setWapiPassphrase(self, p0: str) -> Any: ...
        def setWifi7Enabled(self, p0: bool) -> Any: ...
        def setWifiSsid(self, p0: WifiSsid) -> Any: ...
        def setWpa2EnterpriseConfig(self, p0: WifiEnterpriseConfig) -> Any: ...
        def setWpa2Passphrase(self, p0: str) -> Any: ...
        def setWpa3Enterprise192BitModeConfig(self, p0: WifiEnterpriseConfig) -> Any: ...
        def setWpa3EnterpriseConfig(self, p0: WifiEnterpriseConfig) -> Any: ...
        def setWpa3EnterpriseStandardModeConfig(self, p0: WifiEnterpriseConfig) -> Any: ...
        def setWpa3Passphrase(self, p0: str) -> Any: ...
        def build(self) -> "WifiNetworkSuggestion": ...
        def setPriority(self, p0: int) -> Any: ...

from typing import Any, ClassVar, overload
from android.net.MacAddress import MacAddress
from android.net.NetworkSpecifier import NetworkSpecifier
from android.net.wifi.WifiEnterpriseConfig import WifiEnterpriseConfig
from android.os.Parcel import Parcel
from android.os.PatternMatcher import PatternMatcher

class WifiNetworkSpecifier:
    CREATOR: ClassVar[Any]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    def canBeSatisfiedBy(self, p0: NetworkSpecifier) -> bool: ...
    def getBand(self) -> int: ...
    def getPreferredChannelFrequenciesMhz(self) -> Any: ...
    def redact(self) -> NetworkSpecifier: ...
    def equals(self, p0: Any) -> bool: ...
    def toString(self) -> str: ...
    def hashCode(self) -> int: ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...

    class Builder:
        def __init__(self) -> None: ...
        def setBssid(self, p0: MacAddress) -> Any: ...
        def setBand(self, p0: int) -> Any: ...
        def setIsEnhancedOpen(self, p0: bool) -> Any: ...
        def setIsHiddenSsid(self, p0: bool) -> Any: ...
        def setSsid(self, p0: str) -> Any: ...
        def setWpa2EnterpriseConfig(self, p0: WifiEnterpriseConfig) -> Any: ...
        def setWpa2Passphrase(self, p0: str) -> Any: ...
        def setWpa3Enterprise192BitModeConfig(self, p0: WifiEnterpriseConfig) -> Any: ...
        def setWpa3EnterpriseConfig(self, p0: WifiEnterpriseConfig) -> Any: ...
        def setWpa3EnterpriseStandardModeConfig(self, p0: WifiEnterpriseConfig) -> Any: ...
        def setWpa3Passphrase(self, p0: str) -> Any: ...
        def build(self) -> "WifiNetworkSpecifier": ...
        def setBssidPattern(self, p0: MacAddress, p1: MacAddress) -> Any: ...
        def setPreferredChannelsFrequenciesMhz(self, p0: Any) -> Any: ...
        def setSsidPattern(self, p0: PatternMatcher) -> Any: ...

from typing import Any, ClassVar, overload
from android.os.Parcel import Parcel

class WpsInfo:
    CREATOR: ClassVar[Any]
    DISPLAY: ClassVar[int]
    INVALID: ClassVar[int]
    KEYPAD: ClassVar[int]
    LABEL: ClassVar[int]
    PBC: ClassVar[int]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    BSSID: str
    pin: str
    setup: int
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, p0: "WpsInfo") -> None: ...
    def toString(self) -> str: ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...

from typing import Any, ClassVar, overload
from android.net.MacAddress import MacAddress
from android.net.wifi.WifiSsid import WifiSsid
from android.os.Parcel import Parcel
from android.util.SparseIntArray import SparseIntArray

class SoftApConfiguration:
    BAND_2GHZ: ClassVar[int]
    BAND_5GHZ: ClassVar[int]
    BAND_60GHZ: ClassVar[int]
    BAND_6GHZ: ClassVar[int]
    CREATOR: ClassVar[Any]
    SECURITY_TYPE_OPEN: ClassVar[int]
    SECURITY_TYPE_WPA2_PSK: ClassVar[int]
    SECURITY_TYPE_WPA3_OWE: ClassVar[int]
    SECURITY_TYPE_WPA3_OWE_TRANSITION: ClassVar[int]
    SECURITY_TYPE_WPA3_SAE: ClassVar[int]
    SECURITY_TYPE_WPA3_SAE_TRANSITION: ClassVar[int]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    def getChannels(self) -> SparseIntArray: ...
    def getWifiSsid(self) -> WifiSsid: ...
    def getBssid(self) -> MacAddress: ...
    def getPassphrase(self) -> str: ...
    def getSecurityType(self) -> int: ...
    def getSsid(self) -> str: ...
    def isHiddenSsid(self) -> bool: ...
    def equals(self, p0: Any) -> bool: ...
    def toString(self) -> str: ...
    def hashCode(self) -> int: ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...

    class Builder:
        def __init__(self) -> None: ...
        def setChannels(self, p0: SparseIntArray) -> Any: ...
        def build(self) -> "SoftApConfiguration": ...

from typing import Any, ClassVar, overload
from android.os.Parcel import Parcel

class WifiSsid:
    CREATOR: ClassVar[Any]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    @staticmethod
    def fromBytes(p0: Any) -> "WifiSsid": ...
    def equals(self, p0: Any) -> bool: ...
    def toString(self) -> str: ...
    def hashCode(self) -> int: ...
    def getBytes(self) -> Any: ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...

from typing import Any, ClassVar, overload

class EasyConnectStatusCallback:
    EASY_CONNECT_EVENT_FAILURE_AUTHENTICATION: ClassVar[int]
    EASY_CONNECT_EVENT_FAILURE_BUSY: ClassVar[int]
    EASY_CONNECT_EVENT_FAILURE_CANNOT_FIND_NETWORK: ClassVar[int]
    EASY_CONNECT_EVENT_FAILURE_CONFIGURATION: ClassVar[int]
    EASY_CONNECT_EVENT_FAILURE_ENROLLEE_AUTHENTICATION: ClassVar[int]
    EASY_CONNECT_EVENT_FAILURE_ENROLLEE_FAILED_TO_SCAN_NETWORK_CHANNEL: ClassVar[int]
    EASY_CONNECT_EVENT_FAILURE_ENROLLEE_REJECTED_CONFIGURATION: ClassVar[int]
    EASY_CONNECT_EVENT_FAILURE_GENERIC: ClassVar[int]
    EASY_CONNECT_EVENT_FAILURE_INVALID_NETWORK: ClassVar[int]
    EASY_CONNECT_EVENT_FAILURE_INVALID_URI: ClassVar[int]
    EASY_CONNECT_EVENT_FAILURE_NOT_COMPATIBLE: ClassVar[int]
    EASY_CONNECT_EVENT_FAILURE_NOT_SUPPORTED: ClassVar[int]
    EASY_CONNECT_EVENT_FAILURE_TIMEOUT: ClassVar[int]
    EASY_CONNECT_EVENT_FAILURE_URI_GENERATION: ClassVar[int]

from typing import Any, ClassVar, overload
from android.os.Parcel import Parcel
from java.security.PrivateKey import PrivateKey
from java.security.cert.X509Certificate import X509Certificate

class WifiEnterpriseConfig:
    CREATOR: ClassVar[Any]
    EXTRA_WAPI_AS_CERTIFICATE_DATA: ClassVar[str]
    EXTRA_WAPI_AS_CERTIFICATE_NAME: ClassVar[str]
    EXTRA_WAPI_USER_CERTIFICATE_DATA: ClassVar[str]
    EXTRA_WAPI_USER_CERTIFICATE_NAME: ClassVar[str]
    TLS_V1_0: ClassVar[int]
    TLS_V1_1: ClassVar[int]
    TLS_V1_2: ClassVar[int]
    TLS_V1_3: ClassVar[int]
    WAPI_AS_CERTIFICATE: ClassVar[str]
    WAPI_USER_CERTIFICATE: ClassVar[str]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    @overload
    def __init__(self, p0: "WifiEnterpriseConfig") -> None: ...
    @overload
    def __init__(self) -> None: ...
    def getPassword(self) -> str: ...
    def setSubjectMatch(self, p0: str) -> None: ...
    def setPlmn(self, p0: str) -> None: ...
    def setRealm(self, p0: str) -> None: ...
    def toString(self) -> str: ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
    def setPassword(self, p0: str) -> None: ...
    def enableTrustOnFirstUse(self, p0: bool) -> None: ...
    def getAltSubjectMatch(self) -> str: ...
    def getAnonymousIdentity(self) -> str: ...
    def getCaCertificate(self) -> X509Certificate: ...
    def getCaCertificates(self) -> Any: ...
    def getClientCertificate(self) -> X509Certificate: ...
    def getClientCertificateChain(self) -> Any: ...
    def getClientKeyPairAlias(self) -> str: ...
    def getClientPrivateKey(self) -> PrivateKey: ...
    def getDecoratedIdentityPrefix(self) -> str: ...
    def getDomainSuffixMatch(self) -> str: ...
    def getEapMethod(self) -> int: ...
    def getIdentity(self) -> str: ...
    def getMinimumTlsVersion(self) -> int: ...
    def getPhase2Method(self) -> int: ...
    def getPlmn(self) -> str: ...
    def getRealm(self) -> str: ...
    def getSubjectMatch(self) -> str: ...
    def hasCaCertificate(self) -> bool: ...
    def isAuthenticationSimBased(self) -> bool: ...
    def isEapMethodServerCertUsed(self) -> bool: ...
    def isServerCertValidationEnabled(self) -> bool: ...
    def isTrustOnFirstUseEnabled(self) -> bool: ...
    def setAltSubjectMatch(self, p0: str) -> None: ...
    def setAnonymousIdentity(self, p0: str) -> None: ...
    def setCaCertificate(self, p0: X509Certificate) -> None: ...
    def setCaCertificates(self, p0: Any) -> None: ...
    def setClientKeyEntry(self, p0: PrivateKey, p1: X509Certificate) -> None: ...
    def setClientKeyEntryWithCertificateChain(self, p0: PrivateKey, p1: Any) -> None: ...
    def setClientKeyPairAlias(self, p0: str) -> None: ...
    def setDecoratedIdentityPrefix(self, p0: str) -> None: ...
    def setDomainSuffixMatch(self, p0: str) -> None: ...
    def setEapMethod(self, p0: int) -> None: ...
    def setIdentity(self, p0: str) -> None: ...
    def setMinimumTlsVersion(self, p0: int) -> None: ...
    def setPhase2Method(self, p0: int) -> None: ...

    class Phase2:
        AKA: ClassVar[int]
        AKA_PRIME: ClassVar[int]
        GTC: ClassVar[int]
        MSCHAP: ClassVar[int]
        MSCHAPV2: ClassVar[int]
        NONE: ClassVar[int]
        PAP: ClassVar[int]
        SIM: ClassVar[int]

    class Eap:
        AKA: ClassVar[int]
        AKA_PRIME: ClassVar[int]
        NONE: ClassVar[int]
        PEAP: ClassVar[int]
        PWD: ClassVar[int]
        SIM: ClassVar[int]
        TLS: ClassVar[int]
        TTLS: ClassVar[int]
        UNAUTH_TLS: ClassVar[int]
        WAPI_CERT: ClassVar[int]

from typing import Any, ClassVar, overload
from android.net.DhcpInfo import DhcpInfo
from android.net.wifi.BlockingOption import BlockingOption
from android.net.wifi.SoftApConfiguration import SoftApConfiguration
from android.net.wifi.WifiConfiguration import WifiConfiguration
from android.net.wifi.WifiInfo import WifiInfo
from android.net.wifi.WifiNetworkSpecifier import WifiNetworkSpecifier
from android.net.wifi.WifiNetworkSuggestion import WifiNetworkSuggestion
from android.net.wifi.WifiSsid import WifiSsid
from android.net.wifi.WpsInfo import WpsInfo
from android.net.wifi.hotspot2.PasspointConfiguration import PasspointConfiguration
from android.os.Handler import Handler
from android.os.Parcel import Parcel
from android.os.WorkSource import WorkSource
from java.net.InetAddress import InetAddress
from java.util.concurrent.Executor import Executor
from java.util.function.BiConsumer import BiConsumer
from java.util.function.Consumer import Consumer
from java.util.function.IntConsumer import IntConsumer

class WifiManager:
    ACTION_PICK_WIFI_NETWORK: ClassVar[str]
    ACTION_REMOVE_SUGGESTION_DISCONNECT: ClassVar[int]
    ACTION_REMOVE_SUGGESTION_LINGER: ClassVar[int]
    ACTION_REQUEST_SCAN_ALWAYS_AVAILABLE: ClassVar[str]
    ACTION_WIFI_NETWORK_SUGGESTION_POST_CONNECTION: ClassVar[str]
    ACTION_WIFI_SCAN_AVAILABILITY_CHANGED: ClassVar[str]
    CHANNEL_DATA_KEY_FREQUENCY_MHZ: ClassVar[str]
    CHANNEL_DATA_KEY_NUM_AP: ClassVar[str]
    ERROR_AUTHENTICATING: ClassVar[int]
    EXTRA_BSSID: ClassVar[str]
    EXTRA_NETWORK_INFO: ClassVar[str]
    EXTRA_NETWORK_SUGGESTION: ClassVar[str]
    EXTRA_NEW_RSSI: ClassVar[str]
    EXTRA_NEW_STATE: ClassVar[str]
    EXTRA_PREVIOUS_WIFI_STATE: ClassVar[str]
    EXTRA_RESULTS_UPDATED: ClassVar[str]
    EXTRA_SCAN_AVAILABLE: ClassVar[str]
    EXTRA_SUPPLICANT_CONNECTED: ClassVar[str]
    EXTRA_SUPPLICANT_ERROR: ClassVar[str]
    EXTRA_WIFI_INFO: ClassVar[str]
    EXTRA_WIFI_STATE: ClassVar[str]
    FLAG_SEND_DHCP_HOSTNAME_RESTRICTION_OPEN: ClassVar[int]
    FLAG_SEND_DHCP_HOSTNAME_RESTRICTION_SECURE: ClassVar[int]
    NETWORK_IDS_CHANGED_ACTION: ClassVar[str]
    NETWORK_STATE_CHANGED_ACTION: ClassVar[str]
    ROAMING_MODE_AGGRESSIVE: ClassVar[int]
    ROAMING_MODE_NONE: ClassVar[int]
    ROAMING_MODE_NORMAL: ClassVar[int]
    RSSI_CHANGED_ACTION: ClassVar[str]
    SCAN_RESULTS_AVAILABLE_ACTION: ClassVar[str]
    STATUS_LOCAL_ONLY_CONNECTION_FAILURE_ASSOCIATION: ClassVar[int]
    STATUS_LOCAL_ONLY_CONNECTION_FAILURE_AUTHENTICATION: ClassVar[int]
    STATUS_LOCAL_ONLY_CONNECTION_FAILURE_IP_PROVISIONING: ClassVar[int]
    STATUS_LOCAL_ONLY_CONNECTION_FAILURE_NOT_FOUND: ClassVar[int]
    STATUS_LOCAL_ONLY_CONNECTION_FAILURE_NO_RESPONSE: ClassVar[int]
    STATUS_LOCAL_ONLY_CONNECTION_FAILURE_UNKNOWN: ClassVar[int]
    STATUS_LOCAL_ONLY_CONNECTION_FAILURE_USER_REJECT: ClassVar[int]
    STATUS_NETWORK_SUGGESTIONS_ERROR_ADD_DUPLICATE: ClassVar[int]
    STATUS_NETWORK_SUGGESTIONS_ERROR_ADD_EXCEEDS_MAX_PER_APP: ClassVar[int]
    STATUS_NETWORK_SUGGESTIONS_ERROR_ADD_INVALID: ClassVar[int]
    STATUS_NETWORK_SUGGESTIONS_ERROR_ADD_NOT_ALLOWED: ClassVar[int]
    STATUS_NETWORK_SUGGESTIONS_ERROR_APP_DISALLOWED: ClassVar[int]
    STATUS_NETWORK_SUGGESTIONS_ERROR_INTERNAL: ClassVar[int]
    STATUS_NETWORK_SUGGESTIONS_ERROR_REMOVE_INVALID: ClassVar[int]
    STATUS_NETWORK_SUGGESTIONS_ERROR_RESTRICTED_BY_ADMIN: ClassVar[int]
    STATUS_NETWORK_SUGGESTIONS_SUCCESS: ClassVar[int]
    STATUS_SUGGESTION_APPROVAL_APPROVED_BY_CARRIER_PRIVILEGE: ClassVar[int]
    STATUS_SUGGESTION_APPROVAL_APPROVED_BY_USER: ClassVar[int]
    STATUS_SUGGESTION_APPROVAL_PENDING: ClassVar[int]
    STATUS_SUGGESTION_APPROVAL_REJECTED_BY_USER: ClassVar[int]
    STATUS_SUGGESTION_APPROVAL_UNKNOWN: ClassVar[int]
    STATUS_SUGGESTION_CONNECTION_FAILURE_ASSOCIATION: ClassVar[int]
    STATUS_SUGGESTION_CONNECTION_FAILURE_AUTHENTICATION: ClassVar[int]
    STATUS_SUGGESTION_CONNECTION_FAILURE_IP_PROVISIONING: ClassVar[int]
    STATUS_SUGGESTION_CONNECTION_FAILURE_UNKNOWN: ClassVar[int]
    SUPPLICANT_CONNECTION_CHANGE_ACTION: ClassVar[str]
    SUPPLICANT_STATE_CHANGED_ACTION: ClassVar[str]
    UNKNOWN_SSID: ClassVar[str]
    WIFI_INTERFACE_TYPE_AP: ClassVar[int]
    WIFI_INTERFACE_TYPE_AWARE: ClassVar[int]
    WIFI_INTERFACE_TYPE_DIRECT: ClassVar[int]
    WIFI_INTERFACE_TYPE_STA: ClassVar[int]
    WIFI_MODE_FULL: ClassVar[int]
    WIFI_MODE_FULL_HIGH_PERF: ClassVar[int]
    WIFI_MODE_FULL_LOW_LATENCY: ClassVar[int]
    WIFI_MODE_SCAN_ONLY: ClassVar[int]
    WIFI_MULTI_INTERNET_MODE_DBS_AP: ClassVar[int]
    WIFI_MULTI_INTERNET_MODE_DISABLED: ClassVar[int]
    WIFI_MULTI_INTERNET_MODE_MULTI_AP: ClassVar[int]
    WIFI_STATE_CHANGED_ACTION: ClassVar[str]
    WIFI_STATE_DISABLED: ClassVar[int]
    WIFI_STATE_DISABLING: ClassVar[int]
    WIFI_STATE_ENABLED: ClassVar[int]
    WIFI_STATE_ENABLING: ClassVar[int]
    WIFI_STATE_UNKNOWN: ClassVar[int]
    WPS_AUTH_FAILURE: ClassVar[int]
    WPS_OVERLAP_ERROR: ClassVar[int]
    WPS_TIMED_OUT: ClassVar[int]
    WPS_TKIP_ONLY_PROHIBITED: ClassVar[int]
    WPS_WEP_PROHIBITED: ClassVar[int]
    def addLocalOnlyConnectionFailureListener(self, p0: Executor, p1: Any) -> None: ...
    def addNetwork(self, p0: WifiConfiguration) -> int: ...
    def addNetworkPrivileged(self, p0: WifiConfiguration) -> Any: ...
    def addNetworkSuggestions(self, p0: list) -> int: ...
    def addOrUpdatePasspointConfiguration(self, p0: PasspointConfiguration) -> None: ...
    def addSuggestionConnectionStatusListener(self, p0: Executor, p1: Any) -> None: ...
    def addSuggestionUserApprovalStatusListener(self, p0: Executor, p1: Any) -> None: ...
    def addWifiStateChangedListener(self, p0: Executor, p1: Any) -> None: ...
    def allowAutojoinGlobal(self, p0: bool) -> None: ...
    @overload
    def calculateSignalLevel(self, p0: int) -> int: ...
    @overload
    @staticmethod
    def calculateSignalLevel(p0: int, p1: int) -> int: ...
    def cancelWps(self, p0: Any) -> None: ...
    @staticmethod
    def compareSignalLevel(p0: int, p1: int) -> int: ...
    def createMulticastLock(self, p0: str) -> Any: ...
    @overload
    def createWifiLock(self, p0: int, p1: str) -> Any: ...
    @overload
    def createWifiLock(self, p0: str) -> Any: ...
    def disableNetwork(self, p0: int) -> bool: ...
    def disallowCurrentSuggestedNetwork(self, p0: BlockingOption) -> None: ...
    def enableNetwork(self, p0: int, p1: bool) -> bool: ...
    def flushPasspointAnqpCache(self) -> None: ...
    def getAllowedChannels(self, p0: int, p1: int) -> list: ...
    def getCallerConfiguredNetworks(self) -> list: ...
    def getChannelData(self, p0: Executor, p1: Consumer) -> None: ...
    def getConfiguredNetworks(self) -> list: ...
    def getConnectionInfo(self) -> WifiInfo: ...
    def getDhcpInfo(self) -> DhcpInfo: ...
    def getMaxNumberOfChannelsPerNetworkSpecifierRequest(self) -> int: ...
    def getMaxNumberOfNetworkSuggestionsPerApp(self) -> int: ...
    def getMaxSignalLevel(self) -> int: ...
    def getMaxSupportedConcurrentTdlsSessions(self, p0: Executor, p1: Consumer) -> None: ...
    def getNetworkSuggestions(self) -> list: ...
    def getNumberOfEnabledTdlsSessions(self, p0: Executor, p1: Consumer) -> None: ...
    def getPasspointConfigurations(self) -> list: ...
    def getPerSsidRoamingModes(self, p0: Executor, p1: Consumer) -> None: ...
    def getScanResults(self) -> list: ...
    def getStaConcurrencyForMultiInternetMode(self) -> int: ...
    def getUsableChannels(self, p0: int, p1: int) -> list: ...
    def getWifiState(self) -> int: ...
    def is24GHzBandSupported(self) -> bool: ...
    def is5GHzBandSupported(self) -> bool: ...
    def is60GHzBandSupported(self) -> bool: ...
    def is6GHzBandSupported(self) -> bool: ...
    def isAggressiveRoamingModeSupported(self) -> bool: ...
    def isAutoWakeupEnabled(self) -> bool: ...
    def isBridgedApConcurrencySupported(self) -> bool: ...
    def isCarrierNetworkOffloadEnabled(self, p0: int, p1: bool) -> bool: ...
    def isD2dSupportedWhenInfraStaDisabled(self) -> bool: ...
    def isDecoratedIdentitySupported(self) -> bool: ...
    def isDeviceToApRttSupported(self) -> bool: ...
    def isDualBandSimultaneousSupported(self) -> bool: ...
    def isEasyConnectDppAkmSupported(self) -> bool: ...
    def isEasyConnectEnrolleeResponderModeSupported(self) -> bool: ...
    def isEasyConnectSupported(self) -> bool: ...
    def isEnhancedOpenSupported(self) -> bool: ...
    def isEnhancedPowerReportingSupported(self) -> bool: ...
    def isMakeBeforeBreakWifiSwitchingSupported(self) -> bool: ...
    def isP2pSupported(self) -> bool: ...
    def isPasspointTermsAndConditionsSupported(self) -> bool: ...
    def isPreferredNetworkOffloadSupported(self) -> bool: ...
    def isScanAlwaysAvailable(self) -> bool: ...
    def isScanThrottleEnabled(self) -> bool: ...
    def isStaApConcurrencySupported(self) -> bool: ...
    def isStaBridgedApConcurrencySupported(self) -> bool: ...
    def isStaConcurrencyForLocalOnlyConnectionsSupported(self) -> bool: ...
    def isStaConcurrencyForMultiInternetSupported(self) -> bool: ...
    def isTdlsOperationCurrentlyAvailable(self, p0: Executor, p1: Consumer) -> None: ...
    def isTdlsSupported(self) -> bool: ...
    def isTidToLinkMappingNegotiationSupported(self) -> bool: ...
    def isTlsMinimumVersionSupported(self) -> bool: ...
    def isTlsV13Supported(self) -> bool: ...
    def isTrustOnFirstUseSupported(self) -> bool: ...
    def isWapiSupported(self) -> bool: ...
    def isWepSupported(self) -> bool: ...
    def isWifiDisplayR2Supported(self) -> bool: ...
    def isWifiEnabled(self) -> bool: ...
    def isWifiPasspointEnabled(self) -> bool: ...
    def isWifiStandardSupported(self, p0: int) -> bool: ...
    def isWpa3SaeH2eSupported(self) -> bool: ...
    def isWpa3SaePublicKeySupported(self) -> bool: ...
    def isWpa3SaeSupported(self) -> bool: ...
    def isWpa3SuiteBSupported(self) -> bool: ...
    def isWpaPersonalSupported(self) -> bool: ...
    def pingSupplicant(self) -> bool: ...
    def queryAutojoinGlobal(self, p0: Executor, p1: Consumer) -> None: ...
    def querySendDhcpHostnameRestriction(self, p0: Executor, p1: IntConsumer) -> None: ...
    def reassociate(self) -> bool: ...
    def registerScanResultsCallback(self, p0: Executor, p1: Any) -> None: ...
    def registerSubsystemRestartTrackingCallback(self, p0: Executor, p1: Any) -> None: ...
    def removeLocalOnlyConnectionFailureListener(self, p0: Any) -> None: ...
    def removeNetwork(self, p0: int) -> bool: ...
    @overload
    def removeNetworkSuggestions(self, p0: list, p1: int) -> int: ...
    @overload
    def removeNetworkSuggestions(self, p0: list) -> int: ...
    def removeNonCallerConfiguredNetworks(self) -> bool: ...
    def removePasspointConfiguration(self, p0: str) -> None: ...
    def removePerSsidRoamingMode(self, p0: WifiSsid) -> None: ...
    def removeSuggestionConnectionStatusListener(self, p0: Any) -> None: ...
    def removeSuggestionUserApprovalStatusListener(self, p0: Any) -> None: ...
    def removeWifiStateChangedListener(self, p0: Any) -> None: ...
    def reportCreateInterfaceImpact(self, p0: int, p1: bool, p2: Executor, p3: BiConsumer) -> None: ...
    def saveConfiguration(self) -> bool: ...
    def setPerSsidRoamingMode(self, p0: WifiSsid, p1: int) -> None: ...
    def setSendDhcpHostnameRestriction(self, p0: int) -> None: ...
    @overload
    def setTdlsEnabled(self, p0: InetAddress, p1: bool, p2: Executor, p3: Consumer) -> None: ...
    @overload
    def setTdlsEnabled(self, p0: InetAddress, p1: bool) -> None: ...
    @overload
    def setTdlsEnabledWithMacAddress(self, p0: str, p1: bool) -> None: ...
    @overload
    def setTdlsEnabledWithMacAddress(self, p0: str, p1: bool, p2: Executor, p3: Consumer) -> None: ...
    def setWifiEnabled(self, p0: bool) -> bool: ...
    def startLocalOnlyHotspot(self, p0: Any, p1: Handler) -> None: ...
    def startLocalOnlyHotspotWithConfiguration(self, p0: SoftApConfiguration, p1: Executor, p2: Any) -> None: ...
    def startWps(self, p0: WpsInfo, p1: Any) -> None: ...
    def unregisterScanResultsCallback(self, p0: Any) -> None: ...
    def unregisterSubsystemRestartTrackingCallback(self, p0: Any) -> None: ...
    def updateNetwork(self, p0: WifiConfiguration) -> int: ...
    def validateSoftApConfiguration(self, p0: SoftApConfiguration) -> bool: ...
    def disconnect(self) -> bool: ...
    def startScan(self) -> bool: ...
    def reconnect(self) -> bool: ...

    class WpsCallback:
        def __init__(self) -> None: ...
        def onFailed(self, p0: int) -> None: ...
        def onSucceeded(self) -> None: ...
        def onStarted(self, p0: str) -> None: ...

    class WifiStateChangedListener:
        def onWifiStateChanged(self) -> None: ...

    class WifiLock:
        def setReferenceCounted(self, p0: bool) -> None: ...
        def isHeld(self) -> bool: ...
        def setWorkSource(self, p0: WorkSource) -> None: ...
        def release(self) -> None: ...
        def toString(self) -> str: ...
        def acquire(self) -> None: ...

    class SuggestionUserApprovalStatusListener:
        def onUserApprovalStatusChange(self, p0: int) -> None: ...

    class SuggestionConnectionStatusListener:
        def onConnectionStatus(self, p0: WifiNetworkSuggestion, p1: int) -> None: ...

    class SubsystemRestartTrackingCallback:
        def __init__(self) -> None: ...
        def onSubsystemRestarted(self) -> None: ...
        def onSubsystemRestarting(self) -> None: ...

    class ScanResultsCallback:
        def __init__(self) -> None: ...
        def onScanResultsAvailable(self) -> None: ...

    class MulticastLock:
        def setReferenceCounted(self, p0: bool) -> None: ...
        def isHeld(self) -> bool: ...
        def release(self) -> None: ...
        def toString(self) -> str: ...
        def acquire(self) -> None: ...

    class LocalOnlyHotspotReservation:
        def getSoftApConfiguration(self) -> SoftApConfiguration: ...
        def getWifiConfiguration(self) -> WifiConfiguration: ...
        def close(self) -> None: ...

    class LocalOnlyHotspotCallback:
        ERROR_GENERIC: ClassVar[int]
        ERROR_INCOMPATIBLE_MODE: ClassVar[int]
        ERROR_NO_CHANNEL: ClassVar[int]
        ERROR_TETHERING_DISALLOWED: ClassVar[int]
        def __init__(self) -> None: ...
        def onFailed(self, p0: int) -> None: ...
        def onStarted(self, p0: Any) -> None: ...
        def onStopped(self) -> None: ...

    class LocalOnlyConnectionFailureListener:
        def onConnectionFailed(self, p0: WifiNetworkSpecifier, p1: int) -> None: ...

    class InterfaceCreationImpact:
        def __init__(self, p0: int, p1: set) -> None: ...
        def getInterfaceType(self) -> int: ...
        def equals(self, p0: Any) -> bool: ...
        def hashCode(self) -> int: ...
        def getPackages(self) -> set: ...

    class AddNetworkResult:
        CREATOR: ClassVar[Any]
        STATUS_ADD_PASSPOINT_FAILURE: ClassVar[int]
        STATUS_ADD_WIFI_CONFIG_FAILURE: ClassVar[int]
        STATUS_FAILURE_UNKNOWN: ClassVar[int]
        STATUS_FAILURE_UPDATE_NETWORK_KEYS: ClassVar[int]
        STATUS_INVALID_CONFIGURATION: ClassVar[int]
        STATUS_INVALID_CONFIGURATION_ENTERPRISE: ClassVar[int]
        STATUS_NO_PERMISSION: ClassVar[int]
        STATUS_NO_PERMISSION_MODIFY_CONFIG: ClassVar[int]
        STATUS_NO_PERMISSION_MODIFY_MAC_RANDOMIZATION: ClassVar[int]
        STATUS_NO_PERMISSION_MODIFY_PROXY_SETTING: ClassVar[int]
        STATUS_SUCCESS: ClassVar[int]
        CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
        PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
        networkId: int
        statusCode: int
        def __init__(self, p0: int, p1: int) -> None: ...
        def describeContents(self) -> int: ...
        def writeToParcel(self, p0: Parcel, p1: int) -> None: ...

from typing import Any, ClassVar, overload
from android.net.MacAddress import MacAddress
from android.os.Parcel import Parcel

class MloLink:
    CREATOR: ClassVar[Any]
    INVALID_MLO_LINK_ID: ClassVar[int]
    MLO_LINK_STATE_ACTIVE: ClassVar[int]
    MLO_LINK_STATE_IDLE: ClassVar[int]
    MLO_LINK_STATE_INVALID: ClassVar[int]
    MLO_LINK_STATE_UNASSOCIATED: ClassVar[int]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    def __init__(self) -> None: ...
    def getApMacAddress(self) -> MacAddress: ...
    def getLinkId(self) -> int: ...
    def getStaMacAddress(self) -> MacAddress: ...
    def getRxLinkSpeedMbps(self) -> int: ...
    def getTxLinkSpeedMbps(self) -> int: ...
    def getBand(self) -> int: ...
    def equals(self, p0: Any) -> bool: ...
    def toString(self) -> str: ...
    def hashCode(self) -> int: ...
    def getState(self) -> int: ...
    def getChannel(self) -> int: ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
    def getRssi(self) -> int: ...

from typing import Any, ClassVar, overload
from android.net.MacAddress import MacAddress
from android.net.wifi.WifiSsid import WifiSsid
from android.os.Parcel import Parcel
from java.nio.ByteBuffer import ByteBuffer

class ScanResult:
    CHANNEL_WIDTH_160MHZ: ClassVar[int]
    CHANNEL_WIDTH_20MHZ: ClassVar[int]
    CHANNEL_WIDTH_320MHZ: ClassVar[int]
    CHANNEL_WIDTH_40MHZ: ClassVar[int]
    CHANNEL_WIDTH_80MHZ: ClassVar[int]
    CHANNEL_WIDTH_80MHZ_PLUS_MHZ: ClassVar[int]
    CREATOR: ClassVar[Any]
    PREAMBLE_EHT: ClassVar[int]
    PREAMBLE_HE: ClassVar[int]
    PREAMBLE_HT: ClassVar[int]
    PREAMBLE_LEGACY: ClassVar[int]
    PREAMBLE_VHT: ClassVar[int]
    UNSPECIFIED: ClassVar[int]
    WIFI_BAND_24_GHZ: ClassVar[int]
    WIFI_BAND_5_GHZ: ClassVar[int]
    WIFI_BAND_60_GHZ: ClassVar[int]
    WIFI_BAND_6_GHZ: ClassVar[int]
    WIFI_STANDARD_11AC: ClassVar[int]
    WIFI_STANDARD_11AD: ClassVar[int]
    WIFI_STANDARD_11AX: ClassVar[int]
    WIFI_STANDARD_11BE: ClassVar[int]
    WIFI_STANDARD_11N: ClassVar[int]
    WIFI_STANDARD_LEGACY: ClassVar[int]
    WIFI_STANDARD_UNKNOWN: ClassVar[int]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    BSSID: str
    SSID: str
    capabilities: str
    centerFreq0: int
    centerFreq1: int
    channelWidth: int
    frequency: int
    level: int
    operatorFriendlyName: str
    timestamp: int
    venueName: str
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, p0: "ScanResult") -> None: ...
    @staticmethod
    def convertChannelToFrequencyMhzIfSupported(p0: int, p1: int) -> int: ...
    @staticmethod
    def convertFrequencyMhzToChannelIfSupported(p0: int) -> int: ...
    def getAffiliatedMloLinks(self) -> list: ...
    def getApMldMacAddress(self) -> MacAddress: ...
    def getApMloLinkId(self) -> int: ...
    def getInformationElements(self) -> list: ...
    def getSecurityTypes(self) -> Any: ...
    def getWifiSsid(self) -> WifiSsid: ...
    def getWifiStandard(self) -> int: ...
    def is80211azNtbResponder(self) -> bool: ...
    def is80211mcResponder(self) -> bool: ...
    def isPasspointNetwork(self) -> bool: ...
    def isRangingFrameProtectionRequired(self) -> bool: ...
    def isSecureHeLtfSupported(self) -> bool: ...
    def isTwtResponder(self) -> bool: ...
    def toString(self) -> str: ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...

    class InformationElement:
        CREATOR: ClassVar[Any]
        CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
        PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
        @overload
        def __init__(self, p0: Any) -> None: ...
        @overload
        def __init__(self, p0: int, p1: int, p2: Any) -> None: ...
        def getIdExt(self) -> int: ...
        def equals(self, p0: Any) -> bool: ...
        def hashCode(self) -> int: ...
        def getBytes(self) -> ByteBuffer: ...
        def getId(self) -> int: ...
        def describeContents(self) -> int: ...
        def writeToParcel(self, p0: Parcel, p1: int) -> None: ...

from typing import Any, ClassVar, overload
from android.os.Parcel import Parcel

class BlockingOption:
    CREATOR: ClassVar[Any]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    def getBlockingTimeSeconds(self) -> int: ...
    def isBlockingBssidOnly(self) -> bool: ...
    def equals(self, p0: Any) -> bool: ...
    def toString(self) -> str: ...
    def hashCode(self) -> int: ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...

    class Builder:
        def __init__(self, p0: int) -> None: ...
        def setBlockingBssidOnly(self, p0: bool) -> Any: ...
        def build(self) -> "BlockingOption": ...

from typing import Any, ClassVar, overload
from android.net.MacAddress import MacAddress
from android.net.wifi.SupplicantState import SupplicantState
from android.os.Parcel import Parcel

class WifiInfo:
    FREQUENCY_UNITS: ClassVar[str]
    LINK_SPEED_UNITS: ClassVar[str]
    LINK_SPEED_UNKNOWN: ClassVar[int]
    SECURITY_TYPE_DPP: ClassVar[int]
    SECURITY_TYPE_EAP: ClassVar[int]
    SECURITY_TYPE_EAP_WPA3_ENTERPRISE: ClassVar[int]
    SECURITY_TYPE_EAP_WPA3_ENTERPRISE_192_BIT: ClassVar[int]
    SECURITY_TYPE_OPEN: ClassVar[int]
    SECURITY_TYPE_OSEN: ClassVar[int]
    SECURITY_TYPE_OWE: ClassVar[int]
    SECURITY_TYPE_PASSPOINT_R1_R2: ClassVar[int]
    SECURITY_TYPE_PASSPOINT_R3: ClassVar[int]
    SECURITY_TYPE_PSK: ClassVar[int]
    SECURITY_TYPE_SAE: ClassVar[int]
    SECURITY_TYPE_UNKNOWN: ClassVar[int]
    SECURITY_TYPE_WAPI_CERT: ClassVar[int]
    SECURITY_TYPE_WAPI_PSK: ClassVar[int]
    SECURITY_TYPE_WEP: ClassVar[int]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    def getSubscriptionId(self) -> int: ...
    def getMacAddress(self) -> str: ...
    def getAffiliatedMloLinks(self) -> list: ...
    def getApMldMacAddress(self) -> MacAddress: ...
    def getApMloLinkId(self) -> int: ...
    def getInformationElements(self) -> list: ...
    def getWifiStandard(self) -> int: ...
    def getApplicableRedactions(self) -> int: ...
    def getAssociatedMloLinks(self) -> list: ...
    def getBSSID(self) -> str: ...
    def getCurrentSecurityType(self) -> int: ...
    @staticmethod
    def getDetailedStateOf(p0: SupplicantState) -> Any: ...
    def getHiddenSSID(self) -> bool: ...
    def getLinkSpeed(self) -> int: ...
    def getMaxSupportedRxLinkSpeedMbps(self) -> int: ...
    def getMaxSupportedTxLinkSpeedMbps(self) -> int: ...
    def getPasspointFqdn(self) -> str: ...
    def getPasspointProviderFriendlyName(self) -> str: ...
    def getPasspointUniqueId(self) -> str: ...
    def getRxLinkSpeedMbps(self) -> int: ...
    def getSSID(self) -> str: ...
    def getSupplicantState(self) -> SupplicantState: ...
    def getTxLinkSpeedMbps(self) -> int: ...
    def makeCopy(self, p0: int) -> "WifiInfo": ...
    def getIpAddress(self) -> int: ...
    def getFrequency(self) -> int: ...
    def equals(self, p0: Any) -> bool: ...
    def toString(self) -> str: ...
    def hashCode(self) -> int: ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
    def getRssi(self) -> int: ...
    def getNetworkId(self) -> int: ...
    def isRestricted(self) -> bool: ...

    class Builder:
        def __init__(self) -> None: ...
        def setNetworkId(self, p0: int) -> Any: ...
        def setBssid(self, p0: str) -> Any: ...
        def setCurrentSecurityType(self, p0: int) -> Any: ...
        def setSubscriptionId(self, p0: int) -> Any: ...
        def setSsid(self, p0: Any) -> Any: ...
        def build(self) -> "WifiInfo": ...
        def setRssi(self, p0: int) -> Any: ...

from typing import Any, ClassVar, overload
from android.os.Parcel import Parcel

class WifiAvailableChannel:
    CREATOR: ClassVar[Any]
    OP_MODE_SAP: ClassVar[int]
    OP_MODE_STA: ClassVar[int]
    OP_MODE_TDLS: ClassVar[int]
    OP_MODE_WIFI_AWARE: ClassVar[int]
    OP_MODE_WIFI_DIRECT_CLI: ClassVar[int]
    OP_MODE_WIFI_DIRECT_GO: ClassVar[int]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    def __init__(self, p0: int, p1: int) -> None: ...
    def getFrequencyMhz(self) -> int: ...
    def getOperationalModes(self) -> int: ...
    def getChannelWidth(self) -> int: ...
    def equals(self, p0: Any) -> bool: ...
    def toString(self) -> str: ...
    def hashCode(self) -> int: ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...

