from typing import Any, ClassVar, overload
from java.security.AlgorithmParameters import AlgorithmParameters
from java.security.Key import Key
from java.security.Provider import Provider
from java.security.spec.PKCS8EncodedKeySpec import PKCS8EncodedKeySpec
from javax.crypto.Cipher import Cipher

class EncryptedPrivateKeyInfo:
    @overload
    def __init__(self, p0: AlgorithmParameters, p1: Any) -> None: ...
    @overload
    def __init__(self, p0: str, p1: Any) -> None: ...
    @overload
    def __init__(self, p0: Any) -> None: ...
    def getEncoded(self) -> Any: ...
    def getAlgName(self) -> str: ...
    def getAlgParameters(self) -> AlgorithmParameters: ...
    def getEncryptedData(self) -> Any: ...
    @overload
    def getKeySpec(self, p0: Key, p1: str) -> PKCS8EncodedKeySpec: ...
    @overload
    def getKeySpec(self, p0: Cipher) -> PKCS8EncodedKeySpec: ...
    @overload
    def getKeySpec(self, p0: Key) -> PKCS8EncodedKeySpec: ...
    @overload
    def getKeySpec(self, p0: Key, p1: Provider) -> PKCS8EncodedKeySpec: ...
