from typing import Any, ClassVar, overload
from android.icu.util.ULocale import ULocale
from java.util.Locale import Locale

class DateIntervalInfo:
    @overload
    def __init__(self, p0: Locale) -> None: ...
    @overload
    def __init__(self, p0: ULocale) -> None: ...
    def getDefaultOrder(self) -> bool: ...
    def getIntervalPattern(self, p0: str, p1: int) -> Any: ...
    def setIntervalPattern(self, p0: str, p1: int, p2: str) -> None: ...
    def getFallbackIntervalPattern(self) -> str: ...
    def setFallbackIntervalPattern(self, p0: str) -> None: ...
    @overload
    def cloneAsThawed(self) -> Any: ...
    @overload
    def cloneAsThawed(self) -> "DateIntervalInfo": ...
    def equals(self, p0: Any) -> bool: ...
    def hashCode(self) -> int: ...
    def clone(self) -> Any: ...
    def isFrozen(self) -> bool: ...
    @overload
    def freeze(self) -> Any: ...
    @overload
    def freeze(self) -> "DateIntervalInfo": ...

    class PatternInfo:
        def __init__(self, p0: str, p1: str, p2: bool) -> None: ...
        def getFirstPart(self) -> str: ...
        def firstDateInPtnIsLaterDate(self) -> bool: ...
        def getSecondPart(self) -> str: ...
        def equals(self, p0: Any) -> bool: ...
        def toString(self) -> str: ...
        def hashCode(self) -> int: ...
