from typing import Any, ClassVar, overload
from android.icu.text.NumberingSystem import NumberingSystem
from android.icu.util.Currency import Currency
from android.icu.util.ULocale import ULocale
from java.util.Locale import Locale

class DecimalFormatSymbols:
    CURRENCY_SPC_CURRENCY_MATCH: ClassVar[int]
    CURRENCY_SPC_INSERT: ClassVar[int]
    CURRENCY_SPC_SURROUNDING_MATCH: ClassVar[int]
    @overload
    def __init__(self, p0: Locale) -> None: ...
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, p0: ULocale) -> None: ...
    def getNaN(self) -> str: ...
    @staticmethod
    def getAvailableULocales() -> Any: ...
    @overload
    @staticmethod
    def forNumberingSystem(p0: Locale, p1: NumberingSystem) -> "DecimalFormatSymbols": ...
    @overload
    @staticmethod
    def forNumberingSystem(p0: ULocale, p1: NumberingSystem) -> "DecimalFormatSymbols": ...
    def setZeroDigit(self, p0: str) -> None: ...
    def getDigitStrings(self) -> Any: ...
    def setDigitStrings(self, p0: Any) -> None: ...
    def getSignificantDigit(self) -> str: ...
    def setSignificantDigit(self, p0: str) -> None: ...
    def setGroupingSeparator(self, p0: str) -> None: ...
    def getGroupingSeparatorString(self) -> str: ...
    def setGroupingSeparatorString(self, p0: str) -> None: ...
    def setDecimalSeparator(self, p0: str) -> None: ...
    def getDecimalSeparatorString(self) -> str: ...
    def setDecimalSeparatorString(self, p0: str) -> None: ...
    def getPerMill(self) -> str: ...
    def setPerMill(self, p0: str) -> None: ...
    def getPerMillString(self) -> str: ...
    def setPerMillString(self, p0: str) -> None: ...
    def getPercent(self) -> str: ...
    def setPercent(self, p0: str) -> None: ...
    def getPercentString(self) -> str: ...
    def setPercentString(self, p0: str) -> None: ...
    def getDigit(self) -> str: ...
    def setDigit(self, p0: str) -> None: ...
    def getPatternSeparator(self) -> str: ...
    def setPatternSeparator(self, p0: str) -> None: ...
    def getInfinity(self) -> str: ...
    def setInfinity(self, p0: str) -> None: ...
    def setNaN(self, p0: str) -> None: ...
    def getMinusSign(self) -> str: ...
    def setMinusSign(self, p0: str) -> None: ...
    def getMinusSignString(self) -> str: ...
    def setMinusSignString(self, p0: str) -> None: ...
    def getPlusSign(self) -> str: ...
    def setPlusSign(self, p0: str) -> None: ...
    def getPlusSignString(self) -> str: ...
    def setPlusSignString(self, p0: str) -> None: ...
    def getCurrencySymbol(self) -> str: ...
    def setCurrencySymbol(self, p0: str) -> None: ...
    def getInternationalCurrencySymbol(self) -> str: ...
    def setInternationalCurrencySymbol(self, p0: str) -> None: ...
    def getMonetaryDecimalSeparator(self) -> str: ...
    def setMonetaryDecimalSeparator(self, p0: str) -> None: ...
    def getMonetaryDecimalSeparatorString(self) -> str: ...
    def setMonetaryDecimalSeparatorString(self, p0: str) -> None: ...
    def getMonetaryGroupingSeparator(self) -> str: ...
    def setMonetaryGroupingSeparator(self, p0: str) -> None: ...
    def getMonetaryGroupingSeparatorString(self) -> str: ...
    def setMonetaryGroupingSeparatorString(self, p0: str) -> None: ...
    def getExponentMultiplicationSign(self) -> str: ...
    def setExponentMultiplicationSign(self, p0: str) -> None: ...
    def getExponentSeparator(self) -> str: ...
    def setExponentSeparator(self, p0: str) -> None: ...
    def getPadEscape(self) -> str: ...
    def setPadEscape(self, p0: str) -> None: ...
    def getPatternForCurrencySpacing(self, p0: int, p1: bool) -> str: ...
    def setPatternForCurrencySpacing(self, p0: int, p1: bool, p2: str) -> None: ...
    def getULocale(self) -> ULocale: ...
    def setCurrency(self, p0: Currency) -> None: ...
    def equals(self, p0: Any) -> bool: ...
    def hashCode(self) -> int: ...
    def clone(self) -> Any: ...
    @overload
    @staticmethod
    def getInstance() -> "DecimalFormatSymbols": ...
    @overload
    @staticmethod
    def getInstance(p0: Locale) -> "DecimalFormatSymbols": ...
    @overload
    @staticmethod
    def getInstance(p0: ULocale) -> "DecimalFormatSymbols": ...
    def getCurrency(self) -> Currency: ...
    @staticmethod
    def getAvailableLocales() -> Any: ...
    def getLocale(self) -> Locale: ...
    def getDigits(self) -> Any: ...
    def getZeroDigit(self) -> str: ...
    def getDecimalSeparator(self) -> str: ...
    def getGroupingSeparator(self) -> str: ...
