from typing import Any, ClassVar, overload

class Edits:
    def __init__(self) -> None: ...
    def addUnchanged(self, p0: int) -> None: ...
    def addReplace(self, p0: int, p1: int) -> None: ...
    def numberOfChanges(self) -> int: ...
    def getCoarseChangesIterator(self) -> Any: ...
    def getCoarseIterator(self) -> Any: ...
    def getFineChangesIterator(self) -> Any: ...
    def getFineIterator(self) -> Any: ...
    def lengthDelta(self) -> int: ...
    def hasChanges(self) -> bool: ...
    def mergeAndAppend(self, p0: "Edits", p1: "Edits") -> "Edits": ...
    def reset(self) -> None: ...

    class Iterator:
        def findSourceIndex(self, p0: int) -> bool: ...
        def findDestinationIndex(self, p0: int) -> bool: ...
        def destinationIndexFromSourceIndex(self, p0: int) -> int: ...
        def sourceIndexFromDestinationIndex(self, p0: int) -> int: ...
        def hasChange(self) -> bool: ...
        def replacementIndex(self) -> int: ...
        def destinationIndex(self) -> int: ...
        def toString(self) -> str: ...
        def next(self) -> bool: ...
        def newLength(self) -> int: ...
        def oldLength(self) -> int: ...
        def sourceIndex(self) -> int: ...
