from typing import Any, ClassVar, overload
from android.icu.text.ConstrainedFieldPosition import ConstrainedFieldPosition
from java.lang.Appendable import Appendable
from java.text.AttributedCharacterIterator import AttributedCharacterIterator

class FormattedValue:
    def nextPosition(self, p0: ConstrainedFieldPosition) -> bool: ...
    def toCharacterIterator(self) -> AttributedCharacterIterator: ...
    def toString(self) -> str: ...
    def appendTo(self, p0: Appendable) -> Appendable: ...
