# cython: language_level=3
# Generated by jni-wrap cython — do not edit by hand.
from jni_core._core cimport JavaObject
from jni_core.jni cimport (
    JNIEnv, jobject, jstring,
    jboolean, jbyte, jchar, jshort, jint, jlong, jfloat, jdouble,
)

cdef class ListFormatter(JavaObject):
    cdef jstring _format(self, JNIEnv* env, jobject p0) except? NULL
    cdef jstring _format_0(self, JNIEnv* env, jobject p0) except? NULL
    cdef jstring _format_1(self, JNIEnv* env, jobject p0) except? NULL
    @staticmethod
    cdef jobject _getInstance(JNIEnv* env, jobject p0) except? NULL
    @staticmethod
    cdef jobject _getInstance_0(JNIEnv* env, jobject p0) except? NULL
    @staticmethod
    cdef jobject _getInstance_1(JNIEnv* env, jobject p0, jobject p1, jobject p2) except? NULL
    @staticmethod
    cdef jobject _getInstance_2(JNIEnv* env, jobject p0) except? NULL
    @staticmethod
    cdef jobject _getInstance_3(JNIEnv* env, jobject p0, jobject p1, jobject p2) except? NULL
    @staticmethod
    cdef jobject _getInstance_4(JNIEnv* env) except? NULL
    cdef jstring _getPatternForNumItems(self, JNIEnv* env, jint p0) except? NULL
    cdef jstring _getPatternForNumItems_0(self, JNIEnv* env, jint p0) except? NULL
    cdef jobject _formatToValue(self, JNIEnv* env, jobject p0) except? NULL
    cdef jobject _formatToValue_0(self, JNIEnv* env, jobject p0) except? NULL
    cdef jobject _formatToValue_1(self, JNIEnv* env, jobject p0) except? NULL

cdef class Width(JavaObject):
    @staticmethod
    cdef jobject _values(JNIEnv* env) except? NULL
    @staticmethod
    cdef jobject _values_0(JNIEnv* env) except? NULL
    @staticmethod
    cdef jobject _valueOf(JNIEnv* env, jstring p0) except? NULL
    @staticmethod
    cdef jobject _valueOf_0(JNIEnv* env, jstring p0) except? NULL

cdef class Type(JavaObject):
    @staticmethod
    cdef jobject _values(JNIEnv* env) except? NULL
    @staticmethod
    cdef jobject _values_0(JNIEnv* env) except? NULL
    @staticmethod
    cdef jobject _valueOf(JNIEnv* env, jstring p0) except? NULL
    @staticmethod
    cdef jobject _valueOf_0(JNIEnv* env, jstring p0) except? NULL

cdef class FormattedList(JavaObject):
    cdef jboolean _nextPosition(self, JNIEnv* env, jobject p0) except *
    cdef jboolean _nextPosition_0(self, JNIEnv* env, jobject p0) except *
    cdef jobject _appendTo(self, JNIEnv* env, jobject p0) except? NULL
    cdef jobject _appendTo_0(self, JNIEnv* env, jobject p0) except? NULL
    cdef jobject _toCharacterIterator(self, JNIEnv* env) except? NULL
    cdef jobject _toCharacterIterator_0(self, JNIEnv* env) except? NULL
    cdef jint _length(self, JNIEnv* env) except *
    cdef jint _length_0(self, JNIEnv* env) except *
    cdef jstring _toString(self, JNIEnv* env) except? NULL
    cdef jstring _toString_0(self, JNIEnv* env) except? NULL
    cdef jchar _charAt(self, JNIEnv* env, jint p0) except *
    cdef jchar _charAt_0(self, JNIEnv* env, jint p0) except *
    cdef jstring _subSequence(self, JNIEnv* env, jint p0, jint p1) except? NULL
    cdef jstring _subSequence_0(self, JNIEnv* env, jint p0, jint p1) except? NULL
