from typing import Any, ClassVar, overload
from android.icu.text.NumberFormat import NumberFormat
from android.icu.util.Measure import Measure
from android.icu.util.MeasureUnit import MeasureUnit
from android.icu.util.ULocale import ULocale
from java.lang.StringBuffer import StringBuffer
from java.lang.StringBuilder import StringBuilder
from java.text.FieldPosition import FieldPosition
from java.text.ParsePosition import ParsePosition
from java.util.Locale import Locale

class MeasureFormat:
    def formatMeasurePerUnit(self, p0: Measure, p1: MeasureUnit, p2: StringBuilder, p3: FieldPosition) -> StringBuilder: ...
    @overload
    def formatMeasures(self, p0: StringBuilder, p1: FieldPosition, p2: Any) -> StringBuilder: ...
    @overload
    def formatMeasures(self, p0: Any) -> str: ...
    def getUnitDisplayName(self, p0: MeasureUnit) -> str: ...
    @overload
    @staticmethod
    def getCurrencyFormat() -> "MeasureFormat": ...
    @overload
    @staticmethod
    def getCurrencyFormat(p0: Locale) -> "MeasureFormat": ...
    @overload
    @staticmethod
    def getCurrencyFormat(p0: ULocale) -> "MeasureFormat": ...
    @overload
    def parseObject(self, p0: str, p1: ParsePosition) -> Any: ...
    @overload
    def parseObject(self, p0: str, p1: ParsePosition) -> Measure: ...
    def getNumberFormat(self) -> NumberFormat: ...
    def equals(self, p0: Any) -> bool: ...
    def hashCode(self) -> int: ...
    def format(self, p0: Any, p1: StringBuffer, p2: FieldPosition) -> StringBuffer: ...
    @overload
    @staticmethod
    def getInstance(p0: ULocale, p1: Any) -> "MeasureFormat": ...
    @overload
    @staticmethod
    def getInstance(p0: Locale, p1: Any) -> "MeasureFormat": ...
    @overload
    @staticmethod
    def getInstance(p0: ULocale, p1: Any, p2: NumberFormat) -> "MeasureFormat": ...
    @overload
    @staticmethod
    def getInstance(p0: Locale, p1: Any, p2: NumberFormat) -> "MeasureFormat": ...
    def getLocale(self) -> ULocale: ...
    def getWidth(self) -> Any: ...

    class FormatWidth:
        WIDE: ClassVar["FormatWidth"]
        SHORT: ClassVar["FormatWidth"]
        NARROW: ClassVar["FormatWidth"]
        NUMERIC: ClassVar["FormatWidth"]
        WIDE: ClassVar[Any]
        SHORT: ClassVar[Any]
        NARROW: ClassVar[Any]
        NUMERIC: ClassVar[Any]
        @staticmethod
        def values() -> Any: ...
        @staticmethod
        def valueOf(p0: str) -> Any: ...
