from typing import Any, ClassVar, overload
from java.lang.StringBuffer import StringBuffer
from java.text.FieldPosition import FieldPosition
from java.text.ParsePosition import ParsePosition

class SelectFormat:
    def __init__(self, p0: str) -> None: ...
    def applyPattern(self, p0: str) -> None: ...
    def parseObject(self, p0: str, p1: ParsePosition) -> Any: ...
    def equals(self, p0: Any) -> bool: ...
    def toString(self) -> str: ...
    def hashCode(self) -> int: ...
    @overload
    def format(self, p0: Any, p1: StringBuffer, p2: FieldPosition) -> StringBuffer: ...
    @overload
    def format(self, p0: str) -> str: ...
    def toPattern(self) -> str: ...
