from typing import Any, ClassVar, overload
from android.icu.text.BreakIterator import BreakIterator
from android.icu.text.RuleBasedCollator import RuleBasedCollator
from android.icu.util.ULocale import ULocale
from java.text.CharacterIterator import CharacterIterator
from java.util.Locale import Locale

class StringSearch:
    DONE: ClassVar[int]
    @overload
    def __init__(self, p0: str, p1: CharacterIterator, p2: RuleBasedCollator) -> None: ...
    @overload
    def __init__(self, p0: str, p1: CharacterIterator, p2: RuleBasedCollator, p3: BreakIterator) -> None: ...
    @overload
    def __init__(self, p0: str, p1: CharacterIterator, p2: Locale) -> None: ...
    @overload
    def __init__(self, p0: str, p1: str) -> None: ...
    @overload
    def __init__(self, p0: str, p1: CharacterIterator, p2: ULocale) -> None: ...
    def getPattern(self) -> str: ...
    def getCollator(self) -> RuleBasedCollator: ...
    def setCollator(self, p0: RuleBasedCollator) -> None: ...
    def setPattern(self, p0: str) -> None: ...
    def isCanonical(self) -> bool: ...
    def setCanonical(self, p0: bool) -> None: ...
    def reset(self) -> None: ...
    def getIndex(self) -> int: ...
    def setTarget(self, p0: CharacterIterator) -> None: ...
    def setIndex(self, p0: int) -> None: ...
