from typing import Any, ClassVar, overload
from android.icu.text.Replaceable import Replaceable
from java.lang.StringBuffer import StringBuffer
from java.text.CharacterIterator import CharacterIterator

class UCharacterIterator:
    DONE: ClassVar[int]
    def currentCodePoint(self) -> int: ...
    def getCharacterIterator(self) -> CharacterIterator: ...
    def setToLimit(self) -> None: ...
    def nextCodePoint(self) -> int: ...
    def previousCodePoint(self) -> int: ...
    def setToStart(self) -> None: ...
    def moveIndex(self, p0: int) -> int: ...
    def moveCodePointIndex(self, p0: int) -> int: ...
    def clone(self) -> Any: ...
    def getLength(self) -> int: ...
    def next(self) -> int: ...
    @overload
    @staticmethod
    def getInstance(p0: StringBuffer) -> "UCharacterIterator": ...
    @overload
    @staticmethod
    def getInstance(p0: Any, p1: int, p2: int) -> "UCharacterIterator": ...
    @overload
    @staticmethod
    def getInstance(p0: str) -> "UCharacterIterator": ...
    @overload
    @staticmethod
    def getInstance(p0: Replaceable) -> "UCharacterIterator": ...
    @overload
    @staticmethod
    def getInstance(p0: Any) -> "UCharacterIterator": ...
    @overload
    @staticmethod
    def getInstance(p0: CharacterIterator) -> "UCharacterIterator": ...
    def current(self) -> int: ...
    def previous(self) -> int: ...
    def getIndex(self) -> int: ...
    @overload
    def getText(self) -> str: ...
    @overload
    def getText(self, p0: Any) -> int: ...
    @overload
    def getText(self, p0: Any, p1: int) -> int: ...
    def setIndex(self, p0: int) -> None: ...
