from typing import Any, ClassVar, overload
from android.icu.text.Replaceable import Replaceable
from android.icu.text.UnicodeSet import UnicodeSet

class UnicodeMatcher:
    ETHER: ClassVar[str]
    U_MATCH: ClassVar[int]
    U_MISMATCH: ClassVar[int]
    U_PARTIAL_MATCH: ClassVar[int]
    def matches(self, p0: Replaceable, p1: Any, p2: int, p3: bool) -> int: ...
    def toPattern(self, p0: bool) -> str: ...
    def matchesIndexValue(self, p0: int) -> bool: ...
    def addMatchSetTo(self, p0: UnicodeSet) -> None: ...
