from typing import Any, ClassVar, overload
from android.content.Context import Context
from android.net.IpSecAlgorithm import IpSecAlgorithm
from android.os.OutcomeReceiver import OutcomeReceiver
from java.net.InetAddress import InetAddress
from java.util.concurrent.Executor import Executor

class IpSecTransform:
    def requestIpSecTransformState(self, p0: Executor, p1: OutcomeReceiver) -> None: ...
    def equals(self, p0: Any) -> bool: ...
    def toString(self) -> str: ...
    def close(self) -> None: ...

    class Builder:
        def __init__(self, p0: Context) -> None: ...
        def setAuthentication(self, p0: IpSecAlgorithm) -> Any: ...
        def setEncryption(self, p0: IpSecAlgorithm) -> Any: ...
        def buildTransportModeTransform(self, p0: InetAddress, p1: Any) -> "IpSecTransform": ...
        def setAuthenticatedEncryption(self, p0: IpSecAlgorithm) -> Any: ...
        def setIpv4Encapsulation(self, p0: Any, p1: int) -> Any: ...
