from typing import Any, ClassVar, overload

class MailTo:
    MAILTO_SCHEME: ClassVar[str]
    def getHeaders(self) -> dict: ...
    def getSubject(self) -> str: ...
    def getTo(self) -> str: ...
    @staticmethod
    def isMailTo(p0: str) -> bool: ...
    def getCc(self) -> str: ...
    def getBody(self) -> str: ...
    def toString(self) -> str: ...
    @staticmethod
    def parse(p0: str) -> "MailTo": ...
