from typing import Any, ClassVar, overload
from android.net.NetworkCapabilities import NetworkCapabilities
from android.net.NetworkSpecifier import NetworkSpecifier
from android.os.Parcel import Parcel

class NetworkRequest:
    CREATOR: ClassVar[Any]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    def getNetworkSpecifier(self) -> NetworkSpecifier: ...
    def getSubscriptionIds(self) -> set: ...
    def hasCapability(self, p0: int) -> bool: ...
    def hasTransport(self, p0: int) -> bool: ...
    def canBeSatisfiedBy(self, p0: NetworkCapabilities) -> bool: ...
    def getTransportTypes(self) -> Any: ...
    def equals(self, p0: Any) -> bool: ...
    def toString(self) -> str: ...
    def hashCode(self) -> int: ...
    def getCapabilities(self) -> Any: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
    def describeContents(self) -> int: ...

    class Builder:
        @overload
        def __init__(self) -> None: ...
        @overload
        def __init__(self, p0: "NetworkRequest") -> None: ...
        def setSubscriptionIds(self, p0: set) -> Any: ...
        def removeCapability(self, p0: int) -> Any: ...
        def addCapability(self, p0: int) -> Any: ...
        def addTransportType(self, p0: int) -> Any: ...
        def clearCapabilities(self) -> Any: ...
        def removeTransportType(self, p0: int) -> Any: ...
        def setIncludeOtherUidNetworks(self, p0: bool) -> Any: ...
        @overload
        def setNetworkSpecifier(self, p0: str) -> Any: ...
        @overload
        def setNetworkSpecifier(self, p0: NetworkSpecifier) -> Any: ...
        def build(self) -> "NetworkRequest": ...
