from typing import Any, ClassVar, overload
from android.content.Context import Context

class AudioGroup:
    MODE_ECHO_SUPPRESSION: ClassVar[int]
    MODE_MUTED: ClassVar[int]
    MODE_NORMAL: ClassVar[int]
    MODE_ON_HOLD: ClassVar[int]
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, p0: Context) -> None: ...
    def getStreams(self) -> Any: ...
    def sendDtmf(self, p0: int) -> None: ...
    def clear(self) -> None: ...
    def getMode(self) -> int: ...
    def setMode(self, p0: int) -> None: ...

from typing import Any, ClassVar, overload

class AudioCodec:
    AMR: ClassVar["AudioCodec"]
    GSM: ClassVar["AudioCodec"]
    GSM_EFR: ClassVar["AudioCodec"]
    PCMA: ClassVar["AudioCodec"]
    PCMU: ClassVar["AudioCodec"]
    fmtp: str
    rtpmap: str
    type: int
    @staticmethod
    def getCodec(p0: int, p1: str, p2: str) -> "AudioCodec": ...
    @staticmethod
    def getCodecs() -> Any: ...

from typing import Any, ClassVar, overload
from java.net.InetAddress import InetAddress

class RtpStream:
    MODE_NORMAL: ClassVar[int]
    MODE_RECEIVE_ONLY: ClassVar[int]
    MODE_SEND_ONLY: ClassVar[int]
    def associate(self, p0: InetAddress, p1: int) -> None: ...
    def isBusy(self) -> bool: ...
    def getRemoteAddress(self) -> InetAddress: ...
    def getRemotePort(self) -> int: ...
    def getMode(self) -> int: ...
    def setMode(self, p0: int) -> None: ...
    def release(self) -> None: ...
    def getLocalAddress(self) -> InetAddress: ...
    def getLocalPort(self) -> int: ...

from typing import Any, ClassVar, overload
from android.net.rtp.AudioCodec import AudioCodec
from android.net.rtp.AudioGroup import AudioGroup
from java.net.InetAddress import InetAddress

class AudioStream:
    MODE_NORMAL: ClassVar[int]
    MODE_RECEIVE_ONLY: ClassVar[int]
    MODE_SEND_ONLY: ClassVar[int]
    def __init__(self, p0: InetAddress) -> None: ...
    def isBusy(self) -> bool: ...
    def getCodec(self) -> AudioCodec: ...
    def getDtmfType(self) -> int: ...
    def setCodec(self, p0: AudioCodec) -> None: ...
    def setDtmfType(self, p0: int) -> None: ...
    def join(self, p0: AudioGroup) -> None: ...
    def getGroup(self) -> AudioGroup: ...

