from typing import Any, ClassVar, overload
from android.os.Parcel import Parcel
from android.ranging.oob.DeviceHandle import DeviceHandle
from android.util.Range import Range
from java.time.Duration import Duration

class OobInitiatorRangingConfig:
    CREATOR: ClassVar[Any]
    RANGING_MODE_AUTO: ClassVar[int]
    RANGING_MODE_FUSED: ClassVar[int]
    RANGING_MODE_HIGH_ACCURACY: ClassVar[int]
    RANGING_MODE_HIGH_ACCURACY_PREFERRED: ClassVar[int]
    SECURITY_LEVEL_BASIC: ClassVar[int]
    SECURITY_LEVEL_SECURE: ClassVar[int]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    RANGING_SESSION_OOB: ClassVar[int]
    RANGING_SESSION_RAW: ClassVar[int]
    def toString(self) -> str: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
    def describeContents(self) -> int: ...
    def getSecurityLevel(self) -> int: ...
    def getDeviceHandles(self) -> list: ...
    def getRangingMode(self) -> int: ...
    def getFastestRangingInterval(self) -> Duration: ...
    def getRangingIntervalRange(self) -> Range: ...
    def getSlowestRangingInterval(self) -> Duration: ...

    class Builder:
        def __init__(self) -> None: ...
        def build(self) -> "OobInitiatorRangingConfig": ...
        def addDeviceHandles(self, p0: list) -> Any: ...
        def setFastestRangingInterval(self, p0: Duration) -> Any: ...
        def setRangingMode(self, p0: int) -> Any: ...
        def setSlowestRangingInterval(self, p0: Duration) -> Any: ...
        def addDeviceHandle(self, p0: DeviceHandle) -> Any: ...
        def setSecurityLevel(self, p0: int) -> Any: ...
