from typing import Any, ClassVar, overload
from android.os.Parcel import Parcel

class ChangedPackages:
    CREATOR: ClassVar[Any]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    def __init__(self, p0: int, p1: list) -> None: ...
    def getPackageNames(self) -> list: ...
    def getSequenceNumber(self) -> int: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
    def describeContents(self) -> int: ...
