from typing import Any, ClassVar, overload
from android.content.pm.PackageManager import PackageManager
from android.content.res.XmlResourceParser import XmlResourceParser
from android.graphics.drawable.Drawable import Drawable
from android.os.Bundle import Bundle
from android.os.Parcel import Parcel

class PackageItemInfo:
    banner: int
    icon: int
    isArchived: bool
    labelRes: int
    logo: int
    metaData: Bundle
    name: str
    nonLocalizedLabel: str
    packageName: str
    @overload
    def __init__(self, p0: "PackageItemInfo") -> None: ...
    @overload
    def __init__(self) -> None: ...
    def loadBanner(self, p0: PackageManager) -> Drawable: ...
    def loadIcon(self, p0: PackageManager) -> Drawable: ...
    def loadLabel(self, p0: PackageManager) -> str: ...
    def loadLogo(self, p0: PackageManager) -> Drawable: ...
    def loadUnbadgedIcon(self, p0: PackageManager) -> Drawable: ...
    def loadXmlMetaData(self, p0: PackageManager, p1: str) -> XmlResourceParser: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...

    class DisplayNameComparator:
        def __init__(self, p0: PackageManager) -> None: ...
        @overload
        def compare(self, p0: "PackageItemInfo", p1: "PackageItemInfo") -> int: ...
        @overload
        def compare(self, p0: Any, p1: Any) -> int: ...
