from typing import Any, ClassVar, overload
from android.app.PendingIntent import PendingIntent
from android.content.Intent import Intent
from android.content.IntentSender import IntentSender
from android.content.pm.ArchivedPackageInfo import ArchivedPackageInfo
from android.content.pm.VersionedPackage import VersionedPackage
from android.graphics.Bitmap import Bitmap
from android.icu.util.ULocale import ULocale
from android.net.Uri import Uri
from android.os.Handler import Handler
from android.os.Parcel import Parcel
from android.os.PersistableBundle import PersistableBundle
from android.os.UserHandle import UserHandle
from java.io.InputStream import InputStream
from java.io.OutputStream import OutputStream
from java.util.concurrent.Executor import Executor
from java.util.function.Consumer import Consumer

class PackageInstaller:
    ACTION_SESSION_COMMITTED: ClassVar[str]
    ACTION_SESSION_DETAILS: ClassVar[str]
    ACTION_SESSION_UPDATED: ClassVar[str]
    EXTRA_INSTALL_CONSTRAINTS: ClassVar[str]
    EXTRA_INSTALL_CONSTRAINTS_RESULT: ClassVar[str]
    EXTRA_OTHER_PACKAGE_NAME: ClassVar[str]
    EXTRA_PACKAGE_NAME: ClassVar[str]
    EXTRA_PRE_APPROVAL: ClassVar[str]
    EXTRA_SESSION: ClassVar[str]
    EXTRA_SESSION_ID: ClassVar[str]
    EXTRA_STATUS: ClassVar[str]
    EXTRA_STATUS_MESSAGE: ClassVar[str]
    EXTRA_STORAGE_PATH: ClassVar[str]
    EXTRA_UNARCHIVE_ALL_USERS: ClassVar[str]
    EXTRA_UNARCHIVE_ID: ClassVar[str]
    EXTRA_UNARCHIVE_PACKAGE_NAME: ClassVar[str]
    EXTRA_UNARCHIVE_STATUS: ClassVar[str]
    PACKAGE_SOURCE_DOWNLOADED_FILE: ClassVar[int]
    PACKAGE_SOURCE_LOCAL_FILE: ClassVar[int]
    PACKAGE_SOURCE_OTHER: ClassVar[int]
    PACKAGE_SOURCE_STORE: ClassVar[int]
    PACKAGE_SOURCE_UNSPECIFIED: ClassVar[int]
    STATUS_FAILURE: ClassVar[int]
    STATUS_FAILURE_ABORTED: ClassVar[int]
    STATUS_FAILURE_BLOCKED: ClassVar[int]
    STATUS_FAILURE_CONFLICT: ClassVar[int]
    STATUS_FAILURE_INCOMPATIBLE: ClassVar[int]
    STATUS_FAILURE_INVALID: ClassVar[int]
    STATUS_FAILURE_STORAGE: ClassVar[int]
    STATUS_FAILURE_TIMEOUT: ClassVar[int]
    STATUS_PENDING_USER_ACTION: ClassVar[int]
    STATUS_SUCCESS: ClassVar[int]
    UNARCHIVAL_ERROR_INSTALLER_DISABLED: ClassVar[int]
    UNARCHIVAL_ERROR_INSTALLER_UNINSTALLED: ClassVar[int]
    UNARCHIVAL_ERROR_INSUFFICIENT_STORAGE: ClassVar[int]
    UNARCHIVAL_ERROR_NO_CONNECTIVITY: ClassVar[int]
    UNARCHIVAL_ERROR_USER_ACTION_NEEDED: ClassVar[int]
    UNARCHIVAL_GENERIC_ERROR: ClassVar[int]
    UNARCHIVAL_OK: ClassVar[int]
    def openSession(self, p0: int) -> Any: ...
    def abandonSession(self, p0: int) -> None: ...
    def checkInstallConstraints(self, p0: list, p1: Any, p2: Executor, p3: Consumer) -> None: ...
    def commitSessionAfterInstallConstraintsAreMet(self, p0: int, p1: IntentSender, p2: Any, p3: int) -> None: ...
    def createSession(self, p0: Any) -> int: ...
    def getActiveStagedSession(self) -> Any: ...
    def getActiveStagedSessions(self) -> list: ...
    def getAllSessions(self) -> list: ...
    def getMySessions(self) -> list: ...
    def getSessionInfo(self, p0: int) -> Any: ...
    def getStagedSessions(self) -> list: ...
    def installExistingPackage(self, p0: str, p1: int, p2: IntentSender) -> None: ...
    def installPackageArchived(self, p0: ArchivedPackageInfo, p1: Any, p2: IntentSender) -> None: ...
    @overload
    def registerSessionCallback(self, p0: Any, p1: Handler) -> None: ...
    @overload
    def registerSessionCallback(self, p0: Any) -> None: ...
    def reportUnarchivalState(self, p0: Any) -> None: ...
    def reportUnarchivalStatus(self, p0: int, p1: int, p2: int, p3: PendingIntent) -> None: ...
    def requestArchive(self, p0: str, p1: IntentSender) -> None: ...
    def requestUnarchive(self, p0: str, p1: IntentSender) -> None: ...
    @overload
    def uninstall(self, p0: str, p1: IntentSender) -> None: ...
    @overload
    def uninstall(self, p0: VersionedPackage, p1: int, p2: IntentSender) -> None: ...
    @overload
    def uninstall(self, p0: VersionedPackage, p1: IntentSender) -> None: ...
    def uninstallExistingPackage(self, p0: str, p1: IntentSender) -> None: ...
    def unregisterSessionCallback(self, p0: Any) -> None: ...
    def updateSessionAppIcon(self, p0: int, p1: Bitmap) -> None: ...
    def updateSessionAppLabel(self, p0: int, p1: str) -> None: ...
    def waitForInstallConstraints(self, p0: list, p1: Any, p2: IntentSender, p3: int) -> None: ...

    class UnarchivalState:
        @staticmethod
        def createGenericErrorState(p0: int) -> Any: ...
        @staticmethod
        def createInsufficientStorageState(p0: int, p1: int, p2: PendingIntent) -> Any: ...
        @staticmethod
        def createNoConnectivityState(p0: int) -> Any: ...
        @staticmethod
        def createUserActionRequiredState(p0: int, p1: PendingIntent) -> Any: ...
        @staticmethod
        def createOkState(p0: int) -> Any: ...

    class SessionParams:
        CREATOR: ClassVar[Any]
        MODE_FULL_INSTALL: ClassVar[int]
        MODE_INHERIT_EXISTING: ClassVar[int]
        PERMISSION_STATE_DEFAULT: ClassVar[int]
        PERMISSION_STATE_DENIED: ClassVar[int]
        PERMISSION_STATE_GRANTED: ClassVar[int]
        RESTRICTED_PERMISSIONS_ALL: ClassVar[set]
        USER_ACTION_NOT_REQUIRED: ClassVar[int]
        USER_ACTION_REQUIRED: ClassVar[int]
        USER_ACTION_UNSPECIFIED: ClassVar[int]
        CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
        PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
        def __init__(self, p0: int) -> None: ...
        def setAppIcon(self, p0: Bitmap) -> None: ...
        def setAppLabel(self, p0: str) -> None: ...
        def setAppPackageName(self, p0: str) -> None: ...
        def setApplicationEnabledSettingPersistent(self) -> None: ...
        def setAutoInstallDependenciesEnabled(self, p0: bool) -> None: ...
        def setAutoRevokePermissionsMode(self, p0: bool) -> None: ...
        def setDontKillApp(self, p0: bool) -> None: ...
        def setInstallLocation(self, p0: int) -> None: ...
        def setInstallReason(self, p0: int) -> None: ...
        def setInstallScenario(self, p0: int) -> None: ...
        def setMultiPackage(self) -> None: ...
        def setOriginatingUid(self, p0: int) -> None: ...
        def setOriginatingUri(self, p0: Uri) -> None: ...
        def setPackageSource(self, p0: int) -> None: ...
        def setPermissionState(self, p0: str, p1: int) -> Any: ...
        def setReferrerUri(self, p0: Uri) -> None: ...
        def setRequestUpdateOwnership(self, p0: bool) -> None: ...
        def setRequireUserAction(self, p0: int) -> None: ...
        def setUnarchiveId(self, p0: int) -> None: ...
        def setWhitelistedRestrictedPermissions(self, p0: set) -> None: ...
        def setInstallerPackageName(self, p0: str) -> None: ...
        def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
        def describeContents(self) -> int: ...
        def setSize(self, p0: int) -> None: ...

    class SessionInfo:
        CREATOR: ClassVar[Any]
        INVALID_ID: ClassVar[int]
        SESSION_ACTIVATION_FAILED: ClassVar[int]
        SESSION_CONFLICT: ClassVar[int]
        SESSION_NO_ERROR: ClassVar[int]
        SESSION_UNKNOWN_ERROR: ClassVar[int]
        SESSION_VERIFICATION_FAILED: ClassVar[int]
        STAGED_SESSION_ACTIVATION_FAILED: ClassVar[int]
        STAGED_SESSION_CONFLICT: ClassVar[int]
        STAGED_SESSION_NO_ERROR: ClassVar[int]
        STAGED_SESSION_UNKNOWN: ClassVar[int]
        STAGED_SESSION_VERIFICATION_FAILED: ClassVar[int]
        CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
        PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
        def getChildSessionIds(self) -> Any: ...
        def getParentSessionId(self) -> int: ...
        def isApplicationEnabledSettingPersistent(self) -> bool: ...
        def isMultiPackage(self) -> bool: ...
        def isRequestUpdateOwnership(self) -> bool: ...
        def isStaged(self) -> bool: ...
        def createDetailsIntent(self) -> Intent: ...
        def getAppIcon(self) -> Bitmap: ...
        def getAppLabel(self) -> str: ...
        def getAppPackageName(self) -> str: ...
        def getCreatedMillis(self) -> int: ...
        def getDontKillApp(self) -> bool: ...
        def getInstallLocation(self) -> int: ...
        def getInstallReason(self) -> int: ...
        def getInstallerAttributionTag(self) -> str: ...
        def getInstallerUid(self) -> int: ...
        def getOriginatingUid(self) -> int: ...
        def getOriginatingUri(self) -> Uri: ...
        def getReferrerUri(self) -> Uri: ...
        def getRequireUserAction(self) -> int: ...
        def getStagedSessionErrorCode(self) -> int: ...
        def getStagedSessionErrorMessage(self) -> str: ...
        def getUpdatedMillis(self) -> int: ...
        def hasParentSessionId(self) -> bool: ...
        def isAutoInstallDependenciesEnabled(self) -> bool: ...
        def isCommitted(self) -> bool: ...
        def isPreApprovalRequested(self) -> bool: ...
        def isStagedSessionActive(self) -> bool: ...
        def isStagedSessionApplied(self) -> bool: ...
        def isStagedSessionFailed(self) -> bool: ...
        def isStagedSessionReady(self) -> bool: ...
        def isUnarchival(self) -> bool: ...
        def isSealed(self) -> bool: ...
        def getSize(self) -> int: ...
        def getPackageSource(self) -> int: ...
        def getMode(self) -> int: ...
        def getProgress(self) -> float: ...
        def getInstallerPackageName(self) -> str: ...
        def getUser(self) -> UserHandle: ...
        def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
        def describeContents(self) -> int: ...
        def getSessionId(self) -> int: ...
        def isActive(self) -> bool: ...

    class SessionCallback:
        def __init__(self) -> None: ...
        def onActiveChanged(self, p0: int, p1: bool) -> None: ...
        def onBadgingChanged(self, p0: int) -> None: ...
        def onFinished(self, p0: int, p1: bool) -> None: ...
        def onProgressChanged(self, p0: int, p1: float) -> None: ...
        def onCreated(self, p0: int) -> None: ...

    class Session:
        def addChildSessionId(self, p0: int) -> None: ...
        def fsync(self, p0: OutputStream) -> None: ...
        def removeChildSessionId(self, p0: int) -> None: ...
        def removeSplit(self, p0: str) -> None: ...
        def requestUserPreapproval(self, p0: Any, p1: IntentSender) -> None: ...
        def setAppMetadata(self, p0: PersistableBundle) -> None: ...
        def setChecksums(self, p0: str, p1: list, p2: Any) -> None: ...
        def setStagingProgress(self, p0: float) -> None: ...
        def getAppMetadata(self) -> PersistableBundle: ...
        def abandon(self) -> None: ...
        def getChildSessionIds(self) -> Any: ...
        def getNames(self) -> Any: ...
        def getParentSessionId(self) -> int: ...
        def isApplicationEnabledSettingPersistent(self) -> bool: ...
        def isMultiPackage(self) -> bool: ...
        def isRequestUpdateOwnership(self) -> bool: ...
        def isStaged(self) -> bool: ...
        def openRead(self, p0: str) -> InputStream: ...
        def openWrite(self, p0: str, p1: int, p2: int) -> OutputStream: ...
        def commit(self, p0: IntentSender) -> None: ...
        def close(self) -> None: ...
        def transfer(self, p0: str) -> None: ...
        def requestChecksums(self, p0: str, p1: int, p2: list, p3: Executor, p4: Any) -> None: ...

    class PreapprovalDetails:
        CREATOR: ClassVar[Any]
        CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
        PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
        def toString(self) -> str: ...
        def getPackageName(self) -> str: ...
        def getLabel(self) -> str: ...
        def getLocale(self) -> ULocale: ...
        def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
        def describeContents(self) -> int: ...
        def getIcon(self) -> Bitmap: ...

        class Builder:
            def __init__(self) -> None: ...
            def setIcon(self, p0: Bitmap) -> Any: ...
            def setPackageName(self, p0: str) -> Any: ...
            def setLabel(self, p0: str) -> Any: ...
            def build(self) -> Any: ...
            def setLocale(self, p0: ULocale) -> Any: ...

    class InstallConstraintsResult:
        CREATOR: ClassVar[Any]
        CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
        PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
        def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
        def describeContents(self) -> int: ...
        def areAllConstraintsSatisfied(self) -> bool: ...

    class InstallConstraints:
        CREATOR: ClassVar[Any]
        GENTLE_UPDATE: ClassVar[Any]
        CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
        PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
        def isAppNotForegroundRequired(self) -> bool: ...
        def isAppNotInteractingRequired(self) -> bool: ...
        def isAppNotTopVisibleRequired(self) -> bool: ...
        def isDeviceIdleRequired(self) -> bool: ...
        def isNotInCallRequired(self) -> bool: ...
        def equals(self, p0: Any) -> bool: ...
        def hashCode(self) -> int: ...
        def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
        def describeContents(self) -> int: ...

        class Builder:
            def __init__(self) -> None: ...
            def build(self) -> Any: ...
            def setAppNotTopVisibleRequired(self) -> Any: ...
            def setAppNotInteractingRequired(self) -> Any: ...
            def setAppNotForegroundRequired(self) -> Any: ...
            def setDeviceIdleRequired(self) -> Any: ...
            def setNotInCallRequired(self) -> Any: ...
