from typing import Any, ClassVar, overload
from java.math.BigInteger import BigInteger

class RSAMultiPrimePrivateCrtKey:
    serialVersionUID: ClassVar[int]
    serialVersionUID: ClassVar[int]
    serialVersionUID: ClassVar[int]
    serialVersionUID: ClassVar[int]
    def getOtherPrimeInfo(self) -> Any: ...
    def getPublicExponent(self) -> BigInteger: ...
    def getPrimeP(self) -> BigInteger: ...
    def getPrimeQ(self) -> BigInteger: ...
    def getPrimeExponentP(self) -> BigInteger: ...
    def getPrimeExponentQ(self) -> BigInteger: ...
    def getCrtCoefficient(self) -> BigInteger: ...
