from typing import Any, ClassVar, overload
from android.os.Parcel import Parcel

class GnssStatus:
    CONSTELLATION_BEIDOU: ClassVar[int]
    CONSTELLATION_GALILEO: ClassVar[int]
    CONSTELLATION_GLONASS: ClassVar[int]
    CONSTELLATION_GPS: ClassVar[int]
    CONSTELLATION_IRNSS: ClassVar[int]
    CONSTELLATION_QZSS: ClassVar[int]
    CONSTELLATION_SBAS: ClassVar[int]
    CONSTELLATION_UNKNOWN: ClassVar[int]
    CREATOR: ClassVar[Any]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    def getConstellationType(self, p0: int) -> int: ...
    def getCarrierFrequencyHz(self, p0: int) -> float: ...
    def getSatelliteCount(self) -> int: ...
    def getSvid(self, p0: int) -> int: ...
    def getCn0DbHz(self, p0: int) -> float: ...
    def getElevationDegrees(self, p0: int) -> float: ...
    def getAzimuthDegrees(self, p0: int) -> float: ...
    def hasEphemerisData(self, p0: int) -> bool: ...
    def hasAlmanacData(self, p0: int) -> bool: ...
    def usedInFix(self, p0: int) -> bool: ...
    def hasCarrierFrequencyHz(self, p0: int) -> bool: ...
    def hasBasebandCn0DbHz(self, p0: int) -> bool: ...
    def getBasebandCn0DbHz(self, p0: int) -> float: ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
    def equals(self, p0: Any) -> bool: ...
    def hashCode(self) -> int: ...

    class Callback:
        def __init__(self) -> None: ...
        def onSatelliteStatusChanged(self, p0: "GnssStatus") -> None: ...
        def onFirstFix(self, p0: int) -> None: ...
        def onStopped(self) -> None: ...
        def onStarted(self) -> None: ...

    class Builder:
        def __init__(self) -> None: ...
        def addSatellite(self, p0: int, p1: int, p2: float, p3: float, p4: float, p5: bool, p6: bool, p7: bool, p8: bool, p9: float, p10: bool, p11: float) -> Any: ...
        def clearSatellites(self) -> Any: ...
        def build(self) -> "GnssStatus": ...
