from typing import Any, ClassVar, overload
from android.os.Parcel import Parcel

class Characteristics:
    CREATOR: ClassVar[Any]
    WIFI_AWARE_CIPHER_SUITE_NCS_PK_128: ClassVar[int]
    WIFI_AWARE_CIPHER_SUITE_NCS_PK_256: ClassVar[int]
    WIFI_AWARE_CIPHER_SUITE_NCS_PK_PASN_128: ClassVar[int]
    WIFI_AWARE_CIPHER_SUITE_NCS_PK_PASN_256: ClassVar[int]
    WIFI_AWARE_CIPHER_SUITE_NCS_SK_128: ClassVar[int]
    WIFI_AWARE_CIPHER_SUITE_NCS_SK_256: ClassVar[int]
    WIFI_AWARE_CIPHER_SUITE_NONE: ClassVar[int]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    def getMaxServiceNameLength(self) -> int: ...
    def getMaxServiceSpecificInfoLength(self) -> int: ...
    def getMaxMatchFilterLength(self) -> int: ...
    def getNumberOfSupportedDataInterfaces(self) -> int: ...
    def getNumberOfSupportedPublishSessions(self) -> int: ...
    def getNumberOfSupportedSubscribeSessions(self) -> int: ...
    def getNumberOfSupportedDataPaths(self) -> int: ...
    def isInstantCommunicationModeSupported(self) -> bool: ...
    def isAwarePairingSupported(self) -> bool: ...
    def isSuspensionSupported(self) -> bool: ...
    def getSupportedCipherSuites(self) -> int: ...
    def getSupportedPairingCipherSuites(self) -> int: ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
