from typing import Any, ClassVar, overload
from android.net.wifi.aware.AwarePairingConfig import AwarePairingConfig
from android.net.wifi.aware.WifiAwareDataPathSecurityConfig import WifiAwareDataPathSecurityConfig
from android.os.Parcel import Parcel

class PublishConfig:
    CREATOR: ClassVar[Any]
    PUBLISH_TYPE_SOLICITED: ClassVar[int]
    PUBLISH_TYPE_UNSOLICITED: ClassVar[int]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    def getInstantCommunicationBand(self) -> int: ...
    def isInstantCommunicationModeEnabled(self) -> bool: ...
    def getPairingConfig(self) -> AwarePairingConfig: ...
    def getSecurityConfig(self) -> WifiAwareDataPathSecurityConfig: ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
    def equals(self, p0: Any) -> bool: ...
    def toString(self) -> str: ...
    def hashCode(self) -> int: ...

    class Builder:
        def __init__(self) -> None: ...
        def setDataPathSecurityConfig(self, p0: WifiAwareDataPathSecurityConfig) -> Any: ...
        def setServiceName(self, p0: str) -> Any: ...
        def setServiceSpecificInfo(self, p0: Any) -> Any: ...
        def setMatchFilter(self, p0: list) -> Any: ...
        def setPublishType(self, p0: int) -> Any: ...
        def setTtlSec(self, p0: int) -> Any: ...
        def setTerminateNotificationEnabled(self, p0: bool) -> Any: ...
        def setRangingEnabled(self, p0: bool) -> Any: ...
        def setInstantCommunicationModeEnabled(self, p0: bool, p1: int) -> Any: ...
        def setPairingConfig(self, p0: AwarePairingConfig) -> Any: ...
        def build(self) -> "PublishConfig": ...
