from typing import Any, ClassVar, overload
from android.net.NetworkSpecifier import NetworkSpecifier
from android.net.wifi.aware.DiscoverySessionCallback import DiscoverySessionCallback
from android.net.wifi.aware.PublishConfig import PublishConfig
from android.net.wifi.aware.SubscribeConfig import SubscribeConfig
from android.os.Handler import Handler

class WifiAwareSession:
    def createNetworkSpecifierOpen(self, p0: int, p1: Any) -> NetworkSpecifier: ...
    def createNetworkSpecifierPassphrase(self, p0: int, p1: Any, p2: str) -> NetworkSpecifier: ...
    def subscribe(self, p0: SubscribeConfig, p1: DiscoverySessionCallback, p2: Handler) -> None: ...
    def publish(self, p0: PublishConfig, p1: DiscoverySessionCallback, p2: Handler) -> None: ...
    def close(self) -> None: ...
