from typing import Any, ClassVar, overload
from android.content.Context import Context
from java.util.Calendar import Calendar
from java.util.Date import Date
from java.util.Locale import Locale

class DateFormat:
    def __init__(self) -> None: ...
    @staticmethod
    def getBestDateTimePattern(p0: Locale, p1: str) -> str: ...
    @staticmethod
    def getTimeFormat(p0: Context) -> "DateFormat": ...
    @staticmethod
    def is24HourFormat(p0: Context) -> bool: ...
    @staticmethod
    def getDateFormat(p0: Context) -> "DateFormat": ...
    @staticmethod
    def getLongDateFormat(p0: Context) -> "DateFormat": ...
    @staticmethod
    def getMediumDateFormat(p0: Context) -> "DateFormat": ...
    @staticmethod
    def getDateFormatOrder(p0: Context) -> Any: ...
    @overload
    @staticmethod
    def format(p0: str, p1: Calendar) -> str: ...
    @overload
    @staticmethod
    def format(p0: str, p1: Date) -> str: ...
    @overload
    @staticmethod
    def format(p0: str, p1: int) -> str: ...
