from typing import Any, ClassVar, overload

class Size:
    def __init__(self, p0: int, p1: int) -> None: ...
    def equals(self, p0: Any) -> bool: ...
    def toString(self) -> str: ...
    def hashCode(self) -> int: ...
    def getWidth(self) -> int: ...
    def getHeight(self) -> int: ...
    @staticmethod
    def parseSize(p0: str) -> "Size": ...
