from typing import Any, ClassVar, overload

class XdhKeySpec:
    def __init__(self, p0: Any) -> None: ...
    def equals(self, p0: Any) -> bool: ...
    def hashCode(self) -> int: ...
    def getKey(self) -> Any: ...
    def getFormat(self) -> str: ...
