from typing import Any, ClassVar, overload
from android.graphics.Point import Point
from android.graphics.drawable.Drawable import Drawable
from android.view.View import View

class Magnifier:
    SOURCE_BOUND_MAX_IN_SURFACE: ClassVar[int]
    SOURCE_BOUND_MAX_VISIBLE: ClassVar[int]
    def __init__(self, p0: View) -> None: ...
    def update(self) -> None: ...
    @overload
    def show(self, p0: float, p1: float) -> None: ...
    @overload
    def show(self, p0: float, p1: float, p2: float, p3: float) -> None: ...
    def getWidth(self) -> int: ...
    def getHeight(self) -> int: ...
    def getElevation(self) -> float: ...
    def getOverlay(self) -> Drawable: ...
    def getPosition(self) -> Point: ...
    def getSourceWidth(self) -> int: ...
    def getSourceHeight(self) -> int: ...
    def setZoom(self, p0: float) -> None: ...
    def getZoom(self) -> float: ...
    def getCornerRadius(self) -> float: ...
    def getDefaultHorizontalSourceToMagnifierOffset(self) -> int: ...
    def getDefaultVerticalSourceToMagnifierOffset(self) -> int: ...
    def getSourcePosition(self) -> Point: ...
    def isClippingEnabled(self) -> bool: ...
    def dismiss(self) -> None: ...

    class Builder:
        def __init__(self, p0: View) -> None: ...
        def build(self) -> "Magnifier": ...
        def setInitialZoom(self, p0: float) -> Any: ...
        def setCornerRadius(self, p0: float) -> Any: ...
        def setOverlay(self, p0: Drawable) -> Any: ...
        def setDefaultSourceToMagnifierOffset(self, p0: int, p1: int) -> Any: ...
        def setSourceBounds(self, p0: int, p1: int, p2: int, p3: int) -> Any: ...
        def setElevation(self, p0: float) -> Any: ...
        def setSize(self, p0: int, p1: int) -> Any: ...
        def setClippingEnabled(self, p0: bool) -> Any: ...
