from typing import Any, ClassVar, overload
from android.content.Context import Context
from android.database.Cursor import Cursor
from android.view.View import View
from android.view.ViewGroup import ViewGroup

class ResourceCursorTreeAdapter:
    @overload
    def __init__(self, p0: Context, p1: Cursor, p2: int, p3: int) -> None: ...
    @overload
    def __init__(self, p0: Context, p1: Cursor, p2: int, p3: int, p4: int) -> None: ...
    @overload
    def __init__(self, p0: Context, p1: Cursor, p2: int, p3: int, p4: int, p5: int) -> None: ...
    def newGroupView(self, p0: Context, p1: Cursor, p2: bool, p3: ViewGroup) -> View: ...
    def newChildView(self, p0: Context, p1: Cursor, p2: bool, p3: ViewGroup) -> View: ...
