from typing import Any, ClassVar, overload
from android.view.MotionEvent import MotionEvent
from android.view.View import View
from android.view.ViewGroup import ViewGroup

class ZoomButtonsController:
    def __init__(self, p0: View) -> None: ...
    def setZoomOutEnabled(self, p0: bool) -> None: ...
    def setOnZoomListener(self, p0: Any) -> None: ...
    def isAutoDismissed(self) -> bool: ...
    def setAutoDismissed(self, p0: bool) -> None: ...
    def getContainer(self) -> ViewGroup: ...
    def getZoomControls(self) -> View: ...
    def setZoomInEnabled(self, p0: bool) -> None: ...
    def isVisible(self) -> bool: ...
    def setFocusable(self, p0: bool) -> None: ...
    def setVisible(self, p0: bool) -> None: ...
    def setZoomSpeed(self, p0: int) -> None: ...
    def onTouch(self, p0: View, p1: MotionEvent) -> bool: ...

    class OnZoomListener:
        def onVisibilityChanged(self, p0: bool) -> None: ...
        def onZoom(self, p0: bool) -> None: ...
