from typing import Any, ClassVar, overload
from android.content.om.OverlayIdentifier import OverlayIdentifier
from android.content.res.AssetFileDescriptor import AssetFileDescriptor
from android.os.ParcelFileDescriptor import ParcelFileDescriptor

class FabricatedOverlay:
    def __init__(self, p0: str, p1: str) -> None: ...
    def setNinePatchResourceValue(self, p0: str, p1: ParcelFileDescriptor, p2: str) -> None: ...
    @overload
    def setResourceValue(self, p0: str, p1: int, p2: int, p3: str) -> None: ...
    @overload
    def setResourceValue(self, p0: str, p1: AssetFileDescriptor, p2: str) -> None: ...
    @overload
    def setResourceValue(self, p0: str, p1: ParcelFileDescriptor, p2: str) -> None: ...
    @overload
    def setResourceValue(self, p0: str, p1: int, p2: str, p3: str) -> None: ...
    def setTargetOverlayable(self, p0: str) -> None: ...
    def getIdentifier(self) -> OverlayIdentifier: ...
