from typing import Any, ClassVar, overload
from android.telecom.DisconnectCause import DisconnectCause
from java.util.function.Consumer import Consumer

class CallControlCallback:
    def onSetActive(self, p0: Consumer) -> None: ...
    def onCallStreamingStarted(self, p0: Consumer) -> None: ...
    def onSetInactive(self, p0: Consumer) -> None: ...
    def onAnswer(self, p0: int, p1: Consumer) -> None: ...
    def onDisconnect(self, p0: DisconnectCause, p1: Consumer) -> None: ...
