from jnius import JavaClass, MetaJavaClass, JavaMethod, JavaStaticMethod, JavaMultipleMethod, JavaField, JavaStaticField

__all__ = ["RemoteConnection"]

class RemoteConnection(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "android/telecom/RemoteConnection"
    setCallAudioState = JavaMethod("(Landroid/telecom/CallAudioState;)V")
    abort = JavaMethod("()V")
    isVoipAudioMode = JavaMethod("()Z")
    getConference = JavaMethod("()Landroid/telecom/RemoteConference;")
    getAddressPresentation = JavaMethod("()I")
    getCallerDisplayName = JavaMethod("()Ljava/lang/CharSequence;")
    getCallerDisplayNamePresentation = JavaMethod("()I")
    disconnect = JavaMethod("()V")
    getState = JavaMethod("()I")
    getAddress = JavaMethod("()Landroid/net/Uri;")
    getStatusHints = JavaMethod("()Landroid/telecom/StatusHints;")
    getVideoState = JavaMethod("()I")
    getVideoProvider = JavaMethod("()Landroid/telecom/RemoteConnection$VideoProvider;")
    getDisconnectCause = JavaMethod("()Landroid/telecom/DisconnectCause;")
    getConferenceableConnections = JavaMethod("()Ljava/util/List;")
    getConnectionCapabilities = JavaMethod("()I")
    getConnectionProperties = JavaMethod("()I")
    isRingbackRequested = JavaMethod("()Z")
    getExtras = JavaMethod("()Landroid/os/Bundle;")
    answer = JavaMethod("()V")
    registerCallback = JavaMultipleMethod([("(Landroid/telecom/RemoteConnection$Callback;Landroid/os/Handler;)V", False, False), ("(Landroid/telecom/RemoteConnection$Callback;)V", False, False)])
    unregisterCallback = JavaMethod("(Landroid/telecom/RemoteConnection$Callback;)V")
    addConferenceParticipants = JavaMethod("(Ljava/util/List;)V")
    hold = JavaMethod("()V")
    playDtmfTone = JavaMethod("(C)V")
    postDialContinue = JavaMethod("(Z)V")
    pullExternalCall = JavaMethod("()V")
    reject = JavaMethod("()V")
    stopDtmfTone = JavaMethod("()V")
    unhold = JavaMethod("()V")

    class VideoProvider(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "android/telecom/RemoteConnection$VideoProvider"
        setCamera = JavaMethod("(Ljava/lang/String;)V")
        setDisplaySurface = JavaMethod("(Landroid/view/Surface;)V")
        setPauseImage = JavaMethod("(Landroid/net/Uri;)V")
        setPreviewSurface = JavaMethod("(Landroid/view/Surface;)V")
        requestCallDataUsage = JavaMethod("()V")
        requestCameraCapabilities = JavaMethod("()V")
        sendSessionModifyRequest = JavaMethod("(Landroid/telecom/VideoProfile;Landroid/telecom/VideoProfile;)V")
        sendSessionModifyResponse = JavaMethod("(Landroid/telecom/VideoProfile;)V")
        setDeviceOrientation = JavaMethod("(I)V")
        registerCallback = JavaMethod("(Landroid/telecom/RemoteConnection$VideoProvider$Callback;)V")
        unregisterCallback = JavaMethod("(Landroid/telecom/RemoteConnection$VideoProvider$Callback;)V")
        setZoom = JavaMethod("(F)V")

        class Callback(JavaClass, metaclass=MetaJavaClass):
            __javaclass__ = "android/telecom/RemoteConnection$VideoProvider$Callback"
            __javaconstructor__ = [("()V", False)]
            onCallSessionEvent = JavaMethod("(Landroid/telecom/RemoteConnection$VideoProvider;I)V")
            onCallDataUsageChanged = JavaMethod("(Landroid/telecom/RemoteConnection$VideoProvider;J)V")
            onCameraCapabilitiesChanged = JavaMethod("(Landroid/telecom/RemoteConnection$VideoProvider;Landroid/telecom/VideoProfile$CameraCapabilities;)V")
            onPeerDimensionsChanged = JavaMethod("(Landroid/telecom/RemoteConnection$VideoProvider;II)V")
            onSessionModifyRequestReceived = JavaMethod("(Landroid/telecom/RemoteConnection$VideoProvider;Landroid/telecom/VideoProfile;)V")
            onSessionModifyResponseReceived = JavaMethod("(Landroid/telecom/RemoteConnection$VideoProvider;ILandroid/telecom/VideoProfile;Landroid/telecom/VideoProfile;)V")
            onVideoQualityChanged = JavaMethod("(Landroid/telecom/RemoteConnection$VideoProvider;I)V")

    class Callback(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "android/telecom/RemoteConnection$Callback"
        __javaconstructor__ = [("()V", False)]
        onDisconnected = JavaMethod("(Landroid/telecom/RemoteConnection;Landroid/telecom/DisconnectCause;)V")
        onConnectionEvent = JavaMethod("(Landroid/telecom/RemoteConnection;Ljava/lang/String;Landroid/os/Bundle;)V")
        onVoipAudioChanged = JavaMethod("(Landroid/telecom/RemoteConnection;Z)V")
        onAddressChanged = JavaMethod("(Landroid/telecom/RemoteConnection;Landroid/net/Uri;I)V")
        onPostDialChar = JavaMethod("(Landroid/telecom/RemoteConnection;C)V")
        onCallerDisplayNameChanged = JavaMethod("(Landroid/telecom/RemoteConnection;Ljava/lang/String;I)V")
        onConferenceChanged = JavaMethod("(Landroid/telecom/RemoteConnection;Landroid/telecom/RemoteConference;)V")
        onConferenceableConnectionsChanged = JavaMethod("(Landroid/telecom/RemoteConnection;Ljava/util/List;)V")
        onConnectionCapabilitiesChanged = JavaMethod("(Landroid/telecom/RemoteConnection;I)V")
        onConnectionPropertiesChanged = JavaMethod("(Landroid/telecom/RemoteConnection;I)V")
        onRingbackRequested = JavaMethod("(Landroid/telecom/RemoteConnection;Z)V")
        onStatusHintsChanged = JavaMethod("(Landroid/telecom/RemoteConnection;Landroid/telecom/StatusHints;)V")
        onVideoProviderChanged = JavaMethod("(Landroid/telecom/RemoteConnection;Landroid/telecom/RemoteConnection$VideoProvider;)V")
        onVideoStateChanged = JavaMethod("(Landroid/telecom/RemoteConnection;I)V")
        onPostDialWait = JavaMethod("(Landroid/telecom/RemoteConnection;Ljava/lang/String;)V")
        onExtrasChanged = JavaMethod("(Landroid/telecom/RemoteConnection;Landroid/os/Bundle;)V")
        onStateChanged = JavaMethod("(Landroid/telecom/RemoteConnection;I)V")
        onDestroyed = JavaMethod("(Landroid/telecom/RemoteConnection;)V")