from typing import Any, ClassVar, overload
from android.os.Parcel import Parcel
from android.ranging.RangingConfig import RangingConfig
from android.ranging.SessionConfig import SessionConfig

class RangingPreference:
    CREATOR: ClassVar[Any]
    DEVICE_ROLE_INITIATOR: ClassVar[int]
    DEVICE_ROLE_RESPONDER: ClassVar[int]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    def toString(self) -> str: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
    def describeContents(self) -> int: ...
    def getRangingParams(self) -> RangingConfig: ...
    def getSessionConfig(self) -> SessionConfig: ...
    def getDeviceRole(self) -> int: ...

    class Builder:
        def __init__(self, p0: int, p1: RangingConfig) -> None: ...
        def setSessionConfig(self, p0: SessionConfig) -> Any: ...
        def build(self) -> "RangingPreference": ...
