from typing import Any, ClassVar, overload
from android.os.Parcel import Parcel
from java.util.UUID import UUID

class RangingDevice:
    CREATOR: ClassVar[Any]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    def equals(self, p0: Any) -> bool: ...
    def toString(self) -> str: ...
    def hashCode(self) -> int: ...
    def getUuid(self) -> UUID: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
    def describeContents(self) -> int: ...

    class Builder:
        def __init__(self) -> None: ...
        def setUuid(self, p0: UUID) -> Any: ...
        def build(self) -> "RangingDevice": ...
