# cython: language_level=3
# Generated by jni-wrap cython — do not edit by hand.

from jni_core._core cimport (
    JavaObject, get_env, check_jni_exc,
    find_class_global, get_method_id, get_static_method_id,
    get_field_id, get_static_field_id, j_str, py_str,
)
from jni_core._dispatch cimport (
    jnicore_NewObjectA, jnicore_DeleteLocalRef, jnicore_NewGlobalRef,
    jnicore_CallVoidMethodA, jnicore_CallObjectMethodA,
    jnicore_CallBooleanMethodA, jnicore_CallByteMethodA,
    jnicore_CallCharMethodA, jnicore_CallShortMethodA,
    jnicore_CallIntMethodA, jnicore_CallLongMethodA,
    jnicore_CallFloatMethodA, jnicore_CallDoubleMethodA,
    jnicore_CallStaticVoidMethodA, jnicore_CallStaticObjectMethodA,
    jnicore_CallStaticBooleanMethodA, jnicore_CallStaticByteMethodA,
    jnicore_CallStaticCharMethodA, jnicore_CallStaticShortMethodA,
    jnicore_CallStaticIntMethodA, jnicore_CallStaticLongMethodA,
    jnicore_CallStaticFloatMethodA, jnicore_CallStaticDoubleMethodA,
    jnicore_GetObjectField, jnicore_SetObjectField,
    jnicore_GetBooleanField, jnicore_SetBooleanField,
    jnicore_GetByteField, jnicore_SetByteField,
    jnicore_GetCharField, jnicore_SetCharField,
    jnicore_GetShortField, jnicore_SetShortField,
    jnicore_GetIntField, jnicore_SetIntField,
    jnicore_GetLongField, jnicore_SetLongField,
    jnicore_GetFloatField, jnicore_SetFloatField,
    jnicore_GetDoubleField, jnicore_SetDoubleField,
    jnicore_GetStaticObjectField, jnicore_SetStaticObjectField,
    jnicore_GetStaticBooleanField, jnicore_SetStaticBooleanField,
    jnicore_GetStaticByteField, jnicore_SetStaticByteField,
    jnicore_GetStaticCharField, jnicore_SetStaticCharField,
    jnicore_GetStaticShortField, jnicore_SetStaticShortField,
    jnicore_GetStaticIntField, jnicore_SetStaticIntField,
    jnicore_GetStaticLongField, jnicore_SetStaticLongField,
    jnicore_GetStaticFloatField, jnicore_SetStaticFloatField,
    jnicore_GetStaticDoubleField, jnicore_SetStaticDoubleField,
)
from jni_core.jni cimport (
    jclass, jobject, jmethodID, jfieldID, jvalue, JNIEnv,
    jboolean, jbyte, jchar, jshort, jint, jlong, jfloat, jdouble, jstring,
)

include "jni_core/conversions.pxi"

__javaclass__ = "android/util/DisplayMetrics"  # android.util.DisplayMetrics

cdef jclass _cls_DisplayMetrics = NULL
cdef jmethodID _ctor_DisplayMetrics_0 = NULL
cdef jmethodID _m_DisplayMetrics_equals_0 = NULL
cdef jmethodID _m_DisplayMetrics_equals_1 = NULL
cdef jmethodID _m_DisplayMetrics_toString_0 = NULL
cdef jmethodID _m_DisplayMetrics_hashCode_0 = NULL
cdef jmethodID _m_DisplayMetrics_setTo_0 = NULL
cdef jmethodID _m_DisplayMetrics_setToDefaults_0 = NULL
cdef jfieldID _sf_DisplayMetrics_DENSITY_140 = NULL
cdef jfieldID _sf_DisplayMetrics_DENSITY_180 = NULL
cdef jfieldID _sf_DisplayMetrics_DENSITY_200 = NULL
cdef jfieldID _sf_DisplayMetrics_DENSITY_220 = NULL
cdef jfieldID _sf_DisplayMetrics_DENSITY_260 = NULL
cdef jfieldID _sf_DisplayMetrics_DENSITY_280 = NULL
cdef jfieldID _sf_DisplayMetrics_DENSITY_300 = NULL
cdef jfieldID _sf_DisplayMetrics_DENSITY_340 = NULL
cdef jfieldID _sf_DisplayMetrics_DENSITY_360 = NULL
cdef jfieldID _sf_DisplayMetrics_DENSITY_390 = NULL
cdef jfieldID _sf_DisplayMetrics_DENSITY_400 = NULL
cdef jfieldID _sf_DisplayMetrics_DENSITY_420 = NULL
cdef jfieldID _sf_DisplayMetrics_DENSITY_440 = NULL
cdef jfieldID _sf_DisplayMetrics_DENSITY_450 = NULL
cdef jfieldID _sf_DisplayMetrics_DENSITY_520 = NULL
cdef jfieldID _sf_DisplayMetrics_DENSITY_560 = NULL
cdef jfieldID _sf_DisplayMetrics_DENSITY_600 = NULL
cdef jfieldID _sf_DisplayMetrics_DENSITY_DEFAULT = NULL
cdef jfieldID _sf_DisplayMetrics_DENSITY_DEVICE_STABLE = NULL
cdef jfieldID _sf_DisplayMetrics_DENSITY_HIGH = NULL
cdef jfieldID _sf_DisplayMetrics_DENSITY_LOW = NULL
cdef jfieldID _sf_DisplayMetrics_DENSITY_MEDIUM = NULL
cdef jfieldID _sf_DisplayMetrics_DENSITY_TV = NULL
cdef jfieldID _sf_DisplayMetrics_DENSITY_XHIGH = NULL
cdef jfieldID _sf_DisplayMetrics_DENSITY_XXHIGH = NULL
cdef jfieldID _sf_DisplayMetrics_DENSITY_XXXHIGH = NULL
cdef jfieldID _f_DisplayMetrics_density = NULL
cdef jfieldID _f_DisplayMetrics_densityDpi = NULL
cdef jfieldID _f_DisplayMetrics_heightPixels = NULL
cdef jfieldID _f_DisplayMetrics_scaledDensity = NULL
cdef jfieldID _f_DisplayMetrics_widthPixels = NULL
cdef jfieldID _f_DisplayMetrics_xdpi = NULL
cdef jfieldID _f_DisplayMetrics_ydpi = NULL

cdef int _ensure_ids_DisplayMetrics(JNIEnv* env) except -1:
    global _cls_DisplayMetrics, _ctor_DisplayMetrics_0, _m_DisplayMetrics_equals_0, _m_DisplayMetrics_equals_1, _m_DisplayMetrics_toString_0, _m_DisplayMetrics_hashCode_0, _m_DisplayMetrics_setTo_0, _m_DisplayMetrics_setToDefaults_0, _sf_DisplayMetrics_DENSITY_140, _sf_DisplayMetrics_DENSITY_180, _sf_DisplayMetrics_DENSITY_200, _sf_DisplayMetrics_DENSITY_220, _sf_DisplayMetrics_DENSITY_260, _sf_DisplayMetrics_DENSITY_280, _sf_DisplayMetrics_DENSITY_300, _sf_DisplayMetrics_DENSITY_340, _sf_DisplayMetrics_DENSITY_360, _sf_DisplayMetrics_DENSITY_390, _sf_DisplayMetrics_DENSITY_400, _sf_DisplayMetrics_DENSITY_420, _sf_DisplayMetrics_DENSITY_440, _sf_DisplayMetrics_DENSITY_450, _sf_DisplayMetrics_DENSITY_520, _sf_DisplayMetrics_DENSITY_560, _sf_DisplayMetrics_DENSITY_600, _sf_DisplayMetrics_DENSITY_DEFAULT, _sf_DisplayMetrics_DENSITY_DEVICE_STABLE, _sf_DisplayMetrics_DENSITY_HIGH, _sf_DisplayMetrics_DENSITY_LOW, _sf_DisplayMetrics_DENSITY_MEDIUM, _sf_DisplayMetrics_DENSITY_TV, _sf_DisplayMetrics_DENSITY_XHIGH, _sf_DisplayMetrics_DENSITY_XXHIGH, _sf_DisplayMetrics_DENSITY_XXXHIGH, _f_DisplayMetrics_density, _f_DisplayMetrics_densityDpi, _f_DisplayMetrics_heightPixels, _f_DisplayMetrics_scaledDensity, _f_DisplayMetrics_widthPixels, _f_DisplayMetrics_xdpi, _f_DisplayMetrics_ydpi
    if _cls_DisplayMetrics != NULL:
        return 0
    _cls_DisplayMetrics = find_class_global(env, b"android/util/DisplayMetrics")
    _ctor_DisplayMetrics_0 = get_method_id(env, _cls_DisplayMetrics, b"<init>", b"()V")
    _m_DisplayMetrics_equals_0 = get_method_id(env, _cls_DisplayMetrics, b"equals", b"(Landroid/util/DisplayMetrics;)Z")
    _m_DisplayMetrics_equals_1 = get_method_id(env, _cls_DisplayMetrics, b"equals", b"(Ljava/lang/Object;)Z")
    _m_DisplayMetrics_toString_0 = get_method_id(env, _cls_DisplayMetrics, b"toString", b"()Ljava/lang/String;")
    _m_DisplayMetrics_hashCode_0 = get_method_id(env, _cls_DisplayMetrics, b"hashCode", b"()I")
    _m_DisplayMetrics_setTo_0 = get_method_id(env, _cls_DisplayMetrics, b"setTo", b"(Landroid/util/DisplayMetrics;)V")
    _m_DisplayMetrics_setToDefaults_0 = get_method_id(env, _cls_DisplayMetrics, b"setToDefaults", b"()V")
    _sf_DisplayMetrics_DENSITY_140 = get_static_field_id(env, _cls_DisplayMetrics, b"DENSITY_140", b"I")
    _sf_DisplayMetrics_DENSITY_180 = get_static_field_id(env, _cls_DisplayMetrics, b"DENSITY_180", b"I")
    _sf_DisplayMetrics_DENSITY_200 = get_static_field_id(env, _cls_DisplayMetrics, b"DENSITY_200", b"I")
    _sf_DisplayMetrics_DENSITY_220 = get_static_field_id(env, _cls_DisplayMetrics, b"DENSITY_220", b"I")
    _sf_DisplayMetrics_DENSITY_260 = get_static_field_id(env, _cls_DisplayMetrics, b"DENSITY_260", b"I")
    _sf_DisplayMetrics_DENSITY_280 = get_static_field_id(env, _cls_DisplayMetrics, b"DENSITY_280", b"I")
    _sf_DisplayMetrics_DENSITY_300 = get_static_field_id(env, _cls_DisplayMetrics, b"DENSITY_300", b"I")
    _sf_DisplayMetrics_DENSITY_340 = get_static_field_id(env, _cls_DisplayMetrics, b"DENSITY_340", b"I")
    _sf_DisplayMetrics_DENSITY_360 = get_static_field_id(env, _cls_DisplayMetrics, b"DENSITY_360", b"I")
    _sf_DisplayMetrics_DENSITY_390 = get_static_field_id(env, _cls_DisplayMetrics, b"DENSITY_390", b"I")
    _sf_DisplayMetrics_DENSITY_400 = get_static_field_id(env, _cls_DisplayMetrics, b"DENSITY_400", b"I")
    _sf_DisplayMetrics_DENSITY_420 = get_static_field_id(env, _cls_DisplayMetrics, b"DENSITY_420", b"I")
    _sf_DisplayMetrics_DENSITY_440 = get_static_field_id(env, _cls_DisplayMetrics, b"DENSITY_440", b"I")
    _sf_DisplayMetrics_DENSITY_450 = get_static_field_id(env, _cls_DisplayMetrics, b"DENSITY_450", b"I")
    _sf_DisplayMetrics_DENSITY_520 = get_static_field_id(env, _cls_DisplayMetrics, b"DENSITY_520", b"I")
    _sf_DisplayMetrics_DENSITY_560 = get_static_field_id(env, _cls_DisplayMetrics, b"DENSITY_560", b"I")
    _sf_DisplayMetrics_DENSITY_600 = get_static_field_id(env, _cls_DisplayMetrics, b"DENSITY_600", b"I")
    _sf_DisplayMetrics_DENSITY_DEFAULT = get_static_field_id(env, _cls_DisplayMetrics, b"DENSITY_DEFAULT", b"I")
    _sf_DisplayMetrics_DENSITY_DEVICE_STABLE = get_static_field_id(env, _cls_DisplayMetrics, b"DENSITY_DEVICE_STABLE", b"I")
    _sf_DisplayMetrics_DENSITY_HIGH = get_static_field_id(env, _cls_DisplayMetrics, b"DENSITY_HIGH", b"I")
    _sf_DisplayMetrics_DENSITY_LOW = get_static_field_id(env, _cls_DisplayMetrics, b"DENSITY_LOW", b"I")
    _sf_DisplayMetrics_DENSITY_MEDIUM = get_static_field_id(env, _cls_DisplayMetrics, b"DENSITY_MEDIUM", b"I")
    _sf_DisplayMetrics_DENSITY_TV = get_static_field_id(env, _cls_DisplayMetrics, b"DENSITY_TV", b"I")
    _sf_DisplayMetrics_DENSITY_XHIGH = get_static_field_id(env, _cls_DisplayMetrics, b"DENSITY_XHIGH", b"I")
    _sf_DisplayMetrics_DENSITY_XXHIGH = get_static_field_id(env, _cls_DisplayMetrics, b"DENSITY_XXHIGH", b"I")
    _sf_DisplayMetrics_DENSITY_XXXHIGH = get_static_field_id(env, _cls_DisplayMetrics, b"DENSITY_XXXHIGH", b"I")
    _f_DisplayMetrics_density = get_field_id(env, _cls_DisplayMetrics, b"density", b"F")
    _f_DisplayMetrics_densityDpi = get_field_id(env, _cls_DisplayMetrics, b"densityDpi", b"I")
    _f_DisplayMetrics_heightPixels = get_field_id(env, _cls_DisplayMetrics, b"heightPixels", b"I")
    _f_DisplayMetrics_scaledDensity = get_field_id(env, _cls_DisplayMetrics, b"scaledDensity", b"F")
    _f_DisplayMetrics_widthPixels = get_field_id(env, _cls_DisplayMetrics, b"widthPixels", b"I")
    _f_DisplayMetrics_xdpi = get_field_id(env, _cls_DisplayMetrics, b"xdpi", b"F")
    _f_DisplayMetrics_ydpi = get_field_id(env, _cls_DisplayMetrics, b"ydpi", b"F")
    return 0

cdef class DisplayMetrics(JavaObject):
    """android.util.DisplayMetrics"""

    def __init__(self, ):
        cdef JNIEnv* env = get_env()
        _ensure_ids_DisplayMetrics(env)
        cdef jvalue _args[1]  # unused; arrayless calls disallowed in Cython
        cdef jobject _ret = jnicore_NewObjectA(env, _cls_DisplayMetrics, _ctor_DisplayMetrics_0, _args)
        check_jni_exc(env)
        self._adopt_local(env, _ret)

    # Static field DisplayMetrics.DENSITY_140
    @staticmethod
    def DENSITY_140() -> int:
        cdef JNIEnv* env = get_env()
        _ensure_ids_DisplayMetrics(env)
        cdef jint _ret = jnicore_GetStaticIntField(env, _cls_DisplayMetrics, _sf_DisplayMetrics_DENSITY_140)
        check_jni_exc(env)
        return <int>_ret

    # Static field DisplayMetrics.DENSITY_180
    @staticmethod
    def DENSITY_180() -> int:
        cdef JNIEnv* env = get_env()
        _ensure_ids_DisplayMetrics(env)
        cdef jint _ret = jnicore_GetStaticIntField(env, _cls_DisplayMetrics, _sf_DisplayMetrics_DENSITY_180)
        check_jni_exc(env)
        return <int>_ret

    # Static field DisplayMetrics.DENSITY_200
    @staticmethod
    def DENSITY_200() -> int:
        cdef JNIEnv* env = get_env()
        _ensure_ids_DisplayMetrics(env)
        cdef jint _ret = jnicore_GetStaticIntField(env, _cls_DisplayMetrics, _sf_DisplayMetrics_DENSITY_200)
        check_jni_exc(env)
        return <int>_ret

    # Static field DisplayMetrics.DENSITY_220
    @staticmethod
    def DENSITY_220() -> int:
        cdef JNIEnv* env = get_env()
        _ensure_ids_DisplayMetrics(env)
        cdef jint _ret = jnicore_GetStaticIntField(env, _cls_DisplayMetrics, _sf_DisplayMetrics_DENSITY_220)
        check_jni_exc(env)
        return <int>_ret

    # Static field DisplayMetrics.DENSITY_260
    @staticmethod
    def DENSITY_260() -> int:
        cdef JNIEnv* env = get_env()
        _ensure_ids_DisplayMetrics(env)
        cdef jint _ret = jnicore_GetStaticIntField(env, _cls_DisplayMetrics, _sf_DisplayMetrics_DENSITY_260)
        check_jni_exc(env)
        return <int>_ret

    # Static field DisplayMetrics.DENSITY_280
    @staticmethod
    def DENSITY_280() -> int:
        cdef JNIEnv* env = get_env()
        _ensure_ids_DisplayMetrics(env)
        cdef jint _ret = jnicore_GetStaticIntField(env, _cls_DisplayMetrics, _sf_DisplayMetrics_DENSITY_280)
        check_jni_exc(env)
        return <int>_ret

    # Static field DisplayMetrics.DENSITY_300
    @staticmethod
    def DENSITY_300() -> int:
        cdef JNIEnv* env = get_env()
        _ensure_ids_DisplayMetrics(env)
        cdef jint _ret = jnicore_GetStaticIntField(env, _cls_DisplayMetrics, _sf_DisplayMetrics_DENSITY_300)
        check_jni_exc(env)
        return <int>_ret

    # Static field DisplayMetrics.DENSITY_340
    @staticmethod
    def DENSITY_340() -> int:
        cdef JNIEnv* env = get_env()
        _ensure_ids_DisplayMetrics(env)
        cdef jint _ret = jnicore_GetStaticIntField(env, _cls_DisplayMetrics, _sf_DisplayMetrics_DENSITY_340)
        check_jni_exc(env)
        return <int>_ret

    # Static field DisplayMetrics.DENSITY_360
    @staticmethod
    def DENSITY_360() -> int:
        cdef JNIEnv* env = get_env()
        _ensure_ids_DisplayMetrics(env)
        cdef jint _ret = jnicore_GetStaticIntField(env, _cls_DisplayMetrics, _sf_DisplayMetrics_DENSITY_360)
        check_jni_exc(env)
        return <int>_ret

    # Static field DisplayMetrics.DENSITY_390
    @staticmethod
    def DENSITY_390() -> int:
        cdef JNIEnv* env = get_env()
        _ensure_ids_DisplayMetrics(env)
        cdef jint _ret = jnicore_GetStaticIntField(env, _cls_DisplayMetrics, _sf_DisplayMetrics_DENSITY_390)
        check_jni_exc(env)
        return <int>_ret

    # Static field DisplayMetrics.DENSITY_400
    @staticmethod
    def DENSITY_400() -> int:
        cdef JNIEnv* env = get_env()
        _ensure_ids_DisplayMetrics(env)
        cdef jint _ret = jnicore_GetStaticIntField(env, _cls_DisplayMetrics, _sf_DisplayMetrics_DENSITY_400)
        check_jni_exc(env)
        return <int>_ret

    # Static field DisplayMetrics.DENSITY_420
    @staticmethod
    def DENSITY_420() -> int:
        cdef JNIEnv* env = get_env()
        _ensure_ids_DisplayMetrics(env)
        cdef jint _ret = jnicore_GetStaticIntField(env, _cls_DisplayMetrics, _sf_DisplayMetrics_DENSITY_420)
        check_jni_exc(env)
        return <int>_ret

    # Static field DisplayMetrics.DENSITY_440
    @staticmethod
    def DENSITY_440() -> int:
        cdef JNIEnv* env = get_env()
        _ensure_ids_DisplayMetrics(env)
        cdef jint _ret = jnicore_GetStaticIntField(env, _cls_DisplayMetrics, _sf_DisplayMetrics_DENSITY_440)
        check_jni_exc(env)
        return <int>_ret

    # Static field DisplayMetrics.DENSITY_450
    @staticmethod
    def DENSITY_450() -> int:
        cdef JNIEnv* env = get_env()
        _ensure_ids_DisplayMetrics(env)
        cdef jint _ret = jnicore_GetStaticIntField(env, _cls_DisplayMetrics, _sf_DisplayMetrics_DENSITY_450)
        check_jni_exc(env)
        return <int>_ret

    # Static field DisplayMetrics.DENSITY_520
    @staticmethod
    def DENSITY_520() -> int:
        cdef JNIEnv* env = get_env()
        _ensure_ids_DisplayMetrics(env)
        cdef jint _ret = jnicore_GetStaticIntField(env, _cls_DisplayMetrics, _sf_DisplayMetrics_DENSITY_520)
        check_jni_exc(env)
        return <int>_ret

    # Static field DisplayMetrics.DENSITY_560
    @staticmethod
    def DENSITY_560() -> int:
        cdef JNIEnv* env = get_env()
        _ensure_ids_DisplayMetrics(env)
        cdef jint _ret = jnicore_GetStaticIntField(env, _cls_DisplayMetrics, _sf_DisplayMetrics_DENSITY_560)
        check_jni_exc(env)
        return <int>_ret

    # Static field DisplayMetrics.DENSITY_600
    @staticmethod
    def DENSITY_600() -> int:
        cdef JNIEnv* env = get_env()
        _ensure_ids_DisplayMetrics(env)
        cdef jint _ret = jnicore_GetStaticIntField(env, _cls_DisplayMetrics, _sf_DisplayMetrics_DENSITY_600)
        check_jni_exc(env)
        return <int>_ret

    # Static field DisplayMetrics.DENSITY_DEFAULT
    @staticmethod
    def DENSITY_DEFAULT() -> int:
        cdef JNIEnv* env = get_env()
        _ensure_ids_DisplayMetrics(env)
        cdef jint _ret = jnicore_GetStaticIntField(env, _cls_DisplayMetrics, _sf_DisplayMetrics_DENSITY_DEFAULT)
        check_jni_exc(env)
        return <int>_ret

    # Static field DisplayMetrics.DENSITY_DEVICE_STABLE
    @staticmethod
    def DENSITY_DEVICE_STABLE() -> int:
        cdef JNIEnv* env = get_env()
        _ensure_ids_DisplayMetrics(env)
        cdef jint _ret = jnicore_GetStaticIntField(env, _cls_DisplayMetrics, _sf_DisplayMetrics_DENSITY_DEVICE_STABLE)
        check_jni_exc(env)
        return <int>_ret

    # Static field DisplayMetrics.DENSITY_HIGH
    @staticmethod
    def DENSITY_HIGH() -> int:
        cdef JNIEnv* env = get_env()
        _ensure_ids_DisplayMetrics(env)
        cdef jint _ret = jnicore_GetStaticIntField(env, _cls_DisplayMetrics, _sf_DisplayMetrics_DENSITY_HIGH)
        check_jni_exc(env)
        return <int>_ret

    # Static field DisplayMetrics.DENSITY_LOW
    @staticmethod
    def DENSITY_LOW() -> int:
        cdef JNIEnv* env = get_env()
        _ensure_ids_DisplayMetrics(env)
        cdef jint _ret = jnicore_GetStaticIntField(env, _cls_DisplayMetrics, _sf_DisplayMetrics_DENSITY_LOW)
        check_jni_exc(env)
        return <int>_ret

    # Static field DisplayMetrics.DENSITY_MEDIUM
    @staticmethod
    def DENSITY_MEDIUM() -> int:
        cdef JNIEnv* env = get_env()
        _ensure_ids_DisplayMetrics(env)
        cdef jint _ret = jnicore_GetStaticIntField(env, _cls_DisplayMetrics, _sf_DisplayMetrics_DENSITY_MEDIUM)
        check_jni_exc(env)
        return <int>_ret

    # Static field DisplayMetrics.DENSITY_TV
    @staticmethod
    def DENSITY_TV() -> int:
        cdef JNIEnv* env = get_env()
        _ensure_ids_DisplayMetrics(env)
        cdef jint _ret = jnicore_GetStaticIntField(env, _cls_DisplayMetrics, _sf_DisplayMetrics_DENSITY_TV)
        check_jni_exc(env)
        return <int>_ret

    # Static field DisplayMetrics.DENSITY_XHIGH
    @staticmethod
    def DENSITY_XHIGH() -> int:
        cdef JNIEnv* env = get_env()
        _ensure_ids_DisplayMetrics(env)
        cdef jint _ret = jnicore_GetStaticIntField(env, _cls_DisplayMetrics, _sf_DisplayMetrics_DENSITY_XHIGH)
        check_jni_exc(env)
        return <int>_ret

    # Static field DisplayMetrics.DENSITY_XXHIGH
    @staticmethod
    def DENSITY_XXHIGH() -> int:
        cdef JNIEnv* env = get_env()
        _ensure_ids_DisplayMetrics(env)
        cdef jint _ret = jnicore_GetStaticIntField(env, _cls_DisplayMetrics, _sf_DisplayMetrics_DENSITY_XXHIGH)
        check_jni_exc(env)
        return <int>_ret

    # Static field DisplayMetrics.DENSITY_XXXHIGH
    @staticmethod
    def DENSITY_XXXHIGH() -> int:
        cdef JNIEnv* env = get_env()
        _ensure_ids_DisplayMetrics(env)
        cdef jint _ret = jnicore_GetStaticIntField(env, _cls_DisplayMetrics, _sf_DisplayMetrics_DENSITY_XXXHIGH)
        check_jni_exc(env)
        return <int>_ret

    @property
    def density(self) -> float:
        cdef JNIEnv* env = get_env()
        _ensure_ids_DisplayMetrics(env)
        cdef jfloat _ret = jnicore_GetFloatField(env, self._handle, _f_DisplayMetrics_density)
        check_jni_exc(env)
        return <double>_ret

    @density.setter
    def density(self, value) -> None:
        cdef JNIEnv* env = get_env()
        _ensure_ids_DisplayMetrics(env)
        jnicore_SetFloatField(env, self._handle, _f_DisplayMetrics_density, py_to_jfloat(value))
        check_jni_exc(env)

    @property
    def densityDpi(self) -> int:
        cdef JNIEnv* env = get_env()
        _ensure_ids_DisplayMetrics(env)
        cdef jint _ret = jnicore_GetIntField(env, self._handle, _f_DisplayMetrics_densityDpi)
        check_jni_exc(env)
        return <int>_ret

    @densityDpi.setter
    def densityDpi(self, value) -> None:
        cdef JNIEnv* env = get_env()
        _ensure_ids_DisplayMetrics(env)
        jnicore_SetIntField(env, self._handle, _f_DisplayMetrics_densityDpi, py_to_jint(value))
        check_jni_exc(env)

    @property
    def heightPixels(self) -> int:
        cdef JNIEnv* env = get_env()
        _ensure_ids_DisplayMetrics(env)
        cdef jint _ret = jnicore_GetIntField(env, self._handle, _f_DisplayMetrics_heightPixels)
        check_jni_exc(env)
        return <int>_ret

    @heightPixels.setter
    def heightPixels(self, value) -> None:
        cdef JNIEnv* env = get_env()
        _ensure_ids_DisplayMetrics(env)
        jnicore_SetIntField(env, self._handle, _f_DisplayMetrics_heightPixels, py_to_jint(value))
        check_jni_exc(env)

    @property
    def scaledDensity(self) -> float:
        cdef JNIEnv* env = get_env()
        _ensure_ids_DisplayMetrics(env)
        cdef jfloat _ret = jnicore_GetFloatField(env, self._handle, _f_DisplayMetrics_scaledDensity)
        check_jni_exc(env)
        return <double>_ret

    @scaledDensity.setter
    def scaledDensity(self, value) -> None:
        cdef JNIEnv* env = get_env()
        _ensure_ids_DisplayMetrics(env)
        jnicore_SetFloatField(env, self._handle, _f_DisplayMetrics_scaledDensity, py_to_jfloat(value))
        check_jni_exc(env)

    @property
    def widthPixels(self) -> int:
        cdef JNIEnv* env = get_env()
        _ensure_ids_DisplayMetrics(env)
        cdef jint _ret = jnicore_GetIntField(env, self._handle, _f_DisplayMetrics_widthPixels)
        check_jni_exc(env)
        return <int>_ret

    @widthPixels.setter
    def widthPixels(self, value) -> None:
        cdef JNIEnv* env = get_env()
        _ensure_ids_DisplayMetrics(env)
        jnicore_SetIntField(env, self._handle, _f_DisplayMetrics_widthPixels, py_to_jint(value))
        check_jni_exc(env)

    @property
    def xdpi(self) -> float:
        cdef JNIEnv* env = get_env()
        _ensure_ids_DisplayMetrics(env)
        cdef jfloat _ret = jnicore_GetFloatField(env, self._handle, _f_DisplayMetrics_xdpi)
        check_jni_exc(env)
        return <double>_ret

    @xdpi.setter
    def xdpi(self, value) -> None:
        cdef JNIEnv* env = get_env()
        _ensure_ids_DisplayMetrics(env)
        jnicore_SetFloatField(env, self._handle, _f_DisplayMetrics_xdpi, py_to_jfloat(value))
        check_jni_exc(env)

    @property
    def ydpi(self) -> float:
        cdef JNIEnv* env = get_env()
        _ensure_ids_DisplayMetrics(env)
        cdef jfloat _ret = jnicore_GetFloatField(env, self._handle, _f_DisplayMetrics_ydpi)
        check_jni_exc(env)
        return <double>_ret

    @ydpi.setter
    def ydpi(self, value) -> None:
        cdef JNIEnv* env = get_env()
        _ensure_ids_DisplayMetrics(env)
        jnicore_SetFloatField(env, self._handle, _f_DisplayMetrics_ydpi, py_to_jfloat(value))
        check_jni_exc(env)

    cdef jboolean _equals(self, JNIEnv* env, jobject p0) except *:
        _ensure_ids_DisplayMetrics(env)
        cdef jvalue _args[1]
        _args[0].l = p0
        cdef jboolean _ret = jnicore_CallBooleanMethodA(env, self._handle, _m_DisplayMetrics_equals_0, _args)
        check_jni_exc(env)
        return _ret

    def equals(self, p0) -> bool:
        cdef JNIEnv* env = get_env()
        cdef jboolean _ret = 0
        cdef jobject _h0 = (<JavaObject?>p0)._handle if p0 is not None else <jobject>NULL
        _ret = self._equals(env, _h0)
        return jboolean_to_py(_ret)

    cdef jboolean _equals_0(self, JNIEnv* env, jobject p0) except *:
        _ensure_ids_DisplayMetrics(env)
        cdef jvalue _args[1]
        _args[0].l = p0
        cdef jboolean _ret = jnicore_CallBooleanMethodA(env, self._handle, _m_DisplayMetrics_equals_0, _args)
        check_jni_exc(env)
        return _ret

    def equals_0(self, p0) -> bool:
        cdef JNIEnv* env = get_env()
        cdef jboolean _ret = 0
        cdef jobject _h0 = (<JavaObject?>p0)._handle if p0 is not None else <jobject>NULL
        _ret = self._equals_0(env, _h0)
        return jboolean_to_py(_ret)

    cdef jboolean _equals_1(self, JNIEnv* env, jobject p0) except *:
        _ensure_ids_DisplayMetrics(env)
        cdef jvalue _args[1]
        _args[0].l = p0
        cdef jboolean _ret = jnicore_CallBooleanMethodA(env, self._handle, _m_DisplayMetrics_equals_1, _args)
        check_jni_exc(env)
        return _ret

    def equals_1(self, p0) -> bool:
        cdef JNIEnv* env = get_env()
        cdef jboolean _ret = 0
        cdef jobject _h0 = (<JavaObject?>p0)._handle if p0 is not None else <jobject>NULL
        _ret = self._equals_1(env, _h0)
        return jboolean_to_py(_ret)

    cdef jstring _toString(self, JNIEnv* env) except? NULL:
        _ensure_ids_DisplayMetrics(env)
        cdef jvalue _args[1]  # zero-arg call; _args ignored by JNI
        cdef jstring _ret = <jstring>jnicore_CallObjectMethodA(env, self._handle, _m_DisplayMetrics_toString_0, _args)
        check_jni_exc(env)
        return <jstring>_ret

    def toString(self) -> str:
        cdef JNIEnv* env = get_env()
        cdef jstring _ret = NULL
        _ret = self._toString(env)
        return py_str(env, _ret)

    cdef jstring _toString_0(self, JNIEnv* env) except? NULL:
        _ensure_ids_DisplayMetrics(env)
        cdef jvalue _args[1]  # zero-arg call; _args ignored by JNI
        cdef jstring _ret = <jstring>jnicore_CallObjectMethodA(env, self._handle, _m_DisplayMetrics_toString_0, _args)
        check_jni_exc(env)
        return <jstring>_ret

    def toString_0(self) -> str:
        cdef JNIEnv* env = get_env()
        cdef jstring _ret = NULL
        _ret = self._toString_0(env)
        return py_str(env, _ret)

    cdef jint _hashCode(self, JNIEnv* env) except *:
        _ensure_ids_DisplayMetrics(env)
        cdef jvalue _args[1]  # zero-arg call; _args ignored by JNI
        cdef jint _ret = jnicore_CallIntMethodA(env, self._handle, _m_DisplayMetrics_hashCode_0, _args)
        check_jni_exc(env)
        return _ret

    def hashCode(self) -> int:
        cdef JNIEnv* env = get_env()
        cdef jint _ret = 0
        _ret = self._hashCode(env)
        return <int>_ret

    cdef jint _hashCode_0(self, JNIEnv* env) except *:
        _ensure_ids_DisplayMetrics(env)
        cdef jvalue _args[1]  # zero-arg call; _args ignored by JNI
        cdef jint _ret = jnicore_CallIntMethodA(env, self._handle, _m_DisplayMetrics_hashCode_0, _args)
        check_jni_exc(env)
        return _ret

    def hashCode_0(self) -> int:
        cdef JNIEnv* env = get_env()
        cdef jint _ret = 0
        _ret = self._hashCode_0(env)
        return <int>_ret

    cdef void _setTo(self, JNIEnv* env, jobject p0) except *:
        _ensure_ids_DisplayMetrics(env)
        cdef jvalue _args[1]
        _args[0].l = p0
        jnicore_CallVoidMethodA(env, self._handle, _m_DisplayMetrics_setTo_0, _args)
        check_jni_exc(env)

    def setTo(self, p0) -> None:
        cdef JNIEnv* env = get_env()
        cdef jobject _h0 = (<JavaObject?>p0)._handle if p0 is not None else <jobject>NULL
        self._setTo(env, _h0)

    cdef void _setTo_0(self, JNIEnv* env, jobject p0) except *:
        _ensure_ids_DisplayMetrics(env)
        cdef jvalue _args[1]
        _args[0].l = p0
        jnicore_CallVoidMethodA(env, self._handle, _m_DisplayMetrics_setTo_0, _args)
        check_jni_exc(env)

    def setTo_0(self, p0) -> None:
        cdef JNIEnv* env = get_env()
        cdef jobject _h0 = (<JavaObject?>p0)._handle if p0 is not None else <jobject>NULL
        self._setTo_0(env, _h0)

    cdef void _setToDefaults(self, JNIEnv* env) except *:
        _ensure_ids_DisplayMetrics(env)
        cdef jvalue _args[1]  # zero-arg call; _args ignored by JNI
        jnicore_CallVoidMethodA(env, self._handle, _m_DisplayMetrics_setToDefaults_0, _args)
        check_jni_exc(env)

    def setToDefaults(self) -> None:
        cdef JNIEnv* env = get_env()
        self._setToDefaults(env)

    cdef void _setToDefaults_0(self, JNIEnv* env) except *:
        _ensure_ids_DisplayMetrics(env)
        cdef jvalue _args[1]  # zero-arg call; _args ignored by JNI
        jnicore_CallVoidMethodA(env, self._handle, _m_DisplayMetrics_setToDefaults_0, _args)
        check_jni_exc(env)

    def setToDefaults_0(self) -> None:
        cdef JNIEnv* env = get_env()
        self._setToDefaults_0(env)

    @staticmethod
    def from_java_object(obj) -> object:
        """Wrap a plain JavaObject as DisplayMetrics (no JNI type check)."""
        cdef JNIEnv* env = get_env()
        cdef DisplayMetrics inst = DisplayMetrics.__new__(DisplayMetrics)
        cdef jobject global_ref = jnicore_NewGlobalRef(env, (<JavaObject?>obj)._handle)
        inst._adopt_global(env, global_ref)
        return inst

