from typing import Any, ClassVar, overload
from android.gesture.GestureStroke import GestureStroke
from android.graphics.Bitmap import Bitmap
from android.graphics.Path import Path
from android.graphics.RectF import RectF
from android.os.Parcel import Parcel

class Gesture:
    CREATOR: ClassVar[Any]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    def __init__(self) -> None: ...
    def getStrokesCount(self) -> int: ...
    def getBoundingBox(self) -> RectF: ...
    @overload
    def toBitmap(self, p0: int, p1: int, p2: int, p3: int, p4: int) -> Bitmap: ...
    @overload
    def toBitmap(self, p0: int, p1: int, p2: int, p3: int) -> Bitmap: ...
    def getStrokes(self) -> list: ...
    def addStroke(self, p0: GestureStroke) -> None: ...
    def clone(self) -> Any: ...
    def getLength(self) -> float: ...
    def getID(self) -> int: ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
    @overload
    def toPath(self, p0: Path) -> Path: ...
    @overload
    def toPath(self) -> Path: ...
    @overload
    def toPath(self, p0: Path, p1: int, p2: int, p3: int, p4: int) -> Path: ...
    @overload
    def toPath(self, p0: int, p1: int, p2: int, p3: int) -> Path: ...
