from typing import Any, ClassVar, overload
from android.content.res.Resources import Resources
from android.graphics.Canvas import Canvas
from android.graphics.drawable.Drawable import Drawable
from android.util.AttributeSet import AttributeSet
from org.xmlpull.v1.XmlPullParser import XmlPullParser

class ClipDrawable:
    HORIZONTAL: ClassVar[int]
    VERTICAL: ClassVar[int]
    def __init__(self, p0: Drawable, p1: int, p2: int) -> None: ...
    def inflate(self, p0: Resources, p1: XmlPullParser, p2: AttributeSet, p3: Any) -> None: ...
    def draw(self, p0: Canvas) -> None: ...
    def applyTheme(self, p0: Any) -> None: ...
    def getOpacity(self) -> int: ...
