from typing import Any, ClassVar, overload
from android.content.res.ColorStateList import ColorStateList
from android.content.res.Resources import Resources
from android.graphics.BlendMode import BlendMode
from android.graphics.Canvas import Canvas
from android.graphics.ColorFilter import ColorFilter
from android.graphics.Outline import Outline
from android.graphics.Rect import Rect
from android.graphics.drawable.Drawable import Drawable
from android.util.AttributeSet import AttributeSet
from java.lang.Runnable import Runnable
from org.xmlpull.v1.XmlPullParser import XmlPullParser

class LayerDrawable:
    INSET_UNDEFINED: ClassVar[int]
    PADDING_MODE_NEST: ClassVar[int]
    PADDING_MODE_STACK: ClassVar[int]
    def __init__(self, p0: Any) -> None: ...
    def setDrawable(self, p0: int, p1: Drawable) -> None: ...
    def getEndPadding(self) -> int: ...
    def findIndexByLayerId(self, p0: int) -> int: ...
    def getLayerInsetRight(self, p0: int) -> int: ...
    def getLeftPadding(self) -> int: ...
    def getLayerWidth(self, p0: int) -> int: ...
    def getLayerInsetTop(self, p0: int) -> int: ...
    def getLayerGravity(self, p0: int) -> int: ...
    def getLayerHeight(self, p0: int) -> int: ...
    def getLayerInsetLeft(self, p0: int) -> int: ...
    def getLayerInsetStart(self, p0: int) -> int: ...
    def getLayerInsetEnd(self, p0: int) -> int: ...
    def addLayer(self, p0: Drawable) -> int: ...
    def findDrawableByLayerId(self, p0: int) -> Drawable: ...
    def getLayerInsetBottom(self, p0: int) -> int: ...
    def getNumberOfLayers(self) -> int: ...
    def getPaddingMode(self) -> int: ...
    def getRightPadding(self) -> int: ...
    def getStartPadding(self) -> int: ...
    def setDrawableByLayerId(self, p0: int, p1: Drawable) -> bool: ...
    def setLayerGravity(self, p0: int, p1: int) -> None: ...
    def setLayerHeight(self, p0: int, p1: int) -> None: ...
    def setLayerInset(self, p0: int, p1: int, p2: int, p3: int, p4: int) -> None: ...
    def setLayerInsetBottom(self, p0: int, p1: int) -> None: ...
    def setLayerInsetEnd(self, p0: int, p1: int) -> None: ...
    def setLayerInsetLeft(self, p0: int, p1: int) -> None: ...
    def setLayerInsetRelative(self, p0: int, p1: int, p2: int, p3: int, p4: int) -> None: ...
    def setLayerInsetRight(self, p0: int, p1: int) -> None: ...
    def setLayerInsetStart(self, p0: int, p1: int) -> None: ...
    def setLayerInsetTop(self, p0: int, p1: int) -> None: ...
    def setLayerSize(self, p0: int, p1: int, p2: int) -> None: ...
    def setLayerWidth(self, p0: int, p1: int) -> None: ...
    def setOpacity(self, p0: int) -> None: ...
    def setPaddingMode(self, p0: int) -> None: ...
    def inflate(self, p0: Resources, p1: XmlPullParser, p2: AttributeSet, p3: Any) -> None: ...
    def getId(self, p0: int) -> int: ...
    def setAlpha(self, p0: int) -> None: ...
    def setColorFilter(self, p0: ColorFilter) -> None: ...
    def invalidateDrawable(self, p0: Drawable) -> None: ...
    def draw(self, p0: Canvas) -> None: ...
    def getAlpha(self) -> int: ...
    def scheduleDrawable(self, p0: Drawable, p1: Runnable, p2: int) -> None: ...
    def setId(self, p0: int, p1: int) -> None: ...
    def setPadding(self, p0: int, p1: int, p2: int, p3: int) -> None: ...
    def setPaddingRelative(self, p0: int, p1: int, p2: int, p3: int) -> None: ...
    def unscheduleDrawable(self, p0: Drawable, p1: Runnable) -> None: ...
    def getDrawable(self, p0: int) -> Drawable: ...
    def getChangingConfigurations(self) -> int: ...
    def getBottomPadding(self) -> int: ...
    def getTopPadding(self) -> int: ...
    def canApplyTheme(self) -> bool: ...
    def applyTheme(self, p0: Any) -> None: ...
    def getConstantState(self) -> Any: ...
    def getHotspotBounds(self, p0: Rect) -> None: ...
    def getIntrinsicHeight(self) -> int: ...
    def getIntrinsicWidth(self) -> int: ...
    def getOpacity(self) -> int: ...
    def getOutline(self, p0: Outline) -> None: ...
    def getPadding(self, p0: Rect) -> bool: ...
    def hasFocusStateSpecified(self) -> bool: ...
    def isAutoMirrored(self) -> bool: ...
    def isProjected(self) -> bool: ...
    def isStateful(self) -> bool: ...
    def jumpToCurrentState(self) -> None: ...
    def mutate(self) -> Drawable: ...
    def onLayoutDirectionChanged(self, p0: int) -> bool: ...
    def setAutoMirrored(self, p0: bool) -> None: ...
    def setDither(self, p0: bool) -> None: ...
    def setHotspot(self, p0: float, p1: float) -> None: ...
    def setHotspotBounds(self, p0: int, p1: int, p2: int, p3: int) -> None: ...
    def setTintBlendMode(self, p0: BlendMode) -> None: ...
    def setTintList(self, p0: ColorStateList) -> None: ...
    def setVisible(self, p0: bool, p1: bool) -> bool: ...
