from typing import Any, ClassVar, overload
from android.graphics.Canvas import Canvas
from android.graphics.Outline import Outline
from android.graphics.Paint import Paint
from android.graphics.drawable.shapes.Shape import Shape

class RectShape:
    def __init__(self) -> None: ...
    def equals(self, p0: Any) -> bool: ...
    def hashCode(self) -> int: ...
    @overload
    def clone(self) -> "RectShape": ...
    @overload
    def clone(self) -> Shape: ...
    @overload
    def clone(self) -> Any: ...
    def draw(self, p0: Canvas, p1: Paint) -> None: ...
    def getOutline(self, p0: Outline) -> None: ...

from typing import Any, ClassVar, overload
from android.graphics.Canvas import Canvas
from android.graphics.Outline import Outline
from android.graphics.Paint import Paint
from android.graphics.drawable.shapes.RectShape import RectShape
from android.graphics.drawable.shapes.Shape import Shape

class OvalShape:
    def __init__(self) -> None: ...
    @overload
    def clone(self) -> Any: ...
    @overload
    def clone(self) -> RectShape: ...
    @overload
    def clone(self) -> Shape: ...
    @overload
    def clone(self) -> "OvalShape": ...
    def draw(self, p0: Canvas, p1: Paint) -> None: ...
    def getOutline(self, p0: Outline) -> None: ...

from typing import Any, ClassVar, overload
from android.graphics.Canvas import Canvas
from android.graphics.Paint import Paint
from android.graphics.Path import Path
from android.graphics.drawable.shapes.Shape import Shape

class PathShape:
    def __init__(self, p0: Path, p1: float, p2: float) -> None: ...
    def equals(self, p0: Any) -> bool: ...
    def hashCode(self) -> int: ...
    @overload
    def clone(self) -> Any: ...
    @overload
    def clone(self) -> "PathShape": ...
    @overload
    def clone(self) -> Shape: ...
    def draw(self, p0: Canvas, p1: Paint) -> None: ...

from typing import Any, ClassVar, overload
from android.graphics.Canvas import Canvas
from android.graphics.Outline import Outline
from android.graphics.Paint import Paint

class Shape:
    def __init__(self) -> None: ...
    def equals(self, p0: Any) -> bool: ...
    def hashCode(self) -> int: ...
    @overload
    def clone(self) -> Any: ...
    @overload
    def clone(self) -> "Shape": ...
    def resize(self, p0: float, p1: float) -> None: ...
    def draw(self, p0: Canvas, p1: Paint) -> None: ...
    def getHeight(self) -> float: ...
    def getWidth(self) -> float: ...
    def getOutline(self, p0: Outline) -> None: ...
    def hasAlpha(self) -> bool: ...

from typing import Any, ClassVar, overload
from android.graphics.Canvas import Canvas
from android.graphics.Outline import Outline
from android.graphics.Paint import Paint
from android.graphics.RectF import RectF
from android.graphics.drawable.shapes.RectShape import RectShape
from android.graphics.drawable.shapes.Shape import Shape

class RoundRectShape:
    def __init__(self, p0: Any, p1: RectF, p2: Any) -> None: ...
    def equals(self, p0: Any) -> bool: ...
    def hashCode(self) -> int: ...
    @overload
    def clone(self) -> Shape: ...
    @overload
    def clone(self) -> Any: ...
    @overload
    def clone(self) -> "RoundRectShape": ...
    @overload
    def clone(self) -> RectShape: ...
    def draw(self, p0: Canvas, p1: Paint) -> None: ...
    def getOutline(self, p0: Outline) -> None: ...

from typing import Any, ClassVar, overload
from android.graphics.Canvas import Canvas
from android.graphics.Outline import Outline
from android.graphics.Paint import Paint
from android.graphics.drawable.shapes.RectShape import RectShape
from android.graphics.drawable.shapes.Shape import Shape

class ArcShape:
    def __init__(self, p0: float, p1: float) -> None: ...
    def getSweepAngle(self) -> float: ...
    def getStartAngle(self) -> float: ...
    def equals(self, p0: Any) -> bool: ...
    def hashCode(self) -> int: ...
    @overload
    def clone(self) -> Shape: ...
    @overload
    def clone(self) -> Any: ...
    @overload
    def clone(self) -> RectShape: ...
    @overload
    def clone(self) -> "ArcShape": ...
    def draw(self, p0: Canvas, p1: Paint) -> None: ...
    def getOutline(self, p0: Outline) -> None: ...

