from typing import Any, ClassVar, overload

class Level:
    OFF: ClassVar["Level"]
    SEVERE: ClassVar["Level"]
    WARNING: ClassVar["Level"]
    INFO: ClassVar["Level"]
    CONFIG: ClassVar["Level"]
    FINE: ClassVar["Level"]
    FINER: ClassVar["Level"]
    FINEST: ClassVar["Level"]
    ALL: ClassVar["Level"]
    def getResourceBundleName(self) -> str: ...
    def getName(self) -> str: ...
    def equals(self, p0: Any) -> bool: ...
    def toString(self) -> str: ...
    def hashCode(self) -> int: ...
    def intValue(self) -> int: ...
    @staticmethod
    def parse(p0: str) -> "Level": ...
    def getLocalizedName(self) -> str: ...
