from typing import Any, ClassVar, overload

class LoggingMXBean:
    def getLoggerNames(self) -> list: ...
    def getLoggerLevel(self, p0: str) -> str: ...
    def setLoggerLevel(self, p0: str, p1: str) -> None: ...
    def getParentLoggerName(self, p0: str) -> str: ...
