from typing import Any, ClassVar, overload
from java.lang.Throwable import Throwable
from java.time.Instant import Instant
from java.util.ResourceBundle import ResourceBundle
from java.util.logging.Level import Level

class LogRecord:
    def __init__(self, p0: Level, p1: str) -> None: ...
    def setMessage(self, p0: str) -> None: ...
    def setSequenceNumber(self, p0: int) -> None: ...
    def getSequenceNumber(self) -> int: ...
    def setParameters(self, p0: Any) -> None: ...
    def getMessage(self) -> str: ...
    def getResourceBundleName(self) -> str: ...
    def setLoggerName(self, p0: str) -> None: ...
    def setResourceBundleName(self, p0: str) -> None: ...
    def setResourceBundle(self, p0: ResourceBundle) -> None: ...
    def setThrown(self, p0: Throwable) -> None: ...
    def setSourceClassName(self, p0: str) -> None: ...
    def setSourceMethodName(self, p0: str) -> None: ...
    def getResourceBundle(self) -> ResourceBundle: ...
    def getLoggerName(self) -> str: ...
    def getSourceClassName(self) -> str: ...
    def getSourceMethodName(self) -> str: ...
    def getThreadID(self) -> int: ...
    def setThreadID(self, p0: int) -> None: ...
    def getLongThreadID(self) -> int: ...
    def setLongThreadID(self, p0: int) -> "LogRecord": ...
    def getInstant(self) -> Instant: ...
    def setInstant(self, p0: Instant) -> None: ...
    def getThrown(self) -> Throwable: ...
    def getParameters(self) -> Any: ...
    def getMillis(self) -> int: ...
    def setMillis(self, p0: int) -> None: ...
    def setLevel(self, p0: Level) -> None: ...
    def getLevel(self) -> Level: ...
