from typing import Any, ClassVar, overload
from java.util.logging.LogRecord import LogRecord

class SocketHandler:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, p0: str, p1: int) -> None: ...
    def close(self) -> None: ...
    def publish(self, p0: LogRecord) -> None: ...
