from typing import Any, ClassVar, overload
from java.util.Comparator import Comparator
from java.util.Deque import Deque
from java.util.Enumeration import Enumeration
from java.util.Iterator import Iterator
from java.util.ListIterator import ListIterator
from java.util.NavigableMap import NavigableMap
from java.util.NavigableSet import NavigableSet
from java.util.Queue import Queue
from java.util.Random import Random
from java.util.SequencedCollection import SequencedCollection
from java.util.SequencedMap import SequencedMap
from java.util.SequencedSet import SequencedSet
from java.util.SortedMap import SortedMap
from java.util.SortedSet import SortedSet
from java.util.random.RandomGenerator import RandomGenerator

class Collections:
    EMPTY_SET: ClassVar[set]
    EMPTY_LIST: ClassVar[list]
    EMPTY_MAP: ClassVar[dict]
    @overload
    @staticmethod
    def min(p0: list) -> Any: ...
    @overload
    @staticmethod
    def min(p0: list, p1: Comparator) -> Any: ...
    @overload
    @staticmethod
    def max(p0: list, p1: Comparator) -> Any: ...
    @overload
    @staticmethod
    def max(p0: list) -> Any: ...
    @staticmethod
    def reverse(p0: list) -> None: ...
    @staticmethod
    def replaceAll(p0: list, p1: Any, p2: Any) -> bool: ...
    @staticmethod
    def fill(p0: list, p1: Any) -> None: ...
    @staticmethod
    def list(p0: Enumeration) -> list: ...
    @staticmethod
    def addAll(p0: list, p1: Any) -> bool: ...
    @staticmethod
    def emptyEnumeration() -> Enumeration: ...
    @staticmethod
    def newSetFromMap(p0: dict) -> set: ...
    @staticmethod
    def emptyList() -> list: ...
    @overload
    @staticmethod
    def sort(p0: list) -> None: ...
    @overload
    @staticmethod
    def sort(p0: list, p1: Comparator) -> None: ...
    @staticmethod
    def unmodifiableSet(p0: set) -> set: ...
    @staticmethod
    def enumeration(p0: list) -> Enumeration: ...
    @staticmethod
    def synchronizedSet(p0: set) -> set: ...
    @staticmethod
    def synchronizedCollection(p0: list) -> list: ...
    @staticmethod
    def emptyIterator() -> Iterator: ...
    @staticmethod
    def copy(p0: list, p1: list) -> None: ...
    @overload
    @staticmethod
    def reverseOrder(p0: Comparator) -> Comparator: ...
    @overload
    @staticmethod
    def reverseOrder() -> Comparator: ...
    @staticmethod
    def unmodifiableMap(p0: dict) -> dict: ...
    @staticmethod
    def rotate(p0: list, p1: int) -> None: ...
    @staticmethod
    def indexOfSubList(p0: list, p1: list) -> int: ...
    @staticmethod
    def lastIndexOfSubList(p0: list, p1: list) -> int: ...
    @staticmethod
    def unmodifiableCollection(p0: list) -> list: ...
    @staticmethod
    def unmodifiableSequencedCollection(p0: SequencedCollection) -> SequencedCollection: ...
    @staticmethod
    def unmodifiableSequencedSet(p0: SequencedSet) -> SequencedSet: ...
    @staticmethod
    def unmodifiableSortedSet(p0: SortedSet) -> SortedSet: ...
    @staticmethod
    def unmodifiableNavigableSet(p0: NavigableSet) -> NavigableSet: ...
    @staticmethod
    def unmodifiableList(p0: list) -> list: ...
    @staticmethod
    def unmodifiableSequencedMap(p0: SequencedMap) -> SequencedMap: ...
    @staticmethod
    def unmodifiableSortedMap(p0: SortedMap) -> SortedMap: ...
    @staticmethod
    def unmodifiableNavigableMap(p0: NavigableMap) -> NavigableMap: ...
    @staticmethod
    def synchronizedSortedSet(p0: SortedSet) -> SortedSet: ...
    @staticmethod
    def synchronizedNavigableSet(p0: NavigableSet) -> NavigableSet: ...
    @staticmethod
    def synchronizedList(p0: list) -> list: ...
    @staticmethod
    def synchronizedMap(p0: dict) -> dict: ...
    @staticmethod
    def synchronizedSortedMap(p0: SortedMap) -> SortedMap: ...
    @staticmethod
    def synchronizedNavigableMap(p0: NavigableMap) -> NavigableMap: ...
    @staticmethod
    def checkedCollection(p0: list, p1: type) -> list: ...
    @staticmethod
    def checkedQueue(p0: Queue, p1: type) -> Queue: ...
    @staticmethod
    def checkedSet(p0: set, p1: type) -> set: ...
    @staticmethod
    def checkedSortedSet(p0: SortedSet, p1: type) -> SortedSet: ...
    @staticmethod
    def checkedNavigableSet(p0: NavigableSet, p1: type) -> NavigableSet: ...
    @staticmethod
    def checkedList(p0: list, p1: type) -> list: ...
    @staticmethod
    def checkedMap(p0: dict, p1: type, p2: type) -> dict: ...
    @staticmethod
    def checkedSortedMap(p0: SortedMap, p1: type, p2: type) -> SortedMap: ...
    @staticmethod
    def checkedNavigableMap(p0: NavigableMap, p1: type, p2: type) -> NavigableMap: ...
    @staticmethod
    def emptyListIterator() -> ListIterator: ...
    @staticmethod
    def emptySet() -> set: ...
    @staticmethod
    def emptySortedSet() -> SortedSet: ...
    @staticmethod
    def emptyNavigableSet() -> NavigableSet: ...
    @staticmethod
    def emptyMap() -> dict: ...
    @staticmethod
    def emptySortedMap() -> SortedMap: ...
    @staticmethod
    def emptyNavigableMap() -> NavigableMap: ...
    @staticmethod
    def singleton(p0: Any) -> set: ...
    @staticmethod
    def singletonList(p0: Any) -> list: ...
    @staticmethod
    def singletonMap(p0: Any, p1: Any) -> dict: ...
    @staticmethod
    def frequency(p0: list, p1: Any) -> int: ...
    @staticmethod
    def disjoint(p0: list, p1: list) -> bool: ...
    @staticmethod
    def newSequencedSetFromMap(p0: SequencedMap) -> SequencedSet: ...
    @staticmethod
    def asLifoQueue(p0: Deque) -> Queue: ...
    @staticmethod
    def nCopies(p0: int, p1: Any) -> list: ...
    @staticmethod
    def swap(p0: list, p1: int, p2: int) -> None: ...
    @overload
    @staticmethod
    def binarySearch(p0: list, p1: Any, p2: Comparator) -> int: ...
    @overload
    @staticmethod
    def binarySearch(p0: list, p1: Any) -> int: ...
    @overload
    @staticmethod
    def shuffle(p0: list, p1: Random) -> None: ...
    @overload
    @staticmethod
    def shuffle(p0: list, p1: RandomGenerator) -> None: ...
    @overload
    @staticmethod
    def shuffle(p0: list) -> None: ...
