from typing import Any, ClassVar, overload
from java.util.Iterator import Iterator
from java.util.SequencedCollection import SequencedCollection

class Deque:
    @overload
    def remove(self, p0: Any) -> bool: ...
    @overload
    def remove(self) -> Any: ...
    def size(self) -> int: ...
    def add(self, p0: Any) -> bool: ...
    def iterator(self) -> Iterator: ...
    def contains(self, p0: Any) -> bool: ...
    def addAll(self, p0: list) -> bool: ...
    @overload
    def reversed(self) -> SequencedCollection: ...
    @overload
    def reversed(self) -> "Deque": ...
    def getFirst(self) -> Any: ...
    def getLast(self) -> Any: ...
    def element(self) -> Any: ...
    def addFirst(self, p0: Any) -> None: ...
    def addLast(self, p0: Any) -> None: ...
    def removeFirst(self) -> Any: ...
    def removeLast(self) -> Any: ...
    def poll(self) -> Any: ...
    def push(self, p0: Any) -> None: ...
    def pop(self) -> Any: ...
    def peek(self) -> Any: ...
    def pollFirst(self) -> Any: ...
    def pollLast(self) -> Any: ...
    def offerLast(self, p0: Any) -> bool: ...
    def peekFirst(self) -> Any: ...
    def removeFirstOccurrence(self, p0: Any) -> bool: ...
    def offerFirst(self, p0: Any) -> bool: ...
    def peekLast(self) -> Any: ...
    def removeLastOccurrence(self, p0: Any) -> bool: ...
    def offer(self, p0: Any) -> bool: ...
    def descendingIterator(self) -> Iterator: ...
