from typing import Any, ClassVar, overload
from java.util.random.RandomGenerator import RandomGenerator
from java.util.stream.DoubleStream import DoubleStream
from java.util.stream.IntStream import IntStream
from java.util.stream.LongStream import LongStream

class Random:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, p0: int) -> None: ...
    def nextBoolean(self) -> bool: ...
    def nextLong(self) -> int: ...
    def nextFloat(self) -> float: ...
    @overload
    def ints(self, p0: int, p1: int, p2: int) -> IntStream: ...
    @overload
    def ints(self, p0: int, p1: int) -> IntStream: ...
    @overload
    def ints(self, p0: int) -> IntStream: ...
    @overload
    def ints(self) -> IntStream: ...
    @overload
    def doubles(self, p0: int) -> DoubleStream: ...
    @overload
    def doubles(self) -> DoubleStream: ...
    @overload
    def doubles(self, p0: float, p1: float) -> DoubleStream: ...
    @overload
    def doubles(self, p0: int, p1: float, p2: float) -> DoubleStream: ...
    def setSeed(self, p0: int) -> None: ...
    def nextGaussian(self) -> float: ...
    @staticmethod
    def from_(p0: RandomGenerator) -> "Random": ...
    def nextDouble(self) -> float: ...
    @overload
    def longs(self, p0: int, p1: int, p2: int) -> LongStream: ...
    @overload
    def longs(self, p0: int, p1: int) -> LongStream: ...
    @overload
    def longs(self) -> LongStream: ...
    @overload
    def longs(self, p0: int) -> LongStream: ...
    @overload
    def nextInt(self, p0: int) -> int: ...
    @overload
    def nextInt(self) -> int: ...
    def nextBytes(self, p0: Any) -> None: ...
