from typing import Any, ClassVar, overload
from java.util.Date import Date
from java.util.TimeZone import TimeZone

class SimpleTimeZone:
    WALL_TIME: ClassVar[int]
    STANDARD_TIME: ClassVar[int]
    UTC_TIME: ClassVar[int]
    SHORT: ClassVar[int]
    LONG: ClassVar[int]
    @overload
    def __init__(self, p0: int, p1: str, p2: int, p3: int, p4: int, p5: int, p6: int, p7: int, p8: int, p9: int, p10: int, p11: int, p12: int) -> None: ...
    @overload
    def __init__(self, p0: int, p1: str, p2: int, p3: int, p4: int, p5: int, p6: int, p7: int, p8: int, p9: int, p10: int) -> None: ...
    @overload
    def __init__(self, p0: int, p1: str, p2: int, p3: int, p4: int, p5: int, p6: int, p7: int, p8: int, p9: int) -> None: ...
    @overload
    def __init__(self, p0: int, p1: str) -> None: ...
    def equals(self, p0: Any) -> bool: ...
    def toString(self) -> str: ...
    def hashCode(self) -> int: ...
    def clone(self) -> Any: ...
    @overload
    def setStartRule(self, p0: int, p1: int, p2: int, p3: int) -> None: ...
    @overload
    def setStartRule(self, p0: int, p1: int, p2: int, p3: int, p4: bool) -> None: ...
    @overload
    def setStartRule(self, p0: int, p1: int, p2: int) -> None: ...
    @overload
    def setEndRule(self, p0: int, p1: int, p2: int, p3: int) -> None: ...
    @overload
    def setEndRule(self, p0: int, p1: int, p2: int) -> None: ...
    @overload
    def setEndRule(self, p0: int, p1: int, p2: int, p3: int, p4: bool) -> None: ...
    def setStartYear(self, p0: int) -> None: ...
    def setDSTSavings(self, p0: int) -> None: ...
    @overload
    def getOffset(self, p0: int, p1: int, p2: int, p3: int, p4: int, p5: int) -> int: ...
    @overload
    def getOffset(self, p0: int) -> int: ...
    def inDaylightTime(self, p0: Date) -> bool: ...
    def getRawOffset(self) -> int: ...
    def getDSTSavings(self) -> int: ...
    def useDaylightTime(self) -> bool: ...
    def setRawOffset(self, p0: int) -> None: ...
    def observesDaylightTime(self) -> bool: ...
    def hasSameRules(self, p0: TimeZone) -> bool: ...
