from typing import Any, ClassVar, overload
from java.time.ZoneId import ZoneId
from java.util.Date import Date
from java.util.Locale import Locale

class TimeZone:
    SHORT: ClassVar[int]
    LONG: ClassVar[int]
    def __init__(self) -> None: ...
    def clone(self) -> Any: ...
    @staticmethod
    def getDefault() -> "TimeZone": ...
    @overload
    def getOffset(self, p0: int, p1: int, p2: int, p3: int, p4: int, p5: int) -> int: ...
    @overload
    def getOffset(self, p0: int) -> int: ...
    @staticmethod
    def setDefault(p0: "TimeZone") -> None: ...
    def getID(self) -> str: ...
    @overload
    def getDisplayName(self, p0: bool, p1: int) -> str: ...
    @overload
    def getDisplayName(self, p0: bool, p1: int, p2: Locale) -> str: ...
    @overload
    def getDisplayName(self) -> str: ...
    @overload
    def getDisplayName(self, p0: Locale) -> str: ...
    @overload
    @staticmethod
    def getTimeZone(p0: str) -> "TimeZone": ...
    @overload
    @staticmethod
    def getTimeZone(p0: ZoneId) -> "TimeZone": ...
    def inDaylightTime(self, p0: Date) -> bool: ...
    def getRawOffset(self) -> int: ...
    def getDSTSavings(self) -> int: ...
    def useDaylightTime(self) -> bool: ...
    @overload
    @staticmethod
    def getAvailableIDs() -> Any: ...
    @overload
    @staticmethod
    def getAvailableIDs(p0: int) -> Any: ...
    def setID(self, p0: str) -> None: ...
    def setRawOffset(self, p0: int) -> None: ...
    def observesDaylightTime(self) -> bool: ...
    def hasSameRules(self, p0: "TimeZone") -> bool: ...
    def toZoneId(self) -> ZoneId: ...
