from typing import Any, ClassVar, overload
from java.nio.Buffer import Buffer
from java.nio.FloatBuffer import FloatBuffer
from java.nio.IntBuffer import IntBuffer
from java.nio.ShortBuffer import ShortBuffer

class GL11Ext:
    GL_MATRIX_INDEX_ARRAY_BUFFER_BINDING_OES: ClassVar[int]
    GL_MATRIX_INDEX_ARRAY_OES: ClassVar[int]
    GL_MATRIX_INDEX_ARRAY_POINTER_OES: ClassVar[int]
    GL_MATRIX_INDEX_ARRAY_SIZE_OES: ClassVar[int]
    GL_MATRIX_INDEX_ARRAY_STRIDE_OES: ClassVar[int]
    GL_MATRIX_INDEX_ARRAY_TYPE_OES: ClassVar[int]
    GL_MATRIX_PALETTE_OES: ClassVar[int]
    GL_MAX_PALETTE_MATRICES_OES: ClassVar[int]
    GL_MAX_VERTEX_UNITS_OES: ClassVar[int]
    GL_TEXTURE_CROP_RECT_OES: ClassVar[int]
    GL_WEIGHT_ARRAY_BUFFER_BINDING_OES: ClassVar[int]
    GL_WEIGHT_ARRAY_OES: ClassVar[int]
    GL_WEIGHT_ARRAY_POINTER_OES: ClassVar[int]
    GL_WEIGHT_ARRAY_SIZE_OES: ClassVar[int]
    GL_WEIGHT_ARRAY_STRIDE_OES: ClassVar[int]
    GL_WEIGHT_ARRAY_TYPE_OES: ClassVar[int]
    def glEnable(self, p0: int) -> None: ...
    def glEnableClientState(self, p0: int) -> None: ...
    def glDrawTexsOES(self, p0: int, p1: int, p2: int, p3: int, p4: int) -> None: ...
    def glDrawTexiOES(self, p0: int, p1: int, p2: int, p3: int, p4: int) -> None: ...
    def glDrawTexxOES(self, p0: int, p1: int, p2: int, p3: int, p4: int) -> None: ...
    @overload
    def glDrawTexsvOES(self, p0: Any, p1: int) -> None: ...
    @overload
    def glDrawTexsvOES(self, p0: ShortBuffer) -> None: ...
    @overload
    def glDrawTexivOES(self, p0: Any, p1: int) -> None: ...
    @overload
    def glDrawTexivOES(self, p0: IntBuffer) -> None: ...
    @overload
    def glDrawTexxvOES(self, p0: IntBuffer) -> None: ...
    @overload
    def glDrawTexxvOES(self, p0: Any, p1: int) -> None: ...
    def glDrawTexfOES(self, p0: float, p1: float, p2: float, p3: float, p4: float) -> None: ...
    @overload
    def glDrawTexfvOES(self, p0: FloatBuffer) -> None: ...
    @overload
    def glDrawTexfvOES(self, p0: Any, p1: int) -> None: ...
    def glCurrentPaletteMatrixOES(self, p0: int) -> None: ...
    def glLoadPaletteFromModelViewMatrixOES(self) -> None: ...
    @overload
    def glMatrixIndexPointerOES(self, p0: int, p1: int, p2: int, p3: Buffer) -> None: ...
    @overload
    def glMatrixIndexPointerOES(self, p0: int, p1: int, p2: int, p3: int) -> None: ...
    @overload
    def glWeightPointerOES(self, p0: int, p1: int, p2: int, p3: Buffer) -> None: ...
    @overload
    def glWeightPointerOES(self, p0: int, p1: int, p2: int, p3: int) -> None: ...
    def glTexParameterfv(self, p0: int, p1: int, p2: Any, p3: int) -> None: ...
