from typing import Any, ClassVar, overload

class VcnCellUnderlyingNetworkTemplate:
    MATCH_ANY: ClassVar[int]
    MATCH_FORBIDDEN: ClassVar[int]
    MATCH_REQUIRED: ClassVar[int]
    def getRoaming(self) -> int: ...
    def getRcs(self) -> int: ...
    def getMms(self) -> int: ...
    def getCbs(self) -> int: ...
    def getDun(self) -> int: ...
    def getSimSpecificCarrierIds(self) -> set: ...
    def getOperatorPlmnIds(self) -> set: ...
    def getInternet(self) -> int: ...
    def getIms(self) -> int: ...
    def getOpportunistic(self) -> int: ...
    def equals(self, p0: Any) -> bool: ...
    def hashCode(self) -> int: ...

    class Builder:
        def __init__(self) -> None: ...
        def setRoaming(self, p0: int) -> Any: ...
        def setOpportunistic(self, p0: int) -> Any: ...
        def setMetered(self, p0: int) -> Any: ...
        def setMms(self, p0: int) -> Any: ...
        def setRcs(self, p0: int) -> Any: ...
        def setIms(self, p0: int) -> Any: ...
        def setOperatorPlmnIds(self, p0: set) -> Any: ...
        def setSimSpecificCarrierIds(self, p0: set) -> Any: ...
        def setDun(self, p0: int) -> Any: ...
        def setCbs(self, p0: int) -> Any: ...
        def setMinUpstreamBandwidthKbps(self, p0: int, p1: int) -> Any: ...
        def setMinDownstreamBandwidthKbps(self, p0: int, p1: int) -> Any: ...
        def setInternet(self, p0: int) -> Any: ...
        def build(self) -> "VcnCellUnderlyingNetworkTemplate": ...
