from typing import Any, ClassVar, overload
from android.net.ipsec.ike.IkeTunnelConnectionParams import IkeTunnelConnectionParams

class VcnGatewayConnectionConfig:
    MIN_UDP_PORT_4500_NAT_TIMEOUT_UNSET: ClassVar[int]
    VCN_GATEWAY_OPTION_ENABLE_DATA_STALL_RECOVERY_WITH_MOBILITY: ClassVar[int]
    def hasGatewayOption(self, p0: int) -> bool: ...
    def isSafeModeEnabled(self) -> bool: ...
    def getExposedCapabilities(self) -> Any: ...
    def getGatewayConnectionName(self) -> str: ...
    def getMinUdpPort4500NatTimeoutSeconds(self) -> int: ...
    def getRetryIntervalsMillis(self) -> Any: ...
    def getVcnUnderlyingNetworkPriorities(self) -> list: ...
    def getMaxMtu(self) -> int: ...
    def equals(self, p0: Any) -> bool: ...
    def hashCode(self) -> int: ...

    class Builder:
        def __init__(self, p0: str, p1: IkeTunnelConnectionParams) -> None: ...
        def addGatewayOption(self, p0: int) -> Any: ...
        def setMaxMtu(self, p0: int) -> Any: ...
        def setSafeModeEnabled(self, p0: bool) -> Any: ...
        def addExposedCapability(self, p0: int) -> Any: ...
        def removeExposedCapability(self, p0: int) -> Any: ...
        def removeGatewayOption(self, p0: int) -> Any: ...
        def setMinUdpPort4500NatTimeoutSeconds(self, p0: int) -> Any: ...
        def setRetryIntervalsMillis(self, p0: Any) -> Any: ...
        def setVcnUnderlyingNetworkPriorities(self, p0: list) -> Any: ...
        def build(self) -> "VcnGatewayConnectionConfig": ...
