from typing import Any, ClassVar, overload

class EncryptedTopic:
    def __init__(self, p0: Any, p1: str, p2: Any) -> None: ...
    def getKeyIdentifier(self) -> str: ...
    def getEncryptedTopic(self) -> Any: ...
    def getEncapsulatedKey(self) -> Any: ...
    def equals(self, p0: Any) -> bool: ...
    def toString(self) -> str: ...
    def hashCode(self) -> int: ...
