from typing import Any, ClassVar, overload

class GetTopicsRequest:
    def getAdsSdkName(self) -> str: ...
    def shouldRecordObservation(self) -> bool: ...

    class Builder:
        def __init__(self) -> None: ...
        def setAdsSdkName(self, p0: str) -> Any: ...
        def setShouldRecordObservation(self, p0: bool) -> Any: ...
        def build(self) -> "GetTopicsRequest": ...
