from typing import Any, ClassVar, overload
from java.io.IOException import IOException
from java.lang.Throwable import Throwable

class IkeIOException:
    def __init__(self, p0: IOException) -> None: ...
    @overload
    def getCause(self) -> Throwable: ...
    @overload
    def getCause(self) -> IOException: ...
    def initCause(self, p0: Throwable) -> Throwable: ...
