from typing import Any, ClassVar, overload
from android.content.res.Resources import Resources
from android.graphics.Bitmap import Bitmap
from android.renderscript.Element import Element
from android.renderscript.FieldPacker import FieldPacker
from android.renderscript.RenderScript import RenderScript
from android.renderscript.Type import Type
from android.view.Surface import Surface
from java.nio.ByteBuffer import ByteBuffer

class Allocation:
    USAGE_GRAPHICS_CONSTANTS: ClassVar[int]
    USAGE_GRAPHICS_RENDER_TARGET: ClassVar[int]
    USAGE_GRAPHICS_TEXTURE: ClassVar[int]
    USAGE_GRAPHICS_VERTEX: ClassVar[int]
    USAGE_IO_INPUT: ClassVar[int]
    USAGE_IO_OUTPUT: ClassVar[int]
    USAGE_SCRIPT: ClassVar[int]
    USAGE_SHARED: ClassVar[int]
    def getElement(self) -> Element: ...
    def getSurface(self) -> Surface: ...
    def setSurface(self, p0: Surface) -> None: ...
    def getTimeStamp(self) -> int: ...
    @overload
    def copy1DRangeFrom(self, p0: int, p1: int, p2: Any) -> None: ...
    @overload
    def copy1DRangeFrom(self, p0: int, p1: int, p2: Any) -> None: ...
    @overload
    def copy1DRangeFrom(self, p0: int, p1: int, p2: "Allocation", p3: int) -> None: ...
    @overload
    def copy1DRangeFrom(self, p0: int, p1: int, p2: Any) -> None: ...
    @overload
    def copy1DRangeFrom(self, p0: int, p1: int, p2: Any) -> None: ...
    @overload
    def copy1DRangeFrom(self, p0: int, p1: int, p2: Any) -> None: ...
    @overload
    def copy1DRangeFromUnchecked(self, p0: int, p1: int, p2: Any) -> None: ...
    @overload
    def copy1DRangeFromUnchecked(self, p0: int, p1: int, p2: Any) -> None: ...
    @overload
    def copy1DRangeFromUnchecked(self, p0: int, p1: int, p2: Any) -> None: ...
    @overload
    def copy1DRangeFromUnchecked(self, p0: int, p1: int, p2: Any) -> None: ...
    @overload
    def copy1DRangeFromUnchecked(self, p0: int, p1: int, p2: Any) -> None: ...
    @overload
    def copy1DRangeTo(self, p0: int, p1: int, p2: Any) -> None: ...
    @overload
    def copy1DRangeTo(self, p0: int, p1: int, p2: Any) -> None: ...
    @overload
    def copy1DRangeTo(self, p0: int, p1: int, p2: Any) -> None: ...
    @overload
    def copy1DRangeTo(self, p0: int, p1: int, p2: Any) -> None: ...
    @overload
    def copy1DRangeTo(self, p0: int, p1: int, p2: Any) -> None: ...
    @overload
    def copy1DRangeToUnchecked(self, p0: int, p1: int, p2: Any) -> None: ...
    @overload
    def copy1DRangeToUnchecked(self, p0: int, p1: int, p2: Any) -> None: ...
    @overload
    def copy1DRangeToUnchecked(self, p0: int, p1: int, p2: Any) -> None: ...
    @overload
    def copy1DRangeToUnchecked(self, p0: int, p1: int, p2: Any) -> None: ...
    @overload
    def copy1DRangeToUnchecked(self, p0: int, p1: int, p2: Any) -> None: ...
    @overload
    def copy2DRangeFrom(self, p0: int, p1: int, p2: int, p3: int, p4: Any) -> None: ...
    @overload
    def copy2DRangeFrom(self, p0: int, p1: int, p2: int, p3: int, p4: Any) -> None: ...
    @overload
    def copy2DRangeFrom(self, p0: int, p1: int, p2: Bitmap) -> None: ...
    @overload
    def copy2DRangeFrom(self, p0: int, p1: int, p2: int, p3: int, p4: "Allocation", p5: int, p6: int) -> None: ...
    @overload
    def copy2DRangeFrom(self, p0: int, p1: int, p2: int, p3: int, p4: Any) -> None: ...
    @overload
    def copy2DRangeFrom(self, p0: int, p1: int, p2: int, p3: int, p4: Any) -> None: ...
    @overload
    def copy2DRangeFrom(self, p0: int, p1: int, p2: int, p3: int, p4: Any) -> None: ...
    @overload
    def copy2DRangeTo(self, p0: int, p1: int, p2: int, p3: int, p4: Any) -> None: ...
    @overload
    def copy2DRangeTo(self, p0: int, p1: int, p2: int, p3: int, p4: Any) -> None: ...
    @overload
    def copy2DRangeTo(self, p0: int, p1: int, p2: int, p3: int, p4: Any) -> None: ...
    @overload
    def copy2DRangeTo(self, p0: int, p1: int, p2: int, p3: int, p4: Any) -> None: ...
    @overload
    def copy2DRangeTo(self, p0: int, p1: int, p2: int, p3: int, p4: Any) -> None: ...
    @overload
    def copy3DRangeFrom(self, p0: int, p1: int, p2: int, p3: int, p4: int, p5: int, p6: "Allocation", p7: int, p8: int, p9: int) -> None: ...
    @overload
    def copy3DRangeFrom(self, p0: int, p1: int, p2: int, p3: int, p4: int, p5: int, p6: Any) -> None: ...
    def copy3DRangeTo(self, p0: int, p1: int, p2: int, p3: int, p4: int, p5: int, p6: Any) -> None: ...
    @overload
    def copyFromUnchecked(self, p0: Any) -> None: ...
    @overload
    def copyFromUnchecked(self, p0: Any) -> None: ...
    @overload
    def copyFromUnchecked(self, p0: Any) -> None: ...
    @overload
    def copyFromUnchecked(self, p0: Any) -> None: ...
    @overload
    def copyFromUnchecked(self, p0: Any) -> None: ...
    @staticmethod
    def createAllocations(p0: RenderScript, p1: Type, p2: int, p3: int) -> Any: ...
    @overload
    @staticmethod
    def createCubemapFromBitmap(p0: RenderScript, p1: Bitmap) -> "Allocation": ...
    @overload
    @staticmethod
    def createCubemapFromBitmap(p0: RenderScript, p1: Bitmap, p2: Any, p3: int) -> "Allocation": ...
    @overload
    @staticmethod
    def createCubemapFromCubeFaces(p0: RenderScript, p1: Bitmap, p2: Bitmap, p3: Bitmap, p4: Bitmap, p5: Bitmap, p6: Bitmap, p7: Any, p8: int) -> "Allocation": ...
    @overload
    @staticmethod
    def createCubemapFromCubeFaces(p0: RenderScript, p1: Bitmap, p2: Bitmap, p3: Bitmap, p4: Bitmap, p5: Bitmap, p6: Bitmap) -> "Allocation": ...
    @overload
    @staticmethod
    def createFromBitmap(p0: RenderScript, p1: Bitmap, p2: Any, p3: int) -> "Allocation": ...
    @overload
    @staticmethod
    def createFromBitmap(p0: RenderScript, p1: Bitmap) -> "Allocation": ...
    @overload
    @staticmethod
    def createFromBitmapResource(p0: RenderScript, p1: Resources, p2: int) -> "Allocation": ...
    @overload
    @staticmethod
    def createFromBitmapResource(p0: RenderScript, p1: Resources, p2: int, p3: Any, p4: int) -> "Allocation": ...
    @staticmethod
    def createFromString(p0: RenderScript, p1: str, p2: int) -> "Allocation": ...
    @overload
    @staticmethod
    def createSized(p0: RenderScript, p1: Element, p2: int, p3: int) -> "Allocation": ...
    @overload
    @staticmethod
    def createSized(p0: RenderScript, p1: Element, p2: int) -> "Allocation": ...
    @overload
    @staticmethod
    def createTyped(p0: RenderScript, p1: Type) -> "Allocation": ...
    @overload
    @staticmethod
    def createTyped(p0: RenderScript, p1: Type, p2: int) -> "Allocation": ...
    @overload
    @staticmethod
    def createTyped(p0: RenderScript, p1: Type, p2: Any, p3: int) -> "Allocation": ...
    def generateMipmaps(self) -> None: ...
    def getBytesSize(self) -> int: ...
    def getStride(self) -> int: ...
    def ioReceive(self) -> None: ...
    def ioSend(self) -> None: ...
    def setAutoPadding(self, p0: bool) -> None: ...
    @overload
    def setFromFieldPacker(self, p0: int, p1: FieldPacker) -> None: ...
    @overload
    def setFromFieldPacker(self, p0: int, p1: int, p2: int, p3: int, p4: FieldPacker) -> None: ...
    @overload
    def setFromFieldPacker(self, p0: int, p1: int, p2: FieldPacker) -> None: ...
    def setOnBufferAvailableListener(self, p0: Any) -> None: ...
    @overload
    def copyTo(self, p0: Any) -> None: ...
    @overload
    def copyTo(self, p0: Any) -> None: ...
    @overload
    def copyTo(self, p0: Any) -> None: ...
    @overload
    def copyTo(self, p0: Any) -> None: ...
    @overload
    def copyTo(self, p0: Any) -> None: ...
    @overload
    def copyTo(self, p0: Bitmap) -> None: ...
    def destroy(self) -> None: ...
    def getType(self) -> Type: ...
    def syncAll(self, p0: int) -> None: ...
    def getByteBuffer(self) -> ByteBuffer: ...
    def getUsage(self) -> int: ...
    @overload
    def copyFrom(self, p0: Any) -> None: ...
    @overload
    def copyFrom(self, p0: Any) -> None: ...
    @overload
    def copyFrom(self, p0: Bitmap) -> None: ...
    @overload
    def copyFrom(self, p0: "Allocation") -> None: ...
    @overload
    def copyFrom(self, p0: Any) -> None: ...
    @overload
    def copyFrom(self, p0: Any) -> None: ...
    @overload
    def copyFrom(self, p0: Any) -> None: ...
    @overload
    def copyFrom(self, p0: Any) -> None: ...
    def resize(self, p0: int) -> None: ...

    class OnBufferAvailableListener:
        def onBufferAvailable(self, p0: "Allocation") -> None: ...

    class MipmapControl:
        MIPMAP_FULL: ClassVar["MipmapControl"]
        MIPMAP_NONE: ClassVar["MipmapControl"]
        MIPMAP_ON_SYNC_TO_TEXTURE: ClassVar["MipmapControl"]
        MIPMAP_FULL: ClassVar[Any]
        MIPMAP_NONE: ClassVar[Any]
        MIPMAP_ON_SYNC_TO_TEXTURE: ClassVar[Any]
        @staticmethod
        def values() -> Any: ...
        @staticmethod
        def valueOf(p0: str) -> Any: ...
