from typing import Any, ClassVar, overload
from android.renderscript.RenderScript import RenderScript

class Sampler:
    def getMinification(self) -> Any: ...
    def getMagnification(self) -> Any: ...
    def getWrapS(self) -> Any: ...
    def getWrapT(self) -> Any: ...
    def getAnisotropy(self) -> float: ...
    @staticmethod
    def CLAMP_NEAREST(p0: RenderScript) -> "Sampler": ...
    @staticmethod
    def CLAMP_LINEAR(p0: RenderScript) -> "Sampler": ...
    @staticmethod
    def CLAMP_LINEAR_MIP_LINEAR(p0: RenderScript) -> "Sampler": ...
    @staticmethod
    def WRAP_NEAREST(p0: RenderScript) -> "Sampler": ...
    @staticmethod
    def WRAP_LINEAR(p0: RenderScript) -> "Sampler": ...
    @staticmethod
    def WRAP_LINEAR_MIP_LINEAR(p0: RenderScript) -> "Sampler": ...
    @staticmethod
    def MIRRORED_REPEAT_NEAREST(p0: RenderScript) -> "Sampler": ...
    @staticmethod
    def MIRRORED_REPEAT_LINEAR(p0: RenderScript) -> "Sampler": ...
    @staticmethod
    def MIRRORED_REPEAT_LINEAR_MIP_LINEAR(p0: RenderScript) -> "Sampler": ...

    class Value:
        NEAREST: ClassVar["Value"]
        LINEAR: ClassVar["Value"]
        LINEAR_MIP_LINEAR: ClassVar["Value"]
        LINEAR_MIP_NEAREST: ClassVar["Value"]
        WRAP: ClassVar["Value"]
        CLAMP: ClassVar["Value"]
        MIRRORED_REPEAT: ClassVar["Value"]
        NEAREST: ClassVar[Any]
        LINEAR: ClassVar[Any]
        LINEAR_MIP_LINEAR: ClassVar[Any]
        LINEAR_MIP_NEAREST: ClassVar[Any]
        WRAP: ClassVar[Any]
        CLAMP: ClassVar[Any]
        MIRRORED_REPEAT: ClassVar[Any]
        @staticmethod
        def values() -> Any: ...
        @staticmethod
        def valueOf(p0: str) -> Any: ...

    class Builder:
        def __init__(self, p0: RenderScript) -> None: ...
        def setWrapS(self, p0: Any) -> None: ...
        def setWrapT(self, p0: Any) -> None: ...
        def setAnisotropy(self, p0: float) -> None: ...
        def setMinification(self, p0: Any) -> None: ...
        def setMagnification(self, p0: Any) -> None: ...
        def create(self) -> "Sampler": ...
