from typing import Any, ClassVar, overload
from android.renderscript.Allocation import Allocation
from android.renderscript.Element import Element
from android.renderscript.RenderScript import RenderScript

class ScriptIntrinsicYuvToRGB:
    def getKernelID(self) -> Any: ...
    def getFieldID_Input(self) -> Any: ...
    @staticmethod
    def create(p0: RenderScript, p1: Element) -> "ScriptIntrinsicYuvToRGB": ...
    def setInput(self, p0: Allocation) -> None: ...
    def forEach(self, p0: Allocation) -> None: ...
