from typing import Any, ClassVar, overload
from android.renderscript.Allocation import Allocation
from android.renderscript.Element import Element
from android.renderscript.RenderScript import RenderScript

class ScriptIntrinsicLUT:
    def setRed(self, p0: int, p1: int) -> None: ...
    def setGreen(self, p0: int, p1: int) -> None: ...
    def setBlue(self, p0: int, p1: int) -> None: ...
    def getKernelID(self) -> Any: ...
    def setAlpha(self, p0: int, p1: int) -> None: ...
    @staticmethod
    def create(p0: RenderScript, p1: Element) -> "ScriptIntrinsicLUT": ...
    @overload
    def forEach(self, p0: Allocation, p1: Allocation, p2: Any) -> None: ...
    @overload
    def forEach(self, p0: Allocation, p1: Allocation) -> None: ...
    def destroy(self) -> None: ...
