from typing import Any, ClassVar, overload

class StructTimeval:
    tv_sec: int
    tv_usec: int
    def equals(self, p0: Any) -> bool: ...
    def toString(self) -> str: ...
    def hashCode(self) -> int: ...
    def toMillis(self) -> int: ...
    @staticmethod
    def fromMillis(p0: int) -> "StructTimeval": ...
