from typing import Any, ClassVar, overload
from java.security.PrivateKey import PrivateKey

class ClientCertRequest:
    def __init__(self) -> None: ...
    def getKeyTypes(self) -> Any: ...
    def proceed(self, p0: PrivateKey, p1: Any) -> None: ...
    def ignore(self) -> None: ...
    def getHost(self) -> str: ...
    def getPort(self) -> int: ...
    def getPrincipals(self) -> Any: ...
    def cancel(self) -> None: ...
