from typing import Any, ClassVar, overload
from android.content.Context import Context

class CookieSyncManager:
    def resetSync(self) -> None: ...
    def stopSync(self) -> None: ...
    def run(self) -> None: ...
    @staticmethod
    def getInstance() -> "CookieSyncManager": ...
    def sync(self) -> None: ...
    def startSync(self) -> None: ...
    @staticmethod
    def createInstance(p0: Context) -> "CookieSyncManager": ...
