from typing import Any, ClassVar, overload

class HttpAuthHandler:
    def proceed(self, p0: str, p1: str) -> None: ...
    def useHttpAuthUsernamePassword(self) -> bool: ...
    def cancel(self) -> None: ...
