from typing import Any, ClassVar, overload

class MimeTypeMap:
    def hasMimeType(self, p0: str) -> bool: ...
    @staticmethod
    def getFileExtensionFromUrl(p0: str) -> str: ...
    def getMimeTypeFromExtension(self, p0: str) -> str: ...
    def hasExtension(self, p0: str) -> bool: ...
    def getExtensionFromMimeType(self, p0: str) -> str: ...
    @staticmethod
    def getSingleton() -> "MimeTypeMap": ...
