from typing import Any, ClassVar, overload
from java.io.InputStream import InputStream

class WebResourceResponse:
    @overload
    def __init__(self, p0: str, p1: str, p2: InputStream) -> None: ...
    @overload
    def __init__(self, p0: str, p1: str, p2: int, p3: str, p4: dict, p5: InputStream) -> None: ...
    def getMimeType(self) -> str: ...
    def getReasonPhrase(self) -> str: ...
    def getResponseHeaders(self) -> dict: ...
    def getStatusCode(self) -> int: ...
    def setEncoding(self, p0: str) -> None: ...
    def setMimeType(self, p0: str) -> None: ...
    def setResponseHeaders(self, p0: dict) -> None: ...
    def setStatusCodeAndReasonPhrase(self, p0: int, p1: str) -> None: ...
    def setData(self, p0: InputStream) -> None: ...
    def getEncoding(self) -> str: ...
    def getData(self) -> InputStream: ...
