from typing import Any, ClassVar, overload
from android.os.Parcel import Parcel
from java.security.cert.Certificate import Certificate

class ApkChecksum:
    CREATOR: ClassVar[Any]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    def toString(self) -> str: ...
    def getValue(self) -> Any: ...
    def getType(self) -> int: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
    def describeContents(self) -> int: ...
    def getInstallerCertificate(self) -> Certificate: ...
    def getSplitName(self) -> str: ...
    def getInstallerPackageName(self) -> str: ...
