from typing import Any, ClassVar, overload
from android.content.ComponentName import ComponentName
from android.graphics.drawable.Drawable import Drawable

class ArchivedActivityInfo:
    def __init__(self, p0: str, p1: ComponentName) -> None: ...
    def setIcon(self, p0: Drawable) -> "ArchivedActivityInfo": ...
    def getIcon(self) -> Drawable: ...
    def getComponentName(self) -> ComponentName: ...
    def getMonochromeIcon(self) -> Drawable: ...
    def setLabel(self, p0: str) -> "ArchivedActivityInfo": ...
    def setComponentName(self, p0: ComponentName) -> "ArchivedActivityInfo": ...
    def setMonochromeIcon(self, p0: Drawable) -> "ArchivedActivityInfo": ...
    def getLabel(self) -> str: ...
