from typing import Any, ClassVar, overload
from android.content.ClipData import ClipData
from android.content.Intent import Intent
from android.net.Uri import Uri
from android.os.Bundle import Bundle
from android.os.Parcel import Parcel

class AssistContent:
    CREATOR: ClassVar[Any]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    def __init__(self) -> None: ...
    def setStructuredData(self, p0: str) -> None: ...
    def setWebUri(self, p0: Uri) -> None: ...
    def isAppProvidedIntent(self) -> bool: ...
    def getStructuredData(self) -> str: ...
    def getWebUri(self) -> Uri: ...
    def isAppProvidedWebUri(self) -> bool: ...
    def getIntent(self) -> Intent: ...
    def getClipData(self) -> ClipData: ...
    def getExtras(self) -> Bundle: ...
    def setClipData(self, p0: ClipData) -> None: ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
    def setIntent(self, p0: Intent) -> None: ...
