from typing import Any, ClassVar, overload
from android.bluetooth.BluetoothDevice import BluetoothDevice
from java.io.InputStream import InputStream
from java.io.OutputStream import OutputStream

class BluetoothSocket:
    TYPE_L2CAP: ClassVar[int]
    TYPE_RFCOMM: ClassVar[int]
    TYPE_SCO: ClassVar[int]
    def getRemoteDevice(self) -> BluetoothDevice: ...
    def getMaxTransmitPacketSize(self) -> int: ...
    def getMaxReceivePacketSize(self) -> int: ...
    def getConnectionType(self) -> int: ...
    def isConnected(self) -> bool: ...
    def toString(self) -> str: ...
    def connect(self) -> None: ...
    def close(self) -> None: ...
    def getInputStream(self) -> InputStream: ...
    def getOutputStream(self) -> OutputStream: ...
