from typing import Any, ClassVar, overload
from java.io.InputStream import InputStream
from java.io.Reader import Reader
from java.math.BigDecimal import BigDecimal
from java.net.URL import URL
from java.sql.Array import Array
from java.sql.Blob import Blob
from java.sql.Clob import Clob
from java.sql.Date import Date
from java.sql.NClob import NClob
from java.sql.Ref import Ref
from java.sql.RowId import RowId
from java.sql.SQLXML import SQLXML
from java.sql.Time import Time
from java.sql.Timestamp import Timestamp
from java.util.Calendar import Calendar
from javax.sql.RowSetListener import RowSetListener

class RowSet:
    FETCH_FORWARD: ClassVar[int]
    FETCH_REVERSE: ClassVar[int]
    FETCH_UNKNOWN: ClassVar[int]
    TYPE_FORWARD_ONLY: ClassVar[int]
    TYPE_SCROLL_INSENSITIVE: ClassVar[int]
    TYPE_SCROLL_SENSITIVE: ClassVar[int]
    CONCUR_READ_ONLY: ClassVar[int]
    CONCUR_UPDATABLE: ClassVar[int]
    HOLD_CURSORS_OVER_COMMIT: ClassVar[int]
    CLOSE_CURSORS_AT_COMMIT: ClassVar[int]
    def getDataSourceName(self) -> str: ...
    def setDataSourceName(self, p0: str) -> None: ...
    def setCommand(self, p0: str) -> None: ...
    def getEscapeProcessing(self) -> bool: ...
    def setConcurrency(self, p0: int) -> None: ...
    def addRowSetListener(self, p0: RowSetListener) -> None: ...
    def removeRowSetListener(self, p0: RowSetListener) -> None: ...
    def getMaxFieldSize(self) -> int: ...
    def setMaxFieldSize(self, p0: int) -> None: ...
    def getMaxRows(self) -> int: ...
    def setMaxRows(self, p0: int) -> None: ...
    def setEscapeProcessing(self, p0: bool) -> None: ...
    def getQueryTimeout(self) -> int: ...
    def setQueryTimeout(self, p0: int) -> None: ...
    @overload
    def setNull(self, p0: int, p1: int, p2: str) -> None: ...
    @overload
    def setNull(self, p0: int, p1: int) -> None: ...
    @overload
    def setNull(self, p0: str, p1: int) -> None: ...
    @overload
    def setNull(self, p0: str, p1: int, p2: str) -> None: ...
    @overload
    def setBigDecimal(self, p0: int, p1: BigDecimal) -> None: ...
    @overload
    def setBigDecimal(self, p0: str, p1: BigDecimal) -> None: ...
    @overload
    def setBytes(self, p0: int, p1: Any) -> None: ...
    @overload
    def setBytes(self, p0: str, p1: Any) -> None: ...
    @overload
    def setAsciiStream(self, p0: str, p1: InputStream) -> None: ...
    @overload
    def setAsciiStream(self, p0: int, p1: InputStream) -> None: ...
    @overload
    def setAsciiStream(self, p0: str, p1: InputStream, p2: int) -> None: ...
    @overload
    def setAsciiStream(self, p0: int, p1: InputStream, p2: int) -> None: ...
    @overload
    def setBinaryStream(self, p0: str, p1: InputStream) -> None: ...
    @overload
    def setBinaryStream(self, p0: int, p1: InputStream, p2: int) -> None: ...
    @overload
    def setBinaryStream(self, p0: int, p1: InputStream) -> None: ...
    @overload
    def setBinaryStream(self, p0: str, p1: InputStream, p2: int) -> None: ...
    @overload
    def setObject(self, p0: int, p1: Any, p2: int, p3: int) -> None: ...
    @overload
    def setObject(self, p0: str, p1: Any, p2: int, p3: int) -> None: ...
    @overload
    def setObject(self, p0: str, p1: Any, p2: int) -> None: ...
    @overload
    def setObject(self, p0: int, p1: Any, p2: int) -> None: ...
    @overload
    def setObject(self, p0: int, p1: Any) -> None: ...
    @overload
    def setObject(self, p0: str, p1: Any) -> None: ...
    @overload
    def setCharacterStream(self, p0: str, p1: Reader) -> None: ...
    @overload
    def setCharacterStream(self, p0: int, p1: Reader, p2: int) -> None: ...
    @overload
    def setCharacterStream(self, p0: str, p1: Reader, p2: int) -> None: ...
    @overload
    def setCharacterStream(self, p0: int, p1: Reader) -> None: ...
    @overload
    def setRowId(self, p0: int, p1: RowId) -> None: ...
    @overload
    def setRowId(self, p0: str, p1: RowId) -> None: ...
    @overload
    def setNString(self, p0: str, p1: str) -> None: ...
    @overload
    def setNString(self, p0: int, p1: str) -> None: ...
    @overload
    def setNCharacterStream(self, p0: str, p1: Reader) -> None: ...
    @overload
    def setNCharacterStream(self, p0: str, p1: Reader, p2: int) -> None: ...
    @overload
    def setNCharacterStream(self, p0: int, p1: Reader, p2: int) -> None: ...
    @overload
    def setNCharacterStream(self, p0: int, p1: Reader) -> None: ...
    @overload
    def setNClob(self, p0: int, p1: Reader, p2: int) -> None: ...
    @overload
    def setNClob(self, p0: int, p1: NClob) -> None: ...
    @overload
    def setNClob(self, p0: str, p1: Reader) -> None: ...
    @overload
    def setNClob(self, p0: str, p1: Reader, p2: int) -> None: ...
    @overload
    def setNClob(self, p0: int, p1: Reader) -> None: ...
    @overload
    def setNClob(self, p0: str, p1: NClob) -> None: ...
    @overload
    def setClob(self, p0: int, p1: Reader) -> None: ...
    @overload
    def setClob(self, p0: int, p1: Reader, p2: int) -> None: ...
    @overload
    def setClob(self, p0: int, p1: Clob) -> None: ...
    @overload
    def setClob(self, p0: str, p1: Reader) -> None: ...
    @overload
    def setClob(self, p0: str, p1: Clob) -> None: ...
    @overload
    def setClob(self, p0: str, p1: Reader, p2: int) -> None: ...
    @overload
    def setBlob(self, p0: int, p1: InputStream) -> None: ...
    @overload
    def setBlob(self, p0: int, p1: InputStream, p2: int) -> None: ...
    @overload
    def setBlob(self, p0: int, p1: Blob) -> None: ...
    @overload
    def setBlob(self, p0: str, p1: InputStream) -> None: ...
    @overload
    def setBlob(self, p0: str, p1: Blob) -> None: ...
    @overload
    def setBlob(self, p0: str, p1: InputStream, p2: int) -> None: ...
    @overload
    def setSQLXML(self, p0: str, p1: SQLXML) -> None: ...
    @overload
    def setSQLXML(self, p0: int, p1: SQLXML) -> None: ...
    def setTransactionIsolation(self, p0: int) -> None: ...
    def getTransactionIsolation(self) -> int: ...
    def getTypeMap(self) -> dict: ...
    def setTypeMap(self, p0: dict) -> None: ...
    def getUsername(self) -> str: ...
    def getPassword(self) -> str: ...
    def setUrl(self, p0: str) -> None: ...
    def setUsername(self, p0: str) -> None: ...
    def getCommand(self) -> str: ...
    def setRef(self, p0: int, p1: Ref) -> None: ...
    def clearParameters(self) -> None: ...
    def setPassword(self, p0: str) -> None: ...
    @overload
    def setString(self, p0: int, p1: str) -> None: ...
    @overload
    def setString(self, p0: str, p1: str) -> None: ...
    @overload
    def setDate(self, p0: int, p1: Date, p2: Calendar) -> None: ...
    @overload
    def setDate(self, p0: int, p1: Date) -> None: ...
    @overload
    def setDate(self, p0: str, p1: Date, p2: Calendar) -> None: ...
    @overload
    def setDate(self, p0: str, p1: Date) -> None: ...
    def setType(self, p0: int) -> None: ...
    def getUrl(self) -> str: ...
    def setURL(self, p0: int, p1: URL) -> None: ...
    @overload
    def setTime(self, p0: str, p1: Time, p2: Calendar) -> None: ...
    @overload
    def setTime(self, p0: str, p1: Time) -> None: ...
    @overload
    def setTime(self, p0: int, p1: Time) -> None: ...
    @overload
    def setTime(self, p0: int, p1: Time, p2: Calendar) -> None: ...
    def setArray(self, p0: int, p1: Array) -> None: ...
    @overload
    def setTimestamp(self, p0: str, p1: Timestamp) -> None: ...
    @overload
    def setTimestamp(self, p0: int, p1: Timestamp, p2: Calendar) -> None: ...
    @overload
    def setTimestamp(self, p0: str, p1: Timestamp, p2: Calendar) -> None: ...
    @overload
    def setTimestamp(self, p0: int, p1: Timestamp) -> None: ...
    def isReadOnly(self) -> bool: ...
    def execute(self) -> None: ...
    def setReadOnly(self, p0: bool) -> None: ...
    @overload
    def setBoolean(self, p0: str, p1: bool) -> None: ...
    @overload
    def setBoolean(self, p0: int, p1: bool) -> None: ...
    @overload
    def setByte(self, p0: str, p1: int) -> None: ...
    @overload
    def setByte(self, p0: int, p1: int) -> None: ...
    @overload
    def setShort(self, p0: int, p1: int) -> None: ...
    @overload
    def setShort(self, p0: str, p1: int) -> None: ...
    @overload
    def setInt(self, p0: int, p1: int) -> None: ...
    @overload
    def setInt(self, p0: str, p1: int) -> None: ...
    @overload
    def setLong(self, p0: str, p1: int) -> None: ...
    @overload
    def setLong(self, p0: int, p1: int) -> None: ...
    @overload
    def setFloat(self, p0: int, p1: float) -> None: ...
    @overload
    def setFloat(self, p0: str, p1: float) -> None: ...
    @overload
    def setDouble(self, p0: str, p1: float) -> None: ...
    @overload
    def setDouble(self, p0: int, p1: float) -> None: ...
