from typing import Any, ClassVar, overload
from android.net.eap.EapInfo import EapInfo
from android.net.ipsec.ike.IkeSessionConnectionInfo import IkeSessionConnectionInfo

class IkeSessionConfiguration:
    EXTENSION_TYPE_FRAGMENTATION: ClassVar[int]
    EXTENSION_TYPE_MOBIKE: ClassVar[int]
    def getIkeSessionConnectionInfo(self) -> IkeSessionConnectionInfo: ...
    def getRemoteVendorIds(self) -> list: ...
    def isIkeExtensionEnabled(self, p0: int) -> bool: ...
    def getEapInfo(self) -> EapInfo: ...
    def getRemoteApplicationVersion(self) -> str: ...

    class Builder:
        def __init__(self, p0: IkeSessionConnectionInfo) -> None: ...
        def addRemoteVendorId(self, p0: Any) -> Any: ...
        def clearRemoteVendorIds(self) -> Any: ...
        def setRemoteApplicationVersion(self, p0: str) -> Any: ...
        def clearRemoteApplicationVersion(self) -> Any: ...
        def addIkeExtension(self, p0: int) -> Any: ...
        def clearIkeExtensions(self) -> Any: ...
        def setEapInfo(self, p0: EapInfo) -> Any: ...
        def build(self) -> "IkeSessionConfiguration": ...
