from typing import Any, ClassVar, overload
from android.text.Editable import Editable
from android.text.Spannable import Spannable
from android.view.KeyEvent import KeyEvent
from android.view.View import View

class MetaKeyKeyListener:
    META_ALT_LOCKED: ClassVar[int]
    META_ALT_ON: ClassVar[int]
    META_CAP_LOCKED: ClassVar[int]
    META_SHIFT_ON: ClassVar[int]
    META_SYM_LOCKED: ClassVar[int]
    META_SYM_ON: ClassVar[int]
    def __init__(self) -> None: ...
    @staticmethod
    def resetMetaState(p0: Spannable) -> None: ...
    @staticmethod
    def isMetaTracker(p0: str, p1: Any) -> bool: ...
    @overload
    @staticmethod
    def adjustMetaAfterKeypress(p0: Spannable) -> None: ...
    @overload
    @staticmethod
    def adjustMetaAfterKeypress(p0: int) -> int: ...
    @staticmethod
    def isSelectingMetaTracker(p0: str, p1: Any) -> bool: ...
    @staticmethod
    def resetLockedMeta(p0: int) -> int: ...
    @staticmethod
    def handleKeyDown(p0: int, p1: int, p2: KeyEvent) -> int: ...
    @staticmethod
    def handleKeyUp(p0: int, p1: int, p2: KeyEvent) -> int: ...
    def onKeyDown(self, p0: View, p1: Editable, p2: int, p3: KeyEvent) -> bool: ...
    @overload
    @staticmethod
    def clearMetaKeyState(p0: Editable, p1: int) -> None: ...
    @overload
    def clearMetaKeyState(self, p0: View, p1: Editable, p2: int) -> None: ...
    @overload
    def clearMetaKeyState(self, p0: int, p1: int) -> int: ...
    def onKeyUp(self, p0: View, p1: Editable, p2: int, p3: KeyEvent) -> bool: ...
    @overload
    @staticmethod
    def getMetaState(p0: int, p1: int) -> int: ...
    @overload
    @staticmethod
    def getMetaState(p0: str) -> int: ...
    @overload
    @staticmethod
    def getMetaState(p0: str, p1: KeyEvent) -> int: ...
    @overload
    @staticmethod
    def getMetaState(p0: str, p1: int) -> int: ...
    @overload
    @staticmethod
    def getMetaState(p0: str, p1: int, p2: KeyEvent) -> int: ...
    @overload
    @staticmethod
    def getMetaState(p0: int) -> int: ...
