from typing import Any, ClassVar, overload
from java.io.InputStream import InputStream
from javax.crypto.Cipher import Cipher

class CipherInputStream:
    def __init__(self, p0: InputStream, p1: Cipher) -> None: ...
    @overload
    def read(self, p0: Any, p1: int, p2: int) -> int: ...
    @overload
    def read(self) -> int: ...
    @overload
    def read(self, p0: Any) -> int: ...
    def close(self) -> None: ...
    def skip(self, p0: int) -> int: ...
    def available(self) -> int: ...
    def markSupported(self) -> bool: ...

from typing import Any, ClassVar, overload

class KeyGeneratorSpi:
    def __init__(self) -> None: ...

from typing import Any, ClassVar, overload

class CipherSpi:
    def __init__(self) -> None: ...

from typing import Any, ClassVar, overload
from java.nio.ByteBuffer import ByteBuffer
from java.security.AlgorithmParameters import AlgorithmParameters
from java.security.Key import Key
from java.security.Provider import Provider
from java.security.SecureRandom import SecureRandom
from java.security.cert.Certificate import Certificate
from java.security.spec.AlgorithmParameterSpec import AlgorithmParameterSpec
from javax.crypto.ExemptionMechanism import ExemptionMechanism

class Cipher:
    ENCRYPT_MODE: ClassVar[int]
    DECRYPT_MODE: ClassVar[int]
    WRAP_MODE: ClassVar[int]
    UNWRAP_MODE: ClassVar[int]
    PUBLIC_KEY: ClassVar[int]
    PRIVATE_KEY: ClassVar[int]
    SECRET_KEY: ClassVar[int]
    def getProvider(self) -> Provider: ...
    @overload
    def doFinal(self, p0: ByteBuffer, p1: ByteBuffer) -> int: ...
    @overload
    def doFinal(self, p0: Any, p1: int, p2: int, p3: Any, p4: int) -> int: ...
    @overload
    def doFinal(self, p0: Any, p1: int, p2: int, p3: Any) -> int: ...
    @overload
    def doFinal(self, p0: Any, p1: int, p2: int) -> Any: ...
    @overload
    def doFinal(self, p0: Any) -> Any: ...
    @overload
    def doFinal(self, p0: Any, p1: int) -> int: ...
    @overload
    def doFinal(self) -> Any: ...
    def getExemptionMechanism(self) -> ExemptionMechanism: ...
    @overload
    def updateAAD(self, p0: ByteBuffer) -> None: ...
    @overload
    def updateAAD(self, p0: Any, p1: int, p2: int) -> None: ...
    @overload
    def updateAAD(self, p0: Any) -> None: ...
    def getBlockSize(self) -> int: ...
    def getOutputSize(self, p0: int) -> int: ...
    def getIV(self) -> Any: ...
    @staticmethod
    def getMaxAllowedKeyLength(p0: str) -> int: ...
    @staticmethod
    def getMaxAllowedParameterSpec(p0: str) -> AlgorithmParameterSpec: ...
    def getAlgorithm(self) -> str: ...
    def toString(self) -> str: ...
    @overload
    def update(self, p0: Any, p1: int, p2: int, p3: Any) -> int: ...
    @overload
    def update(self, p0: Any) -> Any: ...
    @overload
    def update(self, p0: Any, p1: int, p2: int, p3: Any, p4: int) -> int: ...
    @overload
    def update(self, p0: ByteBuffer, p1: ByteBuffer) -> int: ...
    @overload
    def update(self, p0: Any, p1: int, p2: int) -> Any: ...
    def wrap(self, p0: Key) -> Any: ...
    @overload
    @staticmethod
    def getInstance(p0: str, p1: Provider) -> "Cipher": ...
    @overload
    @staticmethod
    def getInstance(p0: str) -> "Cipher": ...
    @overload
    @staticmethod
    def getInstance(p0: str, p1: str) -> "Cipher": ...
    @overload
    def init(self, p0: int, p1: Key) -> None: ...
    @overload
    def init(self, p0: int, p1: Key, p2: AlgorithmParameterSpec, p3: SecureRandom) -> None: ...
    @overload
    def init(self, p0: int, p1: Certificate, p2: SecureRandom) -> None: ...
    @overload
    def init(self, p0: int, p1: Key, p2: AlgorithmParameters, p3: SecureRandom) -> None: ...
    @overload
    def init(self, p0: int, p1: Certificate) -> None: ...
    @overload
    def init(self, p0: int, p1: Key, p2: AlgorithmParameters) -> None: ...
    @overload
    def init(self, p0: int, p1: Key, p2: SecureRandom) -> None: ...
    @overload
    def init(self, p0: int, p1: Key, p2: AlgorithmParameterSpec) -> None: ...
    def getParameters(self) -> AlgorithmParameters: ...
    def unwrap(self, p0: Any, p1: str, p2: int) -> Key: ...

from typing import Any, ClassVar, overload

class SecretKeyFactorySpi:
    def __init__(self) -> None: ...

from typing import Any, ClassVar, overload

class NoSuchPaddingException:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, p0: str) -> None: ...

from typing import Any, ClassVar, overload
from java.io.OutputStream import OutputStream
from javax.crypto.Cipher import Cipher

class CipherOutputStream:
    def __init__(self, p0: OutputStream, p1: Cipher) -> None: ...
    def flush(self) -> None: ...
    @overload
    def write(self, p0: Any, p1: int, p2: int) -> None: ...
    @overload
    def write(self, p0: int) -> None: ...
    @overload
    def write(self, p0: Any) -> None: ...
    def close(self) -> None: ...

from typing import Any, ClassVar, overload
from java.security.Provider import Provider
from java.security.spec.KeySpec import KeySpec
from javax.crypto.SecretKey import SecretKey

class SecretKeyFactory:
    def generateSecret(self, p0: KeySpec) -> SecretKey: ...
    def getProvider(self) -> Provider: ...
    def getAlgorithm(self) -> str: ...
    @overload
    @staticmethod
    def getInstance(p0: str, p1: Provider) -> "SecretKeyFactory": ...
    @overload
    @staticmethod
    def getInstance(p0: str) -> "SecretKeyFactory": ...
    @overload
    @staticmethod
    def getInstance(p0: str, p1: str) -> "SecretKeyFactory": ...
    def getKeySpec(self, p0: SecretKey, p1: type) -> KeySpec: ...
    def translateKey(self, p0: SecretKey) -> SecretKey: ...

from typing import Any, ClassVar, overload

class ExemptionMechanismSpi:
    def __init__(self) -> None: ...

from typing import Any, ClassVar, overload
from java.io.Serializable import Serializable
from java.security.Key import Key
from javax.crypto.Cipher import Cipher

class SealedObject:
    def __init__(self, p0: Serializable, p1: Cipher) -> None: ...
    def getAlgorithm(self) -> str: ...
    @overload
    def getObject(self, p0: Key, p1: str) -> Any: ...
    @overload
    def getObject(self, p0: Key) -> Any: ...
    @overload
    def getObject(self, p0: Cipher) -> Any: ...

from typing import Any, ClassVar, overload

class NullCipher:
    ENCRYPT_MODE: ClassVar[int]
    DECRYPT_MODE: ClassVar[int]
    WRAP_MODE: ClassVar[int]
    UNWRAP_MODE: ClassVar[int]
    PUBLIC_KEY: ClassVar[int]
    PRIVATE_KEY: ClassVar[int]
    SECRET_KEY: ClassVar[int]
    def __init__(self) -> None: ...

from typing import Any, ClassVar, overload

class SecretKey:
    serialVersionUID: ClassVar[int]
    serialVersionUID: ClassVar[int]

from typing import Any, ClassVar, overload

class KeyAgreementSpi:
    def __init__(self) -> None: ...

from typing import Any, ClassVar, overload

class ExemptionMechanismException:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, p0: str) -> None: ...

from typing import Any, ClassVar, overload
from java.security.Provider import Provider
from java.security.SecureRandom import SecureRandom
from java.security.spec.AlgorithmParameterSpec import AlgorithmParameterSpec
from javax.crypto.SecretKey import SecretKey

class KeyGenerator:
    def generateKey(self) -> SecretKey: ...
    def getProvider(self) -> Provider: ...
    def getAlgorithm(self) -> str: ...
    @overload
    @staticmethod
    def getInstance(p0: str) -> "KeyGenerator": ...
    @overload
    @staticmethod
    def getInstance(p0: str, p1: str) -> "KeyGenerator": ...
    @overload
    @staticmethod
    def getInstance(p0: str, p1: Provider) -> "KeyGenerator": ...
    @overload
    def init(self, p0: AlgorithmParameterSpec, p1: SecureRandom) -> None: ...
    @overload
    def init(self, p0: int) -> None: ...
    @overload
    def init(self, p0: int, p1: SecureRandom) -> None: ...
    @overload
    def init(self, p0: AlgorithmParameterSpec) -> None: ...
    @overload
    def init(self, p0: SecureRandom) -> None: ...

from typing import Any, ClassVar, overload

class BadPaddingException:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, p0: str) -> None: ...

from typing import Any, ClassVar, overload

class MacSpi:
    def __init__(self) -> None: ...
    def clone(self) -> Any: ...

from typing import Any, ClassVar, overload
from java.security.Key import Key
from java.security.Provider import Provider
from java.security.SecureRandom import SecureRandom
from java.security.spec.AlgorithmParameterSpec import AlgorithmParameterSpec
from javax.crypto.SecretKey import SecretKey

class KeyAgreement:
    @overload
    def generateSecret(self, p0: Any, p1: int) -> int: ...
    @overload
    def generateSecret(self) -> Any: ...
    @overload
    def generateSecret(self, p0: str) -> SecretKey: ...
    def getProvider(self) -> Provider: ...
    def getAlgorithm(self) -> str: ...
    def doPhase(self, p0: Key, p1: bool) -> Key: ...
    @overload
    @staticmethod
    def getInstance(p0: str, p1: str) -> "KeyAgreement": ...
    @overload
    @staticmethod
    def getInstance(p0: str) -> "KeyAgreement": ...
    @overload
    @staticmethod
    def getInstance(p0: str, p1: Provider) -> "KeyAgreement": ...
    @overload
    def init(self, p0: Key) -> None: ...
    @overload
    def init(self, p0: Key, p1: AlgorithmParameterSpec) -> None: ...
    @overload
    def init(self, p0: Key, p1: AlgorithmParameterSpec, p2: SecureRandom) -> None: ...
    @overload
    def init(self, p0: Key, p1: SecureRandom) -> None: ...

from typing import Any, ClassVar, overload
from java.security.AlgorithmParameters import AlgorithmParameters
from java.security.Key import Key
from java.security.Provider import Provider
from java.security.spec.PKCS8EncodedKeySpec import PKCS8EncodedKeySpec
from javax.crypto.Cipher import Cipher

class EncryptedPrivateKeyInfo:
    @overload
    def __init__(self, p0: str, p1: Any) -> None: ...
    @overload
    def __init__(self, p0: Any) -> None: ...
    @overload
    def __init__(self, p0: AlgorithmParameters, p1: Any) -> None: ...
    def getAlgName(self) -> str: ...
    def getAlgParameters(self) -> AlgorithmParameters: ...
    def getEncryptedData(self) -> Any: ...
    def getEncoded(self) -> Any: ...
    @overload
    def getKeySpec(self, p0: Key, p1: str) -> PKCS8EncodedKeySpec: ...
    @overload
    def getKeySpec(self, p0: Key) -> PKCS8EncodedKeySpec: ...
    @overload
    def getKeySpec(self, p0: Key, p1: Provider) -> PKCS8EncodedKeySpec: ...
    @overload
    def getKeySpec(self, p0: Cipher) -> PKCS8EncodedKeySpec: ...

from typing import Any, ClassVar, overload

class IllegalBlockSizeException:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, p0: str) -> None: ...

from typing import Any, ClassVar, overload
from java.nio.ByteBuffer import ByteBuffer
from java.security.Key import Key
from java.security.Provider import Provider
from java.security.spec.AlgorithmParameterSpec import AlgorithmParameterSpec

class Mac:
    def getProvider(self) -> Provider: ...
    def getMacLength(self) -> int: ...
    @overload
    def doFinal(self, p0: Any, p1: int) -> None: ...
    @overload
    def doFinal(self, p0: Any) -> Any: ...
    @overload
    def doFinal(self) -> Any: ...
    def getAlgorithm(self) -> str: ...
    def reset(self) -> None: ...
    def clone(self) -> Any: ...
    @overload
    def update(self, p0: Any, p1: int, p2: int) -> None: ...
    @overload
    def update(self, p0: ByteBuffer) -> None: ...
    @overload
    def update(self, p0: Any) -> None: ...
    @overload
    def update(self, p0: int) -> None: ...
    @overload
    @staticmethod
    def getInstance(p0: str) -> "Mac": ...
    @overload
    @staticmethod
    def getInstance(p0: str, p1: str) -> "Mac": ...
    @overload
    @staticmethod
    def getInstance(p0: str, p1: Provider) -> "Mac": ...
    @overload
    def init(self, p0: Key) -> None: ...
    @overload
    def init(self, p0: Key, p1: AlgorithmParameterSpec) -> None: ...

from typing import Any, ClassVar, overload
from java.security.AlgorithmParameters import AlgorithmParameters
from java.security.Key import Key
from java.security.Provider import Provider
from java.security.spec.AlgorithmParameterSpec import AlgorithmParameterSpec

class ExemptionMechanism:
    @overload
    def genExemptionBlob(self) -> Any: ...
    @overload
    def genExemptionBlob(self, p0: Any) -> int: ...
    @overload
    def genExemptionBlob(self, p0: Any, p1: int) -> int: ...
    def getProvider(self) -> Provider: ...
    def isCryptoAllowed(self, p0: Key) -> bool: ...
    def getOutputSize(self, p0: int) -> int: ...
    def getName(self) -> str: ...
    @overload
    @staticmethod
    def getInstance(p0: str, p1: Provider) -> "ExemptionMechanism": ...
    @overload
    @staticmethod
    def getInstance(p0: str) -> "ExemptionMechanism": ...
    @overload
    @staticmethod
    def getInstance(p0: str, p1: str) -> "ExemptionMechanism": ...
    @overload
    def init(self, p0: Key, p1: AlgorithmParameters) -> None: ...
    @overload
    def init(self, p0: Key, p1: AlgorithmParameterSpec) -> None: ...
    @overload
    def init(self, p0: Key) -> None: ...

from typing import Any, ClassVar, overload

class ShortBufferException:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, p0: str) -> None: ...

from typing import Any, ClassVar, overload

class AEADBadTagException:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, p0: str) -> None: ...

