from typing import Any, ClassVar, overload
from android.os.CancellationSignal import CancellationSignal
from android.print.PrinterId import PrinterId
from android.printservice.CustomPrinterIconCallback import CustomPrinterIconCallback

class PrinterDiscoverySession:
    def __init__(self) -> None: ...
    def getPrinters(self) -> list: ...
    def onStartPrinterDiscovery(self, p0: list) -> None: ...
    def addPrinters(self, p0: list) -> None: ...
    def removePrinters(self, p0: list) -> None: ...
    def onStopPrinterDiscovery(self) -> None: ...
    def onValidatePrinters(self, p0: list) -> None: ...
    def onStartPrinterStateTracking(self, p0: PrinterId) -> None: ...
    def onRequestCustomPrinterIcon(self, p0: PrinterId, p1: CancellationSignal, p2: CustomPrinterIconCallback) -> None: ...
    def onStopPrinterStateTracking(self, p0: PrinterId) -> None: ...
    def getTrackedPrinters(self) -> list: ...
    def isPrinterDiscoveryStarted(self) -> bool: ...
    def onDestroy(self) -> None: ...
    def isDestroyed(self) -> bool: ...
