from typing import Any, ClassVar, overload
from android.app.sdksandbox.SandboxedSdk import SandboxedSdk
from android.content.Context import Context
from android.os.Bundle import Bundle
from android.view.View import View

class SandboxedSdkProvider:
    def __init__(self) -> None: ...
    def beforeUnloadSdk(self) -> None: ...
    def attachContext(self, p0: Context) -> None: ...
    def onLoadSdk(self, p0: Bundle) -> SandboxedSdk: ...
    def getContext(self) -> Context: ...
    def getView(self, p0: Context, p1: Bundle, p2: int, p3: int) -> View: ...
