from typing import Any, ClassVar, overload
from android.net.sip.SipProfile import SipProfile

class SipSession:
    def setListener(self, p0: Any) -> None: ...
    def getCallId(self) -> str: ...
    def endCall(self) -> None: ...
    def isInCall(self) -> bool: ...
    def answerCall(self, p0: str, p1: int) -> None: ...
    def changeCall(self, p0: str, p1: int) -> None: ...
    def getLocalIp(self) -> str: ...
    def getLocalProfile(self) -> SipProfile: ...
    def getPeerProfile(self) -> SipProfile: ...
    def makeCall(self, p0: SipProfile, p1: str, p2: int) -> None: ...
    def register(self, p0: int) -> None: ...
    def getState(self) -> int: ...
    def unregister(self) -> None: ...

    class State:
        DEREGISTERING: ClassVar[int]
        INCOMING_CALL: ClassVar[int]
        INCOMING_CALL_ANSWERING: ClassVar[int]
        IN_CALL: ClassVar[int]
        NOT_DEFINED: ClassVar[int]
        OUTGOING_CALL: ClassVar[int]
        OUTGOING_CALL_CANCELING: ClassVar[int]
        OUTGOING_CALL_RING_BACK: ClassVar[int]
        PINGING: ClassVar[int]
        READY_TO_CALL: ClassVar[int]
        REGISTERING: ClassVar[int]
        @staticmethod
        def toString(p0: int) -> str: ...

    class Listener:
        def __init__(self) -> None: ...
        def onRegistering(self, p0: "SipSession") -> None: ...
        def onRegistrationFailed(self, p0: "SipSession", p1: int, p2: str) -> None: ...
        def onCallBusy(self, p0: "SipSession") -> None: ...
        def onCallChangeFailed(self, p0: "SipSession", p1: int, p2: str) -> None: ...
        def onCallEnded(self, p0: "SipSession") -> None: ...
        def onCallEstablished(self, p0: "SipSession", p1: str) -> None: ...
        def onCalling(self, p0: "SipSession") -> None: ...
        def onRegistrationDone(self, p0: "SipSession", p1: int) -> None: ...
        def onRinging(self, p0: "SipSession", p1: SipProfile, p2: str) -> None: ...
        def onRegistrationTimeout(self, p0: "SipSession") -> None: ...
        def onRingingBack(self, p0: "SipSession") -> None: ...
        def onError(self, p0: "SipSession", p1: int, p2: str) -> None: ...
