from typing import Any, ClassVar, overload
from android.content.Context import Context
from android.util.AttributeSet import AttributeSet

class ListPreference:
    DEFAULT_ORDER: ClassVar[int]
    @overload
    def __init__(self, p0: Context, p1: AttributeSet, p2: int) -> None: ...
    @overload
    def __init__(self, p0: Context, p1: AttributeSet, p2: int, p3: int) -> None: ...
    @overload
    def __init__(self, p0: Context, p1: AttributeSet) -> None: ...
    @overload
    def __init__(self, p0: Context) -> None: ...
    def getSummary(self) -> str: ...
    def setSummary(self, p0: str) -> None: ...
    @overload
    def setEntryValues(self, p0: Any) -> None: ...
    @overload
    def setEntryValues(self, p0: int) -> None: ...
    @overload
    def setEntries(self, p0: Any) -> None: ...
    @overload
    def setEntries(self, p0: int) -> None: ...
    def findIndexOfValue(self, p0: str) -> int: ...
    def getEntryValues(self) -> Any: ...
    def setValueIndex(self, p0: int) -> None: ...
    def getValue(self) -> str: ...
    def setValue(self, p0: str) -> None: ...
    def getEntries(self) -> Any: ...
    def getEntry(self) -> str: ...
