from typing import Any, ClassVar, overload
from android.content.Context import Context
from android.util.AttributeSet import AttributeSet

class MultiSelectListPreference:
    DEFAULT_ORDER: ClassVar[int]
    @overload
    def __init__(self, p0: Context, p1: AttributeSet) -> None: ...
    @overload
    def __init__(self, p0: Context) -> None: ...
    @overload
    def __init__(self, p0: Context, p1: AttributeSet, p2: int, p3: int) -> None: ...
    @overload
    def __init__(self, p0: Context, p1: AttributeSet, p2: int) -> None: ...
    @overload
    def setEntryValues(self, p0: Any) -> None: ...
    @overload
    def setEntryValues(self, p0: int) -> None: ...
    @overload
    def setEntries(self, p0: Any) -> None: ...
    @overload
    def setEntries(self, p0: int) -> None: ...
    def findIndexOfValue(self, p0: str) -> int: ...
    def getEntryValues(self) -> Any: ...
    def getEntries(self) -> Any: ...
    def getValues(self) -> set: ...
    def setValues(self, p0: set) -> None: ...
