from typing import Any, ClassVar, overload
from android.content.Context import Context
from android.preference.Preference import Preference
from android.util.AttributeSet import AttributeSet

class PreferenceGroup:
    DEFAULT_ORDER: ClassVar[int]
    @overload
    def __init__(self, p0: Context, p1: AttributeSet, p2: int, p3: int) -> None: ...
    @overload
    def __init__(self, p0: Context, p1: AttributeSet, p2: int) -> None: ...
    @overload
    def __init__(self, p0: Context, p1: AttributeSet) -> None: ...
    def addPreference(self, p0: Preference) -> bool: ...
    def addItemFromInflater(self, p0: Preference) -> None: ...
    def getPreference(self, p0: int) -> Preference: ...
    def getPreferenceCount(self) -> int: ...
    def isOrderingAsAdded(self) -> bool: ...
    def removePreference(self, p0: Preference) -> bool: ...
    def setOrderingAsAdded(self, p0: bool) -> None: ...
    def findPreference(self, p0: str) -> Preference: ...
    def notifyDependencyChange(self, p0: bool) -> None: ...
    def removeAll(self) -> None: ...
