from typing import Any, ClassVar, overload
from java.lang.Exception import Exception
from java.lang.Throwable import Throwable

class SAXException:
    @overload
    def __init__(self, p0: str, p1: Exception) -> None: ...
    @overload
    def __init__(self, p0: Exception) -> None: ...
    @overload
    def __init__(self, p0: str) -> None: ...
    @overload
    def __init__(self) -> None: ...
    def getCause(self) -> Throwable: ...
    def toString(self) -> str: ...
    def getMessage(self) -> str: ...
    def getException(self) -> Exception: ...
