from typing import Any, ClassVar, overload
from java.lang.Throwable import Throwable
from javax.xml.transform.SourceLocator import SourceLocator

class TransformerConfigurationException:
    @overload
    def __init__(self, p0: str, p1: SourceLocator, p2: Throwable) -> None: ...
    @overload
    def __init__(self, p0: str, p1: SourceLocator) -> None: ...
    @overload
    def __init__(self, p0: str, p1: Throwable) -> None: ...
    @overload
    def __init__(self, p0: Throwable) -> None: ...
    @overload
    def __init__(self, p0: str) -> None: ...
    @overload
    def __init__(self) -> None: ...
