from typing import Any, ClassVar, overload
from android.bluetooth.BluetoothDevice import BluetoothDevice
from android.os.Parcel import Parcel

class CallAudioState:
    CREATOR: ClassVar[Any]
    ROUTE_BLUETOOTH: ClassVar[int]
    ROUTE_EARPIECE: ClassVar[int]
    ROUTE_SPEAKER: ClassVar[int]
    ROUTE_STREAMING: ClassVar[int]
    ROUTE_WIRED_HEADSET: ClassVar[int]
    ROUTE_WIRED_OR_EARPIECE: ClassVar[int]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    def __init__(self, p0: bool, p1: int, p2: int) -> None: ...
    def isMuted(self) -> bool: ...
    def getSupportedRouteMask(self) -> int: ...
    def getActiveBluetoothDevice(self) -> BluetoothDevice: ...
    def getSupportedBluetoothDevices(self) -> list: ...
    @staticmethod
    def audioRouteToString(p0: int) -> str: ...
    def equals(self, p0: Any) -> bool: ...
    def toString(self) -> str: ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
    def getRoute(self) -> int: ...
