from typing import Any, ClassVar, overload

class IndexedPropertyChangeEvent:
    def __init__(self, p0: Any, p1: str, p2: Any, p3: Any, p4: int) -> None: ...
    def getIndex(self) -> int: ...

from typing import Any, ClassVar, overload

class PropertyChangeEvent:
    def __init__(self, p0: Any, p1: str, p2: Any, p3: Any) -> None: ...
    def getNewValue(self) -> Any: ...
    def getOldValue(self) -> Any: ...
    def getPropagationId(self) -> Any: ...
    def setPropagationId(self, p0: Any) -> None: ...
    def toString(self) -> str: ...
    def getPropertyName(self) -> str: ...

from typing import Any, ClassVar, overload
from java.beans.PropertyChangeEvent import PropertyChangeEvent
from java.beans.PropertyChangeListener import PropertyChangeListener

class PropertyChangeSupport:
    def __init__(self, p0: Any) -> None: ...
    @overload
    def addPropertyChangeListener(self, p0: str, p1: PropertyChangeListener) -> None: ...
    @overload
    def addPropertyChangeListener(self, p0: PropertyChangeListener) -> None: ...
    @overload
    def removePropertyChangeListener(self, p0: str, p1: PropertyChangeListener) -> None: ...
    @overload
    def removePropertyChangeListener(self, p0: PropertyChangeListener) -> None: ...
    @overload
    def firePropertyChange(self, p0: str, p1: Any, p2: Any) -> None: ...
    @overload
    def firePropertyChange(self, p0: str, p1: int, p2: int) -> None: ...
    @overload
    def firePropertyChange(self, p0: PropertyChangeEvent) -> None: ...
    @overload
    def firePropertyChange(self, p0: str, p1: bool, p2: bool) -> None: ...
    @overload
    def fireIndexedPropertyChange(self, p0: str, p1: int, p2: bool, p3: bool) -> None: ...
    @overload
    def fireIndexedPropertyChange(self, p0: str, p1: int, p2: Any, p3: Any) -> None: ...
    @overload
    def fireIndexedPropertyChange(self, p0: str, p1: int, p2: int, p3: int) -> None: ...
    def hasListeners(self, p0: str) -> bool: ...
    @overload
    def getPropertyChangeListeners(self) -> Any: ...
    @overload
    def getPropertyChangeListeners(self, p0: str) -> Any: ...

from typing import Any, ClassVar, overload
from java.beans.PropertyChangeEvent import PropertyChangeEvent
from java.beans.PropertyChangeListener import PropertyChangeListener

class PropertyChangeListenerProxy:
    def __init__(self, p0: str, p1: PropertyChangeListener) -> None: ...
    def propertyChange(self, p0: PropertyChangeEvent) -> None: ...
    def getPropertyName(self) -> str: ...

from typing import Any, ClassVar, overload
from java.beans.PropertyChangeEvent import PropertyChangeEvent

class PropertyChangeListener:
    def propertyChange(self, p0: PropertyChangeEvent) -> None: ...

