from typing import Any, ClassVar, overload
from android.net.Uri import Uri
from android.os.Bundle import Bundle
from android.os.Parcel import Parcel
from android.telecom.PhoneAccountHandle import PhoneAccountHandle

class ConnectionRequest:
    CREATOR: ClassVar[Any]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    @overload
    def __init__(self, p0: PhoneAccountHandle, p1: Uri, p2: Bundle, p3: int) -> None: ...
    @overload
    def __init__(self, p0: PhoneAccountHandle, p1: Uri, p2: Bundle) -> None: ...
    def isAdhocConferenceCall(self) -> bool: ...
    def getRttTextStream(self) -> Any: ...
    def isRequestingRtt(self) -> bool: ...
    def getAccountHandle(self) -> PhoneAccountHandle: ...
    def getVideoState(self) -> int: ...
    def getParticipants(self) -> list: ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
    def getExtras(self) -> Bundle: ...
    def getAddress(self) -> Uri: ...
    def toString(self) -> str: ...
