from typing import Any, ClassVar, overload
from android.net.Uri import Uri
from android.os.Parcel import Parcel

class GatewayInfo:
    CREATOR: ClassVar[Any]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    def __init__(self, p0: str, p1: Uri, p2: Uri) -> None: ...
    def getGatewayProviderPackageName(self) -> str: ...
    def getGatewayAddress(self) -> Uri: ...
    def getOriginalAddress(self) -> Uri: ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
    def isEmpty(self) -> bool: ...
