from typing import Any, ClassVar, overload
from android.net.Uri import Uri
from android.os.Bundle import Bundle
from android.os.Handler import Handler
from android.telecom.CallAudioState import CallAudioState
from android.telecom.DisconnectCause import DisconnectCause
from android.telecom.RemoteConference import RemoteConference
from android.telecom.StatusHints import StatusHints
from android.telecom.VideoProfile import VideoProfile
from android.view.Surface import Surface

class RemoteConnection:
    @overload
    def registerCallback(self, p0: Any, p1: Handler) -> None: ...
    @overload
    def registerCallback(self, p0: Any) -> None: ...
    def unregisterCallback(self, p0: Any) -> None: ...
    def disconnect(self) -> None: ...
    def getConference(self) -> RemoteConference: ...
    def getAddressPresentation(self) -> int: ...
    def getCallerDisplayName(self) -> str: ...
    def getCallerDisplayNamePresentation(self) -> int: ...
    def unhold(self) -> None: ...
    def stopDtmfTone(self) -> None: ...
    def pullExternalCall(self) -> None: ...
    def reject(self) -> None: ...
    def playDtmfTone(self, p0: str) -> None: ...
    def hold(self) -> None: ...
    def postDialContinue(self, p0: bool) -> None: ...
    def addConferenceParticipants(self, p0: list) -> None: ...
    def getConferenceableConnections(self) -> list: ...
    def getConnectionCapabilities(self) -> int: ...
    def getConnectionProperties(self) -> int: ...
    def getDisconnectCause(self) -> DisconnectCause: ...
    def getStatusHints(self) -> StatusHints: ...
    def getVideoProvider(self) -> Any: ...
    def getVideoState(self) -> int: ...
    def isRingbackRequested(self) -> bool: ...
    def getState(self) -> int: ...
    def getAddress(self) -> Uri: ...
    def abort(self) -> None: ...
    def isVoipAudioMode(self) -> bool: ...
    def setCallAudioState(self, p0: CallAudioState) -> None: ...
    def getExtras(self) -> Bundle: ...
    def answer(self) -> None: ...

    class VideoProvider:
        def registerCallback(self, p0: Any) -> None: ...
        def unregisterCallback(self, p0: Any) -> None: ...
        def setCamera(self, p0: str) -> None: ...
        def requestCallDataUsage(self) -> None: ...
        def requestCameraCapabilities(self) -> None: ...
        def sendSessionModifyRequest(self, p0: VideoProfile, p1: VideoProfile) -> None: ...
        def sendSessionModifyResponse(self, p0: VideoProfile) -> None: ...
        def setDeviceOrientation(self, p0: int) -> None: ...
        def setDisplaySurface(self, p0: Surface) -> None: ...
        def setPauseImage(self, p0: Uri) -> None: ...
        def setPreviewSurface(self, p0: Surface) -> None: ...
        def setZoom(self, p0: float) -> None: ...

        class Callback:
            def __init__(self) -> None: ...
            def onCallSessionEvent(self, p0: Any, p1: int) -> None: ...
            def onCallDataUsageChanged(self, p0: Any, p1: int) -> None: ...
            def onCameraCapabilitiesChanged(self, p0: Any, p1: Any) -> None: ...
            def onPeerDimensionsChanged(self, p0: Any, p1: int, p2: int) -> None: ...
            def onSessionModifyRequestReceived(self, p0: Any, p1: VideoProfile) -> None: ...
            def onSessionModifyResponseReceived(self, p0: Any, p1: int, p2: VideoProfile, p3: VideoProfile) -> None: ...
            def onVideoQualityChanged(self, p0: Any, p1: int) -> None: ...

    class Callback:
        def __init__(self) -> None: ...
        def onDisconnected(self, p0: "RemoteConnection", p1: DisconnectCause) -> None: ...
        def onStateChanged(self, p0: "RemoteConnection", p1: int) -> None: ...
        def onConnectionEvent(self, p0: "RemoteConnection", p1: str, p2: Bundle) -> None: ...
        def onPostDialWait(self, p0: "RemoteConnection", p1: str) -> None: ...
        def onExtrasChanged(self, p0: "RemoteConnection", p1: Bundle) -> None: ...
        def onConnectionPropertiesChanged(self, p0: "RemoteConnection", p1: int) -> None: ...
        def onRingbackRequested(self, p0: "RemoteConnection", p1: bool) -> None: ...
        def onStatusHintsChanged(self, p0: "RemoteConnection", p1: StatusHints) -> None: ...
        def onVideoProviderChanged(self, p0: "RemoteConnection", p1: Any) -> None: ...
        def onVideoStateChanged(self, p0: "RemoteConnection", p1: int) -> None: ...
        def onPostDialChar(self, p0: "RemoteConnection", p1: str) -> None: ...
        def onAddressChanged(self, p0: "RemoteConnection", p1: Uri, p2: int) -> None: ...
        def onVoipAudioChanged(self, p0: "RemoteConnection", p1: bool) -> None: ...
        def onCallerDisplayNameChanged(self, p0: "RemoteConnection", p1: str, p2: int) -> None: ...
        def onConferenceChanged(self, p0: "RemoteConnection", p1: RemoteConference) -> None: ...
        def onConferenceableConnectionsChanged(self, p0: "RemoteConnection", p1: list) -> None: ...
        def onConnectionCapabilitiesChanged(self, p0: "RemoteConnection", p1: int) -> None: ...
        def onDestroyed(self, p0: "RemoteConnection") -> None: ...
