from typing import Any, ClassVar, overload

class BrowserCompatHostnameVerifier:
    def __init__(self) -> None: ...
    def toString(self) -> str: ...
    def verify(self, p0: str, p1: Any, p2: Any) -> None: ...
