from typing import Any, ClassVar, overload
from org.xml.sax.SAXParseException import SAXParseException

class ErrorHandler:
    def fatalError(self, p0: SAXParseException) -> None: ...
    def error(self, p0: SAXParseException) -> None: ...
    def warning(self, p0: SAXParseException) -> None: ...
