from typing import Any, ClassVar, overload

class CertificateNotYetValidException:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, p0: str) -> None: ...

from typing import Any, ClassVar, overload
from java.io.InputStream import InputStream
from java.math.BigInteger import BigInteger
from java.security.Principal import Principal
from java.util.Date import Date

class X509Certificate:
    def __init__(self) -> None: ...
    @overload
    @staticmethod
    def getInstance(p0: Any) -> "X509Certificate": ...
    @overload
    @staticmethod
    def getInstance(p0: InputStream) -> "X509Certificate": ...
    def getSigAlgName(self) -> str: ...
    def getSigAlgParams(self) -> Any: ...
    @overload
    def checkValidity(self) -> None: ...
    @overload
    def checkValidity(self, p0: Date) -> None: ...
    def getSerialNumber(self) -> BigInteger: ...
    def getIssuerDN(self) -> Principal: ...
    def getSubjectDN(self) -> Principal: ...
    def getNotBefore(self) -> Date: ...
    def getNotAfter(self) -> Date: ...
    def getSigAlgOID(self) -> str: ...
    def getVersion(self) -> int: ...

from typing import Any, ClassVar, overload

class CertificateEncodingException:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, p0: str) -> None: ...

from typing import Any, ClassVar, overload

class CertificateException:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, p0: str) -> None: ...

from typing import Any, ClassVar, overload

class CertificateExpiredException:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, p0: str) -> None: ...

from typing import Any, ClassVar, overload
from java.security.PublicKey import PublicKey

class Certificate:
    def __init__(self) -> None: ...
    def equals(self, p0: Any) -> bool: ...
    def toString(self) -> str: ...
    def hashCode(self) -> int: ...
    def getEncoded(self) -> Any: ...
    @overload
    def verify(self, p0: PublicKey, p1: str) -> None: ...
    @overload
    def verify(self, p0: PublicKey) -> None: ...
    def getPublicKey(self) -> PublicKey: ...

from typing import Any, ClassVar, overload

class CertificateParsingException:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, p0: str) -> None: ...

