from typing import Any, ClassVar, overload
from android.os.Parcel import Parcel

class AppSearchSchema:
    CREATOR: ClassVar[Any]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    def getParentTypes(self) -> list: ...
    def equals(self, p0: Any) -> bool: ...
    def toString(self) -> str: ...
    def hashCode(self) -> int: ...
    def getProperties(self) -> list: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
    def describeContents(self) -> int: ...
    def getSchemaType(self) -> str: ...

    class StringPropertyConfig:
        INDEXING_TYPE_EXACT_TERMS: ClassVar[int]
        INDEXING_TYPE_NONE: ClassVar[int]
        INDEXING_TYPE_PREFIXES: ClassVar[int]
        JOINABLE_VALUE_TYPE_NONE: ClassVar[int]
        JOINABLE_VALUE_TYPE_QUALIFIED_ID: ClassVar[int]
        TOKENIZER_TYPE_NONE: ClassVar[int]
        TOKENIZER_TYPE_PLAIN: ClassVar[int]
        TOKENIZER_TYPE_RFC822: ClassVar[int]
        TOKENIZER_TYPE_VERBATIM: ClassVar[int]
        CARDINALITY_OPTIONAL: ClassVar[int]
        CARDINALITY_REPEATED: ClassVar[int]
        CARDINALITY_REQUIRED: ClassVar[int]
        def getIndexingType(self) -> int: ...
        def getJoinableValueType(self) -> int: ...
        def getTokenizerType(self) -> int: ...

        class Builder:
            def __init__(self, p0: str) -> None: ...
            def setIndexingType(self, p0: int) -> Any: ...
            def setCardinality(self, p0: int) -> Any: ...
            def setTokenizerType(self, p0: int) -> Any: ...
            def setJoinableValueType(self, p0: int) -> Any: ...
            def build(self) -> Any: ...

    class PropertyConfig:
        CARDINALITY_OPTIONAL: ClassVar[int]
        CARDINALITY_REPEATED: ClassVar[int]
        CARDINALITY_REQUIRED: ClassVar[int]
        def getCardinality(self) -> int: ...
        def getName(self) -> str: ...
        def equals(self, p0: Any) -> bool: ...
        def toString(self) -> str: ...
        def hashCode(self) -> int: ...

    class LongPropertyConfig:
        INDEXING_TYPE_NONE: ClassVar[int]
        INDEXING_TYPE_RANGE: ClassVar[int]
        CARDINALITY_OPTIONAL: ClassVar[int]
        CARDINALITY_REPEATED: ClassVar[int]
        CARDINALITY_REQUIRED: ClassVar[int]
        def getIndexingType(self) -> int: ...
        def isScoringEnabled(self) -> bool: ...

        class Builder:
            def __init__(self, p0: str) -> None: ...
            def setIndexingType(self, p0: int) -> Any: ...
            def setCardinality(self, p0: int) -> Any: ...
            def setScoringEnabled(self, p0: bool) -> Any: ...
            def build(self) -> Any: ...

    class EmbeddingPropertyConfig:
        INDEXING_TYPE_NONE: ClassVar[int]
        INDEXING_TYPE_SIMILARITY: ClassVar[int]
        QUANTIZATION_TYPE_8_BIT: ClassVar[int]
        QUANTIZATION_TYPE_NONE: ClassVar[int]
        CARDINALITY_OPTIONAL: ClassVar[int]
        CARDINALITY_REPEATED: ClassVar[int]
        CARDINALITY_REQUIRED: ClassVar[int]
        def getIndexingType(self) -> int: ...
        def getQuantizationType(self) -> int: ...

        class Builder:
            def __init__(self, p0: str) -> None: ...
            def setIndexingType(self, p0: int) -> Any: ...
            def setCardinality(self, p0: int) -> Any: ...
            def setQuantizationType(self, p0: int) -> Any: ...
            def build(self) -> Any: ...

    class DoublePropertyConfig:
        CARDINALITY_OPTIONAL: ClassVar[int]
        CARDINALITY_REPEATED: ClassVar[int]
        CARDINALITY_REQUIRED: ClassVar[int]
        def isScoringEnabled(self) -> bool: ...

        class Builder:
            def __init__(self, p0: str) -> None: ...
            def setCardinality(self, p0: int) -> Any: ...
            def setScoringEnabled(self, p0: bool) -> Any: ...
            def build(self) -> Any: ...

    class DocumentPropertyConfig:
        CARDINALITY_OPTIONAL: ClassVar[int]
        CARDINALITY_REPEATED: ClassVar[int]
        CARDINALITY_REQUIRED: ClassVar[int]
        def shouldIndexNestedProperties(self) -> bool: ...
        def getIndexableNestedProperties(self) -> list: ...
        def getSchemaType(self) -> str: ...

        class Builder:
            def __init__(self, p0: str, p1: str) -> None: ...
            def setCardinality(self, p0: int) -> Any: ...
            def build(self) -> Any: ...
            @overload
            def addIndexableNestedProperties(self, p0: Any) -> Any: ...
            @overload
            def addIndexableNestedProperties(self, p0: list) -> Any: ...
            @overload
            def addIndexableNestedPropertyPaths(self, p0: list) -> Any: ...
            @overload
            def addIndexableNestedPropertyPaths(self, p0: Any) -> Any: ...
            def setShouldIndexNestedProperties(self, p0: bool) -> Any: ...

    class BytesPropertyConfig:
        CARDINALITY_OPTIONAL: ClassVar[int]
        CARDINALITY_REPEATED: ClassVar[int]
        CARDINALITY_REQUIRED: ClassVar[int]

        class Builder:
            def __init__(self, p0: str) -> None: ...
            def setCardinality(self, p0: int) -> Any: ...
            def build(self) -> Any: ...

    class Builder:
        @overload
        def __init__(self, p0: "AppSearchSchema") -> None: ...
        @overload
        def __init__(self, p0: str) -> None: ...
        def clearParentTypes(self) -> Any: ...
        def clearProperties(self) -> Any: ...
        def addParentType(self, p0: str) -> Any: ...
        def addProperty(self, p0: Any) -> Any: ...
        def setSchemaType(self, p0: str) -> Any: ...
        def build(self) -> "AppSearchSchema": ...

    class BooleanPropertyConfig:
        CARDINALITY_OPTIONAL: ClassVar[int]
        CARDINALITY_REPEATED: ClassVar[int]
        CARDINALITY_REQUIRED: ClassVar[int]
        def isScoringEnabled(self) -> bool: ...

        class Builder:
            def __init__(self, p0: str) -> None: ...
            def setCardinality(self, p0: int) -> Any: ...
            def setScoringEnabled(self, p0: bool) -> Any: ...
            def build(self) -> Any: ...

    class BlobHandlePropertyConfig:
        CARDINALITY_OPTIONAL: ClassVar[int]
        CARDINALITY_REPEATED: ClassVar[int]
        CARDINALITY_REQUIRED: ClassVar[int]

        class Builder:
            def __init__(self, p0: str) -> None: ...
            def setCardinality(self, p0: int) -> Any: ...
            def build(self) -> Any: ...
