from typing import Any, ClassVar, overload
from android.app.appsearch.PackageIdentifier import PackageIdentifier
from android.os.Parcel import Parcel

class SchemaVisibilityConfig:
    CREATOR: ClassVar[Any]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    def getAllowedPackages(self) -> list: ...
    def getRequiredPermissions(self) -> set: ...
    def getPubliclyVisibleTargetPackage(self) -> PackageIdentifier: ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
    def equals(self, p0: Any) -> bool: ...
    def hashCode(self) -> int: ...

    class Builder:
        def __init__(self) -> None: ...
        def clearRequiredPermissions(self) -> Any: ...
        def addAllowedPackage(self, p0: PackageIdentifier) -> Any: ...
        def clearAllowedPackages(self) -> Any: ...
        def addRequiredPermissions(self, p0: set) -> Any: ...
        def setPubliclyVisibleTargetPackage(self, p0: PackageIdentifier) -> Any: ...
        def build(self) -> "SchemaVisibilityConfig": ...
