from typing import Any, ClassVar, overload
from android.app.appsearch.JoinSpec import JoinSpec
from android.os.Parcel import Parcel

class SearchSpec:
    CREATOR: ClassVar[Any]
    GROUPING_TYPE_PER_NAMESPACE: ClassVar[int]
    GROUPING_TYPE_PER_PACKAGE: ClassVar[int]
    GROUPING_TYPE_PER_SCHEMA: ClassVar[int]
    ORDER_ASCENDING: ClassVar[int]
    ORDER_DESCENDING: ClassVar[int]
    PROJECTION_SCHEMA_TYPE_WILDCARD: ClassVar[str]
    RANKING_STRATEGY_ADVANCED_RANKING_EXPRESSION: ClassVar[int]
    RANKING_STRATEGY_CREATION_TIMESTAMP: ClassVar[int]
    RANKING_STRATEGY_DOCUMENT_SCORE: ClassVar[int]
    RANKING_STRATEGY_JOIN_AGGREGATE_SCORE: ClassVar[int]
    RANKING_STRATEGY_NONE: ClassVar[int]
    RANKING_STRATEGY_RELEVANCE_SCORE: ClassVar[int]
    RANKING_STRATEGY_SYSTEM_USAGE_COUNT: ClassVar[int]
    RANKING_STRATEGY_SYSTEM_USAGE_LAST_USED_TIMESTAMP: ClassVar[int]
    RANKING_STRATEGY_USAGE_COUNT: ClassVar[int]
    RANKING_STRATEGY_USAGE_LAST_USED_TIMESTAMP: ClassVar[int]
    SCHEMA_TYPE_WILDCARD: ClassVar[str]
    TERM_MATCH_EXACT_ONLY: ClassVar[int]
    TERM_MATCH_PREFIX: ClassVar[int]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    def getProjections(self) -> dict: ...
    def getProjectionPaths(self) -> dict: ...
    def getTermMatch(self) -> int: ...
    def getFilterPackageNames(self) -> list: ...
    def getResultCountPerPage(self) -> int: ...
    def getSnippetCount(self) -> int: ...
    def getSnippetCountPerProperty(self) -> int: ...
    def getMaxSnippetSize(self) -> int: ...
    def getPropertyWeights(self) -> dict: ...
    def getPropertyWeightPaths(self) -> dict: ...
    def getResultGroupingTypeFlags(self) -> int: ...
    def getResultGroupingLimit(self) -> int: ...
    def getJoinSpec(self) -> JoinSpec: ...
    def getAdvancedRankingExpression(self) -> str: ...
    def getSearchSourceLogTag(self) -> str: ...
    def isNumericSearchEnabled(self) -> bool: ...
    def isVerbatimSearchEnabled(self) -> bool: ...
    def isListFilterQueryLanguageEnabled(self) -> bool: ...
    def isListFilterHasPropertyFunctionEnabled(self) -> bool: ...
    def getFilterNamespaces(self) -> list: ...
    def getRankingStrategy(self) -> int: ...
    def getFilterSchemas(self) -> list: ...
    def getFilterProperties(self) -> dict: ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
    def getOrder(self) -> int: ...

    class Builder:
        def __init__(self) -> None: ...
        def setTermMatch(self, p0: int) -> Any: ...
        @overload
        def addFilterPackageNames(self, p0: Any) -> Any: ...
        @overload
        def addFilterPackageNames(self, p0: list) -> Any: ...
        def setResultCountPerPage(self, p0: int) -> Any: ...
        def setSearchSourceLogTag(self, p0: str) -> Any: ...
        def setSnippetCount(self, p0: int) -> Any: ...
        def setSnippetCountPerProperty(self, p0: int) -> Any: ...
        def setMaxSnippetSize(self, p0: int) -> Any: ...
        def setResultGrouping(self, p0: int, p1: int) -> Any: ...
        def setPropertyWeights(self, p0: str, p1: dict) -> Any: ...
        def setJoinSpec(self, p0: JoinSpec) -> Any: ...
        def setPropertyWeightPaths(self, p0: str, p1: dict) -> Any: ...
        def setNumericSearchEnabled(self, p0: bool) -> Any: ...
        def setVerbatimSearchEnabled(self, p0: bool) -> Any: ...
        def setListFilterQueryLanguageEnabled(self, p0: bool) -> Any: ...
        def setListFilterHasPropertyFunctionEnabled(self, p0: bool) -> Any: ...
        def setOrder(self, p0: int) -> Any: ...
        def addProjectionPaths(self, p0: str, p1: list) -> Any: ...
        def addProjection(self, p0: str, p1: list) -> Any: ...
        @overload
        def setRankingStrategy(self, p0: str) -> Any: ...
        @overload
        def setRankingStrategy(self, p0: int) -> Any: ...
        @overload
        def addFilterNamespaces(self, p0: list) -> Any: ...
        @overload
        def addFilterNamespaces(self, p0: Any) -> Any: ...
        @overload
        def addFilterSchemas(self, p0: Any) -> Any: ...
        @overload
        def addFilterSchemas(self, p0: list) -> Any: ...
        def addFilterProperties(self, p0: str, p1: list) -> Any: ...
        def addFilterPropertyPaths(self, p0: str, p1: list) -> Any: ...
        def build(self) -> "SearchSpec": ...
