from typing import Any, ClassVar, overload
from java.security.Timestamp import Timestamp
from java.security.cert.CertPath import CertPath

class CodeSigner:
    def __init__(self, p0: CertPath, p1: Timestamp) -> None: ...
    def equals(self, p0: Any) -> bool: ...
    def toString(self) -> str: ...
    def hashCode(self) -> int: ...
    def getSignerCertPath(self) -> CertPath: ...
    def getTimestamp(self) -> Timestamp: ...
