from typing import Any, ClassVar, overload

class DrbgParameters:
    @staticmethod
    def nextBytes(p0: int, p1: bool, p2: Any) -> Any: ...
    @staticmethod
    def reseed(p0: bool, p1: Any) -> Any: ...
    @staticmethod
    def instantiation(p0: int, p1: Any, p2: Any) -> Any: ...

    class Instantiation:
        def getStrength(self) -> int: ...
        def toString(self) -> str: ...
        def getCapability(self) -> Any: ...
        def getPersonalizationString(self) -> Any: ...

    class Capability:
        PR_AND_RESEED: ClassVar["Capability"]
        RESEED_ONLY: ClassVar["Capability"]
        NONE: ClassVar["Capability"]
        PR_AND_RESEED: ClassVar[Any]
        RESEED_ONLY: ClassVar[Any]
        NONE: ClassVar[Any]
        def toString(self) -> str: ...
        @staticmethod
        def values() -> Any: ...
        @staticmethod
        def valueOf(p0: str) -> Any: ...
        def supportsReseeding(self) -> bool: ...
        def supportsPredictionResistance(self) -> bool: ...

    class NextBytes:
        def getStrength(self) -> int: ...
        def getPredictionResistance(self) -> bool: ...
        def getAdditionalInput(self) -> Any: ...

    class Reseed:
        def getPredictionResistance(self) -> bool: ...
        def getAdditionalInput(self) -> Any: ...
