from typing import Any, ClassVar, overload
from java.security.Key import Key
from java.security.PrivateKey import PrivateKey
from java.security.Provider import Provider
from java.security.PublicKey import PublicKey
from java.security.spec.KeySpec import KeySpec

class KeyFactory:
    @overload
    @staticmethod
    def getInstance(p0: str, p1: str) -> "KeyFactory": ...
    @overload
    @staticmethod
    def getInstance(p0: str, p1: Provider) -> "KeyFactory": ...
    @overload
    @staticmethod
    def getInstance(p0: str) -> "KeyFactory": ...
    def getProvider(self) -> Provider: ...
    def getAlgorithm(self) -> str: ...
    def generatePublic(self, p0: KeySpec) -> PublicKey: ...
    def generatePrivate(self, p0: KeySpec) -> PrivateKey: ...
    def getKeySpec(self, p0: Key, p1: type) -> KeySpec: ...
    def translateKey(self, p0: Key) -> Key: ...
