from typing import Any, ClassVar, overload
from java.security.KeyPair import KeyPair
from java.security.Provider import Provider
from java.security.SecureRandom import SecureRandom
from java.security.spec.AlgorithmParameterSpec import AlgorithmParameterSpec

class KeyPairGenerator:
    def generateKeyPair(self) -> KeyPair: ...
    def getProvider(self) -> Provider: ...
    def genKeyPair(self) -> KeyPair: ...
    @overload
    @staticmethod
    def getInstance(p0: str, p1: Provider) -> "KeyPairGenerator": ...
    @overload
    @staticmethod
    def getInstance(p0: str) -> "KeyPairGenerator": ...
    @overload
    @staticmethod
    def getInstance(p0: str, p1: str) -> "KeyPairGenerator": ...
    @overload
    def initialize(self, p0: AlgorithmParameterSpec, p1: SecureRandom) -> None: ...
    @overload
    def initialize(self, p0: AlgorithmParameterSpec) -> None: ...
    @overload
    def initialize(self, p0: int, p1: SecureRandom) -> None: ...
    @overload
    def initialize(self, p0: int) -> None: ...
    def getAlgorithm(self) -> str: ...
