from typing import Any, ClassVar, overload
from java.io.File import File
from java.io.InputStream import InputStream
from java.io.OutputStream import OutputStream
from java.security.Key import Key
from java.security.PrivateKey import PrivateKey
from java.security.Provider import Provider
from java.security.cert.Certificate import Certificate
from java.security.spec.AlgorithmParameterSpec import AlgorithmParameterSpec
from java.util.Date import Date
from java.util.Enumeration import Enumeration
from javax.crypto.SecretKey import SecretKey
from javax.security.auth.callback.CallbackHandler import CallbackHandler

class KeyStore:
    @staticmethod
    def getDefaultType() -> str: ...
    def size(self) -> int: ...
    @overload
    def load(self, p0: InputStream, p1: Any) -> None: ...
    @overload
    def load(self, p0: Any) -> None: ...
    @overload
    def store(self, p0: Any) -> None: ...
    @overload
    def store(self, p0: OutputStream, p1: Any) -> None: ...
    def getKey(self, p0: str, p1: Any) -> Key: ...
    @overload
    @staticmethod
    def getInstance(p0: str, p1: str) -> "KeyStore": ...
    @overload
    @staticmethod
    def getInstance(p0: File, p1: Any) -> "KeyStore": ...
    @overload
    @staticmethod
    def getInstance(p0: File, p1: Any) -> "KeyStore": ...
    @overload
    @staticmethod
    def getInstance(p0: str) -> "KeyStore": ...
    @overload
    @staticmethod
    def getInstance(p0: str, p1: Provider) -> "KeyStore": ...
    def getType(self) -> str: ...
    def getAttributes(self, p0: str) -> set: ...
    def getCertificateChain(self, p0: str) -> Any: ...
    def getProvider(self) -> Provider: ...
    def deleteEntry(self, p0: str) -> None: ...
    def getEntry(self, p0: str, p1: Any) -> Any: ...
    def getCertificate(self, p0: str) -> Certificate: ...
    def aliases(self) -> Enumeration: ...
    def isCertificateEntry(self, p0: str) -> bool: ...
    def getCreationDate(self, p0: str) -> Date: ...
    @overload
    def setKeyEntry(self, p0: str, p1: Key, p2: Any, p3: Any) -> None: ...
    @overload
    def setKeyEntry(self, p0: str, p1: Any, p2: Any) -> None: ...
    def setCertificateEntry(self, p0: str, p1: Certificate) -> None: ...
    def containsAlias(self, p0: str) -> bool: ...
    def isKeyEntry(self, p0: str) -> bool: ...
    def getCertificateAlias(self, p0: Certificate) -> str: ...
    def setEntry(self, p0: str, p1: Any, p2: Any) -> None: ...
    def entryInstanceOf(self, p0: str, p1: type) -> bool: ...

    class LoadStoreParameter:
        def getProtectionParameter(self) -> Any: ...

    class ProtectionParameter:
        ...

    class Entry:
        def getAttributes(self) -> set: ...

        class Attribute:
            def getName(self) -> str: ...
            def getValue(self) -> str: ...

    class Builder:
        @overload
        @staticmethod
        def newInstance(p0: str, p1: Provider, p2: File, p3: Any) -> Any: ...
        @overload
        @staticmethod
        def newInstance(p0: File, p1: Any) -> Any: ...
        @overload
        @staticmethod
        def newInstance(p0: str, p1: Provider, p2: Any) -> Any: ...
        @overload
        @staticmethod
        def newInstance(p0: "KeyStore", p1: Any) -> Any: ...
        def getProtectionParameter(self, p0: str) -> Any: ...
        def getKeyStore(self) -> "KeyStore": ...

    class TrustedCertificateEntry:
        @overload
        def __init__(self, p0: Certificate) -> None: ...
        @overload
        def __init__(self, p0: Certificate, p1: set) -> None: ...
        def toString(self) -> str: ...
        def getAttributes(self) -> set: ...
        def getTrustedCertificate(self) -> Certificate: ...

    class SecretKeyEntry:
        @overload
        def __init__(self, p0: SecretKey) -> None: ...
        @overload
        def __init__(self, p0: SecretKey, p1: set) -> None: ...
        def toString(self) -> str: ...
        def getAttributes(self) -> set: ...
        def getSecretKey(self) -> SecretKey: ...

    class PrivateKeyEntry:
        @overload
        def __init__(self, p0: PrivateKey, p1: Any) -> None: ...
        @overload
        def __init__(self, p0: PrivateKey, p1: Any, p2: set) -> None: ...
        def getPrivateKey(self) -> PrivateKey: ...
        def toString(self) -> str: ...
        def getAttributes(self) -> set: ...
        def getCertificateChain(self) -> Any: ...
        def getCertificate(self) -> Certificate: ...

    class CallbackHandlerProtection:
        def __init__(self, p0: CallbackHandler) -> None: ...
        def getCallbackHandler(self) -> CallbackHandler: ...

    class PasswordProtection:
        @overload
        def __init__(self, p0: Any) -> None: ...
        @overload
        def __init__(self, p0: Any, p1: str, p2: AlgorithmParameterSpec) -> None: ...
        def getPassword(self) -> Any: ...
        def isDestroyed(self) -> bool: ...
        def destroy(self) -> None: ...
        def getProtectionAlgorithm(self) -> str: ...
        def getProtectionParameters(self) -> AlgorithmParameterSpec: ...
