from typing import Any, ClassVar, overload
from android.content.ClipDescription import ClipDescription
from android.content.ContentResolver import ContentResolver
from android.content.Context import Context
from android.content.Intent import Intent
from android.content.IntentSender import IntentSender
from android.net.Uri import Uri
from android.os.Parcel import Parcel
from android.view.textclassifier.TextLinks import TextLinks

class ClipData:
    CREATOR: ClassVar[Any]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    @overload
    def __init__(self, p0: "ClipData") -> None: ...
    @overload
    def __init__(self, p0: ClipDescription, p1: Any) -> None: ...
    @overload
    def __init__(self, p0: str, p1: Any, p2: Any) -> None: ...
    def toString(self) -> str: ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
    def getItemCount(self) -> int: ...
    @staticmethod
    def newIntent(p0: str, p1: Intent) -> "ClipData": ...
    def getDescription(self) -> ClipDescription: ...
    @overload
    def addItem(self, p0: ContentResolver, p1: Any) -> None: ...
    @overload
    def addItem(self, p0: Any) -> None: ...
    @staticmethod
    def newPlainText(p0: str, p1: str) -> "ClipData": ...
    @staticmethod
    def newHtmlText(p0: str, p1: str, p2: str) -> "ClipData": ...
    @staticmethod
    def newUri(p0: ContentResolver, p1: str, p2: Uri) -> "ClipData": ...
    @staticmethod
    def newRawUri(p0: str, p1: Uri) -> "ClipData": ...
    def getItemAt(self, p0: int) -> Any: ...

    class Item:
        @overload
        def __init__(self, p0: str, p1: str, p2: Intent, p3: Uri) -> None: ...
        @overload
        def __init__(self, p0: str, p1: Intent, p2: Uri) -> None: ...
        @overload
        def __init__(self, p0: Uri) -> None: ...
        @overload
        def __init__(self, p0: str) -> None: ...
        @overload
        def __init__(self, p0: str, p1: str) -> None: ...
        @overload
        def __init__(self, p0: Intent) -> None: ...
        def toString(self) -> str: ...
        def getText(self) -> str: ...
        def getIntent(self) -> Intent: ...
        def getIntentSender(self) -> IntentSender: ...
        def getUri(self) -> Uri: ...
        def getHtmlText(self) -> str: ...
        def getTextLinks(self) -> TextLinks: ...
        def coerceToText(self, p0: Context) -> str: ...
        def coerceToStyledText(self, p0: Context) -> str: ...
        def coerceToHtmlText(self, p0: Context) -> str: ...

        class Builder:
            def __init__(self) -> None: ...
            def build(self) -> Any: ...
            def setText(self, p0: str) -> Any: ...
            def setUri(self, p0: Uri) -> Any: ...
            def setIntent(self, p0: Intent) -> Any: ...
            def setIntentSender(self, p0: IntentSender) -> Any: ...
            def setHtmlText(self, p0: str) -> Any: ...
