from typing import Any, ClassVar, overload
from android.content.Context import Context
from android.os.Parcel import Parcel

class ComponentName:
    CREATOR: ClassVar[Any]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    @overload
    def __init__(self, p0: str, p1: str) -> None: ...
    @overload
    def __init__(self, p0: Parcel) -> None: ...
    @overload
    def __init__(self, p0: Context, p1: str) -> None: ...
    @overload
    def __init__(self, p0: Context, p1: type) -> None: ...
    def equals(self, p0: Any) -> bool: ...
    def toString(self) -> str: ...
    def hashCode(self) -> int: ...
    @overload
    def clone(self) -> "ComponentName": ...
    @overload
    def clone(self) -> Any: ...
    @overload
    def compareTo(self, p0: Any) -> int: ...
    @overload
    def compareTo(self, p0: "ComponentName") -> int: ...
    def getPackageName(self) -> str: ...
    def toShortString(self) -> str: ...
    def getClassName(self) -> str: ...
    @overload
    @staticmethod
    def createRelative(p0: Context, p1: str) -> "ComponentName": ...
    @overload
    @staticmethod
    def createRelative(p0: str, p1: str) -> "ComponentName": ...
    def flattenToString(self) -> str: ...
    def getShortClassName(self) -> str: ...
    def flattenToShortString(self) -> str: ...
    @staticmethod
    def unflattenFromString(p0: str) -> "ComponentName": ...
    @overload
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
    @overload
    @staticmethod
    def writeToParcel(p0: "ComponentName", p1: Parcel) -> None: ...
    @staticmethod
    def readFromParcel(p0: Parcel) -> "ComponentName": ...
    def describeContents(self) -> int: ...
