from typing import Any, ClassVar, overload
from android.net.Uri import Uri
from android.os.Bundle import Bundle
from android.os.Parcel import Parcel
from android.os.ParcelFileDescriptor import ParcelFileDescriptor

class AdRequest:
    CREATOR: ClassVar[Any]
    REQUEST_TYPE_START: ClassVar[int]
    REQUEST_TYPE_STOP: ClassVar[int]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    @overload
    def __init__(self, p0: int, p1: int, p2: Uri, p3: int, p4: int, p5: int, p6: Bundle) -> None: ...
    @overload
    def __init__(self, p0: int, p1: int, p2: ParcelFileDescriptor, p3: int, p4: int, p5: int, p6: str, p7: Bundle) -> None: ...
    def getStopTimeMillis(self) -> int: ...
    def getEchoIntervalMillis(self) -> int: ...
    def getMediaFileType(self) -> str: ...
    def getStartTimeMillis(self) -> int: ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
    def getRequestType(self) -> int: ...
    def getUri(self) -> Uri: ...
    def getMetadata(self) -> Bundle: ...
    def getFileDescriptor(self) -> ParcelFileDescriptor: ...
    def getId(self) -> int: ...
