from typing import Any, ClassVar, overload
from java.nio.Buffer import Buffer
from java.nio.ByteOrder import ByteOrder

class ShortBuffer:
    @overload
    def reset(self) -> Buffer: ...
    @overload
    def reset(self) -> "ShortBuffer": ...
    @overload
    def put(self, p0: "ShortBuffer") -> "ShortBuffer": ...
    @overload
    def put(self, p0: int, p1: "ShortBuffer", p2: int, p3: int) -> "ShortBuffer": ...
    @overload
    def put(self, p0: int) -> "ShortBuffer": ...
    @overload
    def put(self, p0: int, p1: int) -> "ShortBuffer": ...
    @overload
    def put(self, p0: int, p1: Any) -> "ShortBuffer": ...
    @overload
    def put(self, p0: int, p1: Any, p2: int, p3: int) -> "ShortBuffer": ...
    @overload
    def put(self, p0: Any) -> "ShortBuffer": ...
    @overload
    def put(self, p0: Any, p1: int, p2: int) -> "ShortBuffer": ...
    def equals(self, p0: Any) -> bool: ...
    def toString(self) -> str: ...
    def hashCode(self) -> int: ...
    @overload
    def compareTo(self, p0: Any) -> int: ...
    @overload
    def compareTo(self, p0: "ShortBuffer") -> int: ...
    @overload
    def clear(self) -> "ShortBuffer": ...
    @overload
    def clear(self) -> Buffer: ...
    @overload
    @staticmethod
    def wrap(p0: Any) -> "ShortBuffer": ...
    @overload
    @staticmethod
    def wrap(p0: Any, p1: int, p2: int) -> "ShortBuffer": ...
    @overload
    def position(self, p0: int) -> Buffer: ...
    @overload
    def position(self, p0: int) -> "ShortBuffer": ...
    def mismatch(self, p0: "ShortBuffer") -> int: ...
    @overload
    def get(self, p0: int, p1: Any) -> "ShortBuffer": ...
    @overload
    def get(self, p0: int, p1: Any, p2: int, p3: int) -> "ShortBuffer": ...
    @overload
    def get(self, p0: Any) -> "ShortBuffer": ...
    @overload
    def get(self, p0: Any, p1: int, p2: int) -> "ShortBuffer": ...
    @overload
    def get(self, p0: int) -> int: ...
    @overload
    def get(self) -> int: ...
    @overload
    def limit(self, p0: int) -> Buffer: ...
    @overload
    def limit(self, p0: int) -> "ShortBuffer": ...
    def isDirect(self) -> bool: ...
    def hasArray(self) -> bool: ...
    @overload
    def array(self) -> Any: ...
    @overload
    def array(self) -> Any: ...
    def arrayOffset(self) -> int: ...
    @staticmethod
    def allocate(p0: int) -> "ShortBuffer": ...
    @overload
    def mark(self) -> Buffer: ...
    @overload
    def mark(self) -> "ShortBuffer": ...
    def asReadOnlyBuffer(self) -> "ShortBuffer": ...
    def compact(self) -> "ShortBuffer": ...
    def order(self) -> ByteOrder: ...
    @overload
    def flip(self) -> "ShortBuffer": ...
    @overload
    def flip(self) -> Buffer: ...
    @overload
    def rewind(self) -> "ShortBuffer": ...
    @overload
    def rewind(self) -> Buffer: ...
    @overload
    def slice(self, p0: int, p1: int) -> Buffer: ...
    @overload
    def slice(self) -> Buffer: ...
    @overload
    def slice(self, p0: int, p1: int) -> "ShortBuffer": ...
    @overload
    def slice(self) -> "ShortBuffer": ...
    @overload
    def duplicate(self) -> "ShortBuffer": ...
    @overload
    def duplicate(self) -> Buffer: ...
