from typing import Any, ClassVar, overload
from android.content.Context import Context
from android.database.Cursor import Cursor
from android.view.View import View
from android.view.ViewGroup import ViewGroup
from android.widget.Filter import Filter
from android.widget.FilterQueryProvider import FilterQueryProvider

class CursorTreeAdapter:
    @overload
    def __init__(self, p0: Cursor, p1: Context) -> None: ...
    @overload
    def __init__(self, p0: Cursor, p1: Context, p2: bool) -> None: ...
    @overload
    def getGroup(self, p0: int) -> Cursor: ...
    @overload
    def getGroup(self, p0: int) -> Any: ...
    def changeCursor(self, p0: Cursor) -> None: ...
    def convertToString(self, p0: Cursor) -> str: ...
    def getChildId(self, p0: int, p1: int) -> int: ...
    def getChildView(self, p0: int, p1: int, p2: bool, p3: View, p4: ViewGroup) -> View: ...
    def getChildrenCount(self, p0: int) -> int: ...
    def getCursor(self) -> Cursor: ...
    def getFilterQueryProvider(self) -> FilterQueryProvider: ...
    def getGroupCount(self) -> int: ...
    def getGroupId(self, p0: int) -> int: ...
    def getGroupView(self, p0: int, p1: bool, p2: View, p3: ViewGroup) -> View: ...
    def isChildSelectable(self, p0: int, p1: int) -> bool: ...
    def onGroupCollapsed(self, p0: int) -> None: ...
    def runQueryOnBackgroundThread(self, p0: str) -> Cursor: ...
    def setChildrenCursor(self, p0: int, p1: Cursor) -> None: ...
    def setFilterQueryProvider(self, p0: FilterQueryProvider) -> None: ...
    def setGroupCursor(self, p0: Cursor) -> None: ...
    @overload
    def getChild(self, p0: int, p1: int) -> Cursor: ...
    @overload
    def getChild(self, p0: int, p1: int) -> Any: ...
    @overload
    def notifyDataSetChanged(self) -> None: ...
    @overload
    def notifyDataSetChanged(self, p0: bool) -> None: ...
    def notifyDataSetInvalidated(self) -> None: ...
    def hasStableIds(self) -> bool: ...
    def getFilter(self) -> Filter: ...
