from typing import Any, ClassVar, overload
from android.content.res.Configuration import Configuration

class EmbeddedPhotoPickerSession:
    def close(self) -> None: ...
    def notifyResized(self, p0: int, p1: int) -> None: ...
    def getSurfacePackage(self) -> Any: ...
    def notifyConfigurationChanged(self, p0: Configuration) -> None: ...
    def notifyPhotoPickerExpanded(self, p0: bool) -> None: ...
    def notifyVisibilityChanged(self, p0: bool) -> None: ...
    def requestRevokeUriPermission(self, p0: list) -> None: ...

from typing import Any, ClassVar, overload
from android.widget.photopicker.EmbeddedPhotoPickerSession import EmbeddedPhotoPickerSession
from java.lang.Throwable import Throwable

class EmbeddedPhotoPickerClient:
    def onSelectionComplete(self) -> None: ...
    def onUriPermissionGranted(self, p0: list) -> None: ...
    def onUriPermissionRevoked(self, p0: list) -> None: ...
    def onSessionError(self, p0: Throwable) -> None: ...
    def onSessionOpened(self, p0: EmbeddedPhotoPickerSession) -> None: ...

from typing import Any, ClassVar, overload
from android.os.IBinder import IBinder
from android.widget.photopicker.EmbeddedPhotoPickerClient import EmbeddedPhotoPickerClient
from android.widget.photopicker.EmbeddedPhotoPickerFeatureInfo import EmbeddedPhotoPickerFeatureInfo
from java.util.concurrent.Executor import Executor

class EmbeddedPhotoPickerProvider:
    def openSession(self, p0: IBinder, p1: int, p2: int, p3: int, p4: EmbeddedPhotoPickerFeatureInfo, p5: Executor, p6: EmbeddedPhotoPickerClient) -> None: ...

from typing import Any, ClassVar, overload
from android.content.Context import Context
from android.widget.photopicker.EmbeddedPhotoPickerProvider import EmbeddedPhotoPickerProvider

class EmbeddedPhotoPickerProviderFactory:
    @staticmethod
    def create(p0: Context) -> EmbeddedPhotoPickerProvider: ...

from typing import Any, ClassVar, overload
from android.os.Parcel import Parcel

class EmbeddedPhotoPickerFeatureInfo:
    CREATOR: ClassVar[Any]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    def toString(self) -> str: ...
    def getAccentColor(self) -> int: ...
    def getMaxSelectionLimit(self) -> int: ...
    def getMimeTypes(self) -> list: ...
    def getPreSelectedUris(self) -> list: ...
    def getThemeNightMode(self) -> int: ...
    def isOrderedSelection(self) -> bool: ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...

    class Builder:
        def __init__(self) -> None: ...
        def setMaxSelectionLimit(self, p0: int) -> Any: ...
        def setMimeTypes(self, p0: list) -> Any: ...
        def setAccentColor(self, p0: int) -> Any: ...
        def setOrderedSelection(self, p0: bool) -> Any: ...
        def setPreSelectedUris(self, p0: list) -> Any: ...
        def setThemeNightMode(self, p0: int) -> Any: ...
        def build(self) -> "EmbeddedPhotoPickerFeatureInfo": ...

