from typing import Any, ClassVar, overload

class SectionIndexer:
    def getPositionForSection(self, p0: int) -> int: ...
    def getSectionForPosition(self, p0: int) -> int: ...
    def getSections(self) -> Any: ...
