from typing import Any, ClassVar, overload
from android.content.Context import Context
from android.view.View import View
from android.view.ViewGroup import ViewGroup
from java.lang.Runnable import Runnable

class Scene:
    @overload
    def __init__(self, p0: ViewGroup) -> None: ...
    @overload
    def __init__(self, p0: ViewGroup, p1: ViewGroup) -> None: ...
    @overload
    def __init__(self, p0: ViewGroup, p1: View) -> None: ...
    @staticmethod
    def getSceneForLayout(p0: ViewGroup, p1: int, p2: Context) -> "Scene": ...
    def setEnterAction(self, p0: Runnable) -> None: ...
    def setExitAction(self, p0: Runnable) -> None: ...
    def getSceneRoot(self) -> ViewGroup: ...
    def exit(self) -> None: ...
    def enter(self) -> None: ...
    @staticmethod
    def getCurrentScene(p0: ViewGroup) -> "Scene": ...
