from typing import Any, ClassVar, overload
from android.animation.TimeInterpolator import TimeInterpolator
from android.content.Context import Context
from android.transition.PathMotion import PathMotion
from android.transition.Transition import Transition
from android.transition.TransitionPropagation import TransitionPropagation
from android.transition.TransitionValues import TransitionValues
from android.util.AttributeSet import AttributeSet
from android.view.View import View

class TransitionSet:
    ORDERING_SEQUENTIAL: ClassVar[int]
    ORDERING_TOGETHER: ClassVar[int]
    MATCH_ID: ClassVar[int]
    MATCH_INSTANCE: ClassVar[int]
    MATCH_ITEM_ID: ClassVar[int]
    MATCH_NAME: ClassVar[int]
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, p0: Context, p1: AttributeSet) -> None: ...
    def addTransition(self, p0: Transition) -> "TransitionSet": ...
    def setOrdering(self, p0: int) -> "TransitionSet": ...
    def getOrdering(self) -> int: ...
    def getTransitionCount(self) -> int: ...
    def getTransitionAt(self, p0: int) -> Transition: ...
    def removeTransition(self, p0: Transition) -> "TransitionSet": ...
    @overload
    def setDuration(self, p0: int) -> Transition: ...
    @overload
    def setDuration(self, p0: int) -> "TransitionSet": ...
    @overload
    def setStartDelay(self, p0: int) -> "TransitionSet": ...
    @overload
    def setStartDelay(self, p0: int) -> Transition: ...
    @overload
    def setInterpolator(self, p0: TimeInterpolator) -> Transition: ...
    @overload
    def setInterpolator(self, p0: TimeInterpolator) -> "TransitionSet": ...
    def captureStartValues(self, p0: TransitionValues) -> None: ...
    def captureEndValues(self, p0: TransitionValues) -> None: ...
    @overload
    def addTarget(self, p0: View) -> Transition: ...
    @overload
    def addTarget(self, p0: int) -> Transition: ...
    @overload
    def addTarget(self, p0: int) -> "TransitionSet": ...
    @overload
    def addTarget(self, p0: str) -> "TransitionSet": ...
    @overload
    def addTarget(self, p0: str) -> Transition: ...
    @overload
    def addTarget(self, p0: type) -> "TransitionSet": ...
    @overload
    def addTarget(self, p0: type) -> Transition: ...
    @overload
    def addTarget(self, p0: View) -> "TransitionSet": ...
    @overload
    def removeTarget(self, p0: int) -> "TransitionSet": ...
    @overload
    def removeTarget(self, p0: type) -> Transition: ...
    @overload
    def removeTarget(self, p0: type) -> "TransitionSet": ...
    @overload
    def removeTarget(self, p0: str) -> "TransitionSet": ...
    @overload
    def removeTarget(self, p0: int) -> Transition: ...
    @overload
    def removeTarget(self, p0: str) -> Transition: ...
    @overload
    def removeTarget(self, p0: View) -> Transition: ...
    @overload
    def removeTarget(self, p0: View) -> "TransitionSet": ...
    @overload
    def excludeTarget(self, p0: str, p1: bool) -> Transition: ...
    @overload
    def excludeTarget(self, p0: int, p1: bool) -> Transition: ...
    @overload
    def excludeTarget(self, p0: View, p1: bool) -> Transition: ...
    @overload
    def excludeTarget(self, p0: type, p1: bool) -> Transition: ...
    @overload
    def addListener(self, p0: Any) -> "TransitionSet": ...
    @overload
    def addListener(self, p0: Any) -> Transition: ...
    @overload
    def removeListener(self, p0: Any) -> Transition: ...
    @overload
    def removeListener(self, p0: Any) -> "TransitionSet": ...
    def setEpicenterCallback(self, p0: Any) -> None: ...
    def setPathMotion(self, p0: PathMotion) -> None: ...
    def setPropagation(self, p0: TransitionPropagation) -> None: ...
    @overload
    def clone(self) -> Any: ...
    @overload
    def clone(self) -> Transition: ...
    @overload
    def clone(self) -> "TransitionSet": ...
