from typing import Any, ClassVar, overload

class Predicate:
    def negate(self) -> "Predicate": ...
    @staticmethod
    def isEqual(p0: Any) -> "Predicate": ...
    def and_(self, p0: "Predicate") -> "Predicate": ...
    @staticmethod
    def not_(p0: "Predicate") -> "Predicate": ...
    def or_(self, p0: "Predicate") -> "Predicate": ...
    def test(self, p0: Any) -> bool: ...
