from jnius import JavaClass, MetaJavaClass, JavaMethod, JavaStaticMethod, JavaMultipleMethod, JavaField, JavaStaticField

__all__ = ["ActionBar"]

class ActionBar(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "android/app/ActionBar"
    __javaconstructor__ = [("()V", False)]
    DISPLAY_HOME_AS_UP = JavaStaticField("I")
    DISPLAY_SHOW_CUSTOM = JavaStaticField("I")
    DISPLAY_SHOW_HOME = JavaStaticField("I")
    DISPLAY_SHOW_TITLE = JavaStaticField("I")
    DISPLAY_USE_LOGO = JavaStaticField("I")
    NAVIGATION_MODE_LIST = JavaStaticField("I")
    NAVIGATION_MODE_STANDARD = JavaStaticField("I")
    NAVIGATION_MODE_TABS = JavaStaticField("I")
    getTabAt = JavaMethod("(I)Landroid/app/ActionBar$Tab;")
    getNavigationMode = JavaMethod("()I")
    getSelectedTab = JavaMethod("()Landroid/app/ActionBar$Tab;")
    getHideOffset = JavaMethod("()I")
    getThemedContext = JavaMethod("()Landroid/content/Context;")
    removeAllTabs = JavaMethod("()V")
    selectTab = JavaMethod("(Landroid/app/ActionBar$Tab;)V")
    removeTabAt = JavaMethod("(I)V")
    removeTab = JavaMethod("(Landroid/app/ActionBar$Tab;)V")
    addOnMenuVisibilityListener = JavaMethod("(Landroid/app/ActionBar$OnMenuVisibilityListener;)V")
    getDisplayOptions = JavaMethod("()I")
    getNavigationItemCount = JavaMethod("()I")
    getSelectedNavigationIndex = JavaMethod("()I")
    isHideOnContentScrollEnabled = JavaMethod("()Z")
    removeOnMenuVisibilityListener = JavaMethod("(Landroid/app/ActionBar$OnMenuVisibilityListener;)V")
    setDisplayHomeAsUpEnabled = JavaMethod("(Z)V")
    setDisplayOptions = JavaMultipleMethod([("(I)V", False, False), ("(II)V", False, False)])
    setDisplayShowCustomEnabled = JavaMethod("(Z)V")
    setDisplayShowHomeEnabled = JavaMethod("(Z)V")
    setDisplayShowTitleEnabled = JavaMethod("(Z)V")
    setDisplayUseLogoEnabled = JavaMethod("(Z)V")
    setHideOffset = JavaMethod("(I)V")
    setHideOnContentScrollEnabled = JavaMethod("(Z)V")
    setHomeActionContentDescription = JavaMultipleMethod([("(I)V", False, False), ("(Ljava/lang/CharSequence;)V", False, False)])
    setHomeAsUpIndicator = JavaMultipleMethod([("(Landroid/graphics/drawable/Drawable;)V", False, False), ("(I)V", False, False)])
    setHomeButtonEnabled = JavaMethod("(Z)V")
    setListNavigationCallbacks = JavaMethod("(Landroid/widget/SpinnerAdapter;Landroid/app/ActionBar$OnNavigationListener;)V")
    setNavigationMode = JavaMethod("(I)V")
    setSelectedNavigationItem = JavaMethod("(I)V")
    setSplitBackgroundDrawable = JavaMethod("(Landroid/graphics/drawable/Drawable;)V")
    setStackedBackgroundDrawable = JavaMethod("(Landroid/graphics/drawable/Drawable;)V")
    getElevation = JavaMethod("()F")
    getHeight = JavaMethod("()I")
    setBackgroundDrawable = JavaMethod("(Landroid/graphics/drawable/Drawable;)V")
    setElevation = JavaMethod("(F)V")
    isShowing = JavaMethod("()Z")
    hide = JavaMethod("()V")
    show = JavaMethod("()V")
    setIcon = JavaMultipleMethod([("(I)V", False, False), ("(Landroid/graphics/drawable/Drawable;)V", False, False)])
    getSubtitle = JavaMethod("()Ljava/lang/CharSequence;")
    getTitle = JavaMethod("()Ljava/lang/CharSequence;")
    setLogo = JavaMultipleMethod([("(Landroid/graphics/drawable/Drawable;)V", False, False), ("(I)V", False, False)])
    setSubtitle = JavaMultipleMethod([("(I)V", False, False), ("(Ljava/lang/CharSequence;)V", False, False)])
    setTitle = JavaMultipleMethod([("(I)V", False, False), ("(Ljava/lang/CharSequence;)V", False, False)])
    getTabCount = JavaMethod("()I")
    getCustomView = JavaMethod("()Landroid/view/View;")
    setCustomView = JavaMultipleMethod([("(Landroid/view/View;Landroid/app/ActionBar$LayoutParams;)V", False, False), ("(I)V", False, False), ("(Landroid/view/View;)V", False, False)])
    newTab = JavaMethod("()Landroid/app/ActionBar$Tab;")
    addTab = JavaMultipleMethod([("(Landroid/app/ActionBar$Tab;Z)V", False, False), ("(Landroid/app/ActionBar$Tab;IZ)V", False, False), ("(Landroid/app/ActionBar$Tab;I)V", False, False), ("(Landroid/app/ActionBar$Tab;)V", False, False)])

    class TabListener(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "android/app/ActionBar$TabListener"
        onTabUnselected = JavaMethod("(Landroid/app/ActionBar$Tab;Landroid/app/FragmentTransaction;)V")
        onTabReselected = JavaMethod("(Landroid/app/ActionBar$Tab;Landroid/app/FragmentTransaction;)V")
        onTabSelected = JavaMethod("(Landroid/app/ActionBar$Tab;Landroid/app/FragmentTransaction;)V")

    class Tab(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "android/app/ActionBar$Tab"
        __javaconstructor__ = [("()V", False)]
        INVALID_POSITION = JavaStaticField("I")
        select = JavaMethod("()V")
        setTabListener = JavaMethod("(Landroid/app/ActionBar$TabListener;)Landroid/app/ActionBar$Tab;")
        getContentDescription = JavaMethod("()Ljava/lang/CharSequence;")
        getTag = JavaMethod("()Ljava/lang/Object;")
        setContentDescription = JavaMultipleMethod([("(I)Landroid/app/ActionBar$Tab;", False, False), ("(Ljava/lang/CharSequence;)Landroid/app/ActionBar$Tab;", False, False)])
        setTag = JavaMethod("(Ljava/lang/Object;)Landroid/app/ActionBar$Tab;")
        setIcon = JavaMultipleMethod([("(I)Landroid/app/ActionBar$Tab;", False, False), ("(Landroid/graphics/drawable/Drawable;)Landroid/app/ActionBar$Tab;", False, False)])
        getPosition = JavaMethod("()I")
        getCustomView = JavaMethod("()Landroid/view/View;")
        setCustomView = JavaMultipleMethod([("(Landroid/view/View;)Landroid/app/ActionBar$Tab;", False, False), ("(I)Landroid/app/ActionBar$Tab;", False, False)])
        getIcon = JavaMethod("()Landroid/graphics/drawable/Drawable;")
        getText = JavaMethod("()Ljava/lang/CharSequence;")
        setText = JavaMultipleMethod([("(I)Landroid/app/ActionBar$Tab;", False, False), ("(Ljava/lang/CharSequence;)Landroid/app/ActionBar$Tab;", False, False)])

    class OnNavigationListener(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "android/app/ActionBar$OnNavigationListener"
        onNavigationItemSelected = JavaMethod("(IJ)Z")

    class OnMenuVisibilityListener(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "android/app/ActionBar$OnMenuVisibilityListener"
        onMenuVisibilityChanged = JavaMethod("(Z)V")

    class LayoutParams(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "android/app/ActionBar$LayoutParams"
        __javaconstructor__ = [("(III)V", False), ("(II)V", False), ("(I)V", False), ("(Landroid/view/ViewGroup$LayoutParams;)V", False), ("(Landroid/content/Context;Landroid/util/AttributeSet;)V", False), ("(Landroid/app/ActionBar$LayoutParams;)V", False)]
        gravity = JavaField("I")
        bottomMargin = JavaField("I")
        leftMargin = JavaField("I")
        rightMargin = JavaField("I")
        topMargin = JavaField("I")
        FILL_PARENT = JavaStaticField("I")
        MATCH_PARENT = JavaStaticField("I")
        WRAP_CONTENT = JavaStaticField("I")
        height = JavaField("I")
        layoutAnimationParameters = JavaField("Landroid/view/animation/LayoutAnimationController$AnimationParameters;")
        width = JavaField("I")