from typing import Any, ClassVar, overload
from android.app.Activity import Activity
from android.app.PendingIntent import PendingIntent
from android.content.ComponentName import ComponentName
from android.content.Context import Context
from android.content.Intent import Intent
from android.content.pm.ConfigurationInfo import ConfigurationInfo
from android.graphics.Bitmap import Bitmap
from android.os.Bundle import Bundle
from android.os.Parcel import Parcel
from android.util.Size import Size
from java.io.FileDescriptor import FileDescriptor
from java.util.concurrent.Executor import Executor
from java.util.function.Consumer import Consumer

class ActivityManager:
    ACTION_REPORT_HEAP_LIMIT: ClassVar[str]
    LOCK_TASK_MODE_LOCKED: ClassVar[int]
    LOCK_TASK_MODE_NONE: ClassVar[int]
    LOCK_TASK_MODE_PINNED: ClassVar[int]
    META_HOME_ALTERNATE: ClassVar[str]
    MOVE_TASK_NO_USER_ACTION: ClassVar[int]
    MOVE_TASK_WITH_HOME: ClassVar[int]
    RECENT_IGNORE_UNAVAILABLE: ClassVar[int]
    RECENT_WITH_EXCLUDED: ClassVar[int]
    def addAppTask(self, p0: Activity, p1: Intent, p2: Any, p3: Bitmap) -> int: ...
    def addApplicationStartInfoCompletionListener(self, p0: Executor, p1: Consumer) -> None: ...
    def addStartInfoTimestamp(self, p0: int, p1: int) -> None: ...
    def appNotResponding(self, p0: str) -> None: ...
    def clearApplicationUserData(self) -> bool: ...
    def clearWatchHeapLimit(self) -> None: ...
    def dumpPackageState(self, p0: FileDescriptor, p1: str) -> None: ...
    def getAppTaskThumbnailSize(self) -> Size: ...
    def getAppTasks(self) -> list: ...
    def getDeviceConfigurationInfo(self) -> ConfigurationInfo: ...
    def getHistoricalProcessExitReasons(self, p0: str, p1: int, p2: int) -> list: ...
    def getHistoricalProcessStartReasons(self, p0: int) -> list: ...
    def getLargeMemoryClass(self) -> int: ...
    def getLauncherLargeIconDensity(self) -> int: ...
    def getLauncherLargeIconSize(self) -> int: ...
    def getLockTaskModeState(self) -> int: ...
    def getMemoryClass(self) -> int: ...
    def getMemoryInfo(self, p0: Any) -> None: ...
    @staticmethod
    def getMyMemoryState(p0: Any) -> None: ...
    def getProcessMemoryInfo(self, p0: Any) -> Any: ...
    def getProcessesInErrorState(self) -> list: ...
    def getRecentTasks(self, p0: int, p1: int) -> list: ...
    def getRunningAppProcesses(self) -> list: ...
    def getRunningServiceControlPanel(self, p0: ComponentName) -> PendingIntent: ...
    def getRunningServices(self, p0: int) -> list: ...
    def getRunningTasks(self, p0: int) -> list: ...
    def isActivityStartAllowedOnDisplay(self, p0: Context, p1: int, p2: Intent) -> bool: ...
    def isBackgroundRestricted(self) -> bool: ...
    def isInLockTaskMode(self) -> bool: ...
    def isLowRamDevice(self) -> bool: ...
    @staticmethod
    def setVrThread(p0: int) -> None: ...
    def setWatchHeapLimit(self, p0: int) -> None: ...
    def restartPackage(self, p0: str) -> None: ...
    @staticmethod
    def isRunningInTestHarness() -> bool: ...
    @staticmethod
    def isLowMemoryKillReportSupported() -> bool: ...
    @overload
    def moveTaskToFront(self, p0: int, p1: int, p2: Bundle) -> None: ...
    @overload
    def moveTaskToFront(self, p0: int, p1: int) -> None: ...
    @staticmethod
    def isRunningInUserTestHarness() -> bool: ...
    @staticmethod
    def isUserAMonkey() -> bool: ...
    def killBackgroundProcesses(self, p0: str) -> None: ...
    def removeApplicationStartInfoCompletionListener(self, p0: Consumer) -> None: ...
    def setProcessStateSummary(self, p0: Any) -> None: ...

    class TaskDescription:
        CREATOR: ClassVar[Any]
        CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
        PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
        @overload
        def __init__(self, p0: str, p1: int, p2: int) -> None: ...
        @overload
        def __init__(self, p0: str, p1: int) -> None: ...
        @overload
        def __init__(self) -> None: ...
        @overload
        def __init__(self, p0: Any) -> None: ...
        @overload
        def __init__(self, p0: str) -> None: ...
        @overload
        def __init__(self, p0: str, p1: Bitmap) -> None: ...
        @overload
        def __init__(self, p0: str, p1: Bitmap, p2: int) -> None: ...
        def getNavigationBarColor(self) -> int: ...
        def getStatusBarColor(self) -> int: ...
        def getPrimaryColor(self) -> int: ...
        def equals(self, p0: Any) -> bool: ...
        def toString(self) -> str: ...
        def hashCode(self) -> int: ...
        def getLabel(self) -> str: ...
        def getBackgroundColor(self) -> int: ...
        def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
        def readFromParcel(self, p0: Parcel) -> None: ...
        def describeContents(self) -> int: ...
        def getIcon(self) -> Bitmap: ...

        class Builder:
            def __init__(self) -> None: ...
            def setBackgroundColor(self, p0: int) -> Any: ...
            def setIcon(self, p0: int) -> Any: ...
            def setPrimaryColor(self, p0: int) -> Any: ...
            def setLabel(self, p0: str) -> Any: ...
            def build(self) -> Any: ...
            def setNavigationBarColor(self, p0: int) -> Any: ...
            def setStatusBarColor(self, p0: int) -> Any: ...

    class RunningTaskInfo:
        CREATOR: ClassVar[Any]
        CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
        PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
        description: str
        id: int
        numRunning: int
        thumbnail: Bitmap
        baseActivity: ComponentName
        baseIntent: Intent
        isRunning: bool
        numActivities: int
        origActivity: ComponentName
        taskDescription: Any
        taskId: int
        topActivity: ComponentName
        def __init__(self) -> None: ...
        def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
        def readFromParcel(self, p0: Parcel) -> None: ...
        def describeContents(self) -> int: ...

    class RunningServiceInfo:
        CREATOR: ClassVar[Any]
        FLAG_FOREGROUND: ClassVar[int]
        FLAG_PERSISTENT_PROCESS: ClassVar[int]
        FLAG_STARTED: ClassVar[int]
        FLAG_SYSTEM_PROCESS: ClassVar[int]
        CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
        PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
        activeSince: int
        clientCount: int
        clientLabel: int
        clientPackage: str
        crashCount: int
        flags: int
        foreground: bool
        lastActivityTime: int
        pid: int
        process: str
        restarting: int
        service: ComponentName
        started: bool
        uid: int
        def __init__(self) -> None: ...
        def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
        def readFromParcel(self, p0: Parcel) -> None: ...
        def describeContents(self) -> int: ...

    class RunningAppProcessInfo:
        CREATOR: ClassVar[Any]
        IMPORTANCE_BACKGROUND: ClassVar[int]
        IMPORTANCE_CACHED: ClassVar[int]
        IMPORTANCE_CANT_SAVE_STATE: ClassVar[int]
        IMPORTANCE_EMPTY: ClassVar[int]
        IMPORTANCE_FOREGROUND: ClassVar[int]
        IMPORTANCE_FOREGROUND_SERVICE: ClassVar[int]
        IMPORTANCE_GONE: ClassVar[int]
        IMPORTANCE_PERCEPTIBLE: ClassVar[int]
        IMPORTANCE_PERCEPTIBLE_PRE_26: ClassVar[int]
        IMPORTANCE_SERVICE: ClassVar[int]
        IMPORTANCE_TOP_SLEEPING: ClassVar[int]
        IMPORTANCE_TOP_SLEEPING_PRE_28: ClassVar[int]
        IMPORTANCE_VISIBLE: ClassVar[int]
        REASON_PROVIDER_IN_USE: ClassVar[int]
        REASON_SERVICE_IN_USE: ClassVar[int]
        REASON_UNKNOWN: ClassVar[int]
        CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
        PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
        importance: int
        importanceReasonCode: int
        importanceReasonComponent: ComponentName
        importanceReasonPid: int
        lastTrimLevel: int
        lru: int
        pid: int
        pkgList: Any
        processName: str
        uid: int
        @overload
        def __init__(self) -> None: ...
        @overload
        def __init__(self, p0: str, p1: int, p2: Any) -> None: ...
        def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
        def readFromParcel(self, p0: Parcel) -> None: ...
        def describeContents(self) -> int: ...

    class RecentTaskInfo:
        CREATOR: ClassVar[Any]
        CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
        PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
        affiliatedTaskId: int
        description: str
        id: int
        persistentId: int
        baseActivity: ComponentName
        baseIntent: Intent
        isRunning: bool
        numActivities: int
        origActivity: ComponentName
        taskDescription: Any
        taskId: int
        topActivity: ComponentName
        def __init__(self) -> None: ...
        def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
        def readFromParcel(self, p0: Parcel) -> None: ...
        def describeContents(self) -> int: ...

    class ProcessErrorStateInfo:
        CRASHED: ClassVar[int]
        CREATOR: ClassVar[Any]
        NOT_RESPONDING: ClassVar[int]
        NO_ERROR: ClassVar[int]
        CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
        PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
        condition: int
        crashData: Any
        longMsg: str
        pid: int
        processName: str
        shortMsg: str
        stackTrace: str
        tag: str
        uid: int
        def __init__(self) -> None: ...
        def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
        def readFromParcel(self, p0: Parcel) -> None: ...
        def describeContents(self) -> int: ...

    class MemoryInfo:
        CREATOR: ClassVar[Any]
        CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
        PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
        advertisedMem: int
        availMem: int
        lowMemory: bool
        threshold: int
        totalMem: int
        def __init__(self) -> None: ...
        def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
        def readFromParcel(self, p0: Parcel) -> None: ...
        def describeContents(self) -> int: ...

    class AppTask:
        def finishAndRemoveTask(self) -> None: ...
        def getTaskInfo(self) -> Any: ...
        def moveToFront(self) -> None: ...
        def setExcludeFromRecents(self, p0: bool) -> None: ...
        def startActivity(self, p0: Context, p1: Intent, p2: Bundle) -> None: ...
