from typing import Any, ClassVar, overload
from android.app.Activity import Activity
from android.app.PendingIntent import PendingIntent
from android.app.PictureInPictureParams import PictureInPictureParams
from android.content.Context import Context
from android.graphics.Bitmap import Bitmap
from android.graphics.Rect import Rect
from android.os.Bundle import Bundle
from android.view.View import View

class ActivityOptions:
    EXTRA_USAGE_TIME_REPORT: ClassVar[str]
    EXTRA_USAGE_TIME_REPORT_PACKAGES: ClassVar[str]
    MODE_BACKGROUND_ACTIVITY_START_ALLOWED: ClassVar[int]
    MODE_BACKGROUND_ACTIVITY_START_ALLOW_ALWAYS: ClassVar[int]
    MODE_BACKGROUND_ACTIVITY_START_ALLOW_IF_VISIBLE: ClassVar[int]
    MODE_BACKGROUND_ACTIVITY_START_DENIED: ClassVar[int]
    MODE_BACKGROUND_ACTIVITY_START_SYSTEM_DEFINED: ClassVar[int]
    def toString(self) -> str: ...
    def update(self, p0: "ActivityOptions") -> None: ...
    def getLockTaskMode(self) -> bool: ...
    @staticmethod
    def makeBasic() -> "ActivityOptions": ...
    def getLaunchBounds(self) -> Rect: ...
    def getLaunchDisplayId(self) -> int: ...
    def getSplashScreenStyle(self) -> int: ...
    def getPendingIntentBackgroundActivityStartMode(self) -> int: ...
    def getPendingIntentCreatorBackgroundActivityStartMode(self) -> int: ...
    def isAllowPassThroughOnTouchOutside(self) -> bool: ...
    def isPendingIntentBackgroundActivityLaunchAllowed(self) -> bool: ...
    def isShareIdentityEnabled(self) -> bool: ...
    @staticmethod
    def makeClipRevealAnimation(p0: View, p1: int, p2: int, p3: int, p4: int) -> "ActivityOptions": ...
    @overload
    @staticmethod
    def makeCustomAnimation(p0: Context, p1: int, p2: int) -> "ActivityOptions": ...
    @overload
    @staticmethod
    def makeCustomAnimation(p0: Context, p1: int, p2: int, p3: int) -> "ActivityOptions": ...
    @staticmethod
    def makeLaunchIntoPip(p0: PictureInPictureParams) -> "ActivityOptions": ...
    @staticmethod
    def makeScaleUpAnimation(p0: View, p1: int, p2: int, p3: int, p4: int) -> "ActivityOptions": ...
    @overload
    @staticmethod
    def makeSceneTransitionAnimation(p0: Activity, p1: View, p2: str) -> "ActivityOptions": ...
    @overload
    @staticmethod
    def makeSceneTransitionAnimation(p0: Activity, p1: Any) -> "ActivityOptions": ...
    @staticmethod
    def makeTaskLaunchBehind() -> "ActivityOptions": ...
    @staticmethod
    def makeThumbnailScaleUpAnimation(p0: View, p1: Bitmap, p2: int, p3: int) -> "ActivityOptions": ...
    def requestUsageTimeReport(self, p0: PendingIntent) -> None: ...
    def setAllowPassThroughOnTouchOutside(self, p0: bool) -> None: ...
    def setAppVerificationBundle(self, p0: Bundle) -> "ActivityOptions": ...
    def setLaunchBounds(self, p0: Rect) -> "ActivityOptions": ...
    def setLaunchDisplayId(self, p0: int) -> "ActivityOptions": ...
    def setLockTaskEnabled(self, p0: bool) -> "ActivityOptions": ...
    def setPendingIntentBackgroundActivityLaunchAllowed(self, p0: bool) -> None: ...
    def setPendingIntentBackgroundActivityStartMode(self, p0: int) -> "ActivityOptions": ...
    def setPendingIntentCreatorBackgroundActivityStartMode(self, p0: int) -> "ActivityOptions": ...
    def setShareIdentityEnabled(self, p0: bool) -> "ActivityOptions": ...
    def setSplashScreenStyle(self, p0: int) -> "ActivityOptions": ...
    def toBundle(self) -> Bundle: ...
