from typing import Any, ClassVar, overload
from android.app.PendingIntent import PendingIntent
from android.os.Handler import Handler
from android.os.Parcel import Parcel
from java.util.concurrent.Executor import Executor

class AlarmManager:
    ACTION_NEXT_ALARM_CLOCK_CHANGED: ClassVar[str]
    ACTION_SCHEDULE_EXACT_ALARM_PERMISSION_STATE_CHANGED: ClassVar[str]
    ELAPSED_REALTIME: ClassVar[int]
    ELAPSED_REALTIME_WAKEUP: ClassVar[int]
    INTERVAL_DAY: ClassVar[int]
    INTERVAL_FIFTEEN_MINUTES: ClassVar[int]
    INTERVAL_HALF_DAY: ClassVar[int]
    INTERVAL_HALF_HOUR: ClassVar[int]
    INTERVAL_HOUR: ClassVar[int]
    RTC: ClassVar[int]
    RTC_WAKEUP: ClassVar[int]
    @overload
    def setWindow(self, p0: int, p1: int, p2: int, p3: PendingIntent) -> None: ...
    @overload
    def setWindow(self, p0: int, p1: int, p2: int, p3: str, p4: Any, p5: Handler) -> None: ...
    @overload
    def setWindow(self, p0: int, p1: int, p2: int, p3: str, p4: Executor, p5: Any) -> None: ...
    def cancelAll(self) -> None: ...
    @overload
    def set(self, p0: int, p1: int, p2: PendingIntent) -> None: ...
    @overload
    def set(self, p0: int, p1: int, p2: str, p3: Any, p4: Handler) -> None: ...
    @overload
    def cancel(self, p0: PendingIntent) -> None: ...
    @overload
    def cancel(self, p0: Any) -> None: ...
    def setTimeZone(self, p0: str) -> None: ...
    def canScheduleExactAlarms(self) -> bool: ...
    def getNextAlarmClock(self) -> Any: ...
    def setAlarmClock(self, p0: Any, p1: PendingIntent) -> None: ...
    def setAndAllowWhileIdle(self, p0: int, p1: int, p2: PendingIntent) -> None: ...
    @overload
    def setExact(self, p0: int, p1: int, p2: PendingIntent) -> None: ...
    @overload
    def setExact(self, p0: int, p1: int, p2: str, p3: Any, p4: Handler) -> None: ...
    def setExactAndAllowWhileIdle(self, p0: int, p1: int, p2: PendingIntent) -> None: ...
    def setInexactRepeating(self, p0: int, p1: int, p2: int, p3: PendingIntent) -> None: ...
    def setRepeating(self, p0: int, p1: int, p2: int, p3: PendingIntent) -> None: ...
    def setTime(self, p0: int) -> None: ...

    class OnAlarmListener:
        def onAlarm(self) -> None: ...

    class AlarmClockInfo:
        CREATOR: ClassVar[Any]
        CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
        PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
        def __init__(self, p0: int, p1: PendingIntent) -> None: ...
        def getShowIntent(self) -> PendingIntent: ...
        def getTriggerTime(self) -> int: ...
        def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
        def describeContents(self) -> int: ...
