from typing import Any, ClassVar, overload
from android.content.Context import Context
from android.content.DialogInterface import DialogInterface
from android.os.Bundle import Bundle
from android.widget.DatePicker import DatePicker

class DatePickerDialog:
    THEME_DEVICE_DEFAULT_DARK: ClassVar[int]
    THEME_DEVICE_DEFAULT_LIGHT: ClassVar[int]
    THEME_HOLO_DARK: ClassVar[int]
    THEME_HOLO_LIGHT: ClassVar[int]
    THEME_TRADITIONAL: ClassVar[int]
    BUTTON1: ClassVar[int]
    BUTTON2: ClassVar[int]
    BUTTON3: ClassVar[int]
    BUTTON_NEGATIVE: ClassVar[int]
    BUTTON_NEUTRAL: ClassVar[int]
    BUTTON_POSITIVE: ClassVar[int]
    @overload
    def __init__(self, p0: Context) -> None: ...
    @overload
    def __init__(self, p0: Context, p1: int, p2: Any, p3: int, p4: int, p5: int) -> None: ...
    @overload
    def __init__(self, p0: Context, p1: int) -> None: ...
    @overload
    def __init__(self, p0: Context, p1: Any, p2: int, p3: int, p4: int) -> None: ...
    def getDatePicker(self) -> DatePicker: ...
    def setOnDateSetListener(self, p0: Any) -> None: ...
    def onClick(self, p0: DialogInterface, p1: int) -> None: ...
    def onRestoreInstanceState(self, p0: Bundle) -> None: ...
    def onSaveInstanceState(self) -> Bundle: ...
    def updateDate(self, p0: int, p1: int, p2: int) -> None: ...
    def onDateChanged(self, p0: DatePicker, p1: int, p2: int, p3: int) -> None: ...

    class OnDateSetListener:
        def onDateSet(self, p0: DatePicker, p1: int, p2: int, p3: int) -> None: ...
