from typing import Any, ClassVar, overload
from android.view.View import View

class FragmentContainer:
    def __init__(self) -> None: ...
    def onFindViewById(self, p0: int) -> View: ...
    def onHasView(self) -> bool: ...
