from typing import Any, ClassVar, overload
from android.os.Parcel import Parcel

class GameState:
    CREATOR: ClassVar[Any]
    MODE_CONTENT: ClassVar[int]
    MODE_GAMEPLAY_INTERRUPTIBLE: ClassVar[int]
    MODE_GAMEPLAY_UNINTERRUPTIBLE: ClassVar[int]
    MODE_NONE: ClassVar[int]
    MODE_UNKNOWN: ClassVar[int]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    @overload
    def __init__(self, p0: bool, p1: int) -> None: ...
    @overload
    def __init__(self, p0: bool, p1: int, p2: int, p3: int) -> None: ...
    def isLoading(self) -> bool: ...
    def getLabel(self) -> int: ...
    def getMode(self) -> int: ...
    def getQuality(self) -> int: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
    def describeContents(self) -> int: ...
