from typing import Any, ClassVar, overload
from android.app.PendingIntent import PendingIntent
from android.app.Person import Person
from android.app.RemoteInput import RemoteInput
from android.content.Context import Context
from android.content.LocusId import LocusId
from android.graphics.Bitmap import Bitmap
from android.graphics.drawable.Icon import Icon
from android.media.AudioAttributes import AudioAttributes
from android.net.Uri import Uri
from android.os.Bundle import Bundle
from android.os.Parcel import Parcel
from android.util.Pair import Pair
from android.widget.RemoteViews import RemoteViews

class Notification:
    AUDIO_ATTRIBUTES_DEFAULT: ClassVar[AudioAttributes]
    BADGE_ICON_LARGE: ClassVar[int]
    BADGE_ICON_NONE: ClassVar[int]
    BADGE_ICON_SMALL: ClassVar[int]
    CATEGORY_ALARM: ClassVar[str]
    CATEGORY_CALL: ClassVar[str]
    CATEGORY_EMAIL: ClassVar[str]
    CATEGORY_ERROR: ClassVar[str]
    CATEGORY_EVENT: ClassVar[str]
    CATEGORY_LOCATION_SHARING: ClassVar[str]
    CATEGORY_MESSAGE: ClassVar[str]
    CATEGORY_MISSED_CALL: ClassVar[str]
    CATEGORY_NAVIGATION: ClassVar[str]
    CATEGORY_PROGRESS: ClassVar[str]
    CATEGORY_PROMO: ClassVar[str]
    CATEGORY_RECOMMENDATION: ClassVar[str]
    CATEGORY_REMINDER: ClassVar[str]
    CATEGORY_SERVICE: ClassVar[str]
    CATEGORY_SOCIAL: ClassVar[str]
    CATEGORY_STATUS: ClassVar[str]
    CATEGORY_STOPWATCH: ClassVar[str]
    CATEGORY_SYSTEM: ClassVar[str]
    CATEGORY_TRANSPORT: ClassVar[str]
    CATEGORY_VOICEMAIL: ClassVar[str]
    CATEGORY_WORKOUT: ClassVar[str]
    COLOR_DEFAULT: ClassVar[int]
    CREATOR: ClassVar[Any]
    DEFAULT_ALL: ClassVar[int]
    DEFAULT_LIGHTS: ClassVar[int]
    DEFAULT_SOUND: ClassVar[int]
    DEFAULT_VIBRATE: ClassVar[int]
    EXTRA_ANSWER_COLOR: ClassVar[str]
    EXTRA_ANSWER_INTENT: ClassVar[str]
    EXTRA_AUDIO_CONTENTS_URI: ClassVar[str]
    EXTRA_BACKGROUND_IMAGE_URI: ClassVar[str]
    EXTRA_BIG_TEXT: ClassVar[str]
    EXTRA_CALL_IS_VIDEO: ClassVar[str]
    EXTRA_CALL_PERSON: ClassVar[str]
    EXTRA_CALL_TYPE: ClassVar[str]
    EXTRA_CHANNEL_GROUP_ID: ClassVar[str]
    EXTRA_CHANNEL_ID: ClassVar[str]
    EXTRA_CHRONOMETER_COUNT_DOWN: ClassVar[str]
    EXTRA_COLORIZED: ClassVar[str]
    EXTRA_COMPACT_ACTIONS: ClassVar[str]
    EXTRA_CONVERSATION_TITLE: ClassVar[str]
    EXTRA_DECLINE_COLOR: ClassVar[str]
    EXTRA_DECLINE_INTENT: ClassVar[str]
    EXTRA_HANG_UP_INTENT: ClassVar[str]
    EXTRA_HISTORIC_MESSAGES: ClassVar[str]
    EXTRA_INFO_TEXT: ClassVar[str]
    EXTRA_IS_GROUP_CONVERSATION: ClassVar[str]
    EXTRA_LARGE_ICON: ClassVar[str]
    EXTRA_LARGE_ICON_BIG: ClassVar[str]
    EXTRA_MEDIA_SESSION: ClassVar[str]
    EXTRA_MESSAGES: ClassVar[str]
    EXTRA_MESSAGING_PERSON: ClassVar[str]
    EXTRA_NOTIFICATION_ID: ClassVar[str]
    EXTRA_NOTIFICATION_TAG: ClassVar[str]
    EXTRA_PEOPLE: ClassVar[str]
    EXTRA_PEOPLE_LIST: ClassVar[str]
    EXTRA_PICTURE: ClassVar[str]
    EXTRA_PICTURE_CONTENT_DESCRIPTION: ClassVar[str]
    EXTRA_PICTURE_ICON: ClassVar[str]
    EXTRA_PROGRESS: ClassVar[str]
    EXTRA_PROGRESS_INDETERMINATE: ClassVar[str]
    EXTRA_PROGRESS_MAX: ClassVar[str]
    EXTRA_REMOTE_INPUT_DRAFT: ClassVar[str]
    EXTRA_REMOTE_INPUT_HISTORY: ClassVar[str]
    EXTRA_SELF_DISPLAY_NAME: ClassVar[str]
    EXTRA_SHOW_BIG_PICTURE_WHEN_COLLAPSED: ClassVar[str]
    EXTRA_SHOW_CHRONOMETER: ClassVar[str]
    EXTRA_SHOW_WHEN: ClassVar[str]
    EXTRA_SMALL_ICON: ClassVar[str]
    EXTRA_SUB_TEXT: ClassVar[str]
    EXTRA_SUMMARY_TEXT: ClassVar[str]
    EXTRA_TEMPLATE: ClassVar[str]
    EXTRA_TEXT: ClassVar[str]
    EXTRA_TEXT_LINES: ClassVar[str]
    EXTRA_TITLE: ClassVar[str]
    EXTRA_TITLE_BIG: ClassVar[str]
    EXTRA_VERIFICATION_ICON: ClassVar[str]
    EXTRA_VERIFICATION_TEXT: ClassVar[str]
    FLAG_AUTO_CANCEL: ClassVar[int]
    FLAG_BUBBLE: ClassVar[int]
    FLAG_FOREGROUND_SERVICE: ClassVar[int]
    FLAG_GROUP_SUMMARY: ClassVar[int]
    FLAG_HIGH_PRIORITY: ClassVar[int]
    FLAG_INSISTENT: ClassVar[int]
    FLAG_LOCAL_ONLY: ClassVar[int]
    FLAG_NO_CLEAR: ClassVar[int]
    FLAG_ONGOING_EVENT: ClassVar[int]
    FLAG_ONLY_ALERT_ONCE: ClassVar[int]
    FLAG_PROMOTED_ONGOING: ClassVar[int]
    FLAG_SHOW_LIGHTS: ClassVar[int]
    FOREGROUND_SERVICE_DEFAULT: ClassVar[int]
    FOREGROUND_SERVICE_DEFERRED: ClassVar[int]
    FOREGROUND_SERVICE_IMMEDIATE: ClassVar[int]
    GROUP_ALERT_ALL: ClassVar[int]
    GROUP_ALERT_CHILDREN: ClassVar[int]
    GROUP_ALERT_SUMMARY: ClassVar[int]
    INTENT_CATEGORY_NOTIFICATION_PREFERENCES: ClassVar[str]
    PRIORITY_DEFAULT: ClassVar[int]
    PRIORITY_HIGH: ClassVar[int]
    PRIORITY_LOW: ClassVar[int]
    PRIORITY_MAX: ClassVar[int]
    PRIORITY_MIN: ClassVar[int]
    STREAM_DEFAULT: ClassVar[int]
    VISIBILITY_PRIVATE: ClassVar[int]
    VISIBILITY_PUBLIC: ClassVar[int]
    VISIBILITY_SECRET: ClassVar[int]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    actions: Any
    audioAttributes: AudioAttributes
    audioStreamType: int
    bigContentView: RemoteViews
    category: str
    color: int
    contentIntent: PendingIntent
    contentView: RemoteViews
    defaults: int
    deleteIntent: PendingIntent
    extras: Bundle
    flags: int
    fullScreenIntent: PendingIntent
    headsUpContentView: RemoteViews
    icon: int
    iconLevel: int
    largeIcon: Bitmap
    ledARGB: int
    ledOffMS: int
    ledOnMS: int
    number: int
    priority: int
    publicVersion: "Notification"
    sound: Uri
    tickerText: str
    tickerView: RemoteViews
    vibrate: Any
    visibility: int
    when: int
    @overload
    def __init__(self, p0: Parcel) -> None: ...
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, p0: int, p1: str, p2: int) -> None: ...
    def findRemoteInputActionPair(self, p0: bool) -> Pair: ...
    def getAllowSystemGeneratedContextualActions(self) -> bool: ...
    def getBadgeIconType(self) -> int: ...
    def getBubbleMetadata(self) -> Any: ...
    def getChannelId(self) -> str: ...
    def getContextualActions(self) -> list: ...
    def getGroupAlertBehavior(self) -> int: ...
    def getLargeIcon(self) -> Icon: ...
    def getSettingsText(self) -> str: ...
    def getShortCriticalText(self) -> str: ...
    def getShortcutId(self) -> str: ...
    def getSmallIcon(self) -> Icon: ...
    def getSortKey(self) -> str: ...
    def getTimeoutAfter(self) -> int: ...
    def hasImage(self) -> bool: ...
    def hasPromotableCharacteristics(self) -> bool: ...
    def toString(self) -> str: ...
    @overload
    def clone(self) -> Any: ...
    @overload
    def clone(self) -> "Notification": ...
    def getGroup(self) -> str: ...
    def getLocusId(self) -> LocusId: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
    def describeContents(self) -> int: ...

    class WearableExtender:
        SCREEN_TIMEOUT_LONG: ClassVar[int]
        SCREEN_TIMEOUT_SHORT: ClassVar[int]
        SIZE_DEFAULT: ClassVar[int]
        SIZE_FULL_SCREEN: ClassVar[int]
        SIZE_LARGE: ClassVar[int]
        SIZE_MEDIUM: ClassVar[int]
        SIZE_SMALL: ClassVar[int]
        SIZE_XSMALL: ClassVar[int]
        UNSET_ACTION_INDEX: ClassVar[int]
        @overload
        def __init__(self, p0: "Notification") -> None: ...
        @overload
        def __init__(self) -> None: ...
        def getPages(self) -> list: ...
        def addPages(self, p0: list) -> Any: ...
        def addPage(self, p0: "Notification") -> Any: ...
        def addActions(self, p0: list) -> Any: ...
        def clearActions(self) -> Any: ...
        def clearPages(self) -> Any: ...
        def getBridgeTag(self) -> str: ...
        def getContentAction(self) -> int: ...
        def getContentIcon(self) -> int: ...
        def getContentIconGravity(self) -> int: ...
        def getContentIntentAvailableOffline(self) -> bool: ...
        def getCustomContentHeight(self) -> int: ...
        def getCustomSizePreset(self) -> int: ...
        def getDismissalId(self) -> str: ...
        def getDisplayIntent(self) -> PendingIntent: ...
        def getHintAmbientBigPicture(self) -> bool: ...
        def getHintAvoidBackgroundClipping(self) -> bool: ...
        def getHintContentIntentLaunchesActivity(self) -> bool: ...
        def getHintHideIcon(self) -> bool: ...
        def getHintScreenTimeout(self) -> int: ...
        def getHintShowBackgroundOnly(self) -> bool: ...
        def getStartScrollBottom(self) -> bool: ...
        def setBridgeTag(self, p0: str) -> Any: ...
        def setContentAction(self, p0: int) -> Any: ...
        def setContentIcon(self, p0: int) -> Any: ...
        def setContentIconGravity(self, p0: int) -> Any: ...
        def setContentIntentAvailableOffline(self, p0: bool) -> Any: ...
        def setCustomContentHeight(self, p0: int) -> Any: ...
        def setCustomSizePreset(self, p0: int) -> Any: ...
        def setDismissalId(self, p0: str) -> Any: ...
        def setDisplayIntent(self, p0: PendingIntent) -> Any: ...
        def setHintAmbientBigPicture(self, p0: bool) -> Any: ...
        def setHintAvoidBackgroundClipping(self, p0: bool) -> Any: ...
        def setHintContentIntentLaunchesActivity(self, p0: bool) -> Any: ...
        def setHintHideIcon(self, p0: bool) -> Any: ...
        def setHintScreenTimeout(self, p0: int) -> Any: ...
        def setHintShowBackgroundOnly(self, p0: bool) -> Any: ...
        def setStartScrollBottom(self, p0: bool) -> Any: ...
        @overload
        def clone(self) -> Any: ...
        @overload
        def clone(self) -> Any: ...
        def extend(self, p0: Any) -> Any: ...
        def addAction(self, p0: Any) -> Any: ...
        def getActions(self) -> list: ...
        def getGravity(self) -> int: ...
        def setGravity(self, p0: int) -> Any: ...

    class TvExtender:
        @overload
        def __init__(self) -> None: ...
        @overload
        def __init__(self, p0: "Notification") -> None: ...
        def getChannelId(self) -> str: ...
        def getDeleteIntent(self) -> PendingIntent: ...
        def extend(self, p0: Any) -> Any: ...
        def setChannelId(self, p0: str) -> Any: ...
        def setContentIntent(self, p0: PendingIntent) -> Any: ...
        def setDeleteIntent(self, p0: PendingIntent) -> Any: ...
        def getContentIntent(self) -> PendingIntent: ...
        def isAvailableOnTv(self) -> bool: ...
        def isSuppressShowOverApps(self) -> bool: ...
        def setSuppressShowOverApps(self, p0: bool) -> Any: ...

    class Style:
        def __init__(self) -> None: ...
        def build(self) -> "Notification": ...
        def setBuilder(self, p0: Any) -> None: ...

    class ProgressStyle:
        def __init__(self) -> None: ...
        def getProgress(self) -> int: ...
        def setProgress(self, p0: int) -> Any: ...
        def addProgressPoint(self, p0: Any) -> Any: ...
        def addProgressSegment(self, p0: Any) -> Any: ...
        def getProgressEndIcon(self) -> Icon: ...
        def getProgressMax(self) -> int: ...
        def getProgressPoints(self) -> list: ...
        def getProgressSegments(self) -> list: ...
        def getProgressStartIcon(self) -> Icon: ...
        def getProgressTrackerIcon(self) -> Icon: ...
        def isProgressIndeterminate(self) -> bool: ...
        def isStyledByProgress(self) -> bool: ...
        def setProgressEndIcon(self, p0: Icon) -> Any: ...
        def setProgressIndeterminate(self, p0: bool) -> Any: ...
        def setProgressPoints(self, p0: list) -> Any: ...
        def setProgressSegments(self, p0: list) -> Any: ...
        def setProgressStartIcon(self, p0: Icon) -> Any: ...
        def setProgressTrackerIcon(self, p0: Icon) -> Any: ...
        def setStyledByProgress(self, p0: bool) -> Any: ...

        class Segment:
            def __init__(self, p0: int) -> None: ...
            def equals(self, p0: Any) -> bool: ...
            def hashCode(self) -> int: ...
            def getLength(self) -> int: ...
            def getId(self) -> int: ...
            def setId(self, p0: int) -> Any: ...
            def setColor(self, p0: int) -> Any: ...
            def getColor(self) -> int: ...

        class Point:
            def __init__(self, p0: int) -> None: ...
            def equals(self, p0: Any) -> bool: ...
            def hashCode(self) -> int: ...
            def getId(self) -> int: ...
            def setId(self, p0: int) -> Any: ...
            def setColor(self, p0: int) -> Any: ...
            def getPosition(self) -> int: ...
            def getColor(self) -> int: ...

    class MessagingStyle:
        MAXIMUM_RETAINED_MESSAGES: ClassVar[int]
        @overload
        def __init__(self, p0: Person) -> None: ...
        @overload
        def __init__(self, p0: str) -> None: ...
        def getUser(self) -> Person: ...
        def addHistoricMessage(self, p0: Any) -> Any: ...
        @overload
        def addMessage(self, p0: str, p1: int, p2: Person) -> Any: ...
        @overload
        def addMessage(self, p0: str, p1: int, p2: str) -> Any: ...
        @overload
        def addMessage(self, p0: Any) -> Any: ...
        def getConversationTitle(self) -> str: ...
        def getHistoricMessages(self) -> list: ...
        def getMessages(self) -> list: ...
        def getUserDisplayName(self) -> str: ...
        def isGroupConversation(self) -> bool: ...
        def setConversationTitle(self, p0: str) -> Any: ...
        def setGroupConversation(self, p0: bool) -> Any: ...

        class Message:
            @overload
            def __init__(self, p0: str, p1: int, p2: Person) -> None: ...
            @overload
            def __init__(self, p0: str, p1: int, p2: str) -> None: ...
            def setData(self, p0: str, p1: Uri) -> Any: ...
            def getExtras(self) -> Bundle: ...
            def getTimestamp(self) -> int: ...
            def getText(self) -> str: ...
            def getSenderPerson(self) -> Person: ...
            def getSender(self) -> str: ...
            def getDataMimeType(self) -> str: ...
            def getDataUri(self) -> Uri: ...
            @staticmethod
            def getMessagesFromBundleArray(p0: Any) -> list: ...

    class MediaStyle:
        @overload
        def __init__(self) -> None: ...
        @overload
        def __init__(self, p0: Any) -> None: ...
        def setMediaSession(self, p0: Any) -> Any: ...
        def setRemotePlaybackInfo(self, p0: str, p1: int, p2: PendingIntent) -> Any: ...
        def setShowActionsInCompactView(self, p0: Any) -> Any: ...

    class InboxStyle:
        @overload
        def __init__(self) -> None: ...
        @overload
        def __init__(self, p0: Any) -> None: ...
        def addLine(self, p0: str) -> Any: ...
        def setBigContentTitle(self, p0: str) -> Any: ...
        def setSummaryText(self, p0: str) -> Any: ...

    class Extender:
        def extend(self, p0: Any) -> Any: ...

    class DecoratedMediaCustomViewStyle:
        def __init__(self) -> None: ...

    class DecoratedCustomViewStyle:
        def __init__(self) -> None: ...

    class CarExtender:
        @overload
        def __init__(self) -> None: ...
        @overload
        def __init__(self, p0: "Notification") -> None: ...
        def getLargeIcon(self) -> Bitmap: ...
        def getUnreadConversation(self) -> Any: ...
        def setLargeIcon(self, p0: Bitmap) -> Any: ...
        def setUnreadConversation(self, p0: Any) -> Any: ...
        def extend(self, p0: Any) -> Any: ...
        def setColor(self, p0: int) -> Any: ...
        def getColor(self) -> int: ...

        class UnreadConversation:
            def getReplyPendingIntent(self) -> PendingIntent: ...
            def getParticipants(self) -> Any: ...
            def getReadPendingIntent(self) -> PendingIntent: ...
            def getRemoteInput(self) -> RemoteInput: ...
            def getLatestTimestamp(self) -> int: ...
            def getParticipant(self) -> str: ...
            def getMessages(self) -> Any: ...

        class Builder:
            def __init__(self, p0: str) -> None: ...
            def setReadPendingIntent(self, p0: PendingIntent) -> Any: ...
            def setReplyAction(self, p0: PendingIntent, p1: RemoteInput) -> Any: ...
            def setLatestTimestamp(self, p0: int) -> Any: ...
            def build(self) -> Any: ...
            def addMessage(self, p0: str) -> Any: ...

    class CallStyle:
        CALL_TYPE_INCOMING: ClassVar[int]
        CALL_TYPE_ONGOING: ClassVar[int]
        CALL_TYPE_SCREENING: ClassVar[int]
        CALL_TYPE_UNKNOWN: ClassVar[int]
        @staticmethod
        def forIncomingCall(p0: Person, p1: PendingIntent, p2: PendingIntent) -> Any: ...
        @staticmethod
        def forOngoingCall(p0: Person, p1: PendingIntent) -> Any: ...
        @staticmethod
        def forScreeningCall(p0: Person, p1: PendingIntent, p2: PendingIntent) -> Any: ...
        def setAnswerButtonColorHint(self, p0: int) -> Any: ...
        def setDeclineButtonColorHint(self, p0: int) -> Any: ...
        def setIsVideo(self, p0: bool) -> Any: ...
        def setVerificationIcon(self, p0: Icon) -> Any: ...
        def setVerificationText(self, p0: str) -> Any: ...

    class Builder:
        @overload
        def __init__(self, p0: Context) -> None: ...
        @overload
        def __init__(self, p0: Context, p1: str) -> None: ...
        def setLocusId(self, p0: LocusId) -> Any: ...
        def setGroup(self, p0: str) -> Any: ...
        @overload
        def setSound(self, p0: Uri, p1: AudioAttributes) -> Any: ...
        @overload
        def setSound(self, p0: Uri) -> Any: ...
        @overload
        def setSound(self, p0: Uri, p1: int) -> Any: ...
        def getNotification(self) -> "Notification": ...
        def setActions(self, p0: Any) -> Any: ...
        def setNumber(self, p0: int) -> Any: ...
        @overload
        def setLargeIcon(self, p0: Bitmap) -> Any: ...
        @overload
        def setLargeIcon(self, p0: Icon) -> Any: ...
        def setPriority(self, p0: int) -> Any: ...
        def setContent(self, p0: RemoteViews) -> Any: ...
        def setVisibility(self, p0: int) -> Any: ...
        def extend(self, p0: Any) -> Any: ...
        def setChronometerCountDown(self, p0: bool) -> Any: ...
        def setColor(self, p0: int) -> Any: ...
        def setExtras(self, p0: Bundle) -> Any: ...
        def getStyle(self) -> Any: ...
        @overload
        def addAction(self, p0: int, p1: str, p2: PendingIntent) -> Any: ...
        @overload
        def addAction(self, p0: Any) -> Any: ...
        def getExtras(self) -> Bundle: ...
        def build(self) -> "Notification": ...
        def setStyle(self, p0: Any) -> Any: ...
        @staticmethod
        def recoverBuilder(p0: Context, p1: "Notification") -> Any: ...
        def setBubbleMetadata(self, p0: Any) -> Any: ...
        def createContentView(self) -> RemoteViews: ...
        def setCategory(self, p0: str) -> Any: ...
        @overload
        def addPerson(self, p0: str) -> Any: ...
        @overload
        def addPerson(self, p0: Person) -> Any: ...
        def setColorized(self, p0: bool) -> Any: ...
        def addExtras(self, p0: Bundle) -> Any: ...
        def setBadgeIconType(self, p0: int) -> Any: ...
        def createHeadsUpContentView(self) -> RemoteViews: ...
        def setAllowSystemGeneratedContextualActions(self, p0: bool) -> Any: ...
        def createBigContentView(self) -> RemoteViews: ...
        def setContentInfo(self, p0: str) -> Any: ...
        def setContentText(self, p0: str) -> Any: ...
        def setContentTitle(self, p0: str) -> Any: ...
        def setCustomBigContentView(self, p0: RemoteViews) -> Any: ...
        def setCustomContentView(self, p0: RemoteViews) -> Any: ...
        def setCustomHeadsUpContentView(self, p0: RemoteViews) -> Any: ...
        def setDefaults(self, p0: int) -> Any: ...
        def setFlag(self, p0: int, p1: bool) -> Any: ...
        def setForegroundServiceBehavior(self, p0: int) -> Any: ...
        def setFullScreenIntent(self, p0: PendingIntent, p1: bool) -> Any: ...
        def setGroupAlertBehavior(self, p0: int) -> Any: ...
        def setGroupSummary(self, p0: bool) -> Any: ...
        def setLights(self, p0: int, p1: int, p2: int) -> Any: ...
        def setLocalOnly(self, p0: bool) -> Any: ...
        def setOngoing(self, p0: bool) -> Any: ...
        def setOnlyAlertOnce(self, p0: bool) -> Any: ...
        def setPublicVersion(self, p0: "Notification") -> Any: ...
        def setRemoteInputHistory(self, p0: Any) -> Any: ...
        def setSettingsText(self, p0: str) -> Any: ...
        def setShortCriticalText(self, p0: str) -> Any: ...
        def setShortcutId(self, p0: str) -> Any: ...
        def setShowWhen(self, p0: bool) -> Any: ...
        @overload
        def setSmallIcon(self, p0: int, p1: int) -> Any: ...
        @overload
        def setSmallIcon(self, p0: int) -> Any: ...
        @overload
        def setSmallIcon(self, p0: Icon) -> Any: ...
        def setSortKey(self, p0: str) -> Any: ...
        def setSubText(self, p0: str) -> Any: ...
        @overload
        def setTicker(self, p0: str) -> Any: ...
        @overload
        def setTicker(self, p0: str, p1: RemoteViews) -> Any: ...
        def setTimeoutAfter(self, p0: int) -> Any: ...
        def setUsesChronometer(self, p0: bool) -> Any: ...
        def setVibrate(self, p0: Any) -> Any: ...
        def setWhen(self, p0: int) -> Any: ...
        def setAutoCancel(self, p0: bool) -> Any: ...
        def setProgress(self, p0: int, p1: int, p2: bool) -> Any: ...
        def setChannelId(self, p0: str) -> Any: ...
        def setContentIntent(self, p0: PendingIntent) -> Any: ...
        def setDeleteIntent(self, p0: PendingIntent) -> Any: ...

    class BubbleMetadata:
        CREATOR: ClassVar[Any]
        CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
        PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
        def getShortcutId(self) -> str: ...
        def isBubbleSuppressed(self) -> bool: ...
        def getDesiredHeight(self) -> int: ...
        def getDeleteIntent(self) -> PendingIntent: ...
        def getAutoExpandBubble(self) -> bool: ...
        def getDesiredHeightResId(self) -> int: ...
        def isBubbleSuppressable(self) -> bool: ...
        def isNotificationSuppressed(self) -> bool: ...
        def getIntent(self) -> PendingIntent: ...
        def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
        def describeContents(self) -> int: ...
        def getIcon(self) -> Icon: ...

        class Builder:
            @overload
            def __init__(self, p0: str) -> None: ...
            @overload
            def __init__(self, p0: PendingIntent, p1: Icon) -> None: ...
            @overload
            def __init__(self) -> None: ...
            def setDesiredHeight(self, p0: int) -> Any: ...
            def setAutoExpandBubble(self, p0: bool) -> Any: ...
            def setDesiredHeightResId(self, p0: int) -> Any: ...
            def setSuppressNotification(self, p0: bool) -> Any: ...
            def setSuppressableBubble(self, p0: bool) -> Any: ...
            def setIcon(self, p0: Icon) -> Any: ...
            def setIntent(self, p0: PendingIntent) -> Any: ...
            def build(self) -> Any: ...
            def setDeleteIntent(self, p0: PendingIntent) -> Any: ...

    class BigTextStyle:
        @overload
        def __init__(self) -> None: ...
        @overload
        def __init__(self, p0: Any) -> None: ...
        def bigText(self, p0: str) -> Any: ...
        def setBigContentTitle(self, p0: str) -> Any: ...
        def setSummaryText(self, p0: str) -> Any: ...

    class BigPictureStyle:
        @overload
        def __init__(self) -> None: ...
        @overload
        def __init__(self, p0: Any) -> None: ...
        def setContentDescription(self, p0: str) -> Any: ...
        @overload
        def bigLargeIcon(self, p0: Icon) -> Any: ...
        @overload
        def bigLargeIcon(self, p0: Bitmap) -> Any: ...
        @overload
        def bigPicture(self, p0: Icon) -> Any: ...
        @overload
        def bigPicture(self, p0: Bitmap) -> Any: ...
        def showBigPictureWhenCollapsed(self, p0: bool) -> Any: ...
        def setBigContentTitle(self, p0: str) -> Any: ...
        def setSummaryText(self, p0: str) -> Any: ...

    class Action:
        CREATOR: ClassVar[Any]
        SEMANTIC_ACTION_ARCHIVE: ClassVar[int]
        SEMANTIC_ACTION_CALL: ClassVar[int]
        SEMANTIC_ACTION_DELETE: ClassVar[int]
        SEMANTIC_ACTION_MARK_AS_READ: ClassVar[int]
        SEMANTIC_ACTION_MARK_AS_UNREAD: ClassVar[int]
        SEMANTIC_ACTION_MUTE: ClassVar[int]
        SEMANTIC_ACTION_NONE: ClassVar[int]
        SEMANTIC_ACTION_REPLY: ClassVar[int]
        SEMANTIC_ACTION_THUMBS_DOWN: ClassVar[int]
        SEMANTIC_ACTION_THUMBS_UP: ClassVar[int]
        SEMANTIC_ACTION_UNMUTE: ClassVar[int]
        CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
        PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
        actionIntent: PendingIntent
        icon: int
        title: str
        def __init__(self, p0: int, p1: str, p2: PendingIntent) -> None: ...
        @overload
        def clone(self) -> Any: ...
        @overload
        def clone(self) -> Any: ...
        def getExtras(self) -> Bundle: ...
        def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
        def describeContents(self) -> int: ...
        def getIcon(self) -> Icon: ...
        def getSemanticAction(self) -> int: ...
        def isContextual(self) -> bool: ...
        def getRemoteInputs(self) -> Any: ...
        def getAllowGeneratedReplies(self) -> bool: ...
        def getDataOnlyRemoteInputs(self) -> Any: ...
        def isAuthenticationRequired(self) -> bool: ...

        class WearableExtender:
            @overload
            def __init__(self) -> None: ...
            @overload
            def __init__(self, p0: Any) -> None: ...
            def setInProgressLabel(self, p0: str) -> Any: ...
            def getConfirmLabel(self) -> str: ...
            def setConfirmLabel(self, p0: str) -> Any: ...
            def getInProgressLabel(self) -> str: ...
            def setCancelLabel(self, p0: str) -> Any: ...
            def getCancelLabel(self) -> str: ...
            def isAvailableOffline(self) -> bool: ...
            def getHintDisplayActionInline(self) -> bool: ...
            def getHintLaunchesActivity(self) -> bool: ...
            def setAvailableOffline(self, p0: bool) -> Any: ...
            def setHintDisplayActionInline(self, p0: bool) -> Any: ...
            def setHintLaunchesActivity(self, p0: bool) -> Any: ...
            @overload
            def clone(self) -> Any: ...
            @overload
            def clone(self) -> Any: ...
            def extend(self, p0: Any) -> Any: ...

        class Extender:
            def extend(self, p0: Any) -> Any: ...

        class Builder:
            @overload
            def __init__(self, p0: Any) -> None: ...
            @overload
            def __init__(self, p0: int, p1: str, p2: PendingIntent) -> None: ...
            @overload
            def __init__(self, p0: Icon, p1: str, p2: PendingIntent) -> None: ...
            def addRemoteInput(self, p0: RemoteInput) -> Any: ...
            def setSemanticAction(self, p0: int) -> Any: ...
            def setAllowGeneratedReplies(self, p0: bool) -> Any: ...
            def setAuthenticationRequired(self, p0: bool) -> Any: ...
            def setContextual(self, p0: bool) -> Any: ...
            def extend(self, p0: Any) -> Any: ...
            def getExtras(self) -> Bundle: ...
            def build(self) -> Any: ...
            def addExtras(self, p0: Bundle) -> Any: ...
