from typing import Any, ClassVar, overload
from android.os.IBinder import IBinder
from android.os.Parcel import Parcel

class AppOwnedSdkSandboxInterface:
    CREATOR: ClassVar[Any]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    def __init__(self, p0: str, p1: int, p2: IBinder) -> None: ...
    def getVersion(self) -> int: ...
    def getName(self) -> str: ...
    def getInterface(self) -> IBinder: ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...

from typing import Any, ClassVar, overload
from android.app.Activity import Activity
from android.app.sdksandbox.AppOwnedSdkSandboxInterface import AppOwnedSdkSandboxInterface
from android.os.Bundle import Bundle
from android.os.IBinder import IBinder
from android.os.OutcomeReceiver import OutcomeReceiver
from java.util.concurrent.Executor import Executor

class SdkSandboxManager:
    EXTRA_DISPLAY_ID: ClassVar[str]
    EXTRA_HEIGHT_IN_PIXELS: ClassVar[str]
    EXTRA_HOST_TOKEN: ClassVar[str]
    EXTRA_SURFACE_PACKAGE: ClassVar[str]
    EXTRA_WIDTH_IN_PIXELS: ClassVar[str]
    LOAD_SDK_ALREADY_LOADED: ClassVar[int]
    LOAD_SDK_INTERNAL_ERROR: ClassVar[int]
    LOAD_SDK_NOT_FOUND: ClassVar[int]
    LOAD_SDK_SDK_DEFINED_ERROR: ClassVar[int]
    LOAD_SDK_SDK_SANDBOX_DISABLED: ClassVar[int]
    REQUEST_SURFACE_PACKAGE_INTERNAL_ERROR: ClassVar[int]
    REQUEST_SURFACE_PACKAGE_SDK_NOT_LOADED: ClassVar[int]
    SDK_SANDBOX_PROCESS_NOT_AVAILABLE: ClassVar[int]
    SDK_SANDBOX_SERVICE: ClassVar[str]
    SDK_SANDBOX_STATE_DISABLED: ClassVar[int]
    SDK_SANDBOX_STATE_ENABLED_PROCESS_ISOLATION: ClassVar[int]
    def addSdkSandboxProcessDeathCallback(self, p0: Executor, p1: Any) -> None: ...
    def addSyncedSharedPreferencesKeys(self, p0: set) -> None: ...
    def getAppOwnedSdkSandboxInterfaces(self) -> list: ...
    def getSandboxedSdks(self) -> list: ...
    @staticmethod
    def getSdkSandboxState() -> int: ...
    def getSyncedSharedPreferencesKeys(self) -> set: ...
    def loadSdk(self, p0: str, p1: Bundle, p2: Executor, p3: OutcomeReceiver) -> None: ...
    def registerAppOwnedSdkSandboxInterface(self, p0: AppOwnedSdkSandboxInterface) -> None: ...
    def removeSdkSandboxProcessDeathCallback(self, p0: Any) -> None: ...
    def removeSyncedSharedPreferencesKeys(self, p0: set) -> None: ...
    def startSdkSandboxActivity(self, p0: Activity, p1: IBinder) -> None: ...
    def unloadSdk(self, p0: str) -> None: ...
    def unregisterAppOwnedSdkSandboxInterface(self, p0: str) -> None: ...
    def requestSurfacePackage(self, p0: str, p1: Bundle, p2: Executor, p3: OutcomeReceiver) -> None: ...

    class SdkSandboxProcessDeathCallback:
        def onSdkSandboxDied(self) -> None: ...

from typing import Any, ClassVar, overload
from android.app.sdksandbox.SandboxedSdk import SandboxedSdk
from android.content.Context import Context
from android.os.Bundle import Bundle
from android.view.View import View

class SandboxedSdkProvider:
    def __init__(self) -> None: ...
    def onLoadSdk(self, p0: Bundle) -> SandboxedSdk: ...
    def beforeUnloadSdk(self) -> None: ...
    def attachContext(self, p0: Context) -> None: ...
    def getContext(self) -> Context: ...
    def getView(self, p0: Context, p1: Bundle, p2: int, p3: int) -> View: ...

from typing import Any, ClassVar, overload
from android.os.Bundle import Bundle
from android.os.Parcel import Parcel
from java.lang.Throwable import Throwable

class LoadSdkException:
    CREATOR: ClassVar[Any]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    def __init__(self, p0: Throwable, p1: Bundle) -> None: ...
    def getExtraInformation(self) -> Bundle: ...
    def getLoadSdkErrorCode(self) -> int: ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...

from typing import Any, ClassVar, overload
from android.content.pm.SharedLibraryInfo import SharedLibraryInfo
from android.os.IBinder import IBinder
from android.os.Parcel import Parcel

class SandboxedSdk:
    CREATOR: ClassVar[Any]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    def __init__(self, p0: IBinder) -> None: ...
    def getSharedLibraryInfo(self) -> SharedLibraryInfo: ...
    def getInterface(self) -> IBinder: ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...

from typing import Any, ClassVar, overload
from android.os.Bundle import Bundle
from java.lang.Throwable import Throwable

class RequestSurfacePackageException:
    @overload
    def __init__(self, p0: int, p1: str) -> None: ...
    @overload
    def __init__(self, p0: int, p1: str, p2: Throwable, p3: Bundle) -> None: ...
    @overload
    def __init__(self, p0: int, p1: str, p2: Throwable) -> None: ...
    def getRequestSurfacePackageErrorCode(self) -> int: ...
    def getExtraErrorInformation(self) -> Bundle: ...

