from typing import Any, ClassVar, overload
from java.io.File import File
from java.io.InputStream import InputStream
from java.io.Reader import Reader

class StreamSource:
    FEATURE: ClassVar[str]
    @overload
    def __init__(self, p0: Reader) -> None: ...
    @overload
    def __init__(self, p0: InputStream, p1: str) -> None: ...
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, p0: InputStream) -> None: ...
    @overload
    def __init__(self, p0: File) -> None: ...
    @overload
    def __init__(self, p0: str) -> None: ...
    @overload
    def __init__(self, p0: Reader, p1: str) -> None: ...
    def getSystemId(self) -> str: ...
    def getReader(self) -> Reader: ...
    def getInputStream(self) -> InputStream: ...
    @overload
    def setSystemId(self, p0: str) -> None: ...
    @overload
    def setSystemId(self, p0: File) -> None: ...
    def getPublicId(self) -> str: ...
    def setInputStream(self, p0: InputStream) -> None: ...
    def setReader(self, p0: Reader) -> None: ...
    def setPublicId(self, p0: str) -> None: ...
    def isEmpty(self) -> bool: ...
