from typing import Any, ClassVar, overload
from java.time.LocalTime import LocalTime
from java.time.chrono.ChronoLocalDateTime import ChronoLocalDateTime
from java.time.chrono.ChronoPeriod import ChronoPeriod
from java.time.chrono.Chronology import Chronology
from java.time.chrono.Era import Era
from java.time.format.DateTimeFormatter import DateTimeFormatter
from java.time.temporal.Temporal import Temporal
from java.time.temporal.TemporalAccessor import TemporalAccessor
from java.time.temporal.TemporalAdjuster import TemporalAdjuster
from java.time.temporal.TemporalAmount import TemporalAmount
from java.time.temporal.TemporalField import TemporalField
from java.time.temporal.TemporalQuery import TemporalQuery
from java.time.temporal.TemporalUnit import TemporalUnit
from java.util.Comparator import Comparator

class ChronoLocalDate:
    def equals(self, p0: Any) -> bool: ...
    def toString(self) -> str: ...
    def hashCode(self) -> int: ...
    @overload
    def compareTo(self, p0: Any) -> int: ...
    @overload
    def compareTo(self, p0: "ChronoLocalDate") -> int: ...
    def format(self, p0: DateTimeFormatter) -> str: ...
    @staticmethod
    def from_(p0: TemporalAccessor) -> "ChronoLocalDate": ...
    @overload
    def isSupported(self, p0: TemporalUnit) -> bool: ...
    @overload
    def isSupported(self, p0: TemporalField) -> bool: ...
    @overload
    def with_(self, p0: TemporalField, p1: int) -> Temporal: ...
    @overload
    def with_(self, p0: TemporalAdjuster) -> Temporal: ...
    @overload
    def with_(self, p0: TemporalAdjuster) -> "ChronoLocalDate": ...
    @overload
    def with_(self, p0: TemporalField, p1: int) -> "ChronoLocalDate": ...
    def query(self, p0: TemporalQuery) -> Any: ...
    @overload
    def plus(self, p0: int, p1: TemporalUnit) -> "ChronoLocalDate": ...
    @overload
    def plus(self, p0: TemporalAmount) -> "ChronoLocalDate": ...
    @overload
    def plus(self, p0: TemporalAmount) -> Temporal: ...
    @overload
    def plus(self, p0: int, p1: TemporalUnit) -> Temporal: ...
    @overload
    def until(self, p0: Temporal, p1: TemporalUnit) -> int: ...
    @overload
    def until(self, p0: "ChronoLocalDate") -> ChronoPeriod: ...
    @overload
    def minus(self, p0: int, p1: TemporalUnit) -> Temporal: ...
    @overload
    def minus(self, p0: TemporalAmount) -> Temporal: ...
    @overload
    def minus(self, p0: int, p1: TemporalUnit) -> "ChronoLocalDate": ...
    @overload
    def minus(self, p0: TemporalAmount) -> "ChronoLocalDate": ...
    def getChronology(self) -> Chronology: ...
    def isLeapYear(self) -> bool: ...
    def lengthOfMonth(self) -> int: ...
    def lengthOfYear(self) -> int: ...
    def toEpochDay(self) -> int: ...
    def adjustInto(self, p0: Temporal) -> Temporal: ...
    def atTime(self, p0: LocalTime) -> ChronoLocalDateTime: ...
    def isAfter(self, p0: "ChronoLocalDate") -> bool: ...
    def isBefore(self, p0: "ChronoLocalDate") -> bool: ...
    def getEra(self) -> Era: ...
    @staticmethod
    def timeLineOrder() -> Comparator: ...
    def isEqual(self, p0: "ChronoLocalDate") -> bool: ...
