from typing import Any, ClassVar, overload
from java.time.Clock import Clock
from java.time.Instant import Instant
from java.time.ZoneId import ZoneId
from java.time.chrono.ChronoLocalDate import ChronoLocalDate
from java.time.chrono.ChronoLocalDateTime import ChronoLocalDateTime
from java.time.chrono.ChronoZonedDateTime import ChronoZonedDateTime
from java.time.chrono.Era import Era
from java.time.chrono.HijrahDate import HijrahDate
from java.time.chrono.HijrahEra import HijrahEra
from java.time.format.ResolverStyle import ResolverStyle
from java.time.temporal.ChronoField import ChronoField
from java.time.temporal.TemporalAccessor import TemporalAccessor
from java.time.temporal.ValueRange import ValueRange

class HijrahChronology:
    INSTANCE: ClassVar["HijrahChronology"]
    @overload
    def zonedDateTime(self, p0: TemporalAccessor) -> ChronoZonedDateTime: ...
    @overload
    def zonedDateTime(self, p0: Instant, p1: ZoneId) -> ChronoZonedDateTime: ...
    def isLeapYear(self, p0: int) -> bool: ...
    @overload
    def eraOf(self, p0: int) -> Era: ...
    @overload
    def eraOf(self, p0: int) -> HijrahEra: ...
    def getCalendarType(self) -> str: ...
    @overload
    def date(self, p0: TemporalAccessor) -> HijrahDate: ...
    @overload
    def date(self, p0: Era, p1: int, p2: int, p3: int) -> ChronoLocalDate: ...
    @overload
    def date(self, p0: Era, p1: int, p2: int, p3: int) -> HijrahDate: ...
    @overload
    def date(self, p0: int, p1: int, p2: int) -> HijrahDate: ...
    @overload
    def date(self, p0: int, p1: int, p2: int) -> ChronoLocalDate: ...
    @overload
    def date(self, p0: TemporalAccessor) -> ChronoLocalDate: ...
    def range(self, p0: ChronoField) -> ValueRange: ...
    def localDateTime(self, p0: TemporalAccessor) -> ChronoLocalDateTime: ...
    def prolepticYear(self, p0: Era, p1: int) -> int: ...
    @overload
    def dateYearDay(self, p0: int, p1: int) -> ChronoLocalDate: ...
    @overload
    def dateYearDay(self, p0: int, p1: int) -> HijrahDate: ...
    @overload
    def dateYearDay(self, p0: Era, p1: int, p2: int) -> ChronoLocalDate: ...
    @overload
    def dateYearDay(self, p0: Era, p1: int, p2: int) -> HijrahDate: ...
    @overload
    def dateNow(self, p0: ZoneId) -> ChronoLocalDate: ...
    @overload
    def dateNow(self) -> ChronoLocalDate: ...
    @overload
    def dateNow(self, p0: Clock) -> HijrahDate: ...
    @overload
    def dateNow(self, p0: ZoneId) -> HijrahDate: ...
    @overload
    def dateNow(self) -> HijrahDate: ...
    @overload
    def dateNow(self, p0: Clock) -> ChronoLocalDate: ...
    @overload
    def resolveDate(self, p0: dict, p1: ResolverStyle) -> HijrahDate: ...
    @overload
    def resolveDate(self, p0: dict, p1: ResolverStyle) -> ChronoLocalDate: ...
    @overload
    def dateEpochDay(self, p0: int) -> HijrahDate: ...
    @overload
    def dateEpochDay(self, p0: int) -> ChronoLocalDate: ...
    def eras(self) -> list: ...
    def getId(self) -> str: ...
