from typing import Any, ClassVar, overload
from java.time.format.TextStyle import TextStyle
from java.time.temporal.TemporalField import TemporalField
from java.time.temporal.ValueRange import ValueRange
from java.util.Locale import Locale

class JapaneseEra:
    MEIJI: ClassVar["JapaneseEra"]
    TAISHO: ClassVar["JapaneseEra"]
    SHOWA: ClassVar["JapaneseEra"]
    HEISEI: ClassVar["JapaneseEra"]
    REIWA: ClassVar["JapaneseEra"]
    def toString(self) -> str: ...
    @staticmethod
    def values() -> Any: ...
    @staticmethod
    def valueOf(p0: str) -> "JapaneseEra": ...
    @staticmethod
    def of(p0: int) -> "JapaneseEra": ...
    def getValue(self) -> int: ...
    def range(self, p0: TemporalField) -> ValueRange: ...
    def getDisplayName(self, p0: TextStyle, p1: Locale) -> str: ...
