from typing import Any, ClassVar, overload
from java.lang.Runnable import Runnable
from java.util.concurrent.TimeUnit import TimeUnit

class CyclicBarrier:
    @overload
    def __init__(self, p0: int) -> None: ...
    @overload
    def __init__(self, p0: int, p1: Runnable) -> None: ...
    def getParties(self) -> int: ...
    def isBroken(self) -> bool: ...
    def getNumberWaiting(self) -> int: ...
    def reset(self) -> None: ...
    @overload
    def await_(self, p0: int, p1: TimeUnit) -> int: ...
    @overload
    def await_(self) -> int: ...
