from typing import Any, ClassVar, overload
from java.util.concurrent.ForkJoinPool import ForkJoinPool

class ForkJoinWorkerThread:
    MIN_PRIORITY: ClassVar[int]
    NORM_PRIORITY: ClassVar[int]
    MAX_PRIORITY: ClassVar[int]
    def getPoolIndex(self) -> int: ...
    def run(self) -> None: ...
    def getPool(self) -> ForkJoinPool: ...
    def getQueuedTaskCount(self) -> int: ...
