from typing import Any, ClassVar, overload
from java.lang.Runnable import Runnable
from java.util.concurrent.Callable import Callable
from java.util.concurrent.ForkJoinTask import ForkJoinTask
from java.util.concurrent.ForkJoinWorkerThread import ForkJoinWorkerThread
from java.util.concurrent.Future import Future
from java.util.concurrent.TimeUnit import TimeUnit
from java.util.function.Predicate import Predicate

class ForkJoinPool:
    defaultForkJoinWorkerThreadFactory: ClassVar[Any]
    @overload
    def __init__(self, p0: int) -> None: ...
    @overload
    def __init__(self, p0: int, p1: Any, p2: Any, p3: bool, p4: int, p5: int, p6: int, p7: Predicate, p8: int, p9: TimeUnit) -> None: ...
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, p0: int, p1: Any, p2: Any, p3: bool) -> None: ...
    def getParallelism(self) -> int: ...
    def awaitTermination(self, p0: int, p1: TimeUnit) -> bool: ...
    def shutdownNow(self) -> list: ...
    @staticmethod
    def commonPool() -> "ForkJoinPool": ...
    def setParallelism(self, p0: int) -> int: ...
    @overload
    def invokeAny(self, p0: list, p1: int, p2: TimeUnit) -> Any: ...
    @overload
    def invokeAny(self, p0: list) -> Any: ...
    def getPoolSize(self) -> int: ...
    def getAsyncMode(self) -> bool: ...
    def getRunningThreadCount(self) -> int: ...
    def getActiveThreadCount(self) -> int: ...
    def isQuiescent(self) -> bool: ...
    def getStealCount(self) -> int: ...
    def getQueuedSubmissionCount(self) -> int: ...
    def hasQueuedSubmissions(self) -> bool: ...
    def isTerminating(self) -> bool: ...
    def awaitQuiescence(self, p0: int, p1: TimeUnit) -> bool: ...
    @staticmethod
    def getCommonPoolParallelism() -> int: ...
    @overload
    def submit(self, p0: Callable) -> Future: ...
    @overload
    def submit(self, p0: ForkJoinTask) -> ForkJoinTask: ...
    @overload
    def submit(self, p0: Runnable) -> Future: ...
    @overload
    def submit(self, p0: Runnable, p1: Any) -> Future: ...
    @overload
    def submit(self, p0: Runnable) -> ForkJoinTask: ...
    @overload
    def submit(self, p0: Runnable, p1: Any) -> ForkJoinTask: ...
    @overload
    def submit(self, p0: Callable) -> ForkJoinTask: ...
    def isShutdown(self) -> bool: ...
    @overload
    def invokeAll(self, p0: list) -> list: ...
    @overload
    def invokeAll(self, p0: list, p1: int, p2: TimeUnit) -> list: ...
    @staticmethod
    def managedBlock(p0: Any) -> None: ...
    def invoke(self, p0: ForkJoinTask) -> Any: ...
    def shutdown(self) -> None: ...
    def toString(self) -> str: ...
    def getFactory(self) -> Any: ...
    @overload
    def execute(self, p0: Runnable) -> None: ...
    @overload
    def execute(self, p0: ForkJoinTask) -> None: ...
    def isTerminated(self) -> bool: ...
    def getUncaughtExceptionHandler(self) -> Any: ...
    def lazySubmit(self, p0: ForkJoinTask) -> ForkJoinTask: ...
    def externalSubmit(self, p0: ForkJoinTask) -> ForkJoinTask: ...
    def getQueuedTaskCount(self) -> int: ...
    def close(self) -> None: ...

    class ForkJoinWorkerThreadFactory:
        def newThread(self, p0: "ForkJoinPool") -> ForkJoinWorkerThread: ...

    class ManagedBlocker:
        def isReleasable(self) -> bool: ...
        def block(self) -> bool: ...
