from typing import Any, ClassVar, overload
from java.lang.Runnable import Runnable
from java.lang.Throwable import Throwable
from java.util.concurrent.Callable import Callable
from java.util.concurrent.TimeUnit import TimeUnit

class FutureTask:
    @overload
    def __init__(self, p0: Callable) -> None: ...
    @overload
    def __init__(self, p0: Runnable, p1: Any) -> None: ...
    def isCancelled(self) -> bool: ...
    def resultNow(self) -> Any: ...
    def exceptionNow(self) -> Throwable: ...
    def run(self) -> None: ...
    @overload
    def get(self) -> Any: ...
    @overload
    def get(self, p0: int, p1: TimeUnit) -> Any: ...
    def toString(self) -> str: ...
    def state(self) -> Any: ...
    def isDone(self) -> bool: ...
    def cancel(self, p0: bool) -> bool: ...
