from typing import Any, ClassVar, overload
from java.util.concurrent.TimeUnit import TimeUnit

class Phaser:
    @overload
    def __init__(self, p0: "Phaser", p1: int) -> None: ...
    @overload
    def __init__(self, p0: "Phaser") -> None: ...
    @overload
    def __init__(self, p0: int) -> None: ...
    @overload
    def __init__(self) -> None: ...
    def getPhase(self) -> int: ...
    def arriveAndAwaitAdvance(self) -> int: ...
    def bulkRegister(self, p0: int) -> int: ...
    def arrive(self) -> int: ...
    def arriveAndDeregister(self) -> int: ...
    def awaitAdvance(self, p0: int) -> int: ...
    @overload
    def awaitAdvanceInterruptibly(self, p0: int) -> int: ...
    @overload
    def awaitAdvanceInterruptibly(self, p0: int, p1: int, p2: TimeUnit) -> int: ...
    def forceTermination(self) -> None: ...
    def getRegisteredParties(self) -> int: ...
    def getArrivedParties(self) -> int: ...
    def getUnarrivedParties(self) -> int: ...
    def toString(self) -> str: ...
    def register(self) -> int: ...
    def getParent(self) -> "Phaser": ...
    def isTerminated(self) -> bool: ...
    def getRoot(self) -> "Phaser": ...
