from typing import Any, ClassVar, overload
from java.lang.Runnable import Runnable
from java.util.concurrent.BlockingQueue import BlockingQueue
from java.util.concurrent.RejectedExecutionHandler import RejectedExecutionHandler
from java.util.concurrent.ThreadFactory import ThreadFactory
from java.util.concurrent.TimeUnit import TimeUnit

class ThreadPoolExecutor:
    @overload
    def __init__(self, p0: int, p1: int, p2: int, p3: TimeUnit, p4: BlockingQueue, p5: ThreadFactory, p6: RejectedExecutionHandler) -> None: ...
    @overload
    def __init__(self, p0: int, p1: int, p2: int, p3: TimeUnit, p4: BlockingQueue) -> None: ...
    @overload
    def __init__(self, p0: int, p1: int, p2: int, p3: TimeUnit, p4: BlockingQueue, p5: ThreadFactory) -> None: ...
    @overload
    def __init__(self, p0: int, p1: int, p2: int, p3: TimeUnit, p4: BlockingQueue, p5: RejectedExecutionHandler) -> None: ...
    def awaitTermination(self, p0: int, p1: TimeUnit) -> bool: ...
    def shutdownNow(self) -> list: ...
    def getPoolSize(self) -> int: ...
    def isTerminating(self) -> bool: ...
    def isShutdown(self) -> bool: ...
    def getRejectedExecutionHandler(self) -> RejectedExecutionHandler: ...
    def setCorePoolSize(self, p0: int) -> None: ...
    def getCorePoolSize(self) -> int: ...
    def prestartCoreThread(self) -> bool: ...
    def prestartAllCoreThreads(self) -> int: ...
    def setMaximumPoolSize(self, p0: int) -> None: ...
    def getMaximumPoolSize(self) -> int: ...
    def setKeepAliveTime(self, p0: int, p1: TimeUnit) -> None: ...
    def getKeepAliveTime(self, p0: TimeUnit) -> int: ...
    def purge(self) -> None: ...
    def getActiveCount(self) -> int: ...
    def getLargestPoolSize(self) -> int: ...
    def getTaskCount(self) -> int: ...
    def getCompletedTaskCount(self) -> int: ...
    def allowCoreThreadTimeOut(self, p0: bool) -> None: ...
    def allowsCoreThreadTimeOut(self) -> bool: ...
    def setThreadFactory(self, p0: ThreadFactory) -> None: ...
    def getThreadFactory(self) -> ThreadFactory: ...
    def setRejectedExecutionHandler(self, p0: RejectedExecutionHandler) -> None: ...
    def remove(self, p0: Runnable) -> bool: ...
    def shutdown(self) -> None: ...
    def toString(self) -> str: ...
    def execute(self, p0: Runnable) -> None: ...
    def getQueue(self) -> BlockingQueue: ...
    def isTerminated(self) -> bool: ...

    class AbortPolicy:
        def __init__(self) -> None: ...
        def rejectedExecution(self, p0: Runnable, p1: "ThreadPoolExecutor") -> None: ...

    class DiscardOldestPolicy:
        def __init__(self) -> None: ...
        def rejectedExecution(self, p0: Runnable, p1: "ThreadPoolExecutor") -> None: ...

    class DiscardPolicy:
        def __init__(self) -> None: ...
        def rejectedExecution(self, p0: Runnable, p1: "ThreadPoolExecutor") -> None: ...

    class CallerRunsPolicy:
        def __init__(self) -> None: ...
        def rejectedExecution(self, p0: Runnable, p1: "ThreadPoolExecutor") -> None: ...
