from typing import Any, ClassVar, overload
from android.se.omapi.Session import Session

class Channel:
    def isBasicChannel(self) -> bool: ...
    def getSession(self) -> Session: ...
    def getSelectResponse(self) -> Any: ...
    def selectNext(self) -> bool: ...
    def transmit(self, p0: Any) -> Any: ...
    def isOpen(self) -> bool: ...
    def close(self) -> None: ...
