from typing import Any, ClassVar, overload
from java.util.function.BinaryOperator import BinaryOperator
from java.util.function.UnaryOperator import UnaryOperator

class AtomicReferenceFieldUpdater:
    @staticmethod
    def newUpdater(p0: type, p1: type, p2: str) -> "AtomicReferenceFieldUpdater": ...
    def get(self, p0: Any) -> Any: ...
    def set(self, p0: Any, p1: Any) -> None: ...
    def compareAndSet(self, p0: Any, p1: Any, p2: Any) -> bool: ...
    def weakCompareAndSet(self, p0: Any, p1: Any, p2: Any) -> bool: ...
    def getAndSet(self, p0: Any, p1: Any) -> Any: ...
    def lazySet(self, p0: Any, p1: Any) -> None: ...
    def getAndUpdate(self, p0: Any, p1: UnaryOperator) -> Any: ...
    def updateAndGet(self, p0: Any, p1: UnaryOperator) -> Any: ...
    def getAndAccumulate(self, p0: Any, p1: Any, p2: BinaryOperator) -> Any: ...
    def accumulateAndGet(self, p0: Any, p1: Any, p2: BinaryOperator) -> Any: ...
