from typing import Any, ClassVar, overload

class DoubleAdder:
    def __init__(self) -> None: ...
    def reset(self) -> None: ...
    def toString(self) -> str: ...
    def intValue(self) -> int: ...
    def longValue(self) -> int: ...
    def floatValue(self) -> float: ...
    def doubleValue(self) -> float: ...
    def add(self, p0: float) -> None: ...
    def sum(self) -> float: ...
    def sumThenReset(self) -> float: ...
