from typing import Any, ClassVar, overload
from android.hardware.camera2.CameraDevice import CameraDevice
from android.hardware.camera2.CaptureRequest import CaptureRequest
from android.hardware.camera2.TotalCaptureResult import TotalCaptureResult
from java.util.concurrent.Executor import Executor

class CameraExtensionSession:
    def capture(self, p0: CaptureRequest, p1: Executor, p2: Any) -> int: ...
    def setRepeatingRequest(self, p0: CaptureRequest, p1: Executor, p2: Any) -> int: ...
    def stopRepeating(self) -> None: ...
    def getRealtimeStillCaptureLatency(self) -> Any: ...
    def close(self) -> None: ...
    def getDevice(self) -> CameraDevice: ...

    class StillCaptureLatency:
        def __init__(self, p0: int, p1: int) -> None: ...
        def equals(self, p0: Any) -> bool: ...
        def toString(self) -> str: ...
        def hashCode(self) -> int: ...
        def getCaptureLatency(self) -> int: ...
        def getProcessingLatency(self) -> int: ...

    class StateCallback:
        def __init__(self) -> None: ...
        def onConfigureFailed(self, p0: "CameraExtensionSession") -> None: ...
        def onClosed(self, p0: "CameraExtensionSession") -> None: ...
        def onConfigured(self, p0: "CameraExtensionSession") -> None: ...

    class ExtensionCaptureCallback:
        def __init__(self) -> None: ...
        def onCaptureStarted(self, p0: "CameraExtensionSession", p1: CaptureRequest, p2: int) -> None: ...
        def onCaptureProcessStarted(self, p0: "CameraExtensionSession", p1: CaptureRequest) -> None: ...
        @overload
        def onCaptureFailed(self, p0: "CameraExtensionSession", p1: CaptureRequest) -> None: ...
        @overload
        def onCaptureFailed(self, p0: "CameraExtensionSession", p1: CaptureRequest, p2: int) -> None: ...
        def onCaptureSequenceCompleted(self, p0: "CameraExtensionSession", p1: int) -> None: ...
        def onCaptureSequenceAborted(self, p0: "CameraExtensionSession", p1: int) -> None: ...
        def onCaptureResultAvailable(self, p0: "CameraExtensionSession", p1: CaptureRequest, p2: TotalCaptureResult) -> None: ...
        def onCaptureProcessProgressed(self, p0: "CameraExtensionSession", p1: CaptureRequest, p2: int) -> None: ...
