from typing import Any, ClassVar, overload
from android.hardware.camera2.params.MultiResolutionStreamInfo import MultiResolutionStreamInfo
from android.media.ImageReader import ImageReader
from android.view.Surface import Surface
from java.util.concurrent.Executor import Executor

class MultiResolutionImageReader:
    @overload
    def __init__(self, p0: list, p1: int, p2: int) -> None: ...
    @overload
    def __init__(self, p0: list, p1: int, p2: int, p3: int) -> None: ...
    def getStreamInfoForImageReader(self, p0: ImageReader) -> MultiResolutionStreamInfo: ...
    def setOnImageAvailableListener(self, p0: Any, p1: Executor) -> None: ...
    def getSurface(self) -> Surface: ...
    def flush(self) -> None: ...
    def close(self) -> None: ...
