from typing import Any, ClassVar, overload
from android.graphics.Point import Point
from android.graphics.Rect import Rect

class Face:
    ID_UNSUPPORTED: ClassVar[int]
    SCORE_MAX: ClassVar[int]
    SCORE_MIN: ClassVar[int]
    def getLeftEyePosition(self) -> Point: ...
    def getMouthPosition(self) -> Point: ...
    def getRightEyePosition(self) -> Point: ...
    def toString(self) -> str: ...
    def getBounds(self) -> Rect: ...
    def getId(self) -> int: ...
    def getScore(self) -> int: ...

    class Builder:
        @overload
        def __init__(self) -> None: ...
        @overload
        def __init__(self, p0: "Face") -> None: ...
        def build(self) -> "Face": ...
        def setLeftEyePosition(self, p0: Point) -> Any: ...
        def setMouthPosition(self, p0: Point) -> Any: ...
        def setRightEyePosition(self, p0: Point) -> Any: ...
        def setScore(self, p0: int) -> Any: ...
        def setId(self, p0: int) -> Any: ...
        def setBounds(self, p0: Rect) -> Any: ...

from typing import Any, ClassVar, overload

class DeviceStateSensorOrientationMap:
    FOLDED: ClassVar[int]
    NORMAL: ClassVar[int]
    def equals(self, p0: Any) -> bool: ...
    def hashCode(self) -> int: ...
    def getSensorOrientation(self, p0: int) -> int: ...

    class Builder:
        def __init__(self) -> None: ...
        def build(self) -> "DeviceStateSensorOrientationMap": ...
        def addOrientationForState(self, p0: int, p1: int) -> Any: ...

from typing import Any, ClassVar, overload

class OisSample:
    def __init__(self, p0: int, p1: float, p2: float) -> None: ...
    def equals(self, p0: Any) -> bool: ...
    def toString(self) -> str: ...
    def hashCode(self) -> int: ...
    def getXshift(self) -> float: ...
    def getYshift(self) -> float: ...
    def getTimestamp(self) -> int: ...

from typing import Any, ClassVar, overload
from android.graphics.ColorSpace import ColorSpace
from android.hardware.camera2.CaptureRequest import CaptureRequest
from android.hardware.camera2.params.InputConfiguration import InputConfiguration
from android.os.Parcel import Parcel
from java.util.concurrent.Executor import Executor

class SessionConfiguration:
    CREATOR: ClassVar[Any]
    SESSION_HIGH_SPEED: ClassVar[int]
    SESSION_REGULAR: ClassVar[int]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    @overload
    def __init__(self, p0: int, p1: list) -> None: ...
    @overload
    def __init__(self, p0: int, p1: list, p2: Executor, p3: Any) -> None: ...
    def equals(self, p0: Any) -> bool: ...
    def hashCode(self) -> int: ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
    def getColorSpace(self) -> ColorSpace: ...
    def setColorSpace(self, p0: Any) -> None: ...
    def getOutputConfigurations(self) -> list: ...
    def clearColorSpace(self) -> None: ...
    def getExecutor(self) -> Executor: ...
    def getInputConfiguration(self) -> InputConfiguration: ...
    def getSessionParameters(self) -> CaptureRequest: ...
    def getSessionType(self) -> int: ...
    def getStateCallback(self) -> Any: ...
    def setInputConfiguration(self, p0: InputConfiguration) -> None: ...
    def setSessionParameters(self, p0: CaptureRequest) -> None: ...
    def setStateCallback(self, p0: Executor, p1: Any) -> None: ...

from typing import Any, ClassVar, overload
from android.util.Range import Range
from android.util.Size import Size
from android.view.Surface import Surface

class RecommendedStreamConfigurationMap:
    USECASE_10BIT_OUTPUT: ClassVar[int]
    USECASE_LOW_LATENCY_SNAPSHOT: ClassVar[int]
    USECASE_PREVIEW: ClassVar[int]
    USECASE_RAW: ClassVar[int]
    USECASE_RECORD: ClassVar[int]
    USECASE_SNAPSHOT: ClassVar[int]
    USECASE_VIDEO_SNAPSHOT: ClassVar[int]
    USECASE_ZSL: ClassVar[int]
    def getHighResolutionOutputSizes(self, p0: int) -> set: ...
    def getHighSpeedVideoFpsRanges(self) -> set: ...
    def getHighSpeedVideoFpsRangesFor(self, p0: Size) -> set: ...
    def getHighSpeedVideoSizes(self) -> set: ...
    def getHighSpeedVideoSizesFor(self, p0: Range) -> set: ...
    def getInputFormats(self) -> set: ...
    def getInputSizes(self, p0: int) -> set: ...
    def getOutputFormats(self) -> set: ...
    @overload
    def getOutputMinFrameDuration(self, p0: type, p1: Size) -> int: ...
    @overload
    def getOutputMinFrameDuration(self, p0: int, p1: Size) -> int: ...
    @overload
    def getOutputSizes(self, p0: type) -> set: ...
    @overload
    def getOutputSizes(self, p0: int) -> set: ...
    @overload
    def getOutputStallDuration(self, p0: type, p1: Size) -> int: ...
    @overload
    def getOutputStallDuration(self, p0: int, p1: Size) -> int: ...
    def getRecommendedUseCase(self) -> int: ...
    def getValidOutputFormatsForInput(self, p0: int) -> set: ...
    @overload
    def isOutputSupportedFor(self, p0: Surface) -> bool: ...
    @overload
    def isOutputSupportedFor(self, p0: int) -> bool: ...

from typing import Any, ClassVar, overload

class ColorSpaceProfiles:
    UNSPECIFIED: ClassVar[int]
    def __init__(self, p0: Any) -> None: ...
    def getSupportedColorSpacesForDynamicRange(self, p0: int, p1: int) -> set: ...
    def getSupportedDynamicRangeProfiles(self, p0: Any, p1: int) -> set: ...
    def getSupportedColorSpaces(self, p0: int) -> set: ...
    def getSupportedImageFormatsForColorSpace(self, p0: Any) -> set: ...

from typing import Any, ClassVar, overload
from android.util.Range import Range
from android.util.Size import Size

class Capability:
    def __init__(self, p0: int, p1: Size, p2: Range) -> None: ...
    def getMaxStreamingSize(self) -> Size: ...
    def getZoomRatioRange(self) -> Range: ...
    def equals(self, p0: Any) -> bool: ...
    def toString(self) -> str: ...
    def hashCode(self) -> int: ...
    def getMode(self) -> int: ...

from typing import Any, ClassVar, overload

class LensIntrinsicsSample:
    def __init__(self, p0: int, p1: Any) -> None: ...
    def getLensIntrinsics(self) -> Any: ...
    def getTimestampNanos(self) -> int: ...
    def equals(self, p0: Any) -> bool: ...
    def toString(self) -> str: ...
    def hashCode(self) -> int: ...

from typing import Any, ClassVar, overload
from android.graphics.PointF import PointF

class TonemapCurve:
    CHANNEL_BLUE: ClassVar[int]
    CHANNEL_GREEN: ClassVar[int]
    CHANNEL_RED: ClassVar[int]
    LEVEL_BLACK: ClassVar[float]
    LEVEL_WHITE: ClassVar[float]
    POINT_SIZE: ClassVar[int]
    def __init__(self, p0: Any, p1: Any, p2: Any) -> None: ...
    def copyColorCurve(self, p0: int, p1: Any, p2: int) -> None: ...
    def getPoint(self, p0: int, p1: int) -> PointF: ...
    def getPointCount(self, p0: int) -> int: ...
    def equals(self, p0: Any) -> bool: ...
    def toString(self) -> str: ...
    def hashCode(self) -> int: ...

from typing import Any, ClassVar, overload

class DynamicRangeProfiles:
    DOLBY_VISION_10B_HDR_OEM: ClassVar[int]
    DOLBY_VISION_10B_HDR_OEM_PO: ClassVar[int]
    DOLBY_VISION_10B_HDR_REF: ClassVar[int]
    DOLBY_VISION_10B_HDR_REF_PO: ClassVar[int]
    DOLBY_VISION_8B_HDR_OEM: ClassVar[int]
    DOLBY_VISION_8B_HDR_OEM_PO: ClassVar[int]
    DOLBY_VISION_8B_HDR_REF: ClassVar[int]
    DOLBY_VISION_8B_HDR_REF_PO: ClassVar[int]
    HDR10: ClassVar[int]
    HDR10_PLUS: ClassVar[int]
    HLG10: ClassVar[int]
    PUBLIC_MAX: ClassVar[int]
    STANDARD: ClassVar[int]
    def __init__(self, p0: Any) -> None: ...
    def getProfileCaptureRequestConstraints(self, p0: int) -> set: ...
    def getSupportedProfiles(self) -> set: ...
    def isExtraLatencyPresent(self, p0: int) -> bool: ...

from typing import Any, ClassVar, overload

class MultiResolutionStreamInfo:
    def __init__(self, p0: int, p1: int, p2: str) -> None: ...
    def equals(self, p0: Any) -> bool: ...
    def hashCode(self) -> int: ...
    def getPhysicalCameraId(self) -> str: ...
    def getHeight(self) -> int: ...
    def getWidth(self) -> int: ...

from typing import Any, ClassVar, overload

class MultiResolutionStreamConfigurationMap:
    def getOutputInfo(self, p0: int) -> list: ...
    def getInputInfo(self, p0: int) -> list: ...
    def equals(self, p0: Any) -> bool: ...
    def toString(self) -> str: ...
    def hashCode(self) -> int: ...
    def getInputFormats(self) -> Any: ...
    def getOutputFormats(self) -> Any: ...

from typing import Any, ClassVar, overload

class BlackLevelPattern:
    COUNT: ClassVar[int]
    def __init__(self, p0: Any) -> None: ...
    def copyTo(self, p0: Any, p1: int) -> None: ...
    def getOffsetForIndex(self, p0: int, p1: int) -> int: ...
    def equals(self, p0: Any) -> bool: ...
    def toString(self) -> str: ...
    def hashCode(self) -> int: ...

from typing import Any, ClassVar, overload
from android.graphics.Point import Point
from android.graphics.Rect import Rect
from android.util.Size import Size

class MeteringRectangle:
    METERING_WEIGHT_DONT_CARE: ClassVar[int]
    METERING_WEIGHT_MAX: ClassVar[int]
    METERING_WEIGHT_MIN: ClassVar[int]
    @overload
    def __init__(self, p0: Point, p1: Size, p2: int) -> None: ...
    @overload
    def __init__(self, p0: int, p1: int, p2: int, p3: int, p4: int) -> None: ...
    @overload
    def __init__(self, p0: Rect, p1: int) -> None: ...
    def getMeteringWeight(self) -> int: ...
    def getUpperLeftPoint(self) -> Point: ...
    @overload
    def equals(self, p0: Any) -> bool: ...
    @overload
    def equals(self, p0: "MeteringRectangle") -> bool: ...
    def toString(self) -> str: ...
    def hashCode(self) -> int: ...
    def getX(self) -> int: ...
    def getY(self) -> int: ...
    def getHeight(self) -> int: ...
    def getWidth(self) -> int: ...
    def getRect(self) -> Rect: ...
    def getSize(self) -> Size: ...

from typing import Any, ClassVar, overload
from android.hardware.camera2.params.RggbChannelVector import RggbChannelVector

class LensShadingMap:
    MINIMUM_GAIN_FACTOR: ClassVar[float]
    def getGainFactor(self, p0: int, p1: int, p2: int) -> float: ...
    def copyGainFactors(self, p0: Any, p1: int) -> None: ...
    def getGainFactorCount(self) -> int: ...
    def getGainFactorVector(self, p0: int, p1: int) -> RggbChannelVector: ...
    def equals(self, p0: Any) -> bool: ...
    def toString(self) -> str: ...
    def hashCode(self) -> int: ...
    def getColumnCount(self) -> int: ...
    def getRowCount(self) -> int: ...

from typing import Any, ClassVar, overload
from android.util.Rational import Rational

class ColorSpaceTransform:
    @overload
    def __init__(self, p0: Any) -> None: ...
    @overload
    def __init__(self, p0: Any) -> None: ...
    def getElement(self, p0: int, p1: int) -> Rational: ...
    def equals(self, p0: Any) -> bool: ...
    def toString(self) -> str: ...
    def hashCode(self) -> int: ...
    @overload
    def copyElements(self, p0: Any, p1: int) -> None: ...
    @overload
    def copyElements(self, p0: Any, p1: int) -> None: ...

from typing import Any, ClassVar, overload
from android.graphics.ColorSpace import ColorSpace
from android.hardware.camera2.params.OutputConfiguration import OutputConfiguration
from java.util.concurrent.Executor import Executor

class ExtensionSessionConfiguration:
    def __init__(self, p0: int, p1: list, p2: Executor, p3: Any) -> None: ...
    def getPostviewOutputConfiguration(self) -> OutputConfiguration: ...
    def setPostviewOutputConfiguration(self, p0: OutputConfiguration) -> None: ...
    def getExtension(self) -> int: ...
    def getColorSpace(self) -> ColorSpace: ...
    def setColorSpace(self, p0: Any) -> None: ...
    def getOutputConfigurations(self) -> list: ...
    def clearColorSpace(self) -> None: ...
    def getExecutor(self) -> Executor: ...
    def getStateCallback(self) -> Any: ...

from typing import Any, ClassVar, overload

class RggbChannelVector:
    BLUE: ClassVar[int]
    COUNT: ClassVar[int]
    GREEN_EVEN: ClassVar[int]
    GREEN_ODD: ClassVar[int]
    RED: ClassVar[int]
    def __init__(self, p0: float, p1: float, p2: float, p3: float) -> None: ...
    def copyTo(self, p0: Any, p1: int) -> None: ...
    def getRed(self) -> float: ...
    def getBlue(self) -> float: ...
    def getGreenEven(self) -> float: ...
    def getGreenOdd(self) -> float: ...
    def equals(self, p0: Any) -> bool: ...
    def toString(self) -> str: ...
    def hashCode(self) -> int: ...
    def getComponent(self, p0: int) -> float: ...

from typing import Any, ClassVar, overload
from android.util.Range import Range
from android.util.Size import Size
from android.view.Surface import Surface

class StreamConfigurationMap:
    def equals(self, p0: Any) -> bool: ...
    def toString(self) -> str: ...
    def hashCode(self) -> int: ...
    def getHighResolutionOutputSizes(self, p0: int) -> Any: ...
    def getHighSpeedVideoFpsRanges(self) -> Any: ...
    def getHighSpeedVideoFpsRangesFor(self, p0: Size) -> Any: ...
    def getHighSpeedVideoSizes(self) -> Any: ...
    def getHighSpeedVideoSizesFor(self, p0: Range) -> Any: ...
    def getInputFormats(self) -> Any: ...
    def getInputSizes(self, p0: int) -> Any: ...
    def getOutputFormats(self) -> Any: ...
    @overload
    def getOutputMinFrameDuration(self, p0: type, p1: Size) -> int: ...
    @overload
    def getOutputMinFrameDuration(self, p0: int, p1: Size) -> int: ...
    @overload
    def getOutputSizes(self, p0: int) -> Any: ...
    @overload
    def getOutputSizes(self, p0: type) -> Any: ...
    @overload
    def getOutputStallDuration(self, p0: int, p1: Size) -> int: ...
    @overload
    def getOutputStallDuration(self, p0: type, p1: Size) -> int: ...
    def getValidOutputFormatsForInput(self, p0: int) -> Any: ...
    @overload
    def isOutputSupportedFor(self, p0: Surface) -> bool: ...
    @overload
    @staticmethod
    def isOutputSupportedFor(p0: type) -> bool: ...
    @overload
    def isOutputSupportedFor(self, p0: int) -> bool: ...

from typing import Any, ClassVar, overload

class MandatoryStreamCombination:
    def getStreamsInformation(self) -> list: ...
    def isReprocessable(self) -> bool: ...
    def equals(self, p0: Any) -> bool: ...
    def hashCode(self) -> int: ...
    def getDescription(self) -> str: ...

    class MandatoryStreamInformation:
        def getStreamUseCase(self) -> int: ...
        def get10BitFormat(self) -> int: ...
        def is10BitCapable(self) -> bool: ...
        def isInput(self) -> bool: ...
        def isMaximumSize(self) -> bool: ...
        def isUltraHighResolution(self) -> bool: ...
        def getAvailableSizes(self) -> list: ...
        def equals(self, p0: Any) -> bool: ...
        def hashCode(self) -> int: ...
        def getFormat(self) -> int: ...

from typing import Any, ClassVar, overload

class InputConfiguration:
    @overload
    def __init__(self, p0: int, p1: int, p2: int) -> None: ...
    @overload
    def __init__(self, p0: list, p1: int) -> None: ...
    def equals(self, p0: Any) -> bool: ...
    def toString(self) -> str: ...
    def hashCode(self) -> int: ...
    def getHeight(self) -> int: ...
    def getWidth(self) -> int: ...
    def isMultiResolution(self) -> bool: ...
    def getFormat(self) -> int: ...

from typing import Any, ClassVar, overload
from android.hardware.camera2.MultiResolutionImageReader import MultiResolutionImageReader
from android.os.Parcel import Parcel
from android.util.Size import Size
from android.view.Surface import Surface

class OutputConfiguration:
    CREATOR: ClassVar[Any]
    MIRROR_MODE_AUTO: ClassVar[int]
    MIRROR_MODE_H: ClassVar[int]
    MIRROR_MODE_NONE: ClassVar[int]
    MIRROR_MODE_V: ClassVar[int]
    SURFACE_GROUP_ID_NONE: ClassVar[int]
    TIMESTAMP_BASE_CHOREOGRAPHER_SYNCED: ClassVar[int]
    TIMESTAMP_BASE_DEFAULT: ClassVar[int]
    TIMESTAMP_BASE_MONOTONIC: ClassVar[int]
    TIMESTAMP_BASE_REALTIME: ClassVar[int]
    TIMESTAMP_BASE_SENSOR: ClassVar[int]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    @overload
    def __init__(self, p0: int, p1: Size) -> None: ...
    @overload
    def __init__(self, p0: int, p1: int, p2: Size, p3: int) -> None: ...
    @overload
    def __init__(self, p0: int, p1: int, p2: Size) -> None: ...
    @overload
    def __init__(self, p0: int, p1: Size, p2: int) -> None: ...
    @overload
    def __init__(self, p0: Surface) -> None: ...
    @overload
    def __init__(self, p0: Size, p1: type) -> None: ...
    @overload
    def __init__(self, p0: int, p1: Surface) -> None: ...
    def addSensorPixelModeUsed(self, p0: int) -> None: ...
    def addSurface(self, p0: Surface) -> None: ...
    @overload
    @staticmethod
    def createInstancesForMultiResolutionOutput(p0: list, p1: int) -> list: ...
    @overload
    @staticmethod
    def createInstancesForMultiResolutionOutput(p0: MultiResolutionImageReader) -> list: ...
    def enableSurfaceSharing(self) -> None: ...
    def getDynamicRangeProfile(self) -> int: ...
    def getMaxSharedSurfaceCount(self) -> int: ...
    @overload
    def getMirrorMode(self, p0: Surface) -> int: ...
    @overload
    def getMirrorMode(self) -> int: ...
    def getStreamUseCase(self) -> int: ...
    def getSurfaceGroupId(self) -> int: ...
    def getSurfaces(self) -> list: ...
    def getTimestampBase(self) -> int: ...
    def isReadoutTimestampEnabled(self) -> bool: ...
    def removeSensorPixelModeUsed(self, p0: int) -> None: ...
    def removeSurface(self, p0: Surface) -> None: ...
    def setDynamicRangeProfile(self, p0: int) -> None: ...
    @overload
    def setMirrorMode(self, p0: int) -> None: ...
    @overload
    def setMirrorMode(self, p0: Surface, p1: int) -> None: ...
    def setPhysicalCameraId(self, p0: str) -> None: ...
    def setReadoutTimestampEnabled(self, p0: bool) -> None: ...
    def setStreamUseCase(self, p0: int) -> None: ...
    @staticmethod
    def setSurfacesForMultiResolutionOutput(p0: list, p1: MultiResolutionImageReader) -> None: ...
    def setTimestampBase(self, p0: int) -> None: ...
    def getSurface(self) -> Surface: ...
    def equals(self, p0: Any) -> bool: ...
    def hashCode(self) -> int: ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...

