from typing import Any, ClassVar, overload
from org.xml.sax.Attributes import Attributes

class Attributes2Impl:
    @overload
    def __init__(self, p0: Attributes) -> None: ...
    @overload
    def __init__(self) -> None: ...
    def removeAttribute(self, p0: int) -> None: ...
    def setAttributes(self, p0: Attributes) -> None: ...
    @overload
    def isDeclared(self, p0: str, p1: str) -> bool: ...
    @overload
    def isDeclared(self, p0: str) -> bool: ...
    @overload
    def isDeclared(self, p0: int) -> bool: ...
    def setDeclared(self, p0: int, p1: bool) -> None: ...
    def setSpecified(self, p0: int, p1: bool) -> None: ...
    def addAttribute(self, p0: str, p1: str, p2: str, p3: str, p4: str) -> None: ...
    @overload
    def isSpecified(self, p0: int) -> bool: ...
    @overload
    def isSpecified(self, p0: str, p1: str) -> bool: ...
    @overload
    def isSpecified(self, p0: str) -> bool: ...
