from typing import Any, ClassVar, overload
from android.os.Parcel import Parcel

class AlignmentSpan:
    def getAlignment(self) -> Any: ...

    class Standard:
        CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
        PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
        @overload
        def __init__(self, p0: Any) -> None: ...
        @overload
        def __init__(self, p0: Parcel) -> None: ...
        def describeContents(self) -> int: ...
        def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
        def getAlignment(self) -> Any: ...
        def getSpanTypeId(self) -> int: ...
        def toString(self) -> str: ...
