from typing import Any, ClassVar, overload
from android.graphics.Bitmap import Bitmap
from android.graphics.Canvas import Canvas
from android.graphics.Paint import Paint
from android.text.Layout import Layout

class IconMarginSpan:
    @overload
    def __init__(self, p0: Bitmap, p1: int) -> None: ...
    @overload
    def __init__(self, p0: Bitmap) -> None: ...
    def chooseHeight(self, p0: str, p1: int, p2: int, p3: int, p4: int, p5: Any) -> None: ...
    def getBitmap(self) -> Bitmap: ...
    def getLeadingMargin(self, p0: bool) -> int: ...
    def drawLeadingMargin(self, p0: Canvas, p1: Paint, p2: int, p3: int, p4: int, p5: int, p6: int, p7: str, p8: int, p9: int, p10: bool, p11: Layout) -> None: ...
    def getPadding(self) -> int: ...
    def toString(self) -> str: ...
