from typing import Any, ClassVar, overload
from android.content.Context import Context
from android.graphics.Bitmap import Bitmap
from android.graphics.drawable.Drawable import Drawable
from android.net.Uri import Uri

class ImageSpan:
    ALIGN_BASELINE: ClassVar[int]
    ALIGN_BOTTOM: ClassVar[int]
    ALIGN_CENTER: ClassVar[int]
    @overload
    def __init__(self, p0: Context, p1: Uri) -> None: ...
    @overload
    def __init__(self, p0: Context, p1: Uri, p2: int) -> None: ...
    @overload
    def __init__(self, p0: Drawable, p1: str, p2: int) -> None: ...
    @overload
    def __init__(self, p0: Context, p1: int) -> None: ...
    @overload
    def __init__(self, p0: Context, p1: int, p2: int) -> None: ...
    @overload
    def __init__(self, p0: Context, p1: Bitmap, p2: int) -> None: ...
    @overload
    def __init__(self, p0: Context, p1: Bitmap) -> None: ...
    @overload
    def __init__(self, p0: Bitmap, p1: int) -> None: ...
    @overload
    def __init__(self, p0: Bitmap) -> None: ...
    @overload
    def __init__(self, p0: Drawable, p1: str) -> None: ...
    @overload
    def __init__(self, p0: Drawable, p1: int) -> None: ...
    @overload
    def __init__(self, p0: Drawable) -> None: ...
    def getSource(self) -> str: ...
    def getDrawable(self) -> Drawable: ...
    def toString(self) -> str: ...
