from typing import Any, ClassVar, overload
from android.text.TextPaint import TextPaint
from android.text.style.CharacterStyle import CharacterStyle

class MetricAffectingSpan:
    def __init__(self) -> None: ...
    def updateMeasureState(self, p0: TextPaint) -> None: ...
    @overload
    def getUnderlying(self) -> "MetricAffectingSpan": ...
    @overload
    def getUnderlying(self) -> CharacterStyle: ...
