from typing import Any, ClassVar, overload
from android.os.Parcel import Parcel
from android.text.TextPaint import TextPaint

class StrikethroughSpan:
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, p0: Parcel) -> None: ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
    def updateDrawState(self, p0: TextPaint) -> None: ...
    def getSpanTypeId(self) -> int: ...
    def toString(self) -> str: ...
