from typing import Any, ClassVar, overload
from android.content.ComponentName import ComponentName
from android.net.Uri import Uri
from android.os.Parcel import Parcel

class AppLinkInfo:
    CREATOR: ClassVar[Any]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    def __init__(self, p0: str, p1: str, p2: str) -> None: ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
    def getComponentName(self) -> ComponentName: ...
    def getUri(self) -> Uri: ...
    def toString(self) -> str: ...
