from typing import Any, ClassVar, overload
from android.telephony.ims.ImsStateCallback import ImsStateCallback
from java.util.concurrent.Executor import Executor
from java.util.function.Consumer import Consumer

class ImsMmTelManager:
    WIFI_MODE_CELLULAR_PREFERRED: ClassVar[int]
    WIFI_MODE_WIFI_ONLY: ClassVar[int]
    WIFI_MODE_WIFI_PREFERRED: ClassVar[int]
    REGISTRATION_STATE_NOT_REGISTERED: ClassVar[int]
    REGISTRATION_STATE_REGISTERED: ClassVar[int]
    REGISTRATION_STATE_REGISTERING: ClassVar[int]
    def registerImsRegistrationCallback(self, p0: Executor, p1: Any) -> None: ...
    def unregisterImsRegistrationCallback(self, p0: Any) -> None: ...
    def getRegistrationState(self, p0: Executor, p1: Consumer) -> None: ...
    def getRegistrationTransportType(self, p0: Executor, p1: Consumer) -> None: ...
    def registerMmTelCapabilityCallback(self, p0: Executor, p1: Any) -> None: ...
    def unregisterMmTelCapabilityCallback(self, p0: Any) -> None: ...
    def isAdvancedCallingSettingEnabled(self) -> bool: ...
    def isVtSettingEnabled(self) -> bool: ...
    def isVoWiFiSettingEnabled(self) -> bool: ...
    def isCrossSimCallingEnabled(self) -> bool: ...
    def isVoWiFiRoamingSettingEnabled(self) -> bool: ...
    def getVoWiFiModeSetting(self) -> int: ...
    def isTtyOverVolteEnabled(self) -> bool: ...
    def registerImsStateCallback(self, p0: Executor, p1: ImsStateCallback) -> None: ...
    def unregisterImsStateCallback(self, p0: ImsStateCallback) -> None: ...

    class CapabilityCallback:
        def __init__(self) -> None: ...
        def onCapabilitiesStatusChanged(self, p0: Any) -> None: ...
