from typing import Any, ClassVar, overload
from android.os.Parcel import Parcel
from android.telephony.ims.SipDetails import SipDetails

class ImsRegistrationAttributes:
    ATTR_EPDG_OVER_CELL_INTERNET: ClassVar[int]
    CREATOR: ClassVar[Any]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    def getAttributeFlags(self) -> int: ...
    def getSipDetails(self) -> SipDetails: ...
    def getFeatureTags(self) -> set: ...
    def getTransportType(self) -> int: ...
    def equals(self, p0: Any) -> bool: ...
    def toString(self) -> str: ...
    def hashCode(self) -> int: ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
