from typing import Any, ClassVar, overload
from java.nio.Buffer import Buffer
from java.nio.ByteOrder import ByteOrder

class FloatBuffer:
    @overload
    def reset(self) -> Buffer: ...
    @overload
    def reset(self) -> "FloatBuffer": ...
    @overload
    def get(self, p0: int, p1: Any) -> "FloatBuffer": ...
    @overload
    def get(self, p0: int) -> float: ...
    @overload
    def get(self, p0: Any, p1: int, p2: int) -> "FloatBuffer": ...
    @overload
    def get(self, p0: Any) -> "FloatBuffer": ...
    @overload
    def get(self, p0: int, p1: Any, p2: int, p3: int) -> "FloatBuffer": ...
    @overload
    def get(self) -> float: ...
    @overload
    def put(self, p0: int, p1: Any, p2: int, p3: int) -> "FloatBuffer": ...
    @overload
    def put(self, p0: int, p1: Any) -> "FloatBuffer": ...
    @overload
    def put(self, p0: int, p1: "FloatBuffer", p2: int, p3: int) -> "FloatBuffer": ...
    @overload
    def put(self, p0: Any) -> "FloatBuffer": ...
    @overload
    def put(self, p0: "FloatBuffer") -> "FloatBuffer": ...
    @overload
    def put(self, p0: Any, p1: int, p2: int) -> "FloatBuffer": ...
    @overload
    def put(self, p0: float) -> "FloatBuffer": ...
    @overload
    def put(self, p0: int, p1: float) -> "FloatBuffer": ...
    def equals(self, p0: Any) -> bool: ...
    def toString(self) -> str: ...
    def hashCode(self) -> int: ...
    @overload
    def compareTo(self, p0: Any) -> int: ...
    @overload
    def compareTo(self, p0: "FloatBuffer") -> int: ...
    @overload
    def clear(self) -> "FloatBuffer": ...
    @overload
    def clear(self) -> Buffer: ...
    @overload
    @staticmethod
    def wrap(p0: Any, p1: int, p2: int) -> "FloatBuffer": ...
    @overload
    @staticmethod
    def wrap(p0: Any) -> "FloatBuffer": ...
    @overload
    def position(self, p0: int) -> "FloatBuffer": ...
    @overload
    def position(self, p0: int) -> Buffer: ...
    def mismatch(self, p0: "FloatBuffer") -> int: ...
    @overload
    def limit(self, p0: int) -> Buffer: ...
    @overload
    def limit(self, p0: int) -> "FloatBuffer": ...
    def isDirect(self) -> bool: ...
    def hasArray(self) -> bool: ...
    @overload
    def array(self) -> Any: ...
    @overload
    def array(self) -> Any: ...
    def arrayOffset(self) -> int: ...
    @overload
    def mark(self) -> "FloatBuffer": ...
    @overload
    def mark(self) -> Buffer: ...
    @overload
    def flip(self) -> Buffer: ...
    @overload
    def flip(self) -> "FloatBuffer": ...
    @overload
    def rewind(self) -> "FloatBuffer": ...
    @overload
    def rewind(self) -> Buffer: ...
    @overload
    def slice(self) -> "FloatBuffer": ...
    @overload
    def slice(self) -> Buffer: ...
    @overload
    def slice(self, p0: int, p1: int) -> Buffer: ...
    @overload
    def slice(self, p0: int, p1: int) -> "FloatBuffer": ...
    @overload
    def duplicate(self) -> "FloatBuffer": ...
    @overload
    def duplicate(self) -> Buffer: ...
    @staticmethod
    def allocate(p0: int) -> "FloatBuffer": ...
    def asReadOnlyBuffer(self) -> "FloatBuffer": ...
    def compact(self) -> "FloatBuffer": ...
    def order(self) -> ByteOrder: ...
