from typing import Any, ClassVar, overload
from java.nio.Buffer import Buffer
from java.nio.ByteBuffer import ByteBuffer

class MappedByteBuffer:
    @overload
    def reset(self) -> ByteBuffer: ...
    @overload
    def reset(self) -> Buffer: ...
    @overload
    def reset(self) -> "MappedByteBuffer": ...
    def load(self) -> "MappedByteBuffer": ...
    @overload
    def clear(self) -> "MappedByteBuffer": ...
    @overload
    def clear(self) -> ByteBuffer: ...
    @overload
    def clear(self) -> Buffer: ...
    @overload
    def position(self, p0: int) -> ByteBuffer: ...
    @overload
    def position(self, p0: int) -> Buffer: ...
    @overload
    def position(self, p0: int) -> "MappedByteBuffer": ...
    @overload
    def limit(self, p0: int) -> ByteBuffer: ...
    @overload
    def limit(self, p0: int) -> Buffer: ...
    @overload
    def limit(self, p0: int) -> "MappedByteBuffer": ...
    @overload
    def mark(self) -> "MappedByteBuffer": ...
    @overload
    def mark(self) -> ByteBuffer: ...
    @overload
    def mark(self) -> Buffer: ...
    @overload
    def flip(self) -> Buffer: ...
    @overload
    def flip(self) -> ByteBuffer: ...
    @overload
    def flip(self) -> "MappedByteBuffer": ...
    @overload
    def rewind(self) -> "MappedByteBuffer": ...
    @overload
    def rewind(self) -> Buffer: ...
    @overload
    def rewind(self) -> ByteBuffer: ...
    @overload
    def slice(self, p0: int, p1: int) -> ByteBuffer: ...
    @overload
    def slice(self, p0: int, p1: int) -> Buffer: ...
    @overload
    def slice(self) -> ByteBuffer: ...
    @overload
    def slice(self) -> "MappedByteBuffer": ...
    @overload
    def slice(self) -> Buffer: ...
    @overload
    def slice(self, p0: int, p1: int) -> "MappedByteBuffer": ...
    @overload
    def duplicate(self) -> "MappedByteBuffer": ...
    @overload
    def duplicate(self) -> Buffer: ...
    @overload
    def duplicate(self) -> ByteBuffer: ...
    @overload
    def compact(self) -> "MappedByteBuffer": ...
    @overload
    def compact(self) -> ByteBuffer: ...
    def isLoaded(self) -> bool: ...
    @overload
    def force(self) -> "MappedByteBuffer": ...
    @overload
    def force(self, p0: int, p1: int) -> "MappedByteBuffer": ...
