from typing import Any, ClassVar, overload

class FrameStats:
    UNDEFINED_TIME_NANO: ClassVar[int]
    def __init__(self) -> None: ...
    def getFrameCount(self) -> int: ...
    def getRefreshPeriodNano(self) -> int: ...
    def getEndTimeNano(self) -> int: ...
    def getStartTimeNano(self) -> int: ...
    def getFramePresentedTimeNano(self, p0: int) -> int: ...
