from typing import Any, ClassVar, overload
from android.graphics.Matrix import Matrix
from android.os.Parcel import Parcel

class MotionEvent:
    ACTION_BUTTON_PRESS: ClassVar[int]
    ACTION_BUTTON_RELEASE: ClassVar[int]
    ACTION_CANCEL: ClassVar[int]
    ACTION_DOWN: ClassVar[int]
    ACTION_HOVER_ENTER: ClassVar[int]
    ACTION_HOVER_EXIT: ClassVar[int]
    ACTION_HOVER_MOVE: ClassVar[int]
    ACTION_MASK: ClassVar[int]
    ACTION_MOVE: ClassVar[int]
    ACTION_OUTSIDE: ClassVar[int]
    ACTION_POINTER_1_DOWN: ClassVar[int]
    ACTION_POINTER_1_UP: ClassVar[int]
    ACTION_POINTER_2_DOWN: ClassVar[int]
    ACTION_POINTER_2_UP: ClassVar[int]
    ACTION_POINTER_3_DOWN: ClassVar[int]
    ACTION_POINTER_3_UP: ClassVar[int]
    ACTION_POINTER_DOWN: ClassVar[int]
    ACTION_POINTER_ID_MASK: ClassVar[int]
    ACTION_POINTER_ID_SHIFT: ClassVar[int]
    ACTION_POINTER_INDEX_MASK: ClassVar[int]
    ACTION_POINTER_INDEX_SHIFT: ClassVar[int]
    ACTION_POINTER_UP: ClassVar[int]
    ACTION_SCROLL: ClassVar[int]
    ACTION_UP: ClassVar[int]
    AXIS_BRAKE: ClassVar[int]
    AXIS_DISTANCE: ClassVar[int]
    AXIS_GAS: ClassVar[int]
    AXIS_GENERIC_1: ClassVar[int]
    AXIS_GENERIC_10: ClassVar[int]
    AXIS_GENERIC_11: ClassVar[int]
    AXIS_GENERIC_12: ClassVar[int]
    AXIS_GENERIC_13: ClassVar[int]
    AXIS_GENERIC_14: ClassVar[int]
    AXIS_GENERIC_15: ClassVar[int]
    AXIS_GENERIC_16: ClassVar[int]
    AXIS_GENERIC_2: ClassVar[int]
    AXIS_GENERIC_3: ClassVar[int]
    AXIS_GENERIC_4: ClassVar[int]
    AXIS_GENERIC_5: ClassVar[int]
    AXIS_GENERIC_6: ClassVar[int]
    AXIS_GENERIC_7: ClassVar[int]
    AXIS_GENERIC_8: ClassVar[int]
    AXIS_GENERIC_9: ClassVar[int]
    AXIS_GESTURE_PINCH_SCALE_FACTOR: ClassVar[int]
    AXIS_GESTURE_SCROLL_X_DISTANCE: ClassVar[int]
    AXIS_GESTURE_SCROLL_Y_DISTANCE: ClassVar[int]
    AXIS_GESTURE_X_OFFSET: ClassVar[int]
    AXIS_GESTURE_Y_OFFSET: ClassVar[int]
    AXIS_HAT_X: ClassVar[int]
    AXIS_HAT_Y: ClassVar[int]
    AXIS_HSCROLL: ClassVar[int]
    AXIS_LTRIGGER: ClassVar[int]
    AXIS_ORIENTATION: ClassVar[int]
    AXIS_PRESSURE: ClassVar[int]
    AXIS_RELATIVE_X: ClassVar[int]
    AXIS_RELATIVE_Y: ClassVar[int]
    AXIS_RTRIGGER: ClassVar[int]
    AXIS_RUDDER: ClassVar[int]
    AXIS_RX: ClassVar[int]
    AXIS_RY: ClassVar[int]
    AXIS_RZ: ClassVar[int]
    AXIS_SCROLL: ClassVar[int]
    AXIS_SIZE: ClassVar[int]
    AXIS_THROTTLE: ClassVar[int]
    AXIS_TILT: ClassVar[int]
    AXIS_TOOL_MAJOR: ClassVar[int]
    AXIS_TOOL_MINOR: ClassVar[int]
    AXIS_TOUCH_MAJOR: ClassVar[int]
    AXIS_TOUCH_MINOR: ClassVar[int]
    AXIS_VSCROLL: ClassVar[int]
    AXIS_WHEEL: ClassVar[int]
    AXIS_X: ClassVar[int]
    AXIS_Y: ClassVar[int]
    AXIS_Z: ClassVar[int]
    BUTTON_BACK: ClassVar[int]
    BUTTON_FORWARD: ClassVar[int]
    BUTTON_PRIMARY: ClassVar[int]
    BUTTON_SECONDARY: ClassVar[int]
    BUTTON_STYLUS_PRIMARY: ClassVar[int]
    BUTTON_STYLUS_SECONDARY: ClassVar[int]
    BUTTON_TERTIARY: ClassVar[int]
    CLASSIFICATION_AMBIGUOUS_GESTURE: ClassVar[int]
    CLASSIFICATION_DEEP_PRESS: ClassVar[int]
    CLASSIFICATION_NONE: ClassVar[int]
    CLASSIFICATION_PINCH: ClassVar[int]
    CLASSIFICATION_TWO_FINGER_SWIPE: ClassVar[int]
    CREATOR: ClassVar[Any]
    EDGE_BOTTOM: ClassVar[int]
    EDGE_LEFT: ClassVar[int]
    EDGE_RIGHT: ClassVar[int]
    EDGE_TOP: ClassVar[int]
    FLAG_CANCELED: ClassVar[int]
    FLAG_WINDOW_IS_OBSCURED: ClassVar[int]
    FLAG_WINDOW_IS_PARTIALLY_OBSCURED: ClassVar[int]
    INVALID_POINTER_ID: ClassVar[int]
    TOOL_TYPE_ERASER: ClassVar[int]
    TOOL_TYPE_FINGER: ClassVar[int]
    TOOL_TYPE_MOUSE: ClassVar[int]
    TOOL_TYPE_STYLUS: ClassVar[int]
    TOOL_TYPE_UNKNOWN: ClassVar[int]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    CREATOR: ClassVar[Any]
    def toString(self) -> str: ...
    def transform(self, p0: Matrix) -> None: ...
    @overload
    def getSize(self, p0: int) -> float: ...
    @overload
    def getSize(self) -> float: ...
    @staticmethod
    def actionToString(p0: int) -> str: ...
    @overload
    def addBatch(self, p0: int, p1: Any, p2: int) -> None: ...
    @overload
    def addBatch(self, p0: int, p1: float, p2: float, p3: float, p4: float, p5: int) -> None: ...
    @staticmethod
    def axisFromString(p0: str) -> int: ...
    @staticmethod
    def axisToString(p0: int) -> str: ...
    def findPointerIndex(self, p0: int) -> int: ...
    def getActionButton(self) -> int: ...
    def getActionIndex(self) -> int: ...
    def getActionMasked(self) -> int: ...
    @overload
    def getAxisValue(self, p0: int) -> float: ...
    @overload
    def getAxisValue(self, p0: int, p1: int) -> float: ...
    def getButtonState(self) -> int: ...
    def getClassification(self) -> int: ...
    def getEdgeFlags(self) -> int: ...
    def getEventTimeNanos(self) -> int: ...
    @overload
    def getHistoricalAxisValue(self, p0: int, p1: int, p2: int) -> float: ...
    @overload
    def getHistoricalAxisValue(self, p0: int, p1: int) -> float: ...
    def getHistoricalEventTime(self, p0: int) -> int: ...
    def getHistoricalEventTimeNanos(self, p0: int) -> int: ...
    @overload
    def getHistoricalOrientation(self, p0: int) -> float: ...
    @overload
    def getHistoricalOrientation(self, p0: int, p1: int) -> float: ...
    def getHistoricalPointerCoords(self, p0: int, p1: int, p2: Any) -> None: ...
    @overload
    def getHistoricalPressure(self, p0: int, p1: int) -> float: ...
    @overload
    def getHistoricalPressure(self, p0: int) -> float: ...
    @overload
    def getHistoricalSize(self, p0: int, p1: int) -> float: ...
    @overload
    def getHistoricalSize(self, p0: int) -> float: ...
    @overload
    def getHistoricalToolMajor(self, p0: int, p1: int) -> float: ...
    @overload
    def getHistoricalToolMajor(self, p0: int) -> float: ...
    @overload
    def getHistoricalToolMinor(self, p0: int, p1: int) -> float: ...
    @overload
    def getHistoricalToolMinor(self, p0: int) -> float: ...
    @overload
    def getHistoricalTouchMajor(self, p0: int, p1: int) -> float: ...
    @overload
    def getHistoricalTouchMajor(self, p0: int) -> float: ...
    @overload
    def getHistoricalTouchMinor(self, p0: int, p1: int) -> float: ...
    @overload
    def getHistoricalTouchMinor(self, p0: int) -> float: ...
    @overload
    def getHistoricalX(self, p0: int, p1: int) -> float: ...
    @overload
    def getHistoricalX(self, p0: int) -> float: ...
    @overload
    def getHistoricalY(self, p0: int, p1: int) -> float: ...
    @overload
    def getHistoricalY(self, p0: int) -> float: ...
    def getHistorySize(self) -> int: ...
    @overload
    def getOrientation(self) -> float: ...
    @overload
    def getOrientation(self, p0: int) -> float: ...
    def getPointerCoords(self, p0: int, p1: Any) -> None: ...
    def getPointerCount(self) -> int: ...
    def getPointerId(self, p0: int) -> int: ...
    def getPointerProperties(self, p0: int, p1: Any) -> None: ...
    @overload
    def getPressure(self, p0: int) -> float: ...
    @overload
    def getPressure(self) -> float: ...
    @overload
    def getRawX(self, p0: int) -> float: ...
    @overload
    def getRawX(self) -> float: ...
    @overload
    def getRawY(self, p0: int) -> float: ...
    @overload
    def getRawY(self) -> float: ...
    @overload
    def getToolMajor(self) -> float: ...
    @overload
    def getToolMajor(self, p0: int) -> float: ...
    @overload
    def getToolMinor(self) -> float: ...
    @overload
    def getToolMinor(self, p0: int) -> float: ...
    def getToolType(self, p0: int) -> int: ...
    @overload
    def getTouchMajor(self) -> float: ...
    @overload
    def getTouchMajor(self, p0: int) -> float: ...
    @overload
    def getTouchMinor(self) -> float: ...
    @overload
    def getTouchMinor(self, p0: int) -> float: ...
    def getXPrecision(self) -> float: ...
    def getYPrecision(self) -> float: ...
    def isButtonPressed(self, p0: int) -> bool: ...
    @staticmethod
    def obtainNoHistory(p0: "MotionEvent") -> "MotionEvent": ...
    def offsetLocation(self, p0: float, p1: float) -> None: ...
    def setEdgeFlags(self, p0: int) -> None: ...
    def setLocation(self, p0: float, p1: float) -> None: ...
    def setSource(self, p0: int) -> None: ...
    def getEventTime(self) -> int: ...
    def getMetaState(self) -> int: ...
    def getSource(self) -> int: ...
    def getDownTime(self) -> int: ...
    def setAction(self, p0: int) -> None: ...
    def getFlags(self) -> int: ...
    def getAction(self) -> int: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
    def getDeviceId(self) -> int: ...
    @overload
    @staticmethod
    def obtain(p0: int, p1: int, p2: int, p3: int, p4: Any, p5: Any, p6: int, p7: float, p8: float, p9: int, p10: int, p11: int, p12: int) -> "MotionEvent": ...
    @overload
    @staticmethod
    def obtain(p0: int, p1: int, p2: int, p3: float, p4: float, p5: int) -> "MotionEvent": ...
    @overload
    @staticmethod
    def obtain(p0: int, p1: int, p2: int, p3: float, p4: float, p5: float, p6: float, p7: int, p8: float, p9: float, p10: int, p11: int) -> "MotionEvent": ...
    @overload
    @staticmethod
    def obtain(p0: "MotionEvent") -> "MotionEvent": ...
    @overload
    @staticmethod
    def obtain(p0: int, p1: int, p2: int, p3: int, p4: float, p5: float, p6: float, p7: float, p8: int, p9: float, p10: float, p11: int, p12: int) -> "MotionEvent": ...
    @overload
    @staticmethod
    def obtain(p0: int, p1: int, p2: int, p3: int, p4: Any, p5: Any, p6: int, p7: int, p8: float, p9: float, p10: int, p11: int, p12: int, p13: int, p14: int, p15: int) -> "MotionEvent": ...
    @overload
    @staticmethod
    def obtain(p0: int, p1: int, p2: int, p3: int, p4: Any, p5: Any, p6: int, p7: int, p8: float, p9: float, p10: int, p11: int, p12: int, p13: int) -> "MotionEvent": ...
    def recycle(self) -> None: ...
    @overload
    def getX(self) -> float: ...
    @overload
    def getX(self, p0: int) -> float: ...
    @overload
    def getY(self) -> float: ...
    @overload
    def getY(self, p0: int) -> float: ...

    class PointerProperties:
        id: int
        toolType: int
        @overload
        def __init__(self) -> None: ...
        @overload
        def __init__(self, p0: Any) -> None: ...
        def equals(self, p0: Any) -> bool: ...
        def hashCode(self) -> int: ...
        def clear(self) -> None: ...
        def copyFrom(self, p0: Any) -> None: ...

    class PointerCoords:
        orientation: float
        pressure: float
        size: float
        toolMajor: float
        toolMinor: float
        touchMajor: float
        touchMinor: float
        x: float
        y: float
        @overload
        def __init__(self) -> None: ...
        @overload
        def __init__(self, p0: Any) -> None: ...
        def isResampled(self) -> bool: ...
        def setAxisValue(self, p0: int, p1: float) -> None: ...
        def clear(self) -> None: ...
        def getAxisValue(self, p0: int) -> float: ...
        def copyFrom(self, p0: Any) -> None: ...
