from typing import Any, ClassVar, overload
from android.graphics.Rect import Rect
from android.graphics.Region import Region
from android.hardware.HardwareBuffer import HardwareBuffer
from android.hardware.SyncFence import SyncFence
from android.os.Parcel import Parcel
from java.util.concurrent.Executor import Executor
from java.util.function.Consumer import Consumer

class SurfaceControl:
    BUFFER_TRANSFORM_IDENTITY: ClassVar[int]
    BUFFER_TRANSFORM_MIRROR_HORIZONTAL: ClassVar[int]
    BUFFER_TRANSFORM_MIRROR_VERTICAL: ClassVar[int]
    BUFFER_TRANSFORM_ROTATE_180: ClassVar[int]
    BUFFER_TRANSFORM_ROTATE_270: ClassVar[int]
    BUFFER_TRANSFORM_ROTATE_90: ClassVar[int]
    CREATOR: ClassVar[Any]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    def describeContents(self) -> int: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
    def readFromParcel(self, p0: Parcel) -> None: ...
    def isValid(self) -> bool: ...
    def release(self) -> None: ...
    def toString(self) -> str: ...

    class TrustedPresentationThresholds:
        def __init__(self, p0: float, p1: float, p2: int) -> None: ...

    class TransactionStats:
        def getLatchTimeNanos(self) -> int: ...
        def getPresentFence(self) -> SyncFence: ...

    class TransactionCommittedListener:
        def onTransactionCommitted(self) -> None: ...

    class Transaction:
        CREATOR: ClassVar[Any]
        CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
        PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
        def __init__(self) -> None: ...
        def setExtendedRangeBrightness(self, p0: "SurfaceControl", p1: float, p2: float) -> Any: ...
        def setPosition(self, p0: "SurfaceControl", p1: float, p2: float) -> Any: ...
        def setBufferSize(self, p0: "SurfaceControl", p1: int, p2: int) -> Any: ...
        def setLayer(self, p0: "SurfaceControl", p1: int) -> Any: ...
        def setGeometry(self, p0: "SurfaceControl", p1: Rect, p2: Rect, p3: int) -> Any: ...
        def setCrop(self, p0: "SurfaceControl", p1: Rect) -> Any: ...
        def reparent(self, p0: "SurfaceControl", p1: "SurfaceControl") -> Any: ...
        @overload
        def setBuffer(self, p0: "SurfaceControl", p1: HardwareBuffer, p2: SyncFence, p3: Consumer) -> Any: ...
        @overload
        def setBuffer(self, p0: "SurfaceControl", p1: HardwareBuffer) -> Any: ...
        @overload
        def setBuffer(self, p0: "SurfaceControl", p1: HardwareBuffer, p2: SyncFence) -> Any: ...
        def setBufferTransform(self, p0: "SurfaceControl", p1: int) -> Any: ...
        def setDamageRegion(self, p0: "SurfaceControl", p1: Region) -> Any: ...
        def setFrameTimeline(self, p0: int) -> Any: ...
        def addTransactionCommittedListener(self, p0: Executor, p1: Any) -> Any: ...
        def addTransactionCompletedListener(self, p0: Executor, p1: Consumer) -> Any: ...
        def setTrustedPresentationCallback(self, p0: "SurfaceControl", p1: Any, p2: Executor, p3: Consumer) -> Any: ...
        def clearTrustedPresentationCallback(self, p0: "SurfaceControl") -> Any: ...
        def setDesiredPresentTimeNanos(self, p0: int) -> Any: ...
        @overload
        def setFrameRate(self, p0: "SurfaceControl", p1: float, p2: int) -> Any: ...
        @overload
        def setFrameRate(self, p0: "SurfaceControl", p1: float, p2: int, p3: int) -> Any: ...
        def clearFrameRate(self, p0: "SurfaceControl") -> Any: ...
        def describeContents(self) -> int: ...
        def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
        def setScale(self, p0: "SurfaceControl", p1: float, p2: float) -> Any: ...
        def setAlpha(self, p0: "SurfaceControl", p1: float) -> Any: ...
        def setVisibility(self, p0: "SurfaceControl", p1: bool) -> Any: ...
        def setDesiredHdrHeadroom(self, p0: "SurfaceControl", p1: float) -> Any: ...
        def setOpaque(self, p0: "SurfaceControl", p1: bool) -> Any: ...
        def setDataSpace(self, p0: "SurfaceControl", p1: int) -> Any: ...
        def apply(self) -> None: ...
        def merge(self, p0: Any) -> Any: ...
        def close(self) -> None: ...

    class Builder:
        def __init__(self) -> None: ...
        def setBufferSize(self, p0: int, p1: int) -> Any: ...
        def setHidden(self, p0: bool) -> Any: ...
        def setParent(self, p0: "SurfaceControl") -> Any: ...
        def setOpaque(self, p0: bool) -> Any: ...
        def build(self) -> "SurfaceControl": ...
        def setFormat(self, p0: int) -> Any: ...
        def setName(self, p0: str) -> Any: ...
