from typing import Any, ClassVar, overload
from android.os.Parcel import Parcel

class TextInfo:
    CREATOR: ClassVar[Any]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    @overload
    def __init__(self, p0: str, p1: int, p2: int) -> None: ...
    @overload
    def __init__(self, p0: str) -> None: ...
    @overload
    def __init__(self, p0: str, p1: int, p2: int, p3: int, p4: int) -> None: ...
    @overload
    def __init__(self, p0: Parcel) -> None: ...
    def getSequence(self) -> int: ...
    def describeContents(self) -> int: ...
    def getCharSequence(self) -> str: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
    def getText(self) -> str: ...
    def getCookie(self) -> int: ...

from typing import Any, ClassVar, overload
from android.os.Parcel import Parcel
from android.view.textservice.SuggestionsInfo import SuggestionsInfo

class SentenceSuggestionsInfo:
    CREATOR: ClassVar[Any]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    @overload
    def __init__(self, p0: Parcel) -> None: ...
    @overload
    def __init__(self, p0: Any, p1: Any, p2: Any) -> None: ...
    def getSuggestionsCount(self) -> int: ...
    def getLengthAt(self, p0: int) -> int: ...
    def getOffsetAt(self, p0: int) -> int: ...
    def getSuggestionsInfoAt(self, p0: int) -> SuggestionsInfo: ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...

from typing import Any, ClassVar, overload
from android.os.Bundle import Bundle
from android.view.textservice.SpellCheckerInfo import SpellCheckerInfo
from android.view.textservice.TextInfo import TextInfo
from java.util.Locale import Locale

class SpellCheckerSession:
    SERVICE_META_DATA: ClassVar[str]
    @overload
    def getSuggestions(self, p0: TextInfo, p1: int) -> None: ...
    @overload
    def getSuggestions(self, p0: Any, p1: int, p2: bool) -> None: ...
    def getSentenceSuggestions(self, p0: Any, p1: int) -> None: ...
    def getSpellChecker(self) -> SpellCheckerInfo: ...
    def isSessionDisconnected(self) -> bool: ...
    def cancel(self) -> None: ...
    def close(self) -> None: ...

    class SpellCheckerSessionParams:
        def getSupportedAttributes(self) -> int: ...
        def shouldReferToSpellCheckerLanguageSettings(self) -> bool: ...
        def getLocale(self) -> Locale: ...
        def getExtras(self) -> Bundle: ...

        class Builder:
            def __init__(self) -> None: ...
            def setSupportedAttributes(self, p0: int) -> Any: ...
            def setShouldReferToSpellCheckerLanguageSettings(self, p0: bool) -> Any: ...
            def build(self) -> Any: ...
            def setExtras(self, p0: Bundle) -> Any: ...
            def setLocale(self, p0: Locale) -> Any: ...

    class SpellCheckerSessionListener:
        def onGetSuggestions(self, p0: Any) -> None: ...
        def onGetSentenceSuggestions(self, p0: Any) -> None: ...

from typing import Any, ClassVar, overload
from android.content.ComponentName import ComponentName
from android.content.pm.PackageManager import PackageManager
from android.content.pm.ServiceInfo import ServiceInfo
from android.graphics.drawable.Drawable import Drawable
from android.os.Parcel import Parcel
from android.view.textservice.SpellCheckerSubtype import SpellCheckerSubtype

class SpellCheckerInfo:
    CREATOR: ClassVar[Any]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    def getSubtypeAt(self, p0: int) -> SpellCheckerSubtype: ...
    def getSubtypeCount(self) -> int: ...
    def getServiceInfo(self) -> ServiceInfo: ...
    def getPackageName(self) -> str: ...
    def getId(self) -> str: ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
    def getSettingsActivity(self) -> str: ...
    def loadIcon(self, p0: PackageManager) -> Drawable: ...
    def loadLabel(self, p0: PackageManager) -> str: ...
    def getComponent(self) -> ComponentName: ...

from typing import Any, ClassVar, overload
from android.os.Bundle import Bundle
from android.view.textservice.SpellCheckerInfo import SpellCheckerInfo
from android.view.textservice.SpellCheckerSession import SpellCheckerSession
from java.util.Locale import Locale
from java.util.concurrent.Executor import Executor

class TextServicesManager:
    def getEnabledSpellCheckerInfos(self) -> list: ...
    def getCurrentSpellCheckerInfo(self) -> SpellCheckerInfo: ...
    def isSpellCheckerEnabled(self) -> bool: ...
    @overload
    def newSpellCheckerSession(self, p0: Bundle, p1: Locale, p2: Any, p3: bool) -> SpellCheckerSession: ...
    @overload
    def newSpellCheckerSession(self, p0: Any, p1: Executor, p2: Any) -> SpellCheckerSession: ...

from typing import Any, ClassVar, overload
from android.content.Context import Context
from android.content.pm.ApplicationInfo import ApplicationInfo
from android.os.Parcel import Parcel

class SpellCheckerSubtype:
    CREATOR: ClassVar[Any]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    def __init__(self, p0: int, p1: str, p2: str) -> None: ...
    def getExtraValue(self) -> str: ...
    def getExtraValueOf(self, p0: str) -> str: ...
    def containsExtraValueKey(self, p0: str) -> bool: ...
    def getLanguageTag(self) -> str: ...
    def getNameResId(self) -> int: ...
    def equals(self, p0: Any) -> bool: ...
    def hashCode(self) -> int: ...
    def getDisplayName(self, p0: Context, p1: str, p2: ApplicationInfo) -> str: ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
    def getLocale(self) -> str: ...

from typing import Any, ClassVar, overload
from android.os.Parcel import Parcel

class SuggestionsInfo:
    CREATOR: ClassVar[Any]
    RESULT_ATTR_DONT_SHOW_UI_FOR_SUGGESTIONS: ClassVar[int]
    RESULT_ATTR_HAS_RECOMMENDED_SUGGESTIONS: ClassVar[int]
    RESULT_ATTR_IN_THE_DICTIONARY: ClassVar[int]
    RESULT_ATTR_LOOKS_LIKE_GRAMMAR_ERROR: ClassVar[int]
    RESULT_ATTR_LOOKS_LIKE_TYPO: ClassVar[int]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    @overload
    def __init__(self, p0: Parcel) -> None: ...
    @overload
    def __init__(self, p0: int, p1: Any) -> None: ...
    @overload
    def __init__(self, p0: int, p1: Any, p2: int, p3: int) -> None: ...
    def getSuggestionAt(self, p0: int) -> str: ...
    def getSuggestionsAttributes(self) -> int: ...
    def getSuggestionsCount(self) -> int: ...
    def setCookieAndSequence(self, p0: int, p1: int) -> None: ...
    def getSequence(self) -> int: ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
    def getCookie(self) -> int: ...

