from typing import Any, ClassVar, overload
from org.w3c.dom.Node import Node

class DOMSource:
    FEATURE: ClassVar[str]
    @overload
    def __init__(self, p0: Node, p1: str) -> None: ...
    @overload
    def __init__(self, p0: Node) -> None: ...
    @overload
    def __init__(self) -> None: ...
    def getSystemId(self) -> str: ...
    def isEmpty(self) -> bool: ...
    def getNode(self) -> Node: ...
    def setSystemId(self, p0: str) -> None: ...
    def setNode(self, p0: Node) -> None: ...
