from jnius import JavaClass, MetaJavaClass, JavaMethod, JavaStaticMethod, JavaMultipleMethod, JavaField, JavaStaticField

__all__ = ["PlaybackState"]

class PlaybackState(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "android/media/session/PlaybackState"
    ACTION_FAST_FORWARD = JavaStaticField("J")
    ACTION_PAUSE = JavaStaticField("J")
    ACTION_PLAY = JavaStaticField("J")
    ACTION_PLAY_FROM_MEDIA_ID = JavaStaticField("J")
    ACTION_PLAY_FROM_SEARCH = JavaStaticField("J")
    ACTION_PLAY_FROM_URI = JavaStaticField("J")
    ACTION_PLAY_PAUSE = JavaStaticField("J")
    ACTION_PREPARE = JavaStaticField("J")
    ACTION_PREPARE_FROM_MEDIA_ID = JavaStaticField("J")
    ACTION_PREPARE_FROM_SEARCH = JavaStaticField("J")
    ACTION_PREPARE_FROM_URI = JavaStaticField("J")
    ACTION_REWIND = JavaStaticField("J")
    ACTION_SEEK_TO = JavaStaticField("J")
    ACTION_SET_PLAYBACK_SPEED = JavaStaticField("J")
    ACTION_SET_RATING = JavaStaticField("J")
    ACTION_SKIP_TO_NEXT = JavaStaticField("J")
    ACTION_SKIP_TO_PREVIOUS = JavaStaticField("J")
    ACTION_SKIP_TO_QUEUE_ITEM = JavaStaticField("J")
    ACTION_STOP = JavaStaticField("J")
    CREATOR = JavaStaticField("Landroid/os/Parcelable$Creator;")
    PLAYBACK_POSITION_UNKNOWN = JavaStaticField("J")
    STATE_BUFFERING = JavaStaticField("I")
    STATE_CONNECTING = JavaStaticField("I")
    STATE_ERROR = JavaStaticField("I")
    STATE_FAST_FORWARDING = JavaStaticField("I")
    STATE_NONE = JavaStaticField("I")
    STATE_PAUSED = JavaStaticField("I")
    STATE_PLAYING = JavaStaticField("I")
    STATE_REWINDING = JavaStaticField("I")
    STATE_SKIPPING_TO_NEXT = JavaStaticField("I")
    STATE_SKIPPING_TO_PREVIOUS = JavaStaticField("I")
    STATE_SKIPPING_TO_QUEUE_ITEM = JavaStaticField("I")
    STATE_STOPPED = JavaStaticField("I")
    CONTENTS_FILE_DESCRIPTOR = JavaStaticField("I")
    PARCELABLE_WRITE_RETURN_VALUE = JavaStaticField("I")
    getErrorMessage = JavaMethod("()Ljava/lang/CharSequence;")
    getActiveQueueItemId = JavaMethod("()J")
    getBufferedPosition = JavaMethod("()J")
    getCustomActions = JavaMethod("()Ljava/util/List;")
    getLastPositionUpdateTime = JavaMethod("()J")
    getPlaybackSpeed = JavaMethod("()F")
    toString = JavaMethod("()Ljava/lang/String;")
    getState = JavaMethod("()I")
    getPosition = JavaMethod("()J")
    getActions = JavaMethod("()J")
    getExtras = JavaMethod("()Landroid/os/Bundle;")
    writeToParcel = JavaMethod("(Landroid/os/Parcel;I)V")
    describeContents = JavaMethod("()I")
    isActive = JavaMethod("()Z")

    class CustomAction(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "android/media/session/PlaybackState$CustomAction"
        CREATOR = JavaStaticField("Landroid/os/Parcelable$Creator;")
        CONTENTS_FILE_DESCRIPTOR = JavaStaticField("I")
        PARCELABLE_WRITE_RETURN_VALUE = JavaStaticField("I")
        getName = JavaMethod("()Ljava/lang/CharSequence;")
        toString = JavaMethod("()Ljava/lang/String;")
        getExtras = JavaMethod("()Landroid/os/Bundle;")
        getAction = JavaMethod("()Ljava/lang/String;")
        writeToParcel = JavaMethod("(Landroid/os/Parcel;I)V")
        describeContents = JavaMethod("()I")
        getIcon = JavaMethod("()I")

        class Builder(JavaClass, metaclass=MetaJavaClass):
            __javaclass__ = "android/media/session/PlaybackState$CustomAction$Builder"
            __javaconstructor__ = [("(Ljava/lang/String;Ljava/lang/CharSequence;I)V", False)]
            setExtras = JavaMethod("(Landroid/os/Bundle;)Landroid/media/session/PlaybackState$CustomAction$Builder;")
            build = JavaMethod("()Landroid/media/session/PlaybackState$CustomAction;")

    class Builder(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "android/media/session/PlaybackState$Builder"
        __javaconstructor__ = [("()V", False), ("(Landroid/media/session/PlaybackState;)V", False)]
        setActions = JavaMethod("(J)Landroid/media/session/PlaybackState$Builder;")
        addCustomAction = JavaMultipleMethod([("(Landroid/media/session/PlaybackState$CustomAction;)Landroid/media/session/PlaybackState$Builder;", False, False), ("(Ljava/lang/String;Ljava/lang/String;I)Landroid/media/session/PlaybackState$Builder;", False, False)])
        setActiveQueueItemId = JavaMethod("(J)Landroid/media/session/PlaybackState$Builder;")
        setBufferedPosition = JavaMethod("(J)Landroid/media/session/PlaybackState$Builder;")
        setErrorMessage = JavaMethod("(Ljava/lang/CharSequence;)Landroid/media/session/PlaybackState$Builder;")
        setState = JavaMultipleMethod([("(IJFJ)Landroid/media/session/PlaybackState$Builder;", False, False), ("(IJF)Landroid/media/session/PlaybackState$Builder;", False, False)])
        setExtras = JavaMethod("(Landroid/os/Bundle;)Landroid/media/session/PlaybackState$Builder;")
        build = JavaMethod("()Landroid/media/session/PlaybackState;")