from typing import Any, ClassVar, overload
from java.util.logging.ErrorManager import ErrorManager
from java.util.logging.Filter import Filter
from java.util.logging.Formatter import Formatter
from java.util.logging.Level import Level
from java.util.logging.LogRecord import LogRecord

class Handler:
    def isLoggable(self, p0: LogRecord) -> bool: ...
    def flush(self) -> None: ...
    def close(self) -> None: ...
    def setEncoding(self, p0: str) -> None: ...
    def setFormatter(self, p0: Formatter) -> None: ...
    def publish(self, p0: LogRecord) -> None: ...
    def getEncoding(self) -> str: ...
    def getFormatter(self) -> Formatter: ...
    def setErrorManager(self, p0: ErrorManager) -> None: ...
    def getErrorManager(self) -> ErrorManager: ...
    def setFilter(self, p0: Filter) -> None: ...
    def getLevel(self) -> Level: ...
    def setLevel(self, p0: Level) -> None: ...
    def getFilter(self) -> Filter: ...
