from typing import Any, ClassVar, overload
from android.media.midi.MidiDeviceInfo import MidiDeviceInfo
from android.media.midi.MidiInputPort import MidiInputPort
from android.media.midi.MidiOutputPort import MidiOutputPort

class MidiDevice:
    def getInfo(self) -> MidiDeviceInfo: ...
    def toString(self) -> str: ...
    def close(self) -> None: ...
    def connectPorts(self, p0: MidiInputPort, p1: int) -> Any: ...
    def openOutputPort(self, p0: int) -> MidiOutputPort: ...
    def openInputPort(self, p0: int) -> MidiInputPort: ...

    class MidiConnection:
        def close(self) -> None: ...
