from typing import Any, ClassVar, overload
from org.xml.sax.AttributeList import AttributeList
from org.xml.sax.InputSource import InputSource
from org.xml.sax.Locator import Locator
from org.xml.sax.SAXParseException import SAXParseException

class HandlerBase:
    def __init__(self) -> None: ...
    def endDocument(self) -> None: ...
    def ignorableWhitespace(self, p0: Any, p1: int, p2: int) -> None: ...
    def processingInstruction(self, p0: str, p1: str) -> None: ...
    def startDocument(self) -> None: ...
    def warning(self, p0: SAXParseException) -> None: ...
    def error(self, p0: SAXParseException) -> None: ...
    def characters(self, p0: Any, p1: int, p2: int) -> None: ...
    def fatalError(self, p0: SAXParseException) -> None: ...
    def notationDecl(self, p0: str, p1: str, p2: str) -> None: ...
    def unparsedEntityDecl(self, p0: str, p1: str, p2: str, p3: str) -> None: ...
    def resolveEntity(self, p0: str, p1: str) -> InputSource: ...
    def setDocumentLocator(self, p0: Locator) -> None: ...
    def startElement(self, p0: str, p1: AttributeList) -> None: ...
    def endElement(self, p0: str) -> None: ...
