from typing import Any, ClassVar, overload
from java.util.Locale import Locale
from org.xml.sax.DTDHandler import DTDHandler
from org.xml.sax.DocumentHandler import DocumentHandler
from org.xml.sax.EntityResolver import EntityResolver
from org.xml.sax.ErrorHandler import ErrorHandler
from org.xml.sax.InputSource import InputSource

class Parser:
    def setErrorHandler(self, p0: ErrorHandler) -> None: ...
    @overload
    def parse(self, p0: InputSource) -> None: ...
    @overload
    def parse(self, p0: str) -> None: ...
    def setEntityResolver(self, p0: EntityResolver) -> None: ...
    def setDTDHandler(self, p0: DTDHandler) -> None: ...
    def setLocale(self, p0: Locale) -> None: ...
    def setDocumentHandler(self, p0: DocumentHandler) -> None: ...
