from typing import Any, ClassVar, overload
from javax.sql.RowSetEvent import RowSetEvent

class RowSetListener:
    def rowSetChanged(self, p0: RowSetEvent) -> None: ...
    def cursorMoved(self, p0: RowSetEvent) -> None: ...
    def rowChanged(self, p0: RowSetEvent) -> None: ...
