from typing import Any, ClassVar, overload

class Observable:
    def __init__(self) -> None: ...
    def registerObserver(self, p0: Any) -> None: ...
    def unregisterAll(self) -> None: ...
    def unregisterObserver(self, p0: Any) -> None: ...

from typing import Any, ClassVar, overload
from android.database.CharArrayBuffer import CharArrayBuffer
from android.os.Parcel import Parcel

class CursorWindow:
    CREATOR: ClassVar[Any]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    @overload
    def __init__(self, p0: bool) -> None: ...
    @overload
    def __init__(self, p0: str) -> None: ...
    @overload
    def __init__(self, p0: str, p1: int) -> None: ...
    def isBlob(self, p0: int, p1: int) -> bool: ...
    def allocRow(self) -> bool: ...
    def isLong(self, p0: int, p1: int) -> bool: ...
    def freeLastRow(self) -> None: ...
    def getNumRows(self) -> int: ...
    @staticmethod
    def newFromParcel(p0: Parcel) -> "CursorWindow": ...
    def putBlob(self, p0: Any, p1: int, p2: int) -> bool: ...
    def setStartPosition(self, p0: int) -> None: ...
    def isNull(self, p0: int, p1: int) -> bool: ...
    def toString(self) -> str: ...
    def getShort(self, p0: int, p1: int) -> int: ...
    def getInt(self, p0: int, p1: int) -> int: ...
    def getLong(self, p0: int, p1: int) -> int: ...
    def putLong(self, p0: int, p1: int, p2: int) -> bool: ...
    def getFloat(self, p0: int, p1: int) -> float: ...
    def getDouble(self, p0: int, p1: int) -> float: ...
    def putDouble(self, p0: float, p1: int, p2: int) -> bool: ...
    def clear(self) -> None: ...
    def getType(self, p0: int, p1: int) -> int: ...
    def copyStringToBuffer(self, p0: int, p1: int, p2: CharArrayBuffer) -> None: ...
    def getBlob(self, p0: int, p1: int) -> Any: ...
    def putNull(self, p0: int, p1: int) -> bool: ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
    def getStartPosition(self) -> int: ...
    def isFloat(self, p0: int, p1: int) -> bool: ...
    def isString(self, p0: int, p1: int) -> bool: ...
    def getString(self, p0: int, p1: int) -> str: ...
    def putString(self, p0: str, p1: int, p2: int) -> bool: ...
    def setNumColumns(self, p0: int) -> bool: ...

from typing import Any, ClassVar, overload
from android.database.Cursor import Cursor
from java.util.Iterator import Iterator

class CursorJoiner:
    def __init__(self, p0: Cursor, p1: Any, p2: Cursor, p3: Any) -> None: ...
    def remove(self) -> None: ...
    def iterator(self) -> Iterator: ...
    def hasNext(self) -> bool: ...
    @overload
    def next(self) -> Any: ...
    @overload
    def next(self) -> Any: ...

    class Result:
        BOTH: ClassVar["Result"]
        LEFT: ClassVar["Result"]
        RIGHT: ClassVar["Result"]
        BOTH: ClassVar[Any]
        LEFT: ClassVar[Any]
        RIGHT: ClassVar[Any]
        @staticmethod
        def values() -> Any: ...
        @staticmethod
        def valueOf(p0: str) -> Any: ...

from typing import Any, ClassVar, overload

class DataSetObservable:
    def __init__(self) -> None: ...
    def notifyInvalidated(self) -> None: ...
    def notifyChanged(self) -> None: ...

from typing import Any, ClassVar, overload
from android.database.CursorWindow import CursorWindow

class CrossProcessCursor:
    FIELD_TYPE_BLOB: ClassVar[int]
    FIELD_TYPE_FLOAT: ClassVar[int]
    FIELD_TYPE_INTEGER: ClassVar[int]
    FIELD_TYPE_NULL: ClassVar[int]
    FIELD_TYPE_STRING: ClassVar[int]
    def onMove(self, p0: int, p1: int) -> bool: ...
    def fillWindow(self, p0: int, p1: CursorWindow) -> None: ...
    def getWindow(self) -> CursorWindow: ...

from typing import Any, ClassVar, overload
from android.database.sqlite.SQLiteDatabase import SQLiteDatabase

class DefaultDatabaseErrorHandler:
    def __init__(self) -> None: ...
    def onCorruption(self, p0: SQLiteDatabase) -> None: ...

from typing import Any, ClassVar, overload
from java.lang.Iterable import Iterable

class MatrixCursor:
    FIELD_TYPE_BLOB: ClassVar[int]
    FIELD_TYPE_FLOAT: ClassVar[int]
    FIELD_TYPE_INTEGER: ClassVar[int]
    FIELD_TYPE_NULL: ClassVar[int]
    FIELD_TYPE_STRING: ClassVar[int]
    @overload
    def __init__(self, p0: Any) -> None: ...
    @overload
    def __init__(self, p0: Any, p1: int) -> None: ...
    def newRow(self) -> Any: ...
    def isNull(self, p0: int) -> bool: ...
    def getShort(self, p0: int) -> int: ...
    def getInt(self, p0: int) -> int: ...
    def getLong(self, p0: int) -> int: ...
    def getFloat(self, p0: int) -> float: ...
    def getDouble(self, p0: int) -> float: ...
    def getCount(self) -> int: ...
    def getType(self, p0: int) -> int: ...
    def getBlob(self, p0: int) -> Any: ...
    def getColumnNames(self) -> Any: ...
    @overload
    def addRow(self, p0: Any) -> None: ...
    @overload
    def addRow(self, p0: Iterable) -> None: ...
    def getString(self, p0: int) -> str: ...

    class RowBuilder:
        @overload
        def add(self, p0: Any) -> Any: ...
        @overload
        def add(self, p0: str, p1: Any) -> Any: ...

from typing import Any, ClassVar, overload
from java.lang.Throwable import Throwable

class SQLException:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, p0: str) -> None: ...
    @overload
    def __init__(self, p0: str, p1: Throwable) -> None: ...

from typing import Any, ClassVar, overload

class StaleDataException:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, p0: str) -> None: ...

from typing import Any, ClassVar, overload
from android.content.ContentResolver import ContentResolver
from android.database.CharArrayBuffer import CharArrayBuffer
from android.database.ContentObserver import ContentObserver
from android.database.CursorWindow import CursorWindow
from android.database.DataSetObserver import DataSetObserver
from android.net.Uri import Uri
from android.os.Bundle import Bundle

class AbstractCursor:
    FIELD_TYPE_BLOB: ClassVar[int]
    FIELD_TYPE_FLOAT: ClassVar[int]
    FIELD_TYPE_INTEGER: ClassVar[int]
    FIELD_TYPE_NULL: ClassVar[int]
    FIELD_TYPE_STRING: ClassVar[int]
    def __init__(self) -> None: ...
    def onMove(self, p0: int, p1: int) -> bool: ...
    def fillWindow(self, p0: int, p1: CursorWindow) -> None: ...
    def isNull(self, p0: int) -> bool: ...
    def getShort(self, p0: int) -> int: ...
    def getInt(self, p0: int) -> int: ...
    def getLong(self, p0: int) -> int: ...
    def getFloat(self, p0: int) -> float: ...
    def getDouble(self, p0: int) -> float: ...
    def getCount(self) -> int: ...
    def close(self) -> None: ...
    def getType(self, p0: int) -> int: ...
    def isLast(self) -> bool: ...
    def registerContentObserver(self, p0: ContentObserver) -> None: ...
    def copyStringToBuffer(self, p0: int, p1: CharArrayBuffer) -> None: ...
    def deactivate(self) -> None: ...
    def getBlob(self, p0: int) -> Any: ...
    def getColumnIndex(self, p0: str) -> int: ...
    def getColumnIndexOrThrow(self, p0: str) -> int: ...
    def getColumnName(self, p0: int) -> str: ...
    def getColumnNames(self) -> Any: ...
    def getNotificationUri(self) -> Uri: ...
    def getNotificationUris(self) -> list: ...
    def getPosition(self) -> int: ...
    def getWantsAllOnMoveCalls(self) -> bool: ...
    def isAfterLast(self) -> bool: ...
    def isBeforeFirst(self) -> bool: ...
    def isClosed(self) -> bool: ...
    def isFirst(self) -> bool: ...
    def moveToFirst(self) -> bool: ...
    def moveToLast(self) -> bool: ...
    def moveToNext(self) -> bool: ...
    def moveToPosition(self, p0: int) -> bool: ...
    def moveToPrevious(self) -> bool: ...
    def requery(self) -> bool: ...
    def respond(self, p0: Bundle) -> Bundle: ...
    def setExtras(self, p0: Bundle) -> None: ...
    def setNotificationUri(self, p0: ContentResolver, p1: Uri) -> None: ...
    def setNotificationUris(self, p0: ContentResolver, p1: list) -> None: ...
    def unregisterContentObserver(self, p0: ContentObserver) -> None: ...
    def getExtras(self) -> Bundle: ...
    def getColumnCount(self) -> int: ...
    def getString(self, p0: int) -> str: ...
    def registerDataSetObserver(self, p0: DataSetObserver) -> None: ...
    def unregisterDataSetObserver(self, p0: DataSetObserver) -> None: ...
    def move(self, p0: int) -> bool: ...
    def getWindow(self) -> CursorWindow: ...

from typing import Any, ClassVar, overload
from android.database.ContentObserver import ContentObserver
from android.database.DataSetObserver import DataSetObserver

class MergeCursor:
    FIELD_TYPE_BLOB: ClassVar[int]
    FIELD_TYPE_FLOAT: ClassVar[int]
    FIELD_TYPE_INTEGER: ClassVar[int]
    FIELD_TYPE_NULL: ClassVar[int]
    FIELD_TYPE_STRING: ClassVar[int]
    def __init__(self, p0: Any) -> None: ...
    def onMove(self, p0: int, p1: int) -> bool: ...
    def isNull(self, p0: int) -> bool: ...
    def getShort(self, p0: int) -> int: ...
    def getInt(self, p0: int) -> int: ...
    def getLong(self, p0: int) -> int: ...
    def getFloat(self, p0: int) -> float: ...
    def getDouble(self, p0: int) -> float: ...
    def getCount(self) -> int: ...
    def close(self) -> None: ...
    def getType(self, p0: int) -> int: ...
    def registerContentObserver(self, p0: ContentObserver) -> None: ...
    def deactivate(self) -> None: ...
    def getBlob(self, p0: int) -> Any: ...
    def getColumnNames(self) -> Any: ...
    def requery(self) -> bool: ...
    def unregisterContentObserver(self, p0: ContentObserver) -> None: ...
    def getString(self, p0: int) -> str: ...
    def registerDataSetObserver(self, p0: DataSetObserver) -> None: ...
    def unregisterDataSetObserver(self, p0: DataSetObserver) -> None: ...

from typing import Any, ClassVar, overload

class CursorIndexOutOfBoundsException:
    @overload
    def __init__(self, p0: int, p1: int) -> None: ...
    @overload
    def __init__(self, p0: str) -> None: ...

from typing import Any, ClassVar, overload
from android.database.CharArrayBuffer import CharArrayBuffer
from android.database.CursorWindow import CursorWindow

class AbstractWindowedCursor:
    FIELD_TYPE_BLOB: ClassVar[int]
    FIELD_TYPE_FLOAT: ClassVar[int]
    FIELD_TYPE_INTEGER: ClassVar[int]
    FIELD_TYPE_NULL: ClassVar[int]
    FIELD_TYPE_STRING: ClassVar[int]
    def __init__(self) -> None: ...
    def isBlob(self, p0: int) -> bool: ...
    def isLong(self, p0: int) -> bool: ...
    def hasWindow(self) -> bool: ...
    def setWindow(self, p0: CursorWindow) -> None: ...
    def isNull(self, p0: int) -> bool: ...
    def getShort(self, p0: int) -> int: ...
    def getInt(self, p0: int) -> int: ...
    def getLong(self, p0: int) -> int: ...
    def getFloat(self, p0: int) -> float: ...
    def getDouble(self, p0: int) -> float: ...
    def getType(self, p0: int) -> int: ...
    def copyStringToBuffer(self, p0: int, p1: CharArrayBuffer) -> None: ...
    def getBlob(self, p0: int) -> Any: ...
    def isFloat(self, p0: int) -> bool: ...
    def isString(self, p0: int) -> bool: ...
    def getString(self, p0: int) -> str: ...
    def getWindow(self) -> CursorWindow: ...

from typing import Any, ClassVar, overload
from android.database.sqlite.SQLiteDatabase import SQLiteDatabase

class DatabaseErrorHandler:
    def onCorruption(self, p0: SQLiteDatabase) -> None: ...

from typing import Any, ClassVar, overload
from android.content.ContentValues import ContentValues
from android.content.Context import Context
from android.database.Cursor import Cursor
from android.database.sqlite.SQLiteDatabase import SQLiteDatabase
from android.database.sqlite.SQLiteProgram import SQLiteProgram
from android.database.sqlite.SQLiteStatement import SQLiteStatement
from android.os.Parcel import Parcel
from android.os.ParcelFileDescriptor import ParcelFileDescriptor
from java.io.PrintStream import PrintStream
from java.lang.Exception import Exception
from java.lang.StringBuilder import StringBuilder

class DatabaseUtils:
    STATEMENT_ABORT: ClassVar[int]
    STATEMENT_ATTACH: ClassVar[int]
    STATEMENT_BEGIN: ClassVar[int]
    STATEMENT_COMMIT: ClassVar[int]
    STATEMENT_DDL: ClassVar[int]
    STATEMENT_OTHER: ClassVar[int]
    STATEMENT_PRAGMA: ClassVar[int]
    STATEMENT_SELECT: ClassVar[int]
    STATEMENT_UNPREPARED: ClassVar[int]
    STATEMENT_UPDATE: ClassVar[int]
    def __init__(self) -> None: ...
    @overload
    @staticmethod
    def blobFileDescriptorForQuery(p0: SQLiteDatabase, p1: str, p2: Any) -> ParcelFileDescriptor: ...
    @overload
    @staticmethod
    def blobFileDescriptorForQuery(p0: SQLiteStatement, p1: Any) -> ParcelFileDescriptor: ...
    @staticmethod
    def appendEscapedSQLString(p0: StringBuilder, p1: str) -> None: ...
    @staticmethod
    def appendSelectionArgs(p0: Any, p1: Any) -> Any: ...
    @staticmethod
    def appendValueToSql(p0: StringBuilder, p1: Any) -> None: ...
    @staticmethod
    def bindObjectToProgram(p0: SQLiteProgram, p1: int, p2: Any) -> None: ...
    @staticmethod
    def concatenateWhere(p0: str, p1: str) -> str: ...
    @staticmethod
    def createDbFromSqlStatements(p0: Context, p1: str, p2: int, p3: str) -> None: ...
    @staticmethod
    def cursorDoubleToContentValues(p0: Cursor, p1: str, p2: ContentValues, p3: str) -> None: ...
    @staticmethod
    def cursorDoubleToContentValuesIfPresent(p0: Cursor, p1: ContentValues, p2: str) -> None: ...
    @staticmethod
    def cursorDoubleToCursorValues(p0: Cursor, p1: str, p2: ContentValues) -> None: ...
    @staticmethod
    def cursorFloatToContentValuesIfPresent(p0: Cursor, p1: ContentValues, p2: str) -> None: ...
    @overload
    @staticmethod
    def cursorIntToContentValues(p0: Cursor, p1: str, p2: ContentValues, p3: str) -> None: ...
    @overload
    @staticmethod
    def cursorIntToContentValues(p0: Cursor, p1: str, p2: ContentValues) -> None: ...
    @staticmethod
    def cursorIntToContentValuesIfPresent(p0: Cursor, p1: ContentValues, p2: str) -> None: ...
    @overload
    @staticmethod
    def cursorLongToContentValues(p0: Cursor, p1: str, p2: ContentValues) -> None: ...
    @overload
    @staticmethod
    def cursorLongToContentValues(p0: Cursor, p1: str, p2: ContentValues, p3: str) -> None: ...
    @staticmethod
    def cursorLongToContentValuesIfPresent(p0: Cursor, p1: ContentValues, p2: str) -> None: ...
    @staticmethod
    def cursorRowToContentValues(p0: Cursor, p1: ContentValues) -> None: ...
    @staticmethod
    def cursorShortToContentValuesIfPresent(p0: Cursor, p1: ContentValues, p2: str) -> None: ...
    @overload
    @staticmethod
    def cursorStringToContentValues(p0: Cursor, p1: str, p2: ContentValues) -> None: ...
    @overload
    @staticmethod
    def cursorStringToContentValues(p0: Cursor, p1: str, p2: ContentValues, p3: str) -> None: ...
    @staticmethod
    def cursorStringToContentValuesIfPresent(p0: Cursor, p1: ContentValues, p2: str) -> None: ...
    @staticmethod
    def cursorStringToInsertHelper(p0: Cursor, p1: str, p2: Any, p3: int) -> None: ...
    @overload
    @staticmethod
    def dumpCurrentRow(p0: Cursor, p1: PrintStream) -> None: ...
    @overload
    @staticmethod
    def dumpCurrentRow(p0: Cursor) -> None: ...
    @overload
    @staticmethod
    def dumpCurrentRow(p0: Cursor, p1: StringBuilder) -> None: ...
    @staticmethod
    def dumpCurrentRowToString(p0: Cursor) -> str: ...
    @overload
    @staticmethod
    def dumpCursor(p0: Cursor, p1: StringBuilder) -> None: ...
    @overload
    @staticmethod
    def dumpCursor(p0: Cursor, p1: PrintStream) -> None: ...
    @overload
    @staticmethod
    def dumpCursor(p0: Cursor) -> None: ...
    @staticmethod
    def dumpCursorToString(p0: Cursor) -> str: ...
    @staticmethod
    def getCollationKey(p0: str) -> str: ...
    @staticmethod
    def getHexCollationKey(p0: str) -> str: ...
    @staticmethod
    def getSqlStatementType(p0: str) -> int: ...
    @overload
    @staticmethod
    def longForQuery(p0: SQLiteStatement, p1: Any) -> int: ...
    @overload
    @staticmethod
    def longForQuery(p0: SQLiteDatabase, p1: str, p2: Any) -> int: ...
    @overload
    @staticmethod
    def queryNumEntries(p0: SQLiteDatabase, p1: str) -> int: ...
    @overload
    @staticmethod
    def queryNumEntries(p0: SQLiteDatabase, p1: str, p2: str) -> int: ...
    @overload
    @staticmethod
    def queryNumEntries(p0: SQLiteDatabase, p1: str, p2: str, p3: Any) -> int: ...
    @staticmethod
    def readExceptionFromParcel(p0: Parcel) -> None: ...
    @staticmethod
    def readExceptionWithFileNotFoundExceptionFromParcel(p0: Parcel) -> None: ...
    @staticmethod
    def readExceptionWithOperationApplicationExceptionFromParcel(p0: Parcel) -> None: ...
    @staticmethod
    def sqlEscapeString(p0: str) -> str: ...
    @overload
    @staticmethod
    def stringForQuery(p0: SQLiteDatabase, p1: str, p2: Any) -> str: ...
    @overload
    @staticmethod
    def stringForQuery(p0: SQLiteStatement, p1: Any) -> str: ...
    @staticmethod
    def writeExceptionToParcel(p0: Parcel, p1: Exception) -> None: ...

    class InsertHelper:
        def __init__(self, p0: SQLiteDatabase, p1: str) -> None: ...
        def bindNull(self, p0: int) -> None: ...
        def prepareForInsert(self) -> None: ...
        def prepareForReplace(self) -> None: ...
        def insert(self, p0: ContentValues) -> int: ...
        def replace(self, p0: ContentValues) -> int: ...
        def execute(self) -> int: ...
        def close(self) -> None: ...
        def getColumnIndex(self, p0: str) -> int: ...
        @overload
        def bind(self, p0: int, p1: int) -> None: ...
        @overload
        def bind(self, p0: int, p1: Any) -> None: ...
        @overload
        def bind(self, p0: int, p1: bool) -> None: ...
        @overload
        def bind(self, p0: int, p1: float) -> None: ...
        @overload
        def bind(self, p0: int, p1: int) -> None: ...
        @overload
        def bind(self, p0: int, p1: str) -> None: ...
        @overload
        def bind(self, p0: int, p1: float) -> None: ...

from typing import Any, ClassVar, overload
from android.database.ContentObserver import ContentObserver
from android.net.Uri import Uri

class ContentObservable:
    def __init__(self) -> None: ...
    def notifyChange(self, p0: bool) -> None: ...
    @overload
    def dispatchChange(self, p0: bool, p1: Uri) -> None: ...
    @overload
    def dispatchChange(self, p0: bool) -> None: ...
    @overload
    def registerObserver(self, p0: ContentObserver) -> None: ...
    @overload
    def registerObserver(self, p0: Any) -> None: ...

from typing import Any, ClassVar, overload
from android.content.ContentResolver import ContentResolver
from android.database.CharArrayBuffer import CharArrayBuffer
from android.database.ContentObserver import ContentObserver
from android.database.Cursor import Cursor
from android.database.DataSetObserver import DataSetObserver
from android.net.Uri import Uri
from android.os.Bundle import Bundle

class CursorWrapper:
    FIELD_TYPE_BLOB: ClassVar[int]
    FIELD_TYPE_FLOAT: ClassVar[int]
    FIELD_TYPE_INTEGER: ClassVar[int]
    FIELD_TYPE_NULL: ClassVar[int]
    FIELD_TYPE_STRING: ClassVar[int]
    def __init__(self, p0: Cursor) -> None: ...
    def getWrappedCursor(self) -> Cursor: ...
    def isNull(self, p0: int) -> bool: ...
    def getShort(self, p0: int) -> int: ...
    def getInt(self, p0: int) -> int: ...
    def getLong(self, p0: int) -> int: ...
    def getFloat(self, p0: int) -> float: ...
    def getDouble(self, p0: int) -> float: ...
    def getCount(self) -> int: ...
    def close(self) -> None: ...
    def getType(self, p0: int) -> int: ...
    def isLast(self) -> bool: ...
    def registerContentObserver(self, p0: ContentObserver) -> None: ...
    def copyStringToBuffer(self, p0: int, p1: CharArrayBuffer) -> None: ...
    def deactivate(self) -> None: ...
    def getBlob(self, p0: int) -> Any: ...
    def getColumnIndex(self, p0: str) -> int: ...
    def getColumnIndexOrThrow(self, p0: str) -> int: ...
    def getColumnName(self, p0: int) -> str: ...
    def getColumnNames(self) -> Any: ...
    def getNotificationUri(self) -> Uri: ...
    def getNotificationUris(self) -> list: ...
    def getPosition(self) -> int: ...
    def getWantsAllOnMoveCalls(self) -> bool: ...
    def isAfterLast(self) -> bool: ...
    def isBeforeFirst(self) -> bool: ...
    def isClosed(self) -> bool: ...
    def isFirst(self) -> bool: ...
    def moveToFirst(self) -> bool: ...
    def moveToLast(self) -> bool: ...
    def moveToNext(self) -> bool: ...
    def moveToPosition(self, p0: int) -> bool: ...
    def moveToPrevious(self) -> bool: ...
    def requery(self) -> bool: ...
    def respond(self, p0: Bundle) -> Bundle: ...
    def setExtras(self, p0: Bundle) -> None: ...
    def setNotificationUri(self, p0: ContentResolver, p1: Uri) -> None: ...
    def setNotificationUris(self, p0: ContentResolver, p1: list) -> None: ...
    def unregisterContentObserver(self, p0: ContentObserver) -> None: ...
    def getExtras(self) -> Bundle: ...
    def getColumnCount(self) -> int: ...
    def getString(self, p0: int) -> str: ...
    def registerDataSetObserver(self, p0: DataSetObserver) -> None: ...
    def unregisterDataSetObserver(self, p0: DataSetObserver) -> None: ...
    def move(self, p0: int) -> bool: ...

from typing import Any, ClassVar, overload
from android.database.Cursor import Cursor
from android.database.CursorWindow import CursorWindow

class CrossProcessCursorWrapper:
    FIELD_TYPE_BLOB: ClassVar[int]
    FIELD_TYPE_FLOAT: ClassVar[int]
    FIELD_TYPE_INTEGER: ClassVar[int]
    FIELD_TYPE_NULL: ClassVar[int]
    FIELD_TYPE_STRING: ClassVar[int]
    def __init__(self, p0: Cursor) -> None: ...
    def onMove(self, p0: int, p1: int) -> bool: ...
    def fillWindow(self, p0: int, p1: CursorWindow) -> None: ...
    def getWindow(self) -> CursorWindow: ...

from typing import Any, ClassVar, overload

class CharArrayBuffer:
    data: Any
    sizeCopied: int
    @overload
    def __init__(self, p0: Any) -> None: ...
    @overload
    def __init__(self, p0: int) -> None: ...

from typing import Any, ClassVar, overload

class DataSetObserver:
    def __init__(self) -> None: ...
    def onInvalidated(self) -> None: ...
    def onChanged(self) -> None: ...

from typing import Any, ClassVar, overload
from android.content.ContentResolver import ContentResolver
from android.database.CharArrayBuffer import CharArrayBuffer
from android.database.ContentObserver import ContentObserver
from android.database.DataSetObserver import DataSetObserver
from android.net.Uri import Uri
from android.os.Bundle import Bundle

class Cursor:
    FIELD_TYPE_BLOB: ClassVar[int]
    FIELD_TYPE_FLOAT: ClassVar[int]
    FIELD_TYPE_INTEGER: ClassVar[int]
    FIELD_TYPE_NULL: ClassVar[int]
    FIELD_TYPE_STRING: ClassVar[int]
    def isNull(self, p0: int) -> bool: ...
    def getShort(self, p0: int) -> int: ...
    def getInt(self, p0: int) -> int: ...
    def getLong(self, p0: int) -> int: ...
    def getFloat(self, p0: int) -> float: ...
    def getDouble(self, p0: int) -> float: ...
    def getCount(self) -> int: ...
    def close(self) -> None: ...
    def getType(self, p0: int) -> int: ...
    def isLast(self) -> bool: ...
    def registerContentObserver(self, p0: ContentObserver) -> None: ...
    def copyStringToBuffer(self, p0: int, p1: CharArrayBuffer) -> None: ...
    def deactivate(self) -> None: ...
    def getBlob(self, p0: int) -> Any: ...
    def getColumnIndex(self, p0: str) -> int: ...
    def getColumnIndexOrThrow(self, p0: str) -> int: ...
    def getColumnName(self, p0: int) -> str: ...
    def getColumnNames(self) -> Any: ...
    def getNotificationUri(self) -> Uri: ...
    def getNotificationUris(self) -> list: ...
    def getPosition(self) -> int: ...
    def getWantsAllOnMoveCalls(self) -> bool: ...
    def isAfterLast(self) -> bool: ...
    def isBeforeFirst(self) -> bool: ...
    def isClosed(self) -> bool: ...
    def isFirst(self) -> bool: ...
    def moveToFirst(self) -> bool: ...
    def moveToLast(self) -> bool: ...
    def moveToNext(self) -> bool: ...
    def moveToPosition(self, p0: int) -> bool: ...
    def moveToPrevious(self) -> bool: ...
    def requery(self) -> bool: ...
    def respond(self, p0: Bundle) -> Bundle: ...
    def setExtras(self, p0: Bundle) -> None: ...
    def setNotificationUri(self, p0: ContentResolver, p1: Uri) -> None: ...
    def setNotificationUris(self, p0: ContentResolver, p1: list) -> None: ...
    def unregisterContentObserver(self, p0: ContentObserver) -> None: ...
    def getExtras(self) -> Bundle: ...
    def getColumnCount(self) -> int: ...
    def getString(self, p0: int) -> str: ...
    def registerDataSetObserver(self, p0: DataSetObserver) -> None: ...
    def unregisterDataSetObserver(self, p0: DataSetObserver) -> None: ...
    def move(self, p0: int) -> bool: ...

from typing import Any, ClassVar, overload

class CursorWindowAllocationException:
    def __init__(self, p0: str) -> None: ...

from typing import Any, ClassVar, overload
from android.net.Uri import Uri
from android.os.Handler import Handler

class ContentObserver:
    def __init__(self, p0: Handler) -> None: ...
    @overload
    def onChange(self, p0: bool) -> None: ...
    @overload
    def onChange(self, p0: bool, p1: Uri) -> None: ...
    @overload
    def onChange(self, p0: bool, p1: Uri, p2: int) -> None: ...
    @overload
    def onChange(self, p0: bool, p1: list, p2: int) -> None: ...
    @overload
    def dispatchChange(self, p0: bool, p1: list, p2: int) -> None: ...
    @overload
    def dispatchChange(self, p0: bool) -> None: ...
    @overload
    def dispatchChange(self, p0: bool, p1: Uri) -> None: ...
    @overload
    def dispatchChange(self, p0: bool, p1: Uri, p2: int) -> None: ...
    def deliverSelfNotifications(self) -> bool: ...

