from typing import Any, ClassVar, overload
from android.hardware.usb.UsbDevice import UsbDevice
from android.hardware.usb.UsbDeviceConnection import UsbDeviceConnection
from android.mtp.MtpDeviceInfo import MtpDeviceInfo
from android.mtp.MtpEvent import MtpEvent
from android.mtp.MtpObjectInfo import MtpObjectInfo
from android.mtp.MtpStorageInfo import MtpStorageInfo
from android.os.CancellationSignal import CancellationSignal
from android.os.ParcelFileDescriptor import ParcelFileDescriptor

class MtpDevice:
    def __init__(self, p0: UsbDevice) -> None: ...
    def getDeviceName(self) -> str: ...
    def getThumbnail(self, p0: int) -> Any: ...
    def getStorageInfo(self, p0: int) -> MtpStorageInfo: ...
    def deleteObject(self, p0: int) -> bool: ...
    def getDeviceInfo(self) -> MtpDeviceInfo: ...
    def getObjectHandles(self, p0: int, p1: int, p2: int) -> Any: ...
    def getObjectInfo(self, p0: int) -> MtpObjectInfo: ...
    def getPartialObject(self, p0: int, p1: int, p2: int, p3: Any) -> int: ...
    def getPartialObject64(self, p0: int, p1: int, p2: int, p3: Any) -> int: ...
    def getStorageId(self, p0: int) -> int: ...
    def getStorageIds(self) -> Any: ...
    @overload
    def importFile(self, p0: int, p1: str) -> bool: ...
    @overload
    def importFile(self, p0: int, p1: ParcelFileDescriptor) -> bool: ...
    def readEvent(self, p0: CancellationSignal) -> MtpEvent: ...
    def sendObject(self, p0: int, p1: int, p2: ParcelFileDescriptor) -> bool: ...
    def sendObjectInfo(self, p0: MtpObjectInfo) -> MtpObjectInfo: ...
    def toString(self) -> str: ...
    def getParent(self, p0: int) -> int: ...
    def close(self) -> None: ...
    def open(self, p0: UsbDeviceConnection) -> bool: ...
    def getDeviceId(self) -> int: ...
    def getObject(self, p0: int, p1: int) -> Any: ...

from typing import Any, ClassVar, overload

class MtpStorageInfo:
    def getStorageId(self) -> int: ...
    def getVolumeIdentifier(self) -> str: ...
    def getMaxCapacity(self) -> int: ...
    def getDescription(self) -> str: ...
    def getFreeSpace(self) -> int: ...

from typing import Any, ClassVar, overload

class MtpConstants:
    ASSOCIATION_TYPE_GENERIC_FOLDER: ClassVar[int]
    FORMAT_3GP_CONTAINER: ClassVar[int]
    FORMAT_AAC: ClassVar[int]
    FORMAT_ABSTRACT_AUDIO_ALBUM: ClassVar[int]
    FORMAT_ABSTRACT_AUDIO_PLAYLIST: ClassVar[int]
    FORMAT_ABSTRACT_AV_PLAYLIST: ClassVar[int]
    FORMAT_ABSTRACT_DOCUMENT: ClassVar[int]
    FORMAT_ABSTRACT_IMAGE_ALBUM: ClassVar[int]
    FORMAT_ABSTRACT_MEDIACAST: ClassVar[int]
    FORMAT_ABSTRACT_MULTIMEDIA_ALBUM: ClassVar[int]
    FORMAT_ABSTRACT_VIDEO_ALBUM: ClassVar[int]
    FORMAT_ABSTRACT_VIDEO_PLAYLIST: ClassVar[int]
    FORMAT_AIFF: ClassVar[int]
    FORMAT_ASF: ClassVar[int]
    FORMAT_ASSOCIATION: ClassVar[int]
    FORMAT_ASX_PLAYLIST: ClassVar[int]
    FORMAT_AUDIBLE: ClassVar[int]
    FORMAT_AVI: ClassVar[int]
    FORMAT_BMP: ClassVar[int]
    FORMAT_DEFINED: ClassVar[int]
    FORMAT_DNG: ClassVar[int]
    FORMAT_DPOF: ClassVar[int]
    FORMAT_EXECUTABLE: ClassVar[int]
    FORMAT_EXIF_JPEG: ClassVar[int]
    FORMAT_FLAC: ClassVar[int]
    FORMAT_GIF: ClassVar[int]
    FORMAT_HTML: ClassVar[int]
    FORMAT_JFIF: ClassVar[int]
    FORMAT_JP2: ClassVar[int]
    FORMAT_JPX: ClassVar[int]
    FORMAT_M3U_PLAYLIST: ClassVar[int]
    FORMAT_MP2: ClassVar[int]
    FORMAT_MP3: ClassVar[int]
    FORMAT_MP4_CONTAINER: ClassVar[int]
    FORMAT_MPEG: ClassVar[int]
    FORMAT_MPL_PLAYLIST: ClassVar[int]
    FORMAT_MS_EXCEL_SPREADSHEET: ClassVar[int]
    FORMAT_MS_POWERPOINT_PRESENTATION: ClassVar[int]
    FORMAT_MS_WORD_DOCUMENT: ClassVar[int]
    FORMAT_OGG: ClassVar[int]
    FORMAT_PICT: ClassVar[int]
    FORMAT_PLS_PLAYLIST: ClassVar[int]
    FORMAT_PNG: ClassVar[int]
    FORMAT_SCRIPT: ClassVar[int]
    FORMAT_TEXT: ClassVar[int]
    FORMAT_TIFF: ClassVar[int]
    FORMAT_TIFF_EP: ClassVar[int]
    FORMAT_UNDEFINED: ClassVar[int]
    FORMAT_UNDEFINED_AUDIO: ClassVar[int]
    FORMAT_UNDEFINED_COLLECTION: ClassVar[int]
    FORMAT_UNDEFINED_DOCUMENT: ClassVar[int]
    FORMAT_UNDEFINED_FIRMWARE: ClassVar[int]
    FORMAT_UNDEFINED_VIDEO: ClassVar[int]
    FORMAT_WAV: ClassVar[int]
    FORMAT_WINDOWS_IMAGE_FORMAT: ClassVar[int]
    FORMAT_WMA: ClassVar[int]
    FORMAT_WMV: ClassVar[int]
    FORMAT_WPL_PLAYLIST: ClassVar[int]
    FORMAT_XML_DOCUMENT: ClassVar[int]
    OPERATION_CLOSE_SESSION: ClassVar[int]
    OPERATION_COPY_OBJECT: ClassVar[int]
    OPERATION_DELETE_OBJECT: ClassVar[int]
    OPERATION_FORMAT_STORE: ClassVar[int]
    OPERATION_GET_DEVICE_INFO: ClassVar[int]
    OPERATION_GET_DEVICE_PROP_DESC: ClassVar[int]
    OPERATION_GET_DEVICE_PROP_VALUE: ClassVar[int]
    OPERATION_GET_NUM_OBJECTS: ClassVar[int]
    OPERATION_GET_OBJECT: ClassVar[int]
    OPERATION_GET_OBJECT_HANDLES: ClassVar[int]
    OPERATION_GET_OBJECT_INFO: ClassVar[int]
    OPERATION_GET_OBJECT_PROPS_SUPPORTED: ClassVar[int]
    OPERATION_GET_OBJECT_PROP_DESC: ClassVar[int]
    OPERATION_GET_OBJECT_PROP_VALUE: ClassVar[int]
    OPERATION_GET_OBJECT_REFERENCES: ClassVar[int]
    OPERATION_GET_PARTIAL_OBJECT: ClassVar[int]
    OPERATION_GET_PARTIAL_OBJECT_64: ClassVar[int]
    OPERATION_GET_STORAGE_INFO: ClassVar[int]
    OPERATION_GET_STORAGE_I_DS: ClassVar[int]
    OPERATION_GET_THUMB: ClassVar[int]
    OPERATION_INITIATE_CAPTURE: ClassVar[int]
    OPERATION_INITIATE_OPEN_CAPTURE: ClassVar[int]
    OPERATION_MOVE_OBJECT: ClassVar[int]
    OPERATION_OPEN_SESSION: ClassVar[int]
    OPERATION_POWER_DOWN: ClassVar[int]
    OPERATION_RESET_DEVICE: ClassVar[int]
    OPERATION_RESET_DEVICE_PROP_VALUE: ClassVar[int]
    OPERATION_SELF_TEST: ClassVar[int]
    OPERATION_SEND_OBJECT: ClassVar[int]
    OPERATION_SEND_OBJECT_INFO: ClassVar[int]
    OPERATION_SET_DEVICE_PROP_VALUE: ClassVar[int]
    OPERATION_SET_OBJECT_PROP_VALUE: ClassVar[int]
    OPERATION_SET_OBJECT_PROTECTION: ClassVar[int]
    OPERATION_SET_OBJECT_REFERENCES: ClassVar[int]
    OPERATION_SKIP: ClassVar[int]
    OPERATION_TERMINATE_OPEN_CAPTURE: ClassVar[int]
    PROTECTION_STATUS_NONE: ClassVar[int]
    PROTECTION_STATUS_NON_TRANSFERABLE_DATA: ClassVar[int]
    PROTECTION_STATUS_READ_ONLY: ClassVar[int]
    PROTECTION_STATUS_READ_ONLY_DATA: ClassVar[int]
    def __init__(self) -> None: ...
    @staticmethod
    def isAbstractObject(p0: int) -> bool: ...

from typing import Any, ClassVar, overload

class MtpObjectInfo:
    def getKeywords(self) -> str: ...
    def getStorageId(self) -> int: ...
    def getAssociationDesc(self) -> int: ...
    def getAssociationType(self) -> int: ...
    def getCompressedSizeLong(self) -> int: ...
    def getDateCreated(self) -> int: ...
    def getDateModified(self) -> int: ...
    def getImagePixDepth(self) -> int: ...
    def getImagePixDepthLong(self) -> int: ...
    def getImagePixHeight(self) -> int: ...
    def getImagePixHeightLong(self) -> int: ...
    def getImagePixWidth(self) -> int: ...
    def getImagePixWidthLong(self) -> int: ...
    def getObjectHandle(self) -> int: ...
    def getProtectionStatus(self) -> int: ...
    def getSequenceNumberLong(self) -> int: ...
    def getThumbCompressedSize(self) -> int: ...
    def getThumbFormat(self) -> int: ...
    def getThumbPixHeight(self) -> int: ...
    def getThumbPixHeightLong(self) -> int: ...
    def getThumbPixWidth(self) -> int: ...
    def getThumbPixWidthLong(self) -> int: ...
    def getThumbCompressedSizeLong(self) -> int: ...
    def getCompressedSize(self) -> int: ...
    def getName(self) -> str: ...
    def getParent(self) -> int: ...
    def getSequenceNumber(self) -> int: ...
    def getFormat(self) -> int: ...

    class Builder:
        @overload
        def __init__(self, p0: "MtpObjectInfo") -> None: ...
        @overload
        def __init__(self) -> None: ...
        def setAssociationDesc(self, p0: int) -> Any: ...
        def setAssociationType(self, p0: int) -> Any: ...
        def setDateCreated(self, p0: int) -> Any: ...
        def setDateModified(self, p0: int) -> Any: ...
        def setImagePixDepth(self, p0: int) -> Any: ...
        def setImagePixHeight(self, p0: int) -> Any: ...
        def setImagePixWidth(self, p0: int) -> Any: ...
        def setKeywords(self, p0: str) -> Any: ...
        def setObjectHandle(self, p0: int) -> Any: ...
        def setProtectionStatus(self, p0: int) -> Any: ...
        def setSequenceNumber(self, p0: int) -> Any: ...
        def setStorageId(self, p0: int) -> Any: ...
        def setThumbCompressedSize(self, p0: int) -> Any: ...
        def setThumbFormat(self, p0: int) -> Any: ...
        def setThumbPixHeight(self, p0: int) -> Any: ...
        def setThumbPixWidth(self, p0: int) -> Any: ...
        def setCompressedSize(self, p0: int) -> Any: ...
        def setName(self, p0: str) -> Any: ...
        def setFormat(self, p0: int) -> Any: ...
        def build(self) -> "MtpObjectInfo": ...
        def setParent(self, p0: int) -> Any: ...

from typing import Any, ClassVar, overload

class MtpEvent:
    EVENT_CANCEL_TRANSACTION: ClassVar[int]
    EVENT_CAPTURE_COMPLETE: ClassVar[int]
    EVENT_DEVICE_INFO_CHANGED: ClassVar[int]
    EVENT_DEVICE_PROP_CHANGED: ClassVar[int]
    EVENT_DEVICE_RESET: ClassVar[int]
    EVENT_OBJECT_ADDED: ClassVar[int]
    EVENT_OBJECT_INFO_CHANGED: ClassVar[int]
    EVENT_OBJECT_PROP_CHANGED: ClassVar[int]
    EVENT_OBJECT_PROP_DESC_CHANGED: ClassVar[int]
    EVENT_OBJECT_REFERENCES_CHANGED: ClassVar[int]
    EVENT_OBJECT_REMOVED: ClassVar[int]
    EVENT_REQUEST_OBJECT_TRANSFER: ClassVar[int]
    EVENT_STORAGE_INFO_CHANGED: ClassVar[int]
    EVENT_STORE_ADDED: ClassVar[int]
    EVENT_STORE_FULL: ClassVar[int]
    EVENT_STORE_REMOVED: ClassVar[int]
    EVENT_UNDEFINED: ClassVar[int]
    EVENT_UNREPORTED_STATUS: ClassVar[int]
    def getStorageId(self) -> int: ...
    def getObjectHandle(self) -> int: ...
    def getDevicePropCode(self) -> int: ...
    def getEventCode(self) -> int: ...
    def getObjectFormatCode(self) -> int: ...
    def getObjectPropCode(self) -> int: ...
    def getParameter1(self) -> int: ...
    def getParameter2(self) -> int: ...
    def getParameter3(self) -> int: ...
    def getTransactionId(self) -> int: ...

from typing import Any, ClassVar, overload

class MtpDeviceInfo:
    def getEventsSupported(self) -> Any: ...
    def getOperationsSupported(self) -> Any: ...
    def isEventSupported(self, p0: int) -> bool: ...
    def isOperationSupported(self, p0: int) -> bool: ...
    def getVersion(self) -> str: ...
    def getManufacturer(self) -> str: ...
    def getModel(self) -> str: ...
    def getSerialNumber(self) -> str: ...

