from jnius import JavaClass, JavaInterface, MetaJavaClass, JavaMethod, JavaStaticMethod, JavaMultipleMethod, JavaField, JavaStaticField

class VpnService(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "android/net/VpnService"
    __javaconstructor__ = [("()V", False)]
    SERVICE_INTERFACE = JavaStaticField("Ljava/lang/String;")
    SERVICE_META_DATA_SUPPORTS_ALWAYS_ON = JavaStaticField("Ljava/lang/String;")
    START_CONTINUATION_MASK = JavaStaticField("I")
    START_FLAG_REDELIVERY = JavaStaticField("I")
    START_FLAG_RETRY = JavaStaticField("I")
    START_NOT_STICKY = JavaStaticField("I")
    START_REDELIVER_INTENT = JavaStaticField("I")
    START_STICKY = JavaStaticField("I")
    START_STICKY_COMPATIBILITY = JavaStaticField("I")
    STOP_FOREGROUND_DETACH = JavaStaticField("I")
    STOP_FOREGROUND_LEGACY = JavaStaticField("I")
    STOP_FOREGROUND_REMOVE = JavaStaticField("I")
    TRIM_MEMORY_BACKGROUND = JavaStaticField("I")
    TRIM_MEMORY_COMPLETE = JavaStaticField("I")
    TRIM_MEMORY_MODERATE = JavaStaticField("I")
    TRIM_MEMORY_RUNNING_CRITICAL = JavaStaticField("I")
    TRIM_MEMORY_RUNNING_LOW = JavaStaticField("I")
    TRIM_MEMORY_RUNNING_MODERATE = JavaStaticField("I")
    TRIM_MEMORY_UI_HIDDEN = JavaStaticField("I")
    ACCESSIBILITY_SERVICE = JavaStaticField("Ljava/lang/String;")
    ACCOUNT_SERVICE = JavaStaticField("Ljava/lang/String;")
    ACTIVITY_SERVICE = JavaStaticField("Ljava/lang/String;")
    ADVANCED_PROTECTION_SERVICE = JavaStaticField("Ljava/lang/String;")
    ALARM_SERVICE = JavaStaticField("Ljava/lang/String;")
    APPWIDGET_SERVICE = JavaStaticField("Ljava/lang/String;")
    APP_FUNCTION_SERVICE = JavaStaticField("Ljava/lang/String;")
    APP_OPS_SERVICE = JavaStaticField("Ljava/lang/String;")
    APP_SEARCH_SERVICE = JavaStaticField("Ljava/lang/String;")
    AUDIO_SERVICE = JavaStaticField("Ljava/lang/String;")
    BATTERY_SERVICE = JavaStaticField("Ljava/lang/String;")
    BIND_ABOVE_CLIENT = JavaStaticField("I")
    BIND_ADJUST_WITH_ACTIVITY = JavaStaticField("I")
    BIND_ALLOW_ACTIVITY_STARTS = JavaStaticField("I")
    BIND_ALLOW_OOM_MANAGEMENT = JavaStaticField("I")
    BIND_AUTO_CREATE = JavaStaticField("I")
    BIND_DEBUG_UNBIND = JavaStaticField("I")
    BIND_EXTERNAL_SERVICE = JavaStaticField("I")
    BIND_EXTERNAL_SERVICE_LONG = JavaStaticField("J")
    BIND_IMPORTANT = JavaStaticField("I")
    BIND_INCLUDE_CAPABILITIES = JavaStaticField("I")
    BIND_NOT_FOREGROUND = JavaStaticField("I")
    BIND_NOT_PERCEPTIBLE = JavaStaticField("I")
    BIND_PACKAGE_ISOLATED_PROCESS = JavaStaticField("I")
    BIND_SHARED_ISOLATED_PROCESS = JavaStaticField("I")
    BIND_WAIVE_PRIORITY = JavaStaticField("I")
    BIOMETRIC_SERVICE = JavaStaticField("Ljava/lang/String;")
    BLOB_STORE_SERVICE = JavaStaticField("Ljava/lang/String;")
    BLUETOOTH_SERVICE = JavaStaticField("Ljava/lang/String;")
    BUGREPORT_SERVICE = JavaStaticField("Ljava/lang/String;")
    CAMERA_SERVICE = JavaStaticField("Ljava/lang/String;")
    CAPTIONING_SERVICE = JavaStaticField("Ljava/lang/String;")
    CARRIER_CONFIG_SERVICE = JavaStaticField("Ljava/lang/String;")
    CLIPBOARD_SERVICE = JavaStaticField("Ljava/lang/String;")
    COMPANION_DEVICE_SERVICE = JavaStaticField("Ljava/lang/String;")
    CONNECTIVITY_DIAGNOSTICS_SERVICE = JavaStaticField("Ljava/lang/String;")
    CONNECTIVITY_SERVICE = JavaStaticField("Ljava/lang/String;")
    CONSUMER_IR_SERVICE = JavaStaticField("Ljava/lang/String;")
    CONTACT_KEYS_SERVICE = JavaStaticField("Ljava/lang/String;")
    CONTEXT_IGNORE_SECURITY = JavaStaticField("I")
    CONTEXT_INCLUDE_CODE = JavaStaticField("I")
    CONTEXT_RESTRICTED = JavaStaticField("I")
    CREDENTIAL_SERVICE = JavaStaticField("Ljava/lang/String;")
    CROSS_PROFILE_APPS_SERVICE = JavaStaticField("Ljava/lang/String;")
    DEVICE_ID_DEFAULT = JavaStaticField("I")
    DEVICE_ID_INVALID = JavaStaticField("I")
    DEVICE_LOCK_SERVICE = JavaStaticField("Ljava/lang/String;")
    DEVICE_POLICY_SERVICE = JavaStaticField("Ljava/lang/String;")
    DISPLAY_HASH_SERVICE = JavaStaticField("Ljava/lang/String;")
    DISPLAY_SERVICE = JavaStaticField("Ljava/lang/String;")
    DOMAIN_VERIFICATION_SERVICE = JavaStaticField("Ljava/lang/String;")
    DOWNLOAD_SERVICE = JavaStaticField("Ljava/lang/String;")
    DROPBOX_SERVICE = JavaStaticField("Ljava/lang/String;")
    EUICC_SERVICE = JavaStaticField("Ljava/lang/String;")
    FILE_INTEGRITY_SERVICE = JavaStaticField("Ljava/lang/String;")
    FINGERPRINT_SERVICE = JavaStaticField("Ljava/lang/String;")
    GAME_SERVICE = JavaStaticField("Ljava/lang/String;")
    GRAMMATICAL_INFLECTION_SERVICE = JavaStaticField("Ljava/lang/String;")
    HARDWARE_PROPERTIES_SERVICE = JavaStaticField("Ljava/lang/String;")
    HEALTHCONNECT_SERVICE = JavaStaticField("Ljava/lang/String;")
    INPUT_METHOD_SERVICE = JavaStaticField("Ljava/lang/String;")
    INPUT_SERVICE = JavaStaticField("Ljava/lang/String;")
    IPSEC_SERVICE = JavaStaticField("Ljava/lang/String;")
    JOB_SCHEDULER_SERVICE = JavaStaticField("Ljava/lang/String;")
    KEYGUARD_SERVICE = JavaStaticField("Ljava/lang/String;")
    KEYSTORE_SERVICE = JavaStaticField("Ljava/lang/String;")
    LAUNCHER_APPS_SERVICE = JavaStaticField("Ljava/lang/String;")
    LAYOUT_INFLATER_SERVICE = JavaStaticField("Ljava/lang/String;")
    LOCALE_SERVICE = JavaStaticField("Ljava/lang/String;")
    LOCATION_SERVICE = JavaStaticField("Ljava/lang/String;")
    MEDIA_COMMUNICATION_SERVICE = JavaStaticField("Ljava/lang/String;")
    MEDIA_METRICS_SERVICE = JavaStaticField("Ljava/lang/String;")
    MEDIA_PROJECTION_SERVICE = JavaStaticField("Ljava/lang/String;")
    MEDIA_QUALITY_SERVICE = JavaStaticField("Ljava/lang/String;")
    MEDIA_ROUTER_SERVICE = JavaStaticField("Ljava/lang/String;")
    MEDIA_SESSION_SERVICE = JavaStaticField("Ljava/lang/String;")
    MIDI_SERVICE = JavaStaticField("Ljava/lang/String;")
    MODE_APPEND = JavaStaticField("I")
    MODE_ENABLE_WRITE_AHEAD_LOGGING = JavaStaticField("I")
    MODE_MULTI_PROCESS = JavaStaticField("I")
    MODE_NO_LOCALIZED_COLLATORS = JavaStaticField("I")
    MODE_PRIVATE = JavaStaticField("I")
    MODE_WORLD_READABLE = JavaStaticField("I")
    MODE_WORLD_WRITEABLE = JavaStaticField("I")
    NETWORK_STATS_SERVICE = JavaStaticField("Ljava/lang/String;")
    NFC_SERVICE = JavaStaticField("Ljava/lang/String;")
    NOTIFICATION_SERVICE = JavaStaticField("Ljava/lang/String;")
    NSD_SERVICE = JavaStaticField("Ljava/lang/String;")
    OVERLAY_SERVICE = JavaStaticField("Ljava/lang/String;")
    PEOPLE_SERVICE = JavaStaticField("Ljava/lang/String;")
    PERFORMANCE_HINT_SERVICE = JavaStaticField("Ljava/lang/String;")
    PERSISTENT_DATA_BLOCK_SERVICE = JavaStaticField("Ljava/lang/String;")
    POWER_SERVICE = JavaStaticField("Ljava/lang/String;")
    PRINT_SERVICE = JavaStaticField("Ljava/lang/String;")
    PROFILING_SERVICE = JavaStaticField("Ljava/lang/String;")
    RECEIVER_EXPORTED = JavaStaticField("I")
    RECEIVER_NOT_EXPORTED = JavaStaticField("I")
    RECEIVER_VISIBLE_TO_INSTANT_APPS = JavaStaticField("I")
    RESTRICTIONS_SERVICE = JavaStaticField("Ljava/lang/String;")
    ROLE_SERVICE = JavaStaticField("Ljava/lang/String;")
    SATELLITE_SERVICE = JavaStaticField("Ljava/lang/String;")
    SEARCH_SERVICE = JavaStaticField("Ljava/lang/String;")
    SECURITY_STATE_SERVICE = JavaStaticField("Ljava/lang/String;")
    SENSOR_SERVICE = JavaStaticField("Ljava/lang/String;")
    SHORTCUT_SERVICE = JavaStaticField("Ljava/lang/String;")
    STATUS_BAR_SERVICE = JavaStaticField("Ljava/lang/String;")
    STORAGE_SERVICE = JavaStaticField("Ljava/lang/String;")
    STORAGE_STATS_SERVICE = JavaStaticField("Ljava/lang/String;")
    SYSTEM_HEALTH_SERVICE = JavaStaticField("Ljava/lang/String;")
    TELECOM_SERVICE = JavaStaticField("Ljava/lang/String;")
    TELEPHONY_IMS_SERVICE = JavaStaticField("Ljava/lang/String;")
    TELEPHONY_SERVICE = JavaStaticField("Ljava/lang/String;")
    TELEPHONY_SUBSCRIPTION_SERVICE = JavaStaticField("Ljava/lang/String;")
    TETHERING_SERVICE = JavaStaticField("Ljava/lang/String;")
    TEXT_CLASSIFICATION_SERVICE = JavaStaticField("Ljava/lang/String;")
    TEXT_SERVICES_MANAGER_SERVICE = JavaStaticField("Ljava/lang/String;")
    TV_AD_SERVICE = JavaStaticField("Ljava/lang/String;")
    TV_INPUT_SERVICE = JavaStaticField("Ljava/lang/String;")
    TV_INTERACTIVE_APP_SERVICE = JavaStaticField("Ljava/lang/String;")
    UI_MODE_SERVICE = JavaStaticField("Ljava/lang/String;")
    USAGE_STATS_SERVICE = JavaStaticField("Ljava/lang/String;")
    USB_SERVICE = JavaStaticField("Ljava/lang/String;")
    USER_SERVICE = JavaStaticField("Ljava/lang/String;")
    VIBRATOR_MANAGER_SERVICE = JavaStaticField("Ljava/lang/String;")
    VIBRATOR_SERVICE = JavaStaticField("Ljava/lang/String;")
    VIRTUAL_DEVICE_SERVICE = JavaStaticField("Ljava/lang/String;")
    VPN_MANAGEMENT_SERVICE = JavaStaticField("Ljava/lang/String;")
    WALLPAPER_SERVICE = JavaStaticField("Ljava/lang/String;")
    WIFI_AWARE_SERVICE = JavaStaticField("Ljava/lang/String;")
    WIFI_P2P_SERVICE = JavaStaticField("Ljava/lang/String;")
    WIFI_RTT_RANGING_SERVICE = JavaStaticField("Ljava/lang/String;")
    WIFI_SERVICE = JavaStaticField("Ljava/lang/String;")
    WINDOW_SERVICE = JavaStaticField("Ljava/lang/String;")
    isAlwaysOn = JavaMethod("()Z")
    isLockdownEnabled = JavaMethod("()Z")
    onRevoke = JavaMethod("()V")
    protect = JavaMultipleMethod([("(Ljava/net/DatagramSocket;)Z", False, False), ("(I)Z", False, False), ("(Ljava/net/Socket;)Z", False, False)])
    setUnderlyingNetworks = JavaMethod("([Landroid/net/Network;)Z")
    prepare = JavaStaticMethod("(Landroid/content/Context;)Landroid/content/Intent;")
    onBind = JavaMethod("(Landroid/content/Intent;)Landroid/os/IBinder;")

    class Builder(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "android/net/VpnService$Builder"
        __javaconstructor__ = [("(Landroid/net/VpnService;)V", False)]
        setMtu = JavaMethod("(I)Landroid/net/VpnService$Builder;")
        addRoute = JavaMultipleMethod([("(Ljava/lang/String;I)Landroid/net/VpnService$Builder;", False, False), ("(Landroid/net/IpPrefix;)Landroid/net/VpnService$Builder;", False, False), ("(Ljava/net/InetAddress;I)Landroid/net/VpnService$Builder;", False, False)])
        setHttpProxy = JavaMethod("(Landroid/net/ProxyInfo;)Landroid/net/VpnService$Builder;")
        setUnderlyingNetworks = JavaMethod("([Landroid/net/Network;)Landroid/net/VpnService$Builder;")
        addSearchDomain = JavaMethod("(Ljava/lang/String;)Landroid/net/VpnService$Builder;")
        allowFamily = JavaMethod("(I)Landroid/net/VpnService$Builder;")
        establish = JavaMethod("()Landroid/os/ParcelFileDescriptor;")
        excludeRoute = JavaMethod("(Landroid/net/IpPrefix;)Landroid/net/VpnService$Builder;")
        setBlocking = JavaMethod("(Z)Landroid/net/VpnService$Builder;")
        addAddress = JavaMultipleMethod([("(Ljava/net/InetAddress;I)Landroid/net/VpnService$Builder;", False, False), ("(Ljava/lang/String;I)Landroid/net/VpnService$Builder;", False, False)])
        allowBypass = JavaMethod("()Landroid/net/VpnService$Builder;")
        addAllowedApplication = JavaMethod("(Ljava/lang/String;)Landroid/net/VpnService$Builder;")
        addDisallowedApplication = JavaMethod("(Ljava/lang/String;)Landroid/net/VpnService$Builder;")
        addDnsServer = JavaMultipleMethod([("(Ljava/net/InetAddress;)Landroid/net/VpnService$Builder;", False, False), ("(Ljava/lang/String;)Landroid/net/VpnService$Builder;", False, False)])
        setConfigureIntent = JavaMethod("(Landroid/app/PendingIntent;)Landroid/net/VpnService$Builder;")
        setMetered = JavaMethod("(Z)Landroid/net/VpnService$Builder;")
        setSession = JavaMethod("(Ljava/lang/String;)Landroid/net/VpnService$Builder;")

class NetworkInfo(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "android/net/NetworkInfo"
    __javaconstructor__ = [("(IILjava/lang/String;Ljava/lang/String;)V", False)]
    CREATOR = JavaStaticField("Landroid/os/Parcelable$Creator;")
    CONTENTS_FILE_DESCRIPTOR = JavaStaticField("I")
    PARCELABLE_WRITE_RETURN_VALUE = JavaStaticField("I")
    isConnected = JavaMethod("()Z")
    isAvailable = JavaMethod("()Z")
    isRoaming = JavaMethod("()Z")
    getExtraInfo = JavaMethod("()Ljava/lang/String;")
    getSubtype = JavaMethod("()I")
    getDetailedState = JavaMethod("()Landroid/net/NetworkInfo$DetailedState;")
    getSubtypeName = JavaMethod("()Ljava/lang/String;")
    isConnectedOrConnecting = JavaMethod("()Z")
    isFailover = JavaMethod("()Z")
    setDetailedState = JavaMethod("(Landroid/net/NetworkInfo$DetailedState;Ljava/lang/String;Ljava/lang/String;)V")
    toString = JavaMethod("()Ljava/lang/String;")
    getTypeName = JavaMethod("()Ljava/lang/String;")
    getState = JavaMethod("()Landroid/net/NetworkInfo$State;")
    getType = JavaMethod("()I")
    describeContents = JavaMethod("()I")
    writeToParcel = JavaMethod("(Landroid/os/Parcel;I)V")
    getReason = JavaMethod("()Ljava/lang/String;")

    class State(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "android/net/NetworkInfo$State"
        CONNECTED = JavaStaticField("Landroid/net/NetworkInfo$State;")
        CONNECTING = JavaStaticField("Landroid/net/NetworkInfo$State;")
        DISCONNECTED = JavaStaticField("Landroid/net/NetworkInfo$State;")
        DISCONNECTING = JavaStaticField("Landroid/net/NetworkInfo$State;")
        SUSPENDED = JavaStaticField("Landroid/net/NetworkInfo$State;")
        UNKNOWN = JavaStaticField("Landroid/net/NetworkInfo$State;")
        values = JavaStaticMethod("()[Landroid/net/NetworkInfo$State;")
        valueOf = JavaStaticMethod("(Ljava/lang/String;)Landroid/net/NetworkInfo$State;")
        CONNECTED = JavaStaticField("Landroid/net/NetworkInfo$State;")
        CONNECTING = JavaStaticField("Landroid/net/NetworkInfo$State;")
        DISCONNECTED = JavaStaticField("Landroid/net/NetworkInfo$State;")
        DISCONNECTING = JavaStaticField("Landroid/net/NetworkInfo$State;")
        SUSPENDED = JavaStaticField("Landroid/net/NetworkInfo$State;")
        UNKNOWN = JavaStaticField("Landroid/net/NetworkInfo$State;")

    class DetailedState(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "android/net/NetworkInfo$DetailedState"
        AUTHENTICATING = JavaStaticField("Landroid/net/NetworkInfo$DetailedState;")
        BLOCKED = JavaStaticField("Landroid/net/NetworkInfo$DetailedState;")
        CAPTIVE_PORTAL_CHECK = JavaStaticField("Landroid/net/NetworkInfo$DetailedState;")
        CONNECTED = JavaStaticField("Landroid/net/NetworkInfo$DetailedState;")
        CONNECTING = JavaStaticField("Landroid/net/NetworkInfo$DetailedState;")
        DISCONNECTED = JavaStaticField("Landroid/net/NetworkInfo$DetailedState;")
        DISCONNECTING = JavaStaticField("Landroid/net/NetworkInfo$DetailedState;")
        FAILED = JavaStaticField("Landroid/net/NetworkInfo$DetailedState;")
        IDLE = JavaStaticField("Landroid/net/NetworkInfo$DetailedState;")
        OBTAINING_IPADDR = JavaStaticField("Landroid/net/NetworkInfo$DetailedState;")
        SCANNING = JavaStaticField("Landroid/net/NetworkInfo$DetailedState;")
        SUSPENDED = JavaStaticField("Landroid/net/NetworkInfo$DetailedState;")
        VERIFYING_POOR_LINK = JavaStaticField("Landroid/net/NetworkInfo$DetailedState;")
        values = JavaStaticMethod("()[Landroid/net/NetworkInfo$DetailedState;")
        valueOf = JavaStaticMethod("(Ljava/lang/String;)Landroid/net/NetworkInfo$DetailedState;")
        AUTHENTICATING = JavaStaticField("Landroid/net/NetworkInfo$DetailedState;")
        BLOCKED = JavaStaticField("Landroid/net/NetworkInfo$DetailedState;")
        CAPTIVE_PORTAL_CHECK = JavaStaticField("Landroid/net/NetworkInfo$DetailedState;")
        CONNECTED = JavaStaticField("Landroid/net/NetworkInfo$DetailedState;")
        CONNECTING = JavaStaticField("Landroid/net/NetworkInfo$DetailedState;")
        DISCONNECTED = JavaStaticField("Landroid/net/NetworkInfo$DetailedState;")
        DISCONNECTING = JavaStaticField("Landroid/net/NetworkInfo$DetailedState;")
        FAILED = JavaStaticField("Landroid/net/NetworkInfo$DetailedState;")
        IDLE = JavaStaticField("Landroid/net/NetworkInfo$DetailedState;")
        OBTAINING_IPADDR = JavaStaticField("Landroid/net/NetworkInfo$DetailedState;")
        SCANNING = JavaStaticField("Landroid/net/NetworkInfo$DetailedState;")
        SUSPENDED = JavaStaticField("Landroid/net/NetworkInfo$DetailedState;")
        VERIFYING_POOR_LINK = JavaStaticField("Landroid/net/NetworkInfo$DetailedState;")

class Uri(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "android/net/Uri"
    CREATOR = JavaStaticField("Landroid/os/Parcelable$Creator;")
    EMPTY = JavaStaticField("Landroid/net/Uri;")
    CONTENTS_FILE_DESCRIPTOR = JavaStaticField("I")
    PARCELABLE_WRITE_RETURN_VALUE = JavaStaticField("I")
    equals = JavaMethod("(Ljava/lang/Object;)Z")
    toString = JavaMethod("()Ljava/lang/String;")
    hashCode = JavaMethod("()I")
    compareTo = JavaMultipleMethod([("(Ljava/lang/Object;)I", False, False), ("(Landroid/net/Uri;)I", False, False)])
    decode = JavaStaticMethod("(Ljava/lang/String;)Ljava/lang/String;")
    encode = JavaMultipleMethod([("(Ljava/lang/String;)Ljava/lang/String;", True, False), ("(Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;", True, False)])
    isAbsolute = JavaMethod("()Z")
    parse = JavaStaticMethod("(Ljava/lang/String;)Landroid/net/Uri;")
    fromFile = JavaStaticMethod("(Ljava/io/File;)Landroid/net/Uri;")
    fromParts = JavaStaticMethod("(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Landroid/net/Uri;")
    buildUpon = JavaMethod("()Landroid/net/Uri$Builder;")
    getBooleanQueryParameter = JavaMethod("(Ljava/lang/String;Z)Z")
    getEncodedAuthority = JavaMethod("()Ljava/lang/String;")
    getEncodedFragment = JavaMethod("()Ljava/lang/String;")
    getEncodedPath = JavaMethod("()Ljava/lang/String;")
    getEncodedQuery = JavaMethod("()Ljava/lang/String;")
    getEncodedSchemeSpecificPart = JavaMethod("()Ljava/lang/String;")
    getEncodedUserInfo = JavaMethod("()Ljava/lang/String;")
    getLastPathSegment = JavaMethod("()Ljava/lang/String;")
    getPathSegments = JavaMethod("()Ljava/util/List;")
    getQueryParameter = JavaMethod("(Ljava/lang/String;)Ljava/lang/String;")
    getQueryParameterNames = JavaMethod("()Ljava/util/Set;")
    getQueryParameters = JavaMethod("(Ljava/lang/String;)Ljava/util/List;")
    isHierarchical = JavaMethod("()Z")
    normalizeScheme = JavaMethod("()Landroid/net/Uri;")
    withAppendedPath = JavaStaticMethod("(Landroid/net/Uri;Ljava/lang/String;)Landroid/net/Uri;")
    writeToParcel = JavaStaticMethod("(Landroid/os/Parcel;Landroid/net/Uri;)V")
    getSchemeSpecificPart = JavaMethod("()Ljava/lang/String;")
    getFragment = JavaMethod("()Ljava/lang/String;")
    getAuthority = JavaMethod("()Ljava/lang/String;")
    isRelative = JavaMethod("()Z")
    getQuery = JavaMethod("()Ljava/lang/String;")
    getPath = JavaMethod("()Ljava/lang/String;")
    getUserInfo = JavaMethod("()Ljava/lang/String;")
    getScheme = JavaMethod("()Ljava/lang/String;")
    isOpaque = JavaMethod("()Z")
    getHost = JavaMethod("()Ljava/lang/String;")
    getPort = JavaMethod("()I")

    class Builder(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "android/net/Uri$Builder"
        __javaconstructor__ = [("()V", False)]
        toString = JavaMethod("()Ljava/lang/String;")
        appendEncodedPath = JavaMethod("(Ljava/lang/String;)Landroid/net/Uri$Builder;")
        appendPath = JavaMethod("(Ljava/lang/String;)Landroid/net/Uri$Builder;")
        appendQueryParameter = JavaMethod("(Ljava/lang/String;Ljava/lang/String;)Landroid/net/Uri$Builder;")
        clearQuery = JavaMethod("()Landroid/net/Uri$Builder;")
        encodedAuthority = JavaMethod("(Ljava/lang/String;)Landroid/net/Uri$Builder;")
        encodedFragment = JavaMethod("(Ljava/lang/String;)Landroid/net/Uri$Builder;")
        encodedOpaquePart = JavaMethod("(Ljava/lang/String;)Landroid/net/Uri$Builder;")
        encodedPath = JavaMethod("(Ljava/lang/String;)Landroid/net/Uri$Builder;")
        encodedQuery = JavaMethod("(Ljava/lang/String;)Landroid/net/Uri$Builder;")
        build = JavaMethod("()Landroid/net/Uri;")
        scheme = JavaMethod("(Ljava/lang/String;)Landroid/net/Uri$Builder;")
        fragment = JavaMethod("(Ljava/lang/String;)Landroid/net/Uri$Builder;")
        opaquePart = JavaMethod("(Ljava/lang/String;)Landroid/net/Uri$Builder;")
        authority = JavaMethod("(Ljava/lang/String;)Landroid/net/Uri$Builder;")
        query = JavaMethod("(Ljava/lang/String;)Landroid/net/Uri$Builder;")
        path = JavaMethod("(Ljava/lang/String;)Landroid/net/Uri$Builder;")

class NetworkCapabilities(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "android/net/NetworkCapabilities"
    __javaconstructor__ = [("()V", False), ("(Landroid/net/NetworkCapabilities;)V", False)]
    CREATOR = JavaStaticField("Landroid/os/Parcelable$Creator;")
    NET_CAPABILITY_CAPTIVE_PORTAL = JavaStaticField("I")
    NET_CAPABILITY_CBS = JavaStaticField("I")
    NET_CAPABILITY_DUN = JavaStaticField("I")
    NET_CAPABILITY_EIMS = JavaStaticField("I")
    NET_CAPABILITY_ENTERPRISE = JavaStaticField("I")
    NET_CAPABILITY_FOREGROUND = JavaStaticField("I")
    NET_CAPABILITY_FOTA = JavaStaticField("I")
    NET_CAPABILITY_HEAD_UNIT = JavaStaticField("I")
    NET_CAPABILITY_IA = JavaStaticField("I")
    NET_CAPABILITY_IMS = JavaStaticField("I")
    NET_CAPABILITY_INTERNET = JavaStaticField("I")
    NET_CAPABILITY_LOCAL_NETWORK = JavaStaticField("I")
    NET_CAPABILITY_MCX = JavaStaticField("I")
    NET_CAPABILITY_MMS = JavaStaticField("I")
    NET_CAPABILITY_MMTEL = JavaStaticField("I")
    NET_CAPABILITY_NOT_BANDWIDTH_CONSTRAINED = JavaStaticField("I")
    NET_CAPABILITY_NOT_CONGESTED = JavaStaticField("I")
    NET_CAPABILITY_NOT_METERED = JavaStaticField("I")
    NET_CAPABILITY_NOT_RESTRICTED = JavaStaticField("I")
    NET_CAPABILITY_NOT_ROAMING = JavaStaticField("I")
    NET_CAPABILITY_NOT_SUSPENDED = JavaStaticField("I")
    NET_CAPABILITY_NOT_VPN = JavaStaticField("I")
    NET_CAPABILITY_PRIORITIZE_BANDWIDTH = JavaStaticField("I")
    NET_CAPABILITY_PRIORITIZE_LATENCY = JavaStaticField("I")
    NET_CAPABILITY_RCS = JavaStaticField("I")
    NET_CAPABILITY_SUPL = JavaStaticField("I")
    NET_CAPABILITY_TEMPORARILY_NOT_METERED = JavaStaticField("I")
    NET_CAPABILITY_TRUSTED = JavaStaticField("I")
    NET_CAPABILITY_VALIDATED = JavaStaticField("I")
    NET_CAPABILITY_WIFI_P2P = JavaStaticField("I")
    NET_CAPABILITY_XCAP = JavaStaticField("I")
    NET_ENTERPRISE_ID_1 = JavaStaticField("I")
    NET_ENTERPRISE_ID_2 = JavaStaticField("I")
    NET_ENTERPRISE_ID_3 = JavaStaticField("I")
    NET_ENTERPRISE_ID_4 = JavaStaticField("I")
    NET_ENTERPRISE_ID_5 = JavaStaticField("I")
    SIGNAL_STRENGTH_UNSPECIFIED = JavaStaticField("I")
    TRANSPORT_BLUETOOTH = JavaStaticField("I")
    TRANSPORT_CELLULAR = JavaStaticField("I")
    TRANSPORT_ETHERNET = JavaStaticField("I")
    TRANSPORT_LOWPAN = JavaStaticField("I")
    TRANSPORT_SATELLITE = JavaStaticField("I")
    TRANSPORT_THREAD = JavaStaticField("I")
    TRANSPORT_USB = JavaStaticField("I")
    TRANSPORT_VPN = JavaStaticField("I")
    TRANSPORT_WIFI = JavaStaticField("I")
    TRANSPORT_WIFI_AWARE = JavaStaticField("I")
    CONTENTS_FILE_DESCRIPTOR = JavaStaticField("I")
    PARCELABLE_WRITE_RETURN_VALUE = JavaStaticField("I")
    getCapabilities = JavaMethod("()[I")
    getEnterpriseIds = JavaMethod("()[I")
    getLinkDownstreamBandwidthKbps = JavaMethod("()I")
    getLinkUpstreamBandwidthKbps = JavaMethod("()I")
    getNetworkSpecifier = JavaMethod("()Landroid/net/NetworkSpecifier;")
    getOwnerUid = JavaMethod("()I")
    getSignalStrength = JavaMethod("()I")
    getSubscriptionIds = JavaMethod("()Ljava/util/Set;")
    getTransportInfo = JavaMethod("()Landroid/net/TransportInfo;")
    hasCapability = JavaMethod("(I)Z")
    hasEnterpriseId = JavaMethod("(I)Z")
    hasTransport = JavaMethod("(I)Z")
    equals = JavaMethod("(Ljava/lang/Object;)Z")
    toString = JavaMethod("()Ljava/lang/String;")
    hashCode = JavaMethod("()I")
    describeContents = JavaMethod("()I")
    writeToParcel = JavaMethod("(Landroid/os/Parcel;I)V")

class PlatformVpnProfile(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "android/net/PlatformVpnProfile"
    TYPE_IKEV2_IPSEC_PSK = JavaStaticField("I")
    TYPE_IKEV2_IPSEC_RSA = JavaStaticField("I")
    TYPE_IKEV2_IPSEC_USER_PASS = JavaStaticField("I")
    areLocalRoutesExcluded = JavaMethod("()Z")
    isInternetValidationRequired = JavaMethod("()Z")
    getType = JavaMethod("()I")
    getTypeString = JavaMethod("()Ljava/lang/String;")

class NetworkSpecifier(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "android/net/NetworkSpecifier"
    __javaconstructor__ = [("()V", False)]

class TetheringManager(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "android/net/TetheringManager"
    CONNECTIVITY_SCOPE_GLOBAL = JavaStaticField("I")
    TETHERING_WIFI = JavaStaticField("I")
    TETHER_ERROR_DHCPSERVER_ERROR = JavaStaticField("I")
    TETHER_ERROR_DISABLE_FORWARDING_ERROR = JavaStaticField("I")
    TETHER_ERROR_DUPLICATE_REQUEST = JavaStaticField("I")
    TETHER_ERROR_ENABLE_FORWARDING_ERROR = JavaStaticField("I")
    TETHER_ERROR_ENTITLEMENT_UNKNOWN = JavaStaticField("I")
    TETHER_ERROR_IFACE_CFG_ERROR = JavaStaticField("I")
    TETHER_ERROR_INTERNAL_ERROR = JavaStaticField("I")
    TETHER_ERROR_NO_ACCESS_TETHERING_PERMISSION = JavaStaticField("I")
    TETHER_ERROR_NO_CHANGE_TETHERING_PERMISSION = JavaStaticField("I")
    TETHER_ERROR_NO_ERROR = JavaStaticField("I")
    TETHER_ERROR_PROVISIONING_FAILED = JavaStaticField("I")
    TETHER_ERROR_SERVICE_UNAVAIL = JavaStaticField("I")
    TETHER_ERROR_TETHER_IFACE_ERROR = JavaStaticField("I")
    TETHER_ERROR_UNAVAIL_IFACE = JavaStaticField("I")
    TETHER_ERROR_UNKNOWN_IFACE = JavaStaticField("I")
    TETHER_ERROR_UNKNOWN_REQUEST = JavaStaticField("I")
    TETHER_ERROR_UNKNOWN_TYPE = JavaStaticField("I")
    TETHER_ERROR_UNSUPPORTED = JavaStaticField("I")
    TETHER_ERROR_UNTETHER_IFACE_ERROR = JavaStaticField("I")
    registerTetheringEventCallback = JavaMethod("(Ljava/util/concurrent/Executor;Landroid/net/TetheringManager$TetheringEventCallback;)V")
    startTethering = JavaMethod("(Landroid/net/TetheringManager$TetheringRequest;Ljava/util/concurrent/Executor;Landroid/net/TetheringManager$StartTetheringCallback;)V")
    stopTethering = JavaMethod("(Landroid/net/TetheringManager$TetheringRequest;Ljava/util/concurrent/Executor;Landroid/net/TetheringManager$StopTetheringCallback;)V")
    unregisterTetheringEventCallback = JavaMethod("(Landroid/net/TetheringManager$TetheringEventCallback;)V")

    class TetheringRequest(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "android/net/TetheringManager$TetheringRequest"
        CREATOR = JavaStaticField("Landroid/os/Parcelable$Creator;")
        CONTENTS_FILE_DESCRIPTOR = JavaStaticField("I")
        PARCELABLE_WRITE_RETURN_VALUE = JavaStaticField("I")
        getSoftApConfiguration = JavaMethod("()Landroid/net/wifi/SoftApConfiguration;")
        equals = JavaMethod("(Ljava/lang/Object;)Z")
        toString = JavaMethod("()Ljava/lang/String;")
        hashCode = JavaMethod("()I")
        describeContents = JavaMethod("()I")
        writeToParcel = JavaMethod("(Landroid/os/Parcel;I)V")

        class Builder(JavaClass, metaclass=MetaJavaClass):
            __javaclass__ = "android/net/TetheringManager$TetheringRequest$Builder"
            __javaconstructor__ = [("(I)V", False)]
            setSoftApConfiguration = JavaMethod("(Landroid/net/wifi/SoftApConfiguration;)Landroid/net/TetheringManager$TetheringRequest$Builder;")
            build = JavaMethod("()Landroid/net/TetheringManager$TetheringRequest;")

    class TetheringEventCallback(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "android/net/TetheringManager$TetheringEventCallback"
        onTetheredInterfacesChanged = JavaMethod("(Ljava/util/Set;)V")

    class StopTetheringCallback(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "android/net/TetheringManager$StopTetheringCallback"
        onStopTetheringFailed = JavaMethod("(I)V")
        onStopTetheringSucceeded = JavaMethod("()V")

    class StartTetheringCallback(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "android/net/TetheringManager$StartTetheringCallback"
        onTetheringFailed = JavaMethod("(I)V")
        onTetheringStarted = JavaMethod("()V")

class IpSecAlgorithm(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "android/net/IpSecAlgorithm"
    __javaconstructor__ = [("(Ljava/lang/String;[B)V", False), ("(Ljava/lang/String;[BI)V", False)]
    AUTH_AES_CMAC = JavaStaticField("Ljava/lang/String;")
    AUTH_AES_XCBC = JavaStaticField("Ljava/lang/String;")
    AUTH_CRYPT_AES_GCM = JavaStaticField("Ljava/lang/String;")
    AUTH_CRYPT_CHACHA20_POLY1305 = JavaStaticField("Ljava/lang/String;")
    AUTH_HMAC_MD5 = JavaStaticField("Ljava/lang/String;")
    AUTH_HMAC_SHA1 = JavaStaticField("Ljava/lang/String;")
    AUTH_HMAC_SHA256 = JavaStaticField("Ljava/lang/String;")
    AUTH_HMAC_SHA384 = JavaStaticField("Ljava/lang/String;")
    AUTH_HMAC_SHA512 = JavaStaticField("Ljava/lang/String;")
    CREATOR = JavaStaticField("Landroid/os/Parcelable$Creator;")
    CRYPT_AES_CBC = JavaStaticField("Ljava/lang/String;")
    CRYPT_AES_CTR = JavaStaticField("Ljava/lang/String;")
    CONTENTS_FILE_DESCRIPTOR = JavaStaticField("I")
    PARCELABLE_WRITE_RETURN_VALUE = JavaStaticField("I")
    getSupportedAlgorithms = JavaStaticMethod("()Ljava/util/Set;")
    getTruncationLengthBits = JavaMethod("()I")
    getName = JavaMethod("()Ljava/lang/String;")
    toString = JavaMethod("()Ljava/lang/String;")
    getKey = JavaMethod("()[B")
    describeContents = JavaMethod("()I")
    writeToParcel = JavaMethod("(Landroid/os/Parcel;I)V")

class EthernetNetworkSpecifier(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "android/net/EthernetNetworkSpecifier"
    __javaconstructor__ = [("(Ljava/lang/String;)V", False)]
    CREATOR = JavaStaticField("Landroid/os/Parcelable$Creator;")
    CONTENTS_FILE_DESCRIPTOR = JavaStaticField("I")
    PARCELABLE_WRITE_RETURN_VALUE = JavaStaticField("I")
    getInterfaceName = JavaMethod("()Ljava/lang/String;")
    canBeSatisfiedBy = JavaMethod("(Landroid/net/NetworkSpecifier;)Z")
    equals = JavaMethod("(Ljava/lang/Object;)Z")
    toString = JavaMethod("()Ljava/lang/String;")
    hashCode = JavaMethod("()I")
    describeContents = JavaMethod("()I")
    writeToParcel = JavaMethod("(Landroid/os/Parcel;I)V")

class MailTo(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "android/net/MailTo"
    MAILTO_SCHEME = JavaStaticField("Ljava/lang/String;")
    getTo = JavaMethod("()Ljava/lang/String;")
    getCc = JavaMethod("()Ljava/lang/String;")
    getBody = JavaMethod("()Ljava/lang/String;")
    getHeaders = JavaMethod("()Ljava/util/Map;")
    getSubject = JavaMethod("()Ljava/lang/String;")
    isMailTo = JavaStaticMethod("(Ljava/lang/String;)Z")
    toString = JavaMethod("()Ljava/lang/String;")
    parse = JavaStaticMethod("(Ljava/lang/String;)Landroid/net/MailTo;")

class MacAddress(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "android/net/MacAddress"
    BROADCAST_ADDRESS = JavaStaticField("Landroid/net/MacAddress;")
    CREATOR = JavaStaticField("Landroid/os/Parcelable$Creator;")
    TYPE_BROADCAST = JavaStaticField("I")
    TYPE_MULTICAST = JavaStaticField("I")
    TYPE_UNICAST = JavaStaticField("I")
    CONTENTS_FILE_DESCRIPTOR = JavaStaticField("I")
    PARCELABLE_WRITE_RETURN_VALUE = JavaStaticField("I")
    equals = JavaMethod("(Ljava/lang/Object;)Z")
    toString = JavaMethod("()Ljava/lang/String;")
    hashCode = JavaMethod("()I")
    matches = JavaMethod("(Landroid/net/MacAddress;Landroid/net/MacAddress;)Z")
    fromBytes = JavaStaticMethod("([B)Landroid/net/MacAddress;")
    describeContents = JavaMethod("()I")
    writeToParcel = JavaMethod("(Landroid/os/Parcel;I)V")
    getAddressType = JavaMethod("()I")
    getLinkLocalIpv6FromEui48Mac = JavaMethod("()Ljava/net/Inet6Address;")
    isLocallyAssigned = JavaMethod("()Z")
    toOuiString = JavaMethod("()Ljava/lang/String;")
    fromString = JavaStaticMethod("(Ljava/lang/String;)Landroid/net/MacAddress;")
    toByteArray = JavaMethod("()[B")

class IpPrefix(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "android/net/IpPrefix"
    __javaconstructor__ = [("(Ljava/net/InetAddress;I)V", False)]
    CREATOR = JavaStaticField("Landroid/os/Parcelable$Creator;")
    CONTENTS_FILE_DESCRIPTOR = JavaStaticField("I")
    PARCELABLE_WRITE_RETURN_VALUE = JavaStaticField("I")
    getRawAddress = JavaMethod("()[B")
    equals = JavaMethod("(Ljava/lang/Object;)Z")
    toString = JavaMethod("()Ljava/lang/String;")
    hashCode = JavaMethod("()I")
    contains = JavaMethod("(Ljava/net/InetAddress;)Z")
    describeContents = JavaMethod("()I")
    writeToParcel = JavaMethod("(Landroid/os/Parcel;I)V")
    getPrefixLength = JavaMethod("()I")
    getAddress = JavaMethod("()Ljava/net/InetAddress;")

class TetheringInterface(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "android/net/TetheringInterface"
    __javaconstructor__ = [("(ILjava/lang/String;)V", False), ("(ILjava/lang/String;Landroid/net/wifi/SoftApConfiguration;)V", False)]
    CREATOR = JavaStaticField("Landroid/os/Parcelable$Creator;")
    CONTENTS_FILE_DESCRIPTOR = JavaStaticField("I")
    PARCELABLE_WRITE_RETURN_VALUE = JavaStaticField("I")
    getSoftApConfiguration = JavaMethod("()Landroid/net/wifi/SoftApConfiguration;")
    equals = JavaMethod("(Ljava/lang/Object;)Z")
    toString = JavaMethod("()Ljava/lang/String;")
    hashCode = JavaMethod("()I")
    getType = JavaMethod("()I")
    getInterface = JavaMethod("()Ljava/lang/String;")
    describeContents = JavaMethod("()I")
    writeToParcel = JavaMethod("(Landroid/os/Parcel;I)V")

class NetworkRequest(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "android/net/NetworkRequest"
    CREATOR = JavaStaticField("Landroid/os/Parcelable$Creator;")
    CONTENTS_FILE_DESCRIPTOR = JavaStaticField("I")
    PARCELABLE_WRITE_RETURN_VALUE = JavaStaticField("I")
    getCapabilities = JavaMethod("()[I")
    getNetworkSpecifier = JavaMethod("()Landroid/net/NetworkSpecifier;")
    getSubscriptionIds = JavaMethod("()Ljava/util/Set;")
    hasCapability = JavaMethod("(I)Z")
    hasTransport = JavaMethod("(I)Z")
    canBeSatisfiedBy = JavaMethod("(Landroid/net/NetworkCapabilities;)Z")
    getTransportTypes = JavaMethod("()[I")
    equals = JavaMethod("(Ljava/lang/Object;)Z")
    toString = JavaMethod("()Ljava/lang/String;")
    hashCode = JavaMethod("()I")
    describeContents = JavaMethod("()I")
    writeToParcel = JavaMethod("(Landroid/os/Parcel;I)V")

    class Builder(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "android/net/NetworkRequest$Builder"
        __javaconstructor__ = [("()V", False), ("(Landroid/net/NetworkRequest;)V", False)]
        clearCapabilities = JavaMethod("()Landroid/net/NetworkRequest$Builder;")
        removeTransportType = JavaMethod("(I)Landroid/net/NetworkRequest$Builder;")
        setNetworkSpecifier = JavaMultipleMethod([("(Landroid/net/NetworkSpecifier;)Landroid/net/NetworkRequest$Builder;", False, False), ("(Ljava/lang/String;)Landroid/net/NetworkRequest$Builder;", False, False)])
        addCapability = JavaMethod("(I)Landroid/net/NetworkRequest$Builder;")
        setIncludeOtherUidNetworks = JavaMethod("(Z)Landroid/net/NetworkRequest$Builder;")
        addTransportType = JavaMethod("(I)Landroid/net/NetworkRequest$Builder;")
        removeCapability = JavaMethod("(I)Landroid/net/NetworkRequest$Builder;")
        setSubscriptionIds = JavaMethod("(Ljava/util/Set;)Landroid/net/NetworkRequest$Builder;")
        build = JavaMethod("()Landroid/net/NetworkRequest;")

class IpConfiguration(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "android/net/IpConfiguration"
    CREATOR = JavaStaticField("Landroid/os/Parcelable$Creator;")
    CONTENTS_FILE_DESCRIPTOR = JavaStaticField("I")
    PARCELABLE_WRITE_RETURN_VALUE = JavaStaticField("I")
    getHttpProxy = JavaMethod("()Landroid/net/ProxyInfo;")
    getStaticIpConfiguration = JavaMethod("()Landroid/net/StaticIpConfiguration;")
    equals = JavaMethod("(Ljava/lang/Object;)Z")
    toString = JavaMethod("()Ljava/lang/String;")
    hashCode = JavaMethod("()I")
    describeContents = JavaMethod("()I")
    writeToParcel = JavaMethod("(Landroid/os/Parcel;I)V")

    class Builder(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "android/net/IpConfiguration$Builder"
        __javaconstructor__ = [("()V", False)]
        setHttpProxy = JavaMethod("(Landroid/net/ProxyInfo;)Landroid/net/IpConfiguration$Builder;")
        setStaticIpConfiguration = JavaMethod("(Landroid/net/StaticIpConfiguration;)Landroid/net/IpConfiguration$Builder;")
        build = JavaMethod("()Landroid/net/IpConfiguration;")

class SSLSessionCache(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "android/net/SSLSessionCache"
    __javaconstructor__ = [("(Landroid/content/Context;)V", False), ("(Ljava/io/File;)V", False)]

class StaticIpConfiguration(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "android/net/StaticIpConfiguration"
    CREATOR = JavaStaticField("Landroid/os/Parcelable$Creator;")
    CONTENTS_FILE_DESCRIPTOR = JavaStaticField("I")
    PARCELABLE_WRITE_RETURN_VALUE = JavaStaticField("I")
    getDnsServers = JavaMethod("()Ljava/util/List;")
    getDomains = JavaMethod("()Ljava/lang/String;")
    getGateway = JavaMethod("()Ljava/net/InetAddress;")
    getIpAddress = JavaMethod("()Landroid/net/LinkAddress;")
    equals = JavaMethod("(Ljava/lang/Object;)Z")
    toString = JavaMethod("()Ljava/lang/String;")
    hashCode = JavaMethod("()I")
    describeContents = JavaMethod("()I")
    writeToParcel = JavaMethod("(Landroid/os/Parcel;I)V")

    class Builder(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "android/net/StaticIpConfiguration$Builder"
        __javaconstructor__ = [("()V", False)]
        setDnsServers = JavaMethod("(Ljava/lang/Iterable;)Landroid/net/StaticIpConfiguration$Builder;")
        setDomains = JavaMethod("(Ljava/lang/String;)Landroid/net/StaticIpConfiguration$Builder;")
        setGateway = JavaMethod("(Ljava/net/InetAddress;)Landroid/net/StaticIpConfiguration$Builder;")
        setIpAddress = JavaMethod("(Landroid/net/LinkAddress;)Landroid/net/StaticIpConfiguration$Builder;")
        build = JavaMethod("()Landroid/net/StaticIpConfiguration;")

class SSLCertificateSocketFactory(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "android/net/SSLCertificateSocketFactory"
    __javaconstructor__ = [("(I)V", False)]
    getSupportedCipherSuites = JavaMethod("()[Ljava/lang/String;")
    setUseSessionTickets = JavaMethod("(Ljava/net/Socket;Z)V")
    createSocket = JavaMultipleMethod([("(Ljava/net/InetAddress;ILjava/net/InetAddress;I)Ljava/net/Socket;", False, False), ("(Ljava/net/InetAddress;I)Ljava/net/Socket;", False, False), ("(Ljava/net/Socket;Ljava/lang/String;IZ)Ljava/net/Socket;", False, False), ("()Ljava/net/Socket;", False, False), ("(Ljava/lang/String;I)Ljava/net/Socket;", False, False), ("(Ljava/lang/String;ILjava/net/InetAddress;I)Ljava/net/Socket;", False, False)])
    getDefaultCipherSuites = JavaMethod("()[Ljava/lang/String;")
    getInsecure = JavaStaticMethod("(ILandroid/net/SSLSessionCache;)Ljavax/net/ssl/SSLSocketFactory;")
    getNpnSelectedProtocol = JavaMethod("(Ljava/net/Socket;)[B")
    setHostname = JavaMethod("(Ljava/net/Socket;Ljava/lang/String;)V")
    setKeyManagers = JavaMethod("([Ljavax/net/ssl/KeyManager;)V")
    setNpnProtocols = JavaMethod("([[B)V")
    setTrustManagers = JavaMethod("([Ljavax/net/ssl/TrustManager;)V")
    getDefault = JavaMultipleMethod([("(I)Ljavax/net/SocketFactory;", True, False), ("(ILandroid/net/SSLSessionCache;)Ljavax/net/ssl/SSLSocketFactory;", True, False)])

class VpnManager(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "android/net/VpnManager"
    ACTION_VPN_MANAGER_EVENT = JavaStaticField("Ljava/lang/String;")
    CATEGORY_EVENT_ALWAYS_ON_STATE_CHANGED = JavaStaticField("Ljava/lang/String;")
    CATEGORY_EVENT_DEACTIVATED_BY_USER = JavaStaticField("Ljava/lang/String;")
    CATEGORY_EVENT_IKE_ERROR = JavaStaticField("Ljava/lang/String;")
    CATEGORY_EVENT_NETWORK_ERROR = JavaStaticField("Ljava/lang/String;")
    ERROR_CLASS_NOT_RECOVERABLE = JavaStaticField("I")
    ERROR_CLASS_RECOVERABLE = JavaStaticField("I")
    ERROR_CODE_NETWORK_IO = JavaStaticField("I")
    ERROR_CODE_NETWORK_LOST = JavaStaticField("I")
    ERROR_CODE_NETWORK_PROTOCOL_TIMEOUT = JavaStaticField("I")
    ERROR_CODE_NETWORK_UNKNOWN_HOST = JavaStaticField("I")
    EXTRA_ERROR_CLASS = JavaStaticField("Ljava/lang/String;")
    EXTRA_ERROR_CODE = JavaStaticField("Ljava/lang/String;")
    EXTRA_SESSION_KEY = JavaStaticField("Ljava/lang/String;")
    EXTRA_TIMESTAMP_MILLIS = JavaStaticField("Ljava/lang/String;")
    EXTRA_UNDERLYING_LINK_PROPERTIES = JavaStaticField("Ljava/lang/String;")
    EXTRA_UNDERLYING_NETWORK = JavaStaticField("Ljava/lang/String;")
    EXTRA_UNDERLYING_NETWORK_CAPABILITIES = JavaStaticField("Ljava/lang/String;")
    EXTRA_VPN_PROFILE_STATE = JavaStaticField("Ljava/lang/String;")
    deleteProvisionedVpnProfile = JavaMethod("()V")
    getProvisionedVpnProfileState = JavaMethod("()Landroid/net/VpnProfileState;")
    provisionVpnProfile = JavaMethod("(Landroid/net/PlatformVpnProfile;)Landroid/content/Intent;")
    startProvisionedVpnProfile = JavaMethod("()V")
    startProvisionedVpnProfileSession = JavaMethod("()Ljava/lang/String;")
    stopProvisionedVpnProfile = JavaMethod("()V")

class DnsResolver(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "android/net/DnsResolver"
    CLASS_IN = JavaStaticField("I")
    ERROR_PARSE = JavaStaticField("I")
    ERROR_SYSTEM = JavaStaticField("I")
    FLAG_EMPTY = JavaStaticField("I")
    FLAG_NO_CACHE_LOOKUP = JavaStaticField("I")
    FLAG_NO_CACHE_STORE = JavaStaticField("I")
    FLAG_NO_RETRY = JavaStaticField("I")
    TYPE_A = JavaStaticField("I")
    TYPE_AAAA = JavaStaticField("I")
    rawQuery = JavaMultipleMethod([("(Landroid/net/Network;Ljava/lang/String;IIILjava/util/concurrent/Executor;Landroid/os/CancellationSignal;Landroid/net/DnsResolver$Callback;)V", False, False), ("(Landroid/net/Network;[BILjava/util/concurrent/Executor;Landroid/os/CancellationSignal;Landroid/net/DnsResolver$Callback;)V", False, False)])
    getInstance = JavaStaticMethod("()Landroid/net/DnsResolver;")
    query = JavaMultipleMethod([("(Landroid/net/Network;Ljava/lang/String;IILjava/util/concurrent/Executor;Landroid/os/CancellationSignal;Landroid/net/DnsResolver$Callback;)V", False, False), ("(Landroid/net/Network;Ljava/lang/String;ILjava/util/concurrent/Executor;Landroid/os/CancellationSignal;Landroid/net/DnsResolver$Callback;)V", False, False)])

    class DnsException(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "android/net/DnsResolver$DnsException"
        __javaconstructor__ = [("(ILjava/lang/Throwable;)V", False)]
        code = JavaField("I")

    class Callback(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "android/net/DnsResolver$Callback"
        onAnswer = JavaMethod("(Ljava/lang/Object;I)V")
        onError = JavaMethod("(Landroid/net/DnsResolver$DnsException;)V")

class TelephonyNetworkSpecifier(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "android/net/TelephonyNetworkSpecifier"
    CREATOR = JavaStaticField("Landroid/os/Parcelable$Creator;")
    CONTENTS_FILE_DESCRIPTOR = JavaStaticField("I")
    PARCELABLE_WRITE_RETURN_VALUE = JavaStaticField("I")
    getSubscriptionId = JavaMethod("()I")
    equals = JavaMethod("(Ljava/lang/Object;)Z")
    toString = JavaMethod("()Ljava/lang/String;")
    hashCode = JavaMethod("()I")
    describeContents = JavaMethod("()I")
    writeToParcel = JavaMethod("(Landroid/os/Parcel;I)V")

    class Builder(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "android/net/TelephonyNetworkSpecifier$Builder"
        __javaconstructor__ = [("()V", False)]
        setSubscriptionId = JavaMethod("(I)Landroid/net/TelephonyNetworkSpecifier$Builder;")
        build = JavaMethod("()Landroid/net/TelephonyNetworkSpecifier;")

class IpSecManager(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "android/net/IpSecManager"
    DIRECTION_IN = JavaStaticField("I")
    DIRECTION_OUT = JavaStaticField("I")
    allocateSecurityParameterIndex = JavaMultipleMethod([("(Ljava/net/InetAddress;I)Landroid/net/IpSecManager$SecurityParameterIndex;", False, False), ("(Ljava/net/InetAddress;)Landroid/net/IpSecManager$SecurityParameterIndex;", False, False)])
    applyTransportModeTransform = JavaMultipleMethod([("(Ljava/io/FileDescriptor;ILandroid/net/IpSecTransform;)V", False, False), ("(Ljava/net/DatagramSocket;ILandroid/net/IpSecTransform;)V", False, False), ("(Ljava/net/Socket;ILandroid/net/IpSecTransform;)V", False, False)])
    openUdpEncapsulationSocket = JavaMultipleMethod([("(I)Landroid/net/IpSecManager$UdpEncapsulationSocket;", False, False), ("()Landroid/net/IpSecManager$UdpEncapsulationSocket;", False, False)])
    removeTransportModeTransforms = JavaMultipleMethod([("(Ljava/net/DatagramSocket;)V", False, False), ("(Ljava/io/FileDescriptor;)V", False, False), ("(Ljava/net/Socket;)V", False, False)])

    class UdpEncapsulationSocket(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "android/net/IpSecManager$UdpEncapsulationSocket"
        toString = JavaMethod("()Ljava/lang/String;")
        close = JavaMethod("()V")
        getFileDescriptor = JavaMethod("()Ljava/io/FileDescriptor;")
        getPort = JavaMethod("()I")

    class SpiUnavailableException(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "android/net/IpSecManager$SpiUnavailableException"
        getSpi = JavaMethod("()I")

    class SecurityParameterIndex(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "android/net/IpSecManager$SecurityParameterIndex"
        getSpi = JavaMethod("()I")
        toString = JavaMethod("()Ljava/lang/String;")
        close = JavaMethod("()V")

    class ResourceUnavailableException(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "android/net/IpSecManager$ResourceUnavailableException"

class ConnectivityDiagnosticsManager(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "android/net/ConnectivityDiagnosticsManager"
    registerConnectivityDiagnosticsCallback = JavaMethod("(Landroid/net/NetworkRequest;Ljava/util/concurrent/Executor;Landroid/net/ConnectivityDiagnosticsManager$ConnectivityDiagnosticsCallback;)V")
    unregisterConnectivityDiagnosticsCallback = JavaMethod("(Landroid/net/ConnectivityDiagnosticsManager$ConnectivityDiagnosticsCallback;)V")

    class DataStallReport(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "android/net/ConnectivityDiagnosticsManager$DataStallReport"
        __javaconstructor__ = [("(Landroid/net/Network;JILandroid/net/LinkProperties;Landroid/net/NetworkCapabilities;Landroid/os/PersistableBundle;)V", False)]
        CREATOR = JavaStaticField("Landroid/os/Parcelable$Creator;")
        DETECTION_METHOD_DNS_EVENTS = JavaStaticField("I")
        DETECTION_METHOD_TCP_METRICS = JavaStaticField("I")
        KEY_DNS_CONSECUTIVE_TIMEOUTS = JavaStaticField("Ljava/lang/String;")
        KEY_TCP_METRICS_COLLECTION_PERIOD_MILLIS = JavaStaticField("Ljava/lang/String;")
        KEY_TCP_PACKET_FAIL_RATE = JavaStaticField("Ljava/lang/String;")
        CONTENTS_FILE_DESCRIPTOR = JavaStaticField("I")
        PARCELABLE_WRITE_RETURN_VALUE = JavaStaticField("I")
        getNetwork = JavaMethod("()Landroid/net/Network;")
        getDetectionMethod = JavaMethod("()I")
        getReportTimestamp = JavaMethod("()J")
        getStallDetails = JavaMethod("()Landroid/os/PersistableBundle;")
        getLinkProperties = JavaMethod("()Landroid/net/LinkProperties;")
        equals = JavaMethod("(Ljava/lang/Object;)Z")
        hashCode = JavaMethod("()I")
        describeContents = JavaMethod("()I")
        writeToParcel = JavaMethod("(Landroid/os/Parcel;I)V")
        getNetworkCapabilities = JavaMethod("()Landroid/net/NetworkCapabilities;")

    class ConnectivityReport(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "android/net/ConnectivityDiagnosticsManager$ConnectivityReport"
        __javaconstructor__ = [("(Landroid/net/Network;JLandroid/net/LinkProperties;Landroid/net/NetworkCapabilities;Landroid/os/PersistableBundle;)V", False)]
        CREATOR = JavaStaticField("Landroid/os/Parcelable$Creator;")
        KEY_NETWORK_PROBES_ATTEMPTED_BITMASK = JavaStaticField("Ljava/lang/String;")
        KEY_NETWORK_PROBES_SUCCEEDED_BITMASK = JavaStaticField("Ljava/lang/String;")
        KEY_NETWORK_VALIDATION_RESULT = JavaStaticField("Ljava/lang/String;")
        NETWORK_PROBE_DNS = JavaStaticField("I")
        NETWORK_PROBE_FALLBACK = JavaStaticField("I")
        NETWORK_PROBE_HTTP = JavaStaticField("I")
        NETWORK_PROBE_HTTPS = JavaStaticField("I")
        NETWORK_PROBE_PRIVATE_DNS = JavaStaticField("I")
        NETWORK_VALIDATION_RESULT_INVALID = JavaStaticField("I")
        NETWORK_VALIDATION_RESULT_PARTIALLY_VALID = JavaStaticField("I")
        NETWORK_VALIDATION_RESULT_SKIPPED = JavaStaticField("I")
        NETWORK_VALIDATION_RESULT_VALID = JavaStaticField("I")
        CONTENTS_FILE_DESCRIPTOR = JavaStaticField("I")
        PARCELABLE_WRITE_RETURN_VALUE = JavaStaticField("I")
        getNetwork = JavaMethod("()Landroid/net/Network;")
        getReportTimestamp = JavaMethod("()J")
        getAdditionalInfo = JavaMethod("()Landroid/os/PersistableBundle;")
        getLinkProperties = JavaMethod("()Landroid/net/LinkProperties;")
        equals = JavaMethod("(Ljava/lang/Object;)Z")
        hashCode = JavaMethod("()I")
        describeContents = JavaMethod("()I")
        writeToParcel = JavaMethod("(Landroid/os/Parcel;I)V")
        getNetworkCapabilities = JavaMethod("()Landroid/net/NetworkCapabilities;")

    class ConnectivityDiagnosticsCallback(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "android/net/ConnectivityDiagnosticsManager$ConnectivityDiagnosticsCallback"
        __javaconstructor__ = [("()V", False)]
        onDataStallSuspected = JavaMethod("(Landroid/net/ConnectivityDiagnosticsManager$DataStallReport;)V")
        onConnectivityReportAvailable = JavaMethod("(Landroid/net/ConnectivityDiagnosticsManager$ConnectivityReport;)V")
        onNetworkConnectivityReported = JavaMethod("(Landroid/net/Network;Z)V")

class RouteInfo(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "android/net/RouteInfo"
    CREATOR = JavaStaticField("Landroid/os/Parcelable$Creator;")
    RTN_THROW = JavaStaticField("I")
    RTN_UNICAST = JavaStaticField("I")
    RTN_UNREACHABLE = JavaStaticField("I")
    CONTENTS_FILE_DESCRIPTOR = JavaStaticField("I")
    PARCELABLE_WRITE_RETURN_VALUE = JavaStaticField("I")
    getGateway = JavaMethod("()Ljava/net/InetAddress;")
    equals = JavaMethod("(Ljava/lang/Object;)Z")
    toString = JavaMethod("()Ljava/lang/String;")
    hashCode = JavaMethod("()I")
    matches = JavaMethod("(Ljava/net/InetAddress;)Z")
    getType = JavaMethod("()I")
    getInterface = JavaMethod("()Ljava/lang/String;")
    getDestination = JavaMethod("()Landroid/net/IpPrefix;")
    hasGateway = JavaMethod("()Z")
    isDefaultRoute = JavaMethod("()Z")
    describeContents = JavaMethod("()I")
    writeToParcel = JavaMethod("(Landroid/os/Parcel;I)V")

class Proxy(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "android/net/Proxy"
    __javaconstructor__ = [("()V", False)]
    PROXY_CHANGE_ACTION = JavaStaticField("Ljava/lang/String;")
    getDefaultHost = JavaStaticMethod("()Ljava/lang/String;")
    getHost = JavaStaticMethod("(Landroid/content/Context;)Ljava/lang/String;")
    getPort = JavaStaticMethod("(Landroid/content/Context;)I")
    getDefaultPort = JavaStaticMethod("()I")

class LinkProperties(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "android/net/LinkProperties"
    __javaconstructor__ = [("()V", False)]
    CREATOR = JavaStaticField("Landroid/os/Parcelable$Creator;")
    CONTENTS_FILE_DESCRIPTOR = JavaStaticField("I")
    PARCELABLE_WRITE_RETURN_VALUE = JavaStaticField("I")
    getMtu = JavaMethod("()I")
    setMtu = JavaMethod("(I)V")
    getDhcpServerAddress = JavaMethod("()Ljava/net/Inet4Address;")
    getDnsServers = JavaMethod("()Ljava/util/List;")
    getDomains = JavaMethod("()Ljava/lang/String;")
    getHttpProxy = JavaMethod("()Landroid/net/ProxyInfo;")
    getInterfaceName = JavaMethod("()Ljava/lang/String;")
    getLinkAddresses = JavaMethod("()Ljava/util/List;")
    getNat64Prefix = JavaMethod("()Landroid/net/IpPrefix;")
    addRoute = JavaMethod("(Landroid/net/RouteInfo;)Z")
    getPrivateDnsServerName = JavaMethod("()Ljava/lang/String;")
    getRoutes = JavaMethod("()Ljava/util/List;")
    isPrivateDnsActive = JavaMethod("()Z")
    isWakeOnLanSupported = JavaMethod("()Z")
    setDhcpServerAddress = JavaMethod("(Ljava/net/Inet4Address;)V")
    setDnsServers = JavaMethod("(Ljava/util/Collection;)V")
    setDomains = JavaMethod("(Ljava/lang/String;)V")
    setHttpProxy = JavaMethod("(Landroid/net/ProxyInfo;)V")
    setInterfaceName = JavaMethod("(Ljava/lang/String;)V")
    setLinkAddresses = JavaMethod("(Ljava/util/Collection;)V")
    setNat64Prefix = JavaMethod("(Landroid/net/IpPrefix;)V")
    equals = JavaMethod("(Ljava/lang/Object;)Z")
    toString = JavaMethod("()Ljava/lang/String;")
    hashCode = JavaMethod("()I")
    clear = JavaMethod("()V")
    describeContents = JavaMethod("()I")
    writeToParcel = JavaMethod("(Landroid/os/Parcel;I)V")

class ParseException(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "android/net/ParseException"
    __javaconstructor__ = [("(Ljava/lang/String;)V", False), ("(Ljava/lang/String;Ljava/lang/Throwable;)V", False)]
    response = JavaField("Ljava/lang/String;")

class UrlQuerySanitizer(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "android/net/UrlQuerySanitizer"
    __javaconstructor__ = [("(Ljava/lang/String;)V", False), ("()V", False)]
    getAllButWhitespaceLegal = JavaStaticMethod("()Landroid/net/UrlQuerySanitizer$ValueSanitizer;")
    getAllButNulAndAngleBracketsLegal = JavaStaticMethod("()Landroid/net/UrlQuerySanitizer$ValueSanitizer;")
    getAllButNulLegal = JavaStaticMethod("()Landroid/net/UrlQuerySanitizer$ValueSanitizer;")
    getAllIllegal = JavaStaticMethod("()Landroid/net/UrlQuerySanitizer$ValueSanitizer;")
    getAllowUnregisteredParamaters = JavaMethod("()Z")
    getAmpAndSpaceLegal = JavaStaticMethod("()Landroid/net/UrlQuerySanitizer$ValueSanitizer;")
    getAmpLegal = JavaStaticMethod("()Landroid/net/UrlQuerySanitizer$ValueSanitizer;")
    getEffectiveValueSanitizer = JavaMethod("(Ljava/lang/String;)Landroid/net/UrlQuerySanitizer$ValueSanitizer;")
    getParameterList = JavaMethod("()Ljava/util/List;")
    getParameterSet = JavaMethod("()Ljava/util/Set;")
    getPreferFirstRepeatedParameter = JavaMethod("()Z")
    getSpaceLegal = JavaStaticMethod("()Landroid/net/UrlQuerySanitizer$ValueSanitizer;")
    getUnregisteredParameterValueSanitizer = JavaMethod("()Landroid/net/UrlQuerySanitizer$ValueSanitizer;")
    getUrlAndSpaceLegal = JavaStaticMethod("()Landroid/net/UrlQuerySanitizer$ValueSanitizer;")
    getUrlLegal = JavaStaticMethod("()Landroid/net/UrlQuerySanitizer$ValueSanitizer;")
    getValueSanitizer = JavaMethod("(Ljava/lang/String;)Landroid/net/UrlQuerySanitizer$ValueSanitizer;")
    hasParameter = JavaMethod("(Ljava/lang/String;)Z")
    parseQuery = JavaMethod("(Ljava/lang/String;)V")
    parseUrl = JavaMethod("(Ljava/lang/String;)V")
    registerParameter = JavaMethod("(Ljava/lang/String;Landroid/net/UrlQuerySanitizer$ValueSanitizer;)V")
    registerParameters = JavaMethod("([Ljava/lang/String;Landroid/net/UrlQuerySanitizer$ValueSanitizer;)V")
    setAllowUnregisteredParamaters = JavaMethod("(Z)V")
    setPreferFirstRepeatedParameter = JavaMethod("(Z)V")
    setUnregisteredParameterValueSanitizer = JavaMethod("(Landroid/net/UrlQuerySanitizer$ValueSanitizer;)V")
    getValue = JavaMethod("(Ljava/lang/String;)Ljava/lang/String;")
    unescape = JavaMethod("(Ljava/lang/String;)Ljava/lang/String;")

    class ValueSanitizer(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "android/net/UrlQuerySanitizer$ValueSanitizer"
        sanitize = JavaMethod("(Ljava/lang/String;)Ljava/lang/String;")

    class ParameterValuePair(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "android/net/UrlQuerySanitizer$ParameterValuePair"
        __javaconstructor__ = [("(Landroid/net/UrlQuerySanitizer;Ljava/lang/String;Ljava/lang/String;)V", False)]
        mParameter = JavaField("Ljava/lang/String;")
        mValue = JavaField("Ljava/lang/String;")

    class IllegalCharacterValueSanitizer(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "android/net/UrlQuerySanitizer$IllegalCharacterValueSanitizer"
        __javaconstructor__ = [("(I)V", False)]
        ALL_BUT_NUL_AND_ANGLE_BRACKETS_LEGAL = JavaStaticField("I")
        ALL_BUT_NUL_LEGAL = JavaStaticField("I")
        ALL_BUT_WHITESPACE_LEGAL = JavaStaticField("I")
        ALL_ILLEGAL = JavaStaticField("I")
        ALL_OK = JavaStaticField("I")
        ALL_WHITESPACE_OK = JavaStaticField("I")
        AMP_AND_SPACE_LEGAL = JavaStaticField("I")
        AMP_LEGAL = JavaStaticField("I")
        AMP_OK = JavaStaticField("I")
        DQUOTE_OK = JavaStaticField("I")
        GT_OK = JavaStaticField("I")
        LT_OK = JavaStaticField("I")
        NON_7_BIT_ASCII_OK = JavaStaticField("I")
        NUL_OK = JavaStaticField("I")
        OTHER_WHITESPACE_OK = JavaStaticField("I")
        PCT_OK = JavaStaticField("I")
        SCRIPT_URL_OK = JavaStaticField("I")
        SPACE_LEGAL = JavaStaticField("I")
        SPACE_OK = JavaStaticField("I")
        SQUOTE_OK = JavaStaticField("I")
        URL_AND_SPACE_LEGAL = JavaStaticField("I")
        URL_LEGAL = JavaStaticField("I")
        sanitize = JavaMethod("(Ljava/lang/String;)Ljava/lang/String;")

class ProxyInfo(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "android/net/ProxyInfo"
    __javaconstructor__ = [("(Landroid/net/ProxyInfo;)V", False)]
    CREATOR = JavaStaticField("Landroid/os/Parcelable$Creator;")
    CONTENTS_FILE_DESCRIPTOR = JavaStaticField("I")
    PARCELABLE_WRITE_RETURN_VALUE = JavaStaticField("I")
    buildDirectProxy = JavaMultipleMethod([("(Ljava/lang/String;ILjava/util/List;)Landroid/net/ProxyInfo;", True, False), ("(Ljava/lang/String;I)Landroid/net/ProxyInfo;", True, False)])
    buildPacProxy = JavaMultipleMethod([("(Landroid/net/Uri;)Landroid/net/ProxyInfo;", True, False), ("(Landroid/net/Uri;I)Landroid/net/ProxyInfo;", True, False)])
    getExclusionList = JavaMethod("()[Ljava/lang/String;")
    getPacFileUrl = JavaMethod("()Landroid/net/Uri;")
    equals = JavaMethod("(Ljava/lang/Object;)Z")
    toString = JavaMethod("()Ljava/lang/String;")
    hashCode = JavaMethod("()I")
    isValid = JavaMethod("()Z")
    describeContents = JavaMethod("()I")
    writeToParcel = JavaMethod("(Landroid/os/Parcel;I)V")
    getHost = JavaMethod("()Ljava/lang/String;")
    getPort = JavaMethod("()I")

class Ikev2VpnProfile(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "android/net/Ikev2VpnProfile"
    TYPE_IKEV2_IPSEC_PSK = JavaStaticField("I")
    TYPE_IKEV2_IPSEC_RSA = JavaStaticField("I")
    TYPE_IKEV2_IPSEC_USER_PASS = JavaStaticField("I")
    getPassword = JavaMethod("()Ljava/lang/String;")
    getMaxMtu = JavaMethod("()I")
    getUsername = JavaMethod("()Ljava/lang/String;")
    isMetered = JavaMethod("()Z")
    getPresharedKey = JavaMethod("()[B")
    getProxyInfo = JavaMethod("()Landroid/net/ProxyInfo;")
    getRsaPrivateKey = JavaMethod("()Ljava/security/PrivateKey;")
    getServerAddr = JavaMethod("()Ljava/lang/String;")
    getServerRootCaCert = JavaMethod("()Ljava/security/cert/X509Certificate;")
    getUserCert = JavaMethod("()Ljava/security/cert/X509Certificate;")
    getUserIdentity = JavaMethod("()Ljava/lang/String;")
    getAllowedAlgorithms = JavaMethod("()Ljava/util/List;")
    getIkeTunnelConnectionParams = JavaMethod("()Landroid/net/ipsec/ike/IkeTunnelConnectionParams;")
    isAutomaticIpVersionSelectionEnabled = JavaMethod("()Z")
    isAutomaticNattKeepaliveTimerEnabled = JavaMethod("()Z")
    isBypassable = JavaMethod("()Z")
    equals = JavaMethod("(Ljava/lang/Object;)Z")
    toString = JavaMethod("()Ljava/lang/String;")
    hashCode = JavaMethod("()I")

    class Builder(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "android/net/Ikev2VpnProfile$Builder"
        __javaconstructor__ = [("(Landroid/net/ipsec/ike/IkeTunnelConnectionParams;)V", False), ("(Ljava/lang/String;Ljava/lang/String;)V", False)]
        setMaxMtu = JavaMethod("(I)Landroid/net/Ikev2VpnProfile$Builder;")
        setMetered = JavaMethod("(Z)Landroid/net/Ikev2VpnProfile$Builder;")
        setAuthDigitalSignature = JavaMethod("(Ljava/security/cert/X509Certificate;Ljava/security/PrivateKey;Ljava/security/cert/X509Certificate;)Landroid/net/Ikev2VpnProfile$Builder;")
        setAllowedAlgorithms = JavaMethod("(Ljava/util/List;)Landroid/net/Ikev2VpnProfile$Builder;")
        setAuthPsk = JavaMethod("([B)Landroid/net/Ikev2VpnProfile$Builder;")
        setAuthUsernamePassword = JavaMethod("(Ljava/lang/String;Ljava/lang/String;Ljava/security/cert/X509Certificate;)Landroid/net/Ikev2VpnProfile$Builder;")
        setAutomaticIpVersionSelectionEnabled = JavaMethod("(Z)Landroid/net/Ikev2VpnProfile$Builder;")
        setAutomaticNattKeepaliveTimerEnabled = JavaMethod("(Z)Landroid/net/Ikev2VpnProfile$Builder;")
        setBypassable = JavaMethod("(Z)Landroid/net/Ikev2VpnProfile$Builder;")
        setLocalRoutesExcluded = JavaMethod("(Z)Landroid/net/Ikev2VpnProfile$Builder;")
        setProxy = JavaMethod("(Landroid/net/ProxyInfo;)Landroid/net/Ikev2VpnProfile$Builder;")
        setRequiresInternetValidation = JavaMethod("(Z)Landroid/net/Ikev2VpnProfile$Builder;")
        build = JavaMethod("()Landroid/net/Ikev2VpnProfile;")

class L2capNetworkSpecifier(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "android/net/L2capNetworkSpecifier"
    CREATOR = JavaStaticField("Landroid/os/Parcelable$Creator;")
    HEADER_COMPRESSION_6LOWPAN = JavaStaticField("I")
    HEADER_COMPRESSION_ANY = JavaStaticField("I")
    HEADER_COMPRESSION_NONE = JavaStaticField("I")
    PSM_ANY = JavaStaticField("I")
    ROLE_ANY = JavaStaticField("I")
    ROLE_CLIENT = JavaStaticField("I")
    ROLE_SERVER = JavaStaticField("I")
    CONTENTS_FILE_DESCRIPTOR = JavaStaticField("I")
    PARCELABLE_WRITE_RETURN_VALUE = JavaStaticField("I")
    getRemoteAddress = JavaMethod("()Landroid/net/MacAddress;")
    canBeSatisfiedBy = JavaMethod("(Landroid/net/NetworkSpecifier;)Z")
    getRole = JavaMethod("()I")
    getPsm = JavaMethod("()I")
    redact = JavaMethod("()Landroid/net/NetworkSpecifier;")
    getHeaderCompression = JavaMethod("()I")
    equals = JavaMethod("(Ljava/lang/Object;)Z")
    toString = JavaMethod("()Ljava/lang/String;")
    hashCode = JavaMethod("()I")
    describeContents = JavaMethod("()I")
    writeToParcel = JavaMethod("(Landroid/os/Parcel;I)V")

    class Builder(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "android/net/L2capNetworkSpecifier$Builder"
        __javaconstructor__ = [("()V", False)]
        setPsm = JavaMethod("(I)Landroid/net/L2capNetworkSpecifier$Builder;")
        setHeaderCompression = JavaMethod("(I)Landroid/net/L2capNetworkSpecifier$Builder;")
        setRemoteAddress = JavaMethod("(Landroid/net/MacAddress;)Landroid/net/L2capNetworkSpecifier$Builder;")
        setRole = JavaMethod("(I)Landroid/net/L2capNetworkSpecifier$Builder;")
        build = JavaMethod("()Landroid/net/L2capNetworkSpecifier;")

class Credentials(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "android/net/Credentials"
    __javaconstructor__ = [("(III)V", False)]
    getGid = JavaMethod("()I")
    getUid = JavaMethod("()I")
    getPid = JavaMethod("()I")

class LinkAddress(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "android/net/LinkAddress"
    CREATOR = JavaStaticField("Landroid/os/Parcelable$Creator;")
    CONTENTS_FILE_DESCRIPTOR = JavaStaticField("I")
    PARCELABLE_WRITE_RETURN_VALUE = JavaStaticField("I")
    equals = JavaMethod("(Ljava/lang/Object;)Z")
    toString = JavaMethod("()Ljava/lang/String;")
    hashCode = JavaMethod("()I")
    getFlags = JavaMethod("()I")
    describeContents = JavaMethod("()I")
    writeToParcel = JavaMethod("(Landroid/os/Parcel;I)V")
    getScope = JavaMethod("()I")
    getPrefixLength = JavaMethod("()I")
    getAddress = JavaMethod("()Ljava/net/InetAddress;")

class LocalServerSocket(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "android/net/LocalServerSocket"
    __javaconstructor__ = [("(Ljava/io/FileDescriptor;)V", False), ("(Ljava/lang/String;)V", False)]
    accept = JavaMethod("()Landroid/net/LocalSocket;")
    close = JavaMethod("()V")
    getFileDescriptor = JavaMethod("()Ljava/io/FileDescriptor;")
    getLocalSocketAddress = JavaMethod("()Landroid/net/LocalSocketAddress;")

class IpSecTransform(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "android/net/IpSecTransform"
    requestIpSecTransformState = JavaMethod("(Ljava/util/concurrent/Executor;Landroid/os/OutcomeReceiver;)V")
    equals = JavaMethod("(Ljava/lang/Object;)Z")
    toString = JavaMethod("()Ljava/lang/String;")
    close = JavaMethod("()V")

    class Builder(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "android/net/IpSecTransform$Builder"
        __javaconstructor__ = [("(Landroid/content/Context;)V", False)]
        setAuthentication = JavaMethod("(Landroid/net/IpSecAlgorithm;)Landroid/net/IpSecTransform$Builder;")
        setIpv4Encapsulation = JavaMethod("(Landroid/net/IpSecManager$UdpEncapsulationSocket;I)Landroid/net/IpSecTransform$Builder;")
        setEncryption = JavaMethod("(Landroid/net/IpSecAlgorithm;)Landroid/net/IpSecTransform$Builder;")
        buildTransportModeTransform = JavaMethod("(Ljava/net/InetAddress;Landroid/net/IpSecManager$SecurityParameterIndex;)Landroid/net/IpSecTransform;")
        setAuthenticatedEncryption = JavaMethod("(Landroid/net/IpSecAlgorithm;)Landroid/net/IpSecTransform$Builder;")

class LocalSocketAddress(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "android/net/LocalSocketAddress"
    __javaconstructor__ = [("(Ljava/lang/String;)V", False), ("(Ljava/lang/String;Landroid/net/LocalSocketAddress$Namespace;)V", False)]
    getName = JavaMethod("()Ljava/lang/String;")
    getNamespace = JavaMethod("()Landroid/net/LocalSocketAddress$Namespace;")

    class Namespace(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "android/net/LocalSocketAddress$Namespace"
        ABSTRACT = JavaStaticField("Landroid/net/LocalSocketAddress$Namespace;")
        FILESYSTEM = JavaStaticField("Landroid/net/LocalSocketAddress$Namespace;")
        RESERVED = JavaStaticField("Landroid/net/LocalSocketAddress$Namespace;")
        values = JavaStaticMethod("()[Landroid/net/LocalSocketAddress$Namespace;")
        valueOf = JavaStaticMethod("(Ljava/lang/String;)Landroid/net/LocalSocketAddress$Namespace;")
        ABSTRACT = JavaStaticField("Landroid/net/LocalSocketAddress$Namespace;")
        FILESYSTEM = JavaStaticField("Landroid/net/LocalSocketAddress$Namespace;")
        RESERVED = JavaStaticField("Landroid/net/LocalSocketAddress$Namespace;")

class TrafficStats(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "android/net/TrafficStats"
    __javaconstructor__ = [("()V", False)]
    UNSUPPORTED = JavaStaticField("I")
    getRxBytes = JavaStaticMethod("(Ljava/lang/String;)J")
    getRxPackets = JavaStaticMethod("(Ljava/lang/String;)J")
    getTxBytes = JavaStaticMethod("(Ljava/lang/String;)J")
    getTxPackets = JavaStaticMethod("(Ljava/lang/String;)J")
    clearThreadStatsTag = JavaStaticMethod("()V")
    getUidRxBytes = JavaStaticMethod("(I)J")
    clearThreadStatsUid = JavaStaticMethod("()V")
    getAndSetThreadStatsTag = JavaStaticMethod("(I)I")
    getMobileRxBytes = JavaStaticMethod("()J")
    getMobileRxPackets = JavaStaticMethod("()J")
    getMobileTxBytes = JavaStaticMethod("()J")
    getMobileTxPackets = JavaStaticMethod("()J")
    getThreadStatsTag = JavaStaticMethod("()I")
    getThreadStatsUid = JavaStaticMethod("()I")
    getTotalRxBytes = JavaStaticMethod("()J")
    getTotalRxPackets = JavaStaticMethod("()J")
    getTotalTxBytes = JavaStaticMethod("()J")
    getTotalTxPackets = JavaStaticMethod("()J")
    getUidRxPackets = JavaStaticMethod("(I)J")
    getUidTcpRxBytes = JavaStaticMethod("(I)J")
    getUidTcpRxSegments = JavaStaticMethod("(I)J")
    getUidTcpTxBytes = JavaStaticMethod("(I)J")
    getUidTcpTxSegments = JavaStaticMethod("(I)J")
    getUidTxBytes = JavaStaticMethod("(I)J")
    getUidTxPackets = JavaStaticMethod("(I)J")
    getUidUdpRxBytes = JavaStaticMethod("(I)J")
    getUidUdpRxPackets = JavaStaticMethod("(I)J")
    getUidUdpTxBytes = JavaStaticMethod("(I)J")
    getUidUdpTxPackets = JavaStaticMethod("(I)J")
    incrementOperationCount = JavaMultipleMethod([("(II)V", True, False), ("(I)V", True, False)])
    setThreadStatsTag = JavaStaticMethod("(I)V")
    setThreadStatsUid = JavaStaticMethod("(I)V")
    tagDatagramSocket = JavaStaticMethod("(Ljava/net/DatagramSocket;)V")
    tagFileDescriptor = JavaStaticMethod("(Ljava/io/FileDescriptor;)V")
    tagSocket = JavaStaticMethod("(Ljava/net/Socket;)V")
    untagDatagramSocket = JavaStaticMethod("(Ljava/net/DatagramSocket;)V")
    untagFileDescriptor = JavaStaticMethod("(Ljava/io/FileDescriptor;)V")
    untagSocket = JavaStaticMethod("(Ljava/net/Socket;)V")

class ConnectivityManager(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "android/net/ConnectivityManager"
    ACTION_BACKGROUND_DATA_SETTING_CHANGED = JavaStaticField("Ljava/lang/String;")
    ACTION_CAPTIVE_PORTAL_SIGN_IN = JavaStaticField("Ljava/lang/String;")
    ACTION_RESTRICT_BACKGROUND_CHANGED = JavaStaticField("Ljava/lang/String;")
    CONNECTIVITY_ACTION = JavaStaticField("Ljava/lang/String;")
    DEFAULT_NETWORK_PREFERENCE = JavaStaticField("I")
    EXTRA_CAPTIVE_PORTAL = JavaStaticField("Ljava/lang/String;")
    EXTRA_CAPTIVE_PORTAL_URL = JavaStaticField("Ljava/lang/String;")
    EXTRA_EXTRA_INFO = JavaStaticField("Ljava/lang/String;")
    EXTRA_IS_FAILOVER = JavaStaticField("Ljava/lang/String;")
    EXTRA_NETWORK = JavaStaticField("Ljava/lang/String;")
    EXTRA_NETWORK_INFO = JavaStaticField("Ljava/lang/String;")
    EXTRA_NETWORK_REQUEST = JavaStaticField("Ljava/lang/String;")
    EXTRA_NETWORK_TYPE = JavaStaticField("Ljava/lang/String;")
    EXTRA_NO_CONNECTIVITY = JavaStaticField("Ljava/lang/String;")
    EXTRA_OTHER_NETWORK_INFO = JavaStaticField("Ljava/lang/String;")
    EXTRA_REASON = JavaStaticField("Ljava/lang/String;")
    MULTIPATH_PREFERENCE_HANDOVER = JavaStaticField("I")
    MULTIPATH_PREFERENCE_PERFORMANCE = JavaStaticField("I")
    MULTIPATH_PREFERENCE_RELIABILITY = JavaStaticField("I")
    RESTRICT_BACKGROUND_STATUS_DISABLED = JavaStaticField("I")
    RESTRICT_BACKGROUND_STATUS_ENABLED = JavaStaticField("I")
    RESTRICT_BACKGROUND_STATUS_WHITELISTED = JavaStaticField("I")
    TYPE_BLUETOOTH = JavaStaticField("I")
    TYPE_DUMMY = JavaStaticField("I")
    TYPE_ETHERNET = JavaStaticField("I")
    TYPE_MOBILE = JavaStaticField("I")
    TYPE_MOBILE_DUN = JavaStaticField("I")
    TYPE_MOBILE_HIPRI = JavaStaticField("I")
    TYPE_MOBILE_MMS = JavaStaticField("I")
    TYPE_MOBILE_SUPL = JavaStaticField("I")
    TYPE_VPN = JavaStaticField("I")
    TYPE_WIFI = JavaStaticField("I")
    TYPE_WIMAX = JavaStaticField("I")
    getLinkProperties = JavaMethod("(Landroid/net/Network;)Landroid/net/LinkProperties;")
    addDefaultNetworkActiveListener = JavaMethod("(Landroid/net/ConnectivityManager$OnNetworkActiveListener;)V")
    bindProcessToNetwork = JavaMethod("(Landroid/net/Network;)Z")
    createSocketKeepalive = JavaMethod("(Landroid/net/Network;Landroid/net/IpSecManager$UdpEncapsulationSocket;Ljava/net/InetAddress;Ljava/net/InetAddress;Ljava/util/concurrent/Executor;Landroid/net/SocketKeepalive$Callback;)Landroid/net/SocketKeepalive;")
    getActiveNetwork = JavaMethod("()Landroid/net/Network;")
    getActiveNetworkInfo = JavaMethod("()Landroid/net/NetworkInfo;")
    getAllNetworkInfo = JavaMethod("()[Landroid/net/NetworkInfo;")
    getAllNetworks = JavaMethod("()[Landroid/net/Network;")
    getBackgroundDataSetting = JavaMethod("()Z")
    getBoundNetworkForProcess = JavaMethod("()Landroid/net/Network;")
    getConnectionOwnerUid = JavaMethod("(ILjava/net/InetSocketAddress;Ljava/net/InetSocketAddress;)I")
    getDefaultProxy = JavaMethod("()Landroid/net/ProxyInfo;")
    getMultipathPreference = JavaMethod("(Landroid/net/Network;)I")
    getNetworkInfo = JavaMultipleMethod([("(I)Landroid/net/NetworkInfo;", False, False), ("(Landroid/net/Network;)Landroid/net/NetworkInfo;", False, False)])
    getNetworkPreference = JavaMethod("()I")
    getNetworkWatchlistConfigHash = JavaMethod("()[B")
    getProcessDefaultNetwork = JavaStaticMethod("()Landroid/net/Network;")
    getRestrictBackgroundStatus = JavaMethod("()I")
    isActiveNetworkMetered = JavaMethod("()Z")
    isDefaultNetworkActive = JavaMethod("()Z")
    isNetworkTypeValid = JavaStaticMethod("(I)Z")
    registerBestMatchingNetworkCallback = JavaMethod("(Landroid/net/NetworkRequest;Landroid/net/ConnectivityManager$NetworkCallback;Landroid/os/Handler;)V")
    registerDefaultNetworkCallback = JavaMultipleMethod([("(Landroid/net/ConnectivityManager$NetworkCallback;Landroid/os/Handler;)V", False, False), ("(Landroid/net/ConnectivityManager$NetworkCallback;)V", False, False)])
    registerNetworkCallback = JavaMultipleMethod([("(Landroid/net/NetworkRequest;Landroid/app/PendingIntent;)V", False, False), ("(Landroid/net/NetworkRequest;Landroid/net/ConnectivityManager$NetworkCallback;)V", False, False), ("(Landroid/net/NetworkRequest;Landroid/net/ConnectivityManager$NetworkCallback;Landroid/os/Handler;)V", False, False)])
    releaseNetworkRequest = JavaMethod("(Landroid/app/PendingIntent;)V")
    removeDefaultNetworkActiveListener = JavaMethod("(Landroid/net/ConnectivityManager$OnNetworkActiveListener;)V")
    reportBadNetwork = JavaMethod("(Landroid/net/Network;)V")
    reportNetworkConnectivity = JavaMethod("(Landroid/net/Network;Z)V")
    requestBandwidthUpdate = JavaMethod("(Landroid/net/Network;)Z")
    requestNetwork = JavaMultipleMethod([("(Landroid/net/NetworkRequest;Landroid/net/ConnectivityManager$NetworkCallback;Landroid/os/Handler;)V", False, False), ("(Landroid/net/NetworkRequest;Landroid/net/ConnectivityManager$NetworkCallback;)V", False, False), ("(Landroid/net/NetworkRequest;Landroid/app/PendingIntent;)V", False, False), ("(Landroid/net/NetworkRequest;Landroid/net/ConnectivityManager$NetworkCallback;Landroid/os/Handler;I)V", False, False), ("(Landroid/net/NetworkRequest;Landroid/net/ConnectivityManager$NetworkCallback;I)V", False, False)])
    reserveNetwork = JavaMethod("(Landroid/net/NetworkRequest;Landroid/os/Handler;Landroid/net/ConnectivityManager$NetworkCallback;)V")
    setNetworkPreference = JavaMethod("(I)V")
    setProcessDefaultNetwork = JavaStaticMethod("(Landroid/net/Network;)Z")
    unregisterNetworkCallback = JavaMultipleMethod([("(Landroid/app/PendingIntent;)V", False, False), ("(Landroid/net/ConnectivityManager$NetworkCallback;)V", False, False)])
    getNetworkCapabilities = JavaMethod("(Landroid/net/Network;)Landroid/net/NetworkCapabilities;")

    class OnNetworkActiveListener(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "android/net/ConnectivityManager$OnNetworkActiveListener"
        onNetworkActive = JavaMethod("()V")

    class NetworkCallback(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "android/net/ConnectivityManager$NetworkCallback"
        __javaconstructor__ = [("(I)V", False), ("()V", False)]
        FLAG_INCLUDE_LOCATION_INFO = JavaStaticField("I")
        onAvailable = JavaMethod("(Landroid/net/Network;)V")
        onUnavailable = JavaMethod("()V")
        onBlockedStatusChanged = JavaMethod("(Landroid/net/Network;Z)V")
        onCapabilitiesChanged = JavaMethod("(Landroid/net/Network;Landroid/net/NetworkCapabilities;)V")
        onLost = JavaMethod("(Landroid/net/Network;)V")
        onLinkPropertiesChanged = JavaMethod("(Landroid/net/Network;Landroid/net/LinkProperties;)V")
        onLosing = JavaMethod("(Landroid/net/Network;I)V")
        onReserved = JavaMethod("(Landroid/net/NetworkCapabilities;)V")

class InetAddresses(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "android/net/InetAddresses"
    isNumericAddress = JavaStaticMethod("(Ljava/lang/String;)Z")
    parseNumericAddress = JavaStaticMethod("(Ljava/lang/String;)Ljava/net/InetAddress;")

class VpnProfileState(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "android/net/VpnProfileState"
    __javaconstructor__ = [("(ILjava/lang/String;ZZ)V", False)]
    CREATOR = JavaStaticField("Landroid/os/Parcelable$Creator;")
    STATE_CONNECTED = JavaStaticField("I")
    STATE_CONNECTING = JavaStaticField("I")
    STATE_DISCONNECTED = JavaStaticField("I")
    STATE_FAILED = JavaStaticField("I")
    CONTENTS_FILE_DESCRIPTOR = JavaStaticField("I")
    PARCELABLE_WRITE_RETURN_VALUE = JavaStaticField("I")
    getSessionId = JavaMethod("()Ljava/lang/String;")
    isAlwaysOn = JavaMethod("()Z")
    isLockdownEnabled = JavaMethod("()Z")
    equals = JavaMethod("(Ljava/lang/Object;)Z")
    toString = JavaMethod("()Ljava/lang/String;")
    hashCode = JavaMethod("()I")
    getState = JavaMethod("()I")
    describeContents = JavaMethod("()I")
    writeToParcel = JavaMethod("(Landroid/os/Parcel;I)V")

class IpSecTransformState(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "android/net/IpSecTransformState"
    CREATOR = JavaStaticField("Landroid/os/Parcelable$Creator;")
    CONTENTS_FILE_DESCRIPTOR = JavaStaticField("I")
    PARCELABLE_WRITE_RETURN_VALUE = JavaStaticField("I")
    getPacketCount = JavaMethod("()J")
    getTxHighestSequenceNumber = JavaMethod("()J")
    getReplayBitmap = JavaMethod("()[B")
    getRxHighestSequenceNumber = JavaMethod("()J")
    getByteCount = JavaMethod("()J")
    getTimestampMillis = JavaMethod("()J")
    describeContents = JavaMethod("()I")
    writeToParcel = JavaMethod("(Landroid/os/Parcel;I)V")

    class Builder(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "android/net/IpSecTransformState$Builder"
        __javaconstructor__ = [("()V", False)]
        setPacketCount = JavaMethod("(J)Landroid/net/IpSecTransformState$Builder;")
        setByteCount = JavaMethod("(J)Landroid/net/IpSecTransformState$Builder;")
        setRxHighestSequenceNumber = JavaMethod("(J)Landroid/net/IpSecTransformState$Builder;")
        setReplayBitmap = JavaMethod("([B)Landroid/net/IpSecTransformState$Builder;")
        setTxHighestSequenceNumber = JavaMethod("(J)Landroid/net/IpSecTransformState$Builder;")
        setTimestampMillis = JavaMethod("(J)Landroid/net/IpSecTransformState$Builder;")
        build = JavaMethod("()Landroid/net/IpSecTransformState;")

class Network(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "android/net/Network"
    CREATOR = JavaStaticField("Landroid/os/Parcelable$Creator;")
    CONTENTS_FILE_DESCRIPTOR = JavaStaticField("I")
    PARCELABLE_WRITE_RETURN_VALUE = JavaStaticField("I")
    bindSocket = JavaMultipleMethod([("(Ljava/net/DatagramSocket;)V", False, False), ("(Ljava/io/FileDescriptor;)V", False, False), ("(Ljava/net/Socket;)V", False, False)])
    fromNetworkHandle = JavaStaticMethod("(J)Landroid/net/Network;")
    getAllByName = JavaMethod("(Ljava/lang/String;)[Ljava/net/InetAddress;")
    getNetworkHandle = JavaMethod("()J")
    getSocketFactory = JavaMethod("()Ljavax/net/SocketFactory;")
    equals = JavaMethod("(Ljava/lang/Object;)Z")
    toString = JavaMethod("()Ljava/lang/String;")
    hashCode = JavaMethod("()I")
    describeContents = JavaMethod("()I")
    writeToParcel = JavaMethod("(Landroid/os/Parcel;I)V")
    getByName = JavaMethod("(Ljava/lang/String;)Ljava/net/InetAddress;")
    openConnection = JavaMultipleMethod([("(Ljava/net/URL;)Ljava/net/URLConnection;", False, False), ("(Ljava/net/URL;Ljava/net/Proxy;)Ljava/net/URLConnection;", False, False)])

class DhcpInfo(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "android/net/DhcpInfo"
    __javaconstructor__ = [("()V", False)]
    CREATOR = JavaStaticField("Landroid/os/Parcelable$Creator;")
    dns1 = JavaField("I")
    dns2 = JavaField("I")
    gateway = JavaField("I")
    ipAddress = JavaField("I")
    leaseDuration = JavaField("I")
    netmask = JavaField("I")
    serverAddress = JavaField("I")
    CONTENTS_FILE_DESCRIPTOR = JavaStaticField("I")
    PARCELABLE_WRITE_RETURN_VALUE = JavaStaticField("I")
    toString = JavaMethod("()Ljava/lang/String;")
    describeContents = JavaMethod("()I")
    writeToParcel = JavaMethod("(Landroid/os/Parcel;I)V")

class SocketKeepalive(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "android/net/SocketKeepalive"
    ERROR_HARDWARE_ERROR = JavaStaticField("I")
    ERROR_INSUFFICIENT_RESOURCES = JavaStaticField("I")
    ERROR_INVALID_INTERVAL = JavaStaticField("I")
    ERROR_INVALID_IP_ADDRESS = JavaStaticField("I")
    ERROR_INVALID_LENGTH = JavaStaticField("I")
    ERROR_INVALID_NETWORK = JavaStaticField("I")
    ERROR_INVALID_PORT = JavaStaticField("I")
    ERROR_INVALID_SOCKET = JavaStaticField("I")
    ERROR_SOCKET_NOT_IDLE = JavaStaticField("I")
    ERROR_UNSUPPORTED = JavaStaticField("I")
    start = JavaMethod("(I)V")
    stop = JavaMethod("()V")
    close = JavaMethod("()V")

    class Callback(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "android/net/SocketKeepalive$Callback"
        __javaconstructor__ = [("()V", False)]
        onDataReceived = JavaMethod("()V")
        onError = JavaMethod("(I)V")
        onStarted = JavaMethod("()V")
        onStopped = JavaMethod("()V")

class LocalSocket(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "android/net/LocalSocket"
    __javaconstructor__ = [("(I)V", False), ("()V", False)]
    SOCKET_DGRAM = JavaStaticField("I")
    SOCKET_SEQPACKET = JavaStaticField("I")
    SOCKET_STREAM = JavaStaticField("I")
    getOutputStream = JavaMethod("()Ljava/io/OutputStream;")
    isConnected = JavaMethod("()Z")
    toString = JavaMethod("()Ljava/lang/String;")
    connect = JavaMultipleMethod([("(Landroid/net/LocalSocketAddress;)V", False, False), ("(Landroid/net/LocalSocketAddress;I)V", False, False)])
    close = JavaMethod("()V")
    isClosed = JavaMethod("()Z")
    bind = JavaMethod("(Landroid/net/LocalSocketAddress;)V")
    getAncillaryFileDescriptors = JavaMethod("()[Ljava/io/FileDescriptor;")
    getPeerCredentials = JavaMethod("()Landroid/net/Credentials;")
    setFileDescriptorsForSend = JavaMethod("([Ljava/io/FileDescriptor;)V")
    getFileDescriptor = JavaMethod("()Ljava/io/FileDescriptor;")
    getInputStream = JavaMethod("()Ljava/io/InputStream;")
    isBound = JavaMethod("()Z")
    getRemoteSocketAddress = JavaMethod("()Landroid/net/LocalSocketAddress;")
    getLocalSocketAddress = JavaMethod("()Landroid/net/LocalSocketAddress;")
    setSoTimeout = JavaMethod("(I)V")
    getSoTimeout = JavaMethod("()I")
    setSendBufferSize = JavaMethod("(I)V")
    getSendBufferSize = JavaMethod("()I")
    setReceiveBufferSize = JavaMethod("(I)V")
    getReceiveBufferSize = JavaMethod("()I")
    isInputShutdown = JavaMethod("()Z")
    isOutputShutdown = JavaMethod("()Z")
    shutdownInput = JavaMethod("()V")
    shutdownOutput = JavaMethod("()V")

class TransportInfo(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "android/net/TransportInfo"

class CaptivePortal(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "android/net/CaptivePortal"
    CREATOR = JavaStaticField("Landroid/os/Parcelable$Creator;")
    CONTENTS_FILE_DESCRIPTOR = JavaStaticField("I")
    PARCELABLE_WRITE_RETURN_VALUE = JavaStaticField("I")
    ignoreNetwork = JavaMethod("()V")
    reportCaptivePortalDismissed = JavaMethod("()V")
    describeContents = JavaMethod("()I")
    writeToParcel = JavaMethod("(Landroid/os/Parcel;I)V")