from typing import Any, ClassVar, overload
from android.content.Intent import Intent
from android.os.Bundle import Bundle
from android.preference.Preference import Preference
from android.preference.PreferenceManager import PreferenceManager
from android.preference.PreferenceScreen import PreferenceScreen
from android.view.LayoutInflater import LayoutInflater
from android.view.View import View
from android.view.ViewGroup import ViewGroup

class PreferenceFragment:
    TRIM_MEMORY_BACKGROUND: ClassVar[int]
    TRIM_MEMORY_COMPLETE: ClassVar[int]
    TRIM_MEMORY_MODERATE: ClassVar[int]
    TRIM_MEMORY_RUNNING_CRITICAL: ClassVar[int]
    TRIM_MEMORY_RUNNING_LOW: ClassVar[int]
    TRIM_MEMORY_RUNNING_MODERATE: ClassVar[int]
    TRIM_MEMORY_UI_HIDDEN: ClassVar[int]
    def __init__(self) -> None: ...
    def onActivityResult(self, p0: int, p1: int, p2: Intent) -> None: ...
    def onCreateView(self, p0: LayoutInflater, p1: ViewGroup, p2: Bundle) -> View: ...
    def onDestroyView(self) -> None: ...
    def onActivityCreated(self, p0: Bundle) -> None: ...
    def onViewCreated(self, p0: View, p1: Bundle) -> None: ...
    def addPreferencesFromIntent(self, p0: Intent) -> None: ...
    def addPreferencesFromResource(self, p0: int) -> None: ...
    def findPreference(self, p0: str) -> Preference: ...
    def getPreferenceManager(self) -> PreferenceManager: ...
    def getPreferenceScreen(self) -> PreferenceScreen: ...
    def onPreferenceTreeClick(self, p0: PreferenceScreen, p1: Preference) -> bool: ...
    def setPreferenceScreen(self, p0: PreferenceScreen) -> None: ...
    def onStart(self) -> None: ...
    def onSaveInstanceState(self, p0: Bundle) -> None: ...
    def onStop(self) -> None: ...
    def onCreate(self, p0: Bundle) -> None: ...
    def onDestroy(self) -> None: ...

    class OnPreferenceStartFragmentCallback:
        def onPreferenceStartFragment(self, p0: "PreferenceFragment", p1: Preference) -> bool: ...

from typing import Any, ClassVar, overload
from android.content.Context import Context
from android.util.AttributeSet import AttributeSet

class PreferenceCategory:
    DEFAULT_ORDER: ClassVar[int]
    @overload
    def __init__(self, p0: Context) -> None: ...
    @overload
    def __init__(self, p0: Context, p1: AttributeSet, p2: int, p3: int) -> None: ...
    @overload
    def __init__(self, p0: Context, p1: AttributeSet, p2: int) -> None: ...
    @overload
    def __init__(self, p0: Context, p1: AttributeSet) -> None: ...
    def shouldDisableDependents(self) -> bool: ...
    def isEnabled(self) -> bool: ...

from typing import Any, ClassVar, overload
from android.content.Context import Context
from android.util.AttributeSet import AttributeSet
from android.widget.EditText import EditText

class EditTextPreference:
    DEFAULT_ORDER: ClassVar[int]
    @overload
    def __init__(self, p0: Context, p1: AttributeSet) -> None: ...
    @overload
    def __init__(self, p0: Context) -> None: ...
    @overload
    def __init__(self, p0: Context, p1: AttributeSet, p2: int) -> None: ...
    @overload
    def __init__(self, p0: Context, p1: AttributeSet, p2: int, p3: int) -> None: ...
    def shouldDisableDependents(self) -> bool: ...
    def getEditText(self) -> EditText: ...
    def getText(self) -> str: ...
    def setText(self, p0: str) -> None: ...

from typing import Any, ClassVar, overload
from android.content.Context import Context
from android.preference.Preference import Preference
from android.util.AttributeSet import AttributeSet

class PreferenceGroup:
    DEFAULT_ORDER: ClassVar[int]
    @overload
    def __init__(self, p0: Context, p1: AttributeSet, p2: int) -> None: ...
    @overload
    def __init__(self, p0: Context, p1: AttributeSet, p2: int, p3: int) -> None: ...
    @overload
    def __init__(self, p0: Context, p1: AttributeSet) -> None: ...
    def notifyDependencyChange(self, p0: bool) -> None: ...
    def addItemFromInflater(self, p0: Preference) -> None: ...
    def addPreference(self, p0: Preference) -> bool: ...
    def getPreference(self, p0: int) -> Preference: ...
    def getPreferenceCount(self) -> int: ...
    def isOrderingAsAdded(self) -> bool: ...
    def removePreference(self, p0: Preference) -> bool: ...
    def setOrderingAsAdded(self, p0: bool) -> None: ...
    def findPreference(self, p0: str) -> Preference: ...
    def removeAll(self) -> None: ...

from typing import Any, ClassVar, overload
from android.app.Dialog import Dialog
from android.content.DialogInterface import DialogInterface
from android.view.View import View
from android.widget.AdapterView import AdapterView
from android.widget.ListAdapter import ListAdapter
from android.widget.ListView import ListView

class PreferenceScreen:
    DEFAULT_ORDER: ClassVar[int]
    def getDialog(self) -> Dialog: ...
    def getRootAdapter(self) -> ListAdapter: ...
    def onDismiss(self, p0: DialogInterface) -> None: ...
    def onItemClick(self, p0: AdapterView, p1: View, p2: int, p3: int) -> None: ...
    def bind(self, p0: ListView) -> None: ...

from typing import Any, ClassVar, overload
from android.content.Context import Context
from android.content.Intent import Intent
from android.util.AttributeSet import AttributeSet

class RingtonePreference:
    DEFAULT_ORDER: ClassVar[int]
    @overload
    def __init__(self, p0: Context, p1: AttributeSet) -> None: ...
    @overload
    def __init__(self, p0: Context, p1: AttributeSet, p2: int) -> None: ...
    @overload
    def __init__(self, p0: Context, p1: AttributeSet, p2: int, p3: int) -> None: ...
    @overload
    def __init__(self, p0: Context) -> None: ...
    def onActivityResult(self, p0: int, p1: int, p2: Intent) -> bool: ...
    def getShowDefault(self) -> bool: ...
    def getShowSilent(self) -> bool: ...
    def getRingtoneType(self) -> int: ...
    def setRingtoneType(self, p0: int) -> None: ...
    def setShowDefault(self, p0: bool) -> None: ...
    def setShowSilent(self, p0: bool) -> None: ...

from typing import Any, ClassVar, overload
from android.content.Context import Context
from android.util.AttributeSet import AttributeSet

class MultiSelectListPreference:
    DEFAULT_ORDER: ClassVar[int]
    @overload
    def __init__(self, p0: Context, p1: AttributeSet) -> None: ...
    @overload
    def __init__(self, p0: Context, p1: AttributeSet, p2: int) -> None: ...
    @overload
    def __init__(self, p0: Context, p1: AttributeSet, p2: int, p3: int) -> None: ...
    @overload
    def __init__(self, p0: Context) -> None: ...
    def findIndexOfValue(self, p0: str) -> int: ...
    @overload
    def setEntries(self, p0: int) -> None: ...
    @overload
    def setEntries(self, p0: Any) -> None: ...
    @overload
    def setEntryValues(self, p0: int) -> None: ...
    @overload
    def setEntryValues(self, p0: Any) -> None: ...
    def getEntryValues(self) -> Any: ...
    def getValues(self) -> set: ...
    def setValues(self, p0: set) -> None: ...
    def getEntries(self) -> Any: ...

from typing import Any, ClassVar, overload
from android.content.Context import Context
from android.util.AttributeSet import AttributeSet

class TwoStatePreference:
    DEFAULT_ORDER: ClassVar[int]
    @overload
    def __init__(self, p0: Context, p1: AttributeSet, p2: int) -> None: ...
    @overload
    def __init__(self, p0: Context, p1: AttributeSet, p2: int, p3: int) -> None: ...
    @overload
    def __init__(self, p0: Context) -> None: ...
    @overload
    def __init__(self, p0: Context, p1: AttributeSet) -> None: ...
    def shouldDisableDependents(self) -> bool: ...
    def getSummaryOn(self) -> str: ...
    def getDisableDependentsState(self) -> bool: ...
    def setDisableDependentsState(self, p0: bool) -> None: ...
    @overload
    def setSummaryOff(self, p0: int) -> None: ...
    @overload
    def setSummaryOff(self, p0: str) -> None: ...
    @overload
    def setSummaryOn(self, p0: str) -> None: ...
    @overload
    def setSummaryOn(self, p0: int) -> None: ...
    def getSummaryOff(self) -> str: ...
    def isChecked(self) -> bool: ...
    def setChecked(self, p0: bool) -> None: ...

from typing import Any, ClassVar, overload
from android.content.Context import Context
from android.util.AttributeSet import AttributeSet

class ListPreference:
    DEFAULT_ORDER: ClassVar[int]
    @overload
    def __init__(self, p0: Context) -> None: ...
    @overload
    def __init__(self, p0: Context, p1: AttributeSet, p2: int, p3: int) -> None: ...
    @overload
    def __init__(self, p0: Context, p1: AttributeSet, p2: int) -> None: ...
    @overload
    def __init__(self, p0: Context, p1: AttributeSet) -> None: ...
    def getSummary(self) -> str: ...
    def setSummary(self, p0: str) -> None: ...
    def findIndexOfValue(self, p0: str) -> int: ...
    @overload
    def setEntries(self, p0: int) -> None: ...
    @overload
    def setEntries(self, p0: Any) -> None: ...
    @overload
    def setEntryValues(self, p0: int) -> None: ...
    @overload
    def setEntryValues(self, p0: Any) -> None: ...
    def getEntryValues(self) -> Any: ...
    def setValueIndex(self, p0: int) -> None: ...
    def getValue(self) -> str: ...
    def setValue(self, p0: str) -> None: ...
    def getEntry(self) -> str: ...
    def getEntries(self) -> Any: ...

from typing import Any, ClassVar, overload
from android.app.Fragment import Fragment
from android.content.Intent import Intent
from android.content.res.Resources import Resources
from android.os.Bundle import Bundle
from android.os.Parcel import Parcel
from android.preference.Preference import Preference
from android.preference.PreferenceFragment import PreferenceFragment
from android.preference.PreferenceManager import PreferenceManager
from android.preference.PreferenceScreen import PreferenceScreen
from android.view.MenuItem import MenuItem
from android.view.View import View

class PreferenceActivity:
    EXTRA_NO_HEADERS: ClassVar[str]
    EXTRA_SHOW_FRAGMENT: ClassVar[str]
    EXTRA_SHOW_FRAGMENT_ARGUMENTS: ClassVar[str]
    EXTRA_SHOW_FRAGMENT_SHORT_TITLE: ClassVar[str]
    EXTRA_SHOW_FRAGMENT_TITLE: ClassVar[str]
    HEADER_ID_UNDEFINED: ClassVar[int]
    DEFAULT_KEYS_DIALER: ClassVar[int]
    DEFAULT_KEYS_DISABLE: ClassVar[int]
    DEFAULT_KEYS_SEARCH_GLOBAL: ClassVar[int]
    DEFAULT_KEYS_SEARCH_LOCAL: ClassVar[int]
    DEFAULT_KEYS_SHORTCUT: ClassVar[int]
    FULLSCREEN_MODE_REQUEST_ENTER: ClassVar[int]
    FULLSCREEN_MODE_REQUEST_EXIT: ClassVar[int]
    OVERRIDE_TRANSITION_CLOSE: ClassVar[int]
    OVERRIDE_TRANSITION_OPEN: ClassVar[int]
    RESULT_CANCELED: ClassVar[int]
    RESULT_FIRST_USER: ClassVar[int]
    RESULT_OK: ClassVar[int]
    TRIM_MEMORY_BACKGROUND: ClassVar[int]
    TRIM_MEMORY_COMPLETE: ClassVar[int]
    TRIM_MEMORY_MODERATE: ClassVar[int]
    TRIM_MEMORY_RUNNING_CRITICAL: ClassVar[int]
    TRIM_MEMORY_RUNNING_LOW: ClassVar[int]
    TRIM_MEMORY_RUNNING_MODERATE: ClassVar[int]
    TRIM_MEMORY_UI_HIDDEN: ClassVar[int]
    ACCESSIBILITY_SERVICE: ClassVar[str]
    ACCOUNT_SERVICE: ClassVar[str]
    ACTIVITY_SERVICE: ClassVar[str]
    ADVANCED_PROTECTION_SERVICE: ClassVar[str]
    ALARM_SERVICE: ClassVar[str]
    APPWIDGET_SERVICE: ClassVar[str]
    APP_FUNCTION_SERVICE: ClassVar[str]
    APP_OPS_SERVICE: ClassVar[str]
    APP_SEARCH_SERVICE: ClassVar[str]
    AUDIO_SERVICE: ClassVar[str]
    BATTERY_SERVICE: ClassVar[str]
    BIND_ABOVE_CLIENT: ClassVar[int]
    BIND_ADJUST_WITH_ACTIVITY: ClassVar[int]
    BIND_ALLOW_ACTIVITY_STARTS: ClassVar[int]
    BIND_ALLOW_OOM_MANAGEMENT: ClassVar[int]
    BIND_AUTO_CREATE: ClassVar[int]
    BIND_DEBUG_UNBIND: ClassVar[int]
    BIND_EXTERNAL_SERVICE: ClassVar[int]
    BIND_EXTERNAL_SERVICE_LONG: ClassVar[int]
    BIND_IMPORTANT: ClassVar[int]
    BIND_INCLUDE_CAPABILITIES: ClassVar[int]
    BIND_NOT_FOREGROUND: ClassVar[int]
    BIND_NOT_PERCEPTIBLE: ClassVar[int]
    BIND_PACKAGE_ISOLATED_PROCESS: ClassVar[int]
    BIND_SHARED_ISOLATED_PROCESS: ClassVar[int]
    BIND_WAIVE_PRIORITY: ClassVar[int]
    BIOMETRIC_SERVICE: ClassVar[str]
    BLOB_STORE_SERVICE: ClassVar[str]
    BLUETOOTH_SERVICE: ClassVar[str]
    BUGREPORT_SERVICE: ClassVar[str]
    CAMERA_SERVICE: ClassVar[str]
    CAPTIONING_SERVICE: ClassVar[str]
    CARRIER_CONFIG_SERVICE: ClassVar[str]
    CLIPBOARD_SERVICE: ClassVar[str]
    COMPANION_DEVICE_SERVICE: ClassVar[str]
    CONNECTIVITY_DIAGNOSTICS_SERVICE: ClassVar[str]
    CONNECTIVITY_SERVICE: ClassVar[str]
    CONSUMER_IR_SERVICE: ClassVar[str]
    CONTACT_KEYS_SERVICE: ClassVar[str]
    CONTEXT_IGNORE_SECURITY: ClassVar[int]
    CONTEXT_INCLUDE_CODE: ClassVar[int]
    CONTEXT_RESTRICTED: ClassVar[int]
    CREDENTIAL_SERVICE: ClassVar[str]
    CROSS_PROFILE_APPS_SERVICE: ClassVar[str]
    DEVICE_ID_DEFAULT: ClassVar[int]
    DEVICE_ID_INVALID: ClassVar[int]
    DEVICE_LOCK_SERVICE: ClassVar[str]
    DEVICE_POLICY_SERVICE: ClassVar[str]
    DISPLAY_HASH_SERVICE: ClassVar[str]
    DISPLAY_SERVICE: ClassVar[str]
    DOMAIN_VERIFICATION_SERVICE: ClassVar[str]
    DOWNLOAD_SERVICE: ClassVar[str]
    DROPBOX_SERVICE: ClassVar[str]
    EUICC_SERVICE: ClassVar[str]
    FILE_INTEGRITY_SERVICE: ClassVar[str]
    FINGERPRINT_SERVICE: ClassVar[str]
    GAME_SERVICE: ClassVar[str]
    GRAMMATICAL_INFLECTION_SERVICE: ClassVar[str]
    HARDWARE_PROPERTIES_SERVICE: ClassVar[str]
    HEALTHCONNECT_SERVICE: ClassVar[str]
    INPUT_METHOD_SERVICE: ClassVar[str]
    INPUT_SERVICE: ClassVar[str]
    IPSEC_SERVICE: ClassVar[str]
    JOB_SCHEDULER_SERVICE: ClassVar[str]
    KEYGUARD_SERVICE: ClassVar[str]
    KEYSTORE_SERVICE: ClassVar[str]
    LAUNCHER_APPS_SERVICE: ClassVar[str]
    LAYOUT_INFLATER_SERVICE: ClassVar[str]
    LOCALE_SERVICE: ClassVar[str]
    LOCATION_SERVICE: ClassVar[str]
    MEDIA_COMMUNICATION_SERVICE: ClassVar[str]
    MEDIA_METRICS_SERVICE: ClassVar[str]
    MEDIA_PROJECTION_SERVICE: ClassVar[str]
    MEDIA_QUALITY_SERVICE: ClassVar[str]
    MEDIA_ROUTER_SERVICE: ClassVar[str]
    MEDIA_SESSION_SERVICE: ClassVar[str]
    MIDI_SERVICE: ClassVar[str]
    MODE_APPEND: ClassVar[int]
    MODE_ENABLE_WRITE_AHEAD_LOGGING: ClassVar[int]
    MODE_MULTI_PROCESS: ClassVar[int]
    MODE_NO_LOCALIZED_COLLATORS: ClassVar[int]
    MODE_PRIVATE: ClassVar[int]
    MODE_WORLD_READABLE: ClassVar[int]
    MODE_WORLD_WRITEABLE: ClassVar[int]
    NETWORK_STATS_SERVICE: ClassVar[str]
    NFC_SERVICE: ClassVar[str]
    NOTIFICATION_SERVICE: ClassVar[str]
    NSD_SERVICE: ClassVar[str]
    OVERLAY_SERVICE: ClassVar[str]
    PEOPLE_SERVICE: ClassVar[str]
    PERFORMANCE_HINT_SERVICE: ClassVar[str]
    PERSISTENT_DATA_BLOCK_SERVICE: ClassVar[str]
    POWER_SERVICE: ClassVar[str]
    PRINT_SERVICE: ClassVar[str]
    PROFILING_SERVICE: ClassVar[str]
    RECEIVER_EXPORTED: ClassVar[int]
    RECEIVER_NOT_EXPORTED: ClassVar[int]
    RECEIVER_VISIBLE_TO_INSTANT_APPS: ClassVar[int]
    RESTRICTIONS_SERVICE: ClassVar[str]
    ROLE_SERVICE: ClassVar[str]
    SATELLITE_SERVICE: ClassVar[str]
    SEARCH_SERVICE: ClassVar[str]
    SECURITY_STATE_SERVICE: ClassVar[str]
    SENSOR_SERVICE: ClassVar[str]
    SHORTCUT_SERVICE: ClassVar[str]
    STATUS_BAR_SERVICE: ClassVar[str]
    STORAGE_SERVICE: ClassVar[str]
    STORAGE_STATS_SERVICE: ClassVar[str]
    SYSTEM_HEALTH_SERVICE: ClassVar[str]
    TELECOM_SERVICE: ClassVar[str]
    TELEPHONY_IMS_SERVICE: ClassVar[str]
    TELEPHONY_SERVICE: ClassVar[str]
    TELEPHONY_SUBSCRIPTION_SERVICE: ClassVar[str]
    TETHERING_SERVICE: ClassVar[str]
    TEXT_CLASSIFICATION_SERVICE: ClassVar[str]
    TEXT_SERVICES_MANAGER_SERVICE: ClassVar[str]
    TV_AD_SERVICE: ClassVar[str]
    TV_INPUT_SERVICE: ClassVar[str]
    TV_INTERACTIVE_APP_SERVICE: ClassVar[str]
    UI_MODE_SERVICE: ClassVar[str]
    USAGE_STATS_SERVICE: ClassVar[str]
    USB_SERVICE: ClassVar[str]
    USER_SERVICE: ClassVar[str]
    VIBRATOR_MANAGER_SERVICE: ClassVar[str]
    VIBRATOR_SERVICE: ClassVar[str]
    VIRTUAL_DEVICE_SERVICE: ClassVar[str]
    VPN_MANAGEMENT_SERVICE: ClassVar[str]
    WALLPAPER_SERVICE: ClassVar[str]
    WIFI_AWARE_SERVICE: ClassVar[str]
    WIFI_P2P_SERVICE: ClassVar[str]
    WIFI_RTT_RANGING_SERVICE: ClassVar[str]
    WIFI_SERVICE: ClassVar[str]
    WINDOW_SERVICE: ClassVar[str]
    def __init__(self) -> None: ...
    def onBackPressed(self) -> None: ...
    def onOptionsItemSelected(self, p0: MenuItem) -> bool: ...
    def setParentTitle(self, p0: str, p1: str, p2: Any) -> None: ...
    def finishPreferencePanel(self, p0: Fragment, p1: int, p2: Intent) -> None: ...
    def hasHeaders(self) -> bool: ...
    def invalidateHeaders(self) -> None: ...
    def isMultiPane(self) -> bool: ...
    def loadHeadersFromResource(self, p0: int, p1: list) -> None: ...
    def onBuildHeaders(self, p0: list) -> None: ...
    def onBuildStartFragmentIntent(self, p0: str, p1: Bundle, p2: int, p3: int) -> Intent: ...
    def onGetInitialHeader(self) -> Any: ...
    def onGetNewHeader(self) -> Any: ...
    def onHeaderClick(self, p0: Any, p1: int) -> None: ...
    def onIsHidingHeaders(self) -> bool: ...
    def onIsMultiPane(self) -> bool: ...
    def setListFooter(self, p0: View) -> None: ...
    def showBreadCrumbs(self, p0: str, p1: str) -> None: ...
    def startPreferenceFragment(self, p0: Fragment, p1: bool) -> None: ...
    def startPreferencePanel(self, p0: str, p1: Bundle, p2: int, p3: str, p4: Fragment, p5: int) -> None: ...
    @overload
    def startWithFragment(self, p0: str, p1: Bundle, p2: Fragment, p3: int) -> None: ...
    @overload
    def startWithFragment(self, p0: str, p1: Bundle, p2: Fragment, p3: int, p4: int, p5: int) -> None: ...
    @overload
    def switchToHeader(self, p0: Any) -> None: ...
    @overload
    def switchToHeader(self, p0: str, p1: Bundle) -> None: ...
    def onPreferenceStartFragment(self, p0: PreferenceFragment, p1: Preference) -> bool: ...
    def addPreferencesFromIntent(self, p0: Intent) -> None: ...
    def addPreferencesFromResource(self, p0: int) -> None: ...
    def findPreference(self, p0: str) -> Preference: ...
    def getPreferenceManager(self) -> PreferenceManager: ...
    def getPreferenceScreen(self) -> PreferenceScreen: ...
    def onPreferenceTreeClick(self, p0: PreferenceScreen, p1: Preference) -> bool: ...
    def setPreferenceScreen(self, p0: PreferenceScreen) -> None: ...
    def onContentChanged(self) -> None: ...

    class Header:
        CREATOR: ClassVar[Any]
        CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
        PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
        breadCrumbShortTitle: str
        breadCrumbShortTitleRes: int
        breadCrumbTitle: str
        breadCrumbTitleRes: int
        extras: Bundle
        fragment: str
        fragmentArguments: Bundle
        iconRes: int
        id: int
        intent: Intent
        summary: str
        summaryRes: int
        title: str
        titleRes: int
        def __init__(self) -> None: ...
        def getSummary(self, p0: Resources) -> str: ...
        def getBreadCrumbTitle(self, p0: Resources) -> str: ...
        def getBreadCrumbShortTitle(self, p0: Resources) -> str: ...
        def describeContents(self) -> int: ...
        def readFromParcel(self, p0: Parcel) -> None: ...
        def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
        def getTitle(self, p0: Resources) -> str: ...

from typing import Any, ClassVar, overload
from android.content.Context import Context
from android.util.AttributeSet import AttributeSet

class CheckBoxPreference:
    DEFAULT_ORDER: ClassVar[int]
    @overload
    def __init__(self, p0: Context) -> None: ...
    @overload
    def __init__(self, p0: Context, p1: AttributeSet, p2: int, p3: int) -> None: ...
    @overload
    def __init__(self, p0: Context, p1: AttributeSet, p2: int) -> None: ...
    @overload
    def __init__(self, p0: Context, p1: AttributeSet) -> None: ...

from typing import Any, ClassVar, overload
from android.app.Dialog import Dialog
from android.content.Context import Context
from android.content.DialogInterface import DialogInterface
from android.graphics.drawable.Drawable import Drawable
from android.util.AttributeSet import AttributeSet

class DialogPreference:
    DEFAULT_ORDER: ClassVar[int]
    @overload
    def __init__(self, p0: Context, p1: AttributeSet) -> None: ...
    @overload
    def __init__(self, p0: Context, p1: AttributeSet, p2: int) -> None: ...
    @overload
    def __init__(self, p0: Context) -> None: ...
    @overload
    def __init__(self, p0: Context, p1: AttributeSet, p2: int, p3: int) -> None: ...
    def getNegativeButtonText(self) -> str: ...
    def getDialog(self) -> Dialog: ...
    def getDialogLayoutResource(self) -> int: ...
    def getDialogIcon(self) -> Drawable: ...
    def getDialogMessage(self) -> str: ...
    def getDialogTitle(self) -> str: ...
    def getPositiveButtonText(self) -> str: ...
    def onActivityDestroy(self) -> None: ...
    @overload
    def setDialogIcon(self, p0: int) -> None: ...
    @overload
    def setDialogIcon(self, p0: Drawable) -> None: ...
    def setDialogLayoutResource(self, p0: int) -> None: ...
    @overload
    def setDialogMessage(self, p0: int) -> None: ...
    @overload
    def setDialogMessage(self, p0: str) -> None: ...
    @overload
    def setDialogTitle(self, p0: int) -> None: ...
    @overload
    def setDialogTitle(self, p0: str) -> None: ...
    @overload
    def setNegativeButtonText(self, p0: int) -> None: ...
    @overload
    def setNegativeButtonText(self, p0: str) -> None: ...
    @overload
    def setPositiveButtonText(self, p0: str) -> None: ...
    @overload
    def setPositiveButtonText(self, p0: int) -> None: ...
    def onClick(self, p0: DialogInterface, p1: int) -> None: ...
    def onDismiss(self, p0: DialogInterface) -> None: ...

from typing import Any, ClassVar, overload
from android.content.Context import Context
from android.content.Intent import Intent
from android.content.SharedPreferences import SharedPreferences
from android.graphics.drawable.Drawable import Drawable
from android.os.Bundle import Bundle
from android.os.Parcel import Parcel
from android.os.Parcelable import Parcelable
from android.preference.PreferenceDataStore import PreferenceDataStore
from android.preference.PreferenceGroup import PreferenceGroup
from android.preference.PreferenceManager import PreferenceManager
from android.util.AttributeSet import AttributeSet
from android.view.AbsSavedState import AbsSavedState
from android.view.View import View
from android.view.ViewGroup import ViewGroup

class Preference:
    DEFAULT_ORDER: ClassVar[int]
    @overload
    def __init__(self, p0: Context, p1: AttributeSet, p2: int, p3: int) -> None: ...
    @overload
    def __init__(self, p0: Context, p1: AttributeSet, p2: int) -> None: ...
    @overload
    def __init__(self, p0: Context, p1: AttributeSet) -> None: ...
    @overload
    def __init__(self, p0: Context) -> None: ...
    def setKey(self, p0: str) -> None: ...
    def setOrder(self, p0: int) -> None: ...
    def getSummary(self) -> str: ...
    @overload
    def setSummary(self, p0: str) -> None: ...
    @overload
    def setSummary(self, p0: int) -> None: ...
    def getLayoutResource(self) -> int: ...
    def setLayoutResource(self, p0: int) -> None: ...
    def hasKey(self) -> bool: ...
    def getPersistedStringSet(self, p0: set) -> set: ...
    def getPreferenceDataStore(self) -> PreferenceDataStore: ...
    def getShouldDisableView(self) -> bool: ...
    def getTitleRes(self) -> int: ...
    def getWidgetLayoutResource(self) -> int: ...
    def isIconSpaceReserved(self) -> bool: ...
    def isRecycleEnabled(self) -> bool: ...
    def isSingleLineTitle(self) -> bool: ...
    def notifyDependencyChange(self, p0: bool) -> None: ...
    def onDependencyChanged(self, p0: "Preference", p1: bool) -> None: ...
    def onParentChanged(self, p0: "Preference", p1: bool) -> None: ...
    def peekExtras(self) -> Bundle: ...
    def persistStringSet(self, p0: set) -> bool: ...
    def setDefaultValue(self, p0: Any) -> None: ...
    def setDependency(self, p0: str) -> None: ...
    def setFragment(self, p0: str) -> None: ...
    def setIconSpaceReserved(self, p0: bool) -> None: ...
    def setOnPreferenceChangeListener(self, p0: Any) -> None: ...
    def setOnPreferenceClickListener(self, p0: Any) -> None: ...
    def setPreferenceDataStore(self, p0: PreferenceDataStore) -> None: ...
    def setRecycleEnabled(self, p0: bool) -> None: ...
    def setSelectable(self, p0: bool) -> None: ...
    def setShouldDisableView(self, p0: bool) -> None: ...
    def setSingleLineTitle(self, p0: bool) -> None: ...
    def setWidgetLayoutResource(self, p0: int) -> None: ...
    def shouldCommit(self) -> bool: ...
    def shouldDisableDependents(self) -> bool: ...
    def isPersistent(self) -> bool: ...
    def setPersistent(self, p0: bool) -> None: ...
    def getPreferenceManager(self) -> PreferenceManager: ...
    def getDependency(self) -> str: ...
    def getEditor(self) -> Any: ...
    def getOnPreferenceChangeListener(self) -> Any: ...
    def getOnPreferenceClickListener(self) -> Any: ...
    def toString(self) -> str: ...
    @overload
    def compareTo(self, p0: "Preference") -> int: ...
    @overload
    def compareTo(self, p0: Any) -> int: ...
    def isEnabled(self) -> bool: ...
    def getKey(self) -> str: ...
    def getParent(self) -> PreferenceGroup: ...
    def getContext(self) -> Context: ...
    def getSharedPreferences(self) -> SharedPreferences: ...
    def restoreHierarchyState(self, p0: Bundle) -> None: ...
    def saveHierarchyState(self, p0: Bundle) -> None: ...
    def getExtras(self) -> Bundle: ...
    def getIntent(self) -> Intent: ...
    @overload
    def setIcon(self, p0: int) -> None: ...
    @overload
    def setIcon(self, p0: Drawable) -> None: ...
    def setIntent(self, p0: Intent) -> None: ...
    def setEnabled(self, p0: bool) -> None: ...
    def isSelectable(self) -> bool: ...
    def getView(self, p0: View, p1: ViewGroup) -> View: ...
    def getIcon(self) -> Drawable: ...
    def getOrder(self) -> int: ...
    def getFragment(self) -> str: ...
    def getTitle(self) -> str: ...
    @overload
    def setTitle(self, p0: str) -> None: ...
    @overload
    def setTitle(self, p0: int) -> None: ...

    class OnPreferenceClickListener:
        def onPreferenceClick(self, p0: "Preference") -> bool: ...

    class OnPreferenceChangeListener:
        def onPreferenceChange(self, p0: "Preference", p1: Any) -> bool: ...

    class BaseSavedState:
        CREATOR: ClassVar[Any]
        CREATOR: ClassVar[Any]
        EMPTY_STATE: ClassVar[AbsSavedState]
        CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
        PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
        @overload
        def __init__(self, p0: Parcel) -> None: ...
        @overload
        def __init__(self, p0: Parcelable) -> None: ...

from typing import Any, ClassVar, overload

class PreferenceDataStore:
    def getStringSet(self, p0: str, p1: set) -> set: ...
    def getBoolean(self, p0: str, p1: bool) -> bool: ...
    def putBoolean(self, p0: str, p1: bool) -> None: ...
    def getInt(self, p0: str, p1: int) -> int: ...
    def putInt(self, p0: str, p1: int) -> None: ...
    def getLong(self, p0: str, p1: int) -> int: ...
    def putLong(self, p0: str, p1: int) -> None: ...
    def getFloat(self, p0: str, p1: float) -> float: ...
    def putFloat(self, p0: str, p1: float) -> None: ...
    def putStringSet(self, p0: str, p1: set) -> None: ...
    def getString(self, p0: str, p1: str) -> str: ...
    def putString(self, p0: str, p1: str) -> None: ...

from typing import Any, ClassVar, overload
from android.content.Context import Context
from android.content.Intent import Intent
from android.content.SharedPreferences import SharedPreferences
from android.preference.Preference import Preference
from android.preference.PreferenceDataStore import PreferenceDataStore
from android.preference.PreferenceScreen import PreferenceScreen

class PreferenceManager:
    KEY_HAS_SET_DEFAULT_VALUES: ClassVar[str]
    METADATA_KEY_PREFERENCES: ClassVar[str]
    def getPreferenceDataStore(self) -> PreferenceDataStore: ...
    def setPreferenceDataStore(self, p0: PreferenceDataStore) -> None: ...
    def createPreferenceScreen(self, p0: Context) -> PreferenceScreen: ...
    @staticmethod
    def getDefaultSharedPreferences(p0: Context) -> SharedPreferences: ...
    @staticmethod
    def getDefaultSharedPreferencesName(p0: Context) -> str: ...
    def getSharedPreferencesMode(self) -> int: ...
    def getSharedPreferencesName(self) -> str: ...
    def isStorageDefault(self) -> bool: ...
    def isStorageDeviceProtected(self) -> bool: ...
    @overload
    @staticmethod
    def setDefaultValues(p0: Context, p1: int, p2: bool) -> None: ...
    @overload
    @staticmethod
    def setDefaultValues(p0: Context, p1: str, p2: int, p3: int, p4: bool) -> None: ...
    def setSharedPreferencesMode(self, p0: int) -> None: ...
    def setSharedPreferencesName(self, p0: str) -> None: ...
    def setStorageDefault(self) -> None: ...
    def setStorageDeviceProtected(self) -> None: ...
    def findPreference(self, p0: str) -> Preference: ...
    def getSharedPreferences(self) -> SharedPreferences: ...

    class OnActivityStopListener:
        def onActivityStop(self) -> None: ...

    class OnActivityResultListener:
        def onActivityResult(self, p0: int, p1: int, p2: Intent) -> bool: ...

    class OnActivityDestroyListener:
        def onActivityDestroy(self) -> None: ...

from typing import Any, ClassVar, overload
from android.content.Context import Context
from android.util.AttributeSet import AttributeSet

class SwitchPreference:
    DEFAULT_ORDER: ClassVar[int]
    @overload
    def __init__(self, p0: Context) -> None: ...
    @overload
    def __init__(self, p0: Context, p1: AttributeSet) -> None: ...
    @overload
    def __init__(self, p0: Context, p1: AttributeSet, p2: int) -> None: ...
    @overload
    def __init__(self, p0: Context, p1: AttributeSet, p2: int, p3: int) -> None: ...
    def getSwitchTextOff(self) -> str: ...
    def getSwitchTextOn(self) -> str: ...
    @overload
    def setSwitchTextOff(self, p0: str) -> None: ...
    @overload
    def setSwitchTextOff(self, p0: int) -> None: ...
    @overload
    def setSwitchTextOn(self, p0: int) -> None: ...
    @overload
    def setSwitchTextOn(self, p0: str) -> None: ...

