from jnius import JavaClass, JavaInterface, MetaJavaClass, JavaMethod, JavaStaticMethod, JavaMultipleMethod, JavaField, JavaStaticField

class Int2(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "android/renderscript/Int2"
    __javaconstructor__ = [("()V", False), ("(II)V", False)]
    x = JavaField("I")
    y = JavaField("I")

class Byte2(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "android/renderscript/Byte2"
    __javaconstructor__ = [("()V", False), ("(BB)V", False)]
    x = JavaField("B")
    y = JavaField("B")

class Short4(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "android/renderscript/Short4"
    __javaconstructor__ = [("()V", False), ("(SSSS)V", False)]
    w = JavaField("S")
    x = JavaField("S")
    y = JavaField("S")
    z = JavaField("S")

class Long2(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "android/renderscript/Long2"
    __javaconstructor__ = [("()V", False), ("(JJ)V", False)]
    x = JavaField("J")
    y = JavaField("J")

class Matrix3f(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "android/renderscript/Matrix3f"
    __javaconstructor__ = [("([F)V", False), ("()V", False)]
    loadIdentity = JavaMethod("()V")
    loadMultiply = JavaMethod("(Landroid/renderscript/Matrix3f;Landroid/renderscript/Matrix3f;)V")
    loadRotate = JavaMultipleMethod([("(F)V", False, False), ("(FFFF)V", False, False)])
    loadScale = JavaMultipleMethod([("(FFF)V", False, False), ("(FF)V", False, False)])
    loadTranslate = JavaMethod("(FF)V")
    transpose = JavaMethod("()V")
    getArray = JavaMethod("()[F")
    multiply = JavaMethod("(Landroid/renderscript/Matrix3f;)V")
    get = JavaMethod("(II)F")
    load = JavaMethod("(Landroid/renderscript/Matrix3f;)V")
    scale = JavaMultipleMethod([("(FFF)V", False, False), ("(FF)V", False, False)])
    set = JavaMethod("(IIF)V")
    translate = JavaMethod("(FF)V")
    rotate = JavaMultipleMethod([("(FFFF)V", False, False), ("(F)V", False, False)])

class RenderScript(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "android/renderscript/RenderScript"
    CREATE_FLAG_LOW_LATENCY = JavaStaticField("I")
    CREATE_FLAG_LOW_POWER = JavaStaticField("I")
    CREATE_FLAG_NONE = JavaStaticField("I")
    sendMessage = JavaMethod("(I[I)V")
    getErrorHandler = JavaMethod("()Landroid/renderscript/RenderScript$RSErrorHandler;")
    contextDump = JavaMethod("()V")
    createMultiContext = JavaStaticMethod("(Landroid/content/Context;Landroid/renderscript/RenderScript$ContextType;II)Landroid/renderscript/RenderScript;")
    getMessageHandler = JavaMethod("()Landroid/renderscript/RenderScript$RSMessageHandler;")
    releaseAllContexts = JavaStaticMethod("()V")
    setMessageHandler = JavaMethod("(Landroid/renderscript/RenderScript$RSMessageHandler;)V")
    create = JavaMultipleMethod([("(Landroid/content/Context;Landroid/renderscript/RenderScript$ContextType;)Landroid/renderscript/RenderScript;", True, False), ("(Landroid/content/Context;Landroid/renderscript/RenderScript$ContextType;I)Landroid/renderscript/RenderScript;", True, False), ("(Landroid/content/Context;)Landroid/renderscript/RenderScript;", True, False)])
    setPriority = JavaMethod("(Landroid/renderscript/RenderScript$Priority;)V")
    destroy = JavaMethod("()V")
    getApplicationContext = JavaMethod("()Landroid/content/Context;")
    setErrorHandler = JavaMethod("(Landroid/renderscript/RenderScript$RSErrorHandler;)V")
    getMinorVersion = JavaStaticMethod("()J")
    finish = JavaMethod("()V")

    class RSMessageHandler(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "android/renderscript/RenderScript$RSMessageHandler"
        __javaconstructor__ = [("()V", False)]
        run = JavaMethod("()V")

    class RSErrorHandler(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "android/renderscript/RenderScript$RSErrorHandler"
        __javaconstructor__ = [("()V", False)]
        run = JavaMethod("()V")

    class Priority(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "android/renderscript/RenderScript$Priority"
        LOW = JavaStaticField("Landroid/renderscript/RenderScript$Priority;")
        NORMAL = JavaStaticField("Landroid/renderscript/RenderScript$Priority;")
        values = JavaStaticMethod("()[Landroid/renderscript/RenderScript$Priority;")
        valueOf = JavaStaticMethod("(Ljava/lang/String;)Landroid/renderscript/RenderScript$Priority;")
        LOW = JavaStaticField("Landroid/renderscript/RenderScript$Priority;")
        NORMAL = JavaStaticField("Landroid/renderscript/RenderScript$Priority;")

    class ContextType(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "android/renderscript/RenderScript$ContextType"
        DEBUG = JavaStaticField("Landroid/renderscript/RenderScript$ContextType;")
        NORMAL = JavaStaticField("Landroid/renderscript/RenderScript$ContextType;")
        PROFILE = JavaStaticField("Landroid/renderscript/RenderScript$ContextType;")
        values = JavaStaticMethod("()[Landroid/renderscript/RenderScript$ContextType;")
        valueOf = JavaStaticMethod("(Ljava/lang/String;)Landroid/renderscript/RenderScript$ContextType;")
        DEBUG = JavaStaticField("Landroid/renderscript/RenderScript$ContextType;")
        NORMAL = JavaStaticField("Landroid/renderscript/RenderScript$ContextType;")
        PROFILE = JavaStaticField("Landroid/renderscript/RenderScript$ContextType;")

class Short3(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "android/renderscript/Short3"
    __javaconstructor__ = [("()V", False), ("(SSS)V", False)]
    x = JavaField("S")
    y = JavaField("S")
    z = JavaField("S")

class Float2(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "android/renderscript/Float2"
    __javaconstructor__ = [("()V", False), ("(FF)V", False)]
    x = JavaField("F")
    y = JavaField("F")

class Int3(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "android/renderscript/Int3"
    __javaconstructor__ = [("()V", False), ("(III)V", False)]
    x = JavaField("I")
    y = JavaField("I")
    z = JavaField("I")

class ScriptIntrinsic(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "android/renderscript/ScriptIntrinsic"

class ScriptIntrinsicLUT(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "android/renderscript/ScriptIntrinsicLUT"
    getKernelID = JavaMethod("()Landroid/renderscript/Script$KernelID;")
    setRed = JavaMethod("(II)V")
    setBlue = JavaMethod("(II)V")
    setGreen = JavaMethod("(II)V")
    create = JavaStaticMethod("(Landroid/renderscript/RenderScript;Landroid/renderscript/Element;)Landroid/renderscript/ScriptIntrinsicLUT;")
    forEach = JavaMultipleMethod([("(Landroid/renderscript/Allocation;Landroid/renderscript/Allocation;)V", False, False), ("(Landroid/renderscript/Allocation;Landroid/renderscript/Allocation;Landroid/renderscript/Script$LaunchOptions;)V", False, False)])
    destroy = JavaMethod("()V")
    setAlpha = JavaMethod("(II)V")

class ScriptIntrinsicHistogram(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "android/renderscript/ScriptIntrinsicHistogram"
    getFieldID_Input = JavaMethod("()Landroid/renderscript/Script$FieldID;")
    forEach_Dot = JavaMultipleMethod([("(Landroid/renderscript/Allocation;)V", False, False), ("(Landroid/renderscript/Allocation;Landroid/renderscript/Script$LaunchOptions;)V", False, False)])
    getKernelID_Separate = JavaMethod("()Landroid/renderscript/Script$KernelID;")
    setDotCoefficients = JavaMethod("(FFFF)V")
    create = JavaStaticMethod("(Landroid/renderscript/RenderScript;Landroid/renderscript/Element;)Landroid/renderscript/ScriptIntrinsicHistogram;")
    forEach = JavaMultipleMethod([("(Landroid/renderscript/Allocation;)V", False, False), ("(Landroid/renderscript/Allocation;Landroid/renderscript/Script$LaunchOptions;)V", False, False)])
    setOutput = JavaMethod("(Landroid/renderscript/Allocation;)V")

class ScriptIntrinsic3DLUT(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "android/renderscript/ScriptIntrinsic3DLUT"
    setLUT = JavaMethod("(Landroid/renderscript/Allocation;)V")
    getKernelID = JavaMethod("()Landroid/renderscript/Script$KernelID;")
    create = JavaStaticMethod("(Landroid/renderscript/RenderScript;Landroid/renderscript/Element;)Landroid/renderscript/ScriptIntrinsic3DLUT;")
    forEach = JavaMultipleMethod([("(Landroid/renderscript/Allocation;Landroid/renderscript/Allocation;)V", False, False), ("(Landroid/renderscript/Allocation;Landroid/renderscript/Allocation;Landroid/renderscript/Script$LaunchOptions;)V", False, False)])

class Double4(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "android/renderscript/Double4"
    __javaconstructor__ = [("()V", False), ("(DDDD)V", False)]
    w = JavaField("D")
    x = JavaField("D")
    y = JavaField("D")
    z = JavaField("D")

class ScriptIntrinsicBLAS(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "android/renderscript/ScriptIntrinsicBLAS"
    CONJ_TRANSPOSE = JavaStaticField("I")
    LEFT = JavaStaticField("I")
    LOWER = JavaStaticField("I")
    NON_UNIT = JavaStaticField("I")
    NO_TRANSPOSE = JavaStaticField("I")
    RIGHT = JavaStaticField("I")
    TRANSPOSE = JavaStaticField("I")
    UNIT = JavaStaticField("I")
    UPPER = JavaStaticField("I")
    CSYRK = JavaMethod("(IILandroid/renderscript/Float2;Landroid/renderscript/Allocation;Landroid/renderscript/Float2;Landroid/renderscript/Allocation;)V")
    CHERK = JavaMethod("(IIFLandroid/renderscript/Allocation;FLandroid/renderscript/Allocation;)V")
    CGERC = JavaMethod("(Landroid/renderscript/Float2;Landroid/renderscript/Allocation;ILandroid/renderscript/Allocation;ILandroid/renderscript/Allocation;)V")
    CGEMV = JavaMethod("(ILandroid/renderscript/Float2;Landroid/renderscript/Allocation;Landroid/renderscript/Allocation;ILandroid/renderscript/Float2;Landroid/renderscript/Allocation;I)V")
    CSYR2K = JavaMethod("(IILandroid/renderscript/Float2;Landroid/renderscript/Allocation;Landroid/renderscript/Allocation;Landroid/renderscript/Float2;Landroid/renderscript/Allocation;)V")
    CHEMV = JavaMethod("(ILandroid/renderscript/Float2;Landroid/renderscript/Allocation;Landroid/renderscript/Allocation;ILandroid/renderscript/Float2;Landroid/renderscript/Allocation;I)V")
    BNNM = JavaMethod("(Landroid/renderscript/Allocation;ILandroid/renderscript/Allocation;ILandroid/renderscript/Allocation;II)V")
    CTBSV = JavaMethod("(IIIILandroid/renderscript/Allocation;Landroid/renderscript/Allocation;I)V")
    CTRMM = JavaMethod("(IIIILandroid/renderscript/Float2;Landroid/renderscript/Allocation;Landroid/renderscript/Allocation;)V")
    CTRMV = JavaMethod("(IIILandroid/renderscript/Allocation;Landroid/renderscript/Allocation;I)V")
    CTRSM = JavaMethod("(IIIILandroid/renderscript/Float2;Landroid/renderscript/Allocation;Landroid/renderscript/Allocation;)V")
    DGEMM = JavaMethod("(IIDLandroid/renderscript/Allocation;Landroid/renderscript/Allocation;DLandroid/renderscript/Allocation;)V")
    DGER = JavaMethod("(DLandroid/renderscript/Allocation;ILandroid/renderscript/Allocation;ILandroid/renderscript/Allocation;)V")
    CTBMV = JavaMethod("(IIIILandroid/renderscript/Allocation;Landroid/renderscript/Allocation;I)V")
    CTRSV = JavaMethod("(IIILandroid/renderscript/Allocation;Landroid/renderscript/Allocation;I)V")
    CTPMV = JavaMethod("(IIILandroid/renderscript/Allocation;Landroid/renderscript/Allocation;I)V")
    DGEMV = JavaMethod("(IDLandroid/renderscript/Allocation;Landroid/renderscript/Allocation;IDLandroid/renderscript/Allocation;I)V")
    CTPSV = JavaMethod("(IIILandroid/renderscript/Allocation;Landroid/renderscript/Allocation;I)V")
    DGBMV = JavaMethod("(IIIDLandroid/renderscript/Allocation;Landroid/renderscript/Allocation;IDLandroid/renderscript/Allocation;I)V")
    CHEMM = JavaMethod("(IILandroid/renderscript/Float2;Landroid/renderscript/Allocation;Landroid/renderscript/Allocation;Landroid/renderscript/Float2;Landroid/renderscript/Allocation;)V")
    CHPMV = JavaMethod("(ILandroid/renderscript/Float2;Landroid/renderscript/Allocation;Landroid/renderscript/Allocation;ILandroid/renderscript/Float2;Landroid/renderscript/Allocation;I)V")
    CGERU = JavaMethod("(Landroid/renderscript/Float2;Landroid/renderscript/Allocation;ILandroid/renderscript/Allocation;ILandroid/renderscript/Allocation;)V")
    CGBMV = JavaMethod("(IIILandroid/renderscript/Float2;Landroid/renderscript/Allocation;Landroid/renderscript/Allocation;ILandroid/renderscript/Float2;Landroid/renderscript/Allocation;I)V")
    CHPR = JavaMethod("(IFLandroid/renderscript/Allocation;ILandroid/renderscript/Allocation;)V")
    CSYMM = JavaMethod("(IILandroid/renderscript/Float2;Landroid/renderscript/Allocation;Landroid/renderscript/Allocation;Landroid/renderscript/Float2;Landroid/renderscript/Allocation;)V")
    CHPR2 = JavaMethod("(ILandroid/renderscript/Float2;Landroid/renderscript/Allocation;ILandroid/renderscript/Allocation;ILandroid/renderscript/Allocation;)V")
    CHER2 = JavaMethod("(ILandroid/renderscript/Float2;Landroid/renderscript/Allocation;ILandroid/renderscript/Allocation;ILandroid/renderscript/Allocation;)V")
    CHER2K = JavaMethod("(IILandroid/renderscript/Float2;Landroid/renderscript/Allocation;Landroid/renderscript/Allocation;FLandroid/renderscript/Allocation;)V")
    CHER = JavaMethod("(IFLandroid/renderscript/Allocation;ILandroid/renderscript/Allocation;)V")
    CGEMM = JavaMethod("(IILandroid/renderscript/Float2;Landroid/renderscript/Allocation;Landroid/renderscript/Allocation;Landroid/renderscript/Float2;Landroid/renderscript/Allocation;)V")
    CHBMV = JavaMethod("(IILandroid/renderscript/Float2;Landroid/renderscript/Allocation;Landroid/renderscript/Allocation;ILandroid/renderscript/Float2;Landroid/renderscript/Allocation;I)V")
    DSBMV = JavaMethod("(IIDLandroid/renderscript/Allocation;Landroid/renderscript/Allocation;IDLandroid/renderscript/Allocation;I)V")
    DSPMV = JavaMethod("(IDLandroid/renderscript/Allocation;Landroid/renderscript/Allocation;IDLandroid/renderscript/Allocation;I)V")
    DSPR = JavaMethod("(IDLandroid/renderscript/Allocation;ILandroid/renderscript/Allocation;)V")
    DSPR2 = JavaMethod("(IDLandroid/renderscript/Allocation;ILandroid/renderscript/Allocation;ILandroid/renderscript/Allocation;)V")
    DSYMM = JavaMethod("(IIDLandroid/renderscript/Allocation;Landroid/renderscript/Allocation;DLandroid/renderscript/Allocation;)V")
    DSYMV = JavaMethod("(IDLandroid/renderscript/Allocation;Landroid/renderscript/Allocation;IDLandroid/renderscript/Allocation;I)V")
    DSYR = JavaMethod("(IDLandroid/renderscript/Allocation;ILandroid/renderscript/Allocation;)V")
    DSYR2 = JavaMethod("(IDLandroid/renderscript/Allocation;ILandroid/renderscript/Allocation;ILandroid/renderscript/Allocation;)V")
    DSYR2K = JavaMethod("(IIDLandroid/renderscript/Allocation;Landroid/renderscript/Allocation;DLandroid/renderscript/Allocation;)V")
    DSYRK = JavaMethod("(IIDLandroid/renderscript/Allocation;DLandroid/renderscript/Allocation;)V")
    DTBMV = JavaMethod("(IIIILandroid/renderscript/Allocation;Landroid/renderscript/Allocation;I)V")
    DTBSV = JavaMethod("(IIIILandroid/renderscript/Allocation;Landroid/renderscript/Allocation;I)V")
    DTPMV = JavaMethod("(IIILandroid/renderscript/Allocation;Landroid/renderscript/Allocation;I)V")
    DTPSV = JavaMethod("(IIILandroid/renderscript/Allocation;Landroid/renderscript/Allocation;I)V")
    DTRMM = JavaMethod("(IIIIDLandroid/renderscript/Allocation;Landroid/renderscript/Allocation;)V")
    DTRMV = JavaMethod("(IIILandroid/renderscript/Allocation;Landroid/renderscript/Allocation;I)V")
    DTRSM = JavaMethod("(IIIIDLandroid/renderscript/Allocation;Landroid/renderscript/Allocation;)V")
    DTRSV = JavaMethod("(IIILandroid/renderscript/Allocation;Landroid/renderscript/Allocation;I)V")
    SGBMV = JavaMethod("(IIIFLandroid/renderscript/Allocation;Landroid/renderscript/Allocation;IFLandroid/renderscript/Allocation;I)V")
    SGEMM = JavaMethod("(IIFLandroid/renderscript/Allocation;Landroid/renderscript/Allocation;FLandroid/renderscript/Allocation;)V")
    SGEMV = JavaMethod("(IFLandroid/renderscript/Allocation;Landroid/renderscript/Allocation;IFLandroid/renderscript/Allocation;I)V")
    SGER = JavaMethod("(FLandroid/renderscript/Allocation;ILandroid/renderscript/Allocation;ILandroid/renderscript/Allocation;)V")
    SSBMV = JavaMethod("(IIFLandroid/renderscript/Allocation;Landroid/renderscript/Allocation;IFLandroid/renderscript/Allocation;I)V")
    SSPMV = JavaMethod("(IFLandroid/renderscript/Allocation;Landroid/renderscript/Allocation;IFLandroid/renderscript/Allocation;I)V")
    SSPR = JavaMethod("(IFLandroid/renderscript/Allocation;ILandroid/renderscript/Allocation;)V")
    SSPR2 = JavaMethod("(IFLandroid/renderscript/Allocation;ILandroid/renderscript/Allocation;ILandroid/renderscript/Allocation;)V")
    SSYMM = JavaMethod("(IIFLandroid/renderscript/Allocation;Landroid/renderscript/Allocation;FLandroid/renderscript/Allocation;)V")
    SSYMV = JavaMethod("(IFLandroid/renderscript/Allocation;Landroid/renderscript/Allocation;IFLandroid/renderscript/Allocation;I)V")
    SSYR = JavaMethod("(IFLandroid/renderscript/Allocation;ILandroid/renderscript/Allocation;)V")
    SSYR2 = JavaMethod("(IFLandroid/renderscript/Allocation;ILandroid/renderscript/Allocation;ILandroid/renderscript/Allocation;)V")
    SSYR2K = JavaMethod("(IIFLandroid/renderscript/Allocation;Landroid/renderscript/Allocation;FLandroid/renderscript/Allocation;)V")
    SSYRK = JavaMethod("(IIFLandroid/renderscript/Allocation;FLandroid/renderscript/Allocation;)V")
    STBMV = JavaMethod("(IIIILandroid/renderscript/Allocation;Landroid/renderscript/Allocation;I)V")
    STBSV = JavaMethod("(IIIILandroid/renderscript/Allocation;Landroid/renderscript/Allocation;I)V")
    STPMV = JavaMethod("(IIILandroid/renderscript/Allocation;Landroid/renderscript/Allocation;I)V")
    STPSV = JavaMethod("(IIILandroid/renderscript/Allocation;Landroid/renderscript/Allocation;I)V")
    STRMM = JavaMethod("(IIIIFLandroid/renderscript/Allocation;Landroid/renderscript/Allocation;)V")
    STRMV = JavaMethod("(IIILandroid/renderscript/Allocation;Landroid/renderscript/Allocation;I)V")
    STRSM = JavaMethod("(IIIIFLandroid/renderscript/Allocation;Landroid/renderscript/Allocation;)V")
    STRSV = JavaMethod("(IIILandroid/renderscript/Allocation;Landroid/renderscript/Allocation;I)V")
    ZGBMV = JavaMethod("(IIILandroid/renderscript/Double2;Landroid/renderscript/Allocation;Landroid/renderscript/Allocation;ILandroid/renderscript/Double2;Landroid/renderscript/Allocation;I)V")
    ZGEMM = JavaMethod("(IILandroid/renderscript/Double2;Landroid/renderscript/Allocation;Landroid/renderscript/Allocation;Landroid/renderscript/Double2;Landroid/renderscript/Allocation;)V")
    ZGEMV = JavaMethod("(ILandroid/renderscript/Double2;Landroid/renderscript/Allocation;Landroid/renderscript/Allocation;ILandroid/renderscript/Double2;Landroid/renderscript/Allocation;I)V")
    ZGERC = JavaMethod("(Landroid/renderscript/Double2;Landroid/renderscript/Allocation;ILandroid/renderscript/Allocation;ILandroid/renderscript/Allocation;)V")
    ZGERU = JavaMethod("(Landroid/renderscript/Double2;Landroid/renderscript/Allocation;ILandroid/renderscript/Allocation;ILandroid/renderscript/Allocation;)V")
    ZHBMV = JavaMethod("(IILandroid/renderscript/Double2;Landroid/renderscript/Allocation;Landroid/renderscript/Allocation;ILandroid/renderscript/Double2;Landroid/renderscript/Allocation;I)V")
    ZHEMM = JavaMethod("(IILandroid/renderscript/Double2;Landroid/renderscript/Allocation;Landroid/renderscript/Allocation;Landroid/renderscript/Double2;Landroid/renderscript/Allocation;)V")
    ZHEMV = JavaMethod("(ILandroid/renderscript/Double2;Landroid/renderscript/Allocation;Landroid/renderscript/Allocation;ILandroid/renderscript/Double2;Landroid/renderscript/Allocation;I)V")
    ZHER = JavaMethod("(IDLandroid/renderscript/Allocation;ILandroid/renderscript/Allocation;)V")
    ZHER2 = JavaMethod("(ILandroid/renderscript/Double2;Landroid/renderscript/Allocation;ILandroid/renderscript/Allocation;ILandroid/renderscript/Allocation;)V")
    ZHER2K = JavaMethod("(IILandroid/renderscript/Double2;Landroid/renderscript/Allocation;Landroid/renderscript/Allocation;DLandroid/renderscript/Allocation;)V")
    ZHERK = JavaMethod("(IIDLandroid/renderscript/Allocation;DLandroid/renderscript/Allocation;)V")
    ZHPMV = JavaMethod("(ILandroid/renderscript/Double2;Landroid/renderscript/Allocation;Landroid/renderscript/Allocation;ILandroid/renderscript/Double2;Landroid/renderscript/Allocation;I)V")
    ZHPR = JavaMethod("(IDLandroid/renderscript/Allocation;ILandroid/renderscript/Allocation;)V")
    ZHPR2 = JavaMethod("(ILandroid/renderscript/Double2;Landroid/renderscript/Allocation;ILandroid/renderscript/Allocation;ILandroid/renderscript/Allocation;)V")
    ZSYMM = JavaMethod("(IILandroid/renderscript/Double2;Landroid/renderscript/Allocation;Landroid/renderscript/Allocation;Landroid/renderscript/Double2;Landroid/renderscript/Allocation;)V")
    ZSYR2K = JavaMethod("(IILandroid/renderscript/Double2;Landroid/renderscript/Allocation;Landroid/renderscript/Allocation;Landroid/renderscript/Double2;Landroid/renderscript/Allocation;)V")
    ZSYRK = JavaMethod("(IILandroid/renderscript/Double2;Landroid/renderscript/Allocation;Landroid/renderscript/Double2;Landroid/renderscript/Allocation;)V")
    ZTBMV = JavaMethod("(IIIILandroid/renderscript/Allocation;Landroid/renderscript/Allocation;I)V")
    ZTBSV = JavaMethod("(IIIILandroid/renderscript/Allocation;Landroid/renderscript/Allocation;I)V")
    ZTPMV = JavaMethod("(IIILandroid/renderscript/Allocation;Landroid/renderscript/Allocation;I)V")
    ZTPSV = JavaMethod("(IIILandroid/renderscript/Allocation;Landroid/renderscript/Allocation;I)V")
    ZTRMM = JavaMethod("(IIIILandroid/renderscript/Double2;Landroid/renderscript/Allocation;Landroid/renderscript/Allocation;)V")
    ZTRMV = JavaMethod("(IIILandroid/renderscript/Allocation;Landroid/renderscript/Allocation;I)V")
    ZTRSM = JavaMethod("(IIIILandroid/renderscript/Double2;Landroid/renderscript/Allocation;Landroid/renderscript/Allocation;)V")
    ZTRSV = JavaMethod("(IIILandroid/renderscript/Allocation;Landroid/renderscript/Allocation;I)V")
    create = JavaStaticMethod("(Landroid/renderscript/RenderScript;)Landroid/renderscript/ScriptIntrinsicBLAS;")

class RSInvalidStateException(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "android/renderscript/RSInvalidStateException"
    __javaconstructor__ = [("(Ljava/lang/String;)V", False)]

class Float3(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "android/renderscript/Float3"
    __javaconstructor__ = [("()V", False), ("(FFF)V", False)]
    x = JavaField("F")
    y = JavaField("F")
    z = JavaField("F")

class ScriptIntrinsicConvolve5x5(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "android/renderscript/ScriptIntrinsicConvolve5x5"
    setCoefficients = JavaMethod("([F)V")
    getKernelID = JavaMethod("()Landroid/renderscript/Script$KernelID;")
    getFieldID_Input = JavaMethod("()Landroid/renderscript/Script$FieldID;")
    create = JavaStaticMethod("(Landroid/renderscript/RenderScript;Landroid/renderscript/Element;)Landroid/renderscript/ScriptIntrinsicConvolve5x5;")
    forEach = JavaMultipleMethod([("(Landroid/renderscript/Allocation;Landroid/renderscript/Script$LaunchOptions;)V", False, False), ("(Landroid/renderscript/Allocation;)V", False, False)])
    setInput = JavaMethod("(Landroid/renderscript/Allocation;)V")

class Sampler(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "android/renderscript/Sampler"
    MIRRORED_REPEAT_LINEAR = JavaStaticMethod("(Landroid/renderscript/RenderScript;)Landroid/renderscript/Sampler;")
    CLAMP_LINEAR = JavaStaticMethod("(Landroid/renderscript/RenderScript;)Landroid/renderscript/Sampler;")
    CLAMP_NEAREST = JavaStaticMethod("(Landroid/renderscript/RenderScript;)Landroid/renderscript/Sampler;")
    CLAMP_LINEAR_MIP_LINEAR = JavaStaticMethod("(Landroid/renderscript/RenderScript;)Landroid/renderscript/Sampler;")
    MIRRORED_REPEAT_LINEAR_MIP_LINEAR = JavaStaticMethod("(Landroid/renderscript/RenderScript;)Landroid/renderscript/Sampler;")
    MIRRORED_REPEAT_NEAREST = JavaStaticMethod("(Landroid/renderscript/RenderScript;)Landroid/renderscript/Sampler;")
    WRAP_LINEAR = JavaStaticMethod("(Landroid/renderscript/RenderScript;)Landroid/renderscript/Sampler;")
    WRAP_LINEAR_MIP_LINEAR = JavaStaticMethod("(Landroid/renderscript/RenderScript;)Landroid/renderscript/Sampler;")
    WRAP_NEAREST = JavaStaticMethod("(Landroid/renderscript/RenderScript;)Landroid/renderscript/Sampler;")
    getAnisotropy = JavaMethod("()F")
    getMagnification = JavaMethod("()Landroid/renderscript/Sampler$Value;")
    getMinification = JavaMethod("()Landroid/renderscript/Sampler$Value;")
    getWrapS = JavaMethod("()Landroid/renderscript/Sampler$Value;")
    getWrapT = JavaMethod("()Landroid/renderscript/Sampler$Value;")

    class Value(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "android/renderscript/Sampler$Value"
        CLAMP = JavaStaticField("Landroid/renderscript/Sampler$Value;")
        LINEAR = JavaStaticField("Landroid/renderscript/Sampler$Value;")
        LINEAR_MIP_LINEAR = JavaStaticField("Landroid/renderscript/Sampler$Value;")
        LINEAR_MIP_NEAREST = JavaStaticField("Landroid/renderscript/Sampler$Value;")
        MIRRORED_REPEAT = JavaStaticField("Landroid/renderscript/Sampler$Value;")
        NEAREST = JavaStaticField("Landroid/renderscript/Sampler$Value;")
        WRAP = JavaStaticField("Landroid/renderscript/Sampler$Value;")
        values = JavaStaticMethod("()[Landroid/renderscript/Sampler$Value;")
        valueOf = JavaStaticMethod("(Ljava/lang/String;)Landroid/renderscript/Sampler$Value;")
        CLAMP = JavaStaticField("Landroid/renderscript/Sampler$Value;")
        LINEAR = JavaStaticField("Landroid/renderscript/Sampler$Value;")
        LINEAR_MIP_LINEAR = JavaStaticField("Landroid/renderscript/Sampler$Value;")
        LINEAR_MIP_NEAREST = JavaStaticField("Landroid/renderscript/Sampler$Value;")
        MIRRORED_REPEAT = JavaStaticField("Landroid/renderscript/Sampler$Value;")
        NEAREST = JavaStaticField("Landroid/renderscript/Sampler$Value;")
        WRAP = JavaStaticField("Landroid/renderscript/Sampler$Value;")

    class Builder(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "android/renderscript/Sampler$Builder"
        __javaconstructor__ = [("(Landroid/renderscript/RenderScript;)V", False)]
        setAnisotropy = JavaMethod("(F)V")
        setMagnification = JavaMethod("(Landroid/renderscript/Sampler$Value;)V")
        setWrapS = JavaMethod("(Landroid/renderscript/Sampler$Value;)V")
        setMinification = JavaMethod("(Landroid/renderscript/Sampler$Value;)V")
        setWrapT = JavaMethod("(Landroid/renderscript/Sampler$Value;)V")
        create = JavaMethod("()Landroid/renderscript/Sampler;")

class Long4(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "android/renderscript/Long4"
    __javaconstructor__ = [("()V", False), ("(JJJJ)V", False)]
    w = JavaField("J")
    x = JavaField("J")
    y = JavaField("J")
    z = JavaField("J")

class Element(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "android/renderscript/Element"
    RGBA_8888 = JavaStaticMethod("(Landroid/renderscript/RenderScript;)Landroid/renderscript/Element;")
    RGB_565 = JavaStaticMethod("(Landroid/renderscript/RenderScript;)Landroid/renderscript/Element;")
    RGB_888 = JavaStaticMethod("(Landroid/renderscript/RenderScript;)Landroid/renderscript/Element;")
    isComplex = JavaMethod("()Z")
    A_8 = JavaStaticMethod("(Landroid/renderscript/RenderScript;)Landroid/renderscript/Element;")
    RGBA_4444 = JavaStaticMethod("(Landroid/renderscript/RenderScript;)Landroid/renderscript/Element;")
    RGBA_5551 = JavaStaticMethod("(Landroid/renderscript/RenderScript;)Landroid/renderscript/Element;")
    F16_2 = JavaStaticMethod("(Landroid/renderscript/RenderScript;)Landroid/renderscript/Element;")
    F16_4 = JavaStaticMethod("(Landroid/renderscript/RenderScript;)Landroid/renderscript/Element;")
    F16_3 = JavaStaticMethod("(Landroid/renderscript/RenderScript;)Landroid/renderscript/Element;")
    F16 = JavaStaticMethod("(Landroid/renderscript/RenderScript;)Landroid/renderscript/Element;")
    ALLOCATION = JavaStaticMethod("(Landroid/renderscript/RenderScript;)Landroid/renderscript/Element;")
    ELEMENT = JavaStaticMethod("(Landroid/renderscript/RenderScript;)Landroid/renderscript/Element;")
    F32_2 = JavaStaticMethod("(Landroid/renderscript/RenderScript;)Landroid/renderscript/Element;")
    F32 = JavaStaticMethod("(Landroid/renderscript/RenderScript;)Landroid/renderscript/Element;")
    F64 = JavaStaticMethod("(Landroid/renderscript/RenderScript;)Landroid/renderscript/Element;")
    F64_2 = JavaStaticMethod("(Landroid/renderscript/RenderScript;)Landroid/renderscript/Element;")
    MATRIX_3X3 = JavaStaticMethod("(Landroid/renderscript/RenderScript;)Landroid/renderscript/Element;")
    MATRIX_4X4 = JavaStaticMethod("(Landroid/renderscript/RenderScript;)Landroid/renderscript/Element;")
    PROGRAM_FRAGMENT = JavaStaticMethod("(Landroid/renderscript/RenderScript;)Landroid/renderscript/Element;")
    PROGRAM_RASTER = JavaStaticMethod("(Landroid/renderscript/RenderScript;)Landroid/renderscript/Element;")
    PROGRAM_STORE = JavaStaticMethod("(Landroid/renderscript/RenderScript;)Landroid/renderscript/Element;")
    PROGRAM_VERTEX = JavaStaticMethod("(Landroid/renderscript/RenderScript;)Landroid/renderscript/Element;")
    SAMPLER = JavaStaticMethod("(Landroid/renderscript/RenderScript;)Landroid/renderscript/Element;")
    SCRIPT = JavaStaticMethod("(Landroid/renderscript/RenderScript;)Landroid/renderscript/Element;")
    U16 = JavaStaticMethod("(Landroid/renderscript/RenderScript;)Landroid/renderscript/Element;")
    U16_2 = JavaStaticMethod("(Landroid/renderscript/RenderScript;)Landroid/renderscript/Element;")
    U16_3 = JavaStaticMethod("(Landroid/renderscript/RenderScript;)Landroid/renderscript/Element;")
    U16_4 = JavaStaticMethod("(Landroid/renderscript/RenderScript;)Landroid/renderscript/Element;")
    U32 = JavaStaticMethod("(Landroid/renderscript/RenderScript;)Landroid/renderscript/Element;")
    U32_2 = JavaStaticMethod("(Landroid/renderscript/RenderScript;)Landroid/renderscript/Element;")
    U32_3 = JavaStaticMethod("(Landroid/renderscript/RenderScript;)Landroid/renderscript/Element;")
    U32_4 = JavaStaticMethod("(Landroid/renderscript/RenderScript;)Landroid/renderscript/Element;")
    U64 = JavaStaticMethod("(Landroid/renderscript/RenderScript;)Landroid/renderscript/Element;")
    U64_2 = JavaStaticMethod("(Landroid/renderscript/RenderScript;)Landroid/renderscript/Element;")
    U64_3 = JavaStaticMethod("(Landroid/renderscript/RenderScript;)Landroid/renderscript/Element;")
    U64_4 = JavaStaticMethod("(Landroid/renderscript/RenderScript;)Landroid/renderscript/Element;")
    U8 = JavaStaticMethod("(Landroid/renderscript/RenderScript;)Landroid/renderscript/Element;")
    U8_2 = JavaStaticMethod("(Landroid/renderscript/RenderScript;)Landroid/renderscript/Element;")
    U8_3 = JavaStaticMethod("(Landroid/renderscript/RenderScript;)Landroid/renderscript/Element;")
    U8_4 = JavaStaticMethod("(Landroid/renderscript/RenderScript;)Landroid/renderscript/Element;")
    YUV = JavaStaticMethod("(Landroid/renderscript/RenderScript;)Landroid/renderscript/Element;")
    createPixel = JavaStaticMethod("(Landroid/renderscript/RenderScript;Landroid/renderscript/Element$DataType;Landroid/renderscript/Element$DataKind;)Landroid/renderscript/Element;")
    createVector = JavaStaticMethod("(Landroid/renderscript/RenderScript;Landroid/renderscript/Element$DataType;I)Landroid/renderscript/Element;")
    getBytesSize = JavaMethod("()I")
    getDataKind = JavaMethod("()Landroid/renderscript/Element$DataKind;")
    getSubElement = JavaMethod("(I)Landroid/renderscript/Element;")
    getSubElementArraySize = JavaMethod("(I)I")
    getSubElementCount = JavaMethod("()I")
    getSubElementName = JavaMethod("(I)Ljava/lang/String;")
    getSubElementOffsetBytes = JavaMethod("(I)I")
    getVectorSize = JavaMethod("()I")
    isCompatible = JavaMethod("(Landroid/renderscript/Element;)Z")
    F32_3 = JavaStaticMethod("(Landroid/renderscript/RenderScript;)Landroid/renderscript/Element;")
    F32_4 = JavaStaticMethod("(Landroid/renderscript/RenderScript;)Landroid/renderscript/Element;")
    F64_3 = JavaStaticMethod("(Landroid/renderscript/RenderScript;)Landroid/renderscript/Element;")
    F64_4 = JavaStaticMethod("(Landroid/renderscript/RenderScript;)Landroid/renderscript/Element;")
    FONT = JavaStaticMethod("(Landroid/renderscript/RenderScript;)Landroid/renderscript/Element;")
    I16 = JavaStaticMethod("(Landroid/renderscript/RenderScript;)Landroid/renderscript/Element;")
    I16_2 = JavaStaticMethod("(Landroid/renderscript/RenderScript;)Landroid/renderscript/Element;")
    I16_3 = JavaStaticMethod("(Landroid/renderscript/RenderScript;)Landroid/renderscript/Element;")
    I16_4 = JavaStaticMethod("(Landroid/renderscript/RenderScript;)Landroid/renderscript/Element;")
    I32 = JavaStaticMethod("(Landroid/renderscript/RenderScript;)Landroid/renderscript/Element;")
    I32_2 = JavaStaticMethod("(Landroid/renderscript/RenderScript;)Landroid/renderscript/Element;")
    I32_3 = JavaStaticMethod("(Landroid/renderscript/RenderScript;)Landroid/renderscript/Element;")
    I32_4 = JavaStaticMethod("(Landroid/renderscript/RenderScript;)Landroid/renderscript/Element;")
    I64 = JavaStaticMethod("(Landroid/renderscript/RenderScript;)Landroid/renderscript/Element;")
    I64_2 = JavaStaticMethod("(Landroid/renderscript/RenderScript;)Landroid/renderscript/Element;")
    I64_3 = JavaStaticMethod("(Landroid/renderscript/RenderScript;)Landroid/renderscript/Element;")
    I64_4 = JavaStaticMethod("(Landroid/renderscript/RenderScript;)Landroid/renderscript/Element;")
    I8 = JavaStaticMethod("(Landroid/renderscript/RenderScript;)Landroid/renderscript/Element;")
    I8_2 = JavaStaticMethod("(Landroid/renderscript/RenderScript;)Landroid/renderscript/Element;")
    I8_3 = JavaStaticMethod("(Landroid/renderscript/RenderScript;)Landroid/renderscript/Element;")
    I8_4 = JavaStaticMethod("(Landroid/renderscript/RenderScript;)Landroid/renderscript/Element;")
    MATRIX4X4 = JavaStaticMethod("(Landroid/renderscript/RenderScript;)Landroid/renderscript/Element;")
    MATRIX_2X2 = JavaStaticMethod("(Landroid/renderscript/RenderScript;)Landroid/renderscript/Element;")
    MESH = JavaStaticMethod("(Landroid/renderscript/RenderScript;)Landroid/renderscript/Element;")
    TYPE = JavaStaticMethod("(Landroid/renderscript/RenderScript;)Landroid/renderscript/Element;")
    getDataType = JavaMethod("()Landroid/renderscript/Element$DataType;")
    BOOLEAN = JavaStaticMethod("(Landroid/renderscript/RenderScript;)Landroid/renderscript/Element;")

    class DataType(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "android/renderscript/Element$DataType"
        BOOLEAN = JavaStaticField("Landroid/renderscript/Element$DataType;")
        FLOAT_16 = JavaStaticField("Landroid/renderscript/Element$DataType;")
        FLOAT_32 = JavaStaticField("Landroid/renderscript/Element$DataType;")
        FLOAT_64 = JavaStaticField("Landroid/renderscript/Element$DataType;")
        MATRIX_2X2 = JavaStaticField("Landroid/renderscript/Element$DataType;")
        MATRIX_3X3 = JavaStaticField("Landroid/renderscript/Element$DataType;")
        MATRIX_4X4 = JavaStaticField("Landroid/renderscript/Element$DataType;")
        NONE = JavaStaticField("Landroid/renderscript/Element$DataType;")
        RS_ALLOCATION = JavaStaticField("Landroid/renderscript/Element$DataType;")
        RS_ELEMENT = JavaStaticField("Landroid/renderscript/Element$DataType;")
        RS_FONT = JavaStaticField("Landroid/renderscript/Element$DataType;")
        RS_MESH = JavaStaticField("Landroid/renderscript/Element$DataType;")
        RS_PROGRAM_FRAGMENT = JavaStaticField("Landroid/renderscript/Element$DataType;")
        RS_PROGRAM_RASTER = JavaStaticField("Landroid/renderscript/Element$DataType;")
        RS_PROGRAM_STORE = JavaStaticField("Landroid/renderscript/Element$DataType;")
        RS_PROGRAM_VERTEX = JavaStaticField("Landroid/renderscript/Element$DataType;")
        RS_SAMPLER = JavaStaticField("Landroid/renderscript/Element$DataType;")
        RS_SCRIPT = JavaStaticField("Landroid/renderscript/Element$DataType;")
        RS_TYPE = JavaStaticField("Landroid/renderscript/Element$DataType;")
        SIGNED_16 = JavaStaticField("Landroid/renderscript/Element$DataType;")
        SIGNED_32 = JavaStaticField("Landroid/renderscript/Element$DataType;")
        SIGNED_64 = JavaStaticField("Landroid/renderscript/Element$DataType;")
        SIGNED_8 = JavaStaticField("Landroid/renderscript/Element$DataType;")
        UNSIGNED_16 = JavaStaticField("Landroid/renderscript/Element$DataType;")
        UNSIGNED_32 = JavaStaticField("Landroid/renderscript/Element$DataType;")
        UNSIGNED_4_4_4_4 = JavaStaticField("Landroid/renderscript/Element$DataType;")
        UNSIGNED_5_5_5_1 = JavaStaticField("Landroid/renderscript/Element$DataType;")
        UNSIGNED_5_6_5 = JavaStaticField("Landroid/renderscript/Element$DataType;")
        UNSIGNED_64 = JavaStaticField("Landroid/renderscript/Element$DataType;")
        UNSIGNED_8 = JavaStaticField("Landroid/renderscript/Element$DataType;")
        values = JavaStaticMethod("()[Landroid/renderscript/Element$DataType;")
        valueOf = JavaStaticMethod("(Ljava/lang/String;)Landroid/renderscript/Element$DataType;")
        BOOLEAN = JavaStaticField("Landroid/renderscript/Element$DataType;")
        FLOAT_16 = JavaStaticField("Landroid/renderscript/Element$DataType;")
        FLOAT_32 = JavaStaticField("Landroid/renderscript/Element$DataType;")
        FLOAT_64 = JavaStaticField("Landroid/renderscript/Element$DataType;")
        MATRIX_2X2 = JavaStaticField("Landroid/renderscript/Element$DataType;")
        MATRIX_3X3 = JavaStaticField("Landroid/renderscript/Element$DataType;")
        MATRIX_4X4 = JavaStaticField("Landroid/renderscript/Element$DataType;")
        NONE = JavaStaticField("Landroid/renderscript/Element$DataType;")
        RS_ALLOCATION = JavaStaticField("Landroid/renderscript/Element$DataType;")
        RS_ELEMENT = JavaStaticField("Landroid/renderscript/Element$DataType;")
        RS_FONT = JavaStaticField("Landroid/renderscript/Element$DataType;")
        RS_MESH = JavaStaticField("Landroid/renderscript/Element$DataType;")
        RS_PROGRAM_FRAGMENT = JavaStaticField("Landroid/renderscript/Element$DataType;")
        RS_PROGRAM_RASTER = JavaStaticField("Landroid/renderscript/Element$DataType;")
        RS_PROGRAM_STORE = JavaStaticField("Landroid/renderscript/Element$DataType;")
        RS_PROGRAM_VERTEX = JavaStaticField("Landroid/renderscript/Element$DataType;")
        RS_SAMPLER = JavaStaticField("Landroid/renderscript/Element$DataType;")
        RS_SCRIPT = JavaStaticField("Landroid/renderscript/Element$DataType;")
        RS_TYPE = JavaStaticField("Landroid/renderscript/Element$DataType;")
        SIGNED_16 = JavaStaticField("Landroid/renderscript/Element$DataType;")
        SIGNED_32 = JavaStaticField("Landroid/renderscript/Element$DataType;")
        SIGNED_64 = JavaStaticField("Landroid/renderscript/Element$DataType;")
        SIGNED_8 = JavaStaticField("Landroid/renderscript/Element$DataType;")
        UNSIGNED_16 = JavaStaticField("Landroid/renderscript/Element$DataType;")
        UNSIGNED_32 = JavaStaticField("Landroid/renderscript/Element$DataType;")
        UNSIGNED_4_4_4_4 = JavaStaticField("Landroid/renderscript/Element$DataType;")
        UNSIGNED_5_5_5_1 = JavaStaticField("Landroid/renderscript/Element$DataType;")
        UNSIGNED_5_6_5 = JavaStaticField("Landroid/renderscript/Element$DataType;")
        UNSIGNED_64 = JavaStaticField("Landroid/renderscript/Element$DataType;")
        UNSIGNED_8 = JavaStaticField("Landroid/renderscript/Element$DataType;")

    class DataKind(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "android/renderscript/Element$DataKind"
        PIXEL_A = JavaStaticField("Landroid/renderscript/Element$DataKind;")
        PIXEL_DEPTH = JavaStaticField("Landroid/renderscript/Element$DataKind;")
        PIXEL_L = JavaStaticField("Landroid/renderscript/Element$DataKind;")
        PIXEL_LA = JavaStaticField("Landroid/renderscript/Element$DataKind;")
        PIXEL_RGB = JavaStaticField("Landroid/renderscript/Element$DataKind;")
        PIXEL_RGBA = JavaStaticField("Landroid/renderscript/Element$DataKind;")
        PIXEL_YUV = JavaStaticField("Landroid/renderscript/Element$DataKind;")
        USER = JavaStaticField("Landroid/renderscript/Element$DataKind;")
        values = JavaStaticMethod("()[Landroid/renderscript/Element$DataKind;")
        valueOf = JavaStaticMethod("(Ljava/lang/String;)Landroid/renderscript/Element$DataKind;")
        PIXEL_A = JavaStaticField("Landroid/renderscript/Element$DataKind;")
        PIXEL_DEPTH = JavaStaticField("Landroid/renderscript/Element$DataKind;")
        PIXEL_L = JavaStaticField("Landroid/renderscript/Element$DataKind;")
        PIXEL_LA = JavaStaticField("Landroid/renderscript/Element$DataKind;")
        PIXEL_RGB = JavaStaticField("Landroid/renderscript/Element$DataKind;")
        PIXEL_RGBA = JavaStaticField("Landroid/renderscript/Element$DataKind;")
        PIXEL_YUV = JavaStaticField("Landroid/renderscript/Element$DataKind;")
        USER = JavaStaticField("Landroid/renderscript/Element$DataKind;")

    class Builder(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "android/renderscript/Element$Builder"
        __javaconstructor__ = [("(Landroid/renderscript/RenderScript;)V", False)]
        create = JavaMethod("()Landroid/renderscript/Element;")
        add = JavaMultipleMethod([("(Landroid/renderscript/Element;Ljava/lang/String;)Landroid/renderscript/Element$Builder;", False, False), ("(Landroid/renderscript/Element;Ljava/lang/String;I)Landroid/renderscript/Element$Builder;", False, False)])

class Allocation(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "android/renderscript/Allocation"
    USAGE_GRAPHICS_CONSTANTS = JavaStaticField("I")
    USAGE_GRAPHICS_RENDER_TARGET = JavaStaticField("I")
    USAGE_GRAPHICS_TEXTURE = JavaStaticField("I")
    USAGE_GRAPHICS_VERTEX = JavaStaticField("I")
    USAGE_IO_INPUT = JavaStaticField("I")
    USAGE_IO_OUTPUT = JavaStaticField("I")
    USAGE_SCRIPT = JavaStaticField("I")
    USAGE_SHARED = JavaStaticField("I")
    getSurface = JavaMethod("()Landroid/view/Surface;")
    setSurface = JavaMethod("(Landroid/view/Surface;)V")
    getTimeStamp = JavaMethod("()J")
    getBytesSize = JavaMethod("()I")
    copy1DRangeFrom = JavaMultipleMethod([("(II[F)V", False, False), ("(IILandroid/renderscript/Allocation;I)V", False, False), ("(II[B)V", False, False), ("(II[I)V", False, False), ("(IILjava/lang/Object;)V", False, False), ("(II[S)V", False, False)])
    copy1DRangeFromUnchecked = JavaMultipleMethod([("(II[S)V", False, False), ("(II[B)V", False, False), ("(II[F)V", False, False), ("(II[I)V", False, False), ("(IILjava/lang/Object;)V", False, False)])
    copy1DRangeTo = JavaMultipleMethod([("(II[S)V", False, False), ("(II[I)V", False, False), ("(II[F)V", False, False), ("(II[B)V", False, False), ("(IILjava/lang/Object;)V", False, False)])
    copy1DRangeToUnchecked = JavaMultipleMethod([("(II[S)V", False, False), ("(II[B)V", False, False), ("(II[F)V", False, False), ("(II[I)V", False, False), ("(IILjava/lang/Object;)V", False, False)])
    copy2DRangeFrom = JavaMultipleMethod([("(IIIILjava/lang/Object;)V", False, False), ("(IIII[S)V", False, False), ("(IIIILandroid/renderscript/Allocation;II)V", False, False), ("(IILandroid/graphics/Bitmap;)V", False, False), ("(IIII[B)V", False, False), ("(IIII[F)V", False, False), ("(IIII[I)V", False, False)])
    copy2DRangeTo = JavaMultipleMethod([("(IIII[S)V", False, False), ("(IIIILjava/lang/Object;)V", False, False), ("(IIII[B)V", False, False), ("(IIII[I)V", False, False), ("(IIII[F)V", False, False)])
    copy3DRangeFrom = JavaMultipleMethod([("(IIIIIILandroid/renderscript/Allocation;III)V", False, False), ("(IIIIIILjava/lang/Object;)V", False, False)])
    copy3DRangeTo = JavaMethod("(IIIIIILjava/lang/Object;)V")
    copyFromUnchecked = JavaMultipleMethod([("([I)V", False, False), ("([B)V", False, False), ("(Ljava/lang/Object;)V", False, False), ("([S)V", False, False), ("([F)V", False, False)])
    createAllocations = JavaStaticMethod("(Landroid/renderscript/RenderScript;Landroid/renderscript/Type;II)[Landroid/renderscript/Allocation;")
    createCubemapFromBitmap = JavaMultipleMethod([("(Landroid/renderscript/RenderScript;Landroid/graphics/Bitmap;Landroid/renderscript/Allocation$MipmapControl;I)Landroid/renderscript/Allocation;", True, False), ("(Landroid/renderscript/RenderScript;Landroid/graphics/Bitmap;)Landroid/renderscript/Allocation;", True, False)])
    createCubemapFromCubeFaces = JavaMultipleMethod([("(Landroid/renderscript/RenderScript;Landroid/graphics/Bitmap;Landroid/graphics/Bitmap;Landroid/graphics/Bitmap;Landroid/graphics/Bitmap;Landroid/graphics/Bitmap;Landroid/graphics/Bitmap;)Landroid/renderscript/Allocation;", True, False), ("(Landroid/renderscript/RenderScript;Landroid/graphics/Bitmap;Landroid/graphics/Bitmap;Landroid/graphics/Bitmap;Landroid/graphics/Bitmap;Landroid/graphics/Bitmap;Landroid/graphics/Bitmap;Landroid/renderscript/Allocation$MipmapControl;I)Landroid/renderscript/Allocation;", True, False)])
    createFromBitmap = JavaMultipleMethod([("(Landroid/renderscript/RenderScript;Landroid/graphics/Bitmap;Landroid/renderscript/Allocation$MipmapControl;I)Landroid/renderscript/Allocation;", True, False), ("(Landroid/renderscript/RenderScript;Landroid/graphics/Bitmap;)Landroid/renderscript/Allocation;", True, False)])
    createFromBitmapResource = JavaMultipleMethod([("(Landroid/renderscript/RenderScript;Landroid/content/res/Resources;I)Landroid/renderscript/Allocation;", True, False), ("(Landroid/renderscript/RenderScript;Landroid/content/res/Resources;ILandroid/renderscript/Allocation$MipmapControl;I)Landroid/renderscript/Allocation;", True, False)])
    createFromString = JavaStaticMethod("(Landroid/renderscript/RenderScript;Ljava/lang/String;I)Landroid/renderscript/Allocation;")
    createSized = JavaMultipleMethod([("(Landroid/renderscript/RenderScript;Landroid/renderscript/Element;I)Landroid/renderscript/Allocation;", True, False), ("(Landroid/renderscript/RenderScript;Landroid/renderscript/Element;II)Landroid/renderscript/Allocation;", True, False)])
    createTyped = JavaMultipleMethod([("(Landroid/renderscript/RenderScript;Landroid/renderscript/Type;Landroid/renderscript/Allocation$MipmapControl;I)Landroid/renderscript/Allocation;", True, False), ("(Landroid/renderscript/RenderScript;Landroid/renderscript/Type;I)Landroid/renderscript/Allocation;", True, False), ("(Landroid/renderscript/RenderScript;Landroid/renderscript/Type;)Landroid/renderscript/Allocation;", True, False)])
    generateMipmaps = JavaMethod("()V")
    getStride = JavaMethod("()J")
    ioReceive = JavaMethod("()V")
    ioSend = JavaMethod("()V")
    setAutoPadding = JavaMethod("(Z)V")
    setFromFieldPacker = JavaMultipleMethod([("(IIIILandroid/renderscript/FieldPacker;)V", False, False), ("(IILandroid/renderscript/FieldPacker;)V", False, False), ("(ILandroid/renderscript/FieldPacker;)V", False, False)])
    setOnBufferAvailableListener = JavaMethod("(Landroid/renderscript/Allocation$OnBufferAvailableListener;)V")
    copyTo = JavaMultipleMethod([("(Ljava/lang/Object;)V", False, False), ("([S)V", False, False), ("(Landroid/graphics/Bitmap;)V", False, False), ("([B)V", False, False), ("([I)V", False, False), ("([F)V", False, False)])
    destroy = JavaMethod("()V")
    getType = JavaMethod("()Landroid/renderscript/Type;")
    resize = JavaMethod("(I)V")
    copyFrom = JavaMultipleMethod([("(Landroid/renderscript/Allocation;)V", False, False), ("([I)V", False, False), ("([F)V", False, False), ("([B)V", False, False), ("([Landroid/renderscript/BaseObj;)V", False, False), ("(Ljava/lang/Object;)V", False, False), ("([S)V", False, False), ("(Landroid/graphics/Bitmap;)V", False, False)])
    getUsage = JavaMethod("()I")
    getElement = JavaMethod("()Landroid/renderscript/Element;")
    syncAll = JavaMethod("(I)V")
    getByteBuffer = JavaMethod("()Ljava/nio/ByteBuffer;")

    class OnBufferAvailableListener(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "android/renderscript/Allocation$OnBufferAvailableListener"
        onBufferAvailable = JavaMethod("(Landroid/renderscript/Allocation;)V")

    class MipmapControl(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "android/renderscript/Allocation$MipmapControl"
        MIPMAP_FULL = JavaStaticField("Landroid/renderscript/Allocation$MipmapControl;")
        MIPMAP_NONE = JavaStaticField("Landroid/renderscript/Allocation$MipmapControl;")
        MIPMAP_ON_SYNC_TO_TEXTURE = JavaStaticField("Landroid/renderscript/Allocation$MipmapControl;")
        values = JavaStaticMethod("()[Landroid/renderscript/Allocation$MipmapControl;")
        valueOf = JavaStaticMethod("(Ljava/lang/String;)Landroid/renderscript/Allocation$MipmapControl;")
        MIPMAP_FULL = JavaStaticField("Landroid/renderscript/Allocation$MipmapControl;")
        MIPMAP_NONE = JavaStaticField("Landroid/renderscript/Allocation$MipmapControl;")
        MIPMAP_ON_SYNC_TO_TEXTURE = JavaStaticField("Landroid/renderscript/Allocation$MipmapControl;")

class ScriptGroup(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "android/renderscript/ScriptGroup"
    execute = JavaMultipleMethod([("([Ljava/lang/Object;)[Ljava/lang/Object;", False, True), ("()V", False, False)])
    destroy = JavaMethod("()V")
    setOutput = JavaMethod("(Landroid/renderscript/Script$KernelID;Landroid/renderscript/Allocation;)V")
    setInput = JavaMethod("(Landroid/renderscript/Script$KernelID;Landroid/renderscript/Allocation;)V")

    class Input(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "android/renderscript/ScriptGroup$Input"

    class Future(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "android/renderscript/ScriptGroup$Future"

    class Closure(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "android/renderscript/ScriptGroup$Closure"
        getReturn = JavaMethod("()Landroid/renderscript/ScriptGroup$Future;")
        getGlobal = JavaMethod("(Landroid/renderscript/Script$FieldID;)Landroid/renderscript/ScriptGroup$Future;")
        destroy = JavaMethod("()V")

    class Builder2(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "android/renderscript/ScriptGroup$Builder2"
        __javaconstructor__ = [("(Landroid/renderscript/RenderScript;)V", False)]
        addInvoke = JavaMethod("(Landroid/renderscript/Script$InvokeID;[Ljava/lang/Object;)Landroid/renderscript/ScriptGroup$Closure;", varargs=True)
        addInput = JavaMethod("()Landroid/renderscript/ScriptGroup$Input;")
        addKernel = JavaMethod("(Landroid/renderscript/Script$KernelID;Landroid/renderscript/Type;[Ljava/lang/Object;)Landroid/renderscript/ScriptGroup$Closure;", varargs=True)
        create = JavaMethod("(Ljava/lang/String;[Landroid/renderscript/ScriptGroup$Future;)Landroid/renderscript/ScriptGroup;", varargs=True)

    class Builder(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "android/renderscript/ScriptGroup$Builder"
        __javaconstructor__ = [("(Landroid/renderscript/RenderScript;)V", False)]
        addKernel = JavaMethod("(Landroid/renderscript/Script$KernelID;)Landroid/renderscript/ScriptGroup$Builder;")
        addConnection = JavaMultipleMethod([("(Landroid/renderscript/Type;Landroid/renderscript/Script$KernelID;Landroid/renderscript/Script$FieldID;)Landroid/renderscript/ScriptGroup$Builder;", False, False), ("(Landroid/renderscript/Type;Landroid/renderscript/Script$KernelID;Landroid/renderscript/Script$KernelID;)Landroid/renderscript/ScriptGroup$Builder;", False, False)])
        create = JavaMethod("()Landroid/renderscript/ScriptGroup;")

    class Binding(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "android/renderscript/ScriptGroup$Binding"
        __javaconstructor__ = [("(Landroid/renderscript/Script$FieldID;Ljava/lang/Object;)V", False)]

class BaseObj(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "android/renderscript/BaseObj"
    getName = JavaMethod("()Ljava/lang/String;")
    equals = JavaMethod("(Ljava/lang/Object;)Z")
    hashCode = JavaMethod("()I")
    setName = JavaMethod("(Ljava/lang/String;)V")
    destroy = JavaMethod("()V")

class Script(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "android/renderscript/Script"
    setVar = JavaMultipleMethod([("(IF)V", False, False), ("(ID)V", False, False), ("(IZ)V", False, False), ("(ILandroid/renderscript/FieldPacker;Landroid/renderscript/Element;[I)V", False, False), ("(ILandroid/renderscript/FieldPacker;)V", False, False), ("(ILandroid/renderscript/BaseObj;)V", False, False), ("(IJ)V", False, False), ("(II)V", False, False)])
    bindAllocation = JavaMethod("(Landroid/renderscript/Allocation;I)V")
    getVarB = JavaMethod("(I)Z")
    getVarD = JavaMethod("(I)D")
    getVarF = JavaMethod("(I)F")
    getVarI = JavaMethod("(I)I")
    getVarJ = JavaMethod("(I)J")
    getVarV = JavaMethod("(ILandroid/renderscript/FieldPacker;)V")
    setTimeZone = JavaMethod("(Ljava/lang/String;)V")

    class LaunchOptions(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "android/renderscript/Script$LaunchOptions"
        __javaconstructor__ = [("()V", False)]
        getXEnd = JavaMethod("()I")
        getXStart = JavaMethod("()I")
        getYEnd = JavaMethod("()I")
        getYStart = JavaMethod("()I")
        getZEnd = JavaMethod("()I")
        getZStart = JavaMethod("()I")
        setX = JavaMethod("(II)Landroid/renderscript/Script$LaunchOptions;")
        setY = JavaMethod("(II)Landroid/renderscript/Script$LaunchOptions;")
        setZ = JavaMethod("(II)Landroid/renderscript/Script$LaunchOptions;")

    class KernelID(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "android/renderscript/Script$KernelID"

    class InvokeID(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "android/renderscript/Script$InvokeID"

    class FieldID(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "android/renderscript/Script$FieldID"

    class FieldBase(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "android/renderscript/Script$FieldBase"
        updateAllocation = JavaMethod("()V")
        getAllocation = JavaMethod("()Landroid/renderscript/Allocation;")
        getType = JavaMethod("()Landroid/renderscript/Type;")
        getElement = JavaMethod("()Landroid/renderscript/Element;")

    class Builder(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "android/renderscript/Script$Builder"

class ScriptC(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "android/renderscript/ScriptC"

class Long3(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "android/renderscript/Long3"
    __javaconstructor__ = [("()V", False), ("(JJJ)V", False)]
    x = JavaField("J")
    y = JavaField("J")
    z = JavaField("J")

class Byte3(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "android/renderscript/Byte3"
    __javaconstructor__ = [("()V", False), ("(BBB)V", False)]
    x = JavaField("B")
    y = JavaField("B")
    z = JavaField("B")

class ScriptIntrinsicConvolve3x3(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "android/renderscript/ScriptIntrinsicConvolve3x3"
    setCoefficients = JavaMethod("([F)V")
    getKernelID = JavaMethod("()Landroid/renderscript/Script$KernelID;")
    getFieldID_Input = JavaMethod("()Landroid/renderscript/Script$FieldID;")
    create = JavaStaticMethod("(Landroid/renderscript/RenderScript;Landroid/renderscript/Element;)Landroid/renderscript/ScriptIntrinsicConvolve3x3;")
    forEach = JavaMultipleMethod([("(Landroid/renderscript/Allocation;Landroid/renderscript/Script$LaunchOptions;)V", False, False), ("(Landroid/renderscript/Allocation;)V", False, False)])
    setInput = JavaMethod("(Landroid/renderscript/Allocation;)V")

class ScriptIntrinsicBlend(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "android/renderscript/ScriptIntrinsicBlend"
    forEachAdd = JavaMultipleMethod([("(Landroid/renderscript/Allocation;Landroid/renderscript/Allocation;)V", False, False), ("(Landroid/renderscript/Allocation;Landroid/renderscript/Allocation;Landroid/renderscript/Script$LaunchOptions;)V", False, False)])
    forEachClear = JavaMultipleMethod([("(Landroid/renderscript/Allocation;Landroid/renderscript/Allocation;)V", False, False), ("(Landroid/renderscript/Allocation;Landroid/renderscript/Allocation;Landroid/renderscript/Script$LaunchOptions;)V", False, False)])
    forEachDst = JavaMultipleMethod([("(Landroid/renderscript/Allocation;Landroid/renderscript/Allocation;Landroid/renderscript/Script$LaunchOptions;)V", False, False), ("(Landroid/renderscript/Allocation;Landroid/renderscript/Allocation;)V", False, False)])
    forEachDstAtop = JavaMultipleMethod([("(Landroid/renderscript/Allocation;Landroid/renderscript/Allocation;)V", False, False), ("(Landroid/renderscript/Allocation;Landroid/renderscript/Allocation;Landroid/renderscript/Script$LaunchOptions;)V", False, False)])
    forEachDstIn = JavaMultipleMethod([("(Landroid/renderscript/Allocation;Landroid/renderscript/Allocation;Landroid/renderscript/Script$LaunchOptions;)V", False, False), ("(Landroid/renderscript/Allocation;Landroid/renderscript/Allocation;)V", False, False)])
    forEachDstOut = JavaMultipleMethod([("(Landroid/renderscript/Allocation;Landroid/renderscript/Allocation;)V", False, False), ("(Landroid/renderscript/Allocation;Landroid/renderscript/Allocation;Landroid/renderscript/Script$LaunchOptions;)V", False, False)])
    forEachDstOver = JavaMultipleMethod([("(Landroid/renderscript/Allocation;Landroid/renderscript/Allocation;Landroid/renderscript/Script$LaunchOptions;)V", False, False), ("(Landroid/renderscript/Allocation;Landroid/renderscript/Allocation;)V", False, False)])
    forEachMultiply = JavaMultipleMethod([("(Landroid/renderscript/Allocation;Landroid/renderscript/Allocation;)V", False, False), ("(Landroid/renderscript/Allocation;Landroid/renderscript/Allocation;Landroid/renderscript/Script$LaunchOptions;)V", False, False)])
    forEachSrc = JavaMultipleMethod([("(Landroid/renderscript/Allocation;Landroid/renderscript/Allocation;Landroid/renderscript/Script$LaunchOptions;)V", False, False), ("(Landroid/renderscript/Allocation;Landroid/renderscript/Allocation;)V", False, False)])
    forEachSrcAtop = JavaMultipleMethod([("(Landroid/renderscript/Allocation;Landroid/renderscript/Allocation;)V", False, False), ("(Landroid/renderscript/Allocation;Landroid/renderscript/Allocation;Landroid/renderscript/Script$LaunchOptions;)V", False, False)])
    forEachSrcIn = JavaMultipleMethod([("(Landroid/renderscript/Allocation;Landroid/renderscript/Allocation;)V", False, False), ("(Landroid/renderscript/Allocation;Landroid/renderscript/Allocation;Landroid/renderscript/Script$LaunchOptions;)V", False, False)])
    forEachSrcOut = JavaMultipleMethod([("(Landroid/renderscript/Allocation;Landroid/renderscript/Allocation;)V", False, False), ("(Landroid/renderscript/Allocation;Landroid/renderscript/Allocation;Landroid/renderscript/Script$LaunchOptions;)V", False, False)])
    forEachSrcOver = JavaMultipleMethod([("(Landroid/renderscript/Allocation;Landroid/renderscript/Allocation;)V", False, False), ("(Landroid/renderscript/Allocation;Landroid/renderscript/Allocation;Landroid/renderscript/Script$LaunchOptions;)V", False, False)])
    forEachSubtract = JavaMultipleMethod([("(Landroid/renderscript/Allocation;Landroid/renderscript/Allocation;Landroid/renderscript/Script$LaunchOptions;)V", False, False), ("(Landroid/renderscript/Allocation;Landroid/renderscript/Allocation;)V", False, False)])
    forEachXor = JavaMultipleMethod([("(Landroid/renderscript/Allocation;Landroid/renderscript/Allocation;)V", False, False), ("(Landroid/renderscript/Allocation;Landroid/renderscript/Allocation;Landroid/renderscript/Script$LaunchOptions;)V", False, False)])
    getKernelIDAdd = JavaMethod("()Landroid/renderscript/Script$KernelID;")
    getKernelIDClear = JavaMethod("()Landroid/renderscript/Script$KernelID;")
    getKernelIDDst = JavaMethod("()Landroid/renderscript/Script$KernelID;")
    getKernelIDDstAtop = JavaMethod("()Landroid/renderscript/Script$KernelID;")
    getKernelIDDstIn = JavaMethod("()Landroid/renderscript/Script$KernelID;")
    getKernelIDDstOut = JavaMethod("()Landroid/renderscript/Script$KernelID;")
    getKernelIDDstOver = JavaMethod("()Landroid/renderscript/Script$KernelID;")
    getKernelIDMultiply = JavaMethod("()Landroid/renderscript/Script$KernelID;")
    getKernelIDSrc = JavaMethod("()Landroid/renderscript/Script$KernelID;")
    getKernelIDSrcAtop = JavaMethod("()Landroid/renderscript/Script$KernelID;")
    getKernelIDSrcIn = JavaMethod("()Landroid/renderscript/Script$KernelID;")
    getKernelIDSrcOut = JavaMethod("()Landroid/renderscript/Script$KernelID;")
    getKernelIDSrcOver = JavaMethod("()Landroid/renderscript/Script$KernelID;")
    getKernelIDSubtract = JavaMethod("()Landroid/renderscript/Script$KernelID;")
    getKernelIDXor = JavaMethod("()Landroid/renderscript/Script$KernelID;")
    create = JavaStaticMethod("(Landroid/renderscript/RenderScript;Landroid/renderscript/Element;)Landroid/renderscript/ScriptIntrinsicBlend;")

class FieldPacker(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "android/renderscript/FieldPacker"
    __javaconstructor__ = [("([B)V", False), ("(I)V", False)]
    addU8 = JavaMultipleMethod([("(Landroid/renderscript/Short4;)V", False, False), ("(S)V", False, False), ("(Landroid/renderscript/Short3;)V", False, False), ("(Landroid/renderscript/Short2;)V", False, False)])
    addF64 = JavaMultipleMethod([("(Landroid/renderscript/Double2;)V", False, False), ("(Landroid/renderscript/Double3;)V", False, False), ("(Landroid/renderscript/Double4;)V", False, False), ("(D)V", False, False)])
    subI8 = JavaMethod("()B")
    addU32 = JavaMultipleMethod([("(Landroid/renderscript/Long4;)V", False, False), ("(Landroid/renderscript/Long3;)V", False, False), ("(J)V", False, False), ("(Landroid/renderscript/Long2;)V", False, False)])
    addI8 = JavaMultipleMethod([("(Landroid/renderscript/Byte2;)V", False, False), ("(Landroid/renderscript/Byte3;)V", False, False), ("(Landroid/renderscript/Byte4;)V", False, False), ("(B)V", False, False)])
    addU16 = JavaMultipleMethod([("(I)V", False, False), ("(Landroid/renderscript/Int3;)V", False, False), ("(Landroid/renderscript/Int2;)V", False, False), ("(Landroid/renderscript/Int4;)V", False, False)])
    subI32 = JavaMethod("()I")
    subI64 = JavaMethod("()J")
    addI64 = JavaMultipleMethod([("(Landroid/renderscript/Long2;)V", False, False), ("(J)V", False, False), ("(Landroid/renderscript/Long4;)V", False, False), ("(Landroid/renderscript/Long3;)V", False, False)])
    addI32 = JavaMultipleMethod([("(Landroid/renderscript/Int3;)V", False, False), ("(Landroid/renderscript/Int4;)V", False, False), ("(I)V", False, False), ("(Landroid/renderscript/Int2;)V", False, False)])
    subI16 = JavaMethod("()S")
    subF64 = JavaMethod("()D")
    addU64 = JavaMultipleMethod([("(Landroid/renderscript/Long3;)V", False, False), ("(J)V", False, False), ("(Landroid/renderscript/Long4;)V", False, False), ("(Landroid/renderscript/Long2;)V", False, False)])
    subF32 = JavaMethod("()F")
    addF32 = JavaMultipleMethod([("(Landroid/renderscript/Float2;)V", False, False), ("(Landroid/renderscript/Float3;)V", False, False), ("(Landroid/renderscript/Float4;)V", False, False), ("(F)V", False, False)])
    addObj = JavaMethod("(Landroid/renderscript/BaseObj;)V")
    addBoolean = JavaMethod("(Z)V")
    addI16 = JavaMultipleMethod([("(S)V", False, False), ("(Landroid/renderscript/Short2;)V", False, False), ("(Landroid/renderscript/Short4;)V", False, False), ("(Landroid/renderscript/Short3;)V", False, False)])
    addMatrix = JavaMultipleMethod([("(Landroid/renderscript/Matrix4f;)V", False, False), ("(Landroid/renderscript/Matrix3f;)V", False, False), ("(Landroid/renderscript/Matrix2f;)V", False, False)])
    subBoolean = JavaMethod("()Z")
    subByte2 = JavaMethod("()Landroid/renderscript/Byte2;")
    subByte3 = JavaMethod("()Landroid/renderscript/Byte3;")
    subByte4 = JavaMethod("()Landroid/renderscript/Byte4;")
    subDouble2 = JavaMethod("()Landroid/renderscript/Double2;")
    subDouble3 = JavaMethod("()Landroid/renderscript/Double3;")
    subDouble4 = JavaMethod("()Landroid/renderscript/Double4;")
    subFloat2 = JavaMethod("()Landroid/renderscript/Float2;")
    subFloat3 = JavaMethod("()Landroid/renderscript/Float3;")
    subFloat4 = JavaMethod("()Landroid/renderscript/Float4;")
    subInt2 = JavaMethod("()Landroid/renderscript/Int2;")
    subInt3 = JavaMethod("()Landroid/renderscript/Int3;")
    subInt4 = JavaMethod("()Landroid/renderscript/Int4;")
    subLong2 = JavaMethod("()Landroid/renderscript/Long2;")
    subLong3 = JavaMethod("()Landroid/renderscript/Long3;")
    subLong4 = JavaMethod("()Landroid/renderscript/Long4;")
    subMatrix2f = JavaMethod("()Landroid/renderscript/Matrix2f;")
    subMatrix3f = JavaMethod("()Landroid/renderscript/Matrix3f;")
    subMatrix4f = JavaMethod("()Landroid/renderscript/Matrix4f;")
    subShort2 = JavaMethod("()Landroid/renderscript/Short2;")
    subShort3 = JavaMethod("()Landroid/renderscript/Short3;")
    subShort4 = JavaMethod("()Landroid/renderscript/Short4;")
    subalign = JavaMethod("(I)V")
    getData = JavaMethod("()[B")
    reset = JavaMultipleMethod([("(I)V", False, False), ("()V", False, False)])
    align = JavaMethod("(I)V")
    skip = JavaMethod("(I)V")

class RSIllegalArgumentException(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "android/renderscript/RSIllegalArgumentException"
    __javaconstructor__ = [("(Ljava/lang/String;)V", False)]

class Float4(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "android/renderscript/Float4"
    __javaconstructor__ = [("()V", False), ("(FFFF)V", False)]
    w = JavaField("F")
    x = JavaField("F")
    y = JavaField("F")
    z = JavaField("F")

class ScriptIntrinsicResize(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "android/renderscript/ScriptIntrinsicResize"
    getKernelID_bicubic = JavaMethod("()Landroid/renderscript/Script$KernelID;")
    forEach_bicubic = JavaMultipleMethod([("(Landroid/renderscript/Allocation;)V", False, False), ("(Landroid/renderscript/Allocation;Landroid/renderscript/Script$LaunchOptions;)V", False, False)])
    getFieldID_Input = JavaMethod("()Landroid/renderscript/Script$FieldID;")
    create = JavaStaticMethod("(Landroid/renderscript/RenderScript;)Landroid/renderscript/ScriptIntrinsicResize;")
    setInput = JavaMethod("(Landroid/renderscript/Allocation;)V")

class AllocationAdapter(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "android/renderscript/AllocationAdapter"
    USAGE_GRAPHICS_CONSTANTS = JavaStaticField("I")
    USAGE_GRAPHICS_RENDER_TARGET = JavaStaticField("I")
    USAGE_GRAPHICS_TEXTURE = JavaStaticField("I")
    USAGE_GRAPHICS_VERTEX = JavaStaticField("I")
    USAGE_IO_INPUT = JavaStaticField("I")
    USAGE_IO_OUTPUT = JavaStaticField("I")
    USAGE_SCRIPT = JavaStaticField("I")
    USAGE_SHARED = JavaStaticField("I")
    setLOD = JavaMethod("(I)V")
    create1D = JavaStaticMethod("(Landroid/renderscript/RenderScript;Landroid/renderscript/Allocation;)Landroid/renderscript/AllocationAdapter;")
    create2D = JavaStaticMethod("(Landroid/renderscript/RenderScript;Landroid/renderscript/Allocation;)Landroid/renderscript/AllocationAdapter;")
    setFace = JavaMethod("(Landroid/renderscript/Type$CubemapFace;)V")
    createTyped = JavaStaticMethod("(Landroid/renderscript/RenderScript;Landroid/renderscript/Allocation;Landroid/renderscript/Type;)Landroid/renderscript/AllocationAdapter;")
    resize = JavaMethod("(I)V")
    setX = JavaMethod("(I)V")
    setY = JavaMethod("(I)V")
    setZ = JavaMethod("(I)V")

class RSDriverException(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "android/renderscript/RSDriverException"
    __javaconstructor__ = [("(Ljava/lang/String;)V", False)]

class Short2(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "android/renderscript/Short2"
    __javaconstructor__ = [("()V", False), ("(SS)V", False)]
    x = JavaField("S")
    y = JavaField("S")

class ScriptIntrinsicColorMatrix(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "android/renderscript/ScriptIntrinsicColorMatrix"
    setColorMatrix = JavaMultipleMethod([("(Landroid/renderscript/Matrix3f;)V", False, False), ("(Landroid/renderscript/Matrix4f;)V", False, False)])
    setAdd = JavaMultipleMethod([("(FFFF)V", False, False), ("(Landroid/renderscript/Float4;)V", False, False)])
    setGreyscale = JavaMethod("()V")
    setRGBtoYUV = JavaMethod("()V")
    setYUVtoRGB = JavaMethod("()V")
    getKernelID = JavaMethod("()Landroid/renderscript/Script$KernelID;")
    create = JavaMultipleMethod([("(Landroid/renderscript/RenderScript;)Landroid/renderscript/ScriptIntrinsicColorMatrix;", True, False), ("(Landroid/renderscript/RenderScript;Landroid/renderscript/Element;)Landroid/renderscript/ScriptIntrinsicColorMatrix;", True, False)])
    forEach = JavaMultipleMethod([("(Landroid/renderscript/Allocation;Landroid/renderscript/Allocation;Landroid/renderscript/Script$LaunchOptions;)V", False, False), ("(Landroid/renderscript/Allocation;Landroid/renderscript/Allocation;)V", False, False)])

class Type(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "android/renderscript/Type"
    getYuv = JavaMethod("()I")
    createX = JavaStaticMethod("(Landroid/renderscript/RenderScript;Landroid/renderscript/Element;I)Landroid/renderscript/Type;")
    createXY = JavaStaticMethod("(Landroid/renderscript/RenderScript;Landroid/renderscript/Element;II)Landroid/renderscript/Type;")
    createXYZ = JavaStaticMethod("(Landroid/renderscript/RenderScript;Landroid/renderscript/Element;III)Landroid/renderscript/Type;")
    hasFaces = JavaMethod("()Z")
    hasMipmaps = JavaMethod("()Z")
    getCount = JavaMethod("()I")
    getX = JavaMethod("()I")
    getY = JavaMethod("()I")
    getZ = JavaMethod("()I")
    getElement = JavaMethod("()Landroid/renderscript/Element;")

    class CubemapFace(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "android/renderscript/Type$CubemapFace"
        NEGATIVE_X = JavaStaticField("Landroid/renderscript/Type$CubemapFace;")
        NEGATIVE_Y = JavaStaticField("Landroid/renderscript/Type$CubemapFace;")
        NEGATIVE_Z = JavaStaticField("Landroid/renderscript/Type$CubemapFace;")
        POSITIVE_X = JavaStaticField("Landroid/renderscript/Type$CubemapFace;")
        POSITIVE_Y = JavaStaticField("Landroid/renderscript/Type$CubemapFace;")
        POSITIVE_Z = JavaStaticField("Landroid/renderscript/Type$CubemapFace;")
        POSITVE_X = JavaStaticField("Landroid/renderscript/Type$CubemapFace;")
        POSITVE_Y = JavaStaticField("Landroid/renderscript/Type$CubemapFace;")
        POSITVE_Z = JavaStaticField("Landroid/renderscript/Type$CubemapFace;")
        values = JavaStaticMethod("()[Landroid/renderscript/Type$CubemapFace;")
        valueOf = JavaStaticMethod("(Ljava/lang/String;)Landroid/renderscript/Type$CubemapFace;")
        NEGATIVE_X = JavaStaticField("Landroid/renderscript/Type$CubemapFace;")
        NEGATIVE_Y = JavaStaticField("Landroid/renderscript/Type$CubemapFace;")
        NEGATIVE_Z = JavaStaticField("Landroid/renderscript/Type$CubemapFace;")
        POSITIVE_X = JavaStaticField("Landroid/renderscript/Type$CubemapFace;")
        POSITIVE_Y = JavaStaticField("Landroid/renderscript/Type$CubemapFace;")
        POSITIVE_Z = JavaStaticField("Landroid/renderscript/Type$CubemapFace;")
        POSITVE_X = JavaStaticField("Landroid/renderscript/Type$CubemapFace;")
        POSITVE_Y = JavaStaticField("Landroid/renderscript/Type$CubemapFace;")
        POSITVE_Z = JavaStaticField("Landroid/renderscript/Type$CubemapFace;")

    class Builder(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "android/renderscript/Type$Builder"
        __javaconstructor__ = [("(Landroid/renderscript/RenderScript;Landroid/renderscript/Element;)V", False)]
        setFaces = JavaMethod("(Z)Landroid/renderscript/Type$Builder;")
        setMipmaps = JavaMethod("(Z)Landroid/renderscript/Type$Builder;")
        setYuvFormat = JavaMethod("(I)Landroid/renderscript/Type$Builder;")
        create = JavaMethod("()Landroid/renderscript/Type;")
        setX = JavaMethod("(I)Landroid/renderscript/Type$Builder;")
        setY = JavaMethod("(I)Landroid/renderscript/Type$Builder;")
        setZ = JavaMethod("(I)Landroid/renderscript/Type$Builder;")

class Double3(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "android/renderscript/Double3"
    __javaconstructor__ = [("()V", False), ("(DDD)V", False)]
    x = JavaField("D")
    y = JavaField("D")
    z = JavaField("D")

class RSRuntimeException(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "android/renderscript/RSRuntimeException"
    __javaconstructor__ = [("(Ljava/lang/String;)V", False)]

class ScriptIntrinsicBlur(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "android/renderscript/ScriptIntrinsicBlur"
    setRadius = JavaMethod("(F)V")
    getKernelID = JavaMethod("()Landroid/renderscript/Script$KernelID;")
    getFieldID_Input = JavaMethod("()Landroid/renderscript/Script$FieldID;")
    create = JavaStaticMethod("(Landroid/renderscript/RenderScript;Landroid/renderscript/Element;)Landroid/renderscript/ScriptIntrinsicBlur;")
    forEach = JavaMultipleMethod([("(Landroid/renderscript/Allocation;)V", False, False), ("(Landroid/renderscript/Allocation;Landroid/renderscript/Script$LaunchOptions;)V", False, False)])
    setInput = JavaMethod("(Landroid/renderscript/Allocation;)V")

class Double2(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "android/renderscript/Double2"
    __javaconstructor__ = [("()V", False), ("(DD)V", False)]
    x = JavaField("D")
    y = JavaField("D")

class Byte4(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "android/renderscript/Byte4"
    __javaconstructor__ = [("()V", False), ("(BBBB)V", False)]
    w = JavaField("B")
    x = JavaField("B")
    y = JavaField("B")
    z = JavaField("B")

class Matrix4f(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "android/renderscript/Matrix4f"
    __javaconstructor__ = [("()V", False), ("([F)V", False)]
    inverseTranspose = JavaMethod("()Z")
    loadFrustum = JavaMethod("(FFFFFF)V")
    loadOrtho = JavaMethod("(FFFFFF)V")
    loadOrthoWindow = JavaMethod("(II)V")
    loadPerspective = JavaMethod("(FFFF)V")
    loadProjectionNormalized = JavaMethod("(II)V")
    loadIdentity = JavaMethod("()V")
    loadMultiply = JavaMethod("(Landroid/renderscript/Matrix4f;Landroid/renderscript/Matrix4f;)V")
    loadRotate = JavaMethod("(FFFF)V")
    loadScale = JavaMethod("(FFF)V")
    loadTranslate = JavaMethod("(FFF)V")
    transpose = JavaMethod("()V")
    getArray = JavaMethod("()[F")
    multiply = JavaMethod("(Landroid/renderscript/Matrix4f;)V")
    get = JavaMethod("(II)F")
    load = JavaMethod("(Landroid/renderscript/Matrix4f;)V")
    scale = JavaMethod("(FFF)V")
    set = JavaMethod("(IIF)V")
    inverse = JavaMethod("()Z")
    translate = JavaMethod("(FFF)V")
    rotate = JavaMethod("(FFFF)V")

class ScriptIntrinsicYuvToRGB(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "android/renderscript/ScriptIntrinsicYuvToRGB"
    getKernelID = JavaMethod("()Landroid/renderscript/Script$KernelID;")
    getFieldID_Input = JavaMethod("()Landroid/renderscript/Script$FieldID;")
    create = JavaStaticMethod("(Landroid/renderscript/RenderScript;Landroid/renderscript/Element;)Landroid/renderscript/ScriptIntrinsicYuvToRGB;")
    forEach = JavaMethod("(Landroid/renderscript/Allocation;)V")
    setInput = JavaMethod("(Landroid/renderscript/Allocation;)V")

class Int4(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "android/renderscript/Int4"
    __javaconstructor__ = [("()V", False), ("(IIII)V", False)]
    w = JavaField("I")
    x = JavaField("I")
    y = JavaField("I")
    z = JavaField("I")

class Matrix2f(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "android/renderscript/Matrix2f"
    __javaconstructor__ = [("([F)V", False), ("()V", False)]
    loadIdentity = JavaMethod("()V")
    loadMultiply = JavaMethod("(Landroid/renderscript/Matrix2f;Landroid/renderscript/Matrix2f;)V")
    loadRotate = JavaMethod("(F)V")
    loadScale = JavaMethod("(FF)V")
    transpose = JavaMethod("()V")
    getArray = JavaMethod("()[F")
    multiply = JavaMethod("(Landroid/renderscript/Matrix2f;)V")
    get = JavaMethod("(II)F")
    load = JavaMethod("(Landroid/renderscript/Matrix2f;)V")
    scale = JavaMethod("(FF)V")
    set = JavaMethod("(IIF)V")
    rotate = JavaMethod("(F)V")