from typing import Any, ClassVar, overload
from android.text.TextPaint import TextPaint

class GraphemeClusterSegmentFinder:
    DONE: ClassVar[int]
    def __init__(self, p0: str, p1: TextPaint) -> None: ...
    def nextEndBoundary(self, p0: int) -> int: ...
    def nextStartBoundary(self, p0: int) -> int: ...
    def previousEndBoundary(self, p0: int) -> int: ...
    def previousStartBoundary(self, p0: int) -> int: ...

from typing import Any, ClassVar, overload

class NoCopySpan:

    class Concrete:
        def __init__(self) -> None: ...

from typing import Any, ClassVar, overload
from android.text.Spanned import Spanned
from java.util.Locale import Locale

class InputFilter:
    def filter(self, p0: str, p1: int, p2: int, p3: Spanned, p4: int, p5: int) -> str: ...

    class LengthFilter:
        def __init__(self, p0: int) -> None: ...
        def filter(self, p0: str, p1: int, p2: int, p3: Spanned, p4: int, p5: int) -> str: ...
        def getMax(self) -> int: ...

    class AllCaps:
        @overload
        def __init__(self) -> None: ...
        @overload
        def __init__(self, p0: Locale) -> None: ...
        def filter(self, p0: str, p1: int, p2: int, p3: Spanned, p4: int, p5: int) -> str: ...

from typing import Any, ClassVar, overload

class GetChars:
    def getChars(self, p0: int, p1: int, p2: Any, p3: int) -> None: ...

from typing import Any, ClassVar, overload
from android.text.Layout import Layout
from android.text.Spannable import Spannable

class Selection:
    SELECTION_END: ClassVar[Any]
    SELECTION_START: ClassVar[Any]
    @staticmethod
    def moveUp(p0: Spannable, p1: Layout) -> bool: ...
    @staticmethod
    def extendDown(p0: Spannable, p1: Layout) -> bool: ...
    @staticmethod
    def extendLeft(p0: Spannable, p1: Layout) -> bool: ...
    @staticmethod
    def extendRight(p0: Spannable, p1: Layout) -> bool: ...
    @staticmethod
    def extendToLeftEdge(p0: Spannable, p1: Layout) -> bool: ...
    @staticmethod
    def extendToParagraphEnd(p0: Spannable) -> bool: ...
    @staticmethod
    def extendToParagraphStart(p0: Spannable) -> bool: ...
    @staticmethod
    def extendToRightEdge(p0: Spannable, p1: Layout) -> bool: ...
    @staticmethod
    def extendUp(p0: Spannable, p1: Layout) -> bool: ...
    @staticmethod
    def moveDown(p0: Spannable, p1: Layout) -> bool: ...
    @staticmethod
    def moveLeft(p0: Spannable, p1: Layout) -> bool: ...
    @staticmethod
    def moveRight(p0: Spannable, p1: Layout) -> bool: ...
    @staticmethod
    def moveToLeftEdge(p0: Spannable, p1: Layout) -> bool: ...
    @staticmethod
    def moveToParagraphEnd(p0: Spannable, p1: Layout) -> bool: ...
    @staticmethod
    def moveToParagraphStart(p0: Spannable, p1: Layout) -> bool: ...
    @staticmethod
    def moveToRightEdge(p0: Spannable, p1: Layout) -> bool: ...
    @staticmethod
    def removeSelection(p0: Spannable) -> None: ...
    @staticmethod
    def extendSelection(p0: Spannable, p1: int) -> None: ...
    @staticmethod
    def selectAll(p0: Spannable) -> None: ...
    @overload
    @staticmethod
    def setSelection(p0: Spannable, p1: int) -> None: ...
    @overload
    @staticmethod
    def setSelection(p0: Spannable, p1: int, p2: int) -> None: ...
    @staticmethod
    def getSelectionEnd(p0: str) -> int: ...
    @staticmethod
    def getSelectionStart(p0: str) -> int: ...

from typing import Any, ClassVar, overload
from android.text.Spanned import Spanned

class LoginFilter:
    def isAllowed(self, p0: str) -> bool: ...
    def onInvalidCharacter(self, p0: str) -> None: ...
    def filter(self, p0: str, p1: int, p2: int, p3: Spanned, p4: int, p5: int) -> str: ...
    def onStart(self) -> None: ...
    def onStop(self) -> None: ...

    class UsernameFilterGeneric:
        @overload
        def __init__(self, p0: bool) -> None: ...
        @overload
        def __init__(self) -> None: ...
        def isAllowed(self, p0: str) -> bool: ...

    class UsernameFilterGMail:
        @overload
        def __init__(self, p0: bool) -> None: ...
        @overload
        def __init__(self) -> None: ...
        def isAllowed(self, p0: str) -> bool: ...

    class PasswordFilterGMail:
        @overload
        def __init__(self, p0: bool) -> None: ...
        @overload
        def __init__(self) -> None: ...
        def isAllowed(self, p0: str) -> bool: ...

from typing import Any, ClassVar, overload
from android.graphics.Rect import Rect
from android.graphics.text.LineBreakConfig import LineBreakConfig
from android.text.TextDirectionHeuristic import TextDirectionHeuristic
from android.text.TextPaint import TextPaint

class PrecomputedText:
    SPAN_COMPOSING: ClassVar[int]
    SPAN_EXCLUSIVE_EXCLUSIVE: ClassVar[int]
    SPAN_EXCLUSIVE_INCLUSIVE: ClassVar[int]
    SPAN_INCLUSIVE_EXCLUSIVE: ClassVar[int]
    SPAN_INCLUSIVE_INCLUSIVE: ClassVar[int]
    SPAN_INTERMEDIATE: ClassVar[int]
    SPAN_MARK_MARK: ClassVar[int]
    SPAN_MARK_POINT: ClassVar[int]
    SPAN_PARAGRAPH: ClassVar[int]
    SPAN_POINT_MARK: ClassVar[int]
    SPAN_POINT_MARK_MASK: ClassVar[int]
    SPAN_POINT_POINT: ClassVar[int]
    SPAN_PRIORITY: ClassVar[int]
    SPAN_PRIORITY_SHIFT: ClassVar[int]
    SPAN_USER: ClassVar[int]
    SPAN_USER_SHIFT: ClassVar[int]
    def getParagraphCount(self) -> int: ...
    def getParagraphEnd(self, p0: int) -> int: ...
    def getParagraphStart(self, p0: int) -> int: ...
    @staticmethod
    def create(p0: str, p1: Any) -> "PrecomputedText": ...
    def length(self) -> int: ...
    def toString(self) -> str: ...
    def charAt(self, p0: int) -> str: ...
    def subSequence(self, p0: int, p1: int) -> str: ...
    def getBounds(self, p0: int, p1: int, p2: Rect) -> None: ...
    def removeSpan(self, p0: Any) -> None: ...
    def setSpan(self, p0: Any, p1: int, p2: int, p3: int) -> None: ...
    def getSpanEnd(self, p0: Any) -> int: ...
    def getSpanFlags(self, p0: Any) -> int: ...
    def getSpanStart(self, p0: Any) -> int: ...
    def nextSpanTransition(self, p0: int, p1: int, p2: type) -> int: ...
    def getWidth(self, p0: int, p1: int) -> float: ...
    def getParams(self) -> Any: ...
    def getFontMetricsInt(self, p0: int, p1: int, p2: Any) -> None: ...
    def getSpans(self, p0: int, p1: int, p2: type) -> Any: ...

    class Params:
        def equals(self, p0: Any) -> bool: ...
        def toString(self) -> str: ...
        def hashCode(self) -> int: ...
        def getTextDirection(self) -> TextDirectionHeuristic: ...
        def getLineBreakConfig(self) -> LineBreakConfig: ...
        def getTextPaint(self) -> TextPaint: ...
        def getBreakStrategy(self) -> int: ...
        def getHyphenationFrequency(self) -> int: ...

        class Builder:
            @overload
            def __init__(self, p0: Any) -> None: ...
            @overload
            def __init__(self, p0: TextPaint) -> None: ...
            def setLineBreakConfig(self, p0: LineBreakConfig) -> Any: ...
            def setTextDirection(self, p0: TextDirectionHeuristic) -> Any: ...
            def build(self) -> Any: ...
            def setBreakStrategy(self, p0: int) -> Any: ...
            def setHyphenationFrequency(self, p0: int) -> Any: ...

from typing import Any, ClassVar, overload
from android.text.Spannable import Spannable

class SpanWatcher:
    def onSpanAdded(self, p0: Spannable, p1: Any, p2: int, p3: int) -> None: ...
    def onSpanRemoved(self, p0: Spannable, p1: Any, p2: int, p3: int) -> None: ...
    def onSpanChanged(self, p0: Spannable, p1: Any, p2: int, p3: int, p4: int, p5: int) -> None: ...

from typing import Any, ClassVar, overload
from android.graphics.text.LineBreakConfig import LineBreakConfig
from android.text.TextDirectionHeuristic import TextDirectionHeuristic
from android.text.TextPaint import TextPaint

class DynamicLayout:
    BREAK_STRATEGY_BALANCED: ClassVar[int]
    BREAK_STRATEGY_HIGH_QUALITY: ClassVar[int]
    BREAK_STRATEGY_SIMPLE: ClassVar[int]
    DEFAULT_LINESPACING_ADDITION: ClassVar[float]
    DEFAULT_LINESPACING_MULTIPLIER: ClassVar[float]
    DIR_LEFT_TO_RIGHT: ClassVar[int]
    DIR_RIGHT_TO_LEFT: ClassVar[int]
    HYPHENATION_FREQUENCY_FULL: ClassVar[int]
    HYPHENATION_FREQUENCY_FULL_FAST: ClassVar[int]
    HYPHENATION_FREQUENCY_NONE: ClassVar[int]
    HYPHENATION_FREQUENCY_NORMAL: ClassVar[int]
    HYPHENATION_FREQUENCY_NORMAL_FAST: ClassVar[int]
    INCLUSION_STRATEGY_ANY_OVERLAP: ClassVar[Any]
    INCLUSION_STRATEGY_CONTAINS_ALL: ClassVar[Any]
    INCLUSION_STRATEGY_CONTAINS_CENTER: ClassVar[Any]
    JUSTIFICATION_MODE_INTER_CHARACTER: ClassVar[int]
    JUSTIFICATION_MODE_INTER_WORD: ClassVar[int]
    JUSTIFICATION_MODE_NONE: ClassVar[int]
    @overload
    def __init__(self, p0: str, p1: str, p2: TextPaint, p3: int, p4: Any, p5: float, p6: float, p7: bool, p8: Any, p9: int) -> None: ...
    @overload
    def __init__(self, p0: str, p1: str, p2: TextPaint, p3: int, p4: Any, p5: float, p6: float, p7: bool) -> None: ...
    @overload
    def __init__(self, p0: str, p1: TextPaint, p2: int, p3: Any, p4: float, p5: float, p6: bool) -> None: ...
    def getBottomPadding(self) -> int: ...
    def getEllipsisCount(self, p0: int) -> int: ...
    def getEllipsisStart(self, p0: int) -> int: ...
    def getEllipsizedWidth(self) -> int: ...
    def getLineBreakConfig(self) -> LineBreakConfig: ...
    def getLineContainsTab(self, p0: int) -> bool: ...
    def getLineDescent(self, p0: int) -> int: ...
    def getLineDirections(self, p0: int) -> Any: ...
    def getLineStart(self, p0: int) -> int: ...
    def getLineTop(self, p0: int) -> int: ...
    def getParagraphDirection(self, p0: int) -> int: ...
    def getTopPadding(self) -> int: ...
    def getLineCount(self) -> int: ...

    class Builder:
        def setLineBreakConfig(self, p0: LineBreakConfig) -> Any: ...
        def setDisplayText(self, p0: str) -> Any: ...
        def setAlignment(self, p0: Any) -> Any: ...
        def setEllipsizedWidth(self, p0: int) -> Any: ...
        def setIncludePad(self, p0: bool) -> Any: ...
        def setUseLineSpacingFromFallbacks(self, p0: bool) -> Any: ...
        def setTextDirection(self, p0: TextDirectionHeuristic) -> Any: ...
        @staticmethod
        def obtain(p0: str, p1: TextPaint, p2: int) -> Any: ...
        def build(self) -> "DynamicLayout": ...
        def setBreakStrategy(self, p0: int) -> Any: ...
        def setEllipsize(self, p0: Any) -> Any: ...
        def setHyphenationFrequency(self, p0: int) -> Any: ...
        def setJustificationMode(self, p0: int) -> Any: ...
        def setLineSpacing(self, p0: float, p1: float) -> Any: ...
        def setMinimumFontMetrics(self, p0: Any) -> Any: ...
        def setShiftDrawingOffsetForStartOverhang(self, p0: bool) -> Any: ...
        def setUseBoundsForWidth(self, p0: bool) -> Any: ...

from typing import Any, ClassVar, overload
from android.graphics.RectF import RectF
from android.graphics.text.LineBreakConfig import LineBreakConfig
from android.text.TextDirectionHeuristic import TextDirectionHeuristic
from android.text.TextPaint import TextPaint

class StaticLayout:
    BREAK_STRATEGY_BALANCED: ClassVar[int]
    BREAK_STRATEGY_HIGH_QUALITY: ClassVar[int]
    BREAK_STRATEGY_SIMPLE: ClassVar[int]
    DEFAULT_LINESPACING_ADDITION: ClassVar[float]
    DEFAULT_LINESPACING_MULTIPLIER: ClassVar[float]
    DIR_LEFT_TO_RIGHT: ClassVar[int]
    DIR_RIGHT_TO_LEFT: ClassVar[int]
    HYPHENATION_FREQUENCY_FULL: ClassVar[int]
    HYPHENATION_FREQUENCY_FULL_FAST: ClassVar[int]
    HYPHENATION_FREQUENCY_NONE: ClassVar[int]
    HYPHENATION_FREQUENCY_NORMAL: ClassVar[int]
    HYPHENATION_FREQUENCY_NORMAL_FAST: ClassVar[int]
    INCLUSION_STRATEGY_ANY_OVERLAP: ClassVar[Any]
    INCLUSION_STRATEGY_CONTAINS_ALL: ClassVar[Any]
    INCLUSION_STRATEGY_CONTAINS_CENTER: ClassVar[Any]
    JUSTIFICATION_MODE_INTER_CHARACTER: ClassVar[int]
    JUSTIFICATION_MODE_INTER_WORD: ClassVar[int]
    JUSTIFICATION_MODE_NONE: ClassVar[int]
    @overload
    def __init__(self, p0: str, p1: int, p2: int, p3: TextPaint, p4: int, p5: Any, p6: float, p7: float, p8: bool, p9: Any, p10: int) -> None: ...
    @overload
    def __init__(self, p0: str, p1: int, p2: int, p3: TextPaint, p4: int, p5: Any, p6: float, p7: float, p8: bool) -> None: ...
    @overload
    def __init__(self, p0: str, p1: TextPaint, p2: int, p3: Any, p4: float, p5: float, p6: bool) -> None: ...
    def computeDrawingBoundingBox(self) -> RectF: ...
    def getBottomPadding(self) -> int: ...
    def getEllipsisCount(self, p0: int) -> int: ...
    def getEllipsisStart(self, p0: int) -> int: ...
    def getLineContainsTab(self, p0: int) -> bool: ...
    def getLineDescent(self, p0: int) -> int: ...
    def getLineDirections(self, p0: int) -> Any: ...
    def getLineForVertical(self, p0: int) -> int: ...
    def getLineStart(self, p0: int) -> int: ...
    def getLineTop(self, p0: int) -> int: ...
    def getParagraphDirection(self, p0: int) -> int: ...
    def getTopPadding(self) -> int: ...
    def getLineCount(self) -> int: ...

    class Builder:
        def setIndents(self, p0: Any, p1: Any) -> Any: ...
        def setLineBreakConfig(self, p0: LineBreakConfig) -> Any: ...
        def setAlignment(self, p0: Any) -> Any: ...
        def setEllipsizedWidth(self, p0: int) -> Any: ...
        def setIncludePad(self, p0: bool) -> Any: ...
        def setUseLineSpacingFromFallbacks(self, p0: bool) -> Any: ...
        def setTextDirection(self, p0: TextDirectionHeuristic) -> Any: ...
        @staticmethod
        def obtain(p0: str, p1: int, p2: int, p3: TextPaint, p4: int) -> Any: ...
        def build(self) -> "StaticLayout": ...
        def setBreakStrategy(self, p0: int) -> Any: ...
        def setEllipsize(self, p0: Any) -> Any: ...
        def setHyphenationFrequency(self, p0: int) -> Any: ...
        def setJustificationMode(self, p0: int) -> Any: ...
        def setLineSpacing(self, p0: float, p1: float) -> Any: ...
        def setMaxLines(self, p0: int) -> Any: ...
        def setMinimumFontMetrics(self, p0: Any) -> Any: ...
        def setShiftDrawingOffsetForStartOverhang(self, p0: bool) -> Any: ...
        def setText(self, p0: str) -> Any: ...
        def setUseBoundsForWidth(self, p0: bool) -> Any: ...

from typing import Any, ClassVar, overload

class SegmentFinder:
    DONE: ClassVar[int]
    def __init__(self) -> None: ...
    def nextEndBoundary(self, p0: int) -> int: ...
    def nextStartBoundary(self, p0: int) -> int: ...
    def previousEndBoundary(self, p0: int) -> int: ...
    def previousStartBoundary(self, p0: int) -> int: ...

    class PrescribedSegmentFinder:
        DONE: ClassVar[int]
        def __init__(self, p0: Any) -> None: ...
        def nextEndBoundary(self, p0: int) -> int: ...
        def nextStartBoundary(self, p0: int) -> int: ...
        def previousEndBoundary(self, p0: int) -> int: ...
        def previousStartBoundary(self, p0: int) -> int: ...

from typing import Any, ClassVar, overload
from android.graphics.Paint import Paint

class Highlights:
    def getRanges(self, p0: int) -> Any: ...
    def getSize(self) -> int: ...
    def getPaint(self, p0: int) -> Paint: ...

    class Builder:
        def __init__(self) -> None: ...
        def addRanges(self, p0: Paint, p1: Any) -> Any: ...
        def addRange(self, p0: Paint, p1: int, p2: int) -> Any: ...
        def build(self) -> "Highlights": ...

from typing import Any, ClassVar, overload

class ParcelableSpan:
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    def getSpanTypeId(self) -> int: ...

from typing import Any, ClassVar, overload

class TextDirectionHeuristic:
    @overload
    def isRtl(self, p0: Any, p1: int, p2: int) -> bool: ...
    @overload
    def isRtl(self, p0: str, p1: int, p2: int) -> bool: ...

from typing import Any, ClassVar, overload

class Spannable:
    SPAN_COMPOSING: ClassVar[int]
    SPAN_EXCLUSIVE_EXCLUSIVE: ClassVar[int]
    SPAN_EXCLUSIVE_INCLUSIVE: ClassVar[int]
    SPAN_INCLUSIVE_EXCLUSIVE: ClassVar[int]
    SPAN_INCLUSIVE_INCLUSIVE: ClassVar[int]
    SPAN_INTERMEDIATE: ClassVar[int]
    SPAN_MARK_MARK: ClassVar[int]
    SPAN_MARK_POINT: ClassVar[int]
    SPAN_PARAGRAPH: ClassVar[int]
    SPAN_POINT_MARK: ClassVar[int]
    SPAN_POINT_MARK_MASK: ClassVar[int]
    SPAN_POINT_POINT: ClassVar[int]
    SPAN_PRIORITY: ClassVar[int]
    SPAN_PRIORITY_SHIFT: ClassVar[int]
    SPAN_USER: ClassVar[int]
    SPAN_USER_SHIFT: ClassVar[int]
    def removeSpan(self, p0: Any) -> None: ...
    def setSpan(self, p0: Any, p1: int, p2: int, p3: int) -> None: ...

    class Factory:
        def __init__(self) -> None: ...
        @staticmethod
        def getInstance() -> Any: ...
        def newSpannable(self, p0: str) -> "Spannable": ...

from typing import Any, ClassVar, overload
from android.view.View import View

class AutoText:
    @staticmethod
    def get(p0: str, p1: int, p2: int, p3: View) -> str: ...
    @staticmethod
    def getSize(p0: View) -> int: ...

from typing import Any, ClassVar, overload
from android.graphics.Canvas import Canvas
from android.graphics.Paint import Paint
from android.graphics.Path import Path
from android.graphics.RectF import RectF
from android.text.TextDirectionHeuristic import TextDirectionHeuristic
from android.text.TextPaint import TextPaint

class BoringLayout:
    BREAK_STRATEGY_BALANCED: ClassVar[int]
    BREAK_STRATEGY_HIGH_QUALITY: ClassVar[int]
    BREAK_STRATEGY_SIMPLE: ClassVar[int]
    DEFAULT_LINESPACING_ADDITION: ClassVar[float]
    DEFAULT_LINESPACING_MULTIPLIER: ClassVar[float]
    DIR_LEFT_TO_RIGHT: ClassVar[int]
    DIR_RIGHT_TO_LEFT: ClassVar[int]
    HYPHENATION_FREQUENCY_FULL: ClassVar[int]
    HYPHENATION_FREQUENCY_FULL_FAST: ClassVar[int]
    HYPHENATION_FREQUENCY_NONE: ClassVar[int]
    HYPHENATION_FREQUENCY_NORMAL: ClassVar[int]
    HYPHENATION_FREQUENCY_NORMAL_FAST: ClassVar[int]
    INCLUSION_STRATEGY_ANY_OVERLAP: ClassVar[Any]
    INCLUSION_STRATEGY_CONTAINS_ALL: ClassVar[Any]
    INCLUSION_STRATEGY_CONTAINS_CENTER: ClassVar[Any]
    JUSTIFICATION_MODE_INTER_CHARACTER: ClassVar[int]
    JUSTIFICATION_MODE_INTER_WORD: ClassVar[int]
    JUSTIFICATION_MODE_NONE: ClassVar[int]
    @overload
    def __init__(self, p0: str, p1: TextPaint, p2: int, p3: Any, p4: float, p5: float, p6: Any, p7: bool) -> None: ...
    @overload
    def __init__(self, p0: str, p1: TextPaint, p2: int, p3: Any, p4: float, p5: float, p6: Any, p7: bool, p8: Any, p9: int, p10: bool) -> None: ...
    @overload
    def __init__(self, p0: str, p1: TextPaint, p2: int, p3: Any, p4: float, p5: float, p6: Any, p7: bool, p8: Any, p9: int) -> None: ...
    def ellipsized(self, p0: int, p1: int) -> None: ...
    @overload
    @staticmethod
    def isBoring(p0: str, p1: TextPaint, p2: TextDirectionHeuristic, p3: bool, p4: Any) -> Any: ...
    @overload
    @staticmethod
    def isBoring(p0: str, p1: TextPaint, p2: Any) -> Any: ...
    @overload
    @staticmethod
    def isBoring(p0: str, p1: TextPaint) -> Any: ...
    @overload
    def replaceOrMake(self, p0: str, p1: TextPaint, p2: int, p3: Any, p4: float, p5: float, p6: Any, p7: bool, p8: Any, p9: int) -> "BoringLayout": ...
    @overload
    def replaceOrMake(self, p0: str, p1: TextPaint, p2: int, p3: Any, p4: Any, p5: bool, p6: Any, p7: int, p8: bool) -> "BoringLayout": ...
    @overload
    def replaceOrMake(self, p0: str, p1: TextPaint, p2: int, p3: Any, p4: float, p5: float, p6: Any, p7: bool) -> "BoringLayout": ...
    @overload
    @staticmethod
    def make(p0: str, p1: TextPaint, p2: int, p3: Any, p4: float, p5: float, p6: Any, p7: bool) -> "BoringLayout": ...
    @overload
    @staticmethod
    def make(p0: str, p1: TextPaint, p2: int, p3: Any, p4: float, p5: float, p6: Any, p7: bool, p8: Any, p9: int) -> "BoringLayout": ...
    @overload
    @staticmethod
    def make(p0: str, p1: TextPaint, p2: int, p3: Any, p4: Any, p5: bool, p6: Any, p7: int, p8: bool) -> "BoringLayout": ...
    def draw(self, p0: Canvas, p1: Path, p2: Paint, p3: int) -> None: ...
    def getHeight(self) -> int: ...
    def computeDrawingBoundingBox(self) -> RectF: ...
    def getBottomPadding(self) -> int: ...
    def getEllipsisCount(self, p0: int) -> int: ...
    def getEllipsisStart(self, p0: int) -> int: ...
    def getEllipsizedWidth(self) -> int: ...
    def getLineContainsTab(self, p0: int) -> bool: ...
    def getLineDescent(self, p0: int) -> int: ...
    def getLineDirections(self, p0: int) -> Any: ...
    def getLineMax(self, p0: int) -> float: ...
    def getLineStart(self, p0: int) -> int: ...
    def getLineTop(self, p0: int) -> int: ...
    def getLineWidth(self, p0: int) -> float: ...
    def getParagraphDirection(self, p0: int) -> int: ...
    def getTopPadding(self) -> int: ...
    def isFallbackLineSpacingEnabled(self) -> bool: ...
    def getLineCount(self) -> int: ...

    class Metrics:
        width: int
        ascent: int
        bottom: int
        descent: int
        leading: int
        top: int
        def __init__(self) -> None: ...
        def getDrawingBoundingBox(self) -> RectF: ...
        def toString(self) -> str: ...

from typing import Any, ClassVar, overload
from android.icu.util.ULocale import ULocale

class WordSegmentFinder:
    DONE: ClassVar[int]
    def __init__(self, p0: str, p1: ULocale) -> None: ...
    def nextEndBoundary(self, p0: int) -> int: ...
    def nextStartBoundary(self, p0: int) -> int: ...
    def previousEndBoundary(self, p0: int) -> int: ...
    def previousStartBoundary(self, p0: int) -> int: ...

from typing import Any, ClassVar, overload
from android.graphics.text.PositionedGlyphs import PositionedGlyphs
from android.text.TextDirectionHeuristic import TextDirectionHeuristic
from android.text.TextPaint import TextPaint

class TextShaper:
    @staticmethod
    def shapeText(p0: str, p1: int, p2: int, p3: TextDirectionHeuristic, p4: TextPaint, p5: Any) -> None: ...

    class GlyphsConsumer:
        def accept(self, p0: int, p1: int, p2: PositionedGlyphs, p3: TextPaint) -> None: ...

from typing import Any, ClassVar, overload

class InputType:
    TYPE_CLASS_DATETIME: ClassVar[int]
    TYPE_CLASS_NUMBER: ClassVar[int]
    TYPE_CLASS_PHONE: ClassVar[int]
    TYPE_CLASS_TEXT: ClassVar[int]
    TYPE_DATETIME_VARIATION_DATE: ClassVar[int]
    TYPE_DATETIME_VARIATION_NORMAL: ClassVar[int]
    TYPE_DATETIME_VARIATION_TIME: ClassVar[int]
    TYPE_MASK_CLASS: ClassVar[int]
    TYPE_MASK_FLAGS: ClassVar[int]
    TYPE_MASK_VARIATION: ClassVar[int]
    TYPE_NULL: ClassVar[int]
    TYPE_NUMBER_FLAG_DECIMAL: ClassVar[int]
    TYPE_NUMBER_FLAG_SIGNED: ClassVar[int]
    TYPE_NUMBER_VARIATION_NORMAL: ClassVar[int]
    TYPE_NUMBER_VARIATION_PASSWORD: ClassVar[int]
    TYPE_TEXT_FLAG_AUTO_COMPLETE: ClassVar[int]
    TYPE_TEXT_FLAG_AUTO_CORRECT: ClassVar[int]
    TYPE_TEXT_FLAG_CAP_CHARACTERS: ClassVar[int]
    TYPE_TEXT_FLAG_CAP_SENTENCES: ClassVar[int]
    TYPE_TEXT_FLAG_CAP_WORDS: ClassVar[int]
    TYPE_TEXT_FLAG_ENABLE_TEXT_CONVERSION_SUGGESTIONS: ClassVar[int]
    TYPE_TEXT_FLAG_IME_MULTI_LINE: ClassVar[int]
    TYPE_TEXT_FLAG_MULTI_LINE: ClassVar[int]
    TYPE_TEXT_FLAG_NO_SUGGESTIONS: ClassVar[int]
    TYPE_TEXT_VARIATION_EMAIL_ADDRESS: ClassVar[int]
    TYPE_TEXT_VARIATION_EMAIL_SUBJECT: ClassVar[int]
    TYPE_TEXT_VARIATION_FILTER: ClassVar[int]
    TYPE_TEXT_VARIATION_LONG_MESSAGE: ClassVar[int]
    TYPE_TEXT_VARIATION_NORMAL: ClassVar[int]
    TYPE_TEXT_VARIATION_PASSWORD: ClassVar[int]
    TYPE_TEXT_VARIATION_PERSON_NAME: ClassVar[int]
    TYPE_TEXT_VARIATION_PHONETIC: ClassVar[int]
    TYPE_TEXT_VARIATION_POSTAL_ADDRESS: ClassVar[int]
    TYPE_TEXT_VARIATION_SHORT_MESSAGE: ClassVar[int]
    TYPE_TEXT_VARIATION_URI: ClassVar[int]
    TYPE_TEXT_VARIATION_VISIBLE_PASSWORD: ClassVar[int]
    TYPE_TEXT_VARIATION_WEB_EDIT_TEXT: ClassVar[int]
    TYPE_TEXT_VARIATION_WEB_EMAIL_ADDRESS: ClassVar[int]
    TYPE_TEXT_VARIATION_WEB_PASSWORD: ClassVar[int]

from typing import Any, ClassVar, overload
from android.graphics.Canvas import Canvas
from android.graphics.Paint import Paint
from android.graphics.Path import Path
from android.graphics.Rect import Rect
from android.graphics.RectF import RectF
from android.graphics.text.LineBreakConfig import LineBreakConfig
from android.text.SegmentFinder import SegmentFinder
from android.text.TextDirectionHeuristic import TextDirectionHeuristic
from android.text.TextPaint import TextPaint

class Layout:
    BREAK_STRATEGY_BALANCED: ClassVar[int]
    BREAK_STRATEGY_HIGH_QUALITY: ClassVar[int]
    BREAK_STRATEGY_SIMPLE: ClassVar[int]
    DEFAULT_LINESPACING_ADDITION: ClassVar[float]
    DEFAULT_LINESPACING_MULTIPLIER: ClassVar[float]
    DIR_LEFT_TO_RIGHT: ClassVar[int]
    DIR_RIGHT_TO_LEFT: ClassVar[int]
    HYPHENATION_FREQUENCY_FULL: ClassVar[int]
    HYPHENATION_FREQUENCY_FULL_FAST: ClassVar[int]
    HYPHENATION_FREQUENCY_NONE: ClassVar[int]
    HYPHENATION_FREQUENCY_NORMAL: ClassVar[int]
    HYPHENATION_FREQUENCY_NORMAL_FAST: ClassVar[int]
    INCLUSION_STRATEGY_ANY_OVERLAP: ClassVar[Any]
    INCLUSION_STRATEGY_CONTAINS_ALL: ClassVar[Any]
    INCLUSION_STRATEGY_CONTAINS_CENTER: ClassVar[Any]
    JUSTIFICATION_MODE_INTER_CHARACTER: ClassVar[int]
    JUSTIFICATION_MODE_INTER_WORD: ClassVar[int]
    JUSTIFICATION_MODE_NONE: ClassVar[int]
    @overload
    def draw(self, p0: Canvas, p1: list, p2: list, p3: Path, p4: Paint, p5: int) -> None: ...
    @overload
    def draw(self, p0: Canvas, p1: Path, p2: Paint, p3: int) -> None: ...
    @overload
    def draw(self, p0: Canvas) -> None: ...
    def getHeight(self) -> int: ...
    def getWidth(self) -> int: ...
    def getText(self) -> str: ...
    def computeDrawingBoundingBox(self) -> RectF: ...
    def drawBackground(self, p0: Canvas) -> None: ...
    def fillCharacterBounds(self, p0: int, p1: int, p2: Any, p3: int) -> None: ...
    def getAlignment(self) -> Any: ...
    def getBottomPadding(self) -> int: ...
    def getCursorPath(self, p0: int, p1: Path, p2: str) -> None: ...
    @overload
    @staticmethod
    def getDesiredWidth(p0: str, p1: TextPaint) -> float: ...
    @overload
    @staticmethod
    def getDesiredWidth(p0: str, p1: int, p2: int, p3: TextPaint) -> float: ...
    def getEllipsisCount(self, p0: int) -> int: ...
    def getEllipsisStart(self, p0: int) -> int: ...
    def getEllipsizedWidth(self) -> int: ...
    def getLeftIndents(self) -> Any: ...
    def getLineAscent(self, p0: int) -> int: ...
    def getLineBaseline(self, p0: int) -> int: ...
    @overload
    def getLineBottom(self, p0: int) -> int: ...
    @overload
    def getLineBottom(self, p0: int, p1: bool) -> int: ...
    def getLineBreakConfig(self) -> LineBreakConfig: ...
    def getLineContainsTab(self, p0: int) -> bool: ...
    def getLineDescent(self, p0: int) -> int: ...
    def getLineDirections(self, p0: int) -> Any: ...
    def getLineEnd(self, p0: int) -> int: ...
    def getLineForOffset(self, p0: int) -> int: ...
    def getLineForVertical(self, p0: int) -> int: ...
    def getLineLeft(self, p0: int) -> float: ...
    def getLineLetterSpacingUnitCount(self, p0: int, p1: bool) -> int: ...
    def getLineMax(self, p0: int) -> float: ...
    def getLineRight(self, p0: int) -> float: ...
    def getLineSpacingAmount(self) -> float: ...
    def getLineStart(self, p0: int) -> int: ...
    def getLineTop(self, p0: int) -> int: ...
    def getLineVisibleEnd(self, p0: int) -> int: ...
    def getLineWidth(self, p0: int) -> float: ...
    def getOffsetForHorizontal(self, p0: int, p1: float) -> int: ...
    def getOffsetToLeftOf(self, p0: int) -> int: ...
    def getOffsetToRightOf(self, p0: int) -> int: ...
    def getParagraphAlignment(self, p0: int) -> Any: ...
    def getParagraphDirection(self, p0: int) -> int: ...
    def getParagraphLeft(self, p0: int) -> int: ...
    def getParagraphRight(self, p0: int) -> int: ...
    def getPrimaryHorizontal(self, p0: int) -> float: ...
    def getRangeForRect(self, p0: RectF, p1: SegmentFinder, p2: Any) -> Any: ...
    def getRightIndents(self) -> Any: ...
    def getSecondaryHorizontal(self, p0: int) -> float: ...
    def getSelectionPath(self, p0: int, p1: int, p2: Path) -> None: ...
    def getSpacingAdd(self) -> float: ...
    def getSpacingMultiplier(self) -> float: ...
    def getTopPadding(self) -> int: ...
    def increaseWidthTo(self, p0: int) -> None: ...
    def isFallbackLineSpacingEnabled(self) -> bool: ...
    def isFontPaddingIncluded(self) -> bool: ...
    def isRtlCharAt(self, p0: int) -> bool: ...
    def drawText(self, p0: Canvas) -> None: ...
    def getBreakStrategy(self) -> int: ...
    def getEllipsize(self) -> Any: ...
    def getHyphenationFrequency(self) -> int: ...
    def getJustificationMode(self) -> int: ...
    def getLineBounds(self, p0: int, p1: Rect) -> int: ...
    def getLineCount(self) -> int: ...
    def getLineSpacingMultiplier(self) -> float: ...
    def getMaxLines(self) -> int: ...
    def getMinimumFontMetrics(self) -> Any: ...
    def getPaint(self) -> TextPaint: ...
    def getShiftDrawingOffsetForStartOverhang(self) -> bool: ...
    def getTextDirectionHeuristic(self) -> TextDirectionHeuristic: ...
    def getUseBoundsForWidth(self) -> bool: ...

    class TextInclusionStrategy:
        def isSegmentInside(self, p0: RectF, p1: RectF) -> bool: ...

    class Directions:
        ...

    class Builder:
        def __init__(self, p0: str, p1: int, p2: int, p3: TextPaint, p4: int) -> None: ...
        def setLineBreakConfig(self, p0: LineBreakConfig) -> Any: ...
        def setAlignment(self, p0: Any) -> Any: ...
        def setEllipsizedWidth(self, p0: int) -> Any: ...
        def setFallbackLineSpacingEnabled(self, p0: bool) -> Any: ...
        def setFontPaddingIncluded(self, p0: bool) -> Any: ...
        def setLeftIndents(self, p0: Any) -> Any: ...
        def setLineSpacingAmount(self, p0: float) -> Any: ...
        def setLineSpacingMultiplier(self, p0: float) -> Any: ...
        def setRightIndents(self, p0: Any) -> Any: ...
        def setTextDirectionHeuristic(self, p0: TextDirectionHeuristic) -> Any: ...
        def build(self) -> "Layout": ...
        def setBreakStrategy(self, p0: int) -> Any: ...
        def setEllipsize(self, p0: Any) -> Any: ...
        def setHyphenationFrequency(self, p0: int) -> Any: ...
        def setJustificationMode(self, p0: int) -> Any: ...
        def setMaxLines(self, p0: int) -> Any: ...
        def setMinimumFontMetrics(self, p0: Any) -> Any: ...
        def setShiftDrawingOffsetForStartOverhang(self, p0: bool) -> Any: ...
        def setUseBoundsForWidth(self, p0: bool) -> Any: ...

    class Alignment:
        ALIGN_CENTER: ClassVar["Alignment"]
        ALIGN_NORMAL: ClassVar["Alignment"]
        ALIGN_OPPOSITE: ClassVar["Alignment"]
        ALIGN_CENTER: ClassVar[Any]
        ALIGN_NORMAL: ClassVar[Any]
        ALIGN_OPPOSITE: ClassVar[Any]
        @staticmethod
        def values() -> Any: ...
        @staticmethod
        def valueOf(p0: str) -> Any: ...

from typing import Any, ClassVar, overload
from android.text.Editable import Editable

class TextWatcher:
    def afterTextChanged(self, p0: Editable) -> None: ...
    def beforeTextChanged(self, p0: str, p1: int, p2: int, p3: int) -> None: ...
    def onTextChanged(self, p0: str, p1: int, p2: int, p3: int) -> None: ...

from typing import Any, ClassVar, overload

class Spanned:
    SPAN_COMPOSING: ClassVar[int]
    SPAN_EXCLUSIVE_EXCLUSIVE: ClassVar[int]
    SPAN_EXCLUSIVE_INCLUSIVE: ClassVar[int]
    SPAN_INCLUSIVE_EXCLUSIVE: ClassVar[int]
    SPAN_INCLUSIVE_INCLUSIVE: ClassVar[int]
    SPAN_INTERMEDIATE: ClassVar[int]
    SPAN_MARK_MARK: ClassVar[int]
    SPAN_MARK_POINT: ClassVar[int]
    SPAN_PARAGRAPH: ClassVar[int]
    SPAN_POINT_MARK: ClassVar[int]
    SPAN_POINT_MARK_MASK: ClassVar[int]
    SPAN_POINT_POINT: ClassVar[int]
    SPAN_PRIORITY: ClassVar[int]
    SPAN_PRIORITY_SHIFT: ClassVar[int]
    SPAN_USER: ClassVar[int]
    SPAN_USER_SHIFT: ClassVar[int]
    def getSpanEnd(self, p0: Any) -> int: ...
    def getSpanFlags(self, p0: Any) -> int: ...
    def getSpanStart(self, p0: Any) -> int: ...
    def nextSpanTransition(self, p0: int, p1: int, p2: type) -> int: ...
    def getSpans(self, p0: int, p1: int, p2: type) -> Any: ...

from typing import Any, ClassVar, overload
from java.lang.Appendable import Appendable

class Editable:
    SPAN_COMPOSING: ClassVar[int]
    SPAN_EXCLUSIVE_EXCLUSIVE: ClassVar[int]
    SPAN_EXCLUSIVE_INCLUSIVE: ClassVar[int]
    SPAN_INCLUSIVE_EXCLUSIVE: ClassVar[int]
    SPAN_INCLUSIVE_INCLUSIVE: ClassVar[int]
    SPAN_INTERMEDIATE: ClassVar[int]
    SPAN_MARK_MARK: ClassVar[int]
    SPAN_MARK_POINT: ClassVar[int]
    SPAN_PARAGRAPH: ClassVar[int]
    SPAN_POINT_MARK: ClassVar[int]
    SPAN_POINT_MARK_MASK: ClassVar[int]
    SPAN_POINT_POINT: ClassVar[int]
    SPAN_PRIORITY: ClassVar[int]
    SPAN_PRIORITY_SHIFT: ClassVar[int]
    SPAN_USER: ClassVar[int]
    SPAN_USER_SHIFT: ClassVar[int]
    @overload
    def append(self, p0: str) -> Appendable: ...
    @overload
    def append(self, p0: str, p1: int, p2: int) -> Appendable: ...
    @overload
    def append(self, p0: str) -> Appendable: ...
    @overload
    def append(self, p0: str) -> "Editable": ...
    @overload
    def append(self, p0: str) -> "Editable": ...
    @overload
    def append(self, p0: str, p1: int, p2: int) -> "Editable": ...
    @overload
    def insert(self, p0: int, p1: str, p2: int, p3: int) -> "Editable": ...
    @overload
    def insert(self, p0: int, p1: str) -> "Editable": ...
    def clear(self) -> None: ...
    @overload
    def replace(self, p0: int, p1: int, p2: str) -> "Editable": ...
    @overload
    def replace(self, p0: int, p1: int, p2: str, p3: int, p4: int) -> "Editable": ...
    def delete(self, p0: int, p1: int) -> "Editable": ...
    def clearSpans(self) -> None: ...
    def getFilters(self) -> Any: ...
    def setFilters(self, p0: Any) -> None: ...

    class Factory:
        def __init__(self) -> None: ...
        @staticmethod
        def getInstance() -> Any: ...
        def newEditable(self, p0: str) -> "Editable": ...

from typing import Any, ClassVar, overload

class SpannedString:
    SPAN_COMPOSING: ClassVar[int]
    SPAN_EXCLUSIVE_EXCLUSIVE: ClassVar[int]
    SPAN_EXCLUSIVE_INCLUSIVE: ClassVar[int]
    SPAN_INCLUSIVE_EXCLUSIVE: ClassVar[int]
    SPAN_INCLUSIVE_INCLUSIVE: ClassVar[int]
    SPAN_INTERMEDIATE: ClassVar[int]
    SPAN_MARK_MARK: ClassVar[int]
    SPAN_MARK_POINT: ClassVar[int]
    SPAN_PARAGRAPH: ClassVar[int]
    SPAN_POINT_MARK: ClassVar[int]
    SPAN_POINT_MARK_MASK: ClassVar[int]
    SPAN_POINT_POINT: ClassVar[int]
    SPAN_PRIORITY: ClassVar[int]
    SPAN_PRIORITY_SHIFT: ClassVar[int]
    SPAN_USER: ClassVar[int]
    SPAN_USER_SHIFT: ClassVar[int]
    def __init__(self, p0: str) -> None: ...
    def equals(self, p0: Any) -> bool: ...
    def length(self) -> int: ...
    def toString(self) -> str: ...
    def hashCode(self) -> int: ...
    def getChars(self, p0: int, p1: int, p2: Any, p3: int) -> None: ...
    @staticmethod
    def valueOf(p0: str) -> "SpannedString": ...
    def charAt(self, p0: int) -> str: ...
    def subSequence(self, p0: int, p1: int) -> str: ...
    def getSpanEnd(self, p0: Any) -> int: ...
    def getSpanFlags(self, p0: Any) -> int: ...
    def getSpanStart(self, p0: Any) -> int: ...
    def nextSpanTransition(self, p0: int, p1: int, p2: type) -> int: ...
    def getSpans(self, p0: int, p1: int, p2: type) -> Any: ...

from typing import Any, ClassVar, overload
from android.content.Context import Context
from android.os.Parcel import Parcel
from android.text.Spannable import Spannable
from android.text.Spanned import Spanned
from android.text.TextPaint import TextPaint
from android.util.Printer import Printer
from java.lang.Iterable import Iterable
from java.util.Iterator import Iterator
from java.util.Locale import Locale
from java.util.regex.Pattern import Pattern

class TextUtils:
    CAP_MODE_CHARACTERS: ClassVar[int]
    CAP_MODE_SENTENCES: ClassVar[int]
    CAP_MODE_WORDS: ClassVar[int]
    CHAR_SEQUENCE_CREATOR: ClassVar[Any]
    SAFE_STRING_FLAG_FIRST_LINE: ClassVar[int]
    SAFE_STRING_FLAG_SINGLE_LINE: ClassVar[int]
    SAFE_STRING_FLAG_TRIM: ClassVar[int]
    @overload
    @staticmethod
    def ellipsize(p0: str, p1: TextPaint, p2: float, p3: Any) -> str: ...
    @overload
    @staticmethod
    def ellipsize(p0: str, p1: TextPaint, p2: float, p3: Any, p4: bool, p5: Any) -> str: ...
    @staticmethod
    def commaEllipsize(p0: str, p1: TextPaint, p2: float, p3: str, p4: str) -> str: ...
    @staticmethod
    def copySpansFrom(p0: Spanned, p1: int, p2: int, p3: type, p4: Spannable, p5: int) -> None: ...
    @staticmethod
    def dumpSpans(p0: str, p1: Printer, p2: str) -> None: ...
    @staticmethod
    def expandTemplate(p0: str, p1: Any) -> str: ...
    @staticmethod
    def getCapsMode(p0: str, p1: int, p2: int) -> int: ...
    @staticmethod
    def getReverse(p0: str, p1: int, p2: int) -> str: ...
    @staticmethod
    def getTrimmedLength(p0: str) -> int: ...
    @staticmethod
    def htmlEncode(p0: str) -> str: ...
    @staticmethod
    def isDigitsOnly(p0: str) -> bool: ...
    @overload
    @staticmethod
    def isGraphic(p0: str) -> bool: ...
    @overload
    @staticmethod
    def isGraphic(p0: str) -> bool: ...
    @staticmethod
    def listEllipsize(p0: Context, p1: list, p2: str, p3: TextPaint, p4: float, p5: int) -> str: ...
    @staticmethod
    def makeSafeForPresentation(p0: str, p1: int, p2: float, p3: int) -> str: ...
    @staticmethod
    def stringOrSpannedString(p0: str) -> str: ...
    @staticmethod
    def equals(p0: str, p1: str) -> bool: ...
    @staticmethod
    def getChars(p0: str, p1: int, p2: int, p3: Any, p4: int) -> None: ...
    @overload
    @staticmethod
    def indexOf(p0: str, p1: str, p2: int, p3: int) -> int: ...
    @overload
    @staticmethod
    def indexOf(p0: str, p1: str, p2: int) -> int: ...
    @overload
    @staticmethod
    def indexOf(p0: str, p1: str, p2: int) -> int: ...
    @overload
    @staticmethod
    def indexOf(p0: str, p1: str, p2: int, p3: int) -> int: ...
    @overload
    @staticmethod
    def indexOf(p0: str, p1: str) -> int: ...
    @overload
    @staticmethod
    def indexOf(p0: str, p1: str) -> int: ...
    @staticmethod
    def regionMatches(p0: str, p1: int, p2: str, p3: int, p4: int) -> bool: ...
    @overload
    @staticmethod
    def lastIndexOf(p0: str, p1: str, p2: int, p3: int) -> int: ...
    @overload
    @staticmethod
    def lastIndexOf(p0: str, p1: str) -> int: ...
    @overload
    @staticmethod
    def lastIndexOf(p0: str, p1: str, p2: int) -> int: ...
    @staticmethod
    def substring(p0: str, p1: int, p2: int) -> str: ...
    @staticmethod
    def isEmpty(p0: str) -> bool: ...
    @staticmethod
    def replace(p0: str, p1: Any, p2: Any) -> str: ...
    @overload
    @staticmethod
    def split(p0: str, p1: str) -> Any: ...
    @overload
    @staticmethod
    def split(p0: str, p1: Pattern) -> Any: ...
    @overload
    @staticmethod
    def join(p0: str, p1: Any) -> str: ...
    @overload
    @staticmethod
    def join(p0: str, p1: Iterable) -> str: ...
    @staticmethod
    def concat(p0: Any) -> str: ...
    @staticmethod
    def getOffsetAfter(p0: str, p1: int) -> int: ...
    @staticmethod
    def getOffsetBefore(p0: str, p1: int) -> int: ...
    @staticmethod
    def getLayoutDirectionFromLocale(p0: Locale) -> int: ...
    @staticmethod
    def writeToParcel(p0: str, p1: Parcel, p2: int) -> None: ...

    class TruncateAt:
        END: ClassVar["TruncateAt"]
        MARQUEE: ClassVar["TruncateAt"]
        MIDDLE: ClassVar["TruncateAt"]
        START: ClassVar["TruncateAt"]
        END: ClassVar[Any]
        MARQUEE: ClassVar[Any]
        MIDDLE: ClassVar[Any]
        START: ClassVar[Any]
        @staticmethod
        def values() -> Any: ...
        @staticmethod
        def valueOf(p0: str) -> Any: ...

    class StringSplitter:
        def setString(self, p0: str) -> None: ...

    class SimpleStringSplitter:
        def __init__(self, p0: str) -> None: ...
        def remove(self) -> None: ...
        def iterator(self) -> Iterator: ...
        def hasNext(self) -> bool: ...
        @overload
        def next(self) -> Any: ...
        @overload
        def next(self) -> str: ...
        def setString(self, p0: str) -> None: ...

    class EllipsizeCallback:
        def ellipsized(self, p0: int, p1: int) -> None: ...

from typing import Any, ClassVar, overload

class AlteredCharSequence:
    def length(self) -> int: ...
    def toString(self) -> str: ...
    def getChars(self, p0: int, p1: int, p2: Any, p3: int) -> None: ...
    def charAt(self, p0: int) -> str: ...
    def subSequence(self, p0: int, p1: int) -> str: ...
    @staticmethod
    def make(p0: str, p1: Any, p2: int, p3: int) -> "AlteredCharSequence": ...

from typing import Any, ClassVar, overload

class SpannableString:
    SPAN_COMPOSING: ClassVar[int]
    SPAN_EXCLUSIVE_EXCLUSIVE: ClassVar[int]
    SPAN_EXCLUSIVE_INCLUSIVE: ClassVar[int]
    SPAN_INCLUSIVE_EXCLUSIVE: ClassVar[int]
    SPAN_INCLUSIVE_INCLUSIVE: ClassVar[int]
    SPAN_INTERMEDIATE: ClassVar[int]
    SPAN_MARK_MARK: ClassVar[int]
    SPAN_MARK_POINT: ClassVar[int]
    SPAN_PARAGRAPH: ClassVar[int]
    SPAN_POINT_MARK: ClassVar[int]
    SPAN_POINT_MARK_MASK: ClassVar[int]
    SPAN_POINT_POINT: ClassVar[int]
    SPAN_PRIORITY: ClassVar[int]
    SPAN_PRIORITY_SHIFT: ClassVar[int]
    SPAN_USER: ClassVar[int]
    SPAN_USER_SHIFT: ClassVar[int]
    def __init__(self, p0: str) -> None: ...
    def equals(self, p0: Any) -> bool: ...
    def length(self) -> int: ...
    def toString(self) -> str: ...
    def hashCode(self) -> int: ...
    def getChars(self, p0: int, p1: int, p2: Any, p3: int) -> None: ...
    @staticmethod
    def valueOf(p0: str) -> "SpannableString": ...
    def charAt(self, p0: int) -> str: ...
    def subSequence(self, p0: int, p1: int) -> str: ...
    def removeSpan(self, p0: Any) -> None: ...
    def setSpan(self, p0: Any, p1: int, p2: int, p3: int) -> None: ...
    def getSpanEnd(self, p0: Any) -> int: ...
    def getSpanFlags(self, p0: Any) -> int: ...
    def getSpanStart(self, p0: Any) -> int: ...
    def nextSpanTransition(self, p0: int, p1: int, p2: type) -> int: ...
    def getSpans(self, p0: int, p1: int, p2: type) -> Any: ...

from typing import Any, ClassVar, overload

class ClipboardManager:
    def __init__(self) -> None: ...
    def hasText(self) -> bool: ...
    def getText(self) -> str: ...
    def setText(self, p0: str) -> None: ...

from typing import Any, ClassVar, overload

class EmojiConsistency:
    @staticmethod
    def getEmojiConsistencySet() -> set: ...

from typing import Any, ClassVar, overload
from android.text.TextDirectionHeuristic import TextDirectionHeuristic
from java.util.Locale import Locale

class BidiFormatter:
    def getStereoReset(self) -> bool: ...
    def isRtlContext(self) -> bool: ...
    @overload
    def unicodeWrap(self, p0: str, p1: bool) -> str: ...
    @overload
    def unicodeWrap(self, p0: str, p1: TextDirectionHeuristic) -> str: ...
    @overload
    def unicodeWrap(self, p0: str, p1: TextDirectionHeuristic, p2: bool) -> str: ...
    @overload
    def unicodeWrap(self, p0: str, p1: TextDirectionHeuristic) -> str: ...
    @overload
    def unicodeWrap(self, p0: str) -> str: ...
    @overload
    def unicodeWrap(self, p0: str, p1: bool) -> str: ...
    @overload
    def unicodeWrap(self, p0: str, p1: TextDirectionHeuristic, p2: bool) -> str: ...
    @overload
    def unicodeWrap(self, p0: str) -> str: ...
    @overload
    @staticmethod
    def getInstance(p0: bool) -> "BidiFormatter": ...
    @overload
    @staticmethod
    def getInstance() -> "BidiFormatter": ...
    @overload
    @staticmethod
    def getInstance(p0: Locale) -> "BidiFormatter": ...
    @overload
    def isRtl(self, p0: str) -> bool: ...
    @overload
    def isRtl(self, p0: str) -> bool: ...

    class Builder:
        @overload
        def __init__(self) -> None: ...
        @overload
        def __init__(self, p0: Locale) -> None: ...
        @overload
        def __init__(self, p0: bool) -> None: ...
        def stereoReset(self, p0: bool) -> Any: ...
        def setTextDirectionHeuristic(self, p0: TextDirectionHeuristic) -> Any: ...
        def build(self) -> "BidiFormatter": ...

from typing import Any, ClassVar, overload
from android.text.TextDirectionHeuristic import TextDirectionHeuristic

class TextDirectionHeuristics:
    ANYRTL_LTR: ClassVar[TextDirectionHeuristic]
    FIRSTSTRONG_LTR: ClassVar[TextDirectionHeuristic]
    FIRSTSTRONG_RTL: ClassVar[TextDirectionHeuristic]
    LOCALE: ClassVar[TextDirectionHeuristic]
    LTR: ClassVar[TextDirectionHeuristic]
    RTL: ClassVar[TextDirectionHeuristic]
    def __init__(self) -> None: ...

from typing import Any, ClassVar, overload
from android.graphics.drawable.Drawable import Drawable
from android.text.Editable import Editable
from android.text.Spanned import Spanned
from org.xml.sax.XMLReader import XMLReader

class Html:
    FROM_HTML_MODE_COMPACT: ClassVar[int]
    FROM_HTML_MODE_LEGACY: ClassVar[int]
    FROM_HTML_OPTION_USE_CSS_COLORS: ClassVar[int]
    FROM_HTML_SEPARATOR_LINE_BREAK_BLOCKQUOTE: ClassVar[int]
    FROM_HTML_SEPARATOR_LINE_BREAK_DIV: ClassVar[int]
    FROM_HTML_SEPARATOR_LINE_BREAK_HEADING: ClassVar[int]
    FROM_HTML_SEPARATOR_LINE_BREAK_LIST: ClassVar[int]
    FROM_HTML_SEPARATOR_LINE_BREAK_LIST_ITEM: ClassVar[int]
    FROM_HTML_SEPARATOR_LINE_BREAK_PARAGRAPH: ClassVar[int]
    TO_HTML_PARAGRAPH_LINES_CONSECUTIVE: ClassVar[int]
    TO_HTML_PARAGRAPH_LINES_INDIVIDUAL: ClassVar[int]
    @overload
    @staticmethod
    def toHtml(p0: Spanned) -> str: ...
    @overload
    @staticmethod
    def toHtml(p0: Spanned, p1: int) -> str: ...
    @staticmethod
    def escapeHtml(p0: str) -> str: ...
    @overload
    @staticmethod
    def fromHtml(p0: str, p1: int) -> Spanned: ...
    @overload
    @staticmethod
    def fromHtml(p0: str, p1: int, p2: Any, p3: Any) -> Spanned: ...
    @overload
    @staticmethod
    def fromHtml(p0: str, p1: Any, p2: Any) -> Spanned: ...
    @overload
    @staticmethod
    def fromHtml(p0: str) -> Spanned: ...

    class TagHandler:
        def handleTag(self, p0: bool, p1: str, p2: Editable, p3: XMLReader) -> None: ...

    class ImageGetter:
        def getDrawable(self, p0: str) -> Drawable: ...

from typing import Any, ClassVar, overload
from android.os.Parcel import Parcel

class Annotation:
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    @overload
    def __init__(self, p0: Parcel) -> None: ...
    @overload
    def __init__(self, p0: str, p1: str) -> None: ...
    def getValue(self) -> str: ...
    def getKey(self) -> str: ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
    def getSpanTypeId(self) -> int: ...

from typing import Any, ClassVar, overload
from android.graphics.Paint import Paint

class TextPaint:
    ANTI_ALIAS_FLAG: ClassVar[int]
    CURSOR_AFTER: ClassVar[int]
    CURSOR_AT: ClassVar[int]
    CURSOR_AT_OR_AFTER: ClassVar[int]
    CURSOR_AT_OR_BEFORE: ClassVar[int]
    CURSOR_BEFORE: ClassVar[int]
    DEV_KERN_TEXT_FLAG: ClassVar[int]
    DITHER_FLAG: ClassVar[int]
    EMBEDDED_BITMAP_TEXT_FLAG: ClassVar[int]
    END_HYPHEN_EDIT_INSERT_ARMENIAN_HYPHEN: ClassVar[int]
    END_HYPHEN_EDIT_INSERT_HYPHEN: ClassVar[int]
    END_HYPHEN_EDIT_INSERT_MAQAF: ClassVar[int]
    END_HYPHEN_EDIT_INSERT_UCAS_HYPHEN: ClassVar[int]
    END_HYPHEN_EDIT_INSERT_ZWJ_AND_HYPHEN: ClassVar[int]
    END_HYPHEN_EDIT_NO_EDIT: ClassVar[int]
    END_HYPHEN_EDIT_REPLACE_WITH_HYPHEN: ClassVar[int]
    FAKE_BOLD_TEXT_FLAG: ClassVar[int]
    FILTER_BITMAP_FLAG: ClassVar[int]
    HINTING_OFF: ClassVar[int]
    HINTING_ON: ClassVar[int]
    LINEAR_TEXT_FLAG: ClassVar[int]
    START_HYPHEN_EDIT_INSERT_HYPHEN: ClassVar[int]
    START_HYPHEN_EDIT_INSERT_ZWJ: ClassVar[int]
    START_HYPHEN_EDIT_NO_EDIT: ClassVar[int]
    STRIKE_THRU_TEXT_FLAG: ClassVar[int]
    SUBPIXEL_TEXT_FLAG: ClassVar[int]
    TEXT_RUN_FLAG_LEFT_EDGE: ClassVar[int]
    TEXT_RUN_FLAG_RIGHT_EDGE: ClassVar[int]
    UNDERLINE_TEXT_FLAG: ClassVar[int]
    VERTICAL_TEXT_FLAG: ClassVar[int]
    baselineShift: int
    bgColor: int
    density: float
    drawableState: Any
    linkColor: int
    underlineColor: int
    underlineThickness: float
    @overload
    def __init__(self, p0: int) -> None: ...
    @overload
    def __init__(self, p0: Paint) -> None: ...
    @overload
    def __init__(self) -> None: ...
    def set(self, p0: "TextPaint") -> None: ...
    def getUnderlineThickness(self) -> float: ...

from typing import Any, ClassVar, overload
from android.graphics.Paint import Paint
from android.text.Editable import Editable
from java.lang.Appendable import Appendable

class SpannableStringBuilder:
    SPAN_COMPOSING: ClassVar[int]
    SPAN_EXCLUSIVE_EXCLUSIVE: ClassVar[int]
    SPAN_EXCLUSIVE_INCLUSIVE: ClassVar[int]
    SPAN_INCLUSIVE_EXCLUSIVE: ClassVar[int]
    SPAN_INCLUSIVE_INCLUSIVE: ClassVar[int]
    SPAN_INTERMEDIATE: ClassVar[int]
    SPAN_MARK_MARK: ClassVar[int]
    SPAN_MARK_POINT: ClassVar[int]
    SPAN_PARAGRAPH: ClassVar[int]
    SPAN_POINT_MARK: ClassVar[int]
    SPAN_POINT_MARK_MASK: ClassVar[int]
    SPAN_POINT_POINT: ClassVar[int]
    SPAN_PRIORITY: ClassVar[int]
    SPAN_PRIORITY_SHIFT: ClassVar[int]
    SPAN_USER: ClassVar[int]
    SPAN_USER_SHIFT: ClassVar[int]
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, p0: str, p1: int, p2: int) -> None: ...
    @overload
    def __init__(self, p0: str) -> None: ...
    def getTextWatcherDepth(self) -> int: ...
    def equals(self, p0: Any) -> bool: ...
    def length(self) -> int: ...
    def toString(self) -> str: ...
    @overload
    def append(self, p0: str) -> Editable: ...
    @overload
    def append(self, p0: str) -> Appendable: ...
    @overload
    def append(self, p0: str, p1: int, p2: int) -> Editable: ...
    @overload
    def append(self, p0: str) -> Appendable: ...
    @overload
    def append(self, p0: str, p1: int, p2: int) -> Appendable: ...
    @overload
    def append(self, p0: str) -> Editable: ...
    @overload
    def append(self, p0: str) -> "SpannableStringBuilder": ...
    @overload
    def append(self, p0: str, p1: Any, p2: int) -> "SpannableStringBuilder": ...
    @overload
    def append(self, p0: str, p1: int, p2: int) -> "SpannableStringBuilder": ...
    @overload
    def append(self, p0: str) -> "SpannableStringBuilder": ...
    def hashCode(self) -> int: ...
    def getChars(self, p0: int, p1: int, p2: Any, p3: int) -> None: ...
    @overload
    def insert(self, p0: int, p1: str, p2: int, p3: int) -> "SpannableStringBuilder": ...
    @overload
    def insert(self, p0: int, p1: str, p2: int, p3: int) -> Editable: ...
    @overload
    def insert(self, p0: int, p1: str) -> Editable: ...
    @overload
    def insert(self, p0: int, p1: str) -> "SpannableStringBuilder": ...
    @staticmethod
    def valueOf(p0: str) -> "SpannableStringBuilder": ...
    def clear(self) -> None: ...
    def charAt(self, p0: int) -> str: ...
    @overload
    def replace(self, p0: int, p1: int, p2: str, p3: int, p4: int) -> Editable: ...
    @overload
    def replace(self, p0: int, p1: int, p2: str) -> Editable: ...
    @overload
    def replace(self, p0: int, p1: int, p2: str, p3: int, p4: int) -> "SpannableStringBuilder": ...
    @overload
    def replace(self, p0: int, p1: int, p2: str) -> "SpannableStringBuilder": ...
    def subSequence(self, p0: int, p1: int) -> str: ...
    @overload
    def delete(self, p0: int, p1: int) -> "SpannableStringBuilder": ...
    @overload
    def delete(self, p0: int, p1: int) -> Editable: ...
    def clearSpans(self) -> None: ...
    def removeSpan(self, p0: Any) -> None: ...
    def setSpan(self, p0: Any, p1: int, p2: int, p3: int) -> None: ...
    def getSpanEnd(self, p0: Any) -> int: ...
    def getSpanFlags(self, p0: Any) -> int: ...
    def getSpanStart(self, p0: Any) -> int: ...
    def nextSpanTransition(self, p0: int, p1: int, p2: type) -> int: ...
    def getTextRunCursor(self, p0: int, p1: int, p2: int, p3: int, p4: int, p5: Paint) -> int: ...
    def getSpans(self, p0: int, p1: int, p2: type) -> Any: ...
    def getFilters(self) -> Any: ...
    def setFilters(self, p0: Any) -> None: ...

from typing import Any, ClassVar, overload

class AndroidCharacter:
    EAST_ASIAN_WIDTH_AMBIGUOUS: ClassVar[int]
    EAST_ASIAN_WIDTH_FULL_WIDTH: ClassVar[int]
    EAST_ASIAN_WIDTH_HALF_WIDTH: ClassVar[int]
    EAST_ASIAN_WIDTH_NARROW: ClassVar[int]
    EAST_ASIAN_WIDTH_NEUTRAL: ClassVar[int]
    EAST_ASIAN_WIDTH_WIDE: ClassVar[int]
    def __init__(self) -> None: ...
    @staticmethod
    def mirror(p0: Any, p1: int, p2: int) -> bool: ...
    @staticmethod
    def getDirectionalities(p0: Any, p1: Any, p2: int) -> None: ...
    @staticmethod
    def getEastAsianWidth(p0: str) -> int: ...
    @staticmethod
    def getEastAsianWidths(p0: Any, p1: int, p2: int, p3: Any) -> None: ...
    @staticmethod
    def getMirror(p0: str) -> str: ...

