from jnius import JavaClass, JavaInterface, MetaJavaClass, JavaMethod, JavaStaticMethod, JavaMultipleMethod, JavaField, JavaStaticField

class GraphemeClusterSegmentFinder(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "android/text/GraphemeClusterSegmentFinder"
    __javaconstructor__ = [("(Ljava/lang/CharSequence;Landroid/text/TextPaint;)V", False)]
    DONE = JavaStaticField("I")
    nextEndBoundary = JavaMethod("(I)I")
    nextStartBoundary = JavaMethod("(I)I")
    previousEndBoundary = JavaMethod("(I)I")
    previousStartBoundary = JavaMethod("(I)I")

class NoCopySpan(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "android/text/NoCopySpan"

    class Concrete(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "android/text/NoCopySpan$Concrete"
        __javaconstructor__ = [("()V", False)]

class InputFilter(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "android/text/InputFilter"
    filter = JavaMethod("(Ljava/lang/CharSequence;IILandroid/text/Spanned;II)Ljava/lang/CharSequence;")

    class LengthFilter(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "android/text/InputFilter$LengthFilter"
        __javaconstructor__ = [("(I)V", False)]
        filter = JavaMethod("(Ljava/lang/CharSequence;IILandroid/text/Spanned;II)Ljava/lang/CharSequence;")
        getMax = JavaMethod("()I")

    class AllCaps(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "android/text/InputFilter$AllCaps"
        __javaconstructor__ = [("()V", False), ("(Ljava/util/Locale;)V", False)]
        filter = JavaMethod("(Ljava/lang/CharSequence;IILandroid/text/Spanned;II)Ljava/lang/CharSequence;")

class GetChars(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "android/text/GetChars"
    getChars = JavaMethod("(II[CI)V")

class Selection(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "android/text/Selection"
    SELECTION_END = JavaStaticField("Ljava/lang/Object;")
    SELECTION_START = JavaStaticField("Ljava/lang/Object;")
    moveUp = JavaStaticMethod("(Landroid/text/Spannable;Landroid/text/Layout;)Z")
    extendDown = JavaStaticMethod("(Landroid/text/Spannable;Landroid/text/Layout;)Z")
    extendLeft = JavaStaticMethod("(Landroid/text/Spannable;Landroid/text/Layout;)Z")
    extendRight = JavaStaticMethod("(Landroid/text/Spannable;Landroid/text/Layout;)Z")
    extendToLeftEdge = JavaStaticMethod("(Landroid/text/Spannable;Landroid/text/Layout;)Z")
    extendToParagraphEnd = JavaStaticMethod("(Landroid/text/Spannable;)Z")
    extendToParagraphStart = JavaStaticMethod("(Landroid/text/Spannable;)Z")
    extendToRightEdge = JavaStaticMethod("(Landroid/text/Spannable;Landroid/text/Layout;)Z")
    extendUp = JavaStaticMethod("(Landroid/text/Spannable;Landroid/text/Layout;)Z")
    moveDown = JavaStaticMethod("(Landroid/text/Spannable;Landroid/text/Layout;)Z")
    moveLeft = JavaStaticMethod("(Landroid/text/Spannable;Landroid/text/Layout;)Z")
    moveRight = JavaStaticMethod("(Landroid/text/Spannable;Landroid/text/Layout;)Z")
    moveToLeftEdge = JavaStaticMethod("(Landroid/text/Spannable;Landroid/text/Layout;)Z")
    moveToParagraphEnd = JavaStaticMethod("(Landroid/text/Spannable;Landroid/text/Layout;)Z")
    moveToParagraphStart = JavaStaticMethod("(Landroid/text/Spannable;Landroid/text/Layout;)Z")
    moveToRightEdge = JavaStaticMethod("(Landroid/text/Spannable;Landroid/text/Layout;)Z")
    removeSelection = JavaStaticMethod("(Landroid/text/Spannable;)V")
    extendSelection = JavaStaticMethod("(Landroid/text/Spannable;I)V")
    selectAll = JavaStaticMethod("(Landroid/text/Spannable;)V")
    setSelection = JavaMultipleMethod([("(Landroid/text/Spannable;I)V", True, False), ("(Landroid/text/Spannable;II)V", True, False)])
    getSelectionEnd = JavaStaticMethod("(Ljava/lang/CharSequence;)I")
    getSelectionStart = JavaStaticMethod("(Ljava/lang/CharSequence;)I")

class LoginFilter(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "android/text/LoginFilter"
    isAllowed = JavaMethod("(C)Z")
    onInvalidCharacter = JavaMethod("(C)V")
    filter = JavaMethod("(Ljava/lang/CharSequence;IILandroid/text/Spanned;II)Ljava/lang/CharSequence;")
    onStart = JavaMethod("()V")
    onStop = JavaMethod("()V")

    class UsernameFilterGeneric(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "android/text/LoginFilter$UsernameFilterGeneric"
        __javaconstructor__ = [("(Z)V", False), ("()V", False)]
        isAllowed = JavaMethod("(C)Z")

    class UsernameFilterGMail(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "android/text/LoginFilter$UsernameFilterGMail"
        __javaconstructor__ = [("(Z)V", False), ("()V", False)]
        isAllowed = JavaMethod("(C)Z")

    class PasswordFilterGMail(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "android/text/LoginFilter$PasswordFilterGMail"
        __javaconstructor__ = [("(Z)V", False), ("()V", False)]
        isAllowed = JavaMethod("(C)Z")

class PrecomputedText(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "android/text/PrecomputedText"
    SPAN_COMPOSING = JavaStaticField("I")
    SPAN_EXCLUSIVE_EXCLUSIVE = JavaStaticField("I")
    SPAN_EXCLUSIVE_INCLUSIVE = JavaStaticField("I")
    SPAN_INCLUSIVE_EXCLUSIVE = JavaStaticField("I")
    SPAN_INCLUSIVE_INCLUSIVE = JavaStaticField("I")
    SPAN_INTERMEDIATE = JavaStaticField("I")
    SPAN_MARK_MARK = JavaStaticField("I")
    SPAN_MARK_POINT = JavaStaticField("I")
    SPAN_PARAGRAPH = JavaStaticField("I")
    SPAN_POINT_MARK = JavaStaticField("I")
    SPAN_POINT_MARK_MASK = JavaStaticField("I")
    SPAN_POINT_POINT = JavaStaticField("I")
    SPAN_PRIORITY = JavaStaticField("I")
    SPAN_PRIORITY_SHIFT = JavaStaticField("I")
    SPAN_USER = JavaStaticField("I")
    SPAN_USER_SHIFT = JavaStaticField("I")
    getParagraphCount = JavaMethod("()I")
    getParagraphEnd = JavaMethod("(I)I")
    getParagraphStart = JavaMethod("(I)I")
    create = JavaStaticMethod("(Ljava/lang/CharSequence;Landroid/text/PrecomputedText$Params;)Landroid/text/PrecomputedText;")
    length = JavaMethod("()I")
    toString = JavaMethod("()Ljava/lang/String;")
    charAt = JavaMethod("(I)C")
    subSequence = JavaMethod("(II)Ljava/lang/CharSequence;")
    getBounds = JavaMethod("(IILandroid/graphics/Rect;)V")
    removeSpan = JavaMethod("(Ljava/lang/Object;)V")
    setSpan = JavaMethod("(Ljava/lang/Object;III)V")
    getSpanEnd = JavaMethod("(Ljava/lang/Object;)I")
    getSpanFlags = JavaMethod("(Ljava/lang/Object;)I")
    getSpanStart = JavaMethod("(Ljava/lang/Object;)I")
    nextSpanTransition = JavaMethod("(IILjava/lang/Class;)I")
    getWidth = JavaMethod("(II)F")
    getParams = JavaMethod("()Landroid/text/PrecomputedText$Params;")
    getFontMetricsInt = JavaMethod("(IILandroid/graphics/Paint$FontMetricsInt;)V")
    getSpans = JavaMethod("(IILjava/lang/Class;)[Ljava/lang/Object;")

    class Params(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "android/text/PrecomputedText$Params"
        equals = JavaMethod("(Ljava/lang/Object;)Z")
        toString = JavaMethod("()Ljava/lang/String;")
        hashCode = JavaMethod("()I")
        getTextDirection = JavaMethod("()Landroid/text/TextDirectionHeuristic;")
        getLineBreakConfig = JavaMethod("()Landroid/graphics/text/LineBreakConfig;")
        getTextPaint = JavaMethod("()Landroid/text/TextPaint;")
        getBreakStrategy = JavaMethod("()I")
        getHyphenationFrequency = JavaMethod("()I")

        class Builder(JavaClass, metaclass=MetaJavaClass):
            __javaclass__ = "android/text/PrecomputedText$Params$Builder"
            __javaconstructor__ = [("(Landroid/text/PrecomputedText$Params;)V", False), ("(Landroid/text/TextPaint;)V", False)]
            setLineBreakConfig = JavaMethod("(Landroid/graphics/text/LineBreakConfig;)Landroid/text/PrecomputedText$Params$Builder;")
            setTextDirection = JavaMethod("(Landroid/text/TextDirectionHeuristic;)Landroid/text/PrecomputedText$Params$Builder;")
            build = JavaMethod("()Landroid/text/PrecomputedText$Params;")
            setBreakStrategy = JavaMethod("(I)Landroid/text/PrecomputedText$Params$Builder;")
            setHyphenationFrequency = JavaMethod("(I)Landroid/text/PrecomputedText$Params$Builder;")

class SpanWatcher(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "android/text/SpanWatcher"
    onSpanAdded = JavaMethod("(Landroid/text/Spannable;Ljava/lang/Object;II)V")
    onSpanRemoved = JavaMethod("(Landroid/text/Spannable;Ljava/lang/Object;II)V")
    onSpanChanged = JavaMethod("(Landroid/text/Spannable;Ljava/lang/Object;IIII)V")

class DynamicLayout(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "android/text/DynamicLayout"
    __javaconstructor__ = [("(Ljava/lang/CharSequence;Ljava/lang/CharSequence;Landroid/text/TextPaint;ILandroid/text/Layout$Alignment;FFZLandroid/text/TextUtils$TruncateAt;I)V", False), ("(Ljava/lang/CharSequence;Ljava/lang/CharSequence;Landroid/text/TextPaint;ILandroid/text/Layout$Alignment;FFZ)V", False), ("(Ljava/lang/CharSequence;Landroid/text/TextPaint;ILandroid/text/Layout$Alignment;FFZ)V", False)]
    BREAK_STRATEGY_BALANCED = JavaStaticField("I")
    BREAK_STRATEGY_HIGH_QUALITY = JavaStaticField("I")
    BREAK_STRATEGY_SIMPLE = JavaStaticField("I")
    DEFAULT_LINESPACING_ADDITION = JavaStaticField("F")
    DEFAULT_LINESPACING_MULTIPLIER = JavaStaticField("F")
    DIR_LEFT_TO_RIGHT = JavaStaticField("I")
    DIR_RIGHT_TO_LEFT = JavaStaticField("I")
    HYPHENATION_FREQUENCY_FULL = JavaStaticField("I")
    HYPHENATION_FREQUENCY_FULL_FAST = JavaStaticField("I")
    HYPHENATION_FREQUENCY_NONE = JavaStaticField("I")
    HYPHENATION_FREQUENCY_NORMAL = JavaStaticField("I")
    HYPHENATION_FREQUENCY_NORMAL_FAST = JavaStaticField("I")
    INCLUSION_STRATEGY_ANY_OVERLAP = JavaStaticField("Landroid/text/Layout$TextInclusionStrategy;")
    INCLUSION_STRATEGY_CONTAINS_ALL = JavaStaticField("Landroid/text/Layout$TextInclusionStrategy;")
    INCLUSION_STRATEGY_CONTAINS_CENTER = JavaStaticField("Landroid/text/Layout$TextInclusionStrategy;")
    JUSTIFICATION_MODE_INTER_CHARACTER = JavaStaticField("I")
    JUSTIFICATION_MODE_INTER_WORD = JavaStaticField("I")
    JUSTIFICATION_MODE_NONE = JavaStaticField("I")
    getBottomPadding = JavaMethod("()I")
    getEllipsisCount = JavaMethod("(I)I")
    getEllipsisStart = JavaMethod("(I)I")
    getEllipsizedWidth = JavaMethod("()I")
    getLineBreakConfig = JavaMethod("()Landroid/graphics/text/LineBreakConfig;")
    getLineContainsTab = JavaMethod("(I)Z")
    getLineDescent = JavaMethod("(I)I")
    getLineDirections = JavaMethod("(I)Landroid/text/Layout$Directions;")
    getLineStart = JavaMethod("(I)I")
    getLineTop = JavaMethod("(I)I")
    getParagraphDirection = JavaMethod("(I)I")
    getTopPadding = JavaMethod("()I")
    getLineCount = JavaMethod("()I")

    class Builder(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "android/text/DynamicLayout$Builder"
        setLineBreakConfig = JavaMethod("(Landroid/graphics/text/LineBreakConfig;)Landroid/text/DynamicLayout$Builder;")
        setDisplayText = JavaMethod("(Ljava/lang/CharSequence;)Landroid/text/DynamicLayout$Builder;")
        setAlignment = JavaMethod("(Landroid/text/Layout$Alignment;)Landroid/text/DynamicLayout$Builder;")
        setEllipsizedWidth = JavaMethod("(I)Landroid/text/DynamicLayout$Builder;")
        setIncludePad = JavaMethod("(Z)Landroid/text/DynamicLayout$Builder;")
        setUseLineSpacingFromFallbacks = JavaMethod("(Z)Landroid/text/DynamicLayout$Builder;")
        setTextDirection = JavaMethod("(Landroid/text/TextDirectionHeuristic;)Landroid/text/DynamicLayout$Builder;")
        obtain = JavaStaticMethod("(Ljava/lang/CharSequence;Landroid/text/TextPaint;I)Landroid/text/DynamicLayout$Builder;")
        build = JavaMethod("()Landroid/text/DynamicLayout;")
        setBreakStrategy = JavaMethod("(I)Landroid/text/DynamicLayout$Builder;")
        setEllipsize = JavaMethod("(Landroid/text/TextUtils$TruncateAt;)Landroid/text/DynamicLayout$Builder;")
        setHyphenationFrequency = JavaMethod("(I)Landroid/text/DynamicLayout$Builder;")
        setJustificationMode = JavaMethod("(I)Landroid/text/DynamicLayout$Builder;")
        setLineSpacing = JavaMethod("(FF)Landroid/text/DynamicLayout$Builder;")
        setMinimumFontMetrics = JavaMethod("(Landroid/graphics/Paint$FontMetrics;)Landroid/text/DynamicLayout$Builder;")
        setShiftDrawingOffsetForStartOverhang = JavaMethod("(Z)Landroid/text/DynamicLayout$Builder;")
        setUseBoundsForWidth = JavaMethod("(Z)Landroid/text/DynamicLayout$Builder;")

class StaticLayout(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "android/text/StaticLayout"
    __javaconstructor__ = [("(Ljava/lang/CharSequence;IILandroid/text/TextPaint;ILandroid/text/Layout$Alignment;FFZLandroid/text/TextUtils$TruncateAt;I)V", False), ("(Ljava/lang/CharSequence;IILandroid/text/TextPaint;ILandroid/text/Layout$Alignment;FFZ)V", False), ("(Ljava/lang/CharSequence;Landroid/text/TextPaint;ILandroid/text/Layout$Alignment;FFZ)V", False)]
    BREAK_STRATEGY_BALANCED = JavaStaticField("I")
    BREAK_STRATEGY_HIGH_QUALITY = JavaStaticField("I")
    BREAK_STRATEGY_SIMPLE = JavaStaticField("I")
    DEFAULT_LINESPACING_ADDITION = JavaStaticField("F")
    DEFAULT_LINESPACING_MULTIPLIER = JavaStaticField("F")
    DIR_LEFT_TO_RIGHT = JavaStaticField("I")
    DIR_RIGHT_TO_LEFT = JavaStaticField("I")
    HYPHENATION_FREQUENCY_FULL = JavaStaticField("I")
    HYPHENATION_FREQUENCY_FULL_FAST = JavaStaticField("I")
    HYPHENATION_FREQUENCY_NONE = JavaStaticField("I")
    HYPHENATION_FREQUENCY_NORMAL = JavaStaticField("I")
    HYPHENATION_FREQUENCY_NORMAL_FAST = JavaStaticField("I")
    INCLUSION_STRATEGY_ANY_OVERLAP = JavaStaticField("Landroid/text/Layout$TextInclusionStrategy;")
    INCLUSION_STRATEGY_CONTAINS_ALL = JavaStaticField("Landroid/text/Layout$TextInclusionStrategy;")
    INCLUSION_STRATEGY_CONTAINS_CENTER = JavaStaticField("Landroid/text/Layout$TextInclusionStrategy;")
    JUSTIFICATION_MODE_INTER_CHARACTER = JavaStaticField("I")
    JUSTIFICATION_MODE_INTER_WORD = JavaStaticField("I")
    JUSTIFICATION_MODE_NONE = JavaStaticField("I")
    computeDrawingBoundingBox = JavaMethod("()Landroid/graphics/RectF;")
    getBottomPadding = JavaMethod("()I")
    getEllipsisCount = JavaMethod("(I)I")
    getEllipsisStart = JavaMethod("(I)I")
    getLineContainsTab = JavaMethod("(I)Z")
    getLineDescent = JavaMethod("(I)I")
    getLineDirections = JavaMethod("(I)Landroid/text/Layout$Directions;")
    getLineForVertical = JavaMethod("(I)I")
    getLineStart = JavaMethod("(I)I")
    getLineTop = JavaMethod("(I)I")
    getParagraphDirection = JavaMethod("(I)I")
    getTopPadding = JavaMethod("()I")
    getLineCount = JavaMethod("()I")

    class Builder(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "android/text/StaticLayout$Builder"
        setIndents = JavaMethod("([I[I)Landroid/text/StaticLayout$Builder;")
        setLineBreakConfig = JavaMethod("(Landroid/graphics/text/LineBreakConfig;)Landroid/text/StaticLayout$Builder;")
        setAlignment = JavaMethod("(Landroid/text/Layout$Alignment;)Landroid/text/StaticLayout$Builder;")
        setEllipsizedWidth = JavaMethod("(I)Landroid/text/StaticLayout$Builder;")
        setIncludePad = JavaMethod("(Z)Landroid/text/StaticLayout$Builder;")
        setUseLineSpacingFromFallbacks = JavaMethod("(Z)Landroid/text/StaticLayout$Builder;")
        setTextDirection = JavaMethod("(Landroid/text/TextDirectionHeuristic;)Landroid/text/StaticLayout$Builder;")
        obtain = JavaStaticMethod("(Ljava/lang/CharSequence;IILandroid/text/TextPaint;I)Landroid/text/StaticLayout$Builder;")
        build = JavaMethod("()Landroid/text/StaticLayout;")
        setBreakStrategy = JavaMethod("(I)Landroid/text/StaticLayout$Builder;")
        setEllipsize = JavaMethod("(Landroid/text/TextUtils$TruncateAt;)Landroid/text/StaticLayout$Builder;")
        setHyphenationFrequency = JavaMethod("(I)Landroid/text/StaticLayout$Builder;")
        setJustificationMode = JavaMethod("(I)Landroid/text/StaticLayout$Builder;")
        setLineSpacing = JavaMethod("(FF)Landroid/text/StaticLayout$Builder;")
        setMaxLines = JavaMethod("(I)Landroid/text/StaticLayout$Builder;")
        setMinimumFontMetrics = JavaMethod("(Landroid/graphics/Paint$FontMetrics;)Landroid/text/StaticLayout$Builder;")
        setShiftDrawingOffsetForStartOverhang = JavaMethod("(Z)Landroid/text/StaticLayout$Builder;")
        setText = JavaMethod("(Ljava/lang/CharSequence;)Landroid/text/StaticLayout$Builder;")
        setUseBoundsForWidth = JavaMethod("(Z)Landroid/text/StaticLayout$Builder;")

class SegmentFinder(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "android/text/SegmentFinder"
    __javaconstructor__ = [("()V", False)]
    DONE = JavaStaticField("I")
    nextEndBoundary = JavaMethod("(I)I")
    nextStartBoundary = JavaMethod("(I)I")
    previousEndBoundary = JavaMethod("(I)I")
    previousStartBoundary = JavaMethod("(I)I")

    class PrescribedSegmentFinder(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "android/text/SegmentFinder$PrescribedSegmentFinder"
        __javaconstructor__ = [("([I)V", False)]
        DONE = JavaStaticField("I")
        nextEndBoundary = JavaMethod("(I)I")
        nextStartBoundary = JavaMethod("(I)I")
        previousEndBoundary = JavaMethod("(I)I")
        previousStartBoundary = JavaMethod("(I)I")

class Highlights(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "android/text/Highlights"
    getRanges = JavaMethod("(I)[I")
    getSize = JavaMethod("()I")
    getPaint = JavaMethod("(I)Landroid/graphics/Paint;")

    class Builder(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "android/text/Highlights$Builder"
        __javaconstructor__ = [("()V", False)]
        addRanges = JavaMethod("(Landroid/graphics/Paint;[I)Landroid/text/Highlights$Builder;", varargs=True)
        addRange = JavaMethod("(Landroid/graphics/Paint;II)Landroid/text/Highlights$Builder;")
        build = JavaMethod("()Landroid/text/Highlights;")

class ParcelableSpan(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "android/text/ParcelableSpan"
    CONTENTS_FILE_DESCRIPTOR = JavaStaticField("I")
    PARCELABLE_WRITE_RETURN_VALUE = JavaStaticField("I")
    getSpanTypeId = JavaMethod("()I")

class TextDirectionHeuristic(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "android/text/TextDirectionHeuristic"
    isRtl = JavaMultipleMethod([("([CII)Z", False, False), ("(Ljava/lang/CharSequence;II)Z", False, False)])

class Spannable(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "android/text/Spannable"
    SPAN_COMPOSING = JavaStaticField("I")
    SPAN_EXCLUSIVE_EXCLUSIVE = JavaStaticField("I")
    SPAN_EXCLUSIVE_INCLUSIVE = JavaStaticField("I")
    SPAN_INCLUSIVE_EXCLUSIVE = JavaStaticField("I")
    SPAN_INCLUSIVE_INCLUSIVE = JavaStaticField("I")
    SPAN_INTERMEDIATE = JavaStaticField("I")
    SPAN_MARK_MARK = JavaStaticField("I")
    SPAN_MARK_POINT = JavaStaticField("I")
    SPAN_PARAGRAPH = JavaStaticField("I")
    SPAN_POINT_MARK = JavaStaticField("I")
    SPAN_POINT_MARK_MASK = JavaStaticField("I")
    SPAN_POINT_POINT = JavaStaticField("I")
    SPAN_PRIORITY = JavaStaticField("I")
    SPAN_PRIORITY_SHIFT = JavaStaticField("I")
    SPAN_USER = JavaStaticField("I")
    SPAN_USER_SHIFT = JavaStaticField("I")
    removeSpan = JavaMethod("(Ljava/lang/Object;)V")
    setSpan = JavaMethod("(Ljava/lang/Object;III)V")

    class Factory(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "android/text/Spannable$Factory"
        __javaconstructor__ = [("()V", False)]
        getInstance = JavaStaticMethod("()Landroid/text/Spannable$Factory;")
        newSpannable = JavaMethod("(Ljava/lang/CharSequence;)Landroid/text/Spannable;")

class AutoText(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "android/text/AutoText"
    get = JavaStaticMethod("(Ljava/lang/CharSequence;IILandroid/view/View;)Ljava/lang/String;")
    getSize = JavaStaticMethod("(Landroid/view/View;)I")

class BoringLayout(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "android/text/BoringLayout"
    __javaconstructor__ = [("(Ljava/lang/CharSequence;Landroid/text/TextPaint;ILandroid/text/Layout$Alignment;FFLandroid/text/BoringLayout$Metrics;Z)V", False), ("(Ljava/lang/CharSequence;Landroid/text/TextPaint;ILandroid/text/Layout$Alignment;FFLandroid/text/BoringLayout$Metrics;ZLandroid/text/TextUtils$TruncateAt;IZ)V", False), ("(Ljava/lang/CharSequence;Landroid/text/TextPaint;ILandroid/text/Layout$Alignment;FFLandroid/text/BoringLayout$Metrics;ZLandroid/text/TextUtils$TruncateAt;I)V", False)]
    BREAK_STRATEGY_BALANCED = JavaStaticField("I")
    BREAK_STRATEGY_HIGH_QUALITY = JavaStaticField("I")
    BREAK_STRATEGY_SIMPLE = JavaStaticField("I")
    DEFAULT_LINESPACING_ADDITION = JavaStaticField("F")
    DEFAULT_LINESPACING_MULTIPLIER = JavaStaticField("F")
    DIR_LEFT_TO_RIGHT = JavaStaticField("I")
    DIR_RIGHT_TO_LEFT = JavaStaticField("I")
    HYPHENATION_FREQUENCY_FULL = JavaStaticField("I")
    HYPHENATION_FREQUENCY_FULL_FAST = JavaStaticField("I")
    HYPHENATION_FREQUENCY_NONE = JavaStaticField("I")
    HYPHENATION_FREQUENCY_NORMAL = JavaStaticField("I")
    HYPHENATION_FREQUENCY_NORMAL_FAST = JavaStaticField("I")
    INCLUSION_STRATEGY_ANY_OVERLAP = JavaStaticField("Landroid/text/Layout$TextInclusionStrategy;")
    INCLUSION_STRATEGY_CONTAINS_ALL = JavaStaticField("Landroid/text/Layout$TextInclusionStrategy;")
    INCLUSION_STRATEGY_CONTAINS_CENTER = JavaStaticField("Landroid/text/Layout$TextInclusionStrategy;")
    JUSTIFICATION_MODE_INTER_CHARACTER = JavaStaticField("I")
    JUSTIFICATION_MODE_INTER_WORD = JavaStaticField("I")
    JUSTIFICATION_MODE_NONE = JavaStaticField("I")
    ellipsized = JavaMethod("(II)V")
    isBoring = JavaMultipleMethod([("(Ljava/lang/CharSequence;Landroid/text/TextPaint;Landroid/text/TextDirectionHeuristic;ZLandroid/text/BoringLayout$Metrics;)Landroid/text/BoringLayout$Metrics;", True, False), ("(Ljava/lang/CharSequence;Landroid/text/TextPaint;Landroid/text/BoringLayout$Metrics;)Landroid/text/BoringLayout$Metrics;", True, False), ("(Ljava/lang/CharSequence;Landroid/text/TextPaint;)Landroid/text/BoringLayout$Metrics;", True, False)])
    replaceOrMake = JavaMultipleMethod([("(Ljava/lang/CharSequence;Landroid/text/TextPaint;ILandroid/text/Layout$Alignment;FFLandroid/text/BoringLayout$Metrics;ZLandroid/text/TextUtils$TruncateAt;I)Landroid/text/BoringLayout;", False, False), ("(Ljava/lang/CharSequence;Landroid/text/TextPaint;ILandroid/text/Layout$Alignment;Landroid/text/BoringLayout$Metrics;ZLandroid/text/TextUtils$TruncateAt;IZ)Landroid/text/BoringLayout;", False, False), ("(Ljava/lang/CharSequence;Landroid/text/TextPaint;ILandroid/text/Layout$Alignment;FFLandroid/text/BoringLayout$Metrics;Z)Landroid/text/BoringLayout;", False, False)])
    make = JavaMultipleMethod([("(Ljava/lang/CharSequence;Landroid/text/TextPaint;ILandroid/text/Layout$Alignment;FFLandroid/text/BoringLayout$Metrics;Z)Landroid/text/BoringLayout;", True, False), ("(Ljava/lang/CharSequence;Landroid/text/TextPaint;ILandroid/text/Layout$Alignment;FFLandroid/text/BoringLayout$Metrics;ZLandroid/text/TextUtils$TruncateAt;I)Landroid/text/BoringLayout;", True, False), ("(Ljava/lang/CharSequence;Landroid/text/TextPaint;ILandroid/text/Layout$Alignment;Landroid/text/BoringLayout$Metrics;ZLandroid/text/TextUtils$TruncateAt;IZ)Landroid/text/BoringLayout;", True, False)])
    draw = JavaMethod("(Landroid/graphics/Canvas;Landroid/graphics/Path;Landroid/graphics/Paint;I)V")
    getHeight = JavaMethod("()I")
    computeDrawingBoundingBox = JavaMethod("()Landroid/graphics/RectF;")
    getBottomPadding = JavaMethod("()I")
    getEllipsisCount = JavaMethod("(I)I")
    getEllipsisStart = JavaMethod("(I)I")
    getEllipsizedWidth = JavaMethod("()I")
    getLineContainsTab = JavaMethod("(I)Z")
    getLineDescent = JavaMethod("(I)I")
    getLineDirections = JavaMethod("(I)Landroid/text/Layout$Directions;")
    getLineMax = JavaMethod("(I)F")
    getLineStart = JavaMethod("(I)I")
    getLineTop = JavaMethod("(I)I")
    getLineWidth = JavaMethod("(I)F")
    getParagraphDirection = JavaMethod("(I)I")
    getTopPadding = JavaMethod("()I")
    isFallbackLineSpacingEnabled = JavaMethod("()Z")
    getLineCount = JavaMethod("()I")

    class Metrics(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "android/text/BoringLayout$Metrics"
        __javaconstructor__ = [("()V", False)]
        width = JavaField("I")
        ascent = JavaField("I")
        bottom = JavaField("I")
        descent = JavaField("I")
        leading = JavaField("I")
        top = JavaField("I")
        getDrawingBoundingBox = JavaMethod("()Landroid/graphics/RectF;")
        toString = JavaMethod("()Ljava/lang/String;")

class WordSegmentFinder(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "android/text/WordSegmentFinder"
    __javaconstructor__ = [("(Ljava/lang/CharSequence;Landroid/icu/util/ULocale;)V", False)]
    DONE = JavaStaticField("I")
    nextEndBoundary = JavaMethod("(I)I")
    nextStartBoundary = JavaMethod("(I)I")
    previousEndBoundary = JavaMethod("(I)I")
    previousStartBoundary = JavaMethod("(I)I")

class TextShaper(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "android/text/TextShaper"
    shapeText = JavaStaticMethod("(Ljava/lang/CharSequence;IILandroid/text/TextDirectionHeuristic;Landroid/text/TextPaint;Landroid/text/TextShaper$GlyphsConsumer;)V")

    class GlyphsConsumer(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "android/text/TextShaper$GlyphsConsumer"
        accept = JavaMethod("(IILandroid/graphics/text/PositionedGlyphs;Landroid/text/TextPaint;)V")

class InputType(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "android/text/InputType"
    TYPE_CLASS_DATETIME = JavaStaticField("I")
    TYPE_CLASS_NUMBER = JavaStaticField("I")
    TYPE_CLASS_PHONE = JavaStaticField("I")
    TYPE_CLASS_TEXT = JavaStaticField("I")
    TYPE_DATETIME_VARIATION_DATE = JavaStaticField("I")
    TYPE_DATETIME_VARIATION_NORMAL = JavaStaticField("I")
    TYPE_DATETIME_VARIATION_TIME = JavaStaticField("I")
    TYPE_MASK_CLASS = JavaStaticField("I")
    TYPE_MASK_FLAGS = JavaStaticField("I")
    TYPE_MASK_VARIATION = JavaStaticField("I")
    TYPE_NULL = JavaStaticField("I")
    TYPE_NUMBER_FLAG_DECIMAL = JavaStaticField("I")
    TYPE_NUMBER_FLAG_SIGNED = JavaStaticField("I")
    TYPE_NUMBER_VARIATION_NORMAL = JavaStaticField("I")
    TYPE_NUMBER_VARIATION_PASSWORD = JavaStaticField("I")
    TYPE_TEXT_FLAG_AUTO_COMPLETE = JavaStaticField("I")
    TYPE_TEXT_FLAG_AUTO_CORRECT = JavaStaticField("I")
    TYPE_TEXT_FLAG_CAP_CHARACTERS = JavaStaticField("I")
    TYPE_TEXT_FLAG_CAP_SENTENCES = JavaStaticField("I")
    TYPE_TEXT_FLAG_CAP_WORDS = JavaStaticField("I")
    TYPE_TEXT_FLAG_ENABLE_TEXT_CONVERSION_SUGGESTIONS = JavaStaticField("I")
    TYPE_TEXT_FLAG_IME_MULTI_LINE = JavaStaticField("I")
    TYPE_TEXT_FLAG_MULTI_LINE = JavaStaticField("I")
    TYPE_TEXT_FLAG_NO_SUGGESTIONS = JavaStaticField("I")
    TYPE_TEXT_VARIATION_EMAIL_ADDRESS = JavaStaticField("I")
    TYPE_TEXT_VARIATION_EMAIL_SUBJECT = JavaStaticField("I")
    TYPE_TEXT_VARIATION_FILTER = JavaStaticField("I")
    TYPE_TEXT_VARIATION_LONG_MESSAGE = JavaStaticField("I")
    TYPE_TEXT_VARIATION_NORMAL = JavaStaticField("I")
    TYPE_TEXT_VARIATION_PASSWORD = JavaStaticField("I")
    TYPE_TEXT_VARIATION_PERSON_NAME = JavaStaticField("I")
    TYPE_TEXT_VARIATION_PHONETIC = JavaStaticField("I")
    TYPE_TEXT_VARIATION_POSTAL_ADDRESS = JavaStaticField("I")
    TYPE_TEXT_VARIATION_SHORT_MESSAGE = JavaStaticField("I")
    TYPE_TEXT_VARIATION_URI = JavaStaticField("I")
    TYPE_TEXT_VARIATION_VISIBLE_PASSWORD = JavaStaticField("I")
    TYPE_TEXT_VARIATION_WEB_EDIT_TEXT = JavaStaticField("I")
    TYPE_TEXT_VARIATION_WEB_EMAIL_ADDRESS = JavaStaticField("I")
    TYPE_TEXT_VARIATION_WEB_PASSWORD = JavaStaticField("I")

class Layout(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "android/text/Layout"
    BREAK_STRATEGY_BALANCED = JavaStaticField("I")
    BREAK_STRATEGY_HIGH_QUALITY = JavaStaticField("I")
    BREAK_STRATEGY_SIMPLE = JavaStaticField("I")
    DEFAULT_LINESPACING_ADDITION = JavaStaticField("F")
    DEFAULT_LINESPACING_MULTIPLIER = JavaStaticField("F")
    DIR_LEFT_TO_RIGHT = JavaStaticField("I")
    DIR_RIGHT_TO_LEFT = JavaStaticField("I")
    HYPHENATION_FREQUENCY_FULL = JavaStaticField("I")
    HYPHENATION_FREQUENCY_FULL_FAST = JavaStaticField("I")
    HYPHENATION_FREQUENCY_NONE = JavaStaticField("I")
    HYPHENATION_FREQUENCY_NORMAL = JavaStaticField("I")
    HYPHENATION_FREQUENCY_NORMAL_FAST = JavaStaticField("I")
    INCLUSION_STRATEGY_ANY_OVERLAP = JavaStaticField("Landroid/text/Layout$TextInclusionStrategy;")
    INCLUSION_STRATEGY_CONTAINS_ALL = JavaStaticField("Landroid/text/Layout$TextInclusionStrategy;")
    INCLUSION_STRATEGY_CONTAINS_CENTER = JavaStaticField("Landroid/text/Layout$TextInclusionStrategy;")
    JUSTIFICATION_MODE_INTER_CHARACTER = JavaStaticField("I")
    JUSTIFICATION_MODE_INTER_WORD = JavaStaticField("I")
    JUSTIFICATION_MODE_NONE = JavaStaticField("I")
    draw = JavaMultipleMethod([("(Landroid/graphics/Canvas;Ljava/util/List;Ljava/util/List;Landroid/graphics/Path;Landroid/graphics/Paint;I)V", False, False), ("(Landroid/graphics/Canvas;Landroid/graphics/Path;Landroid/graphics/Paint;I)V", False, False), ("(Landroid/graphics/Canvas;)V", False, False)])
    getHeight = JavaMethod("()I")
    getWidth = JavaMethod("()I")
    getText = JavaMethod("()Ljava/lang/CharSequence;")
    computeDrawingBoundingBox = JavaMethod("()Landroid/graphics/RectF;")
    drawBackground = JavaMethod("(Landroid/graphics/Canvas;)V")
    fillCharacterBounds = JavaMethod("(II[FI)V")
    getAlignment = JavaMethod("()Landroid/text/Layout$Alignment;")
    getBottomPadding = JavaMethod("()I")
    getCursorPath = JavaMethod("(ILandroid/graphics/Path;Ljava/lang/CharSequence;)V")
    getDesiredWidth = JavaMultipleMethod([("(Ljava/lang/CharSequence;Landroid/text/TextPaint;)F", True, False), ("(Ljava/lang/CharSequence;IILandroid/text/TextPaint;)F", True, False)])
    getEllipsisCount = JavaMethod("(I)I")
    getEllipsisStart = JavaMethod("(I)I")
    getEllipsizedWidth = JavaMethod("()I")
    getLeftIndents = JavaMethod("()[I")
    getLineAscent = JavaMethod("(I)I")
    getLineBaseline = JavaMethod("(I)I")
    getLineBottom = JavaMultipleMethod([("(I)I", False, False), ("(IZ)I", False, False)])
    getLineBreakConfig = JavaMethod("()Landroid/graphics/text/LineBreakConfig;")
    getLineContainsTab = JavaMethod("(I)Z")
    getLineDescent = JavaMethod("(I)I")
    getLineDirections = JavaMethod("(I)Landroid/text/Layout$Directions;")
    getLineEnd = JavaMethod("(I)I")
    getLineForOffset = JavaMethod("(I)I")
    getLineForVertical = JavaMethod("(I)I")
    getLineLeft = JavaMethod("(I)F")
    getLineLetterSpacingUnitCount = JavaMethod("(IZ)I")
    getLineMax = JavaMethod("(I)F")
    getLineRight = JavaMethod("(I)F")
    getLineSpacingAmount = JavaMethod("()F")
    getLineStart = JavaMethod("(I)I")
    getLineTop = JavaMethod("(I)I")
    getLineVisibleEnd = JavaMethod("(I)I")
    getLineWidth = JavaMethod("(I)F")
    getOffsetForHorizontal = JavaMethod("(IF)I")
    getOffsetToLeftOf = JavaMethod("(I)I")
    getOffsetToRightOf = JavaMethod("(I)I")
    getParagraphAlignment = JavaMethod("(I)Landroid/text/Layout$Alignment;")
    getParagraphDirection = JavaMethod("(I)I")
    getParagraphLeft = JavaMethod("(I)I")
    getParagraphRight = JavaMethod("(I)I")
    getPrimaryHorizontal = JavaMethod("(I)F")
    getRangeForRect = JavaMethod("(Landroid/graphics/RectF;Landroid/text/SegmentFinder;Landroid/text/Layout$TextInclusionStrategy;)[I")
    getRightIndents = JavaMethod("()[I")
    getSecondaryHorizontal = JavaMethod("(I)F")
    getSelectionPath = JavaMethod("(IILandroid/graphics/Path;)V")
    getSpacingAdd = JavaMethod("()F")
    getSpacingMultiplier = JavaMethod("()F")
    getTopPadding = JavaMethod("()I")
    increaseWidthTo = JavaMethod("(I)V")
    isFallbackLineSpacingEnabled = JavaMethod("()Z")
    isFontPaddingIncluded = JavaMethod("()Z")
    isRtlCharAt = JavaMethod("(I)Z")
    drawText = JavaMethod("(Landroid/graphics/Canvas;)V")
    getBreakStrategy = JavaMethod("()I")
    getEllipsize = JavaMethod("()Landroid/text/TextUtils$TruncateAt;")
    getHyphenationFrequency = JavaMethod("()I")
    getJustificationMode = JavaMethod("()I")
    getLineBounds = JavaMethod("(ILandroid/graphics/Rect;)I")
    getLineCount = JavaMethod("()I")
    getLineSpacingMultiplier = JavaMethod("()F")
    getMaxLines = JavaMethod("()I")
    getMinimumFontMetrics = JavaMethod("()Landroid/graphics/Paint$FontMetrics;")
    getPaint = JavaMethod("()Landroid/text/TextPaint;")
    getShiftDrawingOffsetForStartOverhang = JavaMethod("()Z")
    getTextDirectionHeuristic = JavaMethod("()Landroid/text/TextDirectionHeuristic;")
    getUseBoundsForWidth = JavaMethod("()Z")

    class TextInclusionStrategy(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "android/text/Layout$TextInclusionStrategy"
        isSegmentInside = JavaMethod("(Landroid/graphics/RectF;Landroid/graphics/RectF;)Z")

    class Directions(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "android/text/Layout$Directions"

    class Builder(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "android/text/Layout$Builder"
        __javaconstructor__ = [("(Ljava/lang/CharSequence;IILandroid/text/TextPaint;I)V", False)]
        setLineBreakConfig = JavaMethod("(Landroid/graphics/text/LineBreakConfig;)Landroid/text/Layout$Builder;")
        setAlignment = JavaMethod("(Landroid/text/Layout$Alignment;)Landroid/text/Layout$Builder;")
        setEllipsizedWidth = JavaMethod("(I)Landroid/text/Layout$Builder;")
        setFallbackLineSpacingEnabled = JavaMethod("(Z)Landroid/text/Layout$Builder;")
        setFontPaddingIncluded = JavaMethod("(Z)Landroid/text/Layout$Builder;")
        setLeftIndents = JavaMethod("([I)Landroid/text/Layout$Builder;")
        setLineSpacingAmount = JavaMethod("(F)Landroid/text/Layout$Builder;")
        setLineSpacingMultiplier = JavaMethod("(F)Landroid/text/Layout$Builder;")
        setRightIndents = JavaMethod("([I)Landroid/text/Layout$Builder;")
        setTextDirectionHeuristic = JavaMethod("(Landroid/text/TextDirectionHeuristic;)Landroid/text/Layout$Builder;")
        build = JavaMethod("()Landroid/text/Layout;")
        setBreakStrategy = JavaMethod("(I)Landroid/text/Layout$Builder;")
        setEllipsize = JavaMethod("(Landroid/text/TextUtils$TruncateAt;)Landroid/text/Layout$Builder;")
        setHyphenationFrequency = JavaMethod("(I)Landroid/text/Layout$Builder;")
        setJustificationMode = JavaMethod("(I)Landroid/text/Layout$Builder;")
        setMaxLines = JavaMethod("(I)Landroid/text/Layout$Builder;")
        setMinimumFontMetrics = JavaMethod("(Landroid/graphics/Paint$FontMetrics;)Landroid/text/Layout$Builder;")
        setShiftDrawingOffsetForStartOverhang = JavaMethod("(Z)Landroid/text/Layout$Builder;")
        setUseBoundsForWidth = JavaMethod("(Z)Landroid/text/Layout$Builder;")

    class Alignment(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "android/text/Layout$Alignment"
        ALIGN_CENTER = JavaStaticField("Landroid/text/Layout$Alignment;")
        ALIGN_NORMAL = JavaStaticField("Landroid/text/Layout$Alignment;")
        ALIGN_OPPOSITE = JavaStaticField("Landroid/text/Layout$Alignment;")
        values = JavaStaticMethod("()[Landroid/text/Layout$Alignment;")
        valueOf = JavaStaticMethod("(Ljava/lang/String;)Landroid/text/Layout$Alignment;")
        ALIGN_CENTER = JavaStaticField("Landroid/text/Layout$Alignment;")
        ALIGN_NORMAL = JavaStaticField("Landroid/text/Layout$Alignment;")
        ALIGN_OPPOSITE = JavaStaticField("Landroid/text/Layout$Alignment;")

class TextWatcher(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "android/text/TextWatcher"
    afterTextChanged = JavaMethod("(Landroid/text/Editable;)V")
    beforeTextChanged = JavaMethod("(Ljava/lang/CharSequence;III)V")
    onTextChanged = JavaMethod("(Ljava/lang/CharSequence;III)V")

class Spanned(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "android/text/Spanned"
    SPAN_COMPOSING = JavaStaticField("I")
    SPAN_EXCLUSIVE_EXCLUSIVE = JavaStaticField("I")
    SPAN_EXCLUSIVE_INCLUSIVE = JavaStaticField("I")
    SPAN_INCLUSIVE_EXCLUSIVE = JavaStaticField("I")
    SPAN_INCLUSIVE_INCLUSIVE = JavaStaticField("I")
    SPAN_INTERMEDIATE = JavaStaticField("I")
    SPAN_MARK_MARK = JavaStaticField("I")
    SPAN_MARK_POINT = JavaStaticField("I")
    SPAN_PARAGRAPH = JavaStaticField("I")
    SPAN_POINT_MARK = JavaStaticField("I")
    SPAN_POINT_MARK_MASK = JavaStaticField("I")
    SPAN_POINT_POINT = JavaStaticField("I")
    SPAN_PRIORITY = JavaStaticField("I")
    SPAN_PRIORITY_SHIFT = JavaStaticField("I")
    SPAN_USER = JavaStaticField("I")
    SPAN_USER_SHIFT = JavaStaticField("I")
    getSpanEnd = JavaMethod("(Ljava/lang/Object;)I")
    getSpanFlags = JavaMethod("(Ljava/lang/Object;)I")
    getSpanStart = JavaMethod("(Ljava/lang/Object;)I")
    nextSpanTransition = JavaMethod("(IILjava/lang/Class;)I")
    getSpans = JavaMethod("(IILjava/lang/Class;)[Ljava/lang/Object;")

class Editable(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "android/text/Editable"
    SPAN_COMPOSING = JavaStaticField("I")
    SPAN_EXCLUSIVE_EXCLUSIVE = JavaStaticField("I")
    SPAN_EXCLUSIVE_INCLUSIVE = JavaStaticField("I")
    SPAN_INCLUSIVE_EXCLUSIVE = JavaStaticField("I")
    SPAN_INCLUSIVE_INCLUSIVE = JavaStaticField("I")
    SPAN_INTERMEDIATE = JavaStaticField("I")
    SPAN_MARK_MARK = JavaStaticField("I")
    SPAN_MARK_POINT = JavaStaticField("I")
    SPAN_PARAGRAPH = JavaStaticField("I")
    SPAN_POINT_MARK = JavaStaticField("I")
    SPAN_POINT_MARK_MASK = JavaStaticField("I")
    SPAN_POINT_POINT = JavaStaticField("I")
    SPAN_PRIORITY = JavaStaticField("I")
    SPAN_PRIORITY_SHIFT = JavaStaticField("I")
    SPAN_USER = JavaStaticField("I")
    SPAN_USER_SHIFT = JavaStaticField("I")
    append = JavaMultipleMethod([("(Ljava/lang/CharSequence;)Ljava/lang/Appendable;", False, False), ("(Ljava/lang/CharSequence;II)Ljava/lang/Appendable;", False, False), ("(C)Ljava/lang/Appendable;", False, False), ("(Ljava/lang/CharSequence;)Landroid/text/Editable;", False, False), ("(C)Landroid/text/Editable;", False, False), ("(Ljava/lang/CharSequence;II)Landroid/text/Editable;", False, False)])
    insert = JavaMultipleMethod([("(ILjava/lang/CharSequence;II)Landroid/text/Editable;", False, False), ("(ILjava/lang/CharSequence;)Landroid/text/Editable;", False, False)])
    clear = JavaMethod("()V")
    replace = JavaMultipleMethod([("(IILjava/lang/CharSequence;)Landroid/text/Editable;", False, False), ("(IILjava/lang/CharSequence;II)Landroid/text/Editable;", False, False)])
    delete = JavaMethod("(II)Landroid/text/Editable;")
    clearSpans = JavaMethod("()V")
    getFilters = JavaMethod("()[Landroid/text/InputFilter;")
    setFilters = JavaMethod("([Landroid/text/InputFilter;)V")

    class Factory(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "android/text/Editable$Factory"
        __javaconstructor__ = [("()V", False)]
        getInstance = JavaStaticMethod("()Landroid/text/Editable$Factory;")
        newEditable = JavaMethod("(Ljava/lang/CharSequence;)Landroid/text/Editable;")

class SpannedString(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "android/text/SpannedString"
    __javaconstructor__ = [("(Ljava/lang/CharSequence;)V", False)]
    SPAN_COMPOSING = JavaStaticField("I")
    SPAN_EXCLUSIVE_EXCLUSIVE = JavaStaticField("I")
    SPAN_EXCLUSIVE_INCLUSIVE = JavaStaticField("I")
    SPAN_INCLUSIVE_EXCLUSIVE = JavaStaticField("I")
    SPAN_INCLUSIVE_INCLUSIVE = JavaStaticField("I")
    SPAN_INTERMEDIATE = JavaStaticField("I")
    SPAN_MARK_MARK = JavaStaticField("I")
    SPAN_MARK_POINT = JavaStaticField("I")
    SPAN_PARAGRAPH = JavaStaticField("I")
    SPAN_POINT_MARK = JavaStaticField("I")
    SPAN_POINT_MARK_MASK = JavaStaticField("I")
    SPAN_POINT_POINT = JavaStaticField("I")
    SPAN_PRIORITY = JavaStaticField("I")
    SPAN_PRIORITY_SHIFT = JavaStaticField("I")
    SPAN_USER = JavaStaticField("I")
    SPAN_USER_SHIFT = JavaStaticField("I")
    equals = JavaMethod("(Ljava/lang/Object;)Z")
    length = JavaMethod("()I")
    toString = JavaMethod("()Ljava/lang/String;")
    hashCode = JavaMethod("()I")
    getChars = JavaMethod("(II[CI)V")
    valueOf = JavaStaticMethod("(Ljava/lang/CharSequence;)Landroid/text/SpannedString;")
    charAt = JavaMethod("(I)C")
    subSequence = JavaMethod("(II)Ljava/lang/CharSequence;")
    getSpanEnd = JavaMethod("(Ljava/lang/Object;)I")
    getSpanFlags = JavaMethod("(Ljava/lang/Object;)I")
    getSpanStart = JavaMethod("(Ljava/lang/Object;)I")
    nextSpanTransition = JavaMethod("(IILjava/lang/Class;)I")
    getSpans = JavaMethod("(IILjava/lang/Class;)[Ljava/lang/Object;")

class TextUtils(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "android/text/TextUtils"
    CAP_MODE_CHARACTERS = JavaStaticField("I")
    CAP_MODE_SENTENCES = JavaStaticField("I")
    CAP_MODE_WORDS = JavaStaticField("I")
    CHAR_SEQUENCE_CREATOR = JavaStaticField("Landroid/os/Parcelable$Creator;")
    SAFE_STRING_FLAG_FIRST_LINE = JavaStaticField("I")
    SAFE_STRING_FLAG_SINGLE_LINE = JavaStaticField("I")
    SAFE_STRING_FLAG_TRIM = JavaStaticField("I")
    ellipsize = JavaMultipleMethod([("(Ljava/lang/CharSequence;Landroid/text/TextPaint;FLandroid/text/TextUtils$TruncateAt;)Ljava/lang/CharSequence;", True, False), ("(Ljava/lang/CharSequence;Landroid/text/TextPaint;FLandroid/text/TextUtils$TruncateAt;ZLandroid/text/TextUtils$EllipsizeCallback;)Ljava/lang/CharSequence;", True, False)])
    commaEllipsize = JavaStaticMethod("(Ljava/lang/CharSequence;Landroid/text/TextPaint;FLjava/lang/String;Ljava/lang/String;)Ljava/lang/CharSequence;")
    copySpansFrom = JavaStaticMethod("(Landroid/text/Spanned;IILjava/lang/Class;Landroid/text/Spannable;I)V")
    dumpSpans = JavaStaticMethod("(Ljava/lang/CharSequence;Landroid/util/Printer;Ljava/lang/String;)V")
    expandTemplate = JavaStaticMethod("(Ljava/lang/CharSequence;[Ljava/lang/CharSequence;)Ljava/lang/CharSequence;", varargs=True)
    getCapsMode = JavaStaticMethod("(Ljava/lang/CharSequence;II)I")
    getReverse = JavaStaticMethod("(Ljava/lang/CharSequence;II)Ljava/lang/CharSequence;")
    getTrimmedLength = JavaStaticMethod("(Ljava/lang/CharSequence;)I")
    htmlEncode = JavaStaticMethod("(Ljava/lang/String;)Ljava/lang/String;")
    isDigitsOnly = JavaStaticMethod("(Ljava/lang/CharSequence;)Z")
    isGraphic = JavaMultipleMethod([("(C)Z", True, False), ("(Ljava/lang/CharSequence;)Z", True, False)])
    listEllipsize = JavaStaticMethod("(Landroid/content/Context;Ljava/util/List;Ljava/lang/String;Landroid/text/TextPaint;FI)Ljava/lang/CharSequence;")
    makeSafeForPresentation = JavaStaticMethod("(Ljava/lang/String;IFI)Ljava/lang/CharSequence;")
    stringOrSpannedString = JavaStaticMethod("(Ljava/lang/CharSequence;)Ljava/lang/CharSequence;")
    equals = JavaStaticMethod("(Ljava/lang/CharSequence;Ljava/lang/CharSequence;)Z")
    getChars = JavaStaticMethod("(Ljava/lang/CharSequence;II[CI)V")
    indexOf = JavaMultipleMethod([("(Ljava/lang/CharSequence;Ljava/lang/CharSequence;II)I", True, False), ("(Ljava/lang/CharSequence;Ljava/lang/CharSequence;I)I", True, False), ("(Ljava/lang/CharSequence;CI)I", True, False), ("(Ljava/lang/CharSequence;CII)I", True, False), ("(Ljava/lang/CharSequence;Ljava/lang/CharSequence;)I", True, False), ("(Ljava/lang/CharSequence;C)I", True, False)])
    regionMatches = JavaStaticMethod("(Ljava/lang/CharSequence;ILjava/lang/CharSequence;II)Z")
    lastIndexOf = JavaMultipleMethod([("(Ljava/lang/CharSequence;CII)I", True, False), ("(Ljava/lang/CharSequence;C)I", True, False), ("(Ljava/lang/CharSequence;CI)I", True, False)])
    substring = JavaStaticMethod("(Ljava/lang/CharSequence;II)Ljava/lang/String;")
    isEmpty = JavaStaticMethod("(Ljava/lang/CharSequence;)Z")
    replace = JavaStaticMethod("(Ljava/lang/CharSequence;[Ljava/lang/String;[Ljava/lang/CharSequence;)Ljava/lang/CharSequence;")
    split = JavaMultipleMethod([("(Ljava/lang/String;Ljava/lang/String;)[Ljava/lang/String;", True, False), ("(Ljava/lang/String;Ljava/util/regex/Pattern;)[Ljava/lang/String;", True, False)])
    join = JavaMultipleMethod([("(Ljava/lang/CharSequence;[Ljava/lang/Object;)Ljava/lang/String;", True, False), ("(Ljava/lang/CharSequence;Ljava/lang/Iterable;)Ljava/lang/String;", True, False)])
    concat = JavaStaticMethod("([Ljava/lang/CharSequence;)Ljava/lang/CharSequence;", varargs=True)
    getOffsetAfter = JavaStaticMethod("(Ljava/lang/CharSequence;I)I")
    getOffsetBefore = JavaStaticMethod("(Ljava/lang/CharSequence;I)I")
    getLayoutDirectionFromLocale = JavaStaticMethod("(Ljava/util/Locale;)I")
    writeToParcel = JavaStaticMethod("(Ljava/lang/CharSequence;Landroid/os/Parcel;I)V")

    class TruncateAt(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "android/text/TextUtils$TruncateAt"
        END = JavaStaticField("Landroid/text/TextUtils$TruncateAt;")
        MARQUEE = JavaStaticField("Landroid/text/TextUtils$TruncateAt;")
        MIDDLE = JavaStaticField("Landroid/text/TextUtils$TruncateAt;")
        START = JavaStaticField("Landroid/text/TextUtils$TruncateAt;")
        values = JavaStaticMethod("()[Landroid/text/TextUtils$TruncateAt;")
        valueOf = JavaStaticMethod("(Ljava/lang/String;)Landroid/text/TextUtils$TruncateAt;")
        END = JavaStaticField("Landroid/text/TextUtils$TruncateAt;")
        MARQUEE = JavaStaticField("Landroid/text/TextUtils$TruncateAt;")
        MIDDLE = JavaStaticField("Landroid/text/TextUtils$TruncateAt;")
        START = JavaStaticField("Landroid/text/TextUtils$TruncateAt;")

    class StringSplitter(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "android/text/TextUtils$StringSplitter"
        setString = JavaMethod("(Ljava/lang/String;)V")

    class SimpleStringSplitter(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "android/text/TextUtils$SimpleStringSplitter"
        __javaconstructor__ = [("(C)V", False)]
        remove = JavaMethod("()V")
        iterator = JavaMethod("()Ljava/util/Iterator;")
        hasNext = JavaMethod("()Z")
        next = JavaMultipleMethod([("()Ljava/lang/Object;", False, False), ("()Ljava/lang/String;", False, False)])
        setString = JavaMethod("(Ljava/lang/String;)V")

    class EllipsizeCallback(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "android/text/TextUtils$EllipsizeCallback"
        ellipsized = JavaMethod("(II)V")

class AlteredCharSequence(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "android/text/AlteredCharSequence"
    length = JavaMethod("()I")
    toString = JavaMethod("()Ljava/lang/String;")
    getChars = JavaMethod("(II[CI)V")
    charAt = JavaMethod("(I)C")
    subSequence = JavaMethod("(II)Ljava/lang/CharSequence;")
    make = JavaStaticMethod("(Ljava/lang/CharSequence;[CII)Landroid/text/AlteredCharSequence;")

class SpannableString(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "android/text/SpannableString"
    __javaconstructor__ = [("(Ljava/lang/CharSequence;)V", False)]
    SPAN_COMPOSING = JavaStaticField("I")
    SPAN_EXCLUSIVE_EXCLUSIVE = JavaStaticField("I")
    SPAN_EXCLUSIVE_INCLUSIVE = JavaStaticField("I")
    SPAN_INCLUSIVE_EXCLUSIVE = JavaStaticField("I")
    SPAN_INCLUSIVE_INCLUSIVE = JavaStaticField("I")
    SPAN_INTERMEDIATE = JavaStaticField("I")
    SPAN_MARK_MARK = JavaStaticField("I")
    SPAN_MARK_POINT = JavaStaticField("I")
    SPAN_PARAGRAPH = JavaStaticField("I")
    SPAN_POINT_MARK = JavaStaticField("I")
    SPAN_POINT_MARK_MASK = JavaStaticField("I")
    SPAN_POINT_POINT = JavaStaticField("I")
    SPAN_PRIORITY = JavaStaticField("I")
    SPAN_PRIORITY_SHIFT = JavaStaticField("I")
    SPAN_USER = JavaStaticField("I")
    SPAN_USER_SHIFT = JavaStaticField("I")
    equals = JavaMethod("(Ljava/lang/Object;)Z")
    length = JavaMethod("()I")
    toString = JavaMethod("()Ljava/lang/String;")
    hashCode = JavaMethod("()I")
    getChars = JavaMethod("(II[CI)V")
    valueOf = JavaStaticMethod("(Ljava/lang/CharSequence;)Landroid/text/SpannableString;")
    charAt = JavaMethod("(I)C")
    subSequence = JavaMethod("(II)Ljava/lang/CharSequence;")
    removeSpan = JavaMethod("(Ljava/lang/Object;)V")
    setSpan = JavaMethod("(Ljava/lang/Object;III)V")
    getSpanEnd = JavaMethod("(Ljava/lang/Object;)I")
    getSpanFlags = JavaMethod("(Ljava/lang/Object;)I")
    getSpanStart = JavaMethod("(Ljava/lang/Object;)I")
    nextSpanTransition = JavaMethod("(IILjava/lang/Class;)I")
    getSpans = JavaMethod("(IILjava/lang/Class;)[Ljava/lang/Object;")

class ClipboardManager(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "android/text/ClipboardManager"
    __javaconstructor__ = [("()V", False)]
    hasText = JavaMethod("()Z")
    getText = JavaMethod("()Ljava/lang/CharSequence;")
    setText = JavaMethod("(Ljava/lang/CharSequence;)V")

class EmojiConsistency(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "android/text/EmojiConsistency"
    getEmojiConsistencySet = JavaStaticMethod("()Ljava/util/Set;")

class BidiFormatter(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "android/text/BidiFormatter"
    getStereoReset = JavaMethod("()Z")
    isRtlContext = JavaMethod("()Z")
    unicodeWrap = JavaMultipleMethod([("(Ljava/lang/String;Z)Ljava/lang/String;", False, False), ("(Ljava/lang/CharSequence;Landroid/text/TextDirectionHeuristic;)Ljava/lang/CharSequence;", False, False), ("(Ljava/lang/CharSequence;Landroid/text/TextDirectionHeuristic;Z)Ljava/lang/CharSequence;", False, False), ("(Ljava/lang/String;Landroid/text/TextDirectionHeuristic;)Ljava/lang/String;", False, False), ("(Ljava/lang/String;)Ljava/lang/String;", False, False), ("(Ljava/lang/CharSequence;Z)Ljava/lang/CharSequence;", False, False), ("(Ljava/lang/String;Landroid/text/TextDirectionHeuristic;Z)Ljava/lang/String;", False, False), ("(Ljava/lang/CharSequence;)Ljava/lang/CharSequence;", False, False)])
    getInstance = JavaMultipleMethod([("(Z)Landroid/text/BidiFormatter;", True, False), ("()Landroid/text/BidiFormatter;", True, False), ("(Ljava/util/Locale;)Landroid/text/BidiFormatter;", True, False)])
    isRtl = JavaMultipleMethod([("(Ljava/lang/CharSequence;)Z", False, False), ("(Ljava/lang/String;)Z", False, False)])

    class Builder(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "android/text/BidiFormatter$Builder"
        __javaconstructor__ = [("()V", False), ("(Ljava/util/Locale;)V", False), ("(Z)V", False)]
        stereoReset = JavaMethod("(Z)Landroid/text/BidiFormatter$Builder;")
        setTextDirectionHeuristic = JavaMethod("(Landroid/text/TextDirectionHeuristic;)Landroid/text/BidiFormatter$Builder;")
        build = JavaMethod("()Landroid/text/BidiFormatter;")

class TextDirectionHeuristics(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "android/text/TextDirectionHeuristics"
    __javaconstructor__ = [("()V", False)]
    ANYRTL_LTR = JavaStaticField("Landroid/text/TextDirectionHeuristic;")
    FIRSTSTRONG_LTR = JavaStaticField("Landroid/text/TextDirectionHeuristic;")
    FIRSTSTRONG_RTL = JavaStaticField("Landroid/text/TextDirectionHeuristic;")
    LOCALE = JavaStaticField("Landroid/text/TextDirectionHeuristic;")
    LTR = JavaStaticField("Landroid/text/TextDirectionHeuristic;")
    RTL = JavaStaticField("Landroid/text/TextDirectionHeuristic;")

class Html(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "android/text/Html"
    FROM_HTML_MODE_COMPACT = JavaStaticField("I")
    FROM_HTML_MODE_LEGACY = JavaStaticField("I")
    FROM_HTML_OPTION_USE_CSS_COLORS = JavaStaticField("I")
    FROM_HTML_SEPARATOR_LINE_BREAK_BLOCKQUOTE = JavaStaticField("I")
    FROM_HTML_SEPARATOR_LINE_BREAK_DIV = JavaStaticField("I")
    FROM_HTML_SEPARATOR_LINE_BREAK_HEADING = JavaStaticField("I")
    FROM_HTML_SEPARATOR_LINE_BREAK_LIST = JavaStaticField("I")
    FROM_HTML_SEPARATOR_LINE_BREAK_LIST_ITEM = JavaStaticField("I")
    FROM_HTML_SEPARATOR_LINE_BREAK_PARAGRAPH = JavaStaticField("I")
    TO_HTML_PARAGRAPH_LINES_CONSECUTIVE = JavaStaticField("I")
    TO_HTML_PARAGRAPH_LINES_INDIVIDUAL = JavaStaticField("I")
    toHtml = JavaMultipleMethod([("(Landroid/text/Spanned;)Ljava/lang/String;", True, False), ("(Landroid/text/Spanned;I)Ljava/lang/String;", True, False)])
    escapeHtml = JavaStaticMethod("(Ljava/lang/CharSequence;)Ljava/lang/String;")
    fromHtml = JavaMultipleMethod([("(Ljava/lang/String;I)Landroid/text/Spanned;", True, False), ("(Ljava/lang/String;ILandroid/text/Html$ImageGetter;Landroid/text/Html$TagHandler;)Landroid/text/Spanned;", True, False), ("(Ljava/lang/String;Landroid/text/Html$ImageGetter;Landroid/text/Html$TagHandler;)Landroid/text/Spanned;", True, False), ("(Ljava/lang/String;)Landroid/text/Spanned;", True, False)])

    class TagHandler(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "android/text/Html$TagHandler"
        handleTag = JavaMethod("(ZLjava/lang/String;Landroid/text/Editable;Lorg/xml/sax/XMLReader;)V")

    class ImageGetter(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "android/text/Html$ImageGetter"
        getDrawable = JavaMethod("(Ljava/lang/String;)Landroid/graphics/drawable/Drawable;")

class Annotation(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "android/text/Annotation"
    __javaconstructor__ = [("(Landroid/os/Parcel;)V", False), ("(Ljava/lang/String;Ljava/lang/String;)V", False)]
    CONTENTS_FILE_DESCRIPTOR = JavaStaticField("I")
    PARCELABLE_WRITE_RETURN_VALUE = JavaStaticField("I")
    getValue = JavaMethod("()Ljava/lang/String;")
    getKey = JavaMethod("()Ljava/lang/String;")
    describeContents = JavaMethod("()I")
    writeToParcel = JavaMethod("(Landroid/os/Parcel;I)V")
    getSpanTypeId = JavaMethod("()I")

class TextPaint(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "android/text/TextPaint"
    __javaconstructor__ = [("(I)V", False), ("(Landroid/graphics/Paint;)V", False), ("()V", False)]
    baselineShift = JavaField("I")
    bgColor = JavaField("I")
    density = JavaField("F")
    drawableState = JavaField("[I")
    linkColor = JavaField("I")
    underlineColor = JavaField("I")
    underlineThickness = JavaField("F")
    ANTI_ALIAS_FLAG = JavaStaticField("I")
    CURSOR_AFTER = JavaStaticField("I")
    CURSOR_AT = JavaStaticField("I")
    CURSOR_AT_OR_AFTER = JavaStaticField("I")
    CURSOR_AT_OR_BEFORE = JavaStaticField("I")
    CURSOR_BEFORE = JavaStaticField("I")
    DEV_KERN_TEXT_FLAG = JavaStaticField("I")
    DITHER_FLAG = JavaStaticField("I")
    EMBEDDED_BITMAP_TEXT_FLAG = JavaStaticField("I")
    END_HYPHEN_EDIT_INSERT_ARMENIAN_HYPHEN = JavaStaticField("I")
    END_HYPHEN_EDIT_INSERT_HYPHEN = JavaStaticField("I")
    END_HYPHEN_EDIT_INSERT_MAQAF = JavaStaticField("I")
    END_HYPHEN_EDIT_INSERT_UCAS_HYPHEN = JavaStaticField("I")
    END_HYPHEN_EDIT_INSERT_ZWJ_AND_HYPHEN = JavaStaticField("I")
    END_HYPHEN_EDIT_NO_EDIT = JavaStaticField("I")
    END_HYPHEN_EDIT_REPLACE_WITH_HYPHEN = JavaStaticField("I")
    FAKE_BOLD_TEXT_FLAG = JavaStaticField("I")
    FILTER_BITMAP_FLAG = JavaStaticField("I")
    HINTING_OFF = JavaStaticField("I")
    HINTING_ON = JavaStaticField("I")
    LINEAR_TEXT_FLAG = JavaStaticField("I")
    START_HYPHEN_EDIT_INSERT_HYPHEN = JavaStaticField("I")
    START_HYPHEN_EDIT_INSERT_ZWJ = JavaStaticField("I")
    START_HYPHEN_EDIT_NO_EDIT = JavaStaticField("I")
    STRIKE_THRU_TEXT_FLAG = JavaStaticField("I")
    SUBPIXEL_TEXT_FLAG = JavaStaticField("I")
    TEXT_RUN_FLAG_LEFT_EDGE = JavaStaticField("I")
    TEXT_RUN_FLAG_RIGHT_EDGE = JavaStaticField("I")
    UNDERLINE_TEXT_FLAG = JavaStaticField("I")
    VERTICAL_TEXT_FLAG = JavaStaticField("I")
    set = JavaMethod("(Landroid/text/TextPaint;)V")
    getUnderlineThickness = JavaMethod("()F")

class SpannableStringBuilder(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "android/text/SpannableStringBuilder"
    __javaconstructor__ = [("()V", False), ("(Ljava/lang/CharSequence;II)V", False), ("(Ljava/lang/CharSequence;)V", False)]
    SPAN_COMPOSING = JavaStaticField("I")
    SPAN_EXCLUSIVE_EXCLUSIVE = JavaStaticField("I")
    SPAN_EXCLUSIVE_INCLUSIVE = JavaStaticField("I")
    SPAN_INCLUSIVE_EXCLUSIVE = JavaStaticField("I")
    SPAN_INCLUSIVE_INCLUSIVE = JavaStaticField("I")
    SPAN_INTERMEDIATE = JavaStaticField("I")
    SPAN_MARK_MARK = JavaStaticField("I")
    SPAN_MARK_POINT = JavaStaticField("I")
    SPAN_PARAGRAPH = JavaStaticField("I")
    SPAN_POINT_MARK = JavaStaticField("I")
    SPAN_POINT_MARK_MASK = JavaStaticField("I")
    SPAN_POINT_POINT = JavaStaticField("I")
    SPAN_PRIORITY = JavaStaticField("I")
    SPAN_PRIORITY_SHIFT = JavaStaticField("I")
    SPAN_USER = JavaStaticField("I")
    SPAN_USER_SHIFT = JavaStaticField("I")
    getTextWatcherDepth = JavaMethod("()I")
    equals = JavaMethod("(Ljava/lang/Object;)Z")
    length = JavaMethod("()I")
    toString = JavaMethod("()Ljava/lang/String;")
    append = JavaMultipleMethod([("(C)Landroid/text/Editable;", False, False), ("(Ljava/lang/CharSequence;)Ljava/lang/Appendable;", False, False), ("(Ljava/lang/CharSequence;II)Landroid/text/Editable;", False, False), ("(C)Ljava/lang/Appendable;", False, False), ("(Ljava/lang/CharSequence;II)Ljava/lang/Appendable;", False, False), ("(Ljava/lang/CharSequence;)Landroid/text/Editable;", False, False), ("(C)Landroid/text/SpannableStringBuilder;", False, False), ("(Ljava/lang/CharSequence;Ljava/lang/Object;I)Landroid/text/SpannableStringBuilder;", False, False), ("(Ljava/lang/CharSequence;II)Landroid/text/SpannableStringBuilder;", False, False), ("(Ljava/lang/CharSequence;)Landroid/text/SpannableStringBuilder;", False, False)])
    hashCode = JavaMethod("()I")
    getChars = JavaMethod("(II[CI)V")
    insert = JavaMultipleMethod([("(ILjava/lang/CharSequence;II)Landroid/text/SpannableStringBuilder;", False, False), ("(ILjava/lang/CharSequence;II)Landroid/text/Editable;", False, False), ("(ILjava/lang/CharSequence;)Landroid/text/Editable;", False, False), ("(ILjava/lang/CharSequence;)Landroid/text/SpannableStringBuilder;", False, False)])
    valueOf = JavaStaticMethod("(Ljava/lang/CharSequence;)Landroid/text/SpannableStringBuilder;")
    clear = JavaMethod("()V")
    charAt = JavaMethod("(I)C")
    replace = JavaMultipleMethod([("(IILjava/lang/CharSequence;II)Landroid/text/Editable;", False, False), ("(IILjava/lang/CharSequence;)Landroid/text/Editable;", False, False), ("(IILjava/lang/CharSequence;II)Landroid/text/SpannableStringBuilder;", False, False), ("(IILjava/lang/CharSequence;)Landroid/text/SpannableStringBuilder;", False, False)])
    subSequence = JavaMethod("(II)Ljava/lang/CharSequence;")
    delete = JavaMultipleMethod([("(II)Landroid/text/SpannableStringBuilder;", False, False), ("(II)Landroid/text/Editable;", False, False)])
    clearSpans = JavaMethod("()V")
    removeSpan = JavaMethod("(Ljava/lang/Object;)V")
    setSpan = JavaMethod("(Ljava/lang/Object;III)V")
    getSpanEnd = JavaMethod("(Ljava/lang/Object;)I")
    getSpanFlags = JavaMethod("(Ljava/lang/Object;)I")
    getSpanStart = JavaMethod("(Ljava/lang/Object;)I")
    nextSpanTransition = JavaMethod("(IILjava/lang/Class;)I")
    getTextRunCursor = JavaMethod("(IIIIILandroid/graphics/Paint;)I")
    getSpans = JavaMethod("(IILjava/lang/Class;)[Ljava/lang/Object;")
    getFilters = JavaMethod("()[Landroid/text/InputFilter;")
    setFilters = JavaMethod("([Landroid/text/InputFilter;)V")

class AndroidCharacter(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "android/text/AndroidCharacter"
    __javaconstructor__ = [("()V", False)]
    EAST_ASIAN_WIDTH_AMBIGUOUS = JavaStaticField("I")
    EAST_ASIAN_WIDTH_FULL_WIDTH = JavaStaticField("I")
    EAST_ASIAN_WIDTH_HALF_WIDTH = JavaStaticField("I")
    EAST_ASIAN_WIDTH_NARROW = JavaStaticField("I")
    EAST_ASIAN_WIDTH_NEUTRAL = JavaStaticField("I")
    EAST_ASIAN_WIDTH_WIDE = JavaStaticField("I")
    mirror = JavaStaticMethod("([CII)Z")
    getDirectionalities = JavaStaticMethod("([C[BI)V")
    getEastAsianWidth = JavaStaticMethod("(C)I")
    getEastAsianWidths = JavaStaticMethod("([CII[B)V")
    getMirror = JavaStaticMethod("(C)C")