from typing import Any, ClassVar, overload
from java.util.function.Predicate import Predicate
from java.util.regex.Matcher import Matcher
from java.util.stream.Stream import Stream

class Pattern:
    UNIX_LINES: ClassVar[int]
    CASE_INSENSITIVE: ClassVar[int]
    COMMENTS: ClassVar[int]
    MULTILINE: ClassVar[int]
    LITERAL: ClassVar[int]
    DOTALL: ClassVar[int]
    UNICODE_CASE: ClassVar[int]
    CANON_EQ: ClassVar[int]
    UNICODE_CHARACTER_CLASS: ClassVar[int]
    def asPredicate(self) -> Predicate: ...
    def namedGroups(self) -> dict: ...
    def asMatchPredicate(self) -> Predicate: ...
    def splitAsStream(self, p0: str) -> Stream: ...
    @staticmethod
    def quote(p0: str) -> str: ...
    def toString(self) -> str: ...
    def flags(self) -> int: ...
    @staticmethod
    def matches(p0: str, p1: str) -> bool: ...
    @overload
    @staticmethod
    def compile(p0: str, p1: int) -> "Pattern": ...
    @overload
    @staticmethod
    def compile(p0: str) -> "Pattern": ...
    def matcher(self, p0: str) -> Matcher: ...
    @overload
    def split(self, p0: str) -> Any: ...
    @overload
    def split(self, p0: str, p1: int) -> Any: ...
    def splitWithDelimiters(self, p0: str, p1: int) -> Any: ...
    def pattern(self) -> str: ...
