from typing import Any, ClassVar, overload
from android.adservices.common.AdFilters import AdFilters
from android.net.Uri import Uri
from android.os.Parcel import Parcel

class AdData:
    CREATOR: ClassVar[Any]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    def getAdCounterKeys(self) -> set: ...
    def getAdRenderId(self) -> str: ...
    def getAdFilters(self) -> AdFilters: ...
    def getRenderUri(self) -> Uri: ...
    def equals(self, p0: Any) -> bool: ...
    def toString(self) -> str: ...
    def hashCode(self) -> int: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
    def describeContents(self) -> int: ...
    def getMetadata(self) -> str: ...

    class Builder:
        def __init__(self) -> None: ...
        def setRenderUri(self, p0: Uri) -> Any: ...
        def build(self) -> "AdData": ...
        def setMetadata(self, p0: str) -> Any: ...
        def setAdRenderId(self, p0: str) -> Any: ...
        def setAdFilters(self, p0: AdFilters) -> Any: ...
        def setAdCounterKeys(self, p0: set) -> Any: ...
