from typing import Any, ClassVar, overload

class RelativeFrameTimeHistogram:
    def __init__(self) -> None: ...
    def getBucketCounters(self) -> Any: ...
    def getBucketEndpointsMillis(self) -> Any: ...
    def addRelativeFrameTimeMillis(self, p0: int) -> None: ...
