from typing import Any, ClassVar, overload

class BlackLevelPattern:
    COUNT: ClassVar[int]
    def __init__(self, p0: Any) -> None: ...
    def getOffsetForIndex(self, p0: int, p1: int) -> int: ...
    def copyTo(self, p0: Any, p1: int) -> None: ...
    def equals(self, p0: Any) -> bool: ...
    def toString(self) -> str: ...
    def hashCode(self) -> int: ...
