from typing import Any, ClassVar, overload

class MandatoryStreamCombination:
    def isReprocessable(self) -> bool: ...
    def getStreamsInformation(self) -> list: ...
    def getDescription(self) -> str: ...
    def equals(self, p0: Any) -> bool: ...
    def hashCode(self) -> int: ...

    class MandatoryStreamInformation:
        def getStreamUseCase(self) -> int: ...
        def isInput(self) -> bool: ...
        def isUltraHighResolution(self) -> bool: ...
        def isMaximumSize(self) -> bool: ...
        def is10BitCapable(self) -> bool: ...
        def getAvailableSizes(self) -> list: ...
        def get10BitFormat(self) -> int: ...
        def getFormat(self) -> int: ...
        def equals(self, p0: Any) -> bool: ...
        def hashCode(self) -> int: ...
