from typing import Any, ClassVar, overload
from android.os.Parcel import Parcel

class GetValueRequest:
    CREATOR: ClassVar[Any]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    def getScreenKey(self) -> str: ...
    def getPreferenceKey(self) -> str: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
    def describeContents(self) -> int: ...

    class Builder:
        def __init__(self, p0: str, p1: str) -> None: ...
        def build(self) -> "GetValueRequest": ...
