from typing import Any, ClassVar, overload
from android.content.ComponentName import ComponentName
from android.os.Parcel import Parcel

class ChooserResult:
    CHOOSER_RESULT_COPY: ClassVar[int]
    CHOOSER_RESULT_EDIT: ClassVar[int]
    CHOOSER_RESULT_SELECTED_COMPONENT: ClassVar[int]
    CHOOSER_RESULT_UNKNOWN: ClassVar[int]
    CREATOR: ClassVar[Any]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    def isShortcut(self) -> bool: ...
    def getSelectedComponent(self) -> ComponentName: ...
    def equals(self, p0: Any) -> bool: ...
    def hashCode(self) -> int: ...
    def getType(self) -> int: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
    def describeContents(self) -> int: ...
