from typing import Any, ClassVar, overload

class CancellationSignal:
    def __init__(self) -> None: ...
    def cancel(self) -> None: ...
    def throwIfCanceled(self) -> None: ...
    def setOnCancelListener(self, p0: Any) -> None: ...
    def isCanceled(self) -> bool: ...

    class OnCancelListener:
        def onCancel(self) -> None: ...
