from typing import Any, ClassVar, overload
from android.os.MessageQueue import MessageQueue
from android.util.Printer import Printer
from java.lang.Thread import Thread

class Looper:
    def getThread(self) -> Thread: ...
    @staticmethod
    def myLooper() -> "Looper": ...
    @staticmethod
    def myQueue() -> MessageQueue: ...
    @staticmethod
    def prepareMainLooper() -> None: ...
    def quit(self) -> None: ...
    def isCurrentThread(self) -> bool: ...
    def quitSafely(self) -> None: ...
    def setMessageLogging(self, p0: Printer) -> None: ...
    def toString(self) -> str: ...
    def getQueue(self) -> MessageQueue: ...
    def dump(self, p0: Printer, p1: str) -> None: ...
    @staticmethod
    def prepare() -> None: ...
    @staticmethod
    def loop() -> None: ...
    @staticmethod
    def getMainLooper() -> "Looper": ...
