from typing import Any, ClassVar, overload

class Trace:
    @staticmethod
    def isEnabled() -> bool: ...
    @staticmethod
    def endSection() -> None: ...
    @staticmethod
    def setCounter(p0: str, p1: int) -> None: ...
    @staticmethod
    def beginSection(p0: str) -> None: ...
    @staticmethod
    def beginAsyncSection(p0: str, p1: int) -> None: ...
    @staticmethod
    def endAsyncSection(p0: str, p1: int) -> None: ...
