from typing import Any, ClassVar, overload
from android.adservices.adselection.AdSelectionConfig import AdSelectionConfig
from android.adservices.adselection.PerBuyerDecisionLogic import PerBuyerDecisionLogic
from android.adservices.common.AdSelectionSignals import AdSelectionSignals

class AddAdSelectionOverrideRequest:
    @overload
    def __init__(self, p0: AdSelectionConfig, p1: str, p2: AdSelectionSignals) -> None: ...
    @overload
    def __init__(self, p0: AdSelectionConfig, p1: str, p2: AdSelectionSignals, p3: PerBuyerDecisionLogic) -> None: ...
    def getTrustedScoringSignals(self) -> AdSelectionSignals: ...
    def getDecisionLogicJs(self) -> str: ...
    def getPerBuyerDecisionLogic(self) -> PerBuyerDecisionLogic: ...
    def getAdSelectionConfig(self) -> AdSelectionConfig: ...
