from typing import Any, ClassVar, overload
from android.os.Parcel import Parcel

class PerBuyerDecisionLogic:
    CREATOR: ClassVar[Any]
    EMPTY: ClassVar["PerBuyerDecisionLogic"]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    def __init__(self, p0: dict) -> None: ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
    def getPerBuyerLogicMap(self) -> dict: ...
    def equals(self, p0: Any) -> bool: ...
    def hashCode(self) -> int: ...
