from jnius import JavaClass, MetaJavaClass, JavaMethod, JavaStaticMethod, JavaMultipleMethod, JavaField, JavaStaticField

__all__ = ["WifiP2pConfig"]

class WifiP2pConfig(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "android/net/wifi/p2p/WifiP2pConfig"
    __javaconstructor__ = [("(Landroid/net/wifi/p2p/WifiP2pConfig;)V", False), ("()V", False)]
    CREATOR = JavaStaticField("Landroid/os/Parcelable$Creator;")
    GROUP_CLIENT_IP_PROVISIONING_MODE_IPV4_DHCP = JavaStaticField("I")
    GROUP_CLIENT_IP_PROVISIONING_MODE_IPV6_LINK_LOCAL = JavaStaticField("I")
    GROUP_OWNER_BAND_2GHZ = JavaStaticField("I")
    GROUP_OWNER_BAND_5GHZ = JavaStaticField("I")
    GROUP_OWNER_BAND_6GHZ = JavaStaticField("I")
    GROUP_OWNER_BAND_AUTO = JavaStaticField("I")
    GROUP_OWNER_INTENT_AUTO = JavaStaticField("I")
    GROUP_OWNER_INTENT_MAX = JavaStaticField("I")
    GROUP_OWNER_INTENT_MIN = JavaStaticField("I")
    P2P_VERSION_1 = JavaStaticField("I")
    P2P_VERSION_2 = JavaStaticField("I")
    PCC_MODE_CONNECTION_TYPE_LEGACY_ONLY = JavaStaticField("I")
    PCC_MODE_CONNECTION_TYPE_LEGACY_OR_R2 = JavaStaticField("I")
    PCC_MODE_CONNECTION_TYPE_R2_ONLY = JavaStaticField("I")
    deviceAddress = JavaField("Ljava/lang/String;")
    groupOwnerIntent = JavaField("I")
    wps = JavaField("Landroid/net/wifi/WpsInfo;")
    CONTENTS_FILE_DESCRIPTOR = JavaStaticField("I")
    PARCELABLE_WRITE_RETURN_VALUE = JavaStaticField("I")
    getNetworkName = JavaMethod("()Ljava/lang/String;")
    getPassphrase = JavaMethod("()Ljava/lang/String;")
    getGroupOwnerBand = JavaMethod("()I")
    getGroupClientIpProvisioningMode = JavaMethod("()I")
    getGroupOwnerVersion = JavaMethod("()I")
    getPairingBootstrappingConfig = JavaMethod("()Landroid/net/wifi/p2p/WifiP2pPairingBootstrappingConfig;")
    getPccModeConnectionType = JavaMethod("()I")
    isAuthorizeConnectionFromPeerEnabled = JavaMethod("()Z")
    setGroupOwnerVersion = JavaMethod("(I)V")
    toString = JavaMethod("()Ljava/lang/String;")
    getNetworkId = JavaMethod("()I")
    writeToParcel = JavaMethod("(Landroid/os/Parcel;I)V")
    describeContents = JavaMethod("()I")

    class Builder(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "android/net/wifi/p2p/WifiP2pConfig$Builder"
        __javaconstructor__ = [("()V", False)]
        setPassphrase = JavaMethod("(Ljava/lang/String;)Landroid/net/wifi/p2p/WifiP2pConfig$Builder;")
        setNetworkName = JavaMethod("(Ljava/lang/String;)Landroid/net/wifi/p2p/WifiP2pConfig$Builder;")
        enablePersistentMode = JavaMethod("(Z)Landroid/net/wifi/p2p/WifiP2pConfig$Builder;")
        setAuthorizeConnectionFromPeerEnabled = JavaMethod("(Z)Landroid/net/wifi/p2p/WifiP2pConfig$Builder;")
        setGroupClientIpProvisioningMode = JavaMethod("(I)Landroid/net/wifi/p2p/WifiP2pConfig$Builder;")
        setGroupOperatingBand = JavaMethod("(I)Landroid/net/wifi/p2p/WifiP2pConfig$Builder;")
        setGroupOperatingFrequency = JavaMethod("(I)Landroid/net/wifi/p2p/WifiP2pConfig$Builder;")
        setPairingBootstrappingConfig = JavaMethod("(Landroid/net/wifi/p2p/WifiP2pPairingBootstrappingConfig;)Landroid/net/wifi/p2p/WifiP2pConfig$Builder;")
        setPccModeConnectionType = JavaMethod("(I)Landroid/net/wifi/p2p/WifiP2pConfig$Builder;")
        build = JavaMethod("()Landroid/net/wifi/p2p/WifiP2pConfig;")
        setDeviceAddress = JavaMethod("(Landroid/net/MacAddress;)Landroid/net/wifi/p2p/WifiP2pConfig$Builder;")