from typing import Any, ClassVar, overload

class QName:
    @overload
    def __init__(self, p0: str) -> None: ...
    @overload
    def __init__(self, p0: str, p1: str, p2: str) -> None: ...
    @overload
    def __init__(self, p0: str, p1: str) -> None: ...
    def equals(self, p0: Any) -> bool: ...
    def toString(self) -> str: ...
    def hashCode(self) -> int: ...
    @staticmethod
    def valueOf(p0: str) -> "QName": ...
    def getNamespaceURI(self) -> str: ...
    def getLocalPart(self) -> str: ...
    def getPrefix(self) -> str: ...

from typing import Any, ClassVar, overload
from java.util.Iterator import Iterator

class NamespaceContext:
    def getNamespaceURI(self, p0: str) -> str: ...
    def getPrefix(self, p0: str) -> str: ...
    def getPrefixes(self, p0: str) -> Iterator: ...

