from typing import Any, ClassVar, overload
from java.lang.ClassLoader import ClassLoader
from javax.xml.parsers.SAXParser import SAXParser
from javax.xml.validation.Schema import Schema

class SAXParserFactory:
    def getSchema(self) -> Schema: ...
    def setSchema(self, p0: Schema) -> None: ...
    @overload
    @staticmethod
    def newInstance(p0: str, p1: ClassLoader) -> "SAXParserFactory": ...
    @overload
    @staticmethod
    def newInstance() -> "SAXParserFactory": ...
    @staticmethod
    def newDefaultInstance() -> "SAXParserFactory": ...
    def getFeature(self, p0: str) -> bool: ...
    def setFeature(self, p0: str, p1: bool) -> None: ...
    def setNamespaceAware(self, p0: bool) -> None: ...
    @staticmethod
    def newDefaultNSInstance() -> "SAXParserFactory": ...
    @overload
    @staticmethod
    def newNSInstance() -> "SAXParserFactory": ...
    @overload
    @staticmethod
    def newNSInstance(p0: str, p1: ClassLoader) -> "SAXParserFactory": ...
    def newSAXParser(self) -> SAXParser: ...
    def setValidating(self, p0: bool) -> None: ...
    def isNamespaceAware(self) -> bool: ...
    def isValidating(self) -> bool: ...
    def setXIncludeAware(self, p0: bool) -> None: ...
    def isXIncludeAware(self) -> bool: ...

from typing import Any, ClassVar, overload
from java.io.File import File
from java.io.InputStream import InputStream
from javax.xml.validation.Schema import Schema
from org.xml.sax.HandlerBase import HandlerBase
from org.xml.sax.InputSource import InputSource
from org.xml.sax.Parser import Parser
from org.xml.sax.XMLReader import XMLReader
from org.xml.sax.helpers.DefaultHandler import DefaultHandler

class SAXParser:
    def getSchema(self) -> Schema: ...
    def reset(self) -> None: ...
    def getProperty(self, p0: str) -> Any: ...
    def setProperty(self, p0: str, p1: Any) -> None: ...
    @overload
    def parse(self, p0: File, p1: HandlerBase) -> None: ...
    @overload
    def parse(self, p0: File, p1: DefaultHandler) -> None: ...
    @overload
    def parse(self, p0: InputSource, p1: HandlerBase) -> None: ...
    @overload
    def parse(self, p0: InputSource, p1: DefaultHandler) -> None: ...
    @overload
    def parse(self, p0: InputStream, p1: DefaultHandler) -> None: ...
    @overload
    def parse(self, p0: InputStream, p1: HandlerBase, p2: str) -> None: ...
    @overload
    def parse(self, p0: InputStream, p1: HandlerBase) -> None: ...
    @overload
    def parse(self, p0: InputStream, p1: DefaultHandler, p2: str) -> None: ...
    @overload
    def parse(self, p0: str, p1: HandlerBase) -> None: ...
    @overload
    def parse(self, p0: str, p1: DefaultHandler) -> None: ...
    def isNamespaceAware(self) -> bool: ...
    def isValidating(self) -> bool: ...
    def isXIncludeAware(self) -> bool: ...
    def getParser(self) -> Parser: ...
    def getXMLReader(self) -> XMLReader: ...

from typing import Any, ClassVar, overload
from java.lang.Exception import Exception
from java.lang.Throwable import Throwable

class FactoryConfigurationError:
    @overload
    def __init__(self, p0: Exception, p1: str) -> None: ...
    @overload
    def __init__(self, p0: Exception) -> None: ...
    @overload
    def __init__(self, p0: str) -> None: ...
    @overload
    def __init__(self) -> None: ...
    def getCause(self) -> Throwable: ...
    def getMessage(self) -> str: ...
    def getException(self) -> Exception: ...

from typing import Any, ClassVar, overload
from java.lang.ClassLoader import ClassLoader
from javax.xml.parsers.DocumentBuilder import DocumentBuilder
from javax.xml.validation.Schema import Schema

class DocumentBuilderFactory:
    def getSchema(self) -> Schema: ...
    def setSchema(self, p0: Schema) -> None: ...
    @overload
    @staticmethod
    def newInstance(p0: str, p1: ClassLoader) -> "DocumentBuilderFactory": ...
    @overload
    @staticmethod
    def newInstance() -> "DocumentBuilderFactory": ...
    def setAttribute(self, p0: str, p1: Any) -> None: ...
    @staticmethod
    def newDefaultInstance() -> "DocumentBuilderFactory": ...
    def getFeature(self, p0: str) -> bool: ...
    def setFeature(self, p0: str, p1: bool) -> None: ...
    def getAttribute(self, p0: str) -> Any: ...
    def setNamespaceAware(self, p0: bool) -> None: ...
    @staticmethod
    def newDefaultNSInstance() -> "DocumentBuilderFactory": ...
    @overload
    @staticmethod
    def newNSInstance() -> "DocumentBuilderFactory": ...
    @overload
    @staticmethod
    def newNSInstance(p0: str, p1: ClassLoader) -> "DocumentBuilderFactory": ...
    def setValidating(self, p0: bool) -> None: ...
    def isNamespaceAware(self) -> bool: ...
    def isValidating(self) -> bool: ...
    def setXIncludeAware(self, p0: bool) -> None: ...
    def isXIncludeAware(self) -> bool: ...
    def newDocumentBuilder(self) -> DocumentBuilder: ...
    def setIgnoringElementContentWhitespace(self, p0: bool) -> None: ...
    def setExpandEntityReferences(self, p0: bool) -> None: ...
    def setIgnoringComments(self, p0: bool) -> None: ...
    def setCoalescing(self, p0: bool) -> None: ...
    def isIgnoringElementContentWhitespace(self) -> bool: ...
    def isExpandEntityReferences(self) -> bool: ...
    def isIgnoringComments(self) -> bool: ...
    def isCoalescing(self) -> bool: ...

from typing import Any, ClassVar, overload

class ParserConfigurationException:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, p0: str) -> None: ...

from typing import Any, ClassVar, overload
from java.io.File import File
from java.io.InputStream import InputStream
from javax.xml.validation.Schema import Schema
from org.w3c.dom.DOMImplementation import DOMImplementation
from org.w3c.dom.Document import Document
from org.xml.sax.EntityResolver import EntityResolver
from org.xml.sax.ErrorHandler import ErrorHandler
from org.xml.sax.InputSource import InputSource

class DocumentBuilder:
    def setErrorHandler(self, p0: ErrorHandler) -> None: ...
    def getSchema(self) -> Schema: ...
    def reset(self) -> None: ...
    @overload
    def parse(self, p0: str) -> Document: ...
    @overload
    def parse(self, p0: InputSource) -> Document: ...
    @overload
    def parse(self, p0: File) -> Document: ...
    @overload
    def parse(self, p0: InputStream) -> Document: ...
    @overload
    def parse(self, p0: InputStream, p1: str) -> Document: ...
    def isNamespaceAware(self) -> bool: ...
    def isValidating(self) -> bool: ...
    def isXIncludeAware(self) -> bool: ...
    def newDocument(self) -> Document: ...
    def getDOMImplementation(self) -> DOMImplementation: ...
    def setEntityResolver(self, p0: EntityResolver) -> None: ...

