from typing import Any, ClassVar, overload
from java.time.Instant import Instant
from java.util.concurrent.TimeUnit import TimeUnit

class FileTime:
    def equals(self, p0: Any) -> bool: ...
    def toString(self) -> str: ...
    def hashCode(self) -> int: ...
    @overload
    def compareTo(self, p0: "FileTime") -> int: ...
    @overload
    def compareTo(self, p0: Any) -> int: ...
    @overload
    @staticmethod
    def from_(p0: Instant) -> "FileTime": ...
    @overload
    @staticmethod
    def from_(p0: int, p1: TimeUnit) -> "FileTime": ...
    def to(self, p0: TimeUnit) -> int: ...
    def toMillis(self) -> int: ...
    def toInstant(self) -> Instant: ...
    @staticmethod
    def fromMillis(p0: int) -> "FileTime": ...
