from typing import Any, ClassVar, overload
from java.nio.file.attribute.BasicFileAttributes import BasicFileAttributes
from java.nio.file.attribute.GroupPrincipal import GroupPrincipal
from java.nio.file.attribute.PosixFileAttributes import PosixFileAttributes

class PosixFileAttributeView:
    def setGroup(self, p0: GroupPrincipal) -> None: ...
    def name(self) -> str: ...
    def setPermissions(self, p0: set) -> None: ...
    @overload
    def readAttributes(self) -> PosixFileAttributes: ...
    @overload
    def readAttributes(self) -> BasicFileAttributes: ...
