from typing import Any, ClassVar, overload
from android.content.Context import Context
from android.content.Intent import Intent
from android.graphics.Canvas import Canvas
from android.graphics.Rect import Rect
from android.graphics.drawable.Drawable import Drawable
from android.os.Parcelable import Parcelable
from android.text.Editable import Editable
from android.util.AttributeSet import AttributeSet
from android.util.Property import Property
from android.util.SparseBooleanArray import SparseBooleanArray
from android.view.ActionMode import ActionMode
from android.view.KeyEvent import KeyEvent
from android.view.MotionEvent import MotionEvent
from android.view.PointerIcon import PointerIcon
from android.view.View import View
from android.view.ViewStructure import ViewStructure
from android.view.accessibility.AccessibilityNodeInfo import AccessibilityNodeInfo
from android.view.inputmethod.EditorInfo import EditorInfo
from android.view.inputmethod.InputConnection import InputConnection
from android.widget.Adapter import Adapter
from android.widget.ListAdapter import ListAdapter

class AbsListView:
    CHOICE_MODE_MULTIPLE: ClassVar[int]
    CHOICE_MODE_MULTIPLE_MODAL: ClassVar[int]
    CHOICE_MODE_NONE: ClassVar[int]
    CHOICE_MODE_SINGLE: ClassVar[int]
    TRANSCRIPT_MODE_ALWAYS_SCROLL: ClassVar[int]
    TRANSCRIPT_MODE_DISABLED: ClassVar[int]
    TRANSCRIPT_MODE_NORMAL: ClassVar[int]
    INVALID_POSITION: ClassVar[int]
    INVALID_ROW_ID: ClassVar[int]
    ITEM_VIEW_TYPE_HEADER_OR_FOOTER: ClassVar[int]
    ITEM_VIEW_TYPE_IGNORE: ClassVar[int]
    FOCUS_AFTER_DESCENDANTS: ClassVar[int]
    FOCUS_BEFORE_DESCENDANTS: ClassVar[int]
    FOCUS_BLOCK_DESCENDANTS: ClassVar[int]
    LAYOUT_MODE_CLIP_BOUNDS: ClassVar[int]
    LAYOUT_MODE_OPTICAL_BOUNDS: ClassVar[int]
    PERSISTENT_ALL_CACHES: ClassVar[int]
    PERSISTENT_ANIMATION_CACHE: ClassVar[int]
    PERSISTENT_NO_CACHE: ClassVar[int]
    PERSISTENT_SCROLLING_CACHE: ClassVar[int]
    ACCESSIBILITY_DATA_SENSITIVE_AUTO: ClassVar[int]
    ACCESSIBILITY_DATA_SENSITIVE_NO: ClassVar[int]
    ACCESSIBILITY_DATA_SENSITIVE_YES: ClassVar[int]
    ACCESSIBILITY_LIVE_REGION_ASSERTIVE: ClassVar[int]
    ACCESSIBILITY_LIVE_REGION_NONE: ClassVar[int]
    ACCESSIBILITY_LIVE_REGION_POLITE: ClassVar[int]
    ALPHA: ClassVar[Property]
    AUTOFILL_FLAG_INCLUDE_NOT_IMPORTANT_VIEWS: ClassVar[int]
    AUTOFILL_HINT_CREDIT_CARD_EXPIRATION_DATE: ClassVar[str]
    AUTOFILL_HINT_CREDIT_CARD_EXPIRATION_DAY: ClassVar[str]
    AUTOFILL_HINT_CREDIT_CARD_EXPIRATION_MONTH: ClassVar[str]
    AUTOFILL_HINT_CREDIT_CARD_EXPIRATION_YEAR: ClassVar[str]
    AUTOFILL_HINT_CREDIT_CARD_NUMBER: ClassVar[str]
    AUTOFILL_HINT_CREDIT_CARD_SECURITY_CODE: ClassVar[str]
    AUTOFILL_HINT_EMAIL_ADDRESS: ClassVar[str]
    AUTOFILL_HINT_NAME: ClassVar[str]
    AUTOFILL_HINT_PASSWORD: ClassVar[str]
    AUTOFILL_HINT_PHONE: ClassVar[str]
    AUTOFILL_HINT_POSTAL_ADDRESS: ClassVar[str]
    AUTOFILL_HINT_POSTAL_CODE: ClassVar[str]
    AUTOFILL_HINT_USERNAME: ClassVar[str]
    AUTOFILL_TYPE_DATE: ClassVar[int]
    AUTOFILL_TYPE_LIST: ClassVar[int]
    AUTOFILL_TYPE_NONE: ClassVar[int]
    AUTOFILL_TYPE_TEXT: ClassVar[int]
    AUTOFILL_TYPE_TOGGLE: ClassVar[int]
    CONTENT_SENSITIVITY_AUTO: ClassVar[int]
    CONTENT_SENSITIVITY_NOT_SENSITIVE: ClassVar[int]
    CONTENT_SENSITIVITY_SENSITIVE: ClassVar[int]
    DRAG_FLAG_ACCESSIBILITY_ACTION: ClassVar[int]
    DRAG_FLAG_GLOBAL: ClassVar[int]
    DRAG_FLAG_GLOBAL_PERSISTABLE_URI_PERMISSION: ClassVar[int]
    DRAG_FLAG_GLOBAL_PREFIX_URI_PERMISSION: ClassVar[int]
    DRAG_FLAG_GLOBAL_SAME_APPLICATION: ClassVar[int]
    DRAG_FLAG_GLOBAL_URI_READ: ClassVar[int]
    DRAG_FLAG_GLOBAL_URI_WRITE: ClassVar[int]
    DRAG_FLAG_OPAQUE: ClassVar[int]
    DRAG_FLAG_START_INTENT_SENDER_ON_UNHANDLED_DRAG: ClassVar[int]
    DRAWING_CACHE_QUALITY_AUTO: ClassVar[int]
    DRAWING_CACHE_QUALITY_HIGH: ClassVar[int]
    DRAWING_CACHE_QUALITY_LOW: ClassVar[int]
    FIND_VIEWS_WITH_CONTENT_DESCRIPTION: ClassVar[int]
    FIND_VIEWS_WITH_TEXT: ClassVar[int]
    FOCUSABLE: ClassVar[int]
    FOCUSABLES_ALL: ClassVar[int]
    FOCUSABLES_TOUCH_MODE: ClassVar[int]
    FOCUSABLE_AUTO: ClassVar[int]
    FOCUS_BACKWARD: ClassVar[int]
    FOCUS_DOWN: ClassVar[int]
    FOCUS_FORWARD: ClassVar[int]
    FOCUS_LEFT: ClassVar[int]
    FOCUS_RIGHT: ClassVar[int]
    FOCUS_UP: ClassVar[int]
    GONE: ClassVar[int]
    HAPTIC_FEEDBACK_ENABLED: ClassVar[int]
    IMPORTANT_FOR_ACCESSIBILITY_AUTO: ClassVar[int]
    IMPORTANT_FOR_ACCESSIBILITY_NO: ClassVar[int]
    IMPORTANT_FOR_ACCESSIBILITY_NO_HIDE_DESCENDANTS: ClassVar[int]
    IMPORTANT_FOR_ACCESSIBILITY_YES: ClassVar[int]
    IMPORTANT_FOR_AUTOFILL_AUTO: ClassVar[int]
    IMPORTANT_FOR_AUTOFILL_NO: ClassVar[int]
    IMPORTANT_FOR_AUTOFILL_NO_EXCLUDE_DESCENDANTS: ClassVar[int]
    IMPORTANT_FOR_AUTOFILL_YES: ClassVar[int]
    IMPORTANT_FOR_AUTOFILL_YES_EXCLUDE_DESCENDANTS: ClassVar[int]
    IMPORTANT_FOR_CONTENT_CAPTURE_AUTO: ClassVar[int]
    IMPORTANT_FOR_CONTENT_CAPTURE_NO: ClassVar[int]
    IMPORTANT_FOR_CONTENT_CAPTURE_NO_EXCLUDE_DESCENDANTS: ClassVar[int]
    IMPORTANT_FOR_CONTENT_CAPTURE_YES: ClassVar[int]
    IMPORTANT_FOR_CONTENT_CAPTURE_YES_EXCLUDE_DESCENDANTS: ClassVar[int]
    INVISIBLE: ClassVar[int]
    KEEP_SCREEN_ON: ClassVar[int]
    LAYER_TYPE_HARDWARE: ClassVar[int]
    LAYER_TYPE_NONE: ClassVar[int]
    LAYER_TYPE_SOFTWARE: ClassVar[int]
    LAYOUT_DIRECTION_INHERIT: ClassVar[int]
    LAYOUT_DIRECTION_LOCALE: ClassVar[int]
    LAYOUT_DIRECTION_LTR: ClassVar[int]
    LAYOUT_DIRECTION_RTL: ClassVar[int]
    MEASURED_HEIGHT_STATE_SHIFT: ClassVar[int]
    MEASURED_SIZE_MASK: ClassVar[int]
    MEASURED_STATE_MASK: ClassVar[int]
    MEASURED_STATE_TOO_SMALL: ClassVar[int]
    NOT_FOCUSABLE: ClassVar[int]
    NO_ID: ClassVar[int]
    OVER_SCROLL_ALWAYS: ClassVar[int]
    OVER_SCROLL_IF_CONTENT_SCROLLS: ClassVar[int]
    OVER_SCROLL_NEVER: ClassVar[int]
    REQUESTED_FRAME_RATE_CATEGORY_DEFAULT: ClassVar[float]
    REQUESTED_FRAME_RATE_CATEGORY_HIGH: ClassVar[float]
    REQUESTED_FRAME_RATE_CATEGORY_LOW: ClassVar[float]
    REQUESTED_FRAME_RATE_CATEGORY_NORMAL: ClassVar[float]
    REQUESTED_FRAME_RATE_CATEGORY_NO_PREFERENCE: ClassVar[float]
    ROTATION: ClassVar[Property]
    ROTATION_X: ClassVar[Property]
    ROTATION_Y: ClassVar[Property]
    SCALE_X: ClassVar[Property]
    SCALE_Y: ClassVar[Property]
    SCREEN_STATE_OFF: ClassVar[int]
    SCREEN_STATE_ON: ClassVar[int]
    SCROLLBARS_INSIDE_INSET: ClassVar[int]
    SCROLLBARS_INSIDE_OVERLAY: ClassVar[int]
    SCROLLBARS_OUTSIDE_INSET: ClassVar[int]
    SCROLLBARS_OUTSIDE_OVERLAY: ClassVar[int]
    SCROLLBAR_POSITION_DEFAULT: ClassVar[int]
    SCROLLBAR_POSITION_LEFT: ClassVar[int]
    SCROLLBAR_POSITION_RIGHT: ClassVar[int]
    SCROLL_AXIS_HORIZONTAL: ClassVar[int]
    SCROLL_AXIS_NONE: ClassVar[int]
    SCROLL_AXIS_VERTICAL: ClassVar[int]
    SCROLL_CAPTURE_HINT_AUTO: ClassVar[int]
    SCROLL_CAPTURE_HINT_EXCLUDE: ClassVar[int]
    SCROLL_CAPTURE_HINT_EXCLUDE_DESCENDANTS: ClassVar[int]
    SCROLL_CAPTURE_HINT_INCLUDE: ClassVar[int]
    SCROLL_INDICATOR_BOTTOM: ClassVar[int]
    SCROLL_INDICATOR_END: ClassVar[int]
    SCROLL_INDICATOR_LEFT: ClassVar[int]
    SCROLL_INDICATOR_RIGHT: ClassVar[int]
    SCROLL_INDICATOR_START: ClassVar[int]
    SCROLL_INDICATOR_TOP: ClassVar[int]
    SOUND_EFFECTS_ENABLED: ClassVar[int]
    STATUS_BAR_HIDDEN: ClassVar[int]
    STATUS_BAR_VISIBLE: ClassVar[int]
    SYSTEM_UI_FLAG_FULLSCREEN: ClassVar[int]
    SYSTEM_UI_FLAG_HIDE_NAVIGATION: ClassVar[int]
    SYSTEM_UI_FLAG_IMMERSIVE: ClassVar[int]
    SYSTEM_UI_FLAG_IMMERSIVE_STICKY: ClassVar[int]
    SYSTEM_UI_FLAG_LAYOUT_FULLSCREEN: ClassVar[int]
    SYSTEM_UI_FLAG_LAYOUT_HIDE_NAVIGATION: ClassVar[int]
    SYSTEM_UI_FLAG_LAYOUT_STABLE: ClassVar[int]
    SYSTEM_UI_FLAG_LIGHT_NAVIGATION_BAR: ClassVar[int]
    SYSTEM_UI_FLAG_LIGHT_STATUS_BAR: ClassVar[int]
    SYSTEM_UI_FLAG_LOW_PROFILE: ClassVar[int]
    SYSTEM_UI_FLAG_VISIBLE: ClassVar[int]
    SYSTEM_UI_LAYOUT_FLAGS: ClassVar[int]
    TEXT_ALIGNMENT_CENTER: ClassVar[int]
    TEXT_ALIGNMENT_GRAVITY: ClassVar[int]
    TEXT_ALIGNMENT_INHERIT: ClassVar[int]
    TEXT_ALIGNMENT_TEXT_END: ClassVar[int]
    TEXT_ALIGNMENT_TEXT_START: ClassVar[int]
    TEXT_ALIGNMENT_VIEW_END: ClassVar[int]
    TEXT_ALIGNMENT_VIEW_START: ClassVar[int]
    TEXT_DIRECTION_ANY_RTL: ClassVar[int]
    TEXT_DIRECTION_FIRST_STRONG: ClassVar[int]
    TEXT_DIRECTION_FIRST_STRONG_LTR: ClassVar[int]
    TEXT_DIRECTION_FIRST_STRONG_RTL: ClassVar[int]
    TEXT_DIRECTION_INHERIT: ClassVar[int]
    TEXT_DIRECTION_LOCALE: ClassVar[int]
    TEXT_DIRECTION_LTR: ClassVar[int]
    TEXT_DIRECTION_RTL: ClassVar[int]
    TRANSLATION_X: ClassVar[Property]
    TRANSLATION_Y: ClassVar[Property]
    TRANSLATION_Z: ClassVar[Property]
    VISIBLE: ClassVar[int]
    X: ClassVar[Property]
    Y: ClassVar[Property]
    Z: ClassVar[Property]
    @overload
    def __init__(self, p0: Context) -> None: ...
    @overload
    def __init__(self, p0: Context, p1: AttributeSet) -> None: ...
    @overload
    def __init__(self, p0: Context, p1: AttributeSet, p2: int) -> None: ...
    @overload
    def __init__(self, p0: Context, p1: AttributeSet, p2: int, p3: int) -> None: ...
    @overload
    def showContextMenuForChild(self, p0: View) -> bool: ...
    @overload
    def showContextMenuForChild(self, p0: View, p1: float, p2: float) -> bool: ...
    def onInterceptHoverEvent(self, p0: MotionEvent) -> bool: ...
    def requestDisallowInterceptTouchEvent(self, p0: bool) -> None: ...
    def onInterceptTouchEvent(self, p0: MotionEvent) -> bool: ...
    def onStartNestedScroll(self, p0: View, p1: View, p2: int) -> bool: ...
    def onNestedScrollAccepted(self, p0: View, p1: View, p2: int) -> None: ...
    def onNestedScroll(self, p0: View, p1: int, p2: int, p3: int, p4: int) -> None: ...
    def onNestedFling(self, p0: View, p1: float, p2: float, p3: bool) -> bool: ...
    def fling(self, p0: int) -> None: ...
    def setFriction(self, p0: float) -> None: ...
    def draw(self, p0: Canvas) -> None: ...
    def onResolvePointerIcon(self, p0: MotionEvent, p1: int) -> PointerIcon: ...
    def getVerticalScrollbarWidth(self) -> int: ...
    def setVerticalScrollbarPosition(self, p0: int) -> None: ...
    def setScrollIndicators(self, p0: View, p1: View) -> None: ...
    @overload
    def showContextMenu(self) -> bool: ...
    @overload
    def showContextMenu(self, p0: float, p1: float) -> bool: ...
    def onProvideContentCaptureStructure(self, p0: ViewStructure, p1: int) -> None: ...
    def addTouchables(self, p0: list) -> None: ...
    def onWindowFocusChanged(self, p0: bool) -> None: ...
    def onKeyDown(self, p0: int, p1: KeyEvent) -> bool: ...
    def onCreateInputConnection(self, p0: EditorInfo) -> InputConnection: ...
    def checkInputConnectionProxy(self, p0: View) -> bool: ...
    def onGenericMotionEvent(self, p0: MotionEvent) -> bool: ...
    def getFocusedRect(self, p0: Rect) -> None: ...
    def setScrollBarStyle(self, p0: int) -> None: ...
    def onCancelPendingInputEvents(self) -> None: ...
    def onSaveInstanceState(self) -> Parcelable: ...
    def onRestoreInstanceState(self, p0: Parcelable) -> None: ...
    def getSolidColor(self) -> int: ...
    def dispatchDrawableHotspotChanged(self, p0: float, p1: float) -> None: ...
    def requestLayout(self) -> None: ...
    def getCheckedItemCount(self) -> int: ...
    def isItemChecked(self, p0: int) -> bool: ...
    def getCheckedItemPosition(self) -> int: ...
    def getCheckedItemPositions(self) -> SparseBooleanArray: ...
    def getCheckedItemIds(self) -> Any: ...
    def clearChoices(self) -> None: ...
    def setItemChecked(self, p0: int, p1: bool) -> None: ...
    def getChoiceMode(self) -> int: ...
    def setChoiceMode(self, p0: int) -> None: ...
    def setMultiChoiceModeListener(self, p0: Any) -> None: ...
    def setFastScrollEnabled(self, p0: bool) -> None: ...
    def setFastScrollStyle(self, p0: int) -> None: ...
    def setFastScrollAlwaysVisible(self, p0: bool) -> None: ...
    def isFastScrollAlwaysVisible(self) -> bool: ...
    def isFastScrollEnabled(self) -> bool: ...
    def setSmoothScrollbarEnabled(self, p0: bool) -> None: ...
    def isSmoothScrollbarEnabled(self) -> bool: ...
    def setOnScrollListener(self, p0: Any) -> None: ...
    def isScrollingCacheEnabled(self) -> bool: ...
    def setScrollingCacheEnabled(self, p0: bool) -> None: ...
    def setTextFilterEnabled(self, p0: bool) -> None: ...
    def isTextFilterEnabled(self) -> bool: ...
    def isStackFromBottom(self) -> bool: ...
    def setStackFromBottom(self, p0: bool) -> None: ...
    def setFilterText(self, p0: str) -> None: ...
    def getTextFilter(self) -> str: ...
    def getListPaddingTop(self) -> int: ...
    def getListPaddingBottom(self) -> int: ...
    def getListPaddingLeft(self) -> int: ...
    def getListPaddingRight(self) -> int: ...
    def isSelectedChildViewEnabled(self) -> bool: ...
    def setSelectedChildViewEnabled(self, p0: bool) -> None: ...
    def setDrawSelectorOnTop(self, p0: bool) -> None: ...
    def isDrawSelectorOnTop(self) -> bool: ...
    def pointToPosition(self, p0: int, p1: int) -> int: ...
    def pointToRowId(self, p0: int, p1: int) -> int: ...
    def onTouchModeChanged(self, p0: bool) -> None: ...
    def setVelocityScale(self, p0: float) -> None: ...
    @overload
    def smoothScrollToPositionFromTop(self, p0: int, p1: int, p2: int) -> None: ...
    @overload
    def smoothScrollToPositionFromTop(self, p0: int, p1: int) -> None: ...
    def smoothScrollBy(self, p0: int, p1: int) -> None: ...
    def scrollListBy(self, p0: int) -> None: ...
    def canScrollList(self, p0: int) -> bool: ...
    def invalidateViews(self) -> None: ...
    def clearTextFilter(self) -> None: ...
    def hasTextFilter(self) -> bool: ...
    def onGlobalLayout(self) -> None: ...
    def beforeTextChanged(self, p0: str, p1: int, p2: int, p3: int) -> None: ...
    def onTextChanged(self, p0: str, p1: int, p2: int, p3: int) -> None: ...
    def afterTextChanged(self, p0: Editable) -> None: ...
    def onFilterComplete(self, p0: int) -> None: ...
    def setTranscriptMode(self, p0: int) -> None: ...
    def getTranscriptMode(self) -> int: ...
    def getCacheColorHint(self) -> int: ...
    def reclaimViews(self, p0: list) -> None: ...
    def deferNotifyDataSetChanged(self) -> None: ...
    def onRemoteAdapterConnected(self) -> bool: ...
    def onRemoteAdapterDisconnected(self) -> None: ...
    def setEdgeEffectColor(self, p0: int) -> None: ...
    def setBottomEdgeEffectColor(self, p0: int) -> None: ...
    def setTopEdgeEffectColor(self, p0: int) -> None: ...
    def getTopEdgeEffectColor(self) -> int: ...
    def getBottomEdgeEffectColor(self) -> int: ...
    def setRecyclerListener(self, p0: Any) -> None: ...
    def setSelectionFromTop(self, p0: int, p1: int) -> None: ...
    def onTouchEvent(self, p0: MotionEvent) -> bool: ...
    def onKeyUp(self, p0: int, p1: KeyEvent) -> bool: ...
    def getAccessibilityClassName(self) -> str: ...
    def verifyDrawable(self, p0: Drawable) -> bool: ...
    def jumpDrawablesToCurrentState(self) -> None: ...
    def onRtlPropertiesChanged(self, p0: int) -> None: ...
    @overload
    def smoothScrollToPosition(self, p0: int) -> None: ...
    @overload
    def smoothScrollToPosition(self, p0: int, p1: int) -> None: ...
    def setCacheColorHint(self, p0: int) -> None: ...
    def onInitializeAccessibilityNodeInfoForItem(self, p0: View, p1: int, p2: AccessibilityNodeInfo) -> None: ...
    def setRemoteViewsAdapter(self, p0: Intent) -> None: ...
    @overload
    def setAdapter(self, p0: Adapter) -> None: ...
    @overload
    def setAdapter(self, p0: ListAdapter) -> None: ...
    def performItemClick(self, p0: View, p1: int, p2: int) -> bool: ...
    def getSelectedView(self) -> View: ...
    def getSelector(self) -> Drawable: ...
    @overload
    def setSelector(self, p0: Drawable) -> None: ...
    @overload
    def setSelector(self, p0: int) -> None: ...
    @overload
    def generateLayoutParams(self, p0: AttributeSet) -> Any: ...
    @overload
    def generateLayoutParams(self, p0: AttributeSet) -> Any: ...

    class LayoutParams:
        FILL_PARENT: ClassVar[int]
        MATCH_PARENT: ClassVar[int]
        WRAP_CONTENT: ClassVar[int]
        height: int
        layoutAnimationParameters: Any
        width: int
        @overload
        def __init__(self, p0: Any) -> None: ...
        @overload
        def __init__(self, p0: int, p1: int, p2: int) -> None: ...
        @overload
        def __init__(self, p0: int, p1: int) -> None: ...
        @overload
        def __init__(self, p0: Context, p1: AttributeSet) -> None: ...

    class SelectionBoundsAdjuster:
        def adjustListItemSelectionBounds(self, p0: Rect) -> None: ...

    class RecyclerListener:
        def onMovedToScrapHeap(self, p0: View) -> None: ...

    class OnScrollListener:
        SCROLL_STATE_FLING: ClassVar[int]
        SCROLL_STATE_IDLE: ClassVar[int]
        SCROLL_STATE_TOUCH_SCROLL: ClassVar[int]
        def onScrollStateChanged(self, p0: "AbsListView", p1: int) -> None: ...
        def onScroll(self, p0: "AbsListView", p1: int, p2: int, p3: int) -> None: ...

    class MultiChoiceModeListener:
        def onItemCheckedStateChanged(self, p0: ActionMode, p1: int, p2: int, p3: bool) -> None: ...
