from typing import Any, ClassVar, overload
from android.database.DataSetObserver import DataSetObserver
from android.view.View import View
from android.view.ViewGroup import ViewGroup

class BaseAdapter:
    IGNORE_ITEM_VIEW_TYPE: ClassVar[int]
    NO_SELECTION: ClassVar[int]
    def __init__(self) -> None: ...
    def isEmpty(self) -> bool: ...
    def isEnabled(self, p0: int) -> bool: ...
    def getDropDownView(self, p0: int, p1: View, p2: ViewGroup) -> View: ...
    def areAllItemsEnabled(self) -> bool: ...
    def getAutofillOptions(self) -> Any: ...
    def getItemViewType(self, p0: int) -> int: ...
    def notifyDataSetChanged(self) -> None: ...
    def notifyDataSetInvalidated(self) -> None: ...
    def setAutofillOptions(self, p0: Any) -> None: ...
    def getViewTypeCount(self) -> int: ...
    def hasStableIds(self) -> bool: ...
    def registerDataSetObserver(self, p0: DataSetObserver) -> None: ...
    def unregisterDataSetObserver(self, p0: DataSetObserver) -> None: ...
