from typing import Any, ClassVar, overload
from android.database.DataSetObserver import DataSetObserver

class BaseExpandableListAdapter:
    def __init__(self) -> None: ...
    def notifyDataSetChanged(self) -> None: ...
    def notifyDataSetInvalidated(self) -> None: ...
    def onGroupCollapsed(self, p0: int) -> None: ...
    def areAllItemsEnabled(self) -> bool: ...
    def registerDataSetObserver(self, p0: DataSetObserver) -> None: ...
    def unregisterDataSetObserver(self, p0: DataSetObserver) -> None: ...
    def onGroupExpanded(self, p0: int) -> None: ...
    def getCombinedChildId(self, p0: int, p1: int) -> int: ...
    def getCombinedGroupId(self, p0: int) -> int: ...
    def getChildType(self, p0: int, p1: int) -> int: ...
    def getChildTypeCount(self) -> int: ...
    def getGroupType(self, p0: int) -> int: ...
    def getGroupTypeCount(self) -> int: ...
    def isEmpty(self) -> bool: ...
