from typing import Any, ClassVar, overload
from android.content.Context import Context
from android.graphics.BlendMode import BlendMode
from android.graphics.Canvas import Canvas
from android.util.AttributeSet import AttributeSet

class EdgeEffect:
    DEFAULT_BLEND_MODE: ClassVar[BlendMode]
    @overload
    def __init__(self, p0: Context) -> None: ...
    @overload
    def __init__(self, p0: Context, p1: AttributeSet) -> None: ...
    def finish(self) -> None: ...
    @overload
    def onPull(self, p0: float, p1: float) -> None: ...
    @overload
    def onPull(self, p0: float) -> None: ...
    def onAbsorb(self, p0: int) -> None: ...
    def onPullDistance(self, p0: float, p1: float) -> float: ...
    def getDistance(self) -> float: ...
    def onRelease(self) -> None: ...
    def getMaxHeight(self) -> int: ...
    def isFinished(self) -> bool: ...
    def setBlendMode(self, p0: BlendMode) -> None: ...
    def setColor(self, p0: int) -> None: ...
    def draw(self, p0: Canvas) -> bool: ...
    def getColor(self) -> int: ...
    def getBlendMode(self) -> BlendMode: ...
    def setSize(self, p0: int, p1: int) -> None: ...
