from typing import Any, ClassVar, overload

class HeterogeneousExpandableList:
    def getChildType(self, p0: int, p1: int) -> int: ...
    def getChildTypeCount(self) -> int: ...
    def getGroupType(self, p0: int) -> int: ...
    def getGroupTypeCount(self) -> int: ...
