from typing import Any, ClassVar, overload
from android.content.Context import Context
from android.graphics.Rect import Rect
from android.graphics.drawable.Drawable import Drawable
from android.transition.Transition import Transition
from android.util.AttributeSet import AttributeSet
from android.view.View import View

class PopupWindow:
    INPUT_METHOD_FROM_FOCUSABLE: ClassVar[int]
    INPUT_METHOD_NEEDED: ClassVar[int]
    INPUT_METHOD_NOT_NEEDED: ClassVar[int]
    @overload
    def __init__(self, p0: View) -> None: ...
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, p0: Context, p1: AttributeSet, p2: int, p3: int) -> None: ...
    @overload
    def __init__(self, p0: Context, p1: AttributeSet, p2: int) -> None: ...
    @overload
    def __init__(self, p0: Context, p1: AttributeSet) -> None: ...
    @overload
    def __init__(self, p0: Context) -> None: ...
    @overload
    def __init__(self, p0: View, p1: int, p2: int, p3: bool) -> None: ...
    @overload
    def __init__(self, p0: View, p1: int, p2: int) -> None: ...
    @overload
    def __init__(self, p0: int, p1: int) -> None: ...
    def setFocusable(self, p0: bool) -> None: ...
    def isFocusable(self) -> bool: ...
    def getWidth(self) -> int: ...
    def getHeight(self) -> int: ...
    def getElevation(self) -> float: ...
    def setElevation(self, p0: float) -> None: ...
    def setBackgroundDrawable(self, p0: Drawable) -> None: ...
    def getBackground(self) -> Drawable: ...
    def setEnterTransition(self, p0: Transition) -> None: ...
    def getEnterTransition(self) -> Transition: ...
    def setExitTransition(self, p0: Transition) -> None: ...
    def getExitTransition(self) -> Transition: ...
    def getEpicenterBounds(self) -> Rect: ...
    def setEpicenterBounds(self, p0: Rect) -> None: ...
    def getAnimationStyle(self) -> int: ...
    def setIgnoreCheekPress(self) -> None: ...
    def setAnimationStyle(self, p0: int) -> None: ...
    def getContentView(self) -> View: ...
    def setContentView(self, p0: View) -> None: ...
    def setTouchInterceptor(self, p0: Any) -> None: ...
    def getInputMethodMode(self) -> int: ...
    def setInputMethodMode(self, p0: int) -> None: ...
    def setSoftInputMode(self, p0: int) -> None: ...
    def getSoftInputMode(self) -> int: ...
    def isTouchable(self) -> bool: ...
    def setTouchable(self, p0: bool) -> None: ...
    def isOutsideTouchable(self) -> bool: ...
    def setOutsideTouchable(self, p0: bool) -> None: ...
    def isClippingEnabled(self) -> bool: ...
    def setClippingEnabled(self, p0: bool) -> None: ...
    def isClippedToScreen(self) -> bool: ...
    def setIsClippedToScreen(self, p0: bool) -> None: ...
    def isSplitTouchEnabled(self) -> bool: ...
    def setSplitTouchEnabled(self, p0: bool) -> None: ...
    def isLaidOutInScreen(self) -> bool: ...
    def setIsLaidOutInScreen(self, p0: bool) -> None: ...
    def isAttachedInDecor(self) -> bool: ...
    def setAttachedInDecor(self, p0: bool) -> None: ...
    def setWindowLayoutType(self, p0: int) -> None: ...
    def getWindowLayoutType(self) -> int: ...
    def isTouchModal(self) -> bool: ...
    def setTouchModal(self, p0: bool) -> None: ...
    def setWindowLayoutMode(self, p0: int, p1: int) -> None: ...
    def setHeight(self, p0: int) -> None: ...
    def setWidth(self, p0: int) -> None: ...
    def setOverlapAnchor(self, p0: bool) -> None: ...
    def getOverlapAnchor(self) -> bool: ...
    def showAtLocation(self, p0: View, p1: int, p2: int, p3: int) -> None: ...
    @overload
    def showAsDropDown(self, p0: View, p1: int, p2: int, p3: int) -> None: ...
    @overload
    def showAsDropDown(self, p0: View, p1: int, p2: int) -> None: ...
    @overload
    def showAsDropDown(self, p0: View) -> None: ...
    def isAboveAnchor(self) -> bool: ...
    @overload
    def getMaxAvailableHeight(self, p0: View, p1: int) -> int: ...
    @overload
    def getMaxAvailableHeight(self, p0: View) -> int: ...
    @overload
    def getMaxAvailableHeight(self, p0: View, p1: int, p2: bool) -> int: ...
    def dismiss(self) -> None: ...
    def setOnDismissListener(self, p0: Any) -> None: ...
    def isShowing(self) -> bool: ...
    @overload
    def update(self, p0: View, p1: int, p2: int) -> None: ...
    @overload
    def update(self, p0: int, p1: int, p2: int, p3: int, p4: bool) -> None: ...
    @overload
    def update(self, p0: View, p1: int, p2: int, p3: int, p4: int) -> None: ...
    @overload
    def update(self, p0: int, p1: int, p2: int, p3: int) -> None: ...
    @overload
    def update(self, p0: int, p1: int) -> None: ...
    @overload
    def update(self) -> None: ...

    class OnDismissListener:
        def onDismiss(self) -> None: ...
