from typing import Any, ClassVar, overload
from android.app.PendingIntent import PendingIntent
from android.content.Context import Context
from android.content.Intent import Intent
from android.content.res.ColorStateList import ColorStateList
from android.graphics.Bitmap import Bitmap
from android.graphics.BlendMode import BlendMode
from android.graphics.Outline import Outline
from android.graphics.drawable.Icon import Icon
from android.net.Uri import Uri
from android.os.Bundle import Bundle
from android.os.Parcel import Parcel
from android.view.View import View
from android.view.ViewGroup import ViewGroup
from android.view.ViewOutlineProvider import ViewOutlineProvider
from java.lang.Exception import Exception

class RemoteViews:
    CREATOR: ClassVar[Any]
    EXTRA_CHECKED: ClassVar[str]
    EXTRA_SHARED_ELEMENT_BOUNDS: ClassVar[str]
    MARGIN_BOTTOM: ClassVar[int]
    MARGIN_END: ClassVar[int]
    MARGIN_LEFT: ClassVar[int]
    MARGIN_RIGHT: ClassVar[int]
    MARGIN_START: ClassVar[int]
    MARGIN_TOP: ClassVar[int]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    @overload
    def __init__(self, p0: "RemoteViews", p1: "RemoteViews") -> None: ...
    @overload
    def __init__(self, p0: dict) -> None: ...
    @overload
    def __init__(self, p0: Any) -> None: ...
    @overload
    def __init__(self, p0: Parcel) -> None: ...
    @overload
    def __init__(self, p0: str, p1: int, p2: int) -> None: ...
    @overload
    def __init__(self, p0: str, p1: int) -> None: ...
    @overload
    def __init__(self, p0: "RemoteViews") -> None: ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
    def setUri(self, p0: int, p1: str, p2: Uri) -> None: ...
    def getLayoutId(self) -> int: ...
    def addStableView(self, p0: int, p1: "RemoteViews", p2: int) -> None: ...
    def setViewVisibility(self, p0: int, p1: int) -> None: ...
    def setTextViewText(self, p0: int, p1: str) -> None: ...
    def setTextViewTextSize(self, p0: int, p1: int, p2: float) -> None: ...
    def setTextViewCompoundDrawables(self, p0: int, p1: int, p2: int, p3: int, p4: int) -> None: ...
    def setTextViewCompoundDrawablesRelative(self, p0: int, p1: int, p2: int, p3: int, p4: int) -> None: ...
    def setImageViewResource(self, p0: int, p1: int) -> None: ...
    def setImageViewUri(self, p0: int, p1: Uri) -> None: ...
    def setImageViewBitmap(self, p0: int, p1: Bitmap) -> None: ...
    def setImageViewIcon(self, p0: int, p1: Icon) -> None: ...
    def setChronometer(self, p0: int, p1: int, p2: str, p3: bool) -> None: ...
    def setChronometerCountDown(self, p0: int, p1: bool) -> None: ...
    def setProgressBar(self, p0: int, p1: int, p2: int, p3: bool) -> None: ...
    def setOnClickPendingIntent(self, p0: int, p1: PendingIntent) -> None: ...
    def setOnClickResponse(self, p0: int, p1: Any) -> None: ...
    def setPendingIntentTemplate(self, p0: int, p1: PendingIntent) -> None: ...
    def setOnClickFillInIntent(self, p0: int, p1: Intent) -> None: ...
    def setOnCheckedChangeResponse(self, p0: int, p1: Any) -> None: ...
    def setOnStylusHandwritingPendingIntent(self, p0: int, p1: PendingIntent) -> None: ...
    @overload
    def setRemoteAdapter(self, p0: int, p1: Any) -> None: ...
    @overload
    def setRemoteAdapter(self, p0: int, p1: int, p2: Intent) -> None: ...
    @overload
    def setRemoteAdapter(self, p0: int, p1: Intent) -> None: ...
    def setScrollPosition(self, p0: int, p1: int) -> None: ...
    def setRelativeScrollPosition(self, p0: int, p1: int) -> None: ...
    def setViewPadding(self, p0: int, p1: int, p2: int, p3: int, p4: int) -> None: ...
    def setViewLayoutMarginDimen(self, p0: int, p1: int, p2: int) -> None: ...
    def setViewLayoutMarginAttr(self, p0: int, p1: int, p2: int) -> None: ...
    def setViewLayoutMargin(self, p0: int, p1: int, p2: float, p3: int) -> None: ...
    def setViewLayoutWidth(self, p0: int, p1: float, p2: int) -> None: ...
    def setViewLayoutWidthDimen(self, p0: int, p1: int) -> None: ...
    def setViewLayoutWidthAttr(self, p0: int, p1: int) -> None: ...
    def setViewLayoutHeight(self, p0: int, p1: float, p2: int) -> None: ...
    def setViewLayoutHeightDimen(self, p0: int, p1: int) -> None: ...
    def setViewLayoutHeightAttr(self, p0: int, p1: int) -> None: ...
    def setViewOutlinePreferredRadius(self, p0: int, p1: float, p2: int) -> None: ...
    def setViewOutlinePreferredRadiusDimen(self, p0: int, p1: int) -> None: ...
    def setViewOutlinePreferredRadiusAttr(self, p0: int, p1: int) -> None: ...
    @overload
    def setIntDimen(self, p0: int, p1: str, p2: float, p3: int) -> None: ...
    @overload
    def setIntDimen(self, p0: int, p1: str, p2: int) -> None: ...
    def setIntDimenAttr(self, p0: int, p1: str, p2: int) -> None: ...
    def setColor(self, p0: int, p1: str, p2: int) -> None: ...
    def setColorAttr(self, p0: int, p1: str, p2: int) -> None: ...
    def setColorInt(self, p0: int, p1: str, p2: int, p3: int) -> None: ...
    @overload
    def setColorStateList(self, p0: int, p1: str, p2: ColorStateList) -> None: ...
    @overload
    def setColorStateList(self, p0: int, p1: str, p2: ColorStateList, p3: ColorStateList) -> None: ...
    @overload
    def setColorStateList(self, p0: int, p1: str, p2: int) -> None: ...
    def setColorStateListAttr(self, p0: int, p1: str, p2: int) -> None: ...
    @overload
    def setFloatDimen(self, p0: int, p1: str, p2: float, p3: int) -> None: ...
    @overload
    def setFloatDimen(self, p0: int, p1: str, p2: int) -> None: ...
    def setFloatDimenAttr(self, p0: int, p1: str, p2: int) -> None: ...
    @overload
    def setCharSequence(self, p0: int, p1: str, p2: int) -> None: ...
    @overload
    def setCharSequence(self, p0: int, p1: str, p2: str) -> None: ...
    def setCharSequenceAttr(self, p0: int, p1: str, p2: int) -> None: ...
    def setBlendMode(self, p0: int, p1: str, p2: BlendMode) -> None: ...
    def setBundle(self, p0: int, p1: str, p2: Bundle) -> None: ...
    def setIntent(self, p0: int, p1: str, p2: Intent) -> None: ...
    @overload
    def setIcon(self, p0: int, p1: str, p2: Icon) -> None: ...
    @overload
    def setIcon(self, p0: int, p1: str, p2: Icon, p3: Icon) -> None: ...
    def setCompoundButtonChecked(self, p0: int, p1: bool) -> None: ...
    def setRadioGroupChecked(self, p0: int, p1: int) -> None: ...
    def setLightBackgroundLayoutId(self, p0: int) -> None: ...
    def reapply(self, p0: Context, p1: View) -> None: ...
    def onLoadClass(self, p0: type) -> bool: ...
    def getViewId(self) -> int: ...
    def addView(self, p0: int, p1: "RemoteViews") -> None: ...
    def removeAllViews(self, p0: int) -> None: ...
    def setContentDescription(self, p0: int, p1: str) -> None: ...
    def setAccessibilityTraversalBefore(self, p0: int, p1: int) -> None: ...
    def setAccessibilityTraversalAfter(self, p0: int, p1: int) -> None: ...
    def setLabelFor(self, p0: int, p1: int) -> None: ...
    def setString(self, p0: int, p1: str, p2: str) -> None: ...
    def setEmptyView(self, p0: int, p1: int) -> None: ...
    def setBitmap(self, p0: int, p1: str, p2: Bitmap) -> None: ...
    def showNext(self, p0: int) -> None: ...
    def showPrevious(self, p0: int) -> None: ...
    def setDisplayedChild(self, p0: int, p1: int) -> None: ...
    def setTextColor(self, p0: int, p1: int) -> None: ...
    @overload
    def clone(self) -> Any: ...
    @overload
    def clone(self) -> "RemoteViews": ...
    def apply(self, p0: Context, p1: ViewGroup) -> View: ...
    def getPackage(self) -> str: ...
    def setBoolean(self, p0: int, p1: str, p2: bool) -> None: ...
    def setByte(self, p0: int, p1: str, p2: int) -> None: ...
    def setChar(self, p0: int, p1: str, p2: str) -> None: ...
    def setShort(self, p0: int, p1: str, p2: int) -> None: ...
    def setInt(self, p0: int, p1: str, p2: int) -> None: ...
    def setLong(self, p0: int, p1: str, p2: int) -> None: ...
    def setFloat(self, p0: int, p1: str, p2: float) -> None: ...
    def setDouble(self, p0: int, p1: str, p2: float) -> None: ...

    class RemoteViewOutlineProvider:
        BACKGROUND: ClassVar[ViewOutlineProvider]
        BOUNDS: ClassVar[ViewOutlineProvider]
        PADDED_BOUNDS: ClassVar[ViewOutlineProvider]
        def __init__(self, p0: float) -> None: ...
        def getRadius(self) -> float: ...
        def getOutline(self, p0: View, p1: Outline) -> None: ...

    class RemoteView:
        ...

    class RemoteResponse:
        def __init__(self) -> None: ...
        @staticmethod
        def fromPendingIntent(p0: PendingIntent) -> Any: ...
        @staticmethod
        def fromFillInIntent(p0: Intent) -> Any: ...
        def addSharedElement(self, p0: int, p1: str) -> Any: ...

    class RemoteCollectionItems:
        CREATOR: ClassVar[Any]
        CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
        PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
        def describeContents(self) -> int: ...
        def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
        def getItemView(self, p0: int) -> "RemoteViews": ...
        def getItemCount(self) -> int: ...
        def getItemId(self, p0: int) -> int: ...
        def hasStableIds(self) -> bool: ...
        def getViewTypeCount(self) -> int: ...

        class Builder:
            def __init__(self) -> None: ...
            def addItem(self, p0: int, p1: "RemoteViews") -> Any: ...
            def setHasStableIds(self, p0: bool) -> Any: ...
            def setViewTypeCount(self, p0: int) -> Any: ...
            def build(self) -> Any: ...

    class DrawInstructions:
        @staticmethod
        def getSupportedVersion() -> int: ...

        class Builder:
            def __init__(self, p0: list) -> None: ...
            def build(self) -> Any: ...

    class ActionException:
        @overload
        def __init__(self, p0: Exception) -> None: ...
        @overload
        def __init__(self, p0: str) -> None: ...
