from typing import Any, ClassVar, overload
from android.content.Context import Context
from android.content.Intent import Intent
from android.view.SubMenu import SubMenu
from android.view.View import View

class ShareActionProvider:
    DEFAULT_SHARE_HISTORY_FILE_NAME: ClassVar[str]
    def __init__(self, p0: Context) -> None: ...
    def hasSubMenu(self) -> bool: ...
    def onCreateActionView(self) -> View: ...
    def onPrepareSubMenu(self, p0: SubMenu) -> None: ...
    def setOnShareTargetSelectedListener(self, p0: Any) -> None: ...
    def setShareHistoryFileName(self, p0: str) -> None: ...
    def setShareIntent(self, p0: Intent) -> None: ...

    class OnShareTargetSelectedListener:
        def onShareTargetSelected(self, p0: "ShareActionProvider", p1: Intent) -> bool: ...
