from typing import Any, ClassVar, overload
from android.content.Context import Context
from android.content.res.ColorStateList import ColorStateList
from android.graphics.BlendMode import BlendMode
from android.graphics.Rect import Rect
from android.graphics.Typeface import Typeface
from android.graphics.drawable.Drawable import Drawable
from android.os.Bundle import Bundle
from android.os.LocaleList import LocaleList
from android.os.Parcel import Parcel
from android.os.Parcelable import Parcelable
from android.text.Editable import Editable
from android.text.Highlights import Highlights
from android.text.Layout import Layout
from android.text.TextDirectionHeuristic import TextDirectionHeuristic
from android.text.TextPaint import TextPaint
from android.text.TextWatcher import TextWatcher
from android.text.method.KeyListener import KeyListener
from android.text.method.MovementMethod import MovementMethod
from android.text.method.TransformationMethod import TransformationMethod
from android.util.AttributeSet import AttributeSet
from android.util.Property import Property
from android.view.AbsSavedState import AbsSavedState
from android.view.ContentInfo import ContentInfo
from android.view.DragEvent import DragEvent
from android.view.KeyEvent import KeyEvent
from android.view.MotionEvent import MotionEvent
from android.view.PointerIcon import PointerIcon
from android.view.accessibility.AccessibilityEvent import AccessibilityEvent
from android.view.accessibility.AccessibilityNodeInfo import AccessibilityNodeInfo
from android.view.autofill.AutofillValue import AutofillValue
from android.view.inputmethod.CompletionInfo import CompletionInfo
from android.view.inputmethod.CorrectionInfo import CorrectionInfo
from android.view.inputmethod.EditorInfo import EditorInfo
from android.view.inputmethod.ExtractedText import ExtractedText
from android.view.inputmethod.ExtractedTextRequest import ExtractedTextRequest
from android.view.inputmethod.InputConnection import InputConnection
from android.view.textclassifier.TextClassifier import TextClassifier
from android.widget.Scroller import Scroller
from java.util.Locale import Locale
from java.util.function.Consumer import Consumer

class TextView:
    AUTO_SIZE_TEXT_TYPE_NONE: ClassVar[int]
    AUTO_SIZE_TEXT_TYPE_UNIFORM: ClassVar[int]
    FOCUSED_SEARCH_RESULT_INDEX_NONE: ClassVar[int]
    ACCESSIBILITY_DATA_SENSITIVE_AUTO: ClassVar[int]
    ACCESSIBILITY_DATA_SENSITIVE_NO: ClassVar[int]
    ACCESSIBILITY_DATA_SENSITIVE_YES: ClassVar[int]
    ACCESSIBILITY_LIVE_REGION_ASSERTIVE: ClassVar[int]
    ACCESSIBILITY_LIVE_REGION_NONE: ClassVar[int]
    ACCESSIBILITY_LIVE_REGION_POLITE: ClassVar[int]
    ALPHA: ClassVar[Property]
    AUTOFILL_FLAG_INCLUDE_NOT_IMPORTANT_VIEWS: ClassVar[int]
    AUTOFILL_HINT_CREDIT_CARD_EXPIRATION_DATE: ClassVar[str]
    AUTOFILL_HINT_CREDIT_CARD_EXPIRATION_DAY: ClassVar[str]
    AUTOFILL_HINT_CREDIT_CARD_EXPIRATION_MONTH: ClassVar[str]
    AUTOFILL_HINT_CREDIT_CARD_EXPIRATION_YEAR: ClassVar[str]
    AUTOFILL_HINT_CREDIT_CARD_NUMBER: ClassVar[str]
    AUTOFILL_HINT_CREDIT_CARD_SECURITY_CODE: ClassVar[str]
    AUTOFILL_HINT_EMAIL_ADDRESS: ClassVar[str]
    AUTOFILL_HINT_NAME: ClassVar[str]
    AUTOFILL_HINT_PASSWORD: ClassVar[str]
    AUTOFILL_HINT_PHONE: ClassVar[str]
    AUTOFILL_HINT_POSTAL_ADDRESS: ClassVar[str]
    AUTOFILL_HINT_POSTAL_CODE: ClassVar[str]
    AUTOFILL_HINT_USERNAME: ClassVar[str]
    AUTOFILL_TYPE_DATE: ClassVar[int]
    AUTOFILL_TYPE_LIST: ClassVar[int]
    AUTOFILL_TYPE_NONE: ClassVar[int]
    AUTOFILL_TYPE_TEXT: ClassVar[int]
    AUTOFILL_TYPE_TOGGLE: ClassVar[int]
    CONTENT_SENSITIVITY_AUTO: ClassVar[int]
    CONTENT_SENSITIVITY_NOT_SENSITIVE: ClassVar[int]
    CONTENT_SENSITIVITY_SENSITIVE: ClassVar[int]
    DRAG_FLAG_ACCESSIBILITY_ACTION: ClassVar[int]
    DRAG_FLAG_GLOBAL: ClassVar[int]
    DRAG_FLAG_GLOBAL_PERSISTABLE_URI_PERMISSION: ClassVar[int]
    DRAG_FLAG_GLOBAL_PREFIX_URI_PERMISSION: ClassVar[int]
    DRAG_FLAG_GLOBAL_SAME_APPLICATION: ClassVar[int]
    DRAG_FLAG_GLOBAL_URI_READ: ClassVar[int]
    DRAG_FLAG_GLOBAL_URI_WRITE: ClassVar[int]
    DRAG_FLAG_OPAQUE: ClassVar[int]
    DRAG_FLAG_START_INTENT_SENDER_ON_UNHANDLED_DRAG: ClassVar[int]
    DRAWING_CACHE_QUALITY_AUTO: ClassVar[int]
    DRAWING_CACHE_QUALITY_HIGH: ClassVar[int]
    DRAWING_CACHE_QUALITY_LOW: ClassVar[int]
    FIND_VIEWS_WITH_CONTENT_DESCRIPTION: ClassVar[int]
    FIND_VIEWS_WITH_TEXT: ClassVar[int]
    FOCUSABLE: ClassVar[int]
    FOCUSABLES_ALL: ClassVar[int]
    FOCUSABLES_TOUCH_MODE: ClassVar[int]
    FOCUSABLE_AUTO: ClassVar[int]
    FOCUS_BACKWARD: ClassVar[int]
    FOCUS_DOWN: ClassVar[int]
    FOCUS_FORWARD: ClassVar[int]
    FOCUS_LEFT: ClassVar[int]
    FOCUS_RIGHT: ClassVar[int]
    FOCUS_UP: ClassVar[int]
    GONE: ClassVar[int]
    HAPTIC_FEEDBACK_ENABLED: ClassVar[int]
    IMPORTANT_FOR_ACCESSIBILITY_AUTO: ClassVar[int]
    IMPORTANT_FOR_ACCESSIBILITY_NO: ClassVar[int]
    IMPORTANT_FOR_ACCESSIBILITY_NO_HIDE_DESCENDANTS: ClassVar[int]
    IMPORTANT_FOR_ACCESSIBILITY_YES: ClassVar[int]
    IMPORTANT_FOR_AUTOFILL_AUTO: ClassVar[int]
    IMPORTANT_FOR_AUTOFILL_NO: ClassVar[int]
    IMPORTANT_FOR_AUTOFILL_NO_EXCLUDE_DESCENDANTS: ClassVar[int]
    IMPORTANT_FOR_AUTOFILL_YES: ClassVar[int]
    IMPORTANT_FOR_AUTOFILL_YES_EXCLUDE_DESCENDANTS: ClassVar[int]
    IMPORTANT_FOR_CONTENT_CAPTURE_AUTO: ClassVar[int]
    IMPORTANT_FOR_CONTENT_CAPTURE_NO: ClassVar[int]
    IMPORTANT_FOR_CONTENT_CAPTURE_NO_EXCLUDE_DESCENDANTS: ClassVar[int]
    IMPORTANT_FOR_CONTENT_CAPTURE_YES: ClassVar[int]
    IMPORTANT_FOR_CONTENT_CAPTURE_YES_EXCLUDE_DESCENDANTS: ClassVar[int]
    INVISIBLE: ClassVar[int]
    KEEP_SCREEN_ON: ClassVar[int]
    LAYER_TYPE_HARDWARE: ClassVar[int]
    LAYER_TYPE_NONE: ClassVar[int]
    LAYER_TYPE_SOFTWARE: ClassVar[int]
    LAYOUT_DIRECTION_INHERIT: ClassVar[int]
    LAYOUT_DIRECTION_LOCALE: ClassVar[int]
    LAYOUT_DIRECTION_LTR: ClassVar[int]
    LAYOUT_DIRECTION_RTL: ClassVar[int]
    MEASURED_HEIGHT_STATE_SHIFT: ClassVar[int]
    MEASURED_SIZE_MASK: ClassVar[int]
    MEASURED_STATE_MASK: ClassVar[int]
    MEASURED_STATE_TOO_SMALL: ClassVar[int]
    NOT_FOCUSABLE: ClassVar[int]
    NO_ID: ClassVar[int]
    OVER_SCROLL_ALWAYS: ClassVar[int]
    OVER_SCROLL_IF_CONTENT_SCROLLS: ClassVar[int]
    OVER_SCROLL_NEVER: ClassVar[int]
    REQUESTED_FRAME_RATE_CATEGORY_DEFAULT: ClassVar[float]
    REQUESTED_FRAME_RATE_CATEGORY_HIGH: ClassVar[float]
    REQUESTED_FRAME_RATE_CATEGORY_LOW: ClassVar[float]
    REQUESTED_FRAME_RATE_CATEGORY_NORMAL: ClassVar[float]
    REQUESTED_FRAME_RATE_CATEGORY_NO_PREFERENCE: ClassVar[float]
    ROTATION: ClassVar[Property]
    ROTATION_X: ClassVar[Property]
    ROTATION_Y: ClassVar[Property]
    SCALE_X: ClassVar[Property]
    SCALE_Y: ClassVar[Property]
    SCREEN_STATE_OFF: ClassVar[int]
    SCREEN_STATE_ON: ClassVar[int]
    SCROLLBARS_INSIDE_INSET: ClassVar[int]
    SCROLLBARS_INSIDE_OVERLAY: ClassVar[int]
    SCROLLBARS_OUTSIDE_INSET: ClassVar[int]
    SCROLLBARS_OUTSIDE_OVERLAY: ClassVar[int]
    SCROLLBAR_POSITION_DEFAULT: ClassVar[int]
    SCROLLBAR_POSITION_LEFT: ClassVar[int]
    SCROLLBAR_POSITION_RIGHT: ClassVar[int]
    SCROLL_AXIS_HORIZONTAL: ClassVar[int]
    SCROLL_AXIS_NONE: ClassVar[int]
    SCROLL_AXIS_VERTICAL: ClassVar[int]
    SCROLL_CAPTURE_HINT_AUTO: ClassVar[int]
    SCROLL_CAPTURE_HINT_EXCLUDE: ClassVar[int]
    SCROLL_CAPTURE_HINT_EXCLUDE_DESCENDANTS: ClassVar[int]
    SCROLL_CAPTURE_HINT_INCLUDE: ClassVar[int]
    SCROLL_INDICATOR_BOTTOM: ClassVar[int]
    SCROLL_INDICATOR_END: ClassVar[int]
    SCROLL_INDICATOR_LEFT: ClassVar[int]
    SCROLL_INDICATOR_RIGHT: ClassVar[int]
    SCROLL_INDICATOR_START: ClassVar[int]
    SCROLL_INDICATOR_TOP: ClassVar[int]
    SOUND_EFFECTS_ENABLED: ClassVar[int]
    STATUS_BAR_HIDDEN: ClassVar[int]
    STATUS_BAR_VISIBLE: ClassVar[int]
    SYSTEM_UI_FLAG_FULLSCREEN: ClassVar[int]
    SYSTEM_UI_FLAG_HIDE_NAVIGATION: ClassVar[int]
    SYSTEM_UI_FLAG_IMMERSIVE: ClassVar[int]
    SYSTEM_UI_FLAG_IMMERSIVE_STICKY: ClassVar[int]
    SYSTEM_UI_FLAG_LAYOUT_FULLSCREEN: ClassVar[int]
    SYSTEM_UI_FLAG_LAYOUT_HIDE_NAVIGATION: ClassVar[int]
    SYSTEM_UI_FLAG_LAYOUT_STABLE: ClassVar[int]
    SYSTEM_UI_FLAG_LIGHT_NAVIGATION_BAR: ClassVar[int]
    SYSTEM_UI_FLAG_LIGHT_STATUS_BAR: ClassVar[int]
    SYSTEM_UI_FLAG_LOW_PROFILE: ClassVar[int]
    SYSTEM_UI_FLAG_VISIBLE: ClassVar[int]
    SYSTEM_UI_LAYOUT_FLAGS: ClassVar[int]
    TEXT_ALIGNMENT_CENTER: ClassVar[int]
    TEXT_ALIGNMENT_GRAVITY: ClassVar[int]
    TEXT_ALIGNMENT_INHERIT: ClassVar[int]
    TEXT_ALIGNMENT_TEXT_END: ClassVar[int]
    TEXT_ALIGNMENT_TEXT_START: ClassVar[int]
    TEXT_ALIGNMENT_VIEW_END: ClassVar[int]
    TEXT_ALIGNMENT_VIEW_START: ClassVar[int]
    TEXT_DIRECTION_ANY_RTL: ClassVar[int]
    TEXT_DIRECTION_FIRST_STRONG: ClassVar[int]
    TEXT_DIRECTION_FIRST_STRONG_LTR: ClassVar[int]
    TEXT_DIRECTION_FIRST_STRONG_RTL: ClassVar[int]
    TEXT_DIRECTION_INHERIT: ClassVar[int]
    TEXT_DIRECTION_LOCALE: ClassVar[int]
    TEXT_DIRECTION_LTR: ClassVar[int]
    TEXT_DIRECTION_RTL: ClassVar[int]
    TRANSLATION_X: ClassVar[Property]
    TRANSLATION_Y: ClassVar[Property]
    TRANSLATION_Z: ClassVar[Property]
    VISIBLE: ClassVar[int]
    X: ClassVar[Property]
    Y: ClassVar[Property]
    Z: ClassVar[Property]
    @overload
    def __init__(self, p0: Context, p1: AttributeSet) -> None: ...
    @overload
    def __init__(self, p0: Context) -> None: ...
    @overload
    def __init__(self, p0: Context, p1: AttributeSet, p2: int, p3: int) -> None: ...
    @overload
    def __init__(self, p0: Context, p1: AttributeSet, p2: int) -> None: ...
    def onResolvePointerIcon(self, p0: MotionEvent, p1: int) -> PointerIcon: ...
    def performLongClick(self) -> bool: ...
    @overload
    def showContextMenu(self, p0: float, p1: float) -> bool: ...
    @overload
    def showContextMenu(self) -> bool: ...
    def sendAccessibilityEventUnchecked(self, p0: AccessibilityEvent) -> None: ...
    def onReceiveContent(self, p0: ContentInfo) -> ContentInfo: ...
    def autofill(self, p0: AutofillValue) -> None: ...
    def getAutofillType(self) -> int: ...
    def getAutofillHints(self) -> Any: ...
    def getAutofillValue(self) -> AutofillValue: ...
    def addExtraDataToAccessibilityNodeInfo(self, p0: AccessibilityNodeInfo, p1: str, p2: Bundle) -> None: ...
    def findViewsWithText(self, p0: list, p1: str, p2: int) -> None: ...
    def onWindowFocusChanged(self, p0: bool) -> None: ...
    def onKeyPreIme(self, p0: int, p1: KeyEvent) -> bool: ...
    def onKeyDown(self, p0: int, p1: KeyEvent) -> bool: ...
    def onKeyMultiple(self, p0: int, p1: int, p2: KeyEvent) -> bool: ...
    def onKeyShortcut(self, p0: int, p1: KeyEvent) -> bool: ...
    def onCheckIsTextEditor(self) -> bool: ...
    def onCreateInputConnection(self, p0: EditorInfo) -> InputConnection: ...
    def onTrackballEvent(self, p0: MotionEvent) -> bool: ...
    def onGenericMotionEvent(self, p0: MotionEvent) -> bool: ...
    def cancelLongPress(self) -> None: ...
    def getFocusedRect(self, p0: Rect) -> None: ...
    def computeScroll(self) -> None: ...
    def onScreenStateChanged(self, p0: int) -> None: ...
    def onSaveInstanceState(self) -> Parcelable: ...
    def onRestoreInstanceState(self, p0: Parcelable) -> None: ...
    def setPadding(self, p0: int, p1: int, p2: int, p3: int) -> None: ...
    def setPaddingRelative(self, p0: int, p1: int, p2: int, p3: int) -> None: ...
    def onDragEvent(self, p0: DragEvent) -> bool: ...
    def isAutoHandwritingEnabled(self) -> bool: ...
    def onCreateViewTranslationRequest(self, p0: Any, p1: Consumer) -> None: ...
    def onTouchEvent(self, p0: MotionEvent) -> bool: ...
    def onKeyUp(self, p0: int, p1: KeyEvent) -> bool: ...
    def setEnabled(self, p0: bool) -> None: ...
    def getAccessibilityClassName(self) -> str: ...
    def jumpDrawablesToCurrentState(self) -> None: ...
    def invalidateDrawable(self, p0: Drawable) -> None: ...
    def hasOverlappingRendering(self) -> bool: ...
    def getMaxWidth(self) -> int: ...
    def setMaxWidth(self, p0: int) -> None: ...
    def getMaxHeight(self) -> int: ...
    def setMaxHeight(self, p0: int) -> None: ...
    def setSelected(self, p0: bool) -> None: ...
    def onRtlPropertiesChanged(self, p0: int) -> None: ...
    def drawableHotspotChanged(self, p0: float, p1: float) -> None: ...
    def getBaseline(self) -> int: ...
    def onVisibilityAggregated(self, p0: bool) -> None: ...
    def setHeight(self, p0: int) -> None: ...
    def setWidth(self, p0: int) -> None: ...
    def getText(self) -> str: ...
    def setEms(self, p0: int) -> None: ...
    def setAutoSizeTextTypeWithDefaults(self, p0: int) -> None: ...
    def setAutoSizeTextTypeUniformWithConfiguration(self, p0: int, p1: int, p2: int, p3: int) -> None: ...
    def setAutoSizeTextTypeUniformWithPresetSizes(self, p0: Any, p1: int) -> None: ...
    def getAutoSizeTextType(self) -> int: ...
    def getAutoSizeStepGranularity(self) -> int: ...
    def getAutoSizeMinTextSize(self) -> int: ...
    def getAutoSizeMaxTextSize(self) -> int: ...
    def getAutoSizeTextAvailableSizes(self) -> Any: ...
    @overload
    def setTypeface(self, p0: Typeface) -> None: ...
    @overload
    def setTypeface(self, p0: Typeface, p1: int) -> None: ...
    def getEditableText(self) -> Editable: ...
    def getLineHeight(self) -> int: ...
    def getLayout(self) -> Layout: ...
    def getKeyListener(self) -> KeyListener: ...
    def setKeyListener(self, p0: KeyListener) -> None: ...
    def getMovementMethod(self) -> MovementMethod: ...
    def setMovementMethod(self, p0: MovementMethod) -> None: ...
    def getTransformationMethod(self) -> TransformationMethod: ...
    def setTransformationMethod(self, p0: TransformationMethod) -> None: ...
    def getCompoundPaddingTop(self) -> int: ...
    def getCompoundPaddingBottom(self) -> int: ...
    def getCompoundPaddingLeft(self) -> int: ...
    def getCompoundPaddingRight(self) -> int: ...
    def getCompoundPaddingStart(self) -> int: ...
    def getCompoundPaddingEnd(self) -> int: ...
    def getExtendedPaddingTop(self) -> int: ...
    def getExtendedPaddingBottom(self) -> int: ...
    def getTotalPaddingLeft(self) -> int: ...
    def getTotalPaddingRight(self) -> int: ...
    def getTotalPaddingStart(self) -> int: ...
    def getTotalPaddingEnd(self) -> int: ...
    def getTotalPaddingTop(self) -> int: ...
    def getTotalPaddingBottom(self) -> int: ...
    def setCompoundDrawables(self, p0: Drawable, p1: Drawable, p2: Drawable, p3: Drawable) -> None: ...
    @overload
    def setCompoundDrawablesWithIntrinsicBounds(self, p0: Drawable, p1: Drawable, p2: Drawable, p3: Drawable) -> None: ...
    @overload
    def setCompoundDrawablesWithIntrinsicBounds(self, p0: int, p1: int, p2: int, p3: int) -> None: ...
    def setCompoundDrawablesRelative(self, p0: Drawable, p1: Drawable, p2: Drawable, p3: Drawable) -> None: ...
    @overload
    def setCompoundDrawablesRelativeWithIntrinsicBounds(self, p0: Drawable, p1: Drawable, p2: Drawable, p3: Drawable) -> None: ...
    @overload
    def setCompoundDrawablesRelativeWithIntrinsicBounds(self, p0: int, p1: int, p2: int, p3: int) -> None: ...
    def getCompoundDrawables(self) -> Any: ...
    def getCompoundDrawablesRelative(self) -> Any: ...
    def setCompoundDrawablePadding(self, p0: int) -> None: ...
    def getCompoundDrawablePadding(self) -> int: ...
    def setCompoundDrawableTintList(self, p0: ColorStateList) -> None: ...
    def getCompoundDrawableTintList(self) -> ColorStateList: ...
    def setCompoundDrawableTintMode(self, p0: Any) -> None: ...
    def setCompoundDrawableTintBlendMode(self, p0: BlendMode) -> None: ...
    def getCompoundDrawableTintMode(self) -> Any: ...
    def getCompoundDrawableTintBlendMode(self) -> BlendMode: ...
    def setFirstBaselineToTopHeight(self, p0: int) -> None: ...
    def setLastBaselineToBottomHeight(self, p0: int) -> None: ...
    def getFirstBaselineToTopHeight(self) -> int: ...
    def getLastBaselineToBottomHeight(self) -> int: ...
    def getAutoLinkMask(self) -> int: ...
    @overload
    def setTextSelectHandle(self, p0: int) -> None: ...
    @overload
    def setTextSelectHandle(self, p0: Drawable) -> None: ...
    def getTextSelectHandle(self) -> Drawable: ...
    @overload
    def setTextSelectHandleLeft(self, p0: int) -> None: ...
    @overload
    def setTextSelectHandleLeft(self, p0: Drawable) -> None: ...
    def getTextSelectHandleLeft(self) -> Drawable: ...
    @overload
    def setTextSelectHandleRight(self, p0: int) -> None: ...
    @overload
    def setTextSelectHandleRight(self, p0: Drawable) -> None: ...
    def getTextSelectHandleRight(self) -> Drawable: ...
    @overload
    def setTextCursorDrawable(self, p0: Drawable) -> None: ...
    @overload
    def setTextCursorDrawable(self, p0: int) -> None: ...
    def getTextCursorDrawable(self) -> Drawable: ...
    @overload
    def setTextAppearance(self, p0: int) -> None: ...
    @overload
    def setTextAppearance(self, p0: Context, p1: int) -> None: ...
    def getTextLocale(self) -> Locale: ...
    def getTextLocales(self) -> LocaleList: ...
    def setTextLocale(self, p0: Locale) -> None: ...
    def setTextLocales(self, p0: LocaleList) -> None: ...
    def getTextSize(self) -> float: ...
    @overload
    def setTextSize(self, p0: int, p1: float) -> None: ...
    @overload
    def setTextSize(self, p0: float) -> None: ...
    def getTextSizeUnit(self) -> int: ...
    def getTextScaleX(self) -> float: ...
    def setTextScaleX(self, p0: float) -> None: ...
    def getTypeface(self) -> Typeface: ...
    def setElegantTextHeight(self, p0: bool) -> None: ...
    def setFallbackLineSpacing(self, p0: bool) -> None: ...
    def setUseBoundsForWidth(self, p0: bool) -> None: ...
    def getUseBoundsForWidth(self) -> bool: ...
    def setShiftDrawingOffsetForStartOverhang(self, p0: bool) -> None: ...
    def getShiftDrawingOffsetForStartOverhang(self) -> bool: ...
    def setMinimumFontMetrics(self, p0: Any) -> None: ...
    def getMinimumFontMetrics(self) -> Any: ...
    def isLocalePreferredLineHeightForMinimumUsed(self) -> bool: ...
    def setLocalePreferredLineHeightForMinimumUsed(self, p0: bool) -> None: ...
    def isFallbackLineSpacing(self) -> bool: ...
    def isElegantTextHeight(self) -> bool: ...
    def getLetterSpacing(self) -> float: ...
    def setLetterSpacing(self, p0: float) -> None: ...
    def getFontFeatureSettings(self) -> str: ...
    def getFontVariationSettings(self) -> str: ...
    def setBreakStrategy(self, p0: int) -> None: ...
    def getBreakStrategy(self) -> int: ...
    def setHyphenationFrequency(self, p0: int) -> None: ...
    def getHyphenationFrequency(self) -> int: ...
    def setLineBreakStyle(self, p0: int) -> None: ...
    def setLineBreakWordStyle(self, p0: int) -> None: ...
    def getLineBreakStyle(self) -> int: ...
    def getLineBreakWordStyle(self) -> int: ...
    def getTextMetricsParams(self) -> Any: ...
    def setTextMetricsParams(self, p0: Any) -> None: ...
    def setJustificationMode(self, p0: int) -> None: ...
    def getJustificationMode(self) -> int: ...
    def setFontFeatureSettings(self, p0: str) -> None: ...
    def setFontVariationSettings(self, p0: str) -> bool: ...
    @overload
    def setTextColor(self, p0: ColorStateList) -> None: ...
    @overload
    def setTextColor(self, p0: int) -> None: ...
    def getTextColors(self) -> ColorStateList: ...
    def getCurrentTextColor(self) -> int: ...
    def setHighlightColor(self, p0: int) -> None: ...
    def getHighlightColor(self) -> int: ...
    def setShowSoftInputOnFocus(self, p0: bool) -> None: ...
    def getShowSoftInputOnFocus(self) -> bool: ...
    def setShadowLayer(self, p0: float, p1: float, p2: float, p3: int) -> None: ...
    def getShadowRadius(self) -> float: ...
    def getShadowDx(self) -> float: ...
    def getShadowDy(self) -> float: ...
    def getShadowColor(self) -> int: ...
    def getPaint(self) -> TextPaint: ...
    def setAutoLinkMask(self, p0: int) -> None: ...
    def setLinksClickable(self, p0: bool) -> None: ...
    def getLinksClickable(self) -> bool: ...
    def getUrls(self) -> Any: ...
    @overload
    def setHintTextColor(self, p0: int) -> None: ...
    @overload
    def setHintTextColor(self, p0: ColorStateList) -> None: ...
    def getHintTextColors(self) -> ColorStateList: ...
    def getCurrentHintTextColor(self) -> int: ...
    @overload
    def setLinkTextColor(self, p0: ColorStateList) -> None: ...
    @overload
    def setLinkTextColor(self, p0: int) -> None: ...
    def getLinkTextColors(self) -> ColorStateList: ...
    def getPaintFlags(self) -> int: ...
    def setPaintFlags(self, p0: int) -> None: ...
    def setHorizontallyScrolling(self, p0: bool) -> None: ...
    def isHorizontallyScrollable(self) -> bool: ...
    def setMinLines(self, p0: int) -> None: ...
    def getMinLines(self) -> int: ...
    def setMinHeight(self, p0: int) -> None: ...
    def getMinHeight(self) -> int: ...
    def setMaxLines(self, p0: int) -> None: ...
    def getMaxLines(self) -> int: ...
    def setLines(self, p0: int) -> None: ...
    def setMinEms(self, p0: int) -> None: ...
    def getMinEms(self) -> int: ...
    def setMinWidth(self, p0: int) -> None: ...
    def getMinWidth(self) -> int: ...
    def setMaxEms(self, p0: int) -> None: ...
    def getMaxEms(self) -> int: ...
    def setLineSpacing(self, p0: float, p1: float) -> None: ...
    def getLineSpacingMultiplier(self) -> float: ...
    def getLineSpacingExtra(self) -> float: ...
    @overload
    def setLineHeight(self, p0: int, p1: float) -> None: ...
    @overload
    def setLineHeight(self, p0: int) -> None: ...
    def setHighlights(self, p0: Highlights) -> None: ...
    def getHighlights(self) -> Highlights: ...
    def setSearchResultHighlights(self, p0: Any) -> None: ...
    def getSearchResultHighlights(self) -> Any: ...
    def setFocusedSearchResultIndex(self, p0: int) -> None: ...
    def getFocusedSearchResultIndex(self) -> int: ...
    def setSearchResultHighlightColor(self, p0: int) -> None: ...
    def getSearchResultHighlightColor(self) -> int: ...
    def setFocusedSearchResultHighlightColor(self, p0: int) -> None: ...
    def getFocusedSearchResultHighlightColor(self) -> int: ...
    def setFreezesText(self, p0: bool) -> None: ...
    def getFreezesText(self) -> bool: ...
    def setEditableFactory(self, p0: Any) -> None: ...
    def setSpannableFactory(self, p0: Any) -> None: ...
    @overload
    def setText(self, p0: Any, p1: int, p2: int) -> None: ...
    @overload
    def setText(self, p0: str, p1: Any) -> None: ...
    @overload
    def setText(self, p0: int, p1: Any) -> None: ...
    @overload
    def setText(self, p0: str) -> None: ...
    @overload
    def setText(self, p0: int) -> None: ...
    @overload
    def setTextKeepState(self, p0: str, p1: Any) -> None: ...
    @overload
    def setTextKeepState(self, p0: str) -> None: ...
    @overload
    def setHint(self, p0: int) -> None: ...
    @overload
    def setHint(self, p0: str) -> None: ...
    def getHint(self) -> str: ...
    def isSingleLine(self) -> bool: ...
    def setInputType(self, p0: int) -> None: ...
    def setRawInputType(self, p0: int) -> None: ...
    def getInputType(self) -> int: ...
    def setImeOptions(self, p0: int) -> None: ...
    def getImeOptions(self) -> int: ...
    def setImeActionLabel(self, p0: str, p1: int) -> None: ...
    def getImeActionLabel(self) -> str: ...
    def getImeActionId(self) -> int: ...
    def setOnEditorActionListener(self, p0: Any) -> None: ...
    def onEditorAction(self, p0: int) -> None: ...
    def setPrivateImeOptions(self, p0: str) -> None: ...
    def getPrivateImeOptions(self) -> str: ...
    def setInputExtras(self, p0: int) -> None: ...
    def getInputExtras(self, p0: bool) -> Bundle: ...
    def setImeHintLocales(self, p0: LocaleList) -> None: ...
    def getImeHintLocales(self) -> LocaleList: ...
    def getError(self) -> str: ...
    def setFilters(self, p0: Any) -> None: ...
    def getFilters(self) -> Any: ...
    def onPreDraw(self) -> bool: ...
    def isTextSelectable(self) -> bool: ...
    def setTextIsSelectable(self, p0: bool) -> None: ...
    def getLineCount(self) -> int: ...
    def getLineBounds(self, p0: int, p1: Rect) -> int: ...
    def extractText(self, p0: ExtractedTextRequest, p1: ExtractedText) -> bool: ...
    def setExtractedText(self, p0: ExtractedText) -> None: ...
    def onCommitCompletion(self, p0: CompletionInfo) -> None: ...
    def onCommitCorrection(self, p0: CorrectionInfo) -> None: ...
    def beginBatchEdit(self) -> None: ...
    def endBatchEdit(self) -> None: ...
    def onBeginBatchEdit(self) -> None: ...
    def onEndBatchEdit(self) -> None: ...
    def onPrivateIMECommand(self, p0: str, p1: Bundle) -> bool: ...
    def setIncludeFontPadding(self, p0: bool) -> None: ...
    def getIncludeFontPadding(self) -> bool: ...
    @overload
    def bringPointIntoView(self, p0: int) -> bool: ...
    @overload
    def bringPointIntoView(self, p0: int, p1: bool) -> bool: ...
    def moveCursorToVisibleOffset(self) -> bool: ...
    def getSelectionStart(self) -> int: ...
    def getSelectionEnd(self) -> int: ...
    def hasSelection(self) -> bool: ...
    @overload
    def setSingleLine(self, p0: bool) -> None: ...
    @overload
    def setSingleLine(self) -> None: ...
    def setAllCaps(self, p0: bool) -> None: ...
    def isAllCaps(self) -> bool: ...
    def setEllipsize(self, p0: Any) -> None: ...
    def setMarqueeRepeatLimit(self, p0: int) -> None: ...
    def getMarqueeRepeatLimit(self) -> int: ...
    def getEllipsize(self) -> Any: ...
    def setSelectAllOnFocus(self, p0: bool) -> None: ...
    def setCursorVisible(self, p0: bool) -> None: ...
    def isCursorVisible(self) -> bool: ...
    def addTextChangedListener(self, p0: TextWatcher) -> None: ...
    def removeTextChangedListener(self, p0: TextWatcher) -> None: ...
    def clearComposingText(self) -> None: ...
    def didTouchFocusSelect(self) -> bool: ...
    def setScroller(self, p0: Scroller) -> None: ...
    def isInputMethodTarget(self) -> bool: ...
    def onTextContextMenuItem(self, p0: int) -> bool: ...
    def isSuggestionsEnabled(self) -> bool: ...
    def setCustomSelectionActionModeCallback(self, p0: Any) -> None: ...
    def getCustomSelectionActionModeCallback(self) -> Any: ...
    def setCustomInsertionActionModeCallback(self, p0: Any) -> None: ...
    def getCustomInsertionActionModeCallback(self) -> Any: ...
    def setTextClassifier(self, p0: TextClassifier) -> None: ...
    def getTextClassifier(self) -> TextClassifier: ...
    def getOffsetForPosition(self, p0: float, p1: float) -> int: ...
    def getTextDirectionHeuristic(self) -> TextDirectionHeuristic: ...
    @overload
    def setError(self, p0: str) -> None: ...
    @overload
    def setError(self, p0: str, p1: Drawable) -> None: ...
    def getGravity(self) -> int: ...
    def setGravity(self, p0: int) -> None: ...
    def length(self) -> int: ...
    @overload
    def append(self, p0: str) -> None: ...
    @overload
    def append(self, p0: str, p1: int, p2: int) -> None: ...
    def debug(self, p0: int) -> None: ...

    class SavedState:
        CREATOR: ClassVar[Any]
        CREATOR: ClassVar[Any]
        CREATOR: ClassVar[Any]
        EMPTY_STATE: ClassVar[AbsSavedState]
        CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
        PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
        def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
        def toString(self) -> str: ...

    class OnEditorActionListener:
        def onEditorAction(self, p0: "TextView", p1: int, p2: KeyEvent) -> bool: ...

    class BufferType:
        NORMAL: ClassVar["BufferType"]
        SPANNABLE: ClassVar["BufferType"]
        EDITABLE: ClassVar["BufferType"]
        NORMAL: ClassVar[Any]
        SPANNABLE: ClassVar[Any]
        EDITABLE: ClassVar[Any]
        @staticmethod
        def values() -> Any: ...
        @staticmethod
        def valueOf(p0: str) -> Any: ...
