from typing import Any, ClassVar, overload
from android.net.Network import Network
from android.os.Parcel import Parcel
from java.net.InetAddress import InetAddress

class NsdServiceInfo:
    CREATOR: ClassVar[Any]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    def __init__(self) -> None: ...
    def getServiceType(self) -> str: ...
    def setServiceType(self, p0: str) -> None: ...
    def getHostAddresses(self) -> list: ...
    def setHostAddresses(self, p0: list) -> None: ...
    def setNetwork(self, p0: Network) -> None: ...
    def setHost(self, p0: InetAddress) -> None: ...
    def removeAttribute(self, p0: str) -> None: ...
    def setSubtypes(self, p0: set) -> None: ...
    def getSubtypes(self) -> set: ...
    def setServiceName(self, p0: str) -> None: ...
    def setPort(self, p0: int) -> None: ...
    def getNetwork(self) -> Network: ...
    def getServiceName(self) -> str: ...
    def toString(self) -> str: ...
    def getHost(self) -> InetAddress: ...
    def getPort(self) -> int: ...
    def getAttributes(self) -> dict: ...
    def setAttribute(self, p0: str, p1: str) -> None: ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
