from typing import Any, ClassVar, overload
from android.health.connect.datatypes.units.Length import Length
from java.time.Instant import Instant

class ExerciseLap:
    def equals(self, p0: Any) -> bool: ...
    def hashCode(self) -> int: ...
    def getLength(self) -> Length: ...
    def getStartTime(self) -> Instant: ...
    def getEndTime(self) -> Instant: ...

    class Builder:
        def __init__(self, p0: Instant, p1: Instant) -> None: ...
        def setLength(self, p0: Length) -> Any: ...
        def build(self) -> "ExerciseLap": ...
