from typing import Any, ClassVar, overload
from android.health.connect.datatypes.AggregationType import AggregationType
from android.health.connect.datatypes.Metadata import Metadata
from java.time.Instant import Instant
from java.time.ZoneOffset import ZoneOffset

class MindfulnessSessionRecord:
    MINDFULNESS_DURATION_TOTAL: ClassVar[AggregationType]
    MINDFULNESS_SESSION_TYPE_BREATHING: ClassVar[int]
    MINDFULNESS_SESSION_TYPE_MEDITATION: ClassVar[int]
    MINDFULNESS_SESSION_TYPE_MOVEMENT: ClassVar[int]
    MINDFULNESS_SESSION_TYPE_MUSIC: ClassVar[int]
    MINDFULNESS_SESSION_TYPE_OTHER: ClassVar[int]
    MINDFULNESS_SESSION_TYPE_UNGUIDED: ClassVar[int]
    MINDFULNESS_SESSION_TYPE_UNKNOWN: ClassVar[int]
    def equals(self, p0: Any) -> bool: ...
    def hashCode(self) -> int: ...
    def getTitle(self) -> str: ...
    def getNotes(self) -> str: ...
    def getMindfulnessSessionType(self) -> int: ...

    class Builder:
        def __init__(self, p0: Metadata, p1: Instant, p2: Instant, p3: int) -> None: ...
        def setTitle(self, p0: str) -> Any: ...
        def build(self) -> "MindfulnessSessionRecord": ...
        def setEndZoneOffset(self, p0: ZoneOffset) -> Any: ...
        def setNotes(self, p0: str) -> Any: ...
        def setStartZoneOffset(self, p0: ZoneOffset) -> Any: ...
