from typing import Any, ClassVar, overload
from android.health.connect.datatypes.AggregationType import AggregationType
from android.health.connect.datatypes.Metadata import Metadata
from java.time.Instant import Instant
from java.time.ZoneOffset import ZoneOffset

class RestingHeartRateRecord:
    BPM_AVG: ClassVar[AggregationType]
    BPM_MAX: ClassVar[AggregationType]
    BPM_MIN: ClassVar[AggregationType]
    def equals(self, p0: Any) -> bool: ...
    def hashCode(self) -> int: ...
    def getBeatsPerMinute(self) -> int: ...

    class Builder:
        def __init__(self, p0: Metadata, p1: Instant, p2: int) -> None: ...
        def build(self) -> "RestingHeartRateRecord": ...
        def clearZoneOffset(self) -> Any: ...
        def setZoneOffset(self, p0: ZoneOffset) -> Any: ...
