from typing import Any, ClassVar, overload
from android.os.IBinder import IBinder
from android.os.Parcel import Parcel
from android.os.Parcelable import Parcelable
from android.os.PersistableBundle import PersistableBundle
from android.util.Size import Size
from android.util.SizeF import SizeF
from android.util.SparseArray import SparseArray
from java.io.Serializable import Serializable
from java.lang.ClassLoader import ClassLoader

class Bundle:
    CREATOR: ClassVar[Any]
    EMPTY: ClassVar["Bundle"]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    @overload
    def __init__(self, p0: ClassLoader) -> None: ...
    @overload
    def __init__(self, p0: int) -> None: ...
    @overload
    def __init__(self, p0: PersistableBundle) -> None: ...
    @overload
    def __init__(self, p0: "Bundle") -> None: ...
    @overload
    def __init__(self) -> None: ...
    def remove(self, p0: str) -> None: ...
    def toString(self) -> str: ...
    def clone(self) -> Any: ...
    @overload
    def getByte(self, p0: str) -> int: ...
    @overload
    def getByte(self, p0: str, p1: int) -> int: ...
    def putByte(self, p0: str, p1: int) -> None: ...
    @overload
    def getShort(self, p0: str, p1: int) -> int: ...
    @overload
    def getShort(self, p0: str) -> int: ...
    def putShort(self, p0: str, p1: int) -> None: ...
    @overload
    def getChar(self, p0: str, p1: str) -> str: ...
    @overload
    def getChar(self, p0: str) -> str: ...
    def putChar(self, p0: str, p1: str) -> None: ...
    @overload
    def getFloat(self, p0: str, p1: float) -> float: ...
    @overload
    def getFloat(self, p0: str) -> float: ...
    def putFloat(self, p0: str, p1: float) -> None: ...
    def clear(self) -> None: ...
    def getClassLoader(self) -> ClassLoader: ...
    def putAll(self, p0: "Bundle") -> None: ...
    def getSize(self, p0: str) -> Size: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
    def putCharSequence(self, p0: str, p1: str) -> None: ...
    @overload
    def getParcelable(self, p0: str, p1: type) -> Any: ...
    @overload
    def getParcelable(self, p0: str) -> Parcelable: ...
    def setClassLoader(self, p0: ClassLoader) -> None: ...
    def readFromParcel(self, p0: Parcel) -> None: ...
    def putCharArray(self, p0: str, p1: Any) -> None: ...
    def putStringArrayList(self, p0: str, p1: list) -> None: ...
    def putSizeF(self, p0: str, p1: SizeF) -> None: ...
    def putSize(self, p0: str, p1: Size) -> None: ...
    def putShortArray(self, p0: str, p1: Any) -> None: ...
    def putSerializable(self, p0: str, p1: Serializable) -> None: ...
    def putParcelableArray(self, p0: str, p1: Any) -> None: ...
    def putParcelable(self, p0: str, p1: Parcelable) -> None: ...
    def putFloatArray(self, p0: str, p1: Any) -> None: ...
    def putByteArray(self, p0: str, p1: Any) -> None: ...
    def hasFileDescriptors(self) -> bool: ...
    def putBundle(self, p0: str, p1: "Bundle") -> None: ...
    def putBinder(self, p0: str, p1: IBinder) -> None: ...
    def getStringArrayList(self, p0: str) -> list: ...
    def getSizeF(self, p0: str) -> SizeF: ...
    def getShortArray(self, p0: str) -> Any: ...
    @overload
    def getSerializable(self, p0: str, p1: type) -> Serializable: ...
    @overload
    def getSerializable(self, p0: str) -> Serializable: ...
    @overload
    def getParcelableArray(self, p0: str, p1: type) -> Any: ...
    @overload
    def getParcelableArray(self, p0: str) -> Any: ...
    def getFloatArray(self, p0: str) -> Any: ...
    @overload
    def getCharSequence(self, p0: str) -> str: ...
    @overload
    def getCharSequence(self, p0: str, p1: str) -> str: ...
    def getCharArray(self, p0: str) -> Any: ...
    def getByteArray(self, p0: str) -> Any: ...
    def getBundle(self, p0: str) -> "Bundle": ...
    def deepCopy(self) -> "Bundle": ...
    def describeContents(self) -> int: ...
    def getBinder(self, p0: str) -> IBinder: ...
    def getCharSequenceArray(self, p0: str) -> Any: ...
    def getCharSequenceArrayList(self, p0: str) -> list: ...
    def getIntegerArrayList(self, p0: str) -> list: ...
    @overload
    def getParcelableArrayList(self, p0: str, p1: type) -> list: ...
    @overload
    def getParcelableArrayList(self, p0: str) -> list: ...
    @overload
    def getSparseParcelableArray(self, p0: str) -> SparseArray: ...
    @overload
    def getSparseParcelableArray(self, p0: str, p1: type) -> SparseArray: ...
    def putCharSequenceArray(self, p0: str, p1: Any) -> None: ...
    def putCharSequenceArrayList(self, p0: str, p1: list) -> None: ...
    def putIntegerArrayList(self, p0: str, p1: list) -> None: ...
    def putParcelableArrayList(self, p0: str, p1: list) -> None: ...
    def putSparseParcelableArray(self, p0: str, p1: SparseArray) -> None: ...
