from typing import Any, ClassVar, overload

class CpuHeadroomParams:
    CPU_HEADROOM_CALCULATION_TYPE_AVERAGE: ClassVar[int]
    CPU_HEADROOM_CALCULATION_TYPE_MIN: ClassVar[int]
    def getCalculationWindowMillis(self) -> int: ...
    def getTids(self) -> Any: ...
    def getCalculationType(self) -> int: ...
    def equals(self, p0: Any) -> bool: ...
    def toString(self) -> str: ...
    def hashCode(self) -> int: ...
    def toBuilder(self) -> Any: ...

    class Builder:
        @overload
        def __init__(self) -> None: ...
        @overload
        def __init__(self, p0: "CpuHeadroomParams") -> None: ...
        def setCalculationType(self, p0: int) -> Any: ...
        def setTids(self, p0: Any) -> Any: ...
        def setCalculationWindowMillis(self, p0: int) -> Any: ...
        def build(self) -> "CpuHeadroomParams": ...
