from typing import Any, ClassVar, overload
from android.content.Context import Context
from android.content.Intent import Intent
from android.os.Parcel import Parcel
from android.os.UserHandle import UserHandle
from java.io.File import File
from java.util.UUID import UUID

class StorageVolume:
    CREATOR: ClassVar[Any]
    EXTRA_STORAGE_VOLUME: ClassVar[str]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    def isRemovable(self) -> bool: ...
    def createOpenDocumentTreeIntent(self) -> Intent: ...
    def getDirectory(self) -> File: ...
    def getMediaStoreVolumeName(self) -> str: ...
    def getStorageUuid(self) -> UUID: ...
    def isEmulated(self) -> bool: ...
    def createAccessIntent(self, p0: str) -> Intent: ...
    def getUuid(self) -> str: ...
    def isPrimary(self) -> bool: ...
    def equals(self, p0: Any) -> bool: ...
    def toString(self) -> str: ...
    def hashCode(self) -> int: ...
    def getState(self) -> str: ...
    def getOwner(self) -> UserHandle: ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
    def getDescription(self, p0: Context) -> str: ...

from typing import Any, ClassVar, overload
from android.app.PendingIntent import PendingIntent
from android.net.Uri import Uri
from android.os.Handler import Handler
from android.os.ParcelFileDescriptor import ParcelFileDescriptor
from android.os.ProxyFileDescriptorCallback import ProxyFileDescriptorCallback
from android.os.storage.OnObbStateChangeListener import OnObbStateChangeListener
from android.os.storage.StorageVolume import StorageVolume
from java.io.File import File
from java.io.FileDescriptor import FileDescriptor
from java.util.UUID import UUID
from java.util.concurrent.Executor import Executor

class StorageManager:
    ACTION_CLEAR_APP_CACHE: ClassVar[str]
    ACTION_MANAGE_STORAGE: ClassVar[str]
    EXTRA_REQUESTED_BYTES: ClassVar[str]
    EXTRA_UUID: ClassVar[str]
    UUID_DEFAULT: ClassVar[UUID]
    @overload
    def allocateBytes(self, p0: FileDescriptor, p1: int) -> None: ...
    @overload
    def allocateBytes(self, p0: UUID, p1: int) -> None: ...
    def getAllocatableBytes(self, p0: UUID) -> int: ...
    def getCacheQuotaBytes(self, p0: UUID) -> int: ...
    def getCacheSizeBytes(self, p0: UUID) -> int: ...
    def getManageSpaceActivityIntent(self, p0: str, p1: int) -> PendingIntent: ...
    def getMountedObbPath(self, p0: str) -> str: ...
    def getPrimaryStorageVolume(self) -> StorageVolume: ...
    def getRecentStorageVolumes(self) -> list: ...
    @overload
    def getStorageVolume(self, p0: Uri) -> StorageVolume: ...
    @overload
    def getStorageVolume(self, p0: File) -> StorageVolume: ...
    def getStorageVolumes(self) -> list: ...
    def getStorageVolumesIncludingSharedProfiles(self) -> list: ...
    def getUuidForPath(self, p0: File) -> UUID: ...
    def isAllocationSupported(self, p0: FileDescriptor) -> bool: ...
    def isCacheBehaviorGroup(self, p0: File) -> bool: ...
    def isCacheBehaviorTombstone(self, p0: File) -> bool: ...
    def isCheckpointSupported(self) -> bool: ...
    def isEncrypted(self, p0: File) -> bool: ...
    def isObbMounted(self, p0: str) -> bool: ...
    def mountObb(self, p0: str, p1: str, p2: OnObbStateChangeListener) -> bool: ...
    def openProxyFileDescriptor(self, p0: int, p1: ProxyFileDescriptorCallback, p2: Handler) -> ParcelFileDescriptor: ...
    def registerStorageVolumeCallback(self, p0: Executor, p1: Any) -> None: ...
    def setCacheBehaviorGroup(self, p0: File, p1: bool) -> None: ...
    def setCacheBehaviorTombstone(self, p0: File, p1: bool) -> None: ...
    def unmountObb(self, p0: str, p1: bool, p2: OnObbStateChangeListener) -> bool: ...
    def unregisterStorageVolumeCallback(self, p0: Any) -> None: ...

    class StorageVolumeCallback:
        def __init__(self) -> None: ...
        def onStateChanged(self, p0: StorageVolume) -> None: ...

from typing import Any, ClassVar, overload

class OnObbStateChangeListener:
    ERROR_ALREADY_MOUNTED: ClassVar[int]
    ERROR_COULD_NOT_MOUNT: ClassVar[int]
    ERROR_COULD_NOT_UNMOUNT: ClassVar[int]
    ERROR_INTERNAL: ClassVar[int]
    ERROR_NOT_MOUNTED: ClassVar[int]
    ERROR_PERMISSION_DENIED: ClassVar[int]
    MOUNTED: ClassVar[int]
    UNMOUNTED: ClassVar[int]
    def __init__(self) -> None: ...
    def onObbStateChange(self, p0: str, p1: int) -> None: ...

