from typing import Any, ClassVar, overload
from android.os.CombinedVibration import CombinedVibration
from android.os.VibrationAttributes import VibrationAttributes
from android.os.Vibrator import Vibrator

class VibratorManager:
    def getVibratorIds(self) -> Any: ...
    def getDefaultVibrator(self) -> Vibrator: ...
    @overload
    def vibrate(self, p0: CombinedVibration, p1: VibrationAttributes) -> None: ...
    @overload
    def vibrate(self, p0: CombinedVibration) -> None: ...
    def getVibrator(self, p0: int) -> Vibrator: ...
    def cancel(self) -> None: ...
