from typing import Any, ClassVar, overload
from android.content.Context import Context
from android.net.Network import Network
from android.net.http.ConnectionMigrationOptions import ConnectionMigrationOptions
from android.net.http.DnsOptions import DnsOptions
from android.net.http.QuicOptions import QuicOptions
from java.net.URL import URL
from java.net.URLConnection import URLConnection
from java.net.URLStreamHandlerFactory import URLStreamHandlerFactory
from java.time.Instant import Instant
from java.util.concurrent.Executor import Executor

class HttpEngine:
    @staticmethod
    def getVersionString() -> str: ...
    def bindToNetwork(self, p0: Network) -> None: ...
    def createUrlStreamHandlerFactory(self) -> URLStreamHandlerFactory: ...
    def newBidirectionalStreamBuilder(self, p0: str, p1: Executor, p2: Any) -> Any: ...
    def newUrlRequestBuilder(self, p0: str, p1: Executor, p2: Any) -> Any: ...
    def shutdown(self) -> None: ...
    def openConnection(self, p0: URL) -> URLConnection: ...

    class Builder:
        HTTP_CACHE_DISABLED: ClassVar[int]
        HTTP_CACHE_DISK: ClassVar[int]
        HTTP_CACHE_DISK_NO_HTTP: ClassVar[int]
        HTTP_CACHE_IN_MEMORY: ClassVar[int]
        def __init__(self, p0: Context) -> None: ...
        def addQuicHint(self, p0: str, p1: int, p2: int) -> Any: ...
        def setConnectionMigrationOptions(self, p0: ConnectionMigrationOptions) -> Any: ...
        def addPublicKeyPins(self, p0: str, p1: set, p2: bool, p3: Instant) -> Any: ...
        def setDnsOptions(self, p0: DnsOptions) -> Any: ...
        def setEnableBrotli(self, p0: bool) -> Any: ...
        def setEnableHttp2(self, p0: bool) -> Any: ...
        def setEnableHttpCache(self, p0: int, p1: int) -> Any: ...
        def setEnablePublicKeyPinningBypassForLocalTrustAnchors(self, p0: bool) -> Any: ...
        def setEnableQuic(self, p0: bool) -> Any: ...
        def setQuicOptions(self, p0: QuicOptions) -> Any: ...
        def setStoragePath(self, p0: str) -> Any: ...
        def setUserAgent(self, p0: str) -> Any: ...
        def getDefaultUserAgent(self) -> str: ...
        def build(self) -> "HttpEngine": ...
