from typing import Any, ClassVar, overload
from java.util.stream.DoubleStream import DoubleStream
from java.util.stream.IntStream import IntStream
from java.util.stream.LongStream import LongStream
from java.util.stream.Stream import Stream

class RandomGenerator:
    def nextBoolean(self) -> bool: ...
    @overload
    def nextLong(self) -> int: ...
    @overload
    def nextLong(self, p0: int, p1: int) -> int: ...
    @overload
    def nextLong(self, p0: int) -> int: ...
    @overload
    def longs(self) -> LongStream: ...
    @overload
    def longs(self, p0: int, p1: int) -> LongStream: ...
    @overload
    def longs(self, p0: int) -> LongStream: ...
    @overload
    def longs(self, p0: int, p1: int, p2: int) -> LongStream: ...
    @overload
    def nextFloat(self, p0: float) -> float: ...
    @overload
    def nextFloat(self, p0: float, p1: float) -> float: ...
    @overload
    def nextFloat(self) -> float: ...
    @overload
    def ints(self, p0: int, p1: int) -> IntStream: ...
    @overload
    def ints(self) -> IntStream: ...
    @overload
    def ints(self, p0: int) -> IntStream: ...
    @overload
    def ints(self, p0: int, p1: int, p2: int) -> IntStream: ...
    @overload
    def doubles(self, p0: int, p1: float, p2: float) -> DoubleStream: ...
    @overload
    def doubles(self, p0: int) -> DoubleStream: ...
    @overload
    def doubles(self, p0: float, p1: float) -> DoubleStream: ...
    @overload
    def doubles(self) -> DoubleStream: ...
    @overload
    def nextGaussian(self) -> float: ...
    @overload
    def nextGaussian(self, p0: float, p1: float) -> float: ...
    def isDeprecated(self) -> bool: ...
    def nextExponential(self) -> float: ...
    @overload
    def nextDouble(self, p0: float, p1: float) -> float: ...
    @overload
    def nextDouble(self, p0: float) -> float: ...
    @overload
    def nextDouble(self) -> float: ...
    def nextBytes(self, p0: Any) -> None: ...
    @overload
    def nextInt(self, p0: int, p1: int) -> int: ...
    @overload
    def nextInt(self) -> int: ...
    @overload
    def nextInt(self, p0: int) -> int: ...
    @staticmethod
    def getDefault() -> "RandomGenerator": ...
    @staticmethod
    def of(p0: str) -> "RandomGenerator": ...

    class ArbitrarilyJumpableGenerator:
        def leap(self) -> None: ...
        @overload
        def jump(self) -> None: ...
        @overload
        def jump(self, p0: float) -> None: ...
        @overload
        def jumps(self, p0: int, p1: float) -> Stream: ...
        @overload
        def jumps(self, p0: float) -> Stream: ...
        def copyAndJump(self, p0: float) -> Any: ...
        def jumpPowerOfTwo(self, p0: int) -> None: ...
        @staticmethod
        def of(p0: str) -> Any: ...
        @overload
        def copy(self) -> Any: ...
        @overload
        def copy(self) -> Any: ...
        @overload
        def copy(self) -> Any: ...

    class LeapableGenerator:
        def leap(self) -> None: ...
        def leapDistance(self) -> float: ...
        @overload
        def leaps(self, p0: int) -> Stream: ...
        @overload
        def leaps(self) -> Stream: ...
        def copyAndLeap(self) -> Any: ...
        @staticmethod
        def of(p0: str) -> Any: ...
        @overload
        def copy(self) -> Any: ...
        @overload
        def copy(self) -> Any: ...

    class JumpableGenerator:
        @overload
        def rngs(self) -> Stream: ...
        @overload
        def rngs(self, p0: int) -> Stream: ...
        def jump(self) -> None: ...
        def jumpDistance(self) -> float: ...
        @overload
        def jumps(self, p0: int) -> Stream: ...
        @overload
        def jumps(self) -> Stream: ...
        def copyAndJump(self) -> "RandomGenerator": ...
        @staticmethod
        def of(p0: str) -> Any: ...
        def copy(self) -> Any: ...

    class SplittableGenerator:
        @overload
        def splits(self, p0: int, p1: Any) -> Stream: ...
        @overload
        def splits(self, p0: int) -> Stream: ...
        @overload
        def splits(self) -> Stream: ...
        @overload
        def splits(self, p0: Any) -> Stream: ...
        @overload
        def rngs(self, p0: int) -> Stream: ...
        @overload
        def rngs(self) -> Stream: ...
        @overload
        def split(self) -> Any: ...
        @overload
        def split(self, p0: Any) -> Any: ...
        @staticmethod
        def of(p0: str) -> Any: ...

    class StreamableGenerator:
        @overload
        def rngs(self) -> Stream: ...
        @overload
        def rngs(self, p0: int) -> Stream: ...
        @staticmethod
        def of(p0: str) -> Any: ...
