# cython: language_level=3
# Generated by jni-wrap cython — do not edit by hand.

from jni_core._core cimport (
    JavaObject, get_env, check_jni_exc,
    find_class_global, get_method_id, get_static_method_id,
    get_field_id, get_static_field_id, j_str, py_str,
)
from jni_core._dispatch cimport (
    jnicore_NewObjectA, jnicore_DeleteLocalRef, jnicore_NewGlobalRef,
    jnicore_CallVoidMethodA, jnicore_CallObjectMethodA,
    jnicore_CallBooleanMethodA, jnicore_CallByteMethodA,
    jnicore_CallCharMethodA, jnicore_CallShortMethodA,
    jnicore_CallIntMethodA, jnicore_CallLongMethodA,
    jnicore_CallFloatMethodA, jnicore_CallDoubleMethodA,
    jnicore_CallStaticVoidMethodA, jnicore_CallStaticObjectMethodA,
    jnicore_CallStaticBooleanMethodA, jnicore_CallStaticByteMethodA,
    jnicore_CallStaticCharMethodA, jnicore_CallStaticShortMethodA,
    jnicore_CallStaticIntMethodA, jnicore_CallStaticLongMethodA,
    jnicore_CallStaticFloatMethodA, jnicore_CallStaticDoubleMethodA,
    jnicore_GetObjectField, jnicore_SetObjectField,
    jnicore_GetBooleanField, jnicore_SetBooleanField,
    jnicore_GetByteField, jnicore_SetByteField,
    jnicore_GetCharField, jnicore_SetCharField,
    jnicore_GetShortField, jnicore_SetShortField,
    jnicore_GetIntField, jnicore_SetIntField,
    jnicore_GetLongField, jnicore_SetLongField,
    jnicore_GetFloatField, jnicore_SetFloatField,
    jnicore_GetDoubleField, jnicore_SetDoubleField,
    jnicore_GetStaticObjectField, jnicore_SetStaticObjectField,
    jnicore_GetStaticBooleanField, jnicore_SetStaticBooleanField,
    jnicore_GetStaticByteField, jnicore_SetStaticByteField,
    jnicore_GetStaticCharField, jnicore_SetStaticCharField,
    jnicore_GetStaticShortField, jnicore_SetStaticShortField,
    jnicore_GetStaticIntField, jnicore_SetStaticIntField,
    jnicore_GetStaticLongField, jnicore_SetStaticLongField,
    jnicore_GetStaticFloatField, jnicore_SetStaticFloatField,
    jnicore_GetStaticDoubleField, jnicore_SetStaticDoubleField,
)
from jni_core.jni cimport (
    jclass, jobject, jmethodID, jfieldID, jvalue, JNIEnv,
    jboolean, jbyte, jchar, jshort, jint, jlong, jfloat, jdouble, jstring,
)

include "jni_core/conversions.pxi"

__javaclass__ = "android/media/metrics/PlaybackSession"  # android.media.metrics.PlaybackSession

cdef jclass _cls_PlaybackSession = NULL
cdef jmethodID _m_PlaybackSession_reportNetworkEvent_0 = NULL
cdef jmethodID _m_PlaybackSession_reportPlaybackErrorEvent_0 = NULL
cdef jmethodID _m_PlaybackSession_reportPlaybackMetrics_0 = NULL
cdef jmethodID _m_PlaybackSession_reportPlaybackStateEvent_0 = NULL
cdef jmethodID _m_PlaybackSession_reportTrackChangeEvent_0 = NULL
cdef jmethodID _m_PlaybackSession_equals_0 = NULL
cdef jmethodID _m_PlaybackSession_hashCode_0 = NULL
cdef jmethodID _m_PlaybackSession_close_0 = NULL
cdef jmethodID _m_PlaybackSession_getSessionId_0 = NULL

cdef int _ensure_ids_PlaybackSession(JNIEnv* env) except -1:
    global _cls_PlaybackSession, _m_PlaybackSession_reportNetworkEvent_0, _m_PlaybackSession_reportPlaybackErrorEvent_0, _m_PlaybackSession_reportPlaybackMetrics_0, _m_PlaybackSession_reportPlaybackStateEvent_0, _m_PlaybackSession_reportTrackChangeEvent_0, _m_PlaybackSession_equals_0, _m_PlaybackSession_hashCode_0, _m_PlaybackSession_close_0, _m_PlaybackSession_getSessionId_0
    if _cls_PlaybackSession != NULL:
        return 0
    _cls_PlaybackSession = find_class_global(env, b"android/media/metrics/PlaybackSession")
    _m_PlaybackSession_reportNetworkEvent_0 = get_method_id(env, _cls_PlaybackSession, b"reportNetworkEvent", b"(Landroid/media/metrics/NetworkEvent;)V")
    _m_PlaybackSession_reportPlaybackErrorEvent_0 = get_method_id(env, _cls_PlaybackSession, b"reportPlaybackErrorEvent", b"(Landroid/media/metrics/PlaybackErrorEvent;)V")
    _m_PlaybackSession_reportPlaybackMetrics_0 = get_method_id(env, _cls_PlaybackSession, b"reportPlaybackMetrics", b"(Landroid/media/metrics/PlaybackMetrics;)V")
    _m_PlaybackSession_reportPlaybackStateEvent_0 = get_method_id(env, _cls_PlaybackSession, b"reportPlaybackStateEvent", b"(Landroid/media/metrics/PlaybackStateEvent;)V")
    _m_PlaybackSession_reportTrackChangeEvent_0 = get_method_id(env, _cls_PlaybackSession, b"reportTrackChangeEvent", b"(Landroid/media/metrics/TrackChangeEvent;)V")
    _m_PlaybackSession_equals_0 = get_method_id(env, _cls_PlaybackSession, b"equals", b"(Ljava/lang/Object;)Z")
    _m_PlaybackSession_hashCode_0 = get_method_id(env, _cls_PlaybackSession, b"hashCode", b"()I")
    _m_PlaybackSession_close_0 = get_method_id(env, _cls_PlaybackSession, b"close", b"()V")
    _m_PlaybackSession_getSessionId_0 = get_method_id(env, _cls_PlaybackSession, b"getSessionId", b"()Landroid/media/metrics/LogSessionId;")
    return 0

cdef class PlaybackSession(JavaObject):
    """android.media.metrics.PlaybackSession"""

    def __init__(self, *args, **kwargs):
        raise TypeError("PlaybackSession has no public constructor")

    cdef void _reportNetworkEvent(self, JNIEnv* env, jobject p0) except *:
        _ensure_ids_PlaybackSession(env)
        cdef jvalue _args[1]
        _args[0].l = p0
        jnicore_CallVoidMethodA(env, self._handle, _m_PlaybackSession_reportNetworkEvent_0, _args)
        check_jni_exc(env)

    def reportNetworkEvent(self, p0) -> None:
        cdef JNIEnv* env = get_env()
        cdef jobject _h0 = (<JavaObject?>p0)._handle if p0 is not None else <jobject>NULL
        self._reportNetworkEvent(env, _h0)

    cdef void _reportNetworkEvent_0(self, JNIEnv* env, jobject p0) except *:
        _ensure_ids_PlaybackSession(env)
        cdef jvalue _args[1]
        _args[0].l = p0
        jnicore_CallVoidMethodA(env, self._handle, _m_PlaybackSession_reportNetworkEvent_0, _args)
        check_jni_exc(env)

    def reportNetworkEvent_0(self, p0) -> None:
        cdef JNIEnv* env = get_env()
        cdef jobject _h0 = (<JavaObject?>p0)._handle if p0 is not None else <jobject>NULL
        self._reportNetworkEvent_0(env, _h0)

    cdef void _reportPlaybackErrorEvent(self, JNIEnv* env, jobject p0) except *:
        _ensure_ids_PlaybackSession(env)
        cdef jvalue _args[1]
        _args[0].l = p0
        jnicore_CallVoidMethodA(env, self._handle, _m_PlaybackSession_reportPlaybackErrorEvent_0, _args)
        check_jni_exc(env)

    def reportPlaybackErrorEvent(self, p0) -> None:
        cdef JNIEnv* env = get_env()
        cdef jobject _h0 = (<JavaObject?>p0)._handle if p0 is not None else <jobject>NULL
        self._reportPlaybackErrorEvent(env, _h0)

    cdef void _reportPlaybackErrorEvent_0(self, JNIEnv* env, jobject p0) except *:
        _ensure_ids_PlaybackSession(env)
        cdef jvalue _args[1]
        _args[0].l = p0
        jnicore_CallVoidMethodA(env, self._handle, _m_PlaybackSession_reportPlaybackErrorEvent_0, _args)
        check_jni_exc(env)

    def reportPlaybackErrorEvent_0(self, p0) -> None:
        cdef JNIEnv* env = get_env()
        cdef jobject _h0 = (<JavaObject?>p0)._handle if p0 is not None else <jobject>NULL
        self._reportPlaybackErrorEvent_0(env, _h0)

    cdef void _reportPlaybackMetrics(self, JNIEnv* env, jobject p0) except *:
        _ensure_ids_PlaybackSession(env)
        cdef jvalue _args[1]
        _args[0].l = p0
        jnicore_CallVoidMethodA(env, self._handle, _m_PlaybackSession_reportPlaybackMetrics_0, _args)
        check_jni_exc(env)

    def reportPlaybackMetrics(self, p0) -> None:
        cdef JNIEnv* env = get_env()
        cdef jobject _h0 = (<JavaObject?>p0)._handle if p0 is not None else <jobject>NULL
        self._reportPlaybackMetrics(env, _h0)

    cdef void _reportPlaybackMetrics_0(self, JNIEnv* env, jobject p0) except *:
        _ensure_ids_PlaybackSession(env)
        cdef jvalue _args[1]
        _args[0].l = p0
        jnicore_CallVoidMethodA(env, self._handle, _m_PlaybackSession_reportPlaybackMetrics_0, _args)
        check_jni_exc(env)

    def reportPlaybackMetrics_0(self, p0) -> None:
        cdef JNIEnv* env = get_env()
        cdef jobject _h0 = (<JavaObject?>p0)._handle if p0 is not None else <jobject>NULL
        self._reportPlaybackMetrics_0(env, _h0)

    cdef void _reportPlaybackStateEvent(self, JNIEnv* env, jobject p0) except *:
        _ensure_ids_PlaybackSession(env)
        cdef jvalue _args[1]
        _args[0].l = p0
        jnicore_CallVoidMethodA(env, self._handle, _m_PlaybackSession_reportPlaybackStateEvent_0, _args)
        check_jni_exc(env)

    def reportPlaybackStateEvent(self, p0) -> None:
        cdef JNIEnv* env = get_env()
        cdef jobject _h0 = (<JavaObject?>p0)._handle if p0 is not None else <jobject>NULL
        self._reportPlaybackStateEvent(env, _h0)

    cdef void _reportPlaybackStateEvent_0(self, JNIEnv* env, jobject p0) except *:
        _ensure_ids_PlaybackSession(env)
        cdef jvalue _args[1]
        _args[0].l = p0
        jnicore_CallVoidMethodA(env, self._handle, _m_PlaybackSession_reportPlaybackStateEvent_0, _args)
        check_jni_exc(env)

    def reportPlaybackStateEvent_0(self, p0) -> None:
        cdef JNIEnv* env = get_env()
        cdef jobject _h0 = (<JavaObject?>p0)._handle if p0 is not None else <jobject>NULL
        self._reportPlaybackStateEvent_0(env, _h0)

    cdef void _reportTrackChangeEvent(self, JNIEnv* env, jobject p0) except *:
        _ensure_ids_PlaybackSession(env)
        cdef jvalue _args[1]
        _args[0].l = p0
        jnicore_CallVoidMethodA(env, self._handle, _m_PlaybackSession_reportTrackChangeEvent_0, _args)
        check_jni_exc(env)

    def reportTrackChangeEvent(self, p0) -> None:
        cdef JNIEnv* env = get_env()
        cdef jobject _h0 = (<JavaObject?>p0)._handle if p0 is not None else <jobject>NULL
        self._reportTrackChangeEvent(env, _h0)

    cdef void _reportTrackChangeEvent_0(self, JNIEnv* env, jobject p0) except *:
        _ensure_ids_PlaybackSession(env)
        cdef jvalue _args[1]
        _args[0].l = p0
        jnicore_CallVoidMethodA(env, self._handle, _m_PlaybackSession_reportTrackChangeEvent_0, _args)
        check_jni_exc(env)

    def reportTrackChangeEvent_0(self, p0) -> None:
        cdef JNIEnv* env = get_env()
        cdef jobject _h0 = (<JavaObject?>p0)._handle if p0 is not None else <jobject>NULL
        self._reportTrackChangeEvent_0(env, _h0)

    cdef jboolean _equals(self, JNIEnv* env, jobject p0) except *:
        _ensure_ids_PlaybackSession(env)
        cdef jvalue _args[1]
        _args[0].l = p0
        cdef jboolean _ret = jnicore_CallBooleanMethodA(env, self._handle, _m_PlaybackSession_equals_0, _args)
        check_jni_exc(env)
        return _ret

    def equals(self, p0) -> bool:
        cdef JNIEnv* env = get_env()
        cdef jboolean _ret = 0
        cdef jobject _h0 = (<JavaObject?>p0)._handle if p0 is not None else <jobject>NULL
        _ret = self._equals(env, _h0)
        return jboolean_to_py(_ret)

    cdef jboolean _equals_0(self, JNIEnv* env, jobject p0) except *:
        _ensure_ids_PlaybackSession(env)
        cdef jvalue _args[1]
        _args[0].l = p0
        cdef jboolean _ret = jnicore_CallBooleanMethodA(env, self._handle, _m_PlaybackSession_equals_0, _args)
        check_jni_exc(env)
        return _ret

    def equals_0(self, p0) -> bool:
        cdef JNIEnv* env = get_env()
        cdef jboolean _ret = 0
        cdef jobject _h0 = (<JavaObject?>p0)._handle if p0 is not None else <jobject>NULL
        _ret = self._equals_0(env, _h0)
        return jboolean_to_py(_ret)

    cdef jint _hashCode(self, JNIEnv* env) except *:
        _ensure_ids_PlaybackSession(env)
        cdef jvalue _args[1]  # zero-arg call; _args ignored by JNI
        cdef jint _ret = jnicore_CallIntMethodA(env, self._handle, _m_PlaybackSession_hashCode_0, _args)
        check_jni_exc(env)
        return _ret

    def hashCode(self) -> int:
        cdef JNIEnv* env = get_env()
        cdef jint _ret = 0
        _ret = self._hashCode(env)
        return <int>_ret

    cdef jint _hashCode_0(self, JNIEnv* env) except *:
        _ensure_ids_PlaybackSession(env)
        cdef jvalue _args[1]  # zero-arg call; _args ignored by JNI
        cdef jint _ret = jnicore_CallIntMethodA(env, self._handle, _m_PlaybackSession_hashCode_0, _args)
        check_jni_exc(env)
        return _ret

    def hashCode_0(self) -> int:
        cdef JNIEnv* env = get_env()
        cdef jint _ret = 0
        _ret = self._hashCode_0(env)
        return <int>_ret

    cdef void _close(self, JNIEnv* env) except *:
        _ensure_ids_PlaybackSession(env)
        cdef jvalue _args[1]  # zero-arg call; _args ignored by JNI
        jnicore_CallVoidMethodA(env, self._handle, _m_PlaybackSession_close_0, _args)
        check_jni_exc(env)

    def close(self) -> None:
        cdef JNIEnv* env = get_env()
        self._close(env)

    cdef void _close_0(self, JNIEnv* env) except *:
        _ensure_ids_PlaybackSession(env)
        cdef jvalue _args[1]  # zero-arg call; _args ignored by JNI
        jnicore_CallVoidMethodA(env, self._handle, _m_PlaybackSession_close_0, _args)
        check_jni_exc(env)

    def close_0(self) -> None:
        cdef JNIEnv* env = get_env()
        self._close_0(env)

    cdef jobject _getSessionId(self, JNIEnv* env) except? NULL:
        _ensure_ids_PlaybackSession(env)
        cdef jvalue _args[1]  # zero-arg call; _args ignored by JNI
        cdef jobject _ret = jnicore_CallObjectMethodA(env, self._handle, _m_PlaybackSession_getSessionId_0, _args)
        check_jni_exc(env)
        return _ret

    def getSessionId(self) -> object:
        cdef JNIEnv* env = get_env()
        cdef jobject _ret = NULL
        _ret = self._getSessionId(env)
        if _ret == NULL:
            return None
        cdef JavaObject _wrapped = JavaObject.__new__(JavaObject)
        _wrapped._adopt_local(env, _ret)
        return _wrapped

    cdef jobject _getSessionId_0(self, JNIEnv* env) except? NULL:
        _ensure_ids_PlaybackSession(env)
        cdef jvalue _args[1]  # zero-arg call; _args ignored by JNI
        cdef jobject _ret = jnicore_CallObjectMethodA(env, self._handle, _m_PlaybackSession_getSessionId_0, _args)
        check_jni_exc(env)
        return _ret

    def getSessionId_0(self) -> object:
        cdef JNIEnv* env = get_env()
        cdef jobject _ret = NULL
        _ret = self._getSessionId_0(env)
        if _ret == NULL:
            return None
        cdef JavaObject _wrapped = JavaObject.__new__(JavaObject)
        _wrapped._adopt_local(env, _ret)
        return _wrapped

    @staticmethod
    def from_java_object(obj) -> object:
        """Wrap a plain JavaObject as PlaybackSession (no JNI type check)."""
        cdef JNIEnv* env = get_env()
        cdef PlaybackSession inst = PlaybackSession.__new__(PlaybackSession)
        cdef jobject global_ref = jnicore_NewGlobalRef(env, (<JavaObject?>obj)._handle)
        inst._adopt_global(env, global_ref)
        return inst

