from typing import Any, ClassVar, overload
from android.adservices.ondevicepersonalization.RequestLogRecord import RequestLogRecord
from android.os.PersistableBundle import PersistableBundle

class EventInput:
    def getRequestLogRecord(self) -> RequestLogRecord: ...
    def equals(self, p0: Any) -> bool: ...
    def hashCode(self) -> int: ...
    def getParameters(self) -> PersistableBundle: ...
