from typing import Any, ClassVar, overload
from android.adservices.ondevicepersonalization.EventLogRecord import EventLogRecord
from android.adservices.ondevicepersonalization.RenderingConfig import RenderingConfig
from android.adservices.ondevicepersonalization.RequestLogRecord import RequestLogRecord

class ExecuteOutput:
    def getRequestLogRecord(self) -> RequestLogRecord: ...
    def getRenderingConfig(self) -> RenderingConfig: ...
    def getEventLogRecords(self) -> list: ...
    def getOutputData(self) -> Any: ...
    def equals(self, p0: Any) -> bool: ...
    def hashCode(self) -> int: ...

    class Builder:
        def __init__(self) -> None: ...
        def setRenderingConfig(self, p0: RenderingConfig) -> Any: ...
        def setOutputData(self, p0: Any) -> Any: ...
        def setRequestLogRecord(self, p0: RequestLogRecord) -> Any: ...
        def setEventLogRecords(self, p0: list) -> Any: ...
        def addEventLogRecord(self, p0: EventLogRecord) -> Any: ...
        def build(self) -> "ExecuteOutput": ...
