from typing import Any, ClassVar, overload
from android.content.Context import Context
from android.graphics.Bitmap import Bitmap
from android.hardware.biometrics.PromptContentView import PromptContentView
from android.os.CancellationSignal import CancellationSignal
from android.security.identity.IdentityCredential import IdentityCredential
from android.security.identity.PresentationSession import PresentationSession
from java.security.Signature import Signature
from java.util.concurrent.Executor import Executor
from javax.crypto.Cipher import Cipher
from javax.crypto.Mac import Mac

class BiometricPrompt:
    AUTHENTICATION_RESULT_TYPE_BIOMETRIC: ClassVar[int]
    AUTHENTICATION_RESULT_TYPE_DEVICE_CREDENTIAL: ClassVar[int]
    BIOMETRIC_ACQUIRED_GOOD: ClassVar[int]
    BIOMETRIC_ACQUIRED_IMAGER_DIRTY: ClassVar[int]
    BIOMETRIC_ACQUIRED_INSUFFICIENT: ClassVar[int]
    BIOMETRIC_ACQUIRED_PARTIAL: ClassVar[int]
    BIOMETRIC_ACQUIRED_TOO_FAST: ClassVar[int]
    BIOMETRIC_ACQUIRED_TOO_SLOW: ClassVar[int]
    BIOMETRIC_ERROR_CANCELED: ClassVar[int]
    BIOMETRIC_ERROR_HW_NOT_PRESENT: ClassVar[int]
    BIOMETRIC_ERROR_HW_UNAVAILABLE: ClassVar[int]
    BIOMETRIC_ERROR_LOCKOUT: ClassVar[int]
    BIOMETRIC_ERROR_LOCKOUT_PERMANENT: ClassVar[int]
    BIOMETRIC_ERROR_NO_BIOMETRICS: ClassVar[int]
    BIOMETRIC_ERROR_NO_DEVICE_CREDENTIAL: ClassVar[int]
    BIOMETRIC_ERROR_NO_SPACE: ClassVar[int]
    BIOMETRIC_ERROR_SECURITY_UPDATE_REQUIRED: ClassVar[int]
    BIOMETRIC_ERROR_TIMEOUT: ClassVar[int]
    BIOMETRIC_ERROR_UNABLE_TO_PROCESS: ClassVar[int]
    BIOMETRIC_ERROR_USER_CANCELED: ClassVar[int]
    BIOMETRIC_ERROR_VENDOR: ClassVar[int]
    BIOMETRIC_NO_AUTHENTICATION: ClassVar[int]
    def getLogoRes(self) -> int: ...
    def getLogoBitmap(self) -> Bitmap: ...
    def getNegativeButtonText(self) -> str: ...
    def isConfirmationRequired(self) -> bool: ...
    def getAllowedAuthenticators(self) -> int: ...
    @overload
    def authenticate(self, p0: CancellationSignal, p1: Executor, p2: Any) -> None: ...
    @overload
    def authenticate(self, p0: Any, p1: CancellationSignal, p2: Executor, p3: Any) -> None: ...
    def getDescription(self) -> str: ...
    def getContentView(self) -> PromptContentView: ...
    def getLogoDescription(self) -> str: ...
    def getTitle(self) -> str: ...
    def getSubtitle(self) -> str: ...

    class CryptoObject:
        @overload
        def __init__(self, p0: Signature) -> None: ...
        @overload
        def __init__(self, p0: Cipher) -> None: ...
        @overload
        def __init__(self, p0: Mac) -> None: ...
        @overload
        def __init__(self, p0: IdentityCredential) -> None: ...
        @overload
        def __init__(self, p0: PresentationSession) -> None: ...
        @overload
        def __init__(self, p0: int) -> None: ...
        def getIdentityCredential(self) -> IdentityCredential: ...
        def getPresentationSession(self) -> PresentationSession: ...
        def getOperationHandle(self) -> int: ...
        def getCipher(self) -> Cipher: ...
        def getMac(self) -> Mac: ...
        def getSignature(self) -> Signature: ...

    class Builder:
        def __init__(self, p0: Context) -> None: ...
        def setConfirmationRequired(self, p0: bool) -> Any: ...
        def setLogoBitmap(self, p0: Bitmap) -> Any: ...
        def setLogoRes(self, p0: int) -> Any: ...
        def setNegativeButton(self, p0: str, p1: Executor, p2: Any) -> Any: ...
        def setDeviceCredentialAllowed(self, p0: bool) -> Any: ...
        def setAllowedAuthenticators(self, p0: int) -> Any: ...
        def build(self) -> "BiometricPrompt": ...
        def setDescription(self, p0: str) -> Any: ...
        def setContentView(self, p0: PromptContentView) -> Any: ...
        def setLogoDescription(self, p0: str) -> Any: ...
        def setTitle(self, p0: str) -> Any: ...
        def setSubtitle(self, p0: str) -> Any: ...

    class AuthenticationResult:
        def getAuthenticationType(self) -> int: ...
        def getCryptoObject(self) -> Any: ...

    class AuthenticationCallback:
        def __init__(self) -> None: ...
        def onAuthenticationSucceeded(self, p0: Any) -> None: ...
        def onAuthenticationError(self, p0: int, p1: str) -> None: ...
        def onAuthenticationHelp(self, p0: int, p1: str) -> None: ...
        def onAuthenticationFailed(self) -> None: ...
