from typing import Any, ClassVar, overload
from android.os.Parcel import Parcel
from java.util.concurrent.Executor import Executor

class PromptContentViewWithMoreOptionsButton:
    CREATOR: ClassVar[Any]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    def getMoreOptionsButtonListener(self) -> Any: ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
    def getDescription(self) -> str: ...

    class Builder:
        def __init__(self) -> None: ...
        def build(self) -> "PromptContentViewWithMoreOptionsButton": ...
        def setMoreOptionsButtonListener(self, p0: Executor, p1: Any) -> Any: ...
        def setDescription(self, p0: str) -> Any: ...
