from typing import Any, ClassVar, overload
from android.graphics.ColorSpace import ColorSpace

class Color:
    BLACK: ClassVar[int]
    BLUE: ClassVar[int]
    CYAN: ClassVar[int]
    DKGRAY: ClassVar[int]
    GRAY: ClassVar[int]
    GREEN: ClassVar[int]
    LTGRAY: ClassVar[int]
    MAGENTA: ClassVar[int]
    RED: ClassVar[int]
    TRANSPARENT: ClassVar[int]
    WHITE: ClassVar[int]
    YELLOW: ClassVar[int]
    def __init__(self) -> None: ...
    def getComponentCount(self) -> int: ...
    @overload
    def isSrgb(self) -> bool: ...
    @overload
    @staticmethod
    def isSrgb(p0: int) -> bool: ...
    @overload
    def isWideGamut(self) -> bool: ...
    @overload
    @staticmethod
    def isWideGamut(p0: int) -> bool: ...
    @overload
    @staticmethod
    def green(p0: int) -> int: ...
    @overload
    def green(self) -> float: ...
    @overload
    @staticmethod
    def green(p0: int) -> float: ...
    @overload
    @staticmethod
    def blue(p0: int) -> float: ...
    @overload
    def blue(self) -> float: ...
    @overload
    @staticmethod
    def blue(p0: int) -> int: ...
    @staticmethod
    def RGBToHSV(p0: int, p1: int, p2: int, p3: Any) -> None: ...
    @overload
    @staticmethod
    def HSVToColor(p0: int, p1: Any) -> int: ...
    @overload
    @staticmethod
    def HSVToColor(p0: Any) -> int: ...
    @staticmethod
    def colorToHSV(p0: int, p1: Any) -> None: ...
    @overload
    @staticmethod
    def argb(p0: int, p1: int, p2: int, p3: int) -> int: ...
    @overload
    @staticmethod
    def argb(p0: float, p1: float, p2: float, p3: float) -> int: ...
    @overload
    @staticmethod
    def luminance(p0: int) -> float: ...
    @overload
    @staticmethod
    def luminance(p0: int) -> float: ...
    @overload
    def luminance(self) -> float: ...
    @staticmethod
    def parseColor(p0: str) -> int: ...
    @overload
    def getComponents(self, p0: Any) -> Any: ...
    @overload
    def getComponents(self) -> Any: ...
    @staticmethod
    def isInColorSpace(p0: int, p1: ColorSpace) -> bool: ...
    @overload
    @staticmethod
    def rgb(p0: float, p1: float, p2: float) -> int: ...
    @overload
    @staticmethod
    def rgb(p0: int, p1: int, p2: int) -> int: ...
    @overload
    def toArgb(self) -> int: ...
    @overload
    @staticmethod
    def toArgb(p0: int) -> int: ...
    def equals(self, p0: Any) -> bool: ...
    def toString(self) -> str: ...
    def hashCode(self) -> int: ...
    @overload
    @staticmethod
    def convert(p0: int, p1: ColorSpace) -> int: ...
    @overload
    @staticmethod
    def convert(p0: int, p1: ColorSpace) -> int: ...
    @overload
    @staticmethod
    def convert(p0: float, p1: float, p2: float, p3: float, p4: Any) -> int: ...
    @overload
    @staticmethod
    def convert(p0: float, p1: float, p2: float, p3: float, p4: ColorSpace, p5: ColorSpace) -> int: ...
    @overload
    def convert(self, p0: ColorSpace) -> "Color": ...
    @overload
    @staticmethod
    def convert(p0: int, p1: Any) -> int: ...
    @overload
    @staticmethod
    def valueOf(p0: float, p1: float, p2: float, p3: float) -> "Color": ...
    @overload
    @staticmethod
    def valueOf(p0: float, p1: float, p2: float) -> "Color": ...
    @overload
    @staticmethod
    def valueOf(p0: int) -> "Color": ...
    @overload
    @staticmethod
    def valueOf(p0: float, p1: float, p2: float, p3: float, p4: ColorSpace) -> "Color": ...
    @overload
    @staticmethod
    def valueOf(p0: int) -> "Color": ...
    @overload
    @staticmethod
    def valueOf(p0: Any, p1: ColorSpace) -> "Color": ...
    @overload
    @staticmethod
    def pack(p0: float, p1: float, p2: float, p3: float, p4: ColorSpace) -> int: ...
    @overload
    @staticmethod
    def pack(p0: float, p1: float, p2: float, p3: float) -> int: ...
    @overload
    @staticmethod
    def pack(p0: float, p1: float, p2: float) -> int: ...
    @overload
    @staticmethod
    def pack(p0: int) -> int: ...
    @overload
    def pack(self) -> int: ...
    def getComponent(self, p0: int) -> float: ...
    @overload
    def alpha(self) -> float: ...
    @overload
    @staticmethod
    def alpha(p0: int) -> int: ...
    @overload
    @staticmethod
    def alpha(p0: int) -> float: ...
    @staticmethod
    def colorSpace(p0: int) -> ColorSpace: ...
    def getColorSpace(self) -> ColorSpace: ...
    @overload
    def red(self) -> float: ...
    @overload
    @staticmethod
    def red(p0: int) -> int: ...
    @overload
    @staticmethod
    def red(p0: int) -> float: ...
    def getModel(self) -> Any: ...
