from typing import Any, ClassVar, overload
from android.graphics.RenderNode import RenderNode
from android.view.Surface import Surface
from java.lang.Runnable import Runnable
from java.util.concurrent.Executor import Executor

class HardwareRenderer:
    SYNC_CONTEXT_IS_STOPPED: ClassVar[int]
    SYNC_FRAME_DROPPED: ClassVar[int]
    SYNC_LOST_SURFACE_REWARD_IF_FOUND: ClassVar[int]
    SYNC_OK: ClassVar[int]
    SYNC_REDRAW_REQUESTED: ClassVar[int]
    def __init__(self) -> None: ...
    def clearContent(self) -> None: ...
    def notifyFramePending(self) -> None: ...
    @staticmethod
    def setDrawingEnabled(p0: bool) -> None: ...
    @staticmethod
    def isDrawingEnabled() -> bool: ...
    def setContentRoot(self, p0: RenderNode) -> None: ...
    def createRenderRequest(self) -> Any: ...
    def setLightSourceAlpha(self, p0: float, p1: float) -> None: ...
    def setLightSourceGeometry(self, p0: float, p1: float, p2: float, p3: float) -> None: ...
    def start(self) -> None: ...
    def setName(self, p0: str) -> None: ...
    def destroy(self) -> None: ...
    def setOpaque(self, p0: bool) -> None: ...
    def isOpaque(self) -> bool: ...
    def setSurface(self, p0: Surface) -> None: ...
    def stop(self) -> None: ...

    class FrameRenderRequest:
        def setVsyncTime(self, p0: int) -> Any: ...
        def setWaitForPresent(self, p0: bool) -> Any: ...
        def setFrameCommitCallback(self, p0: Executor, p1: Runnable) -> Any: ...
        def syncAndDraw(self) -> int: ...
