from typing import Any, ClassVar, overload
from android.graphics.Canvas import Canvas
from android.graphics.Paint import Paint
from java.io.InputStream import InputStream

class Movie:
    @staticmethod
    def decodeStream(p0: InputStream) -> "Movie": ...
    @staticmethod
    def decodeFile(p0: str) -> "Movie": ...
    @staticmethod
    def decodeByteArray(p0: Any, p1: int, p2: int) -> "Movie": ...
    def duration(self) -> int: ...
    def isOpaque(self) -> bool: ...
    @overload
    def draw(self, p0: Canvas, p1: float, p2: float, p3: Paint) -> None: ...
    @overload
    def draw(self, p0: Canvas, p1: float, p2: float) -> None: ...
    def width(self) -> int: ...
    def height(self) -> int: ...
    def setTime(self, p0: int) -> bool: ...
