from jnius import JavaClass, MetaJavaClass, JavaMethod, JavaStaticMethod, JavaMultipleMethod, JavaField, JavaStaticField

__all__ = ["Path"]

class Path(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "android/graphics/Path"
    __javaconstructor__ = [("()V", False), ("(Landroid/graphics/Path;)V", False)]
    addOval = JavaMultipleMethod([("(FFFFLandroid/graphics/Path$Direction;)V", False, False), ("(Landroid/graphics/RectF;Landroid/graphics/Path$Direction;)V", False, False)])
    approximate = JavaMethod("(F)[F")
    getPathIterator = JavaMethod("()Landroid/graphics/PathIterator;")
    addCircle = JavaMethod("(FFFLandroid/graphics/Path$Direction;)V")
    arcTo = JavaMultipleMethod([("(Landroid/graphics/RectF;FFZ)V", False, False), ("(Landroid/graphics/RectF;FF)V", False, False), ("(FFFFFFZ)V", False, False)])
    incReserve = JavaMethod("(I)V")
    addPath = JavaMultipleMethod([("(Landroid/graphics/Path;)V", False, False), ("(Landroid/graphics/Path;FF)V", False, False), ("(Landroid/graphics/Path;Landroid/graphics/Matrix;)V", False, False)])
    addRect = JavaMultipleMethod([("(FFFFLandroid/graphics/Path$Direction;)V", False, False), ("(Landroid/graphics/RectF;Landroid/graphics/Path$Direction;)V", False, False)])
    conicTo = JavaMethod("(FFFFF)V")
    getFillType = JavaMethod("()Landroid/graphics/Path$FillType;")
    addArc = JavaMultipleMethod([("(Landroid/graphics/RectF;FF)V", False, False), ("(FFFFFF)V", False, False)])
    cubicTo = JavaMethod("(FFFFFF)V")
    computeBounds = JavaMultipleMethod([("(Landroid/graphics/RectF;)V", False, False), ("(Landroid/graphics/RectF;Z)V", False, False)])
    addRoundRect = JavaMultipleMethod([("(Landroid/graphics/RectF;FFLandroid/graphics/Path$Direction;)V", False, False), ("(FFFFFFLandroid/graphics/Path$Direction;)V", False, False), ("(FFFF[FLandroid/graphics/Path$Direction;)V", False, False), ("(Landroid/graphics/RectF;[FLandroid/graphics/Path$Direction;)V", False, False)])
    interpolate = JavaMethod("(Landroid/graphics/Path;FLandroid/graphics/Path;)Z")
    isConvex = JavaMethod("()Z")
    isInterpolatable = JavaMethod("(Landroid/graphics/Path;)Z")
    isInverseFillType = JavaMethod("()Z")
    lineTo = JavaMethod("(FF)V")
    moveTo = JavaMethod("(FF)V")
    quadTo = JavaMethod("(FFFF)V")
    rConicTo = JavaMethod("(FFFFF)V")
    rCubicTo = JavaMethod("(FFFFFF)V")
    rLineTo = JavaMethod("(FF)V")
    rMoveTo = JavaMethod("(FF)V")
    rQuadTo = JavaMethod("(FFFF)V")
    setFillType = JavaMethod("(Landroid/graphics/Path$FillType;)V")
    setLastPoint = JavaMethod("(FF)V")
    toggleInverseFillType = JavaMethod("()V")
    isRect = JavaMethod("(Landroid/graphics/RectF;)Z")
    reset = JavaMethod("()V")
    isEmpty = JavaMethod("()Z")
    offset = JavaMultipleMethod([("(FFLandroid/graphics/Path;)V", False, False), ("(FF)V", False, False)])
    transform = JavaMultipleMethod([("(Landroid/graphics/Matrix;Landroid/graphics/Path;)V", False, False), ("(Landroid/graphics/Matrix;)V", False, False)])
    close = JavaMethod("()V")
    set = JavaMethod("(Landroid/graphics/Path;)V")
    op = JavaMultipleMethod([("(Landroid/graphics/Path;Landroid/graphics/Path;Landroid/graphics/Path$Op;)Z", False, False), ("(Landroid/graphics/Path;Landroid/graphics/Path$Op;)Z", False, False)])
    getGenerationId = JavaMethod("()I")
    rewind = JavaMethod("()V")

    class Op(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "android/graphics/Path$Op"
        DIFFERENCE = JavaStaticField("Landroid/graphics/Path$Op;")
        INTERSECT = JavaStaticField("Landroid/graphics/Path$Op;")
        REVERSE_DIFFERENCE = JavaStaticField("Landroid/graphics/Path$Op;")
        UNION = JavaStaticField("Landroid/graphics/Path$Op;")
        XOR = JavaStaticField("Landroid/graphics/Path$Op;")
        values = JavaStaticMethod("()[Landroid/graphics/Path$Op;")
        valueOf = JavaStaticMethod("(Ljava/lang/String;)Landroid/graphics/Path$Op;")
        DIFFERENCE = JavaStaticField("Landroid/graphics/Path$Op;")
        INTERSECT = JavaStaticField("Landroid/graphics/Path$Op;")
        REVERSE_DIFFERENCE = JavaStaticField("Landroid/graphics/Path$Op;")
        UNION = JavaStaticField("Landroid/graphics/Path$Op;")
        XOR = JavaStaticField("Landroid/graphics/Path$Op;")

    class FillType(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "android/graphics/Path$FillType"
        EVEN_ODD = JavaStaticField("Landroid/graphics/Path$FillType;")
        INVERSE_EVEN_ODD = JavaStaticField("Landroid/graphics/Path$FillType;")
        INVERSE_WINDING = JavaStaticField("Landroid/graphics/Path$FillType;")
        WINDING = JavaStaticField("Landroid/graphics/Path$FillType;")
        values = JavaStaticMethod("()[Landroid/graphics/Path$FillType;")
        valueOf = JavaStaticMethod("(Ljava/lang/String;)Landroid/graphics/Path$FillType;")
        EVEN_ODD = JavaStaticField("Landroid/graphics/Path$FillType;")
        INVERSE_EVEN_ODD = JavaStaticField("Landroid/graphics/Path$FillType;")
        INVERSE_WINDING = JavaStaticField("Landroid/graphics/Path$FillType;")
        WINDING = JavaStaticField("Landroid/graphics/Path$FillType;")

    class Direction(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "android/graphics/Path$Direction"
        CCW = JavaStaticField("Landroid/graphics/Path$Direction;")
        CW = JavaStaticField("Landroid/graphics/Path$Direction;")
        values = JavaStaticMethod("()[Landroid/graphics/Path$Direction;")
        valueOf = JavaStaticMethod("(Ljava/lang/String;)Landroid/graphics/Path$Direction;")
        CCW = JavaStaticField("Landroid/graphics/Path$Direction;")
        CW = JavaStaticField("Landroid/graphics/Path$Direction;")