from typing import Any, ClassVar, overload

class RadialGradient:
    @overload
    def __init__(self, p0: float, p1: float, p2: float, p3: Any, p4: Any, p5: Any) -> None: ...
    @overload
    def __init__(self, p0: float, p1: float, p2: float, p3: int, p4: int, p5: Any) -> None: ...
    @overload
    def __init__(self, p0: float, p1: float, p2: float, p3: Any, p4: Any, p5: Any) -> None: ...
    @overload
    def __init__(self, p0: float, p1: float, p2: float, p3: int, p4: int, p5: Any) -> None: ...
    @overload
    def __init__(self, p0: float, p1: float, p2: float, p3: float, p4: float, p5: float, p6: Any, p7: Any, p8: Any) -> None: ...
