from typing import Any, ClassVar, overload
from android.graphics.Rect import Rect
from android.os.Parcel import Parcel

class RectF:
    CREATOR: ClassVar[Any]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    bottom: float
    left: float
    right: float
    top: float
    @overload
    def __init__(self, p0: float, p1: float, p2: float, p3: float) -> None: ...
    @overload
    def __init__(self, p0: "RectF") -> None: ...
    @overload
    def __init__(self, p0: Rect) -> None: ...
    @overload
    def __init__(self) -> None: ...
    def equals(self, p0: Any) -> bool: ...
    def toString(self) -> str: ...
    def hashCode(self) -> int: ...
    def round(self, p0: Rect) -> None: ...
    def sort(self) -> None: ...
    def isEmpty(self) -> bool: ...
    def offset(self, p0: float, p1: float) -> None: ...
    @overload
    def contains(self, p0: "RectF") -> bool: ...
    @overload
    def contains(self, p0: float, p1: float, p2: float, p3: float) -> bool: ...
    @overload
    def contains(self, p0: float, p1: float) -> bool: ...
    @overload
    def set(self, p0: Rect) -> None: ...
    @overload
    def set(self, p0: "RectF") -> None: ...
    @overload
    def set(self, p0: float, p1: float, p2: float, p3: float) -> None: ...
    def toShortString(self) -> str: ...
    def roundOut(self, p0: Rect) -> None: ...
    def centerX(self) -> float: ...
    def centerY(self) -> float: ...
    def inset(self, p0: float, p1: float) -> None: ...
    @overload
    def intersect(self, p0: "RectF") -> bool: ...
    @overload
    def intersect(self, p0: float, p1: float, p2: float, p3: float) -> bool: ...
    def offsetTo(self, p0: float, p1: float) -> None: ...
    def setEmpty(self) -> None: ...
    def setIntersect(self, p0: "RectF", p1: "RectF") -> bool: ...
    @overload
    def union(self, p0: float, p1: float) -> None: ...
    @overload
    def union(self, p0: "RectF") -> None: ...
    @overload
    def union(self, p0: float, p1: float, p2: float, p3: float) -> None: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
    def readFromParcel(self, p0: Parcel) -> None: ...
    def describeContents(self) -> int: ...
    def width(self) -> float: ...
    def height(self) -> float: ...
    @overload
    def intersects(self, p0: float, p1: float, p2: float, p3: float) -> bool: ...
    @overload
    @staticmethod
    def intersects(p0: "RectF", p1: "RectF") -> bool: ...
