from typing import Any, ClassVar, overload
from android.graphics.Path import Path
from android.graphics.Rect import Rect
from android.os.Parcel import Parcel

class Region:
    CREATOR: ClassVar[Any]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    @overload
    def __init__(self, p0: Rect) -> None: ...
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, p0: "Region") -> None: ...
    @overload
    def __init__(self, p0: int, p1: int, p2: int, p3: int) -> None: ...
    def isComplex(self) -> bool: ...
    def isRect(self) -> bool: ...
    @overload
    def quickContains(self, p0: int, p1: int, p2: int, p3: int) -> bool: ...
    @overload
    def quickContains(self, p0: Rect) -> bool: ...
    @overload
    def getBoundaryPath(self) -> Path: ...
    @overload
    def getBoundaryPath(self, p0: Path) -> bool: ...
    def equals(self, p0: Any) -> bool: ...
    def toString(self) -> str: ...
    def isEmpty(self) -> bool: ...
    def contains(self, p0: int, p1: int) -> bool: ...
    @overload
    def getBounds(self, p0: Rect) -> bool: ...
    @overload
    def getBounds(self) -> Rect: ...
    @overload
    def set(self, p0: int, p1: int, p2: int, p3: int) -> bool: ...
    @overload
    def set(self, p0: Rect) -> bool: ...
    @overload
    def set(self, p0: "Region") -> bool: ...
    @overload
    def op(self, p0: "Region", p1: Any) -> bool: ...
    @overload
    def op(self, p0: "Region", p1: "Region", p2: Any) -> bool: ...
    @overload
    def op(self, p0: int, p1: int, p2: int, p3: int, p4: Any) -> bool: ...
    @overload
    def op(self, p0: Rect, p1: Any) -> bool: ...
    @overload
    def op(self, p0: Rect, p1: "Region", p2: Any) -> bool: ...
    @overload
    def quickReject(self, p0: "Region") -> bool: ...
    @overload
    def quickReject(self, p0: Rect) -> bool: ...
    @overload
    def quickReject(self, p0: int, p1: int, p2: int, p3: int) -> bool: ...
    @overload
    def translate(self, p0: int, p1: int, p2: "Region") -> None: ...
    @overload
    def translate(self, p0: int, p1: int) -> None: ...
    def setEmpty(self) -> None: ...
    def union(self, p0: Rect) -> bool: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
    def describeContents(self) -> int: ...
    def setPath(self, p0: Path, p1: "Region") -> bool: ...

    class Op:
        DIFFERENCE: ClassVar["Op"]
        INTERSECT: ClassVar["Op"]
        REPLACE: ClassVar["Op"]
        REVERSE_DIFFERENCE: ClassVar["Op"]
        UNION: ClassVar["Op"]
        XOR: ClassVar["Op"]
        DIFFERENCE: ClassVar[Any]
        INTERSECT: ClassVar[Any]
        REPLACE: ClassVar[Any]
        REVERSE_DIFFERENCE: ClassVar[Any]
        UNION: ClassVar[Any]
        XOR: ClassVar[Any]
        @staticmethod
        def values() -> Any: ...
        @staticmethod
        def valueOf(p0: str) -> Any: ...
