from jnius import JavaClass, JavaInterface, MetaJavaClass, JavaMethod, JavaStaticMethod, JavaMultipleMethod, JavaField, JavaStaticField

class LineBreaker(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "android/graphics/text/LineBreaker"
    BREAK_STRATEGY_BALANCED = JavaStaticField("I")
    BREAK_STRATEGY_HIGH_QUALITY = JavaStaticField("I")
    BREAK_STRATEGY_SIMPLE = JavaStaticField("I")
    HYPHENATION_FREQUENCY_FULL = JavaStaticField("I")
    HYPHENATION_FREQUENCY_NONE = JavaStaticField("I")
    HYPHENATION_FREQUENCY_NORMAL = JavaStaticField("I")
    JUSTIFICATION_MODE_INTER_CHARACTER = JavaStaticField("I")
    JUSTIFICATION_MODE_INTER_WORD = JavaStaticField("I")
    JUSTIFICATION_MODE_NONE = JavaStaticField("I")
    computeLineBreaks = JavaMethod("(Landroid/graphics/text/MeasuredText;Landroid/graphics/text/LineBreaker$ParagraphConstraints;I)Landroid/graphics/text/LineBreaker$Result;")

    class Result(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "android/graphics/text/LineBreaker$Result"
        getEndLineHyphenEdit = JavaMethod("(I)I")
        getLineBreakOffset = JavaMethod("(I)I")
        getStartLineHyphenEdit = JavaMethod("(I)I")
        hasLineTab = JavaMethod("(I)Z")
        getLineAscent = JavaMethod("(I)F")
        getLineDescent = JavaMethod("(I)F")
        getLineWidth = JavaMethod("(I)F")
        getLineCount = JavaMethod("()I")

    class ParagraphConstraints(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "android/graphics/text/LineBreaker$ParagraphConstraints"
        __javaconstructor__ = [("()V", False)]
        setIndent = JavaMethod("(FI)V")
        getDefaultTabStop = JavaMethod("()F")
        getFirstWidth = JavaMethod("()F")
        getFirstWidthLineCount = JavaMethod("()I")
        getTabStops = JavaMethod("()[F")
        setTabStops = JavaMethod("([FF)V")
        getWidth = JavaMethod("()F")
        setWidth = JavaMethod("(F)V")

    class Builder(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "android/graphics/text/LineBreaker$Builder"
        __javaconstructor__ = [("()V", False)]
        setIndents = JavaMethod("([I)Landroid/graphics/text/LineBreaker$Builder;")
        build = JavaMethod("()Landroid/graphics/text/LineBreaker;")
        setBreakStrategy = JavaMethod("(I)Landroid/graphics/text/LineBreaker$Builder;")
        setHyphenationFrequency = JavaMethod("(I)Landroid/graphics/text/LineBreaker$Builder;")
        setJustificationMode = JavaMethod("(I)Landroid/graphics/text/LineBreaker$Builder;")
        setUseBoundsForWidth = JavaMethod("(Z)Landroid/graphics/text/LineBreaker$Builder;")

class TextRunShaper(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "android/graphics/text/TextRunShaper"
    shapeTextRun = JavaMultipleMethod([("([CIIIIFFZLandroid/graphics/Paint;)Landroid/graphics/text/PositionedGlyphs;", True, False), ("(Ljava/lang/CharSequence;IIIIFFZLandroid/graphics/Paint;)Landroid/graphics/text/PositionedGlyphs;", True, False)])

class LineBreakConfig(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "android/graphics/text/LineBreakConfig"
    CREATOR = JavaStaticField("Landroid/os/Parcelable$Creator;")
    HYPHENATION_DISABLED = JavaStaticField("I")
    HYPHENATION_ENABLED = JavaStaticField("I")
    HYPHENATION_UNSPECIFIED = JavaStaticField("I")
    LINE_BREAK_STYLE_AUTO = JavaStaticField("I")
    LINE_BREAK_STYLE_LOOSE = JavaStaticField("I")
    LINE_BREAK_STYLE_NONE = JavaStaticField("I")
    LINE_BREAK_STYLE_NORMAL = JavaStaticField("I")
    LINE_BREAK_STYLE_NO_BREAK = JavaStaticField("I")
    LINE_BREAK_STYLE_STRICT = JavaStaticField("I")
    LINE_BREAK_STYLE_UNSPECIFIED = JavaStaticField("I")
    LINE_BREAK_WORD_STYLE_AUTO = JavaStaticField("I")
    LINE_BREAK_WORD_STYLE_NONE = JavaStaticField("I")
    LINE_BREAK_WORD_STYLE_PHRASE = JavaStaticField("I")
    LINE_BREAK_WORD_STYLE_UNSPECIFIED = JavaStaticField("I")
    CONTENTS_FILE_DESCRIPTOR = JavaStaticField("I")
    PARCELABLE_WRITE_RETURN_VALUE = JavaStaticField("I")
    getHyphenation = JavaMethod("()I")
    equals = JavaMethod("(Ljava/lang/Object;)Z")
    toString = JavaMethod("()Ljava/lang/String;")
    hashCode = JavaMethod("()I")
    merge = JavaMethod("(Landroid/graphics/text/LineBreakConfig;)Landroid/graphics/text/LineBreakConfig;")
    describeContents = JavaMethod("()I")
    writeToParcel = JavaMethod("(Landroid/os/Parcel;I)V")
    getLineBreakStyle = JavaMethod("()I")
    getLineBreakWordStyle = JavaMethod("()I")

    class Builder(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "android/graphics/text/LineBreakConfig$Builder"
        __javaconstructor__ = [("()V", False)]
        setHyphenation = JavaMethod("(I)Landroid/graphics/text/LineBreakConfig$Builder;")
        merge = JavaMethod("(Landroid/graphics/text/LineBreakConfig;)Landroid/graphics/text/LineBreakConfig$Builder;")
        build = JavaMethod("()Landroid/graphics/text/LineBreakConfig;")
        setLineBreakStyle = JavaMethod("(I)Landroid/graphics/text/LineBreakConfig$Builder;")
        setLineBreakWordStyle = JavaMethod("(I)Landroid/graphics/text/LineBreakConfig$Builder;")

class PositionedGlyphs(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "android/graphics/text/PositionedGlyphs"
    NO_OVERRIDE = JavaStaticField("F")
    getAscent = JavaMethod("()F")
    getDescent = JavaMethod("()F")
    getAdvance = JavaMethod("()F")
    getFakeBold = JavaMethod("(I)Z")
    getFakeItalic = JavaMethod("(I)Z")
    getGlyphId = JavaMethod("(I)I")
    getGlyphX = JavaMethod("(I)F")
    getGlyphY = JavaMethod("(I)F")
    getItalicOverride = JavaMethod("(I)F")
    getOffsetX = JavaMethod("()F")
    getOffsetY = JavaMethod("()F")
    getWeightOverride = JavaMethod("(I)F")
    equals = JavaMethod("(Ljava/lang/Object;)Z")
    toString = JavaMethod("()Ljava/lang/String;")
    hashCode = JavaMethod("()I")
    glyphCount = JavaMethod("()I")
    getFont = JavaMethod("(I)Landroid/graphics/fonts/Font;")

class MeasuredText(JavaClass, metaclass=MetaJavaClass):
    __javaclass__ = "android/graphics/text/MeasuredText"
    getCharWidthAt = JavaMethod("(I)F")
    getBounds = JavaMethod("(IILandroid/graphics/Rect;)V")
    getWidth = JavaMethod("(II)F")
    getFontMetricsInt = JavaMethod("(IILandroid/graphics/Paint$FontMetricsInt;)V")

    class Builder(JavaClass, metaclass=MetaJavaClass):
        __javaclass__ = "android/graphics/text/MeasuredText$Builder"
        __javaconstructor__ = [("(Landroid/graphics/text/MeasuredText;)V", False), ("([C)V", False)]
        HYPHENATION_MODE_FAST = JavaStaticField("I")
        HYPHENATION_MODE_NONE = JavaStaticField("I")
        HYPHENATION_MODE_NORMAL = JavaStaticField("I")
        appendReplacementRun = JavaMethod("(Landroid/graphics/Paint;IF)Landroid/graphics/text/MeasuredText$Builder;")
        appendStyleRun = JavaMultipleMethod([("(Landroid/graphics/Paint;Landroid/graphics/text/LineBreakConfig;IZ)Landroid/graphics/text/MeasuredText$Builder;", False, False), ("(Landroid/graphics/Paint;IZ)Landroid/graphics/text/MeasuredText$Builder;", False, False)])
        setComputeHyphenation = JavaMultipleMethod([("(I)Landroid/graphics/text/MeasuredText$Builder;", False, False), ("(Z)Landroid/graphics/text/MeasuredText$Builder;", False, False)])
        setComputeLayout = JavaMethod("(Z)Landroid/graphics/text/MeasuredText$Builder;")
        build = JavaMethod("()Landroid/graphics/text/MeasuredText;")