from typing import Any, ClassVar, overload
from android.animation.Animator import Animator

class AnimatorListenerAdapter:
    def __init__(self) -> None: ...
    def onAnimationRepeat(self, p0: Animator) -> None: ...
    def onAnimationCancel(self, p0: Animator) -> None: ...
    def onAnimationResume(self, p0: Animator) -> None: ...
    def onAnimationPause(self, p0: Animator) -> None: ...
    def onAnimationEnd(self, p0: Animator) -> None: ...
    def onAnimationStart(self, p0: Animator) -> None: ...
