from typing import Any, ClassVar, overload
from android.animation.TimeInterpolator import TimeInterpolator

class Animator:
    DURATION_INFINITE: ClassVar[int]
    def __init__(self) -> None: ...
    @overload
    def clone(self) -> Any: ...
    @overload
    def clone(self) -> "Animator": ...
    def end(self) -> None: ...
    def start(self) -> None: ...
    def cancel(self) -> None: ...
    def isStarted(self) -> bool: ...
    def setTarget(self, p0: Any) -> None: ...
    def addListener(self, p0: Any) -> None: ...
    def getInterpolator(self) -> TimeInterpolator: ...
    def getStartDelay(self) -> int: ...
    def removeListener(self, p0: Any) -> None: ...
    def setDuration(self, p0: int) -> "Animator": ...
    def setInterpolator(self, p0: TimeInterpolator) -> None: ...
    def setStartDelay(self, p0: int) -> None: ...
    def setupEndValues(self) -> None: ...
    def setupStartValues(self) -> None: ...
    def getTotalDuration(self) -> int: ...
    def isRunning(self) -> bool: ...
    def pause(self) -> None: ...
    def getDuration(self) -> int: ...
    def resume(self) -> None: ...
    def getListeners(self) -> list: ...
    def removeAllListeners(self) -> None: ...
    def isPaused(self) -> bool: ...
    def addPauseListener(self, p0: Any) -> None: ...
    def removePauseListener(self, p0: Any) -> None: ...

    class AnimatorPauseListener:
        def onAnimationResume(self, p0: "Animator") -> None: ...
        def onAnimationPause(self, p0: "Animator") -> None: ...

    class AnimatorListener:
        def onAnimationRepeat(self, p0: "Animator") -> None: ...
        def onAnimationCancel(self, p0: "Animator") -> None: ...
        @overload
        def onAnimationEnd(self, p0: "Animator", p1: bool) -> None: ...
        @overload
        def onAnimationEnd(self, p0: "Animator") -> None: ...
        @overload
        def onAnimationStart(self, p0: "Animator", p1: bool) -> None: ...
        @overload
        def onAnimationStart(self, p0: "Animator") -> None: ...
