from typing import Any, ClassVar, overload
from android.animation.Animator import Animator
from android.animation.TimeInterpolator import TimeInterpolator
from android.animation.TypeEvaluator import TypeEvaluator

class ValueAnimator:
    INFINITE: ClassVar[int]
    RESTART: ClassVar[int]
    REVERSE: ClassVar[int]
    DURATION_INFINITE: ClassVar[int]
    def __init__(self) -> None: ...
    def toString(self) -> str: ...
    @overload
    def clone(self) -> Animator: ...
    @overload
    def clone(self) -> Any: ...
    @overload
    def clone(self) -> "ValueAnimator": ...
    def reverse(self) -> None: ...
    def end(self) -> None: ...
    def start(self) -> None: ...
    def cancel(self) -> None: ...
    def isStarted(self) -> bool: ...
    def getRepeatCount(self) -> int: ...
    def setValues(self, p0: Any) -> None: ...
    def getValues(self) -> Any: ...
    def getInterpolator(self) -> TimeInterpolator: ...
    def getStartDelay(self) -> int: ...
    @overload
    def setDuration(self, p0: int) -> Animator: ...
    @overload
    def setDuration(self, p0: int) -> "ValueAnimator": ...
    def setInterpolator(self, p0: TimeInterpolator) -> None: ...
    def setStartDelay(self, p0: int) -> None: ...
    @staticmethod
    def ofFloat(p0: Any) -> "ValueAnimator": ...
    @staticmethod
    def ofInt(p0: Any) -> "ValueAnimator": ...
    @staticmethod
    def ofArgb(p0: Any) -> "ValueAnimator": ...
    @staticmethod
    def ofObject(p0: TypeEvaluator, p1: Any) -> "ValueAnimator": ...
    @staticmethod
    def ofPropertyValuesHolder(p0: Any) -> "ValueAnimator": ...
    def setFloatValues(self, p0: Any) -> None: ...
    def setIntValues(self, p0: Any) -> None: ...
    def setObjectValues(self, p0: Any) -> None: ...
    def getRepeatMode(self) -> int: ...
    def setRepeatCount(self, p0: int) -> None: ...
    def setRepeatMode(self, p0: int) -> None: ...
    @overload
    def getAnimatedValue(self, p0: str) -> Any: ...
    @overload
    def getAnimatedValue(self) -> Any: ...
    @staticmethod
    def getDurationScale() -> float: ...
    def getCurrentPlayTime(self) -> int: ...
    def addUpdateListener(self, p0: Any) -> None: ...
    @staticmethod
    def areAnimatorsEnabled() -> bool: ...
    def getAnimatedFraction(self) -> float: ...
    @staticmethod
    def getFrameDelay() -> int: ...
    def getTotalDuration(self) -> int: ...
    def isRunning(self) -> bool: ...
    def setCurrentFraction(self, p0: float) -> None: ...
    @staticmethod
    def registerDurationScaleChangeListener(p0: Any) -> bool: ...
    def removeAllUpdateListeners(self) -> None: ...
    def removeUpdateListener(self, p0: Any) -> None: ...
    def setCurrentPlayTime(self, p0: int) -> None: ...
    def setEvaluator(self, p0: TypeEvaluator) -> None: ...
    @staticmethod
    def setFrameDelay(p0: int) -> None: ...
    @staticmethod
    def unregisterDurationScaleChangeListener(p0: Any) -> bool: ...
    def pause(self) -> None: ...
    def getDuration(self) -> int: ...
    def resume(self) -> None: ...

    class DurationScaleChangeListener:
        def onChanged(self, p0: float) -> None: ...

    class AnimatorUpdateListener:
        def onAnimationUpdate(self, p0: "ValueAnimator") -> None: ...
