from typing import Any, ClassVar, overload
from java.lang.Runnable import Runnable
from java.util.concurrent.Callable import Callable
from java.util.concurrent.Future import Future
from java.util.concurrent.TimeUnit import TimeUnit

class AbstractExecutorService:
    def __init__(self) -> None: ...
    @overload
    def invokeAny(self, p0: list) -> Any: ...
    @overload
    def invokeAny(self, p0: list, p1: int, p2: TimeUnit) -> Any: ...
    @overload
    def submit(self, p0: Runnable, p1: Any) -> Future: ...
    @overload
    def submit(self, p0: Callable) -> Future: ...
    @overload
    def submit(self, p0: Runnable) -> Future: ...
    @overload
    def invokeAll(self, p0: list) -> list: ...
    @overload
    def invokeAll(self, p0: list, p1: int, p2: TimeUnit) -> list: ...
