from typing import Any, ClassVar, overload
from java.lang.Runnable import Runnable
from java.lang.Throwable import Throwable
from java.util.concurrent.CompletionStage import CompletionStage
from java.util.concurrent.Executor import Executor
from java.util.concurrent.TimeUnit import TimeUnit
from java.util.function.BiConsumer import BiConsumer
from java.util.function.BiFunction import BiFunction
from java.util.function.Consumer import Consumer
from java.util.function.Function import Function
from java.util.function.Supplier import Supplier

class CompletableFuture:
    def __init__(self) -> None: ...
    def isCancelled(self) -> bool: ...
    @overload
    def get(self, p0: int, p1: TimeUnit) -> Any: ...
    @overload
    def get(self) -> Any: ...
    def toString(self) -> str: ...
    def join(self) -> Any: ...
    def state(self) -> Any: ...
    def isDone(self) -> bool: ...
    def cancel(self, p0: bool) -> bool: ...
    def copy(self) -> "CompletableFuture": ...
    @overload
    def handle(self, p0: BiFunction) -> "CompletableFuture": ...
    @overload
    def handle(self, p0: BiFunction) -> CompletionStage: ...
    def complete(self, p0: Any) -> bool: ...
    def newIncompleteFuture(self) -> "CompletableFuture": ...
    def toCompletableFuture(self) -> "CompletableFuture": ...
    def defaultExecutor(self) -> Executor: ...
    @overload
    def completeAsync(self, p0: Supplier) -> "CompletableFuture": ...
    @overload
    def completeAsync(self, p0: Supplier, p1: Executor) -> "CompletableFuture": ...
    @overload
    def whenComplete(self, p0: BiConsumer) -> CompletionStage: ...
    @overload
    def whenComplete(self, p0: BiConsumer) -> "CompletableFuture": ...
    @overload
    def exceptionallyComposeAsync(self, p0: Function, p1: Executor) -> "CompletableFuture": ...
    @overload
    def exceptionallyComposeAsync(self, p0: Function) -> "CompletableFuture": ...
    @overload
    def exceptionallyComposeAsync(self, p0: Function) -> CompletionStage: ...
    @overload
    def exceptionallyComposeAsync(self, p0: Function, p1: Executor) -> CompletionStage: ...
    @overload
    def exceptionallyCompose(self, p0: Function) -> "CompletableFuture": ...
    @overload
    def exceptionallyCompose(self, p0: Function) -> CompletionStage: ...
    @overload
    def exceptionallyAsync(self, p0: Function, p1: Executor) -> "CompletableFuture": ...
    @overload
    def exceptionallyAsync(self, p0: Function) -> CompletionStage: ...
    @overload
    def exceptionallyAsync(self, p0: Function, p1: Executor) -> CompletionStage: ...
    @overload
    def exceptionallyAsync(self, p0: Function) -> "CompletableFuture": ...
    @overload
    def exceptionally(self, p0: Function) -> "CompletableFuture": ...
    @overload
    def exceptionally(self, p0: Function) -> CompletionStage: ...
    @overload
    def whenCompleteAsync(self, p0: BiConsumer, p1: Executor) -> CompletionStage: ...
    @overload
    def whenCompleteAsync(self, p0: BiConsumer, p1: Executor) -> "CompletableFuture": ...
    @overload
    def whenCompleteAsync(self, p0: BiConsumer) -> "CompletableFuture": ...
    @overload
    def whenCompleteAsync(self, p0: BiConsumer) -> CompletionStage: ...
    @overload
    def handleAsync(self, p0: BiFunction) -> CompletionStage: ...
    @overload
    def handleAsync(self, p0: BiFunction, p1: Executor) -> CompletionStage: ...
    @overload
    def handleAsync(self, p0: BiFunction, p1: Executor) -> "CompletableFuture": ...
    @overload
    def handleAsync(self, p0: BiFunction) -> "CompletableFuture": ...
    @overload
    def thenComposeAsync(self, p0: Function, p1: Executor) -> CompletionStage: ...
    @overload
    def thenComposeAsync(self, p0: Function, p1: Executor) -> "CompletableFuture": ...
    @overload
    def thenComposeAsync(self, p0: Function) -> "CompletableFuture": ...
    @overload
    def thenComposeAsync(self, p0: Function) -> CompletionStage: ...
    @overload
    def thenCompose(self, p0: Function) -> "CompletableFuture": ...
    @overload
    def thenCompose(self, p0: Function) -> CompletionStage: ...
    @overload
    def runAfterEitherAsync(self, p0: CompletionStage, p1: Runnable, p2: Executor) -> CompletionStage: ...
    @overload
    def runAfterEitherAsync(self, p0: CompletionStage, p1: Runnable) -> CompletionStage: ...
    @overload
    def runAfterEitherAsync(self, p0: CompletionStage, p1: Runnable, p2: Executor) -> "CompletableFuture": ...
    @overload
    def runAfterEitherAsync(self, p0: CompletionStage, p1: Runnable) -> "CompletableFuture": ...
    @overload
    def runAfterEither(self, p0: CompletionStage, p1: Runnable) -> CompletionStage: ...
    @overload
    def runAfterEither(self, p0: CompletionStage, p1: Runnable) -> "CompletableFuture": ...
    @overload
    def acceptEitherAsync(self, p0: CompletionStage, p1: Consumer) -> "CompletableFuture": ...
    @overload
    def acceptEitherAsync(self, p0: CompletionStage, p1: Consumer, p2: Executor) -> CompletionStage: ...
    @overload
    def acceptEitherAsync(self, p0: CompletionStage, p1: Consumer) -> CompletionStage: ...
    @overload
    def acceptEitherAsync(self, p0: CompletionStage, p1: Consumer, p2: Executor) -> "CompletableFuture": ...
    @overload
    def acceptEither(self, p0: CompletionStage, p1: Consumer) -> "CompletableFuture": ...
    @overload
    def acceptEither(self, p0: CompletionStage, p1: Consumer) -> CompletionStage: ...
    @overload
    def applyToEitherAsync(self, p0: CompletionStage, p1: Function, p2: Executor) -> "CompletableFuture": ...
    @overload
    def applyToEitherAsync(self, p0: CompletionStage, p1: Function, p2: Executor) -> CompletionStage: ...
    @overload
    def applyToEitherAsync(self, p0: CompletionStage, p1: Function) -> CompletionStage: ...
    @overload
    def applyToEitherAsync(self, p0: CompletionStage, p1: Function) -> "CompletableFuture": ...
    @overload
    def applyToEither(self, p0: CompletionStage, p1: Function) -> "CompletableFuture": ...
    @overload
    def applyToEither(self, p0: CompletionStage, p1: Function) -> CompletionStage: ...
    @overload
    def runAfterBothAsync(self, p0: CompletionStage, p1: Runnable, p2: Executor) -> CompletionStage: ...
    @overload
    def runAfterBothAsync(self, p0: CompletionStage, p1: Runnable) -> CompletionStage: ...
    @overload
    def runAfterBothAsync(self, p0: CompletionStage, p1: Runnable, p2: Executor) -> "CompletableFuture": ...
    @overload
    def runAfterBothAsync(self, p0: CompletionStage, p1: Runnable) -> "CompletableFuture": ...
    @overload
    def runAfterBoth(self, p0: CompletionStage, p1: Runnable) -> CompletionStage: ...
    @overload
    def runAfterBoth(self, p0: CompletionStage, p1: Runnable) -> "CompletableFuture": ...
    @overload
    def thenAcceptBothAsync(self, p0: CompletionStage, p1: BiConsumer, p2: Executor) -> "CompletableFuture": ...
    @overload
    def thenAcceptBothAsync(self, p0: CompletionStage, p1: BiConsumer) -> CompletionStage: ...
    @overload
    def thenAcceptBothAsync(self, p0: CompletionStage, p1: BiConsumer) -> "CompletableFuture": ...
    @overload
    def thenAcceptBothAsync(self, p0: CompletionStage, p1: BiConsumer, p2: Executor) -> CompletionStage: ...
    @overload
    def thenAcceptBoth(self, p0: CompletionStage, p1: BiConsumer) -> CompletionStage: ...
    @overload
    def thenAcceptBoth(self, p0: CompletionStage, p1: BiConsumer) -> "CompletableFuture": ...
    @overload
    def thenCombineAsync(self, p0: CompletionStage, p1: BiFunction) -> "CompletableFuture": ...
    @overload
    def thenCombineAsync(self, p0: CompletionStage, p1: BiFunction, p2: Executor) -> "CompletableFuture": ...
    @overload
    def thenCombineAsync(self, p0: CompletionStage, p1: BiFunction) -> CompletionStage: ...
    @overload
    def thenCombineAsync(self, p0: CompletionStage, p1: BiFunction, p2: Executor) -> CompletionStage: ...
    @overload
    def thenCombine(self, p0: CompletionStage, p1: BiFunction) -> "CompletableFuture": ...
    @overload
    def thenCombine(self, p0: CompletionStage, p1: BiFunction) -> CompletionStage: ...
    @overload
    def thenRunAsync(self, p0: Runnable, p1: Executor) -> CompletionStage: ...
    @overload
    def thenRunAsync(self, p0: Runnable) -> "CompletableFuture": ...
    @overload
    def thenRunAsync(self, p0: Runnable) -> CompletionStage: ...
    @overload
    def thenRunAsync(self, p0: Runnable, p1: Executor) -> "CompletableFuture": ...
    @overload
    def thenRun(self, p0: Runnable) -> CompletionStage: ...
    @overload
    def thenRun(self, p0: Runnable) -> "CompletableFuture": ...
    @overload
    def thenAcceptAsync(self, p0: Consumer) -> "CompletableFuture": ...
    @overload
    def thenAcceptAsync(self, p0: Consumer) -> CompletionStage: ...
    @overload
    def thenAcceptAsync(self, p0: Consumer, p1: Executor) -> CompletionStage: ...
    @overload
    def thenAcceptAsync(self, p0: Consumer, p1: Executor) -> "CompletableFuture": ...
    @overload
    def thenAccept(self, p0: Consumer) -> "CompletableFuture": ...
    @overload
    def thenAccept(self, p0: Consumer) -> CompletionStage: ...
    @overload
    def thenApplyAsync(self, p0: Function, p1: Executor) -> CompletionStage: ...
    @overload
    def thenApplyAsync(self, p0: Function) -> CompletionStage: ...
    @overload
    def thenApplyAsync(self, p0: Function) -> "CompletableFuture": ...
    @overload
    def thenApplyAsync(self, p0: Function, p1: Executor) -> "CompletableFuture": ...
    @overload
    def thenApply(self, p0: Function) -> CompletionStage: ...
    @overload
    def thenApply(self, p0: Function) -> "CompletableFuture": ...
    def resultNow(self) -> Any: ...
    def exceptionNow(self) -> Throwable: ...
    def completeExceptionally(self, p0: Throwable) -> bool: ...
    @staticmethod
    def allOf(p0: Any) -> "CompletableFuture": ...
    @overload
    @staticmethod
    def supplyAsync(p0: Supplier) -> "CompletableFuture": ...
    @overload
    @staticmethod
    def supplyAsync(p0: Supplier, p1: Executor) -> "CompletableFuture": ...
    @overload
    @staticmethod
    def runAsync(p0: Runnable, p1: Executor) -> "CompletableFuture": ...
    @overload
    @staticmethod
    def runAsync(p0: Runnable) -> "CompletableFuture": ...
    @staticmethod
    def completedFuture(p0: Any) -> "CompletableFuture": ...
    def getNow(self, p0: Any) -> Any: ...
    @staticmethod
    def anyOf(p0: Any) -> "CompletableFuture": ...
    def isCompletedExceptionally(self) -> bool: ...
    def obtrudeValue(self, p0: Any) -> None: ...
    def obtrudeException(self, p0: Throwable) -> None: ...
    def getNumberOfDependents(self) -> int: ...
    def minimalCompletionStage(self) -> CompletionStage: ...
    def orTimeout(self, p0: int, p1: TimeUnit) -> "CompletableFuture": ...
    def completeOnTimeout(self, p0: Any, p1: int, p2: TimeUnit) -> "CompletableFuture": ...
    @overload
    @staticmethod
    def delayedExecutor(p0: int, p1: TimeUnit) -> Executor: ...
    @overload
    @staticmethod
    def delayedExecutor(p0: int, p1: TimeUnit, p2: Executor) -> Executor: ...
    @staticmethod
    def completedStage(p0: Any) -> CompletionStage: ...
    @staticmethod
    def failedFuture(p0: Throwable) -> "CompletableFuture": ...
    @staticmethod
    def failedStage(p0: Throwable) -> CompletionStage: ...

    class AsynchronousCompletionTask:
        ...
