from typing import Any, ClassVar, overload
from java.lang.Runnable import Runnable
from java.lang.Throwable import Throwable
from java.util.concurrent.Callable import Callable
from java.util.concurrent.ForkJoinPool import ForkJoinPool
from java.util.concurrent.TimeUnit import TimeUnit

class ForkJoinTask:
    def __init__(self) -> None: ...
    def isCancelled(self) -> bool: ...
    def invoke(self) -> Any: ...
    @overload
    def get(self) -> Any: ...
    @overload
    def get(self, p0: int, p1: TimeUnit) -> Any: ...
    def join(self) -> Any: ...
    def getException(self) -> Throwable: ...
    def state(self) -> Any: ...
    def isDone(self) -> bool: ...
    @overload
    @staticmethod
    def adapt(p0: Runnable) -> "ForkJoinTask": ...
    @overload
    @staticmethod
    def adapt(p0: Runnable, p1: Any) -> "ForkJoinTask": ...
    @overload
    @staticmethod
    def adapt(p0: Callable) -> "ForkJoinTask": ...
    @staticmethod
    def getPool() -> ForkJoinPool: ...
    @staticmethod
    def getQueuedTaskCount() -> int: ...
    def cancel(self, p0: bool) -> bool: ...
    def reinitialize(self) -> None: ...
    @staticmethod
    def helpQuiesce() -> None: ...
    @staticmethod
    def inForkJoinPool() -> bool: ...
    def tryUnfork(self) -> bool: ...
    def getForkJoinTaskTag(self) -> int: ...
    def setForkJoinTaskTag(self, p0: int) -> int: ...
    def compareAndSetForkJoinTaskTag(self, p0: int, p1: int) -> bool: ...
    @staticmethod
    def adaptInterruptible(p0: Callable) -> "ForkJoinTask": ...
    def complete(self, p0: Any) -> None: ...
    def quietlyComplete(self) -> None: ...
    def getRawResult(self) -> Any: ...
    def fork(self) -> "ForkJoinTask": ...
    @overload
    @staticmethod
    def invokeAll(p0: Any) -> None: ...
    @overload
    @staticmethod
    def invokeAll(p0: list) -> list: ...
    @overload
    @staticmethod
    def invokeAll(p0: "ForkJoinTask", p1: "ForkJoinTask") -> None: ...
    def isCompletedNormally(self) -> bool: ...
    @staticmethod
    def getSurplusQueuedTaskCount() -> int: ...
    def isCompletedAbnormally(self) -> bool: ...
    def resultNow(self) -> Any: ...
    def exceptionNow(self) -> Throwable: ...
    def completeExceptionally(self, p0: Throwable) -> None: ...
    @overload
    def quietlyJoin(self, p0: int, p1: TimeUnit) -> bool: ...
    @overload
    def quietlyJoin(self) -> None: ...
    def quietlyInvoke(self) -> None: ...
    def quietlyJoinUninterruptibly(self, p0: int, p1: TimeUnit) -> bool: ...
