from typing import Any, ClassVar, overload
from java.util.stream.DoubleStream import DoubleStream
from java.util.stream.IntStream import IntStream
from java.util.stream.LongStream import LongStream

class ThreadLocalRandom:
    def nextBoolean(self) -> bool: ...
    @overload
    def nextLong(self, p0: int, p1: int) -> int: ...
    @overload
    def nextLong(self) -> int: ...
    @overload
    def nextLong(self, p0: int) -> int: ...
    @overload
    def nextFloat(self) -> float: ...
    @overload
    def nextFloat(self, p0: float) -> float: ...
    @overload
    def nextFloat(self, p0: float, p1: float) -> float: ...
    @overload
    def ints(self) -> IntStream: ...
    @overload
    def ints(self, p0: int, p1: int) -> IntStream: ...
    @overload
    def ints(self, p0: int, p1: int, p2: int) -> IntStream: ...
    @overload
    def ints(self, p0: int) -> IntStream: ...
    @overload
    def doubles(self, p0: int) -> DoubleStream: ...
    @overload
    def doubles(self, p0: float, p1: float) -> DoubleStream: ...
    @overload
    def doubles(self, p0: int, p1: float, p2: float) -> DoubleStream: ...
    @overload
    def doubles(self) -> DoubleStream: ...
    def setSeed(self, p0: int) -> None: ...
    @staticmethod
    def current() -> "ThreadLocalRandom": ...
    @overload
    def nextDouble(self, p0: float, p1: float) -> float: ...
    @overload
    def nextDouble(self, p0: float) -> float: ...
    @overload
    def nextDouble(self) -> float: ...
    @overload
    def longs(self, p0: int, p1: int, p2: int) -> LongStream: ...
    @overload
    def longs(self, p0: int, p1: int) -> LongStream: ...
    @overload
    def longs(self, p0: int) -> LongStream: ...
    @overload
    def longs(self) -> LongStream: ...
    @overload
    def nextInt(self, p0: int) -> int: ...
    @overload
    def nextInt(self) -> int: ...
    @overload
    def nextInt(self, p0: int, p1: int) -> int: ...
