# cython: language_level=3
# Generated by pyjnius-wrap cython — do not edit by hand.

from jni_core._core cimport (
    JavaObject, get_env, check_jni_exc,
    find_class_global, get_method_id, get_static_method_id,
    get_field_id, get_static_field_id, j_str, py_str,
)
from jni_core._dispatch cimport (
    jnicore_NewObjectA, jnicore_DeleteLocalRef,
    jnicore_CallVoidMethodA, jnicore_CallObjectMethodA,
    jnicore_CallBooleanMethodA, jnicore_CallByteMethodA,
    jnicore_CallCharMethodA, jnicore_CallShortMethodA,
    jnicore_CallIntMethodA, jnicore_CallLongMethodA,
    jnicore_CallFloatMethodA, jnicore_CallDoubleMethodA,
    jnicore_CallStaticVoidMethodA, jnicore_CallStaticObjectMethodA,
    jnicore_CallStaticBooleanMethodA, jnicore_CallStaticByteMethodA,
    jnicore_CallStaticCharMethodA, jnicore_CallStaticShortMethodA,
    jnicore_CallStaticIntMethodA, jnicore_CallStaticLongMethodA,
    jnicore_CallStaticFloatMethodA, jnicore_CallStaticDoubleMethodA,
    jnicore_GetObjectField, jnicore_SetObjectField,
    jnicore_GetBooleanField, jnicore_SetBooleanField,
    jnicore_GetByteField, jnicore_SetByteField,
    jnicore_GetCharField, jnicore_SetCharField,
    jnicore_GetShortField, jnicore_SetShortField,
    jnicore_GetIntField, jnicore_SetIntField,
    jnicore_GetLongField, jnicore_SetLongField,
    jnicore_GetFloatField, jnicore_SetFloatField,
    jnicore_GetDoubleField, jnicore_SetDoubleField,
    jnicore_GetStaticObjectField, jnicore_SetStaticObjectField,
    jnicore_GetStaticBooleanField, jnicore_SetStaticBooleanField,
    jnicore_GetStaticByteField, jnicore_SetStaticByteField,
    jnicore_GetStaticCharField, jnicore_SetStaticCharField,
    jnicore_GetStaticShortField, jnicore_SetStaticShortField,
    jnicore_GetStaticIntField, jnicore_SetStaticIntField,
    jnicore_GetStaticLongField, jnicore_SetStaticLongField,
    jnicore_GetStaticFloatField, jnicore_SetStaticFloatField,
    jnicore_GetStaticDoubleField, jnicore_SetStaticDoubleField,
)
from jni_core.jni cimport (
    jclass, jobject, jmethodID, jfieldID, jvalue, JNIEnv,
    jboolean, jbyte, jchar, jshort, jint, jlong, jfloat, jdouble, jstring,
)

include "jni_core/conversions.pxi"

__javaclass__ = "java/util/concurrent/ThreadPoolExecutor"  # java.util.concurrent.ThreadPoolExecutor

cdef jclass _cls_ThreadPoolExecutor = NULL
cdef jmethodID _ctor_ThreadPoolExecutor_0 = NULL
cdef jmethodID _ctor_ThreadPoolExecutor_1 = NULL
cdef jmethodID _ctor_ThreadPoolExecutor_2 = NULL
cdef jmethodID _ctor_ThreadPoolExecutor_3 = NULL
cdef jmethodID _m_ThreadPoolExecutor_setThreadFactory_0 = NULL
cdef jmethodID _m_ThreadPoolExecutor_getThreadFactory_0 = NULL
cdef jmethodID _m_ThreadPoolExecutor_setRejectedExecutionHandler_0 = NULL
cdef jmethodID _m_ThreadPoolExecutor_getRejectedExecutionHandler_0 = NULL
cdef jmethodID _m_ThreadPoolExecutor_setCorePoolSize_0 = NULL
cdef jmethodID _m_ThreadPoolExecutor_getCorePoolSize_0 = NULL
cdef jmethodID _m_ThreadPoolExecutor_prestartCoreThread_0 = NULL
cdef jmethodID _m_ThreadPoolExecutor_prestartAllCoreThreads_0 = NULL
cdef jmethodID _m_ThreadPoolExecutor_setMaximumPoolSize_0 = NULL
cdef jmethodID _m_ThreadPoolExecutor_getMaximumPoolSize_0 = NULL
cdef jmethodID _m_ThreadPoolExecutor_setKeepAliveTime_0 = NULL
cdef jmethodID _m_ThreadPoolExecutor_getKeepAliveTime_0 = NULL
cdef jmethodID _m_ThreadPoolExecutor_purge_0 = NULL
cdef jmethodID _m_ThreadPoolExecutor_getActiveCount_0 = NULL
cdef jmethodID _m_ThreadPoolExecutor_getLargestPoolSize_0 = NULL
cdef jmethodID _m_ThreadPoolExecutor_getTaskCount_0 = NULL
cdef jmethodID _m_ThreadPoolExecutor_getCompletedTaskCount_0 = NULL
cdef jmethodID _m_ThreadPoolExecutor_remove_0 = NULL
cdef jmethodID _m_ThreadPoolExecutor_shutdown_0 = NULL
cdef jmethodID _m_ThreadPoolExecutor_toString_0 = NULL
cdef jmethodID _m_ThreadPoolExecutor_execute_0 = NULL
cdef jmethodID _m_ThreadPoolExecutor_getQueue_0 = NULL
cdef jmethodID _m_ThreadPoolExecutor_isTerminated_0 = NULL
cdef jmethodID _m_ThreadPoolExecutor_isShutdown_0 = NULL
cdef jmethodID _m_ThreadPoolExecutor_awaitTermination_0 = NULL
cdef jmethodID _m_ThreadPoolExecutor_shutdownNow_0 = NULL
cdef jmethodID _m_ThreadPoolExecutor_getPoolSize_0 = NULL
cdef jmethodID _m_ThreadPoolExecutor_isTerminating_0 = NULL
cdef jmethodID _m_ThreadPoolExecutor_allowCoreThreadTimeOut_0 = NULL
cdef jmethodID _m_ThreadPoolExecutor_allowsCoreThreadTimeOut_0 = NULL

cdef int _ensure_ids_ThreadPoolExecutor(JNIEnv* env) except -1:
    global _cls_ThreadPoolExecutor, _ctor_ThreadPoolExecutor_0, _ctor_ThreadPoolExecutor_1, _ctor_ThreadPoolExecutor_2, _ctor_ThreadPoolExecutor_3, _m_ThreadPoolExecutor_setThreadFactory_0, _m_ThreadPoolExecutor_getThreadFactory_0, _m_ThreadPoolExecutor_setRejectedExecutionHandler_0, _m_ThreadPoolExecutor_getRejectedExecutionHandler_0, _m_ThreadPoolExecutor_setCorePoolSize_0, _m_ThreadPoolExecutor_getCorePoolSize_0, _m_ThreadPoolExecutor_prestartCoreThread_0, _m_ThreadPoolExecutor_prestartAllCoreThreads_0, _m_ThreadPoolExecutor_setMaximumPoolSize_0, _m_ThreadPoolExecutor_getMaximumPoolSize_0, _m_ThreadPoolExecutor_setKeepAliveTime_0, _m_ThreadPoolExecutor_getKeepAliveTime_0, _m_ThreadPoolExecutor_purge_0, _m_ThreadPoolExecutor_getActiveCount_0, _m_ThreadPoolExecutor_getLargestPoolSize_0, _m_ThreadPoolExecutor_getTaskCount_0, _m_ThreadPoolExecutor_getCompletedTaskCount_0, _m_ThreadPoolExecutor_remove_0, _m_ThreadPoolExecutor_shutdown_0, _m_ThreadPoolExecutor_toString_0, _m_ThreadPoolExecutor_execute_0, _m_ThreadPoolExecutor_getQueue_0, _m_ThreadPoolExecutor_isTerminated_0, _m_ThreadPoolExecutor_isShutdown_0, _m_ThreadPoolExecutor_awaitTermination_0, _m_ThreadPoolExecutor_shutdownNow_0, _m_ThreadPoolExecutor_getPoolSize_0, _m_ThreadPoolExecutor_isTerminating_0, _m_ThreadPoolExecutor_allowCoreThreadTimeOut_0, _m_ThreadPoolExecutor_allowsCoreThreadTimeOut_0
    if _cls_ThreadPoolExecutor != NULL:
        return 0
    _cls_ThreadPoolExecutor = find_class_global(env, b"java/util/concurrent/ThreadPoolExecutor")
    _ctor_ThreadPoolExecutor_0 = get_method_id(env, _cls_ThreadPoolExecutor, b"<init>", b"(IIJLjava/util/concurrent/TimeUnit;Ljava/util/concurrent/BlockingQueue;)V")
    _ctor_ThreadPoolExecutor_1 = get_method_id(env, _cls_ThreadPoolExecutor, b"<init>", b"(IIJLjava/util/concurrent/TimeUnit;Ljava/util/concurrent/BlockingQueue;Ljava/util/concurrent/ThreadFactory;)V")
    _ctor_ThreadPoolExecutor_2 = get_method_id(env, _cls_ThreadPoolExecutor, b"<init>", b"(IIJLjava/util/concurrent/TimeUnit;Ljava/util/concurrent/BlockingQueue;Ljava/util/concurrent/ThreadFactory;Ljava/util/concurrent/RejectedExecutionHandler;)V")
    _ctor_ThreadPoolExecutor_3 = get_method_id(env, _cls_ThreadPoolExecutor, b"<init>", b"(IIJLjava/util/concurrent/TimeUnit;Ljava/util/concurrent/BlockingQueue;Ljava/util/concurrent/RejectedExecutionHandler;)V")
    _m_ThreadPoolExecutor_setThreadFactory_0 = get_method_id(env, _cls_ThreadPoolExecutor, b"setThreadFactory", b"(Ljava/util/concurrent/ThreadFactory;)V")
    _m_ThreadPoolExecutor_getThreadFactory_0 = get_method_id(env, _cls_ThreadPoolExecutor, b"getThreadFactory", b"()Ljava/util/concurrent/ThreadFactory;")
    _m_ThreadPoolExecutor_setRejectedExecutionHandler_0 = get_method_id(env, _cls_ThreadPoolExecutor, b"setRejectedExecutionHandler", b"(Ljava/util/concurrent/RejectedExecutionHandler;)V")
    _m_ThreadPoolExecutor_getRejectedExecutionHandler_0 = get_method_id(env, _cls_ThreadPoolExecutor, b"getRejectedExecutionHandler", b"()Ljava/util/concurrent/RejectedExecutionHandler;")
    _m_ThreadPoolExecutor_setCorePoolSize_0 = get_method_id(env, _cls_ThreadPoolExecutor, b"setCorePoolSize", b"(I)V")
    _m_ThreadPoolExecutor_getCorePoolSize_0 = get_method_id(env, _cls_ThreadPoolExecutor, b"getCorePoolSize", b"()I")
    _m_ThreadPoolExecutor_prestartCoreThread_0 = get_method_id(env, _cls_ThreadPoolExecutor, b"prestartCoreThread", b"()Z")
    _m_ThreadPoolExecutor_prestartAllCoreThreads_0 = get_method_id(env, _cls_ThreadPoolExecutor, b"prestartAllCoreThreads", b"()I")
    _m_ThreadPoolExecutor_setMaximumPoolSize_0 = get_method_id(env, _cls_ThreadPoolExecutor, b"setMaximumPoolSize", b"(I)V")
    _m_ThreadPoolExecutor_getMaximumPoolSize_0 = get_method_id(env, _cls_ThreadPoolExecutor, b"getMaximumPoolSize", b"()I")
    _m_ThreadPoolExecutor_setKeepAliveTime_0 = get_method_id(env, _cls_ThreadPoolExecutor, b"setKeepAliveTime", b"(JLjava/util/concurrent/TimeUnit;)V")
    _m_ThreadPoolExecutor_getKeepAliveTime_0 = get_method_id(env, _cls_ThreadPoolExecutor, b"getKeepAliveTime", b"(Ljava/util/concurrent/TimeUnit;)J")
    _m_ThreadPoolExecutor_purge_0 = get_method_id(env, _cls_ThreadPoolExecutor, b"purge", b"()V")
    _m_ThreadPoolExecutor_getActiveCount_0 = get_method_id(env, _cls_ThreadPoolExecutor, b"getActiveCount", b"()I")
    _m_ThreadPoolExecutor_getLargestPoolSize_0 = get_method_id(env, _cls_ThreadPoolExecutor, b"getLargestPoolSize", b"()I")
    _m_ThreadPoolExecutor_getTaskCount_0 = get_method_id(env, _cls_ThreadPoolExecutor, b"getTaskCount", b"()J")
    _m_ThreadPoolExecutor_getCompletedTaskCount_0 = get_method_id(env, _cls_ThreadPoolExecutor, b"getCompletedTaskCount", b"()J")
    _m_ThreadPoolExecutor_remove_0 = get_method_id(env, _cls_ThreadPoolExecutor, b"remove", b"(Ljava/lang/Runnable;)Z")
    _m_ThreadPoolExecutor_shutdown_0 = get_method_id(env, _cls_ThreadPoolExecutor, b"shutdown", b"()V")
    _m_ThreadPoolExecutor_toString_0 = get_method_id(env, _cls_ThreadPoolExecutor, b"toString", b"()Ljava/lang/String;")
    _m_ThreadPoolExecutor_execute_0 = get_method_id(env, _cls_ThreadPoolExecutor, b"execute", b"(Ljava/lang/Runnable;)V")
    _m_ThreadPoolExecutor_getQueue_0 = get_method_id(env, _cls_ThreadPoolExecutor, b"getQueue", b"()Ljava/util/concurrent/BlockingQueue;")
    _m_ThreadPoolExecutor_isTerminated_0 = get_method_id(env, _cls_ThreadPoolExecutor, b"isTerminated", b"()Z")
    _m_ThreadPoolExecutor_isShutdown_0 = get_method_id(env, _cls_ThreadPoolExecutor, b"isShutdown", b"()Z")
    _m_ThreadPoolExecutor_awaitTermination_0 = get_method_id(env, _cls_ThreadPoolExecutor, b"awaitTermination", b"(JLjava/util/concurrent/TimeUnit;)Z")
    _m_ThreadPoolExecutor_shutdownNow_0 = get_method_id(env, _cls_ThreadPoolExecutor, b"shutdownNow", b"()Ljava/util/List;")
    _m_ThreadPoolExecutor_getPoolSize_0 = get_method_id(env, _cls_ThreadPoolExecutor, b"getPoolSize", b"()I")
    _m_ThreadPoolExecutor_isTerminating_0 = get_method_id(env, _cls_ThreadPoolExecutor, b"isTerminating", b"()Z")
    _m_ThreadPoolExecutor_allowCoreThreadTimeOut_0 = get_method_id(env, _cls_ThreadPoolExecutor, b"allowCoreThreadTimeOut", b"(Z)V")
    _m_ThreadPoolExecutor_allowsCoreThreadTimeOut_0 = get_method_id(env, _cls_ThreadPoolExecutor, b"allowsCoreThreadTimeOut", b"()Z")
    return 0

cdef class ThreadPoolExecutor(JavaObject):
    """java.util.concurrent.ThreadPoolExecutor"""

    # TODO: 4 constructor overloads; only the first is wired.
    #   overload[0] = (IIJLjava/util/concurrent/TimeUnit;Ljava/util/concurrent/BlockingQueue;)V
    #   overload[1] = (IIJLjava/util/concurrent/TimeUnit;Ljava/util/concurrent/BlockingQueue;Ljava/util/concurrent/ThreadFactory;)V
    #   overload[2] = (IIJLjava/util/concurrent/TimeUnit;Ljava/util/concurrent/BlockingQueue;Ljava/util/concurrent/ThreadFactory;Ljava/util/concurrent/RejectedExecutionHandler;)V
    #   overload[3] = (IIJLjava/util/concurrent/TimeUnit;Ljava/util/concurrent/BlockingQueue;Ljava/util/concurrent/RejectedExecutionHandler;)V
    def __init__(self, p0, p1, p2, p3, p4):
        cdef JNIEnv* env = get_env()
        _ensure_ids_ThreadPoolExecutor(env)
        cdef jvalue _args[5]
        _args[0].i = py_to_jint(p0)
        _args[1].i = py_to_jint(p1)
        _args[2].j = py_to_jlong(p2)
        _args[3].l = (<JavaObject?>p3)._handle if p3 is not None else <jobject>NULL
        _args[4].l = (<JavaObject?>p4)._handle if p4 is not None else <jobject>NULL
        cdef jobject _ret = jnicore_NewObjectA(env, _cls_ThreadPoolExecutor, _ctor_ThreadPoolExecutor_0, _args)
        check_jni_exc(env)
        self._adopt_local(env, _ret)

    cdef void _setThreadFactory(self, jobject p0) except *:
        cdef JNIEnv* env = get_env()
        _ensure_ids_ThreadPoolExecutor(env)
        cdef jvalue _args[1]
        _args[0].l = p0
        jnicore_CallVoidMethodA(env, self._handle, _m_ThreadPoolExecutor_setThreadFactory_0, _args)
        check_jni_exc(env)

    def setThreadFactory(self, p0) -> None:
        cdef JNIEnv* env = get_env()
        cdef jobject _h0 = (<JavaObject?>p0)._handle if p0 is not None else <jobject>NULL
        self._setThreadFactory(_h0)

    cdef jobject _getThreadFactory(self) except? NULL:
        cdef JNIEnv* env = get_env()
        _ensure_ids_ThreadPoolExecutor(env)
        cdef jvalue _args[1]  # zero-arg call; _args ignored by JNI
        cdef jobject _ret = jnicore_CallObjectMethodA(env, self._handle, _m_ThreadPoolExecutor_getThreadFactory_0, _args)
        check_jni_exc(env)
        return _ret

    def getThreadFactory(self) -> object:
        cdef JNIEnv* env = get_env()
        cdef jobject _ret = NULL
        _ret = self._getThreadFactory()
        if _ret == NULL:
            return None
        cdef JavaObject _wrapped = JavaObject.__new__(JavaObject)
        _wrapped._adopt_local(env, _ret)
        return _wrapped

    cdef void _setRejectedExecutionHandler(self, jobject p0) except *:
        cdef JNIEnv* env = get_env()
        _ensure_ids_ThreadPoolExecutor(env)
        cdef jvalue _args[1]
        _args[0].l = p0
        jnicore_CallVoidMethodA(env, self._handle, _m_ThreadPoolExecutor_setRejectedExecutionHandler_0, _args)
        check_jni_exc(env)

    def setRejectedExecutionHandler(self, p0) -> None:
        cdef JNIEnv* env = get_env()
        cdef jobject _h0 = (<JavaObject?>p0)._handle if p0 is not None else <jobject>NULL
        self._setRejectedExecutionHandler(_h0)

    cdef jobject _getRejectedExecutionHandler(self) except? NULL:
        cdef JNIEnv* env = get_env()
        _ensure_ids_ThreadPoolExecutor(env)
        cdef jvalue _args[1]  # zero-arg call; _args ignored by JNI
        cdef jobject _ret = jnicore_CallObjectMethodA(env, self._handle, _m_ThreadPoolExecutor_getRejectedExecutionHandler_0, _args)
        check_jni_exc(env)
        return _ret

    def getRejectedExecutionHandler(self) -> object:
        cdef JNIEnv* env = get_env()
        cdef jobject _ret = NULL
        _ret = self._getRejectedExecutionHandler()
        if _ret == NULL:
            return None
        cdef JavaObject _wrapped = JavaObject.__new__(JavaObject)
        _wrapped._adopt_local(env, _ret)
        return _wrapped

    cdef void _setCorePoolSize(self, jint p0) except *:
        cdef JNIEnv* env = get_env()
        _ensure_ids_ThreadPoolExecutor(env)
        cdef jvalue _args[1]
        _args[0].i = p0
        jnicore_CallVoidMethodA(env, self._handle, _m_ThreadPoolExecutor_setCorePoolSize_0, _args)
        check_jni_exc(env)

    def setCorePoolSize(self, p0) -> None:
        cdef JNIEnv* env = get_env()
        cdef jint _c0 = py_to_jint(p0)
        self._setCorePoolSize(_c0)

    cdef jint _getCorePoolSize(self) except *:
        cdef JNIEnv* env = get_env()
        _ensure_ids_ThreadPoolExecutor(env)
        cdef jvalue _args[1]  # zero-arg call; _args ignored by JNI
        cdef jint _ret = jnicore_CallIntMethodA(env, self._handle, _m_ThreadPoolExecutor_getCorePoolSize_0, _args)
        check_jni_exc(env)
        return _ret

    def getCorePoolSize(self) -> int:
        cdef JNIEnv* env = get_env()
        cdef jint _ret = 0
        _ret = self._getCorePoolSize()
        return <int>_ret

    cdef jboolean _prestartCoreThread(self) except *:
        cdef JNIEnv* env = get_env()
        _ensure_ids_ThreadPoolExecutor(env)
        cdef jvalue _args[1]  # zero-arg call; _args ignored by JNI
        cdef jboolean _ret = jnicore_CallBooleanMethodA(env, self._handle, _m_ThreadPoolExecutor_prestartCoreThread_0, _args)
        check_jni_exc(env)
        return _ret

    def prestartCoreThread(self) -> bool:
        cdef JNIEnv* env = get_env()
        cdef jboolean _ret = 0
        _ret = self._prestartCoreThread()
        return jboolean_to_py(_ret)

    cdef jint _prestartAllCoreThreads(self) except *:
        cdef JNIEnv* env = get_env()
        _ensure_ids_ThreadPoolExecutor(env)
        cdef jvalue _args[1]  # zero-arg call; _args ignored by JNI
        cdef jint _ret = jnicore_CallIntMethodA(env, self._handle, _m_ThreadPoolExecutor_prestartAllCoreThreads_0, _args)
        check_jni_exc(env)
        return _ret

    def prestartAllCoreThreads(self) -> int:
        cdef JNIEnv* env = get_env()
        cdef jint _ret = 0
        _ret = self._prestartAllCoreThreads()
        return <int>_ret

    cdef void _setMaximumPoolSize(self, jint p0) except *:
        cdef JNIEnv* env = get_env()
        _ensure_ids_ThreadPoolExecutor(env)
        cdef jvalue _args[1]
        _args[0].i = p0
        jnicore_CallVoidMethodA(env, self._handle, _m_ThreadPoolExecutor_setMaximumPoolSize_0, _args)
        check_jni_exc(env)

    def setMaximumPoolSize(self, p0) -> None:
        cdef JNIEnv* env = get_env()
        cdef jint _c0 = py_to_jint(p0)
        self._setMaximumPoolSize(_c0)

    cdef jint _getMaximumPoolSize(self) except *:
        cdef JNIEnv* env = get_env()
        _ensure_ids_ThreadPoolExecutor(env)
        cdef jvalue _args[1]  # zero-arg call; _args ignored by JNI
        cdef jint _ret = jnicore_CallIntMethodA(env, self._handle, _m_ThreadPoolExecutor_getMaximumPoolSize_0, _args)
        check_jni_exc(env)
        return _ret

    def getMaximumPoolSize(self) -> int:
        cdef JNIEnv* env = get_env()
        cdef jint _ret = 0
        _ret = self._getMaximumPoolSize()
        return <int>_ret

    cdef void _setKeepAliveTime(self, jlong p0, jobject p1) except *:
        cdef JNIEnv* env = get_env()
        _ensure_ids_ThreadPoolExecutor(env)
        cdef jvalue _args[2]
        _args[0].j = p0
        _args[1].l = p1
        jnicore_CallVoidMethodA(env, self._handle, _m_ThreadPoolExecutor_setKeepAliveTime_0, _args)
        check_jni_exc(env)

    def setKeepAliveTime(self, p0, p1) -> None:
        cdef JNIEnv* env = get_env()
        cdef jlong _c0 = py_to_jlong(p0)
        cdef jobject _h1 = (<JavaObject?>p1)._handle if p1 is not None else <jobject>NULL
        self._setKeepAliveTime(_c0, _h1)

    cdef jlong _getKeepAliveTime(self, jobject p0) except *:
        cdef JNIEnv* env = get_env()
        _ensure_ids_ThreadPoolExecutor(env)
        cdef jvalue _args[1]
        _args[0].l = p0
        cdef jlong _ret = jnicore_CallLongMethodA(env, self._handle, _m_ThreadPoolExecutor_getKeepAliveTime_0, _args)
        check_jni_exc(env)
        return _ret

    def getKeepAliveTime(self, p0) -> int:
        cdef JNIEnv* env = get_env()
        cdef jlong _ret = 0
        cdef jobject _h0 = (<JavaObject?>p0)._handle if p0 is not None else <jobject>NULL
        _ret = self._getKeepAliveTime(_h0)
        return <long long>_ret

    cdef void _purge(self) except *:
        cdef JNIEnv* env = get_env()
        _ensure_ids_ThreadPoolExecutor(env)
        cdef jvalue _args[1]  # zero-arg call; _args ignored by JNI
        jnicore_CallVoidMethodA(env, self._handle, _m_ThreadPoolExecutor_purge_0, _args)
        check_jni_exc(env)

    def purge(self) -> None:
        cdef JNIEnv* env = get_env()
        self._purge()

    cdef jint _getActiveCount(self) except *:
        cdef JNIEnv* env = get_env()
        _ensure_ids_ThreadPoolExecutor(env)
        cdef jvalue _args[1]  # zero-arg call; _args ignored by JNI
        cdef jint _ret = jnicore_CallIntMethodA(env, self._handle, _m_ThreadPoolExecutor_getActiveCount_0, _args)
        check_jni_exc(env)
        return _ret

    def getActiveCount(self) -> int:
        cdef JNIEnv* env = get_env()
        cdef jint _ret = 0
        _ret = self._getActiveCount()
        return <int>_ret

    cdef jint _getLargestPoolSize(self) except *:
        cdef JNIEnv* env = get_env()
        _ensure_ids_ThreadPoolExecutor(env)
        cdef jvalue _args[1]  # zero-arg call; _args ignored by JNI
        cdef jint _ret = jnicore_CallIntMethodA(env, self._handle, _m_ThreadPoolExecutor_getLargestPoolSize_0, _args)
        check_jni_exc(env)
        return _ret

    def getLargestPoolSize(self) -> int:
        cdef JNIEnv* env = get_env()
        cdef jint _ret = 0
        _ret = self._getLargestPoolSize()
        return <int>_ret

    cdef jlong _getTaskCount(self) except *:
        cdef JNIEnv* env = get_env()
        _ensure_ids_ThreadPoolExecutor(env)
        cdef jvalue _args[1]  # zero-arg call; _args ignored by JNI
        cdef jlong _ret = jnicore_CallLongMethodA(env, self._handle, _m_ThreadPoolExecutor_getTaskCount_0, _args)
        check_jni_exc(env)
        return _ret

    def getTaskCount(self) -> int:
        cdef JNIEnv* env = get_env()
        cdef jlong _ret = 0
        _ret = self._getTaskCount()
        return <long long>_ret

    cdef jlong _getCompletedTaskCount(self) except *:
        cdef JNIEnv* env = get_env()
        _ensure_ids_ThreadPoolExecutor(env)
        cdef jvalue _args[1]  # zero-arg call; _args ignored by JNI
        cdef jlong _ret = jnicore_CallLongMethodA(env, self._handle, _m_ThreadPoolExecutor_getCompletedTaskCount_0, _args)
        check_jni_exc(env)
        return _ret

    def getCompletedTaskCount(self) -> int:
        cdef JNIEnv* env = get_env()
        cdef jlong _ret = 0
        _ret = self._getCompletedTaskCount()
        return <long long>_ret

    cdef jboolean _remove(self, jobject p0) except *:
        cdef JNIEnv* env = get_env()
        _ensure_ids_ThreadPoolExecutor(env)
        cdef jvalue _args[1]
        _args[0].l = p0
        cdef jboolean _ret = jnicore_CallBooleanMethodA(env, self._handle, _m_ThreadPoolExecutor_remove_0, _args)
        check_jni_exc(env)
        return _ret

    def remove(self, p0) -> bool:
        cdef JNIEnv* env = get_env()
        cdef jboolean _ret = 0
        cdef jobject _h0 = (<JavaObject?>p0)._handle if p0 is not None else <jobject>NULL
        _ret = self._remove(_h0)
        return jboolean_to_py(_ret)

    cdef void _shutdown(self) except *:
        cdef JNIEnv* env = get_env()
        _ensure_ids_ThreadPoolExecutor(env)
        cdef jvalue _args[1]  # zero-arg call; _args ignored by JNI
        jnicore_CallVoidMethodA(env, self._handle, _m_ThreadPoolExecutor_shutdown_0, _args)
        check_jni_exc(env)

    def shutdown(self) -> None:
        cdef JNIEnv* env = get_env()
        self._shutdown()

    cdef jstring _toString(self) except? NULL:
        cdef JNIEnv* env = get_env()
        _ensure_ids_ThreadPoolExecutor(env)
        cdef jvalue _args[1]  # zero-arg call; _args ignored by JNI
        cdef jstring _ret = <jstring>jnicore_CallObjectMethodA(env, self._handle, _m_ThreadPoolExecutor_toString_0, _args)
        check_jni_exc(env)
        return <jstring>_ret

    def toString(self) -> str:
        cdef JNIEnv* env = get_env()
        cdef jstring _ret = NULL
        _ret = self._toString()
        return py_str(env, _ret)

    cdef void _execute(self, jobject p0) except *:
        cdef JNIEnv* env = get_env()
        _ensure_ids_ThreadPoolExecutor(env)
        cdef jvalue _args[1]
        _args[0].l = p0
        jnicore_CallVoidMethodA(env, self._handle, _m_ThreadPoolExecutor_execute_0, _args)
        check_jni_exc(env)

    def execute(self, p0) -> None:
        cdef JNIEnv* env = get_env()
        cdef jobject _h0 = (<JavaObject?>p0)._handle if p0 is not None else <jobject>NULL
        self._execute(_h0)

    cdef jobject _getQueue(self) except? NULL:
        cdef JNIEnv* env = get_env()
        _ensure_ids_ThreadPoolExecutor(env)
        cdef jvalue _args[1]  # zero-arg call; _args ignored by JNI
        cdef jobject _ret = jnicore_CallObjectMethodA(env, self._handle, _m_ThreadPoolExecutor_getQueue_0, _args)
        check_jni_exc(env)
        return _ret

    def getQueue(self) -> object:
        cdef JNIEnv* env = get_env()
        cdef jobject _ret = NULL
        _ret = self._getQueue()
        if _ret == NULL:
            return None
        cdef JavaObject _wrapped = JavaObject.__new__(JavaObject)
        _wrapped._adopt_local(env, _ret)
        return _wrapped

    cdef jboolean _isTerminated(self) except *:
        cdef JNIEnv* env = get_env()
        _ensure_ids_ThreadPoolExecutor(env)
        cdef jvalue _args[1]  # zero-arg call; _args ignored by JNI
        cdef jboolean _ret = jnicore_CallBooleanMethodA(env, self._handle, _m_ThreadPoolExecutor_isTerminated_0, _args)
        check_jni_exc(env)
        return _ret

    def isTerminated(self) -> bool:
        cdef JNIEnv* env = get_env()
        cdef jboolean _ret = 0
        _ret = self._isTerminated()
        return jboolean_to_py(_ret)

    cdef jboolean _isShutdown(self) except *:
        cdef JNIEnv* env = get_env()
        _ensure_ids_ThreadPoolExecutor(env)
        cdef jvalue _args[1]  # zero-arg call; _args ignored by JNI
        cdef jboolean _ret = jnicore_CallBooleanMethodA(env, self._handle, _m_ThreadPoolExecutor_isShutdown_0, _args)
        check_jni_exc(env)
        return _ret

    def isShutdown(self) -> bool:
        cdef JNIEnv* env = get_env()
        cdef jboolean _ret = 0
        _ret = self._isShutdown()
        return jboolean_to_py(_ret)

    cdef jboolean _awaitTermination(self, jlong p0, jobject p1) except *:
        cdef JNIEnv* env = get_env()
        _ensure_ids_ThreadPoolExecutor(env)
        cdef jvalue _args[2]
        _args[0].j = p0
        _args[1].l = p1
        cdef jboolean _ret = jnicore_CallBooleanMethodA(env, self._handle, _m_ThreadPoolExecutor_awaitTermination_0, _args)
        check_jni_exc(env)
        return _ret

    def awaitTermination(self, p0, p1) -> bool:
        cdef JNIEnv* env = get_env()
        cdef jboolean _ret = 0
        cdef jlong _c0 = py_to_jlong(p0)
        cdef jobject _h1 = (<JavaObject?>p1)._handle if p1 is not None else <jobject>NULL
        _ret = self._awaitTermination(_c0, _h1)
        return jboolean_to_py(_ret)

    cdef jobject _shutdownNow(self) except? NULL:
        cdef JNIEnv* env = get_env()
        _ensure_ids_ThreadPoolExecutor(env)
        cdef jvalue _args[1]  # zero-arg call; _args ignored by JNI
        cdef jobject _ret = jnicore_CallObjectMethodA(env, self._handle, _m_ThreadPoolExecutor_shutdownNow_0, _args)
        check_jni_exc(env)
        return _ret

    def shutdownNow(self) -> object:
        cdef JNIEnv* env = get_env()
        cdef jobject _ret = NULL
        _ret = self._shutdownNow()
        if _ret == NULL:
            return None
        cdef JavaObject _wrapped = JavaObject.__new__(JavaObject)
        _wrapped._adopt_local(env, _ret)
        return _wrapped

    cdef jint _getPoolSize(self) except *:
        cdef JNIEnv* env = get_env()
        _ensure_ids_ThreadPoolExecutor(env)
        cdef jvalue _args[1]  # zero-arg call; _args ignored by JNI
        cdef jint _ret = jnicore_CallIntMethodA(env, self._handle, _m_ThreadPoolExecutor_getPoolSize_0, _args)
        check_jni_exc(env)
        return _ret

    def getPoolSize(self) -> int:
        cdef JNIEnv* env = get_env()
        cdef jint _ret = 0
        _ret = self._getPoolSize()
        return <int>_ret

    cdef jboolean _isTerminating(self) except *:
        cdef JNIEnv* env = get_env()
        _ensure_ids_ThreadPoolExecutor(env)
        cdef jvalue _args[1]  # zero-arg call; _args ignored by JNI
        cdef jboolean _ret = jnicore_CallBooleanMethodA(env, self._handle, _m_ThreadPoolExecutor_isTerminating_0, _args)
        check_jni_exc(env)
        return _ret

    def isTerminating(self) -> bool:
        cdef JNIEnv* env = get_env()
        cdef jboolean _ret = 0
        _ret = self._isTerminating()
        return jboolean_to_py(_ret)

    cdef void _allowCoreThreadTimeOut(self, jboolean p0) except *:
        cdef JNIEnv* env = get_env()
        _ensure_ids_ThreadPoolExecutor(env)
        cdef jvalue _args[1]
        _args[0].z = p0
        jnicore_CallVoidMethodA(env, self._handle, _m_ThreadPoolExecutor_allowCoreThreadTimeOut_0, _args)
        check_jni_exc(env)

    def allowCoreThreadTimeOut(self, p0) -> None:
        cdef JNIEnv* env = get_env()
        cdef jboolean _c0 = py_to_jboolean(p0)
        self._allowCoreThreadTimeOut(_c0)

    cdef jboolean _allowsCoreThreadTimeOut(self) except *:
        cdef JNIEnv* env = get_env()
        _ensure_ids_ThreadPoolExecutor(env)
        cdef jvalue _args[1]  # zero-arg call; _args ignored by JNI
        cdef jboolean _ret = jnicore_CallBooleanMethodA(env, self._handle, _m_ThreadPoolExecutor_allowsCoreThreadTimeOut_0, _args)
        check_jni_exc(env)
        return _ret

    def allowsCoreThreadTimeOut(self) -> bool:
        cdef JNIEnv* env = get_env()
        cdef jboolean _ret = 0
        _ret = self._allowsCoreThreadTimeOut()
        return jboolean_to_py(_ret)

# Nested class: java.util.concurrent.ThreadPoolExecutor$AbortPolicy  (JNI: java/util/concurrent/ThreadPoolExecutor$AbortPolicy)
cdef jclass _cls_AbortPolicy = NULL
cdef jmethodID _ctor_AbortPolicy_0 = NULL
cdef jmethodID _m_AbortPolicy_rejectedExecution_0 = NULL

cdef int _ensure_ids_AbortPolicy(JNIEnv* env) except -1:
    global _cls_AbortPolicy, _ctor_AbortPolicy_0, _m_AbortPolicy_rejectedExecution_0
    if _cls_AbortPolicy != NULL:
        return 0
    _cls_AbortPolicy = find_class_global(env, b"java/util/concurrent/ThreadPoolExecutor$AbortPolicy")
    _ctor_AbortPolicy_0 = get_method_id(env, _cls_AbortPolicy, b"<init>", b"()V")
    _m_AbortPolicy_rejectedExecution_0 = get_method_id(env, _cls_AbortPolicy, b"rejectedExecution", b"(Ljava/lang/Runnable;Ljava/util/concurrent/ThreadPoolExecutor;)V")
    return 0

cdef class AbortPolicy(JavaObject):
    """java.util.concurrent.ThreadPoolExecutor$AbortPolicy"""

    def __init__(self, ):
        cdef JNIEnv* env = get_env()
        _ensure_ids_AbortPolicy(env)
        cdef jvalue _args[1]  # unused; arrayless calls disallowed in Cython
        cdef jobject _ret = jnicore_NewObjectA(env, _cls_AbortPolicy, _ctor_AbortPolicy_0, _args)
        check_jni_exc(env)
        self._adopt_local(env, _ret)

    cdef void _rejectedExecution(self, jobject p0, jobject p1) except *:
        cdef JNIEnv* env = get_env()
        _ensure_ids_AbortPolicy(env)
        cdef jvalue _args[2]
        _args[0].l = p0
        _args[1].l = p1
        jnicore_CallVoidMethodA(env, self._handle, _m_AbortPolicy_rejectedExecution_0, _args)
        check_jni_exc(env)

    def rejectedExecution(self, p0, p1) -> None:
        cdef JNIEnv* env = get_env()
        cdef jobject _h0 = (<JavaObject?>p0)._handle if p0 is not None else <jobject>NULL
        cdef jobject _h1 = (<JavaObject?>p1)._handle if p1 is not None else <jobject>NULL
        self._rejectedExecution(_h0, _h1)

# Nested class: java.util.concurrent.ThreadPoolExecutor$DiscardOldestPolicy  (JNI: java/util/concurrent/ThreadPoolExecutor$DiscardOldestPolicy)
cdef jclass _cls_DiscardOldestPolicy = NULL
cdef jmethodID _ctor_DiscardOldestPolicy_0 = NULL
cdef jmethodID _m_DiscardOldestPolicy_rejectedExecution_0 = NULL

cdef int _ensure_ids_DiscardOldestPolicy(JNIEnv* env) except -1:
    global _cls_DiscardOldestPolicy, _ctor_DiscardOldestPolicy_0, _m_DiscardOldestPolicy_rejectedExecution_0
    if _cls_DiscardOldestPolicy != NULL:
        return 0
    _cls_DiscardOldestPolicy = find_class_global(env, b"java/util/concurrent/ThreadPoolExecutor$DiscardOldestPolicy")
    _ctor_DiscardOldestPolicy_0 = get_method_id(env, _cls_DiscardOldestPolicy, b"<init>", b"()V")
    _m_DiscardOldestPolicy_rejectedExecution_0 = get_method_id(env, _cls_DiscardOldestPolicy, b"rejectedExecution", b"(Ljava/lang/Runnable;Ljava/util/concurrent/ThreadPoolExecutor;)V")
    return 0

cdef class DiscardOldestPolicy(JavaObject):
    """java.util.concurrent.ThreadPoolExecutor$DiscardOldestPolicy"""

    def __init__(self, ):
        cdef JNIEnv* env = get_env()
        _ensure_ids_DiscardOldestPolicy(env)
        cdef jvalue _args[1]  # unused; arrayless calls disallowed in Cython
        cdef jobject _ret = jnicore_NewObjectA(env, _cls_DiscardOldestPolicy, _ctor_DiscardOldestPolicy_0, _args)
        check_jni_exc(env)
        self._adopt_local(env, _ret)

    cdef void _rejectedExecution(self, jobject p0, jobject p1) except *:
        cdef JNIEnv* env = get_env()
        _ensure_ids_DiscardOldestPolicy(env)
        cdef jvalue _args[2]
        _args[0].l = p0
        _args[1].l = p1
        jnicore_CallVoidMethodA(env, self._handle, _m_DiscardOldestPolicy_rejectedExecution_0, _args)
        check_jni_exc(env)

    def rejectedExecution(self, p0, p1) -> None:
        cdef JNIEnv* env = get_env()
        cdef jobject _h0 = (<JavaObject?>p0)._handle if p0 is not None else <jobject>NULL
        cdef jobject _h1 = (<JavaObject?>p1)._handle if p1 is not None else <jobject>NULL
        self._rejectedExecution(_h0, _h1)

# Nested class: java.util.concurrent.ThreadPoolExecutor$DiscardPolicy  (JNI: java/util/concurrent/ThreadPoolExecutor$DiscardPolicy)
cdef jclass _cls_DiscardPolicy = NULL
cdef jmethodID _ctor_DiscardPolicy_0 = NULL
cdef jmethodID _m_DiscardPolicy_rejectedExecution_0 = NULL

cdef int _ensure_ids_DiscardPolicy(JNIEnv* env) except -1:
    global _cls_DiscardPolicy, _ctor_DiscardPolicy_0, _m_DiscardPolicy_rejectedExecution_0
    if _cls_DiscardPolicy != NULL:
        return 0
    _cls_DiscardPolicy = find_class_global(env, b"java/util/concurrent/ThreadPoolExecutor$DiscardPolicy")
    _ctor_DiscardPolicy_0 = get_method_id(env, _cls_DiscardPolicy, b"<init>", b"()V")
    _m_DiscardPolicy_rejectedExecution_0 = get_method_id(env, _cls_DiscardPolicy, b"rejectedExecution", b"(Ljava/lang/Runnable;Ljava/util/concurrent/ThreadPoolExecutor;)V")
    return 0

cdef class DiscardPolicy(JavaObject):
    """java.util.concurrent.ThreadPoolExecutor$DiscardPolicy"""

    def __init__(self, ):
        cdef JNIEnv* env = get_env()
        _ensure_ids_DiscardPolicy(env)
        cdef jvalue _args[1]  # unused; arrayless calls disallowed in Cython
        cdef jobject _ret = jnicore_NewObjectA(env, _cls_DiscardPolicy, _ctor_DiscardPolicy_0, _args)
        check_jni_exc(env)
        self._adopt_local(env, _ret)

    cdef void _rejectedExecution(self, jobject p0, jobject p1) except *:
        cdef JNIEnv* env = get_env()
        _ensure_ids_DiscardPolicy(env)
        cdef jvalue _args[2]
        _args[0].l = p0
        _args[1].l = p1
        jnicore_CallVoidMethodA(env, self._handle, _m_DiscardPolicy_rejectedExecution_0, _args)
        check_jni_exc(env)

    def rejectedExecution(self, p0, p1) -> None:
        cdef JNIEnv* env = get_env()
        cdef jobject _h0 = (<JavaObject?>p0)._handle if p0 is not None else <jobject>NULL
        cdef jobject _h1 = (<JavaObject?>p1)._handle if p1 is not None else <jobject>NULL
        self._rejectedExecution(_h0, _h1)

# Nested class: java.util.concurrent.ThreadPoolExecutor$CallerRunsPolicy  (JNI: java/util/concurrent/ThreadPoolExecutor$CallerRunsPolicy)
cdef jclass _cls_CallerRunsPolicy = NULL
cdef jmethodID _ctor_CallerRunsPolicy_0 = NULL
cdef jmethodID _m_CallerRunsPolicy_rejectedExecution_0 = NULL

cdef int _ensure_ids_CallerRunsPolicy(JNIEnv* env) except -1:
    global _cls_CallerRunsPolicy, _ctor_CallerRunsPolicy_0, _m_CallerRunsPolicy_rejectedExecution_0
    if _cls_CallerRunsPolicy != NULL:
        return 0
    _cls_CallerRunsPolicy = find_class_global(env, b"java/util/concurrent/ThreadPoolExecutor$CallerRunsPolicy")
    _ctor_CallerRunsPolicy_0 = get_method_id(env, _cls_CallerRunsPolicy, b"<init>", b"()V")
    _m_CallerRunsPolicy_rejectedExecution_0 = get_method_id(env, _cls_CallerRunsPolicy, b"rejectedExecution", b"(Ljava/lang/Runnable;Ljava/util/concurrent/ThreadPoolExecutor;)V")
    return 0

cdef class CallerRunsPolicy(JavaObject):
    """java.util.concurrent.ThreadPoolExecutor$CallerRunsPolicy"""

    def __init__(self, ):
        cdef JNIEnv* env = get_env()
        _ensure_ids_CallerRunsPolicy(env)
        cdef jvalue _args[1]  # unused; arrayless calls disallowed in Cython
        cdef jobject _ret = jnicore_NewObjectA(env, _cls_CallerRunsPolicy, _ctor_CallerRunsPolicy_0, _args)
        check_jni_exc(env)
        self._adopt_local(env, _ret)

    cdef void _rejectedExecution(self, jobject p0, jobject p1) except *:
        cdef JNIEnv* env = get_env()
        _ensure_ids_CallerRunsPolicy(env)
        cdef jvalue _args[2]
        _args[0].l = p0
        _args[1].l = p1
        jnicore_CallVoidMethodA(env, self._handle, _m_CallerRunsPolicy_rejectedExecution_0, _args)
        check_jni_exc(env)

    def rejectedExecution(self, p0, p1) -> None:
        cdef JNIEnv* env = get_env()
        cdef jobject _h0 = (<JavaObject?>p0)._handle if p0 is not None else <jobject>NULL
        cdef jobject _h1 = (<JavaObject?>p1)._handle if p1 is not None else <jobject>NULL
        self._rejectedExecution(_h0, _h1)

