from typing import Any, ClassVar, overload
from android.net.wifi.aware.WifiAwareSession import WifiAwareSession

class AttachCallback:
    def __init__(self) -> None: ...
    def onAwareSessionTerminated(self) -> None: ...
    def onAttachFailed(self) -> None: ...
    def onAttached(self, p0: WifiAwareSession) -> None: ...
