from typing import Any, ClassVar, overload

class Rfc822Tokenizer:
    def __init__(self) -> None: ...
    @overload
    @staticmethod
    def tokenize(p0: str) -> Any: ...
    @overload
    @staticmethod
    def tokenize(p0: str, p1: list) -> None: ...
    def findTokenStart(self, p0: str, p1: int) -> int: ...
    def findTokenEnd(self, p0: str, p1: int) -> int: ...
    def terminateToken(self, p0: str) -> str: ...
