from typing import Any, ClassVar, overload

class Rfc822Token:
    def __init__(self, p0: str, p1: str, p2: str) -> None: ...
    @staticmethod
    def quoteName(p0: str) -> str: ...
    @staticmethod
    def quoteComment(p0: str) -> str: ...
    @staticmethod
    def quoteNameIfNecessary(p0: str) -> str: ...
    def setAddress(self, p0: str) -> None: ...
    def getComment(self) -> str: ...
    def getName(self) -> str: ...
    def equals(self, p0: Any) -> bool: ...
    def toString(self) -> str: ...
    def hashCode(self) -> int: ...
    def setName(self, p0: str) -> None: ...
    def getAddress(self) -> str: ...
    def setComment(self, p0: str) -> None: ...
