# cython: language_level=3
# Generated by pyjnius-wrap cython — do not edit by hand.

from jni_core._core cimport (
    JavaObject, get_env, check_jni_exc,
    find_class_global, get_method_id, get_static_method_id,
    get_field_id, get_static_field_id, j_str, py_str,
)
from jni_core._dispatch cimport (
    jnicore_NewObjectA, jnicore_DeleteLocalRef,
    jnicore_CallVoidMethodA, jnicore_CallObjectMethodA,
    jnicore_CallBooleanMethodA, jnicore_CallByteMethodA,
    jnicore_CallCharMethodA, jnicore_CallShortMethodA,
    jnicore_CallIntMethodA, jnicore_CallLongMethodA,
    jnicore_CallFloatMethodA, jnicore_CallDoubleMethodA,
    jnicore_CallStaticVoidMethodA, jnicore_CallStaticObjectMethodA,
    jnicore_CallStaticBooleanMethodA, jnicore_CallStaticByteMethodA,
    jnicore_CallStaticCharMethodA, jnicore_CallStaticShortMethodA,
    jnicore_CallStaticIntMethodA, jnicore_CallStaticLongMethodA,
    jnicore_CallStaticFloatMethodA, jnicore_CallStaticDoubleMethodA,
    jnicore_GetObjectField, jnicore_SetObjectField,
    jnicore_GetBooleanField, jnicore_SetBooleanField,
    jnicore_GetByteField, jnicore_SetByteField,
    jnicore_GetCharField, jnicore_SetCharField,
    jnicore_GetShortField, jnicore_SetShortField,
    jnicore_GetIntField, jnicore_SetIntField,
    jnicore_GetLongField, jnicore_SetLongField,
    jnicore_GetFloatField, jnicore_SetFloatField,
    jnicore_GetDoubleField, jnicore_SetDoubleField,
    jnicore_GetStaticObjectField, jnicore_SetStaticObjectField,
    jnicore_GetStaticBooleanField, jnicore_SetStaticBooleanField,
    jnicore_GetStaticByteField, jnicore_SetStaticByteField,
    jnicore_GetStaticCharField, jnicore_SetStaticCharField,
    jnicore_GetStaticShortField, jnicore_SetStaticShortField,
    jnicore_GetStaticIntField, jnicore_SetStaticIntField,
    jnicore_GetStaticLongField, jnicore_SetStaticLongField,
    jnicore_GetStaticFloatField, jnicore_SetStaticFloatField,
    jnicore_GetStaticDoubleField, jnicore_SetStaticDoubleField,
)
from jni_core.jni cimport (
    jclass, jobject, jmethodID, jfieldID, jvalue, JNIEnv,
    jboolean, jbyte, jchar, jshort, jint, jlong, jfloat, jdouble, jstring,
)

include "jni_core/conversions.pxi"

__javaclass__ = "android/net/vcn/VcnGatewayConnectionConfig"  # android.net.vcn.VcnGatewayConnectionConfig

cdef jclass _cls_VcnGatewayConnectionConfig = NULL
cdef jmethodID _m_VcnGatewayConnectionConfig_getGatewayConnectionName_0 = NULL
cdef jmethodID _m_VcnGatewayConnectionConfig_getRetryIntervalsMillis_0 = NULL
cdef jmethodID _m_VcnGatewayConnectionConfig_getExposedCapabilities_0 = NULL
cdef jmethodID _m_VcnGatewayConnectionConfig_getMinUdpPort4500NatTimeoutSeconds_0 = NULL
cdef jmethodID _m_VcnGatewayConnectionConfig_isSafeModeEnabled_0 = NULL
cdef jmethodID _m_VcnGatewayConnectionConfig_hasGatewayOption_0 = NULL
cdef jmethodID _m_VcnGatewayConnectionConfig_getMaxMtu_0 = NULL
cdef jmethodID _m_VcnGatewayConnectionConfig_getVcnUnderlyingNetworkPriorities_0 = NULL
cdef jmethodID _m_VcnGatewayConnectionConfig_equals_0 = NULL
cdef jmethodID _m_VcnGatewayConnectionConfig_hashCode_0 = NULL
cdef jfieldID _sf_VcnGatewayConnectionConfig_VCN_GATEWAY_OPTION_ENABLE_DATA_STALL_RECOVERY_WITH_MOBILITY = NULL

cdef int _ensure_ids_VcnGatewayConnectionConfig(JNIEnv* env) except -1:
    global _cls_VcnGatewayConnectionConfig, _m_VcnGatewayConnectionConfig_getGatewayConnectionName_0, _m_VcnGatewayConnectionConfig_getRetryIntervalsMillis_0, _m_VcnGatewayConnectionConfig_getExposedCapabilities_0, _m_VcnGatewayConnectionConfig_getMinUdpPort4500NatTimeoutSeconds_0, _m_VcnGatewayConnectionConfig_isSafeModeEnabled_0, _m_VcnGatewayConnectionConfig_hasGatewayOption_0, _m_VcnGatewayConnectionConfig_getMaxMtu_0, _m_VcnGatewayConnectionConfig_getVcnUnderlyingNetworkPriorities_0, _m_VcnGatewayConnectionConfig_equals_0, _m_VcnGatewayConnectionConfig_hashCode_0, _sf_VcnGatewayConnectionConfig_VCN_GATEWAY_OPTION_ENABLE_DATA_STALL_RECOVERY_WITH_MOBILITY
    if _cls_VcnGatewayConnectionConfig != NULL:
        return 0
    _cls_VcnGatewayConnectionConfig = find_class_global(env, b"android/net/vcn/VcnGatewayConnectionConfig")
    _m_VcnGatewayConnectionConfig_getGatewayConnectionName_0 = get_method_id(env, _cls_VcnGatewayConnectionConfig, b"getGatewayConnectionName", b"()Ljava/lang/String;")
    _m_VcnGatewayConnectionConfig_getRetryIntervalsMillis_0 = get_method_id(env, _cls_VcnGatewayConnectionConfig, b"getRetryIntervalsMillis", b"()[J")
    _m_VcnGatewayConnectionConfig_getExposedCapabilities_0 = get_method_id(env, _cls_VcnGatewayConnectionConfig, b"getExposedCapabilities", b"()[I")
    _m_VcnGatewayConnectionConfig_getMinUdpPort4500NatTimeoutSeconds_0 = get_method_id(env, _cls_VcnGatewayConnectionConfig, b"getMinUdpPort4500NatTimeoutSeconds", b"()I")
    _m_VcnGatewayConnectionConfig_isSafeModeEnabled_0 = get_method_id(env, _cls_VcnGatewayConnectionConfig, b"isSafeModeEnabled", b"()Z")
    _m_VcnGatewayConnectionConfig_hasGatewayOption_0 = get_method_id(env, _cls_VcnGatewayConnectionConfig, b"hasGatewayOption", b"(I)Z")
    _m_VcnGatewayConnectionConfig_getMaxMtu_0 = get_method_id(env, _cls_VcnGatewayConnectionConfig, b"getMaxMtu", b"()I")
    _m_VcnGatewayConnectionConfig_getVcnUnderlyingNetworkPriorities_0 = get_method_id(env, _cls_VcnGatewayConnectionConfig, b"getVcnUnderlyingNetworkPriorities", b"()Ljava/util/List;")
    _m_VcnGatewayConnectionConfig_equals_0 = get_method_id(env, _cls_VcnGatewayConnectionConfig, b"equals", b"(Ljava/lang/Object;)Z")
    _m_VcnGatewayConnectionConfig_hashCode_0 = get_method_id(env, _cls_VcnGatewayConnectionConfig, b"hashCode", b"()I")
    _sf_VcnGatewayConnectionConfig_VCN_GATEWAY_OPTION_ENABLE_DATA_STALL_RECOVERY_WITH_MOBILITY = get_static_field_id(env, _cls_VcnGatewayConnectionConfig, b"VCN_GATEWAY_OPTION_ENABLE_DATA_STALL_RECOVERY_WITH_MOBILITY", b"I")
    return 0

cdef class VcnGatewayConnectionConfig(JavaObject):
    """android.net.vcn.VcnGatewayConnectionConfig"""

    def __init__(self, *args, **kwargs):
        raise TypeError("VcnGatewayConnectionConfig has no public constructor")

    # Static field VcnGatewayConnectionConfig.VCN_GATEWAY_OPTION_ENABLE_DATA_STALL_RECOVERY_WITH_MOBILITY
    @staticmethod
    def VCN_GATEWAY_OPTION_ENABLE_DATA_STALL_RECOVERY_WITH_MOBILITY() -> int:
        cdef JNIEnv* env = get_env()
        _ensure_ids_VcnGatewayConnectionConfig(env)
        cdef jint _ret = jnicore_GetStaticIntField(env, _cls_VcnGatewayConnectionConfig, _sf_VcnGatewayConnectionConfig_VCN_GATEWAY_OPTION_ENABLE_DATA_STALL_RECOVERY_WITH_MOBILITY)
        check_jni_exc(env)
        return <int>_ret

    cdef jstring _getGatewayConnectionName(self) except? NULL:
        cdef JNIEnv* env = get_env()
        _ensure_ids_VcnGatewayConnectionConfig(env)
        cdef jvalue _args[1]  # zero-arg call; _args ignored by JNI
        cdef jstring _ret = <jstring>jnicore_CallObjectMethodA(env, self._handle, _m_VcnGatewayConnectionConfig_getGatewayConnectionName_0, _args)
        check_jni_exc(env)
        return <jstring>_ret

    def getGatewayConnectionName(self) -> str:
        cdef JNIEnv* env = get_env()
        cdef jstring _ret = NULL
        _ret = self._getGatewayConnectionName()
        return py_str(env, _ret)

    cdef jobject _getRetryIntervalsMillis(self) except? NULL:
        cdef JNIEnv* env = get_env()
        _ensure_ids_VcnGatewayConnectionConfig(env)
        cdef jvalue _args[1]  # zero-arg call; _args ignored by JNI
        cdef jobject _ret = jnicore_CallObjectMethodA(env, self._handle, _m_VcnGatewayConnectionConfig_getRetryIntervalsMillis_0, _args)
        check_jni_exc(env)
        return _ret

    def getRetryIntervalsMillis(self) -> object:
        cdef JNIEnv* env = get_env()
        cdef jobject _ret = NULL
        _ret = self._getRetryIntervalsMillis()
        if _ret == NULL:
            return None
        cdef JavaObject _wrapped = JavaObject.__new__(JavaObject)
        _wrapped._adopt_local(env, _ret)
        return _wrapped

    cdef jobject _getExposedCapabilities(self) except? NULL:
        cdef JNIEnv* env = get_env()
        _ensure_ids_VcnGatewayConnectionConfig(env)
        cdef jvalue _args[1]  # zero-arg call; _args ignored by JNI
        cdef jobject _ret = jnicore_CallObjectMethodA(env, self._handle, _m_VcnGatewayConnectionConfig_getExposedCapabilities_0, _args)
        check_jni_exc(env)
        return _ret

    def getExposedCapabilities(self) -> object:
        cdef JNIEnv* env = get_env()
        cdef jobject _ret = NULL
        _ret = self._getExposedCapabilities()
        if _ret == NULL:
            return None
        cdef JavaObject _wrapped = JavaObject.__new__(JavaObject)
        _wrapped._adopt_local(env, _ret)
        return _wrapped

    cdef jint _getMinUdpPort4500NatTimeoutSeconds(self) except *:
        cdef JNIEnv* env = get_env()
        _ensure_ids_VcnGatewayConnectionConfig(env)
        cdef jvalue _args[1]  # zero-arg call; _args ignored by JNI
        cdef jint _ret = jnicore_CallIntMethodA(env, self._handle, _m_VcnGatewayConnectionConfig_getMinUdpPort4500NatTimeoutSeconds_0, _args)
        check_jni_exc(env)
        return _ret

    def getMinUdpPort4500NatTimeoutSeconds(self) -> int:
        cdef JNIEnv* env = get_env()
        cdef jint _ret = 0
        _ret = self._getMinUdpPort4500NatTimeoutSeconds()
        return <int>_ret

    cdef jboolean _isSafeModeEnabled(self) except *:
        cdef JNIEnv* env = get_env()
        _ensure_ids_VcnGatewayConnectionConfig(env)
        cdef jvalue _args[1]  # zero-arg call; _args ignored by JNI
        cdef jboolean _ret = jnicore_CallBooleanMethodA(env, self._handle, _m_VcnGatewayConnectionConfig_isSafeModeEnabled_0, _args)
        check_jni_exc(env)
        return _ret

    def isSafeModeEnabled(self) -> bool:
        cdef JNIEnv* env = get_env()
        cdef jboolean _ret = 0
        _ret = self._isSafeModeEnabled()
        return jboolean_to_py(_ret)

    cdef jboolean _hasGatewayOption(self, jint p0) except *:
        cdef JNIEnv* env = get_env()
        _ensure_ids_VcnGatewayConnectionConfig(env)
        cdef jvalue _args[1]
        _args[0].i = p0
        cdef jboolean _ret = jnicore_CallBooleanMethodA(env, self._handle, _m_VcnGatewayConnectionConfig_hasGatewayOption_0, _args)
        check_jni_exc(env)
        return _ret

    def hasGatewayOption(self, p0) -> bool:
        cdef JNIEnv* env = get_env()
        cdef jboolean _ret = 0
        cdef jint _c0 = py_to_jint(p0)
        _ret = self._hasGatewayOption(_c0)
        return jboolean_to_py(_ret)

    cdef jint _getMaxMtu(self) except *:
        cdef JNIEnv* env = get_env()
        _ensure_ids_VcnGatewayConnectionConfig(env)
        cdef jvalue _args[1]  # zero-arg call; _args ignored by JNI
        cdef jint _ret = jnicore_CallIntMethodA(env, self._handle, _m_VcnGatewayConnectionConfig_getMaxMtu_0, _args)
        check_jni_exc(env)
        return _ret

    def getMaxMtu(self) -> int:
        cdef JNIEnv* env = get_env()
        cdef jint _ret = 0
        _ret = self._getMaxMtu()
        return <int>_ret

    cdef jobject _getVcnUnderlyingNetworkPriorities(self) except? NULL:
        cdef JNIEnv* env = get_env()
        _ensure_ids_VcnGatewayConnectionConfig(env)
        cdef jvalue _args[1]  # zero-arg call; _args ignored by JNI
        cdef jobject _ret = jnicore_CallObjectMethodA(env, self._handle, _m_VcnGatewayConnectionConfig_getVcnUnderlyingNetworkPriorities_0, _args)
        check_jni_exc(env)
        return _ret

    def getVcnUnderlyingNetworkPriorities(self) -> object:
        cdef JNIEnv* env = get_env()
        cdef jobject _ret = NULL
        _ret = self._getVcnUnderlyingNetworkPriorities()
        if _ret == NULL:
            return None
        cdef JavaObject _wrapped = JavaObject.__new__(JavaObject)
        _wrapped._adopt_local(env, _ret)
        return _wrapped

    cdef jboolean _equals(self, jobject p0) except *:
        cdef JNIEnv* env = get_env()
        _ensure_ids_VcnGatewayConnectionConfig(env)
        cdef jvalue _args[1]
        _args[0].l = p0
        cdef jboolean _ret = jnicore_CallBooleanMethodA(env, self._handle, _m_VcnGatewayConnectionConfig_equals_0, _args)
        check_jni_exc(env)
        return _ret

    def equals(self, p0) -> bool:
        cdef JNIEnv* env = get_env()
        cdef jboolean _ret = 0
        cdef jobject _h0 = (<JavaObject?>p0)._handle if p0 is not None else <jobject>NULL
        _ret = self._equals(_h0)
        return jboolean_to_py(_ret)

    cdef jint _hashCode(self) except *:
        cdef JNIEnv* env = get_env()
        _ensure_ids_VcnGatewayConnectionConfig(env)
        cdef jvalue _args[1]  # zero-arg call; _args ignored by JNI
        cdef jint _ret = jnicore_CallIntMethodA(env, self._handle, _m_VcnGatewayConnectionConfig_hashCode_0, _args)
        check_jni_exc(env)
        return _ret

    def hashCode(self) -> int:
        cdef JNIEnv* env = get_env()
        cdef jint _ret = 0
        _ret = self._hashCode()
        return <int>_ret

# Nested class: android.net.vcn.VcnGatewayConnectionConfig$Builder  (JNI: android/net/vcn/VcnGatewayConnectionConfig$Builder)
cdef jclass _cls_Builder = NULL
cdef jmethodID _ctor_Builder_0 = NULL
cdef jmethodID _m_Builder_addExposedCapability_0 = NULL
cdef jmethodID _m_Builder_removeExposedCapability_0 = NULL
cdef jmethodID _m_Builder_setVcnUnderlyingNetworkPriorities_0 = NULL
cdef jmethodID _m_Builder_setRetryIntervalsMillis_0 = NULL
cdef jmethodID _m_Builder_setMaxMtu_0 = NULL
cdef jmethodID _m_Builder_setMinUdpPort4500NatTimeoutSeconds_0 = NULL
cdef jmethodID _m_Builder_addGatewayOption_0 = NULL
cdef jmethodID _m_Builder_removeGatewayOption_0 = NULL
cdef jmethodID _m_Builder_setSafeModeEnabled_0 = NULL
cdef jmethodID _m_Builder_build_0 = NULL

cdef int _ensure_ids_Builder(JNIEnv* env) except -1:
    global _cls_Builder, _ctor_Builder_0, _m_Builder_addExposedCapability_0, _m_Builder_removeExposedCapability_0, _m_Builder_setVcnUnderlyingNetworkPriorities_0, _m_Builder_setRetryIntervalsMillis_0, _m_Builder_setMaxMtu_0, _m_Builder_setMinUdpPort4500NatTimeoutSeconds_0, _m_Builder_addGatewayOption_0, _m_Builder_removeGatewayOption_0, _m_Builder_setSafeModeEnabled_0, _m_Builder_build_0
    if _cls_Builder != NULL:
        return 0
    _cls_Builder = find_class_global(env, b"android/net/vcn/VcnGatewayConnectionConfig$Builder")
    _ctor_Builder_0 = get_method_id(env, _cls_Builder, b"<init>", b"(Ljava/lang/String;Landroid/net/ipsec/ike/IkeTunnelConnectionParams;)V")
    _m_Builder_addExposedCapability_0 = get_method_id(env, _cls_Builder, b"addExposedCapability", b"(I)Landroid/net/vcn/VcnGatewayConnectionConfig$Builder;")
    _m_Builder_removeExposedCapability_0 = get_method_id(env, _cls_Builder, b"removeExposedCapability", b"(I)Landroid/net/vcn/VcnGatewayConnectionConfig$Builder;")
    _m_Builder_setVcnUnderlyingNetworkPriorities_0 = get_method_id(env, _cls_Builder, b"setVcnUnderlyingNetworkPriorities", b"(Ljava/util/List;)Landroid/net/vcn/VcnGatewayConnectionConfig$Builder;")
    _m_Builder_setRetryIntervalsMillis_0 = get_method_id(env, _cls_Builder, b"setRetryIntervalsMillis", b"([J)Landroid/net/vcn/VcnGatewayConnectionConfig$Builder;")
    _m_Builder_setMaxMtu_0 = get_method_id(env, _cls_Builder, b"setMaxMtu", b"(I)Landroid/net/vcn/VcnGatewayConnectionConfig$Builder;")
    _m_Builder_setMinUdpPort4500NatTimeoutSeconds_0 = get_method_id(env, _cls_Builder, b"setMinUdpPort4500NatTimeoutSeconds", b"(I)Landroid/net/vcn/VcnGatewayConnectionConfig$Builder;")
    _m_Builder_addGatewayOption_0 = get_method_id(env, _cls_Builder, b"addGatewayOption", b"(I)Landroid/net/vcn/VcnGatewayConnectionConfig$Builder;")
    _m_Builder_removeGatewayOption_0 = get_method_id(env, _cls_Builder, b"removeGatewayOption", b"(I)Landroid/net/vcn/VcnGatewayConnectionConfig$Builder;")
    _m_Builder_setSafeModeEnabled_0 = get_method_id(env, _cls_Builder, b"setSafeModeEnabled", b"(Z)Landroid/net/vcn/VcnGatewayConnectionConfig$Builder;")
    _m_Builder_build_0 = get_method_id(env, _cls_Builder, b"build", b"()Landroid/net/vcn/VcnGatewayConnectionConfig;")
    return 0

cdef class Builder(JavaObject):
    """android.net.vcn.VcnGatewayConnectionConfig$Builder"""

    def __init__(self, p0, p1):
        cdef JNIEnv* env = get_env()
        _ensure_ids_Builder(env)
        cdef jvalue _args[2]
        cdef jstring _arg0_s = NULL
        _arg0_s = j_str(env, p0) if p0 is not None else <jstring>NULL
        _args[0].l = <jobject>_arg0_s
        _args[1].l = (<JavaObject?>p1)._handle if p1 is not None else <jobject>NULL
        cdef jobject _ret = jnicore_NewObjectA(env, _cls_Builder, _ctor_Builder_0, _args)
        if _arg0_s != NULL:
            jnicore_DeleteLocalRef(env, <jobject>_arg0_s)
        check_jni_exc(env)
        self._adopt_local(env, _ret)

    cdef jobject _addExposedCapability(self, jint p0) except? NULL:
        cdef JNIEnv* env = get_env()
        _ensure_ids_Builder(env)
        cdef jvalue _args[1]
        _args[0].i = p0
        cdef jobject _ret = jnicore_CallObjectMethodA(env, self._handle, _m_Builder_addExposedCapability_0, _args)
        check_jni_exc(env)
        return _ret

    def addExposedCapability(self, p0) -> object:
        cdef JNIEnv* env = get_env()
        cdef jobject _ret = NULL
        cdef jint _c0 = py_to_jint(p0)
        _ret = self._addExposedCapability(_c0)
        if _ret == NULL:
            return None
        cdef JavaObject _wrapped = JavaObject.__new__(JavaObject)
        _wrapped._adopt_local(env, _ret)
        return _wrapped

    cdef jobject _removeExposedCapability(self, jint p0) except? NULL:
        cdef JNIEnv* env = get_env()
        _ensure_ids_Builder(env)
        cdef jvalue _args[1]
        _args[0].i = p0
        cdef jobject _ret = jnicore_CallObjectMethodA(env, self._handle, _m_Builder_removeExposedCapability_0, _args)
        check_jni_exc(env)
        return _ret

    def removeExposedCapability(self, p0) -> object:
        cdef JNIEnv* env = get_env()
        cdef jobject _ret = NULL
        cdef jint _c0 = py_to_jint(p0)
        _ret = self._removeExposedCapability(_c0)
        if _ret == NULL:
            return None
        cdef JavaObject _wrapped = JavaObject.__new__(JavaObject)
        _wrapped._adopt_local(env, _ret)
        return _wrapped

    cdef jobject _setVcnUnderlyingNetworkPriorities(self, jobject p0) except? NULL:
        cdef JNIEnv* env = get_env()
        _ensure_ids_Builder(env)
        cdef jvalue _args[1]
        _args[0].l = p0
        cdef jobject _ret = jnicore_CallObjectMethodA(env, self._handle, _m_Builder_setVcnUnderlyingNetworkPriorities_0, _args)
        check_jni_exc(env)
        return _ret

    def setVcnUnderlyingNetworkPriorities(self, p0) -> object:
        cdef JNIEnv* env = get_env()
        cdef jobject _ret = NULL
        cdef jobject _h0 = (<JavaObject?>p0)._handle if p0 is not None else <jobject>NULL
        _ret = self._setVcnUnderlyingNetworkPriorities(_h0)
        if _ret == NULL:
            return None
        cdef JavaObject _wrapped = JavaObject.__new__(JavaObject)
        _wrapped._adopt_local(env, _ret)
        return _wrapped

    cdef jobject _setRetryIntervalsMillis(self, jobject p0) except? NULL:
        cdef JNIEnv* env = get_env()
        _ensure_ids_Builder(env)
        cdef jvalue _args[1]
        _args[0].l = p0
        cdef jobject _ret = jnicore_CallObjectMethodA(env, self._handle, _m_Builder_setRetryIntervalsMillis_0, _args)
        check_jni_exc(env)
        return _ret

    def setRetryIntervalsMillis(self, p0) -> object:
        cdef JNIEnv* env = get_env()
        cdef jobject _ret = NULL
        cdef jobject _h0 = (<JavaObject?>p0)._handle if p0 is not None else <jobject>NULL
        _ret = self._setRetryIntervalsMillis(_h0)
        if _ret == NULL:
            return None
        cdef JavaObject _wrapped = JavaObject.__new__(JavaObject)
        _wrapped._adopt_local(env, _ret)
        return _wrapped

    cdef jobject _setMaxMtu(self, jint p0) except? NULL:
        cdef JNIEnv* env = get_env()
        _ensure_ids_Builder(env)
        cdef jvalue _args[1]
        _args[0].i = p0
        cdef jobject _ret = jnicore_CallObjectMethodA(env, self._handle, _m_Builder_setMaxMtu_0, _args)
        check_jni_exc(env)
        return _ret

    def setMaxMtu(self, p0) -> object:
        cdef JNIEnv* env = get_env()
        cdef jobject _ret = NULL
        cdef jint _c0 = py_to_jint(p0)
        _ret = self._setMaxMtu(_c0)
        if _ret == NULL:
            return None
        cdef JavaObject _wrapped = JavaObject.__new__(JavaObject)
        _wrapped._adopt_local(env, _ret)
        return _wrapped

    cdef jobject _setMinUdpPort4500NatTimeoutSeconds(self, jint p0) except? NULL:
        cdef JNIEnv* env = get_env()
        _ensure_ids_Builder(env)
        cdef jvalue _args[1]
        _args[0].i = p0
        cdef jobject _ret = jnicore_CallObjectMethodA(env, self._handle, _m_Builder_setMinUdpPort4500NatTimeoutSeconds_0, _args)
        check_jni_exc(env)
        return _ret

    def setMinUdpPort4500NatTimeoutSeconds(self, p0) -> object:
        cdef JNIEnv* env = get_env()
        cdef jobject _ret = NULL
        cdef jint _c0 = py_to_jint(p0)
        _ret = self._setMinUdpPort4500NatTimeoutSeconds(_c0)
        if _ret == NULL:
            return None
        cdef JavaObject _wrapped = JavaObject.__new__(JavaObject)
        _wrapped._adopt_local(env, _ret)
        return _wrapped

    cdef jobject _addGatewayOption(self, jint p0) except? NULL:
        cdef JNIEnv* env = get_env()
        _ensure_ids_Builder(env)
        cdef jvalue _args[1]
        _args[0].i = p0
        cdef jobject _ret = jnicore_CallObjectMethodA(env, self._handle, _m_Builder_addGatewayOption_0, _args)
        check_jni_exc(env)
        return _ret

    def addGatewayOption(self, p0) -> object:
        cdef JNIEnv* env = get_env()
        cdef jobject _ret = NULL
        cdef jint _c0 = py_to_jint(p0)
        _ret = self._addGatewayOption(_c0)
        if _ret == NULL:
            return None
        cdef JavaObject _wrapped = JavaObject.__new__(JavaObject)
        _wrapped._adopt_local(env, _ret)
        return _wrapped

    cdef jobject _removeGatewayOption(self, jint p0) except? NULL:
        cdef JNIEnv* env = get_env()
        _ensure_ids_Builder(env)
        cdef jvalue _args[1]
        _args[0].i = p0
        cdef jobject _ret = jnicore_CallObjectMethodA(env, self._handle, _m_Builder_removeGatewayOption_0, _args)
        check_jni_exc(env)
        return _ret

    def removeGatewayOption(self, p0) -> object:
        cdef JNIEnv* env = get_env()
        cdef jobject _ret = NULL
        cdef jint _c0 = py_to_jint(p0)
        _ret = self._removeGatewayOption(_c0)
        if _ret == NULL:
            return None
        cdef JavaObject _wrapped = JavaObject.__new__(JavaObject)
        _wrapped._adopt_local(env, _ret)
        return _wrapped

    cdef jobject _setSafeModeEnabled(self, jboolean p0) except? NULL:
        cdef JNIEnv* env = get_env()
        _ensure_ids_Builder(env)
        cdef jvalue _args[1]
        _args[0].z = p0
        cdef jobject _ret = jnicore_CallObjectMethodA(env, self._handle, _m_Builder_setSafeModeEnabled_0, _args)
        check_jni_exc(env)
        return _ret

    def setSafeModeEnabled(self, p0) -> object:
        cdef JNIEnv* env = get_env()
        cdef jobject _ret = NULL
        cdef jboolean _c0 = py_to_jboolean(p0)
        _ret = self._setSafeModeEnabled(_c0)
        if _ret == NULL:
            return None
        cdef JavaObject _wrapped = JavaObject.__new__(JavaObject)
        _wrapped._adopt_local(env, _ret)
        return _wrapped

    cdef jobject _build(self) except? NULL:
        cdef JNIEnv* env = get_env()
        _ensure_ids_Builder(env)
        cdef jvalue _args[1]  # zero-arg call; _args ignored by JNI
        cdef jobject _ret = jnicore_CallObjectMethodA(env, self._handle, _m_Builder_build_0, _args)
        check_jni_exc(env)
        return _ret

    def build(self) -> object:
        cdef JNIEnv* env = get_env()
        cdef jobject _ret = NULL
        _ret = self._build()
        if _ret == NULL:
            return None
        cdef JavaObject _wrapped = JavaObject.__new__(JavaObject)
        _wrapped._adopt_local(env, _ret)
        return _wrapped

