from typing import Any, ClassVar, overload
from android.graphics.Point import Point
from android.graphics.Rect import Rect
from android.graphics.SurfaceTexture import SurfaceTexture
from android.view.SurfaceHolder import SurfaceHolder

class Camera:
    ACTION_NEW_PICTURE: ClassVar[str]
    ACTION_NEW_VIDEO: ClassVar[str]
    CAMERA_ERROR_EVICTED: ClassVar[int]
    CAMERA_ERROR_SERVER_DIED: ClassVar[int]
    CAMERA_ERROR_UNKNOWN: ClassVar[int]
    @staticmethod
    def getCameraInfo(p0: int, p1: Any) -> None: ...
    @staticmethod
    def getNumberOfCameras() -> int: ...
    def reconnect(self) -> None: ...
    def setPreviewDisplay(self, p0: SurfaceHolder) -> None: ...
    def setPreviewTexture(self, p0: SurfaceTexture) -> None: ...
    def startPreview(self) -> None: ...
    def stopPreview(self) -> None: ...
    def setPreviewCallback(self, p0: Any) -> None: ...
    def setOneShotPreviewCallback(self, p0: Any) -> None: ...
    def setPreviewCallbackWithBuffer(self, p0: Any) -> None: ...
    def addCallbackBuffer(self, p0: Any) -> None: ...
    def autoFocus(self, p0: Any) -> None: ...
    def cancelAutoFocus(self) -> None: ...
    def setAutoFocusMoveCallback(self, p0: Any) -> None: ...
    @overload
    def takePicture(self, p0: Any, p1: Any, p2: Any) -> None: ...
    @overload
    def takePicture(self, p0: Any, p1: Any, p2: Any, p3: Any) -> None: ...
    def startSmoothZoom(self, p0: int) -> None: ...
    def stopSmoothZoom(self) -> None: ...
    def setDisplayOrientation(self, p0: int) -> None: ...
    def enableShutterSound(self, p0: bool) -> bool: ...
    def setZoomChangeListener(self, p0: Any) -> None: ...
    def setFaceDetectionListener(self, p0: Any) -> None: ...
    def startFaceDetection(self) -> None: ...
    def stopFaceDetection(self) -> None: ...
    def setErrorCallback(self, p0: Any) -> None: ...
    def setParameters(self, p0: Any) -> None: ...
    def release(self) -> None: ...
    def getParameters(self) -> Any: ...
    def lock(self) -> None: ...
    def unlock(self) -> None: ...
    @overload
    @staticmethod
    def open(p0: int) -> "Camera": ...
    @overload
    @staticmethod
    def open() -> "Camera": ...

    class Size:
        height: int
        width: int
        def __init__(self, p0: "Camera", p1: int, p2: int) -> None: ...
        def equals(self, p0: Any) -> bool: ...
        def hashCode(self) -> int: ...

    class ShutterCallback:
        def onShutter(self) -> None: ...

    class PreviewCallback:
        def onPreviewFrame(self, p0: Any, p1: "Camera") -> None: ...

    class PictureCallback:
        def onPictureTaken(self, p0: Any, p1: "Camera") -> None: ...

    class Parameters:
        ANTIBANDING_50HZ: ClassVar[str]
        ANTIBANDING_60HZ: ClassVar[str]
        ANTIBANDING_AUTO: ClassVar[str]
        ANTIBANDING_OFF: ClassVar[str]
        EFFECT_AQUA: ClassVar[str]
        EFFECT_BLACKBOARD: ClassVar[str]
        EFFECT_MONO: ClassVar[str]
        EFFECT_NEGATIVE: ClassVar[str]
        EFFECT_NONE: ClassVar[str]
        EFFECT_POSTERIZE: ClassVar[str]
        EFFECT_SEPIA: ClassVar[str]
        EFFECT_SOLARIZE: ClassVar[str]
        EFFECT_WHITEBOARD: ClassVar[str]
        FLASH_MODE_AUTO: ClassVar[str]
        FLASH_MODE_OFF: ClassVar[str]
        FLASH_MODE_ON: ClassVar[str]
        FLASH_MODE_RED_EYE: ClassVar[str]
        FLASH_MODE_TORCH: ClassVar[str]
        FOCUS_DISTANCE_FAR_INDEX: ClassVar[int]
        FOCUS_DISTANCE_NEAR_INDEX: ClassVar[int]
        FOCUS_DISTANCE_OPTIMAL_INDEX: ClassVar[int]
        FOCUS_MODE_AUTO: ClassVar[str]
        FOCUS_MODE_CONTINUOUS_PICTURE: ClassVar[str]
        FOCUS_MODE_CONTINUOUS_VIDEO: ClassVar[str]
        FOCUS_MODE_EDOF: ClassVar[str]
        FOCUS_MODE_FIXED: ClassVar[str]
        FOCUS_MODE_INFINITY: ClassVar[str]
        FOCUS_MODE_MACRO: ClassVar[str]
        PREVIEW_FPS_MAX_INDEX: ClassVar[int]
        PREVIEW_FPS_MIN_INDEX: ClassVar[int]
        SCENE_MODE_ACTION: ClassVar[str]
        SCENE_MODE_AUTO: ClassVar[str]
        SCENE_MODE_BARCODE: ClassVar[str]
        SCENE_MODE_BEACH: ClassVar[str]
        SCENE_MODE_CANDLELIGHT: ClassVar[str]
        SCENE_MODE_FIREWORKS: ClassVar[str]
        SCENE_MODE_HDR: ClassVar[str]
        SCENE_MODE_LANDSCAPE: ClassVar[str]
        SCENE_MODE_NIGHT: ClassVar[str]
        SCENE_MODE_NIGHT_PORTRAIT: ClassVar[str]
        SCENE_MODE_PARTY: ClassVar[str]
        SCENE_MODE_PORTRAIT: ClassVar[str]
        SCENE_MODE_SNOW: ClassVar[str]
        SCENE_MODE_SPORTS: ClassVar[str]
        SCENE_MODE_STEADYPHOTO: ClassVar[str]
        SCENE_MODE_SUNSET: ClassVar[str]
        SCENE_MODE_THEATRE: ClassVar[str]
        WHITE_BALANCE_AUTO: ClassVar[str]
        WHITE_BALANCE_CLOUDY_DAYLIGHT: ClassVar[str]
        WHITE_BALANCE_DAYLIGHT: ClassVar[str]
        WHITE_BALANCE_FLUORESCENT: ClassVar[str]
        WHITE_BALANCE_INCANDESCENT: ClassVar[str]
        WHITE_BALANCE_SHADE: ClassVar[str]
        WHITE_BALANCE_TWILIGHT: ClassVar[str]
        WHITE_BALANCE_WARM_FLUORESCENT: ClassVar[str]
        def setRotation(self, p0: int) -> None: ...
        def setZoom(self, p0: int) -> None: ...
        def getZoom(self) -> int: ...
        def flatten(self) -> str: ...
        def unflatten(self, p0: str) -> None: ...
        def setPreviewSize(self, p0: int, p1: int) -> None: ...
        def getPreviewSize(self) -> Any: ...
        def getSupportedPreviewSizes(self) -> list: ...
        def getSupportedVideoSizes(self) -> list: ...
        def getPreferredPreviewSizeForVideo(self) -> Any: ...
        def setJpegThumbnailSize(self, p0: int, p1: int) -> None: ...
        def getJpegThumbnailSize(self) -> Any: ...
        def getSupportedJpegThumbnailSizes(self) -> list: ...
        def setJpegThumbnailQuality(self, p0: int) -> None: ...
        def getJpegThumbnailQuality(self) -> int: ...
        def setJpegQuality(self, p0: int) -> None: ...
        def getJpegQuality(self) -> int: ...
        def setPreviewFrameRate(self, p0: int) -> None: ...
        def getPreviewFrameRate(self) -> int: ...
        def getSupportedPreviewFrameRates(self) -> list: ...
        def setPreviewFpsRange(self, p0: int, p1: int) -> None: ...
        def getPreviewFpsRange(self, p0: Any) -> None: ...
        def getSupportedPreviewFpsRange(self) -> list: ...
        def setPreviewFormat(self, p0: int) -> None: ...
        def getPreviewFormat(self) -> int: ...
        def getSupportedPreviewFormats(self) -> list: ...
        def setPictureSize(self, p0: int, p1: int) -> None: ...
        def getPictureSize(self) -> Any: ...
        def getSupportedPictureSizes(self) -> list: ...
        def setPictureFormat(self, p0: int) -> None: ...
        def getPictureFormat(self) -> int: ...
        def getSupportedPictureFormats(self) -> list: ...
        def setGpsLatitude(self, p0: float) -> None: ...
        def setGpsLongitude(self, p0: float) -> None: ...
        def setGpsAltitude(self, p0: float) -> None: ...
        def setGpsTimestamp(self, p0: int) -> None: ...
        def setGpsProcessingMethod(self, p0: str) -> None: ...
        def removeGpsData(self) -> None: ...
        def getWhiteBalance(self) -> str: ...
        def setWhiteBalance(self, p0: str) -> None: ...
        def getSupportedWhiteBalance(self) -> list: ...
        def getColorEffect(self) -> str: ...
        def setColorEffect(self, p0: str) -> None: ...
        def getSupportedColorEffects(self) -> list: ...
        def getAntibanding(self) -> str: ...
        def setAntibanding(self, p0: str) -> None: ...
        def getSupportedAntibanding(self) -> list: ...
        def getSceneMode(self) -> str: ...
        def setSceneMode(self, p0: str) -> None: ...
        def getSupportedSceneModes(self) -> list: ...
        def getFlashMode(self) -> str: ...
        def setFlashMode(self, p0: str) -> None: ...
        def getSupportedFlashModes(self) -> list: ...
        def getFocusMode(self) -> str: ...
        def setFocusMode(self, p0: str) -> None: ...
        def getSupportedFocusModes(self) -> list: ...
        def getFocalLength(self) -> float: ...
        def getHorizontalViewAngle(self) -> float: ...
        def getVerticalViewAngle(self) -> float: ...
        def getExposureCompensation(self) -> int: ...
        def setExposureCompensation(self, p0: int) -> None: ...
        def getMaxExposureCompensation(self) -> int: ...
        def getMinExposureCompensation(self) -> int: ...
        def getExposureCompensationStep(self) -> float: ...
        def setAutoExposureLock(self, p0: bool) -> None: ...
        def getAutoExposureLock(self) -> bool: ...
        def isAutoExposureLockSupported(self) -> bool: ...
        def setAutoWhiteBalanceLock(self, p0: bool) -> None: ...
        def getAutoWhiteBalanceLock(self) -> bool: ...
        def isAutoWhiteBalanceLockSupported(self) -> bool: ...
        def isZoomSupported(self) -> bool: ...
        def getMaxZoom(self) -> int: ...
        def getZoomRatios(self) -> list: ...
        def isSmoothZoomSupported(self) -> bool: ...
        def getFocusDistances(self, p0: Any) -> None: ...
        def getMaxNumFocusAreas(self) -> int: ...
        def getFocusAreas(self) -> list: ...
        def setFocusAreas(self, p0: list) -> None: ...
        def getMaxNumMeteringAreas(self) -> int: ...
        def getMeteringAreas(self) -> list: ...
        def setMeteringAreas(self, p0: list) -> None: ...
        def getMaxNumDetectedFaces(self) -> int: ...
        def setRecordingHint(self, p0: bool) -> None: ...
        def isVideoSnapshotSupported(self) -> bool: ...
        def setVideoStabilization(self, p0: bool) -> None: ...
        def getVideoStabilization(self) -> bool: ...
        def isVideoStabilizationSupported(self) -> bool: ...
        def remove(self, p0: str) -> None: ...
        def get(self, p0: str) -> str: ...
        def getInt(self, p0: str) -> int: ...
        @overload
        def set(self, p0: str, p1: int) -> None: ...
        @overload
        def set(self, p0: str, p1: str) -> None: ...

    class OnZoomChangeListener:
        def onZoomChange(self, p0: int, p1: bool, p2: "Camera") -> None: ...

    class FaceDetectionListener:
        def onFaceDetection(self, p0: Any, p1: "Camera") -> None: ...

    class Face:
        id: int
        leftEye: Point
        mouth: Point
        rect: Rect
        rightEye: Point
        score: int
        def __init__(self) -> None: ...

    class ErrorCallback:
        def onError(self, p0: int, p1: "Camera") -> None: ...

    class CameraInfo:
        CAMERA_FACING_BACK: ClassVar[int]
        CAMERA_FACING_FRONT: ClassVar[int]
        canDisableShutterSound: bool
        facing: int
        orientation: int
        def __init__(self) -> None: ...

    class AutoFocusMoveCallback:
        def onAutoFocusMoving(self, p0: bool, p1: "Camera") -> None: ...

    class AutoFocusCallback:
        def onAutoFocus(self, p0: bool, p1: "Camera") -> None: ...

    class Area:
        rect: Rect
        weight: int
        def __init__(self, p0: Rect, p1: int) -> None: ...
        def equals(self, p0: Any) -> bool: ...
