from typing import Any, ClassVar, overload
from android.os.Parcel import Parcel

class OverlayProperties:
    CREATOR: ClassVar[Any]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    def isMixedColorSpacesSupported(self) -> bool: ...
    def isCombinationSupported(self, p0: int, p1: int) -> bool: ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
