from typing import Any, ClassVar, overload

class StringCharacterIterator:
    DONE: ClassVar[str]
    @overload
    def __init__(self, p0: str, p1: int, p2: int, p3: int) -> None: ...
    @overload
    def __init__(self, p0: str, p1: int) -> None: ...
    @overload
    def __init__(self, p0: str) -> None: ...
    def getEndIndex(self) -> int: ...
    def equals(self, p0: Any) -> bool: ...
    def hashCode(self) -> int: ...
    def clone(self) -> Any: ...
    def next(self) -> str: ...
    def last(self) -> str: ...
    def first(self) -> str: ...
    def current(self) -> str: ...
    def setText(self, p0: str) -> None: ...
    def setIndex(self, p0: int) -> str: ...
    def getBeginIndex(self) -> int: ...
    def getIndex(self) -> int: ...
    def previous(self) -> str: ...
