from typing import Any, ClassVar, overload
from android.content.Context import Context

class Formatter:
    def __init__(self) -> None: ...
    @staticmethod
    def formatIpAddress(p0: int) -> str: ...
    @staticmethod
    def formatFileSize(p0: Context, p1: int) -> str: ...
    @staticmethod
    def formatShortFileSize(p0: Context, p1: int) -> str: ...
