from typing import Any, ClassVar, overload

class LoadParams:
    def getPassword(self) -> str: ...

    class Builder:
        def __init__(self) -> None: ...
        def build(self) -> "LoadParams": ...
        def setPassword(self, p0: str) -> Any: ...
