from typing import Any, ClassVar, overload

class ChildSessionParams:
    def getChildSaProposals(self) -> list: ...
    def getHardLifetimeSeconds(self) -> int: ...
    def getInboundTrafficSelectors(self) -> list: ...
    def getOutboundTrafficSelectors(self) -> list: ...
    def getSoftLifetimeSeconds(self) -> int: ...
    def equals(self, p0: Any) -> bool: ...
    def hashCode(self) -> int: ...
