from typing import Any, ClassVar, overload
from android.health.connect.datatypes.Metadata import Metadata
from android.health.connect.datatypes.units.Temperature import Temperature
from java.time.Instant import Instant
from java.time.ZoneOffset import ZoneOffset

class BasalBodyTemperatureRecord:
    def equals(self, p0: Any) -> bool: ...
    def hashCode(self) -> int: ...
    def getTemperature(self) -> Temperature: ...
    def getMeasurementLocation(self) -> int: ...

    class Builder:
        def __init__(self, p0: Metadata, p1: Instant, p2: int, p3: Temperature) -> None: ...
        def build(self) -> "BasalBodyTemperatureRecord": ...
        def setZoneOffset(self, p0: ZoneOffset) -> Any: ...
        def clearZoneOffset(self) -> Any: ...
