from typing import Any, ClassVar, overload
from android.health.connect.datatypes.units.Energy import Energy
from android.health.connect.datatypes.units.Length import Length
from java.time.Duration import Duration

class ExerciseCompletionGoal:

    class UnspecifiedGoal:
        INSTANCE: ClassVar[Any]

    class UnknownGoal:
        INSTANCE: ClassVar[Any]

    class TotalCaloriesBurnedGoal:
        def __init__(self, p0: Energy) -> None: ...
        def equals(self, p0: Any) -> bool: ...
        def hashCode(self) -> int: ...
        def getTotalCalories(self) -> Energy: ...

    class StepsGoal:
        def __init__(self, p0: int) -> None: ...
        def equals(self, p0: Any) -> bool: ...
        def hashCode(self) -> int: ...
        def getSteps(self) -> int: ...

    class RepetitionsGoal:
        def __init__(self, p0: int) -> None: ...
        def equals(self, p0: Any) -> bool: ...
        def hashCode(self) -> int: ...
        def getRepetitions(self) -> int: ...

    class DurationGoal:
        def __init__(self, p0: Duration) -> None: ...
        def equals(self, p0: Any) -> bool: ...
        def hashCode(self) -> int: ...
        def getDuration(self) -> Duration: ...

    class DistanceWithVariableRestGoal:
        def __init__(self, p0: Length, p1: Duration) -> None: ...
        def equals(self, p0: Any) -> bool: ...
        def hashCode(self) -> int: ...
        def getDistance(self) -> Length: ...
        def getDuration(self) -> Duration: ...

    class DistanceGoal:
        def __init__(self, p0: Length) -> None: ...
        def equals(self, p0: Any) -> bool: ...
        def hashCode(self) -> int: ...
        def getDistance(self) -> Length: ...

    class ActiveCaloriesBurnedGoal:
        def __init__(self, p0: Energy) -> None: ...
        def equals(self, p0: Any) -> bool: ...
        def hashCode(self) -> int: ...
        def getActiveCalories(self) -> Energy: ...
