from typing import Any, ClassVar, overload
from java.time.Instant import Instant
from java.time.ZoneOffset import ZoneOffset

class IntervalRecord:
    def equals(self, p0: Any) -> bool: ...
    def hashCode(self) -> int: ...
    def getEndTime(self) -> Instant: ...
    def getEndZoneOffset(self) -> ZoneOffset: ...
    def getStartZoneOffset(self) -> ZoneOffset: ...
    def getStartTime(self) -> Instant: ...
