from typing import Any, ClassVar, overload
from android.health.connect.datatypes.ExerciseCompletionGoal import ExerciseCompletionGoal
from android.health.connect.datatypes.ExercisePerformanceGoal import ExercisePerformanceGoal

class PlannedExerciseStep:
    EXERCISE_CATEGORY_ACTIVE: ClassVar[int]
    EXERCISE_CATEGORY_COOLDOWN: ClassVar[int]
    EXERCISE_CATEGORY_RECOVERY: ClassVar[int]
    EXERCISE_CATEGORY_REST: ClassVar[int]
    EXERCISE_CATEGORY_UNKNOWN: ClassVar[int]
    EXERCISE_CATEGORY_WARMUP: ClassVar[int]
    def equals(self, p0: Any) -> bool: ...
    def hashCode(self) -> int: ...
    def getDescription(self) -> str: ...
    def getExerciseType(self) -> int: ...
    def getCompletionGoal(self) -> ExerciseCompletionGoal: ...
    def getExerciseCategory(self) -> int: ...
    def getPerformanceGoals(self) -> list: ...

    class Builder:
        def __init__(self, p0: int, p1: int, p2: ExerciseCompletionGoal) -> None: ...
        def build(self) -> "PlannedExerciseStep": ...
        def setCompletionGoal(self, p0: ExerciseCompletionGoal) -> Any: ...
        def addPerformanceGoal(self, p0: ExercisePerformanceGoal) -> Any: ...
        def clearPerformanceGoals(self) -> Any: ...
        def setDescription(self, p0: str) -> Any: ...
        def setExerciseCategory(self, p0: int) -> Any: ...
        def setPerformanceGoals(self, p0: list) -> Any: ...
        def setExerciseType(self, p0: int) -> Any: ...
