from typing import Any, ClassVar, overload
from java.util.Properties import Properties
from javax.xml.transform.ErrorListener import ErrorListener
from javax.xml.transform.Result import Result
from javax.xml.transform.Source import Source
from javax.xml.transform.URIResolver import URIResolver

class Transformer:
    def clearParameters(self) -> None: ...
    def reset(self) -> None: ...
    def transform(self, p0: Source, p1: Result) -> None: ...
    def setURIResolver(self, p0: URIResolver) -> None: ...
    def getURIResolver(self) -> URIResolver: ...
    def setOutputProperties(self, p0: Properties) -> None: ...
    def getOutputProperties(self) -> Properties: ...
    def setOutputProperty(self, p0: str, p1: str) -> None: ...
    def getOutputProperty(self, p0: str) -> str: ...
    def setErrorListener(self, p0: ErrorListener) -> None: ...
    def getErrorListener(self) -> ErrorListener: ...
    def setParameter(self, p0: str, p1: Any) -> None: ...
    def getParameter(self, p0: str) -> Any: ...
