from typing import Any, ClassVar, overload
from android.adservices.common.AdTechIdentifier import AdTechIdentifier
from android.net.Uri import Uri

class AdSelectionOutcome:
    NO_OUTCOME: ClassVar["AdSelectionOutcome"]
    def getComponentAdUris(self) -> list: ...
    def getRenderUri(self) -> Uri: ...
    def getWinningSeller(self) -> AdTechIdentifier: ...
    def hasOutcome(self) -> bool: ...
    def equals(self, p0: Any) -> bool: ...
    def hashCode(self) -> int: ...
    def getAdSelectionId(self) -> int: ...

    class Builder:
        def __init__(self) -> None: ...
        def setRenderUri(self, p0: Uri) -> Any: ...
        def setAdSelectionId(self, p0: int) -> Any: ...
        def setComponentAdUris(self, p0: list) -> Any: ...
        def build(self) -> "AdSelectionOutcome": ...
