from typing import Any, ClassVar, overload
from android.adservices.common.AdTechIdentifier import AdTechIdentifier
from android.net.Uri import Uri
from android.os.Parcel import Parcel

class SignedContextualAds:
    CREATOR: ClassVar[Any]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    def getDecisionLogicUri(self) -> Uri: ...
    def getBuyer(self) -> AdTechIdentifier: ...
    def equals(self, p0: Any) -> bool: ...
    def toString(self) -> str: ...
    def hashCode(self) -> int: ...
    def getSignature(self) -> Any: ...
    def getAdsWithBid(self) -> list: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
    def describeContents(self) -> int: ...

    class Builder:
        @overload
        def __init__(self, p0: "SignedContextualAds") -> None: ...
        @overload
        def __init__(self) -> None: ...
        def setBuyer(self, p0: AdTechIdentifier) -> Any: ...
        def setDecisionLogicUri(self, p0: Uri) -> Any: ...
        def setSignature(self, p0: Any) -> Any: ...
        def setAdsWithBid(self, p0: list) -> Any: ...
        def build(self) -> "SignedContextualAds": ...
