from typing import Any, ClassVar, overload
from android.os.Parcel import Parcel

class PdfPageGotoLinkContent:
    CREATOR: ClassVar[Any]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    def __init__(self, p0: list, p1: Any) -> None: ...
    def getDestination(self) -> Any: ...
    def getBounds(self) -> list: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
    def describeContents(self) -> int: ...

    class Destination:
        CREATOR: ClassVar[Any]
        CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
        PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
        def __init__(self, p0: int, p1: float, p2: float, p3: float) -> None: ...
        def getPageNumber(self) -> int: ...
        def getYCoordinate(self) -> float: ...
        def getXCoordinate(self) -> float: ...
        def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
        def describeContents(self) -> int: ...
        def getZoom(self) -> float: ...
