from typing import Any, ClassVar, overload
from android.os.Handler import Handler
from android.view.accessibility.AccessibilityEvent import AccessibilityEvent
from android.view.accessibility.AccessibilityRequestPreparer import AccessibilityRequestPreparer
from java.util.concurrent.Executor import Executor

class AccessibilityManager:
    FLAG_CONTENT_CONTROLS: ClassVar[int]
    FLAG_CONTENT_ICONS: ClassVar[int]
    FLAG_CONTENT_TEXT: ClassVar[int]
    def isTouchExplorationEnabled(self) -> bool: ...
    def getAccessibilityServiceList(self) -> list: ...
    def getInstalledAccessibilityServiceList(self) -> list: ...
    def getEnabledAccessibilityServiceList(self, p0: int) -> list: ...
    @overload
    def addAccessibilityStateChangeListener(self, p0: Any) -> bool: ...
    @overload
    def addAccessibilityStateChangeListener(self, p0: Any, p1: Handler) -> None: ...
    def removeAccessibilityStateChangeListener(self, p0: Any) -> bool: ...
    @overload
    def addTouchExplorationStateChangeListener(self, p0: Any) -> bool: ...
    @overload
    def addTouchExplorationStateChangeListener(self, p0: Any, p1: Handler) -> None: ...
    def removeTouchExplorationStateChangeListener(self, p0: Any) -> bool: ...
    @overload
    def addAccessibilityServicesStateChangeListener(self, p0: Executor, p1: Any) -> None: ...
    @overload
    def addAccessibilityServicesStateChangeListener(self, p0: Any) -> None: ...
    def removeAccessibilityServicesStateChangeListener(self, p0: Any) -> bool: ...
    def isRequestFromAccessibilityTool(self) -> bool: ...
    def addAccessibilityRequestPreparer(self, p0: AccessibilityRequestPreparer) -> None: ...
    def removeAccessibilityRequestPreparer(self, p0: AccessibilityRequestPreparer) -> None: ...
    def getRecommendedTimeoutMillis(self, p0: int, p1: int) -> int: ...
    def getAccessibilityFocusStrokeWidth(self) -> int: ...
    def getAccessibilityFocusColor(self) -> int: ...
    def addAudioDescriptionRequestedChangeListener(self, p0: Executor, p1: Any) -> None: ...
    def removeAudioDescriptionRequestedChangeListener(self, p0: Any) -> bool: ...
    def isAudioDescriptionRequested(self) -> bool: ...
    @staticmethod
    def isAccessibilityButtonSupported() -> bool: ...
    def interrupt(self) -> None: ...
    def isEnabled(self) -> bool: ...
    def sendAccessibilityEvent(self, p0: AccessibilityEvent) -> None: ...

    class TouchExplorationStateChangeListener:
        def onTouchExplorationStateChanged(self, p0: bool) -> None: ...

    class AudioDescriptionRequestedChangeListener:
        def onAudioDescriptionRequestedChanged(self, p0: bool) -> None: ...

    class AccessibilityStateChangeListener:
        def onAccessibilityStateChanged(self, p0: bool) -> None: ...

    class AccessibilityServicesStateChangeListener:
        def onAccessibilityServicesStateChanged(self, p0: "AccessibilityManager") -> None: ...
