from typing import Any, ClassVar, overload
from android.os.Parcel import Parcel
from android.os.ParcelUuid import ParcelUuid

class ObservingDevicePresenceRequest:
    CREATOR: ClassVar[Any]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    def getAssociationId(self) -> int: ...
    def equals(self, p0: Any) -> bool: ...
    def toString(self) -> str: ...
    def hashCode(self) -> int: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
    def describeContents(self) -> int: ...
    def getUuid(self) -> ParcelUuid: ...

    class Builder:
        def __init__(self) -> None: ...
        def setAssociationId(self, p0: int) -> Any: ...
        def build(self) -> "ObservingDevicePresenceRequest": ...
        def setUuid(self, p0: ParcelUuid) -> Any: ...
