from typing import Any, ClassVar, overload
from javax.xml.validation.TypeInfoProvider import TypeInfoProvider
from org.w3c.dom.ls.LSResourceResolver import LSResourceResolver
from org.xml.sax.ContentHandler import ContentHandler
from org.xml.sax.ErrorHandler import ErrorHandler

class ValidatorHandler:
    def setErrorHandler(self, p0: ErrorHandler) -> None: ...
    def getErrorHandler(self) -> ErrorHandler: ...
    def getProperty(self, p0: str) -> Any: ...
    def setProperty(self, p0: str, p1: Any) -> None: ...
    def setResourceResolver(self, p0: LSResourceResolver) -> None: ...
    def getResourceResolver(self) -> LSResourceResolver: ...
    def getTypeInfoProvider(self) -> TypeInfoProvider: ...
    def getFeature(self, p0: str) -> bool: ...
    def setFeature(self, p0: str, p1: bool) -> None: ...
    def setContentHandler(self, p0: ContentHandler) -> None: ...
    def getContentHandler(self) -> ContentHandler: ...
