from typing import Any, ClassVar, overload
from java.math.BigInteger import BigInteger

class ECFieldFp:
    def __init__(self, p0: BigInteger) -> None: ...
    def getP(self) -> BigInteger: ...
    def getFieldSize(self) -> int: ...
    def equals(self, p0: Any) -> bool: ...
    def hashCode(self) -> int: ...
