from typing import Any, ClassVar, overload
from org.w3c.dom.TypeInfo import TypeInfo

class TypeInfoProvider:
    def getElementTypeInfo(self) -> TypeInfo: ...
    def getAttributeTypeInfo(self, p0: int) -> TypeInfo: ...
    def isIdAttribute(self, p0: int) -> bool: ...
    def isSpecified(self, p0: int) -> bool: ...
