from typing import Any, ClassVar, overload
from javax.xml.transform.Result import Result
from javax.xml.transform.Source import Source
from org.w3c.dom.ls.LSResourceResolver import LSResourceResolver
from org.xml.sax.ErrorHandler import ErrorHandler

class Validator:
    def getErrorHandler(self) -> ErrorHandler: ...
    def setErrorHandler(self, p0: ErrorHandler) -> None: ...
    def reset(self) -> None: ...
    def getProperty(self, p0: str) -> Any: ...
    @overload
    def validate(self, p0: Source, p1: Result) -> None: ...
    @overload
    def validate(self, p0: Source) -> None: ...
    def setProperty(self, p0: str, p1: Any) -> None: ...
    def getFeature(self, p0: str) -> bool: ...
    def setFeature(self, p0: str, p1: bool) -> None: ...
    def setResourceResolver(self, p0: LSResourceResolver) -> None: ...
    def getResourceResolver(self) -> LSResourceResolver: ...
