from typing import Any, ClassVar, overload
from android.database.CursorWindow import CursorWindow
from android.database.sqlite.SQLiteCursorDriver import SQLiteCursorDriver
from android.database.sqlite.SQLiteDatabase import SQLiteDatabase
from android.database.sqlite.SQLiteQuery import SQLiteQuery

class SQLiteCursor:
    FIELD_TYPE_BLOB: ClassVar[int]
    FIELD_TYPE_FLOAT: ClassVar[int]
    FIELD_TYPE_INTEGER: ClassVar[int]
    FIELD_TYPE_NULL: ClassVar[int]
    FIELD_TYPE_STRING: ClassVar[int]
    @overload
    def __init__(self, p0: SQLiteDatabase, p1: SQLiteCursorDriver, p2: str, p3: SQLiteQuery) -> None: ...
    @overload
    def __init__(self, p0: SQLiteCursorDriver, p1: str, p2: SQLiteQuery) -> None: ...
    def onMove(self, p0: int, p1: int) -> bool: ...
    def getDatabase(self) -> SQLiteDatabase: ...
    def setSelectionArguments(self, p0: Any) -> None: ...
    def setFillWindowForwardOnly(self, p0: bool) -> None: ...
    def setWindow(self, p0: CursorWindow) -> None: ...
    def getCount(self) -> int: ...
    def close(self) -> None: ...
    def getColumnIndex(self, p0: str) -> int: ...
    def getColumnNames(self) -> Any: ...
    def deactivate(self) -> None: ...
    def requery(self) -> bool: ...
