from typing import Any, ClassVar, overload
from android.bluetooth.le.ScanFilter import ScanFilter
from android.os.Parcel import Parcel
from java.nio.ByteOrder import ByteOrder
from java.util.regex.Pattern import Pattern

class BluetoothLeDeviceFilter:
    CREATOR: ClassVar[Any]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    @staticmethod
    def getRenamePrefixLengthLimit() -> int: ...
    def equals(self, p0: Any) -> bool: ...
    def toString(self) -> str: ...
    def hashCode(self) -> int: ...
    def describeContents(self) -> int: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...

    class Builder:
        def __init__(self) -> None: ...
        def setScanFilter(self, p0: ScanFilter) -> Any: ...
        def setRawDataFilter(self, p0: Any, p1: Any) -> Any: ...
        def setRenameFromBytes(self, p0: str, p1: str, p2: int, p3: int, p4: ByteOrder) -> Any: ...
        def setRenameFromName(self, p0: str, p1: str, p2: int, p3: int) -> Any: ...
        def setNamePattern(self, p0: Pattern) -> Any: ...
        def build(self) -> "BluetoothLeDeviceFilter": ...
