from typing import Any, ClassVar, overload
from java.util.Iterator import Iterator
from java.util.Spliterator import Spliterator
from java.util.function.Consumer import Consumer
from java.util.function.Predicate import Predicate

class ArrayDeque:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, p0: int) -> None: ...
    @overload
    def __init__(self, p0: list) -> None: ...
    def peek(self) -> Any: ...
    def pollFirst(self) -> Any: ...
    def pollLast(self) -> Any: ...
    def offerLast(self, p0: Any) -> bool: ...
    def peekFirst(self) -> Any: ...
    def removeFirstOccurrence(self, p0: Any) -> bool: ...
    def offerFirst(self, p0: Any) -> bool: ...
    def peekLast(self) -> Any: ...
    def removeLastOccurrence(self, p0: Any) -> bool: ...
    def offer(self, p0: Any) -> bool: ...
    def descendingIterator(self) -> Iterator: ...
    def poll(self) -> Any: ...
    def removeAll(self, p0: list) -> bool: ...
    def retainAll(self, p0: list) -> bool: ...
    def removeIf(self, p0: Predicate) -> bool: ...
    def getFirst(self) -> Any: ...
    def getLast(self) -> Any: ...
    def element(self) -> Any: ...
    def addFirst(self, p0: Any) -> None: ...
    def addLast(self, p0: Any) -> None: ...
    def removeFirst(self) -> Any: ...
    def removeLast(self) -> Any: ...
    def push(self, p0: Any) -> None: ...
    def pop(self) -> Any: ...
    @overload
    def remove(self) -> Any: ...
    @overload
    def remove(self, p0: Any) -> bool: ...
    def size(self) -> int: ...
    @overload
    def clone(self) -> "ArrayDeque": ...
    @overload
    def clone(self) -> Any: ...
    def clear(self) -> None: ...
    def isEmpty(self) -> bool: ...
    def add(self, p0: Any) -> bool: ...
    @overload
    def toArray(self) -> Any: ...
    @overload
    def toArray(self, p0: Any) -> Any: ...
    def iterator(self) -> Iterator: ...
    def contains(self, p0: Any) -> bool: ...
    def spliterator(self) -> Spliterator: ...
    def addAll(self, p0: list) -> bool: ...
    def forEach(self, p0: Consumer) -> None: ...
