from typing import Any, ClassVar, overload
from java.io.InputStream import InputStream
from java.io.OutputStream import OutputStream
from java.nio.ByteBuffer import ByteBuffer

class Base64:
    @staticmethod
    def getEncoder() -> Any: ...
    @staticmethod
    def getUrlEncoder() -> Any: ...
    @overload
    @staticmethod
    def getMimeEncoder(p0: int, p1: Any) -> Any: ...
    @overload
    @staticmethod
    def getMimeEncoder() -> Any: ...
    @staticmethod
    def getDecoder() -> Any: ...
    @staticmethod
    def getUrlDecoder() -> Any: ...
    @staticmethod
    def getMimeDecoder() -> Any: ...

    class Encoder:
        def encodeToString(self, p0: Any) -> str: ...
        def wrap(self, p0: OutputStream) -> OutputStream: ...
        @overload
        def encode(self, p0: ByteBuffer) -> ByteBuffer: ...
        @overload
        def encode(self, p0: Any, p1: Any) -> int: ...
        @overload
        def encode(self, p0: Any) -> Any: ...
        def withoutPadding(self) -> Any: ...

    class Decoder:
        @overload
        def decode(self, p0: str) -> Any: ...
        @overload
        def decode(self, p0: Any) -> Any: ...
        @overload
        def decode(self, p0: ByteBuffer) -> ByteBuffer: ...
        @overload
        def decode(self, p0: Any, p1: Any) -> int: ...
        def wrap(self, p0: InputStream) -> InputStream: ...
