from typing import Any, ClassVar, overload
from java.lang.Appendable import Appendable

class HexFormat:
    @overload
    def formatHex(self, p0: Appendable, p1: Any) -> Appendable: ...
    @overload
    def formatHex(self, p0: Appendable, p1: Any, p2: int, p3: int) -> Appendable: ...
    @overload
    def formatHex(self, p0: Any) -> str: ...
    @overload
    def formatHex(self, p0: Any, p1: int, p2: int) -> str: ...
    def toHighHexDigit(self, p0: int) -> str: ...
    def toLowHexDigit(self, p0: int) -> str: ...
    @overload
    def parseHex(self, p0: Any, p1: int, p2: int) -> Any: ...
    @overload
    def parseHex(self, p0: str, p1: int, p2: int) -> Any: ...
    @overload
    def parseHex(self, p0: str) -> Any: ...
    @overload
    @staticmethod
    def fromHexDigits(p0: str, p1: int, p2: int) -> int: ...
    @overload
    @staticmethod
    def fromHexDigits(p0: str) -> int: ...
    @staticmethod
    def fromHexDigit(p0: int) -> int: ...
    @overload
    @staticmethod
    def fromHexDigitsToLong(p0: str, p1: int, p2: int) -> int: ...
    @overload
    @staticmethod
    def fromHexDigitsToLong(p0: str) -> int: ...
    @staticmethod
    def ofDelimiter(p0: str) -> "HexFormat": ...
    def withDelimiter(self, p0: str) -> "HexFormat": ...
    def withPrefix(self, p0: str) -> "HexFormat": ...
    def withSuffix(self, p0: str) -> "HexFormat": ...
    def withLowerCase(self) -> "HexFormat": ...
    @staticmethod
    def isHexDigit(p0: int) -> bool: ...
    def equals(self, p0: Any) -> bool: ...
    def toString(self) -> str: ...
    def hashCode(self) -> int: ...
    def isUpperCase(self) -> bool: ...
    @staticmethod
    def of() -> "HexFormat": ...
    def prefix(self) -> str: ...
    def suffix(self) -> str: ...
    def delimiter(self) -> str: ...
    def withUpperCase(self) -> "HexFormat": ...
    @overload
    def toHexDigits(self, p0: int) -> str: ...
    @overload
    def toHexDigits(self, p0: int) -> str: ...
    @overload
    def toHexDigits(self, p0: str) -> str: ...
    @overload
    def toHexDigits(self, p0: int) -> str: ...
    @overload
    def toHexDigits(self, p0: int, p1: int) -> str: ...
    @overload
    def toHexDigits(self, p0: int) -> str: ...
    @overload
    def toHexDigits(self, p0: Appendable, p1: int) -> Appendable: ...
