from typing import Any, ClassVar, overload
from java.util.SequencedCollection import SequencedCollection
from java.util.SequencedSet import SequencedSet
from java.util.Spliterator import Spliterator

class LinkedHashSet:
    @overload
    def __init__(self, p0: int, p1: float) -> None: ...
    @overload
    def __init__(self, p0: int) -> None: ...
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, p0: list) -> None: ...
    @staticmethod
    def newLinkedHashSet(p0: int) -> set: ...
    @overload
    def reversed(self) -> SequencedCollection: ...
    @overload
    def reversed(self) -> SequencedSet: ...
    def getFirst(self) -> Any: ...
    def getLast(self) -> Any: ...
    def addFirst(self, p0: Any) -> None: ...
    def addLast(self, p0: Any) -> None: ...
    def removeFirst(self) -> Any: ...
    def removeLast(self) -> Any: ...
    def spliterator(self) -> Spliterator: ...
