from typing import Any, ClassVar, overload

class MissingResourceException:
    def __init__(self, p0: str, p1: str, p2: str) -> None: ...
    def getClassName(self) -> str: ...
    def getKey(self) -> str: ...
