from typing import Any, ClassVar, overload
from java.lang.Runnable import Runnable
from java.util.function.DoubleConsumer import DoubleConsumer
from java.util.function.DoubleSupplier import DoubleSupplier
from java.util.function.Supplier import Supplier
from java.util.stream.DoubleStream import DoubleStream

class OptionalDouble:
    def equals(self, p0: Any) -> bool: ...
    def toString(self) -> str: ...
    def hashCode(self) -> int: ...
    @staticmethod
    def of(p0: float) -> "OptionalDouble": ...
    def isEmpty(self) -> bool: ...
    def stream(self) -> DoubleStream: ...
    @staticmethod
    def empty() -> "OptionalDouble": ...
    def orElse(self, p0: float) -> float: ...
    def isPresent(self) -> bool: ...
    @overload
    def orElseThrow(self, p0: Supplier) -> float: ...
    @overload
    def orElseThrow(self) -> float: ...
    def getAsDouble(self) -> float: ...
    def ifPresentOrElse(self, p0: DoubleConsumer, p1: Runnable) -> None: ...
    def orElseGet(self, p0: DoubleSupplier) -> float: ...
    def ifPresent(self, p0: DoubleConsumer) -> None: ...
