from typing import Any, ClassVar, overload
from java.lang.Runnable import Runnable
from java.util.function.Consumer import Consumer
from java.util.function.Function import Function
from java.util.function.Predicate import Predicate
from java.util.function.Supplier import Supplier
from java.util.stream.Stream import Stream

class Optional:
    def equals(self, p0: Any) -> bool: ...
    def toString(self) -> str: ...
    def hashCode(self) -> int: ...
    @staticmethod
    def of(p0: Any) -> "Optional": ...
    def isEmpty(self) -> bool: ...
    def get(self) -> Any: ...
    def map(self, p0: Function) -> "Optional": ...
    def stream(self) -> Stream: ...
    def filter(self, p0: Predicate) -> "Optional": ...
    @staticmethod
    def empty() -> "Optional": ...
    def orElse(self, p0: Any) -> Any: ...
    def isPresent(self) -> bool: ...
    @overload
    def orElseThrow(self) -> Any: ...
    @overload
    def orElseThrow(self, p0: Supplier) -> Any: ...
    def flatMap(self, p0: Function) -> "Optional": ...
    @staticmethod
    def ofNullable(p0: Any) -> "Optional": ...
    def ifPresentOrElse(self, p0: Consumer, p1: Runnable) -> None: ...
    def or_(self, p0: Supplier) -> "Optional": ...
    def orElseGet(self, p0: Supplier) -> Any: ...
    def ifPresent(self, p0: Consumer) -> None: ...
