from typing import Any, ClassVar, overload
from java.util.function.Consumer import Consumer
from java.util.function.DoubleConsumer import DoubleConsumer
from java.util.function.IntConsumer import IntConsumer
from java.util.function.LongConsumer import LongConsumer

class PrimitiveIterator:
    def forEachRemaining(self, p0: Any) -> None: ...

    class OfDouble:
        def nextDouble(self) -> float: ...
        @overload
        def forEachRemaining(self, p0: Any) -> None: ...
        @overload
        def forEachRemaining(self, p0: Consumer) -> None: ...
        @overload
        def forEachRemaining(self, p0: DoubleConsumer) -> None: ...
        @overload
        def next(self) -> float: ...
        @overload
        def next(self) -> Any: ...

    class OfLong:
        def nextLong(self) -> int: ...
        @overload
        def forEachRemaining(self, p0: Any) -> None: ...
        @overload
        def forEachRemaining(self, p0: Consumer) -> None: ...
        @overload
        def forEachRemaining(self, p0: LongConsumer) -> None: ...
        @overload
        def next(self) -> int: ...
        @overload
        def next(self) -> Any: ...

    class OfInt:
        def nextInt(self) -> int: ...
        @overload
        def forEachRemaining(self, p0: Any) -> None: ...
        @overload
        def forEachRemaining(self, p0: Consumer) -> None: ...
        @overload
        def forEachRemaining(self, p0: IntConsumer) -> None: ...
        @overload
        def next(self) -> int: ...
        @overload
        def next(self) -> Any: ...
