from typing import Any, ClassVar, overload
from java.util.Comparator import Comparator
from java.util.Iterator import Iterator
from java.util.SortedSet import SortedSet
from java.util.Spliterator import Spliterator
from java.util.function.Consumer import Consumer
from java.util.function.Predicate import Predicate

class PriorityQueue:
    @overload
    def __init__(self, p0: int, p1: Comparator) -> None: ...
    @overload
    def __init__(self, p0: list) -> None: ...
    @overload
    def __init__(self, p0: "PriorityQueue") -> None: ...
    @overload
    def __init__(self, p0: SortedSet) -> None: ...
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, p0: int) -> None: ...
    @overload
    def __init__(self, p0: Comparator) -> None: ...
    def peek(self) -> Any: ...
    def comparator(self) -> Comparator: ...
    def offer(self, p0: Any) -> bool: ...
    def poll(self) -> Any: ...
    def removeAll(self, p0: list) -> bool: ...
    def retainAll(self, p0: list) -> bool: ...
    def removeIf(self, p0: Predicate) -> bool: ...
    def remove(self, p0: Any) -> bool: ...
    def size(self) -> int: ...
    def clear(self) -> None: ...
    def add(self, p0: Any) -> bool: ...
    @overload
    def toArray(self) -> Any: ...
    @overload
    def toArray(self, p0: Any) -> Any: ...
    def iterator(self) -> Iterator: ...
    def contains(self, p0: Any) -> bool: ...
    def spliterator(self) -> Spliterator: ...
    def forEach(self, p0: Consumer) -> None: ...
