from typing import Any, ClassVar, overload
from java.io.File import File
from java.io.IOException import IOException
from java.io.InputStream import InputStream
from java.lang.Readable import Readable
from java.math.BigDecimal import BigDecimal
from java.math.BigInteger import BigInteger
from java.nio.channels.ReadableByteChannel import ReadableByteChannel
from java.nio.charset.Charset import Charset
from java.nio.file.Path import Path
from java.util.Locale import Locale
from java.util.regex.MatchResult import MatchResult
from java.util.regex.Pattern import Pattern
from java.util.stream.Stream import Stream

class Scanner:
    @overload
    def __init__(self, p0: File, p1: Charset) -> None: ...
    @overload
    def __init__(self, p0: File, p1: str) -> None: ...
    @overload
    def __init__(self, p0: File) -> None: ...
    @overload
    def __init__(self, p0: str) -> None: ...
    @overload
    def __init__(self, p0: ReadableByteChannel) -> None: ...
    @overload
    def __init__(self, p0: Path) -> None: ...
    @overload
    def __init__(self, p0: Path, p1: str) -> None: ...
    @overload
    def __init__(self, p0: Path, p1: Charset) -> None: ...
    @overload
    def __init__(self, p0: InputStream) -> None: ...
    @overload
    def __init__(self, p0: Readable) -> None: ...
    @overload
    def __init__(self, p0: ReadableByteChannel, p1: Charset) -> None: ...
    @overload
    def __init__(self, p0: ReadableByteChannel, p1: str) -> None: ...
    @overload
    def __init__(self, p0: InputStream, p1: Charset) -> None: ...
    @overload
    def __init__(self, p0: InputStream, p1: str) -> None: ...
    def nextBoolean(self) -> bool: ...
    @overload
    def nextLong(self, p0: int) -> int: ...
    @overload
    def nextLong(self) -> int: ...
    def tokens(self) -> Stream: ...
    def nextFloat(self) -> float: ...
    def remove(self) -> None: ...
    def reset(self) -> "Scanner": ...
    def toString(self) -> str: ...
    @overload
    def hasNext(self, p0: str) -> bool: ...
    @overload
    def hasNext(self, p0: Pattern) -> bool: ...
    @overload
    def hasNext(self) -> bool: ...
    @overload
    def next(self) -> Any: ...
    @overload
    def next(self, p0: Pattern) -> str: ...
    @overload
    def next(self) -> str: ...
    @overload
    def next(self, p0: str) -> str: ...
    def delimiter(self) -> Pattern: ...
    def locale(self) -> Locale: ...
    def close(self) -> None: ...
    def match_(self) -> MatchResult: ...
    @overload
    def skip(self, p0: str) -> "Scanner": ...
    @overload
    def skip(self, p0: Pattern) -> "Scanner": ...
    def ioException(self) -> IOException: ...
    def nextDouble(self) -> float: ...
    @overload
    def hasNextBigInteger(self, p0: int) -> bool: ...
    @overload
    def hasNextBigInteger(self) -> bool: ...
    @overload
    def nextBigInteger(self) -> BigInteger: ...
    @overload
    def nextBigInteger(self, p0: int) -> BigInteger: ...
    def useRadix(self, p0: int) -> "Scanner": ...
    @overload
    def useDelimiter(self, p0: Pattern) -> "Scanner": ...
    @overload
    def useDelimiter(self, p0: str) -> "Scanner": ...
    def hasNextLine(self) -> bool: ...
    def nextLine(self) -> str: ...
    def hasNextBoolean(self) -> bool: ...
    def hasNextFloat(self) -> bool: ...
    def hasNextDouble(self) -> bool: ...
    def hasNextBigDecimal(self) -> bool: ...
    def nextBigDecimal(self) -> BigDecimal: ...
    @overload
    def findAll(self, p0: str) -> Stream: ...
    @overload
    def findAll(self, p0: Pattern) -> Stream: ...
    @overload
    def nextInt(self, p0: int) -> int: ...
    @overload
    def nextInt(self) -> int: ...
    def radix(self) -> int: ...
    def useLocale(self, p0: Locale) -> "Scanner": ...
    @overload
    def findWithinHorizon(self, p0: str, p1: int) -> str: ...
    @overload
    def findWithinHorizon(self, p0: Pattern, p1: int) -> str: ...
    @overload
    def findInLine(self, p0: str) -> str: ...
    @overload
    def findInLine(self, p0: Pattern) -> str: ...
    @overload
    def hasNextByte(self, p0: int) -> bool: ...
    @overload
    def hasNextByte(self) -> bool: ...
    @overload
    def nextByte(self, p0: int) -> int: ...
    @overload
    def nextByte(self) -> int: ...
    @overload
    def hasNextShort(self) -> bool: ...
    @overload
    def hasNextShort(self, p0: int) -> bool: ...
    @overload
    def nextShort(self) -> int: ...
    @overload
    def nextShort(self, p0: int) -> int: ...
    @overload
    def hasNextInt(self, p0: int) -> bool: ...
    @overload
    def hasNextInt(self) -> bool: ...
    @overload
    def hasNextLong(self, p0: int) -> bool: ...
    @overload
    def hasNextLong(self) -> bool: ...
