from typing import Any, ClassVar, overload
from java.util.Comparator import Comparator
from java.util.Iterator import Iterator
from java.util.NavigableSet import NavigableSet
from java.util.SortedSet import SortedSet
from java.util.Spliterator import Spliterator

class TreeSet:
    @overload
    def __init__(self, p0: list) -> None: ...
    @overload
    def __init__(self, p0: SortedSet) -> None: ...
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, p0: Comparator) -> None: ...
    def comparator(self) -> Comparator: ...
    def pollFirst(self) -> Any: ...
    def pollLast(self) -> Any: ...
    def descendingIterator(self) -> Iterator: ...
    def descendingSet(self) -> NavigableSet: ...
    def ceiling(self, p0: Any) -> Any: ...
    def higher(self, p0: Any) -> Any: ...
    @overload
    def subSet(self, p0: Any, p1: Any) -> SortedSet: ...
    @overload
    def subSet(self, p0: Any, p1: bool, p2: Any, p3: bool) -> NavigableSet: ...
    @overload
    def headSet(self, p0: Any) -> SortedSet: ...
    @overload
    def headSet(self, p0: Any, p1: bool) -> NavigableSet: ...
    @overload
    def tailSet(self, p0: Any, p1: bool) -> NavigableSet: ...
    @overload
    def tailSet(self, p0: Any) -> SortedSet: ...
    def addFirst(self, p0: Any) -> None: ...
    def addLast(self, p0: Any) -> None: ...
    def lower(self, p0: Any) -> Any: ...
    def remove(self, p0: Any) -> bool: ...
    def size(self) -> int: ...
    def clone(self) -> Any: ...
    def floor(self, p0: Any) -> Any: ...
    def clear(self) -> None: ...
    def isEmpty(self) -> bool: ...
    def add(self, p0: Any) -> bool: ...
    def iterator(self) -> Iterator: ...
    def contains(self, p0: Any) -> bool: ...
    def last(self) -> Any: ...
    def spliterator(self) -> Spliterator: ...
    def addAll(self, p0: list) -> bool: ...
    def first(self) -> Any: ...
