from typing import Any, ClassVar, overload

class UUID:
    def __init__(self, p0: int, p1: int) -> None: ...
    def equals(self, p0: Any) -> bool: ...
    def toString(self) -> str: ...
    def version(self) -> int: ...
    def hashCode(self) -> int: ...
    @overload
    def compareTo(self, p0: Any) -> int: ...
    @overload
    def compareTo(self, p0: "UUID") -> int: ...
    def timestamp(self) -> int: ...
    def node(self) -> int: ...
    def variant(self) -> int: ...
    @staticmethod
    def randomUUID() -> "UUID": ...
    @staticmethod
    def nameUUIDFromBytes(p0: Any) -> "UUID": ...
    @staticmethod
    def ofEpochMillis(p0: int) -> "UUID": ...
    @staticmethod
    def fromString(p0: str) -> "UUID": ...
    def getLeastSignificantBits(self) -> int: ...
    def getMostSignificantBits(self) -> int: ...
    def clockSequence(self) -> int: ...
