from typing import Any, ClassVar, overload

class DataFormatException:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, p0: str) -> None: ...

from typing import Any, ClassVar, overload
from java.io.OutputStream import OutputStream
from java.nio.charset.Charset import Charset
from java.util.zip.ZipEntry import ZipEntry

class ZipOutputStream:
    STORED: ClassVar[int]
    DEFLATED: ClassVar[int]
    LOCSIG: ClassVar[int]
    EXTSIG: ClassVar[int]
    CENSIG: ClassVar[int]
    ENDSIG: ClassVar[int]
    LOCHDR: ClassVar[int]
    EXTHDR: ClassVar[int]
    CENHDR: ClassVar[int]
    ENDHDR: ClassVar[int]
    LOCVER: ClassVar[int]
    LOCFLG: ClassVar[int]
    LOCHOW: ClassVar[int]
    LOCTIM: ClassVar[int]
    LOCCRC: ClassVar[int]
    LOCSIZ: ClassVar[int]
    LOCLEN: ClassVar[int]
    LOCNAM: ClassVar[int]
    LOCEXT: ClassVar[int]
    EXTCRC: ClassVar[int]
    EXTSIZ: ClassVar[int]
    EXTLEN: ClassVar[int]
    CENVEM: ClassVar[int]
    CENVER: ClassVar[int]
    CENFLG: ClassVar[int]
    CENHOW: ClassVar[int]
    CENTIM: ClassVar[int]
    CENCRC: ClassVar[int]
    CENSIZ: ClassVar[int]
    CENLEN: ClassVar[int]
    CENNAM: ClassVar[int]
    CENEXT: ClassVar[int]
    CENCOM: ClassVar[int]
    CENDSK: ClassVar[int]
    CENATT: ClassVar[int]
    CENATX: ClassVar[int]
    CENOFF: ClassVar[int]
    ENDSUB: ClassVar[int]
    ENDTOT: ClassVar[int]
    ENDSIZ: ClassVar[int]
    ENDOFF: ClassVar[int]
    ENDCOM: ClassVar[int]
    @overload
    def __init__(self, p0: OutputStream) -> None: ...
    @overload
    def __init__(self, p0: OutputStream, p1: Charset) -> None: ...
    def putNextEntry(self, p0: ZipEntry) -> None: ...
    def write(self, p0: Any, p1: int, p2: int) -> None: ...
    def close(self) -> None: ...
    def setMethod(self, p0: int) -> None: ...
    def setComment(self, p0: str) -> None: ...
    def closeEntry(self) -> None: ...
    def setLevel(self, p0: int) -> None: ...
    def finish(self) -> None: ...

from typing import Any, ClassVar, overload
from java.io.InputStream import InputStream
from java.util.zip.Inflater import Inflater

class InflaterInputStream:
    @overload
    def __init__(self, p0: InputStream, p1: Inflater) -> None: ...
    @overload
    def __init__(self, p0: InputStream, p1: Inflater, p2: int) -> None: ...
    @overload
    def __init__(self, p0: InputStream) -> None: ...
    def reset(self) -> None: ...
    @overload
    def read(self, p0: Any, p1: int, p2: int) -> int: ...
    @overload
    def read(self) -> int: ...
    def close(self) -> None: ...
    def mark(self, p0: int) -> None: ...
    def skip(self, p0: int) -> int: ...
    def available(self) -> int: ...
    def markSupported(self) -> bool: ...

from typing import Any, ClassVar, overload
from java.io.OutputStream import OutputStream
from java.util.zip.Inflater import Inflater

class InflaterOutputStream:
    @overload
    def __init__(self, p0: OutputStream, p1: Inflater) -> None: ...
    @overload
    def __init__(self, p0: OutputStream) -> None: ...
    @overload
    def __init__(self, p0: OutputStream, p1: Inflater, p2: int) -> None: ...
    def flush(self) -> None: ...
    @overload
    def write(self, p0: int) -> None: ...
    @overload
    def write(self, p0: Any, p1: int, p2: int) -> None: ...
    def close(self) -> None: ...
    def finish(self) -> None: ...

from typing import Any, ClassVar, overload
from java.io.InputStream import InputStream
from java.io.OutputStream import OutputStream
from java.nio.charset.Charset import Charset
from java.util.zip.ZipEntry import ZipEntry

class ZipInputStream:
    LOCSIG: ClassVar[int]
    EXTSIG: ClassVar[int]
    CENSIG: ClassVar[int]
    ENDSIG: ClassVar[int]
    LOCHDR: ClassVar[int]
    EXTHDR: ClassVar[int]
    CENHDR: ClassVar[int]
    ENDHDR: ClassVar[int]
    LOCVER: ClassVar[int]
    LOCFLG: ClassVar[int]
    LOCHOW: ClassVar[int]
    LOCTIM: ClassVar[int]
    LOCCRC: ClassVar[int]
    LOCSIZ: ClassVar[int]
    LOCLEN: ClassVar[int]
    LOCNAM: ClassVar[int]
    LOCEXT: ClassVar[int]
    EXTCRC: ClassVar[int]
    EXTSIZ: ClassVar[int]
    EXTLEN: ClassVar[int]
    CENVEM: ClassVar[int]
    CENVER: ClassVar[int]
    CENFLG: ClassVar[int]
    CENHOW: ClassVar[int]
    CENTIM: ClassVar[int]
    CENCRC: ClassVar[int]
    CENSIZ: ClassVar[int]
    CENLEN: ClassVar[int]
    CENNAM: ClassVar[int]
    CENEXT: ClassVar[int]
    CENCOM: ClassVar[int]
    CENDSK: ClassVar[int]
    CENATT: ClassVar[int]
    CENATX: ClassVar[int]
    CENOFF: ClassVar[int]
    ENDSUB: ClassVar[int]
    ENDTOT: ClassVar[int]
    ENDSIZ: ClassVar[int]
    ENDOFF: ClassVar[int]
    ENDCOM: ClassVar[int]
    @overload
    def __init__(self, p0: InputStream, p1: Charset) -> None: ...
    @overload
    def __init__(self, p0: InputStream) -> None: ...
    def getNextEntry(self) -> ZipEntry: ...
    @overload
    def read(self, p0: Any, p1: int, p2: int) -> int: ...
    @overload
    def read(self) -> int: ...
    def close(self) -> None: ...
    def readAllBytes(self) -> Any: ...
    def closeEntry(self) -> None: ...
    @overload
    def readNBytes(self, p0: Any, p1: int, p2: int) -> int: ...
    @overload
    def readNBytes(self, p0: int) -> Any: ...
    def transferTo(self, p0: OutputStream) -> int: ...
    def skip(self, p0: int) -> int: ...
    def available(self) -> int: ...
    def skipNBytes(self, p0: int) -> None: ...

from typing import Any, ClassVar, overload
from java.io.OutputStream import OutputStream
from java.util.zip.Checksum import Checksum

class CheckedOutputStream:
    def __init__(self, p0: OutputStream, p1: Checksum) -> None: ...
    @overload
    def write(self, p0: Any, p1: int, p2: int) -> None: ...
    @overload
    def write(self, p0: int) -> None: ...
    def getChecksum(self) -> Checksum: ...

from typing import Any, ClassVar, overload
from java.io.InputStream import InputStream

class GZIPInputStream:
    GZIP_MAGIC: ClassVar[int]
    @overload
    def __init__(self, p0: InputStream) -> None: ...
    @overload
    def __init__(self, p0: InputStream, p1: int) -> None: ...
    def read(self, p0: Any, p1: int, p2: int) -> int: ...
    def close(self) -> None: ...

from typing import Any, ClassVar, overload
from java.io.InputStream import InputStream
from java.util.zip.Checksum import Checksum

class CheckedInputStream:
    def __init__(self, p0: InputStream, p1: Checksum) -> None: ...
    @overload
    def read(self, p0: Any, p1: int, p2: int) -> int: ...
    @overload
    def read(self) -> int: ...
    def getChecksum(self) -> Checksum: ...
    def skip(self, p0: int) -> int: ...

from typing import Any, ClassVar, overload
from java.nio.ByteBuffer import ByteBuffer

class Deflater:
    DEFLATED: ClassVar[int]
    NO_COMPRESSION: ClassVar[int]
    BEST_SPEED: ClassVar[int]
    BEST_COMPRESSION: ClassVar[int]
    DEFAULT_COMPRESSION: ClassVar[int]
    FILTERED: ClassVar[int]
    HUFFMAN_ONLY: ClassVar[int]
    DEFAULT_STRATEGY: ClassVar[int]
    NO_FLUSH: ClassVar[int]
    SYNC_FLUSH: ClassVar[int]
    FULL_FLUSH: ClassVar[int]
    @overload
    def __init__(self, p0: int, p1: bool) -> None: ...
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, p0: int) -> None: ...
    @overload
    def deflate(self, p0: Any, p1: int, p2: int) -> int: ...
    @overload
    def deflate(self, p0: Any, p1: int, p2: int, p3: int) -> int: ...
    @overload
    def deflate(self, p0: ByteBuffer) -> int: ...
    @overload
    def deflate(self, p0: Any) -> int: ...
    @overload
    def deflate(self, p0: ByteBuffer, p1: int) -> int: ...
    def reset(self) -> None: ...
    def end(self) -> None: ...
    @overload
    def setInput(self, p0: ByteBuffer) -> None: ...
    @overload
    def setInput(self, p0: Any) -> None: ...
    @overload
    def setInput(self, p0: Any, p1: int, p2: int) -> None: ...
    def getBytesWritten(self) -> int: ...
    def setStrategy(self, p0: int) -> None: ...
    def setLevel(self, p0: int) -> None: ...
    def finish(self) -> None: ...
    def finished(self) -> bool: ...
    def needsInput(self) -> bool: ...
    @overload
    def setDictionary(self, p0: Any, p1: int, p2: int) -> None: ...
    @overload
    def setDictionary(self, p0: Any) -> None: ...
    @overload
    def setDictionary(self, p0: ByteBuffer) -> None: ...
    def getAdler(self) -> int: ...
    def getBytesRead(self) -> int: ...
    def getTotalIn(self) -> int: ...
    def getTotalOut(self) -> int: ...

from typing import Any, ClassVar, overload
from java.nio.ByteBuffer import ByteBuffer

class CRC32:
    def __init__(self) -> None: ...
    def reset(self) -> None: ...
    @overload
    def update(self, p0: int) -> None: ...
    @overload
    def update(self, p0: ByteBuffer) -> None: ...
    @overload
    def update(self, p0: Any, p1: int, p2: int) -> None: ...
    def getValue(self) -> int: ...

from typing import Any, ClassVar, overload

class ZipError:
    def __init__(self, p0: str) -> None: ...

from typing import Any, ClassVar, overload
from java.io.File import File
from java.io.InputStream import InputStream
from java.nio.charset.Charset import Charset
from java.util.Enumeration import Enumeration
from java.util.stream.Stream import Stream
from java.util.zip.ZipEntry import ZipEntry

class ZipFile:
    OPEN_READ: ClassVar[int]
    OPEN_DELETE: ClassVar[int]
    LOCSIG: ClassVar[int]
    EXTSIG: ClassVar[int]
    CENSIG: ClassVar[int]
    ENDSIG: ClassVar[int]
    LOCHDR: ClassVar[int]
    EXTHDR: ClassVar[int]
    CENHDR: ClassVar[int]
    ENDHDR: ClassVar[int]
    LOCVER: ClassVar[int]
    LOCFLG: ClassVar[int]
    LOCHOW: ClassVar[int]
    LOCTIM: ClassVar[int]
    LOCCRC: ClassVar[int]
    LOCSIZ: ClassVar[int]
    LOCLEN: ClassVar[int]
    LOCNAM: ClassVar[int]
    LOCEXT: ClassVar[int]
    EXTCRC: ClassVar[int]
    EXTSIZ: ClassVar[int]
    EXTLEN: ClassVar[int]
    CENVEM: ClassVar[int]
    CENVER: ClassVar[int]
    CENFLG: ClassVar[int]
    CENHOW: ClassVar[int]
    CENTIM: ClassVar[int]
    CENCRC: ClassVar[int]
    CENSIZ: ClassVar[int]
    CENLEN: ClassVar[int]
    CENNAM: ClassVar[int]
    CENEXT: ClassVar[int]
    CENCOM: ClassVar[int]
    CENDSK: ClassVar[int]
    CENATT: ClassVar[int]
    CENATX: ClassVar[int]
    CENOFF: ClassVar[int]
    ENDSUB: ClassVar[int]
    ENDTOT: ClassVar[int]
    ENDSIZ: ClassVar[int]
    ENDOFF: ClassVar[int]
    ENDCOM: ClassVar[int]
    @overload
    def __init__(self, p0: str) -> None: ...
    @overload
    def __init__(self, p0: File, p1: Charset) -> None: ...
    @overload
    def __init__(self, p0: str, p1: Charset) -> None: ...
    @overload
    def __init__(self, p0: File, p1: int) -> None: ...
    @overload
    def __init__(self, p0: File) -> None: ...
    @overload
    def __init__(self, p0: File, p1: int, p2: Charset) -> None: ...
    def getInputStream(self, p0: ZipEntry) -> InputStream: ...
    def getName(self) -> str: ...
    def size(self) -> int: ...
    def stream(self) -> Stream: ...
    def close(self) -> None: ...
    def entries(self) -> Enumeration: ...
    def getEntry(self, p0: str) -> ZipEntry: ...
    def getComment(self) -> str: ...

from typing import Any, ClassVar, overload
from java.nio.file.attribute.FileTime import FileTime
from java.time.LocalDateTime import LocalDateTime

class ZipEntry:
    STORED: ClassVar[int]
    DEFLATED: ClassVar[int]
    LOCSIG: ClassVar[int]
    EXTSIG: ClassVar[int]
    CENSIG: ClassVar[int]
    ENDSIG: ClassVar[int]
    LOCHDR: ClassVar[int]
    EXTHDR: ClassVar[int]
    CENHDR: ClassVar[int]
    ENDHDR: ClassVar[int]
    LOCVER: ClassVar[int]
    LOCFLG: ClassVar[int]
    LOCHOW: ClassVar[int]
    LOCTIM: ClassVar[int]
    LOCCRC: ClassVar[int]
    LOCSIZ: ClassVar[int]
    LOCLEN: ClassVar[int]
    LOCNAM: ClassVar[int]
    LOCEXT: ClassVar[int]
    EXTCRC: ClassVar[int]
    EXTSIZ: ClassVar[int]
    EXTLEN: ClassVar[int]
    CENVEM: ClassVar[int]
    CENVER: ClassVar[int]
    CENFLG: ClassVar[int]
    CENHOW: ClassVar[int]
    CENTIM: ClassVar[int]
    CENCRC: ClassVar[int]
    CENSIZ: ClassVar[int]
    CENLEN: ClassVar[int]
    CENNAM: ClassVar[int]
    CENEXT: ClassVar[int]
    CENCOM: ClassVar[int]
    CENDSK: ClassVar[int]
    CENATT: ClassVar[int]
    CENATX: ClassVar[int]
    CENOFF: ClassVar[int]
    ENDSUB: ClassVar[int]
    ENDTOT: ClassVar[int]
    ENDSIZ: ClassVar[int]
    ENDOFF: ClassVar[int]
    ENDCOM: ClassVar[int]
    @overload
    def __init__(self, p0: str) -> None: ...
    @overload
    def __init__(self, p0: "ZipEntry") -> None: ...
    def isDirectory(self) -> bool: ...
    def getName(self) -> str: ...
    def toString(self) -> str: ...
    def hashCode(self) -> int: ...
    def clone(self) -> Any: ...
    def getMethod(self) -> int: ...
    def setTime(self, p0: int) -> None: ...
    def setTimeLocal(self, p0: LocalDateTime) -> None: ...
    def getTimeLocal(self) -> LocalDateTime: ...
    def setLastAccessTime(self, p0: FileTime) -> "ZipEntry": ...
    def getLastAccessTime(self) -> FileTime: ...
    def setCreationTime(self, p0: FileTime) -> "ZipEntry": ...
    def getCreationTime(self) -> FileTime: ...
    def setSize(self, p0: int) -> None: ...
    def getCompressedSize(self) -> int: ...
    def setCompressedSize(self, p0: int) -> None: ...
    def setCrc(self, p0: int) -> None: ...
    def getCrc(self) -> int: ...
    def setMethod(self, p0: int) -> None: ...
    def setExtra(self, p0: Any) -> None: ...
    def getExtra(self) -> Any: ...
    def setComment(self, p0: str) -> None: ...
    def getSize(self) -> int: ...
    def getTime(self) -> int: ...
    def getComment(self) -> str: ...
    def getLastModifiedTime(self) -> FileTime: ...
    def setLastModifiedTime(self, p0: FileTime) -> "ZipEntry": ...

from typing import Any, ClassVar, overload
from java.io.OutputStream import OutputStream
from java.util.zip.Deflater import Deflater

class DeflaterOutputStream:
    @overload
    def __init__(self, p0: OutputStream, p1: bool) -> None: ...
    @overload
    def __init__(self, p0: OutputStream) -> None: ...
    @overload
    def __init__(self, p0: OutputStream, p1: Deflater, p2: int, p3: bool) -> None: ...
    @overload
    def __init__(self, p0: OutputStream, p1: Deflater) -> None: ...
    @overload
    def __init__(self, p0: OutputStream, p1: Deflater, p2: bool) -> None: ...
    @overload
    def __init__(self, p0: OutputStream, p1: Deflater, p2: int) -> None: ...
    def flush(self) -> None: ...
    @overload
    def write(self, p0: int) -> None: ...
    @overload
    def write(self, p0: Any, p1: int, p2: int) -> None: ...
    def close(self) -> None: ...
    def finish(self) -> None: ...

from typing import Any, ClassVar, overload

class ZipException:
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, p0: str) -> None: ...

from typing import Any, ClassVar, overload
from java.nio.ByteBuffer import ByteBuffer

class CRC32C:
    def __init__(self) -> None: ...
    def reset(self) -> None: ...
    @overload
    def update(self, p0: Any, p1: int, p2: int) -> None: ...
    @overload
    def update(self, p0: int) -> None: ...
    @overload
    def update(self, p0: ByteBuffer) -> None: ...
    def getValue(self) -> int: ...

from typing import Any, ClassVar, overload
from java.io.InputStream import InputStream
from java.util.zip.Deflater import Deflater

class DeflaterInputStream:
    @overload
    def __init__(self, p0: InputStream, p1: Deflater) -> None: ...
    @overload
    def __init__(self, p0: InputStream) -> None: ...
    @overload
    def __init__(self, p0: InputStream, p1: Deflater, p2: int) -> None: ...
    def reset(self) -> None: ...
    @overload
    def read(self, p0: Any, p1: int, p2: int) -> int: ...
    @overload
    def read(self) -> int: ...
    def close(self) -> None: ...
    def mark(self, p0: int) -> None: ...
    def skip(self, p0: int) -> int: ...
    def available(self) -> int: ...
    def markSupported(self) -> bool: ...

from typing import Any, ClassVar, overload
from java.io.OutputStream import OutputStream

class GZIPOutputStream:
    @overload
    def __init__(self, p0: OutputStream, p1: bool) -> None: ...
    @overload
    def __init__(self, p0: OutputStream) -> None: ...
    @overload
    def __init__(self, p0: OutputStream, p1: int, p2: bool) -> None: ...
    @overload
    def __init__(self, p0: OutputStream, p1: int) -> None: ...
    def write(self, p0: Any, p1: int, p2: int) -> None: ...
    def finish(self) -> None: ...

from typing import Any, ClassVar, overload
from java.nio.ByteBuffer import ByteBuffer

class Inflater:
    @overload
    def __init__(self, p0: bool) -> None: ...
    @overload
    def __init__(self) -> None: ...
    def reset(self) -> None: ...
    @overload
    def inflate(self, p0: ByteBuffer) -> int: ...
    @overload
    def inflate(self, p0: Any) -> int: ...
    @overload
    def inflate(self, p0: Any, p1: int, p2: int) -> int: ...
    def end(self) -> None: ...
    @overload
    def setInput(self, p0: Any, p1: int, p2: int) -> None: ...
    @overload
    def setInput(self, p0: Any) -> None: ...
    @overload
    def setInput(self, p0: ByteBuffer) -> None: ...
    def getBytesWritten(self) -> int: ...
    def finished(self) -> bool: ...
    def needsDictionary(self) -> bool: ...
    def needsInput(self) -> bool: ...
    @overload
    def setDictionary(self, p0: Any) -> None: ...
    @overload
    def setDictionary(self, p0: ByteBuffer) -> None: ...
    @overload
    def setDictionary(self, p0: Any, p1: int, p2: int) -> None: ...
    def getAdler(self) -> int: ...
    def getBytesRead(self) -> int: ...
    def getRemaining(self) -> int: ...
    def getTotalIn(self) -> int: ...
    def getTotalOut(self) -> int: ...

from typing import Any, ClassVar, overload
from java.nio.ByteBuffer import ByteBuffer

class Adler32:
    def __init__(self) -> None: ...
    def reset(self) -> None: ...
    @overload
    def update(self, p0: int) -> None: ...
    @overload
    def update(self, p0: ByteBuffer) -> None: ...
    @overload
    def update(self, p0: Any, p1: int, p2: int) -> None: ...
    def getValue(self) -> int: ...

from typing import Any, ClassVar, overload
from java.nio.ByteBuffer import ByteBuffer

class Checksum:
    def reset(self) -> None: ...
    @overload
    def update(self, p0: int) -> None: ...
    @overload
    def update(self, p0: ByteBuffer) -> None: ...
    @overload
    def update(self, p0: Any, p1: int, p2: int) -> None: ...
    @overload
    def update(self, p0: Any) -> None: ...
    def getValue(self) -> int: ...

