from typing import Any, ClassVar, overload

class CredentialDataRequest:
    def getDeviceSignedEntriesToRequest(self) -> dict: ...
    def getIssuerSignedEntriesToRequest(self) -> dict: ...
    def getReaderSignature(self) -> Any: ...
    def getRequestMessage(self) -> Any: ...
    def isAllowUsingExhaustedKeys(self) -> bool: ...
    def isAllowUsingExpiredKeys(self) -> bool: ...
    def isIncrementUseCount(self) -> bool: ...

    class Builder:
        def __init__(self) -> None: ...
        def setAllowUsingExhaustedKeys(self, p0: bool) -> Any: ...
        def setAllowUsingExpiredKeys(self, p0: bool) -> Any: ...
        def build(self) -> "CredentialDataRequest": ...
        def setDeviceSignedEntriesToRequest(self, p0: dict) -> Any: ...
        def setIncrementUseCount(self, p0: bool) -> Any: ...
        def setIssuerSignedEntriesToRequest(self, p0: dict) -> Any: ...
        def setReaderSignature(self, p0: Any) -> Any: ...
        def setRequestMessage(self, p0: Any) -> Any: ...
