from typing import Any, ClassVar, overload
from android.security.identity.PersonalizationData import PersonalizationData
from android.security.identity.ResultData import ResultData
from java.security.KeyPair import KeyPair
from java.security.PublicKey import PublicKey
from java.security.cert.X509Certificate import X509Certificate
from java.time.Instant import Instant

class IdentityCredential:
    def update(self, p0: PersonalizationData) -> Any: ...
    def delete(self, p0: Any) -> Any: ...
    def getEntries(self, p0: Any, p1: dict, p2: Any, p3: Any) -> ResultData: ...
    def getAuthenticationKeyMetadata(self) -> list: ...
    def createEphemeralKeyPair(self) -> KeyPair: ...
    def setReaderEphemeralPublicKey(self, p0: PublicKey) -> None: ...
    def encryptMessageToReader(self, p0: Any) -> Any: ...
    def decryptMessageFromReader(self, p0: Any) -> Any: ...
    def getCredentialKeyCertificateChain(self) -> list: ...
    def setAllowUsingExhaustedKeys(self, p0: bool) -> None: ...
    def setAllowUsingExpiredKeys(self, p0: bool) -> None: ...
    @overload
    def setAvailableAuthenticationKeys(self, p0: int, p1: int, p2: int) -> None: ...
    @overload
    def setAvailableAuthenticationKeys(self, p0: int, p1: int) -> None: ...
    def getAuthKeysNeedingCertification(self) -> list: ...
    @overload
    def storeStaticAuthenticationData(self, p0: X509Certificate, p1: Instant, p2: Any) -> None: ...
    @overload
    def storeStaticAuthenticationData(self, p0: X509Certificate, p1: Any) -> None: ...
    def getAuthenticationDataUsageCount(self) -> Any: ...
    def proveOwnership(self, p0: Any) -> Any: ...
