from typing import Any, ClassVar, overload
from android.security.identity.CredentialDataRequest import CredentialDataRequest
from android.security.identity.CredentialDataResult import CredentialDataResult
from java.security.KeyPair import KeyPair
from java.security.PublicKey import PublicKey

class PresentationSession:
    def setReaderEphemeralPublicKey(self, p0: PublicKey) -> None: ...
    def getCredentialData(self, p0: str, p1: CredentialDataRequest) -> CredentialDataResult: ...
    def getEphemeralKeyPair(self) -> KeyPair: ...
    def setSessionTranscript(self, p0: Any) -> None: ...
