from typing import Any, ClassVar, overload
from android.app.appsearch.AppSearchResult import AppSearchResult

class AppSearchBatchResult:
    def getSuccesses(self) -> dict: ...
    def getFailures(self) -> dict: ...
    def isSuccess(self) -> bool: ...
    def toString(self) -> str: ...
    def getAll(self) -> dict: ...

    class Builder:
        def __init__(self) -> None: ...
        def setSuccess(self, p0: Any, p1: Any) -> Any: ...
        def setFailure(self, p0: Any, p1: int, p2: str) -> Any: ...
        def build(self) -> "AppSearchBatchResult": ...
        def setResult(self, p0: Any, p1: AppSearchResult) -> Any: ...
