# cython: language_level=3
# Generated by jni-wrap cython — do not edit by hand.

from jni_core._core cimport (
    JavaObject, get_env, check_jni_exc,
    find_class_global, get_method_id, get_static_method_id,
    get_field_id, get_static_field_id, j_str, py_str,
)
from jni_core._dispatch cimport (
    jnicore_NewObjectA, jnicore_DeleteLocalRef, jnicore_NewGlobalRef,
    jnicore_CallVoidMethodA, jnicore_CallObjectMethodA,
    jnicore_CallBooleanMethodA, jnicore_CallByteMethodA,
    jnicore_CallCharMethodA, jnicore_CallShortMethodA,
    jnicore_CallIntMethodA, jnicore_CallLongMethodA,
    jnicore_CallFloatMethodA, jnicore_CallDoubleMethodA,
    jnicore_CallStaticVoidMethodA, jnicore_CallStaticObjectMethodA,
    jnicore_CallStaticBooleanMethodA, jnicore_CallStaticByteMethodA,
    jnicore_CallStaticCharMethodA, jnicore_CallStaticShortMethodA,
    jnicore_CallStaticIntMethodA, jnicore_CallStaticLongMethodA,
    jnicore_CallStaticFloatMethodA, jnicore_CallStaticDoubleMethodA,
    jnicore_GetObjectField, jnicore_SetObjectField,
    jnicore_GetBooleanField, jnicore_SetBooleanField,
    jnicore_GetByteField, jnicore_SetByteField,
    jnicore_GetCharField, jnicore_SetCharField,
    jnicore_GetShortField, jnicore_SetShortField,
    jnicore_GetIntField, jnicore_SetIntField,
    jnicore_GetLongField, jnicore_SetLongField,
    jnicore_GetFloatField, jnicore_SetFloatField,
    jnicore_GetDoubleField, jnicore_SetDoubleField,
    jnicore_GetStaticObjectField, jnicore_SetStaticObjectField,
    jnicore_GetStaticBooleanField, jnicore_SetStaticBooleanField,
    jnicore_GetStaticByteField, jnicore_SetStaticByteField,
    jnicore_GetStaticCharField, jnicore_SetStaticCharField,
    jnicore_GetStaticShortField, jnicore_SetStaticShortField,
    jnicore_GetStaticIntField, jnicore_SetStaticIntField,
    jnicore_GetStaticLongField, jnicore_SetStaticLongField,
    jnicore_GetStaticFloatField, jnicore_SetStaticFloatField,
    jnicore_GetStaticDoubleField, jnicore_SetStaticDoubleField,
)
from jni_core.jni cimport (
    jclass, jobject, jmethodID, jfieldID, jvalue, JNIEnv,
    jboolean, jbyte, jchar, jshort, jint, jlong, jfloat, jdouble, jstring,
)

include "jni_core/conversions.pxi"

__javaclass__ = "android/app/appsearch/SearchResult"  # android.app.appsearch.SearchResult

cdef jclass _cls_SearchResult = NULL
cdef jmethodID _m_SearchResult_getGenericDocument_0 = NULL
cdef jmethodID _m_SearchResult_getJoinedResults_0 = NULL
cdef jmethodID _m_SearchResult_getInformationalRankingSignals_0 = NULL
cdef jmethodID _m_SearchResult_getMatchInfos_0 = NULL
cdef jmethodID _m_SearchResult_getParentTypeMap_0 = NULL
cdef jmethodID _m_SearchResult_getRankingSignal_0 = NULL
cdef jmethodID _m_SearchResult_getDatabaseName_0 = NULL
cdef jmethodID _m_SearchResult_getPackageName_0 = NULL
cdef jmethodID _m_SearchResult_writeToParcel_0 = NULL
cdef jmethodID _m_SearchResult_describeContents_0 = NULL
cdef jfieldID _sf_SearchResult_CREATOR = NULL
cdef jfieldID _sf_SearchResult_CONTENTS_FILE_DESCRIPTOR = NULL
cdef jfieldID _sf_SearchResult_PARCELABLE_WRITE_RETURN_VALUE = NULL

cdef int _ensure_ids_SearchResult(JNIEnv* env) except -1:
    global _cls_SearchResult, _m_SearchResult_getGenericDocument_0, _m_SearchResult_getJoinedResults_0, _m_SearchResult_getInformationalRankingSignals_0, _m_SearchResult_getMatchInfos_0, _m_SearchResult_getParentTypeMap_0, _m_SearchResult_getRankingSignal_0, _m_SearchResult_getDatabaseName_0, _m_SearchResult_getPackageName_0, _m_SearchResult_writeToParcel_0, _m_SearchResult_describeContents_0, _sf_SearchResult_CREATOR, _sf_SearchResult_CONTENTS_FILE_DESCRIPTOR, _sf_SearchResult_PARCELABLE_WRITE_RETURN_VALUE
    if _cls_SearchResult != NULL:
        return 0
    _cls_SearchResult = find_class_global(env, b"android/app/appsearch/SearchResult")
    _m_SearchResult_getGenericDocument_0 = get_method_id(env, _cls_SearchResult, b"getGenericDocument", b"()Landroid/app/appsearch/GenericDocument;")
    _m_SearchResult_getJoinedResults_0 = get_method_id(env, _cls_SearchResult, b"getJoinedResults", b"()Ljava/util/List;")
    _m_SearchResult_getInformationalRankingSignals_0 = get_method_id(env, _cls_SearchResult, b"getInformationalRankingSignals", b"()Ljava/util/List;")
    _m_SearchResult_getMatchInfos_0 = get_method_id(env, _cls_SearchResult, b"getMatchInfos", b"()Ljava/util/List;")
    _m_SearchResult_getParentTypeMap_0 = get_method_id(env, _cls_SearchResult, b"getParentTypeMap", b"()Ljava/util/Map;")
    _m_SearchResult_getRankingSignal_0 = get_method_id(env, _cls_SearchResult, b"getRankingSignal", b"()D")
    _m_SearchResult_getDatabaseName_0 = get_method_id(env, _cls_SearchResult, b"getDatabaseName", b"()Ljava/lang/String;")
    _m_SearchResult_getPackageName_0 = get_method_id(env, _cls_SearchResult, b"getPackageName", b"()Ljava/lang/String;")
    _m_SearchResult_writeToParcel_0 = get_method_id(env, _cls_SearchResult, b"writeToParcel", b"(Landroid/os/Parcel;I)V")
    _m_SearchResult_describeContents_0 = get_method_id(env, _cls_SearchResult, b"describeContents", b"()I")
    _sf_SearchResult_CREATOR = get_static_field_id(env, _cls_SearchResult, b"CREATOR", b"Landroid/os/Parcelable$Creator;")
    _sf_SearchResult_CONTENTS_FILE_DESCRIPTOR = get_static_field_id(env, _cls_SearchResult, b"CONTENTS_FILE_DESCRIPTOR", b"I")
    _sf_SearchResult_PARCELABLE_WRITE_RETURN_VALUE = get_static_field_id(env, _cls_SearchResult, b"PARCELABLE_WRITE_RETURN_VALUE", b"I")
    return 0

cdef class SearchResult(JavaObject):
    """android.app.appsearch.SearchResult"""

    def __init__(self, *args, **kwargs):
        raise TypeError("SearchResult has no public constructor")

    # Static field SearchResult.CREATOR
    @staticmethod
    def CREATOR() -> object:
        cdef JNIEnv* env = get_env()
        _ensure_ids_SearchResult(env)
        cdef jobject _ret = jnicore_GetStaticObjectField(env, _cls_SearchResult, _sf_SearchResult_CREATOR)
        check_jni_exc(env)
        if _ret == NULL:
            return None
        cdef JavaObject _wrapped = JavaObject.__new__(JavaObject)
        _wrapped._adopt_local(env, _ret)
        return _wrapped

    # Static field SearchResult.CONTENTS_FILE_DESCRIPTOR
    @staticmethod
    def CONTENTS_FILE_DESCRIPTOR() -> int:
        cdef JNIEnv* env = get_env()
        _ensure_ids_SearchResult(env)
        cdef jint _ret = jnicore_GetStaticIntField(env, _cls_SearchResult, _sf_SearchResult_CONTENTS_FILE_DESCRIPTOR)
        check_jni_exc(env)
        return <int>_ret

    # Static field SearchResult.PARCELABLE_WRITE_RETURN_VALUE
    @staticmethod
    def PARCELABLE_WRITE_RETURN_VALUE() -> int:
        cdef JNIEnv* env = get_env()
        _ensure_ids_SearchResult(env)
        cdef jint _ret = jnicore_GetStaticIntField(env, _cls_SearchResult, _sf_SearchResult_PARCELABLE_WRITE_RETURN_VALUE)
        check_jni_exc(env)
        return <int>_ret

    cdef jobject _getGenericDocument(self, JNIEnv* env) except? NULL:
        _ensure_ids_SearchResult(env)
        cdef jvalue _args[1]  # zero-arg call; _args ignored by JNI
        cdef jobject _ret = jnicore_CallObjectMethodA(env, self._handle, _m_SearchResult_getGenericDocument_0, _args)
        check_jni_exc(env)
        return _ret

    def getGenericDocument(self) -> object:
        cdef JNIEnv* env = get_env()
        cdef jobject _ret = NULL
        _ret = self._getGenericDocument(env)
        if _ret == NULL:
            return None
        cdef JavaObject _wrapped = JavaObject.__new__(JavaObject)
        _wrapped._adopt_local(env, _ret)
        return _wrapped

    cdef jobject _getGenericDocument_0(self, JNIEnv* env) except? NULL:
        _ensure_ids_SearchResult(env)
        cdef jvalue _args[1]  # zero-arg call; _args ignored by JNI
        cdef jobject _ret = jnicore_CallObjectMethodA(env, self._handle, _m_SearchResult_getGenericDocument_0, _args)
        check_jni_exc(env)
        return _ret

    def getGenericDocument_0(self) -> object:
        cdef JNIEnv* env = get_env()
        cdef jobject _ret = NULL
        _ret = self._getGenericDocument_0(env)
        if _ret == NULL:
            return None
        cdef JavaObject _wrapped = JavaObject.__new__(JavaObject)
        _wrapped._adopt_local(env, _ret)
        return _wrapped

    cdef jobject _getJoinedResults(self, JNIEnv* env) except? NULL:
        _ensure_ids_SearchResult(env)
        cdef jvalue _args[1]  # zero-arg call; _args ignored by JNI
        cdef jobject _ret = jnicore_CallObjectMethodA(env, self._handle, _m_SearchResult_getJoinedResults_0, _args)
        check_jni_exc(env)
        return _ret

    def getJoinedResults(self) -> object:
        cdef JNIEnv* env = get_env()
        cdef jobject _ret = NULL
        _ret = self._getJoinedResults(env)
        if _ret == NULL:
            return None
        cdef JavaObject _wrapped = JavaObject.__new__(JavaObject)
        _wrapped._adopt_local(env, _ret)
        return _wrapped

    cdef jobject _getJoinedResults_0(self, JNIEnv* env) except? NULL:
        _ensure_ids_SearchResult(env)
        cdef jvalue _args[1]  # zero-arg call; _args ignored by JNI
        cdef jobject _ret = jnicore_CallObjectMethodA(env, self._handle, _m_SearchResult_getJoinedResults_0, _args)
        check_jni_exc(env)
        return _ret

    def getJoinedResults_0(self) -> object:
        cdef JNIEnv* env = get_env()
        cdef jobject _ret = NULL
        _ret = self._getJoinedResults_0(env)
        if _ret == NULL:
            return None
        cdef JavaObject _wrapped = JavaObject.__new__(JavaObject)
        _wrapped._adopt_local(env, _ret)
        return _wrapped

    cdef jobject _getInformationalRankingSignals(self, JNIEnv* env) except? NULL:
        _ensure_ids_SearchResult(env)
        cdef jvalue _args[1]  # zero-arg call; _args ignored by JNI
        cdef jobject _ret = jnicore_CallObjectMethodA(env, self._handle, _m_SearchResult_getInformationalRankingSignals_0, _args)
        check_jni_exc(env)
        return _ret

    def getInformationalRankingSignals(self) -> object:
        cdef JNIEnv* env = get_env()
        cdef jobject _ret = NULL
        _ret = self._getInformationalRankingSignals(env)
        if _ret == NULL:
            return None
        cdef JavaObject _wrapped = JavaObject.__new__(JavaObject)
        _wrapped._adopt_local(env, _ret)
        return _wrapped

    cdef jobject _getInformationalRankingSignals_0(self, JNIEnv* env) except? NULL:
        _ensure_ids_SearchResult(env)
        cdef jvalue _args[1]  # zero-arg call; _args ignored by JNI
        cdef jobject _ret = jnicore_CallObjectMethodA(env, self._handle, _m_SearchResult_getInformationalRankingSignals_0, _args)
        check_jni_exc(env)
        return _ret

    def getInformationalRankingSignals_0(self) -> object:
        cdef JNIEnv* env = get_env()
        cdef jobject _ret = NULL
        _ret = self._getInformationalRankingSignals_0(env)
        if _ret == NULL:
            return None
        cdef JavaObject _wrapped = JavaObject.__new__(JavaObject)
        _wrapped._adopt_local(env, _ret)
        return _wrapped

    cdef jobject _getMatchInfos(self, JNIEnv* env) except? NULL:
        _ensure_ids_SearchResult(env)
        cdef jvalue _args[1]  # zero-arg call; _args ignored by JNI
        cdef jobject _ret = jnicore_CallObjectMethodA(env, self._handle, _m_SearchResult_getMatchInfos_0, _args)
        check_jni_exc(env)
        return _ret

    def getMatchInfos(self) -> object:
        cdef JNIEnv* env = get_env()
        cdef jobject _ret = NULL
        _ret = self._getMatchInfos(env)
        if _ret == NULL:
            return None
        cdef JavaObject _wrapped = JavaObject.__new__(JavaObject)
        _wrapped._adopt_local(env, _ret)
        return _wrapped

    cdef jobject _getMatchInfos_0(self, JNIEnv* env) except? NULL:
        _ensure_ids_SearchResult(env)
        cdef jvalue _args[1]  # zero-arg call; _args ignored by JNI
        cdef jobject _ret = jnicore_CallObjectMethodA(env, self._handle, _m_SearchResult_getMatchInfos_0, _args)
        check_jni_exc(env)
        return _ret

    def getMatchInfos_0(self) -> object:
        cdef JNIEnv* env = get_env()
        cdef jobject _ret = NULL
        _ret = self._getMatchInfos_0(env)
        if _ret == NULL:
            return None
        cdef JavaObject _wrapped = JavaObject.__new__(JavaObject)
        _wrapped._adopt_local(env, _ret)
        return _wrapped

    cdef jobject _getParentTypeMap(self, JNIEnv* env) except? NULL:
        _ensure_ids_SearchResult(env)
        cdef jvalue _args[1]  # zero-arg call; _args ignored by JNI
        cdef jobject _ret = jnicore_CallObjectMethodA(env, self._handle, _m_SearchResult_getParentTypeMap_0, _args)
        check_jni_exc(env)
        return _ret

    def getParentTypeMap(self) -> object:
        cdef JNIEnv* env = get_env()
        cdef jobject _ret = NULL
        _ret = self._getParentTypeMap(env)
        if _ret == NULL:
            return None
        cdef JavaObject _wrapped = JavaObject.__new__(JavaObject)
        _wrapped._adopt_local(env, _ret)
        return _wrapped

    cdef jobject _getParentTypeMap_0(self, JNIEnv* env) except? NULL:
        _ensure_ids_SearchResult(env)
        cdef jvalue _args[1]  # zero-arg call; _args ignored by JNI
        cdef jobject _ret = jnicore_CallObjectMethodA(env, self._handle, _m_SearchResult_getParentTypeMap_0, _args)
        check_jni_exc(env)
        return _ret

    def getParentTypeMap_0(self) -> object:
        cdef JNIEnv* env = get_env()
        cdef jobject _ret = NULL
        _ret = self._getParentTypeMap_0(env)
        if _ret == NULL:
            return None
        cdef JavaObject _wrapped = JavaObject.__new__(JavaObject)
        _wrapped._adopt_local(env, _ret)
        return _wrapped

    cdef jdouble _getRankingSignal(self, JNIEnv* env) except *:
        _ensure_ids_SearchResult(env)
        cdef jvalue _args[1]  # zero-arg call; _args ignored by JNI
        cdef jdouble _ret = jnicore_CallDoubleMethodA(env, self._handle, _m_SearchResult_getRankingSignal_0, _args)
        check_jni_exc(env)
        return _ret

    def getRankingSignal(self) -> float:
        cdef JNIEnv* env = get_env()
        cdef jdouble _ret = 0.0
        _ret = self._getRankingSignal(env)
        return <double>_ret

    cdef jdouble _getRankingSignal_0(self, JNIEnv* env) except *:
        _ensure_ids_SearchResult(env)
        cdef jvalue _args[1]  # zero-arg call; _args ignored by JNI
        cdef jdouble _ret = jnicore_CallDoubleMethodA(env, self._handle, _m_SearchResult_getRankingSignal_0, _args)
        check_jni_exc(env)
        return _ret

    def getRankingSignal_0(self) -> float:
        cdef JNIEnv* env = get_env()
        cdef jdouble _ret = 0.0
        _ret = self._getRankingSignal_0(env)
        return <double>_ret

    cdef jstring _getDatabaseName(self, JNIEnv* env) except? NULL:
        _ensure_ids_SearchResult(env)
        cdef jvalue _args[1]  # zero-arg call; _args ignored by JNI
        cdef jstring _ret = <jstring>jnicore_CallObjectMethodA(env, self._handle, _m_SearchResult_getDatabaseName_0, _args)
        check_jni_exc(env)
        return <jstring>_ret

    def getDatabaseName(self) -> str:
        cdef JNIEnv* env = get_env()
        cdef jstring _ret = NULL
        _ret = self._getDatabaseName(env)
        return py_str(env, _ret)

    cdef jstring _getDatabaseName_0(self, JNIEnv* env) except? NULL:
        _ensure_ids_SearchResult(env)
        cdef jvalue _args[1]  # zero-arg call; _args ignored by JNI
        cdef jstring _ret = <jstring>jnicore_CallObjectMethodA(env, self._handle, _m_SearchResult_getDatabaseName_0, _args)
        check_jni_exc(env)
        return <jstring>_ret

    def getDatabaseName_0(self) -> str:
        cdef JNIEnv* env = get_env()
        cdef jstring _ret = NULL
        _ret = self._getDatabaseName_0(env)
        return py_str(env, _ret)

    cdef jstring _getPackageName(self, JNIEnv* env) except? NULL:
        _ensure_ids_SearchResult(env)
        cdef jvalue _args[1]  # zero-arg call; _args ignored by JNI
        cdef jstring _ret = <jstring>jnicore_CallObjectMethodA(env, self._handle, _m_SearchResult_getPackageName_0, _args)
        check_jni_exc(env)
        return <jstring>_ret

    def getPackageName(self) -> str:
        cdef JNIEnv* env = get_env()
        cdef jstring _ret = NULL
        _ret = self._getPackageName(env)
        return py_str(env, _ret)

    cdef jstring _getPackageName_0(self, JNIEnv* env) except? NULL:
        _ensure_ids_SearchResult(env)
        cdef jvalue _args[1]  # zero-arg call; _args ignored by JNI
        cdef jstring _ret = <jstring>jnicore_CallObjectMethodA(env, self._handle, _m_SearchResult_getPackageName_0, _args)
        check_jni_exc(env)
        return <jstring>_ret

    def getPackageName_0(self) -> str:
        cdef JNIEnv* env = get_env()
        cdef jstring _ret = NULL
        _ret = self._getPackageName_0(env)
        return py_str(env, _ret)

    cdef void _writeToParcel(self, JNIEnv* env, jobject p0, jint p1) except *:
        _ensure_ids_SearchResult(env)
        cdef jvalue _args[2]
        _args[0].l = p0
        _args[1].i = p1
        jnicore_CallVoidMethodA(env, self._handle, _m_SearchResult_writeToParcel_0, _args)
        check_jni_exc(env)

    def writeToParcel(self, p0, p1) -> None:
        cdef JNIEnv* env = get_env()
        cdef jobject _h0 = (<JavaObject?>p0)._handle if p0 is not None else <jobject>NULL
        cdef jint _c1 = py_to_jint(p1)
        self._writeToParcel(env, _h0, _c1)

    cdef void _writeToParcel_0(self, JNIEnv* env, jobject p0, jint p1) except *:
        _ensure_ids_SearchResult(env)
        cdef jvalue _args[2]
        _args[0].l = p0
        _args[1].i = p1
        jnicore_CallVoidMethodA(env, self._handle, _m_SearchResult_writeToParcel_0, _args)
        check_jni_exc(env)

    def writeToParcel_0(self, p0, p1) -> None:
        cdef JNIEnv* env = get_env()
        cdef jobject _h0 = (<JavaObject?>p0)._handle if p0 is not None else <jobject>NULL
        cdef jint _c1 = py_to_jint(p1)
        self._writeToParcel_0(env, _h0, _c1)

    cdef jint _describeContents(self, JNIEnv* env) except *:
        _ensure_ids_SearchResult(env)
        cdef jvalue _args[1]  # zero-arg call; _args ignored by JNI
        cdef jint _ret = jnicore_CallIntMethodA(env, self._handle, _m_SearchResult_describeContents_0, _args)
        check_jni_exc(env)
        return _ret

    def describeContents(self) -> int:
        cdef JNIEnv* env = get_env()
        cdef jint _ret = 0
        _ret = self._describeContents(env)
        return <int>_ret

    cdef jint _describeContents_0(self, JNIEnv* env) except *:
        _ensure_ids_SearchResult(env)
        cdef jvalue _args[1]  # zero-arg call; _args ignored by JNI
        cdef jint _ret = jnicore_CallIntMethodA(env, self._handle, _m_SearchResult_describeContents_0, _args)
        check_jni_exc(env)
        return _ret

    def describeContents_0(self) -> int:
        cdef JNIEnv* env = get_env()
        cdef jint _ret = 0
        _ret = self._describeContents_0(env)
        return <int>_ret

    @staticmethod
    def from_java_object(obj) -> object:
        """Wrap a plain JavaObject as SearchResult (no JNI type check)."""
        cdef JNIEnv* env = get_env()
        cdef SearchResult inst = SearchResult.__new__(SearchResult)
        cdef jobject global_ref = jnicore_NewGlobalRef(env, (<JavaObject?>obj)._handle)
        inst._adopt_global(env, global_ref)
        return inst

# Nested class: android.app.appsearch.SearchResult$MatchRange  (JNI: android/app/appsearch/SearchResult$MatchRange)
cdef jclass _cls_MatchRange = NULL
cdef jmethodID _ctor_MatchRange_0 = NULL
cdef jmethodID _m_MatchRange_equals_0 = NULL
cdef jmethodID _m_MatchRange_toString_0 = NULL
cdef jmethodID _m_MatchRange_hashCode_0 = NULL
cdef jmethodID _m_MatchRange_getEnd_0 = NULL
cdef jmethodID _m_MatchRange_getStart_0 = NULL

cdef int _ensure_ids_MatchRange(JNIEnv* env) except -1:
    global _cls_MatchRange, _ctor_MatchRange_0, _m_MatchRange_equals_0, _m_MatchRange_toString_0, _m_MatchRange_hashCode_0, _m_MatchRange_getEnd_0, _m_MatchRange_getStart_0
    if _cls_MatchRange != NULL:
        return 0
    _cls_MatchRange = find_class_global(env, b"android/app/appsearch/SearchResult$MatchRange")
    _ctor_MatchRange_0 = get_method_id(env, _cls_MatchRange, b"<init>", b"(II)V")
    _m_MatchRange_equals_0 = get_method_id(env, _cls_MatchRange, b"equals", b"(Ljava/lang/Object;)Z")
    _m_MatchRange_toString_0 = get_method_id(env, _cls_MatchRange, b"toString", b"()Ljava/lang/String;")
    _m_MatchRange_hashCode_0 = get_method_id(env, _cls_MatchRange, b"hashCode", b"()I")
    _m_MatchRange_getEnd_0 = get_method_id(env, _cls_MatchRange, b"getEnd", b"()I")
    _m_MatchRange_getStart_0 = get_method_id(env, _cls_MatchRange, b"getStart", b"()I")
    return 0

cdef class MatchRange(JavaObject):
    """android.app.appsearch.SearchResult$MatchRange"""

    def __init__(self, p0, p1):
        cdef JNIEnv* env = get_env()
        _ensure_ids_MatchRange(env)
        cdef jvalue _args[2]
        _args[0].i = py_to_jint(p0)
        _args[1].i = py_to_jint(p1)
        cdef jobject _ret = jnicore_NewObjectA(env, _cls_MatchRange, _ctor_MatchRange_0, _args)
        check_jni_exc(env)
        self._adopt_local(env, _ret)

    cdef jboolean _equals(self, JNIEnv* env, jobject p0) except *:
        _ensure_ids_MatchRange(env)
        cdef jvalue _args[1]
        _args[0].l = p0
        cdef jboolean _ret = jnicore_CallBooleanMethodA(env, self._handle, _m_MatchRange_equals_0, _args)
        check_jni_exc(env)
        return _ret

    def equals(self, p0) -> bool:
        cdef JNIEnv* env = get_env()
        cdef jboolean _ret = 0
        cdef jobject _h0 = (<JavaObject?>p0)._handle if p0 is not None else <jobject>NULL
        _ret = self._equals(env, _h0)
        return jboolean_to_py(_ret)

    cdef jboolean _equals_0(self, JNIEnv* env, jobject p0) except *:
        _ensure_ids_MatchRange(env)
        cdef jvalue _args[1]
        _args[0].l = p0
        cdef jboolean _ret = jnicore_CallBooleanMethodA(env, self._handle, _m_MatchRange_equals_0, _args)
        check_jni_exc(env)
        return _ret

    def equals_0(self, p0) -> bool:
        cdef JNIEnv* env = get_env()
        cdef jboolean _ret = 0
        cdef jobject _h0 = (<JavaObject?>p0)._handle if p0 is not None else <jobject>NULL
        _ret = self._equals_0(env, _h0)
        return jboolean_to_py(_ret)

    cdef jstring _toString(self, JNIEnv* env) except? NULL:
        _ensure_ids_MatchRange(env)
        cdef jvalue _args[1]  # zero-arg call; _args ignored by JNI
        cdef jstring _ret = <jstring>jnicore_CallObjectMethodA(env, self._handle, _m_MatchRange_toString_0, _args)
        check_jni_exc(env)
        return <jstring>_ret

    def toString(self) -> str:
        cdef JNIEnv* env = get_env()
        cdef jstring _ret = NULL
        _ret = self._toString(env)
        return py_str(env, _ret)

    cdef jstring _toString_0(self, JNIEnv* env) except? NULL:
        _ensure_ids_MatchRange(env)
        cdef jvalue _args[1]  # zero-arg call; _args ignored by JNI
        cdef jstring _ret = <jstring>jnicore_CallObjectMethodA(env, self._handle, _m_MatchRange_toString_0, _args)
        check_jni_exc(env)
        return <jstring>_ret

    def toString_0(self) -> str:
        cdef JNIEnv* env = get_env()
        cdef jstring _ret = NULL
        _ret = self._toString_0(env)
        return py_str(env, _ret)

    cdef jint _hashCode(self, JNIEnv* env) except *:
        _ensure_ids_MatchRange(env)
        cdef jvalue _args[1]  # zero-arg call; _args ignored by JNI
        cdef jint _ret = jnicore_CallIntMethodA(env, self._handle, _m_MatchRange_hashCode_0, _args)
        check_jni_exc(env)
        return _ret

    def hashCode(self) -> int:
        cdef JNIEnv* env = get_env()
        cdef jint _ret = 0
        _ret = self._hashCode(env)
        return <int>_ret

    cdef jint _hashCode_0(self, JNIEnv* env) except *:
        _ensure_ids_MatchRange(env)
        cdef jvalue _args[1]  # zero-arg call; _args ignored by JNI
        cdef jint _ret = jnicore_CallIntMethodA(env, self._handle, _m_MatchRange_hashCode_0, _args)
        check_jni_exc(env)
        return _ret

    def hashCode_0(self) -> int:
        cdef JNIEnv* env = get_env()
        cdef jint _ret = 0
        _ret = self._hashCode_0(env)
        return <int>_ret

    cdef jint _getEnd(self, JNIEnv* env) except *:
        _ensure_ids_MatchRange(env)
        cdef jvalue _args[1]  # zero-arg call; _args ignored by JNI
        cdef jint _ret = jnicore_CallIntMethodA(env, self._handle, _m_MatchRange_getEnd_0, _args)
        check_jni_exc(env)
        return _ret

    def getEnd(self) -> int:
        cdef JNIEnv* env = get_env()
        cdef jint _ret = 0
        _ret = self._getEnd(env)
        return <int>_ret

    cdef jint _getEnd_0(self, JNIEnv* env) except *:
        _ensure_ids_MatchRange(env)
        cdef jvalue _args[1]  # zero-arg call; _args ignored by JNI
        cdef jint _ret = jnicore_CallIntMethodA(env, self._handle, _m_MatchRange_getEnd_0, _args)
        check_jni_exc(env)
        return _ret

    def getEnd_0(self) -> int:
        cdef JNIEnv* env = get_env()
        cdef jint _ret = 0
        _ret = self._getEnd_0(env)
        return <int>_ret

    cdef jint _getStart(self, JNIEnv* env) except *:
        _ensure_ids_MatchRange(env)
        cdef jvalue _args[1]  # zero-arg call; _args ignored by JNI
        cdef jint _ret = jnicore_CallIntMethodA(env, self._handle, _m_MatchRange_getStart_0, _args)
        check_jni_exc(env)
        return _ret

    def getStart(self) -> int:
        cdef JNIEnv* env = get_env()
        cdef jint _ret = 0
        _ret = self._getStart(env)
        return <int>_ret

    cdef jint _getStart_0(self, JNIEnv* env) except *:
        _ensure_ids_MatchRange(env)
        cdef jvalue _args[1]  # zero-arg call; _args ignored by JNI
        cdef jint _ret = jnicore_CallIntMethodA(env, self._handle, _m_MatchRange_getStart_0, _args)
        check_jni_exc(env)
        return _ret

    def getStart_0(self) -> int:
        cdef JNIEnv* env = get_env()
        cdef jint _ret = 0
        _ret = self._getStart_0(env)
        return <int>_ret

    @staticmethod
    def from_java_object(obj) -> object:
        """Wrap a plain JavaObject as MatchRange (no JNI type check)."""
        cdef JNIEnv* env = get_env()
        cdef MatchRange inst = MatchRange.__new__(MatchRange)
        cdef jobject global_ref = jnicore_NewGlobalRef(env, (<JavaObject?>obj)._handle)
        inst._adopt_global(env, global_ref)
        return inst

# Nested class: android.app.appsearch.SearchResult$MatchInfo  (JNI: android/app/appsearch/SearchResult$MatchInfo)
cdef jclass _cls_MatchInfo = NULL
cdef jmethodID _m_MatchInfo_getFullText_0 = NULL
cdef jmethodID _m_MatchInfo_getExactMatchRange_0 = NULL
cdef jmethodID _m_MatchInfo_getExactMatch_0 = NULL
cdef jmethodID _m_MatchInfo_getPropertyPath_0 = NULL
cdef jmethodID _m_MatchInfo_getPropertyPathObject_0 = NULL
cdef jmethodID _m_MatchInfo_getSnippet_0 = NULL
cdef jmethodID _m_MatchInfo_getSnippetRange_0 = NULL
cdef jmethodID _m_MatchInfo_getSubmatch_0 = NULL
cdef jmethodID _m_MatchInfo_getSubmatchRange_0 = NULL
cdef jmethodID _m_MatchInfo_writeToParcel_0 = NULL
cdef jmethodID _m_MatchInfo_describeContents_0 = NULL
cdef jfieldID _sf_MatchInfo_CREATOR = NULL
cdef jfieldID _sf_MatchInfo_CONTENTS_FILE_DESCRIPTOR = NULL
cdef jfieldID _sf_MatchInfo_PARCELABLE_WRITE_RETURN_VALUE = NULL

cdef int _ensure_ids_MatchInfo(JNIEnv* env) except -1:
    global _cls_MatchInfo, _m_MatchInfo_getFullText_0, _m_MatchInfo_getExactMatchRange_0, _m_MatchInfo_getExactMatch_0, _m_MatchInfo_getPropertyPath_0, _m_MatchInfo_getPropertyPathObject_0, _m_MatchInfo_getSnippet_0, _m_MatchInfo_getSnippetRange_0, _m_MatchInfo_getSubmatch_0, _m_MatchInfo_getSubmatchRange_0, _m_MatchInfo_writeToParcel_0, _m_MatchInfo_describeContents_0, _sf_MatchInfo_CREATOR, _sf_MatchInfo_CONTENTS_FILE_DESCRIPTOR, _sf_MatchInfo_PARCELABLE_WRITE_RETURN_VALUE
    if _cls_MatchInfo != NULL:
        return 0
    _cls_MatchInfo = find_class_global(env, b"android/app/appsearch/SearchResult$MatchInfo")
    _m_MatchInfo_getFullText_0 = get_method_id(env, _cls_MatchInfo, b"getFullText", b"()Ljava/lang/String;")
    _m_MatchInfo_getExactMatchRange_0 = get_method_id(env, _cls_MatchInfo, b"getExactMatchRange", b"()Landroid/app/appsearch/SearchResult$MatchRange;")
    _m_MatchInfo_getExactMatch_0 = get_method_id(env, _cls_MatchInfo, b"getExactMatch", b"()Ljava/lang/CharSequence;")
    _m_MatchInfo_getPropertyPath_0 = get_method_id(env, _cls_MatchInfo, b"getPropertyPath", b"()Ljava/lang/String;")
    _m_MatchInfo_getPropertyPathObject_0 = get_method_id(env, _cls_MatchInfo, b"getPropertyPathObject", b"()Landroid/app/appsearch/PropertyPath;")
    _m_MatchInfo_getSnippet_0 = get_method_id(env, _cls_MatchInfo, b"getSnippet", b"()Ljava/lang/CharSequence;")
    _m_MatchInfo_getSnippetRange_0 = get_method_id(env, _cls_MatchInfo, b"getSnippetRange", b"()Landroid/app/appsearch/SearchResult$MatchRange;")
    _m_MatchInfo_getSubmatch_0 = get_method_id(env, _cls_MatchInfo, b"getSubmatch", b"()Ljava/lang/CharSequence;")
    _m_MatchInfo_getSubmatchRange_0 = get_method_id(env, _cls_MatchInfo, b"getSubmatchRange", b"()Landroid/app/appsearch/SearchResult$MatchRange;")
    _m_MatchInfo_writeToParcel_0 = get_method_id(env, _cls_MatchInfo, b"writeToParcel", b"(Landroid/os/Parcel;I)V")
    _m_MatchInfo_describeContents_0 = get_method_id(env, _cls_MatchInfo, b"describeContents", b"()I")
    _sf_MatchInfo_CREATOR = get_static_field_id(env, _cls_MatchInfo, b"CREATOR", b"Landroid/os/Parcelable$Creator;")
    _sf_MatchInfo_CONTENTS_FILE_DESCRIPTOR = get_static_field_id(env, _cls_MatchInfo, b"CONTENTS_FILE_DESCRIPTOR", b"I")
    _sf_MatchInfo_PARCELABLE_WRITE_RETURN_VALUE = get_static_field_id(env, _cls_MatchInfo, b"PARCELABLE_WRITE_RETURN_VALUE", b"I")
    return 0

cdef class MatchInfo(JavaObject):
    """android.app.appsearch.SearchResult$MatchInfo"""

    def __init__(self, *args, **kwargs):
        raise TypeError("MatchInfo has no public constructor")

    # Static field MatchInfo.CREATOR
    @staticmethod
    def CREATOR() -> object:
        cdef JNIEnv* env = get_env()
        _ensure_ids_MatchInfo(env)
        cdef jobject _ret = jnicore_GetStaticObjectField(env, _cls_MatchInfo, _sf_MatchInfo_CREATOR)
        check_jni_exc(env)
        if _ret == NULL:
            return None
        cdef JavaObject _wrapped = JavaObject.__new__(JavaObject)
        _wrapped._adopt_local(env, _ret)
        return _wrapped

    # Static field MatchInfo.CONTENTS_FILE_DESCRIPTOR
    @staticmethod
    def CONTENTS_FILE_DESCRIPTOR() -> int:
        cdef JNIEnv* env = get_env()
        _ensure_ids_MatchInfo(env)
        cdef jint _ret = jnicore_GetStaticIntField(env, _cls_MatchInfo, _sf_MatchInfo_CONTENTS_FILE_DESCRIPTOR)
        check_jni_exc(env)
        return <int>_ret

    # Static field MatchInfo.PARCELABLE_WRITE_RETURN_VALUE
    @staticmethod
    def PARCELABLE_WRITE_RETURN_VALUE() -> int:
        cdef JNIEnv* env = get_env()
        _ensure_ids_MatchInfo(env)
        cdef jint _ret = jnicore_GetStaticIntField(env, _cls_MatchInfo, _sf_MatchInfo_PARCELABLE_WRITE_RETURN_VALUE)
        check_jni_exc(env)
        return <int>_ret

    cdef jstring _getFullText(self, JNIEnv* env) except? NULL:
        _ensure_ids_MatchInfo(env)
        cdef jvalue _args[1]  # zero-arg call; _args ignored by JNI
        cdef jstring _ret = <jstring>jnicore_CallObjectMethodA(env, self._handle, _m_MatchInfo_getFullText_0, _args)
        check_jni_exc(env)
        return <jstring>_ret

    def getFullText(self) -> str:
        cdef JNIEnv* env = get_env()
        cdef jstring _ret = NULL
        _ret = self._getFullText(env)
        return py_str(env, _ret)

    cdef jstring _getFullText_0(self, JNIEnv* env) except? NULL:
        _ensure_ids_MatchInfo(env)
        cdef jvalue _args[1]  # zero-arg call; _args ignored by JNI
        cdef jstring _ret = <jstring>jnicore_CallObjectMethodA(env, self._handle, _m_MatchInfo_getFullText_0, _args)
        check_jni_exc(env)
        return <jstring>_ret

    def getFullText_0(self) -> str:
        cdef JNIEnv* env = get_env()
        cdef jstring _ret = NULL
        _ret = self._getFullText_0(env)
        return py_str(env, _ret)

    cdef jobject _getExactMatchRange(self, JNIEnv* env) except? NULL:
        _ensure_ids_MatchInfo(env)
        cdef jvalue _args[1]  # zero-arg call; _args ignored by JNI
        cdef jobject _ret = jnicore_CallObjectMethodA(env, self._handle, _m_MatchInfo_getExactMatchRange_0, _args)
        check_jni_exc(env)
        return _ret

    def getExactMatchRange(self) -> object:
        cdef JNIEnv* env = get_env()
        cdef jobject _ret = NULL
        _ret = self._getExactMatchRange(env)
        if _ret == NULL:
            return None
        cdef JavaObject _wrapped = JavaObject.__new__(JavaObject)
        _wrapped._adopt_local(env, _ret)
        return _wrapped

    cdef jobject _getExactMatchRange_0(self, JNIEnv* env) except? NULL:
        _ensure_ids_MatchInfo(env)
        cdef jvalue _args[1]  # zero-arg call; _args ignored by JNI
        cdef jobject _ret = jnicore_CallObjectMethodA(env, self._handle, _m_MatchInfo_getExactMatchRange_0, _args)
        check_jni_exc(env)
        return _ret

    def getExactMatchRange_0(self) -> object:
        cdef JNIEnv* env = get_env()
        cdef jobject _ret = NULL
        _ret = self._getExactMatchRange_0(env)
        if _ret == NULL:
            return None
        cdef JavaObject _wrapped = JavaObject.__new__(JavaObject)
        _wrapped._adopt_local(env, _ret)
        return _wrapped

    cdef jstring _getExactMatch(self, JNIEnv* env) except? NULL:
        _ensure_ids_MatchInfo(env)
        cdef jvalue _args[1]  # zero-arg call; _args ignored by JNI
        cdef jstring _ret = <jstring>jnicore_CallObjectMethodA(env, self._handle, _m_MatchInfo_getExactMatch_0, _args)
        check_jni_exc(env)
        return <jstring>_ret

    def getExactMatch(self) -> str:
        cdef JNIEnv* env = get_env()
        cdef jstring _ret = NULL
        _ret = self._getExactMatch(env)
        return py_str(env, _ret)

    cdef jstring _getExactMatch_0(self, JNIEnv* env) except? NULL:
        _ensure_ids_MatchInfo(env)
        cdef jvalue _args[1]  # zero-arg call; _args ignored by JNI
        cdef jstring _ret = <jstring>jnicore_CallObjectMethodA(env, self._handle, _m_MatchInfo_getExactMatch_0, _args)
        check_jni_exc(env)
        return <jstring>_ret

    def getExactMatch_0(self) -> str:
        cdef JNIEnv* env = get_env()
        cdef jstring _ret = NULL
        _ret = self._getExactMatch_0(env)
        return py_str(env, _ret)

    cdef jstring _getPropertyPath(self, JNIEnv* env) except? NULL:
        _ensure_ids_MatchInfo(env)
        cdef jvalue _args[1]  # zero-arg call; _args ignored by JNI
        cdef jstring _ret = <jstring>jnicore_CallObjectMethodA(env, self._handle, _m_MatchInfo_getPropertyPath_0, _args)
        check_jni_exc(env)
        return <jstring>_ret

    def getPropertyPath(self) -> str:
        cdef JNIEnv* env = get_env()
        cdef jstring _ret = NULL
        _ret = self._getPropertyPath(env)
        return py_str(env, _ret)

    cdef jstring _getPropertyPath_0(self, JNIEnv* env) except? NULL:
        _ensure_ids_MatchInfo(env)
        cdef jvalue _args[1]  # zero-arg call; _args ignored by JNI
        cdef jstring _ret = <jstring>jnicore_CallObjectMethodA(env, self._handle, _m_MatchInfo_getPropertyPath_0, _args)
        check_jni_exc(env)
        return <jstring>_ret

    def getPropertyPath_0(self) -> str:
        cdef JNIEnv* env = get_env()
        cdef jstring _ret = NULL
        _ret = self._getPropertyPath_0(env)
        return py_str(env, _ret)

    cdef jobject _getPropertyPathObject(self, JNIEnv* env) except? NULL:
        _ensure_ids_MatchInfo(env)
        cdef jvalue _args[1]  # zero-arg call; _args ignored by JNI
        cdef jobject _ret = jnicore_CallObjectMethodA(env, self._handle, _m_MatchInfo_getPropertyPathObject_0, _args)
        check_jni_exc(env)
        return _ret

    def getPropertyPathObject(self) -> object:
        cdef JNIEnv* env = get_env()
        cdef jobject _ret = NULL
        _ret = self._getPropertyPathObject(env)
        if _ret == NULL:
            return None
        cdef JavaObject _wrapped = JavaObject.__new__(JavaObject)
        _wrapped._adopt_local(env, _ret)
        return _wrapped

    cdef jobject _getPropertyPathObject_0(self, JNIEnv* env) except? NULL:
        _ensure_ids_MatchInfo(env)
        cdef jvalue _args[1]  # zero-arg call; _args ignored by JNI
        cdef jobject _ret = jnicore_CallObjectMethodA(env, self._handle, _m_MatchInfo_getPropertyPathObject_0, _args)
        check_jni_exc(env)
        return _ret

    def getPropertyPathObject_0(self) -> object:
        cdef JNIEnv* env = get_env()
        cdef jobject _ret = NULL
        _ret = self._getPropertyPathObject_0(env)
        if _ret == NULL:
            return None
        cdef JavaObject _wrapped = JavaObject.__new__(JavaObject)
        _wrapped._adopt_local(env, _ret)
        return _wrapped

    cdef jstring _getSnippet(self, JNIEnv* env) except? NULL:
        _ensure_ids_MatchInfo(env)
        cdef jvalue _args[1]  # zero-arg call; _args ignored by JNI
        cdef jstring _ret = <jstring>jnicore_CallObjectMethodA(env, self._handle, _m_MatchInfo_getSnippet_0, _args)
        check_jni_exc(env)
        return <jstring>_ret

    def getSnippet(self) -> str:
        cdef JNIEnv* env = get_env()
        cdef jstring _ret = NULL
        _ret = self._getSnippet(env)
        return py_str(env, _ret)

    cdef jstring _getSnippet_0(self, JNIEnv* env) except? NULL:
        _ensure_ids_MatchInfo(env)
        cdef jvalue _args[1]  # zero-arg call; _args ignored by JNI
        cdef jstring _ret = <jstring>jnicore_CallObjectMethodA(env, self._handle, _m_MatchInfo_getSnippet_0, _args)
        check_jni_exc(env)
        return <jstring>_ret

    def getSnippet_0(self) -> str:
        cdef JNIEnv* env = get_env()
        cdef jstring _ret = NULL
        _ret = self._getSnippet_0(env)
        return py_str(env, _ret)

    cdef jobject _getSnippetRange(self, JNIEnv* env) except? NULL:
        _ensure_ids_MatchInfo(env)
        cdef jvalue _args[1]  # zero-arg call; _args ignored by JNI
        cdef jobject _ret = jnicore_CallObjectMethodA(env, self._handle, _m_MatchInfo_getSnippetRange_0, _args)
        check_jni_exc(env)
        return _ret

    def getSnippetRange(self) -> object:
        cdef JNIEnv* env = get_env()
        cdef jobject _ret = NULL
        _ret = self._getSnippetRange(env)
        if _ret == NULL:
            return None
        cdef JavaObject _wrapped = JavaObject.__new__(JavaObject)
        _wrapped._adopt_local(env, _ret)
        return _wrapped

    cdef jobject _getSnippetRange_0(self, JNIEnv* env) except? NULL:
        _ensure_ids_MatchInfo(env)
        cdef jvalue _args[1]  # zero-arg call; _args ignored by JNI
        cdef jobject _ret = jnicore_CallObjectMethodA(env, self._handle, _m_MatchInfo_getSnippetRange_0, _args)
        check_jni_exc(env)
        return _ret

    def getSnippetRange_0(self) -> object:
        cdef JNIEnv* env = get_env()
        cdef jobject _ret = NULL
        _ret = self._getSnippetRange_0(env)
        if _ret == NULL:
            return None
        cdef JavaObject _wrapped = JavaObject.__new__(JavaObject)
        _wrapped._adopt_local(env, _ret)
        return _wrapped

    cdef jstring _getSubmatch(self, JNIEnv* env) except? NULL:
        _ensure_ids_MatchInfo(env)
        cdef jvalue _args[1]  # zero-arg call; _args ignored by JNI
        cdef jstring _ret = <jstring>jnicore_CallObjectMethodA(env, self._handle, _m_MatchInfo_getSubmatch_0, _args)
        check_jni_exc(env)
        return <jstring>_ret

    def getSubmatch(self) -> str:
        cdef JNIEnv* env = get_env()
        cdef jstring _ret = NULL
        _ret = self._getSubmatch(env)
        return py_str(env, _ret)

    cdef jstring _getSubmatch_0(self, JNIEnv* env) except? NULL:
        _ensure_ids_MatchInfo(env)
        cdef jvalue _args[1]  # zero-arg call; _args ignored by JNI
        cdef jstring _ret = <jstring>jnicore_CallObjectMethodA(env, self._handle, _m_MatchInfo_getSubmatch_0, _args)
        check_jni_exc(env)
        return <jstring>_ret

    def getSubmatch_0(self) -> str:
        cdef JNIEnv* env = get_env()
        cdef jstring _ret = NULL
        _ret = self._getSubmatch_0(env)
        return py_str(env, _ret)

    cdef jobject _getSubmatchRange(self, JNIEnv* env) except? NULL:
        _ensure_ids_MatchInfo(env)
        cdef jvalue _args[1]  # zero-arg call; _args ignored by JNI
        cdef jobject _ret = jnicore_CallObjectMethodA(env, self._handle, _m_MatchInfo_getSubmatchRange_0, _args)
        check_jni_exc(env)
        return _ret

    def getSubmatchRange(self) -> object:
        cdef JNIEnv* env = get_env()
        cdef jobject _ret = NULL
        _ret = self._getSubmatchRange(env)
        if _ret == NULL:
            return None
        cdef JavaObject _wrapped = JavaObject.__new__(JavaObject)
        _wrapped._adopt_local(env, _ret)
        return _wrapped

    cdef jobject _getSubmatchRange_0(self, JNIEnv* env) except? NULL:
        _ensure_ids_MatchInfo(env)
        cdef jvalue _args[1]  # zero-arg call; _args ignored by JNI
        cdef jobject _ret = jnicore_CallObjectMethodA(env, self._handle, _m_MatchInfo_getSubmatchRange_0, _args)
        check_jni_exc(env)
        return _ret

    def getSubmatchRange_0(self) -> object:
        cdef JNIEnv* env = get_env()
        cdef jobject _ret = NULL
        _ret = self._getSubmatchRange_0(env)
        if _ret == NULL:
            return None
        cdef JavaObject _wrapped = JavaObject.__new__(JavaObject)
        _wrapped._adopt_local(env, _ret)
        return _wrapped

    cdef void _writeToParcel(self, JNIEnv* env, jobject p0, jint p1) except *:
        _ensure_ids_MatchInfo(env)
        cdef jvalue _args[2]
        _args[0].l = p0
        _args[1].i = p1
        jnicore_CallVoidMethodA(env, self._handle, _m_MatchInfo_writeToParcel_0, _args)
        check_jni_exc(env)

    def writeToParcel(self, p0, p1) -> None:
        cdef JNIEnv* env = get_env()
        cdef jobject _h0 = (<JavaObject?>p0)._handle if p0 is not None else <jobject>NULL
        cdef jint _c1 = py_to_jint(p1)
        self._writeToParcel(env, _h0, _c1)

    cdef void _writeToParcel_0(self, JNIEnv* env, jobject p0, jint p1) except *:
        _ensure_ids_MatchInfo(env)
        cdef jvalue _args[2]
        _args[0].l = p0
        _args[1].i = p1
        jnicore_CallVoidMethodA(env, self._handle, _m_MatchInfo_writeToParcel_0, _args)
        check_jni_exc(env)

    def writeToParcel_0(self, p0, p1) -> None:
        cdef JNIEnv* env = get_env()
        cdef jobject _h0 = (<JavaObject?>p0)._handle if p0 is not None else <jobject>NULL
        cdef jint _c1 = py_to_jint(p1)
        self._writeToParcel_0(env, _h0, _c1)

    cdef jint _describeContents(self, JNIEnv* env) except *:
        _ensure_ids_MatchInfo(env)
        cdef jvalue _args[1]  # zero-arg call; _args ignored by JNI
        cdef jint _ret = jnicore_CallIntMethodA(env, self._handle, _m_MatchInfo_describeContents_0, _args)
        check_jni_exc(env)
        return _ret

    def describeContents(self) -> int:
        cdef JNIEnv* env = get_env()
        cdef jint _ret = 0
        _ret = self._describeContents(env)
        return <int>_ret

    cdef jint _describeContents_0(self, JNIEnv* env) except *:
        _ensure_ids_MatchInfo(env)
        cdef jvalue _args[1]  # zero-arg call; _args ignored by JNI
        cdef jint _ret = jnicore_CallIntMethodA(env, self._handle, _m_MatchInfo_describeContents_0, _args)
        check_jni_exc(env)
        return _ret

    def describeContents_0(self) -> int:
        cdef JNIEnv* env = get_env()
        cdef jint _ret = 0
        _ret = self._describeContents_0(env)
        return <int>_ret

    @staticmethod
    def from_java_object(obj) -> object:
        """Wrap a plain JavaObject as MatchInfo (no JNI type check)."""
        cdef JNIEnv* env = get_env()
        cdef MatchInfo inst = MatchInfo.__new__(MatchInfo)
        cdef jobject global_ref = jnicore_NewGlobalRef(env, (<JavaObject?>obj)._handle)
        inst._adopt_global(env, global_ref)
        return inst

# Nested class: android.app.appsearch.SearchResult$MatchInfo$Builder  (JNI: android/app/appsearch/SearchResult$MatchInfo$Builder)
cdef jclass _cls_MatchInfo_Builder = NULL
cdef jmethodID _ctor_MatchInfo_Builder_0 = NULL
cdef jmethodID _m_MatchInfo_Builder_build_0 = NULL
cdef jmethodID _m_MatchInfo_Builder_setSnippetRange_0 = NULL
cdef jmethodID _m_MatchInfo_Builder_setSubmatchRange_0 = NULL
cdef jmethodID _m_MatchInfo_Builder_setExactMatchRange_0 = NULL

cdef int _ensure_ids_MatchInfo_Builder(JNIEnv* env) except -1:
    global _cls_MatchInfo_Builder, _ctor_MatchInfo_Builder_0, _m_MatchInfo_Builder_build_0, _m_MatchInfo_Builder_setSnippetRange_0, _m_MatchInfo_Builder_setSubmatchRange_0, _m_MatchInfo_Builder_setExactMatchRange_0
    if _cls_MatchInfo_Builder != NULL:
        return 0
    _cls_MatchInfo_Builder = find_class_global(env, b"android/app/appsearch/SearchResult$MatchInfo$Builder")
    _ctor_MatchInfo_Builder_0 = get_method_id(env, _cls_MatchInfo_Builder, b"<init>", b"(Ljava/lang/String;)V")
    _m_MatchInfo_Builder_build_0 = get_method_id(env, _cls_MatchInfo_Builder, b"build", b"()Landroid/app/appsearch/SearchResult$MatchInfo;")
    _m_MatchInfo_Builder_setSnippetRange_0 = get_method_id(env, _cls_MatchInfo_Builder, b"setSnippetRange", b"(Landroid/app/appsearch/SearchResult$MatchRange;)Landroid/app/appsearch/SearchResult$MatchInfo$Builder;")
    _m_MatchInfo_Builder_setSubmatchRange_0 = get_method_id(env, _cls_MatchInfo_Builder, b"setSubmatchRange", b"(Landroid/app/appsearch/SearchResult$MatchRange;)Landroid/app/appsearch/SearchResult$MatchInfo$Builder;")
    _m_MatchInfo_Builder_setExactMatchRange_0 = get_method_id(env, _cls_MatchInfo_Builder, b"setExactMatchRange", b"(Landroid/app/appsearch/SearchResult$MatchRange;)Landroid/app/appsearch/SearchResult$MatchInfo$Builder;")
    return 0

cdef class MatchInfo_Builder(JavaObject):
    """android.app.appsearch.SearchResult$MatchInfo$Builder"""

    def __init__(self, p0):
        cdef JNIEnv* env = get_env()
        _ensure_ids_MatchInfo_Builder(env)
        cdef jvalue _args[1]
        cdef jstring _arg0_s = NULL
        _arg0_s = j_str(env, p0) if p0 is not None else <jstring>NULL
        _args[0].l = <jobject>_arg0_s
        cdef jobject _ret = jnicore_NewObjectA(env, _cls_MatchInfo_Builder, _ctor_MatchInfo_Builder_0, _args)
        if _arg0_s != NULL:
            jnicore_DeleteLocalRef(env, <jobject>_arg0_s)
        check_jni_exc(env)
        self._adopt_local(env, _ret)

    cdef jobject _build(self, JNIEnv* env) except? NULL:
        _ensure_ids_MatchInfo_Builder(env)
        cdef jvalue _args[1]  # zero-arg call; _args ignored by JNI
        cdef jobject _ret = jnicore_CallObjectMethodA(env, self._handle, _m_MatchInfo_Builder_build_0, _args)
        check_jni_exc(env)
        return _ret

    def build(self) -> object:
        cdef JNIEnv* env = get_env()
        cdef jobject _ret = NULL
        _ret = self._build(env)
        if _ret == NULL:
            return None
        cdef JavaObject _wrapped = JavaObject.__new__(JavaObject)
        _wrapped._adopt_local(env, _ret)
        return _wrapped

    cdef jobject _build_0(self, JNIEnv* env) except? NULL:
        _ensure_ids_MatchInfo_Builder(env)
        cdef jvalue _args[1]  # zero-arg call; _args ignored by JNI
        cdef jobject _ret = jnicore_CallObjectMethodA(env, self._handle, _m_MatchInfo_Builder_build_0, _args)
        check_jni_exc(env)
        return _ret

    def build_0(self) -> object:
        cdef JNIEnv* env = get_env()
        cdef jobject _ret = NULL
        _ret = self._build_0(env)
        if _ret == NULL:
            return None
        cdef JavaObject _wrapped = JavaObject.__new__(JavaObject)
        _wrapped._adopt_local(env, _ret)
        return _wrapped

    cdef jobject _setSnippetRange(self, JNIEnv* env, jobject p0) except? NULL:
        _ensure_ids_MatchInfo_Builder(env)
        cdef jvalue _args[1]
        _args[0].l = p0
        cdef jobject _ret = jnicore_CallObjectMethodA(env, self._handle, _m_MatchInfo_Builder_setSnippetRange_0, _args)
        check_jni_exc(env)
        return _ret

    def setSnippetRange(self, p0) -> object:
        cdef JNIEnv* env = get_env()
        cdef jobject _ret = NULL
        cdef jobject _h0 = (<JavaObject?>p0)._handle if p0 is not None else <jobject>NULL
        _ret = self._setSnippetRange(env, _h0)
        if _ret == NULL:
            return None
        cdef JavaObject _wrapped = JavaObject.__new__(JavaObject)
        _wrapped._adopt_local(env, _ret)
        return _wrapped

    cdef jobject _setSnippetRange_0(self, JNIEnv* env, jobject p0) except? NULL:
        _ensure_ids_MatchInfo_Builder(env)
        cdef jvalue _args[1]
        _args[0].l = p0
        cdef jobject _ret = jnicore_CallObjectMethodA(env, self._handle, _m_MatchInfo_Builder_setSnippetRange_0, _args)
        check_jni_exc(env)
        return _ret

    def setSnippetRange_0(self, p0) -> object:
        cdef JNIEnv* env = get_env()
        cdef jobject _ret = NULL
        cdef jobject _h0 = (<JavaObject?>p0)._handle if p0 is not None else <jobject>NULL
        _ret = self._setSnippetRange_0(env, _h0)
        if _ret == NULL:
            return None
        cdef JavaObject _wrapped = JavaObject.__new__(JavaObject)
        _wrapped._adopt_local(env, _ret)
        return _wrapped

    cdef jobject _setSubmatchRange(self, JNIEnv* env, jobject p0) except? NULL:
        _ensure_ids_MatchInfo_Builder(env)
        cdef jvalue _args[1]
        _args[0].l = p0
        cdef jobject _ret = jnicore_CallObjectMethodA(env, self._handle, _m_MatchInfo_Builder_setSubmatchRange_0, _args)
        check_jni_exc(env)
        return _ret

    def setSubmatchRange(self, p0) -> object:
        cdef JNIEnv* env = get_env()
        cdef jobject _ret = NULL
        cdef jobject _h0 = (<JavaObject?>p0)._handle if p0 is not None else <jobject>NULL
        _ret = self._setSubmatchRange(env, _h0)
        if _ret == NULL:
            return None
        cdef JavaObject _wrapped = JavaObject.__new__(JavaObject)
        _wrapped._adopt_local(env, _ret)
        return _wrapped

    cdef jobject _setSubmatchRange_0(self, JNIEnv* env, jobject p0) except? NULL:
        _ensure_ids_MatchInfo_Builder(env)
        cdef jvalue _args[1]
        _args[0].l = p0
        cdef jobject _ret = jnicore_CallObjectMethodA(env, self._handle, _m_MatchInfo_Builder_setSubmatchRange_0, _args)
        check_jni_exc(env)
        return _ret

    def setSubmatchRange_0(self, p0) -> object:
        cdef JNIEnv* env = get_env()
        cdef jobject _ret = NULL
        cdef jobject _h0 = (<JavaObject?>p0)._handle if p0 is not None else <jobject>NULL
        _ret = self._setSubmatchRange_0(env, _h0)
        if _ret == NULL:
            return None
        cdef JavaObject _wrapped = JavaObject.__new__(JavaObject)
        _wrapped._adopt_local(env, _ret)
        return _wrapped

    cdef jobject _setExactMatchRange(self, JNIEnv* env, jobject p0) except? NULL:
        _ensure_ids_MatchInfo_Builder(env)
        cdef jvalue _args[1]
        _args[0].l = p0
        cdef jobject _ret = jnicore_CallObjectMethodA(env, self._handle, _m_MatchInfo_Builder_setExactMatchRange_0, _args)
        check_jni_exc(env)
        return _ret

    def setExactMatchRange(self, p0) -> object:
        cdef JNIEnv* env = get_env()
        cdef jobject _ret = NULL
        cdef jobject _h0 = (<JavaObject?>p0)._handle if p0 is not None else <jobject>NULL
        _ret = self._setExactMatchRange(env, _h0)
        if _ret == NULL:
            return None
        cdef JavaObject _wrapped = JavaObject.__new__(JavaObject)
        _wrapped._adopt_local(env, _ret)
        return _wrapped

    cdef jobject _setExactMatchRange_0(self, JNIEnv* env, jobject p0) except? NULL:
        _ensure_ids_MatchInfo_Builder(env)
        cdef jvalue _args[1]
        _args[0].l = p0
        cdef jobject _ret = jnicore_CallObjectMethodA(env, self._handle, _m_MatchInfo_Builder_setExactMatchRange_0, _args)
        check_jni_exc(env)
        return _ret

    def setExactMatchRange_0(self, p0) -> object:
        cdef JNIEnv* env = get_env()
        cdef jobject _ret = NULL
        cdef jobject _h0 = (<JavaObject?>p0)._handle if p0 is not None else <jobject>NULL
        _ret = self._setExactMatchRange_0(env, _h0)
        if _ret == NULL:
            return None
        cdef JavaObject _wrapped = JavaObject.__new__(JavaObject)
        _wrapped._adopt_local(env, _ret)
        return _wrapped

    @staticmethod
    def from_java_object(obj) -> object:
        """Wrap a plain JavaObject as MatchInfo_Builder (no JNI type check)."""
        cdef JNIEnv* env = get_env()
        cdef MatchInfo_Builder inst = MatchInfo_Builder.__new__(MatchInfo_Builder)
        cdef jobject global_ref = jnicore_NewGlobalRef(env, (<JavaObject?>obj)._handle)
        inst._adopt_global(env, global_ref)
        return inst

# Nested class: android.app.appsearch.SearchResult$Builder  (JNI: android/app/appsearch/SearchResult$Builder)
cdef jclass _cls_Builder = NULL
cdef jmethodID _ctor_Builder_0 = NULL
cdef jmethodID _m_Builder_addJoinedResult_0 = NULL
cdef jmethodID _m_Builder_addMatchInfo_0 = NULL
cdef jmethodID _m_Builder_setParentTypeMap_0 = NULL
cdef jmethodID _m_Builder_setRankingSignal_0 = NULL
cdef jmethodID _m_Builder_addInformationalRankingSignal_0 = NULL
cdef jmethodID _m_Builder_setGenericDocument_0 = NULL
cdef jmethodID _m_Builder_build_0 = NULL

cdef int _ensure_ids_Builder(JNIEnv* env) except -1:
    global _cls_Builder, _ctor_Builder_0, _m_Builder_addJoinedResult_0, _m_Builder_addMatchInfo_0, _m_Builder_setParentTypeMap_0, _m_Builder_setRankingSignal_0, _m_Builder_addInformationalRankingSignal_0, _m_Builder_setGenericDocument_0, _m_Builder_build_0
    if _cls_Builder != NULL:
        return 0
    _cls_Builder = find_class_global(env, b"android/app/appsearch/SearchResult$Builder")
    _ctor_Builder_0 = get_method_id(env, _cls_Builder, b"<init>", b"(Ljava/lang/String;Ljava/lang/String;)V")
    _m_Builder_addJoinedResult_0 = get_method_id(env, _cls_Builder, b"addJoinedResult", b"(Landroid/app/appsearch/SearchResult;)Landroid/app/appsearch/SearchResult$Builder;")
    _m_Builder_addMatchInfo_0 = get_method_id(env, _cls_Builder, b"addMatchInfo", b"(Landroid/app/appsearch/SearchResult$MatchInfo;)Landroid/app/appsearch/SearchResult$Builder;")
    _m_Builder_setParentTypeMap_0 = get_method_id(env, _cls_Builder, b"setParentTypeMap", b"(Ljava/util/Map;)Landroid/app/appsearch/SearchResult$Builder;")
    _m_Builder_setRankingSignal_0 = get_method_id(env, _cls_Builder, b"setRankingSignal", b"(D)Landroid/app/appsearch/SearchResult$Builder;")
    _m_Builder_addInformationalRankingSignal_0 = get_method_id(env, _cls_Builder, b"addInformationalRankingSignal", b"(D)Landroid/app/appsearch/SearchResult$Builder;")
    _m_Builder_setGenericDocument_0 = get_method_id(env, _cls_Builder, b"setGenericDocument", b"(Landroid/app/appsearch/GenericDocument;)Landroid/app/appsearch/SearchResult$Builder;")
    _m_Builder_build_0 = get_method_id(env, _cls_Builder, b"build", b"()Landroid/app/appsearch/SearchResult;")
    return 0

cdef class Builder(JavaObject):
    """android.app.appsearch.SearchResult$Builder"""

    def __init__(self, p0, p1):
        cdef JNIEnv* env = get_env()
        _ensure_ids_Builder(env)
        cdef jvalue _args[2]
        cdef jstring _arg0_s = NULL
        cdef jstring _arg1_s = NULL
        _arg0_s = j_str(env, p0) if p0 is not None else <jstring>NULL
        _args[0].l = <jobject>_arg0_s
        _arg1_s = j_str(env, p1) if p1 is not None else <jstring>NULL
        _args[1].l = <jobject>_arg1_s
        cdef jobject _ret = jnicore_NewObjectA(env, _cls_Builder, _ctor_Builder_0, _args)
        if _arg0_s != NULL:
            jnicore_DeleteLocalRef(env, <jobject>_arg0_s)
        if _arg1_s != NULL:
            jnicore_DeleteLocalRef(env, <jobject>_arg1_s)
        check_jni_exc(env)
        self._adopt_local(env, _ret)

    cdef jobject _addJoinedResult(self, JNIEnv* env, jobject p0) except? NULL:
        _ensure_ids_Builder(env)
        cdef jvalue _args[1]
        _args[0].l = p0
        cdef jobject _ret = jnicore_CallObjectMethodA(env, self._handle, _m_Builder_addJoinedResult_0, _args)
        check_jni_exc(env)
        return _ret

    def addJoinedResult(self, p0) -> object:
        cdef JNIEnv* env = get_env()
        cdef jobject _ret = NULL
        cdef jobject _h0 = (<JavaObject?>p0)._handle if p0 is not None else <jobject>NULL
        _ret = self._addJoinedResult(env, _h0)
        if _ret == NULL:
            return None
        cdef Builder _wrapped = Builder.__new__(Builder)
        _wrapped._adopt_local(env, _ret)
        return _wrapped

    cdef jobject _addJoinedResult_0(self, JNIEnv* env, jobject p0) except? NULL:
        _ensure_ids_Builder(env)
        cdef jvalue _args[1]
        _args[0].l = p0
        cdef jobject _ret = jnicore_CallObjectMethodA(env, self._handle, _m_Builder_addJoinedResult_0, _args)
        check_jni_exc(env)
        return _ret

    def addJoinedResult_0(self, p0) -> object:
        cdef JNIEnv* env = get_env()
        cdef jobject _ret = NULL
        cdef jobject _h0 = (<JavaObject?>p0)._handle if p0 is not None else <jobject>NULL
        _ret = self._addJoinedResult_0(env, _h0)
        if _ret == NULL:
            return None
        cdef Builder _wrapped = Builder.__new__(Builder)
        _wrapped._adopt_local(env, _ret)
        return _wrapped

    cdef jobject _addMatchInfo(self, JNIEnv* env, jobject p0) except? NULL:
        _ensure_ids_Builder(env)
        cdef jvalue _args[1]
        _args[0].l = p0
        cdef jobject _ret = jnicore_CallObjectMethodA(env, self._handle, _m_Builder_addMatchInfo_0, _args)
        check_jni_exc(env)
        return _ret

    def addMatchInfo(self, p0) -> object:
        cdef JNIEnv* env = get_env()
        cdef jobject _ret = NULL
        cdef jobject _h0 = (<JavaObject?>p0)._handle if p0 is not None else <jobject>NULL
        _ret = self._addMatchInfo(env, _h0)
        if _ret == NULL:
            return None
        cdef Builder _wrapped = Builder.__new__(Builder)
        _wrapped._adopt_local(env, _ret)
        return _wrapped

    cdef jobject _addMatchInfo_0(self, JNIEnv* env, jobject p0) except? NULL:
        _ensure_ids_Builder(env)
        cdef jvalue _args[1]
        _args[0].l = p0
        cdef jobject _ret = jnicore_CallObjectMethodA(env, self._handle, _m_Builder_addMatchInfo_0, _args)
        check_jni_exc(env)
        return _ret

    def addMatchInfo_0(self, p0) -> object:
        cdef JNIEnv* env = get_env()
        cdef jobject _ret = NULL
        cdef jobject _h0 = (<JavaObject?>p0)._handle if p0 is not None else <jobject>NULL
        _ret = self._addMatchInfo_0(env, _h0)
        if _ret == NULL:
            return None
        cdef Builder _wrapped = Builder.__new__(Builder)
        _wrapped._adopt_local(env, _ret)
        return _wrapped

    cdef jobject _setParentTypeMap(self, JNIEnv* env, jobject p0) except? NULL:
        _ensure_ids_Builder(env)
        cdef jvalue _args[1]
        _args[0].l = p0
        cdef jobject _ret = jnicore_CallObjectMethodA(env, self._handle, _m_Builder_setParentTypeMap_0, _args)
        check_jni_exc(env)
        return _ret

    def setParentTypeMap(self, p0) -> object:
        cdef JNIEnv* env = get_env()
        cdef jobject _ret = NULL
        cdef jobject _h0 = (<JavaObject?>p0)._handle if p0 is not None else <jobject>NULL
        _ret = self._setParentTypeMap(env, _h0)
        if _ret == NULL:
            return None
        cdef Builder _wrapped = Builder.__new__(Builder)
        _wrapped._adopt_local(env, _ret)
        return _wrapped

    cdef jobject _setParentTypeMap_0(self, JNIEnv* env, jobject p0) except? NULL:
        _ensure_ids_Builder(env)
        cdef jvalue _args[1]
        _args[0].l = p0
        cdef jobject _ret = jnicore_CallObjectMethodA(env, self._handle, _m_Builder_setParentTypeMap_0, _args)
        check_jni_exc(env)
        return _ret

    def setParentTypeMap_0(self, p0) -> object:
        cdef JNIEnv* env = get_env()
        cdef jobject _ret = NULL
        cdef jobject _h0 = (<JavaObject?>p0)._handle if p0 is not None else <jobject>NULL
        _ret = self._setParentTypeMap_0(env, _h0)
        if _ret == NULL:
            return None
        cdef Builder _wrapped = Builder.__new__(Builder)
        _wrapped._adopt_local(env, _ret)
        return _wrapped

    cdef jobject _setRankingSignal(self, JNIEnv* env, jdouble p0) except? NULL:
        _ensure_ids_Builder(env)
        cdef jvalue _args[1]
        _args[0].d = p0
        cdef jobject _ret = jnicore_CallObjectMethodA(env, self._handle, _m_Builder_setRankingSignal_0, _args)
        check_jni_exc(env)
        return _ret

    def setRankingSignal(self, p0) -> object:
        cdef JNIEnv* env = get_env()
        cdef jobject _ret = NULL
        cdef jdouble _c0 = py_to_jdouble(p0)
        _ret = self._setRankingSignal(env, _c0)
        if _ret == NULL:
            return None
        cdef Builder _wrapped = Builder.__new__(Builder)
        _wrapped._adopt_local(env, _ret)
        return _wrapped

    cdef jobject _setRankingSignal_0(self, JNIEnv* env, jdouble p0) except? NULL:
        _ensure_ids_Builder(env)
        cdef jvalue _args[1]
        _args[0].d = p0
        cdef jobject _ret = jnicore_CallObjectMethodA(env, self._handle, _m_Builder_setRankingSignal_0, _args)
        check_jni_exc(env)
        return _ret

    def setRankingSignal_0(self, p0) -> object:
        cdef JNIEnv* env = get_env()
        cdef jobject _ret = NULL
        cdef jdouble _c0 = py_to_jdouble(p0)
        _ret = self._setRankingSignal_0(env, _c0)
        if _ret == NULL:
            return None
        cdef Builder _wrapped = Builder.__new__(Builder)
        _wrapped._adopt_local(env, _ret)
        return _wrapped

    cdef jobject _addInformationalRankingSignal(self, JNIEnv* env, jdouble p0) except? NULL:
        _ensure_ids_Builder(env)
        cdef jvalue _args[1]
        _args[0].d = p0
        cdef jobject _ret = jnicore_CallObjectMethodA(env, self._handle, _m_Builder_addInformationalRankingSignal_0, _args)
        check_jni_exc(env)
        return _ret

    def addInformationalRankingSignal(self, p0) -> object:
        cdef JNIEnv* env = get_env()
        cdef jobject _ret = NULL
        cdef jdouble _c0 = py_to_jdouble(p0)
        _ret = self._addInformationalRankingSignal(env, _c0)
        if _ret == NULL:
            return None
        cdef Builder _wrapped = Builder.__new__(Builder)
        _wrapped._adopt_local(env, _ret)
        return _wrapped

    cdef jobject _addInformationalRankingSignal_0(self, JNIEnv* env, jdouble p0) except? NULL:
        _ensure_ids_Builder(env)
        cdef jvalue _args[1]
        _args[0].d = p0
        cdef jobject _ret = jnicore_CallObjectMethodA(env, self._handle, _m_Builder_addInformationalRankingSignal_0, _args)
        check_jni_exc(env)
        return _ret

    def addInformationalRankingSignal_0(self, p0) -> object:
        cdef JNIEnv* env = get_env()
        cdef jobject _ret = NULL
        cdef jdouble _c0 = py_to_jdouble(p0)
        _ret = self._addInformationalRankingSignal_0(env, _c0)
        if _ret == NULL:
            return None
        cdef Builder _wrapped = Builder.__new__(Builder)
        _wrapped._adopt_local(env, _ret)
        return _wrapped

    cdef jobject _setGenericDocument(self, JNIEnv* env, jobject p0) except? NULL:
        _ensure_ids_Builder(env)
        cdef jvalue _args[1]
        _args[0].l = p0
        cdef jobject _ret = jnicore_CallObjectMethodA(env, self._handle, _m_Builder_setGenericDocument_0, _args)
        check_jni_exc(env)
        return _ret

    def setGenericDocument(self, p0) -> object:
        cdef JNIEnv* env = get_env()
        cdef jobject _ret = NULL
        cdef jobject _h0 = (<JavaObject?>p0)._handle if p0 is not None else <jobject>NULL
        _ret = self._setGenericDocument(env, _h0)
        if _ret == NULL:
            return None
        cdef Builder _wrapped = Builder.__new__(Builder)
        _wrapped._adopt_local(env, _ret)
        return _wrapped

    cdef jobject _setGenericDocument_0(self, JNIEnv* env, jobject p0) except? NULL:
        _ensure_ids_Builder(env)
        cdef jvalue _args[1]
        _args[0].l = p0
        cdef jobject _ret = jnicore_CallObjectMethodA(env, self._handle, _m_Builder_setGenericDocument_0, _args)
        check_jni_exc(env)
        return _ret

    def setGenericDocument_0(self, p0) -> object:
        cdef JNIEnv* env = get_env()
        cdef jobject _ret = NULL
        cdef jobject _h0 = (<JavaObject?>p0)._handle if p0 is not None else <jobject>NULL
        _ret = self._setGenericDocument_0(env, _h0)
        if _ret == NULL:
            return None
        cdef Builder _wrapped = Builder.__new__(Builder)
        _wrapped._adopt_local(env, _ret)
        return _wrapped

    cdef jobject _build(self, JNIEnv* env) except? NULL:
        _ensure_ids_Builder(env)
        cdef jvalue _args[1]  # zero-arg call; _args ignored by JNI
        cdef jobject _ret = jnicore_CallObjectMethodA(env, self._handle, _m_Builder_build_0, _args)
        check_jni_exc(env)
        return _ret

    def build(self) -> object:
        cdef JNIEnv* env = get_env()
        cdef jobject _ret = NULL
        _ret = self._build(env)
        if _ret == NULL:
            return None
        cdef JavaObject _wrapped = JavaObject.__new__(JavaObject)
        _wrapped._adopt_local(env, _ret)
        return _wrapped

    cdef jobject _build_0(self, JNIEnv* env) except? NULL:
        _ensure_ids_Builder(env)
        cdef jvalue _args[1]  # zero-arg call; _args ignored by JNI
        cdef jobject _ret = jnicore_CallObjectMethodA(env, self._handle, _m_Builder_build_0, _args)
        check_jni_exc(env)
        return _ret

    def build_0(self) -> object:
        cdef JNIEnv* env = get_env()
        cdef jobject _ret = NULL
        _ret = self._build_0(env)
        if _ret == NULL:
            return None
        cdef JavaObject _wrapped = JavaObject.__new__(JavaObject)
        _wrapped._adopt_local(env, _ret)
        return _wrapped

    @staticmethod
    def from_java_object(obj) -> object:
        """Wrap a plain JavaObject as Builder (no JNI type check)."""
        cdef JNIEnv* env = get_env()
        cdef Builder inst = Builder.__new__(Builder)
        cdef jobject global_ref = jnicore_NewGlobalRef(env, (<JavaObject?>obj)._handle)
        inst._adopt_global(env, global_ref)
        return inst

