from typing import Any, ClassVar, overload
from android.os.Parcel import Parcel

class ReportUsageRequest:
    CREATOR: ClassVar[Any]
    CONTENTS_FILE_DESCRIPTOR: ClassVar[int]
    PARCELABLE_WRITE_RETURN_VALUE: ClassVar[int]
    def getDocumentId(self) -> str: ...
    def getNamespace(self) -> str: ...
    def writeToParcel(self, p0: Parcel, p1: int) -> None: ...
    def describeContents(self) -> int: ...
    def getUsageTimestampMillis(self) -> int: ...

    class Builder:
        def __init__(self, p0: str, p1: str) -> None: ...
        def setUsageTimestampMillis(self, p0: int) -> Any: ...
        def build(self) -> "ReportUsageRequest": ...
